### ISSUE TITLE
[Unity - S3] Memory footprint of GetObjectAsync on iOS

### ISSUE THREAD

**Issue by olafolafsson** [aws/aws-sdk-net#1005]
## Expected Behavior
Calling GetObjectAsync to download several files should release memory when downloads are over, which would make it usable on iPhones and iPad with 512 MB of RAM.

## Current Behavior

On iOS, successively downloading several quite large files (~10-30 MB) results in a memory overhead nearing 100 MB which cannot be released completely even by forcing garbage collection. On iOS devices with 512 MB of RAM, this may result in the app being killed by the OS if the RAM consumption of the app reaches ~ 250 MB.

## Steps to Reproduce (for bugs)

The tested code is a slightly modified version of the sample S3 code shipping with the AWS Unity package. It does nothing with the downloaded files and only tells the user when a download is over. 

```
void Start()
{
    UnityInitializer.AttachToGameObject(this.gameObject);
    AWSConfigs.HttpClient = AWSConfigs.HttpClientOption.UnityWebRequest;
    this.isDownloading = false;
}

private void GetObject(string objectName)
{
    if (this.isDownloading) return;
    this.isDownloading = true;

    ResultText.text = string.Format("fetching {0} from bucket {1}", objectName, S3BucketName);

    Client.GetObjectAsync(S3BucketName, objectName, (responseObj) =>
    {
        Debug.LogFormat("Object {0} downloaded", objectName);
        ResultText.text += "\n";
        ResultText.text += string.Format("Object {0} downloaded", objectName); 
        this.isDownloading = false;
    });
}
```

The test consists in downloading several files from a bucket, with the following sizes:

- test.bin: 172 B
- test1.bin: 14,2 KB
- test2.bin: 12,2 MB
- test3.bin: 11.1 MB
- test4.bin: 32,9 MB

Memory consumption is measured using Xcode's debug navigator, with the compiled app running on an iPhone 6s (iOS 10.3). By downloading each file one after the other, here is how the total memory usage evolves

- Start : 45 MB
- After test.bin : 51 MB
- After test1.bin : 52 MB
- After test2.bin : 77,4 MB
- After test3.bin : 76,7 MB
- After test4.bin : 131 MB

So the overhead of downloading those files is 86 MB. At this stage, calling GC.Collect() does not release any memory. _Spamming_ GC.Collect() (just for testing purposes of course) does release around 20 MB. 

On older iOS devices, this overhead makes GetObjectAsync quite unusable - especially with a real app that already occupies around 100 MB before starting the first download.

Notice that the overhead continues increasing with subsequent downloads of the test files (test2.bin -> test3.bin -> test4.bin -> test2.bin -> ...) and the memory usage stabilizes around 180 MB after the download.

## Context
In the app we developp, the user may want to download several DLCs quickly after buying them or restoring purchases. On older iOS devices, this is likely to cause the app to be killed by the OS

## Your Environment

- Unity 2017.4.7, with .NET 4.6 (but the issue also appear with .NET 3.5)
- Xcode 9.4.1
- Several iOS devices : iPhone 6s (iOS 10.3), iPad Air (iOS 10.4), iPad 2 (iOS 9.3.5)
- aws-sdk-unity_3.3.311.0
- The app is compiled using Unity and Xcode's default options (Release, not a development build, BuildForRunning)

**Comment by haydenjameslee** [comment]
We're experiencing a very similar issue. Did you manage to learn any new info or find a workaround @olafolafsson?
