### ISSUE TITLE
Issue with AWSSDK.core and AWSSDK.EC2 nuget packages

### ISSUE THREAD

**Issue by rohanath** [aws/aws-sdk-net#1006]
Hello,

I am trying to call the AWS SDK's for spinning up an EC2 instance. When I try and run the code, it gives an error that says :

could not load file or assembly 'awssdk.core' or one of its dependencies

I read a post somewhere that says that we should use 3.2.X versions of nuget packages for such scenarios but even that does not seem to be working.

Is there any other solution to this?

Thanks,
Rohan

**Comment by normj** [comment]
How are you referencing the SDK. If you are using NuGet when you add the AWSSDK.EC2 NuGet package it will pull in the the dependent AWSSDK.Core NuGet package. If you are adding dll references, possibly getting the dlls from our installer, then you need to add to your project both the AWSSDK.EC2.dll and the AWSSDK.Core.dll.

**Comment by rohanath** [comment]
I am adding the NuGet package for AWSSDK.EC2 and it adds the AWSSDK.Core as you said. But when I run my code, it gives the above error message. To be precise, the error is like this :   

Could not load file or assembly 'AWSSDK, Version=1.5.19.0, Culture=neutral, PublicKeyToken=9f476d3089b52be3' or one of its dependencies. The system cannot find the file specified.

**Comment by rohanath** [comment]
I have one question for you. I am using this to create a console .NET application. When I add AWSSDK.EC2, should there be an entry for it in the .conf file after I do the build for my application. I am wondering about this because from the error it clearly looks like it is not able to find the files which is wierd to me. And I tried your suggestion and installed a newer version, it does not work.

**Comment by normj** [comment]
Not sure what you mean by **.conf**. Is this a .NET Framework or .NET Core console application. Any chance you could post the contents of your **csproj** file?

**Comment by rohanath** [comment]
I got the issue. The problem was with my code and the way .NET loads the reference assemblies. It was not an AWSSDK issue. Thanks for all your help.

**Comment by normj** [comment]
Great, glad you were able to fix your issue.
