### ISSUE TITLE
Typo on the suffix tooltip in "Add Event Configuration" dialog in AWS Tookit for VS2017

### ISSUE THREAD

**Issue by CrosseyeJack** [aws/aws-sdk-net#1007]
## Expected Behavior

Should read "Filter events for S3 object ending with this suffix."

## Current Behavior

OK Dunno if this is even the right place to report this issue, couldn't find a repo for the toolkit directly. If there is a better place to report this please direct me there :-)

I often get Prefix and Suffix mixed up in my head (Say one when I mean the other...), So a suffix is "a morpheme added at the end of a word to form a derivative" right? Well the tooltip in the toolkit reads "Filter events for S3 object starting with this suffix." where a suffix is the end of the filename right? Am I going crazy? Not had enough coffee yet... Anyways It threw me off enough to seek out where to report a bug, so reporting it. If is this as intended nd my brain has yet to kick in feel free to point me in the direction of more coffee and close this.

## Possible Solution

Rename the tooltip.

## Steps to Reproduce (for bugs)

Right click a S3 bucket in the tookit -> Properties -> Notifications -> Add -> Hover over suffix
![suffix](https://user-images.githubusercontent.com/1392296/42862696-90503ff4-8a58-11e8-9698-f5cf17b58bab.png)

Tookit Version | 1.14.4.0

**Comment by normj** [comment]
Sorry to confuse your brain. I have made the fix to go out with the next version. Now go get some coffee 😄
