### ISSUE TITLE
Small percentage of presigned S3 urls return 403 - SignatureDoesNotMatch

### ISSUE THREAD

**Issue by SapientGuardian** [aws/aws-sdk-net#1019]
## Expected Behavior
Embedded signature in presigned S3 urls should match S3 expectation

## Current Behavior
A small percentage of presigned S3 urls generated return a `403 - SignatureDoesNotMatch` when accessed.

## Steps to Reproduce (for bugs)
```
var westCredentials = ... // AssumeRole credentials, based on IAM role applied to ECS task
var eastCredentials = ... // AssumeRole credentials, based on IAM role applied to ECS task

var clientWest = new AmazonS3Client(westCredentials, Amazon.RegionEndpoint.GetBySystemName("us-west-2"));
var clientEast = new AmazonS3Client(eastCredentials, Amazon.RegionEndpoint.GetBySystemName("us-east-1"));

var urls = new List<String>();
var getPreSignedUrlRequestWest = new GetPreSignedUrlRequest
                        {
                            BucketName = "myfiles-usw2-prod-mybucket",
                            Key = "mypath/myfile.jpg",
                            Verb = HttpVerb.GET,
                            Protocol = Protocol.HTTPS,
                            Expires = DateTime.UtcNow.AddDays(1)
                        };
                        urls.Add(clientWest.GetPreSignedURL(getPreSignedUrlRequestWest));
var getPreSignedUrlRequestEast = new GetPreSignedUrlRequest
                        {
                            BucketName = "myfiles-use1-prod-mybucket",
                            Key = "mypath/myfile.jpg",
                            Verb = HttpVerb.GET,
                            Protocol = Protocol.HTTPS,
                            Expires = DateTime.UtcNow.AddDays(1)
                        };
                        urls.Add(clientEast.GetPreSignedURL(getPreSignedUrlRequestEast));

```

## Context
I have a web service which acts as a proxy to various storage systems including S3. Based on the incoming user request, the service will generate presigned urls to a file which may exist in a bucket in us-west-2, us-east-1, or on-prem storage. After assembling a list of possible storage locations, the service will try the URLs in order of preference until it finds one that works, and stream the data back to the user.

This is a high traffic service, handling roughly 60 requests per second per instance. The vast majority of generated S3 urls work just fine, but every few minutes, a pair of s3 urls generated by any given instance will fail with `403 - SignatureDoesNotMatch` when accessed. What's particularly interesting is that _both_ s3 urls for the object (the us-east and us-west buckets) have this problem, but if I re-run the request, causing new urls to be generated with the same input parameters, both urls will succeed. I haven't been able to find any correlation with time, interval, or instances - it seems entirely random. Given that both urls fail, it makes me think that it's related to the time that they are generated or perhaps there's a thread safety issue (multiple threads call GetPreSignedURL on a shared set of S3 clients).

The S3 buckets exist in accounts separate from where the service runs. In order to generate urls for them, the app uses its IAM role to call STS and AssumeRole into the appropriate role for the region of the bucket. Thus, there is a separate S3 client used when generating the West url vs the East URL. The parameters passed in the GetPreSignedUrlRequest are the same for both, with the exception of the bucket name. Each S3 client has its own set of credentials from STS, but they share a root set of credentials provided by ECS.

The application does not send any special headers to S3 or modify the generated URL in any way, it takes the URL as given and does a straight GET request with the standard .NET HttpClient.

## Your Environment
* AWSSDK.Core version used: 3.3.24.1
* AWSSDK.S3 version used: 3.3.18.4
* AWSSDK.SecurityToken version used: 3.3.4.5
* Operating System and version: Amazon ECS Optimized AMI, hosting Debian-based containers
* Visual Studio version: 2017 Professional
* Targeted .NET platform: .NET Core 2.1

## .NET Core Info
* .NET Core version used for development: 2.1
* .NET Core version installed in the environment where application runs: 2.1

**Comment by sstevenkang** [comment]
Could you provide the `dotnet --info` result?

**Comment by SapientGuardian** [comment]
root@c9bdbfbdfba5:/app# dotnet --info

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by sstevenkang** [comment]
One more thing, is there any way you could capture the request ids when SignatureDoesNotMatch exception is thrown?  I suspect that this is a service side issue & I would like to have S3 team take a look while we try to create a consistent repro.

**Comment by SapientGuardian** [comment]
I took a pair of failed URLs from a few minutes ago and put them in my browser (where they also fail) to get request ids. Let me know if it's important for me to get the IDs from when the service itself makes those calls, and I can add some logging to capture that.

US-West-2 request id: EC652E55A5F9D887
US-East-1 request id: 614E7DCD0866ADFE

If it helps at all, particularly if this turns out to be a service issue rather than an SDK issue, my organization has AWS Enterprise Support and I can log a ticket there.

**Comment by sstevenkang** [comment]
My suspicion is that this is a service issue--especially if it is intermittent.  I would definitely provide enterprise support with the request IDs.  Feel free to provide this github issue link as well for context.
