### ISSUE TITLE
Question: Will CompleteMultipartUploadAsync wait for completion?

### ISSUE THREAD

**Issue by LordMike** [aws/aws-sdk-net#1020]
Question: We have a case where we're uploading multiple files to S3. On upload of the last one, we fire off an event which will process all our files in one go - however, with Multipart uploads, the S3 docs say:

```
rocessing of a Complete Multipart Upload request could take several minutes to complete. 
After Amazon S3 begins processing the request, it sends an HTTP response header that 
specifies a 200 OK response. While processing is in progress, Amazon S3 periodically sends 
whitespace characters to keep the connection from timing out. Because a request could 
fail after the initial 200 OK response has been sent, it is important that you check the response 
body to determine whether the request succeeded.
```

So in short. Will the AWS S3 SDK return only upon the successfull combination of uploads, or will it return as soon as this header has been received and not wait for upload completion ?

Note: Of course we "await" the `CompleteMultipartUploadAsync` call.

## Expected Behavior
S3 SDK waits for completed upload

## Current Behavior
Unsure how to test, verify or more. This would be a timing issue.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
N/A

## Context
We're uploading a series of files and need to process them together. Ensuring that a file is uploaded before we proceed is a must.

## Your Environment

* AWSSDK.Core version used: 3.3.24.4
* Service assembly and version used: S3, 3.3.20
* Operating System and version: Win 10
* Visual Studio version: VS 2017
* Targeted .NET platform: .NET Core, 2.0

## .NET Core Info

* .NET Core version used for development: N/A
* .NET Core version installed in the environment where application runs: N/A
* Output of `dotnet --info`: N/A
* Contents of project.json/project.csproj: N/A

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by sstevenkang** [comment]
The SDK always reads in the response body to craft the `CompleteMultipartUploadResponse` object.  Are you seeing a specific behavior where this is not the case?

**Comment by LordMike** [comment]
No observations - purely exploratory. I was worried the AWS SDK would be doing something like HttpClient's "Wait for headers" only, and the optimistically return soon for certain methods where there is no body.

But it seems like the client does what we need, so that's good :)

Thanks.
