### ISSUE TITLE
Unable to subscribe to iot with .net sdk

### ISSUE THREAD

**Issue by Fumi24** [aws/aws-sdk-net#1023]
Hello

Im trying to get a console app to subscribe to my AWS iot without using mqtt libs, but i would like to use the aws sdks but there seems to be no subscribe method?

so i guess my question is
Do i give all devices that has to connect to my iot the same private key and use Mqtt and generate the pem file using the sdk.

Or is there a subscribe method for .net in the works at aws?

**Comment by sstevenkang** [comment]
There's no IoT Device SDKs for .NET.

Is that what you are looking for?

**Comment by Fumi24** [comment]
A way to connect to the Iot while using either amazon certificates for security or though IAM, but if there is no way to use the SDK i will have to use Mqtt libs and distribute my private key among devices, or are there better ways to do this?

my plan is to hook up apps to a mqtt whenever they are first started, and so far mqtt is the only way i have that works.

**Comment by graebm** [comment]
There are [AWS IoT Device SDKs](https://docs.aws.amazon.com/iot/latest/developerguide/iot-sdks.html) available for several languages and platforms. The simplest option would be to use one of the currently supported languages (Python, Javascript, Java, C++, C, etc).

Unfortunately, no IoT Device SDK for .NET is available at this time. We are aware of this hole in our current offerings. You could still use .NET and an MQTT library, as you mention. Specifics on doing so can be found [here](https://docs.aws.amazon.com/iot/latest/developerguide/protocols.html).

Regarding security, take a look at [Understanding the AWS IoT Security Model](https://aws.amazon.com/blogs/iot/understanding-the-aws-iot-security-model/). You are expected to put a private key and certificate on the device, but it should not be the key for your personal AWS account :wink:. AWS IoT helps you issue unique certificates per-device. You are in control of the policy that these certificates operate under, and this lets you limit the actions they can perform, or even revoke priveleges for a individual device if it ever goes rogue.

For more details see the AWS IoT [Developer Guide](https://docs.aws.amazon.com/iot/latest/developerguide/index.html), particularly the following sections:
- [Getting Started with AWS IoT](https://docs.aws.amazon.com/iot/latest/developerguide/iot-gs.html)
- [AWS IoT Device SDKs](https://docs.aws.amazon.com/iot/latest/developerguide/iot-sdks.html)
- [MQTT Protocols](https://docs.aws.amazon.com/iot/latest/developerguide/protocols.html)
- [Security and Identity](https://docs.aws.amazon.com/iot/latest/developerguide/iot-security-identity.html)

**Comment by Fumi24** [comment]
Okay, i will probably continue using MQTT library, Thx for the quick answer even tho it was weekend in some parts of the world 👍
