### ISSUE TITLE
Can't upload file with spaces within file name.

### ISSUE THREAD

**Issue by sergeyk76** [aws/aws-sdk-net#1026]
I try to upload file by using AmazonS3 Client. Everything working properly till i use the spaces with in file 
name or within subDirectoryInBucket path to the uploaded file.

## Expected Behavior

Posibility to upload file objects with spaces within object names or their subdirectory pathes. 
For Example: MyBucket\FolderA\Foledr with spaces\BolderB\File name with spaces.txt

## Current Behavior

I working with local MinioServer or remote Netapp.
Uploading File objects with no spaces within their names completed sucsessfully.
When i try to upload file object with spaces or subdirectory pathes with spaces i receved the following error :

AmazonS3Exception :
"The request signature we calculated does not match the signature you provided. Check your key and signing method."

## Steps to Reproduce (for bugs)

I'm using the following code snippet:

AmazonS3Config config = new AmazonS3Config();
config.ServiceURL = ConfigurationAgent.S3ServiceURL;
config.ForcePathStyle = true;

IAmazonS3 client = new AmazonS3Client(ConfigurationAgent.S3AccessKey,ConfigurationAgent.S3SecretKey,config);                    

config.Validate();

TransferUtility utility = new TransferUtility(client);
TransferUtilityUploadRequest request = new TransferUtilityUploadRequest();

if (subDirectoryInBucket == "" || subDirectoryInBucket == null)
{
	request.BucketName = bucketName; //no subdirectory just bucket name
}
else
{   // subdirectory and bucket name
	request.BucketName = bucketName + @"/" + subDirectoryInBucket;
}
request.Key = fileNameInS3 ; //file name up in S3
request.FilePath = localFilePath; //local file name
request.ContentType = "text/plain";
utility.Upload(request); //commensing the transfer

return true; //indicate that the file was sent

## Your Environment
AWSSDK.Core version used: 3.3.24.6
AWSSDK.S3 version used: 3.3.20.2
Operating System and version: Ubuntu 16.4
Visual Studio Code version: 1.25.1
Targeted .NET Core platform: 2.1

## .NET Core Info
.NET Core version used for development:  2.1.301
.NET Core version installed in the environment where application runs: 2.1.301

Output of `dotnet --info`: 
.NET Core SDK (reflecting any global.json):
 Version:   2.1.301
 Commit:    59524873d6

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.301/

Host (useful for support):
  Version: 2.1.1
  Commit:  6985b9f684

.NET Core SDKs installed:
  1.0.4 [/usr/share/dotnet/sdk]
  2.1.200 [/usr/share/dotnet/sdk]
  2.1.301 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  
  
Contents of project.json/project.csproj: 

<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
	<PackageReference Include="AWSSDK.Core" Version="3.3.24.6" />  
	<PackageReference Include="AWSSDK.S3" Version="3.3.20.2" />  
	<PackageReference Include="Microsoft.Extensions.Configuration" Version="2.1.0" />  
	<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.1.0" />   
	<PackageReference Include="Newtonsoft.Json" Version="11.0.2" />
	<PackageReference Include="NLog.Extensions.Logging" Version="1.0.0-rtm-beta5" />  -->
	<PackageReference Include="NLog" Version="4.5.6" />
	<PackageReference Include="NLog.Extensions.Logging" Version="1.1.0" />
	<PackageReference Include="RestSharp.NetCore" Version="105.2.3" />
	<PackageReference Include="System.Collections" Version="4.3.0" />
	<PackageReference Include="System.Diagnostics.Process" Version="4.3.0" />
	<PackageReference Include="System.IO" Version="4.3.0" />
	<PackageReference Include="System.Net.Ping" Version="4.3.0" />
	<PackageReference Include="System.Net.Requests" Version="4.3.0" />
	<PackageReference Include="System.Runtime.Serialization.Formatters" Version="4.3.0" />
	<PackageReference Include="System.Security.Cryptography.Algorithms" Version="4.3.1" />
	<PackageReference Include="System.ServiceModel.Http" Version="4.5.0" />
	<PackageReference Include="System.ServiceModel.Primitives" Version="4.5.0" />
	<PackageReference Include="System.Text.Encoding" Version="4.3.0" />
	<PackageReference Include="System.Threading" Version="4.3.0" />
	<PackageReference Include="System.Threading.Tasks" Version="4.3.0" />
	<PackageReference Include="System.Threading.Tasks.Parallel" Version="4.3.0" />
	<PackageReference Include="System.Xml.XDocument" Version="4.3.0" />
	<PackageReference Include="System.Xml.XmlDocument" Version="4.3.0" />
	<PackageReference Include="System.Xml.XmlSerializer" Version="4.3.0" />                                       
</ItemGroup>
  
</Project>

**Comment by sstevenkang** [comment]
Please see S3 key & bucket name restrictions:
https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#object-keys
https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html
