### ISSUE TITLE
AWSSDK.Core CNNorthWest1 Error

### ISSUE THREAD

**Issue by johnny123852** [aws/aws-sdk-net#1028]
Hi,
We use Oregon for a long time.
For the China Bussiness, We start to use AWS Ningxia recently.
When We Use .NET AWSSDK.Core in script  choose Region "CNNorthWest1"
using (client = new AmazonS3Client(AWS_Setting.AccessKey, AWS_Setting.SecretKey, Amazon.RegionEndpoint.CNNorthWest1))
We got the error:
找不到欄位: 'Amazon.RegionEndpoint.CNNorthWest1'

SDK Version:3.3.21.6
We update to 3.3.24.6 has the same problem.
How to solve it?

**Comment by normj** [comment]
For the china region you have to create a separate china account and use those credentials. The credentials you use in oregon will not work in the china regions.

**Comment by johnny123852** [comment]
But we choose CNNorth1(Beijing) is OK,
Only use CNNorthWest1 when runtime got the error.
Our China Service is build on Ninxia now...

**Comment by johnny123852** [comment]
BTW,we use .Net Framework 4.5

**Comment by johnny123852** [comment]
We solved this problem with update AWSSDK.S3 to 3.3.20.2!
god damn so much time...

**Comment by klaytaybai** [comment]
Hi @johnny123852 , thank you for reporting this.  We are still trying to look into what may have caused it.  Could you please tell us which version of the S3 solution you were using before 3.3.20.2?
