### ISSUE TITLE
Aws toolkit for Visual Studio serverless template intelligence error

### ISSUE THREAD

**Issue by junjiequ** [aws/aws-sdk-net#1032]
When using resource type "AWS::EC2::VPCEndpoint", the Intelligence in VS prompts use to use <b>"VPCEndpointType"</b>, while in the CloudFormation document, this attribute is <b>"VpcEndpointType"</b>. [AWS CloudFormation Documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpoint.html#cfn-ec2-vpcendpoint-vpcendpointtype)

So when using the "VPCEndpointType" in the serverless template, the CloudFormation stack gives error "VPCEndpointType" is not a valid key for this object. 
```
		"AName":{
			"Type" : "AWS::EC2::VPCEndpoint",
			"Properties" : {
				"VpcId": {"Ref": "AVpc"},
				"RouteTableIds" : [ {"Ref": "ARouteTable"}],
				"ServiceName" : { "Fn::Join": [ "", [ "com.amazonaws.", { "Ref": "AWS::Region" }, ".dynamodb" ] ] },
				"**VPCEndpointType**":"Gateway",
				"PolicyDocument": {
					"Version": "2012-10-17",
					"Statement": [{
						"Action": "*",
						"Effect": "Allow",
						"Resource": "*",
						"Principal": "*"
					}]
				}
			}
		},
```
## Expected Behavior
CloudFormation update success.

## Current Behavior
CloudFormation update failed. Rollback kicks-off.

## Context
Confusion between the documentation and the actual behavior of the VS toolkit. 

## Your Environment
VS 2017 Version 15.7.6
AWS Toolkit for Visual Studio 2017 Version 1.14.4.0

## .NET Core Info
NetCore 2.1

**Comment by awschristou** [comment]
Thank you for posting the discrepancy @junjiequ , we will take a look into this.

**Comment by junjiequ** [comment]
@awschristou You are welcome. 

I found another similar issue here: #1035

**Comment by normj** [comment]
You should see this fixed the next time you restart Visual Studio

**Comment by klaytaybai** [comment]
I confirmed the intelligence warnings are now working as expected.
