### ISSUE TITLE
Kinesis Video Stream PutMedia Api InvalidSignatureException

### ISSUE THREAD

**Issue by lisansojib** [aws/aws-sdk-net#1033]
Hi Everyone, 
I'm trying to call putmedia api of Kinesis Video Stream. I've to sign my request. I've written a helper class to sign my request and then using that to call the api. But I'm getting 403 Forbidden Error.

## Current Behavior
I've created a helper class to sign my PutMediaApi api. Here is the gist link - https://gist.github.com/lisansojib/60895ebb4235e0918e74bc189f79eaee . 
* I added the signature with Authorization header. When I call the api it says - 403 Forbidden and the error message is - "InvalidSignatureException:http://internal.amazon.com/coral/com.amazon.coral.service/". 

* And I add this to my Authorization header "AWS4-HMAC-SHA256 Credential=<access key>/20180814/eu-west-1/kinesisvideo/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amzn-fragment-timecode-type;x-amzn-producer-start-timestamp;x-amzn-stream-name, Signature=8721097bcc77ab2a5b00f9359250fa84ddfa371d750fb24935930596626bc07b"

* The user has full access to Kinesis Video Stream. 

## Your Environment

* AWSSDK.Core version used: 
* AWSSDK KinesisVideoMedia: 
* Operating System and version: Windows 10
* Visual Studio version: 2017
* Targeted .NET platform: 4.7

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by seba-d-work** [comment]
Did you ever find a solution to this?
