### ISSUE TITLE
FilterLogEventsRequest return latest events first

### ISSUE THREAD

**Issue by rbilyi** [aws/aws-sdk-net#1049]
There's no way to make FilterLogEventsRequest return the latest events first. Even with StartTime defined the filter takes only first 50 streams. I want to see the most relevant (latest) events first and if I'm not satisfied I could ask another (older) 50 streams.

## Expected Behavior
`FilterLogEventsRequest` should look through the latest streams bu default or at least as an option

## Current Behavior
`FilterLogEventsRequest` returns 50 oldest streams.

## Context
I'm trying to get latest events since `StartTime` to find exact event has been occurred.

## Your Environment

* AWSSDK.CloudWatchLogs version used: 3.3.5.2
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 2017
* Targeted .NET platform: Core 2.1

## .NET Core Info

* .NET Core version used for development:  2.1
* .NET Core version installed in the environment where application runs:  2.1
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by sstevenkang** [comment]
This looks like a feature request to the service team. I'll pass the request along.
