### ISSUE TITLE
CognitoUser.StartWithSrpAuthAsync failed when CognitoUser has CognitoDevice

### ISSUE THREAD

**Issue by dmitriy-proskurin** [aws/aws-sdk-net#1054]
I try to work with device. I have registered user(in cognito user pool), device(pc, not linked to that user). 
Code
```C#
var currentUser = m_cognitoUserPool.GetUser("my_user_email");
var authRequest = new InitiateSrpAuthRequest {
                    Password = password
                };
currentUser.Device = new CognitoDevice("win_123412341234", new Dictionary<string, string>(),
                    DateTime.Now, DateTime.Now, DateTime.Now, currentUser);
var authResponse = await CurrentUser.StartWithSrpAuthAsync(authRequest);
```

## Expected Behavior
No exceptions

## Current Behavior
And after call StartWithSrpAuthAsync i got exception: "System.ArgumentException  An item with the same key has already been added. Key: DEVICE_KEY" with stack trace:

>    at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
>    at System.Collections.Generic.Dictionary\`2.Insert(TKey key, TValue value, Boolean add)
>    at Amazon.Extensions.CognitoAuthentication.CognitoUser.<StartWithSrpAuthAsync>d__77.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter\`1.GetResult()
>    at MoneyPro.Logic.Synchronization.AuthentificationLogic.<SignInAsync>d__18.MoveNext()

## Possible Solution
Remove 
```C#
if (Device != null && !string.IsNullOrEmpty(Device.DeviceKey))
{
    srpAuthResponses.Add(CognitoConstants.ChlgParamDeviceKey, Device.DeviceKey);
}
```
from CreateSrpPasswordVerifierAuthRequest in CognitoUser (it's not validate device key for request), or use indexer instead of Add method for key CognitoConstants.ChlgParamDeviceKey in CognitoUser.StartWithSrpAuthAsync.

## Steps to Reproduce (for bugs)
Try to run my code. If i not set Device it's work correctly.

## Your Environment

* AWSSDK.Core: 3.3.24.4
* AWSSDK.Extensions.CognitoAuthentication: 0.9.4
* Operating System and version: Windows 10 17134.165
* Visual Studio version: Community 2017 15.7.6
* Targeted .NET platform: Microsoft.NETCore.UniversalWindowsPlatform 5.4.0

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by niraj-bpsoftware** [comment]
Facing same issue. Any ETA?

**Comment by assyadh** [comment]
Hi,

We are keeping track of this issue. While I don't have an ETA yet for the resolution, it is on my radar.

Hamza.

**Comment by assyadh** [comment]
Hi,

The authentication library has been moved to its own repo: 

https://github.com/aws/aws-sdk-net-extensions-cognito

This issue has been fixed in the new repository. 

While the new library is in development, the NuGet package won't be updated. We have no ETA yet for the GA. You can try to build the library yourself in the meantime.

We appreciate any feedback and hope that will solve the issue. If not, please feel free to open an issue in the new repository.

Hamza
