### ISSUE TITLE
Error loading AWS profiles: The located assembly's manifest definition does not match the assemble reference

### ISSUE THREAD

**Issue by wfridy** [aws/aws-sdk-net#1056]
AWS Explorer was working.  Although when I open the panel now, it shows the profile and region display, but any interaction including refresh generates an immediate prompt rendering the panel useless.

Error Message:  
Error loading AWS profiles: The located assembly's manifest definition does not match the assembly reference (Exception from HRESULT: 0x80131040)

Steps I have tried:
I have tried creating a new profile.
I have tried disabling and uninstalling and reinstalling from the Visual Studio extensions screen.
I have also tried using the installer version of the AWS toolkit.

## Your Environment
Microsoft Visual Studio Enterprise 2017 Version 15.7.5
AWS Toolkit for Visual Studio 2017 Version 1.14.4.1
Windows 10 Pro Version 1803 Build 17134.228

Attached find the log file from the extension:

[log.txt](https://github.com/aws/aws-sdk-net/files/2342766/log.txt)

**Comment by wfridy** [comment]
I may have discovered what is triggering the error.  When the Telerik Test Studio Dev Edition is enabled, the error starts happens.  There appears to be a compatibility issue between the AWS extension tooling and the Telerik Test Studio Dev Edition.  When it is disabled, the error does goes away.  I have generated a bug report with Progress about the error.

**Comment by wfridy** [comment]
Here is the link for the public ticket:  https://feedback.telerik.com/Project/161/Feedback/Details/256287-error-loading-aws-profiles

**Comment by normj** [comment]
I assume Telerik Test Studio Dev Edition must be using an old version of the AWS SDK for .NET for some feature that is causing the conflicts. One of the problems with Visual Studio extensions is there is no separate AppDomain for each extensions so you can get these collisions.
