### ISSUE TITLE
How to transfer a payload to S3 in a single chunk 

### ISSUE THREAD

**Issue by mateuszbartosiak** [aws/aws-sdk-net#1057]
According to [aws docs](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-auth-using-authorization-header.html) there are two ways of transfering the payload:
- In multiple chunks (which sets 'x-amz-content-sha256' header to 'STREAMING-AWS4-HMAC-SHA256-PAYLOAD')
- In single chunk (which sets 'x-amz-content-sha256' header to either the payload checksum or to 'UNSIGNED-PAYLOAD')

I want to send a payload in a single chunk with a checksum, but the default for the library seems to be sending in multiple chunks. Is there a way to change that behavior?

**Comment by mateuszbartosiak** [comment]
Having done some research I have found a solution.

In
```
Services\S3\Custom\_bcl+coreclr+pcl\Transfer\Internal\SimpleUploadCommand.cs:54
AWSSDK.S3.dll!Amazon.S3.Transfer.Internal.SimpleUploadCommand.ConstructRequest() Line 54 
```

I had to set: `putRequest.UseChunkEncoding = false;`

Is there a way to make this configurable for clients of the library?

**Comment by normj** [comment]
You would need to the AmazonS3Client directly and call PutObject instead of using the TransferUtility which doesn't currently expose this property.
