### ISSUE TITLE
Sqs error while deleting message 

### ISSUE THREAD

**Issue by yuvayuvips** [aws/aws-sdk-net#1059]
Hi,
we are using DLL in an external application to create/delete messages in AWS SQS queue. But for few cases we are getting error message as follows, we have verified that no issues with policy/access because its getting failed for few cases only and that too getting processed during reties sometime. 

Retry Attempt--5--Message --Access to the resource <SQS QUEUE>is denied.Inner Exce--Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (403) Forbidden. ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.   at System.Net.HttpWebRequest.GetResponse()   at Amazon.Runtime.Internal.HttpRequest.GetResponse()   --- End of inner exception stack trace ---   at Amazon.Runtime.Internal.HttpRequest.GetResponse()   at Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executionContext)   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)   at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext)   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)   at Amazon.SQS.Internal.ValidationResponseHandler.InvokeSync(IExecutionContext executionContext)   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)

**Comment by sstevenkang** [comment]
This looks like it's coming from SQS service not the SDK.  Could you provide request ids for those requests?  We'll forward that information to SQS team.

**Comment by yuvayuvips** [comment]
what kind of request id's you are asking?and what is the SQS team?

**Comment by klaytaybai** [comment]
Hi @yuvayuvips, the SQS team is the AWS team responsible for building the underlying SQS service that the .NET SDK then exposes to .NET developers.  

If you have an AWS support plan, you will probably have better support on this issue if you go through those channels.  

The request ids could be helpful for identifying the cause of your issue.  You can find them in your responses' ResponseMetadata property.

**Comment by yuvayuvips** [comment]
Hi @sstevenkang / @klaytaybai , 
Here is the message id : cf538c5b-e2c4-4c86-b460-8d5e6248cb58
Please do post me the updates. Cheers.

**Comment by yuvayuvips** [comment]
Hi , Any update on this issue :(

**Comment by sstevenkang** [comment]
This sounds similar to https://github.com/aws/aws-sdk-net/issues/1063.  is that the case?

**Comment by klaytaybai** [comment]
I don't think it is closely related to that issue because it sounds like the credentials are still valid after the 403 has already been returned.  

I have made a request for logs, and I am now waiting for a response.

If this is quite problematic for you and retries are sometimes working, I suggest increasing the number of retries to help mitigate the problem for now until a better cause/solution is found.

**Comment by klaytaybai** [comment]
@yuvayuvips, how often are you making these requests?  Are they in a quickly-processing loop or logic that is otherwise making enough requests that they might warrant being throttled by our systems?  That would also return the 403

**Comment by yuvayuvips** [comment]
@klaytaybai we are making 20 request calls per hour by average. as you suggested we have implemented retry count (10 times) as hot fix in our application. but still beyond the limit few cases are failing to connect aws sqs.

**Comment by sstevenkang** [comment]
@yuvayuvips We need request IDs, not message IDs to trace the HTTP request.  Could you provide them?  You can get it via https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/AmazonServiceException.cs#L114

**Comment by yuvayuvips** [comment]
@sstevenkang , After some code changes in exception code , i could able to get request ids from error messages , please find the details below, 
Code Change : 
 catch (AmazonSQSException e)
            {
                throw new AmazonSQSException("SQS Error" + "::RequestId:" + e.RequestId.ToString() + "::Error Code:" + e.ErrorCode.ToString() + "::Error Type:" + e.ErrorType.ToString() + "::HResult:" + e.HResult.ToString() + "::InnerException:" + e.InnerException.ToString() + "::Message:" +e.Message.ToString() +  "::StackTrace:"+ e.StackTrace.ToString());
            }

Error msg : 
Attempt--10--Message --SQS Error::RequestId:2aa467a8-4946-5841-9645-338b41c54613::Error Code:AccessDenied::Error Type:Sender::HResult:-2146233088::InnerException:Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (403) Forbidden. ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.   at System.Net.HttpWebRequest.GetResponse()   at Amazon.Runtime.Internal.HttpRequest.GetResponse()   --- End of inner exception stack trace ---   at Amazon.Runtime.Internal.HttpRequest.GetResponse()   at Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executionContext)   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)   at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext)   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)   at Amazon.SQS.Internal.ValidationResponseHandler.InvokeSync(IExecutionContext executionContext)   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)::Message:Access to the resource https://sqs.eu-west-1.amazonaws.com/719848509458/techservices-automation-kofax-out-prd is denied.::StackTrace:   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)   at Amazon.Runtime.Internal.ExceptionHandler`1.Handle(IExecutionContext executionContext, Exception exception)   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)   at Amazon.Runtime.Internal.Signer.InvokeSync(IExecutionContext executionContext)   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeSync(IExecutionContext executionContext)   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)   at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext)   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)   at Amazon.Runtime.Internal.EndpointResolver.InvokeSync(IExecutionContext executionContext)   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)   at Amazon.SQS.Internal.ProcessRequestHandler.InvokeSync(IExecutionContext executionContext)   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)   at Amazon.Runtime.Internal.Marshaller.InvokeSync(IExecutionContext executionContext)   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext)   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)   at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext)   at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext)   at Amazon.Runtime.AmazonServiceClient.Invoke[TRequest,TResponse](TRequest request, IMarshaller`2 marshaller, ResponseUnmarshaller unmarshaller)   at Amazon.SQS.AmazonSQSClient.SendMessage(SendMessageRequest request)   at Amazon.SQS.ExtendedClient.AmazonSQSExtendedClientBase.SendMessage(SendMessageRequest request)   at Amazon.SQS.ExtendedClient.AmazonSQSExtendedClient.SendMessage(SendMessageRequest sendMessageRequest)InnerException--


Request Ids: 
f6a85727-bd00-5eab-823f-0304b246a6d8
0c3376e1-5283-5343-9f15-22c25df439b6
2aa467a8-4946-5841-9645-338b41c54613

**Comment by Nimaway** [comment]
Can you double check that all servers that are polling the queue have the same permissions.  
If there are more than one server, you could perhaps turn all but one off and test each at a time.

**Comment by yuvayuvips** [comment]
Hi all,..one good news is there was no issue with the code. some unknown service was calling the sqs from the consuming application.we found that and stopped those.now our application is running with no issues. Thanks for your support..
