### ISSUE TITLE
SQS ReceiveMessage sample code error

### ISSUE THREAD

**Issue by joshjreed** [aws/aws-sdk-net#1060]
While working with the latest version of the SDK for SQS, I found that the AmazonSQSClient.ReceiveMessage() method appears to have changed to an internal method. That causes the provided example code (https://github.com/aws/aws-sdk-net/blob/master/docgenerator/AWSSDKDocSamples/SQS/SQSSamples.cs#L28) to show an error "Cannot access internal method 'ReceiveMessage' here". Should the documentation be updated, or is this an unintended bug?

## Expected Behavior
I'd like to be able to call the ReceiveMessage method in my code.

## Current Behavior
The ReceiveMessage method for instances of AmazonSQSClient is marked as internal, which causes errors when trying to run the example code linked above.

## Possible Solution
Remove the internal attribute from the method

## Steps to Reproduce (for bugs)
Running the example code here shows the error for the latest version of AWSSDK.SQS https://github.com/aws/aws-sdk-net/blob/master/docgenerator/AWSSDKDocSamples/SQS/SQSSamples.cs#L28

## Your Environment

* AWSSDK.Core version used: 3.3.25.1
* AWSSDK.SQS version: 3.3.3.17
* Operating System and version: Windows 10
* Visual Studio version: None - Using the Rider IDE
* Targeted .NET platform: Core 2.0

## .NET Core Info

* .NET Core version used for development: 2.0
* .NET Core version installed in the environment where application runs: 2.0

**Comment by sstevenkang** [comment]
.NET Core version of the SDK does not expose synchronous methods.  You should use [`ReceiveMessageAsync()`](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/SQS/Generated/_mobile/AmazonSQSClient.cs#L1398) instead.
