### ISSUE TITLE
extension/package.son not found inside zip

### ISSUE THREAD

**Issue by Ch3ck** [aws/aws-sdk-net#1067]
I tried installing the AWS Lambda extension on VS Code 17 and got the following error above.
## Expected Behavior

It's expected to install when I load the vsix file.

## Steps to Reproduce (for bugs)

just download the vsix file, open entextions-> settings -> install from vsix and load the file on the mac. you get the error above.

## Context

Install the AWS Lambda extension on VS code

## Your Environment

* AWSSDK.Core version used:  1.14.4.1
* Service assembly and version used: 
* Operating System and version: 
Mac OS High Sierra
* Visual Studio version: 
VS Code 2017

* Targeted .NET platform: 
[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by normj** [comment]
I'm not sure what you are installing but we don't currently have an official AWS Lambda extension for Visual Studio Code.

**Comment by Ch3ck** [comment]
@normj This is what I tried installing:  [AWS Toolkit for VS 2017]( https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.AWSToolkitforVisualStudio2017)

**Comment by normj** [comment]
Sorry but that is only for the full Visual Studio 2017 not for Visual Studio Code.

**Comment by Ch3ck** [comment]
Thanks for the clarification
