### ISSUE TITLE
AWSSDK.SimpleNotificationService on unity 2018.2.2f1 can not receive notification on device android

### ISSUE THREAD

**Issue by thuyKP** [aws/aws-sdk-net#1069]
## Current Behavior
My project use AWSSDK.SimpleNotificationService 3.3.1.9 (all version lower) run normal on unity 5.6 (all version 5.6) and i can receiver notification on my device Android. But i open my project on unity 2018.2.2f1 then built apk for device test, i can not receiver notification.
## AWSSDK.SimpleNotificationService run normal on all unity version 5.6
I have tested with api 22 to api 27
## Logcat on Android studio: 
Bellow is all logcat collect when i test ap  on android 5.1 Api 22
## Unity 5.6.6f2:   app run normal and receive notification success

09-11 15:45:31.121 12229-12229/? D/ActivityThread: BDC-Calling onReceive: intent=Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10 pkg=jp.co.personlink.hacot cmp=jp.co.personlink.hacot/com.amazonaws.unity.GCMBroadcastReceiver (has extras) }, receiver=com.amazonaws.unity.GCMBroadcastReceiver@38fabfa8
09-11 15:45:31.181 713-745/? D/PowerManagerService: acquireWakeLockInternal: lock=295198788, flags=0x1, tag="wake:jp.co.personlink.hacot/com.amazonaws.unity.GCMIntentService", ws=null, uid=10100, pid=12229
09-11 15:45:31.181 713-745/? D/PowerManagerNotifier: onWakeLockAcquired: flags=1, tag="wake:jp.co.personlink.hacot/com.amazonaws.unity.GCMIntentService", packageName=jp.co.personlink.hacot, ownerUid=10100, ownerPid=12229, workSource=null
09-11 15:45:31.191 12229-12229/? D/ActivityThread: BDC-RECEIVER handled : 0 / ReceiverData{intent=Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10 pkg=jp.co.personlink.hacot cmp=jp.co.personlink.hacot/com.amazonaws.unity.GCMIntentService (has extras) } packageName=jp.co.personlink.hacot resultCode=-1 resultData=null resultExtras=null}
09-11 15:45:31.192 12229-12229/? D/ActivityThread: SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@d18fac1 className=com.amazonaws.unity.GCMIntentService packageName=jp.co.personlink.hacot intent=null}
09-11 15:45:31.196 12229-12229/? D/ActivityThread: SVC-CREATE_SERVICE handled : 0 / CreateServiceData{token=android.os.BinderProxy@d18fac1 className=com.amazonaws.unity.GCMIntentService packageName=jp.co.personlink.hacot intent=null}
    SVC-Calling onStartCommand: com.amazonaws.unity.GCMIntentService@224fc266, flags=0, startId=1
    SVC-SERVICE_ARGS handled : 0 / ServiceArgsData{token=android.os.BinderProxy@d18fac1 startId=1 args=Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10 pkg=jp.co.personlink.hacot cmp=jp.co.personlink.hacot/com.amazonaws.unity.GCMIntentService (has extras) }}
09-11 15:45:31.200 713-1313/? D/PowerManagerService: releaseWakeLockInternal: lock=295198788 [wake:jp.co.personlink.hacot/com.amazonaws.unity.GCMIntentService], flags=0x0, total_time=19ms
09-11 15:45:31.200 713-1313/? D/PowerManagerNotifier: onWakeLockReleased: flags=1, tag="wake:jp.co.personlink.hacot/com.amazonaws.unity.GCMIntentService", packageName=jp.co.personlink.hacot, ownerUid=10100, ownerPid=12229, workSource=null
09-11 15:45:31.202 12229-12229/? D/ActivityThread: SVC-Destroying service: com.amazonaws.unity.GCMIntentService@224fc266

## Log 1:
09-11 15:57:09.280 12552-12552/? D/ActivityThread: BDC-Calling onReceive: intent=Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10 pkg=jp.co.personlink.hacot cmp=jp.co.personlink.hacot/com.amazonaws.unity.GCMBroadcastReceiver (has extras) }, receiver=com.amazonaws.unity.GCMBroadcastReceiver@3dc5558f
09-11 15:57:09.290 713-2635/? D/PowerManagerService: acquireWakeLockInternal: lock=274943213, flags=0x1, tag="wake:jp.co.personlink.hacot/com.amazonaws.unity.GCMIntentService", ws=null, uid=10100, pid=12552
09-11 15:57:09.291 713-2635/? D/PowerManagerNotifier: onWakeLockAcquired: flags=1, tag="wake:jp.co.personlink.hacot/com.amazonaws.unity.GCMIntentService", packageName=jp.co.personlink.hacot, ownerUid=10100, ownerPid=12552, workSource=null
09-11 15:57:09.292 12552-12552/? D/ActivityThread: BDC-RECEIVER handled : 0 / ReceiverData{intent=Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10 pkg=jp.co.personlink.hacot cmp=jp.co.personlink.hacot/com.amazonaws.unity.GCMIntentService (has extras) } packageName=jp.co.personlink.hacot resultCode=-1 resultData=null resultExtras=null}
09-11 15:57:09.293 12552-12552/? D/ActivityThread: SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@28b1301c className=com.amazonaws.unity.GCMIntentService packageName=jp.co.personlink.hacot intent=null}
09-11 15:57:09.297 12552-12552/? D/ActivityThread: SVC-CREATE_SERVICE handled : 0 / CreateServiceData{token=android.os.BinderProxy@28b1301c className=com.amazonaws.unity.GCMIntentService packageName=jp.co.personlink.hacot intent=null}
09-11 15:57:09.298 12552-12552/? D/ActivityThread: SVC-SERVICE_ARGS handled : 0 / ServiceArgsData{token=android.os.BinderProxy@28b1301c startId=1 args=Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10 pkg=jp.co.personlink.hacot cmp=jp.co.personlink.hacot/com.amazonaws.unity.GCMIntentService (has extras) }}
09-11 15:57:09.316 713-2679/? D/PowerManagerService: releaseWakeLockInternal: lock=274943213 [wake:jp.co.personlink.hacot/com.amazonaws.unity.GCMIntentService], flags=0x0, total_time=25ms
09-11 15:57:09.316 713-2679/? D/PowerManagerNotifier: onWakeLockReleased: flags=1, tag="wake:jp.co.personlink.hacot/com.amazonaws.unity.GCMIntentService", packageName=jp.co.personlink.hacot, ownerUid=10100, ownerPid=12552, workSource=null
09-11 15:57:09.297 12552-12552/? D/ActivityThread: SVC-Calling onStartCommand: com.amazonaws.unity.GCMIntentService@21c23425, flags=0, startId=1
09-11 15:57:09.320 12552-12552/? D/ActivityThread: SVC-Destroying service: com.amazonaws.unity.GCMIntentService@21c23425

## Log 2:

09-11 15:58:38.469 12552-12552/? D/ActivityThread: BDC-Calling onReceive: intent=Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10 pkg=jp.co.personlink.hacot cmp=jp.co.personlink.hacot/com.amazonaws.unity.GCMBroadcastReceiver (has extras) }, receiver=com.amazonaws.unity.GCMBroadcastReceiver@b06eda1
09-11 15:58:38.516 713-1313/? D/PowerManagerService: acquireWakeLockInternal: lock=986118738, flags=0x1, tag="wake:jp.co.personlink.hacot/com.amazonaws.unity.GCMIntentService", ws=null, uid=10100, pid=12552
    updateWakeLockSummaryLocked: mWakefulness=Awake, mWakeLockSummary=0x1
    updateUserActivitySummaryLocked: mWakefulness=Awake, mUserActivitySummary=0x1, nextTimeout=6151847 (in 1094021 ms)
    mDisplayPowerRequest.policy = 3
    isWfdEnabled() mWfdStatus=WifiDisplayStatus{featureState=0, scanState=0, activeDisplayState=0, activeDisplay=null, displays=[], sessionInfo=WifiDisplaySessionInfo: C/O:Client,GId:,Pp:,SId:0,IP:}, return false
09-11 15:58:38.516 713-1313/? D/PowerManagerNotifier: onWakeLockAcquired: flags=1, tag="wake:jp.co.personlink.hacot/com.amazonaws.unity.GCMIntentService", packageName=jp.co.personlink.hacot, ownerUid=10100, ownerPid=12552, workSource=null
09-11 15:58:38.524 12552-12552/? D/ActivityThread: BDC-RECEIVER handled : 0 / ReceiverData{intent=Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10 pkg=jp.co.personlink.hacot cmp=jp.co.personlink.hacot/com.amazonaws.unity.GCMIntentService (has extras) } packageName=jp.co.personlink.hacot resultCode=-1 resultData=null resultExtras=null}
    SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@39e06bc6 className=com.amazonaws.unity.GCMIntentService packageName=jp.co.personlink.hacot intent=null}
09-11 15:58:38.526 12552-12552/? D/ActivityThread: SVC-CREATE_SERVICE handled : 0 / CreateServiceData{token=android.os.BinderProxy@39e06bc6 className=com.amazonaws.unity.GCMIntentService packageName=jp.co.personlink.hacot intent=null}
    SVC-Calling onStartCommand: com.amazonaws.unity.GCMIntentService@26886787, flags=0, startId=1
    SVC-SERVICE_ARGS handled : 0 / ServiceArgsData{token=android.os.BinderProxy@39e06bc6 startId=1 args=Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10 pkg=jp.co.personlink.hacot cmp=jp.co.personlink.hacot/com.amazonaws.unity.GCMIntentService (has extras) }}
09-11 15:58:38.531 713-2635/? D/PowerManagerService: releaseWakeLockInternal: lock=986118738 [wake:jp.co.personlink.hacot/com.amazonaws.unity.GCMIntentService], flags=0x0, total_time=15ms
09-11 15:58:38.531 713-2635/? D/PowerManagerNotifier: onWakeLockReleased: flags=1, tag="wake:jp.co.personlink.hacot/com.amazonaws.unity.GCMIntentService", packageName=jp.co.personlink.hacot, ownerUid=10100, ownerPid=12552, workSource=null
09-11 15:58:38.535 12552-12552/? D/ActivityThread: SVC-Destroying service: com.amazonaws.unity.GCMIntentService@26886787

## Hope someone has the same problem with me and help me solve this problem, thanks a lot

**Comment by iamau555** [comment]
Have the same problem, still looking forward for the solution too
