### ISSUE TITLE
Verifying Message from SNS Topics

### ISSUE THREAD

**Issue by talk2alie** [aws/aws-sdk-net#1070]
Good day folks,
I do not see any means to verify messages that SNS Topics send to a subscribed HTTP endpoint. I see a sample Java servlet here, https://docs.aws.amazon.com/sns/latest/dg/SendMessageToHttp.example.java.html, but none for .Net. Is this supported in .net?
Thanks.

**Comment by klaytaybai** [comment]
Hi @talk2alie, I think [Message.IsMessageSignatureValid](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/SNS/MMessageIsMessageSignatureValid.html) should be able to help you out with that.  I am not aware of any .NET examples that use this.  Thank you for pointing out this documentation gap.  We appreciate customers giving us feedback on our documentation and examples so we can know what improvements to prioritize.
