### ISSUE TITLE
.NET SDK doesn't understand chained assume-role profiles

### ISSUE THREAD

**Issue by akdor1154** [aws/aws-sdk-net#1072]
Set up chained profiles as supported by boto and the js sdk, like so:

`~/.aws/credentials`:
```ini
[base-user]
aws_access_key_id = AKIA...
aws_secret_access_key = ####...
```

`~/.aws/config`:
```ini
[profile base-user]
region = ap-southeast-2

[profile intermediate-role]
role_arn = arn:aws:iam::0123456789:role/intermediate-role
source_profile = base-user
region = ap-southeast-2

[profile final-role]
role_arn = arn:aws:iam::0123456789:role/final-role
source_profile = intermediate-role
region = ap-southeast-2
```

set the environment variable `AWS_PROFILE=final-role`.

Compile this test:

```cs
        static void Main(string[] args)
        {
            var sts = new AmazonSecurityTokenServiceClient();
            var me = sts.GetCallerIdentity(new GetCallerIdentityRequest());
            Console.WriteLine("account: {0}, arn: {1}, userId: {2}", me.Account, me.Arn, me.UserId);
        }
```

## Expected Behavior

Use the CLI to check that your profiles work:
`aws sts get-caller-identity`
```json
{
    "UserId": "AROA****:botocore-session-1234...",
    "Account": "0123456789",
    "Arn": "arn:aws:sts::0123456789:assumed-role/final-role/botocore-session-1234...."
}
```

Now run your C# code that should do the same thing.
This should print:
`account: 0123456789, arn: arn:aws:sts::0123456789:assumed-role/final-role/aws-dotnet-sdk-session-12345..., userId: AROA****:aws-dotnet-sdk-session-12345...`
as an analogue to the cli/boto3.

## Current Behavior
However, it actually prints
`account: 0123456789, arn: arn:aws:sts::0123456789:assumed-role/intermediate-role/aws-dotnet-sdk-session-12345..., userId: AROA...:aws-dotnet-sdk-session-12345...`
(i.e. it only assumes a single level.).

Setting AWS_PROFILE to a single-level assume-role profile, either `intermediate-role` or `another-intermediate-role` above, has everything working fine.

## More Weirdness
Interestingly, if we add another "branch" of role assumption from the base user, then that one actually hangs for a few more seconds than I'd consider acceptable, and then prints a stacktrace.

Add to ~/.aws/config:

```ini
[profile another-intermediate-role]
role_arn = arn:aws:iam::0123456789:role/another-intermediate-role
source_profile = base-user
region = ap-southeast-2

[profile another-final-role]
role_arn = arn:aws:iam::0123456789:role/another-final-role
source_profile = another-intermediate-role
region = ap-southeast-2
```
set `AWS_PROFILE=another-final-role`
Run code above
```
Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.FetchCredentials () [0x00008] in <c720dfff1275465b9241f35ecbf6b958>:0 
  at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentials () [0x0001b] in <c720dfff1275465b9241f35ecbf6b958>:0 
  at Amazon.Runtime.Internal.CredentialsRetriever.PreInvoke (Amazon.Runtime.IExecutionContext executionContext) [0x00030] in <c720dfff1275465b9241f35ecbf6b958>:0 
  at Amazon.Runtime.Internal.CredentialsRetriever.InvokeSync (Amazon.Runtime.IExecutionContext executionContext) [0x00000] in <c720dfff1275465b9241f35ecbf6b958>:0 
  at Amazon.Runtime.Internal.PipelineHandler.InvokeSync (Amazon.Runtime.IExecutionContext executionContext) [0x0000e] in <c720dfff1275465b9241f35ecbf6b958>:0 
  at Amazon.Runtime.Internal.RetryHandler.InvokeSync (Amazon.Runtime.IExecutionContext executionContext) [0x00040] in <c720dfff1275465b9241f35ecbf6b958>:0 
  at ...
``` 

## Your Environment

* AWSSDK.Core version used: 3.3.25.3
* Service assembly and version used: SecurityToken 3.3.4.15
* Operating System and version: Ubuntu 18.04 with mono (trying to emulate a default .NET Framework Visual Studio build).
* Targeted .NET platform: 4.5

Logging gives nothing interesting:
```
UserCrypto 1|2018-09-17T17:23:05.694Z|INFO|UserCrypto is not supported.  This may be due to use of a non-Windows operating system or Windows Nano Server, or the current user account may not have its profile loaded. Crypt32.dll
ProfileAWSRegion 2|2018-09-17T17:23:05.756Z|INFO|Region found in profile 'final-role' in store Amazon.Runtime.CredentialManagement.CredentialProfileStoreChain
```
This is identical in both scenarios. I think the UserCrypto error is unrelated as it appears even when I set up a working profile.

**Comment by akdor1154** [comment]
As a quick guess, could the call in https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/CredentialManagement/_bcl%2Bcoreclr/AWSCredentialsFactory.cs#L191 to `GetSourceAWSCredentials` be changed to recursively call `GetAWSCredentialsInternal`? That would (based on my limited reading) fix this, and allow `GetSourceAWSCredentials` to be completely removed.

**Comment by codeimpossible** [comment]
I think I might be experiencing the same problem and wanted to check before opening a separate issue.

**~/.aws/credentials:**

```
[test]
aws_access_key_id = KEY...
aws_secret_access_key = SECRET...
```

**~/.aws/config:**

```
[profile test-assume-role]
role_arn=arn:iam:1234567890:role/my-testing-role
source_profile=test
```

```csharp
    static void Main(string[] args)
    {
        var dummyConfig = new Amazon.Runtime.CredentialManagement.SharedCredentialsFile();
        foreach(var profile in dummyConfig.ListProfileNames()) 
        {
            Console.WriteLine(profile);
        }
    }
```

I think this should print the following:

- test
- test-assume-role

but instead, it only prints `test-assume-role`. Somewhere the `test` profile is being removed from the list of available profiles. This causes calls to `CredentialProfileStoreChain#TryGetAWSCredentials` with the `test` profile to fail, which is how I noticed this problem.

**Comment by matteo-prosperi** [comment]
Solved by https://github.com/aws/aws-sdk-net/commit/623dbc4c044d209e23be6cc1ea4aac52f5112881

**Comment by oerodriguezn** [comment]
Is it uploaded to nuget? Which version?

**Comment by matteo-prosperi** [comment]
@oerodriguezn it is updated in [AWSSDK.Core 3.3.103.19](https://www.nuget.org/packages/AWSSDK.Core/3.3.103.19). But I would suggest to update to the latest version instead.

See https://github.com/aws/aws-sdk-net/blob/master/SDK.CHANGELOG.md.
```
3.3.561.1 (2019-08-01 21:25 UTC)
Core 3.3.103.19
Allow "Assume Role" profiles to reference other "Assume Role" profiles as their source
All services packages updated to require new Core
```

**Comment by peteristhegreat** [comment]
I was getting behavior (in `3.3.0`) where when I was initializing the `AmazonSecurityTokenServiceClient`, it was freezing up or just hanging on the call without a printed error.  Updating to the `3.3.104` fixed it for me.

**Comment by markomeagher-grocerkey** [comment]
I've been having trouble getting my .net app to use the assumed role setup, to trouble shoot I replicated the application in the original post and when I run the application I get "Unable to get IAM security credentials from EC2 Instance Metadata Service", if I run from the CLI I get expected result.

Any ideas why this would be?
