### ISSUE TITLE
Potential copy-paste error in Http message factory

### ISSUE THREAD

**Issue by LordMike** [aws/aws-sdk-net#1076]
I was looking for the exact implementation of proxies, and stumbled across this.

https://github.com/aws/aws-sdk-net/blob/3fc03fac088bee773d2c4b4df746408688fc5a57/sdk/src/Core/Amazon.Runtime/Pipeline/HttpHandler/_bcl/HttpWebRequestFactory.cs#L421-L422

It would seem metric no. 2 should use a name for "Port", and not "Host".

**Comment by sstevenkang** [comment]
Yup. Looks like a bug to me.  Thanks for pointing this out!

**Comment by sstevenkang** [comment]
Fixed with https://github.com/aws/aws-sdk-net/commit/b180905d51779336bb58b5d1e3f78d5a3f340ef0.
