### ISSUE TITLE
Amazon.Util.EC2InstanceMetadata.Region does not follow documented behaviour

### ISSUE THREAD

**Issue by myron-semack** [aws/aws-sdk-net#1084]
If you use Amazon.Util.EC2InstanceMetadata.Region on a non-EC2 computer, it may throw an exception instead of returning null as the documentation indicates.  (May be a .NET Framework vs .NET Core issue.)

## Expected Behavior
It should return null as indicated by the documentation: https://docs.aws.amazon.com/sdkfornet/v3/apidocs/index.html
```
AWSRegionStatic = Amazon.Util.EC2InstanceMetadata.Region;
if(AWSRegionStatic == null)
{
    Console.WriteLine("Unable to read EC2 metadata");
}
```

## Current Behavior
It throws an exception.  We saw it return either an HttpRequestException or OperationCanceledException on our systems while running .NET Core.
```
try
{
    AWSRegionStatic = Amazon.Util.EC2InstanceMetadata.Region;
}
catch (Exception e)
{
    Console.WriteLine("Got exception reading EC2 metadata", e);
}
```

## Possible Solution
Line 517 in blob/master/sdk/src/Core/Amazon.Util/_bcl%2Bcoreclr/EC2InstanceMetadata.cs does not appear to be catching all exceptions.  Looks like it it is trying to catch WebException, which is fine for .NET Framework but not .NET Core.

## Steps to Reproduce (for bugs)

See code fragments above.

## Context

For starters the function does not match the documented behaviour, which is a problem.  A secondary issue is that we have to do a plain Exception catch in our code (since we do not know what the AWS SDK will throw), which means we may swallow a legitimate error.

## Your Environment

* AWSSDK.Core version used: 3.3.21.20
* Operating System and version: Windows 10 x64 (10.0.17134)
* Visual Studio version: 15.8.5 (Professional)
* Targeted .NET platform: .NET Core 2.1

## .NET Core Info

* .NET Core version used for development: 2.1.4
* .NET Core version installed in the environment where application runs: 2.1.4 
* Output of `dotnet --info`:
```
 .NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Host (useful for support):
  Version: 2.1.1
  Commit:  6985b9f684

.NET Core SDKs installed:
  1.0.4 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by klaytaybai** [comment]
Thanks for reporting this.

**Comment by JJoe2** [comment]
I'm also impacted by this bug - any fix in the pipeline?

I suspect it might be related to https://github.com/dotnet/corefx/issues/20296
