### ISSUE TITLE
S3 Select not returning full records

### ISSUE THREAD

**Issue by softwareguy74** [aws/aws-sdk-net#1092]
For example,  I have the following records in a CSV file in S3:

Row1,Value1
Row2,Value2

Depending on how much data is being returned by S3 Select, I may get only the following for the Payload:

Row1,Value1
Row2,Val

Then, on the next received event, I get the rest of the data, such as:

ue2

This is very hard to handle on the client side.  Can we get the SDK to only return full records with each payload?

**Comment by klaytaybai** [comment]
Hi @softwareguy74, the members of our team who have discussed this so far are unaware of any functionality that would allow you to force the return of full records.  We're putting in an internal ticket to see if this feature can be added.  I can't make guarantees or an estimate at this time.  In the meantime, please consider trying to work with the results that are given and parse them based on the new record delimiter.  Thanks for giving us your feedback!

**Comment by kaleshanagineni** [comment]
is there any update on this feature, I still do see the s3select does not return the entire row in the latest net SDK for s3.

**Comment by Kavitha-Desu-Caci** [comment]
Any update on this feature is greatly appreciated as i am also facing the same issue s3select is not returning the entire row.
