### ISSUE TITLE
Unable to use API Key to Authenticate AppSync requests

### ISSUE THREAD

**Issue by taylor-zr** [aws/aws-sdk-net#1098]
I've been looking at how to use .NET to create a client that is capable of making GraphQL requests to AppSync. There's a class AuthenticationType that contains static members, however these never seem to be passed along. E.g. I can't do:

```
AuthenticationType apiKey = new AuthenticationType.API_KEY;
apiKey.setKey(keyVal);
```

Or even pass along the variable apiKey in any meaningful way afaict.

Is the only way to use AppSync using C# by using Cognito with User Pools, or am I missing something?

EDIT: I actually don't see how to use Cognito User Pools either. Are there any examples to look at?

**Comment by klaytaybai** [comment]
Hi @taylor-zr, I'm not too familiar with AppSync or Cognito yet, but they are high on my list of services in which I want to get more knowledge.  To the best of my knowledge, we are lacking in .NET examples in both, which is something we will try to improve.  In the meantime, I'll try to provide as much info as I have.  

The AuthenticationType class is not where you set the APIKey.  This class is simply for defining constants that you use to tell the API which authentication means to expect.

You can use the SDK to create the GraphqlApi with your choice of authentication type as seen below.  Once you have created the API, use its ApiId property to create your APIKey.  Per the [AppSync documentation](https://docs.aws.amazon.com/appsync/latest/devguide/security.html), you should be able to then create an HttpRequestMethod with the GraphqlApi's Uris and the APIKey's Id values.

`using System;
using System.Threading.Tasks;
using Amazon;
using Amazon.AppSync;
using Amazon.AppSync.Model;

namespace AppSync
{
    class Program
    {
        static void Main(string[] args)
        {
            CreateAPI().Wait();
        }

        static async Task CreateAPI() {
            using (AmazonAppSyncClient client = new AmazonAppSyncClient(RegionEndpoint.USWest2))
            {
                CreateGraphqlApiResponse createGraphqlApiResponse = await client.CreateGraphqlApiAsync(new CreateGraphqlApiRequest() { AuthenticationType = AuthenticationType.API_KEY, Name = "TestApi" });
                CreateApiKeyResponse createApiKeyResponse = await client.CreateApiKeyAsync(new CreateApiKeyRequest() { ApiId = createGraphqlApiResponse.GraphqlApi.ApiId });
            }
        }
    }
}
`

**Comment by costleya** [comment]
I tried finding a nice GraphQL .NET library that let you set HttpHeaders, but after 3 attempts just used HttpClient.

```csharp
        public static async Task Main(string[] args)
        {
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Add("x-api-key", "xxxxxxx");

                client.BaseAddress = new Uri("https://xxxxxxxxxx.amazonaws.com/graphql");

                var query = "{\"query\": \"query ListEvents { listEvents { items { id name }} }\"}";
                var content = new StringContent(query);
                content.Headers.ContentType = MediaTypeHeaderValue.Parse("application/json");

                var response = await client.PostAsync("", content);
                var responseBody = await response.Content.ReadAsStringAsync();
                Console.WriteLine(responseBody);
            }
        }
```

**Comment by taylor-zr** [comment]
Hello. Just to be clear, I'm an internal customer and this is an external customer's request. They are currently using HttpClient, but don't see a way to do this cleanly using the SDK and Cognito and would like to push for an actual fix. If there is another issue tracking this item, I'd be happy to send it along to the customer.

**Comment by costleya** [comment]
There is not an issue tracking this item. This is not core SDK functionality, so this would be a feature request. Please file a request here: https://github.com/aws/dotnet
