### ISSUE TITLE
If there is a parenthesis in the key property value in PutObjectRequest or GetObjectRequest, the SDK returns an error saying "The request signature we calculated does not match the signature you provided. Check your key and signing method"

### ISSUE THREAD

**Issue by rishabh-jha** [aws/aws-sdk-net#1099]
If there is a parenthesis in the key property value in PutObjectRequest or GetObjectRequest, the SDK returns an error saying "The request signature we calculated does not match the signature you provided. Check your key and signing method". I'm using AWSSDK.S3 3.3.25 and AWSSDK.Core 3.3.27.2

I could not find a way to instantiate the AmazonS3Client using bearer token directly, which I can generate using an API Key, and avoid HMAC Keys, to basically skip the hashed payload, which seems to be causing the signature mismatch, as the payload hash is passed in the x-amz-content-sha256 header if HMAC keys are used.

## Expected Behavior
The put and get request should process without an error when the object key has parenthesis. 

## Current Behavior
If there is a parenthesis in the key property value in PutObjectRequest or GetObjectRequest, the SDK returns an error saying "The request signature we calculated does not match the signature you provided. Check your key and signing method"

## Possible Solution
It seems that the AWS S3 sdk uses HMAC access key name and access id to connect to S3, and the payload hash gets passed in the request in the x-amz-content-sha256 header, and that seems to be causing the signature mismatch, when there are certain special characters in the object key, in my case, parenthesis, which is considered as a safe character to be used in the object key. 

I can upload the same document without any issues, when I connect to the IBM cloud object storage  using an HTTP Client, and pass the IAM/bearer token in the Authorization header. 

I could not find a way to pass the bearer token in the AWS.S3 SDK, and avoid HMAC Keys, to basically skip the hashed payload, as mentioned here in the IBM COS documentation - 
https://console.bluemix.net/docs/services/cloud-object-storage/api-reference/api-reference-objects.html#object-operations

## Steps to Reproduce (for bugs)
Connect to IBM Cloud Object storage using AWS S3 SDK, and try to use the PutObjectRequest  or GetObjectRequest methods, with an object key having parenthesis.

## Context
I'm connecting to IBM Cloud object storage using the s3 sdk, and it works fine for general scenarios, but when there is a parenthesis in the key property value in PutObjectRequest or GetObjectRequest, the SDK returns an error saying "The request signature we calculated does not match the signature you provided. Check your key and signing method".

I can upload the same document without any issues when I connect to the IBM cloud object storage  using an HTTP Client, and pass the IAM/bearer token in the Authorization header. 
I could not find a way to pass the bearer token in the AWS.S3 SDK, and avoid HMAC Keys, to basically skip the hashed payload, as mentioned here in the IBM COS documentation - 
https://console.bluemix.net/docs/services/cloud-object-storage/api-reference/api-reference-objects.html#object-operations

## Your Environment

* Version used: AWSSDK.S3 3.3.25, AWSSDK.Core 3.3.27.2
* Service assembly and version used: 
* Operating System and version: Windows 10 
* Visual Studio version: VS 2017
* Targeted .NET platform: .NET Standard 2.0

**Comment by costleya** [comment]
I was able to use the SDK to put and get objects to Amazon S3 using keys that contained parenthesis. So if I am reading the description, this only happens when you are using the SDK to interact with IBM's cloud services? If so, this is not a supported use case from the perspective of Amazon Web Services.

**Comment by rishabh-jha** [comment]
Yes, this is happening when I'm using the SDK to interact with IBM's COS service. 
Is there any way to use a bearer token to instantiate the AmazonS3Client? Otherwise, how can we skip passing/disable the "x-amz-content-sha256" header in the request?

**Comment by romiljnsmile** [comment]
I am facing same problem with Filebase (S3 comaptible).
