### ISSUE TITLE
404 returned on any non-Home Controllers after deployment

### ISSUE THREAD

**Issue by Neuroforge** [aws/aws-sdk-net#1102]
## Expected Behavior
Deploying to Elastic Beanstalk via  AWS via Visual Studio 2017 should make the application available at each controller that is defined.

## Current Behavior
I am able to access pages from the Home controller, but all other controllers return 404.

## Steps to Reproduce (for bugs)
Unsure what aspect is causing the issue.

## Context
I am trying to deploy, as usual, to AWS Elastic Beanstalk.

## Your Environment
AWSSDK 3.3.25 and AWSSDK 3.3.27.3

Localhost is running on Windows10 and works fine.

Configuration: IIS 10.0 running on 64bit Windows Server 2016/1.2.0
EC2 instance type: t1.micro
EC2 image ID: ami-19e8f179
Have you attached logs?: Yes

Visual Studio 2017

.NET Core 2.0 and .NET Core 2.1

## .NET Core Info

* .NET Core version used for development: 
.NET Core 2.0 and .NET Core 2.1

* .NET Core version installed in the environment where application runs: : 
.NET Core 2.0 and .NET Core 2.1

**dotnet --info Output**

.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-preview2-008533
 Commit:    996eb6c92c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-preview2-008533\

Host (useful for support):
  Version: 2.1.1
  Commit:  6985b9f684

.NET Core SDKs installed:
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.1.102 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.300-preview2-008533 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview2-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview2-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview2-26406-04 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
Hi @Neuroforge, I see that you created three issues for this. I'm going to close this one as a duplicate, and we'll try to help you out on the one that remains.
