### ISSUE TITLE
[request] Let GetOpenIdTokenForDeveloperIdentityAsync can be called without logins for authed account

### ISSUE THREAD

**Issue by Thaina** [aws/aws-sdk-net#1112]
When the client side create their own identity with access token like facebook to call lambda. We would get the cognito identityID from client to our server. And then we want to set that ID to have developer identity along with other federated identity, unfortunately `GetOpenIdTokenForDeveloperIdentityAsync` is not be able to link the id with custom token anymore without the access token from client to set in the `Logins` field

`GetOpenIdTokenForDeveloperIdentityAsync` is a function that only able to be called by admin, so it should have privilege to set any account to link with any developer identities

## Expected Behavior
- Get any identityID that generated from facebook access token
- calling `GetOpenIdTokenForDeveloperIdentityAsync` with that identityID along with customID but without facebook access token
- Get the same ID and that ID was linked to customID

## Current Behavior
Error "Logins don't match"

## Possible Solution
If it would be breaking change, maybe we could have another method that would directly set the developer identities to the specific identityID directly, `GetIdForDeveloperIdentityAsync` for example

ps.

The [js sdk document](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentity.html#getOpenIdTokenForDeveloperIdentity-property) was state that

> When you want to associate a new login with an existing authenticated/unauthenticated identity, you can do so by providing the existing IdentityId. This API will create the identity in the specified IdentityPoolId.

Without mentioning anything about providing existing access token. It should just be linked without error about `Logins don't match`

**Comment by klaytaybai** [comment]
Hi @Thaina, can you please confirm that you are using the .NET SDK and not the JavaScript SDK?

**Comment by Thaina** [comment]
@klaytaybai I report this because I was happen to see this in C#. But I actually use both

**Comment by klaytaybai** [comment]
Linking the JS issue for more content: aws/aws-sdk-js#2327
