### ISSUE TITLE
RegionEndpoint has incorrect display names for several regions

### ISSUE THREAD

**Issue by chrismgunn** [aws/aws-sdk-net#1122]
USEast1 and all of the EU regions have incorrect display names which prevents filtering by the location attribute when querying for pricing data.  The location attribute is populated with the display name of the region.

## Expected Behavior
The DisplayName property should return the following values:
* RegionEndpoint.EUWest1.DisplayName should return "EU (Ireland)"
* RegionEndpoint.EUWest2.DisplayName should return "EU (London)"
* RegionEndpoint.EUWest3.DisplayName should return "EU (Paris)"
* RegionEndpoint.EUCentral1.DisplayName should return "EU (Frankfurt)"
* RegionEndpoint.USEast1.DisplayName should return "US East (N. Virginia)"

These values are in the region pickers through out the AWS site.  You can look at the region picker on the [EC2 Pricing Page](https://aws.amazon.com/ec2/pricing/on-demand/) for the expected values.

## Current Behavior
The DisplayName property currrently return the following values:
* RegionEndpoint.EUWest1.DisplayName should return "EU West (Ireland)"
* RegionEndpoint.EUWest2.DisplayName should return "EU West (London)"
* RegionEndpoint.EUWest3.DisplayName should return "EU West (Paris)"
* RegionEndpoint.EUCentral1.DisplayName should return "EU Central (Frankfurt)"
* RegionEndpoint.USEast1.DisplayName should return "US East (Virginia)"

## Steps to Reproduce (for bugs)
```c#
var client = new AmazonPricingClient("YOUR_KEY", "YOUR_SECRET", RegionEndpoint.USEast1);

foreach (var region in RegionEndpoint.EnumerableAllRegions)
{
	var resp = client.GetProducts(new GetProductsRequest()
	{
		ServiceCode = "AmazonEC2",
		Filters = new List<Amazon.Pricing.Model.Filter>()
		{
			new Amazon.Pricing.Model.Filter(){Field = "location", Type = FilterType.TERM_MATCH, Value = region.DisplayName}
		}
	});

	//any region that does not have values in the price has the wrong display name.  Exceptions are the China and US Gov Cloud regions which appear to be tied to specific account types.
	Console.WriteLine($"({region.SystemName}) {region.DisplayName} : {resp.PriceList.Count}");
}
```

## Context
I am trying to retrieve the pricing information for specific regions.  While the sample does not show it, my code is adding additional filters to the request.

## Your Environment
* AWSSDK.Core version 3.3.29.7
* AWSSDK.Pricing version 3.3.0.32
* Targeted .NET platform: .NET Framework 4.6.2

**Comment by sstevenkang** [comment]
The display name for `RegionEndpoint` is not meant to be used by  `AmazonPricingClient`.  Also, it would be breaking change to make this change.

**Comment by chrismgunn** [comment]
When you look at the [Bulk Query API documentation](https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/using-ppslong.html) you need to specify the ServiceCode(i.e. "AmazonEC2") to get a list of region specific offer files that include the RegionEndpoint.SystemName value(i.e. "us-west-1").  I am looking for similar functionality in the Query API but the only thing that I could uncover was creating a filter on the "location" attribute which contains the equivalent of the RegionEndpoint.DisplayName property.  For all but 5 regions the RegionEndpoint.DisplayName works but for the remaining it looks like that value was changed at one point.  If you look at the region drop lists for AWS they all contain the new values that I described in my original post.

If changing the DisplayName value (i.e "US East (N. Virginia)") is a breaking change, can one of the following changes be made to allow for filtering based on RegionEndpoint.SystemName:

#### Create PricingLocation class
Create a class that behaves similar to the RegionEndpoint.GetBySystemName() function in which you can supply the SystemName (i.e. "eu-west-1") and get back an object that contains the appropriate DisplayName (i.e. "EU (Ireland)") that can used as a filter on the "location" attribute.

#### Add Region property to the GetProductsRequest object
Add an optional Region property which expects the SystemName (i.e. "eu-west-1") and is used to filter the pricing data for a specific region.  This would make the Query API behave in a similar manner to the bulk API.  If no value is specified then no region filtering is applied.

#### Add region attribute to product.attributes collection
Add a region attribute that contains the SystemName (i.e. "eu-west-1") so that it can be used to filter by the immutable SystemName instead of the DisplayName.

Right now I am using the following function to clean up the names:
```c#
private string FixDisplayName(string displayName)
{
	switch (displayName)
	{
		case "EU West (Ireland)" : return "EU (Ireland)";
		case "EU West (London)" : return "EU (London)";
		case "EU West (Paris)" : return "EU (Paris)";
		case "EU Central (Frankfurt)" : return "EU (Frankfurt)";
		case "US East (Virginia)" : return "US East (N. Virginia)";
		default: return displayName;
	}
}
```
This gets me past the issue but if the names change again in the future the only way that I will know is when my queries do not return any values.
