### ISSUE TITLE
ByteRange.End as negative should result in empty

### ISSUE THREAD

**Issue by Thaina** [aws/aws-sdk-net#1124]
https://github.com/aws/aws-sdk-net/blob/fb85f9ad8f6e27dfbfd9f8b608a1bcd2401f9540/sdk/src/Services/S3/Custom/Model/ByteRange.cs#L74-L87

Should be

```C#
 return string.Format(CultureInfo.InvariantCulture, "bytes={0}-{1}", this.Start, this.End >= 0 ? this.End.ToString() : ""); 
```

So it would be returned as `"bytes={X}-"` which would means start to end of file. It was mentioned here https://stackoverflow.com/a/42116971/1513380

**Comment by klaytaybai** [comment]
Hi @Thaina, I think you should be able to successfully use the string constructor to the same effect:
`                ByteRange = new ByteRange("bytes=-{X}")
`

[ByteRange tests](https://github.com/aws/aws-sdk-net/blob/b50da18c15202f8135b8a66a95cd3ac695256220/sdk/test/Services/S3/IntegrationTests/GetObjectTests.cs)

Please let us know if this doesn't work out for you.

**Comment by Thaina** [comment]
@klaytaybai I already know about that but I request specifically that we should be able to achieve this effect with any constructor. Especially it far more easier to just specified the `start` as a number and don't need to remember the syntax that it must be `bytes=`. Really, that syntax should be internal and shouldn't force us to know about it from the API perspective

Also the constructor should have default value for `end` as `-1`

```C#
public ByteRange(long start,long end = -1)

// so we could

var range = new ByteRange(x); // x to end
```

**Comment by klaytaybai** [comment]
@Thaina, I agree that what you just proposed is cleaner.  I'll label this as a feature request instead.  I cannot make any guarantees at this time as to when or if this change will happen, so in the meantime please either use the existing string constructor or add the following class to your solution and use it instead:

>     public class MyByteRange : ByteRange
>     {
>         public MyByteRange(string byteRangeValue) : base(byteRangeValue) {}
> 
>         public MyByteRange(long start, long end) : base(start, end) {}
> 
>         public MyByteRange(long start) : base(string.Format(CultureInfo.InvariantCulture, "bytes={0}-", start)) {}
>     }

**Comment by Thaina** [comment]
@klaytaybai Did this was done or rejected?
