### ISSUE TITLE
Using HTTP with Istio (envoy proxy) results in 400 bad request

### ISSUE THREAD

**Issue by emmekappa** [aws/aws-sdk-net#1125]
I'm deploying a .NET Core application inside a Kubernetes cluster which also has Istio installed.

I'm using both DynamoDB and S3 clients and I switched to HTTP endpoints (with `UseHttp = true`) in order to have the requests automatically traced by Jaeger.

What's is happening is that every requests results in 400 bad request with the following exception message: `The request signature we calculated does not match the signature you provided. Check your key and signing method.`

**Comment by emmekappa** [comment]
For the record, this article describe my issue and a workaround implemented for the Go SDK https://blog.aspenmesh.io/blog/2018/01/distributed-tracing-with-istio-in-aws/

**Comment by klaytaybai** [comment]
Hi @emmekappa, we are not currently providing support for trouble integrating with third parties.  It sounds like this is the case with this issue.  Please correct me if you think it is a bug in the SDK.

Presigned urls may help you.

**Comment by emmekappa** [comment]
@klaytaybai no, I'm sure it's not a bug of the SDK, I've been able to fix the issue by swapping the `AWS4Signer` avoiding the signature of few headers.

Even though it's not a bug of the SDK I think that it would be handy to have an AWS4Signer ctor overload that allows to specify what HTTP headers should be skipped while signing the request.

Because otherwise the implementation of the AWS4Signer subclass is quite clunky :)

```
    public class AWS4SignerWithoutEnvoyHeaders : AWS4Signer
    {
        private readonly string[] headersToRemove =
        {
            "user-agent",
            "server",
            "x-client-trace-id",
            "x-envoy-downstream-service-cluster",
            "x-envoy-downstream-service-node",
            "x-envoy-external-address",
            "x-envoy-force-trace",
            "x-envoy-internal",
            "x-envoy-original-dst-host",
            "x-forwarded-client-cert",
            "x-forwarded-for",
            "x-forwarded-proto",
            "x-request-id",
            "x-ot-span-context",
            "x-b3-traceid",
            "x-b3-spanid",
            "x-b3-parentspanid",
            "x-b3-sampled",
            "x-b3-flags",
            "b3",
            "x-datadog-trace-id",
            "x-datadog-parent-id",
            "x-datadog-sampling-priority"
        };

        public override void Sign(IRequest request, IClientConfig clientConfig, RequestMetrics metrics,
            string awsAccessKeyId,
            string awsSecretAccessKey)
        {
            var originalHeaders = new Dictionary<string, string>(request.Headers, StringComparer.InvariantCultureIgnoreCase);
            foreach (var headerToRemove in headersToRemove)
                request.Headers.Remove(headerToRemove);
            
            AWS4SigningResult awS4SigningResult =
                SignRequest(request, clientConfig, metrics, awsAccessKeyId, awsSecretAccessKey);
            request.Headers["Authorization"] = awS4SigningResult.ForAuthorizationHeader;

            foreach (var headerToRemove in headersToRemove)
            {
                if (originalHeaders.ContainsKey(headerToRemove))
                    request.Headers[headerToRemove] = originalHeaders[headerToRemove];
            }
        }
    }
```

**Comment by emmekappa** [comment]
Also... `S3Signer` would require a different implementation since I still got 400 while putting objects on S3
