### ISSUE TITLE
activity class in AndroidManifest of unity sdk still being UnityPlayerNativeActivity

### ISSUE THREAD

**Issue by Thaina** [aws/aws-sdk-net#1128]
`UnityPlayerNativeActivity` was deprecated and importing the android manifest into unity 2018 project will cause runtime crash. Please use `UnityPlayerActivity` instead

https://github.com/aws/aws-sdk-net/blob/fb193a0842a4fb1c1ec77f6b7203b576d0dcac2e/buildtools/UnityTools/Plugins/Default/Android/AndroidManifest.xml#L34-L37

**Comment by klaytaybai** [comment]
Thank you for letting us now.
