### ISSUE TITLE
AmazonSecurityTokenServiceClient.AssumeRoleWithSAML or GetSessionTokenAsync fails with exception

### ISSUE THREAD

**Issue by iprion** [aws/aws-sdk-net#1131]
If I create a AmazonSecurityTokenServiceClient, calling AssumeRoleWithSAML fails with an exception:

> Object reference not set to an instance of an object

Same error occurs when calling GetSessionTokenAsync.

Here is a code sample (method was found on the internet and seems to work for the user who wrote it)
```c#
private static async Task<SessionAWSCredentials> GetTemporaryCredentialsAsync()
        {
            using (var stsClient = new AmazonSecurityTokenServiceClient())
            {
                var getSessionTokenRequest = new GetSessionTokenRequest
                {
                    DurationSeconds = 7200 // seconds
                };

                GetSessionTokenResponse sessionTokenResponse =
                              await stsClient.GetSessionTokenAsync(getSessionTokenRequest);

                Credentials credentials = sessionTokenResponse.Credentials;

                var sessionCredentials =
                    new SessionAWSCredentials(credentials.AccessKeyId,
                                              credentials.SecretAccessKey,
                                              credentials.SessionToken);
                return sessionCredentials;
            }
        }
```

In the debug output I see a lot of exception thrown
Exception thrown: 'System.InvalidOperationException' in AWSSDK.Core.dll
Exception thrown: 'System.IO.DirectoryNotFoundException' in mscorlib.dll
Exception thrown: 'System.IO.DirectoryNotFoundException' in mscorlib.dll
Exception thrown: 'Amazon.Runtime.AmazonClientException' in AWSSDK.Core.dll
Exception thrown: 'System.InvalidOperationException' in AWSSDK.Core.dll
Exception thrown: 'System.InvalidOperationException' in AWSSDK.Core.dll
Exception thrown: 'System.InvalidOperationException' in AWSSDK.Core.dll
Exception thrown: 'System.IO.DirectoryNotFoundException' in mscorlib.dll
Exception thrown: 'System.IO.DirectoryNotFoundException' in mscorlib.dll
Exception thrown: 'System.InvalidOperationException' in AWSSDK.Core.dll
Exception thrown: 'System.IO.DirectoryNotFoundException' in mscorlib.dll
Exception thrown: 'System.IO.DirectoryNotFoundException' in mscorlib.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.IO.IOException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.IO.IOException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.NullReferenceException' in AWSSDK.Core.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.IO.IOException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.NullReferenceException' in AWSSDK.Core.dll
Exception thrown: 'System.NullReferenceException' in AWSSDK.Core.dll
Exception thrown: 'System.NullReferenceException' in AWSSDK.Core.dll

Am I missing something ? Other AWS Api and classes seems to work fine (AmazonS3Client, TransferUtility.DownloadDirectory ...)

## Your Environment

* AWSSDK.Core version used: 3.3.29.12
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 2017
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 4.5
* .NET Core version installed in the environment where application runs: 4.5
* Output of `dotnet --info`: 
.NET Core SDK (reflecting any global.json):
 Version:   2.1.500
 Commit:    b68b931422

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.500\

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.500 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.
App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
Hi @iprion, I'm sorry to hear you are having difficulties.  I was not able to reproduce this issue on a Mac.  I could try at a later time to reproduce on a Windows Server 2008 instance.

Are the errors you listed related to AssumeRoleWithSAML or GetSessionTokenAsync?

**Comment by pbenitez** [comment]
I'm seeing the same error on Windows Server 2012 R2.

**Comment by savanbthakkar** [comment]
Hi @pbenitez , I have the exact same problem. Did you find the solution?

**Comment by xbaha** [comment]
I am receiving this error too:
Exception thrown: 'System.InvalidOperationException' in AWSSDK.Core.dll
too many of them I can't count! Has anyone found a solution???

**Comment by savanbthakkar** [comment]
> I am receiving this error too:
> Exception thrown: 'System.InvalidOperationException' in AWSSDK.Core.dll
> too many of them I can't count! Has anyone found a solution???

My issue turned out to be a misconfigured role in AWS.
@xbaha , Can you post the full exception including InnerExceptions if any?

**Comment by xbaha** [comment]
There was no exception thrown that stopped my app, it's just in my debug output window and too many of them, my app runs normal, but this happened after I installed AWSSimpleEmail.
