### ISSUE TITLE
S3 Multipart copy with SSE-KMS encryption for destination doesn't work

### ISSUE THREAD

**Issue by fixer-m** [aws/aws-sdk-net#1132]
Multipart copy with SSE-KMS encryption for destination doesn't work. 
Method **S3Client.CopyPart(copyRequest)** returns an error:
> Server Side Encryption with AWS KMS managed key requires HTTP header x-amz-server-side-encryption : aws:kms 

Apparently produced request missing header **x-amz-server-side-encryption** which is required (nevertheless x-amz-server-side-encryption-**aws-kms-key-id** is there). Usual (singlepart) copy request have this header and works fine.

Looking at sources I've found that **CopyPartRequestMarshaller.cs** just missing this code (taken from single-part copy **CopyObjectRequestMarshaller.cs**):
```
if (copyObjectRequest.IsSetServerSideEncryptionMethod())
   request.Headers.Add(HeaderKeys.XAmzServerSideEncryptionHeader, S3Transforms.ToStringValue(copyObjectRequest.ServerSideEncryptionMethod));
```
So adding this should resolve the issue.

## Environment
* AWSSDK.Core 3.3.29.12
* AWSSDK.S3 3.3.30
* Targeted .NET platform: NET Framework 4.6.1

## Code sample
Here is my code sample:
```
// <... call S3Client.InitiateMultipartUpload ...>
// ...
for (int i = 1; bytePosition < fileSize; i++)
{
    CopyPartRequest copyRequest = new CopyPartRequest
    {
		DestinationBucket = destinationBucket,
		DestinationKey = destinationKey,
		SourceBucket = sourceBucket,
		SourceKey = sourceKey,
		UploadId = initResponse.UploadId,
		FirstByte = bytePosition,
		LastByte = bytePosition + partSize - 1 >= fileSize ? fileSize - 1 : bytePosition + partSize - 1,
		PartNumber = i,
		ServerSideEncryptionMethod = ServerSideEncryptionMethod.AWSKMS,
		ServerSideEncryptionKeyManagementServiceKeyId = "aws-arn-key-id" 
    };

    var copyPartResponse = S3Client.CopyPart(copyRequest); // throws error
    copyResponses.Add(copyPartResponse);

    bytePosition += partSize;
}
```
Partitional copy covered in details there:  https://docs.aws.amazon.com/AmazonS3/latest/dev/CopyingObjctsUsingLLNetMPUapi.html

**Comment by fixer-m** [comment]
I have created a pull-request to fix this issue. 
Any news on this?

**Comment by fixer-m** [comment]
Thanks for merging my PR!
Now it **does** send this header, but it throws another exception: 
> Amazon.S3.AmazonS3Exception: 'x-amz-server-side-encryption header is not supported for this operation

Turns out that to set destination encryption you have to put encryption details (method + key/keyId) in **InitiateMultipartUploadRequest** only (which you have to call prior to **CopyPartRequest** calls), not in the **CopyPartRequest**s itself. What confused me - is that both of them have the same fields to set destination encryption info: 
- ServerSideEncryptionCustomerMethod
- ServerSideEncryptionCustomerProvidedKey
- ServerSideEncryptionMethod
- ServerSideEncryptionKeyManagementServiceKeyId

Yep, you don't have to send encryption info within **CopyPartRequest**, because - apparently - it doesn't work this way. But why **CopyPartRequest** have these fields if they are useless? 
What also confuses me - **Marshall** method for **CopyPartRequest** (which builds http request itself) has logic to add-if-present all encryption-related headers and only one of them was missing before my PR was merged. But this logic also useless since encryption info would be taken from **InitiateMultipartUploadRequest**. 

So this is kinda design issue, not a bug. 
I don't think that my commit should be reverted, since it doesn't change anything but error message. And actually this message is more helpful than previous one - it helps to understand that _something doesn't supported_ and you do it _wrong way_. 

To actually fix this behavior I can suggest this: 
I. Either - Remove encryption info fields from **CopyPartRequest** and remove adding corresponding headers in **Marshall** method. 
II. Either - Leave fields in **CopyPartRequest** as is, but change **Marshall** method to check if these fields have values. If so - then throw ArgumentException with helpful text (something like "it will not work, you have to set it via InitiateMultipartUploadRequest"). This way is more user friendly.

**Comment by matteo-prosperi** [comment]
@fixer-m, if I understand correctly your latest message, you are now able to successfully perform the multipart copy as long as you put encryption details in InitiateMultipartUploadRequest only. Can you confirm?
Thanks

**Comment by fixer-m** [comment]
@matteo-prosperi, yes, that's correct. 
Bug will appear if you put encryption info to **CopyPartRequests**.
