### ISSUE TITLE
Installing the AWS Toolkit for Visual Studio 2017 Professional causes it to crash immediately

### ISSUE THREAD

**Issue by baileyfriend** [aws/aws-sdk-net#1146]
Visual studio was working fine until I got an update yesterday. After the update, Visual Studio would close on it's own about 5 seconds after initializing the app. I uninstalled and reinstalled the app and found that everything was working fine until I went to deploy to Beanstalk this morning. I noticed that I didn't have the AWS Toolkit for Visual Studio 2017 so I installed it. Once I installed this and restarted my machine, Visual Studio displayed the same behavior (immediately closing when opened). After some troubleshooting I found that the error was caused by a malformed credential in my credentials file. 

## Recommendations
Fail more gracefully. This failure was so nonspecific that I spent a good chunk of time troubleshooting Visual Studio and my operating system because I didn't have a good way of knowing what was causing the issue. There should be some display to the user, and this should NOT crash all of Visual Studio. 

## Expected Behavior
When I open Visual Studio it should stay open.

## Current Behavior
When I open Visual Studio it automatically closes after about 5 seconds or so.

## Steps to Reproduce (for bugs)
Explained above.

## Context
This has prevented me from working on a portion of my project, and has disabled me from deploying to Beanstalk.

## Your Environment
Visual Studio Professional 2017: 15.9.4
AWS Toolkit for Visual Studio 2017: 1.14.5.0
Windows 10 Version	10.0.17134 Build 17134
OS Name	Microsoft Windows 10 Enterprise

**Comment by awschristou** [comment]
Thank you for reporting this @baileyfriend - when you mention malformed credential, do you mean that you had a non-valid key & secret pair, the file format was incorrect (for example, a profile was missing a square bracket), or something else?

**Comment by rrvenki** [comment]
I'm trying to install "AWS Toolkit for Visual Studio 2017 community 15.9.4.  Everytime i install via  standalone MSI installer I get an error stating that the Certificate in the package is invalid.  The Nuget version installs only to the solution and that works fine.

**Comment by rrvenki** [comment]
>           I'm trying to install "AWS Toolkit for Visual Studio 2017 community 15.9.4.  Everytime i install via  standalone MSI installer I get an error stating that the Certificate in the package is invalid.  The Nuget version installs only to the solution and that works fine.

I got it (AWS Toolkit for Visual Studio 2017 community 15.9.4) working fine.  (1) Logged into PC as local admin, (2) Used mobile internet instead of office internet.  The package got installed successfully.
