### ISSUE TITLE
IotData: _subscribe_ to topic?

### ISSUE THREAD

**Issue by jrr** [aws/aws-sdk-net#1147]
I can use the `IotDataClient` to _publish_ a message to a topic, but I'm not sure whether it's possible to _subscribe_ to a topic.

https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/IotData/TIotDataClient.html

If it's not, consider this a feature request!

## Expected Behavior
Using the .NET SDK's IotDataClient, I can subscribe to a topic and view messages as they come through.

## Current Behavior
There's no obvious way to do this.

## Possible Solution
Use some other MQTT client instead of the Amazon library. (perhaps like this https://github.com/aws-samples/iot-dotnet-publisher-consumer )

## Context
The system I'm building will use MQTT-triggered lambda functions, but for testing/development I'd really like to write command-line tools that can pub/sub.(e.g., a tool that can pretend to be my IoT device and communicate as if it were one)

## Environment / .NET Core Info
* AWSSDK.IotData 3.3.0.64
* Operating System and version: OSX 10.14.2
* .NET Core 3.0.100-preview-009812

**Comment by japerki** [comment]
Cancel any accounts associated with email, fraudulent account and identity theft

**Comment by klaytaybai** [comment]
I'm not aware of any functionality like this from the AWS .NET libraries.  We do seem to support it in other languages.  I believe C, C++, Java, JavaScript, and Python all support subscribing to topics.

**Comment by sstevenkang** [comment]
Hi, AWS SDK for .NET is not a MQTT based client.  I think what you are looking for a completely different AWS IoT SDK for .NET which seems like it doesn't exist yet.  Since this is beyond the scope of AWS SDK for .NET, I will close this feature request here.  I'll let the IoT SDK team know that there's a request for client-side IoT library for .NET.

**Comment by jrr** [comment]
> AWS SDK for .NET is not a MQTT based client.

@sstevenkang how is it able to publish messages, then? 🤔

**Comment by sstevenkang** [comment]
The IoTData service client is a .NET interface over REST API.  See https://docs.aws.amazon.com/iot/latest/apireference/API_Operations_AWS_IoT_Data_Plane.html

Only Publish operation is supported via HTTP.

This seems to be the design of the AWS IoT service. See the developer guide [here](https://docs.aws.amazon.com/iot/latest/developerguide/aws-iot-how-it-works.html) and the HTTP/MQTT protocols section [here](https://docs.aws.amazon.com/iot/latest/developerguide/protocols.html).
