### ISSUE TITLE
Static RegionEndpoint methods are not thread-safe

### ISSUE THREAD

**Issue by philipflesher** [aws/aws-sdk-net#1150]
The static method `RegionEndpoint.GetBySystemName` has a race condition. In the event that two threads make it past the point of checking the internal hash for a new region (e.g., `eu-north-1` currently falls into this category), they'll both attempt to add a new synthetic region to the hash. One of them will throw the exception associated with attempting to enter a duplicate value in the hash.

Other accessors that might manipulate the hash are equally suspect - e.g., the `EnumerableAllRegions` could suffer from the same flaw.

We've seen this issue multiple times over the past few years, each time due to a new region that's been created but not yet added as a constant value in the `RegionEndpoint` class. Since these are static accessors that are, supposedly, just getters, it would make sense for them to be thread-safe. There are various possible solutions to the problem, such as adding a lock/monitor or using a thread-safe dictionary instead of the current hash.

**Comment by philipflesher** [comment]
Note that https://github.com/aws/aws-sdk-net/issues/986 may be considered duplicative.

**Comment by klaytaybai** [comment]
Hi @philipflesher, thank you for refreshing awareness to this issue and providing some additional useful information.  I am going to label this as a duplicate and close out this one, but I'll bump up the priority of the old issue a bit.
