### ISSUE TITLE
Renewed Unity support now that Unity's version of Mono has been updated? (2018+)

### ISSUE THREAD

**Issue by prodigga** [aws/aws-sdk-net#1152]
Hi there

Now that Unity's version of mono is a little more modern, I was wondering if it would be much of a stretch to implement support for it (2018+). There is a lot of great services that are not available to Unity, the Unity AWS SDK is fairly limited. 

I tried my hand at adding support for Unity - it seems like the biggest issue is that System.Configuration is not available in Mono, and apart from that not much else.

**Comment by prodigga** [comment]
Unity has recently partnered with Google to provide multiplayer backend support. I feel Amazon has all they need to remaining competitive with Google's offerings if only the SDK worked properly in Unity.

**Comment by klaytaybai** [comment]
Hi @prodigga, thank you for voicing your interest in this and doing some investigation.  Customer interest helps drive our decisions.  We have a policy of not discussing possible features or major work, so we can’t comment on the status at this time.
