### ISSUE TITLE
EC2 Metadata not working in Windows 2016 Instances

### ISSUE THREAD

**Issue by vickyrathee** [aws/aws-sdk-net#1154]
The `Amazon.Util.EC2InstanceMetadata.InstanceId` and all other Metadata commands not working in windows 2016 instances. No exception thrown, it just return null.

![image](https://user-images.githubusercontent.com/6106479/50545383-95a79300-0c38-11e9-95be-19ce69d3f257.png)

**Neither the webservice** [mentioned in documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html) `http://169.254.169.254/latest/meta-data/`

![image](https://user-images.githubusercontent.com/6106479/50545389-b7087f00-0c38-11e9-8745-0068aa296fdd.png)

While both works in my Windows 2008 instance in same VPC and region

**Comment by klaytaybai** [comment]
Hi @vickyrathee, can you please try taking a look at the following documentation that helps to explain the differences between the Windows 2016 instances and earlier versions and let me know if it helps you?

[Windows 2016 -- EC2Launch](https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ec2launch.html)

[< Windows 2016 -- EC2Config](https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ec2config-service.html)

**Comment by vickyrathee** [comment]
Thanks @klaytaybai 

I was able to map the route by `Shutdown with sysprep` and it's working now.

But, 2 things for feedback - 

1. I see that the launch config was aware that it couldn't get the metadata as per logs. So, your team can build a logic to refresh the route automatically on any error and your system is aware of that. Isn't that how it should work?


![image](https://user-images.githubusercontent.com/6106479/50570203-b4776800-0da5-11e9-8b6a-15b55f08b4bc.png)

2. It's understandable that a browser can't show any exception or much details, when it can't connect to a IP address and will just show "Can't display the page" as IE. But your team can add an exception in SDK to provide more details instead just returning null. Something like `RouteException - Can't connect to metdata ip, please check the routing`

Thanks for your help 👍
