### ISSUE TITLE
Visual Studio "Upload to AWS Lambda" System.OutOfMemoryException when packaging

### ISSUE THREAD

**Issue by PaulDMendoza** [aws/aws-sdk-net#1155]
I get this error in Visual Studio when trying to publish.

![image](https://user-images.githubusercontent.com/1039795/50552550-96492500-0c4a-11e9-8225-c7ac4063d820.png)

When I package it using the command line:

![image](https://user-images.githubusercontent.com/1039795/50552560-a52fd780-0c4a-11e9-82cf-7fbf2f99602d.png)

it works fine

![image](https://user-images.githubusercontent.com/1039795/50552566-b842a780-0c4a-11e9-82f2-e05db35c4c97.png)

## Expected Behavior
It should finish publishing to AWS Lambda without dieing. 

## Possible Solution
Not sure

## Steps to Reproduce (for bugs)
Not sure how I'm getting this.

## Your Environment
The packaged version is only 13 MB in size. Unzipped it is around 30 MB.

* Operating System and version: Windows 10
* Visual Studio version: 15.8.4
* Visual Studio AWS Toolkit version: 1.14.5.0 installed on 11/20/2018
* Targeted .NET platform: Core 2.1.5

## .NET Core Info

* .NET Core version used for development: 2.1.5
* Output of `dotnet --info`: 
![image](https://user-images.githubusercontent.com/1039795/50552584-29825a80-0c4b-11e9-8398-8b0ee2851c5f.png)

**Comment by PaulDMendoza** [comment]
Nevermind. Restarting Visual Studio seemed to fix it. 

Visual Studio was using 2.2 GB of RAM before the restart. After the restart it is using 1.8GB of RAM so there must be enough now for it to complete the packaging task.

**Comment by klaytaybai** [comment]
Thanks for the update.
