### ISSUE TITLE
Unable to select Fargate as a Launch Type for Canada Central region

### ISSUE THREAD

**Issue by ctoph13** [aws/aws-sdk-net#1156]
I am unable to select Fargate as a Launch Type when I try to publish a container to AWS by right clicking my project and choosing Publish Container to AWS.

## Expected Behavior
I am expecting to be able to choose Fargate as a Launch Type when I am using the Canada Central region.

## Current Behavior
When I right click my project > Publish Container to AWS, choose my settings for profile, region (Canada central), Docker Image Build and Deployment Target of "Service on an ECS Cluster", and click next, I am unable to choose Fargate as a Launch Type in the dropdown menu. There is a message below the dropdown saying "Fargate is currently not supported in this region. Farget is supported in the regions: us-east-1, us-east-2, us-west-2, eu-west-1, eu-central-1, ap-southeast-1, ap-northeast-1, ap-southeast-2". However Canada is a supported region as far as I can tell and I am able to use Fargate if I go through the AWS website UI.

## Possible Solution
I'm thinking since Canada is only recently supported, and the last update was in November, that there hasn't been an update to allow Canada region profiles to select the Fargate option from the dropdown.

## Steps to Reproduce (for bugs)
Steps are written in the current behavior section.

## Context
I want to be able to publish and update my container with a Fargate launch type from visual studio as opposed to the AWS website UI.

## Your Environment
* Operating System and version: Windows 10, 1803
* Visual Studio version: VS 2017, v15.8.1
* Targeted .NET platform: .NET Core 2.2
* AWS Toolkit Version: 1.14.5.0

## .NET Core Info
.NET Core project but the info isn't relevant to this issue.

**Comment by klaytaybai** [comment]
Hi @ctoph13, thank you for alerting us to this.  I created an internal ticket to the Visual Studio Toolkit team.

**Comment by abrooksv** [comment]
Endpoints data is pulled on start up, have you restarted your IDE recently?

**Comment by normj** [comment]
@abrooksv There is a different file that governs which regions support Fargate that we need to update. I took a look and it is out of date. We need to update the support regions and publish the file.

**Comment by normj** [comment]
If you restart Visual Studio now you will see Canada is a valid region to deploy with Fargate.
