### ISSUE TITLE
SDK should support AWS_SHARED_CREDENTIALS_FILE environment variable

### ISSUE THREAD

**Issue by normj** [aws/aws-sdk-net#1158]
The SDK should support the `AWS_SHARED_CREDENTIALS_FILE` environment variable like the AWS CLI does. 

This is useful for for applications deployed in non AWS environments that want to inject the credential profile for an IIS application without changing any code or settings in the application. Read the following issue for an example https://github.com/aws/aws-sdk-net/issues/1139

**Comment by casey-robertson** [comment]
Also useful (I think) for Kubernetes use cases where we'd like to mount or read the credentials from env var or secret mount.  https://github.com/zalando-incubator/kube-aws-iam-controller/blob/master/docs/sdk-configuration.md.  Note the absence of the .NET SDK.

**Comment by armitagemderivitec** [comment]
+1

**Comment by therohin** [comment]
+1

**Comment by therohin** [comment]
@normj , We are running our .Net application on IIS running on an EC2 instance.
But this is still required there, because we need to specify an **assume role** ARN inside the credential file's profile.
I do not find any other way of doing it than specifying the path in the AWSProfilesLocation appSettings, which I want to avoid.

**Comment by gunniwho** [comment]
I think this could be as simple as modifying this line https://github.com/aws/aws-sdk-net/blob/a7c91a25e5b78376d1bf91c13f55383518b4a57b/sdk/src/Core/Amazon.Runtime/Credentials/FallbackCredentialsFactory.cs#L32 like this

`private static readonly CredentialProfileStoreChain credentialProfileChain = new CredentialProfileStoreChain(Environment.GetEnvironmentVariable("AWS_SHARED_CREDENTIALS_FILE"));`

**Comment by nichols-green** [comment]
+1

**Comment by peterrsongg** [comment]
This has been addressed in the SDK release: 3.7.442.0 (2022-12-16 00:44 UTC) and Core 3.7.103.0
