### ISSUE TITLE
ConfigurationOptionSetting

### ISSUE THREAD

**Issue by sriwantha** [aws/aws-sdk-net#1165]
I am trying to execute following powershell command
Update-EBConfigurationTemplate -ApplicationName "MyTigerApp" -TemplateName "Test2" -Description "Prod Tempate" -OptionSetting Namespace=aws:autoscaling:launchconfiguration,OptionName=InstanceType,Value=t2.large -Force  

propblem
The -OptionSettings is not getting parse properly. 

**I passed yaml input** 
(first save the yaml file with New-EBConfigurationTemplate -ApplicationName "MyTigerApp" -TemplateName "Test" -EnvironmentId "e-rqe9c7jwsg" then use the content)
didn't work. I tried LF/CR characters and then tried still didn't work. 
the YAML input is
EnvironmentConfigurationMetadata:
  Description: DevConfig
Platform:
  PlatformArn: arn:aws:elasticbeanstalk:ap-southeast-2::platform/IIS 10.0 running on 64bit Windows Server 2016/1.2.0
OptionSettings:
  aws:elasticbeanstalk:environment:
    EnvironmentType: SingleInstance
    ServiceRole: aws-elasticbeanstalk-service-role
  aws:autoscaling:launchconfiguration:
    RootVolumeSize: '60'
    IamInstanceProfile: aws-elasticbeanstalk-ec2-role
    InstanceType: t2.large
EnvironmentTier:
  Type: Standard
  Name: WebServer
AWSConfigurationTemplateVersion: 1.1.0.0

**I pass the json input**
still didn't work. 

**I pass a simple input**
it still does not work. 

Expected behavior
There must be a method to pass a large yaml, json content to -optionsetting

Can you add an example, where it shows the json input. 

This is the error I am getting
Update-EBConfigurationTemplate : Cannot bind parameter 'OptionSetting'. Cannot convert the "Namespace=aws:autoscaling:launchconfiguration" 
value of type "System.String" to type "Amazon.ElasticBeanstalk.Model.ConfigurationOptionSetting".
At C:\Users\dev-user\Desktop\test.ps1:5 char:127
+ ... tionSetting Namespace=aws:autoscaling:launchconfiguration,OptionName= ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Update-EBConfigurationTemplate], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Amazon.PowerShell.Cmdlets.EB.UpdateEBConfigurationTemplateCmdlet
[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by steveataws** [comment]
The -OptionSetting parameter is expecting an array of one or more objects, not a formatted string. If you change your code to use a @{} map, you should find it parses as expected:

`Update-EBConfigurationTemplate -ApplicationName "MyTigerApp" -TemplateName "Test2" -Description "Prod Tempate" -OptionSetting @{Namespace="aws:autoscaling:launchconfiguration";OptionName="InstanceType";Value="t2.large"} -Force`
