### ISSUE TITLE
New region eu-north-1 missing from RegionEndpoint.cs

### ISSUE THREAD

**Issue by ckuehl** [aws/aws-sdk-net#1167]
The `eu-north-1` region is missing from `aws-sdk-net/sdk/src/Core/RegionEndpoint/RegionEndpoint.cs`.

**Comment by normj** [comment]
I push out the CR to the rest of the team. Hope to get this out soon.

**Comment by stilettk** [comment]
It seems it have been added in version 3.3.448.1 😊
