### ISSUE TITLE
Authentication with iam username and password

### ISSUE THREAD

**Issue by Gkanda80** [aws/aws-sdk-net#1173]
Currently s3 authentication is only possible with access id and key. Could it be possible to access by accountid, username and password?

**Comment by klaytaybai** [comment]
Hi @Gkanda80, this is not currently supported, and it probably won't be supported--at least in the near future.  Generally we are not allowed to discuss what changes we may or may not make, but it seems safe to say that this won't be changing soon.  It would require modifications in code bases across the organization.  In general, we recommend against using the root account credentials as soon as possible.
https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html

If you are interested in setting up username and password features for end users, you could consider using Cognito:
https://aws.amazon.com/cognito/
https://github.com/aws/aws-sdk-net-extensions-cognito
