### ISSUE TITLE
An item with the same key has already been added. Key: Amazon.DynamoDBv2.DocumentModel.Key

### ISSUE THREAD

**Issue by sidgo28** [aws/aws-sdk-net#1174]
```
var b = db.CreateBatchWrite<T>();
b.AddPutItems(list);
await b.ExecuteAsync(); // ERROR HERE!
```

## Your Environment

* AWSSDK.Core version used: 
    <PackageReference Include="AWSSDK.CognitoIdentity" Version="3.3.2.57" />
    <PackageReference Include="AWSSDK.CognitoIdentityProvider" Version="3.3.11.26" />
    <PackageReference Include="AWSSDK.Core" Version="3.3.29.16" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.3.15.4" />
* Service assembly and version used: 
* Operating System and version: 
Windows 10 v17134
* Visual Studio version: 
VS 2017 15.8
* Targeted .NET platform: 
Xamarin

**Comment by klaytaybai** [comment]
Hi @sidgo28, have you verified that there are no duplicate keys between any items already in DynamoDB and any items in your list, including possible duplicates within the list?
