### ISSUE TITLE
S3 *ObjectAsync throwing MissingMethodException

### ISSUE THREAD

**Issue by mottykohn** [aws/aws-sdk-net#1176]
## Expected Behavior
Async should work just like sync

## Current Behavior
I am using PutObjectAsync and DeleteObjectAsync and it compiles fine but when running it throws {"Method not found: 'System.Threading.Tasks.Task`1<Amazon.S3.Model.DeleteObjectResponse> Amazon.S3.AmazonS3Client.DeleteObjectAsync(Amazon.S3.Model.DeleteObjectRequest, System.Threading.CancellationToken)'."}. PutObject (without Async) works.

## Workaround
Downgrade to version 3.1.10

## Steps to Reproduce (for bugs)
* Create a new AWS S3 sample project.
* Update nuget package to latest version 3.3.31.10
* Fill in bucket name and object name as instructed.
* Change line 153 from client.PutObject to client.PutObjectAsync. (Adjust for async - change method to async etc..).
* Run program.
## Context
My old code doesn't work anymore I will have to change to sync versions
## Your Environment

* AWSSDK.Core version used: v3.3.31.10
* Service assembly and version used: 
* Operating System and version: win 10
* Visual Studio version: 15.9.5
* Targeted .NET platform: 4.5 and 4.7.2

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
Hi @mottykohn, I haven't been able to reproduce this issue.  Most likely it is due to a conflicting DLL.  Try running 'Clean Build', restarting Visual Studio, or other such means of rebuilding and reloading your project.   Thanks.

**Comment by mottykohn** [comment]
As noted above I tried with brand new project. 2 versions of visual studio (2017 and 2019 preview) and still have the problem. My understanding is that every project gets its own fresh copy. Correct me if I'm wrong. @klaytaybai

**Comment by mottykohn** [comment]
@klaytaybai I ran in the immediate window and got slightly different message. Maybe it will help. error CS1061: 'AmazonS3Client' does not contain a definition for 'PutObjectAsync' and no accessible extension method 'PutObjectAsync' accepting a first argument of type 'AmazonS3Client' could be found (are you missing a using directive or an assembly reference?)
Something tells me that there is a mixup on how the parameters are passed.

**Comment by klaytaybai** [comment]
Hi @mottykohn, can you provide example code to show how you are making your call?  Please be sure to not include any confidential data.

The AmazonS3Client shouldn't be a parameter.  It should be the object that has the the PutObjectAsync method: i.e. `client.PutObjectAsync(putObjectRequest)`

**Comment by mottykohn** [comment]
@klaytaybai Here it is. bucketName and keyName have to be filled in.
[S3Sample1.zip](https://github.com/aws/aws-sdk-net/files/2793853/S3Sample1.zip)

**Comment by amacal** [comment]
Today I started getting the same or very similar message:

Method not found: 'System.Threading.Tasks.Task`1<Amazon.S3.Model.PutObjectResponse> Amazon.S3.AmazonS3Client.PutObjectAsync(Amazon.S3.Model.PutObjectRequest, System.Threading.CancellationToken)'.

For me it is related to the machine where I run the code. On my developer computer works as expected, but if I run it on my staging machine it breaks. Once all async methods are replaced with non-async calls it starts working.

The issue is not related for me to compilation. If I copy working code from the development to the "not working" staging machine it does not work.

**Comment by mottykohn** [comment]
Funny I just came here to comment that it's working on a different staging machine, not what I was using, and I see that @amacal  commented 22 seconds ago the same thing.

**Comment by klaytaybai** [comment]
I'm going to close this out due to inactivity.  If either of you are having difficulty with this using newer versions, let us know so we can reopen this.
