### ISSUE TITLE
TargetGroup object does not include Targets

### ISSUE THREAD

**Issue by hoagsie** [aws/aws-sdk-net#1177]
## Expected Behavior

When I call `DescribeTargetGroups`, the object returned should include the targets in the groups.

## Current Behavior

I don't see a `Targets` property in the `ElasticLoadBalancingV2.Model.TargetGroup` object.

## Possible Solution

Include this in the object as the data exists per https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-targetgroup.html#w2ab1c21c10d132c29c11.

## Context

I'm trying to create a recon report that lists any EC2s that are running but not in a load balancer.

## Your Environment

* AWSSDK.Core version used: 3.3.31.2
* Service assembly and version used: AWSSDK.ElasticLoadBalancingV2 ver. 3.3.12.10
* Operating System and version: Windows 10
* Visual Studio version: 2017 Professional
* Targeted .NET platform: 4.7.2 Full

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
Hi @hoagsie, I think it would be clearer if the API behavior was implemented as you expect. 
 Unfortunately that is not currently the case.  However, you can get this information by instead using the [DescribeTargetHealth](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_DescribeTargetHealth.htm) method.  

This is an excerpt from our [samples](https://github.com/aws/aws-sdk-net/blob/b691e46e57a3e24477e6a5fa2e849da44db7002f/docgenerator/AWSSDKDocSamples/ElasticLoadBalancingV2/ElasticLoadBalancingV2.GeneratedSamples.cs) in this repo.  It includes the targets in the request, but these are optional.  If you don't include them in the request, you should get back all your targets.
```
static IAmazonElasticLoadBalancingV2 client = new AmazonElasticLoadBalancingV2Client();


public void ElasticLoadBalancingV2DescribeTargetHealth()
        {
            var response = client.DescribeTargetHealth(new DescribeTargetHealthRequest 
            {
                TargetGroupArn = "arn:aws:elasticloadbalancing:us-west-2:123456789012:targetgroup/my-targets/73e2d6bc24d8a067",
                Targets = new List<TargetDescription> {
                    new TargetDescription {
                        Id = "i-0f76fade",
                        Port = 80
                    }
                }
            });

            List<TargetHealthDescription> targetHealthDescriptions = response.TargetHealthDescriptions;
        }
```

**Comment by hoagsie** [comment]
I was not aware of that behavior. This worked for this case. However, as you mentioned, it would, indeed, be more natural if that property was added to Describe. Further, I would push that it is more consistent and therefore better design as well.

**Comment by klaytaybai** [comment]
I've added your feedback to an outstanding feature request, but I can't make any promises on when, if ever, this will get implemented.  I'm going close out this issue.
