### ISSUE TITLE
CopyObject fails copying object with '%2F' in key

### ISSUE THREAD

**Issue by mwhouser** [aws/aws-sdk-net#1178]
## Current Behavior

When performing  a bucket-to-bucket S3 copy using `AmazonS3Client.CopyObject()`, if the object key includes "%2F", then the object fails to copy with the following exception:

```
Amazon.S3.AmazonS3Exception: The request signature we calculated does not match the signature you provided. Check your key and signing method. --->
Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (403) Forbidden. ---> 
System.Net.WebException: The remote server returned an error: (403) Forbidden.
```

For example, an object key "%2F.txt" will fail to copy.

## Expected Behavior

The file should copy correctly.

## Steps to Reproduce (for bugs)

```csharp
var client = new Amazon.S3.AmazonS3Client("<redacted>", "<redacted>");

var response = client.CopyObject(new Amazon.S3.Model.CopyObjectRequest()
  {
    SourceBucket = "source-bucket",
    SourceKey = "%2F.txt",

    DestinationBucket = "target-bucket",
    DestinationKey = "%2F.txt",
  });
```

## Context

The file fails to copy using the AWS SDK for .NET. It succeeds using the AWS CLI:

```
aws s3 cp s3://source-bucket/%2F.txt s3://target-bucket/%2F.txt
```

## Your Environment

* AWSSDK.Core version used: 3.3.31.2 (straight from Nuget)
* Service assembly and version used: AWSSDK.S3 version 3.3.31.10 (straight from Nuget)
* Operating System and version: Windows 10, Windows Server 2016
* Visual Studio version: Visual Studio 2017
* Targeted .NET platform: 4.6.2, 4.7.2

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
Hi @mwhouser, thank you for reporting this.  I was able to reproduce it.  I'll let you know if we fix it.  I have also asked some people from some of the other AWS SDKs to verify that this isn't an issue for them as well.

**Comment by haus** [comment]
For what it's worth this was introduced in AWSSDK.Core 3.3.29.12. 3.3.29.11 succeeds and 3.3.29.12 throws the S3Exception. Also this appears to impact more than just copy, as `PutObjectAsync` is similarly affected.

**Comment by haus** [comment]
(also I was able to verify that the same request succeeds using the latest version of the java aws sdk)

**Comment by haus** [comment]
@klaytaybai would you be open to a PR to address this?

**Comment by klaytaybai** [comment]
Hi @haus, thanks for the offer, but I don't think we're looking for an external PR for this particular problem right now.  I have an internal code review out to get this fixed up and add some tests around it, but the team is hoping for a longer term solution that would prevent similar bugs in S3 and other services.  It would need to involve the code generators, request marshallers, and more.  I think it would be a bit much effort to ask of a customer.

How badly is this issue affecting you?  I might be able to escalate it more if we know more about the impact severity.

**Comment by haus** [comment]
@klaytaybai it caused us some regressions as we write files with %2F to S3 relatively frequently, so we were forced to roll back to an older version of both awsdk core and secrets manager. We won't be able to update to a newer version until it is resolved.

**Comment by ivan-myob** [comment]
This is still an issue with latest sdk, and blocker for us to upgrade sdk - we have alot of document that were historically created with `%2F`.

**Comment by boblodgett** [comment]
A fix for this issue has been released as of the following versions:
AWSSDK.Core 3.3.103.22
AWSSDK.S3 3.3.104.10
