### ISSUE TITLE
Unity Android: not receiving Async callbacks, when app in background.

### ISSUE THREAD

**Issue by fred4d** [aws/aws-sdk-net#1179]
I am developing a Unity application that performs some tasks in the background (i.e. when the user has navigated away from the app for whatever reason). When the app is in the background, an Android foreground service makes its way back into my Unity C# code, which periodically calls into the AWS Mobile SDK for Unity, specifically DynamoDB interactions.

While the Android app is in the background, these DynamoDB calls (e.g. QueryAsync) never seem to complete (i.e. no async callbacks are executed). To be clear, my Android service runs just fine in the background otherwise, performing additional desired activities in my Unity C# code, besides trying to interact with the database.

**Is there a setting, of which I'm unaware, to allow background database activity, or is there some manual pumping call I can make periodically to 'drain' the callbacks, or . . .?**

## Expected Behavior

I categorize this somewhere between a bug and a change/improvement.  My expectations are that if I operate on the database, either in the foreground or background, the operations should occur.  I'm fine with a configuration setting or a manual pumping method.

## Current Behavior

I think my initial description serves here.

## Possible Solution

From my naive reading of the code, UnityMainThreadDispatcher's ProcessRequests method seems to be most of what I need to call to pump the async calls manually.  I see, however, that there are calls inside it to StartCoroutine, which also will not work, when Unity is otherwise dormant.

## Steps to Reproduce (for bugs)

I don't have a concise snippet.  I've written an Android foreground service that periodically calls into my Unity C# code, when my app (and Unity) is in the background, and tries to exercise the database.

## Context

Much like a mapping app (e.g. navigation instructions) that is active and exchanging data, when your phone is in your pocket, my app has similar requirements.

## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by Icaro-Lima** [comment]
Same problem here. Any solution?

**Comment by fred4d** [comment]
Unfortunately, no.  You are so far the first and only respondent.  At the
time I submitted this question, my quick inspection of the code base led me
to believe that this improvement would not be an extremely heavy lift, but
to this point no interest.

Good luck!
