### ISSUE TITLE
Issue with Amazon.Runtime.Internal.Util.OptimisticLockedTextFile.Read

### ISSUE THREAD

**Issue by knopa** [aws/aws-sdk-net#1189]
I got next exception while creating presigned urls.

System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Windows\system32\config\systemprofile\.aws\credentials'.
at System.IO.__Error.WinIOError
at System.IO.FileStream.Init
at System.IO.FileStream..ctor
at System.IO.StreamReader..ctor
at System.IO.File.InternalReadAllText
at Amazon.Runtime.Internal.Util.OptimisticLockedTextFile.Read
at System.IO.__Error.WinIOError
at System.IO.FileStream.Init
at System.IO.FileStream..ctor
at System.IO.StreamReader..ctor
at System.IO.File.InternalReadAllText
at Amazon.Runtime.Internal.Util.OptimisticLockedTextFile.Read

**Comment by knopa** [comment]
Also next to it I got next error not often but once per few hours

Amazon.Runtime.AmazonClientException: CryptProtectData failed. Error Code: 2
at Amazon.Runtime.Internal.Settings.UserCrypto.Encrypt
at Amazon.Runtime.Internal.Settings.UserCrypto.get_IsUserCryptAvailable

**Comment by vellozzi** [comment]
Can you tell us more about your case?
What user are you running under?
Are you running as a windows service, or maybe in IIS?
Can you send a snippet of the code you're running?

**Comment by knopa** [comment]
I run under IIS,

`
 BasicAWSCredentials AWSCredentials => new BasicAWSCredentials(Config.AWSUserAccessKey, Config.AWSUserSecretKey);
using (IAmazonS3 client = new AmazonS3Client(AWSCredentials, RegionEndpoint.EUCentral1))
            {

                GetPreSignedUrlRequest request = new GetPreSignedUrlRequest
                {
                    BucketName = bucket,
                    Key = url,
                    Verb = HttpVerb.PUT,
                    Expires = DateTime.UtcNow.AddSeconds(Config.AWSTokenExpiration),
                    Protocol = Protocol.HTTPS
                };

                if (isPublic)
                {
                    request.Headers[X_AMZ_ACL] = PUBLIC;
                }

                presignedUrl = client.GetPreSignedURL(request);
            }`

**Comment by knopa** [comment]
That's full stack trace. I belive stackify attached it somehow in wrong way to my code

**Comment by bpancost** [comment]
I am getting the same error when providing the access and secret keys credentials directly in the code. If I create an empty credentials file everything works fine using the directly provided keys. I should not have to create the credentials file though.

Here's the stack trace I'm seeing up to the point I am trying to instantiate the client.

__Error.WinIOError() in System.IO, mscorlib.dll
FileStream.Init() in System.IO, mscorlib.dll
new FileStream() in System.IO, mscorlib.dll
new StreamReader() in System.IO, mscorlib.dll
File.InternalReadAllText() in System.IO, mscorlib.dll
File.ReadAllText() in System.IO, mscorlib.dll
OptimisticLockedTextFile.Read() in Amazon.Runtime.Internal.Util, AWSSDK.Core.dll
new OptimisticLockedTextFile() in Amazon.Runtime.Internal.Util, AWSSDK.Core.dll
new IniFile() in Amazon.Runtime.Internal.Util, AWSSDK.Core.dll
new ProfileIniFile() in Amazon.Runtime.Internal.Util, AWSSDK.Core.dll
SharedCredentialsFile.Refresh() in Amazon.Runtime.CredentialManagement, AWSSDK.Core.dll
new SharedCredentialsFile() in Amazon.Runtime.CredentialManagement, AWSSDK.Core.dll
CredentialProfileStoreChain.TryGetProfile() in Amazon.Runtime.CredentialManagement, AWSSDK.Core.dll
new ProfileCSMConfigs() in Amazon.Runtime.Internal, AWSSDK.Core.dll
CSMFallbackConfigChain.<.ctor>b__19_2() in Amazon.Runtime.Internal, AWSSDK.Core.dll
CSMFallbackConfigChain.GetCSMConfig() in Amazon.Runtime.Internal, AWSSDK.Core.dll
new DeterminedCSMConfiguration() in Amazon.Runtime.Internal, AWSSDK.Core.dll
static DeterminedCSMConfiguration() in Amazon.Runtime.Internal, AWSSDK.Core.dll
AmazonServiceClient.BuildRuntimePipeline() in Amazon.Runtime, AWSSDK.Core.dll
new AmazonServiceClient() in Amazon.Runtime, AWSSDK.Core.dll
new AmazonServiceClient() in Amazon.Runtime, AWSSDK.Core.dll
new AmazonS3Client() in Amazon.S3, AWSSDK.S3.dll
new AmazonS3Client() in Amazon.S3, AWSSDK.S3.dll

**Comment by alexthekid07** [comment]
I have been getting this for a very long time. No idea why it always barks about the credentials missing in some system32 folder when I feed it credentials directly when creating the client(s), and also list them in my web.config

`System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Windows\system32\config\systemprofile\.aws\credentials'.
at System.IO.__Error.WinIOError
at System.IO.FileStream.Init
at System.IO.FileStream..ctor
at System.IO.StreamReader..ctor
at System.IO.File.InternalReadAllText
at System.IO.File.ReadAllText
at Amazon.Runtime.Internal.Util.OptimisticLockedTextFile.Read
at System.IO.__Error.WinIOError
at System.IO.FileStream.Init
at System.IO.FileStream..ctor
at System.IO.StreamReader..ctor
at System.IO.File.InternalReadAllText
at System.IO.File.ReadAllText
at Amazon.Runtime.Internal.Util.OptimisticLockedTextFile.Read`

**Comment by ashishdhingra** [comment]
Hi @knopa,

We have implemented few fixes recently in this area. Please try using the latest SDK and let mw know if the issue is fixed. 

Thanks,
Ashish

**Comment by alexthekid07** [comment]
@ashishdhingra can you note which release this was fixed in?

**Comment by NGL321** [comment]
@alexthekid07,

I am uncertain which release exactly this was deployed in, but any version post 3.5 should work
