### ISSUE TITLE
Intellisense for Serverless.Template Json File In Visual Studio (.Net Core)

### ISSUE THREAD

**Issue by matheusmaximo** [aws/aws-sdk-net#1191]
When I add a Globals tag in serverless.template json file in VisualStudio, Intellisense complains as an invalid key for this object.

`{`
`  "AWSTemplateFormatVersion": "2010-09-09",`
`  "Transform": "AWS::Serverless-2016-10-31",`
`  "Description": "Sample SAM Template",`
`  "Globals": {`
`    "Function": {`
`      "Timeout": 30,`
`      "Runtime": "dotnetcore2.1"`
`    }`
`  }`
`}`

## Expected Behavior
Intellisense was to accept this tag and content.

## Current Behavior
Intellisense underline and colour the tag in red and shows a hint saying that tag is invalid.

## Your Environment

* AWSSDK.Core version used: AWSToolsAndSDKForNet_sdk-3.3.446.0_ps-3.3.428.0_tk-1.14.5.0
* Operating System and version: Windows 10 Professional
* Visual Studio version: Professional 2017 Version 15.9.5 VisualStudio.15.Release/15.9.5+28307.280
* Targeted .NET platform: .Net Core 2.1.5
* AWS Toolkit for Visual Studio 2017   1.14.5.0

**Comment by klaytaybai** [comment]
Thanks for pointing this out.

**Comment by matheusmaximo** [comment]
I will try to read the code and see if I can find a solution this weekend.

**Comment by matheusmaximo** [comment]
Looks like Globals section is not defined in CloudFormation template anatomy (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-anatomy.html).
I tried to find a point in code to validate the file but I couldn't find a simple solution for that.

**Comment by klaytaybai** [comment]
I’ve asked the people who manage the toolkit to work on this.  I don’t know when it will be done, but it is something that we are aware of now.  Thanks

**Comment by normj** [comment]
@matheusmaximo I'm working on updating the backing schema for the editor

**Comment by matheusmaximo** [comment]
Thanks @normj !

**Comment by matheusmaximo** [comment]
It works perfectly! Thank you very much!
