### ISSUE TITLE
ServiceURL value is nulled on AmazonSimpleNotificationServiceConfig

### ISSUE THREAD

**Issue by mattvaughan** [aws/aws-sdk-net#1193]
## Expected Behavior
When setting the `ServiceURL` on an `AmazonSimpleNotificationServiceConfig`, the object should retain the value, despite the order the other properties are set it.

## Current Behavior
When `RegionEndpoint` is set after `ServiceURL`, the value of `ServiceURL` becomes null.

## Steps to Reproduce (for bugs)
```
using System;
using Amazon.SimpleNotificationService;
using Amazon.SimpleNotificationService.Model;
using Amazon;
using Amazon.Runtime;

namespace sdk_bug_demo
{
    public class Program
    {
        public static void Main()
        {
            var snsConfig = new AmazonSimpleNotificationServiceConfig();
            snsConfig.ServiceURL = "http://localhost";
            snsConfig.RegionEndpoint = RegionEndpoint.USEast1;

            Console.WriteLine("This is the url: " + snsConfig.ServiceURL); // ServiceURL is null here. Switch the order of the assignments, and the problem goes away.
        }
    }
}
```

## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used:  `<PackageReference Include="AWSSDK.SimpleNotificationService" Version="3.3.3.15" />`

* Operating System and version: Debian 9
* Visual Studio version: N/A
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 2.1
* .NET Core version installed in the environment where application runs: 2.1
* Output of `dotnet --info`: 
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.302
 Commit:    9048955601

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         debian.9-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.302/

Host (useful for support):
  Version: 2.1.2
  Commit:  811c3ce6c0

.NET Core SDKs installed:
  2.1.302 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
* Contents of project.json/project.csproj: 
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <RootNamespace>sdk_bug_demo</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.SimpleNotificationService" Version="3.3.3.15" />
  </ItemGroup>

</Project>
```

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
Hi @mattvaughan, are you trying to create a local proxy for the service?  What is your goal?

The ServiceURL and RegionEndpoint properties are designed to be incompatible because they are both used to determine the endpoint.  Either way you order them, the last one will always take priority.  If you wish to specify the SNS ServiceURL for us-east-1 you can use http://sns.us-east-1.amazonaws.com or https://sns.us-east-1.amazonaws.com.

You might find the following documentation helpful:
https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-region-selection.html

**Comment by mattvaughan** [comment]
@klaytaybai That makes sense. This issue stemmed from a misunderstanding. I figured aws had one `ServiceURL` and the `RegionEndpoint` was used elsewhere in the request. I was using the sdk against localstack, hence the explicit `ServiceURL`.

Would it be better to throw an exception when both are set? I couldn't find this "one or the other" behavior defined in the API reference.

You may close this issue!

**Comment by klaytaybai** [comment]
Hi @mattvaughan, thanks for the reply and feedback.  Throwing an exception to alert users of the conflict might have been a good design decision originally.  However we have a policy of not deprecating any behavior in our APIs, so this change is unlikely to take effect.

**Comment by erdtsieck** [comment]
I just spent hours on this, so adding an exception would be great
