### ISSUE TITLE
Issues found by PVS-Studio

### ISSUE THREAD

**Issue by skhrenov** [aws/aws-sdk-net#1195]
Hello,
I have found a few bugs using PVS-Studio analyzer.
PVS-Studio is a static code analyzer for C, C++, C#, and Java.
I gave the description of errors and code fragments in the article.
You can read the article at the official site: [https://www.viva64.com/en/b/0605/](https://www.viva64.com/en/b/0605/)

**Comment by klaytaybai** [comment]
Wow.  Hi @skhrenov, that is very helpful.  Thank you for taking the time to do such a thorough article and help us identify and fix some bugs.  We appreciate it a lot.
