### ISSUE TITLE
S3 request query param is trimmed at the end incorrectly

### ISSUE THREAD

**Issue by xakep139** [aws/aws-sdk-net#1196]
Sending signed request using AWS SDK with query params containing space(s) at the end leads to an exception with error `SignatureDoesNotMatch`

## Expected Behavior

`GetObject` request do not trim versionId (or another query params) at the end

## Current Behavior

Sending request without spaces in `versionId` gives me following HTTP request:
```
GET /bucket/object?versionId=AGdtSBttoV2r97kIKQlvwSKt17M0PiS HTTP/1.1
User-Agent: aws-sdk-dotnet-coreclr/3.3.31.13 aws-sdk-dotnet-core/3.3.31.5 .NET_Core/4.6.27129.04 OS/Microsoft_Windows_10.0.17763 ClientAsync
Host: XXX
X-Amz-Date: 20190128T044823Z
X-Amz-Content-SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Authorization: AWS4-HMAC-SHA256 Credential=XXXXXXXXXXXXXXXXXXXX/20190128/us-east-1/s3/aws4_request, SignedHeaders=host;user-agent;x-amz-content-sha256;x-amz-date, Signature=5ba54605c53b8f449af690d0289ff9abf2894e640fd815f41c6df5eb7694cb60
```

With space in the end of `versionId` (signature differs from request without spaces, but query parameter does not have space at the end - `%20`):
```
GET /bucket/object?versionId=AGdtSBttoV2r97kIKQlvwSKt17M0PiS HTTP/1.1
User-Agent: aws-sdk-dotnet-coreclr/3.3.31.13 aws-sdk-dotnet-core/3.3.31.5 .NET_Core/4.6.27129.04 OS/Microsoft_Windows_10.0.17763 ClientAsync
Host: XXX
X-Amz-Date: 20190128T044816Z
X-Amz-Content-SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Authorization: AWS4-HMAC-SHA256 Credential=XXXXXXXXXXXXXXXXXXXX/20190128/us-east-1/s3/aws4_request, SignedHeaders=host;user-agent;x-amz-content-sha256;x-amz-date, Signature=43d551e322a7325d57824549cece0a13f1b9a150563c383df0e7bfc9c65e167f
```
This request leads to an exception:
```
Amazon.S3.AmazonS3Exception: Error making request with Error Code SignatureDoesNotMatch and Http Status Code Forbidden. No further error information was returned by the service.
```

With space in the beginning of `versionId` (space is present in query params):
```
GET /bucket/object?versionId=%20AGdtSBttoV2r97kIKQlvwSKt17M0PiS HTTP/1.1
User-Agent: aws-sdk-dotnet-coreclr/3.3.31.13 aws-sdk-dotnet-core/3.3.31.5 .NET_Core/4.6.27129.04 OS/Microsoft_Windows_10.0.17763 ClientAsync
Host: XXX
X-Amz-Date: 20190128T044944Z
X-Amz-Content-SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Authorization: AWS4-HMAC-SHA256 Credential=XXXXXXXXXXXXXXXXXXXX/20190128/us-east-1/s3/aws4_request, SignedHeaders=host;user-agent;x-amz-content-sha256;x-amz-date, Signature=7644030ebf58475c867e7bbc0dd424c946dfd2b60ba3801bf44e448217292473
```

## Possible Solution

Do not trim query string(s) at the end?

## Steps to Reproduce (for bugs)

```
var client = new AmazonS3Client(bucketRegion);
using (var response = await client.GetObjectAsync("bucket", "key", "versionWithSpaceAtTheEnd "))
{
}
```

## Your Environment

* AWSSDK.Core version used: 3.3.31.13
* Service assembly and version used: 
* Operating System and version: Windows 10 Enterprise 10.0.17763 Build 17763
* Visual Studio version: 15.9.6
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 2.2.1
* .NET Core version installed in the environment where application runs: 2.2.1
* Output of `dotnet --info`: 
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.503
 Commit:    4c506e0f35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.503\

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62
```
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
Hi @xakep139, I have not been able to reproduce this issue using the version of the SDK that you used or the latest.  The issue is likely due to something else.

**Comment by klaytaybai** [comment]
Sorry for my original comment that I have since deleted.  This still needs to investigated.  I'm looking into it.

**Comment by klaytaybai** [comment]
@xakep139, where are you seeing the version ID with a space at the end?  We're working on confirming that a space in a version id should even be valid.

**Comment by klaytaybai** [comment]
The consensus seems to be that a versionId with a space is invalid.  If you are getting one back from S3 or the SDK, we would be very interested to know more.

**Comment by xakep139** [comment]
I agree, but there are many S3-compatible storage systems (e.g. Ceph) and we don't want to trim or validate `versionId` that comes from user request on our side, because we don't know exactly how `versionId` is generated.
Even if there cannot be versionId with spaces (or other non-alphanumeric symbols), there are many more subrecources that should be included as query parameters (according to [docs](https://docs.aws.amazon.com/en_us/AmazonS3/latest/dev/RESTAuthentication.html#ConstructingTheCanonicalizedResourceElement)). Some of them can include space at the end and will be trimmed just like `versionId`. The issue title does not contain anything about `versionId`, but only about query param

**Comment by klaytaybai** [comment]
Can you give me an example of where a space would be used at the end of any of those for a valid input?  I'm not identifying any.

**Comment by klaytaybai** [comment]
I'm going to close this out because I'm not sure there are any valid inputs where this could cause an issue.  If you fine an example, please feel free to reopen or comment.

**Comment by klaytaybai** [comment]
@xakep139, where is the space in your request?  As far as I can tell, this is all theoretical.  Are you only seeing this error if you are purposely appending a space to a value that shouldn't have it, or are you using normal inputs?

**Comment by aotd1** [comment]
This error can be established if someone trying to use fuzzing requests to server.

**Comment by xakep139** [comment]
@klaytaybai, simply create new file with `vi "test "` and try to send `PutObjectRequest` with key equals to this filename. Do you consider such case as a valid input?

**Comment by klaytaybai** [comment]
Hi @xakep139, you can refer to this [S3 naming documentation](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html) for valid key names.  A file named "test " should be fine.  I confirmed when this issue was first created that posting a file using a key with a space at the end works.

**Comment by xakep139** [comment]
I've updated the issue summary, so you can reproduce use-case with `PutObjectRequest`. It leads me to
```
Amazon.S3.AmazonS3Exception: Error making request with Error Code SignatureDoesNotMatch and Http Status Code Forbidden
```
even with latest `AWSSDK.S3`

**Comment by aotd1** [comment]
@klaytaybai so... maybe reopen this issue?
