### ISSUE TITLE
Unable to upload the file to S3 bucket

### ISSUE THREAD

**Issue by suriyaKalidoss123** [aws/aws-sdk-net#1197]
Unable to upload the file to S3 bucket
## Expected Behavior
Need to upload the file.

[stacktrace.txt](https://github.com/aws/aws-sdk-net/files/2807373/stacktrace.txt)

## Current Behavior
Unable to upload the file

## Possible Solution
should be able to upload the file

## Steps to Reproduce (for bugs)
Run the attached project and click upload
Issue occurs randomly

## Context
Because of this, I'm unable to upload the file

## Your Environment
* Xamarin
* AWSSDK.Core version used: 
*AWSSDK.CognitoIdentity---->3.3.2.59
*AWSSDK.S3---->  3.3.31.5
* Service assembly and version used: 
* Operating System and version: windows 10
* Visual Studio version:15.9.6
* Targeted .NET platform: 
Run in Xamarin Forms Android

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
Hi @suriyaKalidoss123, thank you for checking out our SDK.  

In the future, I highly advise you to refrain from posting your whole application code to a public site unless you intend for it to be public.  It is too easy to let confidential information like intellectual property or access tokens to services be exposed.  If you do need to post code to a public site, please first verify that you have obfuscated or removed any confidential information.

**Comment by suriyaKalidoss123** [comment]
hi @klaytaybai ,
Thanks for advise

**Comment by suriyaKalidoss123** [comment]
is there is any workaround for this issue?

**Comment by suriyaKalidoss123** [comment]
Hi @klaytaybai ,
 When does the issue will be fixed??

**Comment by suriyaKalidoss123** [comment]
IAmazonS3 s3Client;
 s3Client = new AmazonS3Client(creds, RegionEndpoint.USWest1);   
s3Client.UploadObjectFromFilePathAsync(bucketName, uploadFileName, filePathName, null);

 I had removed using the async and await but file upload is not done. Your help will get improvement for my project.Please advise

**Comment by klaytaybai** [comment]
If you are using .Net Core, you still need to await the UploadObjectFromFilePathAsync in an async method.  This [article](https://msdn.microsoft.com/en-us/magazine/jj991977.aspx) on async programming in C# might be helpful.

Which region are you trying to use?  Here you are trying to upload to a bucket in USWest1.  Your previous code used USEast1.  If you do not have a bucket with the specified name in your specified region, this won't work.

**Comment by suriyaKalidoss123** [comment]
Hi @klaytaybai ,
 I'm just confused with my Region I previously used USEast1.But an exception condition, it popped as to try to use USWest that's why I changed it to USWest1

**Comment by klaytaybai** [comment]
Whatever region you or your customer base is closest to would probably be most ideal.  What told you to use USWest1 instead?

**Comment by suriyaKalidoss123** [comment]
While using USEast1 an exception condition popped up and said try to use USWest1

**Comment by klaytaybai** [comment]
I'm closing this out due to inactivity.  If you are still having issues, please try seeing some of our documentation and samples.  If that still doesn't work, feel free to reopen.

**Comment by luizniero** [comment]
> Hi @klaytaybai
> IAmazonS3 s3Client;
> s3Client = new AmazonS3Client(creds, RegionEndpoint.USWest1);
> s3Client.UploadObjectFromFilePathAsync(bucketName, uploadFileName, filePathName, null);
> 
> Right now I'm not getting any exception after removing the async and await but file upload is not done. Your help will get improvement for my task so please advise.
> 
> but download is working fine
> s3Client.DownloadToFilePathAsync(bucketName, downloadFileName, filePathName, null);

im also having the same problem. Do you found the fix?
