### ISSUE TITLE
EC2InstanceMetadata threading bug

### ISSUE THREAD

**Issue by JJoe2** [aws/aws-sdk-net#1198]
## Expected Behavior
Amazon.Util.EC2InstanceMetadata exposes static members to retrieve metadata that I would expect to be thread-safe.

## Current Behavior
The EC2InstanceMetadata uses a static `Dictionary<string,string>` to cache instance metadata without implementing any synchronization:

    private static Dictionary<string, string> _cache

The `Dictionary<TKey, TValue>` class is not thread-safe: <a href="https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2?view=netframework-4.7.2">To allow the collection to be accessed by multiple threads for reading and writing, you must implement your own synchronization.</a>

## Possible Solution
Implement synchronization, for example by wrapping all read and write access to the _cache dictionary in a `lock` statement.

## Steps to Reproduce (for bugs)
Difficult to reproduce, but there is the risk of heisenbugs if there is concurrent access from multiple threads.

## Context
Low priority / low impact

## Your Environment
* AWSSDK.Core version used: 3.3.0.0
* Operating System and version: Windows 10
* Visual Studio version: 2017
* Targeted .NET platform: 3.5 and .NET Standard 2.0

**Comment by SebastianToet** [comment]
We have regular problems with our web applications "hanging" on this issue: When multiple threads try to access EC2InstanceMetaData methods, and they all try to access the _cache Dictionary simultaneously, the dictionary seems to get in a loop, consuming 100% CPU. This makes this class basically unusable in multi-threaded scenarios.
Even besides that, it seems a pretty important issue that public static members in an SDK are not thread-safe.

**Comment by ashishdhingra** [comment]
Fixed in AWS SDK Core 3.5.3.0
