### ISSUE TITLE
Amazon.CloudFormation.Model.Stack.CreationTime has a Kind of Local, not Utc

### ISSUE THREAD

**Issue by markshep** [aws/aws-sdk-net#1199]
Your blog post [here](https://aws.amazon.com/blogs/developer/datetime-serialization-changes-in-the-aws-sdk-for-net-and-awspowershell-modules/) talks about the established best practice that date handling should always be in UTC (apart from the final step of displaying it in UI).  However you fail to follow your own advice and the DateTime Amazon.CloudFormation.Model.Stack.CreationTime has a Kind of Local.

## Expected Behavior
Return a DateTime with a Kind of DateTimeKind.Utc.

## Current Behavior
Returns a DateTime with a Kind of DateTimeKind.Local.

## Steps to Reproduce (for bugs)
Get an Amazon.CloudFormation.Model.Stack instance, for example by calling IAmazonCloudFormation.DescribeStacksAsync().

## Context
I'm trying to display stacks sorted by creation time, but noticed that they're not being returned as UTC.

## Your Environment
* AWSSDK.Core version used: 3.3.31.6
* Service assembly and version used: AWSSDK.CloudFormation 3.3.13.15
* Operating System and version: macOS 10.14.3
* Visual Studio version: N/A
* Targeted .NET platform: .NET Core 2.1.7 LTS

**Comment by klaytaybai** [comment]
Hi @markshep,  thank you for alerting us to this.  It appears that, while the Kind property of the DateTime is Local, the value returned from DescribeStacksAsync is the UTC value.

**Comment by markshep** [comment]
I wasn't sure whether it was just a bad Kind or whether it was actually returning the DateTime in the local timezone because I'm in the UK and we're currently on GMT (which is the same as UTC).  So thanks for clarifying that.

I've also found that the timestamps returned from the IAmazonCloudWatch.GetMetricDataAsync() call have a Kind of Local, so maybe this is a general problem with your deserialiser?

**Comment by markshep** [comment]
Hi @klaytaybai,

After your previous answer I started converting the DateTimes to UTC while leaving the actual time alone (by using `new DateTime(timestamp.Ticks, DateTimeKind.Utc)`).  However now that we're in British Summer Time (GMT+1) here I'm getting incorrect timestamps.  Using the "aws" command line tool I can see that the raw timestamps in the JSON are in ISO-8601 format and are in UTC, but when they're returned as DateTimes from the SDK they've been converted into local time, so the Kind of DateTimeKind.Local is actually correct.

This can be seen in this screenshot showing our reporting website that uses the SDK to gather details about the various CloudFormation stacks we've got running.  The page on the left is from a web server running on my local development machine which has its timezone set to "Europe/London".  The one on the right is the live web server running on AWS and has a system timezone of "UTC":

<img width="818" alt="Screenshot 2019-04-08 at 16 29 42" src="https://user-images.githubusercontent.com/490067/55736632-9b70f980-5a1b-11e9-8882-f569c3b12f88.png">

We changed from GMT to BST on 31st March and you can see that the timestamps on the "chat5" stack match, but on the "LiveStable" stack the time on the local web server has gone forward an hour during the conversion to local time.  Again, I'm also seeing the same behaviour for data returned from CloudWatch.

Please could you fix your SDK to always return DateTimes in UTC and *not* convert them to local time?

Thanks,
Mark
