### ISSUE TITLE
Amazon.Runtime.Internal.Util.HashStream get Position should not throw

### ISSUE THREAD

**Issue by chadcampling** [aws/aws-sdk-net#1200]
When opening a file from S3 using the SDK the underlying stream appears to be using Amazon.Runtime.Internal.Util.MD5Stream which inherits Amazon.Runtime.Internal.Util.HashStream, although the stream is not seek-able a consumer should be able to check if the stream is at a position while not being able to set the position.

## Expected Behavior
A library author may have a need to ensure that a stream passed to them is at the beginning of the data stream. A call to get the Position property on the stream should return the current Position of the stream. Currently there is no way to check this without an exception being thrown.

## Current Behavior
Currently a call to get Position on HashStream throws NotSupportedException("HashStream does not support seeking"). A call to get the position of the stream does not attempt to seek the stream and should be permitted. 

## Possible Solution
Alter the Position get property to return the CurrentPosition protected property or the position of the underlying wrapped stream.

## Context
Trying to ensure a stream passed into a generic helper method can ensure the stream is at the beginning of the data stream and throw a meaningful exception in the case it isn't.

## Your Environment

* AWSSDK.Core version used: 3.3.28.1
* Service assembly and version used: AWSSDK.S3 3.3.26.1
* Operating System and version: Windows 2016, Windows 10
* Visual Studio version: NA
* Targeted .NET platform: net Full Framework 4.6.1

**Comment by klaytaybai** [comment]
I'll discuss this with the team tomorrow.  That seems reasonable, but there may be reasons for the current implementation.  The Microsoft base Stream class has this to say: 
> The stream must support seeking to get or set the position. Use the CanSeek property to determine whether the stream supports seeking.

**Comment by klaytaybai** [comment]
Hi @chadcampling, it sounds like the decision is to not make this change at this time in order to keep consistent with the standard for non-seekable streams.  If you are willing to provide us with more insight into your use case, we can factor that into any reconsideration.  Thank you.

**Comment by InflectionPointNow** [comment]
The usecase that comes to mind is when we want to copy data from one S3Client (e.g. opened with temporary credentials), and copy the object to another bucket where S3 client has been opened with different set of credentials.  If this were to be done in a Lambda function of e.g., then there is no way to do it without loading the full object into a memory stream and then using the Memory stream to the target.  This necessitates the memory on the Lambda to be the full size of the object to be copied.  This is not practical.
