### ISSUE TITLE
Cannot find StartStreamTranscription method in AWSSDK.TranscribeService

### ISSUE THREAD

**Issue by dibyadip-das** [aws/aws-sdk-net#1204]
Hi,
I wanted to prototype Streaming Transcription using AWSSDK.TranscribeService but unable find the class.

## Expected Behavior
I was expecting to find a class called "TranscribeStreaming" which will fire events for a continuous stream of Audio data

## Current Behavior
No such method found. 

## Possible Solution
If there are any alternate method with which I can achieve the same. Please let me know.
If the feature is not implemented for .NET, when can we expect it ?

**Comment by klaytaybai** [comment]
Hi @dibyadip-das. thank you for your interest in this service.  As you seem to have learned, it does not appear to be implemented yet in .NET.  It is implemented in Java, so you can use that if that is a viable option for you.  We can't make guarantees at this time as to when it may be added to .NET, but I'll get some communication going around this.

**Comment by normj** [comment]
StartStreamTranscription requires an HTTP 2 client which there isn't one in .NET yet. We are investigating what our alternatives are.

**Comment by cooliodoc** [comment]
Apparently you could use the .net core client since that is cross compatible and it supports http 2.0

"To do this, you'll need to add a reference to System.Net.Http (version 4.3.0 or higher) on NuGet. Then, use the HttpClient and HttpRequestMessage classes from that assembly.

The last thing you'll need to do is set myHttpRequestMessage.Version = new Version(2, 0) in your code for each HttpRequestMessage that you create."
https://blog.yaakov.online/using-http-2-in-net-client-applications/

**Comment by dibyadip-das** [comment]
Have a look at [Microsoft's http2-katana](https://github.com/MicrosoftArchive/http2-katana). This could help you add HTTP/2 functionality to .net.

**Comment by docblop** [comment]
I was able to create a http2 request, but AWS throws an error.

```
byte[] signatureKey = getSignatureKey("mykey", DateTime.UtcNow.ToString("YYYYMMDD"), "us-west-2", "transcribestreaming");

System.Net.Http.HttpClient client = new System.Net.Http.HttpClient(new Http2CustomHandler());
            client.BaseAddress = new Uri("https://transcribestreaming.us-west-2.amazonaws.com");
            var content = new FormUrlEncodedContent(new[]
            {
                new KeyValuePair<string, string>("authorization", "Encoding.UTF8.GetString(signatureKey)"),
                new KeyValuePair<string, string>("content-type", "application/vnd.amazon.eventstream"),
                new KeyValuePair<string, string>("x-amz-content-sha256", "STREAMING-AWS4-HMAC-SHA256-EVENTS"),
                new KeyValuePair<string, string>("x-amz-date", DateTime.UtcNow.ToString("YYYYMMDD'T'HHMMSS'Z'")),
                new KeyValuePair<string, string>("x-amzn-transcribe-language-code", "en-US"),
                new KeyValuePair<string, string>("x-amzn-transcribe-media-encoding", "pcm"),
                new KeyValuePair<string, string>("x-amzn-transcribe-sample-rate", "16000"),
                new KeyValuePair<string, string>("transfer-encoding", "chunked")
            });
            var result = await client.PostAsync("/stream-transcription", content);
            string resultContent = await result.Content.ReadAsStringAsync();
            Console.WriteLine("Content: " + resultContent);
            Console.WriteLine("Headers: " + result.Headers.ToString());
            Console.WriteLine("Status Code: " + result.StatusCode);
            Console.WriteLine("Request Version: " + result.Version);
```
The result is:

```
Content: <UnknownOperationException/>

Headers: Date: Wed, 08 May 2019 07:49:36 GMT
x-amzn-requestid: 4c573264-9fb1-4c95-a037-34cede059073

Status Code: NotFound
Request Version: 2.0
```



Any help would be greatly appreciated. Thanks.

**Comment by Dev-Power** [comment]
Hello,

It's been almost 3 years since the initial request. Is it not still possible to add support to real-time transcription to the SDK?

Thanks.
