### ISSUE TITLE
How to upload/download items from FIPS compalint s3 bucket from different region ?

### ISSUE THREAD

**Issue by rsrini83** [aws/aws-sdk-net#1207]
We are using SDK to upload/download items to S3 bucket. One of our customers is asking does our product support S3 bucket in GovCloud in US.  Do we need to configure anything while uploading/downloading items? or Does framework auto-detects these setting?

EC2 will be running in non-GovCloud and S3 bucket is in GovCloud.

**Comment by klaytaybai** [comment]
Hi @rsrini83,

Basic information on GovCloud can be found [here](https://aws.amazon.com/govcloud-us/).  The customer will first need to be approved to use GovCloud.  

More information about using US GovCloud West can be found [here](https://docs.aws.amazon.com/govcloud-us/latest/ug-west/using-govcloud-endpoints.html), including the correct endpoints to use for S3 on US GovCloud West.  This page doesn't contain information for US GovCloud East.  I'm running out of time to look into this further today, but I can try to find more resources and provide more guidance within the next couple days.  

If the EC2 instance is running in a VPC, which it probably should be, a [VPC Endpoint to the S3](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-endpoints-s3.html) GovCloud region is probably needed.  I'll try to provide more guidance within the next couple days.

Do you know which region of GovCloud the customer is hoping to use?  

Are you an Amazon employee?  Creating an issue with Premium Support might be appropriate if updates to this issue are urgent.

**Comment by klaytaybai** [comment]
@rsrini83, sorry for not getting more information out about US GovCloud East.  Do you still need support on this issue?

**Comment by rsrini83** [comment]
@klaytaybai 

Are there any settings to enable this via programmatically ?  Sample code will help me. 

Other question is, can we access these endpoints outside the region (What if my EC2 is running in a different region )?

**Comment by ashishdhingra** [comment]
Hi @rsrini83,

Good afternoon.

Please let me know what settings are you referring to which need to be enabled programmatically.

Thanks,
Ashish
