### ISSUE TITLE
Unable to upload file to S3 bucket using IAM role credentials

### ISSUE THREAD

**Issue by rsrini83** [aws/aws-sdk-net#1208]
Our application runs in windows EC2 machine which uses IAM role (this role has full access to S3 Bucket). From mid of December, we are observing that our application is not able to upload to S3 bucket (working prior to mid of december).   This is happening in our production environment only.

## Expected Behavior
Able to upload file to S3 bucket using IAM credentials and Region.

## Current Behavior
While uploading the file, getting below exception. However, when we run the sample code in the same machine upload is going through fine. Our application creates EC2 machines on the fly and after finishing the job it gets terminated. 

Amazon.S3.AmazonS3Exception: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.Internal.RedirectHandler.HandleRedirect(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\RedirectHandler.cs:line 138
   at Amazon.Runtime.Internal.RedirectHandler.<InvokeAsync>d__1`1.MoveNext() in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\RedirectHandler.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.Runtime.Internal.Unmarshaller.<InvokeAsync>d__3`1.MoveNext() in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\Unmarshaller.cs:line 0
--- End of stack trace from previous location where exception was thrown ---

## Possible Solution
NONE

## Steps to Reproduce (for bugs)
We use the below code
 using (FileStream inputStrem = File.Open("sample.txt", FileMode.Open, FileAccess.Read))
            {
                TransferUtilityUploadRequest fileTransferUtilityRequest = new TransferUtilityUploadRequest
                {
                    BucketName = bucketName,
                    StorageClass = S3StorageClass.ReducedRedundancy,
                    PartSize = 6291456, // 6 MB.
                    Key = "uploadtest/sample.txt",
                    InputStream = inputStrem,
                    CannedACL = S3CannedACL.Private,
                    AutoCloseStream = false,
                    AutoResetStreamPosition = true,
                };
                TransferUtility fileTransferUtility = new TransferUtility(s3);
                var uploadTask = fileTransferUtility.UploadAsync(fileTransferUtilityRequest);
                uploadTask.Wait();
            }

## Context
We upload application statistics to s3 bucket for future use or will be served to our customers.

## Your Environment
VS Version: 2017
Targeted .NET Platform: 4.5.2
AWS.SDK.S3: 3.3.12

**Comment by klaytaybai** [comment]
Hi @rsrini83, the most likely cause of this issue is that you are specifying a bucket that exists but not in the region that your client is configured to hit.

Please respond with:
* the region in which the bucket is verified to exist
* the region configured in your S3 client that you supplied to the TransferUtility constructor.  Please also verify that the client is not configured with both a region parameter and an endpoint parameter.  If both are specified, please give us both of those as well.

**Comment by rsrini83** [comment]
Hi Klaytaybai,

Looks like i missed the earlier notification about closing-soon-if-no-response. As i mentioned in my question, bucket is created in the same region and as EC2 machine is running the same region. we are not passing region/credentials to s3 client object. This code was working from last 1 year (since our production).  However, it started failing from last December. 

And I'm not able to log more details for the library - which endpoint library is making, what is the actual response (entire HTTP response) 

And, we have tried running manually the same code - at that time code is working fine. However, this is not working when we launch the EC2 machine on the fly using AMI image. 



Can you please re-open the issue?  We would like to open a case with AWS support also, but let me know if any information we need to capture this.

**Comment by sstevenkang** [comment]
This looks like the instance profile attached to the EC2 instance is not vending the credentials with the correct permissions.  Could you provide more information as to what your environment looks like?  If you could grab the request ID for the operation that failed,  that would help too.
