### ISSUE TITLE
ListInputSecurityGroupsRequest won't list tags

### ISSUE THREAD

**Issue by zozzancs** [aws/aws-sdk-net#1211]
## Expected Behavior
When creating ListInputSecurityGroupsRequest and looping through InputSecurityGroups I should also be able to read the Tags.

## Current Behavior
Tags is an empty list.

## Steps to Reproduce (for bugs)
` ListInputSecurityGroupsRequest listInputSecurityGroupsRequest = new ListInputSecurityGroupsRequest();
            var inputsecgroupresponse = amazonMediaLiveClient.ListInputSecurityGroups(listInputSecurityGroupsRequest);
            foreach (var sec_group in inputsecgroupresponse.InputSecurityGroups)
            {
                foreach (var tag in sec_group.Tags)
                {  //Tags in an empty list
                }
            }`

## Context
I would like to find a security group based on tags

## Your Environment
* AWSSDK.Core version used: 3.3.31.7
* AWSSDK.MediaLive version used: 3.3.16
* Service assembly and version used: 
* Operating System and version: Win 10
* Visual Studio version: Community 2017 - 15.9.6
* Targeted .NET platform: 4.5.2

## .NET Core Info
* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
.NET Core SDK (reflecting any global.json):
 Version:   2.1.503
 Commit:    4c506e0f35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.503\

Host (useful for support):
  Version: 2.1.7
  Commit:  cca5d72d48

.NET Core SDKs installed:
  1.0.0 [C:\Program Files\dotnet\sdk]
  1.0.2 [C:\Program Files\dotnet\sdk]
  1.0.3 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.100 [C:\Program Files\dotnet\sdk]
  2.1.101 [C:\Program Files\dotnet\sdk]
  2.1.102 [C:\Program Files\dotnet\sdk]
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
Hi @zozzancs, thank you for reporting this.  As you might know, the ability to tag input security groups in MediaLive is new.  It seems that the service API has not been fully updated yet to account for this new feature.  At this time, there is nothing that our team can do as a workaround for you.  The best I can do is to inquire into whether we can get this implemented into the MediaLive API soon.  If you wish to spread more awareness of it yourself, please feel free to post in the [MediaLive AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=269) or open a ticket in Premium Support if you have it.

**Comment by klaytaybai** [comment]
We try to keep the issues in this repo scoped to the .NET SDK and other products we support.  The SDK should be able to support these service changes without any modifications, so I'm going to close out this issue.  If I get an update that it has been changed, I'll try to remember to inform you.

**Comment by klaytaybai** [comment]
Hi @zozzancs, I believe this should be implemented now.  Thanks again for reporting it.
