### ISSUE TITLE
FederatedAWSCredentials not present in CoreCLR build

### ISSUE THREAD

**Issue by fireflycons** [aws/aws-sdk-net#1213]
If I'm reading the current codebase correctly, `FederatedAWSCredentials` is only available in BCL builds of AWSSDK.Core. 

## Expected Behavior
Should be able to create instance of `FederatedAWSCredentials` in CoreCLR applications

## Current Behavior
Cannot create create instance of `FederatedAWSCredentials` 

## Context
Our Ops department is implementing a policy to remove all developer IAM User accounts and exclusively use federated authentication. Thus it is needed to our many .NET Core applications when debugging at developer workstations.

## Your Environment

* AWSSDK.Core version used: 3.3.31.8
* Service assembly and version used: n/a
* Operating System and version: Windows 10
* Visual Studio version: 2017
* Targeted .NET platform: .NET Core

**Comment by klaytaybai** [comment]
Hi @fireflycons, by your interest in FederatedAWSCredentials, I assume you are trying to use one of the [SAMLAuthenticationType](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/Runtime/TSAMLAuthenticationType.html)s, right?  Depending on your use case, [Cognito](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/cognito-apis-intro.html) could be an alternative, in which case I could provide more guidance on how to use that.  I'm not yet sure why the decision was made to not support FederatedAWSCredentials in Core.  There may be a valid compatibility issue that I'm not aware of.  I'll put this on my list of things to look into.

**Comment by fireflycons** [comment]
Yes @klaytaybai that is what I need to do.
I believe that the FallbackCredentialsFactory is however present in CoreCLR build. Assuming a developer has initialised credentials in the shell that starts Visual Studio, then the factory will return an AWSCredentials initialised from the federated credential?
Additionally, when the application is deployed to EC2, the factory will return InstanceProfileAWSCredentials?

**Comment by prvysoky** [comment]
I don't know if this helps anything but my AWS credentials that I created through the SDK Toolkit for Visual Studio were named "User @ project" and until I removed spaces and @ from the name, I was getting NullReference exception about AWS credentials not found.

**Comment by ashishdhingra** [comment]
Hi @fireflycons,

Please try updating to the latest SDK which has support for `netstandard20` and FederatedAWSCredentials, and let me know if it resolves the issue.

Thanks,
Ashish
