### ISSUE TITLE
AmazonPinpointSMSVoice SendVoiceMessageAsync is using wrong Content Type

### ISSUE THREAD

**Issue by BradVog** [aws/aws-sdk-net#1215]
I'm getting the error `Unsupported Media Type` when calling the `SendVoiceMessageAsync` function on `AmazonPinpointSMSVoiceClient`. After some searching, I found someone else with the same problem who seemed to do some digging on what the underlying problem is:

https://forums.aws.amazon.com/thread.jspa?messageID=887082

## Expected Behavior
`SendVoiceMessageAsync` should return a Success status code, or a status code defined in the API. 

## Current Behavior
`AmazonPinpointSMSVoiceException` is thrown with the message: Unsupported Media Type

## Possible Solution
The beleive following line should be `application/json`, or the server should support `application/x-amz-json-1.1`
https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/PinpointSMSVoice/Generated/Model/Internal/MarshallTransformations/SendVoiceMessageRequestMarshaller.cs#L58

## Context
This is critical blocking bug for me since this failure seems to be out of my control. Any workarounds would be very helpful

## Your Environment

* AWSSDK.Core version used: 3.3.31.9
* Service assembly and version used: AWSSDK.PinpointSMSVoice 3.3.2.4
* Operating System and version: Windows 10
* Visual Studio version: Visual Studio 15.9.3
* Targeted .NET platform: .NET Core 2.2

## .NET Core Info

* .NET Core version used for development: 2.2
* .NET Core version installed in the environment where application runs: 2.2
* Output of `dotnet --info`: 

> .NET Core SDK (reflecting any global.json):
>  Version:   2.2.200-preview-009804
>  Commit:    8e586b8a98
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.17763
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\2.2.200-preview-009804\
> 
> Host (useful for support):
>   Version: 2.2.1
>   Commit:  878dd11e62
> 
> .NET Core SDKs installed:
>   2.1.202 [C:\Program Files\dotnet\sdk]
>   2.1.302 [C:\Program Files\dotnet\sdk]
>   2.1.402 [C:\Program Files\dotnet\sdk]
>   2.1.403 [C:\Program Files\dotnet\sdk]
>   2.1.500 [C:\Program Files\dotnet\sdk]
>   2.1.600-preview-009472 [C:\Program Files\dotnet\sdk]
>   2.1.600-preview-009497 [C:\Program Files\dotnet\sdk]
>   2.2.100-preview2-009404 [C:\Program Files\dotnet\sdk]
>   2.2.100-preview3-009430 [C:\Program Files\dotnet\sdk]
>   2.2.100 [C:\Program Files\dotnet\sdk]
>   2.2.200-preview-009748 [C:\Program Files\dotnet\sdk]
>   2.2.200-preview-009804 [C:\Program Files\dotnet\sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.2.0-preview2-35157 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.2.0-preview3-35497 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.2.0-preview2-35157 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.2.0-preview3-35497 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.2.0-preview2-26905-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.2.0-preview3-27014-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

* Contents of project.json/project.csproj: 

> <Project Sdk="Microsoft.NET.Sdk">
>   <PropertyGroup>
>     <TargetFramework>netcoreapp2.2</TargetFramework>
>     <GenerateDocumentationFile>true</GenerateDocumentationFile>
>     <NoWarn>$(NoWarn);1591</NoWarn>
>     <Version>1.0.166</Version>
>     <Authors></Authors>
>     <Company>VOG</Company>
>     <Product>Backend Core</Product>
>     <Description>Core features and boilerplate code for backend development</Description>
>     <PackageReleaseNotes>Attempt to optimize CrudRepository</PackageReleaseNotes>
>     <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
>     <IncludeSymbols>True</IncludeSymbols>
>     <Copyright>#</Copyright>
>   </PropertyGroup>
>   <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
>     <DocumentationFile>bin\Debug\netcoreapp2.2\VOGBackend.Core.xml</DocumentationFile>
>   </PropertyGroup>
>   <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
>     <DocumentationFile>bin\Release\netcoreapp2.2\VOGBackend.Core.xml</DocumentationFile>
>   </PropertyGroup>
>   <ItemGroup>
>     <PackageReference Include="AspNetCoreRateLimit" Version="2.1.0" />
>     <PackageReference Include="AWSSDK.Core" Version="3.3.31.9" />
>     <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.3.17.7" />
>     <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.3.6" />
>     <PackageReference Include="AWSSDK.PinpointSMSVoice" Version="3.3.2.4" />
>     <PackageReference Include="AWSSDK.S3" Version="3.3.31.17" />
>     <PackageReference Include="AWSSDK.SimpleEmail" Version="3.3.7.32" />
>     <PackageReference Include="AWSSDK.SimpleNotificationService" Version="3.3.3.20" />
>     <PackageReference Include="AWSSDK.SimpleSystemsManagement" Version="3.3.38.6" />
>     <PackageReference Include="BouncyCastle.NetCore" Version="1.8.3" />
>     <PackageReference Include="DatatablesParser-core" Version="1.2.3" />
>     <PackageReference Include="DotNetCore.NPOI" Version="1.2.1" />
>     <PackageReference Include="Microsoft.AspNetCore.All" Version="2.2.2" />
>     <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="2.2.0" />
>     <PackageReference Include="Newtonsoft.Json" Version="12.0.1" />
>     <PackageReference Include="PreMailer.Net" Version="2.0.1" />
>     <PackageReference Include="SixLabors.ImageSharp" Version="1.0.0-beta0005" />
>     <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="1.0.0-beta0005" />
>     <PackageReference Include="Stripe.net" Version="23.0.0" />
>     <PackageReference Include="Swashbuckle.AspNetCore" Version="4.0.1" />
>     <PackageReference Include="TimeZoneConverter" Version="2.5.1" />
>     <PackageReference Include="WindowsAzure.Storage" Version="9.3.3" />
>   </ItemGroup>
>   <ItemGroup>
>     <Folder Include="Utilities\Crypto\" />
>     <Folder Include="ViewModels\Users\" />
>   </ItemGroup>
> </Project>

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by BradVog** [comment]
Followup:
I pulled the code and changed  `application/x-amz-json-1.1` to  `application/json` it fixed the issue for me. Obviously this code seems generated from an external source, but until this is fixed I'm able to use my local build.

**Comment by danielmarbach** [comment]
If I'm not mistaken the schemas are here https://github.com/aws/aws-sdk-net/tree/master/generator/ServiceModels/pinpoint. So if you find the json schema that is used for that call you can tweak that schema and then run the generator. This fixes then the generated code

**Comment by normj** [comment]
Thanks for reporting the issue. I'll take a look into the issue.

**Comment by normj** [comment]
We have identified the bug in the code generator that is causing the incorrect content-type being set. The change is going to affect more than just this service call so it is going to take a bit to test the fix.

**Comment by sstevenkang** [comment]
This is fixed in https://github.com/aws/aws-sdk-net/commit/aa7b4e61b0030dcfcd924a8f1368608dcaf3fbb8 with a new releases of ```AWSSDK.Pinpoint 3.3.13.1``` and ```AWSSDK.Core 3.3.32``` Please let us know if the issue persists.
