### ISSUE TITLE
Different exception behavior when creating clients between full framework and .net core

### ISSUE THREAD

**Issue by danielmarbach** [aws/aws-sdk-net#1216]
When creating a client, for example with

```
new AmazonSqsClient();
```

if now credentials or region are available the above code throw an `AmazonClientException` on the full framework but an `HttpRequestException` on .NET Core. The problem with the `HttpRequestException` is that it is in System.Net.Http and would require to add a reference to that package just to be able to handle it. Ideally, the client would throw `AmazonClientException ` on both frameworks. 

## Expected Behavior

Throw `AmazonClientException` for client configuration problems on both frameworks

## Current Behavior

.NET Core throws `HttpRequestException` while full framework throws `AmazonClientException `

## Steps to Reproduce (for bugs)

Without any credentials available

```
new AmazonSqsClient();
```

run on full framework --> throws an AmazonClientException
run on .net core 2.1 --> throw an HttpRequestException

## Context

At the moment we are forced to handle this behavior with a generic exception catch because we don't want to take a reference to System.NET.Http just to be able to guard against HttpRequestException

## Your Environment

* AWSSDK.Core version used: latest
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: Fullframework 4.6.1 and Net core 2.1.x

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
Hi @danielmarbach, thank you for the feedback on this.  I can address this with the team, but my guess is that anything that is already implemented will not be synced to avoid issues with breaking changes.

**Comment by sstevenkang** [comment]
What were the exception messages?  I am curious as to where this branching is happening.

**Comment by danielmarbach** [comment]
@sstevenkang It is a bit embarrassing but I can't repro it anymore. That is one of the downsides of transitive dependencies with the new csproj :( I guess I'm closing it for now until I have further intel
