### ISSUE TITLE
How do you force a disconnect of a websocket connection in API Gateway?

### ISSUE THREAD

**Issue by ThomasJaeger** [aws/aws-sdk-net#1217]
I need to be able to disconnect websocket connections in API Gateway using the `ApiGatewayManagementApi`. I don't see any other commands besides the `PostToConnectionRequest`.

Is this possible? If not, why not?

**Comment by sstevenkang** [comment]
ApiGatewayManagementApi is a relatively new service.  This is not possible today.

**Comment by VagabondOfHell** [comment]
Are there any plans to add this functionality in?

**Comment by thiskevinwang** [comment]
2021 coming in hot! Any way to dd this today?
