### ISSUE TITLE
S3EventNotification.ParseJson fails to parse S3ObjectEntity with size greater than Int32.MaxValue 

### ISSUE THREAD

**Issue by nicolas-alie** [aws/aws-sdk-net#1219]
## Expected Behavior

`S3EventNotification.ParseJson` should be able to parse a S3EventNotification containing an object with size greater than 2147483647

## Current Behavior

Calling `S3EventNotification.ParseJson` on a event with a S3ObjectEntity containing a size greater than 2147483647 will throw:
```
Amazon.Runtime.AmazonClientException: Failed to parse json string: Instance of JsonData doesn't hold an long ---> System.InvalidCastException: Instance of JsonData doesn't hold an long
   at ThirdParty.Json.LitJson.JsonData.op_Explicit(JsonData data)
   at Amazon.S3.Util.S3EventNotification.GetValueAsLong(JsonData data, String key)
   at Amazon.S3.Util.S3EventNotification.ParseJson(String json)
```

## Steps to Reproduce (for bugs)

```
var body = "{\"Records\":[{\"eventName\":\"ObjectCreated:CompleteMultipartUpload\",\"s3\":{\"object\":{\"size\":2686759848}}}]}";
var eventNotification = S3EventNotification.ParseJson(body);
```

## Context

We can't use the util ParseJson anymore since we have to support uploads bigger than 2GB.
Workaround using another json parser.

## Your Environment

* AWSSDK.Core version used: 3.3.31.12
* Service assembly and version used: AWSSDK.S3 3.3.31.20 
* Operating System and version: Windows 10
* Visual Studio version:  Visual Studio 15.9.2
* Targeted .NET platform:  netcoreapp2.0

## .NET Core Info

* .NET Core version used for development: aspnetcore:2.0.6
* .NET Core version installed in the environment where application runs: aspnetcore:2.0.6
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
Hi @nicolas-alie, thank you for alerting us to this.   We'll get it fixed very soon.

**Comment by nelsonchristopher-dj** [comment]
Any update on this @klaytaybai ?

**Comment by Gr1mR3aver** [comment]
Any update on this?  currently a blocking issue for us on an automated process.

**Comment by mcblair** [comment]
Still a thing.

**Comment by mandertDowJones** [comment]
Per https://github.com/aws/aws-sdk-net/blob/master/SDK.CHANGELOG.md#35781-2020-12-21-2307-utc and https://github.com/aws/aws-sdk-net/commit/83cf981226ad3c9e9598d7a5d461fb63566b26b9#diff-248eb843e3f77d35ea7e3b52e92a2499116ea91bf1f2f5536950bac4f4c016b8 this is fixed now, right?

**Comment by ashishdhingra** [comment]
> Per https://github.com/aws/aws-sdk-net/blob/master/SDK.CHANGELOG.md#35781-2020-12-21-2307-utc and [83cf981#diff-248eb843e3f77d35ea7e3b52e92a2499116ea91bf1f2f5536950bac4f4c016b8](https://github.com/aws/aws-sdk-net/commit/83cf981226ad3c9e9598d7a5d461fb63566b26b9#diff-248eb843e3f77d35ea7e3b52e92a2499116ea91bf1f2f5536950bac4f4c016b8) this is fixed now, right?

Hi @nicolas-alie,

Please review @mandertDowJones comment. This should be fixed in the latest version. Kindly verify and confirm at your end.

Thanks,
Ashish

**Comment by nicolas-alie** [comment]
It is fixed, tested with awssdk.s3\3.5.8.5
thanks
