### ISSUE TITLE
Amazon.S3.Model.GetObjectResponse does not expose Content-Range header

### ISSUE THREAD

**Issue by eangelov** [aws/aws-sdk-net#1221]
Hi, I am working on updating an old aspx page that returns part(s) of a specific object in specific bucket. 
Current implementation of the page makes request to s3 directly via HttpWebRequest and uses the  Content-Range header returned in WebResponse. 

I am trying to remove the direct call to HttpWebRequest and start using aws-sdk-net, but i cannot fint the Content-Range header anywhere on GetObjectResponse when performing a GetObjectRequest.

**Comment by klaytaybai** [comment]
Hi @eangelov, thank you for alerting us to this.  I've identified the issue.  I'll let you know when a fix is released.

**Comment by eangelov** [comment]
Hi @klaytaybai, is there an ETA for this issue ?
