### ISSUE TITLE
Encryption Client Support

### ISSUE THREAD

**Issue by shaikatz** [aws/aws-sdk-net#1223]
Hi

I would like to encrypt data using the following [guide](https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/getting-started.html)

I can't find a suitable client for .NET, there are any plans to implement that?

Thanks

**Comment by sstevenkang** [comment]
The Encryption SDK is something that is not related to AWS SDK.  It is a separate team that owns it.  I'll forward this ask to the team :).

**Comment by lizroth** [comment]
@shaikatz

Thank you for reaching out! AWS Encryption SDK support for .NET is on our roadmap, but I do not have specific dates at this time.

We have the AWS Encryption SDK for C available in public preview if exploring that option might help you in the meantime.

https://github.com/awslabs/aws-encryption-sdk-c

**Comment by shaikatz** [comment]
Thanks
