### ISSUE TITLE
Connect to SQS through VPC endpoint

### ISSUE THREAD

**Issue by s3er** [aws/aws-sdk-net#1225]
I want to connect to SQS from an EC2 instance through a VPC endpoint from a network which has no internet connection.  I setup everything according to the documentation but somehow the dns for sqs.***.amazonaws.com is still resolving to the public IP and not the vpce one which it should. I'm still analyzing this DNS troubles.

Nevertheless I would like to request a method to explicitly define the endpoint url. For example in the aws-cli command I can do it like:
`aws sqs receive-message --region *** --endpoint-url https://vpce-***.sqs.***.vpce.amazonaws.com/ --queue-url https://sqs.***.amazonaws.com/***/***`

That would also solve my next problem: I want the connection to SQS go from my local LAN via private link to the VPC and than to the endpoint. This would be possible if I could define the endpoint.

## Expected Behavior
Use custom endpoint url.

## Current Behavior
SDK is always using sqs.***.amazonaws.com.

## Possible Solution
- use endpoint from queue url
- explicitly define the endpoint

## Steps to Reproduce (for bugs)
Try to connect via vpce when sqs.***.amazonaws.com is resolving to public ip.

## Context
I want the connection to SQS go from my local LAN via private link to the VPC and than to the endpoint. This would be possible if I could define the endpoint.

## Your Environment
* AWSSDK.Core version used:  3.3.0.0
* Service assembly and version used: 
* Operating System and version: Windows Server 2016
* Visual Studio version: 2017
* Targeted .NET platform: 4.5.2

**Comment by klaytaybai** [comment]
Hi @s3er, in the .NET SDK, you can override endpoints using the client configuration's ServiceURL property.   Here is an example:

```          
AmazonSQSConfig sqsConfig = new AmazonSQSConfig()
{
    ServiceURL = "https://vpce-***.sqs.***.vpce.amazonaws.com"
};
using (var client = new AmazonSQSClient(sqsConfig))
{
    ...
}
```

Also see this [blog post](https://aws.amazon.com/blogs/developer/overriding-endpoints-in-the-aws-sdk-for-net/)

**Comment by s3er** [comment]
I tried this before but got the following exception:
`Amazon.SQS.AmazonSQSException: Credential should be scoped to a valid region, not 'vpce'.  ---> Amazon.Runtime.Internal.HttpErrorResponseException: Der Remoteserver hat einen Fehler zurückgegeben: (403) Unzulässig. ---> System.Net.WebException: Der Remoteserver hat einen Fehler zurückgegeben: (403) Unzulässig.`

**Comment by wzowee** [comment]
Having a similar issue connecting to Codepipeline via the SDK and a VPC Endpoint.

Receiving the message "Credential should be scoped to a valid region, not 'vpce'." Config looks like, have also tried without specifying the RegionEndpoint - same error

```
var config = new AmazonCodePipelineConfig {
   RegionEndpoint = RegionEndpoint.APSoutheast2,
   ServiceURL = "https://vpce-XXXXXXXXXXXXXXXX.codepipeline.ap-southeast-2.vpce.amazonaws.com"
};
```

**Comment by wzowee** [comment]
For reference my issue was a config one, when using a VPC endpoint the AuthenticationRegion property needed to be set. 

```
            var config = new AmazonCodePipelineConfig {
                AuthenticationRegion = RegionEndpoint.APSoutheast2.SystemName,
                ServiceURL = "https://vpce-XXXXXXXXXXXXXXXX.codepipeline.ap-southeast-2.vpce.amazonaws.com"
            };
```

**Comment by rustyforeal** [comment]
> I tried this before but got the following exception:
> `Amazon.SQS.AmazonSQSException: Credential should be scoped to a valid region, not 'vpce'. ---> Amazon.Runtime.Internal.HttpErrorResponseException: Der Remoteserver hat einen Fehler zurückgegeben: (403) Unzulässig. ---> System.Net.WebException: Der Remoteserver hat einen Fehler zurückgegeben: (403) Unzulässig.`

any progress with this? I am getting the same exact error message . Dropped the authentication region, dropped the RegionEndpoint properties but still the same issue. The ServiceURL points to the VPCE DNS preceded by a https:// - any ideas ?

**Comment by y-ohno-p** [comment]
This is worked for me, but I am not sure if it is appropriate. (`ap-northeast-1.queue.amazonaws.com` is legacy endpoint.)

```csharp
var config = new AmazonSQSConfig()
{
  ServiceURL = "https://ap-northeast-1.queue.amazonaws.com",
};
using var sqsClient = new AmazonSQSClient(credentials, config);
var message = await client.ReceiveMessageAsync(new ReceiveMessageRequest
{
  QueueUrl = "https://sqs.ap-northeast-1.amazonaws.com/{id}/my-queue"
});
```
