### ISSUE TITLE
[Unity] CreateBatchWrite says ArgumentNullException: Value cannot be null.

### ISSUE THREAD

**Issue by elritualk** [aws/aws-sdk-net#1226]
Im on Unity 2018.3.6f1, using AWSSDK.DynamoDBv2.3.3.17.11.unitypackage.

```
Amazon DynamoDBClient dbClient = new AmazonDynamoDBClient(awsCredentials, endpoint);
DynamoDBContext dbContext = new DynamoDBContext(dbClient);
var companyBatch = dbContext.CreateBatchWrite<CompanyDataDB>();
```

This last line throws me:
ArgumentNullException: Value cannot be null.

## What im trying to do?
Simply create a CreateBatchWrite, next put some items and then call Execute. But I got the mentioned error on CreateBatchWrite step.

## Full Error Log
ArgumentNullException: Value cannot be null.
Parameter name: key
System.Collections.Generic.Dictionary`2[TKey,TValue].FindEntry (TKey key) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].TryGetValue (TKey key, TValue& value) (at <d7ac571ca2d04b2f981d0d886fa067cf>:0)
Amazon.Runtime.Internal.ErrorHandler.ProcessException (Amazon.Runtime.IExecutionContext executionContext, System.Exception exception) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/ErrorHandler/ErrorHandler.cs:202)
Amazon.Runtime.Internal.ErrorHandler.InvokeSync (Amazon.Runtime.IExecutionContext executionContext) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/ErrorHandler/ErrorHandler.cs:78)
Amazon.Runtime.Internal.PipelineHandler.InvokeSync (Amazon.Runtime.IExecutionContext executionContext) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/PipelineHandler.cs:57)
Amazon.Runtime.Internal.CallbackHandler.InvokeSync (Amazon.Runtime.IExecutionContext executionContext) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/CallbackHandler.cs:45)
Amazon.Runtime.Internal.PipelineHandler.InvokeSync (Amazon.Runtime.IExecutionContext executionContext) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/PipelineHandler.cs:57)
Amazon.Runtime.Internal.Signer.InvokeSync (Amazon.Runtime.IExecutionContext executionContext) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/Signer.cs:38)
Amazon.Runtime.Internal.PipelineHandler.InvokeSync (Amazon.Runtime.IExecutionContext executionContext) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/PipelineHandler.cs:57)
Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeSync (Amazon.Runtime.IExecutionContext executionContext) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/EndpointDiscoveryHandler.cs:54)
Amazon.Runtime.Internal.PipelineHandler.InvokeSync (Amazon.Runtime.IExecutionContext executionContext) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/PipelineHandler.cs:57)
Amazon.Runtime.Internal.CredentialsRetriever.InvokeSync (Amazon.Runtime.IExecutionContext executionContext) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/CredentialsRetriever.cs:72)
Amazon.Runtime.Internal.PipelineHandler.InvokeSync (Amazon.Runtime.IExecutionContext executionContext) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/PipelineHandler.cs:57)
Amazon.Runtime.Internal.RetryHandler.InvokeSync (Amazon.Runtime.IExecutionContext executionContext) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/RetryHandler/RetryHandler.cs:84)
Amazon.Runtime.Internal.PipelineHandler.InvokeSync (Amazon.Runtime.IExecutionContext executionContext) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/PipelineHandler.cs:57)
Amazon.Runtime.Internal.CallbackHandler.InvokeSync (Amazon.Runtime.IExecutionContext executionContext) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/CallbackHandler.cs:45)
Amazon.Runtime.Internal.PipelineHandler.InvokeSync (Amazon.Runtime.IExecutionContext executionContext) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/PipelineHandler.cs:57)
Amazon.Runtime.Internal.EndpointResolver.InvokeSync (Amazon.Runtime.IExecutionContext executionContext) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/EndpointResolver.cs:34)
Amazon.Runtime.Internal.PipelineHandler.InvokeSync (Amazon.Runtime.IExecutionContext executionContext) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/PipelineHandler.cs:57)
Amazon.Runtime.Internal.Marshaller.InvokeSync (Amazon.Runtime.IExecutionContext executionContext) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/Marshaller.cs:37)
Amazon.Runtime.Internal.PipelineHandler.InvokeSync (Amazon.Runtime.IExecutionContext executionContext) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/PipelineHandler.cs:57)
Amazon.Runtime.Internal.CallbackHandler.InvokeSync (Amazon.Runtime.IExecutionContext executionContext) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/CallbackHandler.cs:45)
Amazon.Runtime.Internal.PipelineHandler.InvokeSync (Amazon.Runtime.IExecutionContext executionContext) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/PipelineHandler.cs:57)
Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync (Amazon.Runtime.IExecutionContext executionContext) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/ErrorCallbackHandler.cs:44)
Amazon.Runtime.Internal.PipelineHandler.InvokeSync (Amazon.Runtime.IExecutionContext executionContext) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/PipelineHandler.cs:57)
Amazon.Runtime.Internal.MetricsHandler.InvokeSync (Amazon.Runtime.IExecutionContext executionContext) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/MetricsHandler.cs:40)
Amazon.Runtime.Internal.PipelineHandler.InvokeSync (Amazon.Runtime.IExecutionContext executionContext) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/PipelineHandler.cs:57)
Amazon.Runtime.Internal.RuntimePipeline.InvokeSync (Amazon.Runtime.IExecutionContext executionContext) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Pipeline/RuntimePipeline.cs:135)
Amazon.Runtime.AmazonServiceClient.Invoke[TResponse] (Amazon.Runtime.AmazonWebServiceRequest request, Amazon.Runtime.Internal.InvokeOptionsBase options) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/AmazonServiceClient.cs:217)
Amazon.DynamoDBv2.AmazonDynamoDBClient.DescribeTable (Amazon.DynamoDBv2.Model.DescribeTableRequest request) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Services/DynamoDBv2/Generated/_unity/AmazonDynamoDBClient.cs:1478)
Amazon.DynamoDBv2.DocumentModel.Table.DescribeTable (System.String tableName) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Services/DynamoDBv2/Custom/DocumentModel/Table.cs:330)
Amazon.Runtime.Internal.Util.Cache`2[TKey,TValue].GetValueHelper (TKey key, System.Boolean& isStaleItem, System.Func`2[T,TResult] creator) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Internal/Util/SdkCache.cs:428)
Amazon.Runtime.Internal.Util.Cache`2[TKey,TValue].GetValue (TKey key, System.Func`2[T,TResult] creator, System.Boolean& isStaleItem) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Core/Amazon.Runtime/Internal/Util/SdkCache.cs:315)
Amazon.DynamoDBv2.DocumentModel.Table.LoadTableInfo () (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Services/DynamoDBv2/Custom/DocumentModel/Table.cs:133)
Amazon.DynamoDBv2.DocumentModel.Table.LoadTable (Amazon.DynamoDBv2.IAmazonDynamoDB ddbClient, Amazon.DynamoDBv2.DocumentModel.TableConfig config) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Services/DynamoDBv2/Custom/DocumentModel/Table.cs:407)
Amazon.DynamoDBv2.DataModel.DynamoDBContext.GetUnconfiguredTable (System.String tableName) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Services/DynamoDBv2/Custom/DataModel/ContextInternal.cs:130)
Amazon.DynamoDBv2.DataModel.DynamoDBContext.GetTargetTable (Amazon.DynamoDBv2.DataModel.ItemStorageConfig storageConfig, Amazon.DynamoDBv2.DataModel.DynamoDBFlatConfig flatConfig, Amazon.DynamoDBv2.DocumentModel.Table+DynamoDBConsumer consumer) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Services/DynamoDBv2/Custom/DataModel/ContextInternal.cs:111)
Amazon.DynamoDBv2.DataModel.BatchWrite`1[T]..ctor (Amazon.DynamoDBv2.DataModel.DynamoDBContext context, Amazon.DynamoDBv2.DataModel.DynamoDBFlatConfig config) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Services/DynamoDBv2/Custom/DataModel/BatchWrite.cs:199)
Amazon.DynamoDBv2.DataModel.DynamoDBContext.CreateBatchWrite[T] (Amazon.DynamoDBv2.DataModel.DynamoDBOperationConfig operationConfig) (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Services/DynamoDBv2/Custom/DataModel/Context.cs:225)
Amazon.DynamoDBv2.DataModel.DynamoDBContext.CreateBatchWrite[T] () (at D:/JenkinsWorkspaces/trebuchet-stage-release/AWSDotNetPublic/sdk/src/Services/DynamoDBv2/Custom/DataModel/Context.cs:212)
CompanyManager.Crear () (at Assets/Scripts/CompanyManager.cs:78)
UnityEngine.Events.InvokableCall.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:166)
UnityEngine.Events.UnityEvent.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnityEvent_0.cs:58)
UnityEngine.UI.Button.Press () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Button.cs:66)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Button.cs:108)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:50)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:261)
UnityEngine.EventSystems.EventSystem:Update()

## Your Environment

* Unity 2018.3.6f1
* AWSSDK.DynamoDBv2.3.3.17.11.unitypackage

**Comment by klaytaybai** [comment]
Hi @elritualk, what is the value of your endpoint?

**Comment by elritualk** [comment]
> Hi @elritualk, what is the value of your endpoint?

Hi! the value is RegionEndpoint.USWest2. I think is fine, I can operate with the database. The only thing that I cant do is:

var companyBatch = dbContext.CreateBatchWrite<CompanyDataDB>();

If I dont use dbContext and I use dbClient works good with:
...
LoginManager.dbClient.BatchWriteItemAsync(request, BatchWriteCallback);

**Comment by Patryk-Szylin** [comment]
@elritualk I just stumbled on the same issue. Did you manage to fix it in the end? 

I'd rather the context object than the client. 

thanks

**Comment by elritualk** [comment]
@Patryk-Szylin I revised my AWS testing project and the answer is **no**. Im still using AWSManager.dbClient.BatchWriteItemAsync(request, Callback) method.

**Comment by Patryk-Szylin** [comment]
@elritualk I managed to use DBContext to fetch data from my database. Refer to the snippet of code, I hope you find it helpful.

`         List<Game> games = new List<Game>();
            context.FromScanAsync<Game>(new ScanOperationConfig(), new DynamoDBOperationConfig(), (search) =>
            {
                search.Result.GetRemainingAsync((res) =>
                {
                    foreach (var item in res.Result)
                    {
                        print(item.Date);
                        games.Add(item);
                    }
                });
            });`

**Comment by Patryk-Szylin** [comment]
@elritualk I managed to pull database documents using AmazonDBContext. Refer to the snippet below. I hope you find it useful.

```csharp
         List<Game> games = new List<Game>();
            context.FromScanAsync<Game>(new ScanOperationConfig(), new DynamoDBOperationConfig(), (search) =>
            {
                if (search.Exception != null)
                    print(search.Exception.Message);

                search.Result.GetRemainingAsync((res) =>
                {
                    foreach (var item in res.Result)
                    {
                        print(item.Date);
                        games.Add(item);
                    }
                });
            });
```
