### ISSUE TITLE
Visibility of Amazon.S3.Transfer.TransferUtilityDownloadDirectoryRequest.DownloadFilesConcurrently is internal for in dotnet core

### ISSUE THREAD

**Issue by sqdk** [aws/aws-sdk-net#1227]
I am using the S3 client on dotnet core, and I am unable to set the values for concurrency and buffer size 
in both `TransferUtilityDownloadDirectoryRequest` and `TransferUtilityUploadDirectoryRequest`

Is there a reason for this? If so, is there any alternative way of tuning concurrency when using the library in dotnet core?

This is the offending code: 

https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/S3/Custom/_bcl%2Bcoreclr%2Bpcl/Transfer/_bcl%2Bcoreclr/TransferUtilityDownloadDirectoryRequest.cs#L231

https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/S3/Custom/_bcl%2Bcoreclr%2Bpcl/Transfer/_bcl%2Bcoreclr/TransferUtilityUploadDirectoryRequest.cs#L269

## Expected Behavior
I expect `UploadFilesConcurrently` to be visible from my code. It isn't.

## Current Behavior
`UploadFilesConcurrently` is not configurable from m code.

## Possible Solution
Change visibility from internal to public. Alternatively, explicitly set it to public for dotnet core.

## Context
I am trying to reach the same level of performance for uploads that the CLI tool gives. Especially for large amounts of small files, the CLI tool is 7x faster than the library on dotnet core. I suspect that tweaking the concurrency parameters might yield results that are better.

## Your Environment
* AWSSDK.Core version used: 3.3.31.22 
* Service assembly and version used: 3.3.31.22
* Operating System and version: Ubuntu 18.04
* Visual Studio version: N/A
* Targeted .NET platform: .NET Core 2.1

## .NET Core Info

* .NET Core version used for development: 2.1
* .NET Core version installed in the environment where application runs: 2.1
* Output of `dotnet --info`: 
```
dotnet --info   
.NET Core SDK (reflecting any global.json):
 Version:   2.2.104
 Commit:    73f036d4ac

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.104/

Host (useful for support):
  Version: 2.2.2
  Commit:  a4fd7b2c84

.NET Core SDKs installed:
  2.1.402 [/usr/share/dotnet/sdk]
  2.1.504 [/usr/share/dotnet/sdk]
  2.2.100 [/usr/share/dotnet/sdk]
  2.2.104 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

* Contents of project.json/project.csproj: 
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Utilities.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FSharpPlus" Version="1.0.0" />
    <PackageReference Include="Giraffe" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.0.3" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="2.0.2" />
    <PackageReference Include="Microsoft.OData.Core" Version="7.4.4" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
    <PackageReference Include="NodaTime" Version="2.2.6" />
    <PackageReference Include="Npgsql" Version="3.2.7" />
    <PackageReference Include="prometheus-net.AspNetCore" Version="2.1.3" />
    <PackageReference Include="Unity.CDS.FSharpUtilities" Version="1.5.31391" />
    <PackageReference Include="AWSSDK.S3" Version="3.3.31.22" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\jobdefinition\src\Unity.Yamato.JobDefinition\Unity.Yamato.JobDefinition.fsproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="BackendClients\" />
  </ItemGroup>
</Project>
```

**Comment by glaxaco** [comment]
I am running into similar problems attempting to migrate some S3 code from a .NET Framework project to .NET Standard 2.0.

**Comment by ichimura-k** [comment]
Since 3.3.611.0, TransferUtilityUploadDirectoryRequest.UploadFilesConcurrently is public by 777ac25794e3f79ad38d258d8e486b5c3f4cca82, so #1404 may be closed. But TransferUtilityDownloadDirectoryRequest.DownloadFilesConcurrently is still internal.

**Comment by ashishdhingra** [comment]
Merged as a part of PR https://github.com/aws/aws-sdk-net/pull/1719. Please upgrade to latest version.
