### ISSUE TITLE
SQS SendMessage is returning HttpStatusCode OK, but sometimes never makes it in the Queue

### ISSUE THREAD

**Issue by nwestfall** [aws/aws-sdk-net#1228]
When sending messages to a FIFO SQS, sometimes the message will never get sent even though it returns an `OK`

## Expected Behavior
If `OK` is returned, the message makes it in the queue.

## Current Behavior
```c#
SendMessageRequest message = new SendMessageRequest();
message.MessageBody = json;
message.MessageDeduplicationId = Guid.NewGuid().ToString();
message.MessageAttributes.Add("ModelType", new MessageAttributeValue() { DataType = "String", StringValue = "MyModel" });
message.QueueUrl = MY_QUEUE_URL;
message.MessageGroupId = "1";
var response = queueClient.SendMessageAsync(message);
if(response.HttpStatusCode == HttpStatusCode.OK)
    Console.WriteLine("Message Sent!");
else
    Console.WriteLine("Message not Sent!"); // Never makes it here
```

Here is a request with AWS logging that got an `OK` back, but never made it to the queue.
```
AmazonSQSClient 8|2019-03-08T23:07:31.590Z|DEBUG|Received response (truncated to 1024 bytes): [<?xml version="1.0"?><SendMessageResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><SendMessageResult><MessageId>d6f9a73c-595c-453c-960e-2d4e4c78b110</MessageId><MD5OfMessageBody>28c7e6cb4d54e96e9500cf28e851b2b9</MD5OfMessageBody><MD5OfMessageAttributes>1f348101a0132cca03b9a1b7fdd33ca6</MD5OfMessageAttributes><SequenceNumber>37290826887017439232</SequenceNumber></SendMessageResult><ResponseMetadata><RequestId>d46d7ab1-1f24-570d-adfc-2e4c21670e8a</RequestId></ResponseMetadata></SendMessageResponse>]
```

## Context
Maybe I'm missing something with FIFO, but I have a new `MessageDeduplicationId` on each message and even though I get `OK` back, the message doesn't make it in sometimes.  The percentage of failures is about 40%.  Most of the time, from a "cold" start.

## Your Environment

* AWSSDK.SQS version used: 3.3.3.55
* Service assembly and version used: netstandard2.0/netcore2.1
* Operating System and version: macOS (also happens in production on lambda)

## .NET Core Info
* Output of `dotnet --info`: 
.NET Core SDK (reflecting any global.json):
 Version:   2.1.504
 Commit:    91e160c7f0

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.504/

Host (useful for support):
  Version: 3.0.0-preview-27324-5
  Commit:  63a01b08e5

.NET Core SDKs installed:
  1.0.4 [/usr/local/share/dotnet/sdk]
  2.0.0 [/usr/local/share/dotnet/sdk]
  2.1.4 [/usr/local/share/dotnet/sdk]
  2.1.104 [/usr/local/share/dotnet/sdk]
  2.1.300 [/usr/local/share/dotnet/sdk]
  2.1.301 [/usr/local/share/dotnet/sdk]
  2.1.302 [/usr/local/share/dotnet/sdk]
  2.1.504 [/usr/local/share/dotnet/sdk]
  2.2.104 [/usr/local/share/dotnet/sdk]
  3.0.100-preview-010184 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-19075-0444 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27324-5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
* Contents of project.json/project.csproj: 
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <LangVersion>Latest</LangVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <LangVersion>Latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.3.17.5" />
    <PackageReference Include="AWSSDK.SQS" Version="3.3.3.55" />
    <PackageReference Include="Microsoft.Azure.DocumentDB.Core" Version="2.1.3" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="2.1.0" />
    <PackageReference Include="MongoDB.Driver" Version="2.7.2" />
    <PackageReference Include="Microsoft.Azure.ServiceBus" Version="3.3.0" />
    <PackageReference Include="stackexchange.redis" Version="2.0.545" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="MyProject.csproj" />
  </ItemGroup>
</Project>
```

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by indy-singh** [comment]
How is the queue configured on AWS? There are two types of FIFO queues IIRC. Content based deduplication or providing a deduplication ID.

**Comment by nwestfall** [comment]
From my understanding, this isn't a configuration is just how you send the message.

https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/using-messagededuplicationid-property.html 

If you send the message with a `MessageDeduplicationId`, it uses that.  If you don't then it's content based.

As you can see from the example, I have a new `MessageDeduplicationId` per message.

**Comment by klaytaybai** [comment]
Hi @nwestfall, this doesn't seem to be an issue with the .NET SDK, so I'm going to close it out.  Please try seeing if you can get a response through the [AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=12)
