### ISSUE TITLE
InvalidCastException in JsonData(object obj) when object is int, uint, or long

### ISSUE THREAD

**Issue by TheEdgeWalker** [aws/aws-sdk-net#1230]
JsonData(object obj) causes exceptions when object is int, uint, or long.
This exception happens because you cannot directly cast an non-ulong object into a ulong.

## Expected Behavior
JsonData should correctly cast object to respective types.

## Current Behavior
The following code snippet causes InvalidCastException
```
int i = -10;
object o = i;
var data = new JsonData(o); // InvalidCastException 
```
Refer to the following MSDN document for why this happens
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/types/boxing-and-unboxing

## Possible Solution
We did something like this inside JsonData(object obj)
```
            if (obj is Int32) {
                type = JsonType.Int;
                int i = (int)obj;
                inst_number = (ulong)i;
                return;
            }
```
object -> int -> ulong

## Steps to Reproduce (for bugs)
```
int i = -10;
object o = i;
var data = new JsonData(o); // InvalidCastException 
```

## Context
I am trying to serialize a class into JSON. The type to be converted to JSON is undetermined at compile time (I am using generics), so JsonData(object obj) is used.

## Your Environment
* AWSSDK.Core version used: 3.3.22.2
* Operating System and version: Windows 10, Unity 2017.4.21f1
* Targeted .NET platform: 3.5, 4.6

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by sstevenkang** [comment]
I would urge you to take a dependency on https://www.nuget.org/packages/Newtonsoft.Json/ directly.  The JSON library in the .NET SDK is modified to meet the SDK needs and is quite a bit outdated.  We made this decision to avoid introducing a dependency conflict.
