### ISSUE TITLE
AWSSDK.Extensions.NETCore.Setup 3.3.100 broke TryAddAWSService on netcoreapp2.1

### ISSUE THREAD

**Issue by jasonycw** [aws/aws-sdk-net#1232]
## Expected Behavior
We are using .NET Core 2.1 for our Lambda function and after today NuGet update `AWSSDK.Extensions.NETCore.Setup` to 3.3.100, `.TryAddAWSService` stop working with `IAmazonService` and cannot build our project

We expect it to build properly with out error

## Current Behavior
We are using DI with the following under our Lambda's `startup.cs`
``` C#
Configuration = new ConfigurationBuilder()
    .AddEnvironmentVariables()
    .Build();

_services = new ServiceCollection()
    ...
    .TryAddAWSService<IAmazonSQS>(new AWSOptions { Region = RegionEndpoint.APSoutheast1 })
    .TryAddAWSService<IAmazonS3>(new AWSOptions { Region = RegionEndpoint.APSoutheast1 });
```
These were working perfectly with `AWSSDK.Extensions.NETCore.Setup` version 3.3.6. 
But today after updating to 3.3.10, there is an error at ` ... AWSOptions { Region ... ` which said 

> The type 'RegionEndpoint' is defined in an assembly that is not referenced. You must add a reference to assembly 'AWSSDK.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null'.

If I change that to 
``` C#
_services = new ServiceCollection()
    ...
    .TryAddAWSService<IAmazonSQS>()
    ...
```
The error will point to `.TryAddAWSService` saying

> The type 'Amazon.SQS.IAmazonSQS' cannot be used as type parameter 'T' in the generic type or method 'ServiceCollectionExtensions.TryAddAWSService<T>(IServiceCollection, ServiceLifetime)'. There is no implicit reference conversion from 'Amazon.SQS.IAmazonSQS' to 'Amazon.Runtime.IAmazonService'.

We have tried `AWSSDK.S3` and `AWSSDK.SQS` with version 3.3.100 and the older version and it seems the issue only related to `AWSSDK.Extensions.NETCore.Setup` version 3.3.100

## Steps to Reproduce (for bugs)
Update `AWSSDK.Extensions.NETCore.Setup` to 3.3.100 through NuGet

## Your Environment

* AWSSDK.Core version used: 3.3.100
* Service assembly and version used: 3.3.100
* Operating System and version: Windows 10
* Visual Studio version: 16.0.0 RC.3
* Targeted .NET platform: Core 2.1

## .NET Core Info

* .NET Core version used for development: .NET Core 2.1
* .NET Core version installed in the environment where application runs: .NET Core 2.1
* Output of `dotnet --info`: 
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview3-010431
 Commit:    d72abce213

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview3-010431\

Host (useful for support):
  Version: 3.0.0-preview3-27503-5
  Commit:  3844df9537

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.600 [C:\Program Files\dotnet\sdk]
  2.1.601 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.2.100 [C:\Program Files\dotnet\sdk]
  2.2.102 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  2.2.105 [C:\Program Files\dotnet\sdk]
  2.2.200 [C:\Program Files\dotnet\sdk]
  2.2.201 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]
  3.0.100-preview3-010431 [C:\Program Files\dotnet\sdk]

....
```
* Contents of project.json/project.csproj: 
``` XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="1.1.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.Json" Version="1.5.0" />
    <PackageReference Include="Amazon.Lambda.SQSEvents" Version="1.1.0" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.3.100" />
    <PackageReference Include="AWSSDK.S3" Version="3.3.100" />
    <PackageReference Include="AWSSDK.SQS" Version="3.3.100" />
    <PackageReference Include="Dapper" Version="1.60.1" />
    <PackageReference Include="DotLiquid" Version="2.0.298" />
    <PackageReference Include="Ensure.That" Version="8.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="2.2.0" />
  </ItemGroup>

  ...

</Project>
```

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by normj** [comment]
Thanks for reporting the issue. I have reproduced the problem and working on a fix.

**Comment by normj** [comment]
I just pushed out version 3.3.100.1 that fixes the issue. Thanks again for reporting the issue and sorry for the inconvenience.

**Comment by jasonycw** [comment]
@normj Thanks, just pulled 3.3.100.1, seems working
