### ISSUE TITLE
System.InvalidOperationException: Number of hash keys on table [table-name] does not match number of hash keys on type

### ISSUE THREAD

**Issue by mciureanu** [aws/aws-sdk-net#1233]
Sometimes, when I do a simple scan operation, I get this error. Can't really reproduce it, it happens for a while, then everything is fine again. 

I am doing a simple scan like this:

_ddbContext.FromScanAsync<ClassifierModelRule>(new ScanOperationConfig()).GetNextSetAsync();

and I'm registering like I saw in an example like this:

                AWSConfigsDynamoDB.Context.TypeMappings[typeof(ClassifierModelRule)] = new Amazon.Util.TypeMapping(typeof(ClassifierModelRule), tableName);

(with a lock, since this is not thread safe, I guess it doesn't matter)

**Comment by klaytaybai** [comment]
Can you clarify what you mean by "happening for a while"?  Does it work on and off?  Did you change anything between it working and it not working?

**Comment by mciureanu** [comment]
Yes, sorry, it's really weird, it happens only for a particular table, and for a few minutes there are several occurrences, then I stop seeing this error. I have upgraded to the last version, and haven't seen it since then, so maybe it was fixed somehow, I don't know.

**Comment by klaytaybai** [comment]
I'm going to close this out due to inactivity and inability to reproduce.  If anybody finds a way to reproduce this better, let us know and we'll reopen it.
