### ISSUE TITLE
Does AWSSDK support multiple regions using SDK without having to pass credentials directly to client?

### ISSUE THREAD

**Issue by coultonluke** [aws/aws-sdk-net#1235]
Does the SDK support the ability to connect to multiple regions in .NET CORE without having to create a client and explicitly pass an access key and secret key?

## Expected Behavior

To connect to one region by specifying the profile name in the appsettings.json but also ad hock use the same credentials to connect to a different region connect to resources using the SDK without having to pass the access key and secret key in the code.

## Current Behavior

As far as I'm aware I have to create a new client and pass the credentials to it explicitly.

## Possible Solution

To automatically use the credentials that area already configured in the `Startup.cs` from the profile set in my appsettings.json file without but connect to a different region.

## Steps to Reproduce (for bugs)

I can see from the documentation that I can easily get a service (such as the IAmazonSimpleEmailService) by registering it in my ConfigureServices() as shown in the documentation. The documentation also suggests that you can create your own client and pass in a region, this is what I am currently trying to do:

**appsettings.json:**
```
"AWS": {
    "Profile": "development",
    "Region": "us-east-1"
}
```

**My implementation:**
```
public class SendEmailService
{
    public async Task SendEmail()
    {
            // Set the email destination options
            var destination = new Destination
            {
                ToAddresses = new List<string> { "emailto@example.com" }
            };

            // Set the email subject
            var mailSubject = new Content("Email subject");

            // Set the email body
            var mailContent = new Content("Email body");
            var mailBody = new Body();

            // Set HTML body of the email
            mailBody.Html = "<div>Hello</div>;

            var mailMessage = new Message(mailSubject, mailBody);

            // Get an instance of the AWS SES client for sending emails
            var client = new AmazonSimpleEmailServiceClient(RegionEndpoint.EUWest1);
            
            // Attempt to send the email
            await client.SendEmailAsync(emailRequest);
    }
}
```

## Context

Code that talks to `us-east-1` appears to work just fine. For instance I can execute lambda expressions using the injected versions of the clients (IAmazonLambda) and perform other actions absolutely fine. However, when I try to send an email using this implementation where I new up a client that points to a different region it fails with the following exception:

```
> System.OperationCanceledException: **The operation was canceled.**
>    at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
>    at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
>    at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)
>    at Amazon.Runtime.Internal.Util.AsyncHelpers.<>c__DisplayClass1_1`1.<<RunSync>b__0>d.MoveNext() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\Util\_mobile\AsyncHelpers.cs:line 74
> --- End of stack trace from previous location where exception was thrown ---
>    at Amazon.Runtime.Internal.Util.AsyncHelpers.ExclusiveSynchronizationContext.BeginMessageLoop() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\Util\_mobile\AsyncHelpers.cs:line 139
>    at Amazon.Runtime.Internal.Util.AsyncHelpers.RunSync[T](Func`1 task) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\Util\_mobile\AsyncHelpers.cs:line 87
>    at Amazon.Util.AWSSDKUtils.DownloadStringContent(Uri uri, TimeSpan timeout, IWebProxy proxy) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Util\AWSSDKUtils.cs:line 1008
>    at Amazon.Util.EC2InstanceMetadata.GetItems(String relativeOrAbsolutePath, Int32 tries, Boolean slurp) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Util\_bcl+netstandard\EC2InstanceMetadata.cs:line 517
>    at Amazon.Util.EC2InstanceMetadata.GetItems(String path) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Util\_bcl+netstandard\EC2InstanceMetadata.cs:line 443
>    at Amazon.Util.EC2InstanceMetadata.get_IAMSecurityCredentials() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Util\_bcl+netstandard\EC2InstanceMetadata.cs:line 311
>    at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.FetchCredentials() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Credentials\_bcl+netstandard\DefaultInstanceProfileAWSCredentials.cs:line 142
>    at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentials() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Credentials\_bcl+netstandard\DefaultInstanceProfileAWSCredentials.cs:line 88
>    at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentialsAsync() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Credentials\_bcl+netstandard\DefaultInstanceProfileAWSCredentials.cs:line 106
>    at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CredentialsRetriever.cs:line 92
>    at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\RetryHandler\RetryHandler.cs:line 122
>    at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\RetryHandler\RetryHandler.cs:line 138
>    at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 61
>    at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 61
>    at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\ErrorCallbackHandler.cs:line 53
>    at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\MetricsHandler.cs:line 65
>    at Core.Services.SendEmailService.SendEmail() in E:\*******\www\*********\Services\SendEmailService.cs:line 78
```

The documentation implies, because it shows the use of a client and a region, that it would still use the same credentials. I have found a few people with the same problem and their answer is along the lines of "The client wasn't receiving their credentials". So I can change my code to the following to make it work:

`var client = new AmazonSimpleEmailServiceClient(new BasicAWSCredentials("AQSADLKFJASDLKAFSDLDSK", "lkasdflfdlkjLKjlkjLKJLKJHHGGHK+khjgff"), RegionEndpoint.EUWest1); // not real credentials`

But this doesn't seem right. I shouldn't have to put my real credentials into my project to make it work. I expected that creating a new client in the context of my project would use the same credentials that I already use successfully throughout my application, but that it would just communicate with another AWS region. Is this what it is supposed to do as the constructor has an overload for just region and no need for `AWSCredentials`?

## Your Environment

* AWSSDK.Core version used: 
None as far as I'm aware...
* Service assembly and version used: 
* Operating System and version: 
Windows 10
* Visual Studio version: 
Rider (not VS)
* Targeted .NET platform: 
.NET Core 2.2

## .NET Core Info

* .NET Core version used for development: 
AWSSDK.SimpleEmail - v3.3.100.1
AWSSDK.Lambda - v3.3.100.1
AWSSDK.Extensions.NETCore.Setup - v3.3.100.1
* .NET Core version installed in the environment where application runs: 
Microsoft.NETCore.App v2.2.0
* Output of `dotnet --info`: 
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.103
 Commit:    8edbc2570a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.103\

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by coultonluke** [comment]
I've just installed Fiddler hoping that I would be able to work out a request that is failing as a result of my attempt to send email using Amazon SES.

It looks like the code is attempting to make a call to the EC2 instance meta data end point:

GET http://169.254.169.254/latest/meta-data/iam/security-credentials HTTP/1.1
User-Agent: aws-sdk-dotnet-coreclr/ aws-sdk-dotnet-core/3.3.100.1 .NET_Core/4.6.27207.03 OS/Microsoft_Windows_10.0.17763
Host: 169.254.169.254

This is resulting in a 502 Bad Gateway... which it would do, because I'm not running it on EC2, I'm running it on my local machine.

Why would the SDK be trying to access the EC2 metadata end point?  Is it simply because I'm not passing AWSCredentials to the client?

**Comment by klaytaybai** [comment]
Hi @coultonluke, if you haven't done so already, please try following a set of the steps in this [setting up credentials documentation](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-creds.html#creds-file).  In your appsettings.json, you specify that you are referring to a profile named 'development' in your .aws/credentials file, so you will need to verify that you have a matching valid profile there.  You should be able to override the region.  Let me know if your code continues to not work for you after you have verified that your credential profiles are set up.

**Comment by coultonluke** [comment]
@klaytaybai Thanks for taking the time to get back to me on this.

I have a credentials file with a section called 'development' with my app key and secret in there. I used the AWS Windows cli (aws configure) to set these values. I know that these settings are being picked up correctly because it works for any calls where I use IoC to resolve a service as per the documentation but not when I create my own `AmazonSimpleEmailServiceClient` and pass in a different region.

For instance, if I resolve IAmazonSimpleEmailService I can see the locals window the `_credentials` property has my app key and secret as shown in the credentials file.

**Comment by coultonluke** [comment]
It's definitely working for the services that are injected into the services of my application. I can see the credentials in the resolved client as shown in this screenshot:

![image](https://user-images.githubusercontent.com/16463338/54953953-5f309a00-4f41-11e9-80b0-0efae33ecb09.png)

So this works:
```
public void ConfigureServices(IServiceCollection services)
{
    // AWS Config
    services.AddDefaultAWSOptions(Configuration.GetAWSOptions());
    services.AddAWSService<IAmazonLambda>();
    services.AddAWSService<IAmazonS3>();
    services.AddAWSService<IAmazonSimpleEmailService>();
}
```
```
// Attempt to send the email
await this.amazonSimpleEmailService.SendEmailAsync(emailRequest);
```
But this doesn't in the same method...
```
// Get an instance of the AWS SES client for sending emails
var client = new AmazonSimpleEmailServiceClient(RegionEndpoint.EUWest1);
            
// Attempt to send the email
await client.SendEmailAsync(emailRequest);
```

**Comment by klaytaybai** [comment]
Hi @coultonluke, I think your best solution would be to either set a default profile and use those credentials in place of your "development" profile or to set the AWS_PROFILE environment variable to "development".  If you do either of those options, you should be able to get your code to work as is.  

If you have configured other options other than the region and credentials, you should try to reuse your existing config.  The easiest way to do this is to reuse your old client but modify the configuration to use the new RegionEndpoint.
`            ((AmazonSimpleEmailServiceConfig)this.amazonSimpleEmailService.Config).RegionEndpoint = RegionEndpoint.EUWest1;
`
