### ISSUE TITLE
Direct access to Glacier Deep Archive

### ISSUE THREAD

**Issue by maxima120** [aws/aws-sdk-net#1239]
Using latest .NET SDK (awssdk.s3 3.3.0.0), I cannot find any way to upload/download **direct** to Glacier Deep Archive (avoiding S3 bucket and transitioning).

**Is it possible? if not, are there plans to enable it in future?**

*I mean - it is possible (and is a good idea) to have direct access to regular Glacier.. Deep Archive is even more suitable for it yet its not available..*

**Comment by sstevenkang** [comment]
I don't think this is supported.  My understanding is that Glacier is interfaced through S3 API.  Could you point us to a documentation that there's an AWS API that allows you to do this?

**Comment by maxima120** [comment]
Erm. No you cant go to Glaicer direct with S3 SDK. 

You can access regular Glacier directly with **Glacier SDK** only. 

But Deep Archive Glacier is only available with S3 SDK (as far as I can see) and I asked if you would consider opening **direct** access to DA Glacier too.

**Comment by sstevenkang** [comment]
Ah, you are correct.  They are "distinct" services.  However, my understanding of the best practices is to use S3 and set the storage class to `GLACIER`.

We can't answer your question since we are not on Glacier team.

**Comment by hoiast** [comment]
@maxima120 I managed to upload files directly to S3 Glacier Deep Archive using a pre-signed URL. To do so, I added an additional parameter to `GetPreSignedUrlRequest`:
```                   
                    var request = new GetPreSignedUrlRequest
                    {
                        BucketName = "MY_BUCKET_NAME",
                        Key = "MY_FILENAME",
                        Verb = HttpVerb.PUT,
                    };
                    request.Parameters.Add("x-amz-storage-class", "DEEP_ARCHIVE");
                    var path = awsClient.GetPreSignedURL(request);
```

**Comment by maxima120** [comment]
good to know. thank you
