### ISSUE TITLE
CodeCommit does not work at all in Visual Studio 2019

### ISSUE THREAD

**Issue by rgutierrezatx** [aws/aws-sdk-net#1244]
Installed Visual Studio 2019
Downloaded and installed the aws toolkit for visual studio 2017 and 2019
Opened Visual Studio.  AWS explorer works.  CodeCommit link in the Managed Connections does nothing.  
I have uninstalled and reinstalled the toolkit as well as a clean uninstall and reinstall of visual studio

**Comment by normj** [comment]
This is a duplicate of the following issue and we are working on a fix.
https://github.com/aws/aws-sdk-net/issues/1238
