### ISSUE TITLE
Getting Exception on using AWS S3 sdk with openstack to get all buckets/containers.

### ISSUE THREAD

**Issue by sumitc91** [aws/aws-sdk-net#1246]
I am getting Exception on using AWS S3 SDK with OpenStack to get all buckets/containers.

## Expected Behavior
- I should be able get list of buckets from OpenStack using aws s3 sdk using .net Core as it is working fine in dotnet 4.72 framework.

## Current Behavior
- I'm getting exception while fetching list of buckets from OpenStack using S3 sdk.
- AWS s3 sdk is working fine with .net 4.72 frameworks

## Possible Solution
- Is there any incompatibility between dotnet core and openstack ? 

## Steps to Reproduce (for bugs)
- Create a simple dotnet core application and try to fetch list of buckets using AWS s3 credentials.

## Context
- dotnet 4.72 was working fine but now after migrating to dotnet core it is not working.

## Your Environment

* AWSSDK.Core version used: 3.3.100
* Service assembly and version used: 
* Operating System and version: Windows 10
* Visual Studio version: VS 2015
* Targeted .NET platform: dotnet core

## .NET Core Info

* .NET Core version used for development: dotnet core 2.1
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by sstevenkang** [comment]
Hi. We do not make any guarantees on how the SDK behaves with non-S3 service. Please re-open the issue if you can reproduce the problem against S3.
