### ISSUE TITLE
Low level API UpdateAsync does not perform increment on version property

### ISSUE THREAD

**Issue by sloncho** [aws/aws-sdk-net#1248]
If there is a class with a property with `DynamoDbVersionAttribute`, when a low level UpdateAsync attempt is made to increment the version, it performs SET instead of increment.

The same operation, performed from CLI works as expected

Background:
``` csharp
public class Data
{
     public string Data {get; set;}
     // many other properties
     [DynamoDBVersion]
     public int? Version {get; set;}
}
```

If the above class is saved with dbContext.SaveAsync, version numbers are handled property as per documentation.

But if a low level API `IAmazonDynamoDB)` is used to increment the version, the version is set to the increment value. If the update request is for some other attribute, increment happens as is should.

The same request, done from the CLI works:
```
aws dynamodb update-item --table-name MyTable --key '{"Id":{"S":"myid"}}' --update-expression "ADD #V :incr" --expression-attribute-names '{"#V":"Version"}' --expression-attribute-values '{":incr": {"N": "5"}}'
```

## Expected Behavior

Low level API to behave as CLI.

## Current Behavior

Assuming the Version attribute in the database is set to "5", when UpdateAsync is used with:
``` csharp
var request = new UpdateItemRequest
            {
                TableName = "MyTable",
                Key = new Dictionary<string, AttributeValue>
                {
                    {"Id", new AttributeValue {S = "myid"}}
                },
                ExpressionAttributeNames = new Dictionary<string, string>
                {
                    {"#V", "Version"}
                },
                ExpressionAttributeValues = new Dictionary<string, AttributeValue>
                {
                    {":incr", new AttributeValue {N = "1"}}
                },
                UpdateExpression = "ADD #V :incr"
            };
```

The value of the Version attribute in dynamo is set to **"1",** instead of "6".

Using "SET #V = #V + :incr", as well as hard-coding the attribute name in the UpdateExpression instead of using #V, produces the same result.

If another attribute is used, let's say "Counter", the update performs as expected, and Counter is incremented each time.

## Context

Partial updates (ajax calls) to update only certain properties, while bumping the version so stream consumers can keep in sync with the updates.

## Your Environment

* AWSSDK.Core version used:  3.3.100.4
* Targeted .NET platform: .Net Core 2.1

**Comment by klaytaybai** [comment]
Hi @sloncho, I wasn't able to reproduce this issue.  Are you sure the object that you are updating already has an existing "Version" attribute at the time of the update?  If it didn't, that would explain why you are seeing the value set to the increment.
