### ISSUE TITLE
403 forbidden error while checking file in a bucket.

### ISSUE THREAD

**Issue by mahanteshk** [aws/aws-sdk-net#1249]
we have built a module to consume the aws sdk kit and while trying to copy the file from s3 to a virtual directory we check for the file existence till today the services were working fine but in one of the environment we have the exception as below. 

Exception Occured:-2146233088 Inner Exception = Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (403) Forbidden. ---> System.Net.WebException: The remote server returned an error: (403) Forbidden. at System.Net.HttpWebRequest.GetResponse() at Amazon.Runtime.Internal.HttpRequest.GetResponse() --- End of inner exception stack trace --- at Amazon.Runtime.Internal.HttpRequest.GetResponse() at Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executionContext) at Amazon.Runtime.Internal.RedirectHandler.InvokeSync(IExecutionContext executionContext) at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext) at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeSync(IExecutionContext executionContext) at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext) Message = Error making request with Error Code Forbidden and Http Status Code Forbidden. No further error information was returned by the service. StackTrace = at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception) at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception) at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext) at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext) at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeSync(IExecutionContext executionContext) at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext) at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext) at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext) at Amazon.Runtime.AmazonServiceClient.Invoke[TRequest,TResponse](TRequest request, IMarshaller`2 marshaller, ResponseUnmarshaller unmarshaller) at Amazon.S3.AmazonS3Client.GetObjectMetadata(GetObjectMetadataRequest request) at Amazon.S3.IO.S3FileInfo.ExistsWithBucketCheck(Boolean& bucketExists) at INSZoom.Cobra.DocumentStorage.AmazonS3.CheckFileExistsInAWS(String serverFilePath) at INSZoom.Cobra.DocumentStorage.AmazonS3.DownloadFileFromAWS(String serverFilePath, String downloadFilePath) at INSZoom.Cobra.SharedLibrary.Documents.AmazonS3DocumentStorage.DownloadFileFromAWS(String serverFilePath, String fileName, String downloadFileDirectory) at INSZoom.Cobra.ZoomCore.BL.Documents.DocumentStorageBL.DownloadFile(String storageProvider, String serverFilePath, String fileName, String downloadFileDirectory) at INSZoom.Cobra.ZoomCore.BL.Case.AddCaseHelper.Attach(String orgId, String userId, String orgFileName, String createDate, String& renameFile, String ajaxSeqId, Boolean retainName, LogComponent objLogComponent) at INSZoom.Cobra.ZoomCore.BL.Case.AddCase.AddEventsToCase(CreateCaseViewModel caseDetails, List`1 listObjCaseStep, CaseStatusViewModel& caseStatus) at INSZoom.Cobra.ZoomCore.BL.Case.AddCase.CopyCaseSteps(CreateCaseViewModel caseDetails, CaseStatusViewModel& caseStatus) at System.Threading.Tasks.Task.Execute()

**Comment by sstevenkang** [comment]
This sounds like a permissions issue.  Please provide more information or better repro steps.
