### ISSUE TITLE
Amazon.CognitoIdentity.Model.NotAuthorizedException: Invalid login token. Issuer doesn't match providerName 

### ISSUE THREAD

**Issue by kobechenyang** [aws/aws-sdk-net#1251]
I am getting a `Amazon.CognitoIdentity.Model.NotAuthorizedException: Invalid login token. Issuer doesn't match providerName ` error when I tried to use developer-authenticated identities. 

Workflow is from this page: https://docs.aws.amazon.com/zh_cn/cognito/latest/developerguide/authentication-flow.html
![image](https://user-images.githubusercontent.com/8561346/55662766-8d2c9e80-57cb-11e9-9e93-1c1ef302e7fc.png)

I followed the code from here: https://docs.aws.amazon.com/cognito/latest/developerguide/developer-authenticated-identities.html

```

public class DeveloperAuthenticatedCredentials : CognitoAWSCredentials
{
    const string PROVIDER_NAME = "example.com";
    const string IDENTITY_POOL = "IDENTITY_POOL_ID";
    static readonly RegionEndpoint REGION = RegionEndpoint.USEast1;

    private string login = null;

    public DeveloperAuthenticatedCredentials(string loginAlias)
        : base(IDENTITY_POOL, REGION)
    {
        login = loginAlias;
    }

    protected override IdentityState RefreshIdentity()
    {
        IdentityState state = null;
        ManualResetEvent waitLock = new ManualResetEvent(false);
        MainThreadDispatcher.ExecuteCoroutineOnMainThread(ContactProvider((s) =>
        {
            state = s;
            waitLock.Set();
        }));
        waitLock.WaitOne();
        return state;
    }

    IEnumerator ContactProvider(Action<IdentityState> callback)
    {
        WWW www = new WWW("http://example.com/?username="+login);
        yield return www;
        string response = www.text;

        JsonData json = JsonMapper.ToObject(response);

        //The backend has to send us back an Identity and a OpenID token
        string identityId = json["IdentityId"].ToString();
        string token = json["Token"].ToString();

        IdentityState state = new IdentityState(identityId, PROVIDER_NAME, token, false);
        callback(state);
    }
}

```

I am using `getOpenIdTokenForDeveloperIdentity` for my authorized user and `getOpenIdToken` for my unauthorized user. Both identity id and token are return fine from my backend. 

This is one piece from my token returned 

```
"amr": [
    "authenticated",
    "login.yc.ar",
    "login.yc.ar:cn-north-1:xxxxxxxx:test"
  ],
  "iss": "https://cognito-identity.cn-north-1.amazonaws.com.cn"
```

But whenever I tried to invoke my lambda function. It is giving me this `Amazon.CognitoIdentity.Model.NotAuthorizedException: Invalid login token. Issuer doesn't match providerName ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
` error. 

I tried multiple ways to set up the PROVIDER_NAME in `new IdentityState(identityId, PROVIDER_NAME, token, false);` without luck. What should be the correct PROVIDER_NAME here? 

Please help, thanks.

**Comment by Andreyul** [comment]
https://imgur.com/a/eYlu1wo

**Comment by kobechenyang** [comment]
@Andreyul  Thanks for your answer I have tried the developer name "login.yc.ar" I set up on cognito console. My backend is using getOpenIdTokenForDeveloperIdentity which I passed in the Logins in there too which works fine and it is generating the correct token. It is the client side when I tried to get the temporary credentials where it failed.

**Comment by kobechenyang** [comment]
I don't have problem to retrieve the credential using javascript sdk. Here is the code following this page: https://docs.aws.amazon.com/cognito/latest/developerguide/developer-authenticated-identities.html

`AWS.config.region = 'cn-north-1';
    const param = {
      IdentityPoolId: 'xxx',
      IdentityId: 'xxx',
      Logins: {
         'cognito-identity.cn-north-1.amazonaws.com.cn': 'xxxx'
      }
    };
    AWS.config.credentials = new AWS.CognitoIdentityCredentials(param);
    AWS.config.credentials.get(function(e){
        if(e){
          console.log(e);
          return;
        }
         // Credentials will be available when this function is called.
        var accessKeyId = AWS.config.credentials.accessKeyId;
        var secretAccessKey = AWS.config.credentials.secretAccessKey;
        var sessionToken = AWS.config.credentials.sessionToken;
        console.log(AWS.config.credentials);
        res.send(secretAccessKey);
  });`

**Comment by kobechenyang** [comment]
I think I may know what is causing this problem. In the file `/sdk/src/Services/CognitoIdentity/Custom/CognitoAWSCredentials.cs` 
cognito-identity.amazonaws.com is hard coded there. So I have no way to use `https://cognito-identity.cn-north-1.amazonaws.com.cn` from AWS China. Will try to rebuild the dlls with change.

**Comment by Andreyul** [comment]
Change your code
```
AWS.config.region = 'cn-north-1';
    const param = {
      IdentityPoolId: 'xxx',
      IdentityId: 'xxx',
      Logins: {
         'cognito-identity.cn-north-1.amazonaws.com.cn': 'xxxx'
      }
    };
```

to this:

```
AWS.config.region = 'cn-north-1';
    const param = {
      IdentityPoolId: 'xxx',
      IdentityId: 'xxx',
      Logins: {
         'cognito-identity.amazonaws.com': 'xxxx'
      }
    };
```

https://docs.aws.amazon.com/cognito/latest/developerguide/developer-authenticated-identities.html

**Comment by klaytaybai** [comment]
Thanks @Andreyul.  @kobechenyang, does that solve your problem?

**Comment by kobechenyang** [comment]
@Andreyul Thanks. I figured out the problem. I was using AWS China so that is why I am using "cognito-identity.cn-north-1.amazonaws.com.cn". 

```
AWS.config.region = 'cn-north-1';
    const param = {
      IdentityPoolId: 'xxx',
      IdentityId: 'xxx',
      Logins: {
         'cognito-identity.cn-north-1.amazonaws.com.cn': 'xxxx'
      }
    };
```
This was working for me as I tested using the aws javascript sdk. 

@klaytaybai I have to rebuild the SDK with "cognito-identity.amazonaws.com" change to "cognito-identity.cn-north-1.amazonaws.com.cn" in `/sdk/src/Services/CognitoIdentity/Custom/CognitoAWSCredentials.cs`. Then I am able to get the credential fine. You may want to expose this field as aws javascript sdk did.
