### ISSUE TITLE
Generating http (not https) PreSignedURLs

### ISSUE THREAD

**Issue by phlrdomanski** [aws/aws-sdk-net#1253]
I'd like to create a pre-signed URL with HTTP insterad of HTTPS for my local development using localstack (which AFAIK supports only HTTP)

## Expected Behavior
`GetPreSignedURL` method returns a URL with HTTP if the `UseHttp` client config param is set to `true`

## Current Behavior
`GetPreSignedURL` method returns a URL with HTTPS no matter what I set in the `UseHttp` param

## Possible Solution
```
var url = _client.GetPreSignedURL(request);
if (_client.Config.UseHttp && url.StartsWith("https"))
{
    return url.Replace("https", "http");
}
return url;
```
ugly, right? :)

## Steps to Reproduce (for bugs)
my client configuration:
```
var config = new AmazonS3Config
{
    ServiceURL = "http://localhost:4572",
    UseHttp = true,
    ForcePathStyle = true,
    AuthenticationRegion = "us-east-1"
};
AWSCredentials credentials = new BasicAWSCredentials("test", "test");

var awsClient = new AmazonS3Client(credentials, config);
```

## Context
I'm trying to set up my local environment using localstack

## Your Environment
* AWSSDK.Core version used: AWSSDK.S3 Version="3.3.101.3"
* Service assembly and version used: what is that?
* Operating System and version: Ubuntu 18.04
* Visual Studio version: none (I use Rider - version 2018.3.4)
* Targeted .NET platform: .NET Core 

## .NET Core Info
* .NET Core version used for development: 2.1.602
* .NET Core version installed in the environment where application runs: 2.1.602
* Output of `dotnet --info`: 
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.602
 Commit:    04475eb7cf

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.602/

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.1.602 [/usr/share/dotnet/sdk]
  2.2.202 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```
* Contents of project.json/project.csproj: I don't have this file, I do have `global.json`
```
{
  "sdk": {
    "version": "2.1.602"
  }
}
```

**Comment by klaytaybai** [comment]
Hi @phlrdomanski, while just using the UseHttp property in the ClientConfig might be convenient, that is a different concept from presigned URLs.  You can create an HTTP presigned URL by setting the protocol in your GetPresignedUrlRequest.

```
                var request = new GetPreSignedUrlRequest()
                {
                    BucketName = "bucket",
                    Key = "key",
                    Protocol = Protocol.HTTP,
                    Expires = new DateTime(...)
                };
```

**Comment by phlrdomanski** [comment]
thank you for the tip!
