### ISSUE TITLE
AWS CodeCommit Integration with AWS Toolkit for Visual Studio

### ISSUE THREAD

**Issue by marciogmorales** [aws/aws-sdk-net#1254]
## Expected Behavior
From the Team Explorer in the Visual Studio IDE. It's possible to connect to AWS CodeCommit in order to integrate your IDE with the AWS Codestar. Following all the step by step from https://docs.aws.amazon.com/codestar/latest/userguide/setting-up-ide-vs.html 

## Current Behavior
From the Team Explorer, if you click in “Connect to AWS CodeCommit” nothing happens even with my Visual Studio setup up and running.

## Steps to Reproduce (for bugs)
https://docs.aws.amazon.com/codestar/latest/userguide/setting-up-ide-vs.html 

## Context
I'm working in a Demo for one of my customer.

## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: Microsoft Windows Server 2019 Datacenter V.10.0.17763 Build 17763	
* Visual Studio version: 2019 Community 16.0.1
* Targeted .NET platform: 
[sysinfo.txt](https://github.com/aws/aws-sdk-net/files/3060469/sysinfo.txt)
[DxDiag.txt](https://github.com/aws/aws-sdk-net/files/3060470/DxDiag.txt)

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by normj** [comment]
This is similar to the following issue reported for VS 2017. We are almost done with the solution for VS 2017. VS 2019 is going to need additional work which we will do once we get the fix for VS 2017 out.

**Comment by normj** [comment]
Version 1.15.1.0 of the AWS Toolkit for Visual Studio has been released which fixes the issue for VS 2017. For 2019 CodeCommit just doesn't show up and we need a bit more time to fix that issue.

**Comment by normj** [comment]
Update, the fix for CodeCommit in VS 2019 is in code review stage. We hope to get a release out soon.

**Comment by normj** [comment]
Version 1.15.2.0 has been released that adds support for CodeCommit to VS 2019.
