### ISSUE TITLE
signature mismatch when user metadata keys contain _ (underscore)

### ISSUE THREAD

**Issue by ben-schumacher** [aws/aws-sdk-net#1258]
## Expected Behavior
When setting user metadata keys in put object request, an underscore will create a canonicalized header string in the wrong order causing a signature mismatch.

## Current Behavior

Request return a signature mismatch error instead of 200 OK response.

The string comparer is upper-casing the the metadata key names which will incorrectly order the metadata keys with "_" to be lower in the sort.

## Possible Solution

https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Internal/Auth/S3Signer.cs#L154
Need to change the comparer to InvariantCultureIgnoreCase in that line.

## Steps to Reproduce (for bugs)

public static void Main(string[] args)
        {
            // create the AWS S3 client
            AmazonS3Client s3 = AWSS3Factory.getS3Client();

            // retrieve the object key and object content from the user
            Console.Write("Enter the object key: ");
            string key = Console.ReadLine();
            Console.Write("Enter the object content: ");
            string content = Console.ReadLine();

            // create object request with retrieved input
            PutObjectRequest request = new PutObjectRequest()
            {
                BucketName = AWSS3Factory.S3_BUCKET,
                ContentBody = content,
                Key = key
            };

            request.Metadata.Add("acquisitionprotocol", "http");
            request.Metadata.Add("acquisition_time_ms", "5");

            // create the object in demo bucket
            s3.PutObject(request);
           

            // print out object key/value for validation
            Console.WriteLine(string.Format("Created object {0}/{1} with content: {2}", AWSS3Factory.S3_BUCKET, key, content));
            Console.ReadLine();
        }

## Context

Can't create objects with "_" character in the metadata key.

## Your Environment

* AWSSDK.Core version used: 3.3.100.5
* Service assembly and version used: 
* Operating System and version: Windows 10
* Visual Studio version: Community 2019
* Targeted .NET platform: 4.5

**Comment by klaytaybai** [comment]
@ben-schumacher, thanks for submitting this.  I was able to reproduce it with .NET Framework 4.5.  We'll take a look at your pull request.

**Comment by ben-schumacher** [comment]
@klaytaybai I unfortunately discovered today that my fix now incorrectly sorts:

(-)   45  02/13   55  2D                 HYPHEN, MINUS SIGN
(|)  124  07/12  174  7C                 VERTICAL LINE, VERTICAL BAR
(~)  126  07/14  176  7E                 TILDE

Those characters were previously sorting correctly.  I'm looking now at how I can modify the PR to take into account these characters.

**Comment by sugacube** [comment]
I just ran into this issue.
Still same problem with latest version.
Can this please be looked at again ?

**Comment by ashishdhingra** [comment]
Fixed in version 3.5.123.1, commit https://github.com/aws/aws-sdk-net/commit/1f6a23aa77a0e4a1f6d73cfc813c1672431f48c4.
