### ISSUE TITLE
AmazonLambdaClient Exception thrown: 'System.IO.DirectoryNotFoundException' in System.Private.CoreLib.dll

### ISSUE THREAD

**Issue by antony-booth** [aws/aws-sdk-net#1263]
Instantiating AmazonLambdaClient with any of the 12 Constructor overloads throws an exception internally that is output to the console.

> Exception thrown: 'System.IO.DirectoryNotFoundException' in System.Private.CoreLib.dll

## Expected Behavior
An exception should not be thrown attempting to access a file or folder that may not exist and is not needed.

## Current Behavior
Creating a new instance of `Amazon.Lambda.AmazonLambdaClient` attempts to read a folder: `%USERPROFILE%\.aws\credentials` that may not exist and appears to be using error handling as flow control, rather than checking for the folders existence before attempting to read it's contents. Also, there is no indication in the documentation that instantiating an object should attempt to obtain credentials from a users profile. This hard coded path and process during object initialization is bad practice. An instantiating class should not be dependent on the existence of files on a file system. Dependencies should be injected if needed, as reading files is not the purpose and therefore, should not be the responsibility of the AmazonLambdaClient class.

## Possible Solution

- Do not attempt to load credentials from a file, but expect them in a constructor
- Check to see if the folder exists before trying to read from it.
- Don't read from a folder when a constructor has already been passed the information
- Catch and handle the error, gracefully!

## Steps to Reproduce (for bugs)
Ensure folder `%USERPROFILE%\.aws\credentials` does not exist.

        private void CreateClient()
        {
            const string accessKey = "123";
            const string secret = "456";
            const string sessionToken = "789";

            AmazonLambdaConfig config = new AmazonLambdaConfig { RegionEndpoint = RegionEndpoint.APNortheast1 };
            AWSCredentials credentials = new Amazon.Runtime.BasicAWSCredentials(accessKey, secret);

            AmazonLambdaClient client01 = new AmazonLambdaClient();
            AmazonLambdaClient client02 = new AmazonLambdaClient(credentials);
            AmazonLambdaClient client03 = new AmazonLambdaClient(config);
            AmazonLambdaClient client04 = new AmazonLambdaClient(RegionEndpoint.APNortheast1);
            AmazonLambdaClient client05 = new AmazonLambdaClient(credentials, config);
            AmazonLambdaClient client06 = new AmazonLambdaClient(credentials, RegionEndpoint.APNortheast1);
            AmazonLambdaClient client07 = new AmazonLambdaClient(accessKey, secret);
            AmazonLambdaClient client08 = new AmazonLambdaClient(accessKey, secret, config);
            AmazonLambdaClient client09 = new AmazonLambdaClient(accessKey, secret, RegionEndpoint.APNortheast1);
            AmazonLambdaClient client10 = new AmazonLambdaClient(accessKey, secret, sessionToken);
            AmazonLambdaClient client11 = new AmazonLambdaClient(accessKey, secret, sessionToken, config);
            AmazonLambdaClient client12 = new AmazonLambdaClient(accessKey, secret, sessionToken, RegionEndpoint.APNortheast1);
        }

## Context
There is no way to instantiate the client without an exception message being output and has taken time to identify this as not being an issue to the application being developed.

## Your Environment
* AWSSDK.Core 3.3.100.4
* AWSSDK.Lambda, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604
* Windows 10 pro
* Visual Studio 2017

## .NET Core Info
* .NET Core 2.1

> .NET Core SDK (reflecting any global.json):
>  Version:   2.1.505
>  Commit:    b220231234
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.17134
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\2.1.505\
> 
> Host (useful for support):
>   Version: 2.1.9
>   Commit:  dcedc87d22
> 
> .NET Core SDKs installed:
>   2.1.2 [C:\Program Files\dotnet\sdk]
>   2.1.202 [C:\Program Files\dotnet\sdk]
>   2.1.402 [C:\Program Files\dotnet\sdk]
>   2.1.403 [C:\Program Files\dotnet\sdk]
>   2.1.500 [C:\Program Files\dotnet\sdk]
>   2.1.505 [C:\Program Files\dotnet\sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
> 
> To install additional .NET Core runtimes or SDKs:
>   https://aka.ms/dotnet-download

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
@antony-booth, can you reconfirm your AWSSDK.Lambda version?  Version 3.3.100.4 should match AWSSDK.Core 3.3.100.4; 3.3.0 is quite old.  I wasn't able to reproduce your problem.  Most of those constructors should work if you don't have a credentials file.

Regarding the design of the constructors, we appreciate the feedback.  However, to prevent any breaking changes, we won't be able to make any changes until a major version.

**Comment by antony-booth** [comment]
Here are the Nuget Packages being referenced.
![image](https://user-images.githubusercontent.com/35821122/56585345-a6936000-65ab-11e9-9509-439812ec54d5.png)

Here's what I get when I inspect the class in Visual Studio. It's from package 3.3.100.4, but the assembly version is 3.3.0.0
![image](https://user-images.githubusercontent.com/35821122/56585967-d5f69c80-65ac-11e9-8f72-fe2d55217203.png)

The constructors work, but they output an exception message to the console because they are trying to read a credentials file in a non existent folder and is probably just using a try/catch block, logging to the console and eating the error, rather than checking if the full path to the credentials file exists, before attempting to read it.
