### ISSUE TITLE
Api Gateway WebSocket PostToConnectionRequest Forbidden 

### ISSUE THREAD

**Issue by KseniiaPelykh** [aws/aws-sdk-net#1264]
Hi, 

we're using API Gateway WebSocket. For pushing messages to connection we created a lambda that uses the PostToConnectionAsync method from AWSSDK.ApiGatewayManagementApi library. 

```
var apiClient = new AmazonApiGatewayManagementApiClient(new AmazonApiGatewayManagementApiConfig
{
    ServiceURL = _wsConnectionUrl
});
    
var postConnectionRequest = new PostToConnectionRequest
{
    ConnectionId = connection,
    Data = new System.IO.MemoryStream(Encoding.UTF8.GetBytes("Hello")),
};

var response = await apiClient.PostToConnectionAsync(postConnectionRequest);

```

Where `connection` is connectionId stored in DynamoDB and `_wsConnectionUrl` is the url of our API Gateway that has this structure :  $"https://{domainName}/{stage}" 
We expected the "hello" message to be pushed to the client, but we have this error in lambda logs

> One or more errors occurred. (Forbidden): AggregateException
> at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
> at lambda_method(Closure , Stream , Stream , LambdaContextInternal )
> 
> at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
> at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
> at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
> at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
> at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
> at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
> at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)...

Lambda has this policy: 

```
statement {
    effect = "Allow"
    actions =  ["execute-api:ManageConnections"],
    resources  = ["arn:aws:execute-api:*:*:*/@connections/*"]
  }
```

Can you help us to understand if there is any misconfiguration?

Thanks.

**Comment by KseniiaPelykh** [comment]
Hi, 

we found the problem -> our lambda is in VPC.
Sorry for disturb.

**Comment by sergiorua** [comment]
How did you fix it? I have the same issue and can't find the problem.

**Comment by KseniiaPelykh** [comment]
Hi @sergiorua ,
we had a DNS resolution issue, so we needed to remove the lambda from the vpc (as it was the easiest and the fastest solution). If you want I can write you more details. 

Anyway, we use this policy for our lambda (not sure if it is required)

```
  statement {
    effect = "Allow"

    actions = [
      "execute-api:ManageConnections",
      "execute-api:Invoke",
    ]

    resources = ["*"]
  }
```

**Comment by klaytaybai** [comment]
@sergiorua, check out this [documentation on setting up an APIGateway WebSocket API](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-integration-requests.html).  Under "integration type", it briefly mentions [API Gateway Private Integrations for VPCs](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-private-integration.html).  You can follow this practice if you need to keep your Lambda in your VPC, or you can remove your Lambda from the VPC.

**Comment by sergiorua** [comment]
Thanks for taking the time to reply. As far as I can tell all my config is correct but I have a weird problem that the lambda in the same region gets 403 trying to connect to the api websocket but from another region works. I haven't been able to figure it out yet.

**Comment by klaytaybai** [comment]
That does seem odd.  Which regions are you using?

**Comment by sergiorua** [comment]
eu-west-1 and eu-west-2

I'll figure it out eventually. Thanks.

**Comment by asanka-x** [comment]
I faced the same issue. My ecs task was in a vpc and due to a vpc endpoint i had added to api gateway I got the forbidden error. 
Basically if you have enabled private dns for the api gateway vpc endpoint you can't invoke public api gateway endpoints. However there is a workaround for this as mentioned here.
https://aws.amazon.com/premiumsupport/knowledge-center/api-gateway-vpc-connections/

**Comment by chukkalasandeep** [comment]
Hi,

we are facing the same issue of "Forbidden Exception",  there is no VPC for the lambda and also the API gateway. I am using AWSApiGatewayManagementClient to do the request. . Below is the code

AWS API Gateway Client 
`AmazonApiGatewayManagementApiClient apiClient = new AmazonApiGatewayManagementApiClient(new AmazonApiGatewayManagementApiConfig
                {
                    ServiceURL = AWSHelper.WebSocketEndPoint
                });
`
Connection Request
`
var postConnectionRequest = new PostToConnectionRequest
                    {
                        ConnectionId = connectionId,
                        Data = stream
                    };
var connectionresponse = await apiClient.PostToConnectionAsync(postConnectionRequest);
`
Above connectionId is from DynamoDB and stream is a message text. Below is the log from the cloud watch for the request  and I replaced actual apiid with {api-id} in the below screenshot

`
"Config": {
        "RegionEndpointServiceName": "execute-api",
        "ServiceVersion": "2018-11-29",
        "UserAgent": "aws-sdk-dotnet-coreclr/3.3.101.124 aws-sdk-dotnet-core/3.3.107.9 .NET_Core/4.6.28325.0 OS/Linux_4.14.165-102.205.amzn2.x86_64_#1_SMP_Fri_Feb_14_22:46:57_UTC_2020 exec-env/AWS_Lambda_dotnetcore2.1",
        "SignatureMethod": 1,
        "SignatureVersion": "4",
        "UseAlternateUserAgentHeader": false,
        "RegionEndpoint": null,
        "ServiceURL": "https://{api-id}.execute-api.ap-southeast-1.amazonaws.com/prod",
        "UseHttp": false,
        "AuthenticationRegion": null,
        "AuthenticationServiceName": "execute-api",
        "MaxErrorRetry": 4,
        "IsMaxErrorRetrySet": false,
        "LogResponse": false,
        "ReadEntireResponse": false,
        "BufferSize": 8192,
        "ProgressUpdateInterval": 102400,
        "ResignRetries": false,
        "AllowAutoRedirect": true,
        "LogMetrics": false,
        "DisableLogging": false,
        "ProxyCredentials": null,
        "Timeout": null,
        "UseDualstackEndpoint": false,
        "ThrottleRetries": true,
        "CorrectedUtcNow": "2020-06-10T04:39:08.0045979Z",
        "ClockOffset": "00:00:00",
        "DisableHostPrefixInjection": false,
        "EndpointDiscoveryEnabled": false,
        "EndpointDiscoveryCacheLimit": 1000,
        "RetryMode": 0,
        "FastFailRequests": false,
        "CacheHttpClient": true,
        "HttpClientCacheSize": 2,
        "ReadWriteTimeout": null,
        "ProxyHost": null,
        "ProxyPort": 0,
        "MaxConnectionsPerServer": null,
        "HttpClientFactory": null
      }
`

Below is the exception

`
{
      "ErrorType": 2,
      "ErrorCode": "ForbiddenException",
      "RequestId": "5b0d0a0a-2f75-4ed6-a8b6-b439b4074938",
      "StatusCode": 403,
      "Retryable": null,
      "Message": "Forbidden",
      "Data": {
        
      },
      "InnerException": {
        "Response": {
          "StatusCode": 403,
          "IsSuccessStatusCode": false,
          "ContentType": "application/json",
          "ContentLength": 23,
          "ResponseBody": {
            
          }
        },
        "Message": "Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.",
        "Data": {
          
        },
        "InnerException": null,
        "StackTrace": " at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)\n at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)\n at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)\n at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)",
        "HelpLink": null,
        "Source": "AWSSDK.Core",
        "HResult": -2146233088
      },
      "StackTrace": " at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)\n at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)\n at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)\n at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)\n at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)\n at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)\n at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)\n at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)\n at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)\n at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)\n at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)\n at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)\n at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)\n at QI.TrackSynqUtilities.Serverless.Functions.NotifierEventHandler(APIGatewayProxyRequest request, ILambdaContext context) in D:\\QI\\BitbucketRepos\\tracksynqutilities\\QI.TrackSynqUtilities.Serverless\\Functions.cs:line 519",
      "HelpLink": null,
      "Source": "AWSSDK.Core",
      "HResult": -2146233088
    }

`
Below is the permission both for  lambda and deployment profile user
`
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "execute-api:*",
            "Resource": "*"
        }
    ]
}
`
Can someone help on this?

**Comment by divmgl** [comment]
> @sergiorua, check out this [documentation on setting up an APIGateway WebSocket API](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api-integration-requests.html). Under "integration type", it briefly mentions [API Gateway Private Integrations for VPCs](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-private-integration.html). You can follow this practice if you need to keep your Lambda in your VPC, or you can remove your Lambda from the VPC.

It seems that VPC links are not compatible with WebSocket APIs.
