### ISSUE TITLE
Intermitten System.Net.Sockets.SocketException followed by System.Net.Http.HttpRequestException when using S3 to upload and download many files.

### ISSUE THREAD

**Issue by helbize** [aws/aws-sdk-net#1265]
I am experiencing an intermittent exception when downloading or uploading files to S3. My function is using a single instance of Amazon.S3.AmazonS3Client to both download and upload files. The downloads are limited to 5 at once and the uploads are limited to 5 at once for a total of 10. The configuration is unchanged from the default except for raising the BufferSize to 1 MB.

When the function starts it always works for a couple of minutes until it eventually throws the following exception (from either awaiting the result on a download or upload request):

```
System.Net.Http.HttpRequestException: No such host is known ---> System.Net.Sockets.SocketException: No such host is known
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_mobile\HttpRequestMessageFactory.cs:line 524
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:line 175
   at Amazon.Runtime.Internal.RedirectHandler.InvokeAsync[T](IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\RedirectHandler.cs:line 59
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\Unmarshaller.cs:line 85
   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeAsync[T](IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Services\S3\Custom\Internal\AmazonS3ResponseHandler.cs:line 58
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 99
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 61
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\EndpointDiscoveryHandler.cs:line 75
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\EndpointDiscoveryHandler.cs:line 86
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CredentialsRetriever.cs:line 98
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\RetryHandler\RetryHandler.cs:line 122
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\RetryHandler\RetryHandler.cs:line 138
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 61
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 61
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeAsync[T](IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Services\S3\Custom\Internal\AmazonS3ExceptionHandler.cs:line 57
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\ErrorCallbackHandler.cs:line 53
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\MetricsHandler.cs:line 65
```

I'm currently running this instance from the 'AWS .NET Mock Lambda Test Tool' but I've seen similar issues (but much less frequent) when deployed.

## Expected Behavior
If I'm hitting some kind of request limit and S3 is booting my connection, then I'd expect there to be some kind of way for the client to tell.

## Current Behavior
Intermittently one of my downloads or uploads throws the above exception, which as the end client I'm not sure I should be handling.

I've turned on the SDK debugging using:
AWSConfigs.LoggingConfig.LogTo = LoggingOptions.SystemDiagnostics;
AWSConfigs.LoggingConfig.LogMetrics = true;
AWSConfigs.LoggingConfig.LogResponses = ResponseLoggingOption.OnError;

and attached the output right before the issue:
[DebugOutput.txt](https://github.com/aws/aws-sdk-net/files/3114457/DebugOutput.txt)

It always starts with a socket exception that I haven't been able to inspect yet since it gets swallowed up by the retry mechanism:

Amazon Information: 5863 : Exception thrown: 'System.Net.Sockets.SocketException' in System.Private.CoreLib.dll

## Steps to Reproduce (for bugs)
This is an icky bug because I don't know how to simplify my problem but cannot release all of my code for proprietary reasons. Here's the essentials of what the code is doing:

```
public class S3Iterator
{
	public S3Iterator(IAmazonS3 in_s3Client, string in_bucket, List<string> in_keys, int in_maxSimultaneousDownloads)
	{
		m_s3Client = in_s3Client;
		m_bucket = in_bucket;
		m_keys = in_keys;
		m_maxSimultaneousDownloads = in_maxSimultaneousDownloads;
	}

	// The client we use to download objects from S3.
	protected IAmazonS3 m_s3Client;

	// The bucket we are downloading from in S3.
	protected string m_bucket;

	// The list of keys for this iterator.
	protected List<string> m_keys;

	// The maximum amount of files we'll download at once.
	protected int m_maxSimultaneousDownloads;
}

/// Helper class that is used to download multiple keys from S3 asynchronously and iterate over the results.
/// Using this class makes it easy to process files while downloading others in the background. The order that
/// the responses come back is not guaranteed to be the same order as the keys passed in. Instead we return the
/// first file to be finished to minimize the amount of time spent blocking.
public class GetObjectsNonSequentialIterator : S3Iterator, IEnumerable<Amazon.S3.Model.GetObjectResponse>
{
	public GetObjectsNonSequentialIterator(IAmazonS3 in_s3Client, string in_bucket, List<string> in_keys, int in_maxSimultaneousDownloads = 5) :
		base(in_s3Client, in_bucket, in_keys, in_maxSimultaneousDownloads)
	{
		// Immediately start downloading the first few items instead of waiting for the first call to
		// 'GetEnumerator'.
		FillGetObjectResponsesList();
	}

	public IEnumerator<Amazon.S3.Model.GetObjectResponse> GetEnumerator()
	{
		while (m_getObjectResponses.Count > 0)
		{
			// Find the index of the first download completed.
			var indexOfFinishedTask = m_getObjectResponses.FindIndex((in_task) => in_task.IsCompleted);

			// No download is finished so force a wait.
			if (indexOfFinishedTask == -1)
			{
				Task.WaitAny(m_getObjectResponses.ToArray());

				// At this point we are guaranteed at least one item is complete.
				indexOfFinishedTask = m_getObjectResponses.FindIndex((in_task) => in_task.IsCompleted);
			}

			// Get the item to return and remove it from the list.
			var getObjectResponse = m_getObjectResponses[indexOfFinishedTask].Result;
			m_getObjectResponses.RemoveAt(indexOfFinishedTask);

			// Queue up any additional downloads needed.
			FillGetObjectResponsesList();

			// And return the item.
			yield return getObjectResponse;
		}
	}

	System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
	{
		return GetEnumerator();
	}

	/// <summary>
	/// Fills m_getObjectResponses until it either reaches m_maxSimultaneousDownloads or we run out of keys to
	/// download.
	/// </summary>
	private void FillGetObjectResponsesList()
	{
		while (
			m_getObjectResponses.Count < m_maxSimultaneousDownloads &&
			m_nextKeyIndexToGet < m_keys.Count)
		{
			m_getObjectResponses.Add(m_s3Client.GetObjectAsync(new Amazon.S3.Model.GetObjectRequest()
			{
				BucketName = m_bucket,
				Key = m_keys[m_nextKeyIndexToGet]
			}));
			++m_nextKeyIndexToGet;
		}
	}

	// The index into m_keys we should download next.
	private int m_nextKeyIndexToGet = 0;

	// The responses to our get object requests.
	private List<Task<Amazon.S3.Model.GetObjectResponse>> m_getObjectResponses = new List<Task<Amazon.S3.Model.GetObjectResponse>>();
};

var s3Client = new Amazon.S3.AmazonS3Client();
var putObjectTasks = new List<Task>();

For each Foo:
{
   var s3SourceKeys = s3Client.ListObjectsV2Async(Request To Get Foo's Keys).Wait();
   var getObjectsIterator = new GetObjectsNonSequentialIterator(s3Client, MyLib.AWS.S3.Buckets.MyBucket, s3SourceKeys);
   foreach (var response in getObjectsIterator)
   {
       <Process, I use the response and then dispose of it>
   }

   For each Bar:
   {
      <Process>
      putObjectTasks.Add(s3Client.PutObjectAsync(RequestUsingStream));
     <LimitConcurrentPutObjectTasksTo5>
   }
}
```
   
## Context
I'm trying to download data, process it, and upload it in an efficient manner. I've been searching for best practices and it is very possible that I'm doing something wrong but I'm completely stumped at this point.

## Your Environment
* AWSSDK.Core version used: 3.3.100.8
* Service assembly and version used: <See Below>
* Operating System and version: Microsoft Windows 10 Pro 10.0.17134 Build 17134
* Visual Studio version: Visual Studio 2017 Professional
* Targeted .NET platform: NETCore 2.1

## .NET Core Info
* .NET Core version used for development: 2.1
* .NET Core version installed in the environment where application runs: 2.1
* Output of `dotnet --info`: 
.NET Core SDK (reflecting any global.json):
 Version:   2.1.505
 Commit:    b220231234

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.505\

Host (useful for support):
  Version: 2.1.9
  Commit:  dcedc87d22

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

* Contents of project.json/project.csproj: 
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="1.1.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.Json" Version="1.5.0" />
    <PackageReference Include="AWSSDK.Lambda" Version="3.3.100.8" />
    <PackageReference Include="AWSSDK.S3" Version="3.3.101.6" />
    <PackageReference Include="Npgsql" Version="4.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AWSUtils\AWSUtils.csproj" />
  </ItemGroup>

</Project>

**Comment by klaytaybai** [comment]
Hi @helbize, could you try out our [Transfer Utility](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/S3/TTransferUtility.html) and see if that meets your needs?  It might be easier and less problematic to use that.  You may also want to ensure that you have set a sufficient timeout and have a reliable internet connection with available bandwidth.

**Comment by helbize** [comment]
Interestingly, I was debugging this today and turned on catch on all exceptions. I was looking at some of them and looking into how the Retry mechanism works within the sdk. Because I was attached and artificially caused the request rate to temporarily slow down it recovered from the error and continued. I saw that there was some kind of metric that controls the delay when failures occur so I'm going to attempt to modify that.

I agree that it may be my internet, but as I said I've also seen similar intermittent failures when the lambda is deployed. If anything the fact that it causes it to repro semi-reliably is a good thing. The documentation on [Retries and Timeouts is relatively sparse](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/retries-timeouts.html).

The Transfer Utility doesn't fit my needs since all of my data is in memory. All of the upload and download functions within it deal with using the disk.

**Comment by helbize** [comment]
@klaytaybai I see in DownloadCommand.async that there is a retry mechanism built on top of the underlying IAmazonS3.GetObjectAsync. Is it expected that clients should have to handle errors themselves and build that? The documentation and code doesn't make that clear but if that's the answer it's something I can do.

**Comment by helbize** [comment]
I spent today writing a mechanism for doing my own retries on top of S3 and it is now backing off requests and retrying failed requests correctly. To anyone who runs into a similar issue with S3, I recommend writing something on top of it that will retry your requests for you. Here was a basic rundown of what I did:

- In the config set MaxErrorRetry to 0. This makes it so you don't have two separate systems trying to do retries.

- Created something fairly generic to do retries:
```
	/// <summary>
	/// Interface for a task operation that can be retried on a delay.
	/// </summary>
	interface IRetriableTask<T>
	{
		/// <summary>
		/// Perform the operation.
		/// </summary>
		Task<T> Execute();

		/// <summary>
		/// Allows the class to decide whether the given exception can be retried. Return true to retry, false to throw
		/// it.
		/// </summary>
		bool ShouldRetryOnException(Exception in_exception);
	}


	class RetriableTask
	{
		/// <summary>
		/// Executes io_retriableTask multiple times using in_delaysBetweenRetries. If the task throws, this delays
		/// using the TimeSpan within in_delaysBetweenRetries that corresponds to the attempt number prior to trying
		/// again. Typically you want the delays to get progressively longer. Each failure will be logged to the
		/// Console. If we reach our max attempts, or io_retriableTask ShouldRetryOnException returns false the
		/// exception will be rethrown. Otherwise as soon as it succeeds the result is returned.
		/// </summary>
		public static async Task<T> ExecuteAsync<T>(IRetriableTask<T> io_retriableTask, List<TimeSpan> in_delaysBetweenRetries)
		{
			// Keep trying the operation until we either succeed or exceed retries.
			int attemptNum = 0;
			while (true)
			{
				// Attempt to Execute.
				System.Runtime.ExceptionServices.ExceptionDispatchInfo capturedException = null;
				try
				{
					return await io_retriableTask.Execute();
				}
				catch (Exception exception)
				{
					// This helps make callstacks easier to follow if this ends up rethrowing the exception.
					capturedException = System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(exception);
				}

				// We exceeded retries, or this exception should not be retried.
				if (attemptNum >= in_delaysBetweenRetries.Count || 
					!io_retriableTask.ShouldRetryOnException(capturedException.SourceException))
				{
					capturedException.Throw();
				}

				// Otherwise log the captured exception.
				Console.WriteLine($"{io_retriableTask.ToString()} failed attempt {attemptNum} with exception {capturedException.SourceException.ToString()}. Delaying and trying again.");

				// Wait the configured amount of time.
				await Task.Delay(in_delaysBetweenRetries[attemptNum]);

				// And retry.
				++attemptNum;
			}
		}
	}
```

```
		/// <summary>
		/// Base class for all of our S3 retriable tasks.
		/// </summary>
		private abstract class S3RetriableTask<T> : IRetriableTask<T>
		{
			protected S3RetriableTask(IAmazonS3 io_s3Client) 
			{
				m_s3Client = io_s3Client;
			}

			public abstract Task<T> Execute();

			public bool ShouldRetryOnException(Exception in_exception)
			{
				// For now we retry on everything that isn't an AmazonS3Exception. Typically AmazonS3Exceptions are
				// reserved for unrecoverable errors such as missing keys. Retrying and swallowing these wouldn't be
				// good.
				if (in_exception is AmazonS3Exception)
				{
					return false;
				}

				return true;
			}

			protected IAmazonS3 m_s3Client;
		}

		/// <summary>
		/// A retriable task to retrieve an object from S3.
		/// </summary>
		private class GetObjectTask : S3RetriableTask<Amazon.S3.Model.GetObjectResponse>
		{
			public GetObjectTask(IAmazonS3 io_s3Client, string in_bucket, string in_key) : 
				base(io_s3Client)
			{
				m_bucket = in_bucket;
				m_key = in_key;
			}

			public async override Task<Amazon.S3.Model.GetObjectResponse> Execute()
			{
				return await m_s3Client.GetObjectAsync(new Amazon.S3.Model.GetObjectRequest()
				{
					BucketName = m_bucket,
					Key = m_key
				});
			}


			private string m_bucket;
			private string m_key;
		}

```

It seems to be working pretty well except for a couple of kinks that I'm still working out. Thanks for the hints of where to look @klaytaybai.
