### ISSUE TITLE
Retrieve verification code programmatically

### ISSUE THREAD

**Issue by simax** [aws/aws-sdk-net#1266]
Using the SDK I can initiate the forgot password flow with `AmazonCognitoIdentityProviderClient.ForgotPassword` and the verification is code is delivered via email - which is perfectly fine for production use but I'm writing integration tests and therefore retrieving the verification from the email isn't a viable option. 

I need a way to retrieve the verification code programmatically so I can supply it to the`AmazonCognitoIdentityProviderClient.ConfirmForgotPasswordAsync` method. A conversation with AWS support has confirmed that this isn't currently possible with the SDK and that I raise an issue here.

I have successfully written integration tests for all the other endpoints such as signup/login/change email/change password etc. It's just the forgot password flow that's causing a problem.

## Expected Behavior
Would it be possible to add functionality to the SDK to allow retrieval of the verification code programmatically?

## Current Behavior
No way retrieve the verification code programmatically

## Context
Integration testing

## Your Environment

* AWSSDK.Core version used: 3.3.100.5 & Amazon.AspNetCore.Identity.Cognito (1.0.0)
* Service assembly and version used: 
* Operating System and version: Windows 10
* Visual Studio version: 2017
* Targeted .NET platform: Dotnet core 2.2

## .NET Core Info

* .NET Core version used for development: Dotnet core 2.2
* .NET Core version installed in the environment where application runs: Dotnet core 2.2
* Output of `dotnet --info`: 
.NET Core SDK (reflecting any global.json):
 Version:   2.2.105
 Commit:    7cecb35b92

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.105\

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.301 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.2.105 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

* Contents of project.json/project.csproj: 
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.AspNetCore.Identity.Cognito" Version="1.0.0" />
    <PackageReference Include="AWSSDK.Core" Version="3.3.100.5" />
    <PackageReference Include="IdentityServer4.AccessTokenValidation" Version="2.7.0" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>

**Comment by klaytaybai** [comment]
Hi @simax, this functionality would have to be added by the Cognito service team.  However, I think it is unlikely that they would choose to do so.  If the confirmation could be retrieved programmatically by someone without access to the registered email account, it would defeat the security purpose.  If you need to go through the service instead of mocking the objects for your integration tests, I suggest you use an email API to read the response from your inbox.

**Comment by simax** [comment]
Makes sense. I guess I was thinking that I can "confirm" a user with the `AdminConfirmSignUpAsync` without supplying a password - but that doesn't really merit a security problem. With the forgotten password flow, if I could get the verification code it would be possible to change a users password programmatically and that would be a security hole.  For the forgotten password flow I'll defer to unit tests and mock the objects as you suggest.
