### ISSUE TITLE
Where is S3 Intelligent-Tiering Storage Class?

### ISSUE THREAD

**Issue by warrenkc** [aws/aws-sdk-net#1267]
AWSSDK, Version=2.3.55.2

I would like to use the intelligent tiering storage class, but it doesn't seem to be available. Is it possible with this SDK version? Thank you!

namespace Amazon.S3
{
    public sealed class S3StorageClass : ConstantClass
    {
        public static readonly S3StorageClass Standard;
        public static readonly S3StorageClass ReducedRedundancy;
        public static readonly S3StorageClass Glacier;
        public static readonly S3StorageClass StandardInfrequentAccess;

        public S3StorageClass(string value);

        public static S3StorageClass FindValue(string value);

        public static implicit operator S3StorageClass(string value);
    }
}

**Comment by klaytaybai** [comment]
Hi @warrenkc, are you able to try using our V3 SDK?  You should find that it can do a lot more, and it gets maintenance support.

**Comment by warrenkc** [comment]
I am going to try to migrate to it. Thank you!
