### ISSUE TITLE
Supress UserCrypto Warning

### ISSUE THREAD

**Issue by bliles** [aws/aws-sdk-net#1268]
## Expected Behavior
I can run jobs on a Windows server without having the user profile loaded and without the job producing the error "UserCrypto is not supported.  This may be due to use of a non-Windows operating system or Windows Nano Server, or the current user account may not have its profile loaded. CryptProtectData failed. Error Code: -2146892987". Would like to be able to configure an App config setting to disable UserCrypto or suppress this error.

## Current Behavior
When running automated jobs over WinRM on a server, the running environment does not have a user profile, so using the SDK we see the error "UserCrypto is not supported.  This may be due to use of a non-Windows operating system or Windows Nano Server, or the current user account may not have its profile loaded. CryptProtectData failed. Error Code: -2146892987". Credentials have been supplied using the App config so it is not necessary for UserCrypto to be used.

I would like a way to suppress the error or prevent the SDK from trying to use UserCrypto.

## Steps to Reproduce (for bugs)
Tell me if you need a MRE, I can produce, but basically any CLI app that uploads a file to S3. Run this app remotely using WinRM or on a non-Windows operating system, or Window Server Nano.

## Context
This issue caused concern that our app was broken by producing a misleading error message.

## Your Environment
* AWSSDK.Core version used: 3.3.100.7
* Service assembly and version used: AWSSDK.S3 version=3.3.101.5
* Operating System and version: Windows Server 2016
* Visual Studio version: 2017
* Targeted .NET platform: 4.6.2

**Comment by klaytaybai** [comment]
Also mentioned in https://github.com/aws/aws-sdk-net/issues/1072
