### ISSUE TITLE
Failure trying to use SDK in Xamarin.Mac app

### ISSUE THREAD

**Issue by tylerwilson** [aws/aws-sdk-net#1269]
## Expected Behavior
I expected that adding the AWSSDK.Core to a Xamarin.Mac app would work.

## Current Behavior
When I add the AWSSDK.Core, AWSSDK.SimpleNotificationService, PCLCrypto and Validation to a new project, and I build, I get the following error:

Could not load file or assembly 'Xamarin.iOS' or one of its dependencies

## Possible Solution
I suspect that the issue is the AWSSDK.Core reference to Xamarin.iOS instead of Xamarin.Mac a more generic netstandard2.0

## Steps to Reproduce (for bugs)
I created a Xamarin.Mac app from scratch using Visual Studio for Mac. I added the ASKSDK.SimpleNotification, PCLCrypto and Validation packages. I added some AWS code, and then tried to execute. I got the file not found error above.

## Your Environment
AWSSDK verison 3.3.101.2
VS for Mac v8.0.4
MacOS 10.14.4
Xamarin.Mac 5.8.0.0

**Comment by kvasukib** [comment]
@tylerwilson Thank you for reporting to us. We only support Xamarin.iOS and Xamarin.Android through the AWS SDK for Xamarin. Are you trying to use our SDK for Xamarin.Mac platform?

**Comment by tylerwilson** [comment]
Yes, I was trying to use it in a Xamarin.Mac application. Once I saw that it is locked to Xamarin.iOS I switched to using a .NET Core Console application.

I do not know what it is involved in setting targets for a .NET package, but perhaps it is just a flag you can add to support Xamarin.Mac as well? 

Thank you.

**Comment by GitJit** [comment]
I am also stuck in same error while developing for Xamarin Mac.

**Comment by uxsoft** [comment]
Same here

**Comment by ashishdhingra** [comment]
Hi @tylerwilson,

Could you please try using the 3.5 version of SDK and confirm if the issue is resolved?

Thanks,
Ashish
