### ISSUE TITLE
ClientConfig.EndpointDiscoveryEnabled is checked on every request, causing poor performance

### ISSUE THREAD

**Issue by CCludts** [aws/aws-sdk-net#1270]
Hi. We are using the AWS sdk for DynamoDBv2. 

Explicitly setting EndpointDiscoveryEnabled on the AmazonDynamoDBConfig to any value (true OR false) uses 40% less CPU per request. With this setting the sdk also allocates 45% less garbage per request (900kb -> 500kb).

Profiling reveals that FallbackEndpointDiscoveryEnabledFactory.Enabled is called on every dynamoDB request. It uses CredentialProfileStoreChain to look for config files (I assume), which is expensive. The result of this operation is never cached.

default AmazonDynamoDBConfig  (10 concurrent PutItem requests, see code below)
![image](https://user-images.githubusercontent.com/18717967/56868228-dc8f7480-69ef-11e9-8ef7-43f35f5b599a.png)

same test as above, but EndpointDiscoveryEnabled set to any value
![image](https://user-images.githubusercontent.com/18717967/56868187-70ad0c00-69ef-11e9-9e78-f2f77227f1fa.png)

(please note that the absolute values reported in the profiler are much higher than usual. this is due to deep-profiling. Running the test without deep profiling yields the same results)

## Expected Behavior
Expensive configuration checks are cached

## Current Behavior
FallbackEndpointDiscoveryEnabledFactory uses CredentialProfileStoreChain to check config files on every single request.

## Possible Solution
Cache configuration variable after retrieving the result. I'm unsure how the sdk usually caches values like these. One option would be to cache it in ClientConfig.cs

```C#
        public bool EndpointDiscoveryEnabled
        {
            get
            {
                if (!this.endpointDiscoveryEnabled.HasValue)
                {
                    var endpointDiscoveryEnabled = FallbackEndpointDiscoveryEnabledFactory.GetEnabled();
                    if (endpointDiscoveryEnabled != null)
                    {
                        this.endpointDiscoveryEnabled.Value = endpointDiscoveryEnabled.Value;   // SUGGESTED PATCH
                        // return endpointDiscoveryEnabled.Value;   // COMMENTED OUT
                    }
                    else
                    {
                        this.endpointDiscoveryEnabled.Value = false;   // SUGGESTED PATCH
                        // return false;   // COMMENTED OUT
                    }
                }

                return this.endpointDiscoveryEnabled.Value;
            }
            set { this.endpointDiscoveryEnabled = value; }
        }
```

## Steps to Reproduce (for bugs)
code used for benchmark:

```C#
using System;
using System.Collections.Generic;
using System.Net;
using System.Threading;
using System.Threading.Tasks;
using Amazon;
using Amazon.DynamoDBv2;
using Amazon.DynamoDBv2.Model;
using UnityEngine;

public class DynamoTest : MonoBehaviour {
    AmazonDynamoDBClient dy;

    void Start() {
        dy = new AmazonDynamoDBClient("key", "secretkey", CreateDynamoConfig());

        InvokeRepeating(nameof(PutMany), 0f, 5f);
    }

    public static AmazonDynamoDBConfig CreateDynamoConfig() {
        var config = new AmazonDynamoDBConfig();
        config.RegionEndpoint = RegionEndpoint.GetBySystemName("us-east-1");
        config.ServiceURL = "http://localhost:8000/";
        config.EndpointDiscoveryEnabled = true;   // <--- 50% CPU reduction if set to any value!
        return config;
    }

    async void PutMany() {
        var tasks = new List<Task<PutItemResponse>>();
        for (int i = 0; i < 10; i++) {
            tasks.Add(Put());
        }
        await Task.WhenAll(tasks);
    }

    Task<PutItemResponse> Put() {
        return dy.PutItemAsync(new PutItemRequest {
            TableName = "MyTable",
            Item = new Dictionary<string, AttributeValue> {
                { "pk", new AttributeValue("1") },
                { "sk", new AttributeValue(Guid.NewGuid().ToString()) },
            }
        });
    }
}
```

## Context
High-performance server-application (>100 dynamodb requests per second). Heavy CPU-usage and GC allocations are avoided as much as possible in the application-code.

## Your Environment
* AWSSDK.Core version used:  0585ea645ad2cf96861f6587de2aaae2cddbe542 (HEAD -> master, tag: 3.3.492.0)
* Service assembly and version used: DynamoDBv2 netstandard2.0 (built on commit above)
* Operating System and version: Windows10 64bit
* Visual Studio version: (not using Visual Studio)
* Targeted .NET platform: .net standard 2.0

## .NET Core Info
running on Unity 2019.1.0f2 . note that we are using NetStandard 2.0 (not unity dlls!)

**Comment by matt-augustine** [comment]
We noticed a similar increase in CPU usage in one of our services that makes frequent requests to DynamoDB after updating AWSSDK.Core from `3.3.21.20` to `3.3.102` with NuGet. The service was hosted on three c5.large instances running Windows Server 2012 R2 and targeting .Net Framework 4.72.

 Before/after starting new instances with the update and putting them into rotation, with no significant change in load:
![image](https://user-images.githubusercontent.com/7634922/58842270-4966e180-8622-11e9-88e5-f01a8074e80d.png)

Setting `EndpointDiscoveryEnabled ` to `false` appears to have restored CPU usage to normal.

**Comment by Im5tu** [comment]
We discovered this issue earlier this week via a different route. We monitor the number of exceptions that are triggered via .Net Core 3's EventCounters API and noticed an increase proportional to the number of dynamo requests that we are making. The cause of the exceptions is because we didn't have the environment variable for this set (`AWS_ENABLE_ENDPOINT_DISCOVERY`).

@matt-augustine @CCludts - have you had any troubles with the setting being off?

Is there any official guidance on whether this setting should be on or off?

**Comment by matt-augustine** [comment]
> have you had any troubles with the setting being off?

We haven't had any issues with it since disabling endpoint discovery.

**Comment by CCludts** [comment]
> @matt-augustine @CCludts - have you had any troubles with the setting being off?

SDK is working fine in our production setup. If I understand correctly, endpoint discovery is disabled by default.
The expensive operation is not endpoint discovery. It's the sdk trying to read a config file on every single request, and erroring every time. Explicitly setting any value in the config fixes the problem

So if you actually need endpoint discovery, you can just enabled it.

**Comment by CCludts** [comment]
This is still an active issue

**Comment by Im5tu** [comment]
@normj - is there any chance that this could be re-triaged to be a bug, not a feature request please? The perf degradation by not setting the value is pretty big (~40%). Sorry if you're not the right person to ping about this,, wasn't sure who to go to

**Comment by Im5tu** [comment]
Classic

**Comment by Kralizek** [comment]
> Classic

@Im5tu :(
