### ISSUE TITLE
missing-region-endpoint in 3.0.0-preview

### ISSUE THREAD

**Issue by ramkumar-g** [aws/aws-sdk-net#1278]
Missing region endpoints - AP-SOUTH-1

PFA
![missing-region-endpoint](https://user-images.githubusercontent.com/4058503/57153598-56f73480-6df4-11e9-9b76-141b1f560c62.png)

**Comment by assyadh** [comment]
Hi,

Which version of AWSSDK.Core are you using? 

AP-SOUTH-1 is supported in the latest versions: https://github.com/aws/aws-sdk-net/blob/11e2a5a7ca0a0806767247af2ed647a0e41a2e06/sdk/src/Core/RegionEndpoint/RegionEndpoint.cs#L106

I suggest you update your dependency version.

**Comment by ramkumar-g** [comment]
I tried this version - https://www.nuget.org/packages/AWSSDK.Lambda/3.0.0-preview and this https://www.nuget.org/packages/AWSSDK.Core/3.0.0-preview

**Comment by ramkumar-g** [comment]
oh wait!
sorry, my bad. I assumed this was a preview version update for .netcore 3.0.
