### ISSUE TITLE
AmazonS3Uri Unicode Decoding Error

### ISSUE THREAD

**Issue by bigmarkoberg** [aws/aws-sdk-net#1281]
When parsing a S3 URI that contains Unicode characters in the key name, the Key property of the AmazonS3Uri object is not correctly decoded.

## Expected Behavior
If I have a sample S3 URI:
"https://s3.us-east-2.amazonaws.com/bucketname/123—456/"
Note that the key part of the URI has the Unicode character EM-Dash — (in UTF8 hex 0xE2 0x80 0x94).  Also note that this sample URI is non-existent.  In the real application, a legitimate, existing bucket and key that has a EM Dash character are used.
After creating a new AmazonS3Uri with this URI as a string, the Key property of the AmazonS3Uri should report:
"123—456/" or "123\u00E2\u0080\u0094456/"
Instead it reports:
"123â\u0080\u0094456/"

## Current Behavior
Currently the constructor of the AmazonS3Uri object uses the AbsolutePath property of the System.Uri object passed in (from our example above, "/bucketname/123%E2%80%94456/") and then the Key and Bucket properties are parsed using a custom private, static function called Decode.  This function does not decode our example Uri object correctly when certain Unicode characters are used.  See example above.

## Possible Solution
A possible solution is the replace the private, static function Decode with [System.Net.WebUtility.UrlDecode](https://docs.microsoft.com/en-us/dotnet/api/system.net.webutility.urldecode).  This function is part of multiple frameworks, .net core, and .net standard.

## Steps to Reproduce
```
string url = "https://s3.us-east-2.amazonaws.com/bucketname/123—456/";
Amazon.S3.Util.AmazonS3Uri s3uri = new Amazon.S3.Util.AmazonS3Uri(url);
Console.WriteLine(s3uri.Key);
```

## Context
Any object within a bucket with this type of Unicode character will not be accessible if the Key property of the AmazonS3Uri object is used in later Amazon.S3.AmazonS3Client.GetObject requests.

## Environment
* AWSSDK.S3 version used: 3.3.101.13
* Operating System and version: Windows 10 Pro 10.0.17134 Build 17134
* Visual Studio version: MSVS Community 2019 v 16.0.3
* Targeted .NET platform: .NET Framework 4.7.2

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
@bigmarkoberg , thanks for reporting this.
