### ISSUE TITLE
DynamoDB TransactWrite get responseItems from TransactionCanceledException

### ISSUE THREAD

**Issue by CCludts** [aws/aws-sdk-net#1282]
feature request:

Getting the responseItems from TransactionCanceledException would be very helpful. We are currently doing consistent reads after every TransactionCanceledException, which is only a half-fix since the items might have changed in the meantime.

**Comment by CCludts** [comment]
This issue is still present, and would still be very helpful.
Since writing this thread one year ago, multiple issues have come up because of this.

Every time multiple hours were lost writing fragile workarounds.

**Comment by ashishdhingra** [comment]
Hi @CCludts,

Good afternoon.

Please refer the https://github.com/aws/aws-sdk-net/issues/1292#issuecomment-790003583 where I had added findings for `TransactionCanceledException`. There is limited information returned by the DynamoDB service, which does not include item list which might have failed. However, looking at a _Note_ under **TransactionCanceledException** for [TransactWriteItems](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_TransactWriteItems.html) service API operation, the `Transaction cancellation reasons are ordered in the order of requested items, if an item has no error it will have NONE code and Null message.`. So it appears that you could use this order and compare it with initial list of items passed to `TransactWriteItems` to figure out which item failed and corresponding reason. The information provided by SDK is limited by the service API model. 

Hope this helps.

Thanks,
Ashish

**Comment by ShqipognjaLL** [comment]
Would like to know if we can resolve this issue as well.
