### ISSUE TITLE
AmazonECSClient - BlueGreen Deployment

### ISSUE THREAD

**Issue by JakodeWet** [aws/aws-sdk-net#1284]
We are currently using CloudFormation to provision our resources, but BlueGreen for ECS is not currently supported. So we opted to write a Lambda to handle the creation of a CustomType to create the service and blue green.

I have setup the service, but can't seem to create the ECS service with a blue/green deployment strategy? I have tried adding two target group ARN's seperated by comma, but that fails.

Is this possible?

```
var ecsClient = new AmazonECSClient();

var createServiceRequest = new CreateServiceRequest
{
ServiceName = createServiceInput.ServiceName,
SchedulingStrategy = SchedulingStrategy.REPLICA,
PropagateTags = PropagateTags.SERVICE,
PlatformVersion = createServiceInput.PlatformVersion,
Tags = createServiceInput.Tags.Select(t => new Amazon.ECS.Model.Tag { Key = t.Key, Value = t.Value }).ToList(),
NetworkConfiguration = new NetworkConfiguration
{
AwsvpcConfiguration = new AwsVpcConfiguration
{
AssignPublicIp = AssignPublicIp.DISABLED,
SecurityGroups = createServiceInput.SecurityGroups,
Subnets = createServiceInput.Subnets
}
},
LaunchType = createServiceInput.LaunchType == "FARGATE" ? LaunchType.FARGATE : LaunchType.EC2,
HealthCheckGracePeriodSeconds = createServiceInput.HealthCheckGracePeriodSeconds,
EnableECSManagedTags = createServiceInput.EnableECSManagedTags,
DesiredCount = createServiceInput.DesiredCount,
DeploymentController = new DeploymentController { Type = DeploymentControllerType.CODE_DEPLOY },
DeploymentConfiguration = new DeploymentConfiguration { MinimumHealthyPercent = createServiceInput.MinimumHealthyPercentage, MaximumPercent = createServiceInput.MaximumHealthyPercentage },
Cluster = createServiceInput.Cluster,
TaskDefinition = createServiceInput.TaskDefinitionArn,
LoadBalancers = new List
{
new LoadBalancer
{
ContainerName = createServiceInput.ContainerName,
ContainerPort = createServiceInput.ContainerPort,
TargetGroupArn ="arn:aws:elasticloadbalancing:xxxxx"
}
}
};

var createServiceResult = await ecsClient.CreateServiceAsync(createServiceRequest).ConfigureAwait(false)
```

I have set the deployment controller to CODE_DEPLOY but this doesn't seem to do anything

**Comment by sstevenkang** [comment]
This seems like the wrong place to ask the question since there's nothing SDK related.  I would suggest opening a feature request on https://github.com/aws/containers-roadmap/.  For service related question, I would open a ticket against AWS support.

**Comment by JakodeWet** [comment]
Hi @sstevenkang  I am not sure why you say this is not related to the SDK?
I am using the AWSSDK.EcsClient to provision infrastructure. Part of that is to setup a BlueGreen Deployment for one of the services? I have followed all documentation of the SDK to create the Service, which is working. I need to setup the BlueGreen Deployment/Application/DeploymentConfiguration via the SDK aswell, but can't seem to find the settings in either the ECSClient or CodeDeployClient?

To me this is 100% related to the SDK's unless these specific features are not yet available via the SDK?

**Comment by sstevenkang** [comment]
I am confused what's the specific ask from the SDK is.  Is there a CodeDeploy/ECS service API that is not exposed in the service?  Is there a

**Comment by JakodeWet** [comment]
Hi Steven. So when we create a Fargate ECS service via the AWS console, there is an option to choose the Blue/Green deployment strategy. When selecting this option, you need to specify the ALB, production listener (port 80), test listener (port 9000) and 2 x Target Groups. This creates the service AND the CodeDeploy application and deployment configuration that uses the BG strategy when we trigger a new code deploy.

The problem is that this functionality is not exposed via the CloudFormation API as yet, so we thought we could use the SDK's to create a custom Lambda that will create this resource for us and then reference this in the CFN as a CustomResourceType. But I can't seem to find any reference as to how to setup the BG deployments using the ECS or CodeDeploy SDK clients. 

It might be that this functionality is also not availabe via the SDK as yet or I am using missing the SDK Client methods?

Thanks for your feedback. Appreciate all the work that goes into these clients.

**Comment by sstevenkang** [comment]
Ah, I see.  That is a functionality specifically in AWS console which is why it is not exposed in CloudFormation or SDKs.  It is a high level functionality that requires resource creation and I wouldn't expect this to be exposed in low level tools/services such as SDKs or CloudFormation.

Are you following this tutorials?  https://docs.aws.amazon.com/AmazonECS/latest/developerguide/create-blue-green.html#create-blue-green-loadbalancer

I would recommend that you make a feature request to ECS team to implement this as a REST API which will make it trivial to be exposed in SDKs and CF.

**Comment by JakodeWet** [comment]
Thanks for the feedback. Think I have been missing something. I see that there are methods on the CodeDeploy client for this...
CreateApplicationAsync and CreateDeploymentGroupAsync
I should be able to create all this after setting up the service via the ECS Client. I was under the impression it would all be setup via the ECSClient, but a combination of this and CodeDeployClient should do the trick.

Thanks again
