### ISSUE TITLE
Amazon.Lambda.AmazonLambdaException

### ISSUE THREAD

**Issue by lbezawada** [aws/aws-sdk-net#1285]
The code is throwing an intermittent AmazonLambdaException when i try to invoke a lambda from another lambda and both are in the VPC. I don't pass any explicit credentials for invocation.

The payload in the InvokeRequest is  pretty big. I saw another issue that was pretty similar to this but didn't see any resolution there.

I am using **Amazon.Lambda.Core 1.0.0**, **AWSSDK.Lambda 3.3.12.2**. The lambdaInvocation is wrapped in a provider targeting netstandard2.0 and the lambdas themselves are using dotnetcore2.0 runtime.

```
using (AmazonLambdaClient lambdaClient = new AmazonLambdaClient())
                    {
                        InvokeResponse invokeResponse = await lambdaClient.InvokeAsync(invokeRequest);

                        if (invokeResponse.StatusCode < 200 || invokeResponse.StatusCode > 299)
                        {
                            apiStatTracker.Error = true;
                        }

                        return invokeResponse;
                    }
```

**The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method**. Consult the service documentation for details.\nSTACK TRACE:\n   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)\n   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)\n   at Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5`1.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__7`1.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5`1.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__1`1.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at Mantle.LambdaFramework.Aws.LambdaInvoker.<InvokeAsync>d__0.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n

**Comment by sstevenkang** [comment]
Hi, we need more information to debug intermittent issues.  Please provide minimal repro or requestIds so that we can trace what requests are made.

**Comment by klaytaybai** [comment]
I'm closing this until we get more info.
