### ISSUE TITLE
AWS SDK Step Functions intermittently returning null Ouput

### ISSUE THREAD

**Issue by nocoli** [aws/aws-sdk-net#1287]
My application relies heavily on step functions and uses the .NET SDK for AWS step functions. The issue is occurring intermittently where the successful execution of the step function is returning null instead of the actual output. 

More specifically, the result from the `DescribeExecutionAsync` method is returning with an `ExecutionStatus` of SUCCEEDED but the Output is null. I can see that the output should not be null as when I navigate to that specific step function execution in AWS the output is populated in my browser as I expected it to be returned to my application.

In the mean time I have a try catch block handling this and retrying the `DescribeExecutionAsync` on that execution a couple of seconds later which is returning the expected output, so there may be a bug with the SDK.

Here is an example of the request I am making:
```
DescribeExecutionResponse response = _stepFunctions.DescribeExecutionAsync(
    new DescribeExecutionRequest
    {
        ExecutionArn = arn
    }
).Result;

if (response.Status == ExecutionStatus.SUCCEEDED){
    _logger.LogInformation($"Execution arn {arn} finished with {response.Output}");
}
```
Which produces an example log like: `arn arn:aws:states:ap-southeast-2:4654684768:execution:ApplyWorkspaceSecurityStateMachine-4fsd654f56sd4f:asd54fsd356-a5sd-564sa-sd456f-65466d564654 finished with  `

I found someone who had a similar issue with the Javascript AWS SDK but there was no resolution https://github.com/aws/aws-sdk-js/issues/2462.Any help would be great. 

Thanks, Nic

**Comment by klaytaybai** [comment]
Hi @nocoli, can you please include the RequestId of a failing response?  This doesn't seem to be an issue with the .NET SDK because we aren't doing any customizations to the service's response.  I think we'll need the RequestIds to investigate further.  

Could you also please let us know which version of the SDK you are using?
Can you verify that the length of the expected output of a failing response is less than 32768 characters?

You should also structure your async call as follows: 
`DescribeExecutionResponse response = await _stepFunctions.DescribeExecutionAsync(
    new DescribeExecutionRequest
    {
        ExecutionArn = arn
    }
).ConfigureAwait(false);`

**Comment by nocoli** [comment]
Thanks @klaytaybai  for your response. I have just added logging for the Request ID so whenever it next occurs I will be able to provide you with a RequestId.

I am using AWSSDK.StepFunctions 3.3.2.27.
I can also verify that the length of the expected output is less than 32,768 characters. I'm not getting anywhere near that character count as most responses are a couple of hundred characters at most.

**Comment by nocoli** [comment]
Hi @klaytaybai,
Here is the requestId of a failed response: a145b2f1-804c-11e9-a6b4-417da6f05d5f. Not sure if this has anything to do with it but in AWS under the step functions Execution details I can see this character in the output: �.

Let me know if you need any further details.

**Comment by nocoli** [comment]
Hi, I am still experiencing this issue. Another RequestID from the last 24 hours `b951ecb0-129e-487c-92e2-e04ac1fdee9b`.

**Comment by ashishdhingra** [comment]
Hi @nocoli,

Good afternoon.

I was going through the issue backlog and came across this guidance question.

Please let me know if this is still an issue that required further investigation or if this issue could be closed.

Thanks,
Ashish

**Comment by nocoli** [comment]
Hi @ashishdhingra this has not happened for some time. I'll close and if it comes up again I'll open a new issue and reference this old one.
Thanks
