### ISSUE TITLE
Amazon.CostExplorer.Model.TagValues should allow empty list in IsSetValues method

### ISSUE THREAD

**Issue by osvaldolove** [aws/aws-sdk-net#1289]
## Expected Behavior
When submitting a Amazon.CostExplorer.Model.GetCostUsageRequest, the following should be valid.
```csharp
new TagValues
{
  Key = string.Empty,
  Values = new List<string>()
}
```

## Current Behavior
When submitting a Amazon.CostExplorer.Model.GetCostUsageRequest with a Filter object containing the TagValues object with an empty Key and an empty Values list an error is returned stating `Tag expression must have key and values set`. This is not true, sending the object as detailed in Expected Behavior should work and is the equivalent of filtering for untagged resources.

## Possible Solution
In Amazon.CostExplorer.Model.TagValues ` IsSetValues()` method it should read
```csharp        
internal bool IsSetValues()
{
  return this._values != null;
}
```
instead of
```csharp
internal bool IsSetValues()
{
  return this._values != null && this._values.Count > 0; 
}
```
I have tested this locally and it does indeed fix the issue.

## Steps to Reproduce (for bugs)
```csharp
                var costExplorerClient = new AmazonCostExplorerClient("REDACTED",
                    "REDACTED", RegionEndpoint.USWest2);
                var usageReport = costExplorerClient.GetCostAndUsage(new GetCostAndUsageRequest
                {
                    Filter = new Expression
                    {
                        Tags = new TagValues
                        {
                            Key = string.Empty,
                            Values = new List<string>(),
                        }
                    },
                    TimePeriod = new DateInterval
                    {
                        Start = "2019-05-01",
                        End = "2019-06-01"
                    },
                    Granularity = Granularity.DAILY
                });
```

## Context
We are trying to filter untagged resources using the .NET SDK for Cost Explorer.

## Your Environment
* AWSSDK.Core version used: 3.3.101.2
* Service assembly and version used: AWSSDK.CostExplorer - 3.3.100.11
* Operating System and version: Windows 10 Home
* Visual Studio version: Visual Studio 2019 Pro
* Targeted .NET platform: 4.7.2

**Comment by klaytaybai** [comment]
Thanks for reporting this.  Unfortunately we're concerned that the fixes for this and similar issues would be breaking changes in the current major version, so we're holding off on a fix.

**Comment by osvaldolove** [comment]
Hi,

I have discovered that this is not a problem. It's just the Values property needs to be formatted correctly.

This works...

```csharp
new TagValues
{
  Key = string.Empty,
  Values = new List<string>{ string.Empty }
}
```
Note the `string.Empty` or `""` is required when initialising the list to make this work.

I think the real problem is the documentation or SDK could make this error clearer :)

Thanks,

Olly
