### ISSUE TITLE
Multiple conditions on a ScanFilter or QueryFilter is overwitten

### ISSUE THREAD

**Issue by tgran6** [aws/aws-sdk-net#1290]
When adding more than one condition to the ScanFilter or QueryFilter the previous condition is overwritten.

## Expected Behavior
Documentation states you should be able to add as many conditions as you like to the Scan or Query filter.  Example of ScanFilter from [Amazon](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ScanMidLevelDotNet.html):

string tableName = "Thread";
Table ThreadTable = Table.LoadTable(client, tableName);

ScanFilter scanFilter = new ScanFilter();
scanFilter.AddCondition("ForumId", ScanOperator.Equal, 101);
scanFilter.AddCondition("Tags", ScanOperator.Contains, "sortkey");

Search search = ThreadTable.Scan(scanFilter);

## Current Behavior
When running the above example the first AddCondition statement works correctly.  The second AddCondition overwrites the first and you end up with only one condition in the filter.
Currently using version 3.3.101.7 in nuget
I have gone back to version 3.3.16.5 and it always seems to have worked this way.

## Context
When applying multiple filters to a scan or a query only the most recent condition is applied producing incorrect results.  Validated this work in the AWS Console under items in the DynamoDB Table view.

## Your Environment
* AWSSDK.Core version used: 3.3.101.7 - 3.3.16.5
* Operating System and version: Microsoft Windows 10 Pro - 10.0.17763 Build 17763
* Visual Studio version: Microsoft Visual Studio Community 2019 Preview - 16.1.0 Preview 3
* Targeted .NET platform: .NET Core 2.1

## .NET Core Info
* .NET Core version used for development: .NET Core 2.1
* .NET Core version installed in the environment where application runs: .NET Core 2.1
* Output of `dotnet --info`: 

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.300-preview-010067\

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.1.700-preview-009601 [C:\Program Files\dotnet\sdk]
  2.1.700-preview-009618 [C:\Program Files\dotnet\sdk]
  2.2.300-preview-010050 [C:\Program Files\dotnet\sdk]
  2.2.300-preview-010067 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by klaytaybai** [comment]
Hi @tgran6, I wasn't able to reproduce this issue.  Can you please verify that you are having problems with code like your reproduction sample--namely that you are adding conditions with **different** attributes?
