### ISSUE TITLE
[S3] Select is broken on large-ish files

### ISSUE THREAD

**Issue by indy-singh** [aws/aws-sdk-net#1296]
Reproducible example; https://github.com/aws/aws-sdk-net/issues/1296#issuecomment-493769504

## Expected Behavior
The count should be correct:-
```
Expected...
Key: [BCD, 20933]
Key: [DEF, 13528]
Key: [FGH, 12188]
Key: [HIJ, 16105]
Key: [JKL, 21117]
Key: [LMN, 13560]
Key: [NOP, 18547]
```

## Current Behavior
The count is wrong for result set:-
```
Actual...
Key: [BCD, 20933]
Key: [DEF, 13527]
Key: [FGH, 12187]
Key: [HIJ, 16105]
Key: [JKL, 21117]
Key: [LMN, 13560]
Key: [NOP, 18545]
```

I also get malformed data returned, every line should be in the `s._1, s._2` format according to the query:-

```
bad line: DE
bad key: F
bad line: 3
bad line: NO
bad key: P
bad line: 3
bad line: NO
bad key: P
bad line: 3
bad line: FG
bad key: H
```

## Possible Solution
Haven't investigated further, just can consistently reproduce broken behaviour

## Steps to Reproduce (for bugs)
See above

## Your Environment
* AWSSDK.Core version used: 3.3.101.9
* Service assembly and version used: 3.3.101.16
* Operating System and version: Windows 10 Build 1809
* Visual Studio version: 15.9.11
* Targeted .NET platform: 4.5.2

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by indy-singh** [comment]
I've only been able to reproduce this on "large" files. I don't know where the threshold is, but on smaller files (< 10 MB). My results are consistent correct.

**Comment by indy-singh** [comment]
I also haven't been able to ascertain whether this is an SDK issue or a service issue.

**Comment by indy-singh** [comment]
Slightly more concise reproduction:-

```csharp
public static void Main(string[] args)
{
	var client = new AmazonS3Client(new BasicAWSCredentials(_accessKey, _secretKey), RegionEndpoint.EUWest1);

	Console.WriteLine("Generating file...");
	var expectedCount = GenerateFile("BCD", "DEF", "FGH", "HIJ", "JKL", "LMN", "NOP");

	Console.WriteLine("Uploading file...");
	UploadFileToS3(client);

	Console.WriteLine("Selecting file from S3 to get count..");
	SelectFile(client, expectedCount, "BCD", "DEF", "FGH", "HIJ", "JKL", "LMN", "NOP");
}

private static void UploadFileToS3(AmazonS3Client client)
{
	client.PutObject(new PutObjectRequest
	{
		Key = _fileKey,
		BucketName = _bucketName,
		InputStream = File.OpenRead(_localPath)
	});
}

private static void SelectFile(AmazonS3Client client, IDictionary<string, int> expected, params string[] keys)
{
	var keys_in = string.Concat("'", string.Join("', '", keys), "'");

	var response = client.SelectObjectContent(new SelectObjectContentRequest
	{
		Key = _fileKey,
		Bucket = _bucketName,
		ExpressionType = ExpressionType.SQL,
		Expression = $"select s._1, s._2 from S3Object s WHERE s._1 IN ({keys_in}) AND s._2 = '3'; ",
		InputSerialization = new InputSerialization
		{
			CSV = new CSVInput()
		},
		OutputSerialization = new OutputSerialization
		{
			CSV = new CSVOutput()
		}
	});

	var actual = new Dictionary<string, int>();

	foreach (var key in keys)
	{
		actual[key] = 0;
	}

	using (var stream = response.Payload)
	{
		foreach (var ev in stream)
		{
			if (ev is RecordsEvent records)
			{
				using (var reader = new StreamReader(records.Payload, Encoding.UTF8))
				{
					while (reader.EndOfStream == false)
					{
						var line = reader.ReadLine();

						if (line.Contains(","))
						{
							var tokens = line.Split(',');
							var key = tokens[0];

							if (actual.ContainsKey(key))
							{
								actual[key]++;
							}
							else
							{
								Console.WriteLine("bad key: " + key);
							}
						}
						else
						{
							Console.WriteLine("bad line: " + line);
						}
					}
				}
			}
		}
	}

	Console.WriteLine("Actual...");
	foreach (var key in keys)
	{
		var expectedValue = expected[key];
		var actualValue = actual[key];
		Console.WriteLine($"Key: {key} Actual: {actualValue} Expected: {expectedValue} Different? {actualValue != expectedValue}");
	}
}

private static IDictionary<string, int> GenerateFile(params string[] keys)
{
	var random = new Random(252028800);

	var dict = new Dictionary<string, int>
	{
		["ABC"] = random.Next(100000, 200000),
		["BCD"] = random.Next(100000, 200000),
		["CDE"] = random.Next(100000, 200000),
		["DEF"] = random.Next(100000, 200000),
		["EFG"] = random.Next(100000, 200000),
		["FGH"] = random.Next(100000, 200000),
		["GHI"] = random.Next(100000, 200000),
		["HIJ"] = random.Next(100000, 200000),
		["IJK"] = random.Next(100000, 200000),
		["JKL"] = random.Next(100000, 200000),
		["KLM"] = random.Next(100000, 200000),
		["LMN"] = random.Next(100000, 200000),
		["MNO"] = random.Next(100000, 200000),
		["NOP"] = random.Next(100000, 200000),
		["OPQ"] = random.Next(100000, 200000)
	};

	var terms = new[] {12, 24, 36, 48, 60};
	var mileages = new[] {6000, 10000, 15000, 20000, 25000, 30000, 40000, 50000};
	var list = new List<string>();

	var keysWeCareAbout = new Dictionary<string, int>();

	foreach (var key in keys)
	{
		keysWeCareAbout[key] = 0;
	}

	foreach (var pair in dict)
	{
		for (int i = 0; i < pair.Value; i++)
		{
			var elementId = random.Next(1, 10);
			var next = random.Next(100000, 999999);
			var term = terms[random.Next(0, terms.Length)];
			var mileage = mileages[random.Next(0, mileages.Length)];

			if (keysWeCareAbout.ContainsKey(pair.Key) && elementId == 3)
			{
				keysWeCareAbout[pair.Key]++;
			}
			var line = $"{pair.Key},{elementId},{next},{term},{mileage},{random.Next(1, 100)}.{random.Next(1, 99)},,";
			list.Add(line);
		}
	}

	File.WriteAllLines(_localPath, list.OrderBy(x => random.Next()), Encoding.UTF8);

	return keysWeCareAbout;
}
```

**Comment by indy-singh** [comment]
It looks like something is malforming the lines:-

```

**Comment by indy-singh** [comment]
It looks like something is malforming the lines:-

```
bad line: DE
bad key: F
bad line: 3
bad line: NO
bad key: P
bad line: 3
bad line: NO
bad key: P
bad line: 3
bad line: FG
bad key: H
```

If we join the "bad" output we get this:-

```
DEF3NOP3NOP3FGH
```

And if you look at what I'm missing from the counts:-
```
Key: BCD Actual: 20933 Expected: 20933 Different? False
Key: DEF Actual: 13527 Expected: 13528 Different? True
Key: FGH Actual: 12187 Expected: 12188 Different? True
Key: HIJ Actual: 16105 Expected: 16105 Different? False
Key: JKL Actual: 21117 Expected: 21117 Different? False
Key: LMN Actual: 13560 Expected: 13560 Different? False
Key: NOP Actual: 18545 Expected: 18547 Different? True
```

I'm missing one `DEF`, one `FGH`, and two `NOP`.

Still don't know if this is a service issue or SDK issue.

**Comment by indy-singh** [comment]
If you hit S3 Select directly in Postman (`bucketName.s3.amazonaws.com/fileKey?select&select-type=2`), using this request:-

```xml
<SelectRequest>
    <Expression>select s._1, s._2 from S3Object s WHERE s._1 IN ('BCD', 'DEF', 'FGH', 'HIJ', 'JKL', 'LMN', 'NOP') AND s._2 = '3'</Expression>
    <ExpressionType>SQL</ExpressionType>
    <InputSerialization>
        <CSV>
            <FieldDelimiter>,</FieldDelimiter>
        </CSV>
    </InputSerialization>
    <OutputSerialization>
        <CSV>
            <FieldDelimiter>,</FieldDelimiter>
        </CSV>
    </OutputSerialization>
</SelectRequest>
```

You'll see the [records event](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectSELECTContent.html#s3select-frametype-record) is chopping up the stream:-

```
JKL,3
NO– OÅ  þM   UñØžƒ
:message-type event:event-type Records
:content-type application/octet-streamP,3
LMN,3
JKL,3
```

If you look carefully it has chopped up `NOP,3` by inserting the records events in between `O` and `P`. This would explain the bad line / bad key output in my earlier comment.

**Comment by indy-singh** [comment]
If I change the SQL statement to be:-

```csharp
Expression = $"SELECT s._1, s._2 from S3Object s WHERE s._1 IN ({keys_in}) AND s._2 = '3' AND s._4 = '48' AND s._5 = '30000' ; ",
```

And the if statement to be:-

```csharp
if (keysWeCareAbout.ContainsKey(pair.Key) && elementId == 3 && term == 48 && mileage == 30000)
```

Then everything is perfect:-

```
Key: BCD Actual: 481 Expected: 481 Different? False
Key: DEF Actual: 350 Expected: 350 Different? False
Key: FGH Actual: 305 Expected: 305 Different? False
Key: HIJ Actual: 382 Expected: 382 Different? False
Key: JKL Actual: 515 Expected: 515 Different? False
Key: LMN Actual: 350 Expected: 350 Different? False
Key: NOP Actual: 430 Expected: 430 Different? False
```

I don't get any bad output.

And if I change the XML request to be:-

```xml
<Expression>select s._1, s._2 from S3Object s WHERE s._1 IN ('BCD', 'DEF', 'FGH', 'HIJ', 'JKL', 'LMN', 'NOP') AND s._2 = '3' and s._4 = '48' and s._5 = '30000'</Expression>
```

Then the records event is still there but happens to slice up the stream correctly:-

```
JKL,3
FGH,3
v?
weUX3BT
:message-typeevent:event-typeRecords
:content-typeapplication/octet-streamJKL,3
DEF,3
JKL,3
```

I still can not confirm if the S3 Select Service is at fault here or if the SDK is reading the incoming stream incorrectly in some scenarios.

**Comment by indy-singh** [comment]
I've managed to narrow this down to a test case that returns bad results 48% of the time. I've updated my https://github.com/aws/aws-sdk-net/issues/1296#issuecomment-493769504 containing the relevant code.

Snippet of output:-

```
Index: 4
Selecting file from S3 to get count..
Got record event
bad line: DE
Got record event
bad key: F
Key: DEF Actual: 1276 Expected: 1277 Match? False
Not good

Index: 5
Selecting file from S3 to get count..
Got record event
bad line: DE
Got record event
bad key: F
Key: DEF Actual: 1276 Expected: 1277 Match? False
Not good

Index: 6
Selecting file from S3 to get count..
Got record event
Got record event
All good

Index: 7
Selecting file from S3 to get count..
Got record event
bad line: DE
Got record event
bad key: F
Key: DEF Actual: 1276 Expected: 1277 Match? False
Not good

Index: 8
Selecting file from S3 to get count..
Got record event
Got record event
All good
```
I _still_ haven't managed to confirm if it is a service or SDK problem.

**Comment by indy-singh** [comment]
@sstevenkang is there any other information that would be helpful in getting this resolved?

**Comment by normj** [comment]
I'm taking a look

**Comment by normj** [comment]
The problem is we have a usability issue with the S3 select API in the SDK that we need to address.

When you are reading the `RecordsEvent` objects from the `Payload`, S3 makes no guarantees that it contains only full csv lines. Sometimes a csv line will be split over multiple `RecordEvents`. So you need to make sure you are reading from the `RecordsEvent` stream till you have a full csv line before doing any processing on it. I updated your reader code below to keep reading through multiple `RecordsEvent` till a newline was read and then do your processing. Once I did that I was able to successfully do the 100 iterations in your test code.

The SDK should have done a better job of abstracting this but I think when we originally designed the API we didn't take into account getting partial lines in a `RecordsEvent`. I'll talk with the rest of the team to see how we can improve this feature in the SDK.

```csharp
using (var stream = response.Payload)
{
    StringBuilder fullCsvRecord = new StringBuilder();
    foreach (var ev in stream)
    {
        if (ev is RecordsEvent records)
        {
            Console.WriteLine("Got record event");
            using (var reader = new StreamReader(records.Payload, Encoding.UTF8))
            {
                while (reader.EndOfStream == false)
                {
                    var c = (char)reader.Read();
                    if(c == '\n')
                    {
                        var line = fullCsvRecord.ToString();
                        fullCsvRecord.Clear();

                        if (line.Contains(","))
                        {
                            var tokens = line.Split(',');
                            var key = tokens[0];

                            if (actual.ContainsKey(key))
                            {
                                actual[key]++;
                            }
                            else
                            {
                                Console.WriteLine("bad key: " + key);
                            }
                        }
                        else
                        {
                            Console.WriteLine("bad line: " + line);
                        }
                    }
                    else
                    {
                        fullCsvRecord.Append(c);
                    }
                }
            }
        }
    }
}
```

**Comment by indy-singh** [comment]
Ahhh I see. Is it possible to update the documentation to reflect that? Or did I miss that entirely?

I think it would be awesome if the .NET API could do the heavy lifting for me. In my head if a declare `s._1, s._2` then I would expect the data to be returned in that fashion line by line. It would also be nice if it could handle different types of line endings for me (e.g `\n`, `\r\n`).

Does the API guarantee order? Cause the other option to is `ReadToEnd` all the `RecordsEvent` into one StringBuilder and then do the processing.

Would the event driven API suffer from the same issue? I used this [blog post](https://aws.amazon.com/blogs/developer/amazon-s3-select-support-in-the-aws-sdk-for-net/) as a base line example.

I'm happy for this issue to be closed, if need be.

Thanks for helping me :) :+1:

**Comment by indy-singh** [comment]
> I'll talk with the rest of the team to see how we can improve this feature in the SDK.

Any update on what, if anything was decided @normj ?

**Comment by indy-singh** [comment]
Just going through and sorting out my open issues; any update on this @normj ?

Thanks,
Indy

**Comment by ashishdhingra** [comment]
Hi @indy-singh,

Good afternoon.

I was going through the list of open issues and came across this one. From @normj comments, looks like there is a workaround available. Please advise if you would like to convert this guidance question into a feature-request (I'm not sure on how sooner this could b prioritized) or if we could close this issue.

Thanks,
Ashish

**Comment by indy-singh** [comment]
Hi @ashishdhingra ,

I would absolutely like the SDK to support this as a feature, so yes please turn this guidance question into a feature-request.

Thanks,
Indy
