### ISSUE TITLE
Provide an alternative to DynamoDb's Object Persistence Model attributes similarly to EF Core's Fluent API

### ISSUE THREAD

**Issue by fernandreu** [aws/aws-sdk-net#1300]
## Expected Behavior

Using DynamoDb's Object Persistence Model, I would like to configure my entities similarly to how I would do it with [EF Core's Fluent API](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DotNetSDKHighLevel.html). For example (taken from [here](https://www.entityframeworktutorial.net/efcore/fluent-api-in-entity-framework-core.aspx)):

```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    //Write Fluent API configurations here

    //Property Configurations
    modelBuilder.Entity<Student>()
            .Property(s => s.StudentId)
            .HasColumnName("Id")
            .HasDefaultValue(0)
            .IsRequired();
}
```

## Current Behavior

On its current state, the Object Persistence Model only allows you to specify that configuration via attributes. This implies the project containing your entities should also contain a reference to AWSSDK.DynamoDBv2.

With a fluent API (or equivalent), the same configuration could be easily added on top of the entities from another project, and passed when the DynamoDBContext are created.

## Context

I am trying to achieve a typical onion architecture with three layers: a business layer, an infrastructure layer and a presentation layer. The lack of such API is forcing me to find a workaround, such as:

1. Combine the business and infrastructure layers into a single one (not ideal)
2. Add a reference to AWSSDK.DynamoDBv2 to the business layer and define the attributes directly there (a bit better solution, but still not ideal)
3. Create intermediate entity classes inside the infrastructure layer which contain those attributes instead, and use AutoMapper to convert between the initial / annotated entities (this adds a lot of boilerplate)

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by msotiroff** [comment]
The lack of fluent entity builder is not an issue in the AWS SDK for .NET, but the presence of such would be a new feature. The convenience of not using attributes is that you can separate your business or service layer from your data layer as well as you can dynamically use different DynamoDB tables/indexes in the different environments(dev, stage, test, production). Desiring that behavior I created my own simple fluent API for access DynamoDB. You can see some examples [here](https://github.com/msotiroff/EasyDynamo#2-better-way-is-you-override-onmodelcreating-method-in-your-database-context-class). It's available as a nuget package. It's using is very similar to Entity Framework Core's using.

**Comment by fernandreu** [comment]
Your library seems very promising and in the exact direction I wanted to go. I will definitely try it!

**Comment by klaytaybai** [comment]
Thanks for that @msotiroff.  We haven't done a full review of your library, but it does look useful upon first glance.
