### ISSUE TITLE
CognitoIDPClient.InitiateAuthAsync not giving callback on Oculus Go (Android)

### ISSUE THREAD

**Issue by Christer2222** [aws/aws-sdk-net#1301]
I am making a project for the Oculus Go, and I am having users login through CognitoIDPClient.InitiateAuthAsync. This works in the Unity Editor, standard Android, standard IOS, and in standalone builds, but not on the Oculus Go (running Android).

##Expected Behavior
The scripts are expecting a callback, which never arrives.

## Current Behavior
The scripts continue past the CognitoIDPClient.InitiateAuthAsync function (as it is async), but never sends back the callback or any errors.

## Steps to Reproduce (for bugs)
Make an Android build in Unity with VR supported. This is the code handling login info.
´´´ C#
CognitoIDPClient.InitiateAuthAsync(authRequest, (authResponse) => {
			if(authResponse.Exception != null) {
				if (OnFailureF != null)
                                    OnFailureF();
                return;
            }
			
            //The timestamp format returned to AWS _needs_ to be in US Culture
            DateTime _timestamp = TimeZoneInfo.ConvertTimeToUtc(DateTime.Now);
            CultureInfo _usCulture = new CultureInfo("en-US");
            string _timeStr = _timestamp.ToString("ddd MMM d HH:mm:ss \"UTC\" yyyy", _usCulture);

			//Do the hard work to generate the claim we return to AWS
			var _challegeParams = authResponse.Response.ChallengeParameters;
            byte[] _claim = AuthenticationHelper.authenticateUser( 
                                _challegeParams["USERNAME"],
                                password, USER_POOL_NAME, _TupleAa,
                                _challegeParams["SALT"], _challegeParams["SRP_B"], 
                                _challegeParams["SECRET_BLOCK"], _timeStr);
			
			string _claimBase64 = Convert.ToBase64String(_claim);

            // construct the second request
            RespondToAuthChallengeRequest _respondRequest = new 
            RespondToAuthChallengeRequest() {
                ChallengeName = authResponse.Response.ChallengeName,
                ClientId = AppClientID,
                ChallengeResponses = new Dictionary<string, string>() {
                            { "PASSWORD_CLAIM_SECRET_BLOCK", _challegeParams["SECRET_BLOCK"] },
                            { "PASSWORD_CLAIM_SIGNATURE", _claimBase64 },
                            { "USERNAME", username },
                            { "TIMESTAMP", _timeStr } }
            };

			// send the second request
			CognitoIDPClient.RespondToAuthChallengeAsync(_respondRequest, 
                       (finalResponse) => {
                if (finalResponse.Exception != null) {
                    if (OnFailureF != null)
                        OnFailureF();
                    return;
                }
                // Ok, if we got here, we logged in, and here are some tokens
                AuthenticationResultType _authResult = finalResponse.Response.AuthenticationResult;
                string _idToken = _authResult.IdToken;
                string _accessToken = _authResult.AccessToken;
                string _refreshToken = _authResult.RefreshToken;

				if(OnSuccessF != null)
                    OnSuccessF(_idToken);
            });
        });
´´´

## Context
With this problem, one can not log into the project.

## Your Environment
Connected to the internet. Tried disconnecting.
* AWSSDK.Core version used: 3.3.518.0
* Operating System and version: Android APK level 25
* Visual Studio version: 2017
* Targeted .NET platform: 4.8

## .NET Core Info

* .NET Core version used for development: 4.8

**Comment by gentlemanSoup** [comment]
I am experiencing the same exact issue.
Does the Oculus Go not support using Amazon Cognito specifically, or is there something else going on?
Currently, we get nothing to work with, as we can't properly debug the dll's, and we get no error messages.
Would love an answer to this, as our app depends a lot on login working..

**Comment by josette-seitz** [comment]
I am also having the same issue.... please open and explain new solution...
