### ISSUE TITLE
CognitoAWSCredentials.GetIdentityIdAsync does not work in unity 2019

### ISSUE THREAD

**Issue by Thaina** [aws/aws-sdk-net#1302]
I use CognitoAWSCredentials.GetIdentityIdAsync since unity 5.6 to unity 2018 but it not working in unity 2019. It don't have any explicit log. Just silently not continued. Not fail or error anywhere I could catch

Both sdk version 3.3.518.0 and 3.3.411.0 exhibit the same behaviour

## Steps to Reproduce (for bugs)
```C#
var credentials = new CognitoAWSCredentials(poolID,cognitoENDPOINT);
credentials.AddLogin("graph.facebook.com",accessToken);
credentials.GetIdentityIdAsync((result) => {
	myIdentity = result.Response;
	Debug.Log("GetIdentityIdAsync : " + myIdentity); // never got to this line
});
```

## Your Environment

- unity 2019.1.4f
- Windows
- Android Build

**Comment by Calneideck** [comment]
I've just had the same problem start happening with DynamoDBV2,AsyncScan. No error message, just silently fails. However, I am using Unity 2018.3.
This was working fine the past few days, I didn't change anything but now it's no longer working.
