### ISSUE TITLE
.NET Core Setup Extensions Multi-Service Support Is Broken (CloudSearch/S3)

### ISSUE THREAD

**Issue by danielloganking** [aws/aws-sdk-net#1305]
## Expected Behavior
The following setup code should, with the right settings, resolve usable clients for both S3 and CloudSearch:

```csharp
var awsOptions = Configuration.GetAWSOptions();

// these are mutually incompatible depending on the settings:
// if ServiceURL is omitted, AmazonCloudSearchDomain will fail during construction
// if ServiceURL is provided, AmazonS3 will fail when making requests
services.TryAddAWSService<IAmazonS3>(awsOptions);
services.TryAddAWSService<IAmazonCloudSearchDomain>(awsOptions);
```

## Current Behavior
There is no possible combination of settings values and setup code using the `AWSSDK.Extensions.NETCore.Setup` package which can resolve a working instance of both CloudSearch and S3. Though the two objects have different fundamental dependencies (S3 requires a `Region`, CloudSearch requires a `ServiceURL`, both require `AwsCredentials`), fulfilling the dependencies for both in settings results in S3 being unusable. If `ServiceURL` is not provided then `AmazonCloudSearchDomain` cannot be constructed at all. Moreover, there is no mechanism to access underlying object constructors with `TryAddAWSService()` so the functionality of that method must be duplicated in line to set up incompatible services within the same services provider.

In such multi-service scenarios, (at least when using both CloudSearch and S3) clients are forced to manually setup and add AWS services to the services provider using base .NET Core DI library functions and settings configuration.

I expect that this may be the case for other service setups as well but did not do a systemic analysis to prove this hypothesis.

## Possible Solution
There are several solutions which go from simple but possibly incomplete to a complex and far-reaching.

1. Fix the ServiceURL setting making S3 unusable. This may not be an option if configuring the S3 ServiceURL is desired behavior
2.  Allow `ClientConfig` to be separately resolved and passed as an additional override of `TryAddAWSService()` instead of always using `AWSOptions.DefaultClientConfig`. This would not, strictly speaking, resolve the issue but would allow clients to have separate client configurations for each service.
3. Create strongly typed config objects which match the dependencies of each service, then allow them to be set and override the value within `DefaultClientConfig`. This would mean that a setting such as `AWS__ServiceURL` would be used for all services unless specifically overridden ie `AWS__CloudSearchDomain__ServiceURL`.

## Steps to Reproduce (for bugs)
1. Create a new dotnet core project.
2. Add a reference to the latest AWS S3, CloudSearch, and .NET Core Setup packages
3. Add setup code (as above) to create AWSOptions object and register `IAmazonS3` and `IAmazonCloudSearchDomain` to the services container with `TryAddAWSService`
4. Add settings to specify AWS Credentials, Region (desired S3 region), ServiceURL (desired CloudSearch domain URL)
5. Add method that makes a call to S3 (`ListObjects` is a simple test) and searches CloudSearch for anything.
6. S3 call will fail.
7. Remove ServiceURL and CloudSearch dependency will fail to construct but S3 call will work.

See [my comment below](https://github.com/aws/aws-sdk-net/issues/1305#issuecomment-497811582) for a full minimal reproduction

## Context
We have a legacy application that stored data in both S3 and CloudSearch. We are trying to abstract the data access behind an API so that we can then consolidate the data into a single data store. As this is a new API we are using .NET Core to write the data access API.

## Your Environment
* AWSSDK.Extensions.NETCore.Setup version used: "3.3.100.1"
* AWSSDK.CloudSearchDomain version used: "3.3.100.15"
* AWSSDK.S3 version used: "3.3.101.3"

## .NET Core Info
* `dotnet --info`:
```sh
.NET Core SDK (reflecting any global.json):
 Version:   2.2.202
 Commit:    8a7ff6789d
```

**Comment by danielloganking** [comment]
Here is a minimal reproduction:

file: `Aws.Sdk.TestBed.IntegrationTests.csproj`
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.CloudSearchDomain" Version="3.3.100.15" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.3.100.1" />
    <PackageReference Include="AWSSDK.S3" Version="3.3.101.3" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="2.2.0" />
    <PackageReference Include="xunit" Version="2.4.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.0" />
  </ItemGroup>

</Project>
```

file: `SmokeTests.cs`
```csharp
using System;
using System.Threading.Tasks;
using Amazon.CloudSearchDomain;
using Amazon.CloudSearchDomain.Model;
using Amazon.S3;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Xunit;

namespace Aws.Sdk.TestBed.IntegrationTests
{
    public class SmokeTests
    {
        // fill in s3region and cloudSearchDomainUrl that work with the credentials in your local environment
        private string s3region = "";
        private string cloudSearchDomainUrl = "";

        [Fact]
        public async Task S3_CanResolveAlone()
        {
            // arrange
            // NOTE: your environment must already contain working AWS credentials
            Environment.SetEnvironmentVariable("AWS__Region", s3region);

            var serviceProvider = new WebHostBuilder()
                .UseStartup<Startup>()
                .Build()
                .Services;

            var s3 = serviceProvider.GetRequiredService<IAmazonS3>();

            // act
            var response = await s3.ListBucketsAsync();

            // assert
            Assert.True(response.HttpStatusCode == System.Net.HttpStatusCode.OK);
        }

        [Fact]
        public async Task CloudSearchDomain_CanResolveAlone()
        {
            // arrange
            // NOTE: your environment must already contain working AWS credentials
            Environment.SetEnvironmentVariable("AWS__ServiceURL", cloudSearchDomainUrl);

            var serviceProvider = new WebHostBuilder()
                .UseStartup<Startup>()
                .Build()
                .Services;

            var cloudSearch = serviceProvider.GetRequiredService<IAmazonCloudSearchDomain>();

            // act
            var response = await cloudSearch.SearchAsync(new SearchRequest { Query = "*", Size = 1 });

            // assert
            Assert.True(response.HttpStatusCode == System.Net.HttpStatusCode.OK);
        }

        [Fact]
        public async Task CloudSearchDomainAndS3_CanResolveTogether() // FAILS
        {
            // arrange
            // NOTE: your environment must already contain working AWS credentials
            Environment.SetEnvironmentVariable("AWS__Region", s3region);
            Environment.SetEnvironmentVariable("AWS__ServiceURL", cloudSearchDomainUrl);

            var serviceProvider = new WebHostBuilder()
                .UseStartup<Startup>()
                .Build()
                .Services;

            var s3 = serviceProvider.GetRequiredService<IAmazonS3>();
            var cloudSearch = serviceProvider.GetRequiredService<IAmazonCloudSearchDomain>();

            // act
            var s3Response = await s3.ListBucketsAsync(); // exception is thrown here
            var cloudSearchResponse = await cloudSearch.SearchAsync(new SearchRequest { Query = "*", Size = 1 });

            // assert
            Assert.True(cloudSearchResponse.HttpStatusCode == System.Net.HttpStatusCode.OK);
            Assert.True(s3Response.HttpStatusCode == System.Net.HttpStatusCode.OK);
        }

        private class Startup
        {
            public Startup(IHostingEnvironment env)
            {
                var builder = new ConfigurationBuilder()
                    .SetBasePath(env.ContentRootPath)
                    .AddEnvironmentVariables();

                Configuration = builder.Build();
            }

            public IConfiguration Configuration { get; }

            public void ConfigureServices(IServiceCollection services)
            {
                var awsOptions = Configuration.GetAWSOptions("AWS");

                // these are mutually incompatible
                services.TryAddAWSService<IAmazonS3>(awsOptions);
                services.TryAddAWSService<IAmazonCloudSearchDomain>(awsOptions);
            }

            // this is included only so WebHostBuilder doesn't throw an exception
            public void Configure()
            {
            }
        }
    }       
}
```

**Comment by Kaelum** [comment]
I think this is related to an issue that I discovered when using .NET Core 3.0 Preview 5.  The references in AWSSDK.Extensions.NETCore.Setup are hard set to use:

* Microsoft.Extensions.Configuration.Abstractions 2.0.0
* Microsoft.Extensions.DependencyInjection.Abstractions 2.0.0
* Microsoft.Extensions.Logging.Abstractions 2.0.0
* Microsoft.Extensions.Primitives 2.0.0

and will not use the `Sdk="Microsoft.NET.Sdk"` or `Sdk="Microsoft.NET.Sdk.Web"` replacements.  So, I removed the reference for `AWSSDK.Extensions.NETCore.Setup` and, as expected, several code references were broken.  A couple hours later I added it back, and everything worked.  When I did a diff on my project file, I found that `<PackageReference Include="AWSSDK.S3" Version="3.3.102.12" />` had been added.  I'm chalking it up to a Visual Studio 2019 bug, which I have been running into quite a few lately.

Try to upgrade your `AWSSDK.S3` reference to version `3.3.102.12`, and see if that works.

**Comment by danielloganking** [comment]
@Kaelum After upgrading to the lastest stable versions of all AWSSDK packages this still does not work. Here is my updated csproj package references:

```xml
<ItemGroup>
  <PackageReference Include="AWSSDK.CloudSearchDomain" Version="3.3.100.34" />
  <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.3.100.1" />
  <PackageReference Include="AWSSDK.S3" Version="3.3.102.15" />
  <PackageReference Include="Microsoft.AspNetCore.App" />
  <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.1.1" />
  <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="2.2.0" />
  <PackageReference Include="xunit" Version="2.4.1" />
  <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1">
    <PrivateAssets>all</PrivateAssets>
    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
  </PackageReference>
</ItemGroup>

```
