### ISSUE TITLE
Dependency Injection of IAmazonS3 does not respect credentials

### ISSUE THREAD

**Issue by ChronosWS** [aws/aws-sdk-net#1308]
When using AutoFac DI in .NET Core, the AWSCredentials passed to the factory function are ignored, and default credentials are used.

Services registered as:
```
public static void ConfigureServices(IConfiguration Configuration, IServiceCollection services)
{
    ...
    services.AddDefaultAWSOptions(new AWSOptions());
    services.AddAWSService<IAmazonSecurityTokenService>();
    // Transient so each resolution gets a new client (as credentials may differ between uses)
    services.AddAWSService<IAmazonS3>(ServiceLifetime.Transient);
    ...
}
```

Usage:

```
public StorageService(
    IAmazonSecurityTokenService stsClient,
    Func<Amazon.Runtime.AWSCredentials, Amazon.RegionEndpoint, IAmazonS3> s3ClientFactory)
    {
        _stsClient = stsClient;
        _s3ClientFactory = s3ClientFactory;
    }

private async Task<IStorage> CreateStorageAsync(
    string roleArn, string sessionName, string bucketName, string prefix,
    bool useEncryption = false)
    {
        AssumeRoleResponse response = await _stsClient.AssumeRoleAsync(new AssumeRoleRequest()
        {
            RoleSessionName = sessionName,
            RoleArn = roleArn
        });

        var client = _s3ClientFactory(
            response.Credentials,
            Amazon.RegionEndpoint.GetBySystemName(ServiceSettings.AwsS3Region));
        ....
    }
```

## Expected Behavior
When the factory method is called, the credentials passed as the first argument are the ones used.

## Current Behavior
The credentials are ignored, and the default credential search mechanism is used (logging confirms this to be the case.)

## Possible Solution
As a workaround, I can instantiate the client directly, as follows:

```
var client = new AmazonS3Client(response.Credentials, Amazon.RegionEndpoint.GetBySystemName(ServiceSettings.AwsS3Region));
```
This correctly respects the credentials.

## Steps to Reproduce (for bugs)
See description above.

## Context
I moved our AWS service code from using "new XXXClient" to a DI system so we could do mocking/substitution for testing.  Having to new up an actual S3 client breaks this model.

## Your Environment
* ASP.NET Core (SDK version 2.1.401)
* Linux (Ubuntu) container (microsoft/dotnet:2.1.4-aspnetcore-runtime-stretch-slim)
* AWS Services:
```
<AWSSDKCoreVersion>3.3.25.3</AWSSDKCoreVersion>
<AWSSDKS3Version>3.3.24</AWSSDKS3Version>
<AWSSDKSecurityTokenVersion>3.3.4.15</AWSSDKSecurityTokenVersion>
```
* AutoFac:
```
<AutofacExtensionsDependencyInjectionVersion>4.3.0</AutofacExtensionsDependencyInjectionVersion>
<AutofacVersion>4.8.1</AutofacVersion>
```
## .NET Core Info
See above

## Log snippet demonstrating search behavior
```
[11:33:48 INF] Assuming role arn:aws:iam::XXXXXXXXXXXX:role/XXXX-s3-role with session PrivateStorage_56995051-2155-4e6a-bfd2-dc68863291f7_Session, with result OK and access key XXXX
[11:33:48 INF]  Assuming role arn:aws:iam::XXXXXXXXXXXX:role/XXXX-s3-role with session PrivateStorage_56995051-2155-4e6a-bfd2-dc68863291f7_Session, with result OK and access key XXXX
[11:33:53 INF] Found credentials using the AWS SDK's default credential search
[11:33:53 INF] AWSSDK Found credentials using the AWS SDK's default credential search

**Comment by queenB3a** [comment]
This is an issue I also have as I want to be able to assume role upon making s3 calls but without having to instantiate the s3client everytime.  I would prefer to use the aws extensions nuget package and use dependency injection for all my aws clients

**Comment by chrisbecke** [comment]
You are over thinking it. In your AWS options point "Profile" at an assume_role profile, and the SDK will internally handle assuming the role.
