### ISSUE TITLE
Upload/Download S3Link into streams/string

### ISSUE THREAD

**Issue by saguiitay** [aws/aws-sdk-net#131]
When working with S3Link, it sometimes makes sense to work with the data saved in S3 immediately.
Forcing a download to the file system, and then having to loading from there, makes no sense.

I would love to have the following methods:
public System.Threading.Tasks.Task DownloadToStreamAsync(Stream targetStream)
public System.Threading.Tasks.Task UploadFromStreamAsync(Stream sourceStream)

**Comment by normj** [comment]
This was added with the following commit

https://github.com/aws/aws-sdk-net/commit/ebc377a8a26509bc4430e862bb924f182148719d

and is available in version 3.1.3.12 of the AWSSDK.S3 nuget package.
