### ISSUE TITLE
Please allow AWS_ASYNC_API in unity

### ISSUE THREAD

**Issue by Thaina** [aws/aws-sdk-net#1312]
Unity 2017 and later already support dotnet 4.x so we could use Task API and that's much more convenient

Please release the AWS SDK with dotnet 4.x for unity

**Comment by klaytaybai** [comment]
Hi @Thaina, this is the direction we're moving for Unity:  https://aws.amazon.com/blogs/developer/aws-sdk-for-net-now-targets-net-standard-2-0/

**Comment by Thaina** [comment]
@klaytaybai It's good and all but it that already release in unity? Can I get it?

**Comment by Thaina** [comment]
@klaytaybai As of `3.3.545` the task based API still not exist

You actually could do it like firebase, build for both version, 3.5 and 4.5 and put it in the same zip so we could choose. Please did this in `3.3.546`+

**Comment by normj** [comment]
Have you taken a look at this blog post on to reference the .NET Standard 2.0 version of the SDK with Unity? https://aws.amazon.com/blogs/developer/referencing-the-aws-sdk-for-net-standard-2-0-from-unity-xamarin-or-uwp/

**Comment by Thaina** [comment]
@normj Have already read that and in consideration of using it. But I still request that you should just release it as zip like firebase like I said without waiting for anything

You actually could build for both version, 3.5 and 4.5 and put it in the same zip so we could choose which one for our project. Please just do this in `3.3.546`+

Or you think it would be any problem in unity? Then that would be the same problem if I did that manually. Why you require us to workaround hacking instead you just release it

**Comment by Thaina** [comment]
Still not do it?

This is also a fix for #1140 too. This is already 2019. Most people update their unity already. Only your service stuck in 2015 what are you doing man

**Comment by Thaina** [comment]
> Have you taken a look at this blog post on to reference the .NET Standard 2.0 version of the SDK with Unity? https://aws.amazon.com/blogs/developer/referencing-the-aws-sdk-for-net-standard-2-0-from-unity-xamarin-or-uwp/

What happen?
