### ISSUE TITLE
Add support for sourcing credential from external process

### ISSUE THREAD

**Issue by j2clerck** [aws/aws-sdk-net#1313]
When using AWS through an Identity Broker, it is useful to be able to delegate the credential generation process to a thirdy party.
This behavior is named sourcing credential from external process and is supported on python, java and go SDK.
Link to the feature : https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html

When expiration is returned by the external process, SDK will automatically renew the credentials.

## Expected Behavior

When specifying in the config file the following profile
```
[profile developer]
credential_process = /opt/bin/awscreds-custom --username helen
```

the SDK should execute the process and parse the json returned and set them as current credentials.

## Current Behavior
It doesn't work and return an error:
Set-AWSCredential : Credential profile [developer] is not valid.  Please ensure the profile contains a valid combination of properties.

## Possible Solution
Add a new Credential implementation that will execute the process

## Context
I have a custom solution that provides me with ephemeral token and I'd like to delegate the credential generation to the tool, rather than having to automate a caching/refresh mechanism

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by sattpat** [comment]
Credential Process is now supported on the .NET SDK 

https://github.com/aws/aws-sdk-net/commit/5bb8dcdc612963e4dd8f85a64915fd2d1f49a418
