### ISSUE TITLE
AWS Toolkit for VS2017 Templates in a half

### ISSUE THREAD

**Issue by proveroni** [aws/aws-sdk-net#1315]
I have the Visual Studio 2017 Community and i installed the toolkit without errors but only displaying two models of aws project type: 

1 - AWS CloudFormation Project
2 - AWS Lambda Function Project

I don't receive any errors during the installation.

I removed aws * .dll from my computer (C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\nfjnfgb4.iku).
I saw that the directory "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\nfjnfgb4.iku\ProjectTemplates\AWS\1033" just have two folders:
1 - "CloudFormationProjectTemplate"
2 - "LambdaFunctionProjectTemplate"

**Comment by klaytaybai** [comment]
Please reply to Norm on https://github.com/aws/aws-sdk-net/issues/1451 or at https://github.com/aws/aws-toolkit-visual-studio/issues if you would like to communicate more template needs.
