### ISSUE TITLE
Task Cancelled Exception while running .NetCore app in linux

### ISSUE THREAD

**Issue by gowrajan** [aws/aws-sdk-net#1316]
We have a DotNetCore Application which would spin up more than 16 threads, internally each thread access a different file present inside same S3 bucket. Please find the Test code snippet below.

class Program
{
  static void Main(string[] args)
  {
    var fileList = new List<string> { "List of Files more than 16"};
    Console.WriteLine("Application Started!");
    var taskList = new List<Task>();
    foreach(var file in fileList)
    {
	taskList.Add(Task.Factory.StartNew(() => Process(file)));
    }
    Task.WaitAll(taskList.ToArray());
    Console.WriteLine("Application Completed!");
  }

private static void Process(string filename)
{
  try
  {
     var request = new GetObjectRequest() { BucketName = "bucket", Key = filename };
     using (var s3Client = new AmazonS3Client(RegionEndpoint.USWest2))
     using (var response = s3Client.GetObjectAsync(request).Result)
     using (var responseStream = response.ResponseStream)
     using (var reader = new StreamReader(responseStream))
     {
     	Console.WriteLine(reader.ReadLine());
     }
  }
  catch (Exception ex)
  {
     Console.WriteLine(ex.Message);
   }
}

When publishing this snippet code with netcoreapp2.1 and running in Linux instance (Amazon Linux 2 AMI) with proper S3 Access policy set, we are getting task cancelled exception.

{
	"Message": {
		"ClassName": "System.OperationCanceledException",
		"Message": "The operation was canceled.",
		"Data": null,
		"InnerException": null,
		"HelpURL": null,
		"StackTraceString": "   at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)\n   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)\n   at System.Net.Http.HttpClient.GetStringAsyncCore(Task`1 getTask)\n   at Amazon.Runtime.Internal.Util.AsyncHelpers.<>c__DisplayClass1_1`1.<<RunSync>b__0>d.MoveNext()\n--- End of stack trace from previous location where exception was thrown ---\n   at Amazon.Runtime.Internal.Util.AsyncHelpers.ExclusiveSynchronizationContext.BeginMessageLoop()\n   at Amazon.Runtime.Internal.Util.AsyncHelpers.RunSync[T](Func`1 task)\n   at Amazon.Util.AWSSDKUtils.DownloadStringContent(Uri uri, TimeSpan timeout, IWebProxy proxy)\n   at Amazon.Util.EC2InstanceMetadata.GetItems(String relativeOrAbsolutePath, Int32 tries, Boolean slurp)\n   at Amazon.Util.EC2InstanceMetadata.get_IAMSecurityCredentials()\n   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.FetchCredentials()\n   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentials()\n   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentialsAsync()\n   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)\n   at Processor.Process(ConsumerSettings consumerSettings, ILoggingService logService)
		"RemoteStackTraceString": null,
		"RemoteStackIndex": 0,
		"ExceptionMethod": null,
		"HResult": -2146233029,
		"Source": "System.Net.Http",
		"WatsonBuckets": null
	}
}

Note : When this same published code was made to run in Windows instance, it is successfully fetching data.

## Steps to Reproduce (for bugs)
Create a DotNetCore console app
Paste above program class in Program.cs and build and publish it for Linux and Windows Instances and run.

## Your Environment
* Nuget  AWSSDK.Core version used: 3.3.100.5
* Nuget  AWSSDK.Core version used: 3.3.101.3
* Targeted .NET platform: netcoreapp2.1
* Amazon Linux 2 AMI

## .NET Core Info
* .NET Core version used for development: netcoreapp2.1
* .NET Core version installed in the environment where application runs: dotnet core runtime 2.2

**Comment by sag0r** [comment]
Eventually I reached this link after wasting up 12 long hours and BAM!
[](https://stackoverflow.com/a/56110945/11746243)

in short, 
change this
`using (var s3Client = new AmazonS3Client(RegionEndpoint.USWest2))`

to this
`using (var s3Client = new AmazonS3Client(accessKey, secretId, RegionEndpoint.USWest2))`

right now I don't have an explanation of why to do this or why this works. for sure I will mention this to my botmaster.

![err](https://user-images.githubusercontent.com/33243632/60749931-15853000-9fc3-11e9-8b1f-97a69f89d316.PNG)
