### ISSUE TITLE
Lex PostContentResponse.Slots returns string instead of Dictionary<string, string>

### ISSUE THREAD

**Issue by jhchuah-amazon** [aws/aws-sdk-net#1318]
## Expected Behavior
PostContentResponse.Slots should return a Dictionary<string, string> like PostTextResponse.Slots. The documentation for both say that they return a map.

There is a similar issue for other fields in PostContentResponse that return raw JSON:
* SlotsToElicit
* SessionAttributes
* ResponseCard

## Current Behavior
PostContentResponse.Slots returns a string containing the raw JSON of slot names to slot values.

## Possible Solution
PostContentResponseUnmarshaller should use a DictionaryUnmarshaller. This code is in the Generated folder.

## Context
Using Slots with audio sent to Lex requires parsing the JSON response. I have been able to call the DictionaryUnmarshaller myself, but this is in the Amazon.Runtime.Internal namespace and I do not want to call code there.

## Your Environment

* AWSSDK.Core version used: 3.3.529.0
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 4.5

**Comment by klaytaybai** [comment]
Hi @jhchuah-amazon, this response type is determined by the Lex team and changing it would be a breaking change for all users of this service.  If you would like more information about the design decision or if you would like to request an alternative output type, I suggest you post on this issue in the AWS Forums:  [PostContentRequest and PostContentResponse](https://forums.aws.amazon.com/thread.jspa?messageID=830460&#830460).  It looks like you might also be an Amazon employee, so you could consider reaching out to them directly too.

You may also want to consider switching to the PostText operation if it suits your use case.

**Comment by jhchuah-amazon** [comment]
The issue is not with the response type from the Lex server. The issue is entirely within the SDK. The PostTextResponseUnmarshaller and PostContentResponseUnmarshaller both receive the same response type, but PostContentResponseUnmarshaller unmarshalls as a string instead of a dictionary. I have been able to work around this using the following:

```
Stream stream = new MemoryStream(Encoding.UTF8.GetBytes(response.Slots));
var unmarshaller = new DictionaryUnmarshaller<string, string, StringUnmarshaller, StringUnmarshaller>(StringUnmarshaller.Instance, StringUnmarshaller.Instance);
Dictionary<string, string> slots = unmarshaller.Unmarshall(new JsonUnmarshallerContext(stream, false, null));
```

That code is based directly off the code from PostTextResponseUnmarshaller.

**Comment by jhchuah-amazon** [comment]
I dug deeper and discovered the cause of the issue. In

https://github.com/aws/aws-sdk-net/blob/master/generator/ServiceModels/runtime.lex/runtime.lex-2016-11-28.normal.json

Lines 317 and 324 should have the shape as StringMap, not String. This would make them match match lines 416 and 420 for PostTextResponse

**Comment by klaytaybai** [comment]
Yes, this is where it is specified, but the service team provides these definitions.  Changing it would be a breaking change, and we would need the Lex team to agree to a customization anyway.  Please reach out to them via some other channel if you would like to give them more feedback.
