### ISSUE TITLE
GetObjectAsync and GetObjectMetadataAsync hanging on first call

### ISSUE THREAD

**Issue by natsoragge** [aws/aws-sdk-net#1321]
My first call to any "GetObject..." method of s3 SDK never returns.

## Context
I use a file in an s3 bucket to store some data and download this file on the first time the user runs the app. I keep the data on the user's device and only download it again if the server's metadata indicates a new update. I'm using GetObjectAsync to download the data and GetObjectMetadataAsync to get the metadata.

## Expected Behavior
Call GetObjectAsync or GetObjectMetadataAsync and receive a response.

## Current Behavior
Every time I clear the app data and cache on Android or reinstall the app, it gets stuck on GetObjectAsync method. If I close the app and reopen it, the method will return properly. It's not a random bug, the method only gets stuck on the first time I call it. If I use HttpClient to download my data instead of the s3 SDK, everything works fine. 

But then I got the second problem. If I open the app and the data is already in the device, I call GetObjectMetadataAsync to check if there's the need to update it. And this method is also hanging on the first time I call it. 

Curiously, if I get stuck on GetObjectAsync, GetObjectMetadataAsync will work normally, even in its first call. It seems that the first time I use any of the methods, the SDK stores something in my device that makes everything works properly the next time I run the app.

GetObjectAsync code:
```
public static async Task GetS3ObjectAsync(string s3BucketName, string fileName, System.Action<AmazonServiceResult<GetObjectRequest, GetObjectResponse>> callback = null)
{
    AmazonServiceResult<GetObjectRequest, GetObjectResponse> result = new AmazonServiceResult<GetObjectRequest, GetObjectResponse>();
    result.Request = new GetObjectRequest
    {
        BucketName = s3BucketName,
        Key = fileName,
    };

    try
    {
        Console.WriteLine("GetObjectAsync start");
        result.Response = await S3Client.GetObjectAsync(result.Request); // HANGS HERE
    }
    catch (System.Exception exception)
    {
        Console.WriteLine("Exception " + exception.Message); // NEVER CALLED
        result.Exception = exception;
    }

    Console.WriteLine("GetObjectAsync finish"); // NEVER CALLED

    if (callback != null)
        callback(result);
}
```

GetObjectMetadataAsync code:

```
public static async Task GetS3ObjectMetadataAsync(string s3BucketName, string fileName, System.Action<AmazonServiceResult<GetObjectMetadataRequest, GetObjectMetadataResponse>> callback = null)
{
    AmazonServiceResult<GetObjectMetadataRequest, GetObjectMetadataResponse> result = new AmazonServiceResult<GetObjectMetadataRequest, GetObjectMetadataResponse>();
    result.Request = new GetObjectMetadataRequest
    {
        BucketName = s3BucketName,
        Key = fileName
    };

    try
    {
        Console.WriteLine("GetObjectMetadataAsync start");
        result.Response = await S3Client.GetObjectMetadataAsync(result.Request); // HANGS HERE
    }
    catch (System.Exception exception)
    {
        Console.WriteLine("Exception " + exception.Message); // NEVER CALLED
        result.Exception = exception;
    }

    Console.WriteLine("GetObjectMetadataAsync finish"); // NEVER CALLED

    if (callback != null)
        callback(result);
}
```

Other:
```
public static AWSCredentials Credentials
{
    get
    {
        if (_credentials == null)
            _credentials = new CognitoAWSCredentials(m_identityPoolId, CognitoPoolRegion);
        return _credentials;
    }
}

public static IAmazonS3 S3Client
{
    get
    {
        if (_s3Client == null)
            _s3Client = new AmazonS3Client(Credentials, new AmazonS3Config() { RegionEndpoint = S3Region });
        return _s3Client;
    }
}
```

## Your Environment
* AWSSDK.Core version used: tried on 3.3.29.12 and 3.3.102.6
* AWSSDK.S3 version used: tried on 3.3.27.1 and 3.3.102.15
* Operating System and version: Windows 10 Pro 64 bits (10.0, Comp. 17134)
* Devices tested: Samsung Galaxy S8 and Motorola Moto X Play
* Android Version: 9.0 (Pie) and 7.1.1 (Nougat)
* Visual Studio version: VS 2017 15.7.6
* Targeted .NET platform: Xamarin.Forms (Android)

I'm attaching the logs that I get when I succeed and when I fail to download. It's possible to see the responses I get in each call (search for AmazonCognitoIdentityClient)

[LOG_DOWNLOAD_FAIL.txt](https://github.com/aws/aws-sdk-net/files/3323360/LOG_FAIL.txt)
[LOG_DOWNLOAD_SUCCESS.txt](https://github.com/aws/aws-sdk-net/files/3323361/LOG_SUCCESS.txt)

**Comment by natsoragge** [comment]
Made a few more tests and if I call AWSCredentials.GetCredentials or AmazonCognitoIdentityClient.GetOpenIdTokenAsync before the s3 methods, I get the same error. Basically, the first request that I make to AWS will always hang, no matter which it is. And it always hangs at this same point:

> 06-25 02:13:29.459 17937-18244/com.companyname.TesteAmazonS3 I/AmazonCognitoIdentityClient: 2|2019-06-25T02:13:29.458Z|INFO|Request metrics: {"properties":{"AsyncCall":"True","ServiceName":"Amazon.CognitoIdentity","ServiceEndpoint":"https://cognito-identity.us-east-2.amazonaws.com/","MethodName":"GetIdRequest","RequestSize":"67","StatusCode":"OK","BytesProcessed":"63","AWSRequestID":"08558bee-9707-11e9-9fc9-3197da4ef9b7"},"timings":{"HttpRequestTime":1917.5968,"ResponseUnmarshallTime":25.3828,"ResponseProcessingTime":98.888600000000011,"ClientExecuteTime":2119.875},"counters":{}}
> 06-25 02:13:29.464 17937-18244/com.companyname.TesteAmazonS3 D/Mono: DllImport searching in: '__Internal' ('(null)').
>     Searching for 'java_interop_jnienv_call_boolean_method'.
>     Probing 'java_interop_jnienv_call_boolean_method'.
>     Found as 'java_interop_jnienv_call_boolean_method'.

**Comment by normj** [comment]
Could you try another test for me. Could you temporarily create an instance of BasicAWSCredentials with AWS access key and secret key and try and make a call to S3. I would like to see if there is something weird going on in the complicated Cognito credential negotiation. 

Also could you add calls to `.ConfigureAwait(false)` after the async methods made by the SDK. With a hang issue a common culprit is a dead lock on a calling thread.


Another thing to try is we are currently working on deprecating the older Portable Class Library (PCL) version of the SDK which you are probably picking up. I would be curious to know if you force it to use the .NET Standard version if it gives you a different result. Here is a blog post that talks about our temporary work around to force the .NET Standard version till we get the PCL version out of the NuGet package. https://aws.amazon.com/blogs/developer/referencing-the-aws-sdk-for-net-standard-2-0-from-unity-xamarin-or-uwp/

**Comment by natsoragge** [comment]
Everything works fine when I use BasicAWSCredentials instead of CognitoAWSCredentials.

I haven't tried the .NET Standard version yet, but I'll try it as soon as I have some time.

**Comment by natsoragge** [comment]
Just tried the .NET Standard solution and had the same result. ): The methods freeze at the same point.

**Comment by klaytaybai** [comment]
It looks like this is related: [GetIdAsync Hangs #1328](https://github.com/aws/aws-sdk-net/issues/1328)

**Comment by kerembaydogan** [comment]
@natsoragge Thanks for reporting this issue.

I have spent several hours because I did not think this is an SDK bug. 
In my case, the first code block hangs and second code block works as expected.

```
// hangs
var cognitoAWSCredentials = new CognitoAWSCredentials (identityPoolId, region);
var amazonS3Client = new AmazonS3Client (cognitoAWSCredentials, region);

// works as expected
var basicAWSCredentials = new BasicAWSCredentials (accessKey, secretKey);
var amazonS3Client = new AmazonS3Client (basicAWSCredentials, region);
```

**Comment by natsoragge** [comment]
For me, the solution was to remove the Cognito from the equation. Since my bucket is public, I don't need credentials to access it. So I'm justing creating my client like this:

```
public static IAmazonS3 S3Client
{
    get
    {
        if (_s3Client == null)
        _s3Client = new AmazonS3Client(null, new AmazonS3Config() { RegionEndpoint = S3Region, Timeout = TimeSpan.FromSeconds(MAX_TIMEOUT) });
        return _s3Client;
    }
}
```

Unfortunately, this won't help if you have a non-public bucket.

**Comment by assyadh** [comment]
Hi,

Version 3.3.103.28 of AWSSDK.Core is out and should fix the issue.
