### ISSUE TITLE
HTTP Status Code Not Returned on Error

### ISSUE THREAD

**Issue by slimandslam** [aws/aws-sdk-net#1323]
## Expected Behavior
On failure of an AWS SDK NET API call, the AmazonServiceException
should populate e.StatusCode with the numeric HTTP status code.

## Current Behavior
e.StatusCode contains "BadRequest" instead of "400:

## Steps to Reproduce (for bugs)

```
try
    {
       var response = ec2Client.StopInstances(new StopInstancesRequest
       {
         InstanceIds = new List<string> {
          "i-1234567890abcdef0"
       }
       });
       List<InstanceStateChange> stoppingInstances = response.StoppingInstances;
    }
        catch (AmazonServiceException e)
    {
        Console.WriteLine("Message = "+e.Message);
        Console.WriteLine("Error Code = "+e.ErrorCode);
        Console.WriteLine("Request ID = "+e.RequestId);
        Console.WriteLine("Status Code = "+e.StatusCode);
    }

```
## Context
I cannot get the HTTP status code in the error context

## .NET Core Info
AWSSDK.2.3.55.2			
Microsoft.Bcl.Build.1.0.1
Microsoft.Bcl.1.1.7		
Microsoft.Net.Http.2.1.10

**Comment by klaytaybai** [comment]
Hi @slimandslam, we're using this Enum [HttpStatusCode](https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?redirectedfrom=MSDN&view=netframework-4.8).  If you cast the status code (i.e. (int)e.StatusCode) you can get the number value.
