### ISSUE TITLE
GetSecretValue not working with IAM roles inside kubernetes. .net sdk cannot find IAM roles inside kubernetes.yaml file. Only able to find users.

### ISSUE THREAD

**Issue by beverly21** [aws/aws-sdk-net#1324]
We have IAM roles and users set up in AWS. We use roles across all our applications , which are all Java apps. They are also all run on kubernetes and docker.  We recently started a .net project and tried to use roles to grab our secrets but we get an error 403 (forbidden) error message. Exception type: HttpRequestException. This .net application is also running on Kubernetes. When we run it directly on an EC2 instance we are able to access the secrets.
We also tried to get the secrets with the role using the CLI and it worked. When we specify users within kubernetes.yaml it works as well. But when we specify roles we get the error message above. 

## Expected Behavior
Using .net SDK to get secrets from the AWS secrets manager should work  using IAM roles attached to the instance.

## Current Behavior
It is failing with a forbidden error message.  We have used known roles that are currently working very well with other Java applications and we are still getting the same message. 

## Steps to Reproduce (for bugs)
* Create a mini project and use the aws .net sdk to try to retrieve secrets from the aws secrets manager.
* Pass in the secret name and the region in to SDK
* Create a docker image for the application.
*  Create a kubernetes.yaml file and specify an IAM role that has access to the secret and is running on the same EC2 instance.
* Run the application to see if you can retrieve the secrets from secret manager successfully using your specified role.

## Your Environment
* AWSSDK.Core version 3.3.101.1 
* .NETCoreApp,Version=v2.1: 
* AWSSDK.Extensions.NETCore.Setup": "3.3.100.1
* Visual Studio version: 2019
* Targeted .NET platform: 4.7

## .NET Core Info
.NET Core version used for development: 2.1
.NET Core version installed in the environment where application runs: runs on docker image  mcr.microsoft.com/dotnet/core/aspnet:2.1
Output of dotnet --info:

![image](https://user-images.githubusercontent.com/5279901/60116176-caeaf480-9734-11e9-9242-353ef57cb5eb.png)

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
Are you using ECS/EKS?
