### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by phillip-haydon** [aws/aws-sdk-net#1326]
Can the readme, and package descriptions, please be updated to explain what these packages are? When do you need what package?!? If they are the same why are there 2 packages? 

```
AWSSDK.CloudSearch

    Amazon CloudSearch is a managed service in the AWS Cloud that makes it simple and cost-effective to set up, manage, and scale a search solution for your website or application.

AWSSDK.CloudSearchDomain

    Amazon CloudSearch is a managed service in the AWS Cloud that makes it simple and cost-effective to set up, manage, and scale a search solution for your website or application.
```

**Comment by klaytaybai** [comment]
@phillip-haydon, thanks for the feedback on this.  We'll get it updated.  AWSSDK.CloudSearch is the configuration API for setting up CloudSearch domains.  AWSSDK.CloudSearchDomain is the API for both document management (adding, deleting, replacing) within your domain and searching your domain.  You can see more details by looking at the code or referencing the service's documentation here:  https://docs.aws.amazon.com/cloudsearch/latest/developerguide/api-ref.html

**Comment by chris1248** [comment]
It looks like a "Copy and Paste" error.

**Comment by chris1248** [comment]
The problem with this issue is it doesn't state what file issue is in, or even for that matter where it's found.

**Comment by phillip-haydon** [comment]
@chris1248 im referring to the nuget package descriptions.

![A698EBEA-B0FA-4EC8-861E-8826852BFC3E](https://user-images.githubusercontent.com/895629/72944077-d8438c80-3db2-11ea-9d66-4c8358f5564f.png)

**Comment by ashishdhingra** [comment]
Fixed https://www.nuget.org/packages/AWSSDK.CloudSearchDomain/
