### ISSUE TITLE
Unable to differentiate ConditionalCheckFailedException cause

### ISSUE THREAD

**Issue by IIFE** [aws/aws-sdk-net#1332]
I am calling `Table.UpdateItemAsync` with following two conditions:
- The Id of the document being updated must exist in the database
- The version number of the document being updated must be the same as the one in the database (optimistic locking).

If the first check fails, I wish to return a 404 error to the user, if the second check fails I wish to return a 409 error to the user.

The problem is that the SDK throws the same `ConditionalCheckFailedException` for both checks if they fail. This makes it impossible to know which condition was failed.

## Expected Behavior
Have some sort of way to determine which condition failure caused the `ConditionalCheckFailedException`. For example having a property on the exception that indicate the field(s) where conditions failed on would be useful.

## Current Behavior
No information available on `ConditionalCheckFailedException` to indicate which field the condition failed on.

## Possible Solution
Have some sort of way to determine which condition failure caused the `ConditionalCheckFailedException`. For example having a property on the exception that indicate the field(s) where conditions failed on would be useful.

## Your Environment
* AWSSDK.Core version used: 2.1
* Operating System and version: Windows 10
* Visual Studio version: 2019

**Comment by klaytaybai** [comment]
Thanks for the feedback.  It looks like this should be an enhancement within the service first.  I'll let them know about your feedback.

**Comment by korrasami** [comment]
I still see this issue, is there any progress on it?
