### ISSUE TITLE
Get all tags from CloudWatch Rules when listing rules

### ISSUE THREAD

**Issue by carlosrfernandez** [aws/aws-sdk-net#1334]
## Expected Behavior
`IAmazonCloudWatchEvents.ListRulesAsync` should return tags associated with rules in the same request if possible.

If not possible then another approach would be the `IAmazonCloudWatchEvents.ListAllTagsForResource` taking a wildcard that would allow to fetch multiple resources's tags and the resource name associated with it. 

# Current Behavior
Currently the `IAmazonCloudWatchEvents.ListRulesAsync` method is not returning the tags for the result list of rules. 

To get the tags, we need to make another request (per rule) to get all the tags.
## Possible Solution
Have the ListRulesAsync method return the tags.

## Context
Our app creates rules using the SDK, and also assigns tags to them. Currently these are not many, but they can be dynamic. It would be cool to get all the tags when listing the Rules.

## Your Environment

* AWSSDK.Core version used: 3.3.103.7
* Service assembly and version used: AWSSDK.CloudWatchEvents 3.3.100.43
* Operating System and version: Any
* Visual Studio version:  2019
* Targeted .NET platform:  netcore2.1

**Comment by klaytaybai** [comment]
Hi @carlosrfernandez, thanks for the feedback.  I've let the CloudWatchEvents team know about your feedback.  If it's added into their service API, the .NET SDK will get it.  I'm going to close out this issue now as there is nothing left to do on our end.
