### ISSUE TITLE
Paginator Support

### ISSUE THREAD

**Issue by costleya** [aws/aws-sdk-net#1335]
Other AWS SDKs have paginators that simplify using operations that paginate their results. Currently, .NET developers using the SDK have to write a while loop and call a paginated operation multiple times with a token to get all the results from the operation. Paginators will allow developers to make 1 call, and have the work needed to get the all the results be done automatically by the SDK.

**Comment by hunanniu** [comment]
Discussed on Friday, this has been addressed
