### ISSUE TITLE
Verify SDK Xamarin Components function with .NET Standard 2.0

### ISSUE THREAD

**Issue by costleya** [aws/aws-sdk-net#1341]
Verify the components in sdk/xamarin-components work before and after the transition to only offering .NET Standard.

**Comment by costleya** [comment]
We may want to extract these components into a standalone repository.

**Comment by costleya** [comment]
After researching, xamarin "components" are deprecated, and developers should use NuGet packages instead.

**Comment by hunanniu** [comment]
Discussed on Friday, this has been addressed
