### ISSUE TITLE
Remove MobileAnalytics (Pinpoint preferred)

### ISSUE THREAD

**Issue by costleya** [aws/aws-sdk-net#1345]
Amazon Pinpoint has superseded mobile analytics, and requires no platform specific customizations. Therefore, MobileAnalytics code will be removed and customers will be encouraged to migrate to pinpoint APIs to use the .NET Standard 2.0 implementation of the AWS SDK for .NET.

**Comment by hunanniu** [comment]
Discussed on Friday, this has been addressed
