### ISSUE TITLE
Remove CognitoSyncManager (Amazon AppSync Preferred)

### ISSUE THREAD

**Issue by costleya** [aws/aws-sdk-net#1346]
Customers are encouraged to use Amazon AppSync over CognitoSyncManager. Amazon AppSync does not require platform-specific customizations (CognitoSyncManager does). Therefore, customers will be encouraged to migrate to Amazon AppSync as they transition to .NET Standard 2.0.

CogntioSyncManager will be removed from the SDK. We may create a new repository for it if demand is high enough (pending investigation).

**Comment by hunanniu** [comment]
Discussed on Friday, this has been addressed
