### ISSUE TITLE
DynamoDBV2 memory leak .NET Core 2.1

### ISSUE THREAD

**Issue by youngDevelopman** [aws/aws-sdk-net#1352]
We are facing a memory leak issue while getting response back from the server. Every request increases memory from 500 to 100 MB (tests were taken for 5.25 MB of data).   
## Expected Behavior
RAM should be released after response.

## Current Behavior
For example, we send a request that should return us 5.25 MB of data, but RAM increases about 500 MB when we get a response and remains the same, so that the next same request increases RAM up to 1GB, then with another same request RAM increases up to 1.5GB etc. This issue appears on both low-level and high-level implementation approaches.

1. Before request(83 MB of RAM)
![Before request](https://user-images.githubusercontent.com/31933374/61227530-25241780-a72d-11e9-861a-30ecebee5ea2.PNG)

2. After request (550 MB of RAM)
![After request](https://user-images.githubusercontent.com/31933374/61227538-29e8cb80-a72d-11e9-868c-38da07e95293.PNG)

3. Postman response
![PostmanReposne](https://user-images.githubusercontent.com/31933374/61227549-2ead7f80-a72d-11e9-9fb2-67fd209690d3.PNG)

## Possible Solution
There is no possible solution.

## Steps to Reproduce (for bugs)
Send multiple requests with large amount of response data.

## Context

Our application is hosted in ECS container with 2GB of RAM, so when a lot of requests being send to the server, at some point of time container will be stopped and restarted because of memory overflowing.

## Your Environment

* AWSSDK.Core version used: 3.3.103.11
* Service assembly and version used: 
* Operating System and version: Windows 10 Pro, version 1803, 
* Visual Studio version: VS 2017 Version 15.9.5
* Targeted .NET platform: 4.8.03761

## .NET Core Info

* .NET Core version used for development: 2.1
* .NET Core version installed in the environment where application runs: 2.1

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
What kind of request are you sending?  If you can provide a code sample, that may be helpful.

**Comment by youngDevelopman** [comment]
We are sending a query request. Here is our code snippet:
```
List<CarShop> response = null;
            try
            {
                response = context.QueryAsync<CarShop >(
                request.Environment,
                QueryOperator.Between,
                values.Cast<object>(),
                config).GetRemainingAsync().Result;
            }
            catch (Exception ex)
            {
                logger.LogError($"Error while trying to get a response from Dynamo Db\nMessage: {ex.Message}\n{ex.StackTrace}");
                throw;
            }
```

Context is a IDynamoDBContext instance that is injected to the class.
General amazon sdk related configuration in our startup class:
            
```
services.AddDefaultAWSOptions(this.Configuration.GetAWSOptions());
services.AddAWSService<IAmazonDynamoDB>();
services.AddScoped<IDynamoDBContext, DynamoDBContext>();
```


And last but not least the model of our table:
```
 [DynamoDBTable("cars-table")]
    public class CarShop : IFeatureModel
    {
        public CarShop ()
        {
            Id = Guid.NewGuid();
            CarOwner= new List<CarOwner>();
        }

        [DynamoDBRangeKey]
        public Guid Id { get; set; }

        [DynamoDBHashKey(AttributeName = "E")]
        public string Environment { get; set; }

        [DynamoDBLocalSecondaryIndexRangeKey("CollectTimeIndex")]
        [DynamoDBProperty(AttributeName = "CT", Converter = typeof(DateTimeConverter))]
        public DateTime CollectTime { get; set; }

        [DynamoDBProperty(AttributeName = "AN")]
        public string AccountName { get; set; }

        [DynamoDBProperty(AttributeName = "AT")]
        public AccountTypes AccountType { get; set; }

        [DynamoDBProperty(AttributeName = "ANum")]
        public string AccountNumber { get; set; }

        [DynamoDBProperty(AttributeName = "C")]
        public string Country { get; set; }

        [DynamoDBProperty(AttributeName = "SD")]
        public List<CarOwner> CarOwner { get; set; }
    }
```
```
public class CarOwner 
{
        [DynamoDBProperty(AttributeName = "S")]
        public string Site { get; set; }

        [DynamoDBProperty(AttributeName = "CM")]
        public CarModel CarModel{ get; set; }

        [DynamoDBProperty(AttributeName = "CN")]
        public string CarNumber { get; set; }

        [DynamoDBProperty(AttributeName = "C")]
        public int Count { get; set; }
}
```

```
public interface IFeatureModel
{
        DateTime CollectTime { get; set; }
}
```
*Some attributes and classes were renamed due to security purposes.

Few notes that need to be mentioned:
1. We have tried both scan and query requests to the table.
2. We have performed operations to multiple table just to test the difference. The problem with memory remains the same.
3. We have even created a default project and added just one simple request  to the table and the problem haven't gone
4. We have tried to register context as Transient, Scoped and Singleton. Nothing has changed

**Comment by klaytaybai** [comment]
We've had some other concerns about memory leaks in DynamoDB.  We're doing some investigation on it this week, but we can't make any promises on a resolution time at the moment.

I have a few other questions for you:

-  The GetRemainingAsync method will make many smaller calls to get the next set of data.  I'm assuming that one of these small calls is the 5.25 MB that you are seeing.  Do you know how much data you are expecting to be returned total from QueryAsync/GetRemainingAsync?

- What is the purpose of casting the values to object?

- Have you looked at other alternatives for doing the calls asynchronously?  As is, your code will block the calling thread until all results are ready.

**Comment by youngDevelopman** [comment]
So, we have tried a lot of approaches for making the request to the table  including the asynchronous one:
```
var response = await context.QueryAsync<TransmissionsReport>(
request.Environment,
QueryOperator.Between,
values.Cast<object>(),
config).GetRemainingAsync();
```
It doesn't help us. The problem remains the same.

The values object is DateTime list:
```
var values = new List<DateTime>()
{
    // items
}
```

But we've also tried to make an asynchronous request without values object, just specifying a hash key:
```
var response = await context.QueryAsync<TransmissionsReport>(
                 request.Environment).GetRemainingAsync();
```
Unfortunately, it hasn't affected anything.

The table's data has increased since issue was published so the response. But we can test the correctness of the response data by checking list's count of response object and compare it to the expected amount of items. In all of the cases GetRemainingAsync works properly.

**Comment by philn5d** [comment]
Hey guys,

When you call GetRemainingAsync, the results are being collected in the Search document model.
`        /// <summary>
        /// Whether to collect GetNextSet and GetRemaining results in Matches property.
        /// Default is true. If set to false, Matches will always be empty.
        /// </summary>
        public bool CollectResults { get; internal set; }`

Can that be set via a parameter of GetRemainingAsync or on the response object of QueryAsync?
