### ISSUE TITLE
Can't set Content-Disposition header on S3 object using AmazonS3Client.CopyObjectAsync

### ISSUE THREAD

**Issue by madmox** [aws/aws-sdk-net#1353]
## Expected Behavior
It should be possible to set the `Content-Disposition` header on a S3 file using the `AmazonS3Client.CopyObjectAsync` method without touching any other existing metadata.

## Current Behavior
Given an existing file `original` in an S3 bucket, and given that file already has a `Content-Type` metadata with the value `text/plain`. The following code samples produce very unexpected results:

### Sample 1
```csharp
var s3 = new AmazonS3Client();
var s3Request = new CopyObjectRequest()
{
    SourceBucket = "mybucket",
    SourceKey = "original",
    DestinationBucket = "mybucket",
    DestinationKey = "sample1",
    MetadataDirective = S3MetadataDirective.REPLACE
};
s3Request.Metadata.Add("Content-Disposition", "attachment; filename = \"foo.txt\"");
await s3.CopyObjectAsync(s3Request);
```
`sample1` file's metadata are set to the following values:
```
Content-Type: "application/x-amz-json-1.0"
x-amz-meta-content-disposition: "attachment; filename = \"foo.txt\""
```
`Content-Type` is changed (???) and all other metadatas are prefixed with `x-amz-meta-` if the prefix is not already present.

### Sample 2
```csharp
var s3 = new AmazonS3Client();
var s3Request = new CopyObjectRequest()
{
    SourceBucket = "mybucket",
    SourceKey = "original",
    DestinationBucket = "mybucket",
    DestinationKey = "test2",
    MetadataDirective = S3MetadataDirective.REPLACE // same result with S3MetadataDirective.COPY
};
s3Request.Headers.ContentDisposition = "attachment; filename = \"foo.txt\"";
await s3.CopyObjectAsync(s3Request);
```
Fails with the following exception:
> Amazon.S3.AmazonS3Exception: The request signature we calculated does not match the signature you provided. Check your key and signing method.

## Possible Solution
Make the samples work as expected...

## Context
Trying to update the `Content-Disposition` header of existing S3 objects.

## Your Environment
* AWSSDK.S3 version used: 3.3.103.4
* Runtime: AWS lambda with dotnetcore2.1 function runtime.

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by madmox** [comment]
The exception thrown when setting the `ContentDisposition` property on `Headers` could be related to [this (closed) issue](https://github.com/aws/aws-sdk-net/issues/46). I can see something related to the fact that `Content-Disposition` is supposed to sorted before `Content-Type` alphabetically - or really anything related to sorting headers before signing the request.

**Comment by madmox** [comment]
Found a better solution for our use case: don't set the `Content-Disposition` header at the metadata level in S3, but add it at runtime using `GetPreSignedURL`. E.g.:

```csharp
var getPreSignedUrlRequest = new GetPreSignedUrlRequest()
{
    BucketName = "mybucket",
    Key = "original",
    Expires = DateTime.UtcNow.AddDays(1),
    Verb = HttpVerb.GET,
    ResponseHeaderOverrides = new ResponseHeaderOverrides()
    {
        ContentDisposition = "foo.txt"
    }
};
string url = s3.GetPreSignedURL(getPreSignedUrlRequest);
```

This doesn't solve the problem with the use of `CopyObjectAsync` and the `Headers` property of `CopyObjectRequest`, but at least the file name is not duplicated in the S3 metadatas.

**Comment by ajjaxpunk** [comment]
Worked for me thanks!

`var getPreSignedUrlRequest = new GetPreSignedUrlRequest()`
`{`
`    BucketName = "mybucket",`
`    Key = "original",`
`    Expires = DateTime.UtcNow.AddDays(1),`
`    Verb = HttpVerb.GET,`
`    ResponseHeaderOverrides = new ResponseHeaderOverrides()`
`    {`
`        ContentDisposition = "attachement"`
`    }`
`};`
`string url = s3.GetPreSignedURL(getPreSignedUrlRequest);`

**Comment by ashishdhingra** [comment]
Hi @madmox, 

Please confirm if your workaround works and if we could close this issue.

Thanks,
Ashish

**Comment by madmox** [comment]
The workaround is very specific to my use case and doesn't really solve the issue presented here. It seems there are nasty bugs in the way `CopyObjectAsync` is handling metadata headers. The workaround just avoids using the method to add a very specific header, but it is not usable for other types of metadatas.

**Comment by ashishdhingra** [comment]
Reproducible using the following code (AWSSDK.S3 version 3.3.103.4):
```C#
using System;
using Amazon.S3;
using Amazon.S3.Model;
using System.Threading.Tasks;

namespace S3ContentDispositionConsole
{
    class Program
    {
        private static string bucketName = "testbucket-1353";

        static void Main(string[] args)
        {
            Console.WriteLine("Running Sample 1...");
            CopyObjectResponse sample1Response = RunSample1().GetAwaiter().GetResult();
            Console.WriteLine("Running Sample 2...");
            CopyObjectResponse sample2Response = RunSample2().GetAwaiter().GetResult();
        }

        public static async Task<CopyObjectResponse> RunSample1()
        {
            var s3 = new AmazonS3Client();
            var s3Request = new CopyObjectRequest()
            {
                SourceBucket = bucketName,
                SourceKey = "original",
                DestinationBucket = bucketName,
                DestinationKey = "sample1",
                MetadataDirective = S3MetadataDirective.REPLACE
            };
            s3Request.Metadata.Add("Content-Disposition", "attachment; filename = \"foo.txt\"");
            return await s3.CopyObjectAsync(s3Request);
        }

        public static async Task<CopyObjectResponse> RunSample2()
        {
            var s3 = new AmazonS3Client();
            var s3Request = new CopyObjectRequest()
            {
                SourceBucket = bucketName,
                SourceKey = "original",
                DestinationBucket = bucketName,
                DestinationKey = "test2",
                MetadataDirective = S3MetadataDirective.REPLACE // same result with S3MetadataDirective.COPY
            };
            s3Request.Headers.ContentDisposition = "attachment; filename = \"foo.txt\"";
            return await s3.CopyObjectAsync(s3Request);
        }
    }
}
```

**Comment by karlmikko** [comment]
found what worked for me was to use the setContentType amd setContentDisposition method not the usermeta methods and that worked as desired
