### ISSUE TITLE
AmazonCloudWatchLogsClient does not work with LocalStack

### ISSUE THREAD

**Issue by gsfataviva** [aws/aws-sdk-net#1354]
The AmazonCloudWatchLogsClient throws an AmazonUnmarshallingException when the DescribeLogGroupsAsync method is called when a log group has been created in LocalStack.

## Expected Behavior
I expected the DescribeLogGroupsAsync method to return the newly created log group.

## Current Behavior
An exception is thrown:-

System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at CloudWatchTest1.Program.Main(String[] args) in C:\Users\xxxxxxxx\source\repos\CloudWatchTest1\Program.cs:line 33

Inner Exception 1:
AmazonUnmarshallingException: Error unmarshalling response back from AWS.

Inner Exception 2:
FormatException: Input string was not in a correct format.

## Steps to Reproduce (for bugs)
Ensure that the LocalStack's docker-compose.yml file's SERVICES includes "cloudwatch". Start LocalStack.

Create a .NET Core Console application. Install the AWSSDK.CloudWatchLogs NuGet package. Replace the Main method with this:-

        public static void Main(string[] args)
        {
            AmazonCloudWatchLogsConfig awsConfig = new AmazonCloudWatchLogsConfig();

            awsConfig.UseHttp = true;

            awsConfig.RegionEndpoint = Amazon.RegionEndpoint.GetBySystemName("eu-west-1");

            // set the LocalStack URL for CloudWatch logs
            awsConfig.ServiceURL = "http://localhost:4586";

            IAmazonCloudWatchLogs _client = new AmazonCloudWatchLogsClient("aws", "aws", awsConfig); ;

            CreateLogGroupRequest createLogGroupRequest = new CreateLogGroupRequest()
            {
                LogGroupName = "Temp1"
            };

            _client.CreateLogGroupAsync(createLogGroupRequest).Wait();

            // exception is thrown here
            var logGroupResponse = _client.DescribeLogGroupsAsync(new DescribeLogGroupsRequest
            {
                LogGroupNamePrefix = "T"
            }).Result;
        }

## Context
I want to use the AWS SDK with LocalStack to run CloudWatch logging code locally on my development machine before deploying to the real AWS.

## Your Environment
AWSSDK.CloudWatchLogs 3.3.100.48
Windows 10
Visual Studio 2017

## .NET Core Info
.NET Core 2.2

**Comment by matteo-prosperi** [comment]
Hello,
based on the exceptions you describe, it looks like the service response is not in the format expected by the AWS SDK for .NET.
If you can log the service response (I usually do it using Fiddler), I could have a look at it.
Are you able to reproduce this issue with the real Amazon CloudWatch service or does it affect LocalStack only? If it only affects LocalStack, you may want to direct this issue to [that project](https://github.com/localstack/localstack/issues).

**Comment by klaytaybai** [comment]
I think we can handle your other issue, https://github.com/aws/aws-logging-dotnet/issues/93, but please provide us with that service response that Matteo requested for this issue.

**Comment by gsfataviva** [comment]
Hi @matteo-prosperi,
yes, this works fine in the real AWS and only fails in LocalStack. The response from LocalStack when calling DescribeLogGroupsAsync is:-

{"nextToken": null, "logGroups": [{"storedBytes": 0, "metricFilterCount": 0, "creationTime": 1563520032256.783, "logGroupName": "Temp1", "retentionInDays": 30, "arn": "arn:aws:logs:us-east-1:1:log-group:Temp1"}]}

**Comment by gsfataviva** [comment]
Hi @klaytaybai ,

Unfortunately the other issue (with AWSLoggerConfig) isn't quite resolved yet as I mentioned in https://github.com/aws/aws-logging-dotnet/pull/94 because the assignment of the RegionEndPoint undoes the previous assignment of the ServiceURL. The assignment to the ServiceURL must occur AFTER the assignment to RegionEndPoint. I made this change in my local code and tested it and it then works fine.

**Comment by matteo-prosperi** [comment]
The response text you sent doesn't match the specification. You can see samples in the API docs [here](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_DescribeLogGroups.html). 
`creationTime` is expected to be a `long`, in your sample it is a floating point number.

You can try to report this to LocalStack and have them fix their protocol implementation.

**Comment by gsfataviva** [comment]
Thanks @matteo-prosperi I will report this to LocalStack.

**Comment by gsfataviva** [comment]
For anyone else who reads this thread you can find the issue I raised for LocalStack at https://github.com/localstack/localstack/issues/1434.
