### ISSUE TITLE
Feature Request: Add idempotency token to IAmazonEC2.CreateSnapshot

### ISSUE THREAD

**Issue by mwhouser** [aws/aws-sdk-net#1355]
## Expected Behavior

One call to `IAmazonEC2.CreateSnapshot()` should result in at-most one EBS snapshot. No snapshots may be created in case of failure, but never two or more.

## Current Behavior

If a network error occurs during communication, the AWS SDK will retry the `ec2:CreateSnapshot` API action. This can result in one of the following situations:

* Two EBS snapshots are created, but only the second is returned in the response, or
* The API responds with `SnapshotCreationPerVolumeRateExceeded` error code:

> The maximum per volume CreateSnapshot request rate has been exceeded. Use an increasing or variable sleep interval between requests.

For example, if the request makes it to AWS, but the response does not make it back to the client, then (a) the EBS snapshot will be created, and (b) the client won't know it, and will retry.

## Possible Solution

Some AWS SDK methods include an idempotency token used to avoid repeated executions in a network failure situation. `IAmazonEC2.CreateSnapshot()` does not include such a token. Please add one.

## Steps to Reproduce (for bugs)

Call `IAmazonEC2.CreateSnapshot()` at the wrong time (network-wise) and it may happen. 

## Your Environment

* AWSSDK.Core version used: 3.3.101.17
* Service assembly and version used: AWSSDK.EC2 version 3.3.111
* Operating System and version: Windows 2016 server
* Visual Studio version:  Visual Studio 2017
* Targeted .NET platform: 4.7.2

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
Would you mind sharing an example of where one of the SDKs already has this implemented for this operation if you know of one?  I tried looking briefly, but I wasn't coming up with any results.

**Comment by mwhouser** [comment]
@klaytaybai `IAmazonEC2.CopyImage()` has `ClientToken`:

https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CopyImage.html

**Comment by klaytaybai** [comment]
Thanks.  I thought you meant another language SDK had already done it for this method.  This change is going to require a service change, which could take some time.  I'll send your feedback over to them, but I'm going to close this issue out for now in the SDK repo. We should get the update in the SDK if they push it in the service.
