### ISSUE TITLE
Missing RegionEndpoint for ap-east-1

### ISSUE THREAD

**Issue by brown99** [aws/aws-sdk-net#1356]
It appears that the RegionEndpoint is missing entry for APEast1.
[https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/RegionEndpoint/RegionEndpoint.c](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/RegionEndpoint/RegionEndpoint.cs) 

## Expected Behavior

var region = RegionEndpoint.APEast1;

## Actual Behavior

In Visual Studio 2019: 

var region = RegionEndpoint. **multiple fists to the keyboard ensuring that the period key is part of the onslaught; however APEast1  does not magically appear**

**Comment by normj** [comment]
Taking a look

**Comment by matteo-prosperi** [comment]
Hello,
we added the `APEast1` region in AWSSDK.Core 3.3.103.12 (https://github.com/aws/aws-sdk-net/commit/007330c80ba52b674d40a4e0dee9956da95bdd61)
