### ISSUE TITLE
STS Assume Role Lifespan - Looking for Guidance

### ISSUE THREAD

**Issue by Downright-Development** [aws/aws-sdk-net#1358]
I have a the application as User 1 (My dev user), then instantiates another class. In the instantiated class, I assume a role to a client's account so that I may post data to their Kinesis Stream. When that class finishes it's execution, and returns back to the calling class, does the role assumption automatically return to User 1? (As if the temporary role assume is scoped to the life of the instantiated class?)

This pipeline will be executed very often, having to assume roles for each pipe in the pipeline frequently, but returning to the original role (User 1) for the rest of the application.  Is there a better pattern (caching?) to manage switching roles, without having to submit a new request frequently? I know each temp credentials have a TTL, I thought about creating a cache profile provider and catching the access denied exception (refreshing the cache at that point & trying the user's request again). OR, is submitting a  new request for temporary credentials the right thing to do?

Thanks for the time and efforts, I appreciate any feedback :)

**Comment by normj** [comment]
I'll need more details to fully understand how you are creating AWS service clients and AWS credentials but at a high level the credentials are kept in the scope of the `AWSCredentials` credentials object. You are probably using the sub class `AssumeRoleAWSCredentials` either directly or indirectly depending on how you are creating credentials. My suggestion would be to keep a cache of profile names to `AWSCredentials` and the underlying `AssumeRoleAWSCredentials` object will take care of refreshing the credentials when they expire.

**Comment by Downright-Development** [comment]
@normj The AssumeRoleAWSCredentials class you mentioned and the cache concept is exactly what I was looking for. Thanks for that :)
