### ISSUE TITLE
Unable to add tags, metadata, parameters or headers with GetPreSignedURL (S3, C#)

### ISSUE THREAD

**Issue by elsamilagros** [aws/aws-sdk-net#1359]
When generating a pre-signed URL for a client to upload an object to S3, I'm unable to add tags, metadata, headers or parameters without resulting in a SignatureDoesNotMatch code when using the generated URL. Extra information needs to be added to each object when it's uploaded. There's a PUT event in the folder where the file is uploaded that process the file further. This information is needed to know how to process it. At this point, the work-around I'm thinking in doing is to save a JSON file with this extra information in another folder. It would be ideal to attach it to the object in S3 at the point it's created by using tags, metadata, parameters or headers. 

## Expected Behavior
This is the basic request construction:

            string key = "Uploads/" + fileName;
            GetPreSignedUrlRequest request = new GetPreSignedUrlRequest
            {
                BucketName = _bucketName,
                Key = key,
                Verb = HttpVerb.PUT,
                Expires = DateTime.Now.AddMinutes(60),
                ContentType = contentType
            };

I've tried to add tags:

string tags = $"Description={description}&EmailSubject={requestSubject}";
request.Headers["x-amz-tagging"] = tags;

I've tried to add parameters:

request.Parameters.Add("Description", description);
request.Parameters.Add("EmailSubject", requestSubject);

I've tried to add metadata:

request.Metadata["Description"] = description;
request.Metadata["EmailSubject"] = requestSubject;

All of these individual efforts returns a URL. When each one is used from the client (browser or Postman), I receive a 403 Forbidden error:

    <Code>SignatureDoesNotMatch</Code>
    <Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>

Our company's AWS devops team indicates that the policy is correct from the lambda that creates the pre-signed URL and the bucket (bucket policy "Allow" to the lambda with actions s3:GetObject, s3:GetObjectTagging, s3:DeleteObject, s3:DeleteObjectTagging, s3:PutObject, s3:PuObjectTagging).

## Current Behavior
The upload is successful if I remove anything beyond generating the pre-signed URL (i.e. I don't add tags, parameters, headers or metadata). 

I receive a SignatureDoesNotMatch  if I try to add any of these and use the pre-signed URL from a client (browser or Postman). 

I would like to be able to add extra information to the object when generating the pre-signed URL or even from the client, if this is possible. It has to occur when creating the object, since there's an immediate event (PUT) when it reaches the bucket. 

## Your Environment
* AWSSDK.Lambda.AspNetCoreServer version used: 3.1.0
* AWSSDK.S3 version used: 3.3.104.3
* Visual Studio version: 2019
* Targeted .NET platform: Core 2.1

## .NET Core Info
* .NET Core version used for development: 2.1
* .NET Core version installed in the environment where application runs: 2.1
* Output of `dotnet --info`: 
.NET Core SDK (reflecting any global.json):
 Version:   2.1.700
 Commit:    c2ef055a0f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.700\

Host (useful for support):
  Version: 2.1.11
  Commit:  d6a5616240

.NET Core SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by klaytaybai** [comment]
Hi @elsamilagros, I'm not able to reproduce your problem.  I suspect that the error you are seeing is due to the request you are sending.  The request from your client (including browser/Postman) needs to match the details of the presigned request.  My guess is that your request is missing the necessary headers, which you will need to enter manually into Postman.

**Comment by elsamilagros** [comment]
Thanks for your time, but the problem that I'm describing is that I'm not able to add tags, parameters, headers or metadata with the AWS S3 SDK for .NET. Your answer does not answer the problem I posted. Please do not close.

**Comment by klaytaybai** [comment]
> Thanks for your time, but the problem that I'm describing is that I'm not able to add tags, parameters, headers or metadata with the AWS S3 SDK for .NET. Your answer does not answer the problem I posted. Please do not close.

Thanks for the response @elsamilagros.  I'm sorry I didn't seem to meet your needs.  Could you please try rephrasing what you are hoping to do?  As I'm currently understanding your issue, I think my answer is suitable.  Maybe I need clarification around the post processing step you mention and your level of control over it.

The below code will add tags and metadata to the object and presigned url.  

```
         AmazonS3Client client = new AmazonS3Client();
            GetPreSignedUrlRequest request = new GetPreSignedUrlRequest
            {
                BucketName = _bucketName,
                Key = _key,
                Verb = HttpVerb.PUT,
                Expires = DateTime.Now.AddMinutes(60),
                ContentType  = "text/plain"
            };
            request.Metadata.Add("Description", "This is my description");
            string tags = $"EmailSubject=This is my subject";
            request.Headers["x-amz-tagging"] = tags;
            string url = client.GetPreSignedURL(request);
            Console.WriteLine(url);

            PutObjectRequest putObjectRequest = new PutObjectRequest()
            {
                BucketName = _bucketName,
                Key = _key,
                ContentBody = "This is my body",
                TagSet = new List<Tag>()
                {
                    new Tag()
                    {
                        Key = "EmailSubject",
                        Value = "This is my subject"
                    }
                }
            };
            putObjectRequest.Metadata.Add("Description", "This is my description");
```

**Comment by elsamilagros** [comment]
You didn't use the variable that holds pre-signed URL generated (url) in . My request is clear. Please allow others to answer my request. Thanks!

**Comment by klaytaybai** [comment]
Right you were.  Sorry for the mistake.  Can you try the below code?  The same concept I was discussing earlier still applies.  You need to set the headers of the added data onto your upload request.

```
         AmazonS3Client client = new AmazonS3Client();
            GetPreSignedUrlRequest request = new GetPreSignedUrlRequest
            {
                BucketName = _bucketName,
                Key = _key,
                Verb = HttpVerb.PUT,
                Expires = DateTime.Now.AddMinutes(60),
                ContentType  = "text/plain"
            };
            request.Metadata.Add("Description", "This is my description");
            string tags = $"EmailSubject=This is my subject";
            request.Headers["x-amz-tagging"] = tags;
            string url = client.GetPreSignedURL(request);
            Console.WriteLine(url);

            UploadObject(url, request.Headers, request.Metadata);
        }

        private static void UploadObject(string url, HeadersCollection headers, MetadataCollection metadata)
        {
            byte[] data = Encoding.UTF8.GetBytes("This is my sample body");

            // Configure request
            HttpWebRequest httpRequest = WebRequest.Create(url) as HttpWebRequest;
            foreach (var header in headers.Keys)
            {
                httpRequest.Headers.Add(header, headers[header]);
            }
            foreach (var item in metadata.Keys)
            {
                httpRequest.Headers.Add(item, metadata[item]);
            }
            httpRequest.Method = "PUT";
            // Write data to stream
            Stream requestStream = httpRequest.GetRequestStream();
            requestStream.Write(data, 0, data.Length);
            requestStream.Close();

            // Issue request
            HttpWebResponse response = httpRequest.GetResponse() as HttpWebResponse;
        }
```

**Comment by moedeveloper** [comment]
@elsamilagros  how did you solve your issue ? because I have the same issue

**Comment by elsamilagros** [comment]
@moedeveloper I worked around this problem by creating a json file with the metadata I need, storing it in S3 and deleting it when I was done. Very clunky, I know. I wish other people would have chimed in to help out.

**Comment by shen-he** [comment]
Really shocked by the quality of Amazon staff's reply. The code he/she provided does not work. The HTTP response is: Metadata cannot be specified in this context.

Do they even care?!?!?!?!

**Comment by surajg101** [comment]
@elsamilagros  can you please elaborate , on how you achieved it , well even i am getting the same exception.

**Comment by elsamilagros** [comment]
> @elsamilagros can you please elaborate , on how you achieved it , well even i am getting the same exception.

@surajg101 - Thanks for confirming that this is a real issue and that it shouldn’t have been closed. The work-around I chose is described above your comment. https://github.com/aws/aws-sdk-net/issues/1359#issuecomment-545405490

**Comment by fadilafidina** [comment]
Hi @elsamilagros, I am also trying to do something very, very similar - generating a presigned url to upload, setting metadata on the PUT request when uploading the document to S3 with the original file name, and needing that metadata right after the item has been uploaded since it dispatches an event when the file is in the bucket.

I tried adding a line during the presigned url generation - `request.Metadata.Add("filename", "sample value");`  - but doing this meant that the client has to provide the same value of `sample value` in order to get a successful response. I wish there was a way to set custom metadata value from the client.

The workaround I am thinking of doing is providing the original file name as a parameter when requesting the initial presigned url itself from our server. It will set it as part of the presigning, then the client will be able to have the same filename value as what is set in the server. But that's so clunky...

Just saying that I feel you on this problem, and I wish there are easier ways out of this...

**Comment by atrauzzi** [comment]
Running up against this as well.  I really wish there was a way to include the metadata as part of the presigned URI itself, or to have a way to pre-populate the metadata for a key prior to the bytes being uploaded by the client.  Either solution would suffice.

Right now though, requiring the client to be aware of AWS-specific headers is not practical.

**Comment by Phil1972** [comment]
Same here, customer is given the right to write an object, he should have control over the Metadata as well... this design prevents us from using S3 (at least the AWS implementation) since the customers will not tell us in advance what they put in the metadata (it is private).

**Comment by karl-bauer-renaissance** [comment]
@atrauzzi @Phil1972 You are giving your customer an API where they send you information about the file they are uploading so part of that API can be metadata or tags that need to be attached. Then you use that information to create the presigned url and then your return object has a collection of headers that they must add to the request. You build that list of headers for them. That way, they don't need to be aware of any AWS specific anything. They only need to be aware of the fact that you will give them a collection of headers that they must add to the request along with the url of the request.
