### ISSUE TITLE
AdminCreateUserAsync does nothing when call from Console Application

### ISSUE THREAD

**Issue by hanslai** [aws/aws-sdk-net#1361]
The following function works fine and a user will get created in User Pool when I call it from asp.net Web API, but it does nothing when I can it from a Windows Console Application.  

line 89, will not even get hit, and there is no exception either.  the function will just quit and return back to main() without any error after calling AdminCreateUserAsync() .

![image](https://user-images.githubusercontent.com/20576491/61954980-acef0900-afec-11e9-9c0f-104d49f9ca32.png)

My question is:  "Is it possible to called AdminCreateUserAsync() from Windows Console or WinForm Application"

Or do I have to use the AWS CLI for Console application?

## Expected Behavior
A user named "TestUserJohn" should get created in Cognito User Pool.  

## Current Behavior
No User is created, but function return without any error.

## Context
I would like to write a Windows Application (Winform or WPF) client to management Cognito user pool's users.

## Your Environment

* AWSSDK.Core version used:  AWSSDK.CognitoIdentity 3.3.100.52
* Service assembly and version used: 
* Operating System and version:  Windows 10 Pro, version: 1903, 
* Visual Studio version: Visual Studio 16.2
* Targeted .NET platform: 

## .NET Core Info
```
OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview7-012821\

Host (useful for support):
  Version: 3.0.0-preview7-27912-14
  Commit:  4da6ee6450

.NET Core SDKs installed:
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.301 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012821 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19365.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27912-14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by klaytaybai** [comment]
Hi @hanslai, I wasn't able to reproduce this problem using a .NET Core Console Application.  If you are able to, please share some sample code that includes your main method (preferably in a non-image format).   I suspect that your issue might be caused by a parent thread finishing before the CreateUser task completes.

**Comment by hanslai** [comment]
Hi @klaytaybai you are correct, It was because my Main() did not wait for CreateUser to complete.  I cannot believe I miss that, thank you for point that out.
