### ISSUE TITLE
Kinesis.PutRecord(s)Async when Unity OnApplicationQuit

### ISSUE THREAD

**Issue by truegod1205** [aws/aws-sdk-net#1365]
## Expected Behavior

Hello, I'm using Kinesis service: PutRecord(s)Async, 
When users close our game, I tried flush all events to Kinesis.
Therefore, I call PutRecords in Unity OnApplicationQuit.
But it didn't work. 
I really want to know that I can't putrecord after close games originally,
or I have code issues?
Thanks.
Here is my code

```c#
private void OnApplicationQuit()  {
        AmazonServiceCallback<PutRecordsRequest, PutRecordsResponse> callback =
                new AmazonServiceCallback<PutRecordsRequest, PutRecordsResponse>(MultiKinesisCallbackFunc);
        if (_kinesisClient != null)  {
            _kinesisClient.PutRecordsAsync(multuRequests, callback);
        }
    }
```

## Your Environment

* AWSSDK.Core version used: aws-sdk-unity_3.3.528.0
* Service assembly and version used: 
* Operating System and version: Win 10
* Visual Studio version: 2015
* Targeted .NET platform: 3.5

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by maxha651** [comment]
I realize that this is an old issue, but since it still is a problem here is my workaround:

Block the application from quitting and start flushing all events using Application.wantsToQuit.
Then call Application.Quit after all events are flushed.

**Comment by NGL321** [comment]
Hey @truegod1205 and @maxha651,

Are either of you still experiencing this issue (workaround aside)?

Please note that [as of SDK v3.5](https://aws.amazon.com/blogs/developer/aws-sdk-for-net-v3-5-now-generally-available/) we no longer separate Unity support from regular .NET support, if you are having trouble with this transition, please make sure you are [targeting ^.NET 4.0 or ^.NET Standard 2.0](https://docs.unity3d.com/2020.1/Documentation/Manual/dotnetProfileSupport.html) using Unity 2018.0 or later. This means that you can have full access to AWS services when using the .NET SDK with Unity, but if you would still like to use the legacy SDK for Unity, you can reference it from our [archive repo](https://github.com/aws/aws-sdk-unity-net).

Let me know if you still see this behavior in the latest build and I can take a look!

😸 😷
