### ISSUE TITLE
AWS Unity sample package occurs errors. (unity 2018.4, 2019 ~ )

### ISSUE THREAD

**Issue by handapwb** [aws/aws-sdk-net#1371]
## Expected Behavior
We updated Unity project to 2019 from 2018. and we build apk supporting arm64.
but there are two error.
We downloaded AWS Unity Pacakge from https://docs.aws.amazon.com/mobile/sdkforunity/developerguide/setup-unity.html

## Current Behavior
1. Anroidmanifest.xml  Error.
 Androidmanifest.xml in AWS Unity Package use UnityPlayerNativeActivity. but UnityPlayerNativeActivity was deprecated from Unity version 2018.4. So It makes errors.
If Androidmanifest.xml use UnityPlayerNativeActivity, Application get crash at starting.

2. AWS sdk not working with arm64.
 Google play need to arm64 apk. but if i build apk with arm64 and IL2CPP, AWS SDK not working. 

Could you check this?

**Comment by badscotsman** [comment]
I'm also waiting to see a response on this issue. Our project is also not working on Android arm64 device. Unity 2018.4.5f1 LTS and AWS SDK version 'aws-sdk-unity_3.3.567.0'. No errors during the build and no adb logcat log errors showing. The AWS return method delegates are never called (DynamoDB and Lambda).

> 2. AWS sdk not working with arm64.
>    Google play need to arm64 apk. but if i build apk with arm64 and IL2CPP, AWS SDK not working.
> 
> Could you check this?

**Comment by Ethan-VisualVocal** [comment]
Google Play store is rejecting Unity 2018 (and 2017) builds because the unitypackages provided for download are missing an `arm64-v8a` build of `libsqlite3.so` --  they only include a `armeabi-v7a` build.

**Comment by badscotsman** [comment]
Following this post https://github.com/mapbox/mapbox-unity-sdk/issues/1331 for Android arm64 libsqlite3.so installed gives the same result with AWS SDK (not sure if it fixed Mapbox though).

**Comment by Ethan-VisualVocal** [comment]
@badscotsman did you make sure to the target CPU to ARM64 in Unity? 
e.g. 
![image](https://user-images.githubusercontent.com/18012510/63286821-c2fb8c80-c26d-11e9-81ff-6b8d6ae86a14.png) 

Also, you can pop open your built APK in Android Studio to see what it contains (and is maybe missing) 

e.g. this example is missing a LOT of 64 bit binaries, not just libsqlite3.so
![image](https://user-images.githubusercontent.com/18012510/63287181-92682280-c26e-11e9-9a21-000fcecace2f.png)

**Comment by matteo-prosperi** [comment]
Android arm64 applications are not supported by the AWS Mobile SDK for Unity.
We recommend to use the AWS SDK for .NET Standard 2.0 instead. You can find some instructions on how to reference it from Unity in [this blog post](https://aws.amazon.com/blogs/developer/referencing-the-aws-sdk-for-net-standard-2-0-from-unity-xamarin-or-uwp/).
Compared to the Mobile SDK, the AWS SDK for .NET Standard 2.0 has support for all AWS services and it is updated daily.
Please consider that the AWS SDK for .NET is not API-compatible with the AWS Mobile SDK for Unity, so you will need to change some of your code to reference the new APIs.
In case some mobile-specific or Unity-specific feature are missing from the AWS SDK for .NET Standard 2.0, you can open an issue here (https://github.com/aws/aws-sdk-net/issues) and we will consider it for future development.

**Comment by matteo-prosperi** [comment]
Hello,
in case you decide to use the .NET Standard 2.0 version of the AWS SDK for .NET we have made available a [download in .zip format](https://sdk-for-net.amazonwebservices.com/latest/v3/aws-sdk-netstandard2.0.zip) that should be more convenient for Unity users (we also have version specific downloads using a URI like [this one](https://sdk-for-net.amazonwebservices.com/releases/aws-sdk-netstandard2.0-3.3.590.0.zip)).
We have also continued our testing and, whenever using IL2CPP, we recommend to add a file named `link.xml` in your project assets and configure it so that IL2CPP doesn't strip any of the AWSSDK assemblies.
It should look like this:
```
<linker>
       <assembly fullname="AWSSDK.Core" preserve="all"/>
       <assembly fullname="AWSSDK.DynamoDBv2" preserve="all"/>
       <assembly fullname="AWSSDK.Lambda" preserve="all"/>
</linker>
```
Please make sure to include all the AWSSDK dlls that you are using.
The usage of `link.xml` is described [here](https://docs.unity3d.com/Manual/IL2CPP-BytecodeStripping.html).

**Comment by SankarGanesh82** [comment]
Hello,
Tried everything and didn't worked. We are using Unity 2019.1.12f1 and Unity AWSSDK version 3.3.602.0. Working fine in the Editor and got ERROR in Android. Quick solid solution needed. Thanks in advance.

10-11 18:23:32.046  5349  5363 I Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)
10-11 18:23:32.046  5349  5363 I Unity   : 
10-11 18:23:32.114  5349  5363 E Unity   : ArgumentException: Object of type 'System.Object[]' cannot be converted to type 'UnityEngine.AndroidJavaObject[]'.
10-11 18:23:32.114  5349  5363 E Unity   :   at System.RuntimeType.CheckValue (System.Object value, System.Reflection.Binder binder, System.Globalization.CultureInfo culture, System.Reflection.BindingFlags invokeAttr) [0x00000] in <00000000000000000000000000000000>:0 
10-11 18:23:32.114  5349  5363 E Unity   :   at System.Reflection.MonoMethod.ConvertValues (System.Reflection.Binder binder, System.Object[] args, System.Reflection.ParameterInfo[] pinfo, System.Globalization.CultureInfo culture, System.Reflection.BindingFlags invokeAttr) [0x00000] in <00000000000000000000000000000000>:0 
10-11 18:23:32.114  5349  5363 E Unity   :   at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <00000000000000000000000000000000>:0 
10-11 18:23:32.114  5349  5363 E Unity   :   at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <00000000000000000000000000000000>:0 
10-11 18:23:32.114  5349  5363 E Unity   :   a
10-11 18:23:32.115  5349  5363 I Unity   : Attached unity initializer to Test
10-11 18:23:32.115  5349  5363 I Unity   : UnityEngine.Logger:Log(LogType, Object)

**Comment by klaytaybai** [comment]
Work on Unity-related PRs are paused at this time.
 We encourage our users to use the .NET Standard 2.0 version of the AWS SDK for .NET which can be downloaded from NuGet or, as a .zip file, [here](https://sdk-for-net.amazonwebservices.com/latest/v3/aws-sdk-netstandard2.0.zip).  

 The downloads of the last supported version of the AWS Mobile SDK for Unity, as well as its source code, will continue to be available to customers. However the AWS Mobile SDK for Unity will no longer be officially supported by the AWS SDK for .NET team.

**Comment by OscarKing888** [comment]
Library\PackageCache\com.unity.scriptablebuildpipeline@1.9.0\Editor\CacheServer\Client.cs(464,35): error CS0433: The type 'InvalidDataException' exists in both 'AWSSDK.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null' and 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

Painful....
