### ISSUE TITLE
SocketException when use a dynamodb locally

### ISSUE THREAD

**Issue by gsGabriel** [aws/aws-sdk-net#1372]
Hi guys,

When I configure a client with a local URL generated by the amazon / dynamodb-local image, I cannot succeed and a SocketException is always returned. If I browse url http: // localhost: 8000 / shell in the browser, the page opens and I can perform the commands, but via SDK it doesn't work. Follow the code below:

```csharp
    class Program
    {
        static async Task Main(string[] args)
        {
            using (var client = new AmazonDynamoDBClient(new AmazonDynamoDBConfig
            {
                UseHttp = true,
                LogMetrics = true,
                LogResponse = true,
                DisableLogging = false,
                ServiceURL = "http://localhost:8000",
            }))
            {
                client.Config.Validate();

                var tableName = "dev.consoleapplication";
                var tables = await client.ListTablesAsync(); //This point generate exception
```

## Your Environment
* AWSSDK.DynamoDBv2 version 3.3.101.49
* Visual Studio version: Community 2019 16.2.0
* Targeted .NET platform: netcoreapp2.2

## .NET Core Info

* .NET Core version used for development: 2.2.401

**Comment by klaytaybai** [comment]
Hi @gsGabriel, what is the exact error you are getting?  Can you please verify that at the time of this call, your client has valid credentials?  Are you also using the Visual Studio Toolkit?

**Comment by gsGabriel** [comment]
Hi @klaytaybai,

Without the AWS Toolkit. 

I am working with a local docker image, do I need to pass credentials? What would be the credentials? I question because when i run the image I do not configure access credentials. 

In fact when I made the configuration pointing to my region informing the keys, everything works perfectly ...

**Comment by klaytaybai** [comment]
The credentials are the issue.  You can find more here:  https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-creds.html
