### ISSUE TITLE
Linux availability

### ISSUE THREAD

**Issue by pikausp** [aws/aws-sdk-net#1376]
Hey,

I just started working on moving an ASP.NET Core application from Windows to Linux server (made by third party). From reading the documentation I assumed there should be no issue. The app sends emails via amazon and the profile registration fails.

```
var profile = new CredentialProfile(profileName, credentials) {
    Region = RegionEndpoint.EUWest1
};

var netSDKFile = new NetSDKCredentialsFile();
netSDKFile.RegisterProfile(profile);
```
with the following exception
```
Unhandled Exception: Amazon.Runtime.AmazonClientException: The encrypted store is not available.  This may be due to use of a non-Windows operating system or Windows Nano Server, or the current user account may not have its profile loaded.
   at Amazon.Util.Internal.SettingsManager.EnsureAvailable()
   at Amazon.Runtime.CredentialManagement.NetSDKCredentialsFile..ctor()
```
The message seems to state non-Windows OS are not supported, or am I misunderstanding?

**Comment by klaytaybai** [comment]
Hi @pikausp, thanks for the feedback about our documentation not making it clear enough that this method of credentials won't work on Linux.  In some of our [docs](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/Runtime/TNetSDKCredentialsFile.html), we mention that this method is dependent on the Windows Data Protection API, which is specific to Windows OS, but we could still make this clearer.

If you need to change between Linux and Windows, the [credentials methods](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-creds.html) other than SDK Store (e.g. SharedCredentialsFile) will work.
