### ISSUE TITLE
How to avoid cold start impact of large AWSSDK dlls on a Lambda function

### ISSUE THREAD

**Issue by johnfnz** [aws/aws-sdk-net#1377]
I'm writing a .NET Core 2.1 lambda function and I want to use the Systems Manager Parameter Store but when I pull in the AWSSDK references it impacts my cold start time. Is there an alternative?

With a hard-coded connection string my app size well under 100kb and with a cold start of just over 2s. To move to using the Parameter Store I took a dependency on AWSSDK.SimpleSystemsManagement.dll which pulls in AWSSDK.Core.dll and now my application is 1.5Mb with a cold start is 3.8s

**Comment by klaytaybai** [comment]
Hi @johnfnz, I'm surprised to see that your DLLs add that much memory and cold start time.  Thanks for your feedback.  That may be worth investigating, 

The SSM Parameter Store is often the recommended approach, but you may be able to avoid using the Parameter Store by instead defining [environment variables](https://docs.aws.amazon.com/lambda/latest/dg/env_variables.html) on your Lambda.  If you think this suits your use case, it may be worth considering.

**Comment by klaytaybai** [comment]
You should also consider using [Lambda Layers](https://aws.amazon.com/blogs/developer/aws-lambda-layers-with-net-core/).

**Comment by johnfnz** [comment]
Thanks for the suggestions @klaytaybai. To clarify, when I refer to the app size I mean the publish folder size, which it seems has an effect on the cold start time. 

I have used Layers but currently building on Windows so can't set --enable-package-optimization yet. 

I believe I can access the Parameter Store from the SAM at deploy time so that might make environment variables an option and keep the secrets out of the source code.
