### ISSUE TITLE
GetObjectAsync not giving callback on Oculus Go (Android) 

### ISSUE THREAD

**Issue by vincykiranjesus** [aws/aws-sdk-net#1378]
I am making a project for the Oculus Go, and I am having users login through CognitoAWSCredentials. This works in the Unity Editor, standard Android, standard IOS, and in standalone builds, but not on the Oculus Go (running Android).

##Expected Behavior
The scripts are expecting, Get Object from S3 Bucket

**Comment by normj** [comment]
Could you follow this blog post for having your Unity application use the .NET Standard version of the SDK? I'm curious how the .NET Standard version works in Oculus.

https://aws.amazon.com/blogs/developer/referencing-the-aws-sdk-for-net-standard-2-0-from-unity-xamarin-or-uwp/

I know the process is way too cumbersome right now. We are working on making that better.

**Comment by SimonStHilaire** [comment]
I have the exact same problem but on Oculus Quest 3. I am using the .NET Standard version.
