### ISSUE TITLE
.Net Source code for Example "Hello World" app on Elastic Beanstalk is missing from SDK

### ISSUE THREAD

**Issue by duaneking** [aws/aws-sdk-net#138]
Honestly not sure why you guys would only include a binary when the code itself is a lot more helpful; Without this sort of source most people wont even start as the docs are so badly written (and often wrong, as I have been forced to point out to support several times in the past year).

Where/when can we get the code for that simple, first EB hello world app for .net?

**Comment by duaneking** [comment]
That is not what I'm looking for; its not complete and does not fill this need.  You guys need to ship the code for the binary demos.

**Comment by jimfl** [comment]
The Hello World app was developed by a different team inside AWS. I contacted that team to see if I could get the source, but they only have the msdeploy bundle. I think that the only interesting thing that app does is show how to access configuration variables in an ASP.NET page.

If we were to build and publish some more elaborate sample apps, what kinds of features would you like to see them demonstrate?

**Comment by duaneking** [comment]
I just want the code for the sample application; there is no point in you demos not being source available.

**Comment by normj** [comment]
Closing this since the requested source is not something the SDK team owns. If there is still a desire for the source I'd suggest posting to the Beanstalk Forums

https://forums.aws.amazon.com/forum.jspa?forumID=86
