### ISSUE TITLE
Sns push notification not registering device on android pie(API Level 28)  

### ISSUE THREAD

**Issue by differenz-system** [aws/aws-sdk-net#1381]
I have implemented Sns notification with GCM in xamarin forms , it is working properly below 
android api level 28 but not working in Android Pie (Api 28).   

## Expected Behavior
It should register device , Should be getting device token.  

## Current Behavior
It is registering device below api level 28 and I am able to get notification but it is not registering device on Android Pie Devices(api level 28).

## My Environment
* AWSSDK.SimpleNotificationService version used:3.3.101.29 
* Operating System and version: MacOS High Sierra
* Visual Studio for mac Community version: 7.7.2

**Comment by klaytaybai** [comment]
What is the error you are getting?  Do you have any logs?

**Comment by differenz-system** [comment]
Getting below error while Registering broadcast service.

**Device Log:**

Unable to start service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gsf (has extras) } U=0: not found

**My Code**
private void RegisterForGCM()
 {
      string senders = Helpers.Constants.GoogleConsoleProjectId;
      Intent intent = new Intent("com.google.android.c2dm.intent.REGISTER");
      intent.SetPackage("com.google.android.gsf");
      intent.PutExtra("app", PendingIntent.GetBroadcast(this, 0, new Intent(), 0));
      intent.PutExtra("sender", senders);
      StartService(intent);
}
Calling this method in MainActivity > OnCreate

**Comment by nelsonvega** [comment]
Hi everyone, Did we find a solution to this issue?
