### ISSUE TITLE
Reference not found UnityEngine while building gamelift for unity from source

### ISSUE THREAD

**Issue by pritamsamadder048** [aws/aws-sdk-net#1384]
Hi, I am trying to build aws gamelift for unity from source build. I have successfully generated the solution file and when i open the solution file, it shows that In reference UnityEngine is not found in both AWSSDK.Core.Unty and AWSSDK.GameLift.Unity project.
I understand that Unity need to be installed in its standard installetion location and in my system unity is installed through unity hub but in a different location. so is there any way to resolve this issue with UnityEngine.dll not found?
please help

**Comment by klaytaybai** [comment]
You could download and edit the SDK, but it seems the simplest option would be to copy the UnityEngine.dll to C:\Program Files\Unity\Editor\Data\Managed\UnityEngine.dll

**Comment by pritamsamadder048** [comment]
I just did that and regenerated the projects again and now the unityengine reference is correct and i am successfully able to build the AWSSDK.Core.Unity and AWSSDK.GameLift.Unity
But it is not generating any Dll in the bin/Release/unity directory or anywhere else
Can you help me with this too please.

**Comment by zoidberg67** [comment]
I'm also kind of stuck on this, I see no libraries/dlls after building the project to place into Unity is there any guides or explanations anywhere?

**Comment by notpresleybutelvis** [comment]
> I just did that and regenerated the projects again and now the unityengine reference is correct and i am successfully able to build the AWSSDK.Core.Unity and AWSSDK.GameLift.Unity
> But it is not generating any Dll in the bin/Release/unity directory or anywhere else
> Can you help me with this too please.

Thanks @pritamsamadder048 , this trick worked for me
