### ISSUE TITLE
Await query completed CloudWatch log result

### ISSUE THREAD

**Issue by jasonycw** [aws/aws-sdk-net#1386]
https://github.com/aws/aws-sdk-net/blob/ec9c5981aa90babd193a55572f0ffeeeede18062/sdk/src/Services/CloudWatchLogs/Generated/_mobile/AmazonCloudWatchLogsClient.cs#L1621-L1624

Is there any proper documentation on how to query a completed result?

## Expected Behavior
`await GetQueryResultsAsync` will return a completed query result

## Current Behavior
``` C#
var query = await _cloudWatch.StartQueryAsync(
    new StartQueryRequest
    {
        LogGroupName = _config["SEARCH_LOG_GROUP"],
        StartTime = (long)(DateTime.UtcNow.AddMinutes(-10) - new DateTime(1970, 1, 1)).TotalSeconds,
        EndTime = (long)(DateTime.UtcNow - new DateTime(1970, 1, 1)).TotalSeconds,
        QueryString = "{ $.Level=\"Error\"}",
        Limit = 10
    }, token);

var results = await _cloudWatch.GetQueryResultsAsync(
    new GetQueryResultsRequest
    {
        QueryId = query.QueryId
    }, token);
```
`results` will still be in **Running** status

## Your Environment
- AWSSDK.Core version used: 1.1.0
- Service assembly and version used: AWSSDK.CloudWatchLogs 3.3.101.13
- Operating System and version: Windows 10
- Visual Studio version: 2019 16.2.2
- Targeted .NET platform: Core 2.1

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
Hi @jasonycw, as specified in the documentation in the code and the [API reference](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_GetQueryResults.html), GetQueryResults may return incomplete results if the status is not "Complete".  In this case, users are supposed to retry the operation later to see the final results once the status is "Complete".  If you want to stop an ongoing query, you can use the StopQuery operation.

**Comment by jasonycw** [comment]
So there is no way to `await` a completed result and I need to loop `GetQueryResultsAsync` until I get complete status?

**Comment by klaytaybai** [comment]
Currently that is correct, but I believe this will be included in the future "waiters" work described in our project section for SDK improvements. #1336

**Comment by Ganesh-Prakash** [comment]
Hi Team,
is there any properties or method introduced to check QueryResult status is completed?
