### ISSUE TITLE
AmazonS3Client.CopyObjectAsync fails silently when destination key has leading slash

### ISSUE THREAD

**Issue by antplant** [aws/aws-sdk-net#1388]
This is the inverse of #1241.

When using `CopyObjectAsync` to copy an object to a destination key with a leading slash, the copy request succeeds but the destination object is never created.

This is particularly dangerous in workflows which involve deleting source objects after copy.

This affects SDK version 3.3.104.17.

**Comment by antplant** [comment]
It's just occurred to me that our test case for this is copying from "foo" to "/foo" so I wonder if this is actually a result of the leading slash being stripped and the source and destination keys winding up the same.

**Comment by klaytaybai** [comment]
That seems to be the issue.  I'm going to close this for now.

**Comment by antplant** [comment]
Hi - not sure this should be closed. Leading slashes are valid in keys silently stripping them from copy (but apparently not PUT) requests in the SDK seems very unintuitive and dangerous.

We have permanently lost production data as a result of this behaviour.

**Comment by klaytaybai** [comment]
Fair points.  I had once written a solution for this and #1241, but it wasn't approved at the time.  I think there was concern for backwards compatibility for this part.  I'll make it a priority to get this resolved with some kind of a code change soon.  I agree that it's important and that it should be consistent with other S3 operations and AWS offerings.
