### ISSUE TITLE
Can't get S3 sample to work with Unity, IL2CPP and Android

### ISSUE THREAD

**Issue by ShacharWeis** [aws/aws-sdk-net#1389]
I have a Unity app that needs to upload files to S3.
It works on desktop. When I build and run on an Android device, I'm getting no response from S3. There are no errors either (I'm looking at the logcat), just nothing. 

I've added S3 to link.xml 

Any ideas ?

**Comment by ShacharWeis** [comment]
This is why :(

https://issuetracker.unity3d.com/issues/android-aws-sdk-stopped-working-in-android-builds-with-unity-2019-dot-1-0a1-and-up

**Comment by Ethan-VisualVocal** [comment]
I assume you're using the "AWS Mobile SDK for Unity" https://docs.aws.amazon.com/sdk-for-unity/index.html 

But instead, have you tried using the .NET Standard 2.0 version of the SDK? 
https://aws.amazon.com/blogs/developer/referencing-the-aws-sdk-for-net-standard-2-0-from-unity-xamarin-or-uwp/ 
(I have not, but will need to try soon...)

**Comment by derwaldgeist** [comment]
Did you find a solution?

**Comment by NGL321** [comment]
Hey @ShacharWeis,

Are you still experiencing this issue? If so, you may consider updating to the latest version of the SDK and trying again.

[As of SDK v3.5](https://aws.amazon.com/blogs/developer/aws-sdk-for-net-v3-5-now-generally-available/) we no longer separate Unity support from regular .NET support, if you are having trouble with this transition, please make sure you are [targeting ^.NET 4.0 or ^.NET Standard 2.0](https://docs.unity3d.com/2020.1/Documentation/Manual/dotnetProfileSupport.html) using Unity 2018.0 or later. This means that you can have full access to AWS services when using the .NET SDK with Unity, but if you would still like to use the legacy SDK for Unity, you can reference it from our [archive repo](https://github.com/aws/aws-sdk-unity-net).

If you are still struggling with this in the latest version of the SDK, please let me know and I will take a deeper look!

😸 😷
