### ISSUE TITLE
Multiple conditions on Query filter in DynamoDBContext

### ISSUE THREAD

**Issue by malaqueueit** [aws/aws-sdk-net#139]
Hi

I have a query with multiple query filter conditions on the same attribute (named 'Partition') - like this:

``` csharp
                DynamoDBOperationConfig config = new DynamoDBOperationConfig()
                {
                    QueryFilter =
                        new List<ScanCondition>()
                        {
                            new ScanCondition("Partition", ScanOperator.IsNull),
                            new ScanCondition("Partition", ScanOperator.Equal, "Some Value")
                        },
                        ConditionalOperator = ConditionalOperatorValues.Or
                };

                var result = dynamoDBContext.Query<PeerPing>(
                    this._serviceName,
                    QueryOperator.GreaterThan,
                    new object[] { "Some other value" },
                    config);

```

And the Conditional Operator OR. For some reason only the last scan condition is applied. In the above example I get all items where the Partition attribute equals "Some Value", but not the ones where the Partition attribute is null. If I switch the order of the two I get the ones which are null.

I would expect that I would get the items where the Partition attribute is either null or 'Some Value'.

This was spotted in version 2.1.2.0

**Comment by dbaranovsky** [comment]
Any progress on this please? still have the same issue if multiple conditions on the same field -- only last condition applied and not exception
