### ISSUE TITLE
How to use Json Job Settings in MediaConvert?

### ISSUE THREAD

**Issue by maxima120** [aws/aws-sdk-net#1395]
I am looking at the .NET sample here: https://docs.aws.amazon.com/mediaconvert/latest/apireference/custom-endpoints.html

according to this: https://docs.aws.amazon.com/mediaconvert/latest/apireference/sample-json.html

I can only pass job spec as json string to CLI or Python but in .NET SDK I need to construct objects by hand. 

I mean - I am totally at loss.. 

Do I have to write 50000 lines Json parser to convert it to SDK objects or do I have to write and deploy a C# class for each job?? 

Please help

**Comment by klaytaybai** [comment]
Hi @maxima120.  Neither are needed.  If you have a JSON file, you could possibly create the requests with only a few lines of code.  You can use an existing JSON library such as Newtonsoft to handle the deserialization into the CreateJobRequest object.  However, the .NET SDK isn't guaranteed to use the same property names as the fields in the JSON that you would send to the CLI, so you should verify that the fields in the JSON map to an SDK property and that your deserialized objects are complete.

**Comment by maxima120** [comment]
I know how to use newtonsoft. I doubt serialisation will succeed into CreateJobRequest. Exactly as I suspected : "SDK isn't guaranteed to use the same property names"

Which means I will have to search through whole object graph and create a map of dynamic json object to CreateJobRequest properties..

I never seen this kind software since 1984.

**Comment by ashishdhingra** [comment]
Hi @maxima120,

Good afternoon.

I was going through the issue backlog and came across this question. I do see some input provided by @klaytaybai. I'm not sure what further input could be provided here. Please advise if we could close this issue.  

Thanks,
Ashish
