### ISSUE TITLE
Cannot mock DynamoDBContext.CreateBatchGet due to lack of interfaces

### ISSUE THREAD

**Issue by krzysztof-at-mp** [aws/aws-sdk-net#1396]
When I try write unit test for code which uses DynamoDBContext.CreateBatchGet I'm stuck on providing fake results. The BatchGet<T> does not have a public available constructor nor does CreateBatchGet<T> use an interface for return type.

## Expected Behavior

The easiest way would be to add IBatchGet<T> interface and add it as a return type for CreateBatchGet<T>. This would allow easily provide mock when using IDynamoDbContext and return fake data for my tests.

## Current Behavior

BatchGet<T> cannot be instantiated so I'm forced to use concrete type like DynamoDbContext. 

`IAmazonDynamoDB client = Substitute.For<IAmazonDynamoDB>();
IDynamoDBContext context = new DynamoDBContext(client, new DynamoDBOperationConfig
{ OverrideTableName = "Abc" });
BatchGet<T> batch = context.CreateBatchGet<T>();
await batch.ExecuteAsync();`

Having this done I strange exceptions from SDK internals like

`System.NullReferenceException : Object reference not set to an instance of an object.
   at Amazon.DynamoDBv2.DocumentModel.Table.DescribeTable(String tableName)`

and still I see no easy way to return results :(

I could do some tweaks in my code by adding some unwanted entity attributes and be able go over this issue but then I'm at executing the batch and still there is no easy way to provide the results. I could do:

`IDynamoDBContext context = Substitute.For<IDynamoDBContext>();
BatchGet<T> batch = context.CreateBatchGet<T>();
await batch.ExecuteAsync();`

but in this case I cannot find an easy way to provide fake data through the mocked IDynamoDBContext nor mocked IAmazonDynamoDB. 

I also cannot return fake data by using another approach

`IDynamoDBContext context = Substitute.ForPartsOf<DynamoDBContext>();
BatchGet<T> batch = context.CreateBatchGet<T>(...)
context.ExecuteBatchGetAsync(new BatchGet[] { batch })`

because in this case the ExecuteBatchGetAsync public method is not marked as virtual so it's difficult to ovverride that call using eg. NSubstitute.

## Possible Solution

Add IBatchGet interface for CreateBatchGet in IDynamoDBContext.
(or) Make ExecuteBatchGetAsync virtual in DynamoDBContext

I can provide a pull request for this change if you feel you need one :)

## Steps to Reproduce (for bugs)

Write unit test which returns fake data from the batch API.

## Your Environment

* AWSSDK.DynamoDBv2 (3.3.101.59)

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by rue-vmom** [comment]
I think it's because of this:
https://github.com/aws/aws-sdk-net/blame/231a7e147159cc8e0da023f35001a25ed923d01e/sdk/src/Services/DynamoDBv2/Custom/DocumentModel/Table.cs#L378

The `as AmazonDynamoDBClient` makes it impossible to pass in a mocked instance for .NET Standard, it will set it to null (which seems like a bug since there are guards to prevent passing in a null in the constructor).

**Comment by mlhpdx** [comment]
Having the same problem, and found the same issue (essentially): use of the protected version of DescribeTable on AmazonDynamoDBClient instead of the public interface override makes it nonviable to Moq<IAmazonDynamoDB> it.  Why does this require a breaking change to fix?

**Comment by gpomykala** [comment]
I also suffer from this issue. Single item operations (LoadAsync / PutAsync) are mockable but their batch counterparts are not which forces us to test against DynamoDB Local. This is not ideal for scenarios.

**Comment by metapack-poland** [comment]
It has been mentioned here https://github.com/aws/aws-sdk-net/issues/1589 as well.

**Comment by 96malhar** [comment]
Hello, we have been working on the V4 of the AWS SDK for .NET. We have added the ability to mock various DynamoDB operations by adding interfaces in both the Data Model mode and Document Model mode in DynamoDB. 

Refer to this PR - https://github.com/aws/aws-sdk-net/pull/3450

This feature is available in the AWSSDK.DynamoDBv2 Version [4.0.0-preview.2](https://www.nuget.org/packages/AWSSDK.DynamoDBv2/4.0.0-preview.2)
