### ISSUE TITLE
Loading credentials from custom profile location

### ISSUE THREAD

**Issue by abjrcode** [aws/aws-sdk-net#1399]
[According to documentation](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-creds.html#creds-assign) it should be possible to override the profile location and profile name via AppConfig or directly by setting the properties on [AWSConfigs](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/AWSConfigs.cs).

Tried both approaches without avail

## Expected Behavior
Running this:
```c#
 var webHostBuilder = new WebHostBuilder()
                .UseStartup<Startup>()
                .UseEnvironment("Development")
                .ConfigureServices(serviceCollection =>
                {
                    AWSConfigs.AWSProfileName = "dummy";
                    AWSConfigs.AWSProfilesLocation = Path.Join(typeof(TestWebHost).Assembly.Location, "dummy_credentials");
                    serviceCollection.AddSingleton(settings);
                });


            return new TestServer(webHostBuilder).CreateClient();
```
then later this:
```c#
var clientConfig = new AmazonDynamoDBConfig
            {
                ServiceURL = _dynamodbEndpoint // POINTS TO LOCAL CONTAINER ENDPOINT
            };
.
.
.
using (var dynamoClient = new AmazonDynamoDBClient(clientConfig))
```
Then it should load the credentials from my custom credentials file.

## Current Behavior
It doesn't load the credentials from the specified location.
Checking the source code I don't even see how that will happen:
1. https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/DynamoDBv2/Generated/_bcl35/AmazonDynamoDBClient.cs#L83
1. https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Credentials/FallbackCredentialsFactory.cs
1. https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Credentials/FallbackCredentialsFactory.cs#L35
1. https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Credentials/FallbackCredentialsFactory.cs#L54
1. https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Credentials/FallbackCredentialsFactory.cs#L69

From what I see the behaviour described in the documentation page only applies to BCL and not .NET Core?

## Context
I wanted to supply dummy credentials because I am using DynamoDb container in my integration tests but it was still trying to look for the default credential profile in `~/.aws/credentials` which doesn't necessarily exists.
Basically trying to make the tests portable and independent of global environment by supplying fake credentials.

## Your Environment

* AWSSDK.Core version used:  3.3.103.36
* Service assembly and version used: AWSSDK.DynamoDbV2 3.3.101.63
* Operating System and version: Windows 10 Build 1903
* Visual Studio version: JetBrains Rider
* Targeted .NET platform: .NET Core 2.1

## .NET Core Info

* .NET Core version used for development: .NET Core 2.2 (2.2.402)
* .NET Core version installed in the environment where application runs: .NET Core 2.2 (2.2.402)
* Output of `dotnet --info`: 
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.402
 Commit:    3599f217f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.402\

Host (useful for support):
  Version: 2.1.4
  Commit:  85255dde3e

.NET Core SDKs installed:
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```
* Contents of project.json/project.csproj: Empty

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
It looks like you are not using the [.NET Core Setup Extensions](https://github.com/aws/aws-sdk-net/tree/master/extensions/src/AWSSDK.Extensions.NETCore.Setup).  You can read some documentation on this [here](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-netcore.html).  Let me know if that helps.

**Comment by abjrcode** [comment]
What does the region default to if it cannot find it in any of the fallback mechanisms and the service URL points to `localhost`?
Also it seems you cannot anymore provide custom service client configuration?

**Comment by klaytaybai** [comment]
If you specify a region, it will override the service url.  If you are working with localhost, you shouldn't specify the region.  https://github.com/aws/aws-sdk-net/blob/662be216d79d4c34f058d4e1bb1b7891e4d682fc/sdk/src/Core/Amazon.Runtime/ClientConfig.cs#L117-L136

**Comment by abjrcode** [comment]
Thanks for your kind help sir.
