### ISSUE TITLE
AmazonSecurityTokenServiceClient constructor is slow

### ISSUE THREAD

**Issue by jacobusp** [aws/aws-sdk-net#1401]
##  Expected Behavior
The AmazonSecurityTokenServiceClient constructor, provided with credentials and a region, should operate separately from the application configuration.

## Current Behavior
When I remove the following code from my application configuration;
`<aws profileName="someProfile" region="eu-west-1"></aws>`
the constructor will take approximately 10 seconds to complete, even though it does not use the specific profile that was previously specified in the application configuration.

When I put the code back into the configuration file, it does not take the extra 10 seconds.

## Steps to Reproduce
- Remove (aws) section(s) from the application configuration (App.config usually).
- Call the AmazonSecurityTokenServiceClient(AWSCredentials credentials, RegionEndpoint region) constructor.

## Context
I am trying to run my application and use the aws sdk without having to put stuff in my application's configuration file. 
Therefore, I use the constructor of the AmazonSecurityTokenServiceClient that takes credentials and region as parameters: `AmazonSecurityTokenServiceClient(AWSCredentials credentials, RegionEndpoint region)`
Because the default constructor reads credentials from the application's configuration:
`AmazonSecurityTokenServiceClient()`

### Side Notes
Is my line of thought wrong for not wanting credential references in my application configuration (because they are already in the default user's credentials file .aws/credentials)?
Why would the AmazonSecurityTokenServiceClient constructor even incorporate the application's configuration file if I manually provide it with the required data (region and credentials)?

## Environment
* AWSSDK.Core version used: 3.3.103.32
* Operating System and version: Windows 10
* Visual Studio version: 2017 15.9.16
* Targeted .NET platform: .NET Framework 4.6.1

**Comment by klaytaybai** [comment]
This seems odd.  If you're specifying the credentials, it should not need to use the App.config.  It also shouldn't be taking 10 seconds.  What method are you using to set the AWSCredentials credentials?  BasicAWSCredentials where you add the keys or some other means?  Are you using eu-west-1 when you use this constructor, too?

**Comment by klaytaybai** [comment]
I was looking into the credentials.  The problem is with the AmazonSecurityTokenServiceConfig created when taking the region parameter.

**Comment by jacobusp** [comment]
I create the credentials and region using the following code:
```
AWSCredentials credentials = null;
RegionEndPoint region= null;
ICredentialProfileSource source = new SharedCredentialsFile();
bool profileWasFound = source.TryGetProfile(profileName, out CredentialProfile profile);
credentials = profile.GetAWSCredentials(source);
region = profile.Region;
```

Then I create the AmazonSecurityTokenServiceClient like this:
`var tokenServiceClient = new AmazonSecurityTokenServiceClient(credentials, region);`
Which will take ~10 seconds

My credentials file looks like this:
```
[SomeProfile]
region = eu-west-1
aws_access_key_id = SomeAccessKeyId
aws_secret_access_key = SomeSecretAccessKey
```

**Comment by jacobusp** [comment]
I'm just wondering why this is classified as a feature-request? 
As @klaytaybai stated:
> This seems odd. If you're specifying the credentials, it should not need to use the App.config. It also shouldn't be taking 10 seconds.

This should be a bug right?
