### ISSUE TITLE
NullReferenceExecption when intializing AmazonSQSClient from EC2 instance with no assigned IAM role

### ISSUE THREAD

**Issue by BlanchardT** [aws/aws-sdk-net#1403]
Background:
Running a .NET Core client application on an EC2 instance. 
Trying to initialize an AmazonSQSClient with only a region as a parameter

When no IAM role is assigned to the EC2 instance the initialization of the client fails with the following error 

```
NullReferenceException -- Object reference not set to an instance of an object.
Exception.Data: ( )
Exception.TargetSite: Amazon.Runtime.ImmutableCredentials FetchCredentials()
Exception.Source: AWSSDK.Core
Exception.HResult: -2147467261
Exception.StackTrace: 
at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.FetchCredentials()
at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentials()
at Amazon.Runtime.Internal.CredentialsRetriever.PreInvoke(IExecutionContext executionContext)
at Amazon.Runtime.Internal.CredentialsRetriever.InvokeSync(IExecutionContext executionContext)
at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext)
at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext)
at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext)
at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext)
at Amazon.Runtime.AmazonServiceClient.Invoke[TResponse](AmazonWebServiceRequest request, InvokeOptionsBase options)
```

When I assign an IAM role, no error is thrown.

## Expected Behavior
When no IAM role exists on the instance and the AmazonSQSClient is being initialized a more specific exception should get thrown, rather than the NullReferenceException.

## Steps to Reproduce (for bugs)
Initialize an AmazonSQSClient on an EC2 instance without an IAM role

## .NET Core Info
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.109
 Commit:    586f23c400

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.109\

Host (useful for support):
  Version: 2.2.7
  Commit:  b1e29ae826

.NET Core SDKs installed:
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.2.109 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by klaytaybai** [comment]
Hi @BlanchardT, what version of the SDK are you using?  I believe this has already been fixed.

**Comment by BlanchardT** [comment]
AWSSDK.SQS v3.3.101.2
AWSSDK.Core v3.3.103.31
AWSSDK.EC2 v3.3.127

**Comment by BlanchardT** [comment]
@klaytaybai any idea on this?

**Comment by klaytaybai** [comment]
I assume you are not providing credentials at all then?  May I ask why?  If you are not providing credentials at all, you should have an associated IAM role if you want to connect to the service.

**Comment by BlanchardT** [comment]
That's correct, there was no IAM role assigned to the EC2 instance that this ran on. This was during a test and the engineer running the test noticed this error in the log and was unaware of the necessary IAM roles. The null reference error didn't make it obvious as to what was missing. 

In order to provide a nicer error for future engineers we could catch the null reference thrown from the AmazonSQSClient and rethrow a custom error but I think that the sdk could handle this a little better.

**Comment by BlanchardT** [comment]
Is this something your team would consider fixing? We could catch the null reference but it's not nice to handle..

**Comment by runeetv** [comment]
@BlanchardT you seem to be using older version of SDK. This was fixed couple of months ago.

https://github.com/aws/aws-sdk-net/commit/9b7e1f4bc7debb3ecea86b40c97c55bbdb6474c7#diff-19922f5d8acc62e7de2723c988c4e583
