### ISSUE TITLE
TransferUtilityUploadDirectoryRequest.UploadFilesConcurrently is internal in net core

### ISSUE THREAD

**Issue by ArchanaNeog** [aws/aws-sdk-net#1404]
Not able to access UploadFilesConcurrently of TransferUtilityUploadDirectoryRequest.cs

I am using AWSSDK.S3 3.3.104.28.

Is there any plan to expose this property for concurrent processing of files?

**Comment by klaytaybai** [comment]
Thanks for reporting this.  It's being treated as a bug for now.  It should go into a release soon.

**Comment by ashishdhingra** [comment]
Hi @ArchanaNeog, 

This appears to be fixed as per comment https://github.com/aws/aws-sdk-net/issues/1227#issuecomment-657180129.

Thanks,
Ashish
