### ISSUE TITLE
GetPreSignedURL 404 XML error

### ISSUE THREAD

**Issue by ironman1964** [aws/aws-sdk-net#1411]
If Key does not exist, GetPreSignedURL should return an ArgumentError or fails a try catch.
Like sample on this page https://docs.aws.amazon.com/AmazonS3/latest/dev/ShareObjectPreSignedURLDotNetSDK.html

At this moment it returns an XML error "NoSuchKey"
`<Error>
<Code>AccessDenied</Code>
<Message>Request has expired</Message>
<X-Amz-Expires>300</X-Amz-Expires>
<Expires>xxx</Expires>
<ServerTime>xxx</ServerTime>
<RequestId>xxx</RequestId>
<HostId>xxx</HostId>
</Error>`

* AWSSDK.Core version used: 3.3.104.31
* Targeted .NET platform: 4.5

**Comment by klaytaybai** [comment]
Hi @ironman1964, thank you for the feedback.  However, I don't think this is something that we are likely to add.  The main issue with adding this is that it would break one valid use case:  customers could currently first create a valid but premature presigned URL for getting objects and then create those objects.  For your use case, it sounds like you might benefit by adding some extra logic to make the request and verify that it doesn't result in a 404.
