### ISSUE TITLE
client.GetObjectMetadata() failed when file name contains spaces.

### ISSUE THREAD

**Issue by nishani** [aws/aws-sdk-net#1412]
When I am trying to retrieve meta from an object (client.GetObjectMetadata()) for a file name which contains spaces, it gives me 

> Error making request with Error Code Forbidden and Http Status Code Forbidden. No further error information was returned by the service

I am using minio as file server which is hosted locally in my machine. If file name does not contain any spaces it works perfectly fine. Please can anyone help me to figure out a  way to access files where file name contains spaces?

            var credentials = new BasicAWSCredentials(accesKey, secretKey); // Keys to access minio
            var config = new AmazonS3Config()
            {
                ServiceURL = "http://127.0.0.1:9000", // File server url
                SignatureVersion = "4",
                ForcePathStyle = true,
                Timeout = TimeSpan.FromSeconds(10),
                ReadWriteTimeout = TimeSpan.FromSeconds(3),
                MaxErrorRetry = 1,
            };

           AmazonS3Client client = new AmazonS3Client(credentials, config);

            try
            {
                //This is throwing an exception as file name contains spaces
                var response = client.GetObjectMetadata(new GetObjectMetadataRequest() { BucketName = "test", Key = "test 1.pdf" });

                //This is working fine
                //var response = client.GetObjectMetadata(new GetObjectMetadataRequest() { BucketName = "test", Key = "test1.pdf" });
                Console.WriteLine(response.HttpStatusCode);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }`

Versions
AWSSDK.S3 3.3.104.31
.net framework 4.6.1

**Comment by klaytaybai** [comment]
Hi @nishani, unfortunately I wasn't able to reproduce your problem using S3.  Since this doesn't seem to be an issue with the SDK, we probably can't assist you with this issue.
