### ISSUE TITLE
Missing tags, user-defined metadata when uploading any files greater than 8MB using presigned URLs (S3, C#)

### ISSUE THREAD

**Issue by thanhduyvo** [aws/aws-sdk-net#1414]
When I generate a PreSigned URL for user to upload an object to S3. Client able to add tags using ```x-amz-tagging```, and user-defined metadata using ```x-amz-meta-``` for any files less than 8MB, but for files greater than this size, these information are missing after file is uploaded to S3.  Also, Content-Type in Metadata is changed to ```binary/octet-stream``` type.

## Expected Behavior
Server: This is the basic request construction (C#) which generates PreSigned URL:
```
GetPreSignedUrlRequest presignRequest = new GetPreSignedUrlRequest
{
    BucketName = awsBucket,
    Key = fileKey,
    Expires = DateTime.Now.AddMinutes(expiresInMinutes),
    Verb = verbType
};

if (verbType == HttpVerb.PUT)
{
    presignRequest.ContentType = fileType;
    presignRequest.Headers["x-amz-meta-content-type"] = fileType;
    presignRequest.Headers["x-amz-tagging"] = $"contentType={UrlEncode(fileType)}";
}

urlString = awsClient.GetPreSignedURL(presignRequest);                 
```

Client: Use generated PreSigned URL to upload file to S3 (TypeScript):
```
const headers = new HttpHeaders({
    'x-amz-meta-content-type': filetype,
    'x-amz-tagging': `contentType=${encodeURL(filetype)}`
});
this.http.put(url, body, { headers });
```

I'm expecting all files should be uploaded to S3 and have these info:
- Metadata should include two items: 
```Content-Type = {filetype}``` (the file type is added to Metadata as default)
```x-amz-meta-content-type = {filetype}```
- Tags should include one item ```contentType = {filetype}```.

## Current Behavior
The upload is successful but for files greater than 8MB, these information are missing in S3 bucket.  Also, Content-Type in Metadata is changed to ```binary/octet-stream``` type.

## Your Environment

* AWSSDK.Core version used: 3.1.5.3
* Operating System and version: Windows Server 2012 R2 Standard
* Visual Studio version: 2019
* Targeted .NET platform: 4.6.1

## .NET Core Info
This isn't a Core project.

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
Hi @thanhduyvo, I haven't been able to reproduce your problem yet.  I can set custom metadata and tags just fine, but note that I use the ContentType property in the GetPresignedUrlRequest.  I'm not sure why file size would be affecting the behavior.  This happens to you consistently?

**Comment by thanhduyvo** [comment]
@klaytaybai For any files less than 8MB, it's working perfectly as expected. This only happens with the files greater than 8MB. I also noticed there are two AWS CLI S3 config ```multipart_threshold``` and ```multipart_chunksize``` which both have 8MB as default value. Do you think my issue somehow relate to these config?

**Comment by klaytaybai** [comment]
No, those configs shouldn't affect this.  The .NET SDK doesn't use those particular options from the config files at all.  I tried with a 12 MB file, and it worked.  I'm pretty confused why the file size would affect this.  If you want to comment out those configuration settings for the multipart and try again, I would be interested if it ended up working.

How are you setting the body?  Is there any logic in there where file size would affect how it is handled?

**Comment by thanhduyvo** [comment]
@klaytaybai, ```body``` is a File Blob that represents a file from the file system in JavaScript. I'm putting file body directly to S3 using PreSigned URL so I believe there is no logic between HttpClient library and AWS S3.
I tested with a sample PDF file with size 9168377 bytes. This is the metadata of body object:
```
lastModified: 1569334643120
lastModifiedDate: Tue Sep 24 2019 09:17:23 GMT-0500 (Central Daylight Time) {}
name: "sample.pdf"
size: 9168377
type: "application/pdf"
webkitRelativePath: ""
```
After file is uploaded to S3, its Content-Type in Metadata is set to ```binary/octet-stream``` (this is default type of S3 object) instead of ```application/pdf```. Also, all tags and user-defined metadata are gone.
It seems S3 bucket doesn't recognize the file type in this case. So, only file content is uploaded to bucket.

**Comment by ashishdhingra** [comment]
Hi @thanhduyvo,

Good afternoon.

I was going through the issue backlog and came across this one. I was able to set the content type in S3 bucket properly while using Postman with the pre-signed URL generated from the following code (notice setting `request.ContentType`):
```C#
using Amazon;
using Amazon.S3;
using Amazon.S3.Model;
using System;
using System.IO;
using System.Net;

namespace Amazon.DocSamples.S3
{
    class UploadObjectUsingPresignedURLTest
    {
        private const string bucketName = "[bucket name]";
        private const string objectKey = "[object key]";
        private const string filePath = "[path to file]";
        // Specify how long the presigned URL lasts, in hours
        private const double timeoutDuration = 12;
        // Specify your bucket region (an example region is shown).
        private static readonly RegionEndpoint bucketRegion = RegionEndpoint.USEast2;
        private static IAmazonS3 s3Client;

        public static void Main()
        {
            s3Client = new AmazonS3Client(bucketRegion);
            var url = GeneratePreSignedURL(timeoutDuration, "application/pdf");
        }

        private static string GeneratePreSignedURL(double duration, string fileType)
        {
            var request = new GetPreSignedUrlRequest
            {
                BucketName = bucketName,
                Key = objectKey,
                Verb = HttpVerb.PUT,
                Expires = DateTime.UtcNow.AddHours(duration)
            };

            if (!string.IsNullOrWhiteSpace(fileType))
            {
                request.ContentType = fileType;
            }

            string url = s3Client.GetPreSignedURL(request);
            return url;
        }
    }
}
```

I was able to test the upload of more than 8MB (up to 21MB) in my scenario. 

Just a note, there is already an issue logged for tagging https://github.com/aws/aws-sdk-net/issues/1696.

Please let me know if this is still an issue for content type or if this issue could be closed.

Thanks,
Ashish
