### ISSUE TITLE
[AWS Lambda] Keys in S3Event Records replace spaces with plus signs ('+'), resulting in 'Key not found' when trying to access the S3 object.

### ISSUE THREAD

**Issue by honkmother** [aws/aws-sdk-net#1417]
I just spent an hour or more of my life figuring out why an AWS Lambda function was failing when trying to access S3 only to realize that the S3Event object is returning invalid keynames.

In any scenario where there are spaces in the key has spaces in it's name, the spaces will be replaced by addition signs. Trying to access the reported key(s) from the S3Event object will result in a 'Key not found' exception.

e.g: this will fail if the key is named "folder a/data.csv"
```csharp
        static public async Task FunctionHandler(S3Event input, ILambdaContext context) {
          foreach(var record in input.Records) {
           using(var objectResponse = await s3Client.GetObjectAsync(record.S3.Bucket.Name, record.S3.Object.Key)) 
           {
           //... 
           }
          }
```

```csharp
record.S3.Object.Key.Replace('+', ' ')
```

When replacing the addition signs with spaces, it works as expected and the key is found.

**Comment by klaytaybai** [comment]
Thanks for reporting this.

**Comment by jiabiao** [comment]
I think this not a bug. 
The S3 key is UrlEncoded. Not only spaces are encoded,  but also some other special characters.
In dotnet core, you can decode the URL by  `WebUtility.UrlDecode `

**Comment by ashishdhingra** [comment]
@honkmother Please let me know if the guidance orivude day @jiabiao resolved your issue.

Thanks,
Ashish
