### ISSUE TITLE
AmazonCognitoIdentityProviderClient with no credentials throws SocketException

### ISSUE THREAD

**Issue by rwilliams-ultraserve** [aws/aws-sdk-net#1418]
If I construct an AmazonCognitoIdentityProviderClient without providing an AWSCredentials object; then use it to execute StartWithSrpAuthAsync() a SocketException: Host is down is thrown. (Can also result in an OperationCancelledException).

I suspect the problem occurs when my laptop attempts to connect to http://169.254.169.254 to retrieve the EC2InstanceMetedata and does not receive an ARP reply for the 169.254.169.254 host.

## Work Around - Pass Bogus Credentials to the ctor
new AmazonCognitoIdentityProviderClient(new BasicAWSCredentials("Problem", "Solved"));

## Suggestion
Modify all AWS Clients that do NOT require credentials to trap for errors thrown in EC2InstanceMetedata.cs
OR
Expose an option to disable the Credentials via EC2InstanceMetedata mechanism entirely. 

## Sample
var provider = new AmazonCognitoIdentityProviderClient();
var userPool = new CognitoUserPool("XXX", "YYY", provider);
var user = new CognitoUser("Jimmy", "YYY", userPool, provider);
var authResponse = await user.StartWithSrpAuthAsync(new InitiateSrpAuthRequest
{
  Password = "NotVerySecure"
}).ConfigureAwait(false);

**Comment by rwilliams-ultraserve** [comment]
The problem occurs when the [default] entry in ~/.aws/credentails is missing.

**Comment by klaytaybai** [comment]
Hi @rwilliams-ultraserve, please use [CognitoAWSCredentials](https://docs.aws.amazon.com/cognito/latest/developerguide/getting-credentials.html).
