### ISSUE TITLE
ServiceFactory.RegisterService throws Exception

### ISSUE THREAD

**Issue by Andreyul** [aws/aws-sdk-net#1419]
ServiceFactory.RegisterService throws an Exception:
```
New services can only be registered before ServiceFactory is accessed by calling ServiceFactory.Instance
```

## Expected Behavior
ServiceFactory.RegisterService should not throw an Exception

## Current Behavior
`ServiceFactory.RegisterService` checks if `_factoryInitialized` is true.
`_factoryInitialized` is set in `ServiceFactory` ctor. `ServiceFactory` is automatically constructed in a static field `Instance`.

## Possible Solution
Change `ServiceFactory.Instance` to lazy property.

## Steps to Reproduce (for bugs)
Call:
```
ServiceFactory.RegisterService<INetworkReachability>(typeof(Amazon.Util.Internal.PlatformServices.NetworkReachability));
```

## Context
I was trying to find a workaround of the Unity bug by replacing `NetworkReachability` service.
https://forum.unity.com/threads/2019-2-issue-with-application-internetreachability-for-android.726404/

## Your Environment

* AWSSDK version used: 3.3.599.0

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
Thanks
