### ISSUE TITLE
Default to signature v4 for unknown regions

### ISSUE THREAD

**Issue by mwhouser** [aws/aws-sdk-net#142]
For regions/endpoints not specified in the endpoints.xml file, please default to v4 signature.

Use Case: When EU (Frankfurt) region was introduced, attempting to use the eu-central-1 endpoint using an old version of the SDK required code changes and/or "AWS.S3.UseSignatureVersion4" setting in appSettings to force v4 signature which causes problems of their own.

**Comment by jo-rah** [comment]
Don't forget the possibility to set the signature version to use. This is important for other services supporting the S3 interface, e.g. Ceph Object Store. Currently, the AmazonS3Uri() constructor makes some assumptions about the uri that causes AmazonS3KmsHandler() to set SigV4 = true for all but the Offical Amazon S3 servers.

**Comment by jimfl** [comment]
Sigv4 is now the default.
