### ISSUE TITLE
Aggregate Exception - A task was cancelled in AWS lambda execution

### ISSUE THREAD

**Issue by 1ds14te050manoj** [aws/aws-sdk-net#1423]
I have created a lambda function to retrieve the secret using secret manager. When the API is called to secret as response I am getting an exception thrown called Aggregate Exception. 

## Expected Behavior
I am expecting to get the secret as my response and then printing the secret in the console.

## Current Behavior

Name - InnerException
Value - {System.Threading.Tasks.TaskCanceledException: A task was canceled.}
Type - System.Exception {System.Threading.Tasks.TaskCanceledException}

Name -  WaitHandle
Value - '((System.OperationCanceledException)ae.InnerException).CancellationToken.WaitHandle' 
             threw an exception of type 'System.ObjectDisposedException'  
Type - System.Threading.WaitHandle {System.ObjectDisposedException}

## Context
This is the API used to call:
GetSecretValueRequest request = new GetSecretValueRequest();
            request.SecretId = secretName;
            request.VersionStage = "AWSCURRENT" 
try
            {
                response = client.GetSecretValueAsync(request).Result;
            }

## Your Environment
* AWSSDK.Core version used:   AWSSDK.SecretsManager ,  Version - 3.3.101.31
* Service assembly and version used: 
* Operating System and version:  windows 10
* Visual Studio version: 2017
* Targeted .NET platform:  .Net core 2.1

## .NET Core Info
* .NET Core version used for development: >net core 2.1

**Comment by klaytaybai** [comment]
Hi @1ds14te050manoj , the issue is likely that you are not waiting for the result of the async method before trying to access it.  Please try using the async/await pattern or <async method>.GetAwaiter().GetResult()

**Comment by 1ds14te050manoj** [comment]
Hi @klaytaybai , which part of the code should i use .GetAwaiter().GetResult().  for you reference i have attached the code below. i have written this code to retrieve secret using secret manager of a database.

code:
using System;
using Amazon.Lambda.Core;
using Amazon;
using Amazon.SecretsManager;
using Amazon.SecretsManager.Model;
using System.IO;
using Newtonsoft.Json;
using MySql.Data.MySqlClient;

// Assembly attribute to enable the Lambda function's JSON input to be converted into a .NET class.
[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.Json.JsonSerializer))]

namespace SecretManager
{
    /// <summary>
    /// Class for SecretManagerValue
    /// </summary>
    /// 

    public class SecretManagerValue
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Engine { get; set; }
        public string Host { get; set; }
        public string Port { get; set; }
        public string DbClusterIdentifier { get; set; }
    }
    public class Function
    {

        /// <summary>
        /// A simple function that takes a string and does a ToUpper
        /// </summary>
        /// <param name="input"></param>
        /// <param name="context"></param>
        /// <returns></returns>
        /// 

        public string FunctionHandler(String input, ILambdaContext context)
        {
            var result = JsonConvert.DeserializeObject<SecretManagerValue>(GetSecret());
            LambdaLogger.Log("Generating Configuration....");
            var connString = GenerateConfiguration(result);
            LambdaLogger.Log("Check Connection....");
            var connectToDB = CheckConnectionMySQL(connString);
            if (connectToDB) { LambdaLogger.Log("Connection was succesfull."); }
            else { LambdaLogger.Log("Connection was unsuccesfull."); }
            return connString;
        }

        /// <summary>
        /// Generate ConnectionString
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static string GenerateConfiguration(SecretManagerValue value)
        {
            var configString = "Server={ServerName};Port=0000;Database={databaseName};Uid={UserName};Pwd={Password};Convert Zero Datetime=True;default command timeout=0;";

            var connectionString = configString.Replace("{ServerName}", value.Host)
                                                .Replace("{databaseName}", "Database_name")
                                                .Replace("{UserName}", value.UserName)
                                                .Replace("{Password}", value.Password);


            return connectionString;
        }

        public static bool CheckConnectionMySQL(string connString)
        {
            using (var conn = new MySqlConnection(connString))
            {
                try
                {
                    conn.Open();
                    return true;
                }
                catch (Exception ex)
                {
                    LambdaLogger.Log(ex.Message);
                    return false;
                }
            }
        }

        /// <summary>
        /// Get Secret from AWS secret manager
        /// </summary>
        /// <returns></returns>
        public static string GetSecret()
        {
           
            string secretName = "Yur_secret_name";
            string region = "us-west-1";
            string secret = "";

            MemoryStream memoryStream = new MemoryStream();


           

            AmazonSecretsManagerConfig smConfig = new AmazonSecretsManagerConfig
            {


                //RegionEndpoint = RegionEndpoint.USEast1,
                AuthenticationRegion = RegionEndpoint.USEast1.SystemName,
               ServiceURL = "https://your_service_URL"
            };
            IAmazonSecretsManager client = new AmazonSecretsManagerClient(smConfig);
            
            Console.WriteLine("Service URL: " + client.Config.ServiceURL);
            Console.WriteLine("Determined Service URL: " + client.Config.DetermineServiceURL());
            Console.WriteLine("Authentication Region: " + client.Config.AuthenticationRegion);

            GetSecretValueRequest request = new GetSecretValueRequest();
            request.SecretId = secretName;
            request.VersionStage = "AWSCURRENT"; // VersionStage defaults to AWSCURRENT if unspecified.

            GetSecretValueResponse response = null;

            // In this sample we only handle the specific exceptions for the 'GetSecretValue' API.
            // See https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_GetSecretValue.html   
            // We rethrow the exception by default.

            try
            {
                response = client.GetSecretValueAsync(request).Result;

            }
            catch (DecryptionFailureException e)
            {
                // Secrets Manager can't decrypt the protected secret text using the provided KMS key.
                // Deal with the exception here, and/or rethrow at your discretion.
                Console.WriteLine("DecryptionFailureException");
                Console.WriteLine(e.Message);
                throw;
            }
            catch (InternalServiceErrorException e)
            {
                // An error occurred on the server side.
                // Deal with the exception here, and/or rethrow at your discretion.
                Console.WriteLine("InternalServiceErrorException");
                Console.WriteLine(e.Message);
                throw;
            }
            catch (InvalidParameterException e)
            {
                // You provided an invalid value for a parameter.
                // Deal with the exception here, and/or rethrow at your discretion
                Console.WriteLine("InvalidParameterException");
                Console.WriteLine(e.Message);
                throw;
            }
            catch (InvalidRequestException e)
            {
                // You provided a parameter value that is not valid for the current state of the resource.
                // Deal with the exception here, and/or rethrow at your discretion.
                Console.WriteLine("InvalidRequestException");
                Console.WriteLine(e.Message);
                throw;
            }
            catch (ResourceNotFoundException e)
            {
                // We can't find the resource that you asked for.
                // Deal with the exception here, and/or rethrow at your discretion.
                Console.WriteLine("ResourceNotFoundException");
                Console.WriteLine(e.Message);
                throw;
            }
            catch (System.AggregateException ae)
            {
                // More than one of the above exceptions were triggered.
                // Deal with the exception here, and/or rethrow at your discretion.
                Console.WriteLine("AggregateException");
                Console.WriteLine(ae.Message);
                throw;
            }

            // Decrypts secret using the associated KMS CMK.
            // Depending on whether the secret is a string or binary, one of these fields will be populated.
            if (response.SecretString != null)
            {
                secret = response.SecretString;

                dynamic jsonSecret = JsonConvert.DeserializeObject(secret);
                LambdaLogger.Log("User Name: " + Convert.ToString(jsonSecret.username).Substring(0, 3) + "*****");
                LambdaLogger.Log("Password: " + Convert.ToString(jsonSecret.password).Substring(0, 3) + "*****");
            }
            else
            {
                memoryStream = response.SecretBinary;
                StreamReader reader = new StreamReader(memoryStream);
                string decodedBinarySecret = System.Text.Encoding.UTF8.GetString(Convert.FromBase64String(reader.ReadToEnd()));

                dynamic jsonSecret = JsonConvert.DeserializeObject(decodedBinarySecret);
                Console.WriteLine("User Name (decodedBinarySecret): " + Convert.ToString(jsonSecret.username).Substring(0, 3) + "*****");
                Console.WriteLine("Password (decodedBinarySecret): " + Convert.ToString(jsonSecret.password).Substring(0, 3) + "*****");
            }

            return secret;

            // Your code goes here.
        }
    }
}

**Comment by klaytaybai** [comment]
```
        // In this sample we only handle the specific exceptions for the 'GetSecretValue' API.
        // See https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_GetSecretValue.html   
        // We rethrow the exception by default.

        try
        {
            response = client.GetSecretValueAsync(request).Result; <-- This is where you need to handle the asynchronous method somehow.  If you want to learn more, there are a lot of articles online about async methods in C#

        }
        catch (DecryptionFailureException e)
        {
            // Secrets Manager can't decrypt the protected secret text using the provided KMS key.
            // Deal with the exception here, and/or rethrow at your discretion.
            Console.WriteLine("DecryptionFailureException");
            Console.WriteLine(e.Message);
            throw;
        }
```

If you still  have this error after fixing this, let us know so we can continue to investigate.

**Comment by 1ds14te050manoj** [comment]
Thank you so much @klaytaybai . I will work on it and will get back if i find a solution.

**Comment by 1ds14te050manoj** [comment]
Hi @klaytaybai  . I also used this basic code provided by AWS while creating the secret but i still get an error.
It's not an error. It shows successful but doesn't give me my secrets. Here's the error:
---------------------------------------------------------------------------------------------------------------
Response:
null

Request ID:
"53d94744-f103-4c09-937e-128eec610ee9"

Function Logs:
START RequestId: 53d94744-f103-4c09-937e-128eec610ee9 Version: $LATEST
END RequestId: 53d94744-f103-4c09-937e-128eec610ee9
REPORT RequestId: 53d94744-f103-4c09-937e-128eec610ee9	Duration: 60.44 ms	Billed Duration: 100 ms	Memory Size: 128 MB	Max Memory Used: 96 MB	
--------------------------------------------------------------------------------------------------------------

**And this is the code i used:**

// Use this code snippet in your app.
// If you need more information about configurations or implementing the sample code, visit the AWS docs:
// https://aws.amazon.com/developers/getting-started/nodejs/

// Load the AWS SDK
var AWS = require('aws-sdk'),
    region = "us-east-1",
    secretName = "my-secret-name",
    secret,
    decodedBinarySecret;

// Create a Secrets Manager client
var client = new AWS.SecretsManager({
    region: region
});

// In this sample we only handle the specific exceptions for the 'GetSecretValue' API.
// See https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_GetSecretValue.html
// We rethrow the exception by default.

client.getSecretValue({SecretId: secretName}, function(err, data) {
    if (err) {
        if (err.code === 'DecryptionFailureException')
            // Secrets Manager can't decrypt the protected secret text using the provided KMS key.
            // Deal with the exception here, and/or rethrow at your discretion.
            throw err;
        else if (err.code === 'InternalServiceErrorException')
            // An error occurred on the server side.
            // Deal with the exception here, and/or rethrow at your discretion.
            throw err;
        else if (err.code === 'InvalidParameterException')
            // You provided an invalid value for a parameter.
            // Deal with the exception here, and/or rethrow at your discretion.
            throw err;
        else if (err.code === 'InvalidRequestException')
            // You provided a parameter value that is not valid for the current state of the resource.
            // Deal with the exception here, and/or rethrow at your discretion.
            throw err;
        else if (err.code === 'ResourceNotFoundException')
            // We can't find the resource that you asked for.
            // Deal with the exception here, and/or rethrow at your discretion.
            throw err;
    }
    else {
        // Decrypts secret using the associated KMS CMK.
        // Depending on whether the secret is a string or binary, one of these fields will be populated.
        if ('SecretString' in data) {
            secret = data.SecretString;
        } else {
            let buff = new Buffer(data.SecretBinary, 'base64');
            decodedBinarySecret = buff.toString('ascii');
        }
    }
    
    // Your code goes here. 
});

**Comment by klaytaybai** [comment]
Hi @1ds14te050manoj, the above code snippet is for the JavaScript SDK, which is not supported in this repository (.NET).  If you are having an issue with the JS SDK, please open an issue in the appropriate one of their repos according to the major version of the SDK that you are using.  The V3 of the JS SDK is currently in developer preview, but it provides advantages over the previous versions because it is very modular and can create much smaller packages.  If you decide to open another issue with our JavaScript SDK or Premium Support, please include a log of the response from the server with any confidential details removed.

**Comment by 1ds14te050manoj** [comment]
Hi @klaytaybai i used GetAwaiter().GetResult(); as you suggested. But I am facing an error with exception called Operation Canceled Exception. I am attaching the error details below after this code snap. Please provide your guidance. Thank you.
                
  try
            {
                response = client.GetSecretValueAsync(request).  try
            {
                response = client.GetSecretValueAsync(request).GetAwaiter().GetResult();
            }
            }

Error Details:

The operation was canceled.: OperationCanceledException
at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
at SecretManager.Function.GetSecret() in C:\Users\m.kumar.chakladar\Desktop\MRDR Lambda Password\PasswordRetrieval\PasswordRetrieval\Function.cs:line 132
at SecretManager.Function.FunctionHandler(String input, ILambdaContext context) in C:\Users\m.kumar.chakladar\Desktop\MRDR Lambda Password\PasswordRetrieval\PasswordRetrieval\Function.cs:line 44
at lambda_method(Closure , Stream , Stream , LambdaContextInternal )

**Comment by Kayeryan1** [comment]
Did anyone ever identify the cause of the OperationCanceledException?

**Comment by CraigLager** [comment]
Having this exact issue with SecretsManager call in Lambda.

`response = client.GetSecretValueAsync(request).Result;` is provided by AWS sample code and I double checked how `.Result` works: https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task-1.result?view=net-5.0

> Accessing the property's get accessor blocks the calling thread until the asynchronous operation is complete; it is equivalent to calling the Wait method.

I'm not getting this issue when running the app via XUnit
