### ISSUE TITLE
ARMV-64 bit support issue with Unity 2019.1.10f1

### ISSUE THREAD

**Issue by SankarGanesh82** [aws/aws-sdk-net#1425]
Hello,
Tried everything and didn't worked. We are using Unity 2019.1.12f1 and Unity AWSSDK version 3.3.602.0. Working fine in the Editor and got ERROR in Android. Quick solid solution needed. Thanks in advance.

10-11 18:23:32.046 5349 5363 I Unity : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 48)
10-11 18:23:32.046 5349 5363 I Unity :
10-11 18:23:32.114 5349 5363 E Unity : ArgumentException: Object of type 'System.Object[]' cannot be converted to type 'UnityEngine.AndroidJavaObject[]'.
10-11 18:23:32.114 5349 5363 E Unity : at System.RuntimeType.CheckValue (System.Object value, System.Reflection.Binder binder, System.Globalization.CultureInfo culture, System.Reflection.BindingFlags invokeAttr) [0x00000] in <00000000000000000000000000000000>:0
10-11 18:23:32.114 5349 5363 E Unity : at System.Reflection.MonoMethod.ConvertValues (System.Reflection.Binder binder, System.Object[] args, System.Reflection.ParameterInfo[] pinfo, System.Globalization.CultureInfo culture, System.Reflection.BindingFlags invokeAttr) [0x00000] in <00000000000000000000000000000000>:0
10-11 18:23:32.114 5349 5363 E Unity : at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <00000000000000000000000000000000>:0
10-11 18:23:32.114 5349 5363 E Unity : at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <00000000000000000000000000000000>:0
10-11 18:23:32.114 5349 5363 E Unity : a
10-11 18:23:32.115 5349 5363 I Unity : Attached unity initializer to Test
10-11 18:23:32.115 5349 5363 I Unity : UnityEngine.Logger:Log(LogType, Object)

**Comment by klaytaybai** [comment]
Hi @SankarGanesh82, I saw you posted on https://github.com/aws/aws-sdk-net/issues/1371.  We highly recommend following Matteo's advice in that issue.
