### ISSUE TITLE
TryParseAmazonS3Uri(string) may throw System.UriFormatException if invoked with invalid URI string parameter

### ISSUE THREAD

**Issue by OlegBoulanov** [aws/aws-sdk-net#1426]
Just look at your code: https://github.com/aws/aws-sdk-net/blob/befc92152cfdd9c57f59f2304bd54b535f81d76b/sdk/src/Services/S3/Custom/Util/AmazonS3Uri.cs#L166

**Comment by klaytaybai** [comment]
Hi @OlegBoulanov, can you please be more specific about what you are testing or looking for here? I was able to get this code to work.

**Comment by OlegBoulanov** [comment]
NetStandard 2.1/Core 3.0

code:

`if(AmazonS3Uri.TryParseAmazonS3Uri("invalid-uri", out amazonS3Uri)) { /* do something */ }`

it throws System.UriFormatException

while TryXXX assumes it should return false, and not throw

**Comment by normj** [comment]
I agree TryParseAmazonS3Uri should not throw an exception. That is counter intuitive to the pattern for Try methods in .NET.

**Comment by normj** [comment]
Your PR was that fixes this was released in the latest version of the SDK.
