### ISSUE TITLE
Add 'Play Services Resolver' to unity plugins

### ISSUE THREAD

**Issue by mores** [aws/aws-sdk-net#1428]
##  Expected Behavior
After importing AWSSDK.SimpleNotificationService.3.3.101.72.unitypackage - android build should complete without error. If any external jars are needed they should automatically be downloaded - perhaps by utilizing https://github.com/googlesamples/unity-jar-resolver

## Current Behavior
`mples\AWSsns\Temp\gradleOut\src\main\java\com\amazonaws\unity\AWSUnityGCMWrapper.java:11: error: package com.google.android.gms.gcm does not exist
import com.google.android.gms.gcm.GoogleCloudMessaging;
                                 ^
C:\Users\steve\Documents\unity-examples\AWSsns\Temp\gradleOut\src\main\java\com\amazonaws\unity\GCMBroadcastReceiver.java:7: error: package android.support.v4.content does not exist
import android.support.v4.content.WakefulBroadcastReceiver;
                                 ^
C:\Users\steve\Documents\unity-examples\AWSsns\Temp\gradleOut\src\main\java\com\amazonaws\unity\GCMBroadcastReceiver.java:9: error: cannot find symbol
public class GCMBroadcastReceiver extends WakefulBroadcastReceiver {
                                          ^
  symbol: class WakefulBroadcastReceiver
C:\Users\steve\Documents\unity-examples\AWSsns\Temp\gradleOut\src\main\java\com\amazonaws\unity\Utils.java:9: error: package android.support.v4.app does not exist
import android.support.v4.app.NotificationCompat;
                             ^
C:\Users\steve\Documents\unity-examples\AWSsns\Temp\gradleOut\src\main\java\com\amazonaws\unity\AWSUnityGCMWrapper.java:26: error: cannot find symbol
			GoogleCloudMessaging gcm = GoogleCloudMessaging
			^
  symbol:   class GoogleCloudMessaging
  location: class AWSUnityGCMWrapper
C:\Users\steve\Documents\unity-examples\AWSsns\Temp\gradleOut\src\main\java\com\amazonaws\unity\AWSUnityGCMWrapper.java:26: error: cannot find symbol
			GoogleCloudMessaging gcm = GoogleCloudMessaging
			                           ^
  symbol:   variable GoogleCloudMessaging
  location: class AWSUnityGCMWrapper
C:\Users\steve\Documents\unity-examples\AWSsns\Temp\gradleOut\src\main\java\com\amazonaws\unity\AWSUnityGCMWrapper.java:41: error: cannot find symbol
			GoogleCloudMessaging gcm = GoogleCloudMessaging
			^
  symbol:   class GoogleCloudMessaging
  location: class AWSUnityGCMWrapper
C:\Users\steve\Documents\unity-examples\AWSsns\Temp\gradleOut\src\main\java\com\amazonaws\unity\AWSUnityGCMWrapper.java:41: error: cannot find symbol
			GoogleCloudMessaging gcm = GoogleCloudMessaging
			                           ^
  symbol:   variable GoogleCloudMessaging
  location: class AWSUnityGCMWrapper
C:\Users\steve\Documents\unity-examples\AWSsns\Temp\gradleOut\src\main\java\com\amazonaws\unity\GCMBroadcastReceiver.java:11: error: method does not override or implement a method from a supertype
	@Override
	^
C:\Users\steve\Documents\unity-examples\AWSsns\Temp\gradleOut\src\main\java\com\amazonaws\unity\GCMBroadcastReceiver.java:17: error: cannot find symbol
		startWakefulService(context, (intent.setComponent(comp)));
		^
  symbol:   method startWakefulService(Context,Intent)
  location: class GCMBroadcastReceiver
C:\Users\steve\Documents\unity-examples\AWSsns\Temp\gradleOut\src\main\java\com\amazonaws\unity\GCMBroadcastReceiver.java:18: error: cannot find symbol
		setResultCode(Activity.RESULT_OK);
		^
  symbol:   method setResultCode(int)
  location: class GCMBroadcastReceiver
C:\Users\steve\Documents\unity-examples\AWSsns\Temp\gradleOut\src\main\java\com\amazonaws\unity\GCMIntentService.java:40: error: cannot find symbol
			GCMBroadcastReceiver.completeWakefulIntent(intent);
			                    ^
  symbol:   method completeWakefulIntent(Intent)
  location: class GCMBroadcastReceiver
C:\Users\steve\Documents\unity-examples\AWSsns\Temp\gradleOut\src\main\java\com\amazonaws\unity\Utils.java:25: error: package NotificationCompat does not exist
		NotificationCompat.Builder builder = new NotificationCompat.Builder(
		                  ^
C:\Users\steve\Documents\unity-examples\AWSsns\Temp\gradleOut\src\main\java\com\amazonaws\unity\Utils.java:25: error: package NotificationCompat does not exist
		NotificationCompat.Builder builder = new NotificationCompat.Builder(
		                                                           ^
Note: C:\Users\steve\Documents\unity-examples\AWSsns\Temp\gradleOut\src\main\java\com\amazonaws\unity\AWSUnityGCMWrapper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
14 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 34s
]
stdout[
Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details
:preBuild UP-TO-DATE
:preReleaseBuild
:compileReleaseAidl
:compileReleaseRenderscript
:checkReleaseManifest
:generateReleaseBuildConfig
:prepareLintJar
:generateReleaseResValues
:generateReleaseResources
:mergeReleaseResources
:createReleaseCompatibleScreenManifests
:processReleaseManifest
:splitsDiscoveryTaskRelease
:processReleaseResources
:generateReleaseSources
:javaPreCompileRelease
:compileReleaseJavaWithJavac FAILED
14 actionable tasks: 14 executed
]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action`1 progress, System.String error)
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1 progress)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1 progress)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)`

## Possible Solution
Play Services Resolver for Unity - https://github.com/googlesamples/unity-jar-resolver

## Steps to Reproduce (for bugs)
Start a brand new unity project - import AWSSDK.SimpleNotificationService.3.3.101.72.unitypackage - build for Android

## Context
Trying to add SNS to Unity App

## Your Environment
unity 2018.2.18f1

**Comment by klaytaybai** [comment]
Work on Unity-related PRs are paused at this time.
 We encourage our users to use the .NET Standard 2.0 version of the AWS SDK for .NET which can be downloaded from NuGet or, as a .zip file, [here](https://sdk-for-net.amazonwebservices.com/latest/v3/aws-sdk-netstandard2.0.zip).

You can read more about using .NET Standard 2.0 for Unity [here](https://aws.amazon.com/blogs/developer/referencing-the-aws-sdk-for-net-standard-2-0-from-unity-xamarin-or-uwp/).

 The downloads of the last supported version of the AWS Mobile SDK for Unity, as well as its source code, will continue to be available to customers. However the AWS Mobile SDK for Unity will no longer be officially supported by the AWS SDK for .NET team.

**Comment by mores** [comment]
Where is the source repository for com.amazonaws.unity.AWSUnityGCMWrapper ?

I would like to make a fork or pull request - it currently uses GoogleCloudMessaging and I would like to change it to FirebaseMessaging.

**Comment by klaytaybai** [comment]
Hi @mores, thank you for your interest in contributing, but this code is currently being removed anyway.  We are not accepting pull requests on it. We are asking users to transition to the AWS SDK for .NET targeting .NET Standard 2.0 for any Unity projects.
