### ISSUE TITLE
Missing AWS Console Project

### ISSUE THREAD

**Issue by Fight-Shrub** [aws/aws-sdk-net#1430]
I downloaded the AWS Toolkit for Visual Studio 2017 to complete [a tutorial that includes creating a new project as a step](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/CodeSamples.DotNet.html). 
It says I should have a new project type called "AWS Empty Project" under Visual C# -> AWS but it is not there for me. I did get the new category called AWS but it only includes AWS CloudFormation Project and AWS Lambda Function Project.

Why am I missing this project type? Are there any workarounds?
![AWS Toolkit](https://user-images.githubusercontent.com/56561935/66778635-49150780-ee9a-11e9-9885-72375ff591c6.PNG)

**Comment by klaytaybai** [comment]
Hi @Fight-Shrub, I'm not sure why this was possibly removed.  Note that you may have more projects in the Visual C# -> AWS Lambda group.   I'm including a sample of the AWS Console Project you hoped to find.
[AwsConsoleApp2.zip](https://github.com/aws/aws-sdk-net/files/3731134/AwsConsoleApp2.zip)

Please recreate this issue in https://github.com/aws/aws-toolkit-visual-studio/issues if you want to see more done with it.  This is the new home for AWS Toolkit for Visual Studio issues.
