### ISSUE TITLE
Unity 2019 Android crash: library "Crypt32" not found

### ISSUE THREAD

**Issue by bartofzo** [aws/aws-sdk-net#1431]
I'm trying to run a Unity project on an Android device with the AWS .net SDK.

But when using the Cognito Identity service, the app crashes with the following message logged:

```
10-15 14:39:58.907 12657 12765 E Unity   : Unable to find Crypt32
10-15 14:39:58.908 12657 12765 W Unity   : Plugins: Couldn't open Crypt32, error: dlopen failed: library "Crypt32" not found
```

I've cloned this repository and built the .NET Standard solution. Then added the neccessary DLL's to my project. 

Everything works fine inside the Unity editor and it also works for iOS builds. However on Android the app crashes.

The error occurs for both IL2CPP and Mono backends on Android. Also occurs on .NET standard 2.0 and .NET 4.x API compatibility levels.

Unity version is 2019.2.9f1

Thanks.

**Comment by klaytaybai** [comment]
What is the Android version?

**Comment by bartofzo** [comment]
Android 9 on a Samsung Galaxy S8 (SM-G950F)

**Comment by bartofzo** [comment]
Is there anyone using the SDK with Unity 2019 that doesn't have this problem? Wondering if it's as simple as including the DLL with the project. Strange that it does work on iOS and MacOS.

**Comment by bartofzo** [comment]
Found out the crash was not due to this error. Although the message still gets logged, cognito and lambda seem te work correctly, so I'm assuming it's harmless.

**Comment by advantage-software** [comment]
> Found out the crash was not due to this error. Although the message still gets logged, cognito and lambda seem te work correctly, so I'm assuming it's harmless.

What was it due to?
