### ISSUE TITLE
Make default model constructors take required params or at least improve default constructor docs and required property docs

### ISSUE THREAD

**Issue by mishrsud** [aws/aws-sdk-net#1433]
When I create a MessageAttributeValue, the default constructor has no parameters, yet the property DataType is required. This isn't discoverable until one actually publishes a message with attributes only to see a validation exception that points to a missing data type.

## Expected Behavior

I would expect the constructor to ask for all required data before attempting to create an instance. E.g. 
var messageAttributeValue = new MessageAttributeValue(stringValue: "value", dataType: "String");
## Context

I couldn't catch the described issue with a unit test and discovered while looking at application logs. 

## Your Environment

* AWSSDK.Core version used: 3
* Targeted .NET platform: netcore21

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
Thanks for the feedback on this.  I'm going to change the title of the issue to make it more generic
