### ISSUE TITLE
Unable to install this extension for Visual studio 2019 community edition

### ISSUE THREAD

**Issue by mgurjar-dev** [aws/aws-sdk-net#1437]
Unable to install this extension for Visual studio 2019(version 16.3.1) community edition on windows 10

## Expected Behavior
It should be install on described machine for VS

## Current Behavior
Getting error:VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.

## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
Hi @mgurjar-dev, can you please verify that you were installing the correct download?  There is one version of the download for [Visual Studio 2017 and 2019](https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.AWSToolkitforVisualStudio2017) and another installer linked in that same page for Visual Studio 2013 and 2015.

**Comment by mgurjar-dev** [comment]
Hi @klaytaybai , yes, i confirm that i am trying to download and install the same AWS extension toolkit. As work around i am using older version for Visual studio 2015. Please let me know if you have fix for Visual studio 2019. Thank you.

**Comment by klaytaybai** [comment]
I'm going to close this issue for now because we haven't received widespread complaints about this problem, which I would expect to have seen if it was a common problem.  Please try again with the newest versions.  If you are still having an issue, please open your issue in https://github.com/aws/aws-toolkit-visual-studio/issues .
