### ISSUE TITLE
DynamoDBv2 AttributeValue.IsMSet returns false when the M setter is set to Dictionary<string, AttributeValue> empty

### ISSUE THREAD

**Issue by radleta** [aws/aws-sdk-net#1439]
The `AttributeValue.IsMSet` returns false when the M setter is set to `Dictionary<string, AttributeValue>` empty.

## Expected Behavior

Excepted `AttributeValue.IsMSet` to be true when M is set to an empty `Dictionary<string, AttributeValue>`.

-- AND --

Expected `AttributeValue.IsMSet` when standard JSON deserialization of the class happens and an empty `Dictionary<string, AttributeValue>` is set to the M property.

## Current Behavior

Excepted `AttributeValue.IsMSet` returns false when M is set to an empty `Dictionary<string, AttributeValue>`.

## Possible Solution

Change the logic for the setter for M and then update `IsMSet` to match the behavior.

It appears that `IsMSet` relies on `GetIsSet` and `SetIsSet`, however, this logic is not called when the M setter is called.

It appears the `GetIsSet` and `SetIsSet` expect `AlwaysSendDictionary<TKey, TValue>` to be used however this is unexpected behavior and no clear pattern or practice for developers to know an inherited type must be used for an empty dictionary.

## Steps to Reproduce (for bugs)

Two completely different ways this can occur.

1. Simple assignment of the M by use of the setter

```
var attr = new AttributeValue();
attr.M = new Dictionary<string, AttributeValue>();
if (!attr.IsMSet) {
  throw new ApplicationException("Bug here!")
}
```

2. JSON Deserialization

```
var attr = JsonConvert.DeserializeObject<AttributeValue>("{ \"M\": {} }");
if (!attr.IsMSet) {
  throw new ApplicationException("Bug here!")
}
```

## Context

I was working on building a .NET Core Lambda Function to handle DynamoDBv2 streams. The case arose when I had a .NET object with no properties set in a List. This caused the `AttributeValue` to be deserialized and the M to be set to an empty `Dictionary<string, AttributeValue>`. This, in turn, caused the Table.FromAttributeMap() to throw a NullReferenceException.

## Your Environment
* AWSSDK.Core version used: See below
* Service assembly and version used: See below
* Operating System and version: WIN 10 and Amazon Linux
* Visual Studio version: VS 2019
* Targeted .NET platform: netcoreapp2.1

## .NET Core Info
* .NET Core version used for development: 2.1
* .NET Core version installed in the environment where application runs: 2.1

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <Configurations>Debug;Release;Release.Aws</Configurations>
  </PropertyGroup>

  <ItemGroup>
    
    <PackageReference Include="Amazon.Lambda.Core" Version="1.1.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.Json" Version="1.7.0" />
    <PackageReference Include="Amazon.Lambda.DynamoDBEvents" Version="1.1.0" />

    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.3.101.80" />
    <PackageReference Include="Elasticsearch.Net" Version="6.8.3" />
    <PackageReference Include="NEST" Version="6.8.3" />
    <PackageReference Include="NETStandard.Library" Version="2.0.3" />
    <PackageReference Include="System.IO.Compression" Version="4.3.0" />
    
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Amazon.Lambda.Tools" Version="1.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Elasticsearch.Net.Aws\Elasticsearch.Net.Aws.csproj" />
  </ItemGroup>

</Project>
```

**Comment by klaytaybai** [comment]
Thanks for raising attention to this.  We have received similar feedback in the past, and we are discussing how to best work through this issue without causing any backwards compatibility problems.  If you could tell us more about your use case, we would love to hear.

**Comment by ashishdhingra** [comment]
https://github.com/aws/aws-lambda-dotnet/issues/538

**Comment by bjorg** [comment]
How much discussion does such an obvious defect require? Just add a new property called `IsMSetAndThisTimeWeMeanIt` and mark the old property as obsolete, but keep it for backwards compat.
