### ISSUE TITLE
Amazon.Runtime.Internal.HttpErrorResponseException on login attempt, timeout problem

### ISSUE THREAD

**Issue by daniel-rck** [aws/aws-sdk-net#1441]
## EDIT: See https://github.com/aws/aws-sdk-net/issues/1441#issuecomment-553829515 for updated Error description.

I'm using the `aws-sdk-net-extensions-cognito` package this way:

    var authFlowResponse = await user.StartWithSrpAuthAsync(new InitiateSrpAuthRequest()
    {
        Password = password
    }).ConfigureAwait(false);

## Expected Behavior
Returning a valid AuthFlowRewsponse.

## Current Behavior
Sometimes I catch an `Amazon.Runtime.Internal.HttpErrorResponseException`, sometimes everything works.
The Exception is thrown in https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Pipeline/HttpHandler/_mobile/HttpRequestMessageFactory.cs`, Line 39

## Context
I'ts only possible to give client context information, the backend aws part is done by another company.

## Your Environment

* AWSSDK.Core version used: 3.3.103.56
* AWSSDK.CognitoIdentity version used: 3.3.100.91
* AWSSDK.CognitoIdentityProvider version used: 3.3.103.10
* Operating System and version: Windows 10 Pro v1903
* Visual Studio version: 16.4.0 Preview 2.0
* Targeted .NET platform: .Net Core 3.1.0-preview1

**Comment by klaytaybai** [comment]
Are you able to provide the inner exception or status code?

**Comment by Daniel-NP** [comment]
This is probably the same problem, this time running on Android:

> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
  at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync (System.Threading.CancellationToken cancellationToken) [0x000f7] in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_mobile\HttpRequestMessageFactory.cs:539 
  at Amazon.Runtime.Internal.HttpHandler`1[TRequestContent].InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x00233] in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:175 

>11-05 09:32:13.374 I/mono-stdout( 5238): Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.  at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x00031] in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\Unmarshaller.cs:85 
  at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x0002d] in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:99 

>11-05 09:32:13.375 I/mono-stdout( 5238):   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync (System.Threading.CancellationToken cancellationToken) [0x000f7] in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_mobile\HttpRequestMessageFactory.cs:539 
11-05 09:32:13.376 I/mono-stdout( 5238):   at Amazon.Runtime.Internal.HttpHandler`1[TRequestContent].InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x00233] in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:175 
11-05 09:32:13.377 I/mono-stdout( 5238):   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x00031] in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\Unmarshaller.cs:85 
11-05 09:32:13.377 I/mono-stdout( 5238):   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x0002d] in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:99 

It looks like the login would be wrong, but after a few tries it works.

**Comment by Daniel-NP** [comment]
Another Stacktrace:

    {
    "ErrorType": 2,
    "ErrorCode": "NotAuthorizedException",
    "RequestId": "98341539-8733-4728-ab0a-8288204c53be",
    "StatusCode": 400,
    "Message": "Incorrect username or password.",
    "Data": {},
    "InnerException": {
      "Response": {
        "StatusCode": 400,
        "IsSuccessStatusCode": false,
        "ContentType": "application/x-amz-json-1.1",
        "ContentLength": 79,
        "ResponseBody": {}
      },
      "Message": "Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.",
      "Data": {},
      "InnerException": null,
      "StackTrace": "  at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync (System.Threading.CancellationToken cancellationToken) <0x3ef5968 + 0x001a6> in <4d5f8cc54bcb4b2f94c52f14e89fb6fb>:0 \n  at Amazon.Runtime.Internal.HttpHandler`1[TRequestContent].InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) <0x3f73c78 + 0x003e2> in <4d5f8cc54bcb4b2f94c52f14e89fb6fb>:0 \n  at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) <0x3f65f70 + 0x000e8> in <4d5f8cc54bcb4b2f94c52f14e89fb6fb>:0 \n  at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) <0x3f65758 + 0x000de> in <4d5f8cc54bcb4b2f94c52f14e89fb6fb>:0 ",
      "Source": "mscorlib",
      "HResult": -2146233088
    },
    "StackTrace": "  at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException (Amazon.Runtime.IExecutionContext executionContext, Amazon.Runtime.Internal.HttpErrorResponseException exception) <0x3f73250 + 0x00270> in <4d5f8cc54bcb4b2f94c52f14e89fb6fb>:0 \n  at Amazon.Runtime.Internal.ExceptionHandler`1[T].Handle (Amazon.Runtime.IExecutionContext executionContext, System.Exception exception) <0x3f72f70 + 0x00016> in <4d5f8cc54bcb4b2f94c52f14e89fb6fb>:0 \n  at Amazon.Runtime.Internal.ErrorHandler.ProcessException (Amazon.Runtime.IExecutionContext executionContext, System.Exception exception) <0x3f72678 + 0x000ba> in <4d5f8cc54bcb4b2f94c52f14e89fb6fb>:0 \n  at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) <0x3f65758 + 0x00110> in <4d5f8cc54bcb4b2f94c52f14e89fb6fb>:0 \n  at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) <0x3f54fb8 + 0x000ec> in <4d5f8cc54bcb4b2f94c52f14e89fb6fb>:0 \n  at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) <0x3f64ef0 + 0x00126> in <4d5f8cc54bcb4b2f94c52f14e89fb6fb>:0 \n  at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) <0x3f64ef0 + 0x0015c> in <4d5f8cc54bcb4b2f94c52f14e89fb6fb>:0 \n  at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) <0x3f697e0 + 0x0025e> in <4d5f8cc54bcb4b2f94c52f14e89fb6fb>:0 \n  at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) <0x3f68c60 + 0x0012c> in <4d5f8cc54bcb4b2f94c52f14e89fb6fb>:0 \n  at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) <0x3f68c60 + 0x00288> in <4d5f8cc54bcb4b2f94c52f14e89fb6fb>:0 \n  at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) <0x3f54fb8 + 0x000ec> in <4d5f8cc54bcb4b2f94c52f14e89fb6fb>:0 \n  at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) <0x3f54fb8 + 0x000ec> in <4d5f8cc54bcb4b2f94c52f14e89fb6fb>:0 \n  at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) <0x3f548b0 + 0x00100> in <4d5f8cc54bcb4b2f94c52f14e89fb6fb>:0 \n  at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) <0x3f54030 + 0x0013c> in <4d5f8cc54bcb4b2f94c52f14e89fb6fb>:0 \n  at Amazon.Extensions.CognitoAuthentication.CognitoUser.StartWithSrpAuthAsync (Amazon.Extensions.CognitoAuthentication.InitiateSrpAuthRequest srpRequest) <0x3e4bb80 + 0x002f4> in <bfb077a8c7a341ef900f115d002a1c51>:0 \n  at Appocenna.Client.Core.Extensions.CognitoExtensions.SendLoginRequestAsync (Amazon.Extensions.CognitoAuthentication.CognitoUser user, System.String password) <0x3e3e718 + 0x000f8> in <38b18d364271467bb5549f2b92dc635c>:0 \n  at Appocenna.Client.Core.Services.AmazonAuthenticationService.TryLoginAsync (System.String email, System.String password) <0x3c86b98 + 0x00146> in <38b18d364271467bb5549f2b92dc635c>:0 ",
    "Source": "mscorlib",
    "HResult": -2146233088
  }

**Comment by Daniel-NP** [comment]
Maybe it's a performance thing... Made a little logging output:

    WASM: StartWithSrpAuthAsync...
    WASM: StartWithSrpAuthAsync AuthenticationHelper.CreateAaTuple completed after 32,1s
    WASM: StartWithSrpAuthAsync CreateSrpAuthRequest completed after 32,2s
    WASM: StartWithSrpAuthAsync UpdateUsernameAndSecretHash completed after 34,0s
    WASM: StartWithSrpAuthAsync CreateSrpPasswordVerifierAuthRequest completed after 74,0

> POST https://cognito-idp.eu-central-1.amazonaws.com/ [400]

Is it a time-critical problem where the difference betwen the SrpAuthRequest and SrpPasswordVerifierAuthRequest is too long?

**Comment by Daniel-NP** [comment]
I created a small sample-repo for testing: https://github.com/Daniel-NP/AwsCognitoExample
Moreover I added comments in https://github.com/Daniel-NP/AwsCognitoExample/blob/master/AwsCognitoExample.csproj to clarify which versions are working.

**Comment by ashishdhingra** [comment]
Hi @daniel-rck, 

Good afternoon.

I was going through the issue backlog and came across this issue. Please confirm if this is still an issue.

Thanks
Ashish

**Comment by daniel-rck** [comment]
Unfortunately I no longer have access to my production service, the given sample project still has the described problem. Maybe you can try it with real credentials on a working cognito backend. Sorry.

**Comment by NGL321** [comment]
Since this is no longer an issue you are struggling with, I will close this issue. If anyone else experiences it with the latest release, please feel free to reopen the issue

😸
