### ISSUE TITLE
The CreateRepositoryRequest class is missing the RepositoryPolicyText property

### ISSUE THREAD

**Issue by Halleymedia** [aws/aws-sdk-net#1442]
Hello, I'm using the ECR client, latest version (v3.3.102.2 as of today).
The class `Amazon.ECR.Model.CreateRepositoryRequest` does not contain the `RepositoryPolicyText` which is documented [here, on the CloudFormation guide](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html).

![image](https://user-images.githubusercontent.com/56730966/67958221-1c315600-fbf7-11e9-899d-74a4885cf203.png)

Is this intended?
Thanks.

EDIT: I know I can set the policy by invoking `SetRepositoryPolicyAsync` right after che repository creation but I wonder If you could still add the `RepositoryPolicyText` property for consistency with CouldFormation. All of the other request classes I've used so far seem to be consistent.

**Comment by klaytaybai** [comment]
Thanks for reporting this.  We'll reach out to the ECR team to see if we can get this added.

**Comment by ashishdhingra** [comment]
Hi @Halleymedia,

Good afternoon.

I was going through backlog and came across this issue. This does not appear to be an issue. Kindly refer the [CreateRepositoryRequest](https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_CreateRepository.html) service API operation. It also does not define `RepositoryPolicyText` property. On the similar lines, model class [CreateRepositoryRequest](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/ECR/Generated/Model/CreateRepositoryRequest.cs) in AWS SDK for .NET does not define any such property.

The guide you are referring to is for the CloudFormation template. There might not be one-to-one mapping between CloudFormation and service model classes. AWS .NET SDK model classes are based on service API model classes.

For you scenario, you might want to use [SetRepositoryPolicyRequest](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/ECR/Generated/Model/SetRepositoryPolicyRequest.cs) class with [AmazonECRClient.SetRepositoryPolicyAsync](https://github.com/aws/aws-sdk-net/blob/ed8e148abebbd88a8313eaf47ea207c12bcbd531/sdk/src/Services/ECR/Generated/_netstandard/AmazonECRClient.cs#L1777) method.

Hope this helps.

Thanks,
Ashish
