### ISSUE TITLE
Add support to returning the new object as the result of a Save operation

### ISSUE THREAD

**Issue by xavicosta** [aws/aws-sdk-net#1454]
Add support to returning the new object as the result of a Save operation.

**Comment by klaytaybai** [comment]
Hi @xavicosta, are you referring to the DynamoDB save operation?  Why would you need the object returned if you are passing it as a parameter to the save operation?

**Comment by xavicosta** [comment]
Sorry, @klaytaybai,

I have been really busy so did not have time to reply. 

To your questions:

> are you referring to the DynamoDB save operation?
SaveAsync and ExecuteBatchWriteAsync

> Why would you need the object returned if you are passing it as a parameter to the save operation?
First example I can think of would be versioning. If it is on, then VersionNumber property needs to be increased manually rather than getting the attribute value back from db as part of the save operation.
