### ISSUE TITLE
How to add an Intent to a Bot and Build/Publish an Intent using .NET Lex SDK

### ISSUE THREAD

**Issue by vinaykumar0787** [aws/aws-sdk-net#1456]
How to add an Intent to a Bot and Build/Publish an Intent using .NET Lex SDK?

I have been able to Create Intents, Slots and other basic Entities using the Lex SDK, but they are not usable until I go to Lex Console and add them to a Bot manually, and build/publish them. I wanted a full end to end solution to do all the operations dynamically using my own back-end. Is it possible?

Referring: https://docs.aws.amazon.com/lex/latest/dg/API_PutIntent.html

**Comment by klaytaybai** [comment]
Hi @vinaykumar0787, I think you can use PutIntentRequest and then reference the intents in PutBotRequest.  Could you please try this and let us know if it works for you? https://github.com/aws/aws-sdk-net/blob/08abbbd5b4072a932e841f4491790f8520ea2ef1/sdk/src/Services/LexModelBuildingService/Generated/Model/PutBotRequest.cs#L288

**Comment by vinaykumar0787** [comment]
@klaytaybai Thanks, I was able to Put Intent inside Bot with your suggestion, and also build it.
Could you also help with which method could be used in publishing the Bot?

**Comment by klaytaybai** [comment]
https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/LexModelBuildingService/Generated/Model/CreateBotVersionRequest.cs

Sometimes the AWS CLI has better documentation on requests that are also implemented in the .NET SDK: https://docs.aws.amazon.com/lex/latest/dg/gs-cli-publish-bot.html
