### ISSUE TITLE
Message.IsMessageSignatureValid throws an exception

### ISSUE THREAD

**Issue by raghumirajkar** [aws/aws-sdk-net#1458]
Hi,

We use Amazon AWS.SimplenotificationService nuget provided signature validation for ConfirmSubscription message validation.
To get the received message, we read the body content with UTF-8 encoding and detectEncodingFromByteOrderMarks flag is set to true. Then use the following - 
var decoded = WebUtility.UrlDecode(encodedJson);
var message = Message.ParseMessage(decoded);
so calling the below api to verify the signature -
message.IsMessageSignatureValid()
throws an exception 
The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.

This was working all this while but is failing suddenly. Could you please take a look what is going wrong?

## Expected Behavior
Signature validation for SNS message should pass using the API IsMessageSignatureValid

## Current Behavior
Using IsMessageSignatureValidation() throws an exception 
The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.

## Steps to Reproduce (for bugs)
Read the body content with UTF-8 encoding and detectEncodingFromByteOrderMarks flag is set to true. Then use the following - 
var decoded = WebUtility.UrlDecode(encodedJson);
var message = Message.ParseMessage(decoded);
so calling the below apito verify the signature -
message.IsMessageSignatureValid()

## Your Environment

* AWSSDK.Core version used: 3.3.101.57
* Service assembly and version used: 
* Operating System and version: Windows 10
* Visual Studio version: 15.9.3
* Targeted .NET platform: .Net framework version 4.7.03190 (.Net core app)

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by raghumirajkar** [comment]
Update - 
Convert.FromBase64String(amazonSnsMessage.Signature) throws an exception
Invalid length for a Base-64 char array or string.
Basically, the signature returned from amazon sns is not a valid base64 encoded string

**Comment by raghumirajkar** [comment]
Can someone look into the issue please?

**Comment by ashishdhingra** [comment]
Hi @raghumirajkar,

Good morning.

I was going through issue backlog and came across this one. Please let me know if this is still an issue. If yes, request you to share basic code solution which is giving you the above error.

Thanks,
Ashish
