### ISSUE TITLE
Create `MemoryStream` using the correct overload

### ISSUE THREAD

**Issue by maghis** [aws/aws-sdk-net#1459]
Reading records from Kinesis forces call to `MemoryStream.GetBuffer()` that potentially copies memory.

Calling this overload, sets the `MemoryStream` to writable and non-exposable:
https://github.com/aws/aws-sdk-net/blob/dd8d1fb91763f378cec2e162c03e881cc2fd83e9/sdk/src/Core/Amazon.Runtime/Internal/Transform/SimpleTypeUnmarshaller.cs#L493

It would be a lot better to create it as non-writable and exposable using this overload:
https://github.com/dotnet/corefx/blob/e99ec129cfd594d53f4390bf97d1d736cff6f860/src/Common/src/CoreLib/System/IO/MemoryStream.cs#L86

Instantiating it the following way will allow calls to `TryGetBuffer` to get a `ArraySegment<byte>`.
```
new MemoryStream(buffer, 0, buffer.Length, false, true);
```

It would be even better to switch from `MemoryStream` to `ReadOnlyMemory<byte>` but that would break existing consumers.

**Comment by klaytaybai** [comment]
Thanks for the feedback on this
