### ISSUE TITLE
Type issues in Amazon.DynamoDBv2.Model.AttributeValue

### ISSUE THREAD

**Issue by amattie** [aws/aws-sdk-net#146]
AttributeValue's N type is string, but according to the (dynamodb-2012-08-10.normal.json)[https://github.com/aws/aws-sdk-net/blob/master/ServiceModels/dynamodb-2012-08-10.normal.json] service model, it's a "NumberAttributeValue" and thus I think should be a double? or something in AttributeValue.

Also, AttributeValue's constructor only takes a string or List<string>. It'd be easier to use in practice if it accepted the other acceptable attribute types.

**Comment by jimfl** [comment]
Added to https://github.com/aws/aws-sdk-net/blob/master/FEATURE_REQUESTS.md
