### ISSUE TITLE
Remove all environment variables and layers from a lambda function

### ISSUE THREAD

**Issue by Glen-Moonpig** [aws/aws-sdk-net#1462]
## Expected Behavior

I want to remove all environment variables and lambda layers from a lambda function.

## Current Behavior

I am using UpdateFunctionConfigurationAsync and passing in an empty list of strings for UpdateFunctionConfigurationRequest.Layers and an empty dictionary for UpdateFunctionConfigurationRequest.Environment.Variables.

For the environment variables:
The [EnvironmentMarshaller](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/Lambda/Generated/Model/Internal/MarshallTransformations/EnvironmentMarshaller.cs) checks if the environment variables are set before creating the array. The method to check if the environment variables are set ([FunctionConfigurationEnvironment.IsSetVariables](https://github.com/aws/aws-sdk-net/blob/2272b29d9ef6b61c5e8ddd2939ec0aa700cf06bb/sdk/src/Services/Greengrass/Generated/Model/FunctionConfigurationEnvironment.cs#L103)) checks if the count of variables is >0. So, the empty array never gets created, the API thinks it is doing a partial update that does not include environment variables and makes no changes.

If I remove all environment variables except 1 then the update works fine because the array is created for the request and the API knows to update the environment variables. But removing all environment variables is impossible.

The same problem exists for the layers:
```
// Check to see if Layers property is set
internal bool IsSetLayers()
{
    return this._layers != null && this._layers.Count > 0; 
}
```

It is impossible to remove all layers from a function.

## Possible Solution

Remove the `Count > 0` checks, the null check alone is fine.

## Steps to Reproduce (for bugs)

Try to remove all environment variables and layers from a lambda function using UpdateFunctionConfigurationAsync.

## Context

I am trying to automate some function configuration. I can't do this using the .NET SDK, I will have to use my own HTTP client and build the HTTP requests from scratch.

## Your Environment

* AWSSDK.Core version used: 3.3.103.64
* Service assembly and version used: AWSSDK.Lambda 3.3.103.31
* Operating System and version: Windows 10
* Visual Studio version: 2019
* Targeted .NET platform: .NET Core

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by Glen-Moonpig** [comment]
Removing all environment variables is now possible (from 3.3.104.1+) by setting the Environment.IsVariablesSet property in UpdateFunctionConfigurationRequest.

Removing all layers still not possible.

**Comment by normj** [comment]
Late response but the is `IsLayersSet` property was added awhile back.
