### ISSUE TITLE
AmazonSimpleNotificationServiceClient constructor call with BasicAWSCredentials & Region tries to use System.Configuration.ConfigurationManager

### ISSUE THREAD

**Issue by mancku** [aws/aws-sdk-net#1463]
Hi, I have a Class Library project with AWSSDK.AmazonSimpleNotificationService Nuget Package imported and some code to send SMSs. Then I have an ASP.Net Core Web API project in the same solution. The Web API project references the Class Library one and passes the information so the SMSs can be send.
The Class Library code for sending SMSs is something like this:
```csharp
var credentials = new BasicAWSCredentials("{ACCESS KEY}", "{SECRET KEY}");
using (var smsClient = new AmazonSimpleNotificationServiceClient(credentials, RegionEndpoint.EUWest1))
{
	
	var messageAttributes = new Dictionary<string, MessageAttributeValue>
	{
		{"AWS.SNS.SMS.SenderID", new MessageAttributeValue {DataType = "String", StringValue = {SENDER NAME}}},
	};
	
	var publishRequest = new PublishRequest()
	{
		Message = "{SOME RANDOM MESSAGE}",
		PhoneNumber = "{PHONE NUMBER}",
		MessageAttributes = messageAttributes,
	};

	return smsClient.PublishAsync(publishRequest).Result;
}
```

## Expected Behavior
The SMS with the right credentials, the smsClient object should be created.

## Current Behavior
The constructor is crashing with the following exception:

> System.TypeInitializationException: The type initializer for 'Amazon.AWSConfigs' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'System.Configuration.ConfigurationManager, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Amazon.AWSConfigs.GetConfig(String name)
   at Amazon.AWSConfigs..cctor() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\AWSConfigs.cs:line 81
    --- End of inner exception stack trace ---
   at Amazon.AWSConfigs.get_LoggingConfig() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\AWSConfigs.cs:line 416
   at Amazon.Runtime.ClientConfig..ctor() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\ClientConfig.cs:line 62
   at Amazon.SimpleNotificationService.AmazonSimpleNotificationServiceConfig..ctor() in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Services\SimpleNotificationService\Generated\AmazonSimpleNotificationServiceConfig.cs:line 44
   at Amazon.SimpleNotificationService.AmazonSimpleNotificationServiceClient..ctor(AWSCredentials credentials, RegionEndpoint region) in D:\JenkinsWorkspaces\trebuchet-stage-release\AWSDotNetPublic\sdk\src\Services\SimpleNotificationService\Generated\_bcl45\AmazonSimpleNotificationServiceClient.cs:line 136

## Possible Solution
Not a solution, but a workaround is to also add the AWSSDK.AmazonSimpleNotificationService NuGet package to the Web API project. Just doing that, without modifying a single line of code, it works.

## Steps to Reproduce (for bugs)

- Create a solution, add a Class Library Project (.Net 4.7.2) and a .Net Core 3.0 Web API project.
- Reference the Class Library one into the Web API.
- Add the AWSSDK.AmazonSimpleNotificationService NuGet Package to the Class Library project.
- Add some code to send SMSs in the class Library, like in [the documentation](https://docs.aws.amazon.com/sns/latest/dg/sms_publish-to-phone.html)
- Call the Class Library SMS sender method from the Web API controller.

## Context
I was trying to add the sending SMS feature into an existing functionality in a Web API project.
This issue might be similar to https://github.com/aws/aws-sdk-net/issues/980 but I'm having a different exception, and also not the same class constructor.

## Your Environment
* AWSSDK.AmazonSimpleNotificationService version used: 3.3.101.91
* Operating System and version: Windows 10 PRO. Version 10.0.18363.476
* Visual Studio version: 16.3.9
* Targeted .NET platform: .Net Core 3.0 and .Net Framework 4.7.2

## .NET Core Info
* .NET Core version used for development: 3.0.0

**Comment by ashishdhingra** [comment]
Hi @mancku, 

This issue appears to be the missing reference issue. Try adding reference to System.Configuration.dll to your project and let me know if it resolves the issue.

Thanks,
Ashish

**Comment by mancku** [comment]
Hi @ashishdhingra thanks for your reply. Unfortunately I'm not working on that project anymore, nor do I have access to the repo

**Comment by ashishdhingra** [comment]
@mancku Thanks got your reply. I will close the issue for now. Feel free to open a new issue if the you see any error in future.
