### ISSUE TITLE
PutMetricData within the CloudWatch SDK doesn't accept Gzipped payload (though the API states it should)

### ISSUE THREAD

**Issue by amp4045** [aws/aws-sdk-net#1464]
The CloudWatch Client points out that it accepts a Gzipped payload for the PutMetricData request but the SDK does not support this. https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/CloudWatch/TPutMetricDataRequest.html

## Expected Behavior
The SDK should support a Gzipped blob as an argument

## Current Behavior
The SDK does not allow gzipped payloads

## Steps to Reproduce (for bugs)
Look at the SDK

## Context
We're aggregating Cloudwatch metrics within our application to the 'Values' array. Ideally I should be able to send out 20 metrics, each with 150 values, in one request. Unfortunately, due to to 40Kb limit, I cannot even send 10 metrics (each with 150 values) consistently. Adding in the  functionality to gzip the payload may allow more metrics to get aggregated per request. Ultimately, I believe this will save my company money (even if it's a trivial amount). 

## Your Environment

* AWSSDK.Core version used:  3.3.31.6 (Using version 3.3.10.15 of the CloudWatch SDK)
* Service assembly and version used: 
* Operating System and version: Windows 10 1909
* Visual Studio version: 16.3.9
* Targeted .NET platform: netcoreapp2.1

**Comment by klaytaybai** [comment]
Thanks for the feedback on this.  Currently the PutMetricData code is autogenerated.  There wasn't a flag for a custom extension.

**Comment by Downright-Development** [comment]
Any feedback on when this will be fixed?

**Comment by ashovlin** [comment]
Automatic compression for `PutMetricData` is now supported in AWSSDK.CloudWatch version 3.7.302.0 ([changelog](https://github.com/aws/aws-sdk-net/blob/main/changelogs/SDK.CHANGELOG.2024.md#377460-2024-02-12-1919-utc)).
* Blog post: https://aws.amazon.com/blogs/developer/new-default-payload-compression-for-amazon-cloudwatch-putmetricdata-with-the-aws-sdks/
* Docs, which cover to to enable/disable and configure the threshold for which AWS SDKs will compress: https://docs.aws.amazon.com/sdkref/latest/guide/feature-compression.html
