### ISSUE TITLE
QLDB c# sdk does specify how to compute commit digest

### ISSUE THREAD

**Issue by gkathire** [aws/aws-sdk-net#1465]
QLDB C# sdk is unusable without any having specifics on how to calculate the commit digest to commit a transaction. 

## Expected Behavior
Ability to use QLDB c# SDK in your application by using the commit api by calculating the commit digest.

## Current Behavior
Since there is no reference on how to calculate commit digest, we are not able to use QLDB service.

## Possible Solution
Include a working sample on how to calculate commit digest so that the commit transaction api can be used..

## Steps to Reproduce (for bugs)
Get the source code from https://github.com/gkathire/qldb-sample-aws-support/blob/master/Program.cs 

## Context
This issue blocks us from using the QLDB service.

## Your Environment
* AWSSDK.Core version used: 3.3.103.68
* AWSSDK.QLDB: 3.3.100.31 
* AWSSDK.QLDBSession: 3.3.100.31
* Operating System and version: Windows 10
* Visual Studio version: 2019
* Targeted .NET platform: .net core 3.0

## .NET Core Info
* .NET Core version used for development: .net core 3.0

**Comment by klaytaybai** [comment]
Hi @gkathire, I think this may already be possible.  Check out these resources.

[Request for getting an existing digest](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/index.html?page=QLDB/MQLDBGetDigestGetDigestRequest.html. ). This also works on new ledgers without transactions.  You should get a digest address tip and a digest stream that is empty.
[Developer guide for working with digests](https://docs.aws.amazon.com/qldb/latest/developerguide/verification.html)
[.NET CryptoUtil for calculating your own SHA256 hashes (.NET Standard link)]( https://github.com/aws/aws-sdk-net/blob/946b68584a200865daee983e1d541a77589aafe2/sdk/src/Core/Amazon.Util/_netstandard/CryptoUtil.netstandard.cs#L67-L75).

**Comment by prashantnjasure** [comment]
Hi,
Tried getting the Digest but always gives Ledger not found
Please help!

 //AmazonQLDBClient amazonQLDBClient = new AmazonQLDBClient(accessKey, secretKey);

            //GetDigestRequest digestRequest = new GetDigestRequest();// { Name = "LedgerNAME" };
            //digestRequest.Name = "EncrypticsLog";

             
            //GetDigestResponse response = amazonQLDBClient.GetDigest(digestRequest);
          // req.CommitTransaction.CommitDigest = response.Digest;
