### ISSUE TITLE
Support for HTTP2 in AWS SDK

### ISSUE THREAD

**Issue by madhub** [aws/aws-sdk-net#1466]
### .NET Core 3.1 add HTTP/2 support in HttpClient, with this support is it possible to use AWS .NET SDK(3.3.108.3) to send HTTP 2 requests to S3 storage ?
See the sample below, 
```csharp
 internal class MyDemoHttp2ClientFactory : HttpClientFactory
    {
        public override HttpClient CreateHttpClient(IClientConfig clientConfig)
        {
            return new HttpClient()
            {
                // set default http protocol to 2
                DefaultRequestVersion = new Version(2, 0)
            };
        }
    }
    class Program
    {
        static void Main(string[] args)
        {

            var s3Config = new AmazonS3Config() { ServiceURL = "http://" + "_s3_bucket_region" };
            s3Config.HttpClientFactory = new MyDemoHttp2ClientFactory();
            using (var cli = new AmazonS3Client(
                "_s3_access_key",
                "_s3_secret_access_key",
                s3Config))
            {
                // put object here
                // 
            }
        }
    }
```

**Comment by normj** [comment]
Out of curiosity have you seen any performance changes by doing this?

**Comment by madhub** [comment]
I haven't tried out, question was whether HttpClientFactory with HTTP version set 2, works or not.
I will try the sample today

**Comment by klaytaybai** [comment]
I think we still have work to do to get it within the SDK, but you should be able to use the implementation in your sample code.

**Comment by madhub** [comment]
I tried sample shown above to put object on S3 storage, outgoing request still shows HTTP1.1 even though I set the default version to 2.0

**Comment by friedrich-brunzema** [comment]
What is the status on S3 supporting http2 (also interested in doing this with c# .net core 3.1).  I am mostly concerned about performance improvements for the multipart upload.

**Comment by devteamexpress** [comment]
Any update here?

**Comment by madhub** [comment]
Please consider adding this feature
