### ISSUE TITLE
Support IAsyncEnumerable at DynamoDBv2.DataModel.AsyncSearch

### ISSUE THREAD

**Issue by sudoudaisuke** [aws/aws-sdk-net#1468]
Hello.

DynamoDBv2.DataModel.AsyncSearch is AsyncEnumerable pattern class.
IAsyncEnumerable was defined .NET Standard 2.1 for AsyncEnumerable pattern too.

## Expected Behavior
Support converting AsyncSearch to IAsyncEnumerable.

## Current Behavior
AsyncSearch is original and java like Iterator class. This cannot use C# 8.0 "await foreach" statement. 

## Possible Solution
Implement IAsyncEnumerable and IAsyncEnumerator like this.

```csharp
public static IAsyncEnumerable<IList<T>> ToAsyncEnumerable<T>(this AsyncSearch<T> source) 
    => new AsyncSearchEnumerable<T>(source);

internal class AsyncSearchEnumerable<T> : IAsyncEnumerable<IList<T>>
{

    private readonly AsyncSearch<T> _source;

    public AsyncSearchEnumerable(AsyncSearch<T> source)
    {
        if (source == null) throw new ArgumentNullException(nameof(source));
        _source = source;
    }

    public IAsyncEnumerator<IList<T>> GetAsyncEnumerator(CancellationToken cancellationToken = default)
        => new AsyncSearchEnumerator<T>(_source, cancellationToken);
}

internal class AsyncSearchEnumerator<T> : IAsyncEnumerator<IList<T>>
{

    private readonly AsyncSearch<T> _source;
    private readonly CancellationToken _cancellationToken;

    public AsyncSearchEnumerator(AsyncSearch<T> source, CancellationToken cancellationToken = default)
    {
        _source = source;
        _cancellationToken = cancellationToken;
        Current = default;
    }

    public IList<T> Current { get; private set; }

    public ValueTask DisposeAsync() => default;

    public async ValueTask<bool> MoveNextAsync()
    {
        if (_source.IsDone)
        {
            return false;
        }
        Current = await _source.GetNextSetAsync(_cancellationToken).ConfigureAwait(false);
        return true;
    }
}
```

## Steps to Reproduce (for bugs)
not bug.

## Your Environment
.NET Core 3.0 (3.1 preview, 2.1 with Microsoft.Bcl.AsyncInterfaces package)
AWS Lambda (.NET Core 2.1)

**Comment by klaytaybai** [comment]
Thanks for all the thoughts on this.

**Comment by say25** [comment]
@klaytaybai seems like the PR above might fix this. In my limited testing it seems to work for my use cases as well. Anyway we can get this merged?

**Comment by klaytaybai** [comment]
We’ve had related work at the top of our backlog for some time.  The decision was to wait until a dedicated engineer could thoroughly think through this design and our other needs.  Thanks for the interest.  We’ll try to get a decision soon

**Comment by sudoudaisuke** [comment]
Hello.

#1482 was rejected because breaking changes.
I create PR without breaking changes because AWSSDK.Core 3.5 higher. Would you review this?

design memo.

/aws-sdk-net/sdk/src/Services/DynamoDBv2/Custom/DataModel/_bcl35/Context.Sync.cs
```csharp
public IEnumerable<T> FromQuery<T>(QueryOperationConfig queryConfig);
public IEnumerable<T> FromQuery<T>(QueryOperationConfig queryConfig, DynamoDBOperationConfig operationConfig);
```

So, I think `FromQueryAsync` would be like this.
```csharp
public IAsyncEnumerable<T> FromQueryAsync<T>(QueryOperationConfig queryConfig, DynamoDBOperationConfig operationConfig = null);
```

However, this has some changes to be made. So I implemented IAsyncEnumerable<T> to AsyncSearch<T>. API users can use `AsyncSearch FromQueryAsync()` as `IAsyncEnumerable<T> FromQueryAsync()` I think.
There's a bad thing about this: it's a shame that you can't use IAsyncEnumerable operations and AsyncSearch on the same object. This can be a bit confusing for API users.

Thank you.

**Comment by say25** [comment]
This should be supported
