### ISSUE TITLE
TransferUtility.UploadDirectoryAsync has incorrect URL when ServiceURL is set (i.e. when using LocalStack)

### ISSUE THREAD

**Issue by gsfataviva** [aws/aws-sdk-net#1469]
When TransferUtility is used to copy a folder to an S3 bucket and the ServiceURL is set the transfer fails with "No such host" because the URL that is generated is incorrect.

So if you set the ServiceURL to "http://localhost:4572" (i.e. the ServiceUrl of LocalStack's S3 service) call UploadDirectoryAsync where the Bucket is called "MyBucket" and watch the AWS HTTP call using a tool like Fiddler you will see that the URL that the AWS SDK tries to use is something like this:-

http://MyBucket.localhost:4572/Sccm%20file%20test.csv

but it should be:-

http://localhost:4572/MyBucket/Sccm%20file%20test.csv

The call to UploadDirectoryAsync fails with "No such host".

## Expected Behavior
The call to UploadDirectoryAsync should be successful.

## Current Behavior
The call to UploadDirectoryAsync  fails with "No such host".

## Possible Solution
Line 130 of AmazonS3PostMarshallHandler.cs incorrectly concatenates the bucket name and the ServiceURL's host name:-

ub.Host = string.Concat(bucketName, ".", ub.Host);

## Steps to Reproduce (for bugs)
Create a .NET Core Console application with the following code and add the AWSSDK.S3 NuGet package. Run the program and the error occurs:-

using System;
using Amazon;
using Amazon.S3;
using Amazon.S3.Transfer;

namespace AWSSDKS3TransferUtilityTest
{
    class Program
    {
        static void Main(string[] args)
        {
            TransferUtility transferUtility = CreateTransferUtility();

            TransferUtilityUploadDirectoryRequest transferUtilityUploadDirectoryRequest = new TransferUtilityUploadDirectoryRequest
            {
                Directory = @"C:\Temp",
                BucketName = "MyBucket"
            };

            transferUtility.UploadDirectoryAsync(transferUtilityUploadDirectoryRequest).Wait();
        }

        private static TransferUtility CreateTransferUtility()
        {
            AmazonS3Config config = new AmazonS3Config()
            {
                RegionEndpoint = RegionEndpoint.GetBySystemName("eu-west-1"),
            };

            config.ServiceURL = "http://localhost:4572";

            IAmazonS3 amazonS3 = new AmazonS3Client(config);

            TransferUtility transferUtility = new TransferUtility(amazonS3);

            return transferUtility;
        }
    }
}

## Context
It is not possible to use LocalStack's support of S3 with the AWS SDK.

## Your Environment
* AWSSDK.Core version used: 3.3.108.4
* Service assembly and version used: 
* Operating System and version: Windows 10
* Visual Studio version: Visual Studio 2017
* Targeted .NET platform: .NET Core 2.1

**Comment by klaytaybai** [comment]
`config.ForcePathStyle  = true` should help you

**Comment by gsfataviva** [comment]
Thanks @klaytaybai , that does indeed solve the problem.
