### ISSUE TITLE
S3 ReadWriteTimeout in AmazonS3Config does not work on .Net Core

### ISSUE THREAD

**Issue by DouglasLivingstone** [aws/aws-sdk-net#1473]
## Expected Behavior
The `ReadWriteTimeout` for S3 defaults to no timeout so that large downloads don't get interrupted, however it is sometimes useful to set `AmazonS3Config.ReadWriteTimeout` anyway. Expectation is that setting this to a low value will cause the downloads to error out if they don't complete within the timeout.

## Current Behavior
This works correctly in a project using .Net Framework 4.6.1, however it appears to do nothing when using .Net Core 3.0.

## Possible Solution
I found a workaround based on the comments here: https://github.com/dotnet/corefx/issues/34550#issuecomment-497183634

## Steps to Reproduce (for bugs)

As a test, setting `ReadWriteTimeout` to a very small value causes the requests to fail early in .Net Framework, but has no effect in .Net Core:
```
var config = new AmazonS3Config
{
    ReadWriteTimeout = TimeSpan.FromMilliseconds(5)
};

using var client = new AmazonS3Client(awsAccessKeyId, awsSecretAccessKey, config);
using var transfer = new TransferUtility(client);

var request = new TransferUtilityDownloadDirectoryRequest
{
    BucketName = bucketName,
    S3Directory = s3Directory,
    LocalDirectory = localDirectory
};

transfer.DownloadDirectory(request);
```

As a workaround, passing in a cancellation token to `DownloadDirectoryAsync` works.

## Context

This caused a silent breakage when migrating code using the AWS SDK from .Net Framework to .Net Core, as the API was the same but the configuration settings didn't work.

## Your Environment
* AWSSDK.Core version used: 3.3.103.70
* Operating System and version: Win 10
* Visual Studio version: 2019
* Targeted .NET platform: .Net Core 3

## .NET Core Info

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\
```

**Comment by klaytaybai** [comment]
I'm actually not seeing any effect from ReadWriteTimeout on .NET Core or .NET Framework 4.6.1.  Can you please confirm that this was having an effect for you in Framework 4.6.1?  

Timeout might be better suited for your use case.

**Comment by klaytaybai** [comment]
This has been fixed.  Thanks.

**Comment by DouglasLivingstone** [comment]
Great, thanks @klaytaybai, I’ll watch out for the next release!
