### ISSUE TITLE
Unable to connect AWS CodeGuru to Github Enterprise.

### ISSUE THREAD

**Issue by laith-leo** [aws/aws-sdk-net#1475]
## Issue
Unable to connect AWS CodeGuru to Github Enterprise

## Expected Behavior
The Source provider in "Associate Repository" should have a field for GitHub enterprise account.

## Current Behavior
It only allows to connect to standard Github account and AWS CodeCommit.

## Possible Solution
Enable GitHub enterprise account to associate its repositories to be used with Profilers and Reviewer. 

## Your Environment
AWS account and GitHub enterprise account.

**Comment by klaytaybai** [comment]
Hi @laith-leo, I believe associating GitHub accounts is only available on the console right now.  That seems to be intentional, so I'm going to close this issue.

In case you were looking into this for .NET projects, I should notify you that CodeGuru currently only supports code reviews of Java.

**Comment by laith-leo** [comment]
@klaytaybai 
I need to associate the repositories of my "GitHub Enterprise", not "GitHub Free". This was my question.

**Comment by klaytaybai** [comment]
Unless you are at re:Invent and talking with the Code Guru team, the [AWS Forums for Code Guru](https://forums.aws.amazon.com/forum.jspa?forumID=360) are the most appropriate channel for this problem.  It doesn't have relevance to the .NET SDK.
