### ISSUE TITLE
SQS ReceiveMessageAsync() hangs in .Net Core when the provided identity doesn't have access

### ISSUE THREAD

**Issue by hognevevle** [aws/aws-sdk-net#1477]
## Expected Behavior
An exception should be thrown.

## Current Behavior
In a Worker Service (using `HostBuilder`), executing `await _sqs.ReceiveMessageAsync(...)` using credentials that does not have access to the given queue will cause the operation to hang.  It seems indefinite, as it will keep going for several minutes without nothing happening.
[Screenshot](https://drive.google.com/file/d/1whdsEpOpgp2FVkdVsYCRlMYqXhjA7Fol/view?usp=drivesdk)

Same results in .Net Core 3.1 and 3.0. 

In a Console Application, however, an error message is thrown as expected. This is also true for .Net Framework 4.7. [Exception screenshot](https://drive.google.com/file/d/1GvP77Jv5ZP6VQNzFpFY0Fo1u1TVd981Y/view?usp=drivesdk). 

## Possible Solution
Unknown.

## Steps to Reproduce (for bugs)
Repro at https://github.com/hognevevle/SqsWorkerServicePlayground . Make sure you change to a valid Queue URL in `Worker.cs`, and if needed, change to a different region in `Program.cs`. 

## Your Environment

* AWSSDK.Core version used: 3.3.102.39
* Service assembly and version used: Not sure what _Service assembly_ means
* Operating System and version: Windows 10 Pro
* Visual Studio version:  2019 (16.4.0)
* Targeted .NET platform: .Net Core

## .NET Core Info

* .NET Core version used for development: 3.1
* .NET Core version installed in the environment where application runs:  3.1
* Output of `dotnet --info`: 
```dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  3.0.101 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download```

* Contents of project.json/project.csproj: See github repo above

**Comment by klaytaybai** [comment]
Hi @hognevevle, I think this is due to an unhandled exception.  When I reproduced the issue, it hung for me too unless I surrounded the call in a try catch and handled the exception.  Please try doing that.  You should still be getting the access denied exception.

**Comment by hognevevle** [comment]
Thanks @klaytaybai - indeed, a try/catch does the trick. Regardless, I do find this behaviour rather strange, but it seems to be an issue in the .Net Core Generic Host, rather than the AWS SDK. 

I've opened an issue there. https://github.com/aspnet/Extensions/issues/2758
