### ISSUE TITLE
S3 PutACL Causes MalformedACLError when using AccessControlList (EMC ECS)

### ISSUE THREAD

**Issue by scottserven** [aws/aws-sdk-net#1478]
When calling PutACL and passing specific grants instead of a canned ACL, the call fails with a MalformedACLError due to a missing namespace on the AccessControlPolicy element.  

This is while attempting to use PutACL on an EMC ECS instance which uses the S3 protocols.  So perhaps this isn't an issue on AWS itself.  

## Expected Behavior
A 200 response and successful application of the specified ACL

## Current Behavior
Fails with an error 400 response MissingACLError

## Possible Solution
Add the namespace of "http://s3.amazonaws.com/doc/2006-03-01/" to the AccessControlPolicy element in the PutACLRequestMarshaller.cs.

## Steps to Reproduce (for bugs)
Calling GetACL on a bucket, and simply taking the AccessControlList from the response and passing it to a PutACL request causes the problem.

## Your Environment
AWSSDK.Core version: 3.3.104
AWSSDK.S3 version: 3.3.109
EMC ECS version: unknown
.Net Target: 4.5

**Comment by klaytaybai** [comment]
It doesn't appear to be a problem with the SDK.  If you are able to show sample code that would indicate that it might be the AWS SDK for .NET's problem, please share that.  I wasn't able to reproduce the issue using just the SDK for .NET 4.5.  The PutACLRequestMarshaller.cs class looks good too.

**Comment by scottserven** [comment]
Thanks for the reply.  I'll post some samples after I get into the office tomorrow.

I had captured request/responses from the SDK via Fiddler, and then tinkered with the request in Postman to determine what the problem was.  It came down to the determining factor being whether or not the namespace was present on the AccessControlList element.

Just to reiterate, this is on an EMC ECS instance (not AWS) so there may be implementation difference where this works perfectly fine in AWS, and my problem is specific to EMC ECS in this case where it's verifying the XML structure of any requests.  If it's beyond the intent of this SDK to support S3-_compatible_ services, please feel free to close this.  

As for the request marshaller classes that create XML bodies, it looks to be 50/50 on whether or not the code explicitly adds namespaces to their elements via to the WriteElementStart method.  For example, the PutObjectRetentionRequestMarshaller does put namespaces on the elements it creates, although plenty of others do not.  I'm just not seeing the pattern on why some do and some don't.

**Comment by scottserven** [comment]
Here's the minimum code needed to trigger the error, with the invalid request generated from the SDK afterwards, as well as one that works (by adding the xmlns on the AccessControlList).  


**Sample Code**
```
using Amazon.S3;
using Amazon.S3.Model;

namespace ConsoleApplication2 {
    class Program {
        static void Main(string[] args) {

            // fill in these values
            string accessKey = "";
            string secretKey = "";
            string endpoint = "";
            string bucketName = "";

            AmazonS3Config config = new AmazonS3Config();
            config.ForcePathStyle = true; 
            config.SignatureVersion = "2";
            config.SignatureMethod = Amazon.Runtime.SigningAlgorithm.HmacSHA1;
            config.ServiceURL = endpoint;

            AmazonS3Client client = new AmazonS3Client(accessKey, secretKey, config);

            // Just get the existing ACLs from a bucket, and re-apply them as-is
            GetACLResponse getResponse = client.GetACL(new GetACLRequest {
                BucketName = bucketName
            });

            // This fails
            PutACLResponse putResponse = client.PutACL(new PutACLRequest {
                AccessControlList = getResponse.AccessControlList,
                BucketName = bucketName
            });
        }
    }
}
```

**Request Generated From Above Code (Fails)**
```
<AccessControlPolicy>
  <AccessControlList>
    <Grant>
      <Grantee xsi:type="CanonicalUser" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <DisplayName>n2a-archive-user</DisplayName>
        <ID>n2a-archive-user</ID>
      </Grantee>
      <Permission>FULL_CONTROL</Permission>
    </Grant>
    <Grant>
      <Grantee xsi:type="Group" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <URI>http://acs.amazonaws.com/groups/global/AllUsers</URI>
      </Grantee>
      <Permission>READ</Permission>
    </Grant>
  </AccessControlList>
  <Owner>
    <DisplayName>n2a-archive-user</DisplayName>
    <ID>n2a-archive-user</ID>
  </Owner>
</AccessControlPolicy>
```
**HTTP Response**
Status: 400
```
<Error>
    <Code>InvalidArgument</Code>
    <Message>Invalid Argument</Message>
    <RequestId>0ab40557:16d2d3282c1:75b46:caed</RequestId>
</Error>
```
I'm unsure why I'm getting an InvalidArgument error instead of the MalformedACLError I was seeing yesterday.  Regardless, an error still occurs for the same underlying reason and is resolved in the same way.

**Manually Corrected Request That Succeeds**
The xmlns on the AccessControlList is the only difference
```
<AccessControlPolicy>
  <AccessControlList xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <Grant>
      <Grantee xsi:type="CanonicalUser" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <DisplayName>n2a-archive-user</DisplayName>
        <ID>n2a-archive-user</ID>
      </Grantee>
      <Permission>FULL_CONTROL</Permission>
    </Grant>
    <Grant>
      <Grantee xsi:type="Group" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <URI>http://acs.amazonaws.com/groups/global/AllUsers</URI>
      </Grantee>
      <Permission>READ</Permission>
    </Grant>
  </AccessControlList>
  <Owner>
    <DisplayName>n2a-archive-user</DisplayName>
    <ID>n2a-archive-user</ID>
  </Owner>
</AccessControlPolicy>
```

**Comment by klaytaybai** [comment]
Hmm.  I'll continue to look into this a little.  I'm running on AWS, not EMC, and it is working.  Looking into the Fiddler logs, I see that response from the Get operation has the xmlns="http://s3.amazonaws.com/doc/2006-03-01/", but the PutACL request succeeds without it.  The SDK should work with S3-compatible sources that do not have their own incompatibilities, but we do not offer support for S3-compatible sources beyond bugs that affect the SDK in general.

**Comment by ashishdhingra** [comment]
Hi @scottserven,

Good afternoon.

I was going through the issue backlog and came across this issue. As @klaytaybai mentioned, the code works on AWS. Please let me know if this is still an issue or if this could be closed.

Thanks,
Ashish
