### ISSUE TITLE
Add Ability to Set Content-Disposition to S3 Uploads

### ISSUE THREAD

**Issue by jacob-audubon** [aws/aws-sdk-net#1481]
You are unable to set the Content-Disposition of the objects uploaded to S3 using the .NET SDK. 

## Expected Behavior

The property can be added to all the UploadRequest classes so it could be set directly on the request object.

```
var fileTransferUtilityRequest = new TransferUtilityUploadRequest
{
    BucketName = "my-byucket",
    FilePath = "/tmp/myfile.zip",
    PartSize = 6291456, 
    Key = "key name",
    ContentDisposition = "attachment; filename=customized-name.zip"
}; 
```
## Current Behavior

Currently you cannot set it at all, and the best you can do is set the key names to how you would like them.

## Context

The scenario I am up against at the moment is  the desired name of the file when downloaded can not easily be used as the key name, as the desired name is not guaranteed to be unique within the bucket. The only solution from .Net that I can see is to use folders, and then have the desired name there, but this seems more difficult then need be.

**Comment by klaytaybai** [comment]
Hi @jacob-audubon, you can set it via `fileTransferUtilityRequest.Headers.ContentDisposition = "attachment; filename=customized-name.zip"`
