### ISSUE TITLE
Why don't I create Amazon lightsailclient and set up UserData?

### ISSUE THREAD

**Issue by bbhxwl** [aws/aws-sdk-net#1483]
var shuju = new CreateInstancesRequest()
                {
                    BlueprintId = "centos_7_1901_01",
                    BundleId = "micro_2_0",
                    AvailabilityZone = "ap-northeast-1d",
                    InstanceNames = new System.Collections.Generic.List<string>() { "test" },
                    UserData = "echo root:test123456- |sudo chpasswd root\r\nsudo sed -i 's/^#\\?PermitRootLogin.*/PermitRootLogin yes/g' /etc/ssh/sshd_config;\r\nsudo sed -i 's/^#\\?PasswordAuthentication.*/PasswordAuthentication yes/g' /etc/ssh/sshd_config;\r\nsudo reboot\r\n"
                };
If it takes effect, it will support root account login, but UserData is not executed. Why?

**Comment by klaytaybai** [comment]
This question is beyond scope of support from the .NET SDK team.  Could you please open a case with Premium Support or post on the [LightSail AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=231&start=0) instead?
