### ISSUE TITLE
terminate called after throwing an instance of 'EEFileLoadException*' error

### ISSUE THREAD

**Issue by anusha-amz** [aws/aws-sdk-net#1486]
Got an exception when trying to add messages asynchronously to SQS using Lambda dotnetcore2.1

## Current Behavior
Push multiple messages on to the SQS queue asynchronously with await statement from Lambda function and received "terminate called after throwing an instance of 'EEFileLoadException*' error". the exception is seen only when await statement is included.

## Steps to Reproduce (for bugs)
Here is the code snippet which can help to reproduce the issue 
=====================================================
class Program123
    {
        public static async Task Main()
        {
            Amazon.SQS.AmazonSQSClient client = new Amazon.SQS.AmazonSQSClient();
            List<Task> tasks = new List<Task>();
            for (int i = 0; i < 3000; i++)
            {
                Console.WriteLine("Value of i: {0}", i);
                CancellationTokenSource source = new CancellationTokenSource();
                CancellationToken token = source.Token;
                var queueName = "https://sqs.us-east-1.amazonaws.com/XXXXXXXXXXXX/AsyncQueue"; 
				var messageBody = "" + i;
         		tasks.Add(client.SendMessageAsync(queueName, messageBody, token));
            }

            await Task.WhenAll(tasks);
        }
    }
=====================================================

## Context

Push multiple messages on to the SQS queue asynchronously with await statement from Lambda function and received "EEFileLoadException*'. Increasing Lambda function with maximum memory also didn't serve the purpose

## Your Environment
 
* Service assembly and version used: System.Reflection v1.0.0.0
* Operating System and version: macOS Mojave v10.14.6
* Visual Studio Code version: 1.40.2
* Targeted .NET platform: dotnetcore2.1

## .NET Core Info

* .NET Core version used for development: dotnet 2.1
* .NET Core version installed in the environment where application runs:  dotnetcore 2.1
* Output of `dotnet --info`: 
======================================================
.NET Core SDK (reflecting any global.json):
 Version:   2.1.607
 Commit:    cad4fbe2d5
Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.607/
Host (useful for support):
  Version: 2.1.14
  Commit:  57273284ef
.NET Core SDKs installed:
  2.1.607 [/usr/local/share/dotnet/sdk]
.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
==============================================================

* Contents of project.json/project.csproj: 
==============================================================
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="1.0.0 " />
    <PackageReference Include="Amazon.Lambda.Serialization.Json" Version="1.3.0" />
    <PackageReference Include="AWSSDK.SQS" Version="3.3.102.39" />
  </ItemGroup>  
</Project>
=================================================================

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
Are you also using managed C++ code?  All references that I am seeing with a Google search indicate that this is when this issue occurs.  I don't think it has relevance to our SDK.  In a clean solution/project, your repro code executed successfully for me.

**Comment by anusha-amz** [comment]
@klaytaybai to give you little insight, this code works locally but doesn't work and threw 'EEFileLoadException*' exception in Lambda

**Comment by Rudithus** [comment]
Hello,
I've just encountered this problem myself while trying to publish to an SNS topic.

**Comment by klaytaybai** [comment]
The error is strange, but you may be running into an issue with the limits of the service.  The [Lambda limits documentation](https://docs.aws.amazon.com/lambda/latest/dg/limits.html) says that only 1024 threads/processes may be created concurrently.  I'll send this over to the Lambda team to have them investigate further.  If it's only happening at 1000+ threads, please attempt to batch them as a workaround.

**Comment by Rudithus** [comment]
that's what we did as a work around.

Thank you @klaytaybai

**Comment by klaytaybai** [comment]
Since the issue appears to be reaching Lambda's documented max threads, I'm going to close this for now.
