### ISSUE TITLE
AmazonUtil static extensionToMime  needs to user configurable

### ISSUE THREAD

**Issue by damianh** [aws/aws-sdk-net#1487]
## Expected Behavior
Be able to supply to TransferUtility a custom extension to mime map.

## Current Behavior

The current map is missing entries (#1480 ). It also has entries that are wrong. ( `.js` should be `application/javascript` https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/S3/Custom/Util/AmazonS3Util.cs#L104 as per RFC https://www.rfc-editor.org/rfc/rfc4329.txt from 2006!)

## Possible Solution
Allow the user to supply an optional delegate `Func<string,string>` to `TransferUtilityUploadDirectoryRequest` that allows them to map the extension to the content type of their choice. If the delegate is not supplied, then fallback to the current static map. 

## Context

We are using TransferUtilityUploadDirectoryRequest to deploy static content, specically content used in ReactNative/Expo application. Because the content type is incorrectly set, the application was crashing on iOS - it didn't understand `application/x-javascript`. And in fairness, `application/javascript` is in an RFC from 13 years ago.

## Your Environment
AWSSDK.S3 3.3.108

**Comment by klaytaybai** [comment]
Thanks for the feedback on this one.  Those are good points.

**Comment by klaytaybai** [comment]
Hi @damianh.  After working on this, I realized that this is already possible within the SDK.   You will need to do something like:

```
...
var request = new TransferUtilityUploadDirectoryRequest
{
    BucketName = existingBucketName,
    Directory = directoryPath,
    SearchOption = SearchOption.AllDirectories,
 };

request.UploadDirectoryFileRequestEvent += Request_UploadDirectoryFileRequestEvent;
...


private static void Request_UploadDirectoryFileRequestEvent(object sender, UploadDirectoryFileRequestArgs e)
        {
            var request = e.UploadRequest;
            switch (Path.GetExtension(request.Key))
            {
                case ".js":
                    request.ContentType = "application/javascript";
                    break;
                case ".json":
                    request.ContentType = "application/json";
                    break;
                default: break;
            }
        }
```

We are going to have more discussion around what our policy should be for updating the default content type mappings.  If anybody has thoughts, please feel free to contribute here.  We are concerned about backwards compatibility, but we also want to be current.

**Comment by damianh** [comment]
That will work, thanks for sharing.
