### ISSUE TITLE
S3Client.GetPresignedUrl Throwing First Chance Exceptions from Arn.Parse() when Bucket property isn't an ARN

### ISSUE THREAD

**Issue by gbent** [aws/aws-sdk-net#1488]
## Expected Behavior
Arn.TryParse should parse ARNs without throwing exceptions. It does this now, but only by calling Arn.Parse and catching its exceptions.

## Current Behavior
The problem with this method of preventing exceptions when calling Arn.TryParse is that a First Chance Exception handler will still see the exceptions thrown by Parse.

## Possible Solution

Ideally, refactoring Arn.Parse a bit so it will throw only if required by the caller, would keep all the parsing in the same/single function, while not having to catch exceptions in TryParse. However, in the spirit of changing as little as possible, if the basic check Arn.IsArn is done before calling Parse, most exceptions would be avoided when the input isn't even pretending to be an ARN, which is the case when calling s3Client.GetPresignedUrl directly on a bucket and not an S3 Access Point.

## Steps to Reproduce (for bugs)

Calling s3Client.GetPresignedUrl with a GetPreSignedUrlRequest whose bucket property is a bucket name and not an ARN will throw an Arn.Parse Exception (caught by Arn.TryParse).

## Context

Our code calls s3Client.GetPresignedUrl a lot. We don't yet use S3 Access Points and the exception is thrown each time.

## Your Environment

* AWSSDK.Core version used: current master
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by normj** [comment]
Your PR was released in the latest version of the SDK.
