### ISSUE TITLE
Default profile credentials not working in latest builds

### ISSUE THREAD

**Issue by pixelharmony** [aws/aws-sdk-net#1491]
When upgrading to the latest versions of the AWSSDK.S3 or AWSSDK.SecurityToken packages, profile credentials no longer work.

## Expected Behavior
After instantiating an IAmazonS3 via dependency injection it should be using `AssumeRoleAWSCredentials` when the `Profile` in `appsettings.json` is set to a credential profile that specifies the use of a role.

## Current Behavior
Rather than picking up the role from the profile, the S3 client is defaulting to `BasicAWSCredentials`

## Steps to Reproduce (for bugs)
Upgrade either/both of the following packages: 
`AWSSDK.S3` package past version `3.3.110.1`
`AWSSDK.SecurityToken` past version `3.3.104.10`

## Context
I can no longer connect to S3 using my role base credentials.

## Your Environment

* AWSSDK.Core version used: N/A
* AWSSDK.S3 version used: >3.3.110.1
* AWSSDK.SecurityToken: >3.3.104.10
* Operating System and version: Mac OS Catalina
* Visual Studio version: Rider 2019.3
* Targeted .NET platform: .NET Core

## .NET Core Info

* .NET Core version used for development: 2.1
* .NET Core version installed in the environment where application runs: 2.1

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
Thank you for raising this!  I have identified the root cause and proposed the fix to the team.  A release is likely to be delayed due to restrictions around the holidays.  In the meantime, please use a version earlier than Core 3.3.104.7 or remove "role_session_name" from your profile.  If you are not using a role session name in your profile and you are still experiencing this issue, please let us know and provide the property names in your profile.

**Comment by klaytaybai** [comment]
Hi @pixelharmony, I believe that this issue is now fixed.  Please let us know if you are still experiencing this issue when you get a chance.  If you are, please provide us with the property names in your profile (e.g. role_arn, role_session_name).

**Comment by CraigChamberlain** [comment]
I seem to be having this problem with DynamoDB

Rather than load settings as suggested:

```
public void ConfigureServices(IServiceCollection services)
{
    // Add framework services.
    services.AddMvc();

    services.AddDefaultAWSOptions(Configuration.GetAWSOptions());
    services.AddAWSService<IAmazonS3>();
    services.AddAWSService<IAmazonDynamoDB>();
}
```
I'm having to resort to the following:

```

                services.AddSingleton<IAmazonDynamoDB>(sp =>
                {
                    var clientConfig = root.GetAWSOptions();
                    var credentials = new BasicAWSCredentials(
                        System.Environment.GetEnvironmentVariable("AWS_ACCESS_KEY_ID"),
                        System.Environment.GetEnvironmentVariable("AWS_SECRET_ACCESS_KEY"));           
                    return new AmazonDynamoDBClient(credentials, clientConfig.Region );
                });
```

[netcoreapp2.1]: 
   Top-level Package                                 Requested   Resolved
   > Amazon.Lambda.APIGatewayEvents                  1.2.0       1.2.0   
   > Amazon.Lambda.Core                              1.1.0       1.1.0   
   > Amazon.Lambda.Serialization.Json                1.5.0       1.5.0   
   > AWSSDK.DynamoDBv2                               3.5.0.18    3.5.0.18
   > AWSSDK.Extensions.NETCore.Setup                 3.3.101     3.3.101 
   > Microsoft.Extensions.Configuration              3.1.8       3.1.8   
   > Microsoft.Extensions.Configuration.Json         3.1.8       3.1.8   
   > Microsoft.Extensions.Hosting                    3.1.8       3.1.8   
   > Microsoft.NETCore.App                     (A)   [2.1.0, )   2.1.0   
   > Newtonsoft.Json                                 12.0.3      12.0.3  
   > SolarLunarName.Standard                         1.0.2       1.0.2
