### ISSUE TITLE
QLDB C# sdk  GetDigest giving ledger name not found for using to commit digest to commit a transaction.

### ISSUE THREAD

**Issue by prashantnjasure** [aws/aws-sdk-net#1492]
Trying to commit a new transaction to QLDB.
To do that I need to get the the Digest I used the following code : 
        //GetDigestRequest digestRequest = new GetDigestRequest();// { Name = "LedgerName" };
            //digestRequest.Name = "LedgerName";
            //GetDigestResponse response = amazonQLDBClient.GetDigest(digestRequest);
          // req.CommitTransaction.CommitDigest = response.Digest; 

The GetDigest() method gives error Ledger Name not found even though the ledger exists and is active.
Please help.

**Comment by klaytaybai** [comment]
I’ll look into this more tomorrow.  I suspect that, if it is an issue from the Amazon side of things, it is an issue with the service and not the sdk, which would mean there is less we can do from our side without going through Premium Support.

**Comment by klaytaybai** [comment]
The SDK appears to be functioning normally, so there is not much we can do.  Please first verify that your client's credentials, role permissions, and region are correct for ledger that you are trying to access.  If you still need help and have Premium Support, please go through them so they can try to verify and resolve your problem.
