### ISSUE TITLE
Using AssumeRoleWithWebIdentityCredentials causes dead lock

### ISSUE THREAD

**Issue by coryflucas** [aws/aws-sdk-net#1493]
When using AssumeRoleWithWebIdentityCredentials (in my case via environment variables in an EKS cluster), retrieving credentials hangs forever.

## Expected Behavior
Retrieving credentials via AssumeRoleWithWebIdentityCredentials should work.

## Current Behavior
No logs are generated, but the application hangs forever.  I was able to debug the SDK and the issue appears to be that no credentials are provided to the STS client, so it tries to retrieve credentials via the fallback chain, which hits a semaphore which is currently held waiting on the STS client to retrieve credentials.

## Possible Solution
It appears we should be using `AnonymousAWSCredentials` [here](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Credentials/_bcl+netstandard/AssumeRoleWithWebIdentityCredentials.cs#L230-L231)

## Steps to Reproduce (for bugs)
Set the following env vars (role can be invalid, and file contents don't appear to matter):
```
AWS_ROLE_ARN=arn:aws:iam::000000000000:role/whatever
AWS_WEB_IDENTITY_TOKEN_FILE=/path/to/a/file
AWS_REGION=us-east-1
```
And then this code will never complete (service doesn't matter).
```
var snsClient = new AmazonSimpleNotificationServiceClient();
var result = await snsClient.PublishAsync("arn:aws:sns:us-east-1:000000000000:test", "test");
```

## Context
Attempting to use EKS IAM for service accounts

## Your Environment
* AWSSDK.Core version used: 3.3.104.11
* Service assembly and version used: 
  * AWSSDK.SimpleNotificationService - 3.3.101.107
  * AWSSDK.SecurityToken - 3.3.104.15
* Operating System and version: Alpine Linux, Mac OS X 10.14
* Targeted .NET platform: .NET Core 3.1

## .NET Core Info
* .NET Core version used for development:  3.1
* .NET Core version installed in the environment where application runs: 3.1
* Output of `dotnet --info`: 
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.100/

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  2.1.505 [/usr/local/share/dotnet/sdk]
  2.2.105 [/usr/local/share/dotnet/sdk]
  3.0.100 [/usr/local/share/dotnet/sdk]
  3.1.100 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
* Contents of project.json/project.csproj: 
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Core" Version="3.3.104.11" />
    <PackageReference Include="AWSSDK.SecurityToken" Version="3.3.104.15" />
    <PackageReference Include="AWSSDK.SimpleNotificationService" Version="3.3.101.107" />
  </ItemGroup>

</Project>
```

**Comment by klaytaybai** [comment]
Thanks.  We'll try to get this fixed soon.

**Comment by juniortads** [comment]
@coryflucas Thanks for describe this problem, I have the same problem here.

**Comment by coryflucas** [comment]
@klaytaybai Anything I can do to help get this resolved?  We've been using a custom implementation of web identity token support, but now upgrading SDK packages is unintentionally breaking things because the official implementation ends up higher in the fallback credentials.  Happy to address any concerns with the PR or provide more details on the issue.

**Comment by normj** [comment]
Version **3.3.104.14** of AWSSDK.Core is out with the fix. Thanks for reporting the issue and helping us track down the fix.

**Comment by coryflucas** [comment]
Confirmed working 🎉, thanks @normj!
