### ISSUE TITLE
Problem with DynamoDB ScanAsync with blazor wasm (.netstandard 2.1) "Property AllowAutoRedirect is not supported."

### ISSUE THREAD

**Issue by PascalS86** [aws/aws-sdk-net#1498]
Hi, 

As mentioned in the title, I get the following error, when I try to run ScanAsync in blazor wasm:
Property AllowAutoRedirect is not supported. I'm not getting, why this happens. Am I doing something wrong?

## Expected Behavior
I want to retrieve Data from a DynamoDB Table with a ScanCondition

## Current Behavior
Currently I get the Exception Property AllowAutoRedirect is not supported.

## Steps to Reproduce (for bugs)
My setup is the following:
.NETCore 3.1 blazor template for webassembly.
Installed Nuget:
```
AWSSDK.Extensions.NETCore.Setup
AWSSDK.DynamoDBv2 
```

in Startup.cs
```
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDefaultAWSOptions(new AWSOptions(){
                Region = Amazon.RegionEndpoint.EUWest1,
                Credentials  = new BasicAWSCredentials("", "")
            });
            services.AddAWSService<IAmazonDynamoDB>();
            services.AddSingleton<DataService>();
           
        }
```

in DataService.cs
```
    public class DataService
    {   
        private readonly IAmazonDynamoDB _dynamoDbClient;
        
        public DataService(IAmazonDynamoDB dynamoDbClient){
            _dynamoDbClient = dynamoDbClient;
        }

        public async Task<List<Data>> GetData (string client=""){
           try{
                using(var context = new DynamoDBContext (_dynamoDbClient)){
                    var data= await context.ScanAsync<Data>(
                        new List<ScanCondition>(){
                            new ScanCondition("ID",ScanOperator.BeginsWith, client )
                            }).GetRemainingAsync();
                    return data.ToList();
                }
           }
           catch(Exception ex){
               Console.WriteLine(ex.Message);
               return new List<Data>();
           }
        }
    }
```

## Your Environment
.NETCore 3.1 blazor template for webassembly.
Installed Nuget:
```
AWSSDK.Extensions.NETCore.Setup
AWSSDK.DynamoDBv2 
```

## .NET Core Info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by PascalS86** [comment]
Update:

the error detail I got now is:

**Unable to get IAM security credentials from EC2 Instance Metadata Service**

**Comment by jminnihan** [comment]
I have the same issue when using the AWSSDK.S3 and AWSSDK.S3.Transfer methods for UploadFileAsync:

Exception occurred in AwsS3Service.UploadFileAsync, Message was: Property AllowAutoRedirect is not supported.. 
blazor.webassembly.js:1 Stack Trace:   at System.Net.Http.HttpClientHandler.set_AllowAutoRedirect (System.Boolean value) <0x5163148 + 0x0000c> in <filename unknown>:0 
blazor.webassembly.js:1   at Amazon.Runtime.HttpRequestMessageFactory.CreateManagedHttpClient (Amazon.Runtime.IClientConfig clientConfig) [0x0002a] in D:\JenkinsWorkspaces\Stage-release-dry-run\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_netstandard\HttpRequestMessageFactory.cs:261 
blazor.webassembly.js:1   at Amazon.Runtime.HttpRequestMessageFactory.CreateHttpClient (Amazon.Runtime.IClientConfig clientConfig) [0x00008] in D:\JenkinsWorkspaces\Stage-release-dry-run\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_netstandard\HttpRequestMessageFactory.cs:234 
blazor.webassembly.js:1   at Amazon.Runtime.HttpRequestMessageFactory.CreateHttpClientCache (Amazon.Runtime.IClientConfig clientConfig) [0x00010] in D:\JenkinsWorkspaces\Stage-release-dry-run\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_netstandard\HttpRequestMessageFactory.cs:224 
blazor.webassembly.js:1   at Amazon.Runtime.HttpRequestMessageFactory.CreateHttpRequest (System.Uri requestUri) [0x000c5] in D:\JenkinsWorkspaces\Stage-release-dry-run\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_netstandard\HttpRequestMessageFactory.cs:170 
blazor.webassembly.js:1   at Amazon.Runtime.Internal.HttpHandler`1[TRequestContent].CreateWebRequest (Amazon.Runtime.IRequestContext requestContext) [0x0000e] in D:\JenkinsWorkspaces\Stage-release-dry-run\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:422 
blazor.webassembly.js:1   at Amazon.Runtime.Internal.HttpHandler`1[TRequestContent].InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x0003f] in D:\JenkinsWorkspaces\Stage-release-dry-run\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:148 
blazor.webassembly.js:1   at Amazon.Runtime.Internal.RedirectHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x00036] in D:\JenkinsWorkspaces\Stage-release-dry-run\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\RedirectHandler.cs:59 
blazor.webassembly.js:1   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x00034] in D:\JenkinsWorkspaces\Stage-release-dry-run\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\Unmarshaller.cs:85 
blazor.webassembly.js:1   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x0002d] in D:\JenkinsWorkspaces\Stage-release-dry-run\AWSDotNetPublic\sdk\src\Services\S3\Custom\Internal\AmazonS3ResponseHandler.cs:58 
blazor.webassembly.js:1   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x000a7] in D:\JenkinsWorkspaces\Stage-release-dry-run\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:107 
blazor.webassembly.js:1   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x00039] in D:\JenkinsWorkspaces\Stage-release-dry-run\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:61 
blazor.webassembly.js:1   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x00063] in D:\JenkinsWorkspaces\Stage-release-dry-run\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\EndpointDiscoveryHandler.cs:75 
blazor.webassembly.js:1   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x000d8] in D:\JenkinsWorkspaces\Stage-release-dry-run\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\EndpointDiscoveryHandler.cs:85 
blazor.webassembly.js:1   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x00113] in D:\JenkinsWorkspaces\Stage-release-dry-run\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CredentialsRetriever.cs:98 
blazor.webassembly.js:1   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x0006b] in D:\JenkinsWorkspaces\Stage-release-dry-run\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\RetryHandler\RetryHandler.cs:122 
blazor.webassembly.js:1   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x00194] in D:\JenkinsWorkspaces\Stage-release-dry-run\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\RetryHandler\RetryHandler.cs:137 
2blazor.webassembly.js:1   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x00039] in D:\JenkinsWorkspaces\Stage-release-dry-run\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:61 
blazor.webassembly.js:1   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x0008f] in D:\JenkinsWorkspaces\Stage-release-dry-run\AWSDotNetPublic\sdk\src\Services\S3\Custom\Internal\AmazonS3ExceptionHandler.cs:62 
blazor.webassembly.js:1   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x0008f] in D:\JenkinsWorkspaces\Stage-release-dry-run\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\ErrorCallbackHandler.cs:58 
blazor.webassembly.js:1   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T] (Amazon.Runtime.IExecutionContext executionContext) [0x00066] in D:\JenkinsWorkspaces\Stage-release-dry-run\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\MetricsHandler.cs:65 
blazor.webassembly.js:1   at Amazon.S3.Transfer.Internal.SimpleUploadCommand.ExecuteAsync (System.Threading.CancellationToken cancellationToken) [0x000bf] in D:\JenkinsWorkspaces\Stage-release-dry-run\AWSDotNetPublic\sdk\src\Services\S3\Custom\Transfer\Internal\_async\SimpleUploadCommand.async.cs:42

**Comment by elrhomariyounes** [comment]
Same issue with AWSSDK.S3 nuget

**Comment by nukec** [comment]
> Update:
> 
> the error detail I got now is:
> 
> **Unable to get IAM security credentials from EC2 Instance Metadata Service**

you resolved this?

**Comment by aaperfilev92** [comment]
Any updates? AllowAutoRedirect = false does not fix the situation.
