### ISSUE TITLE
S3 work fine with Unity Editor but don't work on android

### ISSUE THREAD

**Issue by hieutran196** [aws/aws-sdk-net#1500]
## Expected Behavior

Return object from bucket on Android
## Current Behavior

Don't return anything, no error appears, but return correct on Unity Editor.

## Steps to Reproduce (for bugs)

Step1: Download and import the newest version S3.

Step2: At Start() function. Add line code:
`UnityInitializer.AttachToGameObject(this.gameObject);`
`AWSConfigs.HttpClient = AWSConfigs.HttpClientOption.UnityWebRequest;`

Step3: In AndroidManifest, change line code from
`android:name="com.unity3d.player.UnityPlayerNativeActivity"`
to
`android:name="com.unity3d.player.UnityPlayerActivity"`
Because when I build with `"com.unity3d.player.UnityPlayerNativeActivity"`, app will crash when I open. And `"com.unity3d.player.UnityPlayerActivity"` will fix that.

So everything work fine in Editor, but when build for Android. It have no error and don't return anything.
## Context

Even when I Debug.Log in
 ` Client.ListBucketsAsync(new ListBucketsRequest(), (responseObject) =>`
` {`
`Debug.Log("Loggg here");`
 `});` => No log appear
## Your Environment

* AWSSDK.Core version used:  3.3.660.0
* Service assembly and version used: AWSSDK.S3.3.3.110.10
* Targeted .NET platform: NET 4.0
* Unity Version: 2019.2.6
* Build: Tested and error on both Mono and IL2CPP 
## .NET Core Info

* .NET Core version used for development: NET 4.0

## Please help, Am I missing any step setup S3 for Unity? Thanks !
[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
Hi @hieutran196,  work on Unity-related PRs are paused at this time.
 We encourage our users to use the .NET Standard 2.0 version of the AWS SDK for .NET which can be downloaded from NuGet or, as a .zip file, [here](https://sdk-for-net.amazonwebservices.com/latest/v3/aws-sdk-netstandard2.0.zip).
 The downloads of the last supported version of the AWS Mobile SDK for Unity, as well as its source code, will continue to be available to customers. However the AWS Mobile SDK for Unity will no longer be officially supported by the AWS SDK for .NET team.

You can read more at:
https://aws.amazon.com/blogs/developer/referencing-the-aws-sdk-for-net-standard-2-0-from-unity-xamarin-or-uwp/
https://aws.amazon.com/blogs/developer/aws-sdk-for-net-now-targets-net-standard-2-0/
https://github.com/aws/aws-sdk-net/projects/1
