### ISSUE TITLE
S3 problem using Amazon.Util.PaginatedResourceFactory

### ISSUE THREAD

**Issue by luizgustavogp** [aws/aws-sdk-net#1501]
I'm trying to use `PaginatedResourceFactory.Create<S3Object, ListObjectsRequest, ListObjectsResponse>` to get informations about S3 objects , but I'm receiving this exception: **System.ArgumentException: 'AmazonS3Client has no method called ListObjectsAsync'**
I'm using the same idea of the method **EnumerateFiles(string searchPattern, SearchOption searchOption)** from this [class ](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/S3/Custom/_bcl/IO/S3DirectoryInfo.cs)

## Expected Behavior
Get files from S3 using PaginatedResourceFactory

## Current Behavior
I'm receiving this exception **System.ArgumentException: 'AmazonS3Client has no method called ListObjectsAsync'** when I call the method **EnumerateFiles**.

## Steps to Reproduce (for bugs)
1- Install the lasted version of AWSS3 SDK
2- Use this method:

```
 public IEnumerable<S3FileInfo> EnumerateFiles(string searchPattern, SearchOption searchOption)
        {
            IEnumerable<S3FileInfo> files = null;
            var request = new ListObjectsRequest
            {
                BucketName = BucketName,
                Delimiter = "/",
                Prefix = S3Helper.EncodeKey(key)
            };

            files = new EnumerableConverter<S3Object, S3FileInfo>
                (((IEnumerable<S3Object>)(PaginatedResourceFactory.Create<S3Object, ListObjectsRequest, ListObjectsResponse>(new PaginatedResourceInfo()
                        .WithClient(S3Client)
                        .WithMethodName("ListObjectsAsync")
                        .WithRequest(request)
                        .WithItemListPropertyPath("S3Objects")
                        .WithTokenRequestPropertyPath("Marker")
                        .WithTokenResponsePropertyPath("NextMarker"))))
                    .Where(s3Object => !string.Equals(S3Helper.DecodeKey(s3Object.Key), key, StringComparison.Ordinal) && !s3Object.Key.EndsWith("\\", StringComparison.Ordinal)),
                    s3Object => new S3FileInfo(S3Client, BucketName, S3Helper.DecodeKey(s3Object.Key)));


            //handle if recursion is set
            if (searchOption == SearchOption.AllDirectories)
            {
                IEnumerable<S3DirectoryInfo> foldersToSearch = EnumerateDirectories();
                foreach (S3DirectoryInfo dir in foldersToSearch)
                {
                    files = files.Concat(dir.EnumerateFiles(searchPattern, searchOption));
                }
            }

            //filter based on search pattern
            var regEx = WildcardToRegex(searchPattern);
            files = files.Where(s3fileInfo => Regex.IsMatch(s3fileInfo.Name, regEx, RegexOptions.IgnoreCase));
            return files;
        }
```

3- Call the method 

## Context
I ported my current project to .Net Core. After ported it, I notice [these methods](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/S3/Custom/_bcl/IO/S3DirectoryInfo.cs) don't exist anymore. These methods are critical for my application and I tried to use the same idea of the old SDK.

## Your Environment
* AWSSDK.S3 version used: 3.3.110.11
* Operating System and version: Windows 10 Enterprise
* Visual Studio version: Microsoft Visual Studio Enterprise 2019
Version 16.4.2
* Targeted .NET platform: .NET Standard 2.0

## .NET Core Info

* .NET Core version used for development: 3.1.100
* .NET Core version installed in the environment where application runs:  3.1.100
* Output of `dotnet --info`:  SDK do .NET Core (refletindo qualquer global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Ambiente de runtime:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

**Comment by klaytaybai** [comment]
Hi @luizgustavogp, what is your use case?  You may be able to use the [TransferUtility](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/S3/Custom/_bcl%2Bnetstandard%2Bpcl/Transfer/_bcl%2Bnetstandard/TransferUtility.cs) to download files or the S3 [ListObjectsV2](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/S3/MS3ListObjectsV2ListObjectsV2Request.html) method to get file metadata.  Let us know if those aren't good options for you.

**Comment by klaytaybai** [comment]
Related issue: https://github.com/aws/aws-sdk-net/issues/1461

**Comment by luizgustavogp** [comment]
Hi @klaytaybai I need to get files metadata using a search pattern like this **"*.txt"** from a specific directory or all subdirectories. Another use case I need is to get all subdirectories metadata from a specific directory. Why AWS S3 SDK is handling this exception? Because I can see the ListObjectsAsync from  IAmazonS3.
