### ISSUE TITLE
How set a custom Region to AmazonS3Client ?  I need use "nl-ams" region from Scaleway

### ISSUE THREAD

**Issue by victorvhpg** [aws/aws-sdk-net#1502]
Scaleway has Object Storage Buckets are Amazon S3-compatible (https://www.scaleway.com/en/docs/object-storage-feature/). but don't works with this SDK.

    Region: nl-ams

    Endpoint: https://s3.nl-ams.scw.cloud

my code:

            string accessKey = "*********";
            string secretKey = "********"; 
            AmazonS3Config config = new AmazonS3Config() {
                ServiceURL = "https://s3.nl-ams.scw.cloud",  
            };
            AmazonS3Client client = new AmazonS3Client(accessKey, secretKey, config);
            string myBucketName = "images-app";
            var listObjectsResponse = await client.ListObjectsAsync(myBucketName);

error:
Unhandled exception. Amazon.S3.AmazonS3Exception: The authorization header is malformed; the region 'us-east-1' is wrong; expecting **'nl-ams'**

 
## .NET Core Info
 .NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.100/

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

**Comment by klaytaybai** [comment]
Thanks for raising this issue.  Unfortunately our policy is to not support competitors' S3-compatible services beyond what would be required to implement features or bug fixes for S3 and AWS customers.  This means that we have no plans to fix this at this time.

**Comment by christophedemey** [comment]
Hey @victorvhpg 
I have the same problem, did u manage to fix it ? What sdk are u using now ?

Thanks :)

**Comment by victorvhpg** [comment]
> 
> 
> Hey @victorvhpg
> I have the same problem, did u manage to fix it ? What sdk are u using now ?
> 
> Thanks :)

i using Minio
[https://github.com/minio/minio-dotnet](https://github.com/minio/minio-dotnet)
[https://stackoverflow.com/a/57971972](https://stackoverflow.com/a/57971972)

**Comment by boba2fett** [comment]
We have it working with another provider and a non aws region via

```
new AmazonS3Client(
                _configuration[S3ConfigurationConstants.AccessKey],
                _configuration[S3ConfigurationConstants.AccessSecret],
                new AmazonS3Config
                {
                    AuthenticationRegion = _configuration[S3ConfigurationConstants.Region],
                    ServiceURL = new UriBuilder(_configuration[S3ConfigurationConstants.Endpoint]) { Scheme = "https", Port = -1 }.Uri.AbsoluteUri,
                    ForcePathStyle = _configuration.GetValue<bool>(S3ConfigurationConstants.PathStyle),
                }
```
