### ISSUE TITLE
Breaking changes in 3.3.110 onwards in S3

### ISSUE THREAD

**Issue by phillip-haydon** [aws/aws-sdk-net#1503]
Something has changed between 3.3.109.4 and 3.3.110

I got an email from AWS saying we are using an old version of the S3 SDK. So I upgraded and it's caused alot of pain.

I went from 3.3.106.2, all the way to 3.3.110.12, and it caused an outage. 

I then proceeded to try:

3.3.106.2 - OK 300-500ms
3.3.107 - OK 300-500ms
3.3.108 - OK 300-500ms
3.3.109 - OK 300-500ms
3.3.109.4 - OK 300-500ms (December 12 release)
3.3.110 - BAD (every request > 2.5s) (December 13 release)
3.3.110.12 - BAD (every request > 2.5s)

(the high latency Singapore to Oregon)

The version of Core is the latest one (3.3.104.16) for all the tested versions above. So I believe it's isolated to JUST the S3 assembly. 

## Expected Behavior
Should be fast to create expiring urls.

## Current Behavior
I'm unsure which part has gotten slow, but between creating the client and generating the url, it's slow.

## Possible Solution
I can't find the changes between the 2 versions.

## Steps to Reproduce (for bugs)
In a loop, create an instance of S3 client (inside the loop), and generate an expiring url. 

## Context
This is causing requests in IIS to queue up and take 2+ seconds, as they queue up they begin to take longer and longer until they take the site offline due to 100% CPU usage.

## Your Environment
Windows 10 / Windows Server 2019
.NET Core 4.8
AWSSDK.Core (any)
AWSSDK.S3 3.3.110 onward

**Comment by normj** [comment]
What do you mean by generating expiring urls? Could you share you test code?

**Comment by phillip-haydon** [comment]
```
            var preSignedRequest = new GetPreSignedUrlRequest
            {
                BucketName = request.Bucket,
                Expires = expiresAt,
                Protocol = Protocol.HTTPS,
                Verb = HttpVerb.GET,
                ResponseHeaderOverrides = responseHeaderOverrides,
                Key = request.Key
            };

            return client?.GetPreSignedURL(preSignedRequest);
```

**Comment by normj** [comment]
I'm still confused where you are saying the performance problem is. I ran the following code but I don't think that matches your use case. I assume you are doing more then just generating presigned urls.

```csharp
using System;
using System.Timers;
using Amazon;
using Amazon.S3;
using Amazon.S3.Model;

namespace PresignedUrlPerfTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var bucketName = "normj-east1";
            var key = "foo.txt";
            var expiresAt = DateTime.UtcNow.AddDays(2);
            var responseHeaderOverrides = new ResponseHeaderOverrides();

            for (int i = 0; i < 20; i++)
            {
                long start = DateTime.Now.Ticks;
                using (var client = new AmazonS3Client(RegionEndpoint.USEast1))
                {
                    var preSignedRequest = new GetPreSignedUrlRequest
                    {
                        BucketName = bucketName,
                        Expires = expiresAt,
                        Protocol = Protocol.HTTPS,
                        Verb = HttpVerb.GET,
                        ResponseHeaderOverrides = responseHeaderOverrides,
                        Key = key
                    };

                    client?.GetPreSignedURL(preSignedRequest);

                    var ts = TimeSpan.FromTicks(DateTime.Now.Ticks - start);
                    Console.WriteLine(ts.TotalMilliseconds);
                }
            }

        }
    }
}

Output:
303.4075
53.0682
53.9938
61.9881
59.2487
50.0861
59.5925
64.6751
61.6231
53.1234
55.4105
57.6939
69.2217
66.7349
54.8913
54.1831
54.2444
53.6534
59.5503
60.9307
```

**Comment by phillip-haydon** [comment]
It's getting late here in Singapore so I need to head home. I'm gonna throw some logging in tomorrow and triple verify that it's the S3Client. So far my assumption is based on Raygun APM + the performance impact only on web pages using the s3 client. 

Please bare with it :D

**Comment by klaytaybai** [comment]
@phillip-haydon, which means of providing credentials are you using and which region are you using?

**Comment by phillip-haydon** [comment]
So the server has a Role for access to AWS Services, but when it comes S3, there are multiple buckets in different accounts, so it uses ID/Secret to authenticate.


```csharp
var regionEndpoint = RegionEndpoint.GetBySystemName(credentials.Region); // e.g "us-west-2"
var config = new AmazonS3Config { RegionEndpoint = regionEndpoint, Timeout = timeout };

var client= new AmazonS3Client(credentials.User, credentials.Password, config);
```


So it creates the s3 client over and over as there's many buckets and credentials.

**Comment by assyadh** [comment]
I have a fix in that I think will solve this. Will let you know when it is released

**Comment by assyadh** [comment]
Hi,

Thanks for reporting the issue, I got a fix in, will let you know when it is available.

H.

**Comment by phillip-haydon** [comment]
Hey @assyadh what was/is the issue if you don't mind me asking.

**Comment by assyadh** [comment]
> Hey @assyadh what was/is the issue if you don't mind me asking.

Hi @phillip-haydon, We released 3.3.110.15 yesterday, but it is not fixing the problem, and potentially making it worse.

Please **do not** consume this version, we are working on rolling forward a new fix.

**Comment by assyadh** [comment]
Hi @phillip-haydon, 3.3.110.17 should fix your issue.

You can have a look at https://github.com/aws/aws-sdk-net/commit/94dfb83fa5eaa6e29ac89e505e233869589ef188 if you want to see how the issue was fixed.

https://www.nuget.org/packages/AWSSDK.S3/3.3.110.17

**Comment by phillip-haydon** [comment]
@assyadh I just updated the project and it doesn't appear to have helped. The change looks like it only applies to 1 scenario for us-east-1?

All the regions I'm using are:

```
ap-northeast-1
ap-southeast-1
ap-southeast-2
cn-north-1
eu-central-1
eu-west-1
eu-west-2
sa-east-1
us-west-2
```

**Comment by assyadh** [comment]
Cool, thanks for letting me know, I was wondering what could have went wrong 👍
