### ISSUE TITLE
Updating from NuGet AWSSDK.Core 3.3.101 to 3.3.101.1 or newer causes my aws call to fail with 403

### ISSUE THREAD

**Issue by Zorgle** [aws/aws-sdk-net#1504]
I did a binary search of the NuGet versions for NuGet AWSSDK.Core to find exactly when the breakage occurs to me.

I can connect and describe S3 buckets successfully up to 3.3.101, but if I update to anything newer (even just 3.3.101.1), then I get 403 errors at my first command.

Inmost exception message: The remote server returned an error: (403) Forbidden.
HRESULT: -2146233079

Middle exception message: The remote server returned an error: (403) Forbidden.
HRESULT: -2146233088

Outer exception message: The AWS Access Key Id you provided does not exist in our records.
HRESULT: -2146233088

I did my binary search through NuGet AWSSDK.Core versions to find the breaking point without changing anything in my code at all, just switching the installed version and testing each time.

Exception occurs at my first call for data, which is an s3 ListBuckets call, like this:

Amazon.S3.AmazonS3Client s3 = …
s3.ListBuckets();  // <- 403 exception

If I revise my code so my first actual call is an ec2.DescribeVps() call, I get the same result

Amazon.EC2.AmazonEC2Client ec2 = …
foreach … ec2.DescribeVpcs().Vpcs    // <- 403 exception

## Your Environment

* AWSSDK.Core version used: 3.3.101.1
* Service assembly and version used: ? (Don't know what this means)
* Operating System and version: Windows 10
* Visual Studio version: Visual Studio 2017
* Targeted .NET platform: .NET 4.8
I am using config & credential files, and have verified the AWS keys multiple times --plus of course they work when I set the Core version to 3.3.101.

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
Hello @Zorgle, we're sorry to hear that.  I'm not sure why that would be happening.  It may require some time to investigate.  Could you please let us know why you are using 3.3.101.1?  This version is quite old.  There may have already been a fix for your problem months ago.

**Comment by Zorgle** [comment]
I'm not using 3.3.101.1, actually, because that one, and all newer ones, cause 403 and nothing works for me.

I was trying to use the current version, but it broke it (causes 403s), so I searched all the versions from current way back, using a binary search, to find out where the broken behavior began, and it begins with 3.3.101.1 (as far as my tests show).

So I'm actually using 3.3.101, because that is the last version that works (for me).

I tried to use the web site to look through the commits to see what changed between 3.3.101 and 3.3.101.1, but you can only see a few commits at a time, and I didn't see any way to jump back, and that is many commits back, so I didn't see any way to get to the commits for that range.

**Comment by Zorgle** [comment]
Let me try to explain more clearly how I found it.

I don't have the exact numbers before me, and I don't remember them exactly, so these are illustrative.

When it didn't work with 3.3.103, but it did work with 3.3.29, then executed a process of choosing a version between them and testing, and going either up (if it worked) or down (if it failed). (You probably recognize this algorithm.)

I tried 3.3.100, and it worked.
I tried 3.3.103, and it failed.
I tried 3.3.101, and it worked.
I tried 3.3.102, and it failed.
I tried 3.3.101.10, and it failed.
I tried 3.3.101.5, and it failed.
I tried 3.3.101.3, and it failed.
I tried 3.3.101.2, and it failed.
I tried 3.3.101.1, and it failed.
I tried 3.3.100 (again), and it worked.
I tried 3.3.101.1 (again), and it failed.

I repeated the last tests several times to make sure they were repeatable.

I drew the conclusion that a change between 3.3.101 and 3.3.101.1 causes my code to fail.

**Comment by Zorgle** [comment]
I tried to find the differences by git cloning the repository from https://github.com/aws/aws-sdk-net.git

However, after I do that, my git log shows 3.3.101.0 committed 2017-06-06 by Norm Johanson, and 3.3.102.0 committed the next day, 2017-06-07, by Steven Kang.

I do not see 3.3.101.1, 3.3.101.2, ... 3.3.101.18, which are the versions I tested with through the Visual Studio Tools > NuGet Package Manager > Updates interface. 

I just checked that interface again, and I can see those versions for AWSSDK.Core.

So I guess that my git clone is not of the correct repository?

**Comment by klaytaybai** [comment]
When you say "first" call, are you implying that future calls with the same client work?

**Comment by Zorgle** [comment]
Oops, no, sorry. First and any subsequent calls fail, if 3.3.101.1 or newer. If older, all calls work.

**Comment by klaytaybai** [comment]
Can you please provide us with the following:

- Sample project?
- type of aws credentials (e.g. Assume Role, Basic, Cognito, etc) and sample means of setting your credentials (Are you using an empty client constructor)
- region that you think you are using
- ways that you set your region
- are you trying to set your own service url
- Where is your code running?


We're not really sure why 3.3.101.1 would have had any impact

**Comment by mechanic22** [comment]
Is this the same issue as https://github.com/aws/aws-sdk-net/issues/933

**Comment by Zorgle** [comment]
I clicked the link, and issue#933 looks like it is tied to S3 signing, and
my issue is a failure to access even EC2, so I doubt that it is the same
issue.

If I just click reply to this email, does this work successfully, to answer
these questions?

I don't recall how to find this issue on the web.

**Comment by klaytaybai** [comment]
I didn't think so either.  I'm still very confused about this issue though.  We might need you to provide a failing sample app to look into reproducing it.

Can you try with a new, clean project and see if you can make calls successfully with the newer versions?  

Also, yes, replying to the email will also update the GitHub post.  You can easily navigate to the post by clicking on the "view it on GitHub" link in the email or by going to [https://github.com/aws/aws-sdk-net/issues/1504](https://github.com/aws/aws-sdk-net/issues/1504) directly.

**Comment by Zorgle** [comment]
I made a copy of my code, and tried to delete out all the code that
actually does anything with any of the data, and deleted all logging,
deleted all configuration handling, and deleted all exception handling, to
try to get to a very bare skeleton.

It still crashes at the first call if I advance it to 3.3.101.1, but works
if I leave it at 3.3.101.

Is there a way I can deliver a zip of the project source code to you?

It is a Visual Studio 2017 C# Console Mode application.

**Comment by Zorgle** [comment]
Is there a way I can deliver a zip of the project code to you, without posting it publicly?

**Comment by Zorgle** [comment]
(Just checking to see if there is any response on this.)

**Comment by Zorgle** [comment]
Let me know if you find time or interest to see the code, and if there is some way to get it to you.

**Comment by Zorgle** [comment]
Just tested with the latest available NuGet packages (AWSSDK.Core 3.3.106.21, etc), and this problem still occurs exactly the same way, so I reverted back to 3.3.101 again.

Any ideas of what could be causing the authorization to break beyond 3.3.101, or anything I could do?

**Comment by Zorgle** [comment]
Also, I was unable to find the source code for the changes from 3.3.101 to 3.3.101.1, which appear to be the breaking changes. Anyone know how to find those changes? (Details of my failure to find them in a clone of the git source are above in my Jan 18 comment.)

**Comment by Zorgle** [comment]
Here is single file demo source code, in case that helps.

Succeeds with 3.3.101, fails with anything newer:


`using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AwsTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var progr = new Program();
            progr.DoMain(args);
            Console.WriteLine("Success");
            Console.WriteLine("Press key to continue");
            var key = Console.ReadKey();
        }
        public void DoMain(string[] args)
        {
            int test = 0;
            if (args.Length > 0)
            {
                int.TryParse(args[0], out test);
            }
            var profileName = System.Configuration.ConfigurationManager.AppSettings["AwsProfileName"];
            foreach (var region in GetRegions())
            {
                try
                {
                    if (test == 0)
                    {
                        var cred = GetCredentials0(profileName);
                        var client = GetS3Client(region, cred);
                        var rsp = client.ListBuckets();
                    }
                    if (test == 1)
                    {
                        var cred = GetCredentials1(profileName);
                        var client = GetS3Client(region, cred);
                        var rsp = client.ListBuckets();
                    }
                    if (test == 2)
                    {
                        var cred = GetCredentials0(profileName);
                        var client = GetEc2Client(region, cred);
                        var rsp = client.DescribeInstances();
                    }
                }
                catch (Exception exc)
                {
                    Console.WriteLine($"Failure in region {region.SystemName}: {exc.ToString()}");
                    Console.WriteLine("Press key to continue");
                    var key = Console.ReadKey();
                    Environment.Exit(1);
                }
                Console.WriteLine($"Region {region.SystemName} succeeded");
            }
        }
        private Amazon.Runtime.AWSCredentials GetCredentials0(string profileName)
        {
            var c = Amazon.Util.ProfileManager.GetProfile(profileName);
            var creds = Amazon.Util.ProfileManager.GetAWSCredentials(profileName);
            return creds;
        }
        private Amazon.Runtime.AWSCredentials GetCredentials1(string profileName)
        {
            Amazon.Runtime.CredentialManagement.CredentialProfile profile = null;
            Amazon.Runtime.AWSCredentials awsCredentials = null;
            var sharedFile = new Amazon.Runtime.CredentialManagement.SharedCredentialsFile();
            if (sharedFile.TryGetProfile(profileName, out profile))
            {
                if (Amazon.Runtime.CredentialManagement.AWSCredentialsFactory.TryGetAWSCredentials(profile, sharedFile, out awsCredentials))
                {
                    return awsCredentials;
                }
                else
                {
                    throw new Exception($"TryGetAWSCredentials failed to find profile '{profile}'");
                }
            }
            else
            {
                throw new Exception($"SharedCredentialsFile.TryGetProfile failed to find profile ;{profile}'");
            }
        }
        private Amazon.S3.AmazonS3Client GetS3Client(Amazon.RegionEndpoint region, Amazon.Runtime.AWSCredentials cred)
        {
            var client = new Amazon.S3.AmazonS3Client(cred, region);
            return client;

        }
        private Amazon.EC2.AmazonEC2Client GetEc2Client(Amazon.RegionEndpoint region, Amazon.Runtime.AWSCredentials cred)
        {
            var client = new Amazon.EC2.AmazonEC2Client(cred, region);
            return client;
        }
        private IEnumerable<Amazon.RegionEndpoint> GetRegions()
        {
            var list = new List<Amazon.RegionEndpoint>();
            foreach (var regionEndpoint in Amazon.RegionEndpoint.EnumerableAllRegions)
            {
                if (regionEndpoint == Amazon.RegionEndpoint.USGovCloudWest1) { continue; }
                if (regionEndpoint == Amazon.RegionEndpoint.USGovCloudEast1) { continue; }
                if (regionEndpoint.SystemName.StartsWith("cn-")) { continue; } // China
                list.Add(regionEndpoint);
            }
            var list2 = list.OrderBy(r => r.SystemName);
            return list2;
        }

    }
}
`

**Comment by ashishdhingra** [comment]
Hi @Zorgle,

I tried using you code above (with minor changes to use `ListBucketsAsync` and `DescribeInstancesAsync`) with the following SDK versions:
- AWSSDK.Core 3.5.1.33
- AWSSDK.S3 3.5.3.11
- AWSSDK.EC2 3.5.14

The code executes successfully for all regions, except for the following regions (`ListBucketsAsync` fails with the error `The provided token is malformed or otherwise invalid.` and `DescribeInstancesAsync` fails with `AWS was not able to validate the provided access credentials`):
- af-south-1
- ap-east-1
- eu-south-1
- me-south-1

In AWS Console, when I try to switch to these regions, it displays some prompt, which indicates that these might be some special regions.

The code hangs for the regions `us-iso-east-1` and `us-isob-east-1`, which are not even listed in AWS Console.

Could you try executing your code with the latest AWSSDK versions and check if the issue is resolved? I'm unable to reproduce the issue with the latest SDK versions and any access denied or forbidden issues indicate the probably problem with your AWS Account having insufficient access.

Thanks,
Ashish

**Comment by Zorgle** [comment]
After waiting many months with no response, I quit checking this any more, so I missed that it finally got a response, and then apparently got closed because I didn't respond quickly enough. Kind of entertaining irony.
