### ISSUE TITLE
 Retries resulting from provisioned capacity exceptions should not be throttled.

### ISSUE THREAD

**Issue by nikolai-kosolapov** [aws/aws-sdk-net#1505]
In accordance with:
https://aws.amazon.com/blogs/developer/introducing-retry-throttling/

https://github.com/aws/aws-sdk-net/blob/40fbe04bd50fd0718fc0804fbf2d0b68b89122c2/sdk/src/Core/Amazon.Runtime/Pipeline/RetryHandler/DefaultRetryPolicy.cs#L200

**Comment by klaytaybai** [comment]
Thanks for the feedback. We’re looking into the retry logic.  As we work on it, we’ll try to check for this and reach out if we have more questions.
