### ISSUE TITLE
Aws Lambda getting Signature expired when try to access SimpleSystemsManagement

### ISSUE THREAD

**Issue by matheusmaximo** [aws/aws-sdk-net#1506]
Hello,

I have a Lambda that accesses an API Gateway, which triggers a second Lambda, and this second Lambda tries to retrieve some information from SSM.

## Expected Behavior
I was expecting the second Lambda to get the information successfully.

## Current Behavior
Eventually and intermittently it fails with a `Signature expired` exception.
This is the second Lambda stack error:

> [Error 4eadcd85-2a3c-ea11-8218-00155d930efa ] Signature expired: 20200121T084217Z is now earlier than 20200121T084217Z (20200121T084717Z - 5 min.)
Amazon.SimpleSystemsManagement.AmazonSimpleSystemsManagementException: Signature expired: 20200121T084217Z is now earlier than 20200121T084217Z (20200121T084717Z - 5 min.) ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
>

I have a retry implemented in the first Lambda so that it retries again and eventually (for this specific situation, after 4 times) it works.

## Possible Solution
I guess this is something related to Clockscrew but I have no idea how to figure out that.

## Steps to Reproduce (for bugs)
Unfortunately, basic of the intermittence I couldn't reproduce it.

## Context
I have some alerts for Lambdas. Whenever we get an issue reported in logs, we are alerted.
As this is not something that we can fix, it is causing us to treat it as a false-positive alert but we still get time to investigate and find the issue reported.

## Your Environment
* AWSSDK.Core version used: The most up to date available
* Service assembly and version used: Lambda and Amazon SimpleSystemsManagement
* Operating System and version: The Lambda one
* Visual Studio version: VS Professional 2019
* Targeted .NET platform: 2.1

## .NET Core Info
* .NET Core version used for development: 2.1

**Comment by klaytaybai** [comment]
Hi @matheusmaximo, I think we're going to need some more details if we are to determine if its an issue with the SDK.  If you think it's an issue with the SDK, sample code and more logs would be helpful.

Most likely the issue is due to misconfigured credentials, a role permission, or code causing your Lambda to run for so long that the credentials expire.  Please check your related settings and determine if they seem appropriate.  You may also want to check that your use case requires temporary credentials on your 2nd Lambda.

**Comment by matheusmaximo** [comment]
Hi @klaytaybai !

Thanks for replying back.

Unfortunately, I'm unable to provide a sample code as this error is intermittent. Sometimes it happens, sometimes it doesn't.

A bit more of the solution: we have a "warm up" rule in place. Every 5 minutes, a CloudWatch Event Schedule triggers my 2nd Lambda to keep it warm. I have noticed that this issue happens when I take more than 30 minutes with that warm Lambda and try to access SimpleSystemsManagement.

Regards the operation on the 2nd Lambda, I do more interactions with Amazon "as taking a token from Cognito" before getting that fail. However, it ever happens when I'm trying to connect to "SimpleSystemsManagement".

Would the credentials to access SimpleSystemsManagement be valid for only 30 minutes?

**Comment by matheusmaximo** [comment]
Sorry, I just took another look in the logs and I got some executions that had succeeded even after the Lambda been kept warm for more than 1 hour.
It looks more related to some sort of synchronisation issue on the Lambda instance that is affecting only SimpleSystemsManagement. Once that instance is out of synchronisation, no other requests to SSM works and that stands until we have a Lambda clean up.

**Comment by matheusmaximo** [comment]
I have a different project with the same issue now. The sad thing on this is we can do nothing other than waiting for the Lambda instance to eventually make its way off and the new instance to come up. :(

**Comment by kamonson** [comment]
Have you had any traction on this @matheusmaximo ?

I am experiencing a similar issue:

----- Inner Stack Trace -----
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ExceptionHandler`1.Handle(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Extensions.CognitoAuthentication.CognitoUser.StartWithSrpAuthAsync(InitiateSrpAuthRequest srpRequest)

for me the error comes from trying to validate a user in cognito, this line pulled from the docs (https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/cognito-authentication-extension.html):

AuthFlowResponse authResponse = await user.StartWithSrpAuthAsync(authRequest).ConfigureAwait(false);

will get periodic errors, I have also had a hard time tracking this down.  In my case I am grabbing the IdToken to make a series of API calls.

**Comment by matheusmaximo** [comment]
I'm still waiting for some reply from Amazon. @kamonson 
When that happens, we just wait for the Lambda to sleep and call it again.

**Comment by normj** [comment]
@matheusmaximo Are you doing anything special with getting credentials for your SSM service client or are you creating the client without credentials and rely on the client to find the credentials for the attached IAM Role?

**Comment by matheusmaximo** [comment]
Hi @normj , thanks for your time replying me!

I'm using Dependency Injection in my Lambdas. I'm using the .Net Core default IoC.
So to create the instance of SSM we do this:

`services.AddAWSService<IAmazonSimpleSystemsManagement>();`

And then I get that error when I execute this line of code:

`await _client.GetParametersByPathAsync(request);`

Thanks,
Matheus

**Comment by matheusmaximo** [comment]
@normj may I assume that is the issue and I should start using `services.AddSingleton<IAmazonSimpleSystemsManagement, AmazonSimpleSystemsManagementClient>();` instead?

**Comment by manichosolar** [comment]
I had the same "signature expired" using a .NET console calling an AWS service from my PC. What it worked to me was to change my local PC time using the Windows clock button "update now" from time.windows.com, setting an incorrect time -according to me- probably because of daylight saving. My clock is one hour ahead, but the application now works perfectly. Probably there are time-zone issues on your computer/server/VM.

**Comment by matheusmaximo** [comment]
Hi @manichosolar , thanks for your suggestion but actually my code is running into an AWS Lambda function, nothing related to my computer. So I think this may be not my issue.

**Comment by abhishekshankar891** [comment]
Hi 
I wrote a lambda function which fetches csv as dataframe from s3 and return a concatenated dataframe which needs to be uploaded back to s3. But i got this error "Calling the invoke API action failed with this message: Signature expired: 20200417T062349Z is now earlier than 20200417T063349Z (20200417T063849Z - 5 min.)"

My basic setting : Timeout 15 min ,Memory 256 MB . I searched in google and found time sync can resolve this issue. It would be great if someone provides detailed steps or another solution to the problem.

Thanks,
Abhishek

**Comment by uncle-scooter** [comment]
Currently experiencing the same exact thing on transnational processing using SQS with lambdas. My current theory is that it has to do with latecy between talking to AWS services from the sdk. We are making calls to dynamo, sqs, and iot. 

I spent several hours on a chat with AWS business support and they recommended me wrap all calls to external services with logs so you can find the high latency calls and adjust. 

But this was just the theory we came up with.

**Comment by dkrusia** [comment]
I am experiencing the same issue.  Every 30 minutes to an hour it happens.  My gut feeling is that it is related to garbage collection.  I think that the GC thread uses the time in an older request, which has time expired.

I got .net core 2.1 package deployed in aws lambda.

Also, I read on other thread that "Signature expired: 20200417T062349Z is now earlier than 20200417T063349Z (20200417T063849Z - 5 min.)" is due to the server clock out of sync.  However, first of all we can not the lambda container's system time.  And, based on my debugging, this may not be the case in the above situation.

**Comment by abhishekshankar891** [comment]
Hi ,I increased the ram to 500 MB and was able to get rid of the situation and timeout to 15 mins(Max).Please try and let me know .Thanks ,Abhishek On May 15, 2020 8:13 PM, dkrusia <notifications@github.com> wrote:
I am experiencing the same issue.  Every 30 minutes to an hour it happens.  My gut feeling is that it is related to garbage collection.  I think that the GC thread uses the time in an older request, which has time expired.
I got .net core 2.1 package deployed in aws lambda.
Also, I read on other thread that "Signature expired: 20200417T062349Z is now earlier than 20200417T063349Z (20200417T063849Z - 5 min.)" is due to the server clock out of sync.  However, first of all we can not the lambda container's system time.  And, based on my debugging, this may not be the case in the above situation.

**Comment by matheusmaximo** [comment]
It just happens again Today:

> Signature expired: 20200525T141839Z is now earlier than 20200525T141840Z (20200525T142340Z - 5 min.)
> Amazon.SimpleSystemsManagement.AmazonSimpleSystemsManagementException: Signature expired: 20200525T141839Z is now earlier than 20200525T141840Z (20200525T142340Z - 5 min.) ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
>    at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
>    at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
>    --- End of inner exception stack trace ---
>    at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
>    at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
>    at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)

**Comment by DamirAinullin** [comment]
I also have this issue in Lambda function on getting configuration parameters from SSM.
We use .net core 3.1. Seems like it happens exaclty after 30 minutes of lambda-instance running.

```
"exceptions": [
        {
            "Depth": 0,
            "ClassName": "Amazon.SimpleSystemsManagement.AmazonSimpleSystemsManagementException",
            "Message": "Signature expired: 20200605T190617Z is now earlier than 20200605T190617Z (20200605T191117Z - 5 min.)",
            "Source": "AWSSDK.Core",
            "StackTrace": [
                "   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)",
                "   at Amazon.Runtime.Internal.ExceptionHandler`1.Handle(IExecutionContext executionContext, Exception exception)",
                "   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)",
                "   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Extensions.Configuration.SystemsManager.Internal.SystemsManagerProcessor.GetParametersByPathAsync()",
                "   at Amazon.Extensions.Configuration.SystemsManager.Internal.SystemsManagerProcessor.GetDataAsync()",
                "   at Amazon.Extensions.Configuration.SystemsManager.SystemsManagerConfigurationProvider.LoadAsync(Boolean reload)"
            ],
            "RemoteStackTrace": [
                "   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)",
                "   at Amazon.Runtime.Internal.ExceptionHandler`1.Handle(IExecutionContext executionContext, Exception exception)",
                "   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)",
                "   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Extensions.Configuration.SystemsManager.Internal.SystemsManagerProcessor.GetParametersByPathAsync()",
                "   at Amazon.Extensions.Configuration.SystemsManager.Internal.SystemsManagerProcessor.GetDataAsync()",
                "   at Amazon.Extensions.Configuration.SystemsManager.SystemsManagerConfigurationProvider.LoadAsync(Boolean reload)"
            ],
            "RemoteStackIndex": 0,
            "HResult": -2146233088,
            "HelpURL": null
        },
        {
            "Depth": 1,
            "ClassName": "Amazon.Runtime.Internal.HttpErrorResponseException",
            "Message": "Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.",
            "Source": "AWSSDK.Core",
            "StackTrace": [
                "   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)",
                "   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)"
            ],
            "RemoteStackTrace": [
                "   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)",
                "   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)"
            ],
            "RemoteStackIndex": 0,
            "HResult": -2146233088,
            "HelpURL": null
        }
    ]
```

Do you know the reason of this issue or at least any workarounds?

**Comment by abhishekshankar891** [comment]
Hi ,I tried with increasing time out to max 15 mins and ram allocation  to 512 mb. This worked for me as my code execution time was on higher side . Hope it helps .Thanks On Jun 6, 2020 1:45 AM, Damir Ainullin <notifications@github.com> wrote:
I also have this issue in Lambda function on getting configuration parameters from SSM.
We use .net core 3.1. Seems like it happens exaclty after 30 minutes of lambda-instance running.
"exceptions": [
        {
            "Depth": 0,
            "ClassName": "Amazon.SimpleSystemsManagement.AmazonSimpleSystemsManagementException",
            "Message": "Signature expired: 20200605T190617Z is now earlier than 20200605T190617Z (20200605T191117Z - 5 min.)",
            "Source": "AWSSDK.Core",
            "StackTrace": [
                "   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)",
                "   at Amazon.Runtime.Internal.ExceptionHandler`1.Handle(IExecutionContext executionContext, Exception exception)",
                "   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)",
                "   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Extensions.Configuration.SystemsManager.Internal.SystemsManagerProcessor.GetParametersByPathAsync()",
                "   at Amazon.Extensions.Configuration.SystemsManager.Internal.SystemsManagerProcessor.GetDataAsync()",
                "   at Amazon.Extensions.Configuration.SystemsManager.SystemsManagerConfigurationProvider.LoadAsync(Boolean reload)"
            ],
            "RemoteStackTrace": [
                "   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)",
                "   at Amazon.Runtime.Internal.ExceptionHandler`1.Handle(IExecutionContext executionContext, Exception exception)",
                "   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)",
                "   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Extensions.Configuration.SystemsManager.Internal.SystemsManagerProcessor.GetParametersByPathAsync()",
                "   at Amazon.Extensions.Configuration.SystemsManager.Internal.SystemsManagerProcessor.GetDataAsync()",
                "   at Amazon.Extensions.Configuration.SystemsManager.SystemsManagerConfigurationProvider.LoadAsync(Boolean reload)"
            ],
            "RemoteStackIndex": 0,
            "HResult": -2146233088,
            "HelpURL": null
        },
        {
            "Depth": 1,
            "ClassName": "Amazon.Runtime.Internal.HttpErrorResponseException",
            "Message": "Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.",
            "Source": "AWSSDK.Core",
            "StackTrace": [
                "   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)",
                "   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)"
            ],
            "RemoteStackTrace": [
                "   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)",
                "   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)",
                "   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)"
            ],
            "RemoteStackIndex": 0,
            "HResult": -2146233088,
            "HelpURL": null
        }
    ]

Do you know the reason of this issue or at least any workarounds?

**Comment by ashishdhingra** [comment]
Hi @matheusmaximo,

Good afternoon.

I was going through the issue backlog and came across this issue. I do see that @abhishekshankar891 provided some input. Please confirm if this issue could be closed.

Thanks,
Ashish

**Comment by matheusmaximo** [comment]
We contacted AWS Premium support and we were advised to use ResignRetries parameter. Since then, we have no more issues. I'm not sure if that's an acceptable solution for this issue. If so, I'm happy to close it.

**Comment by SaidDev10** [comment]
Hi guys,
I had excatly the same issue too.
To fix it, I needed create in the VPC the endpoint 'com.amazonaws.eu-west-1.ssm' and select the security group associated to my lambda. 

I hope it helps.
