### ISSUE TITLE
Code with Creative Commons license strong copyleft

### ISSUE THREAD

**Issue by bmorenc** [aws/aws-sdk-net#1508]
[src/Core/Amazon.Runtime/Internal/Util/_mobile/AsyncHelpers.cs](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Internal/Util/_mobile/AsyncHelpers.cs) has copied code from stackoverflow carrying the Creative Commons Attribution-ShareAlike 3.0 (http://creativecommons.org/licenses/by-sa/3.0/) license.  This license carries a strong copyleft effect which to my understanding (I am not a lawyer) means that the entire AWS SDK for .NET and any consuming use of the same must be CCASA licensed.   

Thank you for your help

## Expected Behavior

All Apache 2.0 as declared

## Possible Solution

If AWS desires this SDK to be Apache 2.0, this code needs to be removed and replaced with an independent implementation.  Is there a documented exception somewhere?

## Steps to Reproduce (for bugs)

N/A

## Context

Our license clearing team has flagged this as incompatible with our commercial EULA.

## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
@bmorenc, thank you for raising this.  I'll send this over to our legal team to review immediately.  The license provides mechanisms for exemptions.  I haven't read into them fully yet, but we may meet those criteria.  If we find that we are violating the license, we'll try to publish a valid version as soon as we can.  Thanks

**Comment by MarkAtwood** [comment]
Hello bmorenc  please email me at atwoodm@amazon.com

**Comment by bmorenc** [comment]
@MarkAtwood email sent.

**Comment by klaytaybai** [comment]
Thank you again for alerting us to this.  I'm going to close this out now as an approved resolution was made in the linked pull request.
