### ISSUE TITLE
Setting non-user metadata on PutObjectAsync

### ISSUE THREAD

**Issue by pikhtaras-sp** [aws/aws-sdk-net#1509]
Hi. I want to set Cache-Control metadata on image when uploading it with PutObjectAsync. I do add it by `request.Metadata.Add("Cache-Control", "no-cache")`, but it gets saved as `x-amz-meta-cache-control`. I understand that it's expected behaviour, but wondering whether there is a way to set the Metadata as Cache-Control. Thank you.

**Comment by klaytaybai** [comment]
Hi @pikhtaras-sp, the most simple way you can set Cache-Control without the x-amz-meta prefix is doing`putObjectRequest.Headers.CacheControl = "no-cache";`. You may also adjust this header and others by intercepting the request before it is sent by creating a handler for the client.BeforeRequestEvent.
