### ISSUE TITLE
Delimiter is not working properly for ListObjectsRequest

### ISSUE THREAD

**Issue by l1x** [aws/aws-sdk-net#1513]
Delimiter is not working properly for ListObjectsRequest

## Expected Behavior

I expect Delimiter to be functional.

## Current Behavior

```
aws --profile xxx s3 ls s3://yyyy/tmp/test1/ --recursive
2020-01-29 20:36:04          0 tmp/test1/
2020-01-29 20:36:11          0 tmp/test1/test2/
2020-01-29 20:37:00     698600 tmp/test1/test2/49442611463_5a23408a04_k.jpg
2020-01-29 20:36:18          0 tmp/test1/test3/
```

```Python
def list_objects_in_s3(s3_client, filters):
    '''This must be a generator'''
    paginator = s3_client.get_paginator('list_objects')
    page_iterator = paginator.paginate(
      **filters,
      PaginationConfig={'MaxItems': 10000, 'PageSize': 50}
    )
    ret = []
    for page in page_iterator:
        logging.debug(page)
        if page.get('CommonPrefixes',[]):
            for content in page.get('CommonPrefixes'):
                ret.append(content['Prefix'])
    return ret

partition_filter = { 'Bucket': 'xxx',
                         'Prefix': 'tmp/test1/',
                         'Delimiter': '/' }
partitions = list_objects_in_s3(s3_client, partition_filter)
logging.info(partitions)
```

```bash
python test.py
2020-01-30 16:58:47 INFO ['tmp/test1/test2/', 'tmp/test1/test3/']
```

```Fsharp
let getDirectories(amazonS3Client:AmazonS3Client) (bucket) (prefix) =
  let listObjectsRequest = ListObjectsRequest(BucketName=bucket, Delimiter = "/", Prefix=prefix)
  let task = amazonS3Client.ListObjectsAsync(listObjectsRequest)
  task.Wait()
  if task.IsCompletedSuccessfully then
    //task.Result.IsTruncated
    Some(task.Result.S3Objects)
  else
    None

 let main argv =
    let bucket = "xxx"
    let prefix = "tmp/test1/" 
    let res = getDirectories amazonS3ClientMaybe.Value bucket prefix
    if res.IsSome then
        System.Console.WriteLine("Some entries")
        System.Console.WriteLine(res.Value.Count)
        for f in res.Value do
          let oout = String.Format("key = {0} size = {1}", f.Key, f.Size)
          System.Console.WriteLine(oout)
      else
        System.Console.WriteLine("No entries")
      System.Console.WriteLine("Ok")
    else
      System.Console.WriteLine("Not found")
    0
```

```bash
./bin/Debug/netcoreapp3.1/microetl
Some entries
1
key = tmp/test1/ size = 0
Ok
```

## Steps to Reproduce (for bugs)

Use basic functionality of the library.

## Context

I cannot use the SDK to complete my work.

## Your Environment

* AWSSDK.Core version used: 3.1.101 [/usr/local/share/dotnet/sdk]
* Service assembly and version used: 3.1.101 [/usr/local/share/dotnet/sdk]
* Operating System and version: MacOS 10.14.6
* Visual Studio version: -
* Targeted .NET platform: netcoreapp3.1 

## .NET Core Info

* .NET Core version used for development:  netcoreapp3.1
* .NET Core version installed in the environment where application runs: netcoreapp3.1
* Output of `dotnet --info`:

.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

* Contents of project.json/project.csproj: 

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Config.fs" /> 
    <Compile Include="S3.fs" />
    <Compile Include="Main.fs" />
    <None Include="config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3"                     Version="3.3.110.3"   />
    <PackageReference Include="AWSSDK.Securitytoken"          Version="3.3.104.26"  />
    <PackageReference Include="FSharp.Data"                   Version="3.3.2"       />
    <PackageReference Include="Parquet.Net"                   Version="3.3.11"      />
    <PackageReference Include="Microsoft.Extensions.Logging"  Version="3.1.1"       />
  </ItemGroup>

</Project>

**Comment by klaytaybai** [comment]
Hi @l1x, I think the delimiter property is working properly.  Your F# code doesn't use the CommonPrefixes property of the response, which is used in your Python code.  Please try again using CommonPrefixes and let us know if this issue can be closed.

**Comment by l1x** [comment]
Thanks @klaytaybai this is exactly the problem.
