### ISSUE TITLE
CloudwatchLogs GetQueryResultsAsync Execution Guidance

### ISSUE THREAD

**Issue by mikebama** [aws/aws-sdk-net#1514]
AWS Support Staff,
I read in the issue [CloudWatchLogs cannot query realtime latest log](https://github.com/aws/aws-sdk-net/issues/1387) some guidance was provided on API execute GetQueryResultsAsync usage while looping to exit when termination states of Complete, Failed, and Cancelled have occurred.  I am wondering if all .NET SDK Get Async queries need this type of execution control?

AWSSDK.Core version used: 3.3.0.0
Targeting .NET Framework 4.7.2
Service assembly and version used: AWSSDK.CloudWatchLogs 3.3.0.0

**Comment by klaytaybai** [comment]
Hi @mikebama, so far these query statuses are API-specific and I believe only for this CloudWatch use case.  If you are using querying the CloudWatch logs, you don't need to use this exact execution control method, but you should be checking each of the terminating statuses (Complete, Failed, Cancelled) unless you have some other way to cancel your code iteration.  

Does that answer your question?
