### ISSUE TITLE
Unity Build: 2019.3 Not working:

### ISSUE THREAD

**Issue by abiehusney25** [aws/aws-sdk-net#1515]
With the latest sdk from [here](https://docs.aws.amazon.com/mobile/sdkforunity/developerguide/setup-unity.html) 
Unity will run, but can't build apk's
Errors:
- /gradleOut/unityLibrary/src/main/java/com/amazonaws/unity/Utils.java:11: error: cannot find symbol
- location: class AWSUnityGCMWrapper
- Temp/gradleOut/unityLibrary/src/main/java/com/amazonaws/unity/AWSUnityGCMWrapper.java uses or overrides a deprecated API.

When using the new netstandard2.0 .dll's [As found here](https://aws.amazon.com/blogs/developer/referencing-the-aws-sdk-for-net-standard-2-0-from-unity-xamarin-or-uwp/)

I get compiler errors :
- The name 'UnityInitializer' does not exist in the current context
- Cannot convert lambda expression to type 'CancellationToken' because it is not a delegate type
- Cannot convert lambda expression to type 'CancellationToken' because it is not a delegate type

## Steps to Reproduce (for bugs)
Make New Unity 2019.3 Build
Import SNS sample from Unity [SDK](https://docs.aws.amazon.com/mobile/sdkforunity) 
1)Make sure: android-support-v4, google-play-services_lib, are in Assets/Plugins/Android/
2)Make sure link.xml file is created [as seen here](https://aws.amazon.com/blogs/developer/referencing-the-aws-sdk-for-net-standard-2-0-from-unity-xamarin-or-uwp/)
3)In root Resources/ make sure awsconfig file is made [as seen here](https://docs.aws.amazon.com/mobile/sdkforunity/developerguide/setup-unity.html)
## Your Environment
aws-sdk-unity_3.3.670.0
aws-sdk-netstandard2.0-3.3.670.0
Mac and Unity 2019.3

## .NET Core Info
The error occurs for both IL2CPP and Mono backends on Android. Also occurs on .NET standard 2.0 and .NET 4.x API compatibility levels.

Thank you so much for the help.

**Comment by klaytaybai** [comment]
I don't think you need to be using the AWS SDK for Unity at all if you are using the NetStandard 2.0 dlls.  This should avoid the compatibility problems.  We are in the process of deprecating our support for the AWS SDK for Unity and improving our documentation on how to continue using AWS with Unity.

**Comment by abiehusney25** [comment]
> I don't think you need to be using the AWS SDK for Unity at all if you are using the NetStandard 2.0 dlls. This should avoid the compatibility problems. We are in the process of deprecating our support for the AWS SDK for Unity and improving our documentation on how to continue using AWS with Unity.

@klaytaybai 

I have read that the Unity aws sdk has been depriciated, but I cant find a tutorial on how to implement the NetStandard 2.0 dlls. I have tried and gotten compiler errors.

    The name 'UnityInitializer' does not exist in the current context
    Cannot convert lambda expression to type 'CancellationToken' because it is not a delegate type
    Cannot convert lambda expression to type 'CancellationToken' because it is not a delegate type

Any tutorials or ways to set up aws for Unity.

**Comment by abiehusney25** [comment]
If the Current AWS Unity SDK is not working, how do I use the current sdk for Unity?

**Comment by abiehusney25** [comment]
@klaytaybai 

As far as I know [this setup](https://github.com/a-leontiev/aws-sdk-net/blob/master/Unity.README.md) is depreciated. 

Do you know where I would get a working sdk, and how to set it up?

Thank you

**Comment by klaytaybai** [comment]
That setup is mostly deprecated, yes.  We are now recommending that Unity users use the .NET Standard dlls and not the AWS SDK for Unity.  As shown in this this migration [blog post](https://aws.amazon.com/blogs/developer/referencing-the-aws-sdk-for-net-standard-2-0-from-unity-xamarin-or-uwp/), you will still need to have the link.xml file.  After importing the DLLs, your AWS calls should be as simple as shown in the sample below and not result in Android compatibility issues.  We're going to be updating our docs and communications soon with more info for Unity developers.  Please reach out to us again if you need more info now or after we get out more documentation.

```
using System.Threading.Tasks;
using Amazon.S3;
using UnityEngine;
using Debug = UnityEngine.Debug;

public class TestSdkScript : MonoBehaviour
{
    // Start is called before the first frame update
    async Task Start()
    {
        using (var client = new AmazonS3Client())
        {
            var result = await client.ListBucketsAsync();
            foreach (var bucket in result.Buckets)
            {
                Debug.Log(bucket.BucketName);
            }
        }
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
```

**Comment by abiehusney25** [comment]
@klaytaybai 

Okay, thank you for getting back

Any samples for the aws SimpleNotificationService.

Like an example or walkthrough. I have the new dll's but the old script does not work.



it gets an error on this code:


                SnsClient.CreatePlatformEndpointAsync(
                    new CreatePlatformEndpointRequest
                    {
                        Token = regId,
                        PlatformApplicationArn = AndroidPlatformApplicationArn
                    },
                    (resultObject) =>
                    {
                        if (resultObject.Exception == null)
                        {
                            CreatePlatformEndpointResponse response = resultObject.Response;
                            _endpointArn = response.EndpointArn;
                            ResultText.text += string.Format(@"Platform endpoint arn is = {0}", response.EndpointArn);
                        }
                    }
                );
            }, GoogleConsoleProjectId);

Cannot convert lambda expression to type 'CancellationToken' because it is not a delegate type

**Comment by klaytaybai** [comment]
> it gets an error on this code:
> 
> ```
>             SnsClient.CreatePlatformEndpointAsync(
>                 new CreatePlatformEndpointRequest
>                 {
>                     Token = regId,
>                     PlatformApplicationArn = AndroidPlatformApplicationArn
>                 },
>                 (resultObject) =>
>                 {
>                     if (resultObject.Exception == null)
>                     {
>                         CreatePlatformEndpointResponse response = resultObject.Response;
>                         _endpointArn = response.EndpointArn;
>                         ResultText.text += string.Format(@"Platform endpoint arn is = {0}", response.EndpointArn);
>                     }
>                 }
>             );
>         }, GoogleConsoleProjectId);
> ```
> 
> Cannot convert lambda expression to type 'CancellationToken' because it is not a delegate type

It is saying that the lambda expression with the resultObject variable cannot be converted to a cancellation token.  The newer major versions of the .NET SDK don't use callbacks in the same way that the AWS SDK for Unity had used.  Your code should follow a format similar to this instead:
```

CreatePlatformEndpointResponse response;
try {
     response = await SnsClient.CreatePlatformEndpointAsync(
                new CreatePlatformEndpointRequest
                {
                    Token = regId,
                    PlatformApplicationArn = AndroidPlatformApplicationArn
                }).ConfigureAwait(false);
} catch (Exception e) {
     // Handle exception
}

if (response != null) {
     _endpointArn = response.EndpointArn;
     ResultText.text += string.Format(@"Platform endpoint arn is = {0}", response.EndpointArn);
}
```

**Comment by abiehusney25** [comment]
@klaytaybai 

Unity Android build.

I've been trying to run the new dll's for push notifications in Unity and I am not getting them to work.

I don't know what I am missing, but it compiled and ran, but the push notifications is not working.

I know that the specific unity builds are depreciated, and that we should use the netsatandard 2.0 aws sdk, but I cannot get it to work.

Do you have a sample unity plugin, or step by step instructions on how to get it working.

I have been trying for weeks and cannot get my project to run.

Thank you so much

**Comment by jasonb202020** [comment]
hey @abiehusney25 
Were you able to get AWS working?
I'm hoping to use Cognito/Lambda/Dynamo/S3 with 2019.3 but am going around in circles searching for up to date getting started docs.
Any pointers appreciated!

**Comment by abiehusney25** [comment]
> hey @abiehusney25
> Were you able to get AWS working?
> I'm hoping to use Cognito/Lambda/Dynamo/S3 with 2019.3 but am going around in circles searching for up to date getting started docs.
> Any pointers appreciated!

Well I could not find any documentation but I did get some things working in Unity.

remove all of the old dll's and put in the corresponding net standard 2 dlls from here https://aws.amazon.com/blogs/developer/referencing-the-aws-sdk-for-net-standard-2-0-from-unity-xamarin-or-uwp/

Also make sure When using Unity (2018.1 or newer), choose .NET 4.x Equivalent as Scripting Runtime Version and copy the AWS SDK for .NET assemblies into the Asset folder.

the c# code should run if you make it fit with unity, but if there is other custom code that is in the sdk you might have to fix it.

For example the gcm for push notifications is completely obsolete and does not work anymore
