### ISSUE TITLE
DescribeKeyPairs: The remote server returned an error: (401) Unauthorized.

### ISSUE THREAD

**Issue by TriSysBusinessSoftware** [aws/aws-sdk-net#1516]
So we have ported our code form the legacy .Net SDK to the latest version.

## Expected Behavior
We expected the authentication using the SAME credentials to work.

## Current Behavior
Raises a run-time error, failing to authenticate.

## Steps to Reproduce (for bugs)

`
Try
            Dim ec2Config As New Amazon.EC2.AmazonEC2Config
            If ServiceURL <> String.Empty Then
                'ec2Config = New Amazon.EC2.AmazonEC2Config(ServiceURL)     'Amazon.EC2.AmazonEC2Config().WithServiceURL(ServiceURL)
                ec2Config.ServiceURL = ServiceURL
                ec2Config.LogMetrics = True
                ec2Config.LogResponse = True
            End If

            m_AWSService = New AmazonEC2Client(AWSAccessKey, AWSSecretKey, ec2Config)
            'm_AWSService = AWSClientFactory.CreateAmazonEC2Client(AWSAccessKey, AWSSecretKey, ec2Config)

            AWSConfigs.Logging = LoggingOptions.Console Or LoggingOptions.Log4Net Or LoggingOptions.SystemDiagnostics
            AWSConfigs.LogMetrics = True
            AWSConfigs.ResponseLogging = ResponseLoggingOption.Always
            AWSConfigs.AWSRegion = "eu-west-1"

            ' Have to do something to prove we are connected
            Dim myKeys As New Amazon.EC2.Model.DescribeKeyPairsRequest
            Dim myResponse As Amazon.EC2.Model.DescribeKeyPairsResponse = m_AWSService.DescribeKeyPairs(myKeys)

            Dim iKeyPairCount As Integer = myResponse.KeyPairs.Count    ' myResponse.DescribeKeyPairsResult.KeyPair.Count

            Return (iKeyPairCount > 0)

        Catch ex As AmazonEC2Exception
            If ex.ErrorCode.Equals("OptInRequired") Then
                ErrorMessage = "You are not signed for Amazon EC2."
            Else
                ErrorMessage = "Caught Exception: " & ex.Message & vbCrLf &
                    "Response Status Code: " & ex.StatusCode & vbCrLf &
                    "Error Code: " & ex.ErrorCode & vbCrLf &
                    "Error Type: " & ex.ErrorType & vbCrLf &
                    "Request ID: " & ex.RequestId
            End If
        End Try
`

Error logging
--------------
AmazonEC2Client 1|2020-01-31T17:53:57.984Z|ERROR|An exception of type HttpErrorResponseException was handled in ErrorHandler. --> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (401) Unauthorized. ---> System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpRequest.GetResponse()
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.EC2.Internal.AmazonEC2ResponseHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext)
AmazonEC2Client 2|2020-01-31T17:53:58.001Z|ERROR|Received error response: [<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>AuthFailure</Code><Message>AWS was not able to validate the provided access credentials</Message></Error></Errors><RequestID>e34b09aa-3599-4342-871b-f763a6168d6b</RequestID></Response>] --> Amazon.EC2.AmazonEC2Exception: AWS was not able to validate the provided access credentials ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (401) Unauthorized. ---> System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpRequest.GetResponse()
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext)

## Context
Show stopper as we are unable to use our code to spin up instances. Problem for AWS as they will not be generating revenue. Needs an urgent fix.

## Your Environment
Windows 10 64-bit, VS 2017, .Net 4.5+

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
To confirm, this was working on an earlier version with the same credentials?  Can you please tell us which AWS SDK version you were using before and the version that you are using now?

It might be an issue with trying to set the service url and the region endpoint both.  Those are mutually exclusive now.  If you specify the service url, the region endpoint is automatically detected from it.  If you set the region endpoint, it uses the default service url.

**Comment by TriSysBusinessSoftware** [comment]
Hi, and thanks for your response.
We were using AWSSDK.dll version 1.3.6.0 dated 29/09/2011
Yes - the same credentials work in our old code, but not in the new code I posted above.
So we are in EU West, and are using these endpoints:
ec2Config.ServiceURL = "https://eu-west-1.ec2.amazonaws.com"
AWSConfigs.AWSRegion = "eu-west-1"

Are these correct?

**Comment by klaytaybai** [comment]
The service url should actually be https://ec2.eu-west-1.amazonaws.com.  Does that help at all?

**Comment by TriSysBusinessSoftware** [comment]
Ah! I will test now...

**Comment by TriSysBusinessSoftware** [comment]
Yay - that worked!
Thank you so much.

**Comment by klaytaybai** [comment]
Great!
