### ISSUE TITLE
AmazonS3Client initialization exception

### ISSUE THREAD

**Issue by rihadd2** [aws/aws-sdk-net#1519]
After updating to .net core 3.1 our web application started throwing the below exception when creating an instance of the AWSS3Client.  We have two servers in the cluster and the error is being thrown only on one of them.  The servers are mirrors of each other.

AWSSDK.3.3.101.2
AWSSDK.S3 3.3.101.9

Code: using (IAmazonS3 client = new AmazonS3Client(key, secretAccessKey, RegionEndpoint.USEast1))

System.TypeInitializationException: The type initializer for 'Amazon.Runtime.Internal.Settings.PersistenceManager' threw an exception.   ---> System.UnauthorizedAccessException: Access to the path 'C:\Windows\system32\config\systemprofile' is denied.     at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)     at System.IO.Directory.CreateDirectory(String path)     at Amazon.Runtime.Internal.Settings.PersistenceManager..cctor()     --- End of inner exception stack trace ---     at Amazon.Util.Internal.SettingsManager.GetSettings()     at Amazon.Util.Internal.SettingsManager.TryGetObjectByProperty(String propertyName, String value, String& uniqueKey, Dictionary`2& properties)     at Amazon.Runtime.CredentialManagement.NetSDKCredentialsFile.TryGetProfile(String profileName, CredentialProfile& profile)     at Amazon.Runtime.CredentialManagement.CredentialProfileStoreChain.TryGetProfile(String profileName, CredentialProfile& profile)     at Amazon.S3.AmazonS3Config.CheckCredentialsFile()     at Amazon.S3.AmazonS3Config.GetEndpointFlagValueForUsEast1Regional()     at Amazon.S3.AmazonS3Config.UpdateEndpointForUsEast1Regional()     at Amazon.S3.AmazonS3Config.Initialize()     at Amazon.S3.AmazonS3Config..ctor()

**Comment by jjrutter** [comment]
We are also having this issue after updating to .net core 3.1 w/

AWSSDK.Core 3.3.104.11
AWSSDK.S3 3.3.110.7

We tried installing the latest, which did not fix the issue
AWSSDK.Core 3.3.104.21
AWSSDK.S3 3.3.110.19

**Comment by rihadd2** [comment]
After looking at the PersistenceManger constructor and examining the IIS app pool Identity user, we have determined that the issue was being caused by the app pool Identity having a local profile loaded from a previous console login (or not profile at all).  The logic in the constructor defaulted the SettingsStoreFolder to 'C:\Windows\system32\config\systemprofile' which is a protected directory.
Deleting the local user profile and recreating the user fixed the issue for us.

`static PersistenceManager()
        {
#if BCL
            SettingsStoreFolder = System.Environment.GetFolderPath(System.Environment.SpecialFolder.LocalApplicationData) + "/AWSToolkit";
#else
            SettingsStoreFolder = System.Environment.GetEnvironmentVariable("HOME");
            if (string.IsNullOrEmpty(SettingsStoreFolder))
                SettingsStoreFolder = System.Environment.GetEnvironmentVariable("USERPROFILE");

            SettingsStoreFolder = Path.Combine(SettingsStoreFolder, "AppData/Local/AWSToolkit");
#endif
            if (!Directory.Exists(SettingsStoreFolder))
                Directory.CreateDirectory(SettingsStoreFolder);
        }`

**Comment by remcolam** [comment]
So how do I fix this? Because I am unable to use the api now? Why was it closed?

**Comment by yuridiniz** [comment]
Same issue here, and I couldn't solve it with the proposed solution

**Comment by rihadd2** [comment]
One way to solve is to uncheck Load User Profile under app pool advanced settings.

**Comment by nemtajo** [comment]
For me,  creating AWSToolkit folder using the code @rihadd2 posted and setting 'Load User Profile' to true in application pool solved the issue.

**Comment by dssagar93** [comment]
For me on IIS, I had to turn on Load User Profile under the pool. It solved the issue.
