### ISSUE TITLE
Publish to AWS Lambda should use the profile from aws-lambda-tools-defaults.json

### ISSUE THREAD

**Issue by jerhewet** [aws/aws-sdk-net#1521]
When "Publish to AWS Lambda..." is selected from the Visual Studio Solution Explorer, the "Upload to AWS Lambda" dialog should be populated using the current settings from the "aws-lambda-tools-defaults.json" file,

## Expected Behavior

The "Upload to AWS Lambda" dialog should always reflect the current settings stored in the "aws-lambda-tools-defaults.json" file.

## Current Behavior

The lambda publish dialog uses the Account Profile and Region from the AWS Explorer drop-down list controls, but the other configuration settings are apparently retrieved from cached values stored during the last publish.  If you select the "Next" button in the dialog the cached values are used for the role, and will display an error dialog if they don't exist in the selected Account Profile.

## Possible Solution

Always reload the settings from the "aws-lambda-tools-defaults.json" file before displaying the "Upload to AWS Lambda" dialog, and do not use any cached settings or currently selected values from the AWS Explorer for the publish.

## Steps to Reproduce (for bugs)

I have two separate MSBuild targets set up in my project file that will replace the existing "aws-lambda-tools-defaults.json" file depending on the build configuration (Debug or Release). The JSON file is always being replaced when I change the build target (read as: the lambda setting for "profile" are completely different between Debug and Release), but when I select "Publish to AWS Lambda" after doing a clean and rebuild the "Upload to AWS Lambda" dialog is still using the last selected profile instead of the new profile contained in the "aws-lambda-tools-defaults.json" file.

This environment can be emulated by publishing a function to AWS Lambda, editing the "aws-lambda-tools-defaults.json" file to change the settings to a different profile, region, or role, and selecting the "Publish to AWS Lambda" option again.

## Context

It is very easy for anyone supporting multiple AWS Lambda functions and configurations to publish the wrong profile to AWS, with the potential to bring down one or more services running in production.

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
Thanks for the feedback.  I'll see if we can get progress on this.

**Comment by ashishdhingra** [comment]
Closing this in favor of https://github.com/aws/aws-toolkit-visual-studio/issues/23
