### ISSUE TITLE
Trying to understand S3 client change. 

### ISSUE THREAD

**Issue by phillip-haydon** [aws/aws-sdk-net#1525]
Sorry for not following the template.

This is in relation to issue #1503

I'm trying to understand what changed in the S3 client that caused performance issues.

Based on the change log we had these changes:

# 3.3.650.0 (2019-12-13 21:43 UTC)
* S3 (3.3.110.0)
  * Updated to use new Core, version 3.3.104.5
  * The S3 client now supports a regional endpoint property for us-east-1

# 3.3.653.0 (2019-12-18 19:46 UTC)
* S3 (3.3.110.3)
  * Updates Amazon S3 endpoints allowing you to configure your client to opt-in to using S3 with the us-east-1 regional endpoint, instead of global.

What happened is in any version prior to 3.3.110.0, the performance to generated a signed url was fast. Like the requests to get a signed url on our API was ~20ms. 

After the change it's like 2+ seconds. 

This was apparently fixed in 3.3.110.17. I upgraded to 17 and the performance went back to roughly what it used to be, sort of...

The issue I have is that the first request to create the s3 client is > 2 seconds still. After that the requests are fast, like 20ms again.

But every now n then our server spikes to 100% cpu and the requests are queued for the endpoint to generate the URL.

So I noticed in the change log that there is a flag. So I updated the code to use Legacy.

```csharp
config = new AmazonS3Config
{
    RegionEndpoint = regionEndPoint, 
    Timeout = timeout, 
    UseAccelerateEndpoint = credentials.UseAccelerateEndpoint,
    USEast1RegionalEndpointValue = S3UsEast1RegionalEndpointValue.Legacy
};
```

After deploying this change, the behavior changed back to pre 3.3.110.0, so every request is like 20ms, even the creation of the S3 client. 

So I still believe there's some issue with the new regional setting, but from the code I really don't understand the change/code. :(

**Comment by klaytaybai** [comment]
We have some more work on this in progress.  I can try to provide some more updates once it is out.

The issue is that some of the S3 configuration around the regional endpoints relied on reading profile files from disk.  In some cases, this shouldn't be necessary or even possible (e.g. permissions), but the SDK was still trying (and retrying).  We've reworked some logic to avoid the attempted file read more often and improve our caching.  This is likely why you are seeing only the first attempt take 2 seconds when you are not using Legacy.

**Comment by ashishdhingra** [comment]
Hi @phillip-haydon,

Good afternoon.

I was going through the list of open issues and came across this one. Please advise if you are still facing issue with the latest version or if we are good to close this issue.

Thanks,
Ashish

**Comment by phillip-haydon** [comment]
I don’t know if it’s still an issue. We set it back to legacy mode. I’m honestly too scared to change it.

**Comment by ashishdhingra** [comment]
@phillip-haydon Please advise if we could close the issue. In case you face issue after upgrade, feel free to open a new issue.

**Comment by phillip-haydon** [comment]
Yeah if that legacy mode is removed and it’s slow again I’ll be here in a flash raising an issue! :)
