### ISSUE TITLE
AWSMobileSDK .net, Xamarin.iOS MobileAnalyticsManager, JSON conversion of event and session to object fails with KeyNotFoundException

### ISSUE THREAD

**Issue by mama933** [aws/aws-sdk-net#1528]
I am trying to implement the MobileAnalyticsManager in Xamarin.Android and Xamarin.iOS. Xamarin.Android version is working as intended in both emulator and on physical device. On Xamarin.iOS the behaviour when using the simulator is correct, but on a physical device the JSON conversion to types "Amazon.MobileAnalytics.Model.Event" and "Amazon.MobileAnalytics.Model.Session" is failing with a KeyNotFoundException on the type itself. 

## Expected Behavior

JSON conversion with JsonMapper.ToObject<T> should succeed and fill the type with the data from the saved event or session JSON string.

## Current Behavior
The JSON conversion with JsonMapper.ToObject<T> is throwing a KeyNotFoundException for the type itself, either "Amazon.MobileAnalytics.Model.Event" or "Amazon.MobileAnalytics.Model.Session" instead of filling the type with the data from the JSON string. 

## Possible Solution
I tried to replace the standard implementation JsonMapper.ToObject<T> with JsonConvert.DeserializeObject<T> from the Newtonsoft.JSON library, which seems to be working correctly. Although not all of the session data (e.g. device platform) is shown in AWS Pinpoint then. There may be more related issues to that, which I was not able to determine yet.

## Steps to Reproduce (for bugs)
1. Grab the sample application provided (AWSSDK.MobileAnalytics.Sample) from https://github.com/awslabs/aws-sdk-net-samples/tree/master/XamarinSamples/MobileAnalytics

2. remove the ABI "armeabi" from the list of ABIs for the android version to make it executable.

3. set the credentials and needed information to contact the backend in the AppDelegate.cs
`private const string APP_ID = "YourAppId";`
`private string COGNITO_POOL_ID = "YourPoolId";`
`private RegionEndpoint COGNITO_REGION = RegionEndpoint.USEast1;`

4. activate logging to check in console later
`LoggingConfig loggingConfig = AWSConfigs.LoggingConfig;`
`loggingConfig.LogMetrics = true;`
`loggingConfig.LogResponses = ResponseLoggingOption.Always;`
`loggingConfig.LogMetricsFormat = LogMetricsFormatOption.JSON;`
`loggingConfig.LogTo = LoggingOptions.SystemDiagnostics;`

5. run the sample on a physical iOS device with iOS13 and wait up to 60 seconds for the execution of the function AttemptDeliveryAsync(), which should read the event data from the saved JSON and convert it to an event to add it to the list to send later. 

6. the line `Amazon.MobileAnalytics.Model.Event _analyticsEvent = JsonMapper.ToObject<Amazon.MobileAnalytics.Model.Event>(eventString);` is then going to be executed and will fail with a KeyNotFound Exception, see details below:

2020-02-15 16:54:10.719 MobileAnalyticsSampleiOS[3499:1254310] BackgroundRunner 8|2020-02-15T16:54:10.718Z|INFO|1|Mobile Analytics Manager is trying to deliver events in background thread.
2020-02-15 16:54:10.730 MobileAnalyticsSampleiOS[3499:1254310] BackgroundRunner 9|2020-02-15T16:54:10.728Z|ERROR|1|An exception occurred in Mobile Analytics Delivery Client : System.Collections.Generic.KeyNotFoundException: The given key 'Amazon.MobileAnalytics.Model.Event' was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x0001e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/Dictionary.cs:226 
  at ThirdParty.Json.LitJson.JsonMapper.ReadValue (System.Type inst_type, ThirdParty.Json.LitJson.JsonReader reader) [0x0027c] in <9489314074bd4da4b40094012e6ca0fb>:0 
  at ThirdParty.Json.LitJson.JsonMapper.ToObject[T] (System.String json) [0x00007] in <9489314074bd4da4b40094012e6ca0fb>:0 
  at Amazon.MobileAnalytics.MobileAnalyticsManager.Internal.DeliveryClient.AttemptDeliveryAsync () [0x00181] in <203348cc2dbc4b3e9b3d10d781b248b1>:0 
  at Amazon.MobileAnalytics.MobileAnalyticsManager.Internal.BackgroundRunner.DoWorkAsync (System.Int32 millisecondsDelay) [0x0017a] in <203348cc2dbc4b3e9b3d10d781b248b1>:0  --> System.Collections.Generic.KeyNotFoundException: The given key 'Amazon.MobileAnalytics.Model.Event' was not present in the dictionary.
  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x0001e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/Dictionary.cs:226 
  at ThirdParty.Json.LitJson.JsonMapper.ReadValue (System.Type inst_type, ThirdParty.Json.LitJson.JsonReader reader) [0x0027c] in <9489314074bd4da4b40094012e6ca0fb>:0 
  at ThirdParty.Json.LitJson.JsonMapper.ToObject[T] (System.String json) [0x00007] in <9489314074bd4da4b40094012e6ca0fb>:0 
  at Amazon.MobileAnalytics.MobileAnalyticsManager.Internal.DeliveryClient.AttemptDeliveryAsync () [0x00181] in <203348cc2dbc4b3e9b3d10d781b248b1>:0 
  at Amazon.MobileAnalytics.MobileAnalyticsManager.Internal.BackgroundRunner.DoWorkAsync (System.Int32 millisecondsDelay) [0x0017a] in <203348cc2dbc4b3e9b3d10d781b248b1>:0 

## Context
This results in not delivering the events to AWS Pinpoint. 

## Your Environment

* AWSSDK.Core version used:
  package id="AWSSDK.CognitoIdentity" version="3.1.0.1" targetFramework="xamarinios10"
  package id="AWSSDK.Core" version="3.1.1.0" targetFramework="xamarinios10"
  package id="AWSSDK.MobileAnalytics" version="3.1.1.0" targetFramework="xamarinios10" />
  package id="AWSSDK.SecurityToken" version="3.1.0.1" targetFramework="xamarinios10" />
  package id="Microsoft.Bcl" version="1.1.10" targetFramework="xamarinios10" />
  package id="Microsoft.Bcl.Build" version="1.0.14" targetFramework="xamarinios10" />
  package id="Microsoft.Net.Http" version="2.2.29" targetFramework="xamarinios10" />
  package id="PCLCrypto" version="1.0.2.15130" targetFramework="xamarinios10" />
  package id="PCLStorage" version="1.0.2" targetFramework="xamarinios10" />
  package id="SQLitePCL" version="3.8.7.2" targetFramework="xamarinios10" />
  package id="Validation" version="2.0.6.15003" targetFramework="xamarinios10" />

* Service assembly and version used: 
  package id="AWSSDK.CognitoIdentity" version="3.1.0.1" targetFramework="xamarinios10" />
  package id="AWSSDK.Core" version="3.1.1.0" targetFramework="xamarinios10" />
  package id="AWSSDK.MobileAnalytics" version="3.1.1.0" targetFramework="xamarinios10" />
  package id="AWSSDK.SecurityToken" version="3.1.0.1" targetFramework="xamarinios10" />
  package id="Microsoft.Bcl" version="1.1.10" targetFramework="xamarinios10" />
  package id="Microsoft.Bcl.Build" version="1.0.14" targetFramework="xamarinios10" />
  package id="Microsoft.Net.Http" version="2.2.29" targetFramework="xamarinios10" />
  package id="PCLCrypto" version="1.0.2.15130" targetFramework="xamarinios10" />
  package id="PCLStorage" version="1.0.2" targetFramework="xamarinios10" />
  package id="SQLitePCL" version="3.8.7.2" targetFramework="xamarinios10" />
  package id="Validation" version="2.0.6.15003" targetFramework="xamarinios10" />

* Operating System and version: macOS Catalina (Version 10.15.2)
* Visual Studio version: Visual Studio for Mac (Community, Version 8.4.5, Build 19)
* Targeted .NET platform: 3.1

## .NET Core Info

* Output of `dotnet --info`: 
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.0.101 [/usr/local/share/dotnet/sdk]
  3.1.100 [/usr/local/share/dotnet/sdk]
  3.1.101 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

* Contents of project.json/project.csproj: 
```
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">iPhoneSimulator</Platform>
    <ProjectTypeGuids>{FEACFBD2-3405-455C-9665-78FE426C6842};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>
    <ProjectGuid>{E7C618DF-06DE-49D8-8CCB-2D5F6B43BF03}</ProjectGuid>
    <OutputType>Exe</OutputType>
    <RootNamespace>MobileAnalyticsSample.iOS</RootNamespace>
    <IPhoneResourcePrefix>Resources</IPhoneResourcePrefix>
    <AssemblyName>MobileAnalyticsSampleiOS</AssemblyName>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|iPhoneSimulator' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\iPhoneSimulator\Debug</OutputPath>
    <DefineConstants>DEBUG;ENABLE_TEST_CLOUD;</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <ConsolePause>false</ConsolePause>
    <MtouchArch>i386</MtouchArch>
    <MtouchLink>None</MtouchLink>
    <MtouchDebug>true</MtouchDebug>
    <MtouchProfiling>true</MtouchProfiling>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|iPhone' ">
    <DebugType>full</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\iPhone\Release</OutputPath>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <CodesignEntitlements>Entitlements.plist</CodesignEntitlements>
    <MtouchArch>ARMv7, ARM64</MtouchArch>
    <ConsolePause>false</ConsolePause>
    <CodesignKey>iPhone Developer</CodesignKey>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|iPhoneSimulator' ">
    <DebugType>full</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\iPhoneSimulator\Release</OutputPath>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <MtouchArch>i386</MtouchArch>
    <ConsolePause>false</ConsolePause>
    <MtouchLink>None</MtouchLink>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|iPhone' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\iPhone\Debug</OutputPath>
    <DefineConstants>DEBUG;ENABLE_TEST_CLOUD;</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <ConsolePause>false</ConsolePause>
    <MtouchArch>ARMv7, ARM64</MtouchArch>
    <CodesignEntitlements>Entitlements.plist</CodesignEntitlements>
    <MtouchProfiling>true</MtouchProfiling>
    <CodesignKey>iPhone Developer</CodesignKey>
    <MtouchDebug>true</MtouchDebug>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Core" />
    <Reference Include="Xamarin.iOS" />
    <Reference Include="SQLitePCL">
      <HintPath>..\packages\SQLitePCL.3.8.7.2\lib\Xamarin.iOS10\SQLitePCL.dll</HintPath>
    </Reference>
    <Reference Include="SQLitePCL.Ext">
      <HintPath>..\packages\SQLitePCL.3.8.7.2\lib\Xamarin.iOS10\SQLitePCL.Ext.dll</HintPath>
    </Reference>
    <Reference Include="System.Net.Http.Primitives">
      <HintPath>..\packages\Microsoft.Net.Http.2.2.29\lib\Xamarin.iOS10\System.Net.Http.Primitives.dll</HintPath>
    </Reference>
    <Reference Include="System.Net.Http.Extensions">
      <HintPath>..\packages\Microsoft.Net.Http.2.2.29\lib\Xamarin.iOS10\System.Net.Http.Extensions.dll</HintPath>
    </Reference>
    <Reference Include="PCLStorage">
      <HintPath>..\packages\PCLStorage.1.0.2\lib\portable-Xamarin.iOS+Xamarin.Mac\PCLStorage.dll</HintPath>
    </Reference>
    <Reference Include="PCLStorage.Abstractions">
      <HintPath>..\packages\PCLStorage.1.0.2\lib\portable-Xamarin.iOS+Xamarin.Mac\PCLStorage.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Validation">
      <HintPath>..\packages\Validation.2.0.6.15003\lib\portable-net40+sl50+win+wpa81+wp80+Xamarin.iOS10+MonoAndroid10+MonoTouch10\Validation.dll</HintPath>
    </Reference>
    <Reference Include="PCLCrypto">
      <HintPath>..\packages\PCLCrypto.1.0.2.15130\lib\Xamarin.iOS\PCLCrypto.dll</HintPath>
    </Reference>
    <Reference Include="AWSSDK.Core">
      <HintPath>..\packages\AWSSDK.Core.3.1.1.0\lib\Xamarin.iOS10\AWSSDK.Core.dll</HintPath>
    </Reference>
    <Reference Include="AWSSDK.MobileAnalytics">
      <HintPath>..\packages\AWSSDK.MobileAnalytics.3.1.1.0\lib\Xamarin.iOS10\AWSSDK.MobileAnalytics.dll</HintPath>
    </Reference>
    <Reference Include="AWSSDK.SecurityToken">
      <HintPath>..\packages\AWSSDK.SecurityToken.3.1.0.1\lib\portable-net45+netcore45+wpa81+wp8+MonoAndroid10+xamarinios10+MonoTouch10\AWSSDK.SecurityToken.dll</HintPath>
    </Reference>
    <Reference Include="AWSSDK.CognitoIdentity">
      <HintPath>..\packages\AWSSDK.CognitoIdentity.3.1.0.1\lib\portable-net45+netcore45+wpa81+wp8+MonoAndroid10+xamarinios10+MonoTouch10\AWSSDK.CognitoIdentity.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <ImageAsset Include="Resources\Images.xcassets\AppIcons.appiconset\Contents.json">
      <InProject>false</InProject>
    </ImageAsset>
  </ItemGroup>
  <ItemGroup>
    <InterfaceDefinition Include="Resources\LaunchScreen.xib" />
    <InterfaceDefinition Include="Main.storyboard" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Info.plist" />
    <None Include="Entitlements.plist" />
    <None Include="packages.config" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Main.cs" />
    <Compile Include="AppDelegate.cs" />
    <Compile Include="ViewController.cs" />
    <Compile Include="ViewController.designer.cs">
      <DependentUpon>ViewController.cs</DependentUpon>
    </Compile>
  </ItemGroup>
  <Import Project="$(MSBuildExtensionsPath)\Xamarin\iOS\Xamarin.iOS.CSharp.targets" />
  <Import Project="..\packages\Microsoft.Bcl.Build.1.0.14\tools\Microsoft.Bcl.Build.targets" Condition="Exists('..\packages\Microsoft.Bcl.Build.1.0.14\tools\Microsoft.Bcl.Build.targets')" />
  <Target Name="EnsureBclBuildImported" BeforeTargets="BeforeBuild" Condition="'$(BclBuildImported)' == ''">
    <Error Condition="!Exists('..\packages\Microsoft.Bcl.Build.1.0.14\tools\Microsoft.Bcl.Build.targets')" Text="This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=317567." HelpKeyword="BCLBUILD2001" />
    <Error Condition="Exists('..\packages\Microsoft.Bcl.Build.1.0.14\tools\Microsoft.Bcl.Build.targets')" Text="The build restored NuGet packages. Build the project again to include these packages in the build. For more information, see http://go.microsoft.com/fwlink/?LinkID=317568." HelpKeyword="BCLBUILD2002" />
  </Target>
</Project>
```

## EDIT
I forgot to mention, I was using the example, cause the SDK logging is not working in newer version. But the issue also occurs identically on the newest versions of the nuget packages.

**Comment by klaytaybai** [comment]
Support for Mobile Analytics has been deprecated.  We recommend that anybody doing new development use Amazon Pinpoint entirely instead of integrating with Mobile Analytics.  With the deprecation of support for the Mobile Analytics package, we realize that there are some high-level feature gaps.  If you would like to see a high level library for Pinpoint on .NET, please comment on this tracking/discussion [issue](https://github.com/aws/dotnet/issues/19).

Read more about the deprecation (and Xamarin development) here:
https://aws.amazon.com/blogs/developer/aws-sdk-for-net-v3-5-preview
https://docs.aws.amazon.com/mobileanalytics/latest/ug/migrate.html
