### ISSUE TITLE
SimpleNotificationService Andorid: GCM NOT WORKING

### ISSUE THREAD

**Issue by abiehusney25** [aws/aws-sdk-net#1530]
SimpleNotificationService is working on IOS, but not on Android.

I am not sure if GCM is depreciated, and if it will even work at all. [SEE HERE FOR MORE INFO ](https://developers.google.com/cloud-messaging/android/android-migrate-fcm)

## Expected Behavior
The SimpleNotificationService does connect to platform application endpoints, when trying to connect on Android

## Current Behavior
It returns null. When trying the sample project: regId returns null.
The call is  GCM.Register((regId)

## Steps to Reproduce (for bugs)
Install the Unity SDK on unity 2017. 
Import the SimpleNotificationService follow all the steps [As  shown here](https://docs.aws.amazon.com/mobile/sdkforunity/developerguide/sns.html)

NOTE:
When trying to create a platform application on AWS, there is no option for "Google Cloud Service (GCM)". There is a way to get an api key from creating a "Firebase account" that I cant get it working.
You can create the key with firebase, and putting it in the aws Platform application. But the android app cannot reach the endpoint.

## Context
Cannot sen Push Notifications to android devices. 
## Your Environment
AWSSDK.Core
AWSSDK.CognitoIdentity
AWSSDK.SecurityToken
AWSSDK.SimpleNotificationService
* Operating System and version: Mac
* Visual Studio version: 2019 Unity: 2017
* Targeted .NET platform: Net 4.6

## .NET Core Info
Net 4.6

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

Sample Code
//
// Copyright 2014-2015 Amazon.com, 
// Inc. or its affiliates. All Rights Reserved.
// 
// Licensed under the AWS Mobile SDK For Unity 
// Sample Application License Agreement (the "License"). 
// You may not use this file except in compliance with the 
// License. A copy of the License is located 
// in the "license" file accompanying this file. This file is 
// distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR 
// CONDITIONS OF ANY KIND, express or implied. See the License 
// for the specific language governing permissions and 
// limitations under the License.
//

using UnityEngine;
using System.Collections;
using Amazon.SimpleNotificationService;
using Amazon.Runtime;
using Amazon.CognitoIdentity;
using Amazon;
using UnityEngine.UI;
using Amazon.SimpleNotificationService.Model;

namespace AWSSDK.Examples
{
    public class SNSExample : MonoBehaviour
    {
        //identity pool id for cognito credentials
        public string IdentityPoolId = "";
        
        //sns android platform arn
        public string AndroidPlatformApplicationArn = "";
        
        //sns ios platform arn
        public string iOSPlatformApplicationArn = "";
        
        //project id for android gcm
        public string GoogleConsoleProjectId = "";

        public string CognitoIdentityRegion = RegionEndpoint.USEast1.SystemName;

        private RegionEndpoint _CognitoIdentityRegion
        {
            get { return RegionEndpoint.GetBySystemName(CognitoIdentityRegion); }
        }

        public string SNSRegion = RegionEndpoint.USEast1.SystemName;

        private RegionEndpoint _SNSRegion
        {
            get { return RegionEndpoint.GetBySystemName(SNSRegion); }
        }
            
        public Button RegisterButton;
        public Button UnregisterButton;
        
        public Text ResultText;
        
        private string _endpointArn;
        
        // Use this for initialization
        void Start()
        {
            UnityInitializer.AttachToGameObject(this.gameObject);
            RegisterButton.onClick.AddListener(RegisterDevice);
            UnregisterButton.onClick.AddListener(UnregisterDevice);
        }
        
        private AWSCredentials _credentials;
        
        private AWSCredentials Credentials
        {
            get
            {
                if (_credentials == null)
                    _credentials = new CognitoAWSCredentials(IdentityPoolId, _CognitoIdentityRegion);
                return _credentials;
            }
        }
        
        private IAmazonSimpleNotificationService _snsClient;
        
        private IAmazonSimpleNotificationService SnsClient
        {
            get
            {
                if (_snsClient == null)
                    _snsClient = new AmazonSimpleNotificationServiceClient(Credentials, _SNSRegion);
                return _snsClient;
            }
        }
        
        private void RegisterDevice()
        {
#if UNITY_ANDROID
            ResultText.text += string.Format("Hey you started..." + _credentials.ToString());
            if (string.IsNullOrEmpty(GoogleConsoleProjectId))
            {
                Debug.Log("sender id is null");
                ResultText.text += string.Format("sender id is null");
                return;
            }
            GCM.Register((regId) =>
            {
                //ResultText.text += string.Format("regId: " + regId);
                if (string.IsNullOrEmpty(regId))
                {
                    ResultText.text = string.Format(" Failed to get the registration id");
                    return;
                }
                
                ResultText.text = string.Format(@"Your registration Id is = {0}", regId);
                
                SnsClient.CreatePlatformEndpointAsync(
                    new CreatePlatformEndpointRequest
                    {
                        Token = regId,
                        PlatformApplicationArn = AndroidPlatformApplicationArn
                    },
                    (resultObject) =>
                    {
                        if(resultObject.Exception==null)
                        {
                            CreatePlatformEndpointResponse response = resultObject.Response;
                            _endpointArn = response.EndpointArn;
                            ResultText.text += string.Format(@"Platform endpoint arn is = {0}", response.EndpointArn);                            
                        }
                    }
                );
            }, GoogleConsoleProjectId);
#elif UNITY_IOS
#if UNITY_5
//#if UNITY_5_3_OR_NEWER
            UnityEngine.iOS.NotificationServices.RegisterForNotifications(UnityEngine.iOS.NotificationType.Alert | UnityEngine.iOS.NotificationType.Badge | UnityEngine.iOS.NotificationType.Sound);
#else
            NotificationServices.RegisterForRemoteNotificationTypes(RemoteNotificationType.Alert|RemoteNotificationType.Badge|RemoteNotificationType.Sound);
#endif
            CancelInvoke("CheckForDeviceToken");
            InvokeRepeating("CheckForDeviceToken",1f,1f);
#endif
        }
        string deviceToken = null;
        //to keep a track of max number of times the device token is polled
        int count = 0;
        private void CheckForDeviceToken()
        {
#if UNITY_IOS
//#if UNITY_5
#if UNITY_5_3_OR_NEWER
            var token = UnityEngine.iOS.NotificationServices.deviceToken;
            var error = UnityEngine.iOS.NotificationServices.registrationError;
#else
            var token = NotificationServices.deviceToken;
            var error = NotificationServices.registrationError;
#endif
            if(count>=10 || !string.IsNullOrEmpty(error))
            {
                CancelInvoke("CheckForDeviceToken");
                Debug.Log(@"Cancel polling");
                return;
            }
            
            if(token!=null)
            {
                deviceToken = System.BitConverter.ToString(token).Replace("-","");
                Debug.Log("device token  = " + deviceToken);
                ResultText.text = string.Format(@"Your device token is = {0}", deviceToken);
                SnsClient.CreatePlatformEndpointAsync(
                    new CreatePlatformEndpointRequest
                    {
                        Token = deviceToken,
                        PlatformApplicationArn = iOSPlatformApplicationArn
                    },
                    (resultObject) =>
                    {
                        if(resultObject.Exception==null)
                        {
                            CreatePlatformEndpointResponse response = resultObject.Response;
                            _endpointArn = response.EndpointArn;
                            ResultText.text += string.Format("\n Subscribed to Platform endpoint arn = {0}", response.EndpointArn);
                        }
                    }
                );
                
                CancelInvoke("CheckForDeviceToken");
            }
            count++;
#endif
        }

        private void UnregisterDevice()
        {
            if(!string.IsNullOrEmpty(_endpointArn))
            {
                SnsClient.DeleteEndpointAsync(
                    new DeleteEndpointRequest
                    {
                        EndpointArn = _endpointArn
                    },
                    (resultObject)=>{
                        if(resultObject.Exception == null)
                        {
                            Debug.Log("Deleted the endpoint. You will not get any new notifications");
                            ResultText.text = @"You will not get any new notifications";
                        }
                    }
                );
            }
        }
        
    }
}

**Comment by klaytaybai** [comment]
Hi @abiehusney25, support for the AWS SDK for Unity has been deprecated.  To continue using Unity with AWS, please follow the instructions in [this blog post about the deprecation](https://aws.amazon.com/blogs/developer/aws-sdk-for-net-v3-5-preview/).  By utilizing the new method, you will also gain access to all AWS services in your Unity projects and improved async.

**Comment by abiehusney25** [comment]
@klaytaybai 

Thank you for the response.

I have been trying to integrate the new  .NET Standard 2.0 but cannot get the c# code to run.

This is for unity:

What I am trying to do is just create an endpoint on aws sns:

First what I need is the android and IOS deviceToken. I cannot get the tokens

Then I run

 SnsClient.CreatePlatformEndpointAsync(
                new CreatePlatformEndpointRequest
                {
                    Token = deviceToken,
                    PlatformApplicationArn = iOSPlatformApplicationArn/AndroidPlatformApplicationArn
                },

I cannot get code that runs this for the new dlls, and I cannot find a walk-through on how to create endpoints on android and IOS 

Do you have a sample Unity project I could import and try out...
