### ISSUE TITLE
AmazonMediaStoreDataClient sends invalid data when using chunked transfer

### ISSUE THREAD

**Issue by vindor** [aws/aws-sdk-net#1533]
Hello,

I'm trying to use the AmazonMediaStoreDataClient to stream objects in chunks. 

## Expected Behavior

For example, if I send `testdata` as bytes, the data in the MediaStore object should be `testdata` even if chunked transfer is used.

## Current Behavior

At the moment this is not the case when using the AmazonMediaStoreDataClient. Instead the uploaded data in the MediaStore contains the chunked transfer header (length of the content as hex) and tail:
```
8
testdata
0
```

## Possible Solution
This behavior is not the same when using the Python SDK (boto3/botocore). There, the data in the MediaStore object is only `testdata` as it should be. I've narrowed down the difference between the two implementations and I think it is about how the packets are sent. For example the botocore implementation uses the urllib3 library to make the [chunked request](https://github.com/urllib3/urllib3/blob/1dd69c5c5982fae7c87a620d487c2ebf7a6b436b/src/urllib3/connection.py#L201). It sends the chunk header, a CRLF, the chunk payload (`testdata`), a CRLF and the tail. The .NET implementation sends everything at once (parts of the implementation in [HttpHandler](https://github.com/aws/aws-sdk-net/blob/b8e87705d351f2f62d236ea9407b864086b9b3d0/sdk/src/Core/Amazon.Runtime/Pipeline/HttpHandler/HttpHandler.cs#L407) and [ChunkedUploadWrapperStream](https://github.com/aws/aws-sdk-net/blob/b8e87705d351f2f62d236ea9407b864086b9b3d0/sdk/src/Core/Amazon.Runtime/Internal/Util/ChunkedUploadWrapperStream.cs#L38)).

Here are some [Wireshark](https://www.wireshark.org/) logs and screenshots showing both behaviors when sending requests to a test server running on localhost.

#### .NET 
[wireshark-net.pcapng.zip](https://github.com/aws/aws-sdk-net/files/4231750/wireshark-net.pcapng.zip)
![wireshark-net-dechunked body](https://user-images.githubusercontent.com/8329135/74954300-2d4ede80-5403-11ea-84fe-e9963a344451.png)

#### Python
[wireshark-python.pcapng.zip](https://github.com/aws/aws-sdk-net/files/4231753/wireshark-python.pcapng.zip)
![wireshark-python-dechunked body](https://user-images.githubusercontent.com/8329135/74954325-38a20a00-5403-11ea-9c28-772d6011aa1e.png)

## Steps to Reproduce (for bugs)
Here is a small .NET Core console application to push against the test server on localhost. It uses a non-seekable stream to force the use of the ChunkedUploadWrapperStream in the HttpHandler.
```
using Amazon.MediaStoreData;
using System;
using System.IO;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    public class NonSeekableMemoryStream : MemoryStream
    {
        public NonSeekableMemoryStream(byte[] buffer) : base(buffer)
        {
        }

        /// <summary>
        /// Make it non-seekable to simulate chunked input
        /// </summary>
        public override bool CanSeek
        {
            get { return false; }
        }
    }
    class Program
    {
        public static void Main(string[] args)
        {
            try
            {
                MainAsync(args).GetAwaiter().GetResult();
            }
            catch (AmazonMediaStoreDataException)
            {
                //  Catch error due to an invalid test server response
            }
        }

        public static async Task MainAsync(string[] args)
        {
            var client = new AmazonMediaStoreDataClient("http://127.0.0.1/api");

            var stream = new NonSeekableMemoryStream(Encoding.UTF8.GetBytes("testdata"));
            await client.PutObjectAsync(new Amazon.MediaStoreData.Model.PutObjectRequest()
            {
                UploadAvailability = UploadAvailability.STREAMING,
                Body = stream,
                Path = "testfolder/item.txt"
            });
        }
    }
}
```

## Your Environment
* AWSSDK.Core version used: 3.3.104.27
* AWSSDK.MediaStoreData version used: 3.3.101.110
* Operating System and version: Windows 10 Version 10.0.18363 Build 18363

## .NET Core Info
* .NET Core version used for development:  3.1
* .NET Core version installed in the environment where application runs:  3.1

**Comment by klaytaybai** [comment]
Thanks for reporting this!
