### ISSUE TITLE
PutObjectAsync bad linux performance 

### ISSUE THREAD

**Issue by bruizarroyo** [aws/aws-sdk-net#1538]
I upload 8000 blobs of 512 bytes each using the Async call and waiting at the end for all.

On windows it works OK, it takes 6.6 seconds. But on Linux the same code doesn't end, I have to kill it after 15 minutes. I include the sample code.

If I limit the number of tasks that are processed at the concurrently time it works. But the performance is much worse. It takes about 23s with a limit of 40 tasks (on Windows and Linux). 

## Expected Behavior
I expected that the code ends on Linux on a similar time than on Windows (6.6 seconds)

## Current Behavior
On Linux,  I have to kill the process after a several minutes.

## Steps to Reproduce (for bugs)
Execute the following code.

```
ServicePointManager.UseNagleAlgorithm = false;
ServicePointManager.Expect100Continue = false;
ServicePointManager.DefaultConnectionLimit = 500;

string bucket = "XXXXX"

AmazonS3Client s3Client = new AmazonS3Client(
    "XXXXXX",
    "XXXXXX",
    new AmazonS3Config
    {
        MaxErrorRetry = 5,
        RegionEndpoint = RegionEndpoint.GetBySystemName("eu-west-1"),
    });

Random rnd = new Random();
int dataSize = 512;
List<FileData> files = new List<FileData>();
for (int i = 1; i <= 8000; i++)
{
    byte[] data = new byte[dataSize];
    rnd.NextBytes(data);
    files.Add(new FileData(i, data));
}

string prefix = Guid.NewGuid().ToString("N") + "/";

List<Task> allTasks = new List<Task>(files.Count);
foreach (FileData file in files)
    allTasks.Add(Upload(bucket, prefix, file.Id, file.Data, s3Client));

Task.WhenAll(allTasks).GetAwaiter().GetResult();


static async Task Upload(
    string bucket,
    string blobsPrefix,
    long revId,
    byte[] data,
    AmazonS3Client s3Client)
{
    PutObjectRequest request = new PutObjectRequest();
    request.BucketName = bucket;
    request.Key = blobsPrefix + revId;
    request.ContentType = "application/octet-stream";

    using (MemoryStream dataStream = new MemoryStream(data, 0, data.Length, false))
    {
        request.InputStream = dataStream;
        await s3Client.PutObjectAsync(request);
    }
}

struct FileData
{
    internal int Id;
    internal byte[] Data;
    internal FileData(int id, byte[] data)
    {
        Id = id;
        Data = data;
    }
}
```

## Context
For our app write & read blobs quickly is critical. We read & write several files on groups like the tested one.

## Your Environment

* AWSSDK.Core version used: 3.3.104.27
* Service assembly and version used: AWSSDK.S3 3.3.110.25 
* Operating System and version: Debian 8.10 & Windows 10 (18363.657)
* Visual Studio version: Visual Studio Code
* Targeted .NET platform: .Net core 3.1

## .NET Core Info
* .NET Core version used for development:. 3.1
* .NET Core version installed in the environment where application runs: none, the dotnet publish content is used. 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by normj** [comment]
Where were you running your code, in EC2? If you were running in EC2 can you let me know what instance types you used?

**Comment by bruizarroyo** [comment]
I run it on a local machine.
Yes, with the 40 limit it takes about 23s on Windows and Linux. It takes a little more on Linux but the difference is less than 1s.

**Comment by bruizarroyo** [comment]
Increasing the open files limits on Linux, the test run on more or less on the same time than on Windows

**Comment by normj** [comment]
Interesting, can you explain how you increased the open files limit?

**Comment by JosuGZ** [comment]
I think you can edit `/etc/sysctl.conf` with something like `fs.file-max = 100000`.

**Comment by bruizarroyo** [comment]
I'm afraid but it's still not working from outside Amazon. 

We show that the original test on the original machine was throwing several errors "too many open files". But we launch the new tests on Amazon.

We did the test to compare the speed using a Linux EC2 instance m5d.2xlarge & a Windows EC2 instance c5.2xlarge on both cases it 3,7s on Linux and 3,5s.

Regarding the limit it can be changed using:

- `sysctl -w fs.file-max=100000` -> That changes it only until the next reboot
- To make the change persistent you need to edit `/etc/sysctl.conf` file and put following line `fs.file-max = 100000` 

The test is using a huge amount of handles. If I get the open handles during the test, there were more than 222k:
```
$ lsof | wc -l
223906
```
When executing the same after killing the process return a much smaller number:
```
$ lsof | wc -l
15004
```

But after increasing the limit, the test is still failing on the original Linux machine, but with a different error. Now it fails with the error:
```
The SSL connection could not be established, see inner exception
Authentication failed, see inner exception
SSL Handshake failed with OpenSSL error - SSL_ERROR_ZERO_RETURN
```

This error usually means that the TLS/SSL connection has been closed. But I don't know why it's closed. Maybe it's a timeout, but why is reaching the timeout that is so high by default. 

This error is not happing limiting the concurrent calls on the same Linux. On the original Windows is not given any error.

I cannot understand why it's opening that huge amount of handles to upload 8k blobs. I cannot understand why the SSL connection

**Comment by bruizarroyo** [comment]
Is there any news about this?

Although it works inside the Amazon instances (after updating the open file limits), it doesn't work from local Linux servers.

We used the Amazon instances for testing, but we need to use it from outside (not with the Amazon instances).

We have other alternatives that we are using as a workaround by there are much slower than this one.

**Comment by ashishdhingra** [comment]
Hi @bruizarroyo,

Good afternoon.

I was going through the issue backlog and came across this issue. I don't see any movement on this issue and not sure if this is a bug in the SDK, rather than an environmental issue. Please let me know if this issue could be closed. 

Thanks,
Ashish

**Comment by bruizarroyo** [comment]
Hi,

I think that it's an issue under load on the SDK. But I cannot be sure.

We were unable to make it work outside the AWS on those machines.

We finally decide to use the REST API directly for some performance reasons and it works without any problem under the same or more load on the same VM. 

Anyway, as we are no longer using the SDK, we are no longer affected but his issue.

Best regards,

Borja

**Comment by ashishdhingra** [comment]
@bruizarroyo Thanks got your reply. I will close this issue for now.
