### ISSUE TITLE
ProfileAWSRegion should consider AWSProfileName from config as well

### ISSUE THREAD

**Issue by McDoit** [aws/aws-sdk-net#1539]
Currently the ProfileAWSRegion doesnt consider the AWSProfileName set from config

## Expected Behavior
It should consider a profile name set by AWSProfileName in config

## Current Behavior
Currently it is only considering the Environment variable 

## Possible Solution
```
public ProfileAWSRegion(ICredentialProfileSource source)
{
    var profileName = Amazon.AWSConfigs.AWSProfileName;
    if (profileName == null)
        profileName = Environment.GetEnvironmentVariable(FallbackCredentialsFactory.AWS_PROFILE_ENVIRONMENT_VARIABLE);
    if (profileName == null)
        profileName = FallbackCredentialsFactory.DefaultProfileName;
    Setup(source, profileName);
}
```
or something similar in 
https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/AWSRegion.cs
## Steps to Reproduce (for bugs)
app.config:
```
<configuration>
  <appSettings>
    <add key="AWSProfileName" value="test-profile" />
  </appSettings>
</configuration>
```
code (tested in linqpad):
```
var cpod = new CredentialProfileOptions
{
    AccessKey = "access_key",
    SecretKey = "secret_key"
};

var defaultProfile = new CredentialProfile("default", cpod);

defaultProfile.Region = RegionEndpoint.EUWest1;

var cpo = new CredentialProfileOptions
{
    RoleArn = "arn:aws:iam::X:role/Role",
    SourceProfile = "default"
};

var testProfile = new CredentialProfile("test-profile", cpo);

testProfile.Region = RegionEndpoint.EUNorth1;

var sc = new Amazon.Runtime.CredentialManagement.CredentialProfileStoreChain();

sc.RegisterProfile(defaultProfile);
sc.RegisterProfile(testProfile);

var ec2c = new AmazonEC2Client();	

Console.WriteLine(ec2c.Config.RegionEndpoint.SystemName);
```		

this prints eu-west-1 but should print eu-north-1

## Context
Trying to create a profile with its own region setting, and not using the default one

## Your Environment

* AWSSDK.Core version used: 3.3.104.29
* Service assembly and version used: 
AWSSDK.EC2 3.3.162
AWSSDK.SecurityToken 3.3.104.35
* Operating System and version: Win 10 1909
* Visual Studio version: 
* Targeted .NET platform:

**Comment by klaytaybai** [comment]
Thanks for the feedback.  I agree that your expectations seem right.  I think there may be concerns about breaking changes if we were to solve this problem.  I'll bring it up and see if we can get a decision made.

**Comment by ashishdhingra** [comment]
This has been fixed in `AWSSDK.Core Core 3.7.0.40`
