### ISSUE TITLE
S3 file download Fails for UWP

### ISSUE THREAD

**Issue by ImCarrot** [aws/aws-sdk-net#1541]
Hi working with this SDK (`3.3.110.29`) and UWP. In UWP we don't have access to file system instead we can store to Local AppData stores. Below is my code:

    public async Task DownloadContent()
    {
        var request = new GetObjectRequest
        {
            BucketName = Constants.S3BucketName,
            Key = Constants.BackboneFileName
        };

        using (var response = await _client.GetObjectAsync(request))
        {
            response.WriteObjectProgressEvent += Response_WriteObjectProgressEvent;
            Windows.Storage.StorageFolder localFolder = Windows.Storage.ApplicationData.Current.LocalFolder;
            await response.WriteResponseStreamToFileAsync(localFolder.Path, false);
        }
    }

On running this code I get the error: 

> System.IO.FileNotFoundException: 'The filename, directory name, or volume label syntax is incorrect. (Exception from HRESULT: 0x8007007B)'

I also tried it via the `TransferUtility` using the below code:

            TransferUtility fileTransferUtility = new TransferUtility(_client);

            Windows.Storage.StorageFolder localFolder = Windows.Storage.ApplicationData.Current.LocalFolder;

            var path = localFolder.Path + @"\Backbone.json";

            TransferUtilityDownloadRequest downloadRequest = new TransferUtilityDownloadRequest()
            {
                BucketName = Constants.S3BucketName,
                Key = Constants.BackboneFileName,
                FilePath = path
            };

            await fileTransferUtility.DownloadAsync(downloadRequest);

But the outcome is same and the `TransferUtility` doesn't have a way to track progress of the download since the package I am trying to pull down is approx 2GB

**Comment by klaytaybai** [comment]
What is your stack trace?  How are you supplying credentials?  The issue might be with the app data file path you are providing, but I'm hoping the stack traces might reveal a problem loading credentials from the default credentials profile.  That would be easier to fix.

**Comment by ImCarrot** [comment]
I've made a `readonly` instance of the aws client and init it in the constructor when an instance of `S3Service` (my class) is made   
    private readonly IAmazonS3 _client;

    public S3Service() =>
            _client = new AmazonS3Client(Constants.S3AccessKey, Constants.S3AccessSecret, RegionEndpoint.APSouth1);

Below is the stack trace:

	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at PCLStorage.WinRTFolder.<CreateFolderAsync>d__12.MoveNext()
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at Amazon.S3.Model.GetObjectResponse.<CreateDirectory>d__137.MoveNext()
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at Amazon.S3.Model.GetObjectResponse.<WriteResponseStreamToFileAsync>d__135.MoveNext()
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	at MyTestApplication.Services.S3Service.<DownloadContent>d__2.MoveNext() in X:\1. Projects\CSharp\MyTestApplication\Services\S3Service.cs:line 58

**Comment by klaytaybai** [comment]
Hi @ImCarrot, I see why you're experiencing this problem.  However, we have no plans to fix it.  We are in the process of deprecating platform specific code for Unity, Xamarin, UWP, and Silverlight in order to accelerate feature development and offer newer functionality to all users.  The problematic code lies in a file that will be deleted when the deprecation is complete.  You may want to consider trying out our [AWS SDK for .NET 3.5 preview build that targets .NET Standard 2.0](https://aws.amazon.com/blogs/developer/aws-sdk-for-net-v3-5-preview/).  I believe that will fix your problem.

**Comment by ImCarrot** [comment]
@klaytaybai Alright thanks for atleast letting me know about this maybe put out a deprecation notice on online sources so that people can know about this and can directly use the relevant lib. 

That being said, can you please share a link to the nugget and the link to the documentation for it? Also the issue that I've reported is that handled in a stable release or is it just available as part of a preview release
