### ISSUE TITLE
is there any issue to bypass MD5Stream() in Model.Internal.MarshallTransformations.Marshall()?

### ISSUE THREAD

**Issue by immarvin** [aws/aws-sdk-net#1542]
We found` MD5Stream()` in `Model.Internal.MarshallTransformations.Marshall()` cause cpu spike, we would like to bypass `MD5Stream()`.

We did not pass `uploadPartRequest.MD5Digest` to `Marshall()`, so there will be comparison inside `MD5Stream()`. 
```
Amazon.S3.Model.Internal.MarshallTransformations.Marshall():

		public IRequest Marshall(UploadPartRequest uploadPartRequest)
		{
...
			if (uploadPartRequest.IsSetMD5Digest())
			{
				request.Headers["Content-MD5"] = uploadPartRequest.MD5Digest;
			}
...
			if (uploadPartRequest.InputStream != null)
			{
...
				MD5Stream mD5Stream = (MD5Stream)(uploadPartRequest.InputStream = new MD5Stream(partialWrapperStream, null, partialWrapperStream.Length));
			}
			request.ContentStream = uploadPartRequest.InputStream;
...
			return request;
		}
	}
```

I have 2 questions here:
1. how does `MD5Stream mD5Stream = (MD5Stream)(uploadPartRequest.InputStream = new MD5Stream(partialWrapperStream, null, partialWrapperStream.Length));`  modify the `uploadPartRequest.InputStream`? what is the modification for? will there be some accroding validation in server side ?
2. we would like to bypass the conversion `MD5Stream mD5Stream = (MD5Stream)(uploadPartRequest.InputStream = new MD5Stream(partialWrapperStream, null, partialWrapperStream.Length));` , will there be any potential issue? thanks

**Comment by klaytaybai** [comment]
What is your reasoning for bypassing the conversion?  Are you simply trying to improve efficiency?  We typically don't recommend modifying code within the "Internal" namespaces.

The conversion does not alter the underlying stream.  The data sent to the service will be the same that you specified.  However, you can intercept the request before it is made with `client.BeforeRequestEvent += handler` and get the value of the MD5 hash prior to sending the request.  You can use this MD5 hash to validate the integrity of an S3 upload.

**Comment by immarvin** [comment]
hi @klaytaybai  , thanks for reply

> What is your reasoning for bypassing the conversion? Are you simply trying to improve efficiency? We typically don't recommend modifying code within the "Internal" namespaces.

we observed the MD5 calculation cost a lot of cpu, which caused the service to be unavailable due to cpu limitation of the K8S pod under low workload. 
We decided to bypass md5 by modifying the code because the SDK does not provide any option or arguments to do so, I noticed that there are already several tickets on the high cpu usage caused by this in the bugzilla, do you have some recommended method to avoid this issue?

> The conversion does not alter the underlying stream. The data sent to the service will be the same that you specified. However, you can intercept the request before it is made with client.BeforeRequestEvent += handler and get the value of the MD5 hash prior to sending the request. You can use this MD5 hash to validate the integrity of an S3 upload.

so the MD5 validation is only performed on the client or SDK side, not on the server side, is it?

**Comment by Woody-Hu** [comment]
Now I only found https://github.com/aws/aws-sdk-net/blob/ae822fc19be5d95e38e777672f51c9358be99a6d/sdk/src/Services/S3/Custom/Internal/AmazonS3ResponseHandler.cs#L111 will use MD5 stream to validate response.

**Comment by HermanFeng1985** [comment]
@klaytaybai Can you share more about how the md5 works in sdk? Is this feature optional? If it must to have, why?

**Comment by immarvin** [comment]
any comments on the new questions above?

**Comment by kevin-wyx** [comment]
According to S3 API docs, Content-MD5 is an optional header in S3 requests[1], and it's not required in requests like complete multipart upload[2]. It would be great to have an option to skip Content-MD5/checksum calculation in a request, just like SkipMd5CheckStrategy in Java sdk[3] and compute_checksums in ruby sdk[4].


1.https://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonRequestHeaders.html
2.https://docs.aws.amazon.com/AmazonS3/latest/API/API_CompleteMultipartUpload.html
3.https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/internal/SkipMd5CheckStrategy.html
4.https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html

**Comment by boblodgett** [comment]
As of AWSSDK.Core 3.5.1.28 and AWSSDK.S3 3.5.3.6:

TransferUtilityUploadRequest, PutObjectRequest, and UploadPartRequest have two additional properties:
   1. DisableMD5Stream
   2. DisablePayloadSigning

In addition, AWSConfigsS3.DisableMD5Stream is a global property to disable MD5Stream so that it does not need to be set on each request.

These properties each disable a data integrity check which consumes some percentage of the CPU during upload. Before use, view the comments on each property to get a better understanding of the effect of disabling one of these checks.

As mentioned in the property comments, disabling both checks results in HTTPS being the only remaining source of data integrity verification.

https://github.com/aws/aws-sdk-net/commit/1d005dbefb3bc1f8d74966d1da1203b20f342530
