### ISSUE TITLE
Seeking clarification for S3 client thread-safety and disposal

### ISSUE THREAD

**Issue by KenHundley** [aws/aws-sdk-net#1544]
I've seen some conflicting information around reuse of the S3 client and I'm seeking some clarification around thread-safety and disposal.

The documentation states that all the Clients are thread-safe and should be reused, but I've also found examples in the documentation like:
```C#
using(var client = new Amazon.S3.AmazonS3Client())
{
    var request = new GetObjectRequest
    {
        BucketName = bucketName, Key = key
    };
    using(var response = client.GetObject(request))
    {
        response.ResponseStream.CopyTo(ms);
    }
}
```
with the note:
> As you can see, we wrapped both the client and the response in using blocks. This makes sure that we dispose of the underlying .NET web streams. (If these are not properly disposed of, you may eventually not be able to make any service calls at all.)

>There are two disposable response objects like this in the SDK: Amazon.S3.Model.GetObjectResponse and Amazon.S3.Model.GetObjectTorrentResponse.

Is this meaning that the the client is safe for reuse on all calls except GetObject and GetObjectTorrent, and those must always get new clients and dispose of them? It's not enough to properly dispose of the Response object, and must always dispose of the client after these calls?

A little context around the app that is using the client. It's a containerized API microservice that highly multi-threaded and handles around 1k requests per minute, per container. Each request would call the GetObject call at-most once. Many requests would not contain the GetObject call, but may make calls to HeadObject, PutObject, etc. 

With this information, would it be better to create an instance per request? That way we are at least reusing the object across the request, but it will still be disposed at the end of that requests to prevent the web stream issue.

Any clarification here would be highly appreciated. 

## Your Environment

* AWSSDK.Core version used: Current version
* Service assembly and version used: S3 Current
* Operating System and version: Alpine 3
* Visual Studio version: 2019
* Targeted .NET platform: .Net Core 2.1

## .NET Core Info

* .NET Core version used for development: 2.1
* .NET Core version installed in the environment where application runs: 2.1

**Comment by klaytaybai** [comment]
In general, to avoid running out of system resources both the client and the response stream should be disposed when not needed.  This does not mean that you can't reuse the client.  You probably want to reuse the same client unless you have a reason why it should be disposed or reconfigured.

**Comment by KenHundley** [comment]
So would you see any issue with this structure
```C#
//psudocode
Startup()
{
    services.AddAWSService<IAmazonS3>(); //Singleton by AWS default
}

//per request
public void ProcessRequest(IAmazonS3 s3)
    var request = new GetObjectRequest
    {
        BucketName = bucketName, Key = key
    };
    using(var response = s3.GetObject(request))
    {
        response.ResponseStream.CopyTo(ms);
    }
}
```
Specifically in relation to the comment:  
> This makes sure that we dispose of the underlying .NET web streams. (If these are not properly disposed of, you may eventually not be able to make any service calls at all.)

I'm asking because it's not clear if the web streams held by the client or the repsonse object. I'm assuming the response object, but you know about assuming :)

**Comment by xendren** [comment]
> So would you see any issue with this structure
> 
> ```cs
> //psudocode
> Startup()
> {
>     services.AddAWSService<IAmazonS3>(); //Singleton by AWS default
> }
> 
> //per request
> public void ProcessRequest(IAmazonS3 s3)
>     var request = new GetObjectRequest
>     {
>         BucketName = bucketName, Key = key
>     };
>     using(var response = s3.GetObject(request))
>     {
>         response.ResponseStream.CopyTo(ms);
>     }
> }
> ```
> 
> Specifically in relation to the comment:
> 
> > This makes sure that we dispose of the underlying .NET web streams. (If these are not properly disposed of, you may eventually not be able to make any service calls at all.)
> 
> I'm asking because it's not clear if the web streams held by the client or the repsonse object. I'm assuming the response object, but you know about assuming :)

Did you ever get a response?  Do you need to dispose of the response after each call to prevent leaking?
