### ISSUE TITLE
Support for StorageFile while downloading from S3 UWP

### ISSUE THREAD

**Issue by ImCarrot** [aws/aws-sdk-net#1546]
Hi, This is a continuation from [this thread](https://github.com/aws/aws-sdk-net/issues/1541). I am working with the `AWSSDK.S3 3.5.0 Preview` and UWP.

## What I am trying to do:

Download a file from S3 to the App `LocalData folder` using a UWP application.

## Preface:

In UWP we don't have access to any directory via a File Path, moreover we have a `StorageFile` or `StorageFolder` Instance to work with for dealing with files and folders respectively. Now as soon as we do a `storageFolder.Path` we loose all access/permissions to the actual folder.

> The problem is that you are throwing away the picked StorageFile's permission by converting it to a path. ~ [MSDN Source](https://social.msdn.microsoft.com/Forums/office/en-US/ff62185a-5a3a-42fe-bc5a-d6bf9f60b0fa/uwpaccess-denied-while-writing-files-to-documents-in-uwp?forum=wpdevelop) 

And the only way of interacting via the FileSystem is using `StorageFile` / `StorageFolder` read more: [Skip the paths](https://docs.microsoft.com/en-us/archive/blogs/wsdevsol/skip-the-path-stick-to-the-storagefile) and [File Access Permissions](https://docs.microsoft.com/en-us/previous-versions/windows/apps/hh967755(v=win.10)?redirectedfrom=MSDN)

## What problem I am facing:

The `GetObjectResponse.WriteResponseStreamToFileAsync() accepts only `String` as a filePath but lacks overrides for StorageFiles / StorageFolders. 

Is there any way I can get this to work?

## Code that I am using to access and store the file:

```
var request = new GetObjectRequest
{
	BucketName = Constants.S3BucketName,
	Key = Constants.BackboneFileName
};

using (var response = await _client.GetObjectAsync(request))
using (var responseStream = response.ResponseStream)
using (var reader = new StreamReader(responseStream))
{

	response.WriteObjectProgressEvent += Response_WriteObjectProgressEvent;
	Windows.Storage.StorageFolder localFolder = Windows.Storage.ApplicationData.Current.LocalFolder;
	await response.WriteResponseStreamToFileAsync(localFolder.Path, false, new CancellationToken());
}
```

**Comment by klaytaybai** [comment]
Thanks for the follow-up clarification.  I'm labeling this as a feature request for now to have overrides for the StorageFiles, but I think it's unlikely that we will have plans in the near future to implement it given our move away from platform-specific code.  You can still write to the Windows StorageFiles if you write the streaming logic on your own.  The GetObjectResponse is a StreamingResponse, which means that you can access `response.ResponseStream`.  Using that property, you should be able to write to any file as you normally would.  If you want the additional functionality that our WriteResponseStreamToFileAsync methods provide, it probably wouldn't be too bad to copy the logic and write your own overrides for the StorageFiles.

**Comment by ImCarrot** [comment]
@klaytaybai thanks for the insights. Yes I did kinda anticipate your response on the topic as I was writing the question but posted it because there isn't anything available online regarding this and at least others who look into a similar topic would come across this thread and save some time at the very least. That being said I did start implementing my own using the `Stream` from the `S3 response`. I'll see if I can get an example with download progress up and running so as to share it with others facing the same issue.

**Comment by ImCarrot** [comment]
@klaytaybai can you please point me to the code in the SDK where the file downloading mechanism is written? I can't seem to find it

**Comment by Mogikan** [comment]
localFolder is not a file
await response.WriteResponseStreamToFileAsync(localFolder.Path

**Comment by ImCarrot** [comment]
@Mogikan yes I did go online and try to use a filepath instead, it didn't work either. It throws `AccessDeniedException`
