### ISSUE TITLE
S3 Client does not handle 302 and 303 correctly

### ISSUE THREAD

**Issue by talibsharif** [aws/aws-sdk-net#1547]
S3 Client does not handle 302 and 303 correctly

## Expected Behavior
- The client should follow the redirect.

## Current Behavior
- The client throws an Exception with an Unexpected HTTP Status Code

## Possible Solution
- Fix the Client Code to act the same has HTTP 307

**Comment by talibsharif** [comment]
Here is the Pull Request Addressing this:
https://github.com/aws/aws-sdk-net/pull/1548

**Comment by klaytaybai** [comment]
Thanks for the PR.

**Comment by talibsharif** [comment]
hi @klaytaybai - can you give some guidance on the timelines for getting such a fix into a release version? This will help us know whether to wait for update or just compiled and use a forked build (would prefer not to).

**Comment by ashishdhingra** [comment]
Hi @talibsharif,

Good afternoon.

Looks like the PR #1548 was not approved by @normj. Please let me know if we could close this issue.

Thanks,
Ashish
