### ISSUE TITLE
Dynamo Db CreateBatchWrite not Persisting All Values

### ISSUE THREAD

**Issue by JustinJohnWilliams** [aws/aws-sdk-net#1549]
## Expected Behavior

When executing a batch insert, dynamo should persist ALL items or throw an exception if some fail to write due to capacity limitations. I would expect an exception of type `ProvisionedThroughputExceededException` to be thrown if some of the items fail to write.

## Current Behavior

On initial attempt to batch write only a portion of my objects are written to dynamo db. No exceptions are thrown or logged. e.g. log says "305 items written to dynamo", however, dynamo only has 55 records in it. If I re-run the lambda, all 305 items are written.

## Steps to Reproduce (for bugs)

```
public async Task InsertBatchAsync<T>(IEnumerable<T> objectsToInsert)
{
    try
    {
        using(var client = new AmazonDynamoDBClient(_config))
        using (var dbContext = new DynamoDBContext(client))
        {
            var batch = dbContext.CreateBatchWrite<T>();

            batch.AddPutItems(objectsToInsert);

            await batch.ExecuteAsync();

            LambdaLogger.Log($"Info - Batch inserted {objectsToInsert.Count()} {typeof(T).Name} items.");
        }
    }
    catch (Exception exception)
    {
        LambdaLogger.Log($"Error - {exception.Message}");
        throw;
    }
}
```

In my Lambda logs, I see the info log, not an error log.

## Context

I am gathering report data from a few different places, aggregating them into a single object an store a list of those objects into a dynamo table via a cloudwatch cron job executing a lambda once a week. I write several reports for each of our customer accounts. I have auto scaling turned on with Dynamo to accommodate a sudden burst in writing a bunch of objects to the table.

## Your Environment

* AWSSDK.Core version used: `3.3.104.32`
* Service assembly and version used: `AWSSDK.DynamoDBv2` version: `3.3.105.6`
* Operating System and version: Lambda
* Visual Studio version: VSCode
* Targeted .NET platform: `netcoreapp2.1`

## .NET Core Info

* .NET Core version used for development: `netcoreapp2.1`
* .NET Core version installed in the environment where application runs: `netcoreapp2.1`
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>
    <AssemblyName>Reports</AssemblyName>
    <RootNamespace>Reports</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Query\**" />
    <EmbeddedResource Remove="Query\**" />
    <None Remove="Query\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.3.101" />
    <PackageReference Include="AWSSDK.Lambda" Version="3.3.108.5" />
    <PackageReference Include="Amazon.Lambda.APIGatewayEvents" Version="1.3.0" />
    <PackageReference Include="Amazon.Lambda.Core" Version="1.1.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.Json" Version="1.7.0" />
    <PackageReference Include="AWSSDK.Core" Version="3.3.104.32 " />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.3.105.6" />
    <PackageReference Include="AWSSDK.SecretsManager" Version="3.3.102.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="2.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="2.1.1" />
    <PackageReference Include="RestSharp" Version="106.10.0" />
  </ItemGroup>
</Project>
````

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
Was your problem resolved or does this issue still need work?

**Comment by JustinJohnWilliams** [comment]
it was resolved on my end
