### ISSUE TITLE
PutItemAsync of AWSSDK.DynamoDBv2 always returns null

### ISSUE THREAD

**Issue by armache** [aws/aws-sdk-net#1553]
Please see more details on: 
https://stackoverflow.com/questions/60581812/table-putitemasync-of-awssdk-dynamodbv2-always-returns-null

**Comment by klaytaybai** [comment]
Hello @armache, you need to specify the ReturnValues enum type in your PutItemOperationConfig and include this config in your request.  The default is to return None.  If you specify ReturnValues.AllOldAttributes (the only other option for this request), then you will get back the a document with the old item's attributes if you overwrote an item or an empty item if you added a new item.

                var putItemOperationConfig = new PutItemOperationConfig()
                {
                    ReturnValues = ReturnValues.AllOldAttributes
                };

**Comment by vivekgowdatv1992** [comment]
What should be the code . if i wanted return document item when i added a new item
