### ISSUE TITLE
[DynamoDB] Can I actually save an attribute of type Dictionary into a table?

### ISSUE THREAD

**Issue by RoyIL** [aws/aws-sdk-net#1557]
## Context
According to [DynamoDB's Attribute Value documentation](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_AttributeValue.html) the L attribute is similar to .NET's Dictionary type (List of Key-Value pairs, correct me if i'm wrong!).

However, there never seems to be a reference to the Dictionary type in the entire DynamoDB specific .NET documentation. I also went forward and took a look at the "[Supported Data Types Section](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.DataTypes.html)" in the Java documentation and it seems like DynamoDB's Java mapper is able to save Map<K,V> types as attributes (not sure about Map<K,V> sets though).

So as can be understood from my short description and to sum everything up: Can a Dictionary<Key, Value> (or KeyValuePair<Key, Value>) be saved into a DynamoDB table? 

Thanks in advance!

**Comment by klaytaybai** [comment]
Hi @RoyIL, you want to use the M (Map) type.  While the L type is a list of key-value pairs, these keys are actually other type indicators used to determine how data is stored and parsed.  Take another look at that original link you posted.

**Comment by RoyIL** [comment]
Ohhh, alright. My bad 😅.
What is the .NET equivalent of the "Map" Java type that DynamoDB uses? (Will KeyValuePair work?)

Thank you very much!

**Comment by RoyIL** [comment]
Found a response to my question in one of DynamoDB's / Lambda's .NET examples, closing.

**Comment by ADringer** [comment]
@RoyIL  Have you got a link to the example you found? I'm trying to solve the same problem.
