### ISSUE TITLE
AWS4Signer Behavior Doesn't Match Test Suite Examples

### ISSUE THREAD

**Issue by hakenmt** [aws/aws-sdk-net#1558]
The `AWS4Signer` appears to call `SetRequestBodyHash` in every signature call in the code [here](https://github.com/aws/aws-sdk-net/blob/e11d72cc57b19832973c783b331e18ba93e25dd7/sdk/src/Core/Amazon.Runtime/Internal/Auth/AWS4Signer.cs#L158). This is also what I see in reality. However, given the [Test Suite](https://docs.aws.amazon.com/general/latest/gr/signature-v4-test-suite.html) examples, it doesn't actually look like the signer would pass, since it adds the `x-amz-content-sha256` header to every request.

## Expected Behavior
Given the description of the SigV4 process, this suggestion may not be specific to the SDK, unless it is an incorrect behavior, but the Test Suite should include the content hash as part of the requests since it appears that any valid implementation of the process wouldn't pass those tests, since the `x-amz-content-sha256` header would always be added and computed as part of the signature.

**Comment by ashishdhingra** [comment]
Hi @hakenmt,

Good afternoon.

I was going through the issue backlog and came across this one. Not sure if this is an issue with the SDK, could you please point me to the Test Suite examples which might be failing?

Thanks,
Ashish

**Comment by hakenmt** [comment]
It appears the test suite has been removed from the documentation. Here's a link to an old version:
https://web.archive.org/web/20200405075117if_/https://docs.aws.amazon.com/general/latest/gr/signature-v4-test-suite.html

and a link to download the test suite files
https://docs.aws.amazon.com/general/latest/gr/samples/aws-sig-v4-test-suite.zip

This is the final content that would be sent in the request based on the test suite for the get-vanilla test:
```
GET /?Param2=value2&Param1=value1 HTTP/1.1
Host:example.amazonaws.com
X-Amz-Date:20150830T123600Z
Authorization: AWS4-HMAC-SHA256 Credential=AKIDEXAMPLE/20150830/us-east-1/service/aws4_request, SignedHeaders=host;x-amz-date, Signature=b97d918cfa904a5beff61c982a1b6f458b799221646efd99d3219ec94cdf2500
```

The request above doesn't include the `X-Amz-Content-SHA256` header. The `SignedHeaders` value for a real request would look like something like this:
`SignedHeaders=host;user-agent;x-amz-content-sha256;x-amz-date`. So, if you used the `AWS4Signer` code to sign the original request from get-vanilla, i.e. `get-vanilla.req`, it would not match the data provided in the test suite under `get-vanilla.sreq`. Hope that helps clarify.
