### ISSUE TITLE
SNS Message attributes emtpy/nullable values

### ISSUE THREAD

**Issue by 3GDXC** [aws/aws-sdk-net#1562]
## Expected Behavior
Adding an empty string value as a message attribute should allow posting/publishing of the message or nullable values

## Current Behavior
SNS currently fails to publish any message with attributes that have a empty string value

**Comment by klaytaybai** [comment]
Thanks for the bug report.  This looks like a simple fix.

**Comment by ashishdhingra** [comment]
Hi @3GDXC,

Good morning.

As per section **Message attribute items and validation** under [Amazon SNS message attributes](https://docs.aws.amazon.com/sns/latest/dg/sns-message-attributes.html) in [Amazon Simple Notification Service Developer Guide](https://docs.aws.amazon.com/sns/latest/dg/welcome.html), looks like Name, type, and value must not be empty or null. Hence, the services is giving error if we pass empty value for string MessageAttributeValue. Hope this provides some guidance. Please let me know if this issue could be closed.

Thanks,
Ashish

**Comment by 3GDXC** [comment]
@ashishdhingra thanks for the update; in which case I would expect that we shouldn't be able to add empty/null values to the collection and receive an exception accordingly, or preventing calling the publishing of the message.  following the catch exceptions early pattern as opposed to calling a service with know message issues and receiving errors

**Comment by ashishdhingra** [comment]
Hi @3GDXC,

I understand your concern about validation in place before actually sending the Publish request.

Here's the sample code I used to reproduce the issue:

```C#
string topicArn = "arn:aws:sns:us-east-2:NNNNNNNNNNNN:TestTopic";
string msg = "If you receive this message, publishing a message to an Amazon SNS topic works.";
var messageAttributes = new System.Collections.Generic.Dictionary<string, MessageAttributeValue>();
messageAttributes.Add("Test2", new MessageAttributeValue() { DataType = "String" , StringValue = "Test" });

using (AmazonSimpleNotificationServiceClient snsClient = new AmazonSimpleNotificationServiceClient("<accessKeyId>", "<secretAccessKey>", RegionEndpoint.USEast2))
{
    PublishRequest publishRequest = new PublishRequest() { TopicArn = topicArn, Message = msg, MessageAttributes = messageAttributes };
    PublishResponse publishResponse = snsClient.PublishAsync(publishRequest).Result;

    // Print the MessageId of the published message.
    Console.WriteLine("MessageId: " + publishResponse.MessageId);
}
```

The classes like _MessageAttributeValue_, _PublishRequest_ and _Dictionary_ (collection) are just plain .NET classes. As I see the current implementation of **SNSClient.PublishAsync()**, it is just a wrapper to invoke SNS Service API, and it just Marshalls the request object and invokes the Service API (there are exceptions to this rule though). Hence, until and unless we invoke the **SNSClient.PublishAsync()**, there is no place to validate for non-null/non-empty the attribute values. 

Hence the best way get around this problem is to add validation before adding item to MessageAttributeValue dictionary collection. Hope this answers your question.

Thanks,
Ashish

**Comment by 3GDXC** [comment]
@ashishdhingra I understand how to validate parameters and attributes etc. this however IMHO SHOULD NOT be the responsibility of the developer using the AWS-SDK but should be the responsibility of the SDK itself, preventing calls to the service that are known to be invalid is best-practice; and as rules may change the AWS-SDK would therefore change to enforce rules accordingly base on the service contract. (just like other API providers that may SOAP/RESTful/gRPC contract)

**Comment by ashishdhingra** [comment]
@3GDXC Thanks for the input. I agree with your concern and will pass on your feedback to the development team. However, with wrapper classes like these, I'm not sure if there would be a plan to change the current design. I will update you of any feedback that is received on this issue.

Thanks,
Ashish

**Comment by 3GDXC** [comment]
@ashishdhingra I'm unsure why/what would be stopping the teams developing the AWS-SDK from following best practices and introducing the model validations ? I understand these are generated using the tooling and the .json files; some of the .json files already have the metadata required to allow the generated code to validate (in part) the models

could it be as simple as adding the min/max length StringValue? 

 "MessageAttributeValue":{
      "type":"structure",
      "required":["DataType"],
      "members":{
        "DataType":{"shape":"String"},
        "StringValue":{"shape":"String"},
        "BinaryValue":{"shape":"Binary"}
      }
    },

**Comment by ashishdhingra** [comment]
@3GDXC Thanks for this input. I have added this to the list of items to discuss with development team and would provide an update soon.

**Comment by ashishdhingra** [comment]
@3GDXC We have created an internal backlog item to update the service model JSON with latest updates, which could include the validation criteria. I'm changing this issue to feature request for better tracking.
