### ISSUE TITLE
Client.GetObjectAsync() with large files - Oculus Quest

### ISSUE THREAD

**Issue by tenebris93** [aws/aws-sdk-net#1563]
## Expected Behavior
Client.GetObjectAsync() should return a response object.

## Current Behavior
Client.GetObjectAsync() crashes oculus quest headset's OS preventing any log data to be shown in Android Device Monitor.

## Steps to Reproduce (for bugs)
1) Upload a 1GB object to a private amazon s3 bucket.
2) Create an instance of AmazonS3Client:
IAmazonS3 Client = new AmazonS3Client(Credentials, _S3Region);
3) Initiate the get object request:
Client.GetObjectAsync(S3BucketName, "star_trails.mp4", (responseObj) => {});

## Context
Trying to download a 1 GB video file to an Oculus Quest headset to be played locally when offline.

Example Code used for testing:
```
    private AWSCredentials Credentials
    {
        get
        {
            if (_credentials == null)
                _credentials = new CognitoAWSCredentials(identityPoolId, _CognitoIdentityRegion);
            return _credentials;
        }
    }

    private IAmazonS3 Client
    {
        get
        {
            if (_s3Client == null)
            {
                _s3Client = new AmazonS3Client(Credentials, _S3Region);
            }

            return _s3Client;
        }
    }

    public void DownloadObject()
    {

        Client.GetObjectAsync(S3BucketName, "star_trails.mp4", (responseObj) =>
        {
            var response = responseObj.Response;

            if (response.ResponseStream != null)
            {
                string rootPath = Application.persistentDataPath;

                // Points to the place we access our videos.
                string videoPath = Path.Combine(rootPath, "StreamingAssets");

                using (var fs = File.Create(Path.Combine(videoPath, "video.mp4")))
                {
                    byte[] buffer = new byte[response.ContentLength];
                    int count;

                    while ((count = response.ResponseStream.Read(buffer, 0, buffer.Length)) != 0)
                    {
                        fs.Write(buffer, 0, count);
                    }

                    fs.Flush();
                }
            }
        });
    }
```

Debug Log:
```
03-25 11:00:36.849: E/Unity(9597): Could not allocate memory: System out of memory!
03-25 11:00:36.849: E/Unity(9597): Trying to allocate: 1090870032B with 16 alignment. MemoryLabel: WebRequest
03-25 11:00:36.849: E/Unity(9597): Allocation happened at: Line:75 in 
03-25 11:00:36.849: E/Unity(9597): Memory overview
03-25 11:00:36.849: E/Unity(9597): [ ALLOC_DEFAULT ] used: 28451816B | peak: 49836581B | reserved: 29077638B 
03-25 11:00:36.849: E/Unity(9597): [ ALLOC_TEMP_JOB ] used: 0B | peak: 0B | reserved: 5242880B 
03-25 11:00:36.849: E/Unity(9597): [ ALLOC_TEMP_BACKGROUND_JOB ] used: 0B | peak: 0B | reserved: 1048576B 
03-25 11:00:36.849: E/Unity(9597): [ ALLOC_GAMEOBJECT ] used: 882875B | peak: 937377B | reserved: 895681B 
03-25 11:00:36.849: E/Unity(9597): [ ALLOC_GFX ] used: 2994944B | peak: 38777811B | reserved: 2997661B 
03-25 11:00:36.849: E/Unity(9597): [ ALLOC_TEMP_THREAD ] used: 0B | peak: 0B | reserved: 2785280B 
03-25 11:00:36.849: E/Unity(9597):  
03-25 11:00:36.849: E/Unity(9597): (Filename:  Line: 1161)
03-25 11:00:36.849: E/Unity(9597): --------- beginning of crash
```

## Your Environment
UnityEditor: 2018.4.19f1
VisualStudio: Community 2017 - v15.9.21

Plugins Used:
* AWS SDK Unity: aws-sdk-unity_3.3.706.0
* AWSSDK.S3.3.3.110.39
* AWSSDK.CognitoSync.3.3.100.148
* AWSSDK.IdentityManagement.3.3.105.21

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by ashishdhingra** [comment]
Hi @tenebris93,

Starting with version 3.5 of the AWS SDK for .NET, projects using Unity 2018.1 or later should target the .NET Standard 2.0 release of the SDK. You can find additional information in the developer guide: [Unity support](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/unity-special.html) and [Migrating your Unity application](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/net-dg-v35.html#net-dg-v35-changes-unity).

Please try using the .NET Standard 2.0 version of the AWS SDK for .NET (version 3.5). 

Thanks,
Ashish
