### ISSUE TITLE
Should BatchWrite<T> implement an interface?

### ISSUE THREAD

**Issue by safv12** [aws/aws-sdk-net#1565]
I'm trying to write a unit test to validate the BatchWrite.Execute invocation, but I'm struggling with the mock of the `CreateBatchWrite<T>` method because I'm not able to instantiate the `BatchWrite<T>` class.

I'm using Moq to build the mocks, the code looks like:

```csharp
this.dynamoDbMock
    .Setup(m => m.CreateBatchWrite<SomeType>(It.IsAny<DynamoDBOperationConfig>()))
    .Returns(Mock.Of<BatchWrite<SomeType>>());
```

But the Returns part is throwing an error because the BatchWrite class does not have a default constructor. 

## Possible Solution
I think is a good idea to define an interface for the BatchWrite<T> class. In this way, the unit test will be easier to write.

```csharp
public class BatchWrite<T> : BatchWrite, IBatchWriteOperations
```

**Comment by Kralizek** [comment]
@ashishdhingra any comment on this? This is just one of many issues regarding the hard testability of code using DynamoDB.

**Comment by ashishdhingra** [comment]
> @ashishdhingra any comment on this? This is just one of many issues regarding the hard testability of code using DynamoDB.

@Kralizek Some DynamoDB revamp work is planned in the coming sprints and this feature request might be included as well. We would post any updates here.

**Comment by jakubbujak** [comment]
This is one of the worst libraries regarding testability. Shame on you Amazon, shame 😡

**Comment by Kilowhisky** [comment]
I just ran into this as well. Can't test any data layer code at all because of this.

**Comment by rferreiraLGC** [comment]
I am also unable to run tests at all due to this.

**Comment by rynkadink** [comment]
+1
This seems to have been designed without testability in mind, how can we test any data layer code when using this lib?

**Comment by Cussa** [comment]
Any news on that?

**Comment by Kralizek** [comment]
Still waiting for the rework...

**Comment by LBognanni** [comment]
+1, I worked around this by using the nullabilty operator when interacting with the BatchWrite object (ie `batch?.AddPutItem(thing)`)

I would also contend that the detail of BatchWrite should be ideally be hidden for the consumer and the dynamo context should expose something like `SaveAsync<T>(IEnumerable<T> things)` that handles batching internally

**Comment by 96malhar** [comment]
Hello, we have been working on the V4 of the AWS SDK for .NET. We have added the ability to mock various DynamoDB operations by adding interfaces in both the Data Model mode and Document Model mode in DynamoDB. 

Refer to this PR - https://github.com/aws/aws-sdk-net/pull/3450

This feature is available in the AWSSDK.DynamoDBv2 Version [4.0.0-preview.2](https://www.nuget.org/packages/AWSSDK.DynamoDBv2/4.0.0-preview.2)
