### ISSUE TITLE
Is there a way to generate aws-lambda-tools-defaults.json from current deployed function?

### ISSUE THREAD

**Issue by Thaina** [aws/aws-sdk-net#1568]
I have using aws lambda for years but now I want to migrate into new version of publishing pipeline of the same existing function. So I want to have publishing config derived from current config

Is it possible? If not I wish this would be considered feature request

## Expected Behavior
Have a command line `dotnet lambda get-publishing-config --region={region} -fn={name} [--targetfile | default to aws-lambda-tools-defaults.json]`

**Comment by ashishdhingra** [comment]
Hi @Thaina,

Good morning.

I don't think there is a flag to service publishing config from existing config. If you envision having to duplicate functions in the future, it may be worthwhile to use [AWS CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/Welcome.html) to create your Lambda Functions. Please let me know if this workaround works for you.

Thanks,
Ashish
