### ISSUE TITLE
SQS concurrent SetQueueAttribute with policy creates incomplete policies

### ISSUE THREAD

**Issue by danielmarbach** [aws/aws-sdk-net#1569]
When trying to set queue attributes with a policy concurrently then the written policy is partially complete.

## Expected Behavior

For concurrent policy overrides it would be expected that either the service handles it or at least provides a way for one operation to retry (by throwing an exception for example)

## Current Behavior

Two concurrent SetQueuAttribute with policy will create incomplete policies. In the test I used the SNS Client `SubscribeQueueAsync` but I was able to further boil the problem down to 

https://github.com/aws/aws-sdk-net/blob/b691e46e57a3e24477e6a5fa2e849da44db7002f/sdk/src/Services/SimpleNotificationService/Custom/_async/AmazonSimpleNotificationServiceClient.Extensions.cs#L145 that's why I raise it under SQS.

## Possible Solution

I looked at the SDK code and I couldn't find a behavior that indicates it is an SDK issue so my hunch is it is a service issue but I did not spend hours in digging.

At this stage we are able to have a semaphore slim that guards the subscription setup and sequentializes the policy setting. This works ok for non-scaled out endpoints. With scaled out endpoints our current thinking is that given they are similar they should converge towards the same policy if each of the endpoint guards with its own semaphore. The problem though comes again at play when in a competing consumer scenario one instance of a scaled out endpoint is updated to subscribe to a new topic we are not sure yet what would happen.

## Steps to Reproduce (for bugs)

https://github.com/danielmarbach/SqsPolicyRepro

Run and observe that either Topic1 or Topic2 is not present in the policy
Set Semaphore to 1
Run and observe that Topic1 and Topic2 is present in the policy (expected behavior)

## Context

We are implementing SNS support for NServiceBus AmazonSQS transport and hit that problem. NServiceBus allows to dynamically subscribe and unsubscribe. When loading an endpoint subscription request are done by default concurrently.

## Your Environment

* AWSSDK.Core version used: Multiple versions
* Service assembly and version used: 
* Operating System and version:  Tested on Windows only
* Visual Studio version: All versions
* Targeted .NET platform:  All platforms

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by danielmarbach** [comment]
I've also tried

```
var addPermissionRequest = new AddPermissionRequest();
addPermissionRequest.Actions.Add("SendMessage");
addPermissionRequest.QueueUrl = sqsQueueUrl;
addPermissionRequest.Label = topicArn;
addPermissionRequest.AWSAccountIds.Add(new Principal("*").Id);
await sqsClient.AddPermissionAsync(addPermissionRequest).ConfigureAwait(false);
```

but that doesn't like the `*` permission and when you search the wisdom of the internet it suggests to create a custom policy which brings us back to square one

**Comment by NGL321** [comment]
Hey @danielmarbach,

You are very likely correct that this is an issue with SQS itself, I will reach out to the team, and update this issue if there is any update.

Thanks for submitting!

😸 😷

**Comment by danielmarbach** [comment]
@NGL321 Any updates on this one? We are currently struggling quite a bit because with 3.5 of the SDK all the policy-related objects have been deprecated. We are using those to work around the above issue but now this prevents us from moving forward or we need to reimplement some of the policy json serialization and deserialization :(

**Comment by ashishdhingra** [comment]
P52353693

**Comment by ashishdhingra** [comment]
No close.

**Comment by danielmarbach** [comment]
So how has this then be solved? The last comment was https://github.com/aws/aws-sdk-net/issues/1569#issuecomment-702424293 and no follow up at all. 

How about make at least a comment along the lines of "we had a closer look and works as designed we are not planning to make changes" or "yes it is still a service issue and we will follow up, sorry for not coming back earlier"? Otherwise anyone that stumbles over this issue has no clue where we stand (and I do neither)

**Comment by ashishdhingra** [comment]
@danielmarbach I have sent a ping to service team for their inputs. Waiting for them to share the investigation. Would post any updates here as I get them.

**Comment by danielmarbach** [comment]
That's very kind of you. Thanks

**Comment by ashishdhingra** [comment]
@danielmarbach Per the last response from service team, SQS service uses optimistic locking when modifying the policies. So in the case of concurrent mutations, it is very possible that only 1 of the concurrent calls succeeds. This might explain why you are observing incomplete policies while executing concurrently. It is also advised against any kind of solution that aims to "scale out" concurrent modifications of Queue Metadata (or by extension, queue policies), which the attached issue seems to suggest is the underlying intention here. SQS is great at concurrent dataplane operations (Send. Receive, etc..), but we are not designed for highly concurrent / rapid queue metadata mutations.

Thanks,
Ashish

**Comment by danielmarbach** [comment]
Thanks!
