### ISSUE TITLE
AWSSDK.Chime gives ForbiddenException when resources not found

### ISSUE THREAD

**Issue by Aarondorn2** [aws/aws-sdk-net#1571]
Please let me know if there is a better place to report Chime issues.

## Expected Behavior
If I have authenticated but the resource requested does not exist, I would expect a NotFoundException or something similar.

## Current Behavior
Calling `GetMeetingAsync` or `DeleteAttendeeAsync` will occasionally throw a ForbiddenException.  This occurs when I am attempting to get a meeting that has been deleted or remove an attendee that is already removed.

## Possible Solution
Only throw ForbiddenExceptions when there is an authentication issue

## Steps to Reproduce (for bugs)
Create a Meeting, join an attendee, remove the attendee, attempt to remove the attendee a second time.

## Context
I should check an attendee's state before attempting to remove, but I would like to receive the correct error messages so that I can debug issues correctly.

## Your Environment
AWSSDK.Chime 3.3.107.18
AWSSDK.Core  3.3.105.5

**Comment by NGL321** [comment]
Hey @Aarondorn2,

Thanks for reporting this, however we do not control the exceptions thrown by the service, that is decided by the service team itself. I will pass along your note/request to the team, and will update here if I get an update from tham.

😸 😷

**Comment by ashishdhingra** [comment]
Hi @Aarondorn2,

Good afternoon.

I was going through backlog and came across this issue. Kindly advise if this is still an issue or if we could close it. As @NGL321 mentioned, in this case, the exceptions are controlled by service.

Thanks,
Ashish

**Comment by Aarondorn2** [comment]
Hey! Thanks for the follow-up.  We've currently been burying the exception while watching this issue.  I can do some testing on Monday to see if this is still an issue.

**Comment by ashishdhingra** [comment]
> Hey! Thanks for the follow-up. We've currently been burying the exception while watching this issue. I can do some testing on Monday to see if this is still an issue.

@Aarondorn2 Thanks a lot. Let me know the result of your testing. If this is still an issue, please share the detailed steps along with sample code, so that I could open issue with service team.

**Comment by Aarondorn2** [comment]
It looks like the behavior has changed since opening this ticket.  The DeleteAttendee endpoint now returns `NoContent` regardless of whether or not it succeeded.  I ran the following in LINQPad:

```
// set up client
var chimeClient = new AmazonChimeClient(accessKeyId, secretAccessKey, RegionEndpoint.USEast1);

// set up meeting
var meeting = await chimeClient.CreateMeetingAsync(new CreateMeetingRequest {
	ClientRequestToken = Guid.NewGuid().ToString()
});

var meetingId = meeting.Meeting.MeetingId;

// join an attendee
var attendee = await chimeClient.CreateAttendeeAsync(new CreateAttendeeRequest {
	MeetingId = meetingId,
	ExternalUserId = Guid.NewGuid().ToString()
});

var attendeeId = attendee.Attendee.AttendeeId;

// remove an attendee
await chimeClient.DeleteAttendeeAsync(new DeleteAttendeeRequest {
	MeetingId = meetingId,
	AttendeeId = attendeeId
}).Dump();

// attempt to remove the same attendee again
await chimeClient.DeleteAttendeeAsync(new DeleteAttendeeRequest {
	MeetingId = meetingId,
	AttendeeId = attendeeId
}).Dump();

// attempt to remove an attendee that never joined
await chimeClient.DeleteAttendeeAsync(new DeleteAttendeeRequest {
	MeetingId = meetingId,
	AttendeeId = Guid.NewGuid().ToString()
}).Dump();
```

The last two calls previously would have thrown a ForbiddenException but now return a `204 No Content` in all cases.


I am no longer receiving an unexpected exception from this operation - I'll close the issue.  Thank you!
