### ISSUE TITLE
Cannot use AWS SDK Net in a IIS hosted environment

### ISSUE THREAD

**Issue by PascalUmaknow** [aws/aws-sdk-net#1574]
Cannot use AWS SDK Net in a IIS hosted environment

## Expected Behavior
When using AWS SDK Net in a IIS Environment (Standard Azure App Service for the test), most of the packages (like AWSSDK.SecurityToken, AWSSDK.IdentityManagement) cannot be used.

The error stack trace is as follow :
```
[UnauthorizedAccessException: Access to the path '/AWSToolkit' is denied.]
   System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) +417
   System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost) +1394
   System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost) +92
   Amazon.Runtime.Internal.Settings.PersistenceManager..cctor() +176
```

The Amazon.Runtime.AmazonServiceClient.BuildRuntimePipeline is relying on PersistenceManager even if we do not want to use any PersistenceManager like when we call the constructor like new AmazonIdentityManagementServiceClient(settings.AWSAccessKeyId, settings.AWSSecretAccessKey, regionEndPointToUse)

## Current Behavior
The issue seems to be related to the fact that internally AmazonServiceClient.BuildRuntimePipeline is trying to instantiate a PersistenceManager and this PersistenceManager cannot be created sucessfully as the environment variable Environment.SpecialFolder.LocalApplicationData is emtpy (variable used in the PersistenceManager Constructor). So it tries to create a folder /AWSToolkit and gets an access denied. The environment variable Environment.SpecialFolder.LocalApplicationData is emtpy because the IIS is runing under a Non-User Account (like Network Service) which is something that cannot be changed in Azure for Instance.

As all AWSSDK packages are using AmazonServiceClient which calls BuildRuntimePipeline that fails to initialize a PersistenceManager so none of the packages can be used.

## Possible Solution
We should be able to use AWSSDK without having mandatory dependency with the PersistenceManager (it was the case before - at least for 3.3.104.38 of AWSSDKCore)

## Steps to Reproduce (for bugs)
1. Create an empty ASP.NET Web Application
2. Add the following lines in the home page 
     AmazonIdentityManagementServiceClient client  = new AmazonIdentityManagementServiceClient(xxxx, xxxx)
3. Deploy to a IIS Hosted WebApp in Azure App Service

## Context
The new version of the AWS SDK is not usable because of this dependencies to PersistenceManager.
We would expect that when you want to use AWSSDK, it does not at some point try to use PersistenceManager if we provide the credentials in our constructors for the different clients. It it tries to use the PersistenceManager, it should not fail if it cannot find the directory or create it.

## Your Environment

* AWSSDK.Core version used: 3.3.106.2
* Service assembly and version used: all. For example AWSSDK.IdentityManagement 3.3.105.31
* Operating System and version:  Windows Server 2019
* Visual Studio version: VS 2019
* Targeted .NET platform: .NET 4.6.2

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by NGL321** [comment]
Hey @PascalUmaknow,

It appears that we have added some fixes that should resolve this issue. Are you still experiencing this problem with the latest version of the SDK? If so I will keep investigating, otherwise we can close this out.

Thanks!
😸 😷

**Comment by PascalUmaknow** [comment]
No more issues, that's working great now 👍 Thanks a lot !
