### ISSUE TITLE
Failed to upload directory using TransferUtility.UploadDirectory()

### ISSUE THREAD

**Issue by ArchanaNeog** [aws/aws-sdk-net#1577]
I am trying to upload a directory using AWS S3 transferUtility.UploadDirectory.
I have set the keyPrefix "/_Test/Dummy" in TransferUtilityUploadDirectoryRequest

my bucket policy is as shown below
"allowed": {
            "resources": [
                "/*"
            ],
            "actions": [
               "GET",
                "PUT",
                "LIST"
            ]
        }
example : 
## Expected Behavior

I expect to upload files with the given key prefix

## Current Behavior

But for me now upload fails with error message AccessDenied
I can see in UploadDirectoryCommand.cs, the key is altered and removed that preceding '/', from keyPrefix. As per bucket policy allowed resource is "/*, since the preceding forward slash '/' is removed, as per policy it is not allowed.

## Steps to Reproduce (for bugs)

string keyPrefix = "/_Test/Dummy"
var uploadDirectoryRequest = new TransferUtilityUploadDirectoryRequest {
                    BucketName = bucketName,
                    Directory = directory,
                    KeyPrefix = keyPrefix,
                    ServerSideEncryptionMethod = serverSideEncryption,
                    SearchOption = SearchOption.AllDirectories,
                    UploadFilesConcurrently = true
                };
                transferUtility.UploadDirectory(uploadDirectoryRequest);

## Your Environment

* AWSSDK.Core version used: 3.3.108.4
* Service assembly and version used: 
* Operating System and version: Windows10
* Visual Studio version: VS2017 15.9.3
* Targeted .NET platform: 
## .NET Core Info

* .NET Core version used for development:  .Net Core 2.0
* .NET Core version installed in the environment where application runs: .Net Core 2.0
* Output of `dotnet --info`: 
.NET Core SDK (reflecting any global.json):
 Version:   2.1.500
 Commit:    b68b931422

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.500\

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
* Contents of project.json/project.csproj: 
<PackageReference Include="AWSSDK.S3" Version="3.3.108.4" />
[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by kazimanzurrashid** [comment]
The permissions you have list does not include the multi-part related permissions:
https://docs.aws.amazon.com/AmazonS3/latest/dev/mpuAndPermissions.html

**Comment by ashishdhingra** [comment]
Hi @ArchanaNeog, 

Thanks for reporting the issue. I used your snippet in the issue to develop a sample code and was able to upload directory containing sub-directories and files, to the S3 bucket. The _KeyPrefix_ in the **TransferUtilityUploadDirectoryRequest** object specifies the path starting at the bucket root level. The logic is expected to work the similar way whether forward slash is provided or not. The issue most likely is due to the policy set at the bucket level. 

Please share the exact policy (with sensitive information excluded) configured at your S3 bucket level.

Thanks,
Ashish
