### ISSUE TITLE
getpresignedurl + apostrophe (possible bug)

### ISSUE THREAD

**Issue by foxontherock** [aws/aws-sdk-net#158]
We are storing our files in S3 exactly like they were on our disk drive. Some of them have special characters, unicode, or anything else. We do not have any trouble with all of them, except one: the apostrophe ('), single quote.

That character is not url-encoded like others do when using GetPreSignedURL function. 

The generated url works fine in IE and Chrome, but not in firefox that re-encode it, and the signature does not match. In the sample below, the trouble is not in the content-dispoisition header, but in the key. I can change my content-disposition filename to fix half of it, but I can't change my key.

Sample (FAIL, single quote) - not working in firefox because FF replace ' with %20 automatically
   Key: ace48a/49277_fred's image.jpg
   url: http://(bucket).s3.amazonaws.com/ace48a/49277_fred's%20image.jpg?AWSAccessKeyId=<Access Key Removed>&Expires=1416405527&Signature=KDahwlD72RbAV1P%2BZxCdMhH%2FngA%3D
Single quote NOT replaced in url.

Sample 2: (WIN, with double quote)
   Key: ace48a/49277_fred"s image.jpg
   url: http://(bucket).s3.amazonaws.com/ace48a/49277_fred%22s%20image.jpg?AWSAccessKeyId=<Access Key Removed>&Expires=1416405464&Signature=2OUOFRWvhdNJSqGtTvnjttDnZlU%3D
Double quote REPLACED by %22 in url.

**Comment by bootleg224** [comment]
Looks like Firefox  35 and onwards started escapaing characters like ' and [ and ].

 https://github.com/aws/aws-sdk-net/blob/6c5b5a7c61ba1dfc17bd2b7e39813b37b77aa9f7/AWSSDK_DotNet35/Amazon.Util/AWSSDKUtils.cs

This method likely needs to be updated

internal static string UrlEncode(int rfcNumber, string data, bool path)

**Comment by bootleg224** [comment]
Looks like DetermineValidPathCharacters should have ' [ and ] removed?

**Comment by jimfl** [comment]
Hi. This is a tricky one. It looks like this is an unfortunate interaction between Firefox uri encoding and the signature verification in the S3 service. I did some tests, and it turns out that if you enable Sigv4 when creating pre-signed URLs work from both browsers. It's not clear that we wouldn't break existing consumers of the API by fixing it in the SDK.

You can enable Sigv4 signing with

    Amazon.AWSConfigs.S3Config.UseSignatureVersion4 = true;

I also chased down the bug in Mozilla that was "fixed" by this change. It looks like it had to do with cutting-and-pasting URLs from the location field. It's possible they didn't realize the same code path was taken when putting the URI on the wire.

**Comment by bootleg224** [comment]
Thanks sigv4 works.  Problem with sigv4 is that it doesn't have the same rules for max url expiration date.

The fix I pushed does work, contrary to the note about it simply stripping characters.

In summary, either mozilla should fix this though, or sigv4 should be used.  The suggested fix is useful as a stop-gap though, until one can upgrade to sigv4

**Comment by foxontherock** [comment]
Thank you, that fixed our trouble too. 
And, that was not a copy-paste issue, I cleary see in Fiddler that the url is not changed or urlencoded, the exact string returned from getUrlToEncode was re-use as-is in firefox. 
But now, it works! Thank you.
