### ISSUE TITLE
In Unity, "Main thread has not been set exception" from Play + unfocus window

### ISSUE THREAD

**Issue by sporeservant** [aws/aws-sdk-net#1581]
Any time I run the AWS SDK examples or my own code, the first run is smooth, but if I unfocus the window by going to a browser for example, then when I come back, this error is *always* thrown.

I assume there is some sort of lost reference to the main thread, but I am not certain. 

I am using Unity 2020.1.0b4.3439 Personal on Mac OSX Mojave 10.14.6, .NET 3.5 using Unity SDK downloaded from here: https://github.com/rms80/awscognito-unity-accounts-demo/tree/master/Assets/AWSSDK

## Expected Behavior

You should not have to stop and play to test changes in your project.

## Current Behavior

Once you press play, everything is fine. Then you move away from the play screen to something like AWS documentation, and once you come back, this exception triggers until you stop the application.

```
Exception: Main thread has not been set, is the AWSPrefab on the scene?
Amazon.UnityInitializer.IsMainThread () (at <8ae371e1c5da43cca34e6137469c61c6>:0)
Amazon.AWSConfigs.LoadConfigFromResource () (at <8ae371e1c5da43cca34e6137469c61c6>:0)
Amazon.AWSConfigs.GetSection[T] (System.String sectionName) (at <8ae371e1c5da43cca34e6137469c61c6>:0)
Amazon.Util.Internal.RootConfig..ctor () (at <8ae371e1c5da43cca34e6137469c61c6>:0)
Amazon.AWSConfigs..cctor () (at <8ae371e1c5da43cca34e6137469c61c6>:0)
Rethrow as TypeInitializationException: The type initializer for 'Amazon.AWSConfigs' threw an exception.
Amazon.Runtime.Internal.Util.Logger.ConfigureLoggers () (at <8ae371e1c5da43cca34e6137469c61c6>:0)
Amazon.Runtime.Internal.Util.Logger..ctor (System.Type type) (at <8ae371e1c5da43cca34e6137469c61c6>:0)
Amazon.Runtime.Internal.Util.Logger.GetLogger (System.Type type) (at <8ae371e1c5da43cca34e6137469c61c6>:0)
Amazon.Util.Internal.AmazonHookedPlatformInfo..cctor () (at <8ae371e1c5da43cca34e6137469c61c6>:0)
Rethrow as TypeInitializationException: The type initializer for 'Amazon.Util.Internal.AmazonHookedPlatformInfo' threw an exception.
Amazon.Util.Internal.PlatformServices.EnvironmentInfo..ctor () (at <8ae371e1c5da43cca34e6137469c61c6>:0)
System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) (at <437ba245d8404784b9fbab9b439ac908>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.Activator.CreateInstance (System.Type type) (at <437ba245d8404784b9fbab9b439ac908>:0)
Amazon.Util.Internal.PlatformServices.ServiceFactory..ctor () (at <8ae371e1c5da43cca34e6137469c61c6>:0)
Amazon.Util.Internal.PlatformServices.ServiceFactory..cctor () (at <8ae371e1c5da43cca34e6137469
```

## Possible Solution

Probably changing the way the main thread is referenced?

## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by orbitalnine** [comment]
I'm seeing the same exception, though it doesn't occur when Unity loses the focus. I'm not certain when it starts, but when it does it happens every run and closing and reopening Unity fixes it. I haven't tested on device yet, but wondering if anyone has solved this?

My setup:
- Window 10
- Unity 2019.3.10f1
- AWSSDK (v3.3) downloaded from here: http://sdk-for-net.amazonwebservices.com/latest/aws-sdk-unity.zip

**Comment by ashishdhingra** [comment]
Hi @sporeservant,

Good afternoon.
 
Starting with version 3.5 of the AWS SDK for .NET, projects using Unity 2018.1 or later should target the .NET Standard 2.0 release of the SDK. You can find additional information in the developer guide: [Unity support](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/unity-special.html) and [Migrating your Unity application](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/net-dg-v35.html#net-dg-v35-changes-unity).

Please try using the .NET Standard 2.0 version of the AWS SDK for .NET (version 3.5). 

Thanks,
Ashish

**Comment by shive1807** [comment]
`UnityInitializer.AttachToGameObject(this.gameObject);
`
add this in your script from where you are trying to access the aws.
