### ISSUE TITLE
Why does PutItemAsync only return a Document when requesting AllOldAttributes? 

### ISSUE THREAD

**Issue by winzig** [aws/aws-sdk-net#1582]
https://github.com/aws/aws-sdk-net/blob/966617d346169e89a693dae74c5eec5cda0551b2/sdk/src/Services/DynamoDBv2/Custom/DocumentModel/Table.cs#L646

Can someone explain why a `Document` is only returned from `Table.PutItemAsync()` when the config is passed in requesting `AllOldAttributes`?

**Comment by winzig** [comment]
I see in the docs where it states this fact also, but was wondering _why_ DDB works like this?

<img width="975" alt="Screen Shot 2020-04-21 at 11 01 46 PM" src="https://user-images.githubusercontent.com/127062/79946821-94017000-8425-11ea-92ce-c978ad6941bb.png">

**Comment by ashishdhingra** [comment]
Hi @winzig,

Good morning.

I was going through the issue backlog and came across this question. One reason I can think of is that attributes belong to a Document object in NoSQL databases. Hence, requesting got AllOldAttributes expectedly returns a Document object. For any design related questions, DynamoDb service team could provide more inputs. Hope this answers the question. 

Thanks,
Ashish
