### ISSUE TITLE
PostObjectAsync doesn't work on Unity 2018.4.18f1: Error making request with Error Code 0 and Http Status Code 0. No further error information was returned by the service. Response Body: Unknown Error

### ISSUE THREAD

**Issue by Nightgaze** [aws/aws-sdk-net#1588]
After updating to Unity 2018 we started receiving this error when calling PostObjectAsync on our Linux server:

Error making request with Error Code 0 and Http Status Code 0. No further error information was returned by the service. Response Body: Unknown Error

Also we use the UnityWebRequest option in AWSConfig.

I also tried to replace it with PutAsync but the behaviour is identical.

## Expected Behavior
Request should succeed and upload the file

## Possible Solution
It seems like there is something related to the way Unity 2018 does web requests compared to Unity 2017.

## Steps to Reproduce (for bugs)
Create and empty Unity 2018 project, call PostObjectAsync for a file and run the build on Linux.

## Context
This breaks our server process save feature

## Your Environment
* AWSSDK.Core version used: 
* Service assembly and version used: last update from aws sdk net sources, also tried official version from amazon website
* Operating System and version: Amazon Server 2
* Visual Studio version: 2017
* Targeted .NET platform: 3.5 (Obsolete), we cannot use 4.0 since another plugin we use doesn't have 4.0 support

**Comment by Nightgaze** [comment]
I found the cause of the problem and it was actually with Unity 2018!
Unity 2018 looks for CA certs in debian location only so I needed to create a symlink of the actual location where our certificate is

sudo mkdir -p /etc/ssl/certs
cd /etc/ssl/certs
sudo ln -s /etc/pki/tls/certs/ca-bundle.crt /etc/ssl/certs/ca-certificates.crt

**Comment by ashishdhingra** [comment]
Hi @Nightgaze, 

Good that you were able to self-resolve the issue. Please advise if this issue could be closed.

Thanks,
Ashish
