### ISSUE TITLE
GetItem can't distinguish no row vs empty projection

### ISSUE THREAD

**Issue by WalkerCodeRanger** [aws/aws-sdk-net#159]
When I do `AmazonDynamoDBClient.GetItem()` the result always has a non-null `Item` value even if there was no item with the given key.  However, if I specify a `ProjectionExpression` for `GetItem()` then I could get a non-null empty item if there is an item but it doesn't have any of the attributes in my projection expression.  Consequently, there is no way to tell if an item with the given key exists in that case.

Looking at the code of `GetItemResponseUnmarshaller` it looks like it can tell that there was no matching item, but because `GetItemResult` always initalizes the `Item` property it is never null.

I think `AmazonDynamoDBClient.GetItem()` should return a result with `GetItemResult.Item == null` if no item matches the requested key.

**Comment by PavelSafronov** [comment]
Unfortunately, changing the default behavior as you described (`GetItemResult.Item` is null when the item is not found) is a breaking change. Namely, it would impact users who are currently assuming that `Item` is not null and thus are not performing a null check before using the collection.

There are two possible approaches for your case:
1. Include a key attribute (or any attribute that is guaranteed to exist on every item) in the `ProjectionExpression`. This way you will be able to tell if an item exists or not.
2. Make the change you suggested in your local repo.

**Comment by WalkerCodeRanger** [comment]
Would you consider adding a boolean property to `GetItemResult` that indicates whether an item matched the key?  That would provide a way to detect this situation without being a breaking change.  I understand option 1 is normally an easy solution to this problem.  However, I am trying to write a generic library and I can't control what users will provide for their `ProjectionExpression`.

**Comment by PavelSafronov** [comment]
Given that the low-level DynamoDB API is generated, adding a very specific property to the `GetItemResult` class is a fairly large customization, and it's a solution that doesn't scale very well.

As you pointed out, collection items are always initialized, so there could be other cases where a service may not return a collection or return an empty collection, and there is currently no way to tell apart these two cases from outside the SDK. We are considering how to address these cases in a general way, but there is no current estimate on when or how this will be done.

For now, your only options are to fork the SDK and make the change you suggested, or append the key attribute names to the `ProjectionExpression` if they are not present.

**Comment by PavelSafronov** [comment]
The fix for [issue 161](https://github.com/aws/aws-sdk-net/issues/161) applies to this issue as well.
