### ISSUE TITLE
New regions like  EUSouth1 and AFSouth1 doesn't exists in RegionEndpoint class

### ISSUE THREAD

**Issue by KpoxaDroid** [aws/aws-sdk-net#1594]
## Your Environment

* AWSSDK.Core version used: 3.3.106.16
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: '.NETFramework,Version=v4.0'

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by normj** [comment]
Thanks for reporting the issue. I have created the following PR to get them added. https://github.com/aws/aws-sdk-net/pull/1596

**Comment by normj** [comment]
Version 3.3.106.20 of AWSSDK.Core has been released with the missing enums
