### ISSUE TITLE
set record property twice?

### ISSUE THREAD

**Issue by grahamehorner** [aws/aws-sdk-net#1595]
cut-copy-paste error? [S3EventNotification.cs#L43](https://github.com/aws/aws-sdk-net/blame/master/sdk/src/Services/S3/Custom/Util/S3EventNotification.cs#L43)

**Comment by normj** [comment]
Yes copy-paste error, PR to remove it https://github.com/aws/aws-sdk-net/pull/1597

**Comment by normj** [comment]
Version 3.3.110.66 of AWSSDK.S3 has been released with this change.
