### ISSUE TITLE
System.Threading.SynchronizationLockException: Cannot wait on monitors on this runtime.

### ISSUE THREAD

**Issue by user72356** [aws/aws-sdk-net#1598]
This is in a Blazor WebAssembly app. Trying to load DynamoDB items with the object persistence model, I receive a SynchronizationLockException on LoadAsync(). However, the same operation works fine with the low-level API.

## Expected Behavior
I should receive a "Book" object.

## Current Behavior
Doing:
```
Book book = await dynamoDBContext.LoadAsync<Book>(1);
```
Throws:
```
System.Threading.SynchronizationLockException: Cannot wait on monitors on this runtime.
```
See details below.

## Steps to Reproduce (for bugs)
Create a test DynamoDB table called Book with an index called "Id" (number).

Create a new Blazor WebAssembly project in Visual Studio (client side template). This will create the default Blazor app for you. Then replace/create the following files. Don't forget to replace "XXX" by your own credentials to access the table of course.

Replace Program.cs with:
```
using Amazon;
using Amazon.DynamoDBv2;
using Amazon.DynamoDBv2.DataModel;
using Amazon.DynamoDBv2.Model;
using Amazon.Runtime;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;

namespace AWSTest1
{
    class HttpInjectorFactory : HttpClientFactory
    {
        private readonly HttpClient _injectedClient;

        public HttpInjectorFactory(HttpClient injectedClient)
        {
            _injectedClient = injectedClient;
        }

        public override HttpClient CreateHttpClient(IClientConfig clientConfig)
        {
            return _injectedClient;
        }

        public override bool DisposeHttpClientsAfterUse(IClientConfig clientConfig)
        {
            return false;
        }

        public override bool UseSDKHttpClientCaching(IClientConfig clientConfig)
        {
            return false;
        }
    }

    public class Program
    {
        public static async Task Main(string[] args)
        {
            var builder = WebAssemblyHostBuilder.CreateDefault(args);
            builder.RootComponents.Add<App>("app");
            builder.Services.AddSingleton(new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });
            var host = builder.Build();

            AWSConfigs.RegionEndpoint = RegionEndpoint.USEast2;
            AWSConfigs.HttpClientFactory = new HttpInjectorFactory(host.Services.GetRequiredService<HttpClient>());
            AWSConfigs.UseAlternateUserAgentHeader = true;

            // Request Book id 1 using low-level API, no error

            var dynamoDBClient = new AmazonDynamoDBClient("XXX", "XXX");

            Dictionary<string, AttributeValue> key = new Dictionary<string, AttributeValue>
            {
                { "Id", new AttributeValue { N = "1" } }
            };

            GetItemRequest request = new GetItemRequest
            {
                TableName = "Book",
                Key = key,
            };

            var result = await dynamoDBClient.GetItemAsync(request);

            // Request Book id 1 using object persistence model, throws SynchronizationLockException
            var dynamoDBContext = new DynamoDBContext(dynamoDBClient);
            Book book = await dynamoDBContext.LoadAsync<Book>(1);

            await host.RunAsync();
        }
    }
}
```
Create Book.cs:
```
using Amazon.DynamoDBv2.DataModel;

namespace AWSTest1
{
    [DynamoDBTable("Book")]
    public class Book
    {
        [DynamoDBHashKey]
        public int Id { get; set; }
    }
}
```

## Your Environment

* AWSSDK.Core version used: 3.3.106.17
* Service assembly and version used: AWSSDK.DynamoDBv2 3.3.105.39
* Operating System and version: Windows 10.0.18363
* Visual Studio version: 16.6.0 Preview 5.0
* Targeted .NET platform: .NET Standard 2.1

**Comment by gb1337** [comment]
I've edited my OP with more details for easier reproduction.

**Comment by normj** [comment]
Yes, unfortunately the object persistence layer isn't going to work in Blazor WebAssembly. It uses an internal synchronous to load table metadata which causes the SynchronizationLockException exception. 

We are hoping to do some major work to the object persistence layer to remove that synchronous load call but that work isn't scheduled yet. 

Sorry for the inconvenience but thank you for pointing this out, it helps me push to get this work prioritized.

**Comment by gb1337** [comment]
Bummer, but I'm glad it's on your radar. Hopefully it can be prioritized soon enough! I think Blazor WebAssembly is a game changer for web app development and about to blow up! Obviously well-supported at Azure, but some of us would like to use it on AWS 👍

**Comment by normj** [comment]
@gb1337 Totally agree and I'm very excited for Blazor WebAssembly. We have been doing work on the SDK to get it ready for Blazor but in the case of the DynamoDB object persistence layer getting rid of the sync call is going to cause a significant redesign of the library. We need to do that work because it affects other things besides Blazor but we just got to get the dedicated time for it.

I would appreciate any other feedback you have with Blazor WebAssembly.

**Comment by gb1337** [comment]
I will make sure to provide feedback as I experiment more. One trouble spot has been the lack of documentation and the fact that things don't seem to be in sync between the docs and the libs. I've had to rely on outside blogs a lot.

**Comment by gb1337** [comment]
@normj can you please confirm that the Document models suffers from the same issue as well? I thought I could use it but I'm getting the same error... Ouch

**Comment by MahdiKarimipour** [comment]
Also, should I expect to have the same experience if I try to load static files in Blazor using Http.GetStreamAsync?
