### ISSUE TITLE
Double clicking S3 vertical scrollbar opens file

### ISSUE THREAD

**Issue by rbirkby** [aws/aws-sdk-net#160]
When viewing files in an S3 bucket in the AWS Visual Studio extension, if the user double clicks on the vertical scrollbar, then the currently selected S3 file is opened in the default web browser.

### Expected Behavior
The S3 file viewport scrolls one page every time the user clicks on the scrollbar track. Nothing happens if the user clicks or double clicks on the scrollbar thumb.

### Actual Behavior
The currently selected S3 file is opened in the default web browser

**Comment by steveataws** [comment]
Thanks for reporting the issue. Unfortunately it fell off our radar but we're tacking a look now.

**Comment by steveataws** [comment]
Issue fixed and will roll into next release (which will be version 1.9.1.2 or higher).
