### ISSUE TITLE
AWS Textract NuGet description out of date?

### ISSUE THREAD

**Issue by berkeleybross** [aws/aws-sdk-net#1600]
The AWSSDK.Textract NuGet package has a description sayings it's in preview and shouldn't be used. This appears to be misleading, because Texttract is [now GA](https://aws.amazon.com/about-aws/whats-new/2019/05/amazon-textract-now-generally-available/)

## Current Behavior
"This release is intended ONLY for customers that are officially part of the Amazon Textract Preview program. If you are not officially part of the Amazon Textract program THIS WILL NOT WORK. Our two main regions for Amazon Textract Preview are N. Virginia and Dublin. Also some members have been added to Oregon and Ohio. If you are outside of any of these AWS regions, Amazon Textract Preview definitely will not work. If you would like to be part of the Amazon Textract program, you can officially request sign up here - https://pages.awscloud.com/textract-preview.html. To set expectations appropriately, we are aiming to admit new preview participants once a week until General Availability."

## Context
Confusing but easy to ignore / try anyway

## Your Environment
nuget Package manager -> AWSSDK.Textract v3.3.102.65
nuget website -> https://www.nuget.org/packages/AWSSDK.Textract/3.3.102.65?_src=template

**Comment by ashishdhingra** [comment]
This has been fixed in [AWSSDK.Textract 3.7.0.29](https://www.nuget.org/packages/AWSSDK.Textract/3.7.0.29)
