### ISSUE TITLE
TransactWriteItemsAsync does not guarantee the order in which the items are recorded

### ISSUE THREAD

**Issue by MiguelAlho** [aws/aws-sdk-net#1601]
While using `TransactWriteItemsAsync` to record events from an Event-sourced system as DynamoDB entries, we noticed that in some cases the recorded events appear in the associated DynamoStream out-of-order. 

Most of the time, we write a single event per action, but we do have an action that generates 3 events. In this action, we want to write all 3 in a transaction (all written or none written) and want the events to appear in the stream in the same order as we added to the list that is sent to `TransactWriteItemsAsync`. Each event in our system represents a change in the domain aggregate. The partition key is the aggregate Id, and the sort key is the version of the aggregate caused by each event (first event is version 0, second event, 1, etc.). 

So, this single command on the aggregate generates 3 events. We send the 3 events in order in a list to the `TransactWriteItemsAsync` method. The records get written to the DynamoDB table. In the lambda that consumes the associated DynamoStream, we notice that the events are published to the stream out of order (such as 1,2,0). This affects the lambda that consumes the events and is expected to build a search model from these events. 

Is this expected? The docs for `BatchWriteItems` seems to suggest so (transaction not worried about the order things are written to the DynamoDB table), but it isn't clear if `TransactWriteItemsAsync` is some type of wrapper around the `BatchWriteItems` logic or sharing the implementation.

Also, is there some configuration element that activates / deactivates in order writing (maybe related to isolation levels?).?

## Expected Behavior
The expectation is that, during the transaction, all the items in the transaction are written to the DynamoDB table in the same order they are supplied to the `TransactWriteItemsAsync` method.

## Current Behavior
Currently, though the operation succeeds, the items written to the DynamoDB table, and published to the DynamoDB stream appear out of the order in which they were supplied. 

## Your Environment

* AWSSDK.Core version used: 3.3.106.3
* AWSSDK.DynamoDBv2 : 3.3.105.26

## .NET Core Info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by ashishdhingra** [comment]
Hi @MiguelAlho, 

Good afternoon.

Looking at the code in .NET SDK for [**TransactWriteItemsRequestMarshaller.Marshall()**](https://github.com/aws/aws-sdk-net/blob/c31ab2fd0e6335c410009d79d5d6648324ce8e33/sdk/src/Services/DynamoDBv2/Generated/Model/Internal/MarshallTransformations/TransactWriteItemsRequestMarshaller.cs#L94), I do not see the any logic that changes the order of TransactItems. The logic is simply writing the JSON for TransactItems in the order mentioned in the **TransactWriteItemsRequest** object. Hence, I cannot pin-point if there is a problem with the SDK or the DynamoDb service.

As a workaround, is listing and ordering objects based on SortKey and passing them to Lambda function works for you?

Thanks,
Ashish

Thanks,
Ashish

**Comment by MiguelAlho** [comment]
Hi, Thanks for looking into this. 

I suspect it isn't so much a SDK issue as it is either a misinterpretation of the docs (and expectations) on my side or a potential error in the stream publishing. The SDK itself seems to be OK as I can get the items stored in the database. 

The problem, though, is that they are not published to the stream in order that I expect them to be. So when I try to pull events from the stream in my lambda function, the batch that I read might not have them in order (though I would expect them to be read / made available in order). 

The docs (https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.html) say "For each item that is modified in a DynamoDB table, the stream records appear in the same sequence as the actual modifications to the item."

What I do know is that in the batch of items saved, the first doc has a much larger payload then any of the others so I would suspect that the time to write / propagate that record could be larger than the other, much smaller docs if parallelism were to be considered, and that could be a cause for out of order on the stream. Is there any prop on the payload in the stream's message that could help me pinpoint that?

**Comment by MiguelAlho** [comment]
It's been a while , but I've finally come around to producing a sample repo that demos the behavior, to to some other order-related issues I'm trying to understand. 

https://github.com/MiguelAlho/DynamoDb_TransactWriteItem_OutOfOrder

Hope it is useful. I'm still interested in understanding if the behaviour is expected / by design or if it is an unexpected bit of behavior.
