### ISSUE TITLE
.NET core 2.1 lambda - RDS connection using windows authentication

### ISSUE THREAD

**Issue by SiddharthChoudhury** [aws/aws-sdk-net#1604]
We are developing a .net core lambda function, which we need to connect to an RDS instance using Active Directory. 
In connection string, when we set Integrated Security to "True", we are getting "Kerberos authentication error." And when we try Integrated Security = False, we get "Login Failed" error.

Kerberos Error Description:
"Cannot authenticate using Kerberos. Ensure Kerberos has been initialized on the client with 'kinit' and a Service Principal Name has been registered for the SQL Server to allow Kerberos authentication.\nErrorCode=InternalError, Exception=Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error - Unspecified GSS failure.  Minor code may provide more information (SPNEGO cannot find mechanisms to negotiate)

We have investigated that the RDS instance has Mixed authentication enabled for the AD account that we want to login with.

Please help how can we let our lambda login to the RDS using Active Directory account authenticated with Windows authentication.

## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by ashishdhingra** [comment]
Hi @SiddharthChoudhury,

Please refer the link [https://blog.thundra.io/can-lambda-and-rds-play-nicely-together](https://blog.thundra.io/can-lambda-and-rds-play-nicely-together). It provides good overview on how to setup RDS when using with AWS Lambda. It basically talks about:

1. RDS instances are usually run (and should be) in a private subnet in a VPC assigned to your account. It’s a basic security principle to keep RDS instances isolated from the outside word, but this makes it inaccessible for Lambda functions.

2. Lambda functions, on the other hand, run in an isolated, AWS-managed VPC that can be accessed only by the AWS Lambda service. Functions have access to the internet and can call AWS services or any third-party resources that are publicly available. They are not, however, able to access private resources, like RDS instances running in private subnets.

3. In order for the two to work together, you’ll need to establish a proper inter-VPC connection by specifying a VPC and a subnet configuration when Lambda is created.

Please let me know if this helps and if this issue could be closed.

Thanks,
Ashish
