### ISSUE TITLE
InvalidDataException AWSSDK.Core and System DLL conflict in Unity 3D

### ISSUE THREAD

**Issue by michael-martinez** [aws/aws-sdk-net#1606]
Under Unity 2019.3.9f1, after importing the AWS SDK for dotnet unity packages, there is a conflict between the Unity Transport package and the AWS Core package.

A similar issue is described here:
https://forum.unity.com/threads/error-when-using-addressables-and-aws-mobile-sdk-for-unity.697352/

## Expected Behavior

There should be no DLL conflicts after importing the AWS.Core SDK.

## Current Behavior

The DLLs are in conflict, I am getting the following error in the Unity Editor when pressing play.

```
LogError: "Library/PackageCache/com.unity.transport@0.2.1-preview.1/Runtime/IPCManager.cs(168,27): error CS0433: The type 'InvalidDataException' exists in both 'AWSSDK.Core, Version=3.1.0.0, Culture=neutral, PublicKeyToken=null' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'"
```

## Possible Solution

Some fixes seems to be suggested here but I did not managed to make it working: 
https://forum.unity.com/threads/error-when-using-addressables-and-aws-mobile-sdk-for-unity.697352/#post-4663022

## Steps to Reproduce (for bugs)

Using Unity version 2019.3.9f1, import AWS SDK for DOT Net Unity packages: `aws-unity-sdk-v3-preview` (`AWSSDK.Lambda.3.1.2.5.unitypackage`, `AWSSDK.CognitoSync.3.1.0.5.unitypackage`, `AWSSDK.IdentityManagement.3.1.3.2.unitypackage`).
=> The `com.unity.transport@0.2.1-preview.1` throws the described error.

## Context

I am trying to use Amazon Gamelift with the Unity DOTS Netcode package.

I am unable to find any simple working example for Unity and Gamelift for recent versions of Unity.

## Your Environment

* AWSSDK.Core version used: ProductVersion3.1.4.3Assembly Version3.1.0.0
* Service assembly and version used: ProductVersion3.1.4.3Assembly Version3.1.0.0
* Operating System and version: macOS Mojave Version 10.14.6
* Visual Studio version: Visual Studio Code Version: 1.45.0
* Targeted .NET platform: Unity Editor - Linux Server Build

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.201/

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  2.1.4 [/usr/local/share/dotnet/sdk]
  3.1.201 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

* Contents of project.json/project.csproj: N/A

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by jeff0fisher** [comment]
I have the same issue when I import the AWS SDK unity packages and the Mixed Reality Toolkit. Though, it doesn't happen until I import both packages.

Not sure where you got your AWS unity packages, and the published one here are not previews. The download is aws-sdk-unity_3.3.736.0, and for example, the Lambda package is 3.3.109.23

Maybe try the newer version?

**Comment by chrisdirkisaurecon** [comment]
Can reproduce with aws-sdk-net-3.3.750.0 and the Addressables package within Unity

`Library\PackageCache\com.unity.scriptablebuildpipeline@1.8.2\Editor\CacheServer\Client.cs(464,35): error CS0433: The type 'InvalidDataException' exists in both 'AWSSDK.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null' and 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'`

**Comment by ashishdhingra** [comment]
Hi @michael-martinez,

Starting with version 3.5 of the AWS SDK for .NET, projects using Unity 2018.1 or later should target the .NET Standard 2.0 release of the SDK. You can find additional information in the developer guide: [Unity support](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/unity-special.html) and [Migrating your Unity application](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/net-dg-v35.html#net-dg-v35-changes-unity).

Please try using the .NET Standard 2.0 version of the AWS SDK for .NET (version 3.5). 

Thanks,
Ashish
