### ISSUE TITLE
PrestoDB query with .NET

### ISSUE THREAD

**Issue by sindizzy** [aws/aws-sdk-net#1608]
A third-party has provided my company with an **AWS Presto** database. I can use DBeaver to connect and make simple queries like

```
select *
from hive.mycompany.trip_master
where yyyymmdd = '20191201' and operator='XY' and carid='3AQQW39''
```

That all works great but now I need to automate this with a .NET application. Since Athena is based on Presto my first inclination is to use the AWSSDK.Athena library. However there are no examples on how to use the Athena driver to connect to an AWS Presto DB. 

Am I going down the right path? Are there examples of .NET code on how to do this? Should I be using the AWSSDK.ElasticMapReduce library?

`

**Comment by ashishdhingra** [comment]
Hi @sindizzy, 

The [Athena Code Samples](https://docs.aws.amazon.com/athena/latest/ug/code-samples.html) could be helpful. Even though the examples are in Java, it should be easily portable to .NET. Kindly let me know if this is helpful.

Thanks,
Ashish

**Comment by sindizzy** [comment]
@ashishdhingra Presto is based on Athena but its a different mechanism. I can connect to Athena no problem. Its the Presto db that I am having trouble with. If there is an example specific to Presto I haven't seen it.

**Comment by ashishdhingra** [comment]
@sindizzy As of now, I could not find any working example on using Presto using .NET SDK. The [Athena Code Samples](https://docs.aws.amazon.com/athena/latest/ug/code-samples.html) link provides examples in Java. As mentioned earlier, these examples should easily be ported to .NET using the [AWSSDK.Athena](https://github.com/aws/aws-sdk-net/tree/master/sdk/src/Services/Athena). Please try porting some examples and let me know if it works.

Thanks,
Ashish

**Comment by sindizzy** [comment]
Thank you, but again that is Athena. Regardless if the sample is in Java, .NET, or Python it is still for Athena. I don't have to port the samples to .NET because Amazon has [samples in .NET](https://docs.aws.amazon.com/code-samples/latest/catalog/dotnet_legacy-Athena-AthenaSample2-SimpleQuery-athena_dotnet_example.cs.html) already. For **Athena**. I already have working code for connections to an Athena db. Again Athena is not the issue.

The samples I am looking for is Presto which is a different animal.

**Comment by ashishdhingra** [comment]
Hi @sindizzy, 

Good morning.

I was trying to explore for code samples for using Athena with PrestoDB. As per [Athena User Guide](https://docs.aws.amazon.com/athena/latest/ug/what-is.html), the first step is setting up datasource. It doesn't specifically mentions about PrestoDB, may be Athena support could provide some guidance. 

.NET SDK appears to have API for interactions with Athena, but not directly with PrestoDB.

Thanks,
Ashish

**Comment by sindizzy** [comment]
I have already gone through all these sources and even posted on the Amazon official forum. There are no samples connecting to presto that I can find.

**Comment by ashishdhingra** [comment]
@sindizzy As mentioned in my previous reply, Athena appears to use PrestoDB in the back end. This could be something that might be configurable in Athena dashboard, may be Athena support could help. AWS .NET SDK only has wrapper to connect to Athena service API, with no direct interaction with PrestoDB. I wish I could help here.
