### ISSUE TITLE
Empty AttributeValues are indistinguishable

### ISSUE THREAD

**Issue by WalkerCodeRanger** [aws/aws-sdk-net#161]
This may be related to issue #159.  I have found that three attribute values are indistinguishable through the public API.  The three values (all legal and the same as would be returned from a GetItem request) are:

    var boolValue = new AttributeValue() { BOOL = false };
    var listValue = new AttributeValue() { L = new List<AttributeValue>() };
    var mapValue = new AttributeValue() { M = new Dictionary<string, AttributeValue>() };

Looking at the code this appears to be mostly because collection values are initialized to an empty collection.  Using reflection to access the *internal* method `IsSetBOOL` the first value can be distinguished.  However, the last two are literally identical in their internal state.

This situation is UNACCEPTABLE.  It is literally impossible to determine the type of a stored value in a row if it is an empty list or map.  Something most be done to fix this.

Note: this actually causes a bug in your own `Amazon.DynamoDBv2.DocumentModel` API where `null` will be returned instead of an empty `DynamoDBList` or empty `Document` because `IsSetL` and `IsSetM` return false.

**Comment by PavelSafronov** [comment]
In SDK version 2.3.19 we added properties `IsBOOLSet`, `IsLSet`, and `IsMSet` fields to `AttributeValue` class that allows you to check if the corresponding `BOOL`, `L`, and `M` properties are set, as well as clearing them. This should allow you to test if a collection type is empty and if BOOL is set without using reflection.

We also added a similar `IsItemSet` field to `GetItemResult` class to address [issue 159](https://github.com/aws/aws-sdk-net/issues/159).

Thanks for reporting this issue!

**Comment by WalkerCodeRanger** [comment]
Thanks, I have updated my code to use these properties and they worked fine.  I would suggest you better document the use of these properties.  Particular setting `IsLSet` and `IsMSet` in order to put/update and empty list or map was not very clear.

**Comment by NullVoxPopuli** [comment]
looks like there needs to be one for `SS`
