### ISSUE TITLE
RegionEndpoint has incorrect display names for european regions

### ISSUE THREAD

**Issue by gustyr** [aws/aws-sdk-net#1611]
## Expected Behavior

RegionEndpoint descriptions should be consistent and follow same format.

## Current Behavior

`Amazon.endpoints.json` contain all european regions starting with "Europe"
class RegionEndpoint has static fields:
``` c#
	public static readonly RegionEndpoint EUNorth1 = GetEndpoint("eu-north-1", "**EU North** (Stockholm)");
	public static readonly RegionEndpoint EUWest1 = GetEndpoint("eu-west-1", "**EU West** (Ireland)");
	public static readonly RegionEndpoint EUWest2 = GetEndpoint("eu-west-2", "**EU West** (London)");
	public static readonly RegionEndpoint EUWest3 = GetEndpoint("eu-west-3", "**EU West** (Paris)");
	public static readonly RegionEndpoint EUCentral1 = GetEndpoint("eu-central-1", "**EU Central** (Frankfurt)");
	public static readonly RegionEndpoint EUSouth1 = GetEndpoint("eu-south-1", "**Europe** (Milan)");
```

## Possible Solution

Fix RegionEndpoint class with correct descriptions

## Your Environment

* AWSSDK.Core version used: 3.3.106.23
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

check commit: https://github.com/aws/aws-sdk-net/commit/856b496abe180c9592565e48393e738e144cc346

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by normj** [comment]
This has been fixed in newer versions of the SDK
