### ISSUE TITLE
AWS S3 plugin with unity conflicts with Unity's Addressables

### ISSUE THREAD

**Issue by nanop** [aws/aws-sdk-net#1612]
AWS Conflicts with `InvalidDataException` class

## Steps to Reproduce (for bugs)
When Installing `AWSSDK.S3.3.3.110.70.unitypackage` with unity 2019.3.9f1 and having `Addressables` already as an installed package, you will get the below exception.

Heres the exception: 
```
Library/PackageCache/com.unity.scriptablebuildpipeline@1.7.2/Editor/CacheServer/Client.cs(464,35): error CS0433: The type 'InvalidDataException' exists in both 'AWSSDK.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null' and 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
```

## Your Environment
Im On a (Mac with 10.15.4 (19E287))
installing package  AWSSDK.S3.3.3.110.70.unitypackage with unity 2019.3.9f1

output of dotnet --info...
.NET Core SDK (reflecting any global.json):
 Version:   3.1.202
 Commit:    6ea70c8dca

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.202/

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  3.0.100 [/usr/local/share/dotnet/sdk]
  3.1.200 [/usr/local/share/dotnet/sdk]
  3.1.202 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by marc-call-healthscholars** [comment]
Has there been any solution or fix for this?

**Comment by nanop** [comment]
> Has there been any solution or fix for this?

There documentation is crap! and is not easily visible, but afaik they have dont support it anymore, instead they want us to use their github, its been a while, but I was able to download it and use it, there's like link.xml u have to create as well... it absolutely sucks they didnt have out of the box solution.
heres the blog I used if I rem right...
https://aws.amazon.com/blogs/developer/referencing-the-aws-sdk-for-net-standard-2-0-from-unity-xamarin-or-uwp/

**Comment by marc-call-healthscholars** [comment]
Thank you @nanop really appreciate giving me some guidance!

**Comment by nanop** [comment]
> Thank you @nanop really appreciate giving me some guidance!

Yeah sure.. if it doesnt work... let me know I have the dll's and link file etc.. happy to send it to you.

**Comment by marc-call-healthscholars** [comment]
If you wouldn't mind posting a link to download the dll's I'd appreciate it!

**Comment by nanop** [comment]
https://drive.google.com/drive/folders/1pGDYRnUYZYsyHi9mkMufB3g_1hJLxHdU?usp=sharing 
This package is only for S3, if you want other things, youll have add to link.xml and put those dlls there.

**Comment by ashishdhingra** [comment]
Hi @nanop,

Starting with version 3.5 of the AWS SDK for .NET, projects using Unity 2018.1 or later should target the .NET Standard 2.0 release of the SDK. You can find additional information in the developer guide: [Unity support](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/unity-special.html) and [Migrating your Unity application](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/net-dg-v35.html#net-dg-v35-changes-unity).

Please try using the .NET Standard 2.0 version of the AWS SDK for .NET (version 3.5). 

Thanks,
Ashish
