### ISSUE TITLE
How to use custom ServiceURL when building Clients with AWSOptions.CreateServiceClient

### ISSUE THREAD

**Issue by danielhill** [aws/aws-sdk-net#1613]
I need to make calls to MediaConvert, which requires me to use a specific ServiceURL. As per the guidance to create a concrete client implementation of `IAmazonMediaConvertClient` I am using `AWSOptions.CreateServiceClient<IAmazonMediaConvertClient>()`. Unfortunately I cannot see any way I can change the ServiceURL as it's readonly.

The way I've had to do it was to steal the `CreateCredentials` method from `AWSSDK.Extensions.NETCore.Setup/ClientFactory.cs`and copy it into my program, then manually build the config objects, credentials and client like:

```
var awsOptions = config.GetAWSOptions();
AmazonMediaConvertConfig mcConfig = new AmazonMediaConvertConfig
{
   ServiceURL = "https://******.mediaconvert.ap-southeast-2.amazonaws.com",
};

var cr = CreateCredentials(logger, awsOptions);

using (var mediaConvertClient = new AmazonMediaConvertClient(cr, mcConfig))
{
   ...
```
rather than the usual and simpler `using (var s3Client = awsOptions.CreateServiceClient<IAmazonS3>())`.

## Expected Behavior
Ideally I'd like to be able to pass some sort of parameter or something into CreateServiceClient letting me customise the ServiceURL. Failing that, can I change ServiceURL once the client is created?

## Context
This issue has added a lot more complexity and pain to my requirement to invoke the MediaConvert API.

## Your Environment

AWSSDK.Extensions.NETCore.Setup 3.3.101
AWSSDK.MediaConvert 3.3.117.9
AWSSDK.S3 3.3.110.70

Targetting .NET Core 3.1.202

## .NET Core Info

* .NET Core version used for development: 3.1.202
* .NET Core version installed in the environment where application runs: 3.1.202
* Output of `dotnet --info`: 
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.202
 Commit:    6ea70c8dca

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.202/

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  3.1.101 [/usr/local/share/dotnet/sdk]
  3.1.102 [/usr/local/share/dotnet/sdk]
  3.1.200 [/usr/local/share/dotnet/sdk]
  3.1.201 [/usr/local/share/dotnet/sdk]
  3.1.202 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```
* Contents of project.json/project.csproj: 
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\XXXModelsEntities\XXXModelsEntities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.3.101" />
    <PackageReference Include="AWSSDK.MediaConvert" Version="3.3.117.9" />
    <PackageReference Include="AWSSDK.S3" Version="3.3.110.70" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="1.1.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="3.1.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="3.1.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="3.1.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="3.1.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="3.1.4" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="3.1.4" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="3.1.4" />
    <PackageReference Include="MimeTypes" Version="1.1.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
```
[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by alesfrede** [comment]
hi i find a fix  for AmazonMediaConvertConfig 
https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/MediaConvert/Generated/AmazonMediaConvertConfig.cs

   var mcConfig = new AmazonMediaConvertConfig // config service
            {
                //ServiceURL = mediaConvertEndpoint, //bug?  
            };
            mcConfig.ServiceURL = mediaConvertEndpoint; // fixed

**Comment by ashishdhingra** [comment]
Hi @danielhill,

Good afternoon.

All SDK service clients have the several overloaded constructors, some of which (as pointed by @alesfrede) have parameter to specify configuration object. For [AmazonMediaConvertClient](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/MediaConvert/Generated/_netstandard/AmazonMediaConvertClient.cs), it is [AmazonMediaConvertConfig](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/MediaConvert/Generated/AmazonMediaConvertConfig.cs). These service specific configuration classes inherit from [ClientConfig](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/ClientConfig.cs) which allows you to specify [ServiceURL](https://github.com/aws/aws-sdk-net/blob/6efe190fa4bc3e3e9ca55020b7042219ba9b6c53/sdk/src/Core/Amazon.Runtime/ClientConfig.cs#L181) property. You should be able to use code something like to override `ServiceURL`:
```C#
var amazonMediaConvertClient = new AmazonMediaConvertClient(new AmazonMediaConvertConfig() {
                ServiceURL = <<service_url>>
            });
```

Also, is using `AWSOptions`, could you kindly confirm if the below code works for you:
```C#
AWSOptions awsOptions = new AWSOptions();
awsOptions.DefaultClientConfig.ServiceURL = "<<service_url>>";
var amazonMediaConvertClient = awsOptions.CreateServiceClient<IAmazonMediaConvertClient>();
```

Please let me know if this helps and if we could close the issue.

Thanks,
Ashish
