### ISSUE TITLE
S3 3.3.110.66 breaks metadata contract; backward compat and interoperability

### ISSUE THREAD

**Issue by LeadAssimilator** [aws/aws-sdk-net#1617]
## Expected Behavior

S3 metadata values should not be percent-encoded.

## Current Behavior

S3 metadata values are percent-encoded.

## Possible Solution

Revert 342407feaa47e10175d9c657c149be59e9293658.

## Steps to Reproduce (for bugs)

Install S3 3.3.110.66.
Upload a file with metadata characters containing characters like {space}{tab}{\r}{\n}%^&+{}|:"<>?`[]\;./.
Observe the percent-encoded values.

## Context

The change in 342407feaa47e10175d9c657c149be59e9293658 is a breaking contract change since previously unencoded values are now percent encoded.  

It completely breaks backwards compatibility with older sdks, other sdks and clients accessing S3 directly that are not expecting percent-encoded values in metadata.  

For example, using the encryption client on .66 or later makes x-amz-meta-x-amz-iv, x-amz-meta-x-amz-key and x-amz-meta-x-amz-matdesc unreadable to versions < .66 and all fail to download/decrypt with invalid base64 exceptions.  

The aforementioned commit should be reverted to restore interoperability and avoid corruption of metadata for unsuspecting users when they update.  It should remain the developer's responsibility to encode their metadata as they see fit and NOT the sdk.

## Your Environment

* AWSSDK.Core version used: NA
* Service assembly and version used: S3 3.3.110.66
* Operating System and version: NA
* Visual Studio version: NA
* Targeted .NET platform: 4.8

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by normj** [comment]
Thanks for reporting the issue and we are investigate the right way how to move forward. I'm not sure simply reverting is the right way since this was done because of another GitHub issue dealing with unicode characters.

**Comment by LeadAssimilator** [comment]
I don't view breaking the existing contract as a really viable solution and the longer this breaking change remains in place, the more people will be affected by it and waste valuable time figuring out what is wrong with their stack.  I think it is best to revert first, then determine how to re-address the Unicode issue.  

What was the unicode issue number?  Unicode almost always requires special handling so having those that need to use it call Uri.EscapeDataString/Uri.UnescapeDataString is not out of the ordinary or unexpected.  For example, when uploading files to S3, it is quite common to have to call Uri.EscapeDataString as part of constructing the Content-Disposition header for the utf-8 filename.

**Comment by ganeshnj** [comment]
The issue has been fixed in AWSSDK.S3 3.3.111.1.

We added EnableUnicodeEncodingForObjectMetadata flag to enable/disable escaping of non-ascii characters in metadata. It is set to false by default.
