### ISSUE TITLE
Q: service model json files

### ISSUE THREAD

**Issue by grahamehorner** [aws/aws-sdk-net#1619]
I'm interested to know how/where the source of the service model JSON files; and if these are available possibly as swagger definitions to allow generation of models/client APIs that use data annotations to enforce/perform request validation prior to sending requests to the service (catch issues early)

for example: using the [Required]/[StringLength]/[Range] ... attribution; having a swagger and/or gRPC proto contracts for the API surface would also allow for better more comprehensive documentation generation and constancies across all platforms as swagger/gRPC proto contract are widely supported and thus would allow developers to use their tool of choice to generate clients in other languages that AWS may not support directly.

**Comment by lukebrowell** [comment]
I can certainly see the theoretical advantages of your suggestion Grahame.

Would you consider putting together a PR with a subsection of a library generated for comparison in each of the ways you outline above; That way the community could see a concrete example of the benefits you outlined?

**Comment by ashishdhingra** [comment]
Hi @grahamehorner,

Please have a look at [generator](https://github.com/aws/aws-sdk-net/tree/master/generator) folder under root of [aws-net-sdk](https://github.com/aws/aws-sdk-net) repo. Hope it helps. Let me know if it is what you are looking for and if this issue could be closed.

Thanks,
Ashish

**Comment by 3GDXC** [comment]
@ashishdhingra how are these .json files created is the ask; these aren't in Swagger/OpenAPI format and having vision of how/what tooling was used and the process (with source) that created these files would assist in creating for an enhanced experience i.e. having tooling create Swagger/OpenAPI files with additional model validation metadata like string length/ranges/regex/nullable etc. and thus have these create swagger clients for said API with better model validation using client tooling.

**Comment by ashishdhingra** [comment]
@3GDXC, I will post the question with the development team and share any update with you.

Thanks,
Ashish

**Comment by normj** [comment]
AWS services use a few different internal tools and technologies to model their APIs. None of them are swagger. You have to remember many AWS services predate swagger. The json files are created using some tools we have to translate the models service teams write into a common format that all of the AWS SDKs can use. 

Long term wise is to have services use our new open source protocol-agnostic interface definition language called [Smithy](https://github.com/awslabs/smithy).

**Comment by 3GDXC** [comment]
@normj hmm, so yet another proprietary IDL ? with little or no tooling as yet for languages as opposed to working with open standards and/or contributing to said standard with a PR if/when they have failings or design short comings.  IMHO its the wrong thing to do  :'(    hence why I was looking to develop swagger tooling for AWS  :'(

**Comment by ashishdhingra** [comment]
Closing this issue based on @normj's response.

**Comment by lukebrowell** [comment]
Adequate explanation for the premature closing of this issue was not provided and the technical justification for not using OpenAPI (Formerly swagger) seems inadequate given that Swagger is actively supported by AWS API Gateway as the industry standard; The community engagement approach taken here ought to be reviewed for lessons-learned.
