### ISSUE TITLE
Deployment version label in New Wizard.

### ISSUE THREAD

**Issue by minzdrav** [aws/aws-sdk-net#162]
Hi Amazon team.
New publishing wizard doesn't allow to set version on first publish.
I have several Environment for application: test, beta, production. I'm publishing with different build configurations and transformed configs. 
I'm using version to distinguish which version is designed for the environment (t123, b123, p123). It's important because sometimes I need to restore previous environment version and I can simple look at first char of version. 
With new wizard I can't use version for that. 
Could you please return version input to wizard?

**Comment by minzdrav** [comment]
Hi Jimfl.
Thank you. I know about legacy wizard. I hope this missing functionality will be added to new wizard before removing legacy wizard.

**Comment by jimfl** [comment]
Promoting to a feature request. Thanks for letting us know this is valuable to you.

**Comment by jimfl** [comment]
Since this is not directly SDK related, I have moved the item to our internal backlog.
