### ISSUE TITLE
BufferSize property does not affect buffer size when reading from the input stream

### ISSUE THREAD

**Issue by VasilSirakov** [aws/aws-sdk-net#1621]
## Expected Behavior

I am setting a value for `BufferSize` in the `AmazonS3Client` config. I expect that after calling `PutObjectAsync`, the amount of bytes buffered from the stream will be the size specified by the `BufferSize` property.

## Current Behavior

Creating the client and sending the PUT request for creating an object.
```c#
var s3Client = new AmazonS3Client(access, secret, token, new AmazonS3Config
{
     RegionEndpoint = Amazon.RegionEndpoint.USEast1,
     BufferSize = 1024 * 1024, // completely arbitrary
});

var response = await s3Client.PutObjectAsync(new PutObjectRequest
{
      Key = fileName,
      BucketName = bucketName,
      InputStream = new CustomStream(...),
});
```

In my implementation of `CustomStream` I have solely overriden `ReadAsync`. The problem comes after sending the PUT request. When I debug the `ReadAsync` function the amount of bytes buffered is the default buffer size for the `Stream` class - 81920 and not the value specified in the `BufferSize` property or the one in `AWSSDKUtils`.
Could it be something to do with my the custom implementation of my stream? I've kept it very minimal there and it doesn't seem like anything there should be the cause.

## Your Environment

* .NET Core 3.1 
* AWSSDK.Core 3.3.110.70

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by ashishdhingra** [comment]
Hi @VasilSirakov,

Good afternoon.

Please confirm if you happen to enable the ChunkedEncoding. Looking at the [code](https://github.com/aws/aws-sdk-net/blob/382df643ea2e9a69613a19a991dd51f7c2dd697f/sdk/src/Core/Amazon.Runtime/Pipeline/HttpHandler/HttpHandler.cs#L544), looks like the buffer size is taken into account only if chunked encoding is enabled. Just assuming this could be the cause of buffer size not taken into account.

Thanks,
Ashish

**Comment by VasilSirakov** [comment]
Thank you for the reply @ashishdhingra. I have not set `ChunkedEncoding` to `false` anywhere and its default value is true. This particular property cannot be causing it.

The insides of my implementation of `ReadAsync` in the custom stream are a bit funky - I am working with a gRPC stream reader and asynchronously awaiting and reading message by message containing a set amount of bytes (basically an `IAsyncEnumerable`). This also can't be related because the `ReadAsync` function is called by the SDK after firing the PUT with the value 81920 as buffer size regardless of its implementation.

Since I opened this issue I haven't had the time to dig deeper so I've moved to the multi-part upload approach as there I can explicitly send it in chunks. I was just initially drawn to the simplicity of this high level API. I don't see any similar issues related to this in this repo, though, so it could very well be something sneaky on my end.

**Comment by ashishdhingra** [comment]
@VasilSirakov Thanks for your response. Please advise if you would like to close this issue given that multipart upload approach works for your scenario.

**Comment by VasilSirakov** [comment]
@ashishdhingra I suppose I'll close it even though it isn't resolved. I can't really contribute with further information that would help you.

**Comment by jefferson** [comment]
# Expected Behavior
As @VasilSirakov I am setting a value for BufferSize in the AmazonS3Client config. But in this time I expect that after calling `GetObjectStreamAsync`, the amount of bytes buffered from the stream will be the size specified by the BufferSize property.

# Current Behavior

```c#
using (var stream = await _amazonS3.GetObjectStreamAsync(bucketName, key, additionalProperties, source.Token))
{
      //omiting some part of configuration for be brevity
      while ((read = await stream.ReadAsync(memory)) > 0)
      {
            using (var memoryStream = new MemoryStream())
            {
                    //the amount of data in read is wrong
            }
       }
 }
```

In my code I just use GetObjectStreamAsync.

**Comment by ashishdhingra** [comment]
#1814
