### ISSUE TITLE
Please add Equals() implementation to AttributeValue

### ISSUE THREAD

**Issue by WalkerCodeRanger** [aws/aws-sdk-net#163]
Tried to write a unit test today and needed to compare two AtttributeValues for equality, however it doesn't implement .Equals().  AttributeValue seems like the kind of class that should implement .Equals() given that it does represent a simple value.

**Comment by jimfl** [comment]
Added to https://github.com/aws/aws-sdk-net/blob/master/FEATURE_REQUESTS.md
