### ISSUE TITLE
SNS message parser incorrectly parses key for "messageText"

### ISSUE THREAD

**Issue by jordlynn** [aws/aws-sdk-net#1632]
We found that messages coming from SNS via HTTP/s  to our service, the "messageText" field key is literally "MessageText:", however looking the parser looks for the key "Message" which doesn't exist in the message body. This results in the field's value being "null".

## Expected Behavior

When `Message.ParseMessage(messageText)` is called the "MessageText" field in the json is added to the Message object.

## Current Behavior

When the messageText is being parsed, the "MessageText" field is skipped/ignored because currently the parser looks for "Message".

## Possible Solution

Change the key value from "Message" to "MessageText".

## Steps to Reproduce (for bugs)

Receive a HTTP/s SNS message, and try and parse the message into a Message object.
run `Message.ParseMessage(messageText)` where

```
messageText = {
TopicArn: "arn:aws:sns:us-east-1:187094234111:XXXXX",
Type: "Notification",
Subject: "",
MessageId: "798fd224-c134-5755-XXXX",
MessageText: "{\"someUserID\": \"someID\"}",
SubscribeURL: "",
Token: "",
SignatureVersion: 1
Signature: XXXX
SigningCertURL: XXXX
"

```
## Your Environment

* AWSSDK.Core version used: 3.3.101.178
* Service assembly and version used: x
* Operating System and version: x
* Visual Studio version: x
* Targeted .NET platform: 4.7

## .NET Core Info

* .NET Core version used for development: 4.7
* .NET Core version installed in the environment where application runs:  4.7
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by ashishdhingra** [comment]
Hi @jordlynn, 

Good afternoon.

Thanks for reporting the issue. Please help me with the following to troubleshoot the issue:

1. Use case for your scenario. In other words, how is the message received from SNS (is it part in the Lambda function, etc.)

2. Logs, if available.

While in the [Message.ParseMessage()](https://github.com/aws/aws-sdk-net/blob/caaa1d702b6e9ad2a3a32d468a07f03db3ae6a67/sdk/src/Services/SimpleNotificationService/Custom/Util/Message.cs#L76) I do see that the code is expecting **Message** field, I just want to examine the JSON sent by SNS Topic.

Thanks,
Ashish
