### ISSUE TITLE
Unity Readme: Incorrect XML and NullReferenceException

### ISSUE THREAD

**Issue by derwaldgeist** [aws/aws-sdk-net#1634]
I tried to follow the Unity setup as described here:

https://github.com/aws/aws-sdk-net/blob/master/Unity.README.md#unity-sdk-fundamentals

First of all, I noticed that the `awsconfig.xml` file described there is not a valid XML document, as the `<logging>` element is nested inside the `<aws>` start tag. I corrected the XML to this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<aws>
  <logging
  		logTo="UnityLogger"
  		logResponses="Always"
  		logMetrics="true"
  		logMetricsFormat="JSON" />
  	/>
</aws>
```

However, when I add this to the S3 sample and run it, I get the following error message:

```
NullReferenceException: Object reference not set to an instance of an object
Amazon.AWSConfigs.GetSection[T] (System.String sectionName) (at <cdbb096e571842bea12614965a2b3227>:0)
Amazon.Util.Internal.RootConfig..ctor () (at <cdbb096e571842bea12614965a2b3227>:0)
Amazon.AWSConfigs..cctor () (at <cdbb096e571842bea12614965a2b3227>:0)
Rethrow as TypeInitializationException: The type initializer for 'Amazon.AWSConfigs' threw an exception.
Amazon.Runtime.Internal.Util.Logger.ConfigureLoggers () (at <cdbb096e571842bea12614965a2b3227>:0)
Amazon.Runtime.Internal.Util.Logger..ctor (System.Type type) (at <cdbb096e571842bea12614965a2b3227>:0)
Amazon.Runtime.Internal.Util.Logger.GetLogger (System.Type type) (at <cdbb096e571842bea12614965a2b3227>:0)
Amazon.Util.Internal.AmazonHookedPlatformInfo..cctor () (at <cdbb096e571842bea12614965a2b3227>:0)
Rethrow as TypeInitializationException: The type initializer for 'Amazon.Util.Internal.AmazonHookedPlatformInfo' threw an exception.
Amazon.UnityInitializer.Awake () (at <cdbb096e571842bea12614965a2b3227>:0)
UnityEngine.GameObject:AddComponent()
Amazon.UnityInitializer:AttachToGameObject(GameObject)
AWSSDK.Examples.S3Example:Start() (at Assets/S3Example.cs:55)
```

Once I disable the XML file, the error goes away. So it doesn't seem as if the XML is correctly interpreted by the SDK.

**Comment by boxseto** [comment]
I come across the same issue. I think there is a fix to that by also changing **ALL** the `assembly` of AWSSDK to the format of 
```
 <assembly fullname="assembly.XXXXXXXXXXXXXXXXX" preserve="all">
  	<namespace fullname="Amazon.Util.Internal.PlatformServices" preserve="all"/>
  </assembly>
```
Rather than
```
<assembly fullname="AWSSDK.XXXXXXXXXXXX" preserve="all"/>
```
in the README.

For example, the working format in that of README will be:
```
 <assembly fullname="AWSSDK.Core" preserve="all">
  	<namespace fullname="Amazon.Util.Internal.PlatformServices" preserve="all"/>
  </assembly>
  <assembly fullname="AWSSDK.CognitoIdentity" preserve="all">
  	<namespace fullname="Amazon.Util.Internal.PlatformServices" preserve="all"/>
  </assembly>
  <assembly fullname="AWSSDK.SecurityToken" preserve="all">
  	<namespace fullname="Amazon.Util.Internal.PlatformServices" preserve="all"/>
  </assembly>
```

Hope this helps

**Comment by Paul-B-AWS** [comment]
@derwaldgeist, a couple of notes:
* It looks like the README file you're referring to has moved to a new (Unity archive) repo:
  https://github.com/aws/aws-sdk-unity-net
  I'm working at updating the README of this repo (aws-sdk-net) with the correct link.
* I noticed that your replacement XML in `awsconfig.xml` seems to have an extra ending angle bracket (`/>`) just before the closing `</aws>` tag.
  I'm not sure what the type initializer for **Amazon.AWSConfigs** would do with this, so don't know if it contributed to the error message you saw, but I thought I'd mention it.

I also wanted to ask if you were able to resolve your issues.
If so, would you be willing to describe the resolution here and then close the issue?

**Comment by Paul-B-AWS** [comment]
The README for [aws/aws-sdk-net](https://github.com/aws/aws-sdk-net) has been updated to handle changes to Unity support.
* Added links to the latest developer guide with information about using Unity with V3.5 and later of the SDK.
   If enhancements, clarifications, etc., are needed in the [developer guide](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide), please click the feedback link in the appropriate developer-guide webpage and then provide details.
* Updated the link to point to the repo that contains the _**legacy**_ information and code for Unity support.

The following is a direct link to the Unity content in the README: https://github.com/aws/aws-sdk-net#unity-support
