### ISSUE TITLE
Valid calls to SNS ConfirmSubscription methods always return "invalidParameter: topicArn" exception

### ISSUE THREAD

**Issue by horizondave** [aws/aws-sdk-net#1638]
## Description
Calling ConfirmSubscription on the AWSSDK SNS Client always returns an exception, even with valid parameters.
## Reproduction Steps
Try to setup a HTTPS subscription to an SNS topic in code using the AWSSDK SNS Client
In the HTTPS callback, use Message.ParseMessage to get a class instance.
Call <snsclient>.ConfirmSubscription and pass message.token and message.topicArn received in the callback - any of the confirm methods can be called.  They all fail equally.
An InvalidParameter exception always gets thrown for topicArn

### Logs
Amazon.SimpleNotificationService.Model.InvalidParameterException: Invalid parameter: TopicArn
  Module "Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler", in HandleException
  Module "Amazon.Runtime.Internal.ExceptionHandler`1", in Handle
  Module "Amazon.Runtime.Internal.ErrorHandler", in ProcessException
  Module "Amazon.Runtime.Internal.ErrorHandler+<InvokeAsync>d__5`1", in MoveNext
  Module "System.Runtime.ExceptionServices.ExceptionDispatchInfo", in Throw
  Module "System.Runtime.CompilerServices.TaskAwaiter", in ThrowForNonSuccess
  Module "System.Runtime.CompilerServices.TaskAwaiter", in HandleNonSuccessAndDebuggerNotification
  Module "System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter", in GetResult
  Module "Amazon.Runtime.Internal.CallbackHandler+<InvokeAsync>d__9`1", in MoveNext
  Module "System.Runtime.ExceptionServices.ExceptionDispatchInfo", in Throw
  Module "System.Runtime.CompilerServices.TaskAwaiter", in ThrowForNonSuccess
  Module "System.Runtime.CompilerServices.TaskAwaiter", in HandleNonSuccessAndDebuggerNotification
  Module "System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter", in GetResult
  Module "Amazon.Runtime.Internal.EndpointDiscoveryHandler+<InvokeAsync>d__2`1", in MoveNext
  Module "System.Runtime.ExceptionServices.ExceptionDispatchInfo", in Throw
  Module "Amazon.Runtime.Internal.EndpointDiscoveryHandler+<InvokeAsync>d__2`1", in MoveNext
  Module "System.Runtime.ExceptionServices.ExceptionDispatchInfo", in Throw
  Module "System.Runtime.CompilerServices.TaskAwaiter", in ThrowForNonSuccess
  Module "System.Runtime.CompilerServices.TaskAwaiter", in HandleNonSuccessAndDebuggerNotification
  Module "System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter", in GetResult
  Module "Amazon.Runtime.Internal.CredentialsRetriever+<InvokeAsync>d__7`1", in MoveNext
  Module "System.Runtime.ExceptionServices.ExceptionDispatchInfo", in Throw
  Module "System.Runtime.CompilerServices.TaskAwaiter", in ThrowForNonSuccess
  Module "Amazon.Runtime.Internal.RetryHandler+<InvokeAsync>d__10`1", in MoveNext
  Module "System.Runtime.ExceptionServices.ExceptionDispatchInfo", in Throw
  Module "Amazon.Runtime.Internal.RetryHandler+<InvokeAsync>d__10`1", in MoveNext
  Module "System.Runtime.ExceptionServices.ExceptionDispatchInfo", in Throw
  Module "System.Runtime.CompilerServices.TaskAwaiter", in ThrowForNonSuccess
  Module "System.Runtime.CompilerServices.TaskAwaiter", in HandleNonSuccessAndDebuggerNotification
  Module "System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter", in GetResult
  Module "Amazon.Runtime.Internal.CallbackHandler+<InvokeAsync>d__9`1", in MoveNext
  Module "System.Runtime.ExceptionServices.ExceptionDispatchInfo", in Throw
  Module "System.Runtime.CompilerServices.TaskAwaiter", in ThrowForNonSuccess
  Module "System.Runtime.CompilerServices.TaskAwaiter", in HandleNonSuccessAndDebuggerNotification
  Module "System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter", in GetResult
  Module "Amazon.Runtime.Internal.CallbackHandler+<InvokeAsync>d__9`1", in MoveNext
  Module "System.Runtime.ExceptionServices.ExceptionDispatchInfo", in Throw
  Module "System.Runtime.CompilerServices.TaskAwaiter", in ThrowForNonSuccess
  Module "System.Runtime.CompilerServices.TaskAwaiter", in HandleNonSuccessAndDebuggerNotification
  Module "System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter", in GetResult
  Module "Amazon.Runtime.Internal.ErrorCallbackHandler+<InvokeAsync>d__5`1", in MoveNext
  Module "System.Runtime.ExceptionServices.ExceptionDispatchInfo", in Throw
  Module "System.Runtime.CompilerServices.TaskAwaiter", in ThrowForNonSuccess
  Module "System.Runtime.CompilerServices.TaskAwaiter", in HandleNonSuccessAndDebuggerNotification
  Module "System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter", in GetResult
  Module "Amazon.Runtime.Internal.MetricsHandler+<InvokeAsync>d__1`1", in MoveNext
  Module "System.Runtime.ExceptionServices.ExceptionDispatchInfo", in Throw
  Module "System.Runtime.CompilerServices.TaskAwaiter", in ThrowForNonSuccess
  Module "System.Runtime.CompilerServices.TaskAwaiter", in HandleNonSuccessAndDebuggerNotification
  Module "System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter", in GetResult
  File <my code>
### Environment

* SDK Version: latest as of 2020-06-10
* Package Version: 3.3.101.181
* OS Info: Windows 10
* Build Environment VS2019 
* Targeted .NET Platform:  aspnetcore 3.1.4

## Resolution
Calling the SubscribeUrl from Message instead of executing a Confirm method is successful.

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @horizondave, 

Thanks for posting the issue. Please share the code snippet to reproduce and troubleshoot the issue.

Regards,
Ashish

**Comment by horizondave** [comment]
"How to reproduce" is clear?
If you try to use the topicARN parameter sent to the HTTPS endpoint in the SNSClient "Confirmsubscription" method, it fails - every time.  You have to call the SubscribeUrl manually to successfully confirm the subscription.

**Comment by ashishdhingra** [comment]
Hi @horizondave, 

Good afternoon.

Please share the use case of your application. For instance, I'm using the following code from the API documents at [AmazonSimpleNotificationServiceClient.Subscribe](https://docs.aws.amazon.com/sdkfornet/latest/apidocs/items/TSNSSubscribeRequestNET45.html):

```C#
            var snsClient = new AmazonSimpleNotificationServiceClient("<accessId>", "<secretKey>", "<sessionToken>");

            var topicRequest = new CreateTopicRequest
            {
                Name = "CodingTestResults"
            };

            var topicResponse = snsClient.CreateTopicAsync(topicRequest).Result;

            var topicAttrRequest = new SetTopicAttributesRequest
            {
                TopicArn = topicResponse.TopicArn,
                AttributeName = "DisplayName",
                AttributeValue = "Coding Test Results"
            };

            var topicSttributesResponse = snsClient.SetTopicAttributesAsync(topicAttrRequest).Result;

            var subscribeResponse = snsClient.SubscribeAsync(new SubscribeRequest
            {
                Endpoint = "johndoe@example.com",
                Protocol = "email",
                TopicArn = topicResponse.TopicArn
            }).Result;
```

In the above code, "email" protocol is used in SubscribeRequest. Similarly, please share the following:
1. Protocol you are using in your code. Refer [SNS API Reference](https://docs.aws.amazon.com/sns/latest/api/API_Subscribe.html) for list of valid protocols.

2. Code snippet in the target protocol (I'm assuming you are Lambda/SQS/Application).

Thanks,
Ashish
