### ISSUE TITLE
Trying to run the build step in TeamCity creates  Amazon.Runtime.Internal.Transform.JsonUnmarshallerContext error

### ISSUE THREAD

**Issue by nukec** [aws/aws-sdk-net#1642]
## Description

I am having a build step which publishes the standalone package. The project uses amazon sqs and lambda. When I try to run that step on TeamCity I get following error:

`RUNREADYTORUNCOMPILER : error : Method not found: 'Void Amazon.Runtime.Internal.Transform.JsonUnmarshallerContext..ctor(System.IO.Stream, Boolean, Amazon.Runtime.Internal.Transform.IWebResponseData)'. while resolving 0xa0003df - Amazon.Runtime.Internal.Transform.JsonUnmarshallerContext..ctor.`

I can't really find anything on google, I tried to remove amazon references it works of course, then when I put amazon references back in same issue.

## Reproduction Steps
1. Make app with Aws sdk for net core.
2. Create publish standalone app step in teamcity.
3. Run to get an error.

### Logs
` RUNREADYTORUNCOMPILER : error : Method not found: 'Void Amazon.Runtime.Internal.Transform.JsonUnmarshallerContext..ctor(System.IO.Stream, Boolean, Amazon.Runtime.Internal.Transform.IWebResponseData)'. while resolving 0xa0003df - Amazon.Runtime.Internal.Transform.JsonUnmarshallerContext..ctor.
14:15:09
        Server -> C:\BuildAgent2\work\7ed9eec653ed3220\src\publish-win-x64\
14:15:09
      14:15:09
      Build FAILED.`

### Environment

* SDK Version: 3.1.202
* Package Version: AwsSdk.DynamoDbv2 3.3.106.2
* OS Info: Win 10
* Build Environment Visual studio
* Targeted .NET Platform:  

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

---

This is a :bug: bug-report

**Comment by nukec** [comment]
Resolved this with installing latest version of DynamoDbV2. Couldn't find anything on internet or in package changelog that would show issues with teamcity thought.

**Comment by nukec** [comment]
Resolved this with installing latest version of DynamoDbV2. Couldn't find anything on internet or in package changelog that would show issues with teamcity thought.

**Comment by ignas-sakalauskas-cko** [comment]
I had the same issue running code locally, and upgrading to the latest DynamoDB v2 SDK solved it.
