### ISSUE TITLE
.Net SDK S3 sync feature

### ISSUE THREAD

**Issue by brignolij** [aws/aws-sdk-net#1643]
## Describe the Feature
I could be very usefull to have the same aws-cli sync feature for S3 into the AWS SDK for .Net

### Describe alternatives you've considered

i tried to make work aws-cli sync from powershell with c# but i'm facing lot of troubles with profiling/credential, as i'm working with iis.

### Environment

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change  

---

This is a :rocket: Feature Request

**Comment by NGL321** [comment]
Hey @brignolij,

Thanks for submitting a request! I just wanted to clarify, are you looking for this feature to be added to the .NET SDK or to the aws Powershell toolkit?


😸 😷

**Comment by brignolij** [comment]
@NGL321 the feature is present into powershell toolkit, and i like it.
I really enjoy to have into the .Net SDK.

Regards

**Comment by kellertk** [comment]
We have no plans to implement a sync client for the .NET SDK at this time.
