### ISSUE TITLE
Upload file stream to S3 by web api

### ISSUE THREAD

**Issue by deadislove** [aws/aws-sdk-net#1646]
## The Question
I have the ASP.NET MVC API project and want to design the upload file stream web API, which stores to S3 bucket. I have tried the code is correct and can work in the console app project, but when I copy my code to the API project, it will keep waiting for the response messages for a long time.

```
public void uploadS3(long DrugsID,string sCategory, FileStream fs, out bool Result, out string Exe_Msg)
{
    try
    {
        var fileTransferUtility = new TransferUtility(s3Client);
        FileInfo fi = new FileInfo(fs.Name);
        keyName = fi.Name;

        if (fs.Length > 0)
        {
	   fileTransferUtility.UploadAsync(fs, bucketName, fi.Name);
        }

        Result = true;
        Exe_Msg = string.Empty;
    }
    catch (AmazonS3Exception AWSe)
    {
        Result = false;
        Exe_Msg = AWSe.Message.ToString();
    }
    catch (FileNotFoundException IOe)
    {
        Result = false;
        Exe_Msg = IOe.Message.ToString();
    }
    catch (Exception e)
    {
        Result = false;
        Exe_Msg = e.InnerException.ToString();
    }    
}
```

### Environment
* SDK Version: AWSSDK.S3
* Package Version: 
* OS Info: Windows 10
* Build Environment Visual Studio 2017
* Targeted .NET Platform:  ASP.Net framework 4.7

---

This is a :question: general question

**Comment by cbinbir** [comment]
we have an asp.net mvc application hosted in aws. Updated awssdk.s3 nuget to latest and it stopped working. (no exception)
Tried both sync (Upload) and async (UploadAsync) methods.

It works for awssdk.s3 version 3.3.110.22, awssdk.core version 3.3.104.24

**Comment by deadislove** [comment]
> we have an asp.net mvc application hosted in aws. Updated awssdk.s3 nuget to latest and it stopped working. (no exception)
> Tried both sync (Upload) and async (UploadAsync) methods.
> 
> It works for awssdk.s3 version 3.3.110.22, awssdk.core version 3.3.104.24

Today, I have installed these in my project, but it doesn't work. I try another method that is the low-level API method of the AWS S3, which can work. I don't understand the low-level API and the high-level API where the difference is?

**Comment by boblodgett** [comment]
This sounds like another issue that was happening in ASP.NET web applications where the async calls were hanging.  I released a fix for this today as of versions:
AWSSDK.Core 3.3.107.16
AWSSDK.S3 3.3.111.17

Can you give these versions a try and let us know if it corrected this issue? This should fix the UploadAsync calls from hanging.

**Comment by deadislove** [comment]
> This sounds like another issue that was happening in ASP.NET web applications where the async calls were hanging. I released a fix for this today as of versions:
> AWSSDK.Core 3.3.107.16
> AWSSDK.S3 3.3.111.17
> 
> Can you give these versions a try and let us know if it corrected this issue? This should fix the UploadAsync calls from hanging.

OK. I will try to create the new ASP.NET Web API project to test for this issue. Now, I installed the AWS SDK version list in my web API project, which is below.
```
  <package id="AWSSDK.Core" version="3.3.107.11" targetFramework="net47" />
  <package id="AWSSDK.S3" version="3.3.111.12" targetFramework="net47" />
```
I hope it can help you to find the solution method.

**Comment by boblodgett** [comment]
Closing this issue as the fix released should correct the problem and I have not heard back. Please reopen if the issue persists after upgrading to the latest versions.
