### ISSUE TITLE
unable to add tags in getPresignedURL S3(c#).

### ISSUE THREAD

**Issue by ngsaws** [aws/aws-sdk-net#1647]
In my project i am uploading objects with presigned URL using c#. Now I have a requirement to add tags in object. please suggect me how to add tags in presigned url request?

**Comment by ashishdhingra** [comment]
Hi @ngsaws,

Thanks for posting a guidance question. I did some research and looks like S3 service does not support adding Tags directly in the presigned URL. Please try adding header "**x-amz-tagging**" in HttpWebRequest Headers collection as shown in below code snippet as an example:

```C#
WebHeaderCollection myWebHeaderCollection = myHttpWebRequest.Headers;
myWebHeaderCollection.Add("x-amz-tagging","myrealtag=tagvalue");
```

Thanks,
Ashish
