### ISSUE TITLE
TransferUtility.Upload hangs

### ISSUE THREAD

**Issue by bzamfir** [aws/aws-sdk-net#1648]
## Description
I have the following code
`Dim fileTransferUtility = New TransferUtility(new AmazonS3Client(credentials,region))`
`Dim fileTransferUtilityRequest = New TransferUtilityUploadRequest With {`
`        .BucketName = bucketName,`
`        .FilePath = sourceFileName,`
`        .PartSize = 6291456,`
`        .Key = awsFileKey`
`}`
`fileTransferUtility.Upload(fileTransferUtilityRequest)`

This code worked just fine up until 
  AWSSDK.Core version="3.3.107.5"
  AWSSDK.S3 version="3.3.111.6" 

But hangs starting from 
  AWSSDK.Core version="3.3.107.6"
  AWSSDK.S3 version="3.3.111.6" 

It does never return, with exception or anything. It simply hangs.

## Reproduction Steps
See details above

### Environment
* SDK Version: 3.3
* Package Version: 
  AWSSDK.Core version="3.3.107.6"
  AWSSDK.S3 version="3.3.111.6" 

* OS Info: Windows 10 Pro, Windows Server 2012 +
* Build Environment Visual Studio 2019, 16.6.2
* Targeted .NET Platform:  4.7.1

## Resolution
- I had to stay with the following versions of the package to have the code working
  AWSSDK.Core version="3.3.107.5"
  AWSSDK.S3 version="3.3.111.6" 

This is a :bug: bug-report

**Comment by boblodgett** [comment]
A fix for this has been released as of versions:
AWSSDK.Core 3.3.107.16
AWSSDK.S3 3.3.111.17

**Comment by bzamfir** [comment]
Tested and confirm it works.
Thank you

**Comment by thorwm-zz** [comment]
This error seems to be back in the latest version as of December 28, 2022:
AWSSDK.Core 3.7.103.6
AWSSDK.S3 3.7.101.44

As reported before, there is no return or exception... it just hangs when doing an await and following the sample code from the AWS SDKs (high-level APIs, .net):
https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpu-upload-object.html
