### ISSUE TITLE
UploadDirectoryAsync - delete local file after upload

### ISSUE THREAD

**Issue by hashitha** [aws/aws-sdk-net#165]
Feature request to delete file after upload

**Comment by normj** [comment]
I'm leery of the SDK being in charge of deleting local files when it seems like a simple thing for the client application to take care of when it knows for sure when to delete the files. Can you give a better reason why you would want that logic in UploadDirectoryAsync?

**Comment by hashitha** [comment]
The only reason I asked for this is because I can't seem to find a way to detect which files were uploaded and which ones failed. for e.g. when the internet drops after a few files have uploaded.

**Comment by PavelSafronov** [comment]
At the moment, there is no simple way to detect when the SDK has uploaded a particular item in a directory, but we are thinking of adding a progress callback that would be called when a file has been successfully uploaded to S3. That should allow you to delete the files.

**Comment by hashitha** [comment]
Thanks that would be great if you can please add this to uploadFileRequest as well. I tried deleting the file at the progress by checking if sent bytes == total bytes but it looks like the file is still open at this stage so i get error file open by other application.

**Comment by PavelSafronov** [comment]
Glad to hear that this approach will work for your case.
For uploading an individual file, you should be able to delete the file once the upload method returns.

**Comment by jimfl** [comment]
Added to https://github.com/aws/aws-sdk-net/blob/master/FEATURE_REQUESTS.md
