### ISSUE TITLE
Mismatch between SDK and SDK's documentation for S3

### ISSUE THREAD

**Issue by ciceroneves** [aws/aws-sdk-net#1653]
## Description
In AWS SDK .NET documentation it states the AmazonS3Config has the property name ConnectionLimit which inherited from Amazon.Runtime.ClientConfig
When I try to set this value in my project using the lastest version of the SDK, the compiler says that this property does not exist

Link for documentation https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/S3/TS3Config.html

## Reproduction Steps
Create a .net standard project
Add the AWSSDK.S3 nuget package (version 3.3.111.20)
Try to instantiate an AmazonS3Config object and set the ConnectionLimit property
``` C#
new AmazonS3Config
{
    ConnectionLimit = 42
});
```

### Logs
N/A

### Environment

* SDK Version: 3.3.111.20
* Package Version: 3.3.111.20
* OS Info: Windows 10
* Build Environment Visual Studio
* Targeted .NET Platform:  netstandard2.0

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Looks like ConnectionLimit is only available for .NET Framework as indicated by code https://github.com/aws/aws-sdk-net/blob/7c88eeceb52869892adb1fe50c3f06c8f1a6b126/sdk/src/Core/Amazon.Runtime/_bcl/ClientConfig.cs#L170. However, documentation needs to properly indicate that it is framework specific. Hence added `doc-apireference` label.
