### ISSUE TITLE
CodeGuru profiler

### ISSUE THREAD

**Issue by PaulDMendoza** [aws/aws-sdk-net#1654]
Is CodeGuru profiler support for .net core on the roadmap? I really need this. 

https://docs.aws.amazon.com/codeguru/latest/profiler-ug/what-is-codeguru-profiler.html

**Comment by NGL321** [comment]
Hey @PaulDMendoza,

Thanks for reaching out. CodeGuru Profiler is indeed supported for .NET Core. If you look [here](https://github.com/aws/aws-sdk-net/tree/master/sdk/src/Services/CodeGuruProfiler), you will see there is a `.csproj` file for .NET Standard (this means it supports both .NET Framework and .NET Core).

If you are having a problem using that service with .NET Core, please consider submitting a separate bug report. If you do, please utilize the issue template so we can get all information needed to triage your bug.


Cheers!

😸 😷
