### ISSUE TITLE
SNS Message class does not handle Message Attributes when reading SQS SNS Message.

### ISSUE THREAD

**Issue by shoter** [aws/aws-sdk-net#1655]
## Description

When using `AmazonSimpleNotificationService.Util.Message.ParseMessage(messageBody)` we are creating an object that in theory should represent all information that we send with `PublishRequest` to the SNS.
When using `MessageAttributes` inside `PublishRequest` we are unable to retrieve them with `AmazonSimpleNotificationService.Util.Message` type. It does not contain any kind of field/property that would let us access this data.
Fix to this situation would be to create Property `MessageAttributes` inside `Message` type that would be parsed from JSON.

Message attributes are also unobtainable from the SQS message I received. They are inside SQS message body.

## Reproduction Steps
Create SNS Message with `MessageAttributes` inside `PublishRequest` and read it using `AmazonSimpleNotificationService.Util.Message.ParseMessage(messageBody)` - you will not be able to access message attributes through this type.

### Environment
* AWSSDK.SimpleNotificationService: 3.3.101.192
* AWSSDK.SQS: 3.3.103.7
* OS Info: Windows 10
* Build Environment Visual Studio
* Targeted .NET Platform:  .NET Core

## Resolution
- [x] :wave: I can implement a fix for this problem myself after this issue will be triaged.

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @shoter,

Thanks for posting the issue.

As per [Amazon SNS message](https://docs.aws.amazon.com/sns/latest/dg/sns-message-attributes.html) documentation, 
```
Message attributes are optional and separate from—but are sent together with—the message body. 
```

To use message attributes with Amazon SQS endpoints, there are reported solutions that setting Raw Message Delivery to True for subscription attribute, would enable message to have Message Attributes and separate message content. Please give it a try and let me know if it works.

Thanks,
Ashish

**Comment by nestor2878** [comment]
Since the documentation does state that `Message attributes are optional and separate from—but are sent together with—the message body`, perhaps a separate utility should exist to parse out the message attributes? 

Here's an example json of a message incoming (this is for an HTTP subscription)

Example JSON:

```
 {
   "Type" : "Notification",
   "MessageId" : "aba1adaa-6fb8-5ab8-8d72-f7bae050b969",
   "TopicArn" : "xxxxxx",
   "Message" : "\"Hello how are you\"",
   "Timestamp" : "2021-11-18T17:30:16.976Z",
   "SignatureVersion" : "1",
   "Signature" : "xxxxxx",
   "SigningCertURL" : "xxxxxx,
   "UnsubscribeURL" : "xxxxxx",
   "MessageAttributes" : {
     "MyAttribute" : {"Type":"String","Value":"MyValue"}
   }
 }
```

I'm currently manually parsing them out myself.
