### ISSUE TITLE
VisualStudio CloudFormation template editor shows invalid key for S3::Bucket

### ISSUE THREAD

**Issue by sliedig** [aws/aws-sdk-net#166]
Hello,

looks like the Visual Studio template editor is showing a invalid key notification for "NotificationConfiguration" property. Thinks it should be "Notification"

![image](https://cloud.githubusercontent.com/assets/597073/6367152/35be153a-bd0a-11e4-97e9-de9b369f6085.png)

Regards,

Steve

**Comment by normj** [comment]
Thanks for pointing this out. I have update the schema for the editor which you should see the next time you restart Visual Studio.
