### ISSUE TITLE
Update S3Region class to include Africa (af-south-1)

### ISSUE THREAD

**Issue by jc1001** [aws/aws-sdk-net#1664]
## Description
The current `S3Region` class in the S3 SDK does not inlude the Africa (af-south-1) region.

Current S3Region class:
https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/S3/TS3Region.html
List of S3 endpoints:
https://docs.aws.amazon.com/general/latest/gr/s3.html

### Environment
* Package Version: 3.3.111.29 (AWSSDK.S3)
* OS Info: Windows 10
* Build Environment: Visual Studio 2019
* Targeted .NET Platform:  4.7.1
---

This is a :bug: bug-report

**Comment by NGL321** [comment]
I can confirm this is missing. I will submit a fix and note here.

😸 😷

**Comment by jc1001** [comment]
Perfect - thank you!

**Comment by SrutiG** [comment]
As of AWSSDK.S3 v3.3.111.37 S3Region should include the af-south-1 region

**Comment by NGL321** [comment]
Cloaing because of resolved status!

@jc1001 if you are still having issues post-`v3.3.111.37` feel free to reopen this issue
