### ISSUE TITLE
S3 GetObjectAsync doesn't returns response and making the application to wait

### ISSUE THREAD

**Issue by srinivas-baipothu** [aws/aws-sdk-net#1667]
I am trying to fetch files from S3 in a dotnet core application as below. It was working fine till yesterday. But after yesterday it was not able to fetch files and making the application to wait at the line "return S3Client.GetObjectAsync". When I ran the below code today. It fetched the first file and for the 2nd file it got stuck at GetObjectAsync without throwing any error and waited for the response almost 5hrs and terminated the application to re-run. On re-run it was the same story.

Can anyone help me in understanding the issue and fix this?
``` c#
private AmazonS3Client S3Client;

#region Constructor

public S3Helper()
{
    this.S3Client = new AmazonS3Client(new AmazonS3Config { Timeout=TimeSpan.FromSeconds(60) });
}

#endregion Constructor


public GetObjectResponse GetObject(bool isDebug, string key)
{
    int retry = 1;
    while (retry <= MAX_RETRY_COUNT)
    {
        try
        {
            //var s3C = new AmazonS3Client();
            GetObjectRequest request = new GetObjectRequest { BucketName = S3_BUCKET, Key = key };
            return S3Client.GetObjectAsync(request).Result;
            //Task<GetObjectResponse> getObjectTask = S3Client.GetObjectAsync(request);
            //getObjectTask.Wait();
            //if (isDebug) Console.WriteLine($"Fetched the file: {key} from S3");
            //return getObjectTask.Result;
        }
        catch (Exception ex)
        {
            if (retry == MAX_RETRY_COUNT)
            {
                Console.WriteLine($"An error occurred while fetching the object:{key} from S3. Details: {ex.Message}. StackTrace:{ex.StackTrace}");
                // Need to Get confirmation whether to throw error as it stops the whole process
                throw ex;
            }

            retry++;
        }
    }

    return null;
}
```

**Comment by ashishdhingra** [comment]
Hi @srinivas-baipothu,

Please provide more details in the following format:

**Description**

**Reproduction Steps**

**Logs**

**Environment**
Package Version:
OS Info:
Build Environment:
Targeted .NET Platform:


This would help troubleshoot the issue.

Thanks,
Ashish
