### ISSUE TITLE
Unable to create bucket replication with V1 config to replicate all objects with latest package versions

### ISSUE THREAD

**Issue by SDW-23** [aws/aws-sdk-net#1668]
## Description
Upgraded the Amazon Core and S3 NuGet packages to the latest versions.
**Expected behaviour**: Able to create a bucket replication that replicates all the objects in the bucket (no prefix), using the V1 configuration (no Filter property).
**Current behaviour**: When calling the PutBucketReplication method, the following exception is thrown:
The XML you provided was not well-formed or did not validate against our published schema.
The remote server returned an error: (400) Bad Request.

If I revert back to the previous versions that were used, then it works as expected.

## Reproduction Steps
Previous package versions where it worked:
AWSSDK.Core: 3.3.23.1
AWSSDK.S3: 3.3.18.3

I have made use of similar code to what is in the dev guide for C# to reproduce the issue in the attached zipped sample app: https://docs.aws.amazon.com/AmazonS3/latest/dev/replication-walkthrough1.html
[AWS S3 Bucket Replication.zip](https://github.com/aws/aws-sdk-net/files/4988947/AWS.S3.Bucket.Replication.zip)

Stack Trace:
[Replication StackTrace.txt](https://github.com/aws/aws-sdk-net/files/4988661/Replication.StackTrace.txt)

According to the documentation, you should be able to replicate all objects in a bucket and that the V1 configuration is still supported:
https://docs.aws.amazon.com/AmazonS3/latest/dev/replication-how-setup.html
https://docs.aws.amazon.com/AmazonS3/latest/dev/replication-add-config.html#replication-config-example-configs
https://docs.aws.amazon.com/AmazonS3/latest/dev/replication-add-config.html#replication-backward-compat-considerations

I also tried to use the V2 config to replicate all the objects in the bucket and the same exception was thrown.

I'm not sure if there is perhaps something small that I am missing, but it seems like there might be an issue.

### Environment
* Package Version: 3.3.111.30 (S3) and 3.3.107.28 (Core)
* OS Info: Windows 10
* Build Environment: Visual Studio 2019
* Targeted .NET Platform:  4.7.1

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
This might be related to existing issue https://github.com/aws/aws-tools-for-powershell/issues/176
