### ISSUE TITLE
S3 GetObject hangs on the 51st or 98th file in a folder

### ISSUE THREAD

**Issue by rbluff** [aws/aws-sdk-net#1669]
## Description
I am iterating through a folder (ie. a prefix) containing 100 files, and calling AmazonS3Client.GetObject() on each key. Sometimes the call to GetObject() fails to return on the 51st file and sometimes on the 98th file.

## Reproduction Steps
Using Cyberduck, create a folder inside the bucket and upload 100 files. Update the appropriate settings inside the S3Test class of the test project and run the console app. 

### Environment

* SDK Version: aws-sdk-v3
* Package Version: Core 3.3.107.29, S3 3.3.111.31
* OS Info: Windows 10
* Build Environment Visual Studio 2017
* Targeted .NET Platform:  Framework 4.7.2

![Console screenshot](https://user-images.githubusercontent.com/25833714/88802361-4f3c6080-d1ee-11ea-8da7-0d6454d1052b.png)
[S3Test.zip](https://github.com/aws/aws-sdk-net/files/4994928/S3Test.zip)
[100 Files.zip](https://github.com/aws/aws-sdk-net/files/4994943/100.Files.zip)

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @rbluff, 

Thanks for reporting the issue. From initial test, this appears to be a bug where the _AmazonS3Client.GetObject()_ gets stuck after fetching a number of objects continuosly. I will pass on the information to developer for further investigation.

Thanks,
Ashish

**Comment by pixelnix** [comment]
Any update on this? This problem seems easily reproducible, and is killing some of our internal processes.

**Comment by pixelnix** [comment]
One thing to note is that GetObjectResponse is disposable; if you dispose of it either explicitly or implicitly in a using block, does this behave any differently?

**Comment by ashishdhingra** [comment]
Hi @pixelnix, 

Thanks for pointing out and you are right, the `GetObjectResponse()` is Disposable. The code shared by @rbluff doesn't dispose the object in S3Helper.GetFileProperties(). In documentation [Get an object Using the AWS SDK for .NET](https://docs.aws.amazon.com/AmazonS3/latest/dev/RetrievingObjectUsingNetSDK.html), it is mentioned that:
```
When you download an object, you get all of the object's metadata and a stream from which to read the contents. You should read the content of the stream as quickly as possible because the data is streamed directly from Amazon S3 and your network connection will remain open until you read all the data or close the input stream.
```

So it appears that not disposing off the GetObjectResponse object appears to cause S3 connection limit to reach, hence the application hangs randomly after fetching number of files. Making the following simple adjustment to use `using` block solves the issue and program executes to completion:
```C#
private FileProperties GetFileProperties(string filePath)
{
	using (var helper = new S3Helper(_context))
	{
		using (var objectResponse = helper.GetObjectResponse(filePath))
		{
			//var objectResponse = helper.GetObjectResponseAsync(filePath).GetAwaiter().GetResult();

			var properties = new FileProperties()
			{
				Size = objectResponse.ContentLength,
				CreatedUtc = objectResponse.LastModified, // objects are immutable, so the created date == modified date
				ModifiedUtc = objectResponse.LastModified
			};

			return properties;
		}
	}
}
```

@rbluff Please make the above code change as suggested, it would run to completion. Also, note that `AmazonS3Client.GetObject()` gets complete object along with metadata. In your example, you don't appear to consume the object content. Please see if you would want to use [`AmazonS3Client.GetObjectMetadata()`](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/index.html) method instead.

Kindly confirm is this issue could be closed.

Thanks,
Ashish
