### ISSUE TITLE
Unable To Access System.DirectoryServices method from lambda function

### ISSUE THREAD

**Issue by jithinjudepaule** [aws/aws-sdk-net#1670]
When I try to access the user details using the DirectorySearcher Type from a lambda function, it throws **PlatformNotSupportedException** as Lambda runs on Linux containers and it does not support it.

**Proposal**
If we can give the user permission to launch lambda in a container of user's choice, this issue can be tackled as System.Directory services are supported by default. I tried to create a workaround for the above issue by using Novell.Directory.Ldap.NETStandard nuget package, but it did not give the required results ( https://www.nuget.org/packages/Novell.Directory.Ldap.NETStandard/ )

It would be great if AWS brings this feature to choose the environment on which the Lambda can run, as that would make the life of platform dependent programmers' life easy

**Comment by BClev** [comment]
PowerShell 7.1 supports this (requires .Net Core 5), and so AWS would need to make Powershell 7.1 lambda available to implement it (currently is only 7.0.0).

**Comment by ashishdhingra** [comment]
> PowerShell 7.1 supports this (requires .Net Core 5), and so AWS would need to make Powershell 7.1 lambda available to implement it (currently it is only 7.0.0).

Needs review with the team.

**Comment by erosen03** [comment]
The issue is that Microsoft has not ported `System.DirectoryServices` to Linux or MacOS .Net framework runtimes, which is why you can't use it from within a Lambda function. And apparently, Microsoft has no plans to do so. However, Microsoft has implemented `System.DirectoryServices.Protocols` cross-platform. More details are available in the [dotnet runtime GitHub repo](https://github.com/dotnet/runtime/issues/23944).

**Comment by ashishdhingra** [comment]
> The issue is that Microsoft has not ported `System.DirectoryServices` to Linux or MacOS .Net framework runtimes, which is why you can't use it from within a Lambda function. And apparently, Microsoft has no plans to do so. However, Microsoft has implemented `System.DirectoryServices.Protocols` cross-platform. More details are available in the [dotnet runtime GitHub repo](https://github.com/dotnet/runtime/issues/23944).

@jithinjudepaule Please see if guidance provided by @erosen03 explains why you are unable to access `System.DirectoryServices` in Lambda and confirm if this issue could be closed.

**Comment by DreamCeptor** [comment]
this issue I am facing .Net core 6
