### ISSUE TITLE
Help with Elastic Search - Role based

### ISSUE THREAD

**Issue by sudhadurhakula** [aws/aws-sdk-net#1679]
Hello

   I have ElasticSearch Domain which is accessible to certain ROLE 
   I need to access that Domain from SDK  ElasticSearch.NET   and keep erroring  saying...

{Unsuccessful (403) low level call on POST: /employees/_bulk}

  var esendpoint= "https://search-MyEndpoint-.us-east-1.es.amazonaws.com";
  var settings = new ConnectionSettings(new Uri(esendpoint)).DefaultIndex("employees");    
            var esClient = new ElasticClient(settings);
            var response= await esClient.SearchAsync<Employee>(s => s.Query(q => q.MatchAll()));

When I change the ElasticSearch permissions to accesible public, I am able to access.  But  I want only certain Role to access that. 
My Ec2 instance  which runs my code   has the   same Role.

**Comment by ashishdhingra** [comment]
Hi @sudhadurhakula,

The link [Creating and Managing Amazon Elasticsearch Service Domains](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-createupdatedomains.html) gives some overview of Amazon ElasticSearch domain. It also has section for Configuring Access Policies. Hopefully it helps on how to configure the ES service.

Thanks,
Ashish

**Comment by sudhadurhakula** [comment]
HI I don't need Configuring Access policies. I need  .NET code to access it, when Domain is Role based access Level. Which has access to certain Role.

**Comment by sudhadurhakula** [comment]
My Question again is....

My ElasticSearchDomain is provided by Adminstrators  Runs in   Dex-XXXXX   Role,
I have access to Ec2 instance which also accessible to same Role.  Now  I need to access the  Elastic Seach Domain... 
 What Do I need?  I was reading over it was saying I need to Sign the Request to access  Elastic Search Domain.

How do I get API keys?? How to access ElasticSearch Domain?

**Comment by ashishdhingra** [comment]
Hi @sudhadurhakula,

Please confirm which package you are using for ElasticSearch. Is this 3rd party package [ElasticSearch.NET](https://github.com/bcuff/elasticsearch-net-aws)?

The article [How to Control Access to Your Amazon Elasticsearch Service Domain](https://aws.amazon.com/blogs/security/how-to-control-access-to-your-amazon-elasticsearch-service-domain/) has some information on how to sign ElasticSearch request, however, the example is in Java.

Thanks,
Ashish
