### ISSUE TITLE
S3 PutObjectAsync fails when I published to AWS lambda through Visual Studio 2019 (.net core 3.1). But is working with Mock Lambda Test tool.

### ISSUE THREAD

**Issue by rahul-JFL** [aws/aws-sdk-net#1681]
## The Question
I am unable to upload a plain text file to my S3 bucket with 'putobjectAsync' method in one of my lambda functions .
My lambda is working in below three step
1) reading json file from S3
2) Checks and validated json data and logged into RDS mysql
3) read correct data from RDS mysql in order to create a new text/csv file on S3.

Above all steps are working with the Mock Lambda test tool. but it is not working,when i am uploading my publish zip file into Lambda function.
--> My UploadFile function code is here

      public async Task<string> UploadFilet()
        {
            S3Client = new AmazonS3Client( RegionEndpoint.APSouth1);  
            return await Task.Run(() =>
            {
                for (int i = 0; i < 6; i++)
                {
                    PutObjectRequest request = new PutObjectRequest
                    {
                        BucketName = bucketName,
                        Key = "AWS  TestFile1.txt",
                        ContentBody = "testing upload file.",
                        ContentType = "text/plain",
                        StorageClass = S3StorageClass.Standard,
                        CannedACL = S3CannedACL.NoACL
                    };
                    S3Client.PutObjectAsync(request);
                    Task.Delay(TimeSpan.FromSeconds(1)).Wait();
                }
                return "Put Object Completed";
            }).ConfigureAwait(false);
        }

### Environment

* SDK Version: AWSSDK.Core 3.3.107.39
* Package Version: 1.1.0
* OS Info:  Windows 10 
* Build Environment:  Visual Studio 
* Targeted .NET Platform:  VS2019(.net core 3.1)

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @rahul-JFL,

Thanks for posting the guidance question. Please share logs and stack trace (if any) from CloudWatch. Also, it would be helpful if you could add logging statements (using ILambdaContext.Logger) to the above code to trace the execution.

The problem if see in the above code is that await is used to execute _Task.Run()_ which executes loop in the background thread and then use _S3Client.PutObjectAsync()_ which is not awaited. It is quite possible that the background thread for S3Client.PutObjectAsync() are paused (since these are not awaited) when Lambda function returns. Lambda Test Tool is just a simulation of code execution, it is different from the actual Lambda execution environment.

Thanks,
Ashish

**Comment by rahul-JFL** [comment]
Thanks Ashish for your reply.

I will definitely share required logs and trace with you.
If you don’t mine, can we have sort call discussion over this issue. I can explain you more in details.

Thanks & Regards,
Rahul Gupta|+91-9599039322

**Comment by ashishdhingra** [comment]
Hi @rahul-JFL, 

GitHub is the effective way to communicate about issues. Please post the logs (after adding logging statements), code snippet (if different from above) and stack trace for any failures here on GitHub.

Also try using await keyword before S3Client.PutObjectAsync(request) call like below and see if it helps:

```C#
await S3Client.PutObjectAsync(request);
```

Thanks,
Ashish

**Comment by rahul-JFL** [comment]
Thanks Ashis,
My lambda Execution logs is here ( LambdaLogger.Log)
----------------------------------------------------------------------------------
START RequestId: 02906c10-9b66-495e-baeb-27683602d25c Version: $LATEST
fileName: DPI66639_20200819120927.csv
fileContent :1021,20200819,1000,D834,000000000010000492,C009,0.1,KGS,
Call-Class:UploadFileS3;Function:UploadIndent
bucketName: indentbucket/Post
END RequestId: 02906c10-9b66-495e-baeb-27683602d25c
REPORT RequestId: 02906c10-9b66-495e-baeb-27683602d25c	Duration: 90090.23 ms	Billed Duration: 90000 ms	Memory Size: 640 MB	Max Memory Used: 112 MB	Init Duration: 160.06 ms	
2020-08-19T12:10:55.064Z 02906c10-9b66-495e-baeb-27683602d25c Task timed out after 90.09 seconds
--------------------------------------------------------------------------------------------------------------------
                                                                 Parent Function
--------------------------------------------------------------------------------------------------------------------
  public String PostIndentFile(String StoreId, DataTable dt)
        {
            try
            {
                string fileName = string.Format("**_{0:yyyyMMddhhmmss}.csv", DateTime.Now);
                fileName = fileName.Replace("**", StoreId);
                LambdaLogger.Log("fileName: " + fileName);
                //String fileName = Extennsions.GetFileName(StoreId);
                String input = GetDataForFile(dt);
                LambdaLogger.Log("fileContent :" + input.ToString());
                UploadFileS3 oUploadFileS3 = new UploadFileS3();
                var result = oUploadFileS3.UploadIndent(input, fileName);
                LambdaLogger.Log("Result1: " + result);
                return result;
            }
            catch (Exception ex)
            {
                return ex.Message.ToString();
            }
        }
--------------------------------------------------------------------------------------------------------------------
                                                                 Child Function
--------------------------------------------------------------------------------------------------------------------
  public async Task<string> UploadFileToS3Bucket(String input, String fileName)
        {
            S3 = new AmazonS3Client(awsAccessKeyId, awsSecretAccessKey, RegionEndpoint.APSouth1);
            LambdaLogger.Log("RegionEndPoint:" + RegionEndpoint.APEast1);
            LambdaLogger.Log("bucketName:" + bucketName);
            LambdaLogger.Log("fileName:" + fileName);
            LambdaLogger.Log("input:" + input);
            return await Task.Run(() =>
            {
                for (int i = 0; i < 6; i++)
                {
                    PutObjectRequest request = new PutObjectRequest
                    {
                        BucketName = bucketName,
                        Key = fileName,
                        ContentBody = input,
                        ContentType = "text/csv",
                        StorageClass = S3StorageClass.Standard,
                        CannedACL = S3CannedACL.NoACL
                    };
                    S3.PutObjectAsync(request);
                    LambdaLogger.Log("PutObjectAsync Request:" + request);
                    Task.Delay(TimeSpan.FromSeconds(1)).Wait();
                }
                LambdaLogger.Log("Put Object Completed");
                return "Success";
            }).ConfigureAwait(false);
        }

**Comment by ashishdhingra** [comment]
Hi @rahul-JFL, 

Thanks for your inputs. I made some minor changes to your code (notice the proper use of await keyword specifically) and was able to successfully upload file to S3 inside AWS Lambda:

```C#
public async Task<string> FunctionHandler(string input, ILambdaContext context)
{
    string returnMessage = await UploadFileToS3Bucket(fileContent, fileName);
    return returnMessage;
}

public async Task<string> UploadFileToS3Bucket(String input, String fileName)
{
    using (AmazonS3Client s3Client = new AmazonS3Client(awsAccessKeyId, awsSecretAccessKey, awsSessionToken, region))
    {
        LambdaLogger.Log("RegionEndPoint:" + region);
        LambdaLogger.Log("bucketName:" + bucketName);
        LambdaLogger.Log("fileName:" + fileName);
        LambdaLogger.Log("input:" + input);

        return await Task.Run(async () =>
        {
            for (int i = 0; i < 6; i++)
            {
                PutObjectRequest request = new PutObjectRequest
                {
                    BucketName = bucketName,
                    Key = fileName,
                    ContentBody = input,
                    ContentType = "text/csv",
                    StorageClass = S3StorageClass.Standard,
                    CannedACL = S3CannedACL.NoACL
                };
                await s3Client.PutObjectAsync(request);
                LambdaLogger.Log("PutObjectAsync Request:" + request);
                Task.Delay(TimeSpan.FromSeconds(1)).Wait();
            }

            LambdaLogger.Log("Put Object Completed");
            return "Success";
        }).ConfigureAwait(false);
    }
}
```

**Logs:**
```
START RequestId: 64616574-6b98-48a3-875c-7e0a145be654 Version: $LATEST
RegionEndPoint:Asia Pacific (Mumbai) (ap-south-1)bucketName:tests3bucket-1681fileName:DPI66639_20200819120927.csvinput:1021,20200819,1000,D834,000000000010000492,C009,0.1,KGS,PutObjectAsync Request:Amazon.S3.Model.PutObjectRequestPutObjectAsync Request:Amazon.S3.Model.PutObjectRequestPutObjectAsync Request:Amazon.S3.Model.PutObjectRequestPutObjectAsync Request:Amazon.S3.Model.PutObjectRequestPutObjectAsync Request:Amazon.S3.Model.PutObjectRequestPutObjectAsync Request:Amazon.S3.Model.PutObjectRequestPut Object CompletedEND RequestId: 64616574-6b98-48a3-875c-7e0a145be654
REPORT RequestId: 64616574-6b98-48a3-875c-7e0a145be654	Duration: 10242.09 ms	Billed Duration: 10300 ms	Memory Size: 256 MB	Max Memory Used: 104 MB	
```

I also had to add appropriate role to AWS Lambda so that it's able to upload file to S3.

Please let me know if this helps.

Thanks,
Ashish

**Comment by rahul-JFL** [comment]
Thanks a lot! Ashish.

Is ‘awsSessionToken’ is a mandatory parameter in function UploadFileToS3Bucket? Because without this, issue is same.
If yes, please help me to generate ‘SessionToken’ code in my Lambda Function.
For your information, I am not using  ‘Amazon API Gateway’ in my case. My lambda function is getting triggered through ‘Kinesis Firehose’.


Regards,
Rahul Gupta

**Comment by ashishdhingra** [comment]
@rahul-JFL,
AwsSessionToken is not a mandatory token. Please check the permissions and policies. Also modify u you our code to use the await keyword properly since any background threads would be suspended once Lambda function returns.

**Comment by rahul-JFL** [comment]
Yes, I review and checked my permission and policy on my bucket and lambda functions have full rights.
Still I am receiving time-out exception
{"errorMessage":"2020-08-20T15:48:30.712Z 85291954-22b9-45fc-8099-e1bdd2616421 Task timed out after 60.02 seconds"}

FYI file content :”My test text”.

**Comment by ashishdhingra** [comment]
Hi @rahul-JFL, 

Could you confirm if you modified your code to properly use "**await**" keyword? As mentioned earlier, background threads could be suspended if the Lambda returns the invocation call. In your code, the call **s3Client.PutObjectAsync(request)** needs to awaited or executed synchronously. 
In other words:

```C#
await s3Client.PutObjectAsync(request);
```

or

```C#
var putItemResponse = s3Client.PutObjectAsync(request).Result;
```

Using the modified code snippet shared with you, I'm unable to reproduce the issue.

Thanks,
Ashish

**Comment by rahul-JFL** [comment]
Yes, I tried both Async as well as synchronous. Please find attached my both function class and exception screen shot.
![ScreenCapture](https://user-images.githubusercontent.com/46673071/90803753-dc2e9180-e336-11ea-8853-4787206415a4.JPG)
[Async-Function.txt](https://github.com/aws/aws-sdk-net/files/5104479/Async-Function.txt)
[synchronously-Function.txt](https://github.com/aws/aws-sdk-net/files/5104480/synchronously-Function.txt)

@ashishdhingra : I really appreciate your effort and support but for me, this is show stopper task . Please help me.

**Comment by ashishdhingra** [comment]
Hi @rahul-JFL,

In your code, could you please change the following:

```C#
private string bucketName = "indentbucket";
...
string returnMessage = UploadFileToS3Bucket(input, "Post/MyText.csv");
``` 

Refer to [Bucket restrictions and limitations](https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html) and [Object key and metadata](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html) for the naming guidelines.

Thanks,
Ashish

**Comment by rahul-JFL** [comment]
My VPC routes table 
![image](https://user-images.githubusercontent.com/46673071/91027166-5e5dd500-e619-11ea-8bdf-63d58cad6be1.png)

And Subnet Associations

**Comment by rahul-JFL** [comment]
My Subnet Associations
![image](https://user-images.githubusercontent.com/46673071/91027378-a5e46100-e619-11ea-9ee6-311acf26aeac.png)

**Comment by ashishdhingra** [comment]
Hi @rahul-JFL,

Good morning.

As we figured out earlier, Lambda code is correct and working, so the only thing left is to figure out the proper service level configuration within VPC. I would recommend going through service specific documentation which could provide some reference to VPC specific scenarios. Following documentation links might be helpful for your scenario:

- [Example Bucket Policies for VPC Endpoints for Amazon S3](https://docs.aws.amazon.com/AmazonS3/latest/dev/example-bucket-policies-vpc-endpoint.html)

- [Configuring a Lambda function to access resources in a VPC](https://docs.aws.amazon.com/lambda/latest/dg/configuration-vpc.html)

For any other support related to VPC, please directly contact service specific support to get expertise guidance related to service.

Please let me know if any more guidance for .NET SDK related Lambda code is required and if this issue could be closed.

Thanks,
Ashish

**Comment by rahul-JFL** [comment]
Thanks @Ashish

Let me check and close this issue soon.
I have another question , how can I pass a csv string to my lambda function as an input parameter.

Actually, my scenario is that
Triggered (if any .csv file pushed) a lambda function then a lambda function will  read a csv file from S3- bucket and data saved into RDS.


Thanks
Rahul Gupta

**Comment by rahul-JFL** [comment]
Thanks @ashishdhingra 


Let me check and close this issue soon.
I have another question , how can I pass a csv string to my lambda function as an input parameter.
 
Actually, my scenario is that 
Triggered (if any .csv file pushed) a lambda function then a lambda function will  read a csv file from S3- bucket and data saved into RDS.

[JFLGetSTN.txt](https://github.com/aws/aws-sdk-net/files/5119595/JFLGetSTN.txt)

Thanks
Rahul Gupta

**Comment by Ashish** [comment]
I think you guys are tagging wrong Ashish

**Comment by ashishdhingra** [comment]
Hi @rahul-JFL,

There is one good article [Tutorial: Importing data into Amazon Pinpoint from external sources](https://docs.aws.amazon.com/pinpoint/latest/developerguide/tutorials-importing-data.html) which closely resembles you scenarios. It basically involves setting up events on S3 bucket whenever a CSV file is pushed to the bucket which later triggers lambda function. Lambda function would receive event data in a specified JSON format which you can use to fetch file from S3, parse CSV content and do further processing.

There are many such code samples online if you look out for it in a search engine.

Kindly note that the above article is just provided as a guidance source and you should develop and fully test your code before production implementation.

Let me know if this helps.

Thanks,
Ashish

**Comment by Ashish** [comment]
I think you are mentioning wrong Ashish

**Comment by rahul-JFL** [comment]
Hi Ashish,

Lambda Function to be invoked or triggered by S3(csv file upload). My query is here now, how do i get csv file data in function, because i tried with 'String input' parameter.but it is not working.

Thanks & Regards;
Rahul Gupta

**Comment by ashishdhingra** [comment]
https://github.com/aws/aws-lambda-dotnet/issues/723

**Comment by ashishdhingra** [comment]
Hi @rahul-JFL,

I notice that the new guidance issue https://github.com/aws/aws-lambda-dotnet/issues/723 was created for your question on Lambda triggered via CSV upload in S3 bucket. Hence I will close this issue for now since the original issue is resolved and can continue on CSV guidance under new issue.

Thanks,
Ashish

**Comment by rahul-JFL** [comment]
Yes Sure, Thanks Ashish.
