### ISSUE TITLE
S3 select on a public S3 object throws access denied error

### ISSUE THREAD

**Issue by JoshyAbraham** [aws/aws-sdk-net#1687]
when running S3 select using .net SDK , getting access denied error on a public S3 object when no credentials passed on initializing  AmazonS3Client.  based on the AWS .net SDK document, https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/S3/TS3Client.html  AWS SDK does not allow to initialize  AmazonS3Client without a credential. 

in this case, how to run an S3 select on a public S3 object.
AmazonS3Client  initialized with an empty credential allows to read files from public S3 objects, but fails when running S3 Select.

code example 
var Client = new AmazonS3Client("","",RegionEndpoint.USWest2);
Task<SelectObjectContentResponse> ts= Client.SelectObjectContentAsync(new SelectObjectContentRequest() ...

**Comment by ashishdhingra** [comment]
Hi @JoshyAbraham,

Good morning.

The documentation [Selecting content from objects](https://docs.aws.amazon.com/AmazonS3/latest/dev/selecting-content-from-objects.html) lists the requirements and limits for selecting content from S3 objects. One of the requirements is that the user must have s3:GetObject permission on the object. 

Also, you might see the following warning when you access S3 bucket via AWS console:

```
The block public access settings turned on for this account prevent granting public access.
```

May be this is blocking public access to S3 bucket. Please let me know if this helps.

Thanks,
Ashish

**Comment by JoshyAbraham** [comment]
thanks  Ashish,  i found the following guideline in S3 documentation. this explain why i am not able to run S3 Select on public S3 objects.

https://docs.aws.amazon.com/AmazonS3/latest/API/API_SelectObjectContent.html
**"Amazon S3 Select does not support anonymous access"**

**Comment by ashishdhingra** [comment]
Hi @JoshyAbraham, 

Thanks for confirming. Looks like the anonymous access is blocked at the service level, not the .NET SDK level. this might be due some design/security constraints that we are not aware of. Hence, closing this issue. 

Thanks,
Ashish
