### ISSUE TITLE
Port number will be ignored for temporary redirects

### ISSUE THREAD

**Issue by DetlefGolze** [aws/aws-sdk-net#1689]
## Description
If AllowAutoRedirects is false, the redirect handler does not honor the port number which is provided in the redirected location.
Thus redirection fails unless the default port is used.

## Reproduction Steps
Force an S3 server to return a temporary redirect with a non-default port number.

### Environment

* SDK Version: 3.3.110.11
* Package Version: 
* OS Info: Windows 10
* Build Environment: VSCode + Terminal dotnet
* Targeted .NET Platform:  .NET Core 3.1

## Resolution
I will provide a fix.

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
PR https://github.com/aws/aws-sdk-net/pull/1690 merged.
