### ISSUE TITLE
 Cookie is not passed to back-end .Net Application through API Gateway with HTTP Integration

### ISSUE THREAD

**Issue by AZarenin** [aws/aws-sdk-net#1691]
## Description
.Net WEB application deployed to API Gateway with HTTP integration does not receive cookies

## Reproduction Steps
Attached is a vary simple application that demonstrate this issue.
[CookieError.zip](https://github.com/aws/aws-sdk-net/files/5144738/CookieError.zip)

### Logs
API Gateway passes HTTP request into the application placing the cookies into the JSON field **"cookies"** while the Lambda entry point **Amazon.Lambda.AspNetCoreServer.APIGatewayHttpApiV2ProxyFunction** is looking for the field **"cookie"** to pass cookies to the application pipeline:

{
  "version": "2.0",
  "routeKey": "$default",
  "rawPath": "/",
  "rawQueryString": "",
  "cookies": ["MyCookie=some-value"], 
  "headers": {
    "accept": "text/html,application/xhtml\u002Bxml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
    "accept-encoding": "gzip, deflate, br",
    "accept-language": "en-US,en;q=0.9",
    "cache-control": "max-age=0",
    "content-length": "0",
    "host": "x2h9emdh9c.execute-api.us-east-1.amazonaws.com",
    "referer": "https://console.aws.amazon.com/apigateway/main/api-detail?api=x2h9emdh9c\u0026region=us-east-1",
    "sec-fetch-dest": "document",
    "sec-fetch-mode": "navigate",
    "sec-fetch-site": "cross-site",
    "sec-fetch-user": "?1",
    "upgrade-insecure-requests": "1",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36 Edg/85.0.564.41",
    "x-amzn-trace-id": "Root=1-5f48f846-f0e7e7ea497044ab9643734f",
    "x-forwarded-for": "75.2.216.195",
    "x-forwarded-port": "443",
    "x-forwarded-proto": "https"
  },
  "queryStringParameters": null,
  "requestContext": {
    "accountId": "982831078337",
    "apiId": "x2h9emdh9c",
    "authorizer": null,
    "domainName": "x2h9emdh9c.execute-api.us-east-1.amazonaws.com",
    "domainPrefix": "x2h9emdh9c",
    "http": {
      "method": "GET",
      "path": "/",
      "protocol": "HTTP/1.1",
      "sourceIp": "75.2.216.195",
      "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36 Edg/85.0.564.41"
    },
    "requestId": "R-u7GguCoAMESrQ=",
    "routeId": null,
    "routeKey": "$default",
    "stage": "$default",
    "time": "28/Aug/2020:12:27:50 \u002B0000",
    "timeEpoch": 1598617670905
  },
  "body": null,
  "isBase64Encoded": false,
  "stageVariables": null
}

### Environment

* SDK Version: AWSSDK.Core version 3.5.13
* Package Version: Amazon.Lambda.AspNetCoreServer version 5.1.3
* OS Info: Windows 10 
* Build Environment:  Visual Studio 
* Targeted .NET Platform:  .Net Core 3.1

## Resolution

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @AZarenin,

Good afternoon.

While looking at your sample code, looks like you are trying to read the cookie named "Lang" in Index.cshtml.cs. However, in the sample request you provided, there is no cookie named "Lang". Please confirm if you are trying to read value of HTTP header or cookie. Also, it would be helpful if you could provide detailed steps to reproduce the scenario.

Thanks,
Ashish

**Comment by AZarenin** [comment]
That was just a sample log; the application passes "Lang" cookie when you select a flag in the upper right corner and select language other than English.

**Comment by ashishdhingra** [comment]
Hi @AZarenin,

I'm not sure if it would help, as mentioned in the documentation link [Working with AWS Lambda proxy integrations for HTTP APIs](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html), the format 2.0 of API Gateway includes a new cookies field. All cookie headers in the request are combined with commas and added to the cookies field. 

From first glance at the code, it appears to be a bug. I will request developer to have a look at it and provide the inputs.

Thanks,
Ashish

**Comment by AZarenin** [comment]
Hi Ashish,

As was confirmed by my colleague, this is a bug in **Amazon.Lambda.AspNetCoreServer.APIGatewayHttpApiV2ProxyFunction** as it is looking for the field "cookie" in the JSON packet instead of the documented field "cookies". A change to **Amazon.Lambda.AspNetCoreServer.APIGatewayHttpApiV2ProxyFunction** required to make cookies available for .Net application.

**Comment by NGL321** [comment]
Duplicate of https://github.com/aws/aws-lambda-dotnet/issues/713. In progress

**Comment by normj** [comment]
Version 5.1.4 of Amazon.Lambda.AspNetCoreServer has been released with the PR containing the fix.
