### ISSUE TITLE
SQS - Should the AWS4Signer take region from RegionEndpoint before attempting to look at query string 

### ISSUE THREAD

**Issue by joro550** [aws/aws-sdk-net#1692]
## The Question
I was running some SQS code against a local API today and was setting the region endpoint up in a way that is consistent with S3:

```
var sqsClient = new AmazonSQSClient(new AmazonSQSConfig
{
    UseHttp = true,
    
    RegionEndpoint = RegionEndpoint.EUWest1,
    ServiceURL = "http://localhost:4566"
});
```
Because this API was respecting region implementation I was creating a queue via the SDK and attempting to see it in the code (or visa versa) and was seeing 0 queues being returned (but when I created the queue via cli and listed queues form the cli it was working) after some request inspection I saw that the region was actually set to `us-east-1`.

After a bit of digging around in the sdk I found you signer that does this logic:

```
string authenticationRegion = clientConfig.AuthenticationRegion;
if (request != null && request.AuthenticationRegion != null)
    authenticationRegion = request.AuthenticationRegion;

if (!string.IsNullOrEmpty(authenticationRegion))
    return authenticationRegion.ToLowerInvariant();

if (!string.IsNullOrEmpty(clientConfig.ServiceURL))
{
    var parsedRegion = AWSSDKUtils.DetermineRegion(clientConfig.ServiceURL);
    if (!string.IsNullOrEmpty(parsedRegion))
        return parsedRegion.ToLowerInvariant();
}
```

Which makes the correct way to change regions here look like this:

```
var sqsClient = new AmazonSQSClient(new AmazonSQSConfig
{
    UseHttp = true,
    AuthenticationRegion = "eu-west-1", // this is what controls regions here
    RegionEndpoint = RegionEndpoint.EUWest1,
    ServiceURL = "http://localhost:4576"
});
```

I'm wondering whether it would be a sensible idea to do a check on `RegionEndpoint` here as that is what _usually_ changes regions for other clients, be it kinesis or S3 etc. 

### Environment

* SDK Version: 
* Package Version: 3.5.0.7
* OS Info: Windows 10
* Build Environment Visual Studio
* Targeted .NET Platform:  .Net Core 3.1

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @joro550,

Good morning. 

Please advise if you are using community LocalStack emulation. I'm not quite sure if that would cause the issue and how credentials are configured in LocalStack. Based on the logic in [DetermineSigningRegion()](https://github.com/aws/aws-sdk-net/blob/7c88eeceb52869892adb1fe50c3f06c8f1a6b126/sdk/src/Core/Amazon.Runtime/Internal/Auth/AWS4Signer.cs#L537), here is the order in which region information takes precedence:

- IRequest.AlternateEndpoint takes precedence over client config properties.
- AuthenticationRegion
- Region determined from Service URL
- RegionEndpoint

RegionEndpoint would be the fallback case if no preceding sources are able to resolve the region. I will try to reproduce the issue. Could you please share the default configuration in credentials and config files (excluding the sensitive information like secret and access keys) and your application configuration which might have default profile set.

Thanks,
Ashish

**Comment by joro550** [comment]
Hey @ashishdhingra,

Yes I am using the community LocalStack emulation, I guess my confusion came in when the ServiceUrl was returning `us-east-1`, in the local stack instance (in my code) the `AWS4Signer.DetermineSigningRegion` would always fall into the following case unless you have the authentication region (or alternative region which I'm unsure how to set):

```
if (!string.IsNullOrEmpty(clientConfig.ServiceURL))
{
    var parsedRegion = AWSSDKUtils.DetermineRegion(clientConfig.ServiceURL);
    if (!string.IsNullOrEmpty(parsedRegion))
        return parsedRegion.ToLowerInvariant();
}
```
case, if it cannot retrieve a region out of the url it actually defaults to `us-east-1`. It makes sense that Service URL would come first in most cases, but looking at the `AWSSDKUtils.DetermineRegion` implementation:

```
public static string DetermineRegion(string url)
{
    int delimIndex = url.IndexOf("//", StringComparison.Ordinal);
    if (delimIndex >= 0)
        url = url.Substring(delimIndex + 2);

    if (url.EndsWith("/", StringComparison.Ordinal))
        url = url.Substring(0, url.Length - 1);

    int awsIndex = url.IndexOf(".amazonaws.com", StringComparison.Ordinal);
    if (awsIndex < 0)
        return DefaultRegion;

...... more code 
}
```

It looks like it would return `DefaultRegion` which is set to `us-east-1` because we are setting our url to "localhost" (or whatever your docker instance is called).

The confusion came because normally when I'm using localstack I set region endpoint and the service URL and it allows me to connect to the correct region.

I'll try and get a copy of my configuration and credentials and copy them into this issue ASAP, thank you 😄

**Comment by joro550** [comment]
Here is my credentials file with access and secret key taken out:

```
[default]
output=json
region = eu-west-1
aws_access_key_id = 
toolkit_artifact_guid=8e972762-e8e3-47fd-8c0a-8aa9ffc2302b
aws_secret_access_key = 
```

interestingly I don't actually have a configuration file

**Comment by joro550** [comment]
Oh - I have just figured out that there is intrinsic logic within the config object that set the service url to null when region endpoint is provided and visa versa, so this may be an easy answer to say that it _wouldn't_ work in the way I want it to work :smile:

**Comment by ashishdhingra** [comment]
Thanks @joro550 for the input. Could you please paste the perm link to that logic here for reference. Also confirm if we could close this issue.

**Comment by joro550** [comment]
Sure thing, so as a result of my investigation you cannot set the service url and region endpoint to use to connect to localstack because the client config sets service url to null if you set region endpoint and visa versa which you can see [here](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/ClientConfig.cs#L147)

What that means is that you need to set the region you are connecting to via the methods listed (in priority order):
- IRequest.AlternateEndpoint takes precedence over client config properties.
- AuthenticationRegion
- Region determined from Service URL
- RegionEndpoint

You can see that in this method [here](https://github.com/aws/aws-sdk-net/blob/7c88eeceb52869892adb1fe50c3f06c8f1a6b126/sdk/src/Core/Amazon.Runtime/Internal/Auth/AWS4Signer.cs#L537), all though I have suspicions that in the case where you *don't* have `.amazonaws.com` in your ServiceUrl (when set) that it will default to `us-east-1` which you can see in [this](https://github.com/aws/aws-sdk-net/blob/aws-sdk-net-v3.3/sdk/src/Core/Amazon.Util/AWSSDKUtils.cs#L514) logic - which  seems to have changed in master.

Anyway - I confirm that you can close this issue, I'll do it myself with this comment, thank you for your time 😄
