### ISSUE TITLE
GetPreSignedURL() does not generate correct parameter for "x-amz-tagging"

### ISSUE THREAD

**Issue by yyc-github** [aws/aws-sdk-net#1696]
## Description
I try to use pre-signed url with tagging for http PUT but found an issue with the generated url. The parameter "x-amz-tagging" in the url is not placed as a query parameter and it ignores the value I specified.

## Reproduction Steps
Here is my code:
```
            var request = new GetPreSignedUrlRequest
            {
                BucketName = bucket,
                Key = key,
                Verb = HttpVerb.PUT,
                Expires = DateTime.Now.AddMinutes(1)
            };
            string tags = $"EmailSubject=This";
            request.Headers["x-amz-tagging"] = tags;
            var url = S3Client.GetPreSignedURL(request); 
```
I also tried capitalized "X-Amz-Tagging", it doesn't make any difference. Here is generated url from GetPreSignedURL()

"https://s3.ap-southeast-2.amazonaws.com/BUCKET_NAME/file.txt?X-Amz-Expires=60&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AMZ_CREDENTIAL&X-Amz-Date=20200909T020259Z&X-Amz-SignedHeaders=host;x-amz-tagging&X-Amz-Signature=AMZ_SIGNATURE"

### Environment
AWSSDK.S3 version used: 3.3.104.3
Visual Studio version: 2019
Targeted .NET platform: Core 2.1  
OS: Windows 10 Professional
OS Version: 1903

## Resolution
Is there any workaround I could do to fix this issue? Or did I miss anything when I construct the request? Thanks for the help.

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @yyc-github,

Thanks for reporting the issue. This is a known issue and I would discuss this with developer. While I do not have any timeline on when this issue could be fixed, but I will post any updates that I receive from the team.

Thanks,
Ashish

**Comment by AntShep** [comment]
Hi @ashishdhingra!

I have the same problem and I want to clarify some point: 
I can set tags using generated pre-signed URL if I additionally pass the "x-amz-tagging" header on the client side - it works, but I do not want to require the client to send any additional meta information other than the generated URL and the required HTTP method. It would be better to put all required information in the generated URL parameters -> in this case the client can just use the generated URL without any additional obscure knowledge of how to call it. Do you plan to fix this?

Thanks,
Anton

**Comment by ashishdhingra** [comment]
Hi @AntShep,

Good afternoon.

While looking closely at the issue and troubleshooting it, it appears that this behavior is as per design. 

At high level:
- [AWS4Signer.CanonicalizeHeaders()](https://github.com/aws/aws-sdk-net/blob/e54ffe43a68a60ebe65b139487e4e9122902226e/sdk/src/Core/Amazon.Runtime/Internal/Auth/AWS4Signer.cs#L761) appears to canonicalize the headers with values for the request, with the format `[headername:headervalue]\n`. This also includes `x-amz-tagging` header.
- These canonicalized headers are included as part of canonicalized request as per [AWS4Signer.CanonicalizeRequestHelper()](https://github.com/aws/aws-sdk-net/blob/e54ffe43a68a60ebe65b139487e4e9122902226e/sdk/src/Core/Amazon.Runtime/Internal/Auth/AWS4Signer.cs#L716) along with header names.
- The canonicalized request is used to [ComputeSignature](https://github.com/aws/aws-sdk-net/blob/e54ffe43a68a60ebe65b139487e4e9122902226e/sdk/src/Core/Amazon.Runtime/Internal/Auth/AWS4Signer.cs#L312) in [AWS4Signer.SignRequest()](https://github.com/aws/aws-sdk-net/blob/e54ffe43a68a60ebe65b139487e4e9122902226e/sdk/src/Core/Amazon.Runtime/Internal/Auth/AWS4Signer.cs#L176).

The headers are never included as part of query string, but are used to compute signature. **Hence, when user needs to use presigned URL, then it also needs to specify the exact value for `x-amz-tagging`**.

The .NET SDK is using the process/specification mentioned at https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html. All the headers are used to calculate the signature, but these are never included as part of query string. The only information in query string for headers is parameter `X-Amz-SignedHeaders` which indicates which headers are included to calculate the signature (`host;x-amz-tagging` in your case).

Hope this explains the behavior. Kindly confirm if this issue could be closed.

Thanks,
Ashish

**Comment by AntShep** [comment]
@ashishdhingra Thanks for clarification!

If this behavior is as per design, then I have no further questions.
