### ISSUE TITLE
General performance problems with the client

### ISSUE THREAD

**Issue by Rodrigo-Andrade** [aws/aws-sdk-net#1700]
The SDK is  now the bottleneck in several of our systems, the dotnet ecosystem kept getting faster, fleshing out this issue more and more.

We are writing some custom implementations of the clients because the performance of the SDK is not acceptable for some of our workloads, greatly increasing the cost to use AWS services.

I propose that performance tests be included in your development pipeline. 

Here is a sample trace from the S3 client as an exemple of the problems that permeate the SDK:

![image](https://user-images.githubusercontent.com/1174384/92727615-c7498a80-f345-11ea-8614-1f5260c66ed5.png)

You can see that 20% of the CPU time spent sending this get request is at:

```csharp
public static bool IsAmazonS3Endpoint(Uri uri)
{
      Match match = !(uri == (Uri) null) ? new Regex("^(.+\\.)?s3[.-]([a-z0-9-]+)\\.").Match(uri.Host) : throw new ArgumentNullException(nameof (uri));
      return (uri.Host.EndsWith("amazonaws.com", StringComparison.OrdinalIgnoreCase) || uri.Host.EndsWith("amazonaws.com.cn", StringComparison.OrdinalIgnoreCase)) && match.Success;
}
```
Every request runs this code.

**Comment by ppittle** [comment]
Thinking about this, few things to try:

- Create `Regex` as a constant field in `AmazonS3Uri`
- Use `RegexOptions.Compilex` or `Regex.CompileToAssembly` ([Best Practicies](https://docs.microsoft.com/en-us/dotnet/standard/base-types/best-practices))
- Decorate `IsAmazonS3Endpoint` with [`MethodImplOptions.AggressiveInlining`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.methodimploptions?view=netcore-3.1)

**Comment by indy-singh** [comment]
We've run into similar issues, and found that using pre-signed urls have alleviated a lot of the issues in case that helps @Rodrigo-Andrade 

Regards,
Indy

**Comment by ppittle** [comment]
Performance improvements are available in `[AWSSDK.S3 3.5.19](https://www.nuget.org/packages/AWSSDK.S3/3.5.1.9)`
