### ISSUE TITLE
Sample errors with "Cannot call GetSessionToken with session credentials"

### ISSUE THREAD

**Issue by jzabroski** [aws/aws-sdk-net#1704]
## Description
I tried the sample at https://docs.aws.amazon.com/AmazonS3/latest/dev/AuthUsingTempSessionTokenDotNet.html and got the following stack trace back:

```
---> Amazon.SecurityToken.AmazonSecurityTokenServiceException: Cannot call GetSessionToken with session credentials
 ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ExceptionHandler`1.Handle(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Infra.Services.FileTransferers.S3ClientFactory.GetTemporaryCredentialsAsync() in D:\Teamcity\buildAgent\work\448738e290cb3a26\source\Infra.Services\FileTransferers\S3ClientFactory.cs:line 70
```

## Reproduction Steps
1. Use 3.5.09 AWSDK for .NET with .NETCoreApp v3.1.6 .NET SDK
2. Follow linked tutorial:  https://docs.aws.amazon.com/AmazonS3/latest/dev/AuthUsingTempSessionTokenDotNet.html - in particular, all you need is the static call to `GetTemporaryCredentialsAsync()` and nothing else - that will repro the issue

### Logs
I followed the logging guide here: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html and it contains out of date documentation for .NET Core.

I found that the correct logging framework guide is here: https://docs.aws.amazon.com/toolkit-for-visual-studio/latest/user-guide/cw-log-frameworks.html

However, it doesn't seem to work - or it's confusing in how to configure it.  We use Serilog for logging as well, which probably adds a layer of difficulty.  Still, I'd expect `System.Diagnostics` logging to work, but it looks like .NET Core support isn't quote there.

Instead, I used logman (first trying trying it on .NET Core), and I can see that latest/metadata/iam/security-credentials returns HTTP/1.1 200.

Here is the failing call logged by LogMan:

ThreadID="3,512" ProcessorNumber="1" poolId="24,121,565" workerId="28,972,298" requestId="5,541,955" memberName="SendAsyncCore" message="Sending request: Method: POST, RequestUri: 'https://sts.amazonaws.com/', Version: 1.1, Content: System.Net.Http.ByteArrayContent, Headers: { User-Agent: aws-sdk-dotnet-netstandard/3.5.0.9 User-Agent: aws-sdk-dotnet-core/3.5.1.7 User-Agent: .NET_Core/3.1.3 User-Agent: OS/Microsoft_Windows_10.0.14393 User-Agent: ClientAsync x-amz-security-token: **security token deleted** Host: sts.amazonaws.com X-Amz-Date: 20200912T005435Z X-Amz-Content-SHA256: 8f07b22fd225cb8a5d441b42d1ead110c1f87259902c7bd5955ad186d135542a Authorization: AWS4-HMAC-SHA256 Credential=**credential deleted**/20200912/us-east-1/sts/aws4_request, SignedHeaders=content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-security-token, Signature=**signature deleted** Content-Length: 62 Content-Type: application/x-www-form-urlencoded; charset=utf-8 }"

ThreadID="3,512" ProcessorNumber="1" poolId="24,121,565" workerId="28,972,298" requestId="5,541,955" memberName="SendAsyncCore" message="Request content is not null, start processing it. hasExpectContinueHeader = False"

ThreadID="3,512" ProcessorNumber="1" poolId="24,121,565" workerId="28,972,298" requestId="5,541,955" memberName="WriteToStreamAsync" message="Writing 1798 bytes."

ThreadID="3,512" ProcessorNumber="1" poolId="24,121,565" workerId="28,972,298" requestId="5,541,955" memberName="SendRequestContentAsync" message="Finished sending request content."

ThreadID="3,560" ProcessorNumber="1" poolId="24,121,565" workerId="28,972,298" requestId="5,541,955" memberName="FillAsync" message="Received 164 bytes."

ThreadID="3,560" ProcessorNumber="1" poolId="24,121,565" workerId="28,972,298" requestId="5,541,955" memberName="SendAsyncCore" message="Request is fully sent."

ThreadID="3,560" ProcessorNumber="1" poolId="24,121,565" workerId="28,972,298" requestId="5,541,955" memberName="SendAsyncCore" message="Received response: StatusCode: 403, ReasonPhrase: 'Forbidden', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers: { x-amzn-RequestId: 2d835f5d-c94f-4feb-8864-5d351dd64987 Date: Sat, 12 Sep 2020 00:54:35 GMT Content-Type: text/xml Content-Length: 296 }"

ThreadID="3,560" ProcessorNumber="1" responseString="StatusCode: 403, ReasonPhrase: 'Forbidden', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers: { x-amzn-RequestId: 2d835f5d-c94f-4feb-8864-5d351dd64987 Date: Sat, 12 Sep 2020 00:54:35 GMT Content-Type: text/xml Content-Length: 296 }" httpRequestMessageHash="5,541,955" httpResponseMessageHash="55,401,902" httpClientHash="22,985,394"

ThreadID="3,560" ProcessorNumber="1" poolId="24,121,565" workerId="28,972,298" requestId="5,541,955" memberName="Read" message="Received 296 bytes."

### Environment
* SDK Version: 3.5.0.9
* Package Version:  3.5.0.9
* OS Info: Windows Server 2016 Data Center Edition (largest Amazon Workspace instance)
* Build Environment Visual Studio 2019 16.6.5
* Targeted .NET Platform:  .NETCoreApp3.1  (3.1.6 runtime)

## Resolution

I think the tutorial only works if you don't have a fancier overall organization-level security policy in place, like SAML Federation 2.0.  It probably needs a disclaimer, as well as a workaround for the fact the tutorial doesn't really deliver.

Alternatively, it's possible this is just a flat out bug that was introduced recently and the sample never works, regardless of whether the end user is using Duo SAML Federation 2.0, etc.

---

This is a :bug: bug-report

**Comment by jzabroski** [comment]
I believe the issue is hinted at in the following STS API operations comparison page: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_request.html#stsapi_comparison

However, I can't make sense of why the sample doesn't work out-of-the-box.  Hoping someone from Amazon can help me connect the dots.

**Comment by ashishdhingra** [comment]
Hi @jzabroski, 

Good morning.

Looks like your default profile (in `.aws/credentials`) is configured with session credentials. Hence, when the following call is made:
```C#
GetSessionTokenResponse sessionTokenResponse =
                              await stsClient.GetSessionTokenAsync(getSessionTokenRequest);
```

it correctly throws error `Amazon.SecurityToken.AmazonSecurityTokenServiceException: Cannot call GetSessionToken with session credentials`.

I was able to reproduce the issue when I used session credentials in my default profile.

When I modified my default profile with the IAM user access and secret key, the above code worked fine giving the following output for the sample at [Making requests using IAM user temporary credentials - AWS SDK for .NET](https://docs.aws.amazon.com/AmazonS3/latest/dev/AuthUsingTempSessionTokenDotNet.html):
```
Listing objects stored in a bucket
Object count = 1
```

Please use the IAM user credentials (not the session credentials) for this sample to work. Alternatively, you may create another profile and specify it using configuration file or client constructor. Please refer AWS [.NET SDK documentation](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-creds.html) on how to use profile with SDK clients. Also refer sections **Credential and Profile Resolution** and **Specifying a Profile** on the same page.

Hope this helps. Please confirm if we could close this issue.

Thanks,
Ashish

**Comment by jzabroski** [comment]
> Looks like your default profile (in `.aws/credentials`) is configured with session credentials.

Interesting - I get this error even though the file is empty, or the file does not exist.

> When I modified my default profile with the IAM user access and secret key, the above code worked fine giving the following output for the sample at [Making requests using IAM user temporary credentials - AWS SDK for .NET](https://docs.aws.amazon.com/AmazonS3/latest/dev/AuthUsingTempSessionTokenDotNet.html):
> 
> ```
> Listing objects stored in a bucket
> Object count = 1
> ```
> 
> Please use the IAM user credentials (not the session credentials) for this sample to work.

I think I have a knowledge gap here, since I am not clear on what you did to get it to work.  In particular, I don't want to use an access and secret key.  I thought that the EC2 instance itself has an IAM role, which should get picked up.  For example, it defaults to default-server-role.  The way I was expecting this to work is if I don't specify a particular IAM role (e.g., via AssumeRole API), then it will use the EC2 Instance Metadata.  But maybe that is not correct expectation.  Basically, I don't see how requesting fresh temporary access credentials results in a 403 Forbidden message.

Is there a way I can step through the AWSSDK .NET code and figure out what path it is hitting?  Part of me feels like I am looking to go several layers deeper than the average developer, but that is sort of the point of my question.  I want to fully understand how this is supposed to work.

**Comment by jzabroski** [comment]
@ashishdhingra I think I got it - it clicked after I replied.

From https://docs.aws.amazon.com/STS/latest/APIReference/API_GetSessionToken.html (**emphasis _mine_**) :

> The GetSessionToken operation **must be called by using _the long-term_ AWS security credentials** of the AWS account root user or an IAM user. 

Session credentials are not long-term AWS security credentials.  Is that right?  I think that may be the bit I was missing and not understanding.  And I can see how an access key / secret key pair is a "long-term AWS security credential".  But then, what other forms of long-term credential can I use that are more safe than access key / secret key pair?

**Comment by ashishdhingra** [comment]
@jzabroski You are right, session credentials are not long term credentials. Please refer [AWS security credentials](https://docs.aws.amazon.com/general/latest/gr/aws-security-credentials.html) for details about credentials and best practices. Please let me know if this provides necessary guidance.

**Comment by jzabroski** [comment]
Got it - that clears things up.  I found https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html#temporary-access-keys from the link you sent, which notes that assume role is a temporary access credential.

I didn't have the hierarchy of how these things worked until that clarifying moment, so thank you very much!
