### ISSUE TITLE
AWSSDK.Extensions.CognitoAuthetication 0.9.4 can't work with AWSSDK.Core 3.5.x.x

### ISSUE THREAD

**Issue by SETSinsperion** [aws/aws-sdk-net#1706]
## Description
Good day. I have a **Visual Studio solution (Community 2019)** using AWS SDK, and for a couple of weeks **I can´t update successfully all Nuget Packages related to AWS** due to the package _**AWSSDK.Extensions.CognitoAuthetication 0.9.4 can't work with AWSSDK.Core 3.5.x.x**_. I've been working with stable **versions 3.3.x.x of the AWS SDK NuGet packages, working OK**, and versions 3.5.x.x packages are launched 2 weeks ago and from that time I can't update reporting the NuGet error/warning I was mentioned with AWSSDK.Extensions.CognitoAuthetication 0.9.4 package. A doubt related to this is: _what is the main difference between AWSSDK.Extensions.CognitoAuthentication and Amazon.Extension.CognitoAuthentication?_.

## Reproduction Steps
1. Open Visual Studio and create a solution, inside that solution create a NET console app project.
2. Install via NuGet (your project > Manage your NuGet packages) **AWSSDK.Core version 3.3.107.40**
3. Now install via NuGet **AWSSDK.Extensions.CognitoAuthentication version 0.9.4**
4. **Update AWSSDK.Core to the most stable version (in this moment 3.5.1.10)**.
5. In the Error List Visual Studio tab, **you'll see warnings/errors related to Cognito packages (_CognitoAuthetication, CognitoIdentityProvider, CognitoIdentity_) that need AWSSDK.Core versions 3.3.17.2 >= && 3.4.0** 

### Environment
* SDK Version: version 3
* Package Version: working OK will 3.3.x.x packages, need to update to 3.5.x.x packages
* OS Info: Windows 10 version 2004 (Build 19041.508)
* Build Environment: Visual Studio Community 2019
* Targeted .NET Platform:  Solution with projects using
  - .NET Framework 4.6.1
  - .NET Standard 2.0

This is a :bug: bug-report

**Comment by SETSinsperion** [comment]
Have a good day @ashishdhingra . I found an issue that is completely related with this one that was reported 3 days before mine: https://github.com/aws/aws-sdk-net-extensions-cognito/issues/57 . Do you have any news about this problem? Thank much in advance.

**Comment by hashitha** [comment]
I updated to this package and it worked fine
https://github.com/aws/aws-sdk-net-extensions-cognito/

**Comment by SETSinsperion** [comment]
**@hashitha greetings and have a happy new year 2021,** I'm sorry for my late response. One of my main questions is **what's the difference between AWSSDK.Extension.CognitoAuthetication & Amazon.Extension.CognitoAuthetication**, in my project I have both Nuget packages installed. The AWSSDK.Extension.CognitoAuthentication is the one who has the problem about the update in this issue and I checked that this package don't have any update since the version 0.9.4, here you have the error (using VS in spanish, sorry for the language):

**_Error	NU1107	Se detectó un conflicto de versiones para AWSSDK.CognitoIdentityProvider. Para resolver este problema, instale o haga referencia a AWSSDK.CognitoIdentityProvider 3.5.0.2 directamente en el proyecto AWS Power Snippets.  AWS Power Snippets -> Amazon.Extensions.CognitoAuthentication 2.0.2 -> AWSSDK.CognitoIdentityProvider (>= 3.5.0.2)  AWS Power Snippets -> AWSSDK.Extensions.CognitoAuthentication 0.9.4 -> AWSSDK.CognitoIdentityProvider (>= 3.3.4.3 && < 3.4.0).	AWS Power Snippets	F:\Users\sergi\Documents\Visual Studio 2019\Projects\NetUtilities\AWS Power Snippets\AWS Power Snippets.csproj_**

**I installed the Amazon.Extension.CognitoAuthetication and Visual Studio reported me that my project was successfully compiled, so I have that doubt if the AWSSDK.Extension.CognitoAuthentication isn't needed for the solution or AWS hasn't reported this package is not longer needed for Cognito in .NET.** I'm using Cognito code to manage credentials for my Cognito accounts, both packages have the same description at Visual Studio Nuget Manager, so I don't wanna remove one or another package if I'm not sure the difference of usage.

**Can you help me answering this doubt @hashitha ? Beforehand a lot of thanks.**

**Comment by ashovlin** [comment]
Hello @SETSinsperion,

`Amazon.Extension.CognitoAuthetication` (https://www.nuget.org/packages/Amazon.Extensions.CognitoAuthentication/) is the replacement for `AWSSDK.Extension.CognitoAuthetication` and should be used moving forward. 

The 2.0.0 version of `Amazon.Extension.CognitoAuthetication` is compatible with version 3.5 of the AWSSDK packages.

We'll look into marking the older version as deprecated on NuGet. Thanks.

**Comment by SETSinsperion** [comment]
@ashovlin hello, a lot of thanks for your answer, that's not in the AWS .NET documentation, like many details. So I'. gonna do the changes in my solutions to test what you said to close this issue. Thanks for all that have contribute to this issue.

**Comment by hunanniu** [comment]
Please let us know if your change works as you expect. If you haven't made the change, please use version 2.0.3 as it has Device level support.

**Comment by ashishdhingra** [comment]
Please use [Amazon.Extensions.CognitoAuthentication 2.0.3](https://www.nuget.org/packages/Amazon.Extensions.CognitoAuthentication/2.0.3)

**Comment by SETSinsperion** [comment]
Greetings @ashishdhingra  and @hunanniu , I'm very sorry to let this issue along time. I tested all today all works perfectly. A lot of thanks to your attention & support. Keep it going!
