### ISSUE TITLE
S3 presigned URL - if filename contains three dots, it uploads to the parent folder.

### ISSUE THREAD

**Issue by jbesw** [aws/aws-sdk-net#1707]
## Description
When uploading an object to S3 with a presigned URL, if the filename *contains* three dots, it uploads to the parent folder instead.

## Reproduction Steps
1. Create a presigned URL to upload with an object name containing three dots.
2. Upload the object.
3. The object appears in the parent folder.

### Environment
FYI, this was reported by a Twitter user in response to a blog post about uploading S3 events. See https://twitter.com/jon_raRaRa/status/1305541955552772097. I am reporting here to capture their observation but have not tested the bug myself.

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

---

This is a :bug: bug-report

**Comment by normj** [comment]
This is an issue with the .NET System.Uri class which is used by .NET to make requests. As documented on MSDN, https://docs.microsoft.com/en-us/dotnet/api/system.uri, it will canonicalizes the request including handling ".." in the uri path. There is no option in the Uri class to turn this behavior off so we don't have a valid work around right now and we are stuck with the limitations of .NET in this case.

**Comment by jbesw** [comment]
Thanks for the background, @normj.

**Comment by normj** [comment]
By the way in response to the tweet we did update the documentation of the Key properties on request objects to document this behavior.

https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/S3/Custom/Model/GetPreSignedUrlRequest.cs#L90

**Comment by normj** [comment]
I have created a feature request on the .NET repos to provide us someway to turn off the canonicalization in the System.Uri class. https://github.com/dotnet/runtime/issues/52628
