### ISSUE TITLE
Add "Default" AWS credentials object

### ISSUE THREAD

**Issue by grbartel** [aws/aws-sdk-net#1712]
## Describe the Feature
When creating an AWS Clients you are currently able to use the default credential search options by not specifying any credential object.  What I would like to see is a new credential object that follows the AWSCredentials base class.

### Is your Feature Request related to a problem?

Not having this is currently causing issues for us where we are trying to use a function to create the credentials object but in some cases we want to fall back on an EC2 Instance Role and currently this involves either catching an error or using an extra check outside of that function.

## Additional Context

A quick sudo code example of what we are doing is:

```
if ( awsProfile != Null || awsAccessKey != Null){
AWSCredentials awsCredentials = GetAWSCredentials(awsProfile, awsAccessKey)
client = new AmazonCloudFormationClient(awsCredentials,region)
} else {
client = new AmazonCloudFormationClient(region)
}

```

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change  

---

This is a :rocket: Feature Request

**Comment by GoFightNguyen** [comment]
Are you asking for something similar to the `DefaultAWSCredentialsProviderChain` in [Java](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html)?

**Comment by grbartel** [comment]
Yeah that looks to be exactly what I would want.

**Comment by GoFightNguyen** [comment]
I would like to upvote for this then

**Comment by ashishdhingra** [comment]
@grbartel Just curious whether [Amazon.Runtime.FallbackCredentialsFactory.GetCredentials()](https://github.com/aws/aws-sdk-net/blob/3eea05c7fa04ddd6bca16d5c83510d4fb05ce2ca/sdk/src/Core/Amazon.Runtime/Credentials/FallbackCredentialsFactory.cs#L111) fits the need. Could you please check?

**Comment by GoFightNguyen** [comment]
@ashishdhingra This looks promising, I'll try to make time during this upcoming week to try it out
