### ISSUE TITLE
AWS lambda setup error in .NET Core 3.1

### ISSUE THREAD

**Issue by Ryan881** [aws/aws-sdk-net#1714]
Hello I am trying to Configure AWS lambda in .NET core 3.1 project but when I am installing Amazon.Lambda.Tools from Nuget I am getting error that  Amazon.Lambda.Tools 4.0.1 doesn't support .netcoreapp 3.1. Please help me fixing this issue. I can't downgrade my project to .net 2.1

**Comment by ashishdhingra** [comment]
Hi @Ryan881,

Good morning.

Could you please try executing the following command from .NET CLI to install the latest version of the tool:

```
dotnet tool install --global Amazon.Lambda.Tools --version 4.1.0
```

Also, I don't see version 4.0.1 on https://www.nuget.org/packages/Amazon.Lambda.Tools/.

Thanks,
Ashish
