### ISSUE TITLE
Log4net assumes xml configuration

### ISSUE THREAD

**Issue by matt-richardson** [aws/aws-sdk-net#172]
When using 
````
AWSConfigs.LoggingConfig.LogTo = LoggingOptions.Log4Net;
````
it calls 
````
XmlConfigurator.Configure()
````
in https://github.com/aws/aws-sdk-net/blob/5f19301ee9fa1ec29b11b3dfdee82071a04ed5ae/AWSSDK_DotNet35/Amazon.Runtime/Internal/Util/Logger.Log4net.cs#L119.

This results in the following error:

````
log4net:ERROR XmlConfigurator: Failed to find configuration section 'log4net' in the application's .config file. Check your .config file for the <log4net> and <configSections> elements. The configuration section should look like: <section name="log4net" type="log4net.Config.Log4NetConfigurationSectionHandler,log4net" />
log4net:ERROR XmlConfigurator: Failed to find configuration section 'log4net' in the application's .config file. Check your .config file for the <log4net> and <configSections> elements. The configuration section should look like: <section name="log4net" type="log4net.Config.Log4NetConfigurationSectionHandler,log4net" />
````

While this is a common way of configuring log4net, it is definitely not the only way (I am configuring in code, as I do not want to ship a config file with my application).

It might be worth checking whether the logging is already configured before calling this method.

**Comment by PavelSafronov** [comment]
Thanks for pointing this out. I will add a call to `LogManager.GetRepository().Configured` to see if log4net is already configured, this way we can avoid the extraneous `XmlConfigurator.Configure()` call.

**Comment by matt-richardson** [comment]
I've created a fix for it, with some tests, but I'm not convinced that it should be merged.

It seems the code goes to a lot of effort to ensure that it doesn't have a dependency on log4net, so adding a dependency to be able to test this seems wrong. 

I've also had to make public some internal classes to make it work (InternalLog4netLogger & InternalLogger) which didn't feel great. (I tried the InternalsVisibleTo approach, but it didn't work too well given its strongly named).

So... you may just want the actual fix to InternalLog4netLogger, without the tests.

Let me know if you want a PR for that.

**Comment by PavelSafronov** [comment]
I was thinking of making a reflection-only call to `LogManager.GetRepository().Configured` (similar to the code [here](https://github.com/aws/aws-sdk-net/blob/master/AWSSDK_DotNet35/Amazon.Runtime/Internal/Util/Logger.Log4net.cs#L127)) , so the change itself should be fairly straightforward, but I agree with you, adding tests for this is problematic.

Though, giving it some more thought, it sounds like overall this would be a breaking change: existing customers could be attaching listeners as you are doing, through code, but if they *also* have an app.config, they may be "relying" on the SDK to make the `XmlConfigurator.Configure()` call to pick up the log4net config.

In essence, we're currently performing log4net XML configuration, and if this was suddenly removed then the above customers would have to make the call on their own, which would require a code change.

I'll keep thinking about this, but at the moment I don't think we should make this change.

**Comment by matt-richardson** [comment]
Hmmm... I think that case is unlikely, but it is definitely possible... It also doesn't seem the kind of thing that merits a major version bump as well.

Maybe we could add a check for the config file to see if it exists before calling `XmlConfigurator.Configure()` using the same logic as log4net uses to determine the config file name - https://github.com/apache/log4net/blob/84a6c6c2af369ee525effc4e6f3262b08a82459b/src/log4net/Util/SystemInfo.cs#L167.

Either that, or we expose a boolean flag that defaults to true that we check before we call the method? This might be the easiest / lowest impact approach.

**Comment by PavelSafronov** [comment]
I like your first approach, though I believe it should be enough to [attempt and retrieve the config element](https://github.com/apache/log4net/blob/trunk/src/log4net/Config/XmlConfigurator.cs#L172), and then check if it is null, in which case we can skip the `XmlConfigurator.Configure()` call. I don't think we need to use log4net's `SystemInfo.ConfigurationFileLocation` for this purpose.

**Comment by matt-richardson** [comment]
Okay, sounds like we are on the same page.
Want me to create a PR?

**Comment by PavelSafronov** [comment]
No need, we've already made the changes internally. This fix should be out with the next release of the SDK.

**Comment by matt-richardson** [comment]
Great, thanks.

**Comment by PavelSafronov** [comment]
Version 2.3.26 of the SDK has just been released and it contains this fix.

**Comment by matt-richardson** [comment]
Brilliant. Thanks @PavelSafronov!
