### ISSUE TITLE
Version 3.5.25.0 has dependency on Microsoft.Bcl.AsyncInterfaces [This breaks Unity Support]

### ISSUE THREAD

**Issue by ExodusOTH** [aws/aws-sdk-net#1722]
When attempting to use the AWS .NET SDK in Unity, the latest version supplied on [this page](https://aws.amazon.com/blogs/developer/referencing-the-aws-sdk-for-net-standard-2-0-from-unity-xamarin-or-uwp/) links to the latest version of the SDK, however this latest version's _AWSSDK.Core.dll_ file has a dependency on _Microsoft.Bcl.AsyncInterfaces_, and this breaks Unity support as attempting to find some workaround such as using a NUGET Package Manager (the only available one is unofficial, [linked here](https://github.com/GlitchEnzo/NuGetForUnity)) with Unity and then adding that package (Microsoft.Bcl.AsyncInterfaces) just leads to more dependencies and a never ending rabbit hole.

This dependency does not exist with the prior versions (specifically V3.3) of the SDK, so is this intentional? This creates a large issue when all of the few Unity tutorials and workshops that AWS provides use a 3.3 version of the SDK.

[I have successfully replicated this in 2019.4.9f1 and 2020.1.6f1. As this dependency is on AWS' side however, I would imagine that it is not dependent upon a Unity Version]

**Comment by znebby** [comment]
Really hoping we can get this fixed

**Comment by dave-trainor** [comment]
Yes, I'm running into the same problems with my Unity project. I'd really hoped V3.5 would finally bring proper AWS SDK functionality to Unity, but it seems there's more work to be done. I'd be very grateful if this could be addressed as soon as possible.

**Comment by ExodusOTH** [comment]
This is NOT a fix for V3.5, however 

For the other Unity Game Developers trying to integrate AWS, I don't remember where I found it, but if you can get a copy of the V3.3 DLLs, they didn't require dependencies. They don't have ALL the services (which was the point of V3.5), however V3.3 has some of the big ones.

**Comment by dave-trainor** [comment]
Thanks @ExodusOTH ! The V3.3 DLLs can be found at http://sdk-for-net.amazonwebservices.com/releases/aws-sdk-netstandard2.0-3.3.597.0.zip

If I can get Cognito, DynamoDB and S3 operational then I'll be happy for now!

**Comment by ExodusOTH** [comment]
@dave-trainor Yep! Those are actually the exact services I'm using in my project.

**Comment by znebby** [comment]
Does 3.3x include the CognitoAuthentication Extension? From what I understand, without it, you need to implement a lot of your own crypto.

**Comment by dave-trainor** [comment]
@znebby From what I can see the CognitoAuthentication extension is not in the zipfile download for either V3.3 or V3.5. As you say, without that extension you have to code a lot of the crypto yourself, particularly for advanced authentication flows like SRP. I'm looking to see if it's possible to extract the CognitioAuthentication DLL from the NuGet packages available at https://www.nuget.org/packages/Amazon.Extensions.CognitoAuthentication/ and bring that DLL into Unity, after all the .NET SDK dependencies are in place.

**Comment by ExodusOTH** [comment]
[This Repo from AWS ](https://github.com/aws-samples/serverless-games-on-aws) has a Unity Package under "Cognito User Pools Authentication Lab" and if you import that package, then deselect everything except for that Extension, bingo you're good.

This is all why V3.5 needs to have that dependency removed, it was a needle in a haystack when I first tried finding all this stuff. Just figured I'd post the janky workaround back here so the public has SOMETHING that can help them get going. 

[This link](https://serverless-game-analytics.workshop.aws/en/introduction.html) is also a workshop hidden in the weeds that AWS provides, but that workshop doesn't link to the exact files that they used. This workshop is what pointed me to that GitHub Repo, but that GitHub repo says it's deprecated. It's a mess, but there's the files you need.

**Comment by dave-trainor** [comment]
Just as an update, I've managed to bring in the .NET SDK V3.3 DLLs and the CognitioAuthentication DLL into a Unity 2020.1 project and create an app that authenticates with Cognito and then access a DynamoDB table. The app works fine in the Unity Editor and when built as a PC/Mac/Linux app. Howeverwhen it is built and executed as a UWP app it fails, generated many COM "class not registered" exceptions, followed by many "Il2CppExceptionWrapper at memory location" exceptions before terminating. I can't work out why this is happening.

**Comment by znebby** [comment]
@dave-trainor Is it possible for you to share some boiler plate code to get Cognito working?

I am using the code here: https://github.com/rms80/awscognito-unity-accounts-demo but while account creation works, attempting to login with the same details results in an Incorrect username or password error from AWS.

**Comment by 02annouser** [comment]
For the newest aws sdk: aws-sdk-netstandard2.0-3.5.60.0.zip I did download the following nuget packages:
microsoft.bcl.asyncinterfaces.1.0.0.nupkg
system.threading.tasks.extensions.4.5.2.nupkg
system.runtime.compilerservices.unsafe.5.0.0.nupkg

Then extracted them (change to zip) & copied from them the lib/netstandard2.0/*.dll into the Unity folder Assets/Plugins/
and then at least it runs for me in the editor so far without errors/warnings. 
But I did not further testings so far...

**Comment by 17kisern** [comment]
The latest version seems to work for me, but considering they haven't added anything to this issue I am assuming they haven't done much testing with it against Unity. But V3.5.62 doesn't have the dependency on AsyncInterfaces from what I can tell. Now I'm just going through the process of getting used to the new method using Begin* and End* instead of a single *Async call.

Here's a link on AWS with a link to the latest version of just the DLLs
https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-install-assemblies.html

**Comment by znebby** [comment]
@17kisern Okay, using the AWS DLLs linked above, it seems I get the dependency issue using .NET standard 2.0, but if I grab the .NET 4.5 DLLs (and set Unity to the same) it works without any dependency issues.

**Comment by 17kisern** [comment]
Can confirm with @znebby , 

I did some further testing and variations of configurations, and the only way I could get V3.5.62 to work was setting Unity's API Compatibility level to 4.x, and using the .NET 4.5 DLLs.

**Comment by dave-trainor** [comment]
@znebby sorry for the delayed response. I got Cognito working by using the [CognitoAuthentication ](https://github.com/aws/aws-sdk-net-extensions-cognito) extension together with the AWS .NET SDK and the [example Cognito script](https://github.com/aws-samples/serverless-games-on-aws/blob/master/Cognito%20User%20Pools%20Authentication%20Lab/Cognito.cs) from the project referenced by @ExodusOTH  above.

I've tried the new AWS .NET SDK revision 3.5.62 and I get similar results to @znebby  and @17kisern . The .NET Standard 2.0 version has the same kind of dependencies issues as before, but the .NET 4.5 version does not.

With the .NET 4.5 version of the AWS .NET SDK revision 3.5.62, together with the CognitoAuthentication extension, I can succesfully run my app in the Unity Editor. It also works when I build a PC/Mac/Linux Standalone app with Unity. However, when I build a Unified Windows Program (UWP) app with Unity, the app always fails when it tries to use the AWS functions. I reported this earlier as issue #1740 . Has anybody managed to successfully build a working UWP app from Unity that uses the latest  AWS .NET SDK?

**Comment by 17kisern** [comment]
The other ticket I mentioned this one in has been resolved, and I provided some sample code for any of you other Unity Developers there. Specifically, how in the heck you can actually support caching, because AWS tells you to override the CognitoAWSCredentials class to do so, but overriding that breaks the User.GetCognitoAWSCredentials() call that the CognitoExtensions library provides.

That linked issue has sample code that was the solution that allowed me to do everything (be able to cache, and still use the Extension Library for Authentication). Basically, it came down to switching one line of code, but I figured it might be useful for you guys.

**Comment by ashovlin** [comment]
Hi everyone, we're working on the issue with the additional necessary dependencies for the `netstandard2.0` version of the v3.5 AWSSDK DLLs.

These are the three that are required:
1. Microsoft.Bcl.AsyncInterfaces.dll- https://www.nuget.org/packages/Microsoft.Bcl.AsyncInterfaces/
2. System.Runtime.CompilerServices.Unsafe.dll -https://www.nuget.org/packages/System.Runtime.CompilerServices.Unsafe/
3. System.Threading.Tasks.Extensions.dll - https://www.nuget.org/packages/System.Threading.Tasks.Extensions/

We're exploring adding them to the zip available at https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/net-dg-obtain-assemblies.html#download-zip-files

In the meantime, it should be possible to grab them from NuGet by downloading the package, renaming from `.nupkg` to `.zip`, unzipping, then copying the DLLs from the `lib\netstandard2.0` folder to your Unity project.

**Comment by alloplastic** [comment]
@ashovlin - Any guidance on assembly versions?  Under Unity 2019.4.17f1 I get runtime errors related to certain assemblies (including Unity assemblies) depending on specific versions of the three DLLs above.  Example:

```
Assembly 'Library/ScriptAssemblies/Unity.Collections.dll' will not be loaded due to errors:
Unity.Collections references strong named System.Runtime.CompilerServices.Unsafe Assembly references: 4.0.4.0 Found in project: 5.0.0.0.
Assembly Version Validation can be disabled in Player Settings "Assembly Version Validation"
```

I found the exact version for Microsoft.Bcl.AsyncInterfaces, but for these others I can't find an exact match.  I'll try something closer, like 4.7.1, then I'll get an error that 4.0.6.0 is being found:

```
Assembly 'Library/ScriptAssemblies/Unity.Serialization.dll' will not be loaded due to errors:
Unity.Serialization references strong named System.Runtime.CompilerServices.Unsafe Assembly references: 4.0.4.0 Found in project: 4.0.6.0.
Assembly Version Validation can be disabled in Player Settings "Assembly Version Validation"
```

Maybe turning off validation would be safe enough.

Or I may just try an earlier version of the AWS SDK if there isn't a simple way to clear up these dependencies.

**Comment by ashovlin** [comment]
From the SDK's perspective, we depend on v.1.1.0 of `Microsoft.Bcl.AsyncInterfaces` [here](https://github.com/aws/aws-sdk-net/blob/133eddb00a3fbd2ab395e01c3d84ac9fe1ff38b2/sdk/src/Core/AWSSDK.Core.NetStandard.csproj#L87).

The other two are pulled in as transitive dependencies of that. For v.1.1.0 of the above, it looks like it needs:
1. System.Threading.Tasks.Extensions (>= 4.5.2)
2. System.Runtime.CompilerServices.Unsafe (>= 4.5.2)

Let me test how those work with the two Unity packages you mentioned. Admittedly I don't think we typically test alongside packages beyond what's included by default with a new Unity project.

**Comment by ashovlin** [comment]
@alloplastic 

I was able to get this building on 2019.4.17.f1:
1. References to `"com.unity.serialization": "1.5.0-preview"` and `"com.unity.collections": "0.9.0-preview.6"`
   * I had initially tried the latest versions, but was getting an error with `collections@0.12.0-preview.13` (which seems to be pulled in by `com.unity.serilization@1.6.0-preview`) like  `The type name 'ReadOnly' does not exist in the type 'NativeArray<T>'` Discussed [here](https://forum.unity.com/threads/collections-package-throws-the-type-name-readonly-does-not-exist-in-the-type-nativearray-t.887377/), I think it's unrelated so I just downgraded.
2. Uncheck "Assembly Version Validation" in Project Settings > Player.
3.  In my `/Assets/AWS SDK` folder where I was dropping the AWS SDK DLLs, I only included `Microsoft.Bcl.AsyncInterfaces.dll` and `System.Threading.Tasks.Extensions.dll`. 
    *  `System.Runtime.CompileServices.Unsafe` appears to be resolved through `com.unity.collections`

**Comment by alloplastic** [comment]
@ashovlin - Thank you for following up.

It's good to hear that there is a way to navigate the dependencies.  For my own project, which is unfortunately dependent on that older version of Unity, I decided to decouple the AWS SDK from the Unity executables via a NodeJS service.  I was probably going to need a Web API anyway, so in my case it made sense to simplify down to one environment for the AWS integration.

Thanks again for checking this out, though.  Hopefully your notes will reduce the trial and error of others facing this issue.

**Comment by ashovlin** [comment]
As of today's (2/15/21) SDK release (v3.5.109), we now include the three required dependencies in the [aws-sdk-netstandard2.0.zip](https://sdk-for-net.amazonwebservices.com/latest/v3/aws-sdk-netstandard2.0.zip) available from https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/net-dg-obtain-assemblies.html#download-zip-files.

You can copy those to your Unity project alongside `AWSSDK.Core.dll` and whichever AWS services you're using.

We're still working on updating the docs, likely at https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/unity-special.html (will leave this open in the meantime, and post again once they're live).

![unityDependencies](https://user-images.githubusercontent.com/1170880/107996713-0c39b300-6faf-11eb-84d8-046b878928e3.PNG)

**Comment by ashovlin** [comment]
We've added a bullet point to https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/unity-special.html mentioning the need to copy the three required dependencies alongside the v3.5+ `netstandard2.0` DLLs now that they're included in the zip.

I'm going to close this for now as that was the original issue. I know others came up along the way (Cognito Authentication, conflicts with Unity references), so feel free to open those as new, more focused issues. Thanks!

**Comment by halzate93** [comment]
@ashovlin I am still having problems to build with the version you provided. When I try to build I get the following error: 

This is happening with Unity 2020.2.4f1 with iOS as the build target and Api compatibility set to .NET Standard 2.0

```
Exception: IL2CPP error for type 'System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1' in assembly '/Users/halzate/Projects/YumeGO/Temp/StagingArea/Data/Managed/Microsoft.Bcl.AsyncInterfaces.dll'
System.NullReferenceException: Object reference not set to an instance of an object.
   at Mono.Cecil.GenericInstanceType..ctor(TypeReference type)
   at Unity.IL2CPP.GenericsCollection.Inflater.ConstructGenericType(GenericContext context, TypeDefinition typeDefinition, IEnumerable`1 genericArguments) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/Inflater.cs:line 71
   at Unity.IL2CPP.GenericsCollection.Inflater.InflateType(GenericContext context, GenericInstanceType genericInstanceType) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/Inflater.cs:line 25
   at Unity.IL2CPP.GenericsCollection.Inflater.InflateType(GenericContext context, TypeReference typeReference) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/Inflater.cs:line 11
   at Unity.IL2CPP.GenericsCollection.Inflater.ConstructGenericType(GenericContext context, TypeDefinition typeDefinition, IEnumerable`1 genericArguments) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/Inflater.cs:line 73
   at Unity.IL2CPP.GenericsCollection.Inflater.InflateType(GenericContext context, GenericInstanceType genericInstanceType) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/Inflater.cs:line 25
   at Unity.IL2CPP.GenericsCollection.GenericContextAwareVisitor.Visit(FieldReference fieldReference, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/GenericContextAwareVisitor.cs:line 116
   at Unity.Cecil.Visitor.Visitor.Visit(Instruction instruction, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.Cecil.Visitor/Visitor.cs:line 365
   at Unity.IL2CPP.GenericsCollection.GenericContextAwareVisitor.Visit(Instruction instruction, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/GenericContextAwareVisitor.cs:line 177
   at Unity.Cecil.Visitor.Visitor.Visit(MethodBody methodBody, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.Cecil.Visitor/Visitor.cs:line 348
   at Unity.Cecil.Visitor.Visitor.Visit(MethodDefinition methodDefinition, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.Cecil.Visitor/Visitor.cs:line 264
   at Unity.IL2CPP.GenericsCollection.GenericContextAwareVisitor.Visit(MethodDefinition methodDefinition, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/GenericContextAwareVisitor.cs:line 76
   at Unity.Cecil.Visitor.Visitor.Visit(TypeDefinition typeDefinition, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.Cecil.Visitor/Visitor.cs:line 193
   at Unity.IL2CPP.GenericsCollection.GenericContextAwareVisitor.ProcessGenericType(PrimaryCollectionContext context, GenericInstanceType type, InflatedCollectionCollector generics, GenericInstanceMethod contextMethod) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/GenericContextAwareVisitor.cs:line 229
   at Unity.IL2CPP.GenericsCollection.GenericContextAwareVisitor.Visit(FieldReference fieldReference, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/GenericContextAwareVisitor.cs:line 119
   at Unity.Cecil.Visitor.Visitor.Visit(Instruction instruction, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.Cecil.Visitor/Visitor.cs:line 365
   at Unity.IL2CPP.GenericsCollection.GenericContextAwareVisitor.Visit(Instruction instruction, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/GenericContextAwareVisitor.cs:line 177
   at Unity.Cecil.Visitor.Visitor.Visit(MethodBody methodBody, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.Cecil.Visitor/Visitor.cs:line 348
   at Unity.Cecil.Visitor.Visitor.Visit(MethodDefinition methodDefinition, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.Cecil.Visitor/Visitor.cs:line 264
   at Unity.IL2CPP.GenericsCollection.GenericContextAwareVisitor.Visit(MethodDefinition methodDefinition, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/GenericContextAwareVisitor.cs:line 76
   at Unity.Cecil.Visitor.Visitor.Visit(TypeDefinition typeDefinition, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.Cecil.Visitor/Visitor.cs:line 193
   at Unity.IL2CPP.GenericsCollection.GenericContextAwareVisitor.ProcessGenericType(PrimaryCollectionContext context, GenericInstanceType type, InflatedCollectionCollector generics, GenericInstanceMethod contextMethod) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/GenericContextAwareVisitor.cs:line 229
   at Unity.IL2CPP.GenericsCollection.GenericContextFreeVisitor.Visit(TypeDefinition typeDefinition, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/GenericContextFreeVisitor.cs:line 26
   at Unity.Cecil.Visitor.Visitor.Visit(ModuleDefinition moduleDefinition, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.Cecil.Visitor/Visitor.cs:line 178
   at Unity.Cecil.Visitor.Visitor.Visit(AssemblyDefinition assemblyDefinition, Context context) in /Users/bokken/build/output/unity/il2cpp/Unity.Cecil.Visitor/Visitor.cs:line 172
   at Unity.IL2CPP.GenericsCollection.GenericsCollector.Collect(PrimaryCollectionContext context, ReadOnlyCollection`1 assemblies) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/GenericsCollection/GenericsCollector.cs:line 13
   at Unity.IL2CPP.AssemblyConversion.PrimaryCollection.Steps.Global.GenericsCollection.ProcessAllItems(GlobalPrimaryCollectionContext context, ReadOnlyCollection`1 items) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/AssemblyConversion/PrimaryCollection/Steps.Global/GenericsCollection.cs:line 32
   at Unity.IL2CPP.AssemblyConversion.Steps.Base.GlobalScheduledStepFunc`3.WorkerWrapper(WorkItemData`3 workerData) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/AssemblyConversion/Steps.Base/GlobalScheduledStepFunc.cs:line 41
   at Unity.IL2CPP.Contexts.Scheduling.PhaseWorkScheduler`1.WorkerLoop(Object data) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/Contexts.Scheduling/PhaseWorkScheduler.cs:line 247
UnityEditorInternal.Runner.RunProgram (UnityEditor.Utils.Program p, System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:129)
UnityEditorInternal.Runner.RunManagedProgram (System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser, System.Action`1[T] setupStartInfo) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildUtils.cs:65)
UnityEditorInternal.IL2CPPBuilder.RunIl2CppWithArguments (System.Collections.Generic.List`1[T] arguments, System.Action`1[T] setupStartInfo, System.String generatedCppOutputDirectory) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:793)
UnityEditorInternal.IL2CPPBuilder.ConvertPlayerDlltoCpp (UnityEditor.Il2Cpp.Il2CppBuildPipelineData data, System.String outputDirectory, System.Boolean platformSupportsManagedDebugging) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:765)
UnityEditorInternal.IL2CPPBuilder.Run () (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:598)
UnityEditorInternal.IL2CPPUtils.RunIl2Cpp (System.String tempFolder, System.String stagingAreaData, UnityEditorInternal.IIl2CppPlatformProvider platformProvider, System.Action`1[T] modifyOutputBeforeCompile, UnityEditor.RuntimeClassRegistry runtimeClassRegistry) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/Il2Cpp/IL2CPPUtils.cs:269)
UnityEditor.iOS.PostProcessiPhonePlayer.CrossCompileManagedDlls (UnityEditor.iOS.PostProcessiPhonePlayer+BuildSettings bs, UnityEditor.iOS.PostProcessiPhonePlayer+ProjectPaths paths, UnityEditor.AssemblyReferenceChecker checker, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport buildReport) (at /Users/bokken/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs:908)
UnityEditor.iOS.PostProcessiPhonePlayer.PostProcess (UnityEditor.iOS.PostProcessiPhonePlayer+BuildSettings bs, UnityEditor.iOS.PostProcessiPhonePlayer+ProjectPaths paths, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport buildReport) (at /Users/bokken/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs:718)
UnityEditor.iOS.PostProcessiPhonePlayer.PostProcess (UnityEditor.iOS.PostProcessorSettings postProcessorSettings, UnityEditor.Modules.BuildPostProcessArgs args) (at /Users/bokken/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/BuildPostProcessor.cs:663)
UnityEditor.iOS.iOSBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at /Users/bokken/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/ExtensionModule.cs:45)
Rethrow as BuildFailedException: Exception of type 'UnityEditor.Build.BuildFailedException' was thrown.
UnityEditor.iOS.iOSBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at /Users/bokken/buildslave/unity/build/PlatformDependent/iPhonePlayer/Extensions/Common/ExtensionModule.cs:49)
UnityEditor.Modules.DefaultBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at /Users/bokken/buildslave/unity/build/Editor/Mono/Modules/DefaultBuildPostprocessor.cs:29)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:337)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)
```
