### ISSUE TITLE
return object metadata from TransferUtility.UploadAsync

### ISSUE THREAD

**Issue by hauntingEcho** [aws/aws-sdk-net#1723]
## Describe the Feature
After calling `TransferUtility.UploadAsync`, I need a handler to the thing I've just uploaded.  In particular, `versionId` is needed to request the same version of the object and is assigned during the upload.

### Is your Feature Request related to a problem?
This would greatly simplify supporting versioned S3 objects for Serverless artifacts: https://github.com/aws/aws-extensions-for-dotnet-cli/issues/141

## Proposed Solution
Return a metadata object of the common properties in underlying calls.  Going by [CompleteMultipartUploadResponse](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/S3/TCompleteMultipartUploadResponse.html) and [PutObjectResponse](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/S3/TPutObjectResponse.html), this would include versionId & ETag.

---

This is a :rocket: Feature Request

**Comment by ashishdhingra** [comment]
Appears to be the valid feature request. However, not sure whether this is feasible without breaking existing customer. This needs discussion with the team.

**Comment by hauntingEcho** [comment]
Going from a [Task](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task?view=net-5.0) to a [Task<TResult>](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task-1?view=net-5.0) return type shouldn't cause breakages, since the parameterized version inherits from the one [currently used](https://github.com/aws/aws-sdk-net/blob/475822dec5e87954b7a47ac65995714ae1f1b115/sdk/src/Services/S3/Custom/Transfer/_async/TransferUtility.async.cs#L182).
