### ISSUE TITLE
DynamoDBContext SaveAsync - How to prevent a field from being overwritten

### ISSUE THREAD

**Issue by RichieRunner** [aws/aws-sdk-net#1725]
## The Question
[I understand that SaveAsync method on the DynamoDBContext class level will create an item if it doesn't exist, and update the item if the item already exists](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DotNetDynamoDBContext.html#w20aac17c17c21c35c33).

My use case is that I have a DateAdded field on the table that is intended to only be updated on new item creation, and should not be updated thereafter. How can I continue to use SaveAsync so that it continue to update existing items for me, but just ignore this one DateAdded field so that it doesn't get overwritten with a new date or null?

### Environment

* SDK Version: 3.5.0-beta
* Package Version: 3.5.0-beta
* OS Info: Windows 10
* Build Environment Visual Studio
* Targeted .NET Platform:  .NET Core 3.1

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @RichieRunner,

I'm not sure if I understand your question properly, while saving, if you don't set the property for a field, it would not be overwritten. Consider the below example (assuming you have the table `ProductCatalog` in the default region determined by the client):
```C#
using System;
using System.Collections.Generic;
using Amazon.DynamoDBv2;
using Amazon.DynamoDBv2.DataModel;
using Amazon.Runtime;

namespace DynamoDbTest
{
    class HighLevelItemCRUD
    {
        private static AmazonDynamoDBClient client = new AmazonDynamoDBClient();

        static void Main(string[] args)
        {
            try
            {
                DynamoDBContext context = new DynamoDBContext(client);
                TestCRUDOperations(context);
                Console.WriteLine("To continue, press Enter");
                Console.ReadLine();
            }
            catch (AmazonDynamoDBException e) { Console.WriteLine(e.Message); }
            catch (AmazonServiceException e) { Console.WriteLine(e.Message); }
            catch (Exception e) { Console.WriteLine(e.Message); }
        }

        private static void TestCRUDOperations(DynamoDBContext context)
        {
            int bookID = 1001; // Some unique value.
            Book myBook = new Book
            {
                Id = bookID,
                Title = "object persistence-AWS SDK for.NET SDK-Book 1001",
                ISBN = "111-1111111001",
                DateAdded = DateTime.Now,
                BookAuthors = new List<string> { "Author 1", "Author 2" },
            };

            // Save the book.
            context.SaveAsync(myBook).GetAwaiter().GetResult();

            // Retrieve the book.
            Book bookRetrieved = context.LoadAsync<Book>(bookID).Result;

            Console.WriteLine("NEW BOOK --> " + bookRetrieved);

            // Update few properties.
            bookRetrieved.ISBN = "222-2222221001";
            bookRetrieved.BookAuthors = new List<string> { " Author 1", "Author x" }; // Replace existing authors list with this.
            context.SaveAsync(bookRetrieved).GetAwaiter().GetResult();

            // Retrieve the updated book. This time add the optional ConsistentRead parameter using DynamoDBContextConfig object.
            Book updatedBook = context.LoadAsync<Book>(bookID, new DynamoDBContextConfig
            {
                ConsistentRead = true
            }).Result;

            Console.WriteLine("UPDATED BOOK --> " + updatedBook);
        }
    }

    [DynamoDBTable("ProductCatalog")]
    public class Book
    {
        [DynamoDBHashKey] //Partition key
        public int Id
        {
            get; set;
        }

        [DynamoDBProperty]
        public string Title
        {
            get; set;
        }

        [DynamoDBProperty]
        public string ISBN
        {
            get; set;
        }

        [DynamoDBProperty]
        public DateTime DateAdded
        { get; set; }

        [DynamoDBProperty("Authors")] //String Set datatype
        public List<string> BookAuthors
        {
            get; set;
        }

        public override string ToString()
        {
            return $"[BOOK: (Id: {Id}), (Title: {Title}), (ISBN: {ISBN}), (DateAdded: {DateAdded}), (Authors: {(BookAuthors != null? string.Join(", ", BookAuthors): string.Empty)})])";
        }
    }
}
```

Running it gives the following output:
```
NEW BOOK --> [BOOK: (Id: 1001), (Title: object persistence-AWS SDK for.NET SDK-Book 1001), (ISBN: 111-1111111001), (DateAdded: 10/6/2020 4:32:38 PM), (Authors: Author 1, Author 2)])
UPDATED BOOK --> [BOOK: (Id: 1001), (Title: object persistence-AWS SDK for.NET SDK-Book 1001), (ISBN: 222-2222221001), (DateAdded: 10/6/2020 4:32:38 PM), (Authors:  Author 1, Author x)])
``` 

To prevent overwriting specific field, you could have a check to make sure `DateAdded` is set whenever a new item is added. Kindly note that DynamoDB does not automatically store created time or/last modified times of items.

I don't think there is a way to selectively tell `SaveAsync` method to update the field only when the item is created. I also don't think triggers would help which are conceptually different from RDBMS triggers, where for DynamoDb, it would basically execute a Lambda function.

Hope this helps and let me know if this issue could be closed.

Thanks,
Ashish

**Comment by RichieRunner** [comment]
Hi Ashish, thanks for the detailed example. The difference in our usage is that I don't do a `LoadAsync` to get a `bookRetrieved` back before I do a 2nd `SaveAsync`. 

My 2nd `SaveAsync` always assumes that the item does not already exist. Therefore, the `DateAdded` property is always initialized to the current `DateTime`. I'm wanting to know if DynamoDBContext will allow me to not update a field like `DateAdded` if the record already exists.

**Comment by ashishdhingra** [comment]
Hi @RichieRunner,

I'm not sure if I understand your approach properly, I made the following changes to code:

```C#
private static void TestCRUDOperations(DynamoDBContext context)
{
        int bookID = 1001; // Some unique value.
        Book myBook = new Book
        {
        Id = bookID,
        Title = "object persistence-AWS SDK for.NET SDK-Book 1001",
        ISBN = "111-1111111001",
        DateAdded = DateTime.Now,
        BookAuthors = new List<string> { "Author 1", "Author 2" },
    };

    // Save the book.
    context.SaveAsync(myBook).GetAwaiter().GetResult();

    Console.WriteLine("SAVED BOOK --> " + myBook);

    // Retrieve the book.
    //Book bookRetrieved = context.LoadAsync<Book>(bookID).Result;

    //Console.WriteLine("NEW BOOK --> " + bookRetrieved);

    // Update few properties.
    myBook.ISBN = "222-2222221001";
    myBook.BookAuthors = new List<string> { " Author 1", "Author x" }; // Replace existing authors list with this.
    context.SaveAsync(myBook).GetAwaiter().GetResult();

    // Retrieve the updated book. This time add the optional ConsistentRead parameter using DynamoDBContextConfig object.
    Book updatedBook = context.LoadAsync<Book>(bookID, new DynamoDBContextConfig
    {
        ConsistentRead = true
    }).Result;

    Console.WriteLine("UPDATED BOOK --> " + updatedBook);
}
```

Notice that I'm not re-loading the book instance, instead modifying the some of the properties and then re-saving. I get the following output:
```
SAVED BOOK --> [BOOK: (Id: 1001), (Title: object persistence-AWS SDK for.NET SDK-Book 1001), (ISBN: 111-1111111001), (DateAdded: 10/7/2020 4:04:11 PM), (Authors: Author 1, Author 2)])
UPDATED BOOK --> [BOOK: (Id: 1001), (Title: object persistence-AWS SDK for.NET SDK-Book 1001), (ISBN: 222-2222221001), (DateAdded: 10/7/2020 4:04:11 PM), (Authors:  Author 1, Author x)]
```

In this case we are not touching the DateAdded field in the 2nd call (setting it to `DateTime.Now` in first call assigns the current DateTime value which doesn't change). Behind the scenes DynamodDB is updating the item attributes since it already exists.

You might also want to check [DynamoDB UpdateItem API reference](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html) where it also talks about conditional updates. I'm not sure how that would fit to your scenario and I didn't test it using `DynamoDbContext.SaveAsync` 2nd overload.

Hope this helps.

Thanks,
Ashish

**Comment by RichieRunner** [comment]
I want to return back to answer how I handled this situation. My initial quandary came from not wanting to do an initial query/lookup for the value before invoking `SaveAsync`. I understand now that the best practice before saving an item to DynamoDB (or saving an existing item **back** to DynamoDB) is to that do that requisite query so that you hold the full object with its full attributes before writing it back to DynamoDB.

This issue can be closed.
