### ISSUE TITLE
IoT-Data not using expected credentials

### ISSUE THREAD

**Issue by AdamLewisGMSL** [aws/aws-sdk-net#1726]
## Description
We recently had a bit of a headscratcher problem where we were trying to use AmazonIotDataClient/AwsIotDataClient to publish a message in some local tests. As per https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-creds.html we were trying to pass in AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_SESSION_TOKEN environment variables but only the first two were being used.

Publish was returning an exception with "The client used an Server Name Indication (SNI) that is not associated with this account." and cross referencing Fiddler/Chrome we noticed that the X-Amz-Security-Token header was missing, once we started creating our own SessionAWSCredentials and manually passing it however the code started to work again.

### Environment

* Latest SDK & IotData package
* OS Info: Windows 10
* Build Environment Visual Studio 
* Targeted .NET Platform:  .NET Core 3

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @AdamLewisGMSL,

Good afternoon.

Thanks for reporting the issue. Although I understand the issue, request you to provide some code snippet to troubleshoot the issue. 

Regards,
Ashsih

**Comment by AdamLewisGMSL** [comment]
`
Environment.SetEnvironmentVariable("AWS_REGION", "eu-central-1", EnvironmentVariableTarget.Process);
Environment.SetEnvironmentVariable("AWS_ACCESS_KEY_ID", "ABC", EnvironmentVariableTarget.Process);
Environment.SetEnvironmentVariable("AWS_SECRET_ACCESS_KEY", "ABC", EnvironmentVariableTarget.Process);
Environment.SetEnvironmentVariable("AWS_SESSION_TOKEN", "ABC", EnvironmentVariableTarget.Process);

try
{
    var iot = new AmazonIotDataClient("https://abc-ats.iot.eu-central-1.amazonaws.com");

    await iot.PublishAsync(
            new PublishRequest
            {
                Topic = "Foo",
                Payload = new MemoryStream(new byte[]
                    {1, 2, 3, 4}),
            },
            CancellationToken.None);
}
catch (Exception e)
{
    Console.WriteLine(e);
    throw;
}
`

Was running this within an NUnit 3 test if that at any point becomes relevant

**Comment by ashishdhingra** [comment]
Hi @AdamLewisGMSL,

I'm not sure what's the issue in your scenario, when I debug using Visual Studio, I do see that the Credentials property of IOT client is correctly set to [EnvironmentVariablesAWSCredentials](https://github.com/aws/aws-sdk-net/blob/7ce5e80f1db180054e1f77acd4ac865abdc112c9/sdk/src/Core/Amazon.Runtime/Credentials/EnvironmentVariablesAWSCredentials.cs#L32) object:

<img width="699" alt="Screen Shot 2020-10-08 at 10 23 37 AM" src="https://user-images.githubusercontent.com/67916761/95492900-96fb0900-0950-11eb-8fd1-b21b6176cfd3.png">

I'm unable to validate through Visual Studio debugger if the credentials are set properly, though. The credentials are resolved using the [FallbackCredentialsFactory](https://github.com/aws/aws-sdk-net/blob/7ce5e80f1db180054e1f77acd4ac865abdc112c9/sdk/src/Core/Amazon.Runtime/Credentials/FallbackCredentialsFactory.cs#L57).

Thanks,
Ashish

**Comment by normj** [comment]
The SDK's logic for finding the session token is right with the logic to get the access key id and secret key. So if it is using the environment variables to get the access key and secret key then session token should be found as well.

https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Credentials/EnvironmentVariablesAWSCredentials.cs#L66-L90

I wonder if in your environment you have an AWS credentials profile called default or is the AWS_PROFILE environment variable set to a profile? When the SDK searches for credentials it will use the the default profile first before falling back to environment variables.

**Comment by AdamLewisGMSL** [comment]
Ah that would be it. There is a default profile set up in the config file - the ordering must be set up this way.

Thanks!
