### ISSUE TITLE
AppSync Lambda resolver dotnet sample

### ISSUE THREAD

**Issue by thesobercoder** [aws/aws-sdk-net#1727]
## Describe the Feature
AppSync Lambda resolver dotnet sample

### Is your Feature Request related to a problem?
Can't find one official docs about this topic. Please provide an example.

**Comment by ashishdhingra** [comment]
Hi @thesobercoder,

Good afternoon.

The article [Tutorial: AWS Lambda Resolvers](https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-lambda-resolvers.html) provides an example on how to use AppSync with AWS Lambda. It talks about having Lambda expose set of operations. On the similar lines, I came across the useful post [AWS: AppSync with Lambda Resolver for MongoDB using DotNet core](https://www.codefari.com/2019/12/aws-appsync-with-lambda-resolver-for.html) which lists step by step example for using AppSync with Lambda (**NOTE:** Kindly use this article as a reference, not as the actual production code).

Please let me know if this helps and if this issue could be closed.

Thanks,
Ashish
