### ISSUE TITLE
GetPreSignedURL completely different 

### ISSUE THREAD

**Issue by cocosip** [aws/aws-sdk-net#1729]
### Environment

* SDK Version: 
* Package Version: 
* OS Info: 
* Build Environment 
* Targeted .NET Platform:  

When i use `AWSSDK.S3`  v3.5.1+  call method GetPreSignedURL,  the result is completely different.

Here is my code:
```c#
var client =new AmazonS3Client("ak","sk", new AmazonS3Config(){
    ServiceURL="http://ks3-cn-beijing.ksyun.com",
    SignatureVersion="2.0"
});

 var url = GetClient().GetPreSignedURL(new GetPreSignedUrlRequest()
{
        BucketName = "bucket1",
        Key = key,
        Expires = DateTime.Now.AddMinutes(5),
});
```
result:
```
https://bucket1.ks3-cn-beijing.ksyun.com/100001/100001001/20191203/5de6040ec3b3175954a29581.dcm?AWSAccessKeyId=AKLTtDqcvpxGQ1-z8gpH6lKGkw&Expires=1602733886&Signature=Py7TKbkH1vvCjGfKlW%2FuGir7Sls%3D
```

but when ServiceURL is  `http://ks3-cn-beijing-2.ksyun.com`
the result is completely different 

```
https://bucket1.ks3-cn-beijing-2.ksyun.com/100001/100001001/20191203/5de6040ec3b3175954a29581.dcm?X-Amz-Expires=300&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKLTtDqcvpxGQ1-z8gpH6lKGkw/20201015/cn-beijing-32/s3/aws4_request&X-Amz-Date=20201015T014435Z&X-Amz-SignedHeaders=host&X-Amz-Signature=637745eddca446d2c3c2c8e631968fa1f8fbfb3dd99f4034a1cfa8a41089584a
```
It seem  signature-version does not work.

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @cocosip,

Thanks for posting the guidance question. Could you please try changing the `SignatureVersion` to `2` and confirm if it works? Please refer the code https://github.com/aws/aws-sdk-net/blob/7c88eeceb52869892adb1fe50c3f06c8f1a6b126/sdk/src/Core/Amazon.Runtime/Internal/Auth/AbstractAWSSigner.cs#L94 for reference, looks like SDK is expecting the whole number string.

Thanks,
Ashish

**Comment by cocosip** [comment]
> Hi @cocosip,
> 
> Thanks for posting the guidance question. Could you please try changing the `SignatureVersion` to `2` and confirm if it works? Please refer the code
> 
> https://github.com/aws/aws-sdk-net/blob/7c88eeceb52869892adb1fe50c3f06c8f1a6b126/sdk/src/Core/Amazon.Runtime/Internal/Auth/AbstractAWSSigner.cs#L94
> 
> for reference, looks like SDK is expecting the whole number string.
> Thanks,
> Ashish

I add a endpoint.json to resolve this problem. Thank you!
``` json
"defaults": {
        "hostname": "{service}.{region}.{dnsSuffix}",
        "protocols": [ "http" ],
        "signatureVersions": [ "v2" ]
      },
```
