### ISSUE TITLE
DynamoDB QueryAsync Performance

### ISSUE THREAD

**Issue by hashitha** [aws/aws-sdk-net#173]
i have the following statement

`
AsyncSearch<Appointment> AppointmentSearch = context.QueryAsync<Appointment>("13-02-2015");
`

This statement takes about 5 seconds to run when the application is first run, within this time the ui is not responsive. Any calls after the first call it runs very fast. 

The query itself is very fast. its only this statement and only on the first call.

**Comment by PavelSafronov** [comment]
The reason for the slow first call is that this is the first time the `DynamoDBContext` is working with this particular table, so it makes a `DescribeTable` call, then caches the result. This is the reason that the first operation is slower, there is a service call happening.

You can "pre-load" a table by making the below call at any time before the `QueryAsync` call (for instance, in an async call at the start of the application).

`
context.GetTargetTable<Data>();
`

The above call will retrieve the table associated with the `Data` class (replace this with your own class) and will cache this information in the `context` instance. From this point, calls to `QueryAsync` will be very fast.

**Comment by hashitha** [comment]
Thanks that works.

this is what i have done. I run this when the app is first opened so is it okay to run the queryasync while this is running? e.g. user clicks load data soon as he opens the app and this method is still running.

AmazonDynamoDBClient client = CommonUtils.getDynamoDBClient();
var context = new DynamoDBContext(client);

await Task.Run(() =>
{
     context.GetTargetTable<Appointment>();
});

**Comment by PavelSafronov** [comment]
As long as you keep both the client and the context around for the lifecycle of the application, this is a good approach to making sure the table information is retrieved before you make any calls.

**Comment by hashitha** [comment]
if i do keep the client and context for the lifecycle of the application can they be used by multiple threads running at the same time or is that bad?

**Comment by PavelSafronov** [comment]
Both the DynamoDB client (as well as all the other service clients) and the `DynamoDBContext` are thread safe, so they can be used across different threads at the same time.

In fact, since `DynamoDBContext` retrieves and caches table descriptions, it's a good idea to keep it around as long as possible to avoid retrieving the same information over and over again. This is also true of the `Amazon.DynamoDBv2.DocumentModel.Table` objects: the best approach is to keep the `Table` objects around as long as possible.

**Comment by hashitha** [comment]
That is great and Thanks a lot for all the info Pavel.

**Comment by gpomykala** [comment]
What is the recommendation in Lambda scenario? They are short lived by definition and that first DescribeTable call results in a noticeable latency (~400ms). Why DescribeTable takes more time that the actual query (~100ms)?
