### ISSUE TITLE
Found the following error while initiating DynamoDB Context in AWSSDK.DynamoDBv2 to 3.5.13

### ISSUE THREAD

**Issue by ultrma** [aws/aws-sdk-net#1730]
## Description
We are having to trouble to update AWSSDK.DynamoDBv2 to 3.5.13 with AWSSDK.Core 3.5.1.25. 
When we run the application to initiate DynamoDBContext, we always get such error.

**Exception**
System.MissingMethodException: Method not found: 'Amazon.Runtime.RequestRetryMod
e Amazon.Runtime.IClientConfig.get_RetryMode()'.
   at Amazon.DynamoDBv2.AmazonDynamoDBClient.CustomizeRuntimePipeline(RuntimePip
eline pipeline)
   at Amazon.Runtime.AmazonServiceClient.BuildRuntimePipeline()
   at Amazon.Runtime.AmazonServiceClient..ctor(AWSCredentials credentials, Clien
tConfig config)
   at Amazon.DynamoDBv2.AmazonDynamoDBClient..ctor()
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext..ctor()
   at TestDynamoDB.Program.Main(String[] args) in C:\temp\TestDynamoDB\Program.c
s:line 15

**Source Code**
try
{
  var dynamoContext = new DynamoDBContext();

}
catch (Exception ex)
{
  Console.WriteLine(ex.ToString());
}

## Reproduction Steps
1. Build a windows console application with .NET Framework 4.6.1
2. Deploy to windows 2012 server on AWS EC2

### Environment

* SDK Version / PackageVersion: AWSSDK.DynamoDBv2 to 3.5.13 with AWSSDK.Core 3.5.1.25
* OS Info: Windows 2012 R2
* Build Environment: VS 2019 Pro
* Targeted: .NET Framework version: 4.6.1
* Application type: Windows Console Application
* The server is hosted on AWS EC2 instance.

Prior to update, we are good to run our application with AWSSDK.DynamoDBv2 3.3.4.9 with AWSSDK.Core 3.3.102.2 at the same environment. And we are also good to run with new DynamoDB update on developers’ windows 10 pro local machine. I am not sure why this is different in Windows 2012 server.

**Comment by ashishdhingra** [comment]
Hi @ultrma,

Good morning.

Thanks for reporting the issue. At high level, it appears to be dependency issue due to conflicting versions. Similar issues https://github.com/aws/aws-sdk-net/issues/1652 (3.3.107.19) and https://github.com/aws/aws-sdk-net/issues/1662 (3.3.111.27) were self-resolved by users. Could you please check if there are any conflicting dependencies? Also, it would be helpful if you could share your sample solution to troubleshoot the issue.

Thanks,
Ashish

**Comment by ultrma** [comment]
> Hi @ultrma,
> 
> Good morning.
> 
> Thanks for reporting the issue. At high level, it appears to be dependency issue due to conflicting versions. Similar issues #1652 (3.3.107.19) and #1662 (3.3.111.27) were self-resolved by users. Could you please check if there are any conflicting dependencies? Also, it would be helpful if you could share your sample solution to troubleshoot the issue.
> 
> Thanks,
> Ashish

Hi Ashish,

Thanks for checking with me. 
I have checked the version compatibility by NuGet. I think AWSSDK.DynamoDBv2 to 3.5.13 with AWSSDK.Core 3.5.1.25 are matched.
![image](https://user-images.githubusercontent.com/17281511/96293505-b7097880-0f9f-11eb-8a4c-d0d847701d92.png)

Could you elaborate the right solution from that two tickets?
Thank you. 
#1652 (3.3.107.19) and #1662 (3.3.111.27)

**Comment by ashishdhingra** [comment]
Hi @ultrma,

I used the below code and deployed the console application to `Windows Server 2012 R2` EC2 instance, and unable to reproduce the issue.

```C#
using Amazon.DynamoDBv2.DataModel;
using System;

namespace DynamoDbTest
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                Console.WriteLine("START: Creating DynamoDbContext object.");
                var dynamoContext = new DynamoDBContext();
                Console.WriteLine("Finished: Creating DynamoDbContext object.");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }

            Console.ReadLine();
        }
    }
}
``` 
**.csproh file**
```XML
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{768C0182-4E72-4804-814D-6F451631921D}</ProjectGuid>
    <OutputType>Exe</OutputType>
    <RootNamespace>DynamoDbTest</RootNamespace>
    <AssemblyName>DynamoDbTest</AssemblyName>
    <TargetFrameworkVersion>v4.6.1</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <Deterministic>true</Deterministic>
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <PublishUrl>publish\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Disk</InstallFrom>
    <UpdateEnabled>false</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ApplicationRevision>1</ApplicationRevision>
    <ApplicationVersion>1.0.0.%2a</ApplicationVersion>
    <UseApplicationTrust>false</UseApplicationTrust>
    <PublishWizardCompleted>true</PublishWizardCompleted>
    <BootstrapperEnabled>true</BootstrapperEnabled>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup>
    <ManifestCertificateThumbprint>F9FBD6FDD0F101D2E3E8897746798E670C5193C1</ManifestCertificateThumbprint>
  </PropertyGroup>
  <PropertyGroup>
    <ManifestKeyFile>DynamoDbTest_TemporaryKey.pfx</ManifestKeyFile>
  </PropertyGroup>
  <PropertyGroup>
    <GenerateManifests>true</GenerateManifests>
  </PropertyGroup>
  <PropertyGroup>
    <SignManifests>true</SignManifests>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="AWSSDK.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604, processorArchitecture=MSIL">
      <HintPath>..\packages\AWSSDK.Core.3.5.1.25\lib\net45\AWSSDK.Core.dll</HintPath>
    </Reference>
    <Reference Include="AWSSDK.DynamoDBv2, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604, processorArchitecture=MSIL">
      <HintPath>..\packages\AWSSDK.DynamoDBv2.3.5.1.3\lib\net45\AWSSDK.DynamoDBv2.dll</HintPath>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="App.config" />
    <None Include="DynamoDbTest_TemporaryKey.pfx" />
    <None Include="packages.config" />
  </ItemGroup>
  <ItemGroup>
    <Analyzer Include="..\packages\AWSSDK.DynamoDBv2.3.5.1.3\analyzers\dotnet\cs\AWSSDK.DynamoDBv2.CodeAnalysis.dll" />
  </ItemGroup>
  <ItemGroup>
    <BootstrapperPackage Include=".NETFramework,Version=v4.6.1">
      <Visible>False</Visible>
      <ProductName>Microsoft .NET Framework 4.6.1 %28x86 and x64%29</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```

<img width="1115" alt="Screen Shot 2020-10-16 at 11 13 40 AM" src="https://user-images.githubusercontent.com/67916761/96294952-03ee4e80-0fa2-11eb-877b-aa5bec3c0591.png">

Thanks,
Ashish

**Comment by ultrma** [comment]
Hi Ashish, thanks for verifying this.

I guess there is something wrong with our current environment. 
Let me dig more information from that server.
