### ISSUE TITLE
Support for Provision IOT Thing in Client using Provisioning Template and Certificates 

### ISSUE THREAD

**Issue by purusartha** [aws/aws-sdk-net#1736]
## The Question
I am working on a project where we need to provision heaps of devices (Android devices build using Xamarin). The provisioning template name and provisioning certificates are known. Other than that, no other AWS credentials are known. There are a few samples available [here](https://github.com/aws-samples/aws-iot-fleet-provisioning) but non of them use the AWS SDKs. I explored the following sdks, but each uses accessKeyId/accessKeySecret:
AWSSDK.Iot
ASWSDK.IotData

Furthermore, [there were no official .net device sdks Aug, 2018](https://github.com/aws/aws-sdk-net/issues/1023). I am wondering if there has been any work done since.

I am currently using m2mqtt client in xamarin, but it seems to be quite unstable. Any guidance is much appreciated. 

### Environment

Windows 10  
Visual Studio 
Targeted .NET Platform:  .net standard 2.1, Xamarin

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @purusartha,

Good morning.

Thanks for posting guidance question. I don't see any listing for IOT Device SDK for .NET on the page [AWS IoT Device and Mobile SDKs](https://docs.aws.amazon.com/iot/latest/developerguide/iot-sdks.html). The device SDKs are managed by separate team, the best course of action is to click **Provide feedback** on the bottom of the page to submit a query.

That said, there is a package [AWSSDK.IoT](https://www.nuget.org/packages/AWSSDK.IoT/) on NuGet, but that is merely a wrapper for [AWS IoT Service API](https://docs.aws.amazon.com/iot/latest/apireference/Welcome.html), and as you might be aware, all service APIs required AccessKeyId and AccessKeySecret part to invoke API operations.

Hope this answers your question or may be points you to right direction.

Thanks,
Ashish
