### ISSUE TITLE
VisualStudio CloudFormation template editor shows key is invalid for this object

### ISSUE THREAD

**Issue by etoh91** [aws/aws-sdk-net#1737]
## Description
Visual Studio v1.18.1.0 for Cloudformation is throwing 'xxx key is invalid for this object" for "HttpParameters" and "QueryStringParameters" when trying to create EventBridge/Event Rules resource. Here's a screenshot:
![image](https://user-images.githubusercontent.com/74193507/98550969-c2805480-226a-11eb-86b8-f6f3e825bfd6.png)

## Reproduction Steps
These are valid properties according to documentation for EventBridge/Event Rules (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_Events.html). Similar issues for other scenarios:
1. https://github.com/aws/aws-sdk-net/issues/663
2. https://github.com/aws/aws-sdk-net/issues/133

---

Visual Studio Version: 2017/2019
AWS Toolkit for Visual Studio Version: v1.18.1.0

**Comment by ashishdhingra** [comment]
Hi @etoh91,

Good afternoon.

Could you please attach the complete template to this ticket? Looking at high level, it appears to be issue.

Thanks,
Ashish

**Comment by etoh91** [comment]
This is just for this resource that's part of a bigger template. Thanks. 

[eventbridge.json.zip](https://github.com/aws/aws-sdk-net/files/5513762/eventbridge.json.zip)

**Comment by etoh91** [comment]
> Hi @etoh91,
> 
> Good afternoon.
> 
> Could you please attach the complete template to this ticket? Looking at high level, it appears to be issue.
> 
> Thanks,
> Ashish

This is just for this resource that's part of a bigger template. Thanks.

[eventbridge.json.zip](https://github.com/aws/aws-sdk-net/files/5513764/eventbridge.json.zip)

**Comment by etoh91** [comment]
@ashishdhingra checking on update. Thanks!

**Comment by ashishdhingra** [comment]
> @ashishdhingra checking on update. Thanks!

Hi @etoh91,

Good morning.

I will discuss with the developer and get this prioritized.

Thanks,
Ashish

**Comment by ashishdhingra** [comment]
Assigned to @normj.

**Comment by normj** [comment]
A new version of the CloudFormation schema has been released which fixes this issue. You should automatically see the change after restarting Visual Studio.
