### ISSUE TITLE
Unity UWP app using AWS .NET SDK functions fails with COM/Il2CppExceptionWrapper exceptions

### ISSUE THREAD

**Issue by dave-trainor** [aws/aws-sdk-net#1740]
I've imported the .NET SDK **V3.3** DLLs and the Amazon Cognito Authentication Extension DLL into a Unity 2020.1 project and created an app that authenticates with Cognito and then accesses a DynamoDB table. I cannot currently use the latest .NET SDK version 3.5 in this Unity app due to #1722 . The Unity app works fine in the Unity Editor and when built as a PC Standalone app. However when it is built in Unity and executed as a UWP app it fails, generated many COM "class not registered" exceptions, followed by many "Il2CppExceptionWrapper at memory location" exceptions before terminating. I did construct a Unity linker file to prevent assembly stripping as outlined [here](https://aws.amazon.com/blogs/developer/referencing-the-aws-sdk-for-net-standard-2-0-from-unity-xamarin-or-uwp/).

Any ideas or advice on why this is happening would be very welcome.

**Comment by dave-trainor** [comment]
I can confirm that a similar issue appears when using the .NET 4.5 DLLs from the latest AWS .NET SDK 3.5.62 and the Amazon Cognito Authentication Extension DLL into a Unity 2020.1 project.

**Comment by dave-trainor** [comment]
Any update on this? I have a commercial project  that's trying to use this feature and if I can't get a resolution soon I'll need to look at alternative technologies. Can you confirm that someone somewhere has built a working Unity app for the Unified Windows Platform using a modern version of Unity, the IL2CPP Unity scripting backend, and a modern version of the AWS .NET SDK? Amazon articles such as [this ](https://aws.amazon.com/blogs/developer/referencing-the-aws-sdk-for-net-standard-2-0-from-unity-xamarin-or-uwp/) suggest that it's possible, but none of these examples work as Unified Windows Platform apps (at least for me).

**Comment by ashishdhingra** [comment]
Need to revisit this issue once #1722 is addressed.

**Comment by ashishdhingra** [comment]
Hi @dave-trainor,

Good afternoon.

Now that issues #1722 is addressed, could you please try upgrading to AWS .NET SDK 3.5 version and see if issue is fixed.

Thanks,
Ashish
