### ISSUE TITLE
UWP Not Connecting To S3, but works fine in Unity Player

### ISSUE THREAD

**Issue by HeckDotExe** [aws/aws-sdk-net#1742]
## Description
I've been trying to get a program I made in Unity to simply read a line of text from a file I've stored in my totally public S3 bucket, and it works perfectly in the Unity Editor (will return the data in a timely manner etc.) But when I build the application to UWP so I can port it over to my HoloLens (although I have tested it just on my local machine, as well, which resulted in failure) it results in the following error:
**Curl error 6: Could not resolve host (my bucket name).s3.amazon.com.** 
It comes up after the program makes about 100 unsuccessful requests, as the Curl error message limit gets reached.
Like I said, it's not a problem on the bucket end, since it works just fine in the Unity Editor, so I think it's a problem with UWP processing the AmazonS3Client.GetObjectAsync() method.

## Reproduction Steps

Here's the code I have:
```C#
 private AWSCredentials Credentials
      {
          get
          {
              if (_credentials == null)
                
               _credentials = new Amazon.Runtime.BasicAWSCredentials("(my access key)", "(my secret key)");
              return _credentials;
          }
      }
 private IAmazonS3 Client
    {
        get
        {
            if (_s3Client == null)
            {
                _s3Client = new AmazonS3Client(Credentials, RegionEndpoint.USEast1);
            }
            //test comment
            return _s3Client;
        }
    }
void GetObject()
{
 _s3Client.GetObjectAsync(S3BucketName, SampleFileName, (responseObj) =>
            {
                string data = null;
                var response = responseObj.Response;
                Debug.Log("Reponse: " + responseObj.Response);
                if (response.ResponseStream != null)
                {
                    using (StreamReader reader = new StreamReader(response.ResponseStream))
                    {
                        data = reader.ReadToEnd();
                    }

                    ResultText.text += "\n";
                    ResultText.text += data;

                }
                Debug.Log(data);
}
```

### Logs

There's typically a wait before all of the requests (I think they're called that?) fail at once. Once they do this is the resulting log times a hundred:

[(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Exception thrown at 0x749D4662 in MyProgramName.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x1D2EF764.
Exception thrown at 0x749D4662 in MyProgramName.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x217FF2E4.](url)

### Environment

* SDK Version: 3.5.1.36
* Package Version: 3.5.4 for S3, if that's what this is asking (Sorry, I'm new w/ this) 
* OS Info: Windows 10 Home Edition
* Build Environment Visual Studio 2019
* Targeted .NET Platform:  UWP, deploying to x86
Trying to deploy to HoloLens 1
Unsure of where the AWSSDK packages are always supposed to be, so I have them in both the built version and the scripts in unity 

## Resolution
If you have any tips or suggestions, please let me know! I'm trying to get this finished relatively soon, and this bug has put me in a tight spot since I thought it was working.
Thank you very much for your help!!

---

This is a :bug: bug-report

**Comment by dave-trainor** [comment]
That blizzard of Il2CppExceptionWrapper exceptions is similar to what I see in my UWP (Unity) app. See issue #1740

**Comment by ashovlin** [comment]
Sorry we're getting back to this so late, but in case you or anyone is still looking for Unity + UWP guidance - I was able to get similar code snippet working with S3 via the following.

**Unity Version:** 2019.4.17f1
**AWS SDK:** Version 3.7.38 of the `netstandard2.0` DLLs
**Build Environment:** Visual Studio 2019
**Target Architecture:** x86
**Test Environment:** UWP running on Windows 10, not an actual HoloLens
**Api Compatibility Level:** .NET Standard 2.0

In my Unity project, I have a sample scene with a Text object that we'll write to with the contents of an S3 object.

In the project's `Assets` folder, I have:
1. An `Assets\AWS SDK` folder, which contains the following DLLs downloaded from [here](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/net-dg-obtain-assemblies.html)
    1. AWSSDK.Core.dll
    2. AWSSDK.S3.dll
    3. Microsoft.Bcl.AsyncInterfaces.dll
    4. System.Runtime.CompilerServices.Unsafe.dll
    5. System.Threading.Tasks.Extensions.dll
2. To avoid issues related [Manged Code Stripping](https://docs.unity3d.com/Manual/ManagedCodeStripping.html), I have `Assets\link.xml` with contents:
```
<linker>
    <assembly fullname="AWSSDK.Core" preserve="all"/>
    <assembly fullname="AWSSDK.S3" preserve="all"/>
</linker>
```
3. Then in the scene's script, I have:

```
using Amazon;
using Amazon.Runtime;
using Amazon.S3;
using System;
using System.IO;
using System.Threading.Tasks;
using UnityEngine;
using UnityEngine.UI;

public class S3Demo : MonoBehaviour
{
    public Text m_MyText;

    async Task Start()
    {
        try 
        {
            var config = new AmazonS3Config
            {
                RegionEndpoint = RegionEndpoint.USEast1
            };

            var credentials = new BasicAWSCredentials("<access key>", "<secret>");
            var client = new AmazonS3Client(credentials, config);

            var response = await client.GetObjectAsync("<bucket>", "<object key>");
            
            string data = null;
            Debug.unityLogger.Log("Reponse: " + response);

            if (response.ResponseStream != null)
            {
                using (StreamReader reader = new StreamReader(response.ResponseStream))
                {
                    data = reader.ReadToEnd();
                }

                // Update Text object with contents from S3 object
                m_MyText = GameObject.Find("Text").GetComponent<Text>();
                m_MyText.text = data;

                // Also log text
                Debug.unityLogger.Log(data);
            }
        }
        catch(Exception ex)
        {
            Debug.unityLogger.Log(ex.Message);
        }
    }
}
```
4. I have the `internetClient` capability enabled both in the _Project Settings > Player > Publishing Settings_, and in the `Package.appxmanifest` in the UWP publish folder. I was seeing HTTP exceptions until I manually added it to the manifest in addition to the project settings.


With that, I am able to rewrite the Text upon starting the scene. Let us know if this is helpful and/or you're still hitting issues. Thanks.

**Comment by marck0zz** [comment]
Hello!

I have a similar issue, but in my case I think that my problem is with getting the credentians with "TryGetAWSCredentials" (I wouldn't like to use my keys in the code) In the unity player every thing works fine but in the UWP build I can't get the credetials and so, I can't use the AWS APIs.

My code:

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System;
using System.Collections.Specialized;
using System.Configuration;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Amazon.S3;
using Amazon.S3.Model;
using Amazon.S3.Transfer;
using Amazon.Runtime.CredentialManagement;
using Amazon.Runtime;
using Amazon.S3.Util;
//using Amazon.S3.;

//using UnityEditor.PackageManager;

public class S3Test01 : MonoBehaviour
{
    public GameObject awsPanel;
    CredentialProfileStoreChain chain;
    private AmazonS3Client client;
    private AWSCredentials awsCredentials;
    private string bucketName = "a-bucket-made-with-csharp";
    private string keyName = "simpletextkey";
    private bool fileExist;
    
    void Start()
    {
        chain = new CredentialProfileStoreChain();

        if (chain.TryGetAWSCredentials("default", out awsCredentials))
        {
            client = new AmazonS3Client(awsCredentials);
            Debug.Log("Credential OK");
        }
        else
        {
            Debug.Log("Credential NO OK");
        }
    }

Unity Version: 2020.3.3f1
AWS SDK: Version 3.7.38 of the netstandard2.0 DLLs
Build Environment: Visual Studio 2019
Build Type: Executable Only (for fast iteration and local test)
Build Configuration: Release
Target Architecture: x64
Test Environment: UWP running on Windows 10 Desktop, build 19041.985
Api Compatibility Level: .NET Standard 4.X

Also, link.xml file for preserving my AWS .dlls, and "internet client" anabled in both "player settings" and "appxmanifest"

**Comment by marck0zz** [comment]
Sorry for double post

I also built it with Api Compatibility Level: .NET Standard 2.0... Same result
