### ISSUE TITLE
Visual Studio templates currupted in SDK 2.3.24.3-tk-1.9.0.0

### ISSUE THREAD

**Issue by sliedig** [aws/aws-sdk-net#175]
Hello,

weird, but it seems the latest tools for Visual Studio (2.3.24.3) have corrupted the Visual Studio project and file templates. I've attempted multiple reinstall and repair operations which have failed to resolve the issue. Here are a set of screenshot that illustrate the problems. 

**Current installation AWSToolsAndSDKForNet_sdk-2.3.23.0-ps-2.3.23.0-tk-1.8.2.1**

Fig.1: Adding a new template to Cloudformation project
![image](https://cloud.githubusercontent.com/assets/597073/6610816/bf43defc-c89f-11e4-8e94-eaf4e762f1ff.png)

Fig.2: Adding a New Project to solution
![image](https://cloud.githubusercontent.com/assets/597073/6610553/ed8b3a52-c89b-11e4-866d-09e53a55a577.png)

**After installing AWSToolsAndSet_sdk-2.3.24.3-ps-2.3.24.3-tk-1.9.0.0**

Fig.3: Adding a new template to Cloudformation project
![image](https://cloud.githubusercontent.com/assets/597073/6610610/b9e37998-c89c-11e4-8684-b565038c33d1.png)

Here the Cloudformation template is no longer available.

Fig.4: Adding a New Project.
![image](https://cloud.githubusercontent.com/assets/597073/6610620/db1a4812-c89c-11e4-9b2d-f47923194fed.png)

The AWS category only contains the Cloudformation and new Lamda project types. All the other sub category templates are distributed under C# templates.

Ultimately I just reverted to the previous version which does not have these issues. Not 100% is this is isolated case, suffice to say I have not had an upgrade issue before.

**Comment by normj** [comment]
Thanks for letting us know. We have reproduced the issue and we are working on a fix.

**Comment by sliedig** [comment]
Still an issue in version 2.3.26.0-ps-2.3.26.0-tk-1.9.1.1, but only when Adding new item. Project templates seem to be ok.

**Comment by normj** [comment]
Yes, I reproduced the issue. I'll get the toolkit updated.

**Comment by normj** [comment]
I just released version 1.9.1.2 of the toolkit which fixes this issue. Thanks again for letting us know.

**Comment by sliedig** [comment]
Looks good. Thanks @normj
