### ISSUE TITLE
Request models should avoid relying on "Json strings" as properties

### ISSUE THREAD

**Issue by julealgon** [aws/aws-sdk-net#1750]
Some request models for various services require properties to be set as `string` representing Json. This forces developers to manually serialize objects to populate those properties, making code less clear, less strongly typed and harder to test. These properties should be exposed as strongly typed objects instead of `string`.

## Describe the Feature
Providing a more type-safe model that represents the various Amazon services would be a net benefit to managed language users (in this particular case C#). Amazon SDK clients already take care of serializing the requests internally to call a REST API, so there is a Json serializer already available to use so there is no need to put the burden on the user.

### Is your Feature Request related to a problem?
The problems I'm having are mostly related to code complexity and unit testing. Since manual serialization is required on the caller, unit tests have to start considering the Json serialization result as well, or an interface-based serialization strategy has to be implemented on consuming code.

## Proposed Solution
- Change `Amazon.SimpleEmail.Model.SendTemplatedEmailRequest`'s `TemplateData` property from `string` to `IDictionary<string, object>`
- Change `Amazon.StepFunctions.Model.StartExecutionRequest`'s `Input` property from `string` to `T` and make the class generic on `T`
- Any other similar use cases where a "Json string" is expected.

### Describe alternatives you've considered
No alternatives besides manually calling serializer libraries on the calling end.

## Additional Context
"Primitive obsession" is a code smell in strongly typed languages when there are stronger types available to use instead of `string`. Using more adequate types simplify development and make it more robust by significantly reducing the chance of invalid values being sent across. It also reduces the need to keep serializing/deserializing values back and forth, since the same representation can be passed along.

### Environment
- AWSSDK.SimpleEmail, Version=3.5.0.42
- AWSSDK.StepFunctions, Version=3.5.2.24

* [ ] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change  

---

This is a :rocket: Feature Request

**Comment by julealgon** [comment]
> We have noticed this issue has not received attention in 1 year. We will close this issue for now. If you think this is in error, please feel free to comment and reopen the issue.

I think closing this is ill-advised. By proceeding with this change, the API would become dramatically more robust, discoverable and easy to use.

The current API is pushing transport details (Json serialization) up to customer code, which is far from ideal.

**Comment by ashishdhingra** [comment]
@julealgon Upon analysis, this appears to be as per design. Most of the service model classes are auto-generated by consuming JSON models from service teams. For instance, the class [Amazon.StepFunctions.Model. StartExecutionRequest](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/StepFunctions/Generated/Model/StartExecutionRequest.cs) is generated from service model [StartExecutionInput](https://github.com/aws/aws-sdk-net/blob/03592ffc82832546c186c39fad87092880ed8bd7/generator/ServiceModels/states/states-2016-11-23.api.json#L1214), where `input` parameter of being shape [SensitiveData](https://github.com/aws/aws-sdk-net/blob/03592ffc82832546c186c39fad87092880ed8bd7/generator/ServiceModels/states/states-2016-11-23.api.json#L1198) which is of type `string`.

Since auto-generation of model classes is dependent on service models and changing any behavior would affect all the SDK(s) which would be backward incompatible, this doesn't appear to be feasible.

**Comment by julealgon** [comment]
> @julealgon Upon analysis, this appears to be as per design. Most of the service model classes are auto-generated by consuming JSON models from service teams. For instance, the class [Amazon.StepFunctions.Model. StartExecutionRequest](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/StepFunctions/Generated/Model/StartExecutionRequest.cs) is generated from service model [StartExecutionInput](https://github.com/aws/aws-sdk-net/blob/03592ffc82832546c186c39fad87092880ed8bd7/generator/ServiceModels/states/states-2016-11-23.api.json#L1214), where `input` parameter of being shape [SensitiveData](https://github.com/aws/aws-sdk-net/blob/03592ffc82832546c186c39fad87092880ed8bd7/generator/ServiceModels/states/states-2016-11-23.api.json#L1198) which is of type `string`.

Ashish, I'm aware that the .NET SDK is generated from a centralized service and that whatever the service outputs will be present in the C# model (I remember you mentioning this in some other issue I opened). However, the service in question is not open source/hosted in here, so I can't target it with this issue: I can only target the "customer facing" class, which to me is the C# abstraction.

If the issue is in the underlying central service, then it should most definitely be changed there, and not in the C# wrappers. It's not like I'm proposing a customization to the auto-generation tool to handle this during generation time, that would be indeed quite hacky.

> Since auto-generation of model classes is dependent on service models and changing any behavior would affect all the SDK(s) which would be backward incompatible, this doesn't appear to be feasible.

It wouldn't be an easy change, that's for sure, and I do realize that. It would require perhaps service versioning to migrate incrementally towards strong models and away from the raw string. Still, I think you should consider at least proposing this change to the core team to see their reaction. 

I was a consumer of these types (been several months since I've not worked directly with AWS from .NET) and as I mentioned, they are _really_ bad, non-idiomatic .NET. They probably work well in a dynamic language, in particular languages where Json is a first class element like JavaScript, but when it comes to a typed language like C#, it really is less than ideal to have to manage strings that represent more complex structures, instead of just having the complex structure in the model in the first place and abstracting the transport from the consumer. I hope you'd agree that this is a generally a bad idea and that one should favor proper classes and value types instead of treating everything as `string` (commonly known as primitive obsession). I'd also assume this exact same problem extends to other typed languages as well, like Java, so it wouldn't necessarily be an improvement only for .NET.

And from an architecture standpoint, this is also really undesirable: AWS SDK classes already have the responsibility of serializing the strong types it provides into Json to make the underlying API calls, but then it forces the consumer to _also_ have to worry about _some_ parts of the payload as Json and have the consumers themselves serialize those parts... this is just not a good way to do it.

It's up to you of course on whether or not you want to pursue this further. I personally see it as a great opportunity to make the AWS interfaces more robust, discoverable, easier to use, etc. It was a big pain for me to have to handle these Json strings in my application (I ended up creating all sorts of adapters and had to manually create the strong model myself). The more hacky code I have to write to properly interface with AWS the less I'm willing to do so, you know. And if you don't write the wrappers and the strong models, you end up leaking the bad practice from the SDK into your own codebase, something that is even worse.

**Comment by ashishdhingra** [comment]
This needs discussion with the team. With common service model classes for all SDK(s) and different languages having different types/features, not sure of this is feasible.
