### ISSUE TITLE
AmazonResourceGroupsTaggingAPIClient Paginators will loop indefinitely (always)

### ISSUE THREAD

**Issue by dorki** [aws/aws-sdk-net#1753]
## Description
The AmazonResourceGroupsTaggingAPIClient new paginators are running in an infinite loop because of a bad verification for the pagination token.

## Reproduction Steps
Just runing the 
```client.Paginators.GetResources(new GetResourcesRequest()).ResourceTagMappingList.ToReadOnlyCollectionAsync()```
will stuck in a loop forever.

this is because the pagination loop exits when the Token is NULL (like in most sdk's) but it seems that in AmazonResourceGroupsTaggingAPIClient it will always return string.Empty 
https://github.com/aws/aws-sdk-net/blob/7243a423eb694169b8261d9fa2e025bf1a6893ce/sdk/src/Services/ResourceGroupsTaggingAPI/Generated/Model/_bcl45%2Bnetstandard/GetResourcesPaginator.cs#L94

### Logs
logs are useless here but it can be very simple to notice here since the PaginationToken is string.Empty:
![image](https://user-images.githubusercontent.com/53277987/100525372-f9da8500-31c8-11eb-9dcb-7d5550d1da87.png)

### Environment
* SDK Version: 3.5.0.31
* Package Version: 3.5.0.31
* OS Info: Windows10
* Build Environment: everywhere
* Targeted .NET Platform:  core 3.1

## Resolution
this is autogenerated so I don't really know where it should be fixed

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @dorki,

Good morning.

Thanks for posting the issue. Although the issue is quite evident from the description, it would be helpful if you could share the following:
- Sample code solution to reproduce the issue.
- The resources (types) returned by the above call (while it executes indefinitely).

Thanks,
Ashish

**Comment by ashishdhingra** [comment]
While I'm unable to use the call `client.Paginators.GetResources(getResourcesRequest)` successfully (something might be wrong with my call), the following code gets the `PaginationToken` as empty string for the last response:
```C#
using Amazon.ResourceGroupsTaggingAPI;
using Amazon.ResourceGroupsTaggingAPI.Model;

namespace AmazonResourceGroupPaginator_Issue1753
{
    class Program
    {
        static void Main(string[] args)
        {
            AmazonResourceGroupsTaggingAPIClient client = new AmazonResourceGroupsTaggingAPIClient();
            string paginationToken = null;
            do
            {
                GetResourcesRequest getResourcesRequest = new GetResourcesRequest() { ResourcesPerPage = 1, PaginationToken = paginationToken ?? string.Empty };
                var getResourcesResponse = client.GetResourcesAsync(getResourcesRequest).GetAwaiter().GetResult();
                paginationToken = getResourcesResponse.PaginationToken;
            } while (paginationToken != null);
        }
    }
}
```

The [GetResources](https://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/API_GetResources.html) in Resource Groups Tagging API reference has an example that appear to return `PaginationToken` as empty string. So the above code should have the while condition as `string.IsNullOrEmpty(paginationToken)`.

**Comment by ashishdhingra** [comment]
Hi @dorki,

Looks like the fix for the issue was implemented back in Dec 2020, refer https://github.com/aws/aws-sdk-net/commit/2a0f2a27f0e57a5460def141c6d14679964ea130. Could you please verify it in the latest version of SDK and confirm if this could be closed?

Thanks,
Ashish

**Comment by dorki** [comment]
Hi @ashishdhingra,
Yep, it seems resolved. 
Thank you very much.
