### ISSUE TITLE
RDSAuthTokenGenerates NullReferenceException when ArgumentException is expected.

### ISSUE THREAD

**Issue by jon-armen** [aws/aws-sdk-net#1755]
## Description
Obtaining auth tokens from GenerateAuthToken may fail with a NullReferenceException when it should fail with an ArgumentException indicating where the fault originated.

## Reproduction Steps
1. Call RDSAuthTokenGenerator.GenerateAuthToken with a null hostname or dbUser.
2. hostname.Trim() and dbUser.Trim() will throw NullReference before ArgumentException.  The check should null coalesce.

### Logs
Object reference not set to an instance of an object.: NullReferenceException
   at Amazon.RDS.Util.RDSAuthTokenGenerator.GenerateAuthToken(AWSCredentials credentials, RegionEndpoint region, String hostname, Int32 port, String dbUser)
   at Amazon.RDS.Util.RDSAuthTokenGenerator.GenerateAuthToken(RegionEndpoint region, String hostname, Int32 port, String dbUser)
   at Amazon.RDS.Util.RDSAuthTokenGenerator.GenerateAuthToken(String hostname, Int32 port, String dbUser)

### Environment
* SDK Version: 3.3.101
* Package Version: 3.3.101
* OS Info: AWS Lambda
* Targeted .NET Platform:  dotnet 3.1

## Resolution
- [x] :wave: I can/would-like-to implement a fix for this problem myself

https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/RDS/Custom/Util/RDSAuthTokenGenerator.cs

```C#
hostname = hostname?.Trim();
if (string.IsNullOrEmpty(hostname))
    throw new ArgumentException("Hostname must not be null or empty.");

dbUser = dbUser?.Trim();
if (string.IsNullOrEmpty(dbUser))
    throw new ArgumentException("DBUser must not be null or empty.");
```

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Appears to be a bug looking at high level in the code.
