### ISSUE TITLE
AWS Recommends to extend CognitoAWSCredentials to cache IdentityID, but this is broken when using the CognitoExtensions library

### ISSUE THREAD

**Issue by 17kisern** [aws/aws-sdk-net#1757]
Hello,

In [this article](https://aws.amazon.com/blogs/developer/caching-amazon-cognito-identity-ids/) AWS Recommends for .NET users to extend the CognitoAWSCredentials library in order to actually be able to cache the IdentityID properly, however, if you use the [CognitoExtension library](https://github.com/aws/aws-sdk-net-extensions-cognito) (or any Cognito function that returns CognitoAWSCredentials) to get your actual authenticated credentials, you're required to do a downcast that **does not work with OOP.**

Due to the natural structure of how Object Oriented Programming works, you are unable to downcast the CognitoAWSCredentials received into an extended class. And since some of the values within CognitoAWSCredentials are read-only, you cannot create a conversion function.

Are there any workarounds for this for the time being? It seems that the only way for this to actually get fixed is for the AWS .NET SDK to handle it's own caching, and not rely upon the user to do so.

-- Edit --
The only guidance I've found in AWS documentation to perform Cognito Identity Pool authentication using Cognito User Pools is on [this page](https://docs.aws.amazon.com/cognito/latest/developerguide/getting-credentials.html), however this only covers anonymous/unauthenticated credentials. Additionally, [AWS's CognitoExtensions library](https://serverless-game-analytics.workshop.aws/en/introduction.html) is the only place I've found that gives an example of retrieving the CognitoAWSCredentials for authenticated users (completely different IAM Roles associated with authenticated users)

**Comment by ashishdhingra** [comment]
Hi @17kisern,

Good morning.

Thanks for posting the guidance question. Could you please share your use case? I would need to do some research on caching the IdentityID and would let you know if I find something.

Thanks,
Ashish

**Comment by 17kisern** [comment]
Hey @ashishdhingra,

My use case is utilizing AWS' .NET SDK within Unity (that has it's own peculiarities, despite conforming to the .NET standard, [this other ticket](https://github.com/aws/aws-sdk-net/issues/1722) has more info regarding that, but I don't believe that would affect this OOP issue). 
I use Cognito User Pools to facilitate user accounts (users), with Cognito Identity Pools (identities) to handle distribution/connection of the appropriate IAM roles to Unauthenticated(anonymous) and Authenticated(logged in) users accordingly. 
To perform the actual Authentication, I am using the AWS provided library [_CognitoExtensions_](https://github.com/aws/aws-sdk-net-extensions-cognito). In order to get authenticated credentials, I follow the use case outlined in the "Authenticating with Different Levels of Authentication" subsection of the ReadMe tied to that _CognitoExtensions_ Git Repo, in which a call is made to _GetCognitoAWSCredentials()_ and returns a _CognitoAWSCredentials_ object.

From what I can tell, .NET is one of the only AWS SDKs that requires the developer (me) to override this class in order to support caching of the IdentityID, while other SDKs handle this natively within that class (_CognitoAWSCredentials_). The reason caching of this IdentityID is necessary, is because if it is not cached, the number of "Total Identities" created within a Cognito Identity Pool skyrockets, making an entirely new identity every single time anonymous credentials are created, regardless of if it's the same machine. This problem because readily apparent in Unity, as a new anonymous Identity was created every single time my code re-compiled.

**Comment by ashishdhingra** [comment]
Hi @17kisern,

Upon further investigating, the article [Caching Amazon Cognito Identity IDs](https://aws.amazon.com/blogs/developer/caching-amazon-cognito-identity-ids/) talks about using Amazon Cognito Credentials Provider for caching IDs. There is an article [Amazon Cognito Credentials Provider](https://aws.amazon.com/blogs/developer/amazon-cognito-credentials-provider/) which shows on how to use credentials provider. I don't think you would be able to use the extended credentials class with [Amazon Cognito Authentication Extension Library](https://github.com/aws/aws-sdk-net-extensions-cognito) which just simplifies the Cognito authentication process. Once you get the access token from the extensions library, you can construct the extended CognitoAWSCredentials object to add access token via `AddLogin` method.

I'm not sure if this helps, but as of now, I don't have complete example which I could share and didn't test if it really works.

Thanks,
Ashish

**Comment by 17kisern** [comment]
Hey @ashishdhingra,

I was able to get it working using the links you provided (thank you! :D), for anybody else who runs into the same problem, 

**if you want to include caching with the .NET SDK, you must extend the CognitoAWSCredentials class! Doing so will make it so you can't call functions that return CognitoAWSCredentials, however, you can still get federated identities (using Cognito Identity Pools) (and in extension, IAM Roles determined by Identity Pool's RBAC; In my case, Unauth, Auth, and then a User Pool Admin group that gets picked up by a rule in the Identity Pool configuration) by manually plugging in a login provider and associated ID TOKEN (Access Token is the wrong token for this)**

Here is sample code that I am currently using, hopefully it'll save someone a few weeks.

`        public static async void LoginUserPass(string username, string password)
        {

            Debug.Log("Logging in using User/Pass");

            #region Configure Authentication Parameters

            CognitoUserPool userPool = new CognitoUserPool(
                CognitoConfig.userPoolId,
                CognitoConfig.appClientId,
                cognitoIdentityProviderClient
                );

            CognitoUser user = new CognitoUser(
                username,
                CognitoConfig.appClientId,
                userPool,
                cognitoIdentityProviderClient
                );

            InitiateSrpAuthRequest authRequest = new InitiateSrpAuthRequest()
            {
                Password = password
            };

            #endregion

            #region Actually perform the authentication

            try
            {
                AuthFlowResponse authResponse = await user.StartWithSrpAuthAsync(authRequest).ConfigureAwait(false);

                // Loading our User's Info - Irrelevant to the authentication process. This is a function I created to get User Attributes and translate them to a custom class I have
                activeUser = await GetUser(authResponse.AuthenticationResult.AccessToken, authResponse.AuthenticationResult.RefreshToken);
                Debug.Log("Loaded User: " + activeUser.username + " [" + activeUser.userID + "]");

                // // Got rid of this, because it doesn't work with extended class CognitoAWSCredentials
                // cognitoCredentials = user.GetCognitoAWSCredentials(CognitoConfig.identityPool, region);

                // Configuring CognitoAWSCredentials to know that it can pull credentials using the Access Token given by our Cognito IdentityPool
                string provider = "cognito-idp." + region.SystemName + ".amazonaws.com/" + CognitoConfig.userPoolId;
                cognitoCredentials.AddLogin(provider, authResponse.AuthenticationResult.IdToken);`

**Comment by ashishdhingra** [comment]
Hi @17kisern,

Thanks for your response and documenting your findings in this issue. This would be helpful for other users in the community. Closing this issue.

Regards,
Ashish
