### ISSUE TITLE
DynamoDB Scalar Attribute Types

### ISSUE THREAD

**Issue by phillip-haydon** [aws/aws-sdk-net#176]
Working with DynamoDB there's an enum `ScalarAttributeType` which has the values:

`N` `B` and `S`

I assume this is Number Set / Binary Set / String Set?

There's no documentation on this anywhere that I can find. 

The only thing I found was:

http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/model/ScalarAttributeType.html

And there's no descriptions. 

Can we get the enum named something better, so its useful?

**Comment by PavelSafronov** [comment]
The closest documentation for these enums is [the AttributeDefinition documentation](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_AttributeDefinition.html).

Unfortunately, renaming the enums at this point is not possible as that would be a breaking change, but we'll take a look into improving our documentation around them.

**Comment by phillip-haydon** [comment]
What about adding code comments. So the intellesese is available.

**Comment by PavelSafronov** [comment]
These enumerations are generated from the [DynamoDB service model](https://github.com/aws/aws-sdk-net/blob/master/ServiceModels/dynamodb-2012-08-10.normal.json), so it's not quite as simple as updating the corresponding .cs file, but I've added a task to our internal backlog to come up with better documentation for this and other enums in the SDK.

**Comment by phillip-haydon** [comment]
Ok thank you.

**Comment by PavelSafronov** [comment]
This is a large issue that requires internal Amazon work, so we can't add this to the public features backlog, which is used for tracking feature requests that the community can take on. We're tracking this request internally, though.
