### ISSUE TITLE
Link not working in the https://github.com/aws/aws-sdk-net#unity-support section

### ISSUE THREAD

**Issue by myonara** [aws/aws-sdk-net#1761]
The link to the unity support brings a 404, see [section](https://github.com/aws/aws-sdk-net#unity-support) and the broken [link](https://github.com/aws/aws-sdk-net/blob/master/Unity.README.md). Is Unity still supported?
---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @myonara,

We already have a `documentation` issue https://github.com/aws/aws-sdk-net/issues/1634 which is being worked upon to update the Unity Readme. The Readme that you want to refer to has moved to https://github.com/aws/aws-sdk-unity-net. As the page points out:

```
This is the archive for legacy Unity support. This repository is provided for customers who are currently using the Unity specific binaries. This repository will not be supported by the AWS SDK for .NET team; use at your own risk. Please consider migrating your app to a newer version of Unity, and use the AWS SDK for .NET - .NET Standard 2.0 binaries.
```

Hope this helps. Closing this in favor of existing documentation issue.

Thanks,
Ashish
