### ISSUE TITLE
AWS Encryption SDK for .NET

### ISSUE THREAD

**Issue by seyedk** [aws/aws-sdk-net#1762]
## Describe the Feature

Currently, AWS Encryption SDK supports the following programming languages : C, Java, JavaScript, Python, and AWS CLI and does not support .NET or .NET Core. 
Please see here: 
https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/introduction.html

### Is your Feature Request related to a problem?

We are currently in need to use the features supplied in this SDK. Without that, we need to custom develop the concept in our code.
### Describe alternatives you've considered

We have considered using a custom implementation around our current issue, by creating a data key, storing it alongside our data (or maybe in secret manager), outside of KMS using C# libraries. 

## Additional Context

Can you please tell us if there's a REST API we can use while waiting for this feature? 
### Environment

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change  

---

This is a :rocket: Feature Request

**Comment by Kunigaikstis** [comment]
Need the C# Encryption SDK as well.

**Comment by ashishdhingra** [comment]
Hi @Kunigaikstis,

Good morning.

Please see if you are looking for [aws/amazon-s3-encryption-client-dotnet](https://github.com/aws/amazon-s3-encryption-client-dotnet).

Thanks,
Ashish

**Comment by Kunigaikstis** [comment]
@ashishdhingra if this supports encryption in general, not just for S3 then yes, that would be sufficient. Primarily need the encryption SDK for encrypting data client-side for field-level encryption on DynamoDB, Neptune etc.

**Comment by slipdexic** [comment]
+1 need the C# Encryption SDK

**Comment by AmithDotKota** [comment]
+1  Yes we need C# Encryption SDK

**Comment by James-RC** [comment]
> 
> 
> Hi @Kunigaikstis,
> 
> Good morning.
> 
> Please see if you are looking for [aws/amazon-s3-encryption-client-dotnet](https://github.com/aws/amazon-s3-encryption-client-dotnet).
> 
> Thanks,
> Ashish

Hi, it is not possible.
Please see the compatibility section in:
https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/introduction.html.

+1 for .net / .net core

**Comment by pascalconfluent** [comment]
+1 for .net / .net core

**Comment by alex-chew** [comment]
Hi all, today we launched the AWS Encryption SDK for .NET.

You can find documentation on how to get started in the AWS Encryption SDK Developer Guide: https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/dot-net.html

You can also find the AWS.EncryptionSDK package itself on NuGet: https://www.nuget.org/packages/AWS.EncryptionSDK

If you have any questions or concerns, please feel free to open an issue in our GitHub repo: https://github.com/aws/aws-encryption-sdk-dafny

**Comment by ashishdhingra** [comment]
> Hi all, today we launched the AWS Encryption SDK for .NET.
> 
> 
> 
> You can find documentation on how to get started in the AWS Encryption SDK Developer Guide: https://docs.aws.amazon.com/encryption-sdk/latest/developer-guide/dot-net.html
> 
> 
> 
> You can also find the AWS.EncryptionSDK package itself on NuGet: https://www.nuget.org/packages/AWS.EncryptionSDK
> 
> 
> 
> If you have any questions or concerns, please feel free to open an issue in our GitHub repo: https://github.com/aws/aws-encryption-sdk-dafny

Closing this feature request.
