### ISSUE TITLE
Package versioning problem

### ISSUE THREAD

**Issue by chucklu** [aws/aws-sdk-net#1763]
The latest nuget version is https://www.nuget.org/packages/AWSSDK.Core/3.5.1.50, and 3.5.1.50 did not match the Semantic Versioning.
https://docs.microsoft.com/en-us/nuget/concepts/package-versioning
https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string

According the above documentation, it would be better if you can apply the rule of Semantic Versioning for package version.
https://regex101.com/r/Ly7O1x/3/

The question would be how do you define the four section of verison 3.5.1.50?

The assembly version is as following:
// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version
//      Build Number
//      Revision
//

However the nuget package version might differ from the assembly version.

**Comment by chucklu** [comment]
There is also another documentation about when to upgrade the version number
https://docs.npmjs.com/about-semantic-versioning#incrementing-semantic-versions-in-published-packages

**Comment by Kralizek** [comment]
Would this help you?

https://github.com/aws/aws-sdk-net#versioning

**Comment by chucklu** [comment]
OK, you have your own version rules.
