### ISSUE TITLE
Bucket operations an issue with C# AWSSDK.S3 client

### ISSUE THREAD

**Issue by Badb0yBadb0y** [aws/aws-sdk-net#1764]
## Description
Bucket operations an issue with C# AWSSDK.S3 client
We are having issues with bucket operations with ceph octopus 15.2.7 when using AWSSDK.S3 client.
The client library used is : AWSSDK.S3 Version 3.5.6.6
Also used an old version of client: AWSSDK Version 2.3.55.2
Used it in both .net core and simple .net projects but the same result

All methods mentioned below work perfectly fine with nodejs client 
Node js Client: https://www.npmjs.com/package/ceph
Nodejs client doc: https://github.com/YounGoat/nodejs.osapi/blob/2f9d82092589bb50e452c57131499f6d673af0f4/docs/connection.md

ALSO Note : All methods mentioned below work alright with another old version of ceph (luminous 12.2.8) with the same c# client

## Reproduction Steps, LOGS, SDK version

The client  object below is

```
new AmazonS3Client(
    "<Our_Access_Key>", 
    "<Our_Secret_Key>", 
    new AmazonS3Config {ServiceURL = "<Our_Service_Url>" } 
);

```

1.	List Buckets. 
Result: OK
Library method used : 
`client.ListBucketsAsync();`
https://i.ibb.co/W3WJKCC/1.png
 
2.	Create a New Bucket

Result: Error 405 MethodNotAllowed (You might think it’s a permission issue but it’s not, because the same creds work in nodejs)

Library method used : 
```
var request = new PutBucketRequest {BucketName = “seo”}; // seo is an existing bucket created by command line
client.PutBucketAsync(request);
```

Result error snapshot:
https://i.ibb.co/zG17VCy/2.png

3.	Create Object in an existing bucket
Result: Error 501 Not Implemented 
       Library method used : 
```
var request = new PutObjectRequest
{
    BucketName = “seo”,
    Key = “test2”,
    ContentType = "text/plain",
    ContentBody = value,
  };
client.PutObjectAsync(request);
```

We tried adding headers for content length as well but does not work as well
Result error snapshot:

https://i.ibb.co/rF419dX/3.png

4.	Read object existing in a bucket
Existing bucket name: seo
Existing object name(key): test
Result: No Such Bucket
Library code method:
```
var request = new GetObjectRequest {BucketName = “seo”, Key = “test”};
client.GetObjectAsync(request);

```
Result error snapshot:
 
https://i.ibb.co/x1Vxz0G/4.png

Thank you in advance your help.

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @Badb0yBadb0y,

Good morning.

Please refer the documentation [Amazon S3 - Operations on objects](https://docs.aws.amazon.com/AmazonS3/latest/dev/ObjectOperations.html) for details/examples of various S3 operations. The operations that you mentioned are basic S3 bucket operations and should work without any issue if there are appropriate permissions.

Please share the following details:
- I notice that you are using `ServiceURL = "<Our_Service_Url>"`, what is the value of `ServiceURL` for your case? 
- What is the region for your S3 bucket?
- Also, could you instead try using the `region` constructor overload for `AmazonS3Client`? 
- Do you (access key and secret) have sufficient permissions for your account to execute bucket operations? 

Thanks,
Ashish

**Comment by Badb0yBadb0y** [comment]
Hmm, issue solved with this flag on ceph:

rgw_relaxed_s3_bucket_names = true
