### ISSUE TITLE
Passing filter expression to request

### ISSUE THREAD

**Issue by webecker25272** [aws/aws-sdk-net#1767]
This might be simple, but I can't figure out how to pass a filter Expression to a request.  The documentation says that the GetCostAndUsageWithResources request needs a filter with the expression "SERVICE = Amazon Elastic Compute Cloud - Compute" but I'm not sure how to pass it.

@ashishdhingra

```
            AmazonCostExplorerClient client = new AmazonCostExplorerClient(awsAccessKey, awsSecretKey, RegionEndpoint.USEast1);

            //generate request headers
            GetCostAndUsageWithResourcesRequest request = new GetCostAndUsageWithResourcesRequest();
            request.TimePeriod = new DateInterval();
            request.TimePeriod.Start = DateTime.Now.AddDays(-1).ToString("yyyy-MM-dd");
            request.TimePeriod.End = DateTime.Now.ToString("yyyy-MM-dd");

            request.Granularity = Granularity.DAILY;

            request.Filter = ???;
```

**Comment by ashishdhingra** [comment]
> Amazon Elastic Compute Cloud - Compute

Hi @webecker25272,

Thanks for posting guidance question. The `GetCostAndUsageWithResourcesRequest.Filter` is of type `Amazon.CostExplorer.Model.Expression`. For the above example, you may try expression something like:

```C#
request.Filter = new Expression() { 
                Dimensions = new DimensionValues() { 
                    Key = "SERVICE",
                    Values = new List<string> { "Amazon Elastic Compute Cloud - Compute" }
                }
            };
```

Please let me know if this helps.

Thanks,
Ashish

**Comment by webecker25272** [comment]
Thank you for your help!
