### ISSUE TITLE
Slowness across all calls to AWS services

### ISSUE THREAD

**Issue by dthomas-ss** [aws/aws-sdk-net#1769]
### Environment
* SDK Version
* Package Version: 
* AWSSDK.Extensions.NETCore.Setup 3.3.100.1
* AWSSDK.DynamoDBv2 3.3.106.11
* AWSSDK.S3 3.3.104.3
* AWSDK.Kinesis 3.3.100.51
* OS Info: Ubuntu
* Build Environment: Rider, dotnet cli on MacOS Catalina
* Targeted .NET Platform: .NET Core 3.1 

---
## Slowness across all AWS services
We have been experiencing some slowness >600ms to even beyond a few seconds when calling AWS services from our .NET Core App. Not every call is slow, but it does happen often enough that it is worth investigating. There is no specific time throughout the day that the slow requests occur. Lastly, the services are running in the same region as the AWS services we are calling out to, in this case `us-west-2`.

We enabled SDK Logging and confirmed that the HttpRequestTime for various calls to AWS matches the slowness we are observing.

### Configuration
The way our services are configured are as follows in Startup.cs

```
services.AddAWSService<IAmazonS3>(new AWSOptions
                {
                    Region = RegionEndpoint.GetBySystemName(
                        appSettingsConfiguration.GetValue<string>("StorageRegion"))
                });

services.AddAWSService<IAmazonDynamoDB>(new AWSOptions
                {
                    Region = RegionEndpoint.GetBySystemName(
appSettingsConfiguration.GetValue<string>("DatabaseRegion"))
                });

services.AddSingleton<Table, Table>(d =>
            {
                return Table.LoadTable((IAmazonDynamoDB)d.GetService(typeof(IAmazonDynamoDB)), AppSettings.TableName);
            });

services.AddAWSService<IAmazonKinesis>(new AWSOptions
                {
                    Region = RegionEndpoint.GetBySystemName(
                        appSettingsConfiguration.GetValue<string>("EventStreamRegion"))
                });
```

Our appsettings file configures the SDK like this:
```
    "AWS": {
      "Profile": "our-account-profile",
      "Region": "us-west-2",
      "LogMetrics": true, // for debugging
      "LogResponse": true // for debugging
    }
```

### Logs
Kinesis example with HttpRequestTime of 1048.8336 ms
```
{"properties":{"AsyncCall":"True","CanonicalRequest":"POST\n/\n\ncontent-type:application/x-amz-json-1.1\nhost:kinesis.us-west-2.amazonaws.com\nuser-agent:aws-sdk-dotnet-coreclr/3.3.100.51 aws-sdk-dotnet-core/3.3.107.3 .NET_Core/3.1.10 OS/Linux_5.4.0-1028-aws_#29-Ubuntu_SMP_Mon_Oct_5_15:30:10_UTC_2020 ClientAsync\nx-amz-api-version:2013-12-02\<redacted>","StringToSign":"<redacted>","ServiceName":"Amazon.Kinesis","ServiceEndpoint":"https://kinesis.us-west-2.amazonaws.com/","MethodName":"PutRecordRequest","RequestSize":"24642","StatusCode":"OK","BytesProcessed":"133","AWSRequestID":"e1ef2049-c0af-0936-b99f-01914f902fca"},"timings":{"CredentialsRequestTime":0.0137,"RequestSigningTime":0.1814,"HttpRequestTime":1048.8336,"ResponseUnmarshallTime":0.0387,"ResponseProcessingTime":0.1106,"ClientExecuteTime":1049.4375},"counters":{}}
```

Dynamo example with HttpRequestTime of 1001.9114 ms
```
{"properties":{"AsyncCall":"True","CanonicalRequest":"POST\n/\n\ncontent-type:application/x-amz-json-1.0\nhost:dynamodb.us-west-2.amazonaws.com\nuser-agent:aws-sdk-dotnet-coreclr/3.3.106.11 aws-sdk-dotnet-core/3.3.107.3 .NET_Core/3.1.10 OS/Linux_5.4.0-1028-aws_#29-Ubuntu_SMP_Mon_Oct_5_15:30:10_UTC_2020 ClientAsync\nx-amz-api-version:2012-08-10\<redacted>\nx-amz-target:DynamoDB_20120810.Query\n\ncontent-type;host;user-agent;x-amz-api-version;x-amz-content-sha256;<redacted>,"StringToSign":"<redacted>","ServiceName":"Amazon.DynamoDBv2","ServiceEndpoint":"https://dynamodb.us-west-2.amazonaws.com/","MethodName":"QueryRequest","RequestSize":"386","StatusCode":"OK","BytesProcessed":"849","AWSRequestID":"6INE55ECP46VHKTAUIB219APURVV4KQNSO5AEMVJF66Q9ASUAAJG"},"timings":{"CredentialsRequestTime":0.0151,"RequestSigningTime":0.1329,"HttpRequestTime":1001.9114,"ResponseUnmarshallTime":0.1021,"ResponseProcessingTime":0.1548,"ClientExecuteTime":1002.2846},"counters":{}}
```

S3 example with HttpRequestTime of 1136.9015 ms
```
{"properties":{"AsyncCall":"True","CanonicalRequest":"PUT\n/staging-digisign3-documents-us-west-2.skyslope.com/<redacted>\n\ncontent-length:180886\ncontent-type:application/pdf\nhost:s3.us-west-2.amazonaws.com\nuser-agent:aws-sdk-dotnet-coreclr/3.3.104.3 aws-sdk-dotnet-core/3.3.107.3 .NET_Core/3.1.10 OS/Linux_5.4.0-1028-aws_#29-Ubuntu_SMP_Mon_Oct_5_15:30:10_UTC_2020 ClientAsync TransferManager/SimpleUploadCommand\nx-amz-content-sha256:STREAMING-AWS4-HMAC-SHA256-PAYLOAD\nx-amz-date:20210105T230520Z\nx-amz-decoded-content-length:180531\<redacted>","StringToSign":"<redacted>","ServiceName":"AmazonS3","ServiceEndpoint":"https://s3.us-west-2.amazonaws.com/","MethodName":"PutObjectRequest","StatusCode":"OK","BytesProcessed":"0","AWSRequestID":"44DD242B80037FF8"},"timings":{"CredentialsRequestTime":0.0363,"RequestSigningTime":0.4016,"HttpRequestTime":1136.9015,"ResponseUnmarshallTime":0.0293,"ResponseProcessingTime":0.1476,"ClientExecuteTime":1137.8078},"counters":{}}
```

Is there anything obvious in our configuration that we may be missing or anything else we should look into? Appreciate any insight!

**Comment by ashishdhingra** [comment]
Hi @dthomas-ss,

Good afternoon.

I'm not sure what can be done here since you mentioned the issue is intermittent. I can propose the following:
- Check [AWS Service Health Dashboard](https://status.aws.amazon.com) for any service related issues.
- Check if your application is compiled/built and deployed in Release mode (Debug mode is usually slower due to additional debug information and symbols)
- Try to re-use AWS Service client instances (e.g. using Singleton instance) although it might not matter much.
- Dispose of any unused objects when no longer in use.
- If the .NET Core app is deployed on-premise (somewhat unlikely), then try running network trace to see if there is any network related latency.

Please let me know if this helps.

Thanks,
Ashish

**Comment by dthomas-ss** [comment]
Hi @ashishdhingra,

No latency is reported on the AWS side, so we seem good there.
App is running under Release mode.
I will confirm we are using Singletons. Does the use of `AddAwsService` inject a singleton?
And the app is running on EC2s managed by kubernetes.

Is there any additional logging we could enable or anything else you'd suggest we can investigate?

Thanks,
Daryl

**Comment by ashishdhingra** [comment]
Hi @dthomas-ss,

Good morning.

Few more suggestions after brainstorming with development team:

- Since it is an EC2 instance, you may try to remote login into the instance and run network trace. Not sure if there is any network latency on the EC2 side.

- Are there any other applications running on the EC2 instance? Normally, for production workloads, it's recommended to have dedicated instance for web application.

- Try spinning up another EC2 instance for testing purposes in the same region and then deploy your application in Release mode to this instance. Thereafter, measure the metrics on this new instance for comparison.

Please let me know if this helps.

Thanks,
Ashish

**Comment by dthomas-ss** [comment]
Hi @ashishdhingra,
We are continuing to actively look into this, and are exploring the use of VPC endpoints to hopefully improve performance. That aside, do you or anyone from the team have any suggestions to investigate any issues with the usage of HttpClient? One suspicion that we have is that HttpClient is not being handled correctly. Do you have any insight on how to explore that further with the SDK?

**Comment by ashishdhingra** [comment]
Hi @dthomas-ss,

I can try to see what we can do to investigate HttpClient handling in sDK. But I do not think it's an issue since it would have a broader impact if that were the case. The best bet right now is to explore Microsoft's documentation and investigate the HTTP traffic via web monitoring tools. 

Thanks,
Ashish

**Comment by dthomas-ss** [comment]
Hi @ashishdhingra,

Do you have any code samples for how to best register AWS service dependencies?

As I showed above, we are using both AddAWSService for Dynamo, S3, and Kinesis and also registering the following

```
            services.AddSingleton<IDynamoDBContext, DynamoDBContext>();
            services.AddSingleton<Table, Table>(d =>
            {
                return Table.LoadTable((IAmazonDynamoDB)d.GetService(typeof(IAmazonDynamoDB)), AppSettings.EnvelopeTableName);
            });
```

Could this lead to any potential issues?
Also, does AddAWSService register services as Transient, Scoped, or Singletons?

**Comment by ashishdhingra** [comment]
> Hi @ashishdhingra,
> 
> Do you have any code samples for how to best register AWS service dependencies?
> 
> As I showed above, we are using both AddAWSService for Dynamo, S3, and Kinesis and also registering the following
> 
> ```
>             services.AddSingleton<IDynamoDBContext, DynamoDBContext>();
>             services.AddSingleton<Table, Table>(d =>
>             {
>                 return Table.LoadTable((IAmazonDynamoDB)d.GetService(typeof(IAmazonDynamoDB)), AppSettings.EnvelopeTableName);
>             });
> ```
> 
> Could this lead to any potential issues?
> Also, does AddAWSService register services as Transient, Scoped, or Singletons?

Hi @dthomas-ss,

Here are some inputs:

- The section **ASP.NET Core dependency injection** at [Configuring the AWS SDK for .NET with .NET Core](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-netcore.html) provides good information for registering AWS Services.
- The `AddAWSService()` extension method for `IServiceCollection` defaults to Singleton lifetime as indicated by the signature https://github.com/aws/aws-sdk-net/blob/169fde196274c4e994ca1a7845267606a9c00460/extensions/src/AWSSDK.Extensions.NETCore.Setup/ServiceCollectionExtensions.cs#L71

As far as I can tell, I do not see any issues with your DI code. 

Thanks,
Ashish
