### ISSUE TITLE
GetCostAndUsageWithResources Daily Granularity saying hourly?

### ISSUE THREAD

**Issue by webecker25272** [aws/aws-sdk-net#1773]
When I run the following code, I get an error saying that 'start date is too old for hourly, the max supported days for hourly granularity is 14 days.'  You'll notice in the code that the granularity is DAILY, not hourly.  Also, the response data is daily as well.  I'm assuming this is a bug, but maybe I'm doing something wrong?

@ashishdhingra 

Thanks!

```
            GetCostAndUsageWithResourcesRequest request = new GetCostAndUsageWithResourcesRequest();
            request.TimePeriod = new DateInterval();
            request.TimePeriod.Start = DateTime.Now.AddDays(-15).ToString("yyyy-MM-dd");
            request.TimePeriod.End = DateTime.Now.ToString("yyyy-MM-dd");

            request.Granularity = Granularity.DAILY;

            request.GroupBy = new List<GroupDefinition>();
            request.GroupBy.Add(new GroupDefinition { Type = GroupDefinitionType.DIMENSION, Key = Dimension.RESOURCE_ID });
            request.GroupBy.Add(new GroupDefinition { Type = GroupDefinitionType.DIMENSION, Key = Dimension.OPERATION });

            request.Filter = new Expression() { Dimensions = new DimensionValues() { Key = "SERVICE", Values = new List<string> { "Amazon Elastic Compute Cloud - Compute" } } };


            request.Metrics = new List<string>();
            request.Metrics.Add(Metric.AMORTIZED_COST);
            request.Metrics.Add(Metric.BLENDED_COST);
            request.Metrics.Add(Metric.UNBLENDED_COST);
            request.Metrics.Add(Metric.USAGE_QUANTITY);
            request.Metrics.Add(Metric.NORMALIZED_USAGE_AMOUNT);


            GetCostAndUsageWithResourcesResponse cost = client.GetCostAndUsageWithResources(request);
```

**Comment by ashishdhingra** [comment]
Hi @webecker25272,

Good morning.

Looking at the SDK code base, the error and response are returned by the service API. The method [GetCostAndUsageWithResources](https://github.com/aws/aws-sdk-net/blob/d0965be3fc49bd2df574872696b5475076de38bc/sdk/src/Services/CostExplorer/Generated/_bcl45/AmazonCostExplorerClient.cs#L984) is only a wrapper around the service API call. Looking at the service API documentation https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_GetCostAndUsageWithResources.html, it appears that `TimePeriod` start and end date range must be within the last 14 days (the start date cannot be earlier than 14 days ago). Hence you are getting that date range error.

Hope this helps.

Thanks,
Ashish

**Comment by garyholiday13** [comment]
@ashishdhingra This does not resolve the issue.

If setting Granularity by 'MONTH' or 'DAY' is an option, why would the time period have to fall within the past 14 days? 

I want to get my costs from the past x Months.

**Comment by ashishdhingra** [comment]
> @ashishdhingra This does not resolve the issue.
> 
> 
> 
> If setting Granularity by 'MONTH' or 'DAY' is an option, why would the time period have to fall within the past 14 days? 
> 
> 
> 
> I want to get my costs from the past x Months. 

Hi @garyholiday13,

The restriction is imposed by service, not by the SDK. SDK provides wrapper classes for making service API calls.

Thanks,
Ashish

**Comment by gtestault** [comment]
Im also getting this error on the `GetCostAndUsage` command with DAILY granularity even though the service 
https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_GetCostAndUsage.html doesn't say that there is a 14 day limit.

**Comment by amediantsev** [comment]
I also have the same. The error message says that it is the limitation for `hourly` granularity. But the granularity in the request is `DAILY`, so I believe it is the bug.

**Comment by donets420** [comment]
I also have the same. It looks like aws ce is not relevant tool for usage.

**Comment by DaneRosa** [comment]
Also running into the same issue with the following: 
`response = client.get_cost_and_usage_with_resources(
        TimePeriod={
            'Start': '2022-06-01',
            'End': '2022-06-30'
        },
        Granularity='MONTHLY',
        Filter = {
            'CostCategories': {
                'Key': 'string',
                'Values': [
                    'string',
                ],
            }
        },
        Metrics=[
            'NetUnblendedCost'
        ]
    )`
    I have it set to monthly but getting an error message for hourly

**Comment by yikoma** [comment]
I also have the same issue.

**Comment by fivetran-AndreyKalugin** [comment]
Same problem. I have it set to daily but getting an error message for hourly

**Comment by 50ur48h** [comment]
Running this PowerShell query and getting error for `hourly` granularity even though I am using Daily/Monthly granularity. Can anyone suggest whats the issue?

I am using the latest version of AWS.Tools.CostExplorer [Version: 4.1.398]

```
$TimePeriod = (New-Object Amazon.CostExplorer.Model.DateInterval -Property @{Start='2023-08-22'; End='2023-07-10'})
$BlendedCost = Get-CeCostAndUsage -TimePeriod $TimePeriod -Granularity DAILY -Metric 'BlendedCost'

[Error] Get-CECostAndUsageWithResource : Hourly timePeriod is not supported for this request

```

**Comment by domaa11** [comment]
Same issue. Please update the documentation to specify --granularity is not an option, or allow for MONTHLY and DAILY to be used.

**Comment by eddiemcs3** [comment]
Thank you for the feedback.  We have reopened this issue to open a ticket against the service team or to provide a solution.

**Comment by eddiemcs3** [comment]
We have opened a ticket with the service team and will provide an update.

**Comment by bhoradc** [comment]
V1275484116

**Comment by ashishdhingra** [comment]
> Running this PowerShell query and getting error for `hourly` granularity even though I am using Daily/Monthly granularity. Can anyone suggest whats the issue?
> 
> I am using the latest version of AWS.Tools.CostExplorer [Version: 4.1.398]
> 
> ```
> $TimePeriod = (New-Object Amazon.CostExplorer.Model.DateInterval -Property @{Start='2023-08-22'; End='2023-07-10'})
> $BlendedCost = Get-CeCostAndUsage -TimePeriod $TimePeriod -Granularity DAILY -Metric 'BlendedCost'
> 
> [Error] Get-CECostAndUsageWithResource : Hourly timePeriod is not supported for this request
> ```

@50ur48h I guess this is the same issue where I posted an update https://github.com/aws/aws-sdk-net/issues/3036#issuecomment-1688809665 from the service team. Please refer note `Resource-level data granularity is an opt-in only feature. You can be enable this feature from the PAYER account's Cost Explorer Settings page.` and check of you have enabled granularity at your end.

Thanks,
Ashish

**Comment by goforgold** [comment]
> We have opened a ticket with the service team and will provide an update.

Did you get any update from service team? We literally have no clue why APIs are behaving oddly.
