### ISSUE TITLE
Generic query methods with overridden table name performing describe on assumed table name

### ISSUE THREAD

**Issue by junderhill** [aws/aws-sdk-net#1774]
## The Question
We're using all generic query methods on the DynamoDbContext within our code and we override the table name using the `QueryOperationConfig` however we're seeing lots of errors within CloudTrail where our system is trying to perform a describe operation on the 'non-overridden' table which of course doesn't exist. I've checked that we are overriding the table name in all calls to the DynamoDbContext.

Functionally our system is operating as expected however we're plagued with errors in CloudTrail as a result.

Examples of our queries:

```
var query = _dynamoDbContext.QueryAsync<Connection>(connectionId, new DynamoDBOperationConfig
            {
                OverrideTableName = _operationConfig.OverrideTableName,
                IndexName = "ByConnectionId"
            })
```

Errors in CloudTrail
```
User: arn:aws:sts::**REDACTED**:assumed-role/SendMessageFunctionRole-1WE84Y5BCARYQ/SendMessageFunction-JTV2TGAHXL2U is not authorized to perform: dynamodb:DescribeTable on resource: arn:aws:dynamodb:eu-west-1:**REDACTED**:table/Connection
```

Our table names are in the format SYSTEMNAME-ENVNAME-Connections etc.

Are we doing something wrong or is this a bug?

### Environment

* SDK Version: 3.1
* Package Version: 3.3.106.47
* OS Info:  AWS Lambda
* Build Environment: dotnet CLI
* Targeted .NET Platform:  netcoreapp3.1

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @junderhill,

Good afternoon.

Somehow, I'm unable to reproduce the issue. I created a table named `Connection` with Primary Key as `Id` (string) and IndexName `ByConnectionId`. Thereafter, I used the following minimal code:

```C#
using Amazon.DynamoDBv2;
using Amazon.DynamoDBv2.DataModel;
using System;

namespace DynamoDBTest
{
    class Program
    {
        static void Main(string[] args)
        {
            AmazonDynamoDBClient client = new AmazonDynamoDBClient();
            string connectionId = "12345";
            var _dynamoDbContext = new DynamoDBContext(client);

            var query = _dynamoDbContext.QueryAsync<Test>(connectionId, new DynamoDBOperationConfig
            {
                OverrideTableName = "Connection",
                IndexName = "ByConnectionId"
            });

            var result = query.GetNextSetAsync().Result;
        }
    }

    public class Test
    {
        [DynamoDBHashKey("Id")]
        public string Id { get; set; }

        [DynamoDBProperty("Title")]
        public string Title { get; set; }
    }
}
```

I do not see any DescribeTable event logged in CloudTrail events. Could you please share your DynamoDb schema and settings so that I could try reproducing the issue.

Thanks,
Ashish

**Comment by junderhill** [comment]
@ashishdhingra Hi, Thanks for getting back to me. After some further debugging I think it may be related to a different query than the one I posted. I just want to confirm the level of detail I'm allowed to send over to you. Do you have an email address I can reach you at?

**Comment by ashishdhingra** [comment]
> @ashishdhingra Hi, Thanks for getting back to me. After some further debugging I think it may be related to a different query than the one I posted. I just want to confirm the level of detail I'm allowed to send over to you. Do you have an email address I can reach you at?

Hi @junderhill,

For security reasons, I'm might not be allowed to share the email address. You may post your question with any inputs, with sensitive information removed (e.g., share minimal schema/code required to reproduce the issue) as a comment on this issue. Please let me know if this is no longer an issue.

Thanks,
Ashish

**Comment by mrjrt** [comment]
For what it's worth, I was experiencing exactly this issue, and seem to have resolved it by upgrading AWSSDK.DynamoDBv2 from 3.3.105.11 to 3.5.4.20.

...need to do more tests, but I'm not seeing the issue in my logs locally any more.
