### ISSUE TITLE
Amazon AppSync - Higher Level Library/Amplify Support

### ISSUE THREAD

**Issue by yoni536** [aws/aws-sdk-net#1776]
issue for a higher level library / **Amplify** Framework port for interfacing with Amazon **AppSync**.
This is the preferred service for doing offline data synchronization and cross-device data management.
**support for .net and unity**

**Comment by yoni536** [comment]
@AppSync

**Comment by yoni536** [comment]
any updates?

@AppSync  @Amplify

**Comment by normj** [comment]
Closing as a duplicate of this issue
https://github.com/aws/dotnet/issues/20
