### ISSUE TITLE
S3 notification configuration cloudformation missing event configuration types

### ISSUE THREAD

**Issue by sliedig** [aws/aws-sdk-net#178]
Hello,

S3 supports the following even types (ref: http://ow.ly/KgSku):

* s3:ObjectCreated:
* s3:ObjectCreated:Put
* s3:ObjectCreated:Post
* s3:ObjectCreated:Copy
* s3:ObjectCreated:CompleteMultipartUpload
* s3:ReducedRedundancyLostObject

Visual Studio schema does not recognise anything but s3:ReducedRedundancyLostObject.

![image](https://cloud.githubusercontent.com/assets/597073/6631816/4f095130-c967-11e4-9905-bf6db4a8fa92.png)

**Comment by normj** [comment]
Thanks for letting us know. I have updated the schema which you will see the next time you restart Visual Studio.
