### ISSUE TITLE
'PutEventsResultEntry.EventId' should be typed as 'Guid' instead of 'string'

### ISSUE THREAD

**Issue by julealgon** [aws/aws-sdk-net#1786]
## Description

Documentation for EventBridge responses indicate that the `EventId` property on generated events is actually a `Guid` value. For example:
https://docs.aws.amazon.com/eventbridge/latest/userguide/add-events-putevents.html#failure-handling

```json
{
    "FailedEntryCount": 1, 
    "Entries": [
        {
            "EventId": "11710aed-b79e-4468-a20b-bb3c0c3b4860"
        },
        {   
            "ErrorCode": "InternalFailure",
            "ErrorMessage": "Internal Service Failure"
        }, 
            "EventId": "d804d26a-88db-4b66-9eaf-9a11c708ae82"
        }
    ]
}
```

However, the `EventId` property on `PutEventsResultEntry` is typed as `string`. This forces interfacing code to have to parse the value to use it as a strongly typed object.

### Environment

* Package Version: `Assembly AWSSDK.EventBridge 3.5.4.26`
* OS Info:  Windows 10
* Build Environment  Visual Studio
* Targeted .NET Platform:  NetCore 3.1 and Net5

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

The offending property should be changed from `string` to `Guid?`. Nullable seems to be required because when an error occurs there won't be any event ID generated.

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @julealgon,

The [PutEventsResultentry](https://github.com/aws/aws-sdk-net/blob/874768a26b4d6a3f7bf5fd57ac7d94e07a5b3b80/sdk/src/Services/EventBridge/Generated/Model/PutEventsResultEntry.cs#L34) class is generated from the [eventbridge-2015-10-07.normal.json](https://github.com/aws/aws-sdk-net/blob/master/generator/ServiceModels/eventbridge/eventbridge-2015-10-07.normal.json) service model. If you refer the service model JSON, the service API sends the EventId as `string` per the line https://github.com/aws/aws-sdk-net/blob/874768a26b4d6a3f7bf5fd57ac7d94e07a5b3b80/generator/ServiceModels/eventbridge/eventbridge-2015-10-07.normal.json#L1417. 

Since this is the automated process and the classes are generated from the language agnostic service models, .NET service class generator does not make any assumptions about the type, it uses the type defined the shape in service model JSON. Please let me know if this provides necessary explanation.

Thanks,
Ashish

**Comment by julealgon** [comment]
Ashish, I understand these request/response types are automatically generated. However, I feel like in this particular case, the actual source data needs correction/augmentation.

While `string` is the correct type in Json form for guids, specifying the `format` value would allow generators to create strongly typed `Guid` types instead of `string` when the language supports it. This is similar to how types like `DateTime` and `TimeSpan` works. The format for Guids is `uuid`.

In your example, this would become:
```json
"EventId": {
  "type": "string",
  "format": "uuid"
}, 
```

Here is some information regarding UUID in Json Schema as well as OpenAPI:
- https://stackoverflow.com/questions/50204588/how-to-define-uuid-property-in-json-schema-and-open-api-oas

Here is an excerpt of one of our own OData APIs swagger documentation highlighting a few such formats:

```json
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "idCard": {
            "$ref": "#/components/schemas/CustomerIdCard"
          },
          "emailAddress": {
            "maxLength": 200,
            "minLength": 1,
            "type": "string",
            "format": "email"
          },
          "name": {
            "$ref": "#/components/schemas/CustomerName"
          },
          "mobilePhoneNumber": {
            "maxLength": 10,
            "minLength": 10,
            "pattern": "^\\d*$",
            "type": "string",
            "format": "tel"
          }
        },
```
In this example, the `Id`, `EmailAddress` and `MobilePhoneNumber` properties are all `strings` in the json, but have specific formats defined based on the Json schema spec. `Id` in this example maps into C#'s `Guid`, while the other 2 map into raw `string` types.

This document provides the list of standard Json string formats that can be used by various tools:
- https://json-schema.org/understanding-json-schema/reference/string.html#built-in-formats

**Comment by ashishdhingra** [comment]
Hi @julealgon,

Thanks for providing the reference articles. However, based on what the current implementation is, this is probably a `feature-request` and that too would require service model having support for `format` property. I will discuss this with development team and share any updates here accordingly.

Thanks,
Ashish

**Comment by julealgon** [comment]
Thank you @ashishdhingra . I filed it under "bug" as it also includes other types of "problems", and I personally considered this poor typing a problem. Feel free to move it to a feature request if that's more appropriate for you and team ;)

There is a strong likelihood that your json schema generator already has support for this though, going by the rest of the payload there which exposes all validations etc. Let's hope that's the case.

**Comment by ashishdhingra** [comment]
> Thank you @ashishdhingra . I filed it under "bug" as it also includes other types of "problems", and I personally considered this poor typing a problem. Feel free to move it to a feature request if that's more appropriate for you and team ;)
> 
> There is a strong likelihood that your json schema generator already has support for this though, going by the rest of the payload there which exposes all validations etc. Let's hope that's the case.

Just FYI, the service API documentation https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_PutEventsResultEntry.html mentions `EventId` as of type `String` (even though the value might be represented as GUID). I also compared with AWS Java SDK (V1), which also declares `eventId` of type `String` (refer https://github.com/aws/aws-sdk-java/blob/00f289a50d8c910830f172599d6d0c6b034f6221/aws-java-sdk-eventbridge/src/main/java/com/amazonaws/services/eventbridge/model/PutEventsResultEntry.java#L36).

It appears that the type of `EventId` is consistently declared as type `string` across SDKs (at least as we see in case of Java SDK and from the service API documentation) and changing the type would definitely a breaking change with a very large service area.

I will discuss this issue with development team and reply back with an update.

Thanks,
Ashish

**Comment by ashishdhingra** [comment]
Hi @julealgon,

Good morning.

Unfortunately, based on my discussion with development team, the data type of `EventId` as `string` is as per design. .NET SDK doesn't expose `Guid` data type for these parameters, it is dependent on what service model exposes; and as you saw, this has been implemented consistently across other SDKs (Java is an example) and any change from this behavior would have a very large impact.

Thanks,
Ashish

**Comment by julealgon** [comment]
Thanks for getting back on this @ashishdhingra . 

While I understand the issue here, I still believe the API would be considerably cleaner if you could limit the data types closer to what they actually represent.

I'm hoping that this is taken into account for any new fields in the API.
