### ISSUE TITLE
Handle exception while HttpClientResponseData is disposed

### ISSUE THREAD

**Issue by Zubastic** [aws/aws-sdk-net#1789]
## Description
I want to log response from server, but if I try to read response body i got ObjectDisposedException.

I use fiddler to get it:
![img](https://klikr.org/ebd91f1b12f2760806d08256f516.png)

## Reproduction Steps
Here sample to reproduce
```c#
            try
            {
                var putRequest = new PutObjectRequest { BucketName = this.BucketName, Key = "already existing file", InputStream = contentStream, ContentType = "text/plain" };
                await this.Client.PutObjectAsync(putRequest, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception e)
            {
                //log answer from server
                if (e is HttpErrorResponseException ex)
                {
                    var message = await ex.Response.ResponseBody.OpenResponse().ReadStringAsync(); // disposing exception
                }
            }
```

### Environment

* SDK Version: 3.5.1.49
* Package Version: 3.5.1.49
* OS Info: Windows 10 1607 LTSB
* Build Environment Rider 2020.3
* Targeted .NET Platform:  netcoreapp3.1

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

I guess, it disposed at CompleteFailedRequest, so maybe before disposing try to save response from server?
![img](https://klikr.org/8cfbb671ca87609b903e964bb83a.png)

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @Zubastic,

Good morning.

I will try to reproduce the issue. However, this doesn't appear to be an issue since SDK pipeline would dispose of the HttpClient instances when it is finished with processing the request, whether it is successful or not.

Thanks,
Ashish

**Comment by ashishdhingra** [comment]
Hi @Zubastic,

Good morning.

The error is most probably coming from the code https://github.com/aws/aws-sdk-net/blob/6d0f7f91920db3cc9af65ebc6ee2cfde04c591b0/sdk/src/Core/Amazon.Runtime/Internal/Transform/_netstandard/HttpClientResponseData.cs#L139

As mentioned earlier, the SDK tries to dispose the objects no longer needed, which's pointed by you is being done at https://github.com/aws/aws-sdk-net/blob/6d0f7f91920db3cc9af65ebc6ee2cfde04c591b0/sdk/src/Core/Amazon.Runtime/Pipeline/HttpHandler/HttpHandler.cs#L95

I'm unsure about the use case to parse Http Response body from the returned exception when the only useful piece of information is the error message, which could be read from `Message` property of exception object. Please review the `Message` property of the exception object and see if it useful.

Thanks,
Ashish

Thanks,
Ashish
