### ISSUE TITLE
 "Publish to AWS..." broken for AWS China

### ISSUE THREAD

**Issue by EvanWeiner** [aws/aws-sdk-net#179]
I found that there is no AWS China support in the "Publish to AWS..." feature of the AWS Toolkit for Visual Studio. 

Specifically, this is a broken scenario:
http://d1un85p0f2qstc.cloudfront.net/visualstudio/cloudformation/video.html

Is there any plans to update the toolkit for AWS China deployment support?

**Comment by steveataws** [comment]
Thanks for the query.

At this time none of the services to which you can currently publish from Visual Studio (AWS CloudFormation and AWS Elastic Beanstalk) are supported in the China (Beijing) region. The current set of supported services in this region can be found at http://docs.aws.amazon.com/general/latest/gr/isolated_regions.html.

As and when new services are added to the region, we'll evaluate adding support in the Visual Studio toolkit.

**Comment by EvanWeiner** [comment]
Hi Steve

I can make the changes to add support and submit a pull request. Can you give me a hint of where to add the cn-north-1 end points?

**Comment by IainCole** [comment]
I think the point @steveataws was making is that neither AWS CloudFormation or AWS Elastic Beanstalk are supported in the AWS China region, so adding them to the SDK/Toolkit would be pointless.

**Comment by EvanWeiner** [comment]
No, CloudFormation is in-fact supported in the AWS China region. I am a user.
