### ISSUE TITLE
Slow Publish calls on IAmazonSimpleNotificationServiceClient

### ISSUE THREAD

**Issue by msjonathan** [aws/aws-sdk-net#1790]
### Environment
* SDK Version: 3.3.102.11
* .Net Platform: netcoreapp3.1
* OS: Azure Windows App Service (North Europe) 
* Amazon Data Center: Ireland 

We do run an Aspnet Core API in a Azure App Plan, today we noticed some delays when publishing a notification. 

We use application insights to track our dependencies

`dependencies
| where cloud_RoleName contains "****" and timestamp > ago(2h) and target == "sns.eu-west-1.amazonaws.com"
| summarize count=count() by performanceBucket`

All these dependency call's are "Posts" to publish a notification, but the results are quite surprising. 

![image](https://user-images.githubusercontent.com/6077485/106595527-fa3e2600-6553-11eb-826d-fde1ad8d6644.png)

In total we did an Total of **3610** call's over a period of **10 minutes** - but we see that 14% of the call's to SNS takes longer than 1 second - and event with outliers going to **15 seconds**!

We don't think we are hitting the SNS throttle limits  https://docs.aws.amazon.com/general/latest/gr/sns.html as it states that it can handle publishes requests till 30/second - and we are still far from it. 

**Important**: this test run was publishing to the **same** **Topic** - we'll re-run this load across multiple topics. 

❓ Did anybody else experiences these response times? Is there a throttle limit per Topic? 

Thanks

Jonathan

**Comment by ashishdhingra** [comment]
Hi @msjonathan,

Good morning.

Thanks for posting the guidance question. Could you please share code snippet which uses AWS .NET SDK and uses  `IAmazonSimpleNotificationServiceClient` to publish SNS messages? Also advise if you tried running the same logic in AWS environment and it still has noticeable delay.

While I do not have any metrics for response times, most likely there could be delays at SNS service side.

Thansk,
Ashish

**Comment by msjonathan** [comment]
Hej @ashishdhingra ,
It's a very basic setup. 

In the startup.cs
`var awsOptions = Configuration.GetAWSOptions();
            var awsAccessKey = Configuration.GetValue<string>("AWS:Credentials:AccessKey");
            var awsSecretKey = Configuration.GetValue<string>("AWS:Credentials:SecretKey");

            awsOptions.Credentials = new BasicAWSCredentials(awsAccessKey, awsSecretKey);
            services.AddDefaultAWSOptions(awsOptions);

            services.AddAWSService<IAmazonSimpleNotificationService>();`


In a Service Class we inject the "IAmazonSimpleNotificationService " in the ctor and assign it to a member of that class.

 `var response = await _snsClient.PublishAsync(request);`

Currently we are using 98% of Azure infrastructure, therefor we would like to keep the client on Azure infrastucture. 

Thanks.

Jonathan

**Comment by ashishdhingra** [comment]
> Hej @ashishdhingra ,
> It's a very basic setup.
> 
> In the startup.cs
> 
> ```
> var awsOptions = Configuration.GetAWSOptions();
>             var awsAccessKey = Configuration.GetValue<string>("AWS:Credentials:AccessKey");
>             var awsSecretKey = Configuration.GetValue<string>("AWS:Credentials:SecretKey");
>              awsOptions.Credentials = new BasicAWSCredentials(awsAccessKey, awsSecretKey);
>             services.AddDefaultAWSOptions(awsOptions);
> 
>             services.AddAWSService<IAmazonSimpleNotificationService>();
> ```
> 
> In a Service Class we inject the "IAmazonSimpleNotificationService " in the ctor and assign it to a member of that class.
> 
> `var response = await _snsClient.PublishAsync(request);`
> 
> Currently we are using 98% of Azure infrastructure, therefor we would like to keep the client on Azure infrastucture.
> 
> Thanks.
> 
> Jonathan

Hi @msjonathan,

I do see that it's a very basic example to use SNS service to publish messages. I'm not sure if there is any latency caused within the Azure infrastructure which could be causing that delay. That's why I was curious if you see the same latency when running the application outside of Azure infrastructure, may be in private server. You might want to also try running some kind of network trace (not sure how it would be done in Azure environment) to figure out the delay and implement optimizations accordingly.

Thanks,
Ashish
