### ISSUE TITLE
TransferUtility gives hash error if bucket has encryption enabled

### ISSUE THREAD

**Issue by dlippy** [aws/aws-sdk-net#1794]
On a bucket setup with write/list permissions and encryption enabled the TransferUtility correctly uploads the file to the bucket but reports the following error back on each file upload: 

"Unable to verify integrity of data upload.  Client calculated content hash didn't match hash calculated by Amazon S3.  You may need to delete the data stored in Amazon S3."

**Comment by dlippy** [comment]
Note this only occurs with AWS Key Managment Service Key as the key type.  Amazon S3 Key seems to work fine.

**Comment by ashishdhingra** [comment]
Not reproducible using the following code with `Amazon S3 key (SSE-S3)` as Encryption key type:
```C#
using System;
using System.Threading.Tasks;
using Amazon;
using Amazon.S3;
using Amazon.S3.Transfer;

namespace TransferUtilityEncryptUpload_Issue1794
{
    class Program
    {
        private const string bucketName = "<bucketname>";
        private const string filePath = "<full_file_path>";

        // Specify your bucket region (an example region is shown).
        private static readonly RegionEndpoint bucketRegion = RegionEndpoint.USEast2;
        private static IAmazonS3 s3Client;

        public static void Main()
        {
            s3Client = new AmazonS3Client(bucketRegion);
            UploadFileAsync().Wait();
        }

        private static async Task UploadFileAsync()
        {
            try
            {
                var fileTransferUtility = new TransferUtility(s3Client);

                await fileTransferUtility.UploadAsync(filePath, bucketName);
                Console.WriteLine("Upload completed");

            }
            catch (AmazonS3Exception e)
            {
                Console.WriteLine("Error encountered on server. Message:'{0}' when writing an object", e.Message);
            }
            catch (Exception e)
            {
                Console.WriteLine("Unknown encountered on server. Message:'{0}' when writing an object", e.Message);
            }
        }
    }
}
```

**Comment by dlippy** [comment]
One possible difference is that we are using a userid/key that only has write and list permissions.  Below is a code snippet.  We reproduced using this code on two different AWS organizations.  Both when the bucket is set to AWS Key Management Service key (SSE-KMS) failed.  We are using the following:

'com.amazonaws:aws-android-sdk-core:2.15.+'
'com.amazonaws:aws-android-sdk-cognito:2.15.+'
'com.amazonaws:aws-android-sdk-s3:2.15.+'
'com.amazonaws:aws-android-sdk-ddb:2.15.+'

`	BasicAWSCredentials credentials = new BasicAWSCredentials(	AWS_KEY, AWS_SECRET);
		AmazonS3Client s3Client = new AmazonS3Client(credentials);
		s3Client.setRegion(Region.getRegion("us-east-2"));

		TransferUtility transferUtility =
			TransferUtility.builder()
				.context(MainApplication.getAppContext())
				.s3Client(s3Client)
				.build();

		File file = new File(fileName);
		if (file.exists()) {
			int pos = fileName.lastIndexOf('/');
			String nameOfFile = fileName.substring(++pos);

			TransferObserver uploadObserver =
					transferUtility.upload(AWS_BUCKET, "app-logs/" + getFormattedBikeSerialNumber() + "/" + nameOfFile, file);`

**Comment by ashishdhingra** [comment]
Hi @dlippy,

Good morning.

Looks like you are using AWS Java SDK. Kindly confirm which version (v1 or v2). You have wrongly opened issue in AWS .NET SDK repository.


Thanks,
Ashish

**Comment by dlippy** [comment]
Ashish,

Sorry for the confusion.  We are using v2.  I will close this and create issue in the correct repo.

**Comment by ashishdhingra** [comment]
No problem. I could have helped you transfer this issue over.
