### ISSUE TITLE
Bulk send emails with ListManagementOptions

### ISSUE THREAD

**Issue by franhoey** [aws/aws-sdk-net#1795]
If you want to use ListManagementOptions to allow Amazon to manage the unsubscribe features you can only send emails 1 by 1.

SendEmail will only allow a single destination
BulkSendEmail does not have an option for ListManagementOptions

## Describe the Feature
Can ListManagementOptions be added as to BulkSendEmail?

## Additional Context
I would like to use the list management features of Amazon as its the best way to ensure I have high-quality email sending, however, I have to send emails to my entire contact list one at a time

### Environment

---

This is a :rocket: Feature Request

**Comment by timoha** [comment]
Looking for this support in SES as well.

**Comment by ashishdhingra** [comment]
Hi @franhoey,

Good afternoon.
 
I was going through backlog and came across this issue. The model for [SendBulkEmailRequest](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/SimpleEmailV2/Generated/Model/SendBulkEmailRequest.cs) is driven by the service API. Kindly refer service API for [SendBulkEmail](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_SendBulkEmail.html), the action does not expose `ListManagementOptions` (as opposed to in [SendEmail](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_SendEmail.html)). Hence, this is not exposed in AWS SDK for .NET. 

Thanks,
Ashish

**Comment by franhoey** [comment]
Thank you @ashishdhingra, that is exactly the problem this ticket is about.

My intention is to send an email to my whole list, and have the unsubscribe options added to each email. However, this is not possible. The work around I have in place is:

- Download the contact list
- Loop through the list
- Send make a call to SendEmail for each contact and add the ListManagementOptions

This works but means many many API requests to SendEmail rather than a single request to SendBulkEmail.

**Comment by ashishdhingra** [comment]
> Thank you @ashishdhingra, that is exactly the problem this ticket is about.
> 
> My intention is to send an email to my whole list, and have the unsubscribe options added to each email. However, this is not possible. The work around I have in place is:
> 
> * Download the contact list
> * Loop through the list
> * Send make a call to SendEmail for each contact and add the ListManagementOptions
> 
> This works but means many many API requests to SendEmail rather than a single request to SendBulkEmail.

@franhoey Since AWS SDKs rely on service API models, I would open ticket with service team if this is something that can be exposed in service API. I will post any updates here accordingly.

**Comment by ashishdhingra** [comment]
P49903965

**Comment by franhoey** [comment]
Thanks @ashishdhingra can you point me to where I can post that? I cant find the github repo

**Comment by ashishdhingra** [comment]
> Thanks @ashishdhingra can you point me to where I can post that? I cant find the github repo

@franhoey I have opened issue with service team internally and would post an update here as I get the response.

**Comment by ashishdhingra** [comment]
P58495551

**Comment by ashishdhingra** [comment]
SES currently has no immediate plans to expand `ListManagementOptions` to SendBulkEmail. In the mean time, please use the `SendEmail` API.

**Comment by sandycs-protoss** [comment]
so.. is this problem fixed?

**Comment by wherewasit** [comment]
In 2023, it looks like the limitation is still in place... What is the reasoning for this limitation?

**Comment by sebastienlabine** [comment]
@ashishdhingra same thing goes for SendTemplatedEmail...

**Comment by nicodemuz** [comment]
Below quotes are from the recent [AWS article](https://aws.amazon.com/blogs/messaging-and-targeting/an-overview-of-bulk-sender-changes-at-yahoo-gmail/):

> "In a move to safeguard user inboxes, [Gmail](https://blog.google/products/gmail/gmail-security-authentication-spam-protection/) and [Yahoo Mail](https://blog.postmaster.yahooinc.com/post/730172167494483968/more-secure-less-spam) announced a new set of requirements for senders effective from February 2024."

> 2. Set up an easy unsubscribe for email recipients
> Bulk senders are expected to include a mechanism to unsubscribe by adding an easy to find link within the message. The February 2024 mailbox provider rules will require senders to additionally add one-click unsubscribe headers as defined by [RFC 2369](https://datatracker.ietf.org/doc/html/rfc2369) and [RFC 8058](https://datatracker.ietf.org/doc/html/rfc8058). These headers make it easier for recipients to unsubscribe, which reduces the rate at which recipients will complain by marking messages as spam.

> To set up one-click unsubscribe without using the SES subscription management feature, include both of these headers in outgoing messages:
> 
> List-Unsubscribe-Post: List-Unsubscribe=One-Click
> List-Unsubscribe: <https://example.com/unsubscribe/example>

How can we use [sendBulkTemplatedEmail](https://docs.aws.amazon.com/ses/latest/APIReference/API_SendBulkTemplatedEmail.html) API to add List-Unsubscribe-Post and List-Unsubscribe headers? With a quick look at the API documentation, I don't see any ways to add these headers. We do not wish to use SES subscription management feature as we already have our subscription management page where the user can unsubscribe.

@ashishdhingra Going forward, this seems like an essential feature that needs to be supported. Can you check with the SES team if this can be supported?
