### ISSUE TITLE
Improve dependency injection and client configuration

### ISSUE THREAD

**Issue by rbx-rchall** [aws/aws-sdk-net#1796]
I'm trying to use an S3 client as long as I don't have to configure anything that is not available on the appsettings.json file everything is ok, but let's say I would like to configure the `ForcePathStyle`. I haven't been able to find a good solution for this nor documentation about it. 

Note that I could go and wrap the injected client on another class that would configure the client but this is not that pretty. 

## Describe the Feature
Ideally we have the extension method that injects the client provide a delegate with the client configuration or something similar.

```
services.AddAWSService<IAmazonS3ClientA>(options1, (clientConfig) => {
// Where clientConfig is AmazonS3Config
// and then we can things like 
clientConfig.ForcePathStyle = true;
});
```

## Solution
Not sure if something like this would be acceptable but this PR draft provides a better idea of what I consider a potential solution to this problem: https://github.com/aws/aws-sdk-net/pull/1798

Note that we might also follow a different pattern injecting a ConfigurationBuilder and provide a DefaultConfigurationBuilder generic on the Configuration type that can read params from `appsettings.json` file but the above solution also solves the problem if you are using the `options1.CreateServiceClient` in the event you are having to inject multiple clients of the same service with different aws options.

## How to use
```
var options1 = Configuration.GetAWSOptions("AWS_Profile_A");
var client = options1.CreateServiceClient<IAmazonS3>(configureClient:
                    (clientConfig) =>
                    {
                        if (clientConfig is AmazonS3Config config) config.ForcePathStyle = true;
                    });

```
or 

```
services.AddAWSService<IAmazonS3>(options1, configureClient:
                (clientConfig) =>
                {
                    if (clientConfig is AmazonS3Config config) config.ForcePathStyle = true;
                });
```

This is a :rocket: Feature Request

**Comment by ashishdhingra** [comment]
Needs review with the team as this is getting lot of traction.

**Comment by TylerReid** [comment]
@ashishdhingra I implemented this in the way that I described and opened [a PR](https://github.com/aws/aws-sdk-net/pull/2571) for consideration.

**Comment by madhub** [comment]
@ashishdhingra  why this PR is stuck in review since 2021. Pls pull this change its useful feature

**Comment by ashishdhingra** [comment]
> @ashishdhingra why this PR is stuck in review since 2021. Pls pull this change its useful feature

@madhub Thanks for the follow up. The PR is in team's radar and should be reviewed soon.

**Comment by cadilhac** [comment]
I can't find these new signatures in sdk v4...

**Comment by dscpinheiro** [comment]
The signature for the `GetAWSOptions` method changed in V4, this is covered in [our migration guide](https://docs.aws.amazon.com/sdk-for-net/v4/developer-guide/net-dg-v4.html#net-dg-v4-netcore-setup) and https://github.com/aws/aws-sdk-net/issues/3866
