### ISSUE TITLE
AWSSDK.CognitoIdentityProvider: CreateUserPoolAsync with LambdaConfig.CustomMessage sets wrong Cognito trigger

### ISSUE THREAD

**Issue by mario-d-s** [aws/aws-sdk-net#1797]
## Description
We are using AWSSDK.CognitoIdentityProvider (currently version 3.3.113.1) to create a Cognito User pool and we want to set a CustomMessage lambda trigger. So we use the following code (irrelevant bits stripped out):

```C#
var request = new CreateUserPoolRequest
{
    LambdaConfig = new LambdaConfigType
    {
        CustomMessage = "..."
    }
};

await _cognitoClient.CreateUserPoolAsync(request);

```

in Cognito, this should set the "Custom message" lambda trigger. What it does instead, is set the "Pre sign-up" trigger!

## Reproduction Steps

1. Create a User Pool via AmazonCognitoIdentityProviderClient, with a Lambda function ARN in LambdaConfig.CustomMessage 
2. Observe that this Lamba function gets configured as "Pre sign-up" trigger in the AWS console.
3. Observe the "Custom message" trigger remains unassigned.

### Logs
Not configured right now, as we don't use Log4Net.
If this is necessary for this bug report, please let me know.

### Environment

* SDK Version: 3.3.113.1
* Package Version: 3.3.113.1
* OS Info: Fedora 33
* Build Environment VSCode + Terminal `dotnet`
* Targeted .NET Platform:  ASP.NET Core 2.1

## Resolution

I presume the parameter in the .NET SDK is mapped to the wrong parameter in the HTTP API call?

---

This is a :bug: bug-report

**Comment by mario-d-s** [comment]
Important info that may be of help to you: previously we were using version `3.3.109.50` and here it is working fine.
I will further "bisect" the version to identify the exact package version where this bug was introduced.

I would check if it occurs in the newer `3.5.x` releases but we can't upgrade due to some intermediary dependency.

**Comment by mario-d-s** [comment]
Another bug that happens with the `3.3.113.1` is that the following is ignored:

```
EmailConfiguration = new EmailConfigurationType
{
    EmailSendingAccount = EmailSendingAccountType.DEVELOPER,
    SourceArn = _configuration.SesEmailIdentityArn
}

The configured SES identity was just not applied. I thought we needed to figure out some IAM permissions but it turns out that downgrading the SDK also fixes this...

Do you want me to open a separate issue for this?
```

**Comment by ashishdhingra** [comment]
Hi @mario-d-s,

Good afternoon.

Thanks for reporting the issue. Unfortunately, I'm unable to reproduce using the `AWSSDK.CognitoIdentityProvider` version `3.7.1.4` with the following code:
```C#
using Amazon.CognitoIdentityProvider;
using Amazon.CognitoIdentityProvider.Model;

namespace CreateUserPoolCustomMessage_Issue1797
{
    class Program
    {
        static void Main(string[] args)
        {
            var _cognitoClient = new AmazonCognitoIdentityProviderClient();
            var request = new CreateUserPoolRequest
            {
                PoolName="testuserpool-issue1797",
                LambdaConfig = new LambdaConfigType
                {
                    CustomMessage = "arn:aws:lambda:us-east-2:139480602983:function:TestCognitoCustomMessage" // Existing Lambda function
                }
            };

            var response = _cognitoClient.CreateUserPoolAsync(request).Result;
        }
    }
}
```
Executing the above code creates a new user pool _testuserpool-issue1797_ in the default region with the Custom Message trigger set, as shown below:
<img width="1480" alt="Screen Shot 2021-06-22 at 3 15 31 PM" src="https://user-images.githubusercontent.com/67916761/123006584-c29e1200-d36c-11eb-93f7-2a22756edc98.png">

Please try using the latest version of `AWSSDK.CognitoIdentityProvider` package.

Thanks,
Ashish
