### ISSUE TITLE
Is there any example of AWSSDK.Amplify for .net mvc application (MVC 3)

### ISSUE THREAD

**Issue by anandjaisy** [aws/aws-sdk-net#1800]
Looking for an example or documentation for an AWSSDK.Amplify nuget package for MVC application. I am using MVC 3 application where I have to implement the Cognito authentication and authorization.

**Comment by ashishdhingra** [comment]
Hi @anandjaisy,

Good morning.

Please advise if you are looking to use [AWS Amplify](https://aws.amazon.com/amplify/) to add features to you application or simply integrate Cognito to your application. While I could not find a complete end-to-end example, the developer blog post [Introducing .NET Core Support for AWS Amplify Backend Functions](https://aws.amazon.com/blogs/developer/introducing-net-core-support-for-aws-amplify-backend-functions/) provides some overview of using Amplify with .NET Core application. For Cognito, [Integrate Amazon Cognito with .NET Core ASP.NET MVC Application](https://net-immersionday.workshop.aws/9-how-to-authenticate-users-in-my-application.html) provides an excellent tutorial. 

Please let me know if this helps.

Thanks,
Ashish

**Comment by anandjaisy** [comment]
@ashishdhingra I was looking for an example for MVC .net application specifically mvc 3. Since I have an old system and trying to integrate with Cognito, since I don't have an .net core application. So if I get an example for mvc 3, it will be great. Thanks for the link

**Comment by ashishdhingra** [comment]
Hi @anandjaisy,

Good morning.

The [ASP.NET Core Identity Provider for Amazon Cognito](https://github.com/aws/aws-aspnet-cognito-identity-provider) is only compatible with .NET Core. It is wrapper over [Amazon Cognito Authentication Extension Library](https://github.com/aws/aws-sdk-net-extensions-cognito). You may follow [Amazon CognitoAuthentication Extension Library Examples](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/cognito-authentication-extension.html) to use Cognito with ASP.NET MVC application. Other things, like dependency injection, caching access tokens, refreshing access tokens, etc. would need to be handled by your application design. 

Hope this helps.

Thanks,
Ashish
