### ISSUE TITLE
Using a mocked IAmazonDynamoDB instance in DynamoDBContext

### ISSUE THREAD

**Issue by kpenergy** [aws/aws-sdk-net#1801]
## The Question
Is there any way to inject a mocked `IAmazonDynamoDB` instance into `AmazonDynamoDB `, in order to catch the request that hits the mocked client so the request details can be verified? 

I'm trying to do so by injecting a mocked `IAmazonDynamoDB` instance into `DynamoDBContext`, constructing a new instance of my class to be passed into the DynamoDBContext, and calling SaveAsync, but I'm hitting a `NullReferenceException`. 

```C#
[Fact]
public void Test()
{
	var clientMock = new Mock<IAmazonDynamoDB>();

	var context = new DynamoDBContext(clientMock.Object);

	Dictionary<string, AttributeValue> attributes = null;

	clientMock
		.Setup(m => m.PutItemAsync(It.IsAny<string>(), It.IsAny<Dictionary<string, AttributeValue>>(), default))
		.Callback((string s, Dictionary<string, AttributeValue> a, CancellationToken c) => attributes = a);

	var model = new MyModel { HashKey = Guid.NewGuid().ToString() };

	context.SaveAsync(model).Wait();
}

public class MyModel
{
	[DynamoDBHashKey]
	public string HashKey { get; set; }
}
```

The exception I'm hitting is:

> System.NullReferenceException: 'Object reference not set to an instance of an object.'
Amazon.DynamoDBv2.DocumentModel.Table.DDBClient.get returned null.

This seems to be a result of the SDK casting the injected `IAmazonDynamoDB` instance to `AmazonDynamoDBClient` when using `NETSTANDARD`. The `Amazon.DynamoDBv2.DocumentModel.Table` class's private constructor casts the mocked interface to `AmazonDynamoDBClient`, but the cast fails and results in `null`. This is the code which seems to be causing the null.

```C#
private Table(IAmazonDynamoDB ddbClient, TableConfig config)
{
	if (config == null)
		throw new ArgumentNullException("config");

	if (ddbClient == null)
		throw new ArgumentNullException("ddbClient");

#if NETSTANDARD
	DDBClient = ddbClient as AmazonDynamoDBClient; // THIS CAUSES NULL
#else
	DDBClient = ddbClient;
#endif
	Config = config;
}
```

Perhaps I'm using the wrong approach to achieve my goal. If there's any way to do this, I'd appreciate the support. Thanks!

### Environment

* SDK Version: 3
* Package Version: 3.5.4.29
* OS Info: Windows 10
* Build Environment Visual Studio
* Targeted .NET Platform:  .Net Core 3.1
---

This is a :question: general question

**Comment by Kralizek** [comment]
This is an old issue that we have also been discussing here: #1589 
Nice to see it's not just me feeling the pain.

**Comment by ashishdhingra** [comment]
Hi @kpenergy,

Good morning.

Thanks for posting guidance question. There are already 2 issues in the backlog:

- https://github.com/aws/aws-sdk-net/issues/1396
- https://github.com/aws/aws-sdk-net/issues/1589

This is a breaking change and the fix would most likely be incorporated in the next major version of SDK. Could you please add :+1: reaction to both issues so that it gets some traction from developer?

I'm not sure what guidance could be provided here since it is a breaking change. Hope this provides some information.

Thanks,
Ashish
