### ISSUE TITLE
SNS - Message.IsMessageSignatureValid() fails with COM Exception

### ISSUE THREAD

**Issue by as-444** [aws/aws-sdk-net#1806]
## Description
I am subscribed to a feed which is sending my endpoint messages via a http post request.

When running Method `Message.IsMessageSignatureValid()` on a valid `Message` object, my application hangs. After a while a COM exception is thrown when running on an azure function.

## Reproduction Steps
```csharp
Message mes = Message.ParseMessage("valid sns json");
bool isValid = mes.IsMessageSignatureValid();
```

### Environment

* SDK Version: v3.5.3.2
* Package Version: AWSSDK.SimpleNotificationService v3.5.1.44
* OS Info: Windows 10 
* Build Environment  Visual Studio 
* Targeted .NET Platform:  

I've checked and when I remove the call to `IsMessageSignatureValid()` the code does not hang and no exceptions are thrown.
I believe the issue is with the signature validation method.

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @as-444,

Good morning.

Looks like your JSON string is not a valid message format. I'm not even able to successfully execute `Message.ParseMessage()` using your code. Kindly refer [Simple Notification Service > Parsing message formats](https://docs.aws.amazon.com/sns/latest/dg/sns-message-and-json-formats.html) for more information on message formats. 

Following code works fine while parsing the message (sample JSON taken from reference URL above):
```C#
using Amazon.SimpleNotificationService.Util;

namespace Issue1806_SNS
{
    class Program
    {
        static void Main(string[] args)
        {
            string snsJsonString = @"{
              ""Type"" : ""SubscriptionConfirmation"",
              ""MessageId"" : ""165545c9-2a5c-472c-8df2-7ff2be2b3b1b"",
              ""Token"" : ""2336412f37..."",
              ""TopicArn"" : ""arn:aws:sns:us-west-2:123456789012:MyTopic"",
              ""Message"" : ""You have chosen to subscribe to the topic arn:aws:sns:us-west-2:123456789012:MyTopic.\nTo confirm the subscription, visit the SubscribeURL included in this message."",
              ""SubscribeURL"" : ""https://sns.us-west-2.amazonaws.com/?Action=ConfirmSubscription&TopicArn=arn:aws:sns:us-west-2:123456789012:MyTopic&Token=2336412f37..."",
              ""Timestamp"" : ""2012 -04-26T20:45:04.751Z"",
              ""SignatureVersion"" : ""1"",
              ""Signature"" : ""EXAMPLEpH +DcEwjAPg8O9mY8dReBSwksfg2S7WKQcikcNKWLQjwu6A4VbeS0QHVCkhRS7fUQvi2egU3N858fiTDN6bkkOxYDVrY0Ad8L10Hs3zH81mtnPk5uvvolIC1CXGu43obcgFxeL3khZl8IKvO61GWB6jI9b5+gLPoBc1Q="",
              ""SigningCertURL"" : ""https://sns.us-west-2.amazonaws.com/SimpleNotificationService-f3ecfb7224c7233fe7bb5f59f96de52f.pem""
            }";
            Message mes = Message.ParseMessage(snsJsonString);
            bool isValid = mes.IsMessageSignatureValid();
        }
    }
}
```
Regarding `Message.IsMessageSignatureValid()` method, it tries to download the certificate specified by `SigningCertURL` property of JSON message, refer SDK code https://github.com/aws/aws-sdk-net/blob/f9672a81e6240984de24b6fa39fae7136ac565b3/sdk/src/Services/SimpleNotificationService/Custom/Util/Message.cs#L386

In your case (also in my case), the certificate download process could be failing. Kindly validate your JSON and ensure that `SigningCertURL` is correct and accessible from your environment. Let me know if this provides necessary guidance.

Thanks,
Ashish

**Comment by as-444** [comment]
Hi @ashishdhingra 

Just to clarify, when I execute `Message.ParseMessage()` on a valid `Notification` message type it does parse successfully.
`Message parsedMessage = Message.ParseMessage(validSnsNotification)`

The issue I have is when I immediately call `parsedMessage.IsMessageSignatureValid()` this is where the code starts to hang and eventually throws an COM Exception when running on a Azure Function,
If I remove the call to `parsedMessage.IsMessageSignatureValid()` then there is no issue.

I've checked and I am able to download the certificate from `SigningCertURL` on my azure function.

I've done a little more debugging and it seems like this is where we're getting the issues.
`Message.cs` class, method `private X509Certificate2 GetX509Certificate()`
https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/SimpleNotificationService/Custom/Util/Message.cs#L372-L392

I suspect the code hangs between lines 372-392 in that method.

**Comment by ashishdhingra** [comment]
> Hi @ashishdhingra 
> 
> 
> 
> Just to clarify, when I execute `Message.ParseMessage()` on a valid `Notification` message type it does parse successfully.
> 
> `Message parsedMessage = Message.ParseMessage(validSnsNotification)`
> 
> 
> 
> The issue I have is when I immediately call `parsedMessage.IsMessageSignatureValid()` this is where the code starts to hang and eventually throws an COM Exception when running on a Azure Function,
> 
> If I remove the call to `parsedMessage.IsMessageSignatureValid()` then there is no issue.
> 
> 
> 
> I've checked and I am able to download the certificate from `SigningCertURL` on my azure function.
> 
> 
> 
> I've done a little more debugging and it seems like this is where we're getting the issues.
> 
> `Message.cs` class, method `private X509Certificate2 GetX509Certificate()`
> 
> 
> 
> I suspect the code hangs between lines 372-392 in that method.
> 
> 
> 
> https://github.com/aws/aws-sdk-net/blob/633b4fe2288186e0da57ce3805c692121667e0ed/sdk/src/Services/SimpleNotificationService/Custom/Util/Message.cs#L372-L392
> 
> 
> 
> I am getting a lot of notifications on my endpoint and I am running the signature validation against each notification.
> 
> Could there possibly be a threading issue?
> 
> 

@as-444 Thanks for your reply. Could you please share the stack trace and exception message, it might be helpful to troubleshoot the issue?
