### ISSUE TITLE
How to get details for list of primary key from dynamodb.

### ISSUE THREAD

**Issue by SARAVANA1501** [aws/aws-sdk-net#1807]
## The Question
`DynamoDbContext` injected to controller using DI, and I have a list of primary key.
Can i get details for all the primary key from  dynamodb using single call?

### Environment
SDK Version: 3.5.1
Package Version:
OS Info: OSX Catalina
Build Environment: Rider
Targeted .NET Platform: Dotnet core 3.1

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @SARAVANA1501,

Good morning.

Could you please elaborate your scenario with example and provide details preferably in the following format:



## Expected Behavior



## Current Behavior






## Possible Solution



## Steps to Reproduce (for bugs)





## Context



## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

Thanks,
Ashish

**Comment by SARAVANA1501** [comment]
```
using System;
using System.Collections.Generic;
using Amazon.DynamoDBv2;
using Amazon.DynamoDBv2.DataModel;
using Amazon.DynamoDBv2.DocumentModel;
using Amazon.DynamoDBv2.Model;
using Amazon.Runtime;

namespace DynamoDbNestedScan_Issue1805
{
    class Program
    {
        private static AmazonDynamoDBClient client = new AmazonDynamoDBClient();

        static void Main(string[] args)
        {
            var config = new DynamoDBContextConfig
            {
                TableNamePrefix = $"{appSettings.Environment}-"
            };
            var context = new DynamoDBContext(client, config)
            var listOfId = new [] {<List of ids>}
            try
            {
                var doc = context.LoadAsync<Root>("sampleId1").Result;
                Console.WriteLine("To continue, press Enter");
                Console.ReadLine();
            }
            catch (AmazonDynamoDBException e) { Console.WriteLine(e.Message); }
            catch (AmazonServiceException e) { Console.WriteLine(e.Message); }
            catch (Exception e) { Console.WriteLine(e.Message); }
        }
    }

    [DynamoDBTable("Root")]
    public class Root
    {
        [DynamoDBHashKey] //Partition key
        public string Id
        {
            get; set;
        }

        [DynamoDBProperty("Attribute1")]
        public string Attribute1
        {
            get; set;
        }

        [DynamoDBProperty("PropertyName")]
        public string PropertyName
        {
            get; set;
        }
    }
}
```

This is a sample code, I have a multiple id, more than 10, I would like to query every thing using single call

**Comment by SARAVANA1501** [comment]
@ashishdhingra  Load accepting single Id and returning single record, I have 10s of ids, I need the data for all the ids in single query. I don't like to make multiple calls, Any suggestion?

**Comment by ashishdhingra** [comment]
> @ashishdhingra Load accepting single Id and returning single record, I have 10s of ids, I need the data for all the ids in single query. I don't like to make multiple calls, Any suggestion?

Hi @SARAVANA1501,

You may try using the [AmazonDynamoDBClient.BatchGetItem()](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/DynamoDBv2/MDynamoDBBatchGetItemBatchGetItemRequest.html) to query based on list of IDs. However, kindly note that, as SDK API and [Service API](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchGetItem.html) documentation mentions, ` single operation can retrieve up to 16 MB of data, which can contain as many as 100 items. BatchGetItem returns a partial result if the response size limit is exceeded, the table's provisioned throughput is exceeded, or an internal processing failure occurs. If a partial result is returned, the operation returns a value for UnprocessedKeys. You can use this value to retry the operation starting with the next item to get.`.

Hope this provides guidance. Closing this issue.

Thanks,
Ashish
