### ISSUE TITLE
AccountID missing from resource policy for S3 Event Notification sources

### ISSUE THREAD

**Issue by shruti0085** [aws/aws-sdk-net#1809]
## Description

The SNSClient and SQSClient have extension methods that allow S3 buckets to publish events to them. For reference: [AuthorizeS3ToPublish](https://github.com/aws/aws-sdk-net/blob/fead493c883bc6d1f5bf19803980c4f39da089e6/sdk/src/Services/SimpleNotificationService/Custom/_bcl/AmazonSimpleNotificationServiceClient.Extensions.cs#L195) and [AuthorizeS3ToSendMessage](https://github.com/aws/aws-sdk-net/blob/fead493c883bc6d1f5bf19803980c4f39da089e6/sdk/src/Services/SQS/Custom/_bcl/AmazonSQSClient.Extension.cs#L62).
These methods update the resource policy of the topic/queue which lacks an accountID field. This leaves the resource open to any user to perform operations with against it.
## Reproduction Steps

1. Create a SNS client
2. Make the following call: `this._snsClient.AuthorizeS3ToPublish(resourceArn, bucketName)`
3. In your account a resource policy similar to the one below would appear: 
```
 { 
      "Sid": "abc",
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"
      },
      "Action": "sns:Publish",
      "Resource": "arn:aws:sns:region:11223344556:sampletopic",
      "Condition": {
        "ArnLike": {
          "aws:SourceArn": "arn:aws:s3:*:*:samplebucket"
        }
      }
}
```
Expected:
```
{ 
      "Sid": "abc",
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"
      },
      "Action": "sns:Publish",
      "Resource": "arn:aws:sns:us-west-2:11223344556:sampletopic",
      "Condition": {
        "StringEquals": {
          "aws:SourceAccount": "11223344556"
        },
        "ArnLike": {
          "aws:SourceArn": "arn:aws:s3:*:*:samplebucket"
        }
      }
}
```
4. Repeat the same with a SQS client
### Environment

* Package Version: AWSSDK.SNS v3.5.1.44 AWSSDK.SQS v3.5.1.21
* OS Info:  Windows 10
* Build Environment Visual Studio 2017
* Targeted .NET Platform:  .NET Framework 4.6

## Resolution

Adding the sourceAccount condition to the resource policy should help resolve this issue. Something along the lines of: `ConditionFactory.NewCondition(ConditionFactory.StringComparisonType.StringEquals,
                "aws:SourceAccount", accountNumber)`

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @shruti0085,

Good afternoon.

I'm not sure if I understand the issue correctly. You mentioned that executing the call `this._snsClient.AuthorizeS3ToPublish(resourceArn, bucketName)` generates the policy similar to below:

```JSON
{ 
      "Sid": "abc",
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"
      },
      "Action": "sns:Publish",
      "Resource": "arn:aws:sns:region:11223344556:sampletopic",
      "Condition": {
        "ArnLike": {
          "aws:SourceArn": "arn:aws:s3:*:*:samplebucket"
        }
      }
}
```

The S3 bucket names are unique. No two AWS accounts can have the bucket with same name. So the condition `"aws:SourceArn": "arn:aws:s3:*:*:samplebucket"` should be sufficient here. Please correct me if I'm missing anything.

Thanks,
Ashish

**Comment by ashishdhingra** [comment]
Hi @shruti0085,

Good afternoon.

Based on my discussion with development team, we would track this issue internally. Hence closing this GitHub issue.

Thanks,
Ashish
