### ISSUE TITLE
VisualStudio CloudFormation template editor shows invalid key for FileSystemConfigs

### ISSUE THREAD

**Issue by hashitha** [aws/aws-sdk-net#1811]
Hi,

Visual studio template editor throws validation error for FileSystemConfigs, Similar to issues #133 and #663 
https://github.com/aws-samples/aws-lambda-efs-samples/blob/master/2-lambda-template/template.yaml

![image](https://user-images.githubusercontent.com/10569142/110230388-7f4d9e00-7f4b-11eb-9274-53fffb8665ae.png)

**Comment by ashishdhingra** [comment]
This could require schema updation.

**Comment by ashishdhingra** [comment]
This is fixed in the  `AWS Toolkit for Visual Studio 2017 and 2019` version `1.21.2.0`.
