### ISSUE TITLE
ap-northeast-3 should now be named Asia Pacific (Osaka)

### ISSUE THREAD

**Issue by ckuehl** [aws/aws-sdk-net#1812]
## Description

ap-northeast-3 is no longer a local region. Therefore, it's name should be updated from `Asia Pacific (Osaka-Local)` to `Asia Pacific (Osaka)`:

https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/RegionEndpoint/RegionEndpoint.cs#L116

Related announcement:

https://aws.amazon.com/blogs/aws/aws-asia-pacific-osaka-region-now-open-to-all-with-three-azs-more-services/

**Comment by ashishdhingra** [comment]
This has been fixed in `AWSSDK.Core 3.5.3.7`
