### ISSUE TITLE
How to Mock GetTargetTable<T>/ Table?

### ISSUE THREAD

**Issue by p-brito** [aws/aws-sdk-net#1813]
I'm developing unit tests for CRUD operations using DynamoDb and I can't mock a "Table", any ideas on how to do that?? An interface ITable would solve this problem!

**Comment by ashishdhingra** [comment]
Hi @p-brito,

Looking at the code for [Amazon.DynamoDBv2.DocumentModel.Table](https://github.com/aws/aws-sdk-net/blob/40d5410740a3001b58ee13b807e474b54999ee74/sdk/src/Services/DynamoDBv2/Custom/DocumentModel/Table.cs#L39), it doesn't implement any interface. Hence, it doesn't seem like you can mock the `Table` object.

Thanks,
Ashish

**Comment by p-brito** [comment]
Yes, it doesn't! That is way I said that an interface solves this problem. :) From a user perspective is impossible to develop unit tests against this class, and there are others, this library is not designed with testing from the user side in mind. I hope that in a major version this changes :)  cheers!
