### ISSUE TITLE
How can I configure buffersize in a way that works when downloading files?

### ISSUE THREAD

**Issue by jefferson** [aws/aws-sdk-net#1814]
### Expected Behavior
As @VasilSirakov I am setting a value for BufferSize in the AmazonS3Client config. But in this time I expect that after calling `GetObjectStreamAsync`, the amount of bytes buffered from the stream will be the size specified by the BufferSize property.

### Current Behavior

```c#
using (var stream = await _amazonS3.GetObjectStreamAsync(bucketName, key, additionalProperties, source.Token))
{
      //omitting some part of configuration to be brevity
      while ((read = await stream.ReadAsync(memory)) > 0)
      {
            using (var memoryStream = new MemoryStream())
            {
                    //the amount of data in read is wrong
            }
       }
 }
```

In my code I just use GetObjectStreamAsync.
How can I configure buffersize in a way that works when downloading files?

### Environment

* SDK Version: Net Core 3.1
* Package Version: AWSSDK.S3 3.5.5.2
* OS Info: Windows 10 
* Build Environment: Visual Studio 
 Targeted .NET Platform:  .NET Core

This is a :question: general question

**Comment by ashishdhingra** [comment]
#1621

**Comment by jefferson** [comment]
@ashishdhingra I know, but there is no way to realize this configuration when you are update `DefaultClientConfig` or working with Streams in AWSDK for .net.

**Comment by ashishdhingra** [comment]
> @ashishdhingra I know, but there is no way to realize this configuration when you are updating `DefaultClientConfig` or working with Streams in AWSDK for .net.

@jefferson Does this imply that setting ChunkEncoding to true works for you? If yes, this is probably a documentation issue.

**Comment by jefferson** [comment]
I don't know @ashishdhingra because I'm trying do test this feature here.

But I saw that is possible to set `UseChunkEncoding` when we want to make upload with `PutObject` in AWS, but there is no way to configure `UseChunkEncoding` when we are trying do Download a object.

**Comment by ashishdhingra** [comment]
> Maybe @ashishdhingra if it's possivel to set `Transfer-Encoding` on header of request, but it's not possivel in current aws api for .net core.
> 
> But I saw that is possible to set `UseChunkEncoding` when we want to make upload with `PutObject` in AWS, but there is no way to configure `UseChunkEncoding` when we are trying do Download a object.

@jefferson 
Here are my findings:
- As per API reference, [ICoreAmazonS3](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/Runtime/TICoreS3.html) is not meant to use directly.
- I do not see any logic where `BufferSize` is used while download files from S3 bucket.
- You can use [AmazonS3Client.GetObject(GetObjectRequest)](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/S3/MS3GetObjectGetObjectRequest.html) to retrieve object from Amazon S3. The [GetObjectResponse](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/S3/TGetObjectResponse.html).`ResponseStream` would give you access to stream which you could use in your own logic to read object based on buffer size. 

Hope this helps.

Thanks,
Ashish

Thanks,
Ashish

**Comment by jefferson** [comment]
@ashishdhingra I'm trying change `BufferSize` to increase the amount of bytes while I'm stream file using `GetObjectAsync`.

But just for let more clear, I'm downloading a file and I would to increase amount of bytes during stream, because of this I'd like to change `Buffer Size`.

Thanks Ashish for your attention.

**Comment by ashishdhingra** [comment]
> @ashishdhingra I'm trying change `BufferSize` to increase the amount of bytes while I'm stream file using `GetObjectAsync` or `GetObjectStreamAsync` or `transferUtility.OpenStreamAsync`.
> 
> But just for let more clear, I'm downloading a file and I would to increase amount of bytes during stream, because of this I'd like to change `Buffer Size`. If I change de `BufferSize` I've always got the same amount of data, as an example if I change `BufferSize` to 5MB I'll receive 15K.
> 
> I'm configuring `BufferSize` like this in AWS SDK fo S3:
> 
> ```cs
> ....
> var aws_options = configuration.GetAWSOptions();
> aws_options.DefaultClientConfig.BufferSize = 5 * 1_048_576; //5MB 
> 
> ....
> var buffer = new byte[5 * 1_048_576];
> 
> using (var stream = await  amazonS3.GetObjectStreamAsync(bucket, key, additionalProperties, cancellationToken.Token))
> {
>   //read always return less than 15KB
>   while ((read = await stream.ReadAsync(buffer, 0, buffer.Length)) > 0)
>   {
>       using (var memoryStream = new MemoryStream())
>       {
>           memoryStream.Write(buffer, 0, read);
> 
>           memoryStream.Position = 0;
>       }
>   }
> }
> ```
> 
> Thanks Ashish for your attention.

Hi @jefferson,

Thanks for your response. As mentioned in my previous comment https://github.com/aws/aws-sdk-net/issues/1814#issuecomment-803083476, the `BufferSize` doesn't appear to be used or set the the HttpResponse level while getting object from S3. At this point, I'm not sure if this is a bug and if `BufferSize` is intended to be used while downloading files. I can try to get inputs from development team.

Thanks,
Ashish

**Comment by jefferson** [comment]
@ashishdhingra thanks again for your attention. If it's possible to talk with development team about this question I'd appreciate it very much.

Thanks Ashish,

Jefferson.

**Comment by normj** [comment]
Hi @jefferson 

The stream S3 handing back to you is basically just the network stream returned back to S3. The SDK puts a small wrapper around the stream to compute the MD5 as you read but it doesn't affect buffer size. So how much you can read at a time from the stream is controlled by S3 and how much data it sends before you read from the network stream. The SDK itself doesn't do any buffering on reading.

Norm

**Comment by jefferson** [comment]
Thanks Norm and Ashish.
