### ISSUE TITLE
Unable to upload object with PreSigned Url

### ISSUE THREAD

**Issue by rohit3d2003** [aws/aws-sdk-net#1815]
## Description
I am generating a Pre-Signed URL for S3 bucket from Lambda using AWS .Net SDK to upload excel files but the upload is failing with 403 (Forbidden) error. Same upload when tried with PostMan is giving 'SignatureDoesNotMatch' error. Lambda function has 's3:PutObject' action allowed on the bucket. S3 Bucket itself has CORS configured with 'Put' from any origin and headers, along with a bucket policy to allow 's3:PutObject'.

<img width="441" alt="Screen Shot 2021-03-21 at 1 10 03 PM" src="https://user-images.githubusercontent.com/16943885/111919343-c60cbf00-8a46-11eb-9951-2365e1accab0.png">

<img width="652" alt="Screen Shot 2021-03-21 at 1 10 54 PM" src="https://user-images.githubusercontent.com/16943885/111919373-e2106080-8a46-11eb-9279-4da632355734.png">

<img width="608" alt="Screen Shot 2021-03-21 at 1 14 04 PM" src="https://user-images.githubusercontent.com/16943885/111919467-58ad5e00-8a47-11eb-96bb-094f2e6b1b79.png">

### Environment
* SDK Version: AWSSDK.S3 -> 3.5.10
* Targeted .NET Platform:  .Net Core 3.1

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @rohit3d2003,

Good afternoon.

Thanks for posting the question.

Unfortunately, I'm unable to reproduce the issue. Here's the code:
```C#
using Amazon.S3;
using Amazon.S3.Model;
using System;
using System.IO;
using System.Net;

namespace PreSignedUrlTest
{
    class Program
    {
        private static string bucket = "test-bucket-issue1410";
        private static string key = "testkey.jpg";
        private static string filePath = @"<<folder_path>>\IMG_XXXX.jpg";
        static void Main(string[] args)
        {
            var amazonS3Client = new AmazonS3Client();

            var request = new GetPreSignedUrlRequest
            {
                BucketName = bucket,
                Key = key,
                Verb = HttpVerb.PUT,
                Expires = DateTime.Now.AddMinutes(60)
            };
            
            var url = amazonS3Client.GetPreSignedURL(request);

            UploadFile(filePath, url);
        }

        private async static void UploadFile(string filePath, string presignedUrl)
        {
            if (string.IsNullOrWhiteSpace(filePath)) throw new ArgumentNullException("filePath");
            if (string.IsNullOrWhiteSpace(presignedUrl)) throw new ArgumentNullException("presignedUrl");
            if (!File.Exists(filePath)) throw new FileNotFoundException($"File '{filePath}' not found");

            byte[] bytes;
            await using (var fs = File.Open(filePath, FileMode.Open))
            {
                bytes = new BinaryReader(fs).ReadBytes((int)fs.Length);
            }

            var httpRequest = WebRequest.Create(presignedUrl) as HttpWebRequest;
            if(httpRequest != null)
            {
                httpRequest.Method = "PUT";
                httpRequest.ContentLength = bytes.Length;

                using (var requestStream = httpRequest.GetRequestStream())
                {
                    requestStream.Write(bytes, 0, bytes.Length);
                }

                var httpResponse = httpRequest.GetResponse() as HttpWebResponse;
            }
        }
    }
}

``` 

I used the above code (similar to your code) and it works perfectly fine. It could be the S3 bucket configuration issue. Could you also check the value of `Verb` which is set in `GetPreSignedUrlRequest`?

Thanks,
Ashish

**Comment by rohit3d2003** [comment]
@ashishdhingra - You saved my day. The error was related to HttpVerb, somehow I wasn't mapping it correctly. Thank you so much!
