### ISSUE TITLE
How to track events from non-aws users

### ISSUE THREAD

**Issue by hupo376787** [aws/aws-sdk-net#1817]
## The Question

Hi, I want to track non-aws users using my app. So I downloaded mobile analytics and pinpoint.
And found pinpoint seems to track aws users, so should I user mobile analytics to track non-aws users?

![image](https://user-images.githubusercontent.com/14960168/112611446-cb0fab00-8e58-11eb-80b1-7ebe0bee8fa8.png)

And I can't find docs/code targeting uwp platform.

### Environment

* SDK Version: 3.7.0
* Package Version: 3.7.0
* OS Info: Windows 10 19042
* Build Environment: Visual Studio
* Targeted .NET Platform:  Universal Windows Platform

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @hupo376787,

Good morning.

Thanks for posting guidance question. As per page https://aws.amazon.com/mobileanalytics/, `Mobile Analytics is now part of Amazon Pinpoint`.  Following references could be helpful and code in other languages could be easily translated to .NET code using appropriate packages:
- [Amazon Pinpoint Examples Using the AWS SDK for Java](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/examples-pinpoint.html)
- [awsdocs/aws-doc-sdk-examples](https://github.com/awsdocs/aws-doc-sdk-examples) repository. It has folders for .NET and other languages. For instance, Pinpoint example for .NET is located under [aws-doc-sdk-examples/dotnet/example_code_legacy/Pinpoint/](https://github.com/awsdocs/aws-doc-sdk-examples/tree/master/dotnet/example_code_legacy/Pinpoint)
- [Tracking App Usage Data with Amazon Mobile Analytics](https://docs.aws.amazon.com/mobile/sdkforxamarin/developerguide/getting-started-analytics.html).

Hope this helps.

Thanks,
Ashish

**Comment by hupo376787** [comment]
Thanks, @ashishdhingra.
But we found that `AmazonPinpointClient` has several initialization methods. We have `identityPoolId`, `region`, `appId` at hand, and don't know how to initialize `AmazonPinpointClient`. `AmazonPinpointClient` seems to use `awsAccessKeyId` & `awsSecretAccessKey` only.
![image](https://user-images.githubusercontent.com/14960168/112660911-f0201000-8e90-11eb-8e36-32c39382bf57.png)

So in order to track non-aws users using our app, which initialization should we use, thx.

**Comment by ashishdhingra** [comment]
> Thanks, @ashishdhingra.
> But we found that `AmazonPinpointClient` has several initialization methods. We have `identityPoolId`, `region`, `appId` at hand, and don't know how to initialize `AmazonPinpointClient`. `AmazonPinpointClient` seems to use `awsAccessKeyId` & `awsSecretAccessKey` only.
> ![image](https://user-images.githubusercontent.com/14960168/112660911-f0201000-8e90-11eb-8e36-32c39382bf57.png)
> 
> So in order to track non-aws users using our app, which initialization should we use, thx.

Hi @hupo376787,

All AWS service clients (not only `AmazonPinpointClient`) have these overloaded constructors. These parameters, for example credentials,  **are required as a first step to access AWS services** and should not be confused with `identityPoolId` and `appId`. For most cases, if you have AWS credentials and region configured at default locations (refer [Credential and profile resolution](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/creds-assign.html) and [Configure the AWS Region](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/net-dg-region-selection.html)), you can use parameterless constructor. If you are using Cognito, refer [Amazon Cognito Credentials Provider](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/cognito-creds-provider.html).

Hope this helps.

Thanks,
Ashish

**Comment by hupo376787** [comment]
Hi, Ashish. 
I used https://www.nuget.org/packages/AWSSDK/2.3.55.2?_src=template, it's out-dated. That's why I can't pass credentials to `mazonPinpointClient`. Now I use https://www.nuget.org/packages/AWSSDK.CognitoIdentity/3.7.0?_src=template.

```
CognitoAWSCredentials credentials = new CognitoAWSCredentials(appId, poolId, null, null, RegionEndpoint.USEast1);
var pinpoint = new AmazonPinpointClient(credentials);
```

Am I correct now? Can I set the third and fourth params null to track users?
Thx.

**Comment by ashishdhingra** [comment]
> Hi, Ashish.
> I used https://www.nuget.org/packages/AWSSDK/2.3.55.2?_src=template, it's out-dated. That's why I can't pass credentials to `AmazonPinpointClient`. Now I use https://www.nuget.org/packages/AWSSDK.CognitoIdentity/3.7.0?_src=template.
> 
> ```
> CognitoAWSCredentials credentials = new CognitoAWSCredentials(appId, poolId, null, null, RegionEndpoint.USEast1);
> var pinpoint = new AmazonPinpointClient(credentials);
> ```
> 
> Am I correct now? Can I set the third and fourth params null to track users?
> Thx.

@hupo376787 You should have used https://www.nuget.org/packages/AWSSDK.Pinpoint/ package. It has dependency on https://www.nuget.org/packages/AWSSDK.Core/ which provides core functionality including credentials management. 

If you are using Cognito:
- Are your credentials and OpenId provider configured in Cognito Identity Pool?
- You need to specify role for authenticated users? All access to AWS resources, including PinPoint, is controlled by role.
- Is your app using Cognito?

Please refer Cognito documentation for more details on identity pool.

Thanks,
Ashish

**Comment by hupo376787** [comment]
OK, Thanks, @ashishdhingra. I'll check with the backend dev for more details.

Thanks again.

**Comment by hupo376787** [comment]
Hi, @ashishdhingra. I checked the docs on https://github.com/awsdocs/aws-doc-sdk-examples/tree/master/dotnet/example_code_legacy/Pinpoint, we are using 
`AmazonPinpointClient.PutEventsAsync(PutEventsRequest request, CancellationToken cancellationToken = default)`

Is there an example to compose `PutEventsRequest`, I searched known issues, but got no results.
Our code is like below.

```
           CognitoAWSCredentials credentials = new CognitoAWSCredentials(poolId, RegionEndpoint.USEast1);
            var pinpoint = new AmazonPinpointClient(credentials, RegionEndpoint.USEast1);

            Dictionary<string, string> attribute = new Dictionary<string, string> 
            {
                {"event_type", "screen" },
                {"event_screen", "Login" },
                {"screen_metadata", "" },
            };

            Event @event = new Event 
            {
                Attributes = attribute
            };
            Dictionary<string, Event> events = new Dictionary<string, Event>();
            events.Add("Events", @event);

            EventsBatch eventsBatch = new EventsBatch
            {
                Events = events
            };

            Dictionary<string, EventsBatch> batchItem = new Dictionary<string, EventsBatch>();
            batchItem.Add("BatchItem", eventsBatch);

            EventsRequest eventsRequest = new EventsRequest
            {
                BatchItem = batchItem
            };

            PutEventsRequest putEventsRequest = new PutEventsRequest 
            {
                ApplicationId = appId,
                EventsRequest = eventsRequest
            };
                        
            await pinpoint.PutEventsAsync(putEventsRequest);
```

It throws an exception:

Amazon.Pinpoint.AmazonPinpointException: 'User: arn:aws:sts::008213563068:assumed-role/devpinpointtv_unauth_MOBILEHUB_570582113/CognitoIdentityCredentials is not authorized to perform: mobiletargeting:PutEvents on resource: arn:aws:mobiletargeting:us-east-1:008213563068:apps/7b6c7d0f3fc74b228a537807a612e4b7/events'
Inner exception
HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
This exception was originally thrown at this call stack:
    [External Code]

**Comment by ashishdhingra** [comment]
Hi @hupo376787,

Good morning.

Looking at the error, you need to **create a new policy** with permissions for `Pinpoint` services and attach that policy to the **role** you are assuming. You can create policy in AWS IAM Console, it would provide you interface to select the `Pinpoint` service and add relevant permissions (`PutEvents` in this case, you might need to add more permissions depending on your application requirements).
<img width="1218" alt="Screen Shot 2021-03-29 at 9 28 20 AM" src="https://user-images.githubusercontent.com/67916761/112868626-20bea000-9071-11eb-8137-bde7879f0936.png">

For more details, please refer [Policies and permissions in IAM](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies.html). 

Hope this helps. Closing this issue.

Thanks,
Ashish

**Comment by hupo376787** [comment]
@ashishdhingra Thanks we changed another pool and succeeded.
