### ISSUE TITLE
Dependency to Microsoft.Bcl.AsyncInterfaces can cause problems on certain environments running under netcoreapp3.1

### ISSUE THREAD

**Issue by danielmarbach** [aws/aws-sdk-net#1818]
## Description

We recently bumped AWSSDK.SQS from 3.5.1.21 to 3.5.1.27 and ran under Ubuntu Linux under .NET Core 3.1 into the following issue

```
package: 'Microsoft.Bcl.AsyncInterfaces', version: '1.1.0'
path: 'lib/netstandard2.0/Microsoft.Bcl.AsyncInterfaces.dll'
```

More information available at

https://github.com/dotnet/orleans/issues/6028#issuecomment-540233306

The solution was to no longer have a transitive dependency but actually change to an explicit dependency like

https://github.com/Particular/NServiceBus.AmazonSQS/pull/718/commits/387e362b44a4a9da8a316d0223d2782a20028ca5

### Environment

* SDK Version: 
* Package Version: 
* OS Info: 
* Build Environment 
* Targeted .NET Platform:  

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

---

This is a :bug: bug-report

**Comment by normj** [comment]
The .NET Core 3.1 build of the SDK doesn't not have a dependency on Micorosft.Bcl.AsyncInterfaces  https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/AWSSDK.Core.NetStandard.csproj#L74

Are you building something below .NET Core 3.1 but you happen to on machine that has .NET Core 3.1 installed?

**Comment by danielmarbach** [comment]
It might be related to the way we restore dependencies on Linux. We are about to change the way we build and run the things on Linux. Currently, we build on Windows, port the artifacts over and then restore the platform-specific dependencies on Linux. We will soon be moving away from the legacy way of doing things. I'm happy to close this when you haven't  heard other people running into this issue.

**Comment by ashishdhingra** [comment]
`Microsoft.Bcl.AsyncInterfaces ` is not used as dependency on .NET Core 3.1. Closing this since there are no similar issues reported by customers.
