### ISSUE TITLE
AWSConfigs.CorrectForClockSkew is false when not using App.config

### ISSUE THREAD

**Issue by theofanis** [aws/aws-sdk-net#182]
As per Pavel Safronov's blog [post](http://blogs.aws.amazon.com/net/post/Tx2HM54KL5LMTGI/Clock-skew-correction), correction for clock skew should be enabled by default.

I just checked this in my .net application code and `AWSConfigs.CorrectForClockSkew` is `false`. I don't use a config file, as per the [documentation recommendation] (http://docs.aws.amazon.com/AWSSdkDocsNET/latest/DeveloperGuide/net-dg-config.html), but I initialize my s3 clients as shown below:

```
_s3Config = new AmazonS3Config();
_s3Config.RegionEndpoint = Amazon.RegionEndpoint.USWest2;
_s3Config.ProgressUpdateInterval = 2 * 100 * 1024;
s3Client = new AmazonS3Client(accessKeyID, secretAccessKey, sessionToken, _s3Config);
```

I checked the aws code and I see that `AWSConfigs` uses a `RootConfig` to obtain the `CorrectForClockSkew`, which is indeed initialized to `true`.

So, am I missing anything on how I configure my s3 client?

**Comment by PavelSafronov** [comment]
You are not missing anything, this is a bug in the current SDK.
I'm checking in a fix into our local repo and it should be available with the next release of the SDK. For now, you can set `AWSConfigs.CorrectForClockSkew` to `true` in your code to make sure this feature is enabled.

**Comment by theofanis** [comment]
Yes, that's what I currently do, just thought of reporting this. Good to know there's a fix in the pipeline, thanks!

**Comment by PavelSafronov** [comment]
Version 2.3.26 of the SDK has just been released and it contains this fix.
