### ISSUE TITLE
Version conflict with the latest packages

### ISSUE THREAD

**Issue by jasonycw** [aws/aws-sdk-net#1820]
## Description
New packages are not compatible with each others without `AWSSDK.Core`

## Reproduction Steps

Update NuGet packages
![image](https://user-images.githubusercontent.com/4518597/112779295-fbce2b00-9078-11eb-8af2-009b6679535d.png)
Select all the AWSSDK packages
Click `Update`

### Logs
```
Version conflict detected for AWSSDK.Core. Install/reference AWSSDK.Core 3.7.0.1 directly to project Project.Name to resolve this issue. 
 Project.Name -> AWSSDK.SimpleSystemsManagement 3.7.0.1 -> AWSSDK.Core (>= 3.7.0.1 && < 3.8.0) 
 Project.Name -> Amazon.Lambda.S3Events 1.3.0 -> AWSSDK.S3 3.5.3.5 -> AWSSDK.Core (>= 3.5.1.27 && < 3.6.0).
```

### Environment

* SDK Version: 1.3.0
* Package Version: Amazon.Lambda.S3Events
* OS Info: Windows 10
* Build Environment: Visual Studio
* Targeted .NET Platform:  .NET Core 3.1

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

---

This is a :bug: bug-report

**Comment by ashovlin** [comment]
https://github.com/aws/aws-lambda-dotnet/pull/826 is underway to remove .NET Standard 1.3 support as well as update the AWS SDK dependencies from the Lambda packages.

**Comment by ashishdhingra** [comment]
Hi @jasonycw,

Good afternoon.

Please try upgrading to latest versions and verify if upgrade works fine. Kindly let us know in case you face any issues.

Thanks,
Ashish

**Comment by jasonycw** [comment]
Yes, seems like the new packages don't have conflict anymore, thanks
