### ISSUE TITLE
Changing agent status in Amazon Connect

### ISSUE THREAD

**Issue by srivathsah** [aws/aws-sdk-net#1823]
Hi, Is there any possibility to change the status of an agent logged onto Amazon Connect ? I have tried looking into the AWSSDK.AmazonConnectClient and also AWSSDK.AmazonConnectParticipantClient. There are no relevant API calls for this.

* SDK Version: 3.7.0.2

**Comment by ashishdhingra** [comment]
Hi @srivathsah,

Good morning.

Thanks for posting guidance question. Here are the links for Service API reference:
- [Amazon Connect Service API Reference](https://docs.aws.amazon.com/connect/latest/APIReference/Welcome.html)
- [Amazon Connect Participant Service API Reference](https://docs.aws.amazon.com/connect-participant/latest/APIReference/Welcome.html)

The client operations provided by AWS .NET SDK map to available service actions. I'm not sure if there is any service API action that corresponds to changing status of an agent.

Here is the link for [About agent status](https://docs.aws.amazon.com/connect/latest/adminguide/metrics-agent-status.html). Also refer to https://github.com/amazon-connect/amazon-connect-streams/issues/150#issuecomment-567986399 which mentions that it is not supported via Amazon Connect API, but might be available in [Connect Streams API](https://github.com/aws/amazon-connect-streams/blob/master/Documentation.md#agentsetstate--agentsetstatus) (there is no equivalent client in .NET SDK).

Hope this helps.

Thanks,
Ashish

**Comment by srivathsah** [comment]
Hi Ashish,

Thanks a lot for the response, so from what I understand,  we have to create a c# client on our own, could you please confirm if it is feasible to mimic the API calls from the javascript streams project in c# including Auth, or do we have any restrictions on the backend in the auth layer so that only the javascript clients could connect ?

**Comment by ashishdhingra** [comment]
> Hi Ashish,
> 
> Thanks a lot for the response, so from what I understand, we have to create a c# client on our own, could you please confirm if it is feasible to mimic the API calls from the javascript streams project in c# including Auth, or do we have any restrictions on the backend in the auth layer so that only the javascript clients could connect ?

@srivathsah I don't think there should be any restrictions. But what you are talking about if de-factoring the code and translating in C#. I would suggest to post question in https://github.com/amazon-connect/amazon-connect-streams repo to see if something is already available. As far as .NET SDK is concerned, there appears to be no support for changing the status of agent due to unavailable service operation.

Closing this issue now. Let me know if you have any questions.
