### ISSUE TITLE
GetObjectAsync() not working on VS2019 version 16.9.3 - NET 5 app using nuget AWSSDK.S3 version 3.7.0.6

### ISSUE THREAD

**Issue by dlandi** [aws/aws-sdk-net#1824]
## Description
 - VS2019 version: 16.9.3
 - Target Framework: .NET 5
 - Nuget Pkg: AWSSDK.S3 version 3.7.0.6

I posted this on stackoverflow, as well:
https://stackoverflow.com/questions/66910200/getobjectasync-not-working-on-vs2019-version-16-9-3-net-5-app-using-awssdk-s

After upgrading to VS2019 version 16.9.3, I now cannot run S3Client.GetObjectAsync() without getting the error "The provided token is malformed or otherwise invalid".

## Reproduction Steps
```
using Amazon.S3;
using Amazon.S3.Model;

using (var client = new AmazonS3Client("AccessKey",
                       "SecretAccessKey",
                       "MyRegion"))
{
    try
    {
        string BucketName = "my-files";
        string Key = "my.pdf";
        response = await client.GetObjectAsync(BucketName, Key);
    }
    catch (Exception e)
    {
        //Error Here! - "The provided token is malformed or otherwise invalid"
          throw;
    }
}
```

### Environment

* SDK Version: 
* Package Version: 
* OS Info: 
* Build Environment 
* Targeted .NET Platform:  

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

---

This is a :bug: bug-report

**Comment by dlandi** [comment]
***Solved it!*** 

The specific change that has been introduced somewhere is that the "Region" parameter in

    new AmazonS3Client()

can no longer be a string. It must be a RegionEndpoint Enum. (Even though the API allows a string!)

So this works:

    var client = new AmazonS3Client(key, secret, RegionEndpoint.EUCentral1)

I have a work-around, but this is a bug.

**Comment by ashishdhingra** [comment]
> _**Solved it!**_
> 
> The specific change that has been introduced somewhere is that the "Region" parameter in
> 
> ```
> new AmazonS3Client()
> ```
> 
> can no longer be a string. It must be a RegionEndpoint Enum. (Even though the API allows a string!)
> 
> So this works:
> 
> ```
> var client = new AmazonS3Client(key, secret, RegionEndpoint.EUCentral1)
> ```
> 
> I have a work-around, but this is a bug.
> 
> Previously, I could use "eu-central-1" or "us-east-1", which is a lot more convenient because I can read it directly from appsettings.json.
> 
> It could be that the accepted string format has changed for this parameter (but why!)

Hi @dlandi,

Good morning.

Looking at tht SDK code base, the `AmazonS3Client` supports constructor overload with 3 string parameters [public AmazonS3Client(string awsAccessKeyId, string awsSecretAccessKey, string awsSessionToken)](https://github.com/aws/aws-sdk-net/blob/bebc73ea3ec79563dedf90695f63f82dd288bc9f/sdk/src/Services/S3/Generated/_netstandard/AmazonS3Client.cs#L175). However, the 3rd parameter corresponds to `SessionToken`, not the `RegionEndpoint`. In such a case, SDK tries to find the region in the default locations as specified in section **Specify a Region for all service clients** in [Configure the AWS Region](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/net-dg-region-selection.html). Not sure if you had region configured earlier at any of the default locations. Your workaround is one of the ways to specify region endpoint, although this hardcodes the S3 client to specific region.

Hope this helps.

Closing this issue as guidance.

Thanks,
Ashish
