### ISSUE TITLE
S3 Select CSV Serialization Issue

### ISSUE THREAD

**Issue by tomas-sezima** [aws/aws-sdk-net#1825]
## Description
Data obtained through `AmazonS3Client`'s `SelectObjectContentAsync` method do not obey line endings (record delimiters) specified via `InputSerialization` and/or `OutputSerialization` CSV configurations. 

## Reproduction Steps
Having the following CRLF CSV stored in targeted S3 bucket,

```
A,B\r\n
1,2\r\n
3,4\r\n
```

a code snippet

```
var inSer = new InputSerialization()
{
    CSV = new CSVInput()
    {
        FileHeaderInfo = FileHeaderInfo.Use,
        RecordDelimiter = "\r\n"
    }
};

var outSer = new OutputSerialization()
{
    CSV = new CSVOutput()
    {
        RecordDelimiter = "\n"
    }
};

var response = await client.SelectObjectContentAsync(
    new SelectObjectContentRequest
    {
        Bucket = <bucket>,
        Key = <object>,
        Expression = "select * from s3object",
        ExpressionType = ExpressionType.SQL,
        InputSerialization = inSer,
        OutputSerialization = outSer
    }
);
```

would result in a response that (contrary to expectations) contains carriage return characters:

```
1,2\r\n
3,4\r\n
```

Interestingly, if no `RecordDelimiter` is specified in `OutputSerialization` config, responses only contain newline characters, i.e. 

```
1,2\n
3,4\n
```

This, however, only applies for Windows - when executed in `mcr.microsoft.com/dotnet/runtime:5.0` based Docker container, carriage returns would still be included in the responses 🤯

### Environment
* SDK Version: `3.7.0.8`
* OS Info: `Windows 10`
* Build Environment: `Visual Studio`
* Targeted .NET Platform:  `.NET 5`
---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Reproducible on both Windows and Mac using `AWSSDK.S3 3.7.0.8` package using code below (examine the value of `text` in Visual Studio debugger):
```C#
using Amazon.S3;
using Amazon.S3.Model;
using System;
using System.IO;
using System.Text;

namespace S3Select_Issue1825
{
    class Program
    {
        static void Main(string[] args)
        {
            AmazonS3Client client = new AmazonS3Client();
            var inSer = new InputSerialization()
            {
                CSV = new CSVInput()
                {
                    FileHeaderInfo = FileHeaderInfo.Use,
                    RecordDelimiter = "\r\n"
                }
            };

            var outSer = new OutputSerialization()
            {
                CSV = new CSVOutput()
                {
                    RecordDelimiter = "\n"
                }
            };

            var response = client.SelectObjectContentAsync(
                new SelectObjectContentRequest
                {
                    Bucket = "<<bucket_name>>",
                    Key = "<<key>>",
                    Expression = "select * from s3object",
                    ExpressionType = ExpressionType.SQL,
                    InputSerialization = inSer,
                    OutputSerialization = outSer
                }
            ).Result;

            using (var stream = response.Payload)
            {
                foreach (var ev in stream)
                {
                    if (ev is RecordsEvent records)
                    {
                        Console.WriteLine("Got record event");
                        using (var reader = new StreamReader(records.Payload, Encoding.UTF8))
                        {
                            string text = reader.ReadToEnd();
                        }
                    }
                }
            }
        }
    }
}
```
Few observations:
- Looking at the Example 1 at https://docs.aws.amazon.com/AmazonS3/latest/API/API_SelectObjectContent.html, it appears that the default `RecordDelimiter` for `OutputSerialization` is `\n`.
- However,  explicitly setting `RecordDelimiter` it to `\n` in code causes it to return `\r\n`.
- Setting `RecordDelimiter` to some other string (e.g. `__`) works fine.

Thanks,
Ashish

**Comment by ashishdhingra** [comment]
This has been fixed in `AWSSDK.S3` version `3.7.0.18` as part of commit https://github.com/aws/aws-sdk-net/commit/a9ae2b5dc89765289ea43031fb56f5220584b00c.
