### ISSUE TITLE
Deserializing Booleans in AttributeValue from Json is broken.

### ISSUE THREAD

**Issue by ajmcateer** [aws/aws-sdk-net#1828]
## Description
When you take the DynamoDB stream record and run that through de serialization it sets the isBOOLSet correctly inside the attribute value but always sets the actual boolean to false. 

## Reproduction Steps
Try and de-serialize a DynamoDB stream record with an AttributeValue with a Boolean set to true with Newtonsoft

### Environment
* Package Version: 3.7.0.10
* OS Info: Windows 10
* Build Environment: Visual Studio 2019
* Targeted .NET Platform: 3.1

## Resolution
There are a few ways to fix this. 

In AttributeValue just add a new private field for isBoolSet and pass that in instead 

Change 

		private bool? _bool;
               Amazon.Util.Internal.InternalSDKUtils.SetIsSet(value, ref this._bool);

To

		private bool? _isBoolSet;
               Amazon.Util.Internal.InternalSDKUtils.SetIsSet(value, ref this._isBoolSet);

I would do it myself but the file says it was generated and not to make changes which makes a simple fix much harder. If making this change manually is an option let me know and I will submit the request tonight. 

EDIT: After thinking about it more there is no way to resolve this issue without changing AttributeValue manually. Just add another field to track isBoolSet instead of passing the actual bool in by ref.

The other option would be to set _bool to null and if its false or true then its set otherwise its not set.

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @ajmcateer,

Good morning.

Thanks for posting the issue. Although the issue might be quite obvious, would it be possible for you to provide sample code solution to help troubleshoot the issue?

Thanks,
Ashish

**Comment by ajmcateer** [comment]
Hi @ashishdhingra,

The issue is that BOOL will always be set to false during de-serialization. I create a sample project on my github you can pull down and check out.

https://github.com/ajmcateer/AWS.BOOL.Example

To go into more detail, below I have pasted a json string which will de-serialize to an AttributeValue. As you can see below both bool and IsBOOLSet are true.

```
{
	"bool": true,
	"isBOOLSet": true,
	"bs": [],
	"l": [],
	"isLSet": false,
	"m": { },
	"isMSet": false,
	"ns": [],
	"null": false,
	"ss": []
}
```

After de-serializing it to an AttributeValue using the Newtonsoft.Json package, the value became false.

![image](https://user-images.githubusercontent.com/7401629/115123742-6bef1300-9f8c-11eb-92b6-458b7904a85b.png)

This is copied from example-processed.json which my example program writes to the working folder after.

```
{
  "B": null,
  "BOOL": false,
  "IsBOOLSet": true,
  "BS": [],
  "L": [],
  "IsLSet": false,
  "M": {},
  "IsMSet": false,
  "N": null,
  "NS": [],
  "NULL": false,
  "S": null,
  "SS": []
}
```

The issue is because the bool property and IsBoolSet both use _bool as the backing field
        
```
        private bool? _bool;
        ...
        public bool BOOL
        {
            get { return this._bool.GetValueOrDefault(); }
            set { this._bool = value; }
        }
        ...
        public bool IsBOOLSet
        {
            get
            {
                return Amazon.Util.Internal.InternalSDKUtils.GetIsSet(this._bool);
            }
            set
            {
                Amazon.Util.Internal.InternalSDKUtils.SetIsSet(value, ref this._bool);
            }
        }
```


When the Set method is called for IsBOOLSet it passes _bool in by reference in the 2nd Parameter otherwise known as field. Since IsBoolSet is true the line "field = default(T);" is executed.


```
    public static void SetIsSet<T>(bool isSet, ref Nullable<T> field)  where T : struct
    {
        if (isSet)
            field = default(T);
        else
            field = null;
    }
```

field is then changed to be default which as you pointed out for Booleans is false. Since it was passed in by reference you mutated the field holding my true boolean to false.

bool in AttributeValue will always de-serialize to false every time with no exceptions. As far as I can tell this has always been the case.

As for the fix I'm at a loss at the moment. The file is generated and has do not edit at the top. I don't think this can be fixed in SetIsSet. I honestly don't understand why this method exists. IsBoolSet is read from the json string as well as BOOL, thus they are set correctly. Why BOOL needs any extra processing is what I can't explain. 

The simplest fix would be to give IsBOOLSet its own backing field and remove the call to SetIsSet all together, but since that file is not supposed to be edited manually, I guess the file will have to be re-generated to fix the issue.

```
       private bool _isBoolSet;

        public bool IsBOOLSet
        {
            get
            {
                return Amazon.Util.Internal.InternalSDKUtils.GetIsSet(this._bool);
            }
            set
            {
                _isBoolSet = value;
            }
        }
```

**Comment by raul-taurus** [comment]
If the field is already set, we should not set a default value, so it should be: 
```
    public static void SetIsSet<T>(bool isSet, ref Nullable<T> field)  where T : struct
    {
        if (isSet && !field.HasValue)
            field = default(T);
        else
            field = null;
    }
```

**Comment by MohammadKh** [comment]
C'mon! After more than 2 years since it is reported, the issue is still open and people are facing the same issue over and over!

**Comment by joshtramposo** [comment]
A fix for everybody in C#:
  
  public static T FixDynamoDbBooleansDeserialize<T>(this T entity, Document itemAsDocument)
  {
      //Fix for dynamoDb bug when deserializing boolean values
      if (entity!.GetType().GetProperties().Where(x => x.PropertyType == typeof(bool?)).Any())
      {
          foreach (var boolProperty in entity!.GetType().GetProperties().Where(x => x.PropertyType == typeof(bool?)).ToList())
          {
              
              if (itemAsDocument.ContainsKey(boolProperty.Name))
              {
                  if (itemAsDocument[boolProperty.Name].AsDynamoDBBool() != null)
                  {
                      boolProperty.SetValue(entity, itemAsDocument[boolProperty.Name].AsBoolean());
                  }
              }
          }
      }

      return entity;
  }

**Comment by GordonSo** [comment]
> A fix for everybody in C#:
> 
> ```
>   public static T FixDynamoDbBooleansDeserialize<T>(this T entity, Document itemAsDocument)
>   {
>       //Fix for dynamoDb bug when deserializing boolean values
>       if (entity!.GetType().GetProperties().Where(x => x.PropertyType == typeof(bool?)).Any())
>       {
>           foreach (var boolProperty in entity!.GetType().GetProperties().Where(x => x.PropertyType == typeof(bool?)).ToList())
>           {
>               
>               if (itemAsDocument.ContainsKey(boolProperty.Name))
>               {
>                   if (itemAsDocument[boolProperty.Name].AsDynamoDBBool() != null)
>                   {
>                       boolProperty.SetValue(entity, itemAsDocument[boolProperty.Name].AsBoolean());
>                   }
>               }
>           }
>       }
> 
>       return entity;
>   }
> ```

It didn't work for me `itemAsDocument[boolProperty.Name].AsDynamoDBBool()` is null so it doesn't set the property correctly. However, you approach has inspired me with the following as a hackaround:
 
```
    private static T FixDynamoDbBooleansDeserialize<T>(T entity, Document itemAsDocument)
    {
        // Fix for dynamoDb bug when deserializing boolean values
        // https://github.com/aws/aws-sdk-net/issues/1828
        var boolProperties = entity!.GetType()
            .GetProperties()
            .Where(x => x.PropertyType == typeof(bool) || x.PropertyType == typeof(bool?))
            .ToList();

        if (!boolProperties.Any())
        {
            return entity;
        }

        foreach (var boolProperty in boolProperties)
        {
            bool? value = itemAsDocument.ContainsKey(boolProperty.Name) ? itemAsDocument[boolProperty.Name].AsString() == "True" : null;
            boolProperty.SetValue(entity, value);
        }

        return entity;
    }
```

**Comment by dscpinheiro** [comment]
@raul-taurus PR was included in yesterday's release, and it's available in the last version of the [AWSSDK.DynamoDBv2](https://www.nuget.org/packages/AWSSDK.DynamoDBv2) package.

Thanks again for the contribution!
