### ISSUE TITLE
Specify Tags and TransitiveTagKeys in AssumeRoleAWSCredentialsOptions

### ISSUE THREAD

**Issue by JeffAshton** [aws/aws-sdk-net#1829]
Would like to see `Tags` and `TransitiveTagKeys` added to `Amazon.Runtime.AssumeRoleAWSCredentialsOptions`.  Session tags allow fine grained control access to resources.  It would be amazing if `AssumeRoleAWSCredentials` supported this.

## Proposed Solution
* Add `Tags` and `TransitiveTagKeys` to [Amazon.Runtime.AssumeRoleAWSCredentialsOptions](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Credentials/AssumeRoleAWSCredentialsOptions.cs)
* Pass the `Tags` and `TransitiveTagKeys` to the `Amazon.SecurityToken.Model.AssumeRoleRequest` via [Amazon.SecurityToken.AmazonSecurityTokenServiceClient.CredentialsFromAssumeRoleAuthentication](https://github.com/aws/aws-sdk-net/blob/96d631d32d45478a4bfacbd832ee7835a28eaed8/sdk/src/Services/SecurityToken/Custom/AmazonSecurityTokenServiceClient.Extension.cs#L151) method

* [X] :wave: I may be able to implement this feature request
* [X] :warning: This feature might incur a breaking change depending on what class name is used for `Tag` in the namespace `Amazon.Runtime` of `AWSSDK.Core`

---

This is a :rocket: Feature Request

**Comment by JeffAshton** [comment]
Just a thought, but adding an equivalent replacement for `AssumeRoleAWSCredentials`  that lives in the Security Token assembly might be more ideal.  That way it can reuse the `Tag` model class, and the assembly dependency is explicit instead of implicit.  It's annoying when this fails at runtime because you forgot to reference the Security Token package as well.

**Comment by ashishdhingra** [comment]
[ICoreAmazonSTS.CredentialsFromAssumeRoleAuthentication](https://github.com/aws/aws-sdk-net/blob/5d21419c15faca581bce8ee27c689c6634702b74/sdk/src/Services/SecurityToken/Custom/AmazonSecurityTokenServiceClient.Extension.cs#L151) extension method is currently only used internally in [AssumeRoleAWSCredentials.GenerateNewCredentials()](https://github.com/aws/aws-sdk-net/blob/5d21419c15faca581bce8ee27c689c6634702b74/sdk/src/Core/Amazon.Runtime/Credentials/AssumeRoleAWSCredentials.cs#L118). [AmazonSecurityTokenServiceClient](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/SecurityToken/Generated/_netstandard/AmazonSecurityTokenServiceClient.cs) supports [AssumeRoleAsync()](https://github.com/aws/aws-sdk-net/blob/5d21419c15faca581bce8ee27c689c6634702b74/sdk/src/Services/SecurityToken/Generated/_netstandard/AmazonSecurityTokenServiceClient.cs#L432) which has support for tags (as specified by [AWS Security Token Service -> AssumeRole](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html) service API. May be adding support for tags and transitive keys in the extension method could be helpful for user. Not sure if this should be added in `AssumeRoleAWSCredentialsOptions` as it might be a breaking change. Needs review with the team.

**Comment by ashishdhingra** [comment]
[AWSSDK.SecurityToken](3.7.300.107) added support for `Tags` and `TransitiveTagKeys` in `ICoreAmazonSTS.CredentialsFromAssumeRoleAuthentication()` method.
