### ISSUE TITLE
DynamoDBTraceListener, RangeKey timestamp is formatted as String with seconds precision

### ISSUE THREAD

**Issue by mahoua** [aws/aws-sdk-net#183]
DynamoDBTraceListener can only log one message per second. Every other log messages created during that second will overwrite the message.

The cause : 
In the following file,
https://github.com/aws/aws-sdk-net/blob/master/AWS.Extensions/TraceListener/DynamoDBTraceListener.cs

Line 445 : return doc[key].AsString();

In the case where key is a DateTime (for example when used for the RangeKey with format {Timestamp}, as instructed in the sample documentation,) this gets rendered as "2015-03-18 11:45:01", which is a string without milliseconds. I think internally it does a simple ToString() on the DateTime, where it should do a ToString("o") or some other alternative that would preserve at least milliseconds precision.

The problem with using this string format for dates is that I can only log one message per second. Every log happening during that second will overwrite the previous ones.

Thanks for your time!

**Comment by PavelSafronov** [comment]
Thanks for bringing this to our attention. This issue has been fixed in our internal repo and the fix will go out with the next release of the SDK.

**Comment by PavelSafronov** [comment]
Version 2.3.26 of the SDK has just been released and it contains this fix.

**Comment by mahoua** [comment]
Thanks! I confirm that 2.3.26 fixed my issues.
