### ISSUE TITLE
VS2019 project template AWSServerless1 generates "Unable to get IAM security credentials from EC2 instance metadata service"

### ISSUE THREAD

**Issue by chrisgull** [aws/aws-sdk-net#1830]
## The Question

Why am I unable to build this VS2019 project template?

Attempting to build and run the VS2019 project template
"AWS Lambda Project with Tests (.Net Core - C#)"
which creates two projects AWSServerless1 and AWSServerless1.Tests,
everything works fine, including publishing the AWSServerless1 project to my AWS account.

However, running the AWSServerless1.Tests causes the following failure.

The only authentication configuration I have done is create a new root AWS account, and use that account when I configured the AWS extension for VS2019. 
Do I have to use an IAM user instead?

`[xUnit.net 00:00:02.23]     AWSServerless1.Tests.FunctionTest.BlogTestAsync [FAIL]
  Failed AWSServerless1.Tests.FunctionTest.BlogTestAsync [1 ms]
  Error Message:
   System.AggregateException : One or more errors occurred. (**Unable to get IAM security credentials from EC2 Instance Metadata Service**.)
---- Amazon.Runtime.AmazonServiceException : Unable to get IAM security credentials from EC2 Instance Metadata Service.
  Stack Trace:
     at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at AWSServerless1.Tests.FunctionTest..ctor() in C:\dev\Monochrome\AWSServerless1.Tests\FunctionTest.cs:line 30
----- Inner Stack Trace -----
   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.FetchCredentials()
   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentials()
   at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentialsAsync()
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at AWSServerless1.Tests.FunctionTest.SetupTableAsync() in C:\dev\Monochrome\AWSServerless1.Tests\FunctionTest.cs:line 148

Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: 1 ms - AWSServerless1.Tests.dll (netcoreapp3.1)`

### Environment

Windows 10 Pro
Visual Studio 2019 16.9.2
Targeting .NET Core 3.1
AWS Toolkit for Visual Studio 2017 and 2019 version 1.20.2.0
Amazon.Lambda.Core 2.0.0
Amazon.Lambda, APIGatewayEvents 2.4.0
Amazon.Lambda.Serialization.SystemTextJson 2.1.0
AWSSDK.DynamoDBv2 3.7.0.11
Newtonsoft.Json 13.0.0

---

This is a :question: general question

**Comment by chrisgull** [comment]
More info:
I'm following the instructions in the readme.md file provided with my instantiated project. It's the "Execute unit tests" part that fails with the above log.

`# Amazon DynamoDB Blog API Serverless Application Project

This starter project consists of:
* serverless.template - an AWS CloudFormation Serverless Application Model template file for declaring your Serverless functions and other AWS resources
* Function.cs - class file containing the C# methods mapped to the Serverless functions declared in the template file
* Blog.cs - file containing a C# class representing a blog entry in the DynamoDB table
* aws-lambda-tools-defaults.json - default argument settings for use with Visual Studio and command line deployment tools for AWS

You may also have a test project depending on the options selected.

The generated project contains a Serverless template declaration for a simple web API for blogging with the blog data stored in a DynamoDB table. The blogging API functions are hosted as a set of AWS Lambda functions that will be exposed through Amazon API Gateway as HTTP operations. Edit the template to customize the functions or add more functions and other resources needed by your application, and edit the function code in Function.cs/Blog.cs. You can then deploy your Serverless application.

## Here are some steps to follow from Visual Studio:

To deploy your Serverless application, right click the project in Solution Explorer and select *Publish to AWS Lambda*.

To view your deployed application open the Stack View window by double-clicking the stack name shown beneath the AWS CloudFormation node in the AWS Explorer tree. The Stack View also displays the root URL to your published application.

## Here are some steps to follow to get started from the command line:

Once you have edited your template and code you can deploy your application using the [Amazon.Lambda.Tools Global Tool](https://github.com/aws/aws-extensions-for-dotnet-cli#aws-lambda-amazonlambdatools) from the command line.

Install Amazon.Lambda.Tools Global Tools if not already installed.
```
    dotnet tool install -g Amazon.Lambda.Tools
```

If already installed check if new version is available.
```
    dotnet tool update -g Amazon.Lambda.Tools
```

Execute unit tests
```
    cd "AWSServerless1/test/AWSServerless1.Tests"
    dotnet test
```

Deploy application
```
    cd "AWSServerless1/src/AWSServerless1"
    dotnet lambda deploy-serverless
```
`

**Comment by ashishdhingra** [comment]
Hi @chrisgull,

Good morning.

 Thanks for posting guidance question. You need to configure your credentials in any of the search locations specified in the page [Credential and profile resolution](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/creds-assign.html). AWS SDK for .NET searches for credentials in a certain order and uses the first available set for the current application. If you notice, `Amazon EC2 instance metadata` is the last one to be searched. Since your machine is not an EC2 instance with attached role, it error out.

Hope this helps.


Thanks,
Ashish

**Comment by chrisgull** [comment]
Found solution. 
As expected, it was a credentials issue.
The source code in the Test project uses default credentials in accessing DynamoDB:

```
	TableName = "AWSServerless1-Blogs-" + DateTime.Now.Ticks;
	DDBClient = new AmazonDynamoDBClient( RegionEndpoint.USWest2 );
	SetupTableAsync( ).Wait( );
```
As I understand it, default credentials are pulled from app.config, if it exists. 
The readme.md file does not mention credentials configuration for the test, so in my attempt to run the test I had not configured any credentials.
Hardcoding my access key solved the problem (and setting the preferred region):

```
	TableName = "AWSServerless1-Blogs-" + DateTime.Now.Ticks;
	var cred = new BasicAWSCredentials( [my access key], [my secret] );
	DDBClient = new AmazonDynamoDBClient( cred, RegionEndpoint.USWest1 );
	SetupTableAsync( ).Wait( );
```
Perhaps the readme.md file for the test project should mention credentials configuration to avoid confusion like this.
