### ISSUE TITLE
AWSSDK.DAX.Client not compatible with AWSSDK.DynamoDBv2 latest versions

### ISSUE THREAD

**Issue by albertocorrales** [aws/aws-sdk-net#1831]
## Reproduction Steps
Latest version of package AWSSDK.DAX.Client https://www.nuget.org/packages/AWSSDK.DAX.Client/2.0.1 is only compatible with AWSSDK.DynamoDBv2 (>= 3.3.15.1 && < 3.4.0). However, new version have been published since then. Latest one is 3.7.x

### Logs
If you try to use package AWSSDK.DAX.Client with newer version of  AWSSDK.DynamoDBv2 you get this warning:

Severity	Code	Description	Project	File	Line	Suppression State
Warning	NU1608	Detected package version outside of dependency constraint: AWSSDK.DAX.Client 2.0.1 requires AWSSDK.DynamoDBv2 (>= 3.3.15.1 && < 3.4.0) but version AWSSDK.DynamoDBv2 3.5.1.2 was resolved.	

### Environment
* SDK Version: 3.5.1
* Package Version: AWSSDK.DynamoDBv2 3.5.1.2
* OS Info: Windows
* Build Environment  Visual Studio
* Targeted .NET Platform:  dotnet core 3.1

## Resolution
I think new version of package AWSSDK.DAX.Client should be published. I there were not breaking changes in AWSSDK.DynamoDBv2 dependency, updating dependency version constrains on AWSSDK.DynamoDBv2 should be enough.

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @albertocorrales,

Good morning.

We have forwarded this request internally to the respective team, would post any update accordingly.

Thanks,
Ashish

**Comment by ashishdhingra** [comment]
Hi @albertocorrales,

This has been fixed in [AWSSDK.DAX.Client 2.0.2](https://www.nuget.org/packages/AWSSDK.DAX.Client/2.0.2).

Thanks,
Ashish

**Comment by smashedtoatoms** [comment]
This is happening again in versions greater than 4.0.0.0
