### ISSUE TITLE
Missing svg mime type

### ISSUE THREAD

**Issue by michal1106** [aws/aws-sdk-net#184]
Hi There,

We are using 
TransferUtility.UploadDirectory (TransferUtilityUploadDirectoryRequest)
We have svg file in it

I've seen that 
https://github.com/aws/aws-sdk-net/blob/5f19301ee9fa1ec29b11b3dfdee82071a04ed5ae/AWSSDK_DotNet35/Amazon.S3/Util/AmazonS3Util.cs
is missing .svg mime type 
so we are getting 
application/octet-stream
for it instead of 
image/svg+xml 
which means that the browser doesn't display this image file 

Can you add this to the extensionToMime in the AmazonS3Util.cs?
When do you plan to have your next release?

Much Thanks,
Michal

**Comment by PavelSafronov** [comment]
I've added the .svg mime type in our internal repo, it will be available with the next release. Unfortunately, I cannot say when the next SDK release will be.

In the meantime, you can use the below approach to modify the ContentType and other properties on individual file uploads.
`
uploadDirectoryRequest.UploadDirectoryFileRequestEvent += (s, e) =>
{
    var uploadRequest = e.UploadRequest;
    var path = uploadRequest.FilePath;

    if (Path.GetExtension(path).Equals(".svg", StringComparison.OrdinalIgnoreCase))
    {
        uploadRequest.ContentType = "image/svg+xml";
    }
};
`

**Comment by michal1106** [comment]
Thanks for your quick reply and for the workaround that you suggested!!

Nice to learn new things :)

**Comment by jimfl** [comment]
This was fixed in version 2.3.27 of the SDK. https://aws.amazon.com/releasenotes/.NET/6728787774361892
