### ISSUE TITLE
Subnet creation option for Auto-assign public IPv4 address

### ISSUE THREAD

**Issue by Evgeny-at-avocado** [aws/aws-sdk-net#1840]
## Describe the Feature
Need an option to enable Auto-assign public IPv4 address for new subnet.

## Proposed Solution
Add new flag to CreateSubnetRequest

### Describe alternatives you've considered
Currently need to open AWS console and manually enable for subnet

This is a :rocket: Feature Request

Thanks

**Comment by ashishdhingra** [comment]
Hi @Evgeny-at-avocado,

Good morning.

Upon further research, [Amazon.EC2.AmazonEC2Client.CreateSubnetAsync()](https://raw.githubusercontent.com/aws/aws-sdk-net/master/sdk/src/Services/EC2/Generated/_netstandard/AmazonEC2Client.cs) invokes [CreateSubnet](http://docs.aws.amazon.com/goto/WebAPI/ec2-2016-11-15/CreateSubnet) service operation. The [CreateSubnet](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateSubnet.html) API operation does not support any flag/option which allows to enable auto-assign IP address for the new subnet. Hence, this is not supported by .NET SDK.

After subnet creation, you may try using [Amazon.EC2.AmazonEC2Client.ModifySubnetAttributeAsync()](https://raw.githubusercontent.com/aws/aws-sdk-net/master/sdk/src/Services/EC2/Generated/_netstandard/AmazonEC2Client.cs) which invokes [ModifySubnetAttribute](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifySubnetAttribute.html) service API operation. The [Amazon.EC2.Model.ModifySubnetAttributeRequest](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/EC2/Generated/Model/ModifySubnetAttributeRequest.cs) appears to have property `MapPublicIpOnLaunch` which might suffice your requirement.

Let me know if this helps.

Thanks,
Ashish

**Comment by Evgeny-at-avocado** [comment]
Hi, works perfectly.

Thanks for prompt response.

Regards,
Evgeny
