### ISSUE TITLE
ELB creation option for type

### ISSUE THREAD

**Issue by Evgeny-at-avocado** [aws/aws-sdk-net#1841]
## Describe the Feature
Need a way to set ELB type during creation. Currently it defaults to classic.

## Proposed Solution
Add new string field to CreateLoadBalancerRequest

This is a :rocket: Feature Request

Thanks

**Comment by ashishdhingra** [comment]
Hi @Evgeny-at-avocado,

Good morning.

Thanks for posting the issue. Upon looking at the .NET API documents, there is are new set of classes under [Amazon.ElasticLoadBalancingV2](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/ElasticLoadBalancingV2/NELBV2.html) namespace. The class [Amazon.ElasticLoadBalancingV2.Model. CreateLoadBalancerRequest](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/ElasticLoadBalancingV2/TCreateLoadBalancerRequest.html) has a property `Type` which accepts value from enum [Amazon.ElasticLoadBalancingV2.LoadBalancerTypeEnum](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/ElasticLoadBalancingV2/TLoadBalancerTypeEnum.html) allowing values `Application`, `Gateway` and `Network`. Please use this new set of classes.

The older namespace [Amazon.ElasticLoadBalancing](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/ELB/NELB.html) only supports classic type.

Hope this helps.

Thanks,
Ashish
