### ISSUE TITLE
DuplicateItemException on SaveAsync

### ISSUE THREAD

**Issue by DizzyDeveloper** [aws/aws-sdk-net#1842]
## The Question

Probably a simple question.

Is it possible to make the SaveAsync throw a DuplicateItemException? Or do I need to manually perform LoadAsync check first, then if the item already exist manually throw an exception?

I couldn't find any info around this, it appears possible to do via the lower level PutItem, but not via the DynamoDB context SaveAsync.
If this documentation doesn't exist would be nice if this behaviour is detailed. Unless I missed that point in then docs then apologies.

### Environment

* Package: AWSSDK.DynamoDBv2
* SDK Version: 3.7.0.16
* Package Version:  3.7.0.16
* OS Info: Windows 10 
* Build Environment Visual Studio
* Targeted .NET Platform:  core3.1 or netstandard2.1

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @DizzyDeveloper,

Good morning.

Thanks for posting the guidance question. Based on testing using the code below, looks like `DynamoDBContext` updates the item if it is trying to save the item with the existing key:
```C#
 using System;
using Amazon;
using Amazon.DynamoDBv2;
using Amazon.DynamoDBv2.DataModel;
using Amazon.Runtime;

namespace DynamoDbTest_Issue1842
{
    class Program
    {
        private static AmazonDynamoDBClient client = new AmazonDynamoDBClient();

        static void Main(string[] args)
        {
            try
            {
                DynamoDBContext context = new DynamoDBContext(client);
                int id = 1001;
                TestTable test = new TestTable
                {
                    Id = id,
                    Title = "Object Persistence"
                };

                context.SaveAsync(test).ConfigureAwait(false);
                test.Title = "Object Persistence - Modified";
                context.SaveAsync(test).ConfigureAwait(false); ;

                Console.WriteLine("To continue, press Enter");
                Console.ReadLine();
            }
            catch (AmazonDynamoDBException e) { Console.WriteLine(e.Message); }
            catch (AmazonServiceException e) { Console.WriteLine(e.Message); }
            catch (Exception e) { Console.WriteLine(e.Message); }
        }
    }

    [DynamoDBTable("testtable")]
    public class TestTable
    {
        [DynamoDBHashKey] //Partition key
        public int Id
        {
            get; set;
        }
        [DynamoDBProperty]
        public string Title
        {
            get; set;
        }
    }
}
```

This is aligned with the documentation at [DynamoDBContext Class](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DotNetDynamoDBContext.html) for `Save` which specifies that `Saves the specified object to the table. If the primary key specified in the input object doesn't exist in the table, the method adds a new item to the table. If the primary key exists, the method updates the existing item.`. I do not see any option to override this behavior.

Hope this helps.

Thanks,
Ashish

**Comment by DizzyDeveloper** [comment]
Hi @ashishdhingra 
Thanks for that, so I either have to use the low level api, or manually check first.
It would be nice if there was an `InsertAsync` function of sorts that would actually throw an exception if there is a primary key conflict.
Thanks,
DizzyDeveloper

**Comment by ashishdhingra** [comment]
> Hi @ashishdhingra
> Thanks for that, so I either have to use the low level api, or manually check first.
> It would be nice if there was an `InsertAsync` function of sorts that would actually throw an exception if there is a primary key conflict.
> Or maybe even just an `ExistAsync` function
> Thanks,
> DizzyDeveloper

@DizzyDeveloper The proposed `ExistsAsync` function would also need to call something like `LoadAsync` in background to check for the existence of an item with the given hash key. Not sure if this could be prioritized soon given that the workaround is available. Feel free to add `feature-request` label and remove `guidance` label, or close this issue.

Thanks,
Ashish
