### ISSUE TITLE
ThirdParty.Json.LitJson.JsonData objects created after the creation of AmazonSecretsManagerClient

### ISSUE THREAD

**Issue by JuanZamudioGBM** [aws/aws-sdk-net#1843]
## The Question
I have a lambda in .net core netcoreapp2.1  that uses an AmazonSecretsManagerClient that is injected through DI
In the constructor of the lambda we inject de client like this

```
public class MyLambda
{
    public MyLambda()
    {
        var serviceCollection = new ServiceCollection();
        this.ConfigureServices(serviceCollection);
        this.ServiceProvider = serviceCollection.BuildServiceProvider();
    }
    private void ConfigureServices(IServiceCollection serviceCollection)
    {
        serviceCollection.AddScoped<IAmazonSecretsManager, AmazonSecretsManagerClient>();
        serviceCollection.AddScoped<ISecretsRepository, SecretsRepository>();
    }
} 
```

SecretsRepository  receives an IAmazonSecretsManager in the constructor and gets the secret.

Before the initialization of AmazonSecretsManagerClient I have around 3000 objects in memory, after AmazonSecretsManagerClient  is initialized and made a call to get a secret I have 46k+ new objects
![image](https://user-images.githubusercontent.com/28072896/116617184-2d017b80-a903-11eb-9955-7d561a964ea4.png)

Most of the objects are used by the secrets manager client
![image](https://user-images.githubusercontent.com/28072896/116617509-88cc0480-a903-11eb-8943-739a2a36a3f9.png)

Is this behavior normal? Or the secret client is being is not being created correctly?

### Environment
netcoreapp2.1 lambda
Amazon.Lambda.Core 2.0.0
Amazon.Lambda.Serialization.Json 2.0.0
AWSSDK.Lambda 3.7.0.15
AWSSDK.SecretsManager 3.7.0.15
Windows 10
Visual Studio 2019 16.9.4

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @JuanZamudioGBM,

Good afternoon.

Looking at your issue,  you are using `AddScoped()` to add secrets manager dependency which registers the service with a scoped lifetime, the lifetime of a single request (refer https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection#service-lifetimes). Looks like the client objects are not yet disposed by garbage collector.  Perhaps implementing the Disposable pattern could help here, for example code below:
```C#
public class SecretsRepository : ISecretsRepository, IDisposable
{
    private readonly IAmazonSecretsManager secretsManager;
                
    public SecretsRepository(IAmazonSecretsManager secretsManager)
    {
        this.secretsManager = secretsManager;
    }
   
    public void Dispose()
    {
        this.secretsManager.Dispose();
        this.cache.Dispose();
     }
        
    ...
    <<Other logic>>
}        
```

Or try using the `AddSingleton()` to use singleton scope if it fits the need.

Hope this helps. Please let me know if this issue could be closed.

Thanks,
Ashish

**Comment by JuanZamudioGBM** [comment]
Hi @ashishdhingra 

Another objects use that repository so I can dispose it right away. But if it the normal behavior of AmazonSecretsManagerClient to create those objects feel free to close the issue.

Thanks for your time.
