### ISSUE TITLE
use AssumeRole(Async) without MFA everytime

### ISSUE THREAD

**Issue by dannystommen** [aws/aws-sdk-net#1844]
Hi,

When using the AWS Console, I only provide my MFA when I log-in to the console. From that point on, I can switch roles constantly and don't need to provide my MFA again.

Can this same behaviour be achieved using the SDK? 

Why do I want to achieve this: We have our product running in multiple AWS environments, and need to switch roles multiple times a day. Would be great if we could switch roles without providing the MFA token each and every time (similar to the Console).

**Comment by ashishdhingra** [comment]
Hi @dannystommen,

Good afternoon.

Please refer article https://adamhathcock.blog/2017/09/06/using-the-aws-sdk-to-login-with-mfa-and-assume-role/ which provides some guidance. Pasting the code below for future reference:
```C#
//needed info from target account
var targetRoleAccount = "<account id>";
var targetRoleName = "<role name>";
//needed info from main account about my user
var mainAccount = "<account id>";
var mainAccountUser = "<my user name>";
//my user creds
var mainAccountUserAccessToken = "<aws access token>";
var mainAccountUserSecretToken = "<aws secret token>";
//make some ARNs
var roleArn = $"arn:aws:iam::{targetRoleAccount}:role/{targetRoleName}";
var mfaArn = $"arn:aws:iam::{mainAccount}:mfa/{mainAccountUser}";
 
var basicCreds = new BasicAWSCredentials(mainAccountUserAccessToken, mainAccountUserSecretToken);
 
var stsClient = new AmazonSecurityTokenServiceClient(basicCreds);
var sessionResponse = await stsClient.GetSessionTokenAsync();
 
var sessionCreds = new SessionAWSCredentials(sessionResponse.Credentials.AccessKeyId,
    sessionResponse.Credentials.SecretAccessKey, sessionResponse.Credentials.SessionToken);
 
var options = new AssumeRoleAWSCredentialsOptions()
{
    MfaSerialNumber = mfaArn,
    MfaTokenCodeCallback = () =>
    {
        Console.WriteLine("Enter MFA");
        return Console.ReadLine();
    }
};
 
var assumeRoleCredentials = new AssumeRoleAWSCredentials(sessionCreds, roleArn, targetRoleName, options);
 
//time to work!
var client = new AmazonEC2Client(assumeRoleCredentials, RegionEndpoint.EUWest1);
```

I guess you would need to provide MFA, there is no way to bypass MFA step. Refer to [AmazonSecurityTokenServiceClient.AssumeRole (AssumeRoleRequest)](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/Index.html) for more details.

Thanks,
Ashish

**Comment by dannystommen** [comment]
Hi Ashish,

Thanks for explaining. We do have it working with passing the MFA, I was just hoping we didn't need to provide it each and every time, but only the first time (like the AWS Console). Sometimes we need to assume roles a couples of times within in sequence, and it's kind of annoying that I need to wait for the next MFA token before I can assume the next role (since MFA tokens are not allowed to be used twice).

**Comment by divekarvinit** [comment]
Hey @dannystommen, how did you get it to work in a Web API project?

**Comment by dannystommen** [comment]
@divekarvinit I did not get it work. But it was not in an Web API project, it was for a local desktop application.
