### ISSUE TITLE
AWSCredentials.GetCredentials() will hang indefinitely with a credential_process profile when cmd.exe is disabled

### ISSUE THREAD

**Issue by GoneWacko** [aws/aws-sdk-net#1845]
## Description
On Windows, when using an AWS credential profile that sources the credentials from an external process using the `credential_process` feature, the AWSCredentials.GetCredentials() call will hang indefinitely if `cmd.exe` has been disabled via a Group Policy for the current user.

On Windows, aws-sdk-net will run the `credential_process` process inside of a `cmd.exe` shell: https://github.com/aws/aws-sdk-net/blob/13bd83ed856609040c6482d25394a0d39339c6b0/sdk/src/Core/Amazon.Runtime/Credentials/ProcessAWSCredentials.cs#L59
But when `cmd.exe` has been disabled through a group policy, the `cmd.exe` process will start, show a message indicating that an administrator has disabled the command prompt, and then wait indefinitely on a "press any key to continue" prompt. Unfortunately, the AWS .NET SDK will wait indefinitely for the `cmd.exe` process to exit. `AWSCredentials.GetCredentials()` will essentially be deadlocked, waiting for `cmd.exe` to exit, which it never will.

## Reproduction Steps

1. On Windows, disable cmd.exe by running `gpedit.msc`, navigating to `User Administration\System` and setting the `Prevent access to the command prompt` policy to `Enabled`.
2. Run `cmd.exe` manually to verify that the command prompt shows a message about being disabled and waits for user input.
3. Configure `%USER_RROFILE%/.aws/config` with a profile called `my_test_profile` that uses a `credential_process` per the documentation here: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html
4. Run a .NET program that uses the configured profile in some way, e.g., create an S3 client and get an object. The program will hang indefinitely. Using a tool like ProcMon you can also clearly see that `cmd.exe` is running as a child process of your .NET program.

Simple reproduction code (.NET Framework 4.6.2):
```
using Amazon.Runtime;
using Amazon.Runtime.CredentialManagement;
using Amazon.S3;
using System;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var profileName = "my_test_profile";
            var region = Amazon.RegionEndpoint.GetBySystemName("us-east-1");
            var bucket = "some-bucket";
            var key = "some-key";

            var sharedFile = new SharedCredentialsFile();
            var profile_exists = sharedFile.TryGetProfile(profileName, out CredentialProfile profile);
            Console.WriteLine("Profile exists: " + profile_exists.ToString());
            var credentials_created = AWSCredentialsFactory.TryGetAWSCredentials(profile, sharedFile, out AWSCredentials credentials);
            Console.WriteLine("AWSCredentials created: " + credentials_created.ToString());
            if (credentials_created)
            {
                Console.WriteLine("Created AWSCredentials of type " + credentials.GetType().ToString());
                Console.WriteLine("Found access key ID: " + credentials.GetCredentials().AccessKey.ToString());
                var s3 = new AmazonS3Client(credentials, region);
                var response = s3.GetObject(bucket, key);
                Console.WriteLine("response: " + response.ToString());
            }
        }
    }
}
```

### Environment

* SDK Version: AWSSDK.Core 3.7.0.10 / AWSSDK.S3 3.7.0.10
* Package Version: AWSSDK.Core / AWSSDK.S3 3.7.0.10
* OS Info: Windows 10 Pro / Windows Server 2019 (Amazon AppStream 2.0)
* Build Environment: VIsual Studio Professional 2019
* Targeted .NET Platform:  .NET Framework 4.6.2

## Resolution
The best solution is probably to just invoke the `credential_process` directly rather than wrapping it inside of a `cmd.exe`.

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @GoneWacko,

Good afternoon.

Thanks for reporting the issue. Could you please check and share the default program for `.cmd` file type in your system?

Regards,
Ashish

**Comment by GoneWacko** [comment]
@ashishdhingra Hello,

It looks like the file type is associated with cmd.exe. The Windows Server 2019 "Choose default apps by file type' settings pane shows no actual application associated with the file type, but when running a .cmd file, I see the process tree is `conhost.exe` as a child of `cmd.exe`.

It's worth noting that, for unprivileged users, we also configured our Windows image to have a [software restriction policy](https://docs.microsoft.com/en-us/windows-server/identity/software-restriction-policies/software-restriction-policies) that prevents execution of .cmd files that are not in specific paths of the file system. But of course this is less of a concern; if the idea is to make the SDK generate a .cmd script, we can set up an exclusion in the restriction policy that so that it can still be executed.

And I don't think it matters, but for what it's worth: We're mostly running into this issue inside of an Amazon AppStream 2.0 session where we don't want end-users to start cmd.exe/powershell, to avoid abuse.

For now I think we can work around the problem by simply running the credential process ourselves, parsing the JSON output, and giving the credentials to the SDK 'manually'.

**Comment by ashishdhingra** [comment]
Research to see how this scenario is handled in other SDKs.
