### ISSUE TITLE
DynamoDBv2 DynamoDBContext.FromDocument - Inconsistent deserialization in .NET Framework and .NET Standard

### ISSUE THREAD

**Issue by pfinch-dub** [aws/aws-sdk-net#1848]
## Description

When using DynamoDBContext to deserialize to an object with FromDocument<T> or FromQueryAsync<T> it will populate private properties in .Net standard but ignore them in .Net Framwork 4.5.

## Reproduction Steps

If we take the following classes

```
    [DynamoDBTable("Animal")]
    public class Animal
    {
        [DynamoDBHashKey("pk")]
        public string pk { get; set; }
        [DynamoDBRangeKey("sk")]
        public string sk { get; set; }
        [DynamoDBProperty("tag")]
        protected string _tag { get; set; }

        public string Name { get; set; }
    }

    public class Dog: Animal
    {
        [DynamoDBProperty("tag")]
        private string _id;

        public string Breed { get; set; }
    }
```

And use DynamoDBContext to either context.FromQueryAsync<Animal>() or context.FromDocument<T>(doc)) it will populate all of the members above in .NET standard but only the public members in .NET Framework.

I personally prefer the .NET standard implemenation of populating all members (private/protected/public).

### Environment

* SDK Version: AWSSDK.DynamoDBv2 3.7.0.17 and AWSSDK.Core 3.7.0.17 and master branch on github
* OS Info: Windows 10
* Build Environment Visual Studio
* Targeted .NET Platform:  netcoreapp3.1 and .NET Framework 4.7.2

## Resolution

The issue is with the GetMembers() method in Amazon.Util.Internal.TypeFactory in the Core library.
The .NET Framework version does a simple
```
            public override MemberInfo[] GetMembers()
            {
                return this._type.GetMembers();
            }
```
while the .NET standard version has a custom implemenation of the above using a GetMembers_Helper() private method.

Changing the .NET Framwork version of GetMembers() to:
```
            public override MemberInfo[] GetMembers()
            {
                BindingFlags flags = BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public;

                return this._type.GetMembers(flags);
            }
```
Would give more consistent results but may introduce a breaking change for some applications. A cleaner way might be allow a user to override the members flags in the DynamoDBContextConfig and defaulting to the current method.

Let me know if you would like any more details or any input into a potential fix.
---

This is a :bug: bug-report

**Comment by ashovlin** [comment]
We realizing that we inadvertently fixed this in the 3.7.300 release of the SDK, when we moved away from our own `TypeFactory` implementation that was added for early .NET Standard versions.

I added tests to our `v4-development` branch in #3416 to guard this against regressions in the future, but you should be able to see this fixed in 3.7.300+. Let us know if you're still seeing issues.
