### ISSUE TITLE
SDK does not return accurate service endpoints

### ISSUE THREAD

**Issue by apatterson57390** [aws/aws-sdk-net#1849]
## Description

SDK does not return always accurate endpoints when using `IRegionEndpoint.GetEndpointForService()`, or any other method that uses `endpoints.json` as its source of truth. This is particularly true when attempting to get FIPS endpoint addresses for S3 or dualstack endpoints for a number of services.

I have been using this documentation as my source of truth for AWS Endpoints https://docs.aws.amazon.com/general/latest/gr/aws-service-information.html

## Reproduction Steps

Using the above AWS documentation as reference, attempt to generate a usable service endpoint by using the following code:

```
var regionEndpoint =  new RegionEndpointProviderV3();
var result = regionEndpoint.GetRegionEndpoint("us-west-1");
var serviceEndpoint =  result.GetEndpointForService("sqs", true);
Console.WriteLine(serviceEndpoint.Hostname);

PS C:\Users\austinpatterson\Documents\Repositories\awssdk-region-test> dotnet run
sqs.dualstack.us-west-1.amazonaws.com
```
```
var regionEndpoint =  new RegionEndpointProviderV3();
var result = regionEndpoint.GetRegionEndpoint("fips-us-west-2");
var serviceEndpoint =  result.GetEndpointForService("s3", false);
Console.WriteLine(serviceEndpoint.Hostname);

PS C:\Users\austinpatterson\Documents\Repositories\awssdk-region-test> dotnet run
s3.fips-us-west-2.amazonaws.com
```
Based on the above documentation, neither of these endpoints are valid.
### Logs

There are no logs to speak of. However, I did build the sdk with some additional console logs to better understand what was happening. By doing this, I was able to discover that the SDK doesn't return accurate endpoints because of the behavior seen within the following code https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/RegionEndpoint/RegionEndpointProviderV3.cs#L66-L102

Endpoint combinations not found within `endpoints.json` don't appear to be a reason to throw an error. Rather, the information is concatenated and returned to the user who is likely not wise to the fact that they may have just generated a entirely invalid endpoint.

### Environment

* SDK Version: 3.7.0.18
* Package Version: 3.7.0.18
* OS Info:  Microsoft Windows 10 Pro 10.0.19042
* Build Environment  VSCode/VisualStudio/Terminal
* Targeted .NET Platform:  4.8/5.0/Core

## Resolution
We believe this can be resolved by updating the `endpoints.json` file with the appropriate endpoints.
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @apatterson57390,

Good afternoon.

For .NET SDK, we recommend using `ServiceURL` to set the FIPS endpoint explicitly on the `AmazonS3Config` object. Currently, there is no support/information for FIPS endpoints in `endpoints.json`.

Thanks,
Ashish

**Comment by fv-ian** [comment]
I'm a bit surprised this is a valid answer to close this ticket.   


@ashishdhingra Why is there no support for this?   Is endpoints.json the direction forward for the SDK or is there no SDK pattern for managing endpoints effectively?

**Comment by ashishdhingra** [comment]
> I'm a bit surprised this is a valid answer to close this ticket.
> 
> @ashishdhingra Why is there no support for this? Is endpoints.json the direction forward for the SDK or is there no SDK pattern for managing endpoints effectively?

@fv-ian We are working towards better way to support FIPS endpoints. As of now, we cannot commit on the timeline though.
