### ISSUE TITLE
aws-tracelistener-sample.config created by installing Nuget TraceListener extensions has wrong namespace

### ISSUE THREAD

**Issue by mahoua** [aws/aws-sdk-net#185]
This file got created upon installing the AWS SDK .NET TraceListener extensions Nuget package : 

aws-tracelistener-sample.config : 

< configuration>

  < system.diagnostics>
    < sources>
      < source name="Amazon.S3">
        < listeners>
          < add name="s3" type="Amazon.Logging.DynamoDBTraceListener, AWS.TraceListener"
               AWSProfileName="AWS Default"
               AWSProfilesLocation=".aws/credentials"
               Table="Logs"
               Region="us-east-1"
           / >
        < /listeners>
      < /source>
    < /sources>
  < /system.diagnostics>
  
 < /configuration>

The issue is that the DynamoDBTraceListener class is not in the Amazon.Logging namespace, but in the Amazon.TraceListener namespace. 

Also, I don't remember where, but somewhere in the documentation I saw that same error in a sample config.

**Comment by PavelSafronov** [comment]
Thanks for reporting this. This will be fixed in the next SDK release.

**Comment by jimfl** [comment]
This was fixed in version 2.3.27 of the SDK
https://aws.amazon.com/releasenotes/.NET/6728787774361892
