### ISSUE TITLE
PinPoint PutEventsAsync timeout

### ISSUE THREAD

**Issue by hupo376787** [aws/aws-sdk-net#1852]
## Description

Set timeout when `PutEventAsync`, but not work.
When the network is very bad, the timeout may not work.

## Reproduction Steps

```
CancellationTokenSource cancellationTokenSource = new CancellationTokenSource(new TimeSpan(0, 0, 3));
var res = await pinpoint.PutEventsAsync(putEventsRequest, cancellationTokenSource.Token);
```

It seems no matter how long I set it, pinpoint will cancel it after about 250 seconds.

### Environment

* SDK Version: 3.7.1.4
* Package Version: 3.7.1.4
* OS Info: Windows 10 19042.928
* Build Environment: Visual Studio 2019, universal windows platform, .net core
* Targeted .NET Platform:  .net core 5.0

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @hupo376787,

Good afternoon.

Looking at high level, this doesn't appear to be an SDK issue. The CancellationToken and async features are provided by .NET runtime, and it should cancel the async call once the timeout elapses. Could you please share the complete sample code and Amazon Pinpoint settings to reproduce the issue?

Thanks,
Ashish

**Comment by hupo376787** [comment]
Hi, @ashishdhingra . If the network is good, the CancellationToken works. But for the sample I provided, If set network speed to very bad, like 0.1KB/s, it seems not to work until 200s.
 See repo: https://github.com/hupo376787/PinPointTimeout.git

The repo is uwp platform, you will install uwp sdk.

![image](https://user-images.githubusercontent.com/14960168/117913320-bf4a4c00-b313-11eb-8fe1-a32d101b3803.png)

**Comment by ashishdhingra** [comment]
Hi @hupo376787,

Good afternoon.

Based on discussion with developer and analysis, the AWS SDK is just passing down the `CancellationToken` to the HttpClient's Send method. Kindly note that CancellationToken timeout just signals that the cancellation is requested, but might not guarantee it's timely execution. The implementation is handled by the .NET framework and not sure if AWS SDK has control over it. Microsoft has done some work to improve cancellation and HTTP (old ticket): https://github.com/dotnet/corefx/pull/9446. In case there is a consistent reproduction, issue could be opened in Microsoft's repository for further analysis.

As a workaround, logic something like below could be implemented to get a better fidelity timeout (this needs to be tested):
```C#
var cts = new CancellationTokenSource(TimeSpan.FromSeconds(3));
await Task.WaitAny(
   Task.Run(async () => await Task.Delay(10, cts.Token)),
   pinpoint.PutEventsAsync(putEventsRequest, cts.Token));
```

Thanks,
Ashish
