### ISSUE TITLE
Reading credentials in recent SDK versions

### ISSUE THREAD

**Issue by asherber** [aws/aws-sdk-net#1853]
My org uses SSO credentials, which I know until fairly recently were not supported by the SDK. I've been doing `aws sso login`, then using [yawsso](https://github.com/victorskl/yawsso) to sync legacy v1 credentials, and setting the AWS_PROFILE environment variable, and apps with the SDK have been working just fine, reading the credentials with no additional code or configuration. 

I recently updated to the latest versions of the SDK assemblies, and it seems that they no longer read the v1 credentials; and even though it looks like support for SSO creds was added in v3.5.2 of AWSSDK.Core, they don't seem to be reading those credentials either. As a result, my SDK calls all fail with "Unable to get IAM security credentials from EC2 Instance Metadata Service.", which is the fallback error that occurs when no local credentials can be found.

I've read the docs [here](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/creds-assign.html), which say they're just for .NET Core, and also the ones [here](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-creds.html#creds-assign) for Framework. Interestingly, the docs for Framework no longer mention the AWS_PROFILE environment variable. 

I'm guessing this is user error, since I think if it were just broken I would have found more complaints about it. I'd appreciate some guidance about the appropriate way to find default credentials with the current SDK.

I'm working on Windows 10, testing using Linqpad. I've been able to reproduce this issue in both .NET Core 3.1 and Framework 4.7.2, using AWSSDK.SimpleSystemsManagement v3.7.3.2, which uses AWSSDK.Core v.3.7.0.21. I need to roll back to SSM v3.5.7.5 in order to get the old behavior.

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @asherber,

Good morning.

Thanks for posting guidance question. If you refer the code in [Amazon.Runtime.FallbackCredentialsFactory](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Credentials/FallbackCredentialsFactory.cs) class, the order in which the credentials are retrieved are same as what is specified in [Credential and profile resolution](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/creds-assign.html) in the latest developer guide, and the `AWS_PROFILE` environment variable is indeed supported as indicated by the generator `() => GetAWSCredentials(credentialProfileChain)`. The profile credentials are subsequently loaded by [GetAWSCredentialsInternal](https://github.com/aws/aws-sdk-net/blob/85af718a01f63e0a71cd6bacbdb0c07f54fbb737/sdk/src/Core/Amazon.Runtime/CredentialManagement/AWSCredentialsFactory.cs#L183). I'm assuming that the [yawsso](https://github.com/victorskl/yawsso) tool that you are using is updating the basic/session profile credentials. In case you have the test environment, to troubleshoot the issue, you may get the latest SDK source for `AWSSDK.Core` and use it to debug to find the exact point of failure (if possible).

Hope this helps.

Thanks,
Ashish

**Comment by asherber** [comment]
Okay, I'll take a look at debugging this. I was hoping there was something obvious that I was missing; it seems odd that the exact same code in the exact same environment works with a version of the SDK from 6 months ago but not with current versions.

**Comment by asherber** [comment]
I think I see what's going on. Starting with a clean .aws folder, I did `aws configure sso` to set up my SSO profile. This gave me an entry in .aws/config:

```ini
[profile foo]
sso_start_url = ...
sso_region = us-east-1
sso_account_id = 1234
sso_role_name = PowerUserAccess
region = us-east-1
```

Next I ran `yawsso`, which fetched session credentials and gave me an entry in .aws/credentials:

```ini
[foo]
region = us-east-1
aws_access_key_id = NKJSDNF
aws_secret_access_key  = sdfmsnfl
aws_session_token = ...
aws_security_token = ...
aws_session_expiration = 2021-05-15T23:45:29+0000
```

When I do some SDK operation that requires login, [`FallbackCredentialsFactory`](https://github.com/aws/aws-sdk-net/blob/8bb0bc38d545fa0bca664d83ec82372d223455d9/sdk/src/Core/Amazon.Runtime/Credentials/FallbackCredentialsFactory.cs#L68) calls [`GetAwsCredentials()`](https://github.com/aws/aws-sdk-net/blob/8bb0bc38d545fa0bca664d83ec82372d223455d9/sdk/src/Core/Amazon.Runtime/CredentialManagement/AWSCredentialsFactory.cs#L143) in `AWSCredentialsFactory`. At this point, the `CredentialProfileOptions` parameter contains entries for the profile both from the config file and from the credentials file.

When `GetAwsCredentials()` calls `CredentialProfileTypeDetector.DetectProfileType()`, I think that function is too eager to determine that the profile is an SSO profile. All it does is [look for](https://github.com/aws/aws-sdk-net/blob/8bb0bc38d545fa0bca664d83ec82372d223455d9/sdk/src/Core/Amazon.Runtime/CredentialManagement/Internal/CredentialProfileTypeDetector.cs#L277) the presence in the `CredentialProfileOptions` parameter of any of the SSO properties and then immediately decides that it's an SSO profile. And then `GetAwsCredentials()` throws an exception because it can't use an SSO profile here.

Now, `foo` definitely is an SSO profile, but it also has valid session credentials attached to it and would match `CredentialProfileType.Session` if the SSO check didn't short-circuit the process. I think this code should be more forgiving, since the top-level code is really just interested in whether we have a profile with session credentials, not whether that profile also happens to be an SSO profile.

**Comment by asherber** [comment]
I also tried another approach, deleting the section from .aws/credentials and adding a `credential_process` to the profile in .aws/config. But the `CredentialProfileTypeDetector` still short circuits when it sees the SSO properties, so the credential process never gets triggered.

**Comment by ashishdhingra** [comment]
Hi @asherber,

Good morning.

Thanks for your reply. The issue noticed by you appears to be related to https://github.com/aws/aws-sdk-net/issues/1821. Could you please check if you are able to use the workaround suggested in the issue description. Or may be configure `yawsso` to set the profile with a different profile name (mat be `foo_sso`) and use that profile for credentials.

I will upgrade this issue to `bug`.

Thanks,
Ashish

**Comment by asherber** [comment]
Hi @ashishdhingra,

It's debatable whether or not these are truly related. #1821 appears to block an SSO profile from using the SSO process to obtain session creds. In my case, the SSO profile already has valid session creds, but the SDK sees only that it's SSO and refuses to use the existing creds.

I implemented a workaround basically as you describe -- after `yawsso` obtains session creds for a profile, I copy those creds to a non-SSO profile with a different name.

**Comment by boyersnet** [comment]
@asherber, the SDK was updated yesterday based on #1821 and I was able to get SSO working with CLI login.  I've created [AWSSSO.S3Buckets](https://github.com/boyersnet/AWSSSO.S3Buckets) as a demonstration project.

**Comment by ashishdhingra** [comment]
Hi @asherber,

Good afternoon.

Please review the comment from @boyersnet and see if your issue is resolved. You shouldn't have to use `yawsso`.

Thanks,
Ashish

**Comment by asherber** [comment]
Still not working for me. As I indicated, I think #1821 and the PR to address it are a different issue, further downstream from what I'm describing here.

**Comment by ashishdhingra** [comment]
Need to verify SSO fix using latest version of SDK. Customer shouldn't have to use `yawsso`.

**Comment by ashishdhingra** [comment]
Hi @asherber,

Good afternoon.

I had tried the demonstration project [AWSSSO.S3Buckets](https://github.com/boyersnet/AWSSSO.S3Buckets) shared by @boyersnet mentioned in the comment https://github.com/aws/aws-sdk-net/issues/1853#issuecomment-844100607 and it works fine using the latest version of SDK. Per design of SSO change, the dependency to `AWSSDK.SSO` and `AWSSDK.SSOOIDC` packages must be included in the project. Hence, you should not have to use `yawsso` and should remove the other temporary credentials added by `yawsso`. You would need to use `aws configure sso` (as mentioned in [Configuring the AWS CLI to use AWS Single Sign-On](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html)) to configure SSO credentials and then use `aws sso login --profile my-dev-profile`.

Please let me know if this works for you.

Thanks,
Ashish

**Comment by heitorlessa** [comment]
I'm having a similar issue, where the SDK doesn't seem able to [read credentials](https://github.com/aws/aws-sdk-net/blob/cb17835d8cc9cca7e7d948693e11913662290ebe/sdk/src/Core/Amazon.Runtime/Credentials/FallbackCredentialsFactory.cs#L64) from a non-default Profile that uses SSO - `AWS_PROFILE` is set correctly, if I switch to a non-SSO profile it works fine.

I'd appreciate any assistance, since I'm new to C# and this is proving rather challenging after following a few docs. 

I'm using `CredentialProfileStoreChain` as a workaround, though there must be a better way:

```c#
using System;
using System.Threading.Tasks;
using Amazon;
using Amazon.Extensions.NETCore.Setup;
using Amazon.Runtime;
using Amazon.Runtime.CredentialManagement;
using Amazon.S3;
using Amazon.S3.Model;

namespace MyApp
{
	class Program
	{

		static void Main(string[] args)
		{
			var buckets = FetchBuckets();
			foreach (var bucket in buckets.Result.Buckets)
			{
				Console.WriteLine(bucket.BucketName);
			}
		}

		static async Task<ListBucketsResponse> FetchBuckets()
		{
		    // Ideally it would be as simple as just like in Python or Java
		    // AmazonS3Client s3 = new AmazonS3Client();
			var chain = new CredentialProfileStoreChain();
			AWSCredentials awsCredentials;

            // expects a profile string
			var profileName = Environment.GetEnvironmentVariable("AWS_PROFILE") ?? "default";
            chain.TryGetAWSCredentials(profileName, out awsCredentials);

			AmazonS3Client s3 = new AmazonS3Client(awsCredentials, RegionEndpoint.EUWest1);

			return await s3.ListBucketsAsync();
		}
	}
}

```

**Comment by ashishdhingra** [comment]
> ```cs
> var buckets = FetchBuckets();
> 			foreach (var bucket in buckets.Result.Buckets)
> 			{
> 				Console.WriteLine(bucket.BucketName);
> 			}
> ```

Hi @heitorlessa,

Thanks for sharing the code snippet for using SSO credentials. Based on my analysis, the logic for getting credentials based on environment variable `AWS_PROFILE` uses the flow in https://github.com/aws/aws-sdk-net/blob/7bed6856e8818181087c7501d93391b04380599e/sdk/src/Core/Amazon.Runtime/CredentialManagement/AWSCredentialsFactory.cs#L144, with `nonCallbackOnly` as `false`. SSO credentials requires callback, hence retrieving SSO credentials via `AWS_PROFILE` environment variable is not supported. Your logic to retrieve SSO credentials looks good. Hope this explains the design.

Thanks,
Ashish

**Comment by asherber** [comment]
@ashishdhingra In my case, I shouldn't need to include the `SSO` and `SSOOIDC` packages. And let's forget about `yawsso` for now.

One way or another, I have a profile which has valid session credentials, and which also happens to be an SSO profile. As I explained [above](https://github.com/aws/aws-sdk-net/issues/1853#issuecomment-841648967), older versions of the SDK used to have no problem using the session credentials to log in (because they didn't know anything about SSO), but newer versions _only_ see the fact that it's an SSO profile -- they ignore the valid session credentials. To me, this is breaking behavior: Code which used to work fine in a given environment does not work after updating SDK libraries. 

If a profile has valid (i.e., non-expired) session credentials, they should be used for login, just like they used to be. The fact that the profile is SSO, and that SSO needs to be used in order to refresh the session credentials, is only relevant if the session credentials are invalid.

**Comment by heitorlessa** [comment]
> > ```cs
> > var buckets = FetchBuckets();
> > 			foreach (var bucket in buckets.Result.Buckets)
> > 			{
> > 				Console.WriteLine(bucket.BucketName);
> > 			}
> > ```
> 
> Hi @heitorlessa,
> 
> Thanks for sharing the code snippet for using SSO credentials. Based on my analysis, the logic for getting credentials based on environment variable `AWS_PROFILE` uses the flow in
> 
> https://github.com/aws/aws-sdk-net/blob/7bed6856e8818181087c7501d93391b04380599e/sdk/src/Core/Amazon.Runtime/CredentialManagement/AWSCredentialsFactory.cs#L144
> , with `nonCallbackOnly` as `false`. SSO credentials requires callback, hence retrieving SSO credentials via `AWS_PROFILE` environment variable is not supported. Your logic to retrieve SSO credentials looks good. Hope this explains the design.
> 
> Thanks,
> Ashish

Thanks a lot for explaining it -- Question: Is there a shorter or more elegant way of dealing with this like we do in other SDKs?

For example, I've tried to use this along with setting AWS_PROFILE env var to a SSO profile but failed to resolve the credentials. I'd guess it's the same that @asherber is finding.

```c#
var s3 = new AmazonS3Client(RegionEndpoint.EUWest1);
```

As in:

```c#
using System;
using System.Threading.Tasks;
using Amazon;
using Amazon.S3;
using Amazon.S3.Model;

namespace MyApp
{
	class Program
	{
		static void Main(string[] args)
		{
			var buckets = FetchBuckets();
			foreach (var bucket in buckets.Result.Buckets)
			{
				Console.WriteLine(bucket.BucketName);
			}
		}

		static async Task<ListBucketsResponse> FetchBuckets()
		{
			var s3 = new AmazonS3Client(RegionEndpoint.EUWest1);

			return await s3.ListBucketsAsync();
		}
	}
}

```

**Comment by supergibbs** [comment]
FYI for those that are using [yawsso](https://github.com/victorskl/yawsso). I added a [feature to rename the profile](https://github.com/victorskl/yawsso#rename-profile-on-sync) on sync so you can have `rolesso` in your config sync'd to `role` in credentials file. It helps this scenario but will ideally still be fixed in a future SDK release. Thanks to @victorskl for the quick merge and release!

**Comment by ashishdhingra** [comment]
Similar issue #1900 reported.

As mentioned in https://github.com/aws/aws-sdk-net/issues/1853#issuecomment-863641331, default credential resolution fetches credentials which require no callback, for SSO this fails at https://github.com/aws/aws-sdk-net/blob/f33050e58133959457b66b95481257e4f17e67ce/sdk/src/Core/Amazon.Runtime/CredentialManagement/AWSCredentialsFactory.cs#L158. The credential resolution ultimately fails at last EC2 instance credential generator (https://github.com/aws/aws-sdk-net/blob/f33050e58133959457b66b95481257e4f17e67ce/sdk/src/Core/Amazon.Runtime/Credentials/FallbackCredentialsFactory.cs#L58).

**Comment by ashishdhingra** [comment]
This has been fixed in the latest version of SDK. Closing the issue.
