### ISSUE TITLE
AmazonResourceGroupsTaggingAPIClient.GetResourcesAsync does not adhere to CLI spec

### ISSUE THREAD

**Issue by DizzyDeveloper** [aws/aws-sdk-net#1854]
## Description

Attempting to perform a GetResourcesAsync without specify TagFilters fails. However, according to the spec (below) and being able to execute the corresponding operation via CLI successfully, not providing TagFilters should not throw exceptions.

From [Spec](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/ResourceGroupsTaggingAPI/TGetResourcesRequest.html):
"[sic] If you don't specify a TagFilter, the response includes all resources that are currently tagged or ever had a tag. Resources that currently don't have tags are shown with an empty tag set, like this: "Tags": []."

Providing a null or empty list to TagFilters you ends up with validation errors.

Note: the follow call works as expected in the CLI.
`aws resourcegroupstaggingapi get-resources --region ap-southeast-2 --resource-arn-list <some-arn>`

## Reproduction Steps

```c#
           var request= new GetResourcesRequest
            {
                TagFilters = new List<TagFilter>(), // or null
                ResourceARNList = new List<string> { "<some-arn>" }
            };

            var response = await taggingClient.GetResourcesAsync(request);
```

### Logs
`Amazon.ResourceGroupsTaggingAPI.AmazonResourceGroupsTaggingAPIException with message "1 validation error detected: Value null at 'tagKeys' failed to satisfy constraint: Member must not be null"`

### Environment

AWSSDK.ResourceGroupsTaggingAPI
* SDK Version: 3.7.0.21
* Package Version: 3.7.0.21
* OS Info: Windows 10
* Build Environment Visual Studio
* Targeted .NET Platform:  netcore3.1 or netstandard2.1

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @DizzyDeveloper,

Good afternoon.

Somehow I'm unable to reproduce the issue using the `AWSSDK.ResourceGroupsTaggingAPI` version `3.7.0.23`. I tried with both empty list or null for `TagFilter` list. It doesn't throw any exception. Not sure how you are getting the error.

Thanks,
Ashish

**Comment by DizzyDeveloper** [comment]
Hi @ashishdhingra,

Well that is a bit awkward...I will have to have another look myself then. Mayhap I missed something on myside. 
Give me some time I will get back to you :) 

Thanks,
DizzyDeveloper
