### ISSUE TITLE
Need IBatchGet<T> interface for testing

### ISSUE THREAD

**Issue by SARAVANA1501** [aws/aws-sdk-net#1857]
I would like to have following mocking, Since `BatchGet<T>` is concrete class, we are unable to mock and test the functionality.
```
var dynamoDbContext = new Mock<IDynamoDBContext>();
            dynamoDbContext.Setup(t => t.CreateBatchGet<TestModel>(It.IsAny<DynamoDBOperationConfig>()))
                .Returns(new Mock<BatchGet<TestModel>>().Object);
            var service = new TestService(dynamoDbContext.Object);
```

**Comment by SARAVANA1501** [comment]
@ashishdhingra  any update on this?

**Comment by ashishdhingra** [comment]
Hi @SARAVANA1501,

Good afternoon.

[BatchGet<T>](https://github.com/aws/aws-sdk-net/blob/57611dffdfdb0ce86af1f7f4fa76969e2742034e/sdk/src/Services/DynamoDBv2/Custom/DataModel/BatchGet.cs#L108) inherits from the abstract [BatchGet](https://github.com/aws/aws-sdk-net/blob/57611dffdfdb0ce86af1f7f4fa76969e2742034e/sdk/src/Services/DynamoDBv2/Custom/DataModel/BatchGet.cs#L33) class. So you should be able to mock `BatchGet`. Kindly refer article [How to Unit Test an Abstract Class](https://enterprisecraftsmanship.com/posts/how-to-unit-test-an-abstract-class/) for details. Hope this helps.

Thanks,
Ashish

**Comment by Kralizek** [comment]
@ashishdhingra I wonder if your comment is really relevant. Because the `IDynamoDBContext` returns `BatchGet<T>` so if we were to use create a mock from `BatchGet`, it would be a sibling class of `BatchGet<T>` making it not usable for what @SARAVANA1501 is trying to achieve.

**Comment by SARAVANA1501** [comment]
Commenting to keeps it open

**Comment by SARAVANA1501** [comment]
@ashishdhingra  I would like to contribute on this

**Comment by 96malhar** [comment]
Hello, we have been working on the V4 of the AWS SDK for .NET. We have added the ability to mock various DynamoDB operations by adding interfaces in both the Data Model mode and Document Model mode in DynamoDB. 

Refer to this PR - https://github.com/aws/aws-sdk-net/pull/3450

This feature is available in the AWSSDK.DynamoDBv2 Version [4.0.0-preview.2](https://www.nuget.org/packages/AWSSDK.DynamoDBv2/4.0.0-preview.2)
