### ISSUE TITLE
AmazonAPIGateway.GetBasePathMappingAsync response not mapped to fields

### ISSUE THREAD

**Issue by Osypchuk** [aws/aws-sdk-net#1861]
## Description
Response of AmazonAPIGateway.GetBasePathMappingAsync method has all fields set to null.

## Reproduction Steps
Provided you have API gateway mapped to basepath following response returns all empty:
```
var API = new AmazonAPIGatewayClient();
var apiMapping = await API.GetBasePathMappingAsync(new GetBasePathMappingRequest()
                { DomainName = "valid.example.com", BasePath = string.Empty });
```
All fields of GetBasePathMappingResponse are null except ContentLength, which is 80 for me (probably depends on Stage and Domain name; domain in code above altered).
In case of invalid domain:
```
var apiMapping = await API.GetBasePathMappingAsync(new GetBasePathMappingRequest()
                { DomainName = "invalid.example.com", BasePath = string.Empty });
```
Expected result: Not found exception.
Actual result: All fields of GetBasePathMappingResponse are null except ContentLength, which is set to 12.
            
### Logs
```
AmazonAPIGatewayClient 1|2021-05-24T23:31:25.623Z|DEBUG|Received response (truncated to 1024 bytes): [{"item":[{"basePath":"(none)","restApiId":"x2y2ae142c","stage":"EMDev_stage"}]}
```

Documentation declares a slightly different model (*without "item", not array but single element*):
https://docs.aws.amazon.com/apigateway/api-reference/resource/base-path-mapping/ 
C# generated class matches documentation but doesn't match actual response:
https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/APIGateway/Generated/Model/GetBasePathMappingResponse.cs 

### Environment
* SDK Version: netcoreapp3.1
* Package Version: 3.7.0.26
* OS Info:  Windows 10 
* Build Environment: dotnet run
* Targeted .NET Platform:  

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

It looks like API was changed on server-side without updating API declaration used for documentation and client generation.
---

This is a :bug: bug-report

**Comment by Osypchuk** [comment]
CLI is also affected:
```
$ aws apigateway get-base-path-mapping --domain-name  valid.domain.net  --base-path ""

$
```

**Comment by boblodgett** [comment]
I have setup a test application using the environment and versions you specified.
For the invalid case I am getting the following exception: "NotFoundException: Invalid domain name identifier specified"

For the valid case, it will require more setup to verify. I would like to figure out why the exception isn't showing up for the invalid case first to ensure you are not getting an unexpected exception for the valid case as well.

Is the example code the actual code you are using or a mocked up example? Do you have anything in your code that could be hiding the exception?

**Comment by Osypchuk** [comment]
@boblodgett domain name is mocked - just an example (I believe none is allowed to query domain names from my account anyway).

You should add some domain in ec2 console first: https://[region].console.aws.amazon.com/apigateway/main/publish/domain-names 
In order to create a domain entity, you should have a matching SSL certificate which can be obtained only when you validate domain ownership.

Provided you have access to API source code compare response model for 
https://docs.aws.amazon.com/apigateway/api-reference/resource/base-path-mapping/
and 
https://docs.aws.amazon.com/apigateway/api-reference/resource/base-path-mappings/

I believe in code result type is the same but in the service definition (are you using coral service?) they are different. The invalid model leads to errors in generated documentation and client code.
