### ISSUE TITLE
AmazonCloudFrontCookieSigner throws exception on specific culture

### ISSUE THREAD

**Issue by carlozamagni** [aws/aws-sdk-net#1862]
## Description
I'm using AmazonCloudFrontCookieSigner inside an aspnet core web api and, whenever the current thread culture is set to th-TH (Thailand), the method `Amazon.CloudFront.AmazonCloudFrontCookieSigner.GetCookiesForCustomPolicy(String resourceUrlOrPath, TextReader privateKey, String keyPairId, DateTime expiresOn, DateTime activeFrom, String ipRange)` throws an exception. 

## Reproduction Steps
The issue only seems to happen when the culture is set to th-TH and  when the process is run on AWS EC2 instances running AmazonLinux. Everything works fine on OSX and Windows10.

### Logs
`{
  "Field": "UnhandledException",
  "Type": "System",
  "Details": "[Invalid RSA Private Key] - [   at Amazon.CloudFront.AmazonCloudFrontUrlSigner.ConvertPEMToRSAParameters(TextReader privateKeyReader)\n   at Amazon.CloudFront.AmazonCloudFrontCookieSigner.GetCookiesForCustomPolicy(String resourceUrlOrPath, TextReader privateKey, String keyPairId, DateTime expiresOn, DateTime activeFrom, String ipRange)",
  "ErrorMessage": "Invalid RSA Private Key",
  "Message": "Invalid RSA Private Key"
},
{
  "_typeTag": "ResponseError",
  "Field": "UnhandledException - InnerException",
  "Type": "System",
  "Details": "   at ThirdParty.BouncyCastle.OpenSsl.PemReader.ReadPrivatekey()\n   at Amazon.CloudFront.AmazonCloudFrontUrlSigner.ConvertPEMToRSAParameters(TextReader privateKeyReader)",
  "ErrorMessage": "Object reference not set to an instance of an object.",
  "Message": "Object reference not set to an instance of an object."
}`

### Environment
* SDK Version: 3
* Package Version: 3.7.1.10 and below
* OS Info: AmazonLinux
* Targeted .NET Platform:  netcore 3.1/ net5

## Resolution
I only managed to circumvent the issue by switching the current thread culture to a default (en-GB) before calling the aws sdk and restoring to the previous culture after the signing is completed.

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Need to check if culture `th-TH` is installed on Amazon Linux and see if installing it resolves the issue.

**Comment by ashishdhingra** [comment]
Created the new Amazon Linux EC2 instance and used the following program to check for installed cultures (published using `dotnet publish -o dist/ -r rhel-x64`):
```C#
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;

namespace LocaleTest
{
    class Program
    {
        public static IEnumerable<CultureInfo> AllCultureInfo { get; } =
                CultureInfo.GetCultures(CultureTypes.SpecificCultures)
                .ToList();

        static void Main(string[] args)
        {
            foreach (var cultureInfo in AllCultureInfo)
                Console.WriteLine(cultureInfo.Name);
        }
    }
}
```
It listed `th-TH` as one of the installed cultures.
