### ISSUE TITLE
S3 Hash verification

### ISSUE THREAD

**Issue by koderi-dp** [aws/aws-sdk-net#1863]
Hi,

is there a example, documentation how to create hash on local file as the one in etag of s3 object which was uploaded using multipart upload process, want to generate same hash of local file as the generated etag on s3 to verify if the files are same.

did find on net lot of example that are reverse engineering of s3 hash but none of them work.

like https://teppen.io/2018/06/23/aws_s3_etags/

Thanks

**Comment by ashishdhingra** [comment]
Hi @koderi-dp,

Good morning.

Thanks for posting guidance question. ETag is generated on the server and may not be reversed engineered. Is your requirement only to generate some kind of checksum so that you could verify that the uploaded S3 object is same?  `AWSSDK.S3 3.7.0.31` introduce flag `CalculateContentMD5Header` (refer https://github.com/aws/aws-sdk-net/commit/c08f5af7d67738944af1350cd5ddd786e353bb86) to automatically calculate MD5 while uploading S3 object via simple or multipart upload. This is particularly useful with TransferUtility and S3 bucket having Object Lock (and governance) enabled.

Hope this helps.

Thanks,
Ashish

**Comment by koderi-dp** [comment]
Hi,

thanks for the quick reply, i have looked at that flag and source code, from what i see it will generate md5 hash before upload and put it into request header, and md5 used is standard one from net System.Security.Cryptography. HashAlgorithm, when that hash is persisted into request header, is the file when it is uploaded validated by server using same md5 algorithm?
Also is it possible to retrieve that md5 hash when downloading file back to local storage?

problem is that we are using tree hashing algorithm https://en.wikipedia.org/wiki/Merkle_tree
For local files because its faster then standard md5, not sure if we can provide our none standard hash to request header?

**Comment by ashishdhingra** [comment]
> Hi,
> 
> thanks for the quick reply, i have looked at that flag and source code, from what i see it will generate md5 hash before upload and put it into request header, and md5 used is standard one from net System.Security.Cryptography. HashAlgorithm, when that hash is persisted into request header, is the file when it is uploaded validated by server using same md5 algorithm?
> Also is it possible to retrieve that md5 hash when downloading file back to local storage?
> 
> problem is that we are using tree hashing algorithm https://en.wikipedia.org/wiki/Merkle_tree
> For local files because its faster then standard md5, not sure if we can provide our none standard hash to request header?

@koderi-dp Hope this helps:
- MD5 is a requirement when Object Lock is enabled for the bucket along with governance retention period enabled. If MD5 is not specified, then S3 PutObject request fails with exception that MD5 needs to be specified. The new flag introduced would enable automatic calculation of MD5. 
- As mentioned in my previous reply, the automatic MD5 calculation is particularly useful when using TransferUtility where it automatically takes care of simple or multipart upload depending on the configuration values.
- You can choose to calculate your own MD5 and specify it as part of PutObjectRequest or UploadPartRequest. For multipart upload, you need to calculate and set it for each part as it uploads.
- MD5 is validated by the server. For Object Lock enabled, the service returns an error if MD5 is not specified.
- MD5 is for consistency purposes and for verifying the integrity of data. There is nothing like retrieving the MD5 when downloading file back to local storage. As a part of your design, you might want to store MD5 for each uploaded file to some persistent store and as the file is downloaded, you can recalculate the MD5 and compare it with the stored MD5.

Hope this provides necessary guidance. Let me know if we could close this issue.

Thanks,
Ashish

**Comment by augustoproiete** [comment]
@ashishdhingra Are there any plans for AWS S3 to store/expose the calculated server-side content MD5 hash in the object metadata properties, so that it can be easily queried via `GetObjectMetadata`?

I understand the use-case for client-side content MD5 provided at the time of upload and integrity checks, but it would be extremely useful to have access to the server-side content MD5 hash that is already calculated by AWS S3 at the time of upload.

**Comment by ashishdhingra** [comment]
> @ashishdhingra Are there any plans for AWS S3 to store/expose the calculated server-side content MD5 hash in the object metadata properties, so that it can be easily queried via `GetObjectMetadata`?
> 
> I understand the use-case for client-side content MD5 provided at the time of upload and integrity checks, but it would be extremely useful to have access to the server-side content MD5 hash that is already calculated by AWS S3 at the time of upload.

@augustoproiete `ETag` is specified as one of the response headers in [Common Response Headers](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html), where ETag may or may not be an MD5 digest of the object data. Are you referring to ETag response header? I think submitting a feedback request in the service API reference could also be helpful.

Thanks,
Ashish

**Comment by augustoproiete** [comment]
@ashishdhingra I'm not referring to `ETag` exactly because it's not guaranteed to be an MD5 digest of the contents as you stated.

What I'm looking for is a way to retrieve an MD5 digest of the contents without having to download the file to calculate it.

Given that AWS S3 already calculates the MD5 hash of the file upon upload, it would seem reasonable to expect this information to be exposed as part of the metadata of the file, the same way that `ContentLength` is.

> submitting a feedback request in the service API reference could also be helpful

I'm not sure I know where the "the service API reference" repo is located. Please, let me know if I should create a new issue in this repo or somewhere else.

**Comment by koderi-dp** [comment]
> * MD5 is a requirement when Object Lock is enabled for the bucket along with governance retention period enabled

Thanks, very helpful informations, only part that i don't understand is 

MD5 is a requirement when Object Lock is enabled for the bucket along with governance retention period enabled

in case that object lock is not enable and i provide md5 hash in request header, will the server do the check or it will ignore it because object lock is not enabled on bucket?

**Comment by koderi-dp** [comment]
> @ashishdhingra I'm not referring to `ETag` exactly because it's not guaranteed to be an MD5 digest of the contents as you stated.
> 
> What I'm looking for is a way to retrieve an MD5 digest of the contents without having to download the file to calculate it.
> 
> Given that AWS S3 already calculates the MD5 hash of the file upon upload, it would seem reasonable to expect this information to be exposed as part of the metadata of the file, the same way that `ContentLength` is.
> 
> > submitting a feedback request in the service API reference could also be helpful
> 
> I'm not sure I know where the "the service API reference" repo is located. Please, let me know if I should create a new issue in this repo or somewhere else.

This would be very useful to have that information, i noticed in my testing that i always get md5 context header null when getting object metadata, not sure if it is connected to my question about lock enabled, my workaround was adding custom metadata when uploading file in which metadata contains md5 hash generated before upload, so i can compare it when downloading file back (so no need for external storage)

**Comment by ashishdhingra** [comment]
> I'm not sure I know where the "the service API reference" repo is located. Please, let me know if I should create a new issue in this repo or somewhere else.

@augustoproiete S3 Service API documentation is located at https://docs.aws.amazon.com/AmazonS3/latest/API/Welcome.html.

**Comment by augustoproiete** [comment]
Thanks @ashishdhingra. I only see ways of providing feedback to the documentation itself, not feature requests.

![image](https://user-images.githubusercontent.com/177608/120695507-dc40ed80-c481-11eb-9c11-69093a4c46dc.png)

Could you point me to the right place to submit a request for storing a server-side MD5 hash?

**Comment by ashishdhingra** [comment]
> Thanks @ashishdhingra. I only see ways of providing feedback to the documentation itself, not feature requests.
> 
> Could you point me to the right place to submit a request for storing a server-side MD5 hash?

@augustoproiete Could you please open a new issue with `feature-request` label linking this issue? I will close this `guidance` issue and as a part of new feature request, open a new issue internally with the service team.

**Comment by augustoproiete** [comment]
Thanks @ashishdhingra. Created issue [#1868 Expose MD5 hash of objects in AWS S3 via APIs](https://github.com/aws/aws-sdk-net/issues/1868).
