### ISSUE TITLE
Dependance of ListBucket on various commands generate a high amount bill. It´s really necessary?

### ISSUE THREAD

**Issue by reinaldocoelho** [aws/aws-sdk-net#1867]
## Why ListBucket is called with other requests?

Working with S3 functions like GetObjectAsync, ListObjectAsync and others, the bill present an ammount of ListBucket uneeded requests (Ok, the Doc inform it as permission needed to the command).

The ListBucket requests is about 50% of total amount of requests in month, and the value on bill is very high if the requests are unnecessary.

Is really necessary to call all this additional requests?
Can we load the bucket one time only and pass then as parameter to avoid the excessive request quantity?

Examples of requests may be found on run tests with this project:
https://github.com/EnkiGroup/enki.storage

### Environment
* SDK Version: AWSSDK.S3, version 3.5.8.2
* Package Version: 3.5.8.2
* OS Info: Windows 10 | Ubuntu | AmazonLinux
* Build Environment: Visual Studio 19, VSCode + Terminal `dotnet` , dotnet 5
* Targeted .NET Platform:  dotnet 5

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @reinaldocoelho,

Good afternoon.

Could you please point me to location where it specifies that `ListBucket` is invoked before calling other S3 operation, e.g., `GetObjectAsync`.

Here is the code for `GetObjectAsync()` https://github.com/aws/aws-sdk-net/blob/4437c0e06b7e20ac85477b17d5fd3de55ed8e5a1/sdk/src/Services/S3/Generated/_netstandard/AmazonS3Client.cs#L5527.
It invokes [GetObject](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html) S3 service API operation. Same could be inferred for `ListObjectsAsync` method.

Kindly advise.

Thanks,
Ashish

**Comment by reinaldocoelho** [comment]
Hi Ashish!

Thanks for the answer. I don´t have an specific operation that runs it, my questions is based on the documentation that inform the s3:ListBucket as a dependence and I inferred that runs always because the S3 bill with a lot of ListBucket operations.

I don´t have ListBucket operation on my code, and my question rise from this think.

You tell that some operations runs ListBucket for validations, when this occours?
At first I have registered in database the Bucket and Path to object, then I think the ListBucket don´t be must running.

I wrong understanding something?
Can I do something to avoid the ListBucket execution?

My AWS S3 bill today has 50% operations of ListBucket.

**Comment by ashishdhingra** [comment]
> s3:ListBucket as a dependence

@reinaldocoelho Could you please point me to documentation that mentions dependence on s3:ListBucket for some operations? This would be helpful to investigate it further.

**Comment by reinaldocoelho** [comment]
For example in this image to validate if Object Exists:
![ListBucketRequired](https://user-images.githubusercontent.com/889634/120850025-45d9fe00-c54d-11eb-8c73-51d766947e64.png)

**Comment by ashishdhingra** [comment]
> For example in this image to validate if Object Exists:
> ![ListBucketRequired](https://user-images.githubusercontent.com/889634/120850025-45d9fe00-c54d-11eb-8c73-51d766947e64.png)

@reinaldocoelho The code for [AmazonS3Client. ListObjectsV2Async()](https://github.com/aws/aws-sdk-net/blob/7a26cad0135f82495cd0ad67c3dbb982912ec719/sdk/src/Services/S3/Generated/_netstandard/AmazonS3Client.cs#L8415) in AWS SDK for .NET does not execute `s3:ListBuckets`. The documentation for AWS SDK for .NET is coming from service API documentation at https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html. It talks about having `s3:ListBucket` permission for listing objects. This is something controlled by the S3 service. The best course of action is to submit the feedback by using `Provide Feedback` link at the bottom of the API documentation page, requesting them to elaborate on why `s3:ListBucket` permission is needed. I guess if user doesn't have this permission, they cannot list objects as well and hence this permission is needed to list objects. Hope this helps.

**Comment by reinaldocoelho** [comment]
Thanks @ashishdhingra, I thought the document was from the library!
Sorry for wasting your time and thanks again for the help :-)
