### ISSUE TITLE
Scan Range not working with .Net SDK

### ISSUE THREAD

**Issue by ravi27may** [aws/aws-sdk-net#1869]
## Description
Currently with .Net AWS SDK S3 Select Scan Range is not working. 

## Reproduction Steps
In the code https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/S3/Custom/Model/Internal/MarshallTransformations/SelectObjectContentRequestMarshaller.cs
Line: 139 ScanRange is embedded inside RequestProgress element. So ScanRange is never consider in the request
![image](https://user-images.githubusercontent.com/3860857/121009235-89cd3d00-c7b1-11eb-8c74-b8f31d77b5ac.png)

In the below link the request syntax is different which doesn't matches the code that is defined above
https://docs.aws.amazon.com/AmazonS3/latest/API/API_SelectObjectContent.html

### Environment
Latest .Net SDK

## Resolution
- If we move xmlWriter.WriteEndElement() above the scanrange then it will fix the issue

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Reproducible using the following code and attached text file:
```C#
using Amazon.S3;
using Amazon.S3.Model;
using System;
using System.IO;
using System.Text;

namespace S3Select_Issue1825
{
    class Program
    {
        static void Main(string[] args)
        {
            AmazonS3Client client = new AmazonS3Client();
            var inSer = new InputSerialization()
            {
                CSV = new CSVInput()
                {
                    FileHeaderInfo = FileHeaderInfo.Use,
                    RecordDelimiter = "\r\n"
                }
            };

            var outSer = new OutputSerialization()
            {
                CSV = new CSVOutput()
                {
                    RecordDelimiter = "\n"
                }
            };

            var response = client.SelectObjectContentAsync(
                new SelectObjectContentRequest
                {
                    Bucket = "<<bucket_name>>",
                    Key = "<<key>>",
                    Expression = "select * from s3object",
                    ExpressionType = ExpressionType.SQL,
                    InputSerialization = inSer,
                    OutputSerialization = outSer,
                    ScanRange = new ScanRange() { Start= 10, End = 20 }
                }
            ).Result;

            using (var stream = response.Payload)
            {
                foreach (var ev in stream)
                {
                    if (ev is RecordsEvent records)
                    {
                        Console.WriteLine("Got record event");
                        using (var reader = new StreamReader(records.Payload, Encoding.UTF8))
                        {
                            string text = reader.ReadToEnd();
                        }
                    }
                }
            }
        }
    }
}
```
[testfile.txt](https://github.com/aws/aws-sdk-net/files/6612095/testfile.txt)

This retrieves all the records. User proposed change fixes the issue.

**Comment by ashishdhingra** [comment]
This has been fixed in [AWSSDK.S3 (3.7.1.1)](https://www.nuget.org/packages/AWSSDK.S3/3.7.1.1).
