### ISSUE TITLE
DynamoDB SDK: Speed up SDK/Table initialization by removing global lock on DescribeTable

### ISSUE THREAD

**Issue by williamdenton** [aws/aws-sdk-net#1873]
Before the DynamoDB can execute an operation on dynamodb, it must first describe the table. Once described it uses the table information for validation etc.
To optimise this, the result of the describe table operation is saved in an in-memory dictionary so to doesn't have to be requested again. It is cached at two levels, sdk wide in the `SDKCache`, and in a dictionary on the `DynamoDBContext` itself.

The cache mechanism in `DynamoDBContext` is very primitive, using a `Dictionary<string, Table>` to store the table data. Dictionaries are not threadsafe so to guard access to the cache a global lock is used. This means any api call that dynamodb makes must obtain the global lock while it accesses and possibly populates the cache.

The Describe table is a slow API (150-200ms) compared with 5-20ms for a table access (times here are from a Lambda).

In the case where an app accesses multiple dynamodb tables to service a request, this initialization time becomes significant, 3 tables might mean a 600ms delay for the first request.

## Describe the Feature
Modify the `GetUnconfiguredTable()` method to use a `ConcurrentDictionary<string, Table>` to avoid obtaining a global lock. This would allow concurrent access to the table cache. If I chose to run three queries to different tables concurrently, the sdk initialization can also run in parallel, meaning my api can return in ~200ms rather than ~600.

### Is your Feature Request related to a problem?
I'm frustrated at the cold start time of my lambda function, which is partially a result of the DynamoDB SDK running requests in serially rather than in parallel.

## Proposed Solution

Existing:
https://github.com/aws/aws-sdk-net/blob/7bed6856e8818181087c7501d93391b04380599e/sdk/src/Services/DynamoDBv2/Custom/DataModel/Context.cs#L38

https://github.com/aws/aws-sdk-net/blob/475822dec5e87954b7a47ac65995714ae1f1b115/sdk/src/Services/DynamoDBv2/Custom/DataModel/ContextInternal.cs#L124-L138

Proposed change:
```cs

ConcurrentDictionary<string, Table> tablesMap = new ConcurrentDictionary<string, Table>();

internal Table GetUnconfiguredTable(string tableName)
{
	return tablesMap.GetOrAdd(tableName, (_) => {
		var emptyConfig = new TableConfig(tableName, conversion: null, consumer: Table.DynamoDBConsumer.DataModel,
			storeAsEpoch: null, isEmptyStringValueEnabled: false);
		return Table.LoadTable(Client, emptyConfig);
	});
}
```

### Describe alternatives you've considered
* Using different DynamoDB Context objects for different tables, but this is awkward.
* During Cold start, use `n` different contexts to launch `n` dummy requests, to populate the SDKCache, allowing the DynamoDB context to fall though and behave as expected in the general case.

## Additional Context
Alternatively/Additionally speed up the DescribeTable api - though i realise that is a very different ask, not to mention different aws team/division.

### Environment
This is particularly impactful in Lambda where cold starts occur more frequently than a traditional app

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change  

---

This is a :rocket: Feature Request

**Comment by williamdenton** [comment]
for reference this is the call chain to get to describe table:

`Table.LoadTable()` from above calls here:

https://github.com/aws/aws-sdk-net/blob/449bb72eccfe78c2bfbd8ee2edbc2a7225e8323b/sdk/src/Services/DynamoDBv2/Custom/DocumentModel/Table.cs#L409-L414


`LoadTableInfo()` from above calls here:
https://github.com/aws/aws-sdk-net/blob/449bb72eccfe78c2bfbd8ee2edbc2a7225e8323b/sdk/src/Services/DynamoDBv2/Custom/DocumentModel/Table.cs#L128-L134

`DescribeTable` from above calls here:
https://github.com/aws/aws-sdk-net/blob/449bb72eccfe78c2bfbd8ee2edbc2a7225e8323b/sdk/src/Services/DynamoDBv2/Custom/DocumentModel/Table.cs#L327-L335

this then makes a synchronous api call to dynamo using `AmazonServiceClient`

**Comment by hunanniu** [comment]
@williamdenton. We have a plan to improve overall performance and usability of DynamoDB this year. We can incorporate your request here into our plan. We will post the relevant progress when we get there. Thanks

**Comment by joro550** [comment]
Hey :wave:, just wanted to mention that I took a stab something similar to this almost a year ago: https://github.com/aws/aws-sdk-net/pull/1678, looking back this is probably not the best pull request (as I was using semaphore slims and not concurrent dictionaries which feel like the better option) but I was trying - at the time - to make small changes so that the pull request would be reviewed faster (apparently I was wrong) but if you want to take inspiration from what I did, go ahead

Also person note: If you run the DDB tests on an actual AWS account and they fail make sure to delete the AWS artifacts other wise you might wake up to a nice hefty AWS bill, speaking from experience (thanks AWS)

**Comment by williamdenton** [comment]
Disappointed. Big start up gains for lambda to be had here and no action from the aws team.
