### ISSUE TITLE
AWS SDK for .NET Satisfaction Survey

### ISSUE THREAD

**Issue by ik130** [aws/aws-sdk-net#1879]
**Hello AWS .NET community!**

We are conducting a survey to learn about your recent experiences working with the AWS SDK for .NET and its learning resources. It will take less than 10 minutes to answer survey questions. We look forward to hearing from you!

### [Click HERE to take the survey](https://amazonmr.au1.qualtrics.com/jfe/form/SV_bqfQLfZ5nhFUiV0)

**Comment by Xyncgas** [comment]
Hi, the sdk for .net is missing the ability to set headers for PutObjectRequest.
![image](https://user-images.githubusercontent.com/35312807/133872588-fbf92916-8747-41b7-8492-2105cd209df5.png)

**Comment by ik130** [comment]
Survey is completed.
