### ISSUE TITLE
Real-time Transcribe 

### ISSUE THREAD

**Issue by hashitha** [aws/aws-sdk-net#1881]
Is it possible to use the Real-time feature of Transcribe using the SDK?

https://docs.aws.amazon.com/transcribe/latest/dg/API_streaming_StartMedicalStreamTranscription.html

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @hashitha,

Good afternoon.

Thanks for posting guidance question. Following articles could be helpful:
- [Automatic speech recognition using Amazon Transcribe](https://dotnet-developer-dojo.workshop.aws/lab7-ai-ml/transcribe.html)
- [How to use AWS Transcribe in real-time with React and .NET Core](https://automationrhapsody.com/how-to-use-aws-transcribe-in-real-time-with-react-and-net-core/)

Kindly note that the articles are for reference purposes only. Hope this helps.

Thanks,
Ashish
