### ISSUE TITLE
Kinesis Video Stream in Unity

### ISSUE THREAD

**Issue by Kanyade** [aws/aws-sdk-net#1882]
Greetings!

I just have a general question. Is the Kinesis Video Stream service supported in Unity? I couldn't find any info on this.
And if it is, how should one implement a stream in Unity, so that the mobile would stream it live?

**Comment by ashishdhingra** [comment]
Hi @Kanyade,

Good morning.

Thanks for posting guidance question. Although, I do not recall similar issue reported earlier, following articles might be helpful:
- https://github.com/aws-samples/aws-sdk-unity-samples/tree/master/Kinesis
- [Direct ingestion with Kinesis & the AWS SDK > Integrating with Unity](https://serverless-game-analytics.workshop.aws/en/ingest/unity.html)
- [Generate Custom Game Events from Unity Integrated With the Game Analytics Pipeline](https://aws.amazon.com/blogs/gametech/generate-custom-game-events-from-unity-integrated-with-our-game-analytics-pipeline/)
