### ISSUE TITLE
ListUsersAsync linked Sub

### ISSUE THREAD

**Issue by stephenstroud** [aws/aws-sdk-net#1883]
## The Question

After successfully merging user accounts using AdminLinkProviderForUserAsync the Cognito dashboard shows both linked accounts have a common sub between them. (As excepted) the original non primary accounts have adopted the primary account sub.

In this case I linked a native account with a Google account using the same email address.

However, calling the endpoint ListUsersAsync after linkage using filter email returns both accounts but with the original subs and not the linked sub in both identity occurrences. 

Is this expected behaviour? If so, how can I get the linked account sub or which account is primary?

### Environment
* Nuget Version: AWSSDK.CognitoIdentityProvider 3.7.1.10
* OS Info: Windows 10
* Build Environment: Visual Studio
* Targeted .NET Platform:  .NET 5.0

---

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @stephenstroud,

Good morning.

Thanks for posting guidance question. Could you please elaborate the issue, may be by providing some sample code and screenshots, is possible? The `AWSSDK.CognitoIdentityProvider` is just a wrapper to invoke Cognito service API calls. Any behavior for the mentioned operations is driven by the service API. More details for these operations could be found at [AdminLinkProviderForUser](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminLinkProviderForUser.html) and [ListUsers](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ListUsers.html). 

Thanks,
Ashish

**Comment by stephenstroud** [comment]
Same question with code snippets. 

I link any existing users via Lambda using AdminLinkProviderForUserAsync with preAuth trigger

`  private async Task LinkUserAccountAsync(string userName, Event input)
        {
            var sourceProvider = input.UserName.Split("_")[0];
            string formatedSourceProvider;
            switch (sourceProvider)
            {
                case "signinwithapple":
                    formatedSourceProvider = "SignInWithApple";
                 break;
                case "google":
                    formatedSourceProvider = "Google";
                    break;
                default:
                    throw new Exception("Missing Configured Provider");
            }

            var adminLinkProvider = new AdminLinkProviderForUserRequest()
            {
                DestinationUser = new ProviderUserIdentifierType
                {
                    ProviderAttributeValue = userName,
                    ProviderName = "Cognito"
                },
                SourceUser = new ProviderUserIdentifierType
                {
                    ProviderAttributeName = "Cognito_Subject",
                    ProviderAttributeValue = input.UserName.Split("_")[1],
                    ProviderName = formatedSourceProvider
                },
                UserPoolId = _userPoolSettings.Id
            };

            await _amazonCognitoIdentityProviderClient.AdminLinkProviderForUserAsync(adminLinkProvider);

            LambdaLogger.Log($"Linked account for {userName} + {input.UserName}");
        }
`
Later sometime after account merge I retrieve all the user accounts using ListUsersAsync with the same email (code below). The linked accounts all have different subs when calling this endpoint, however, shown in the Cognito user pool dashboard they all have the same shared sub after account merge. I can also call other endpoints like adminAddUserToGroup using the shared sub which will link all the shared accounts to that group.  

`
var serializedEmail = JsonConvert.SerializeObject(email);

            var response = await _amazonCognitoIdentityProviderClient.ListUsersAsync(new ListUsersRequest { UserPoolId = _userPoolSettings.Id, Filter = $"email = {serializedEmail}" }, cancellationToken);
`

My question is - why doesn't ListUsersAsync return the shared sub? It only returns the original sub for each account before account merge. How do I get the merged sub? Shouldn't ListUsersAsync return the merged sub instead of the original subs?

thanks

**Comment by ashishdhingra** [comment]
Hi @stephenstroud,

Good afternoon.

Could you please share the detailed information, possibly shared with screenshots? Also, could you let us know what is meant by `shown in the Cognito user pool dashboard they all have the same shared sub after account merge`? Sub appears to be a GUID value and these are unique in time and space. As mentioned in my earlier reply, `AWSSDK.CognitoIdentityProvider` package just has wrapper classes to invoke Cognito service API calls and any behavior for the mentioned operations is driven by the service API.

Thanks,
Ashish
