### ISSUE TITLE
`AWSSDKUtils.IsAbsolutePath` incorrect for Framework 4.7.2 target on non-Windows platforms

### ISSUE THREAD

**Issue by richarddbarnett** [aws/aws-sdk-net#1884]
## Description

I'm running applications targeting .NET Framework 4.7.2 on Mono 6.6 in Ubuntu 18.04 containers in EKS (k8s 1.19). 
Pods are associated with a service account associated with an IAM role.
I use `FallbackCredentialsFactory.GetCredentials()` to obtain credentials, expecting `AssumeRoleWithWebIdentityCredentials.FromEnvironmentVariables()` to provide them in this environment.

The EKS environment is correctly configured for this:
* Pods have environment variable `AWS_WEB_IDENTITY_TOKEN_FILE` set to `/var/run/secrets/eks.amazonaws.com/serviceaccount/token`
* This file exists & its content seems reasonable
* Other required environment variables are also set in the pods

`FallbackCredentialsFactory.GetCredentials()` fails with an exception message `The webIdentityTokenFile must be an absolute path.`

This can be traced to `AWSSDKUtils.IsAbsolutePath` & its use of `IsWindows` in [`AWSSDKUtils.cs`](https://github.com/aws/aws-sdk-net/blob/3.7.72.0/sdk/src/Core/Amazon.Util/AWSSDKUtils.cs#L875-L886)
```csharp
        public static bool IsAbsolutePath(string path)
        {
            return IsWindows() ? !IsPartiallyQualifiedForWindows(path) : Path.IsPathRooted(path);
        }

        private static bool IsWindows()
        {
#if NETSTANDARD
            return RuntimeInformation.IsOSPlatform(OSPlatform.Windows);
#endif
            return true;
        }
```

On a non-Windows platform, `IsWindows` will clearly return the wrong result for any .NET Framework target. 

[`RuntimeInformation.IsOSPlatform`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation.isosplatform?view=net-5.0) is available since .NET Framework 4.7.1

This was mentioned in https://github.com/aws/aws-sdk-net/issues/1615#issuecomment-790150012 but that related issue's now been closed.

### Environment

* SDK Version: git tag 3.7.72.0
* Package Version: 
* OS Info: Ubuntu 18.04
* Build Environment: mcr.microsoft.com/dotnet/core/sdk:3.1-bionic
* Targeted .NET Platform: .NET Framework 4.7.2

---

This is a :bug: bug-report

**Comment by ppittle** [comment]
Unfortunately .NET Framework is only supported on Windows using the Microsoft runtime.

You could:
* Update your Kubernetes cluster to add Windows nodes: https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html
* Update your application to target Net Standard 2.0+, which has native support for running on Linux.  The Porting Assistant for .NET tool may help with such an upgrade: https://aws.amazon.com/porting-assistant-dotnet/
