### ISSUE TITLE
UploadDirectoryFileRequestArgs and Amazon.S3.Model.MetadataCollection

### ISSUE THREAD

**Issue by malaterre** [aws/aws-sdk-net#1886]
## Describe the Feature

I'd like to be able to Clear() any existing Metadata from an TransferUtilityUploadRequest instance. As in:

```C#
private void Request_UploadDirectoryFileRequestEvent(object sender, UploadDirectoryFileRequestArgs e)
{
    TransferUtilityUploadRequest? request = e.UploadRequest;
    string? ext = Path.GetExtension(request.Key);
    request.Metadata.Clear(); // Remove any existing metadata from previous run
    switch (ext)
    {
        case ".png":
            request.Metadata.Add("x-amz-meta-foo", "foo");
            break;
        case ".jpg":
            request.Metadata.Add("x-amz-meta-bar", "bar");
            break;
    }
}

```
### Is your Feature Request related to a problem?

Otherwise depending on the order of operation two metadata are created or only one.

The API only offer Add() functionality:

* https://github.com/aws/aws-sdk-net/blob/475822dec5e87954b7a47ac65995714ae1f1b115/sdk/src/Services/S3/Custom/Model/MetadataCollection.cs#L64

## Proposed Solution

Implement a Clear() function, using Dictionary<TKey,TValue>.Clear Method:

* https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.clear?view=net-5.0

### Describe alternatives you've considered

I would need to reimplement UploadDirectoryAsync on my own.

**Comment by malaterre** [comment]
Posted on SO, but I suspect there is no real alternative:

* https://stackoverflow.com/questions/68500048/uploaddirectoryfilerequestargs-and-amazon-s3-model-metadatacollection

**Comment by ashishdhingra** [comment]
Providing `Clear()` would clear all metadata, including system defined metadata. So the solution (if feasible) could be:
- Provide `Clear()` method which iterates over all keys and only removes user defined keys beginning with `x-amz-meta-`, OR
- Provide `Remove()` method which only allows removal of user defined keys beginning with `x-amz-meta-`.

(Refer [Working with object metadata](https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingMetadata.html#UserMetadata) for more details)

**Comment by ashishdhingra** [comment]
Fixed in [AWSSDK.S3 (3.7.4.0)](https://www.nuget.org/packages/AWSSDK.S3/3.7.4)
