### ISSUE TITLE
AmazonCloudFrontUrlSigner.BuildPolicyForSignedUrl() method doesn't support not passing DateGreaterThan

### ISSUE THREAD

**Issue by WalkerCodeRanger** [aws/aws-sdk-net#189]
The `AmazonCloudFrontUrlSigner.BuildPolicyForSignedUrl(...)` method has code  intended to support not having a DateGreaterThan value ("`epochDateGreaterThan == null ? "" :...`"). However, this doesn't work becuase the DateTime datatype isn't nullable so `epochDateGreaterThan == null` is always false.

Given that you need backward compatibility and likely want to be CLS complaint, I recommend you add an overload without the `DateTime epochDateGreaterThan` parameter.  Note, the `AmazonCloudFrontUrlSigner.GetCustomSignedURL(...)` methods call this one and should be overloaded/changed to match.

Also, since wildcards can't be used with canned policies, the `BuildPolicyForSignedUrl` is useful even when you only want to specify resourcePath and epochDateLessThan.  It would be nice to have an overload or default parameters which supports that use case.

Finally, the `epochDateLessThan == null` check at the beginning of the `BuildPolicyForSignedUrl` method will always be false and so has no effect and can be removed.

**Comment by johnboker** [comment]
+1

**Comment by cmilam87** [comment]
+1

**Comment by normj** [comment]
Good catch, I'm surprised the compiler didn't complain about doing null comparisons on a null type.

I'm leery of overloads because they have tend to explode in the number of needed overloads. I'm thinking of changing the logic to not include epochDateLessThan if it equals DateTime.MinValue and epochDateGreaterThan if it is equal to DateTime.MaxValue. What do you think?

**Comment by WalkerCodeRanger** [comment]
I understand your hesitation about overloads, this does seem like a case where the overloads might multiply.  The use of DateTime.MinValue and DateTime.MaxValue is reasonable, as long as it is very clearly documented.  I have seen other APIs declare constants equal to the MinValue and MaxValue to make the code more readable (for example [Cache.NoAbsoluteExpiration](https://msdn.microsoft.com/en-us/library/system.web.caching.cache.noabsoluteexpiration%28v=vs.110%29.aspx)).  Personally, I'd rather see the parameters changed to *nullable* DateTime.  I think null more clearly indicates no limit.

**Comment by normj** [comment]
Switching to nullables would be preferred but a breaking change I don't want to make. We'll be sure the documentation clearly explains the significance using MinValue and MaxValue

**Comment by gokarnm** [comment]
The incorrect null check has been removed and new overloads have been added for [BuildPolicyForSignedUrl](https://github.com/aws/aws-sdk-net/blob/master/AWSSDK_DotNet35/Amazon.CloudFront/AmazonCloudFrontUrlSigner.cs#L410) and [GetCustomSignedURL](https://github.com/aws/aws-sdk-net/blob/master/AWSSDK_DotNet35/Amazon.CloudFront/AmazonCloudFrontUrlSigner.cs#L155) that do not require passing the activeFrom (DateGreaterThan) parameter.
