### ISSUE TITLE
[S3] Weird random S3.PutObject error with RecyclableMemoryStream body

### ISSUE THREAD

**Issue by oakad** [aws/aws-sdk-net#1893]
Package version: AWSSDK.S3 Version="3.7.0.26", Windows 10, Dotnet Core 5

Really weird error happening at random when doing a trivial PutObject with RecyclableMemoryStream `InputStream` (listed below).

1. The indicated error is weird: "Error making request with Error Code BadRequest and Http Status Code BadRequest. No further error information was returned by the service.", not something I've ever seen or can make sense of from the docs.
2. `Position` on the `InputStream` object property at the exception catch site indicates that `InputStream` was read in full (10s to 100s of kBs, nothing fancy).
3. Happens randomly, strongly prefers release builds and some machines over other.
4. Body is  RecyclableMemoryStream from "Microsoft.IO.RecyclableMemoryStream" Version="2.1.0" package, may be it has something to do with this.

> "exception": "Amazon.S3.AmazonS3Exception: Error making request with Error Code BadRequest and Http Status Code BadRequest. No further error information was returned by the service.\r\n ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.\r\n   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)\r\n   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)\r\n   at Amazon.Runtime.Internal.RedirectHandler.InvokeAsync[T](IExecutionContext executionContext)\r\n   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)\r\n   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeAsync[T](IExecutionContext executionContext)\r\n   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)\r\n   --- End of inner exception stack trace ---\r\n   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionStream(IRequestContext requestContext, IWebResponseData httpErrorResponse, HttpErrorResponseException exception, Stream responseStream)\r\n   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionAsync(IExecutionContext executionContext, HttpErrorResponseException exception)\r\n   at Amazon.Runtime.Internal.ExceptionHandler`1.HandleAsync(IExecutionContext executionContext, Exception exception)\r\n   at Amazon.Runtime.Internal.ErrorHandler.ProcessExceptionAsync(IExecutionContext executionContext, Exception exception)\r\n   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)\r\n   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)\r\n   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)\r\n   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)\r\n   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)\r\n   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)\r\n   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)\r\n   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)\r\n   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)\r\n   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeAsync[T](IExecutionContext executionContext)\r\n   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)\r\n   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)\r\n

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @oakad,

Good morning.

Could you please share sample code solution to help troubleshoot the issue?

Thanks,
Ashish

**Comment by oakad** [comment]
It's a very basic PutObject request which works vast majority of the times. The problem appears to happen under load (many tasks doing PutObject) and even then, not always.

Is there a way to log the prepared request from s3 client? Headers and all?
Considering the weird nature of the error returned by s3, I think some corruption is happening in the request headers.

**Comment by oakad** [comment]
The actual call site on our side looks like so:
```
await client.PutObjectAsync(new PutObjectRequest {
				AutoCloseStream = false,
				Key = objKey,
				BucketName = bucket,
				CannedACL = S3CannedACL.BucketOwnerFullControl,
				InputStream = src // this is RecyclableMemoryStream object with some data in it, Length() != 0
			}).ConfigureAwait(false);
```

**Comment by oakad** [comment]
Minrepro!

The below program will trigger the issue.
Some instructions:
1. It needs to run for minutes
2. It won't happen every time
3. When the issue happens, the program appears to get stuck for a bit (a minute or so).  Then it exits and the above exception is printed out.

```
using System;
using System.Threading;
using System.Threading.Tasks;
using System.Security.Cryptography;

using Microsoft.IO;

using Amazon;
using Amazon.S3;
using Amazon.S3.Model;
using Amazon.Runtime;

namespace Sdk_1893 {

public class T2 {
	public static async Task Main(string[] args) {
		var t = new T2();
		await t.Run();
	}

	T2() {
		bucket = "bucket-test";
		keyPrefix = "t9/assets/";
		var creds = FallbackCredentialsFactory.GetCredentials(true);

		var cl = new AmazonS3Client(
			creds,
			RegionEndpoint.USEast1 // Autodetect client region for easier testing
		);
		var resp = cl.GetBucketLocationAsync(bucket).Result;

		client = new AmazonS3Client(
			creds,
			RegionEndpoint.GetBySystemName(
				resp.Location.Value
			)
		);
	}

	async Task Run() {
		while (true) {
			await limiter.WaitAsync();
			_ = UploadNext().ContinueWith(t => {
				limiter.Release();
				if (t.Exception != null) {
					Console.WriteLine(t.Exception);
					limiter.Dispose();
					Environment.Exit(1);
				}
			});
		}
	}

	async Task UploadNext() {
		int dataSize = RandomNumberGenerator.GetInt32(1 << 8, 1 << 20);
		int blockSize = RandomNumberGenerator.GetInt32(1 << 5, 1 << 9);
		var block = new byte[blockSize];

		using var data = bufferPool.GetStream();
		int dataIn = 0;
		while (true) {
			RandomNumberGenerator.Fill(block);
			var rem = dataSize - dataIn;
			if (rem > block.Length) {
				data.Write(block);
				dataIn += block.Length;
			} else {
				data.Write(block, 0, rem);
				break;
			}
		}
		data.Position = 0;
		var hasher = MD5.Create();
		var hash = await hasher.ComputeHashAsync(data).ConfigureAwait(false);
		data.Position = 0;

		var objKey = keyPrefix + HexEncode(hash);

		var resp = await client.PutObjectAsync(new PutObjectRequest {
			AutoCloseStream = false,
			Key = objKey,
			BucketName = bucket,
			CannedACL = S3CannedACL.BucketOwnerFullControl,
			InputStream = data
		}).ConfigureAwait(false);
		Console.WriteLine(
			"Uploaded key {0} to bucket {1}, size {2}, etag {3}",
			objKey, bucket, data.Position, resp.ETag
		);
	}

	public static string HexEncode(byte[] bb_) {
		if (bb_ == null)
			return "";

		return string.Create(bb_.Length * 2, bb_, (cc, bb) => {
			const string digits = "0123456789abcdef";

			for (int pos = 0; pos < cc.Length; pos += 2) {
				var b = (int)(bb[pos >> 1]) & 0xff;
				cc[pos] = digits[b >> 4];
				cc[pos + 1] = digits[b & 0xf];
			}
		});
	}

	SemaphoreSlim limiter = new SemaphoreSlim(256, 256);
	RecyclableMemoryStreamManager bufferPool = new RecyclableMemoryStreamManager();
	AmazonS3Client client;
	string bucket;
	string keyPrefix;

}
}
```

**Comment by ashishdhingra** [comment]
Hi @oakad,

Good afternoon.

Thanks for the reproduction code sample. I ran it for several minutes and was unable to reproduce the issue. Although I'm not sure, you may receive throttling errors since your program is uploading too many objects per second (indirectly making many API calls) inside a `while` loop. Refer the following articles:
- https://aws.amazon.com/premiumsupport/knowledge-center/s3-resolve-503-slowdown-throttling/
- https://www.alluxio.io/answers/storage/am-i-bottlenecking-on-s3-s3-throttling-my-requests/

You might want some mechanism in place to avoid hitting S3 service with too many requests over a period of time.

You might also want to check the memory usage when the program throws the exception.

You may enable logging by using properties of `AWSConfigs` as shown below for example:
```C#
Amazon.AWSConfigs.LoggingConfig.LogResponses = Amazon.ResponseLoggingOption.Always;
Amazon.AWSConfigs.LoggingConfig.LogTo = Amazon.LoggingOptions.SystemDiagnostics;
Amazon.AWSConfigs.AddTraceListener("Amazon", new System.Diagnostics.ConsoleTraceListener());
```

Thanks,
Ashish

**Comment by oakad** [comment]
It's not a throttling issue, as it happens on different levels of limiting. Also, we know what throttling looks like, we can max out s3 quite easily with our Go apps. :-)

Note, that mechanism is in place, in form of `SemaphoreSlim`, handily called "limiter".

This is not an easy to reproduce issue. Clearly, a combination of factors is at play, possibly some problem with dotnet runtime. The memory utilization of the program stays steady, you can see it for yourself.

**Comment by ashishdhingra** [comment]
@oakad Thanks for your response. Please share the logs for the failure once available, may be we could find some meaningful information to troubleshoot the issue.
