### ISSUE TITLE
Support CloudFront signed cookies

### ISSUE THREAD

**Issue by WalkerCodeRanger** [aws/aws-sdk-net#190]
The `AmazonCloudFrontUrlSigner` method is very helpful in creating signed CloudFront urls and should really be mentioned in the [relevant AWS docs](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CreateSignatureInCSharp.html).  *Please add support for similar functionality for the new [CloudFront Signed Cookies](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-signed-cookies.html).*

Most of the needed functionality already exists in the `AmazonCloudFrontUrlSigner` class. It just needs to be exposed in a way that makes this easier.  Currently we use `BuildPolicyForSignedUrl` and `SignUrlCanned` and then break apart the Url to get the various pieces for the cookies.

**Comment by normj** [comment]
I agree this does sound useful. I have added the feature request to our backlog.

**Comment by gokarnm** [comment]
Hi, the [AmazonCloudFrontCookieSigner](https://github.com/aws/aws-sdk-net/blob/master/AWSSDK_DotNet35/Amazon.CloudFront/AmazonCloudFrontCookieSigner.cs) utility class was added to the latest version of the SDK (2.3.36) to support generation of signed cookies. Thanks for the feedback!

**Comment by altanai** [comment]
Unable to locate CloudfrontCookieSigner from the above mentioned URL . github 404 . could you share the a working location f the same . thanks

**Comment by IainCole** [comment]
Looks like master now has the modular sdk code. The equivalent appears to be here https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/CloudFront/Custom/_bcl/AmazonCloudFrontCookieSigner.cs

**Comment by normj** [comment]
Also the V2 code can be found on the aws-sdk-net-v2 branch

https://github.com/aws/aws-sdk-net/tree/aws-sdk-net-v2

**Comment by rajasrmit** [comment]
I have tried out the given code but I'm getting "nvalid RSA Private Key" by using this method.
AmazonCloudFrontCookieSigner.GetCookiesForCannedPolicy()
