### ISSUE TITLE
SSO credentials are not accepted as default

### ISSUE THREAD

**Issue by ryan-motive** [aws/aws-sdk-net#1900]
## Description
Not clear if this is a bug or a feature request. It seems like a bug. If I defined SSO credentials as the default in my credentials file, the SDK fails to resolve them using the default resolve path. Current workaround is to generate temporary key/secret and add those to the credentials file manually or to re-write the code to explicitly look up the SSO credentials by profile name.

## Reproduction Steps
Add your SSO credentials configuration to the [default] section of the credentials file.

### Logs
N/A

### Environment
* SDK Version: 3.7.2.1
* OS Info: Windows 10
* Build Environment Visual Studio
* Targeted .NET Platform:  .NET 5.0

## Resolution
Unknown what the resolution is. SSO credentials can be used if you explicitly send them to a service, but this breaks a lot of code that assumes there are default credentials configured. Understood that these calls will fail if you're not logged in. I don't believe it's important to kick off the login step, users who configure this way will be aware that they need to log into SSO in advance.

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @ryan-motive,

Thanks for reporting the issue. Could you please share the error message and stack trace, if any? I believe this is related to the existing issue https://github.com/aws/aws-sdk-net/issues/1853 where similar issue is reported. There is a workaround posted in https://github.com/aws/aws-sdk-net/issues/1853#issuecomment-863207180 which might help without requiring you to generate temporary credentials.

Thanks,
Ashish

**Comment by ryan-motive** [comment]
The error is this, which I understand just means the credentials chain got to the end and wasn't able to find any it could use:

"Unable to get IAM security credentials from EC2 Instance Metadata Service"

Issue 1853 is similar, but the workaround is not viable because it would require me to rewrite all of the current code that expects defaults to take in configured credentials instead.

**Comment by ashishdhingra** [comment]
Default credential resolution fetches credentials which require no callback, for SSO this fails at https://github.com/aws/aws-sdk-net/blob/f33050e58133959457b66b95481257e4f17e67ce/sdk/src/Core/Amazon.Runtime/CredentialManagement/AWSCredentialsFactory.cs#L158. The credential resolution ultimately fails at last EC2 instance credential generator (https://github.com/aws/aws-sdk-net/blob/f33050e58133959457b66b95481257e4f17e67ce/sdk/src/Core/Amazon.Runtime/Credentials/FallbackCredentialsFactory.cs#L58).

**Comment by ashishdhingra** [comment]
> Right - is this considered a bug or is this by design? It seems like this should work as long as I'm logged in and have fresh SSO credentials. Otherwise the only workaround is to hand-patch the credentials file every time I run.

@ryan-motive I will discuss this with team and update here accordingly.

**Comment by ryan-motive** [comment]
Thank you!

**Comment by supergibbs** [comment]
> Otherwise the only workaround is to hand-patch the credentials file every time I run.

Alternative workaround is using [yawsso](https://github.com/victorskl/yawsso), it'll help with the hand patching part at least.
