### ISSUE TITLE
AmazonS3Uri failed to decode url with unicode characters

### ISSUE THREAD

**Issue by akivamu** [aws/aws-sdk-net#1902]
## Description
I have s3 file name include unicode character, e.g. "患.txt".
When pass the url (get from S3 console) into AmazonS3Uri(), the result Key is incorrect.

## Reproduction Steps
```
var url = $"https://bucket.s3.amazonaws.com/%E6%82%A3.txt";
var s3Uri = new AmazonS3Uri(url);

Assert.AreEqual("患.txt", s3Uri.Key);
```

Result:

```
Assert.AreEqual failed. Expected:<患.txt>. Actual:<æ£.txt>. 
```

### Environment
* SDK Version: AWSSDK.S3:3.7.1.20
* Package Version: AWSSDK.S3:3.7.1.20
* OS Info: Windows 10
* Build Environment Visual Studio 2019
* Targeted .NET Platform:  net5.0

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Reproducible using the below code:
```C#
using Amazon.S3;
using Amazon.S3.Model;
using Amazon.S3.Util;
using System;

namespace S3AmazonS3Uri_Issue1902
{
    class Program
    {
        static void Main(string[] args)
        {
            var url = $"https://bucket.s3.amazonaws.com/%E6%82%A3.txt";
            var uri = new Uri(url);
            var amazonS3Uri = new AmazonS3Uri(url);
            Console.WriteLine($"URI: {uri}, Amazon S3 URI: {amazonS3Uri.Bucket}::{amazonS3Uri.Key}");
        }
    }
}

```
which produces the following output:
```
URI: https://bucket.s3.amazonaws.com/患.txt, Amazon S3 URI: bucket::æ£.txt
```

**Comment by ashishdhingra** [comment]
Looks like `AmazonS3Uri` constructor is not handling the customer's use case properly at:
- https://github.com/aws/aws-sdk-net/blob/958fdf964055c1b794f242924f7a28f5ee0b0aa0/sdk/src/Services/S3/Custom/Util/AmazonS3Uri.cs#L124
- https://github.com/aws/aws-sdk-net/blob/958fdf964055c1b794f242924f7a28f5ee0b0aa0/sdk/src/Services/S3/Custom/Util/AmazonS3Uri.cs#L245

**Comment by ashishdhingra** [comment]
Looks like similar to Java SDK (which uses `URLEncoder.encode()`) https://github.com/aws/aws-sdk-java/blob/09b348b81616134989a09bca0495b56e90b8b4c2/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3URI.java#L261, we should support overloaded version to encode URL. Following code works (for .NET Core 3.1):
```
var url = $"https://bucket.s3.amazonaws.com/%E6%82%A3.txt";
var uri = new Uri(System.Net.WebUtility.UrlEncode(url).Replace("%3A", ":").Replace("%2F", "/").Replace("+", "%20"));
var amazonS3Uri = new AmazonS3Uri(url);
Console.WriteLine($"URI: {uri}, Amazon S3 URI: {amazonS3Uri.Bucket}::{amazonS3Uri.Key}");
```

In .NET Framework, we have `System.Web.HttpUtility`. Not sure we want to include these dependencies in `AWSSDK.S3`.

**Comment by waiwaing** [comment]
I believe this is still an issue with the AWS SDK based on an issue I've been investigating today; passing in a correctly percent-encoded `Uri` to the `AmazonS3Uri` constructor still results in an incorrect `Path`.
