### ISSUE TITLE
The secondary remote name could not be resolved

### ISSUE THREAD

**Issue by likun862679370** [aws/aws-sdk-net#1907]
## Description

![image](https://user-images.githubusercontent.com/7893375/131238328-25b28af8-4a43-48b3-bfb2-328133f9e560.png)

python use same configuration is ok

### Environment

* SDK Version: ![image](https://user-images.githubusercontent.com/7893375/131238328-25b28af8-4a43-48b3-bfb2-328133f9e560.png)1.28
* Package Version: 3.7.1.28
* OS Info: win10
* Build Environment Visual Studio
* Targeted .NET Platform:  .net core 3.1

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @likun862679370,

Good morning.

Looking at your logic above, looks like you are setting the `ServiceUrl` after setting the `RegionEndpoint`. This is resetting the `RegionEndpoint` to `null` based on the logic at https://github.com/aws/aws-sdk-net/blob/2b93f7db42290aa61000d8fd143a7e40e5890456/sdk/src/Core/Amazon.Runtime/ClientConfig.cs#L181.
the behavior is also documented in API documentation at https://docs.aws.amazon.com/sdkfornet1/latest/apidocs/html/T_Amazon_S3_AmazonS3Config.htm.

Kindly note that `ServiceUrl` must be set to valid service URL or VPC endpoint URL. Not sure if the value **other-test.s3-syny-changingedu.com** is valid for `ServiceUrl`, could you please advise? Kindly note that even though there are many local stack implementations, we do not guarantee if AWS SDKs would work correctly.

Thanks,
Ashish
