### ISSUE TITLE
"Invalid region endpoint provided" In .NET Core 

### ISSUE THREAD

**Issue by RichardD012** [aws/aws-sdk-net#1908]
## Description
We recently did an update of our libraries to the latest in the .NET SDK and any that are using the SDK of at least 3.7.0.43, seem to throw an Invalid Region Endpoint Provided locally. We're not seeing this issue in production so I'm not sure how to track down the difference. We have a handful of different AWS Services but any individual one that isupdated to use the above SDK, causes this exception. It's clearly from a recent change, but I'm not sure what needs to change on our side. https://github.com/aws/aws-sdk-net/blob/2b93f7db42290aa61000d8fd143a7e40e5890456/sdk/src/Core/RegionEndpoint/RegionEndpointProviderV3.cs#L61

## Reproduction Steps
In our `Startup.cs` we follow the guidelines here: https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-netcore.html

```
            var awsOptions = Configuration.GetAWSOptions();
             services.AddDefaultAWSOptions(awsOptions);
            services.AddAWSService<IAmazonSimpleEmailService>();
            services.AddAWSService<IAmazonSQS>();
            services.AddAWSService<IAmazonS3>();
            services.AddAWSService<IAmazonEC2>();
            services.AddAWSService<IAmazonECS>();
```

Our configuration in appsettings.json looks like:
```
{
	"Logging": {
		"LogLevel": {
			"Default": "Trace",
			"Microsoft": "Warning",
			"Microsoft.Hosting.Lifetime": "Warning"
		}
	},
	"AWS": {
		"Profile": "default",
		"Region": "us-east-1"
	}
}
```

Debugging the above, I can clearly see that the awsOptions is loading the correct Configuration information from our `appsettings.json` file and has a region endpoint of `{US East (N. Virginia) (us-east-1)}`.  However, any controller we end up injecting any of the above services throws a "Invalid Region Endpoint Provided" exception. Below is the stack trace.

I specifically included the AWSSDK.Extensions.NETCore.Setup because the previous version of 3.7.0.1 correctly works so that individual jump is a good indicator that it's the specific change referenced above.

### Logs
```
[message=Invalid region endpoint provided] System.ArgumentException: Invalid region endpoint provided
   at Amazon.Internal.RegionEndpointProviderV3.GetNonstandardRegionEndpoint(String regionName)
   at Amazon.Internal.RegionEndpointProviderV3.GetRegionEndpoint(String regionName)
   at Amazon.RegionEndpoint.GetEndpoint(String systemName, String displayName)
   at Amazon.RegionEndpoint.GetBySystemName(String systemName)
   at Amazon.Runtime.CredentialManagement.SharedCredentialsFile.TryGetProfile(String profileName, Boolean doRefresh, CredentialProfile& profile)
   at Amazon.Runtime.CredentialManagement.SharedCredentialsFile.TryGetProfile(String profileName, CredentialProfile& profile)
   at Amazon.Runtime.CredentialManagement.CredentialProfileStoreChain.TryGetProfile(String profileName, CredentialProfile& profile)
   at Amazon.Runtime.CredentialManagement.CredentialProfileStoreChain.TryGetAWSCredentials(String profileName, AWSCredentials& credentials)
   at Amazon.Extensions.NETCore.Setup.ClientFactory.CreateCredentials(ILogger logger, AWSOptions options)
   at Amazon.Extensions.NETCore.Setup.ClientFactory.CreateServiceClient(ILogger logger, Type serviceInterfaceType, AWSOptions options)
   at Amazon.Extensions.NETCore.Setup.ClientFactory.CreateServiceClient(IServiceProvider provider)
```

### Environment
* SDK Version:  3.7.0.43
* Package Version: AWSSDK.Extensions.NETCore.Setup 3.7.1
* OS Info: OSX Big Sur
* Build Environment: Visual Studio Code
* Targeted .NET Platform:  .NET 5.0.201

---

This is a :bug: bug-report

**Comment by RichardD012** [comment]
Sorry to spam this but immediately after looking at this, I thought to look in our `credentials` file. We use a 2FA login that updates the credentials file routinely. The region set in there was empty. It seems the updated code uses the region from the credentials file and not what is passed in with the Options settings from the settings above.

Once I set `region = us-east-1` in the credentials file it seems to work.

I'm not sure what the appropriate hierarchy here is but my assumption is that providing it in the configuration file of the .NET Core project would override any missing information in the credentials file.

**Comment by ashishdhingra** [comment]
Hi @RichardD012,

Good afternoon.

I was able to generate the reported error `ArgumentException: Invalid region endpoint provided` if have the `region` key in `credentials` file but **do not specify any value** using the below minimal code:
**Startup.cs**
```C#
using Amazon.S3;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace WebApplication1
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc(options => options.EnableEndpointRouting = false);

            var awsOptions = Configuration.GetAWSOptions();
            services.AddDefaultAWSOptions(awsOptions);
            services.AddAWSService<IAmazonS3>();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRouting();

            app.UseAuthorization();
            app.UseMvc(m =>
            {
                m.MapRoute(
                    name: "default",
                    template: "{controller}/{action}/{id?}",
                    defaults: new { controller = "Home", action = "Index" });
            });
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapRazorPages();
            });
        }
    }
}
```
**.csproj**
```XML
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.7.1" />
    <PackageReference Include="AWSSDK.S3" Version="3.7.1.30" />
  </ItemGroup>

</Project>
```
**Controllers\HomeController.cs**
```C#
using Amazon.S3;
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Contollers
{
    public class HomeController : Controller
    {
        private IAmazonS3 _amazonS3;

        public HomeController(IAmazonS3 amazonS3)
        {
            this._amazonS3 = amazonS3;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}
```
**appSettings.json**
```JSON
{
  "Logging": {
    "LogLevel": {
      "Default": "Trace",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Warning"
    }
  },
  "AWS": {
    "Profile": "default",
    "Region": "us-east-1"
  }
}
```

If I specify the region value in credentials file (used `us-east-2`) or remove the region key all together, proper region is set on the service client when injected in controller via DI. This indicates that the SDK is properly taking `region` specified in `appSettings.json` over what is specified in default profile in credentials file.

The above said error is expected since the region key is present in the default profile with missing value. The presence of region key in default profile signals SDK to parse __incorrect__ empty value when loading the default profile. So in your case, you could either remove region key from the default profile or specify __any__ value.

Hope this helps. Kindly confirm if this issue could be closed.

Thanks,
Ashish

**Comment by RichardD012** [comment]
Thanks that absolutely helps and I think is a new case compared to the old way, which totally makes sense. Removing the key altogether seems to work with our 2fa provider and everything works fine. Not sure if some documentation could specify this since it is an odd quirk of an empty region being absolutely invalid now.
