### ISSUE TITLE
AmazonSecurityTokenServiceClient Client.AssumeRoleAsync(Role) throwing the exception "Unable to get IAM security credentials from EC2 Instance Metadata Service."

### ISSUE THREAD

**Issue by Lurchicus** [aws/aws-sdk-net#1909]
## Description
My employers network security team has advised us that we can no longer use an IAM User or AccessKey/SecretKey
keypairs (prod or nonprod) to obtain credentials for AWS S3 Glacier and S3 services which my application uses. 

This included not allowing the use of an encrypted shared credentials profile (which had been working well for me)

I have been advised to use Assume Role  (AssumeRoleAsync()) instead, but it's giving me a fairly generic error ("Unable to get IAM security credentials from EC2 Instance Metadata Service.")

## Reproduction Steps

Exception thrown when executing AssumeRoleAsync()

'''
Glacial assume role error (Exception): 
Unable to get IAM security credentials from EC2 Instance Metadata Service. 
Stack:    
at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.FetchCredentials()     
at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentials()     
at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentialsAsync()     
at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)     
at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)     
at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)     
at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)     
at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)     
at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)     
at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)     
at Glacial.Program.DoAssumeRoleG(AmazonSecurityTokenServiceClient Client) 
in C:\Users\rheada01\Source\Repos\glacial-archiver\Glacial\Program.cs:line 519 
Inner ex:  (none)
RoleArn: arn:aws:iam::{redact}:role/Glacial-Archiver-Nonprod 
RoleSessionName: GlacialArchiverGSession-08-2021-105627
'''

Code snippet:

'''C#
        /// Get temporary credentials using AssumeRoleAsync()
        /// As I am no longer allowed to use an IAM user or public/private keypairs (even from an 
        /// encrypted shared credentials profile) I am back to trying to get AssumeRoleAsync() to work 
        /// (without success so far)
        private static async Task AssumeGlacierRoll()
        {

            GRoleFail = false;

            AssumeGRoleReq = new AssumeRoleRequest
            {
                //Parameters below are stored in a configuration file we read at runtime (DoSetup())
                RoleArn = GlacierRoleArn,                   // The arn for the role I want to assume
                RoleSessionName = GlacierRoleSessionName,   // A unique session name (name-mm-yyyy-hhmnss)
                DurationSeconds = 14400                     // Time in seconds before temp credintials expire
            };

            // Get a security token service client to work with AssumeRoleAsync()
            AmazonSecurityTokenServiceClient Client = new AmazonSecurityTokenServiceClient(RegionEP);

            // While the following code looks clunky, it's the only way I found to be able to use 
            // try/catch with an async method in DoAssumeRoleG()
            Task RG = DoAssumeRoleG(Client);
            RG.Wait(); // Force sync

            if (GRoleFail)
            {
                Logger(GRoleFailMess + " RoleArn: " + GlacierRoleArn + 
                    " RoleSessionName: " + GlacierRoleSessionName, 3);
            }
            else
            {
                AssumedGRoleUser = AssumedGRoleResp.AssumedRoleUser;
                GRoleCredentials = AssumedGRoleResp.Credentials;
            }
        }

        private static async Task DoAssumeRoleG(AmazonSecurityTokenServiceClient Client)
        {
            GRoleFail = false;
            try
            {
                AssumedGRoleResp = await Task.Run(() => Client.AssumeRoleAsync(AssumeGRoleReq));
            }
            catch (ExpiredTokenException e1)
            {
                GRoleFail = true;
                GRoleFailMess = "Glacial assume role error (ExpiredTokenException): " + e1.Message;
            }
            catch (MalformedPolicyDocumentException e2) 
            {
                GRoleFail = true;
                GRoleFailMess = "Glacial assume role error (MalformedPolicyDocumentException): " + e2.Message;
            }
            catch (PackedPolicyTooLargeException e3)
            {
                GRoleFail = true;
                GRoleFailMess = "Glacial assume role error (PackedPolicyTooLargeException): " + e3.Message;
            }
            catch (RegionDisabledException e4)
            {
                GRoleFail = true;
                GRoleFailMess = "Glacial assume role error (RegionDisabledException): " + e4.Message;
            }
            catch (Exception ex)
            {
                GRoleFail = true;
                GRoleFailMess = "Glacial assume role error (Exception): " + ex.Message + 
                    " Stack: " + ex.StackTrace + " Inner ex: " + ex.InnerException;
            }
        }
'''

### Logs

'Glacial.exe' (CoreCLR: DefaultDomain): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Private.CoreLib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Users\rheada01\Source\Repos\glacial-archiver\Glacial\bin\Debug\netcoreapp3.1\Glacial.dll'. Symbols loaded.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Threading.Tasks.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Collections.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Step into: Stepping over non-user code 'Glacial.Program.Main'
Step into: Stepping over non-user code 'Glacial.Program.<Main>d__43..ctor'
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Users\rheada01\Source\Repos\glacial-archiver\Glacial\bin\Debug\netcoreapp3.1\AWSSDK.SecurityToken.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Users\rheada01\Source\Repos\glacial-archiver\Glacial\bin\Debug\netcoreapp3.1\AWSSDK.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\netstandard.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Users\rheada01\Source\Repos\glacial-archiver\Glacial\bin\Debug\netcoreapp3.1\AWSSDK.Glacier.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Net.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Users\rheada01\Source\Repos\glacial-archiver\Glacial\bin\Debug\netcoreapp3.1\AWSSDK.S3.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Console.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Users\rheada01\Source\Repos\glacial-archiver\Glacial\bin\Debug\netcoreapp3.1\System.Configuration.ConfigurationManager.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Collections.Specialized.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Runtime.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Threading.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Private.Uri.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.IO.FileSystem.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Xml.ReaderWriter.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Private.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Runtime.InteropServices.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Net.WebClient.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.ComponentModel.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Threading.Thread.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Memory.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Security.Cryptography.Algorithms.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Text.Encoding.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.ComponentModel.TypeConverter.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.ObjectModel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Linq.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Drawing.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Users\rheada01\Source\Repos\glacial-archiver\Glacial\bin\Debug\netcoreapp3.1\runtimes\win\lib\netcoreapp3.1\Microsoft.Data.SqlClient.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Data.Common.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Transactions.Local.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Diagnostics.DiagnosticSource.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Collections.Concurrent.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Diagnostics.Tracing.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Threading.Timer.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Resources.ResourceManager.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Threading.ThreadPool.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Security.Cryptography.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Buffers.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Text.Encoding.CodePages.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\Microsoft.Win32.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Diagnostics.Process.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.ComponentModel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Text.RegularExpressions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Diagnostics.TraceSource.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Net.Http.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Runtime.InteropServices.RuntimeInformation.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Net.Security.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Security.Cryptography.X509Certificates.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Net.Requests.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Net.Sockets.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Threading.Overlapped.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Net.NameResolution.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Exception thrown: 'Amazon.Runtime.AmazonServiceException' in System.Private.CoreLib.dll
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Collections.Immutable.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.IO.MemoryMappedFiles.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'Glacial.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.18\System.Diagnostics.Debug.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The program '[16948] Glacial.exe' has exited with code 1 (0x1).

### Environment

* SDK Version: AWSSDK.Core (3.3.107.24), AWSSDK.SecurityToken (3.3.105.28)
* Package Version: 3.3.107.24
* OS Info: Microsoft Windows Server 2016 Standard (1607)
* Build Environment: Microsoft Visual Studio Professional 2019 (Version 16.10.4)
* Targeted .NET Platform:  .NET Core 3.1 Console Application

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @Lurchicus,

Good morning.

Just for your reference, [Credential and profile resolution](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/creds-assign.html) details about the credential search order in AWS SDK for .NET.

Could you please share if you are running your application locally or on an EC2 instance?

If running locally, your machine is not an EC2 instance and hence it's failing with the mentioned error (assuming the credentials are not found at the locations mentioned in link above).

If running on EC2 instance, kindly create an IAM role and attach it to your instance on which you are running the .NET code (IAM Role: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html). Also, make sure that you can reach the metadata URL http://169.254.169.254/latest/meta-data/ from within the instance (also refer https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html).

Hope this helps.

Thanks,
Ashish

**Comment by Lurchicus** [comment]
Hi Ashish,

I am not using an EC2 instance so I'm running locally (via my laptop when debugging on an on-prem Windows Server when in production).

I guess what I really need to do is find out how to go from a local server to AWS S3 Glacier/AWS S3. 

Previously I had been using an encrypted shared profile...

    chain.TryGetAWSCredentials("basic_profile", out awsCredentials);

This had been working fine for my application but I was advised by our network security team that I have to change my application to use Assume Role to obtain temporary credentials. I am no longer allowed to use an IAM User or the AccessKey/SecretKey keypair.

Thank you
Dan Rhea

**Comment by ashishdhingra** [comment]
> Hi Ashish,
> 
> I am not using an EC2 instance so I'm running locally (via my laptop when debugging on an on-prem Windows Server when in production).
> 
> I guess what I really need to do is find out how to go from a local server to AWS S3 Glacier/AWS S3.
> 
> Previously I had been using an encrypted shared profile...
> 
> ```
> chain.TryGetAWSCredentials("basic_profile", out awsCredentials);
> ```
> 
> This had been working fine for my application but I was advised by our network security team that I have to change my application to use Assume Role to obtain temporary credentials. I am no longer allowed to use an IAM User or the AccessKey/SecretKey keypair.
> 
> Thank you
> Dan Rhea

@Lurchicus Thanks for your response. Since this is not a bug in the SDK, I would change this issue to guidance. One option could be that your network security team could provide you with some interface to generate temporary session credentials which you could use in AWS environment variables (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_SESSION_TOKEN) or shared credential file. Not sure what guidance we could provide here, please advise if we should close this issue.

**Comment by Lurchicus** [comment]
Hi Ashish,

I have been advised that I am not allowed to use AWS environment variables (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_SESSION_TOKEN) or shared credential file. I was previously using a shared credential file. 

So is it simply not possible to access AWS with AWS SDK.NET from a non-EC2 instance Windows Server except using the methods I've been told I cannot use? I have questioned this internally and I keep being directed to use Assume Role.

Thank you

**Comment by ashishdhingra** [comment]
> Hi Ashish,
> 
> I have been advised that I am not allowed to use AWS environment variables (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_SESSION_TOKEN) or shared credential file. I was previously using a shared credential file.
> 
> So is it simply not possible to access AWS with AWS SDK.NET from a non-EC2 instance Windows Server except using the methods I've been told I cannot use? I have questioned this internally and I keep being directed to use Assume Role.
> 
> Thank you

@Lurchicus I'm afraid, no. As a workaround, your security team could provide you an API endpoint internal to your organization to fetch credentials which you could use in the service client constructor overload to specify credentials.

**Comment by Lurchicus** [comment]
Hi Ashish,

I am already on my organizations internal network (via VPN when debugging from my laptop). The Windows Server is part of our internal network as well. 

It looks like the security restrictions I've been told to comply with will prevent me from being able to access AWS S3 or AWS S3 Glacier from our Windows Servers going forward.  

It looks like our automated Windows archiving tools are getting an early end of life, unless I can get a security exception to go back to using an encrypted shared credentials file. 

Thank you for your assistance

**Comment by Lurchicus** [comment]
Leaving this open for one more round.
