### ISSUE TITLE
Document size calculation for DynamoDb

### ISSUE THREAD

**Issue by hlesesne** [aws/aws-sdk-net#191]
Can someone point me to an explanation of exactly how document size is determined for DynamoDB?

In addition, it would be a great feature if Amazon.DyanmoDBv2.DocumentModel.Document could provide a property, or an extension method, that could do this calculation - allow us to determine whether or not the payload needs to be S3'd. If I fully understood the calculation, I would be happy to take a shot at a PR for this.

Thanks for your help and a terrific project.

**Comment by PavelSafronov** [comment]
The [Limits](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html) page of the DynamoDB Developer Guide has information about this logic.
