### ISSUE TITLE
AWSSDK.Extensions.NETCore.Setup doesn't work correctly

### ISSUE THREAD

**Issue by bwn-z** [aws/aws-sdk-net#1910]
## The Question
Hi. Previously. I worked with test console application when I tried to create an integration to the Minio server. It was ok. Now I try to create the integration to the Minio at ASP.NET Core. I have the problem of a dependency injection.
I found this code from amazon.docs:
```
var awsOptions = configuration.GetAWSOptions(nameof(MinioOptions));
awsOptions.Credentials = new BasicAWSCredentials("my-access-key", "my-secret-key");
services.AddDefaultAWSOptions(awsOptions);
services.AddAWSService<IAmazonS3>();
```
Then I worked with IAmazonS3 and used the PutObjectAsync method. I got an error:
```
  "detail": "Error making request with Error Code MethodNotAllowed and Http Status Code MethodNotAllowed. No further error information was returned by the service.",
  "source": "AWSSDK.Core",
  "innerDetail": "Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown."
```
then I found the source of issue: `ForcePathStyle = false`. I changed the value (from `false` to `true`) while debugging via the VisualStudio Watcher. And I respond the OK result. I think that problem is `ForcePathStyle` because I work with objects as paths. Example: `https://myminio.com/mybucket/someGuid/v0/someObject`

### Environment

* SDK Version: 
```
<PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.7.1" />
<PackageReference Include="AWSSDK.S3" Version="3.7.1.30" />
```
* OS Info: `Windows 10`
* Build Environment: `Visual Studio`
* Targeted .NET Platform: `netcoreapp3.1`

---

1. How can I assign the `ForcePathStyle = true` to `awsOptions`?(((
2. Or how can I register correctly amazonClient? When I created directly an instance AmazonS3Client. It worked correctly.
3. Can I join correctly` IAmazonS3` to our http pool? Is it possible? I'm worried about performance of amazon client. At the begging I wanted to use PreSigned methods and httpClient with `GetAsync/SendAsync` method, but the PreSigned methods are not flexible.

**Comment by ashishdhingra** [comment]
Hi @bwn-z,

Good morning.

Thanks for posting guidance question. Just to accurately reproduce the issue, could you please share your `appSettings.json` (with sensitive information removed)? In the meanwhile, I will try to research on it.

Thanks,
Ashish

**Comment by bwn-z** [comment]
Good evening)

Yeah, my actual `appsetting.json` is:
```
"MinioOptions": {
    "BucketName": "my-bucket-name",
    "AcccessKey": "my-access-key",
    "ServiceURL": "https://myminio.com",
    "ForcePathStyle": true,
    "SecretKey": "my-secret-key",
    "MinioConfig": {
      "ServiceURL": "https://myminio.com",
      "ForcePathStyle": true
    }
```
don't be alarmed if it seems strange.
At the beginning I had the first version of setting:
```
"MinioOptions": {
    "BucketName": "my-bucket-name",
    "AcccessKey": "my-access-key",
    "SecretKey": "my-secret-key",
    "MinioConfig": {
      "ServiceURL": "https://myminio.com",
      "ForcePathStyle": true
    }
``` 
to MinioOptions instance, then I created directly an instance of AmazonS3Client.
Startup.cs contained: `Configuration.GetSection(options => nameof(MinioOptions).Bind(options));`
Then I got the option from DI:
```
public class MinioServiceClient : IMinioServiceClient
{
   private readonly string _bucketName;
   private readonly IAmazonS3 _client;
   public MinioServiceClient(IOptions<MinioOptions> options)
   {
     _client = new AmazonS3Client(_options.Value.AccessKey, _options.Value.SecretKey, _options.Value.MinioConfig);
     _bucketName = options.Value.BucketName;
   }
   
   public async Task<string> CreateObjectAsync(...)
   {
     ...
     var result = await _client.PutObjectAsync(new PutObjectRequest { ... }, default);
     ...
   }
}
```
It worked correctly. Then I tried to use that:
appsettings.json
```
"MinioOptions": {
    "BucketName": "my-bucket-name",
    "AcccessKey": "my-access-key",
    "ServiceURL": "https://myminio.com",
    "ForcePathStyle": true,
    "SecretKey": "my-secret-key",
    "MinioConfig": {
      "ServiceURL": "https://myminio.com",
      "ForcePathStyle": true
    }
```
Startup.cs: 
```
var awsOptions = configuration.GetAWSOptions(nameof(MinioOptions));
awsOptions.Credentials = new BasicAWSCredentials("my-access-key", "my-secret-key");
services.AddDefaultAWSOptions(awsOptions);
services.AddAWSService<IAmazonS3>();
```
MinioServiceClient:
```
{
   private readonly string _bucketName;
   private readonly IAmazonS3 _client;
   public MinioServiceClient(IAmazonS3 client, IOptions<MinioOptions> options)
   {
     _client = client;
     _bucketName = options.Value.BucketName;
   }
   
   public async Task<string> CreateObjectAsync(...)
   {
     ...
     var result = await _client.PutObjectAsync(new PutObjectRequest { ... }, default);
     ...
   }
}
```
It doesn't work. I received th error: 
```
  "detail": "Error making request with Error Code MethodNotAllowed and Http Status Code MethodNotAllowed. No further error information was returned by the service.",
  "source": "AWSSDK.Core",
  "innerDetail": "Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown."
```
At VistualStudio watcher I found that a property `ForcePathStyle = false`

**Comment by ashishdhingra** [comment]
Hi @bwn-z,

Good afternoon.

Looking at the code base for `AWSSDK.Extensions.NETCore.Setup`:
- [IConfiguration.GetAWSOptions(string configSection)](https://github.com/aws/aws-sdk-net/blob/cc3cdef441cb5e7923bf33c665fcc23f73e96390/extensions/src/AWSSDK.Extensions.NETCore.Setup/ConfigurationExtensions.cs#L57) return object of type [AWSOptions](https://github.com/aws/aws-sdk-net/blob/master/extensions/src/AWSSDK.Extensions.NETCore.Setup/AWSOptions.cs).
- [AWSOptions](https://github.com/aws/aws-sdk-net/blob/master/extensions/src/AWSSDK.Extensions.NETCore.Setup/AWSOptions.cs) class has properties `Profile`, `ProfileLocation`, `Region`, `Credentials` and `DefaultClientConfig`. Kindly note that there is no `ForcePathStyle` property (not even in `Default ClientConfig` type, which inherits from [ClientConfig](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/ClientConfig.cs)).
- [IConfiguration.GetAWSOptions(string configSection)](https://github.com/aws/aws-sdk-net/blob/cc3cdef441cb5e7923bf33c665fcc23f73e96390/extensions/src/AWSSDK.Extensions.NETCore.Setup/ConfigurationExtensions.cs#L57) loads the specified config section and populates the properties, including `DefaultClientConfig` (you may check the code for more details).
- Since `DefaultClientConfig` does not have the `ForcePathStyle` property, it is not set while creating service client (you would notice that the `ServiceURL` property is correctly set).

Also, the [AmazonS3Config](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/S3/Custom/AmazonS3Config.cs) has customizations which includes `ForcePathStyle` property. Since the `ClientConfig` class is generic for all SDK supported service clients and not tied to only S3 client, this is not a bug.

Hope this provides guidance.

Thanks,
Ashish

**Comment by bwn-z** [comment]
Hello @ashishdhingra 

A best way for me is not using `AWSSDK.Extensions.NETCore.Setup` and using the code at Startup.cs:
```
var options = _serviceProvider.GetRequredServices<IOptions<MinioOptions>>().Value;
services.AddSingleton<IAmazonS3>(x => new AmazonS3Client(_options.AccessKey, _options.SecretKey, _options.MinioConfig));
```
I've previously used this code. It worked correctly too. 
Can you please answer these questions?
1. Is it a good way for registering service? Or maybe do you know a better way then this for registering `AmazonS3Client` service with `ForcePathStyle`?
2. It's strange. Why do we have a universal library if each of AWS services has a custom settings (example: `ForcePathStyle` for `IAmazonS3`)?
3. Can I join correctly `IAmazonS3` to our http pool? Is it possible? I'm worried about performance of amazon client. At the begging I wanted to use PreSigned methods and httpClient with `GetAsync/SendAsync` method, but the PreSigned methods are not flexible?

**Comment by ashishdhingra** [comment]
> 2\. ForcePathStyle

Hi @bwn-z,

Here are my inputs:
1. I guess you would be using minio setup only for development purposes and would point to Amazon S3 in production. So the better code would be:
```C#
services
    .AddSingleton<IAmazonS3>(p => {
        var config = new AmazonS3Config
        {
            RegionEndpoint = RegionEndpoint.USWest2,  // Set your region endpoint here.
        };
        if (p.GetService<IHostEnvironment>().IsDevelopment())
        {
            config.ForcePathStyle = true;
            config.ServiceURL = _options.ServiceURL;  // set the service URL here.
        }
        return new AmazonS3Client(_options.AccessKey, _options.SecretKey, config); // You might use _options.MinioConfig here.
    });
```
(Kindly note that the above code is only provided for guidance and should be thoroughly tested.)

2. `AWSSDK.Extensions.NETCore.Setup` is generic package for all the services, not just S3 service. Service specific custom properties should be set manually. Services are added using the interface for DI process (e.g. `IAmazonS3`). Kindly note that concrete classes that depend on interface could add additional properties.
3. I'm not sure what is the question here. Could you please elaborate with example? You should be able to use singleton S3 client normally without any performance implications. Presigned URLs are generated using [GetPresignedUrlRequest](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/S3/Custom/Model/GetPreSignedUrlRequest.cs) with specific properties set.

Hope this provides necessary guidance and let me know if this issue could be closed.

Thanks,
Ashish
