### ISSUE TITLE
WEBGL support for AWS

### ISSUE THREAD

**Issue by intrmasked** [aws/aws-sdk-net#1914]
Hi,
was wondering when will you allow support to webgl and make the installation process for the plugins to unity easier as they are a pain to install

**Comment by ashishdhingra** [comment]
@intrmasked Are you referring to general question on WebGL support on AWS? If yes, please review the blog post [Serving compressed WebGL websites using Amazon CloudFront, Amazon S3 and AWS Lambda](https://aws.amazon.com/blogs/networking-and-content-delivery/serving-compressed-webgl-websites-using-amazon-cloudfront-amazon-s3-and-aws-lambda/).
