### ISSUE TITLE
pInvokeStackImbalance with aws-crt-http and S3 GetObject() and multiregion access point

### ISSUE THREAD

**Issue by superdex** [aws/aws-sdk-net#1918]
Upgraded our projects from 3.3 to sdk 3.7.124 to take advantage of the multiregion access points, and we're getting a few issues. First, using NuGet to install the dependency AWSSDK.Extensions.CrtIntegration, we get errors with installing CMake 3.5.2 in order to pull in the aws-crt dependencies. 

So I included the aws-crt-* assemblies from the 3.7.124 zip file, and included the S3 and CrtIntegration assemblies from the zip to keep things together. 

When I execute my GetObject:

		GetObjectRequest request = new GetObjectRequest
			{
				BucketName = Bucket,
				Key = objectname
			};

			try
			{
				GetObjectResponse response = S3client.GetObject(request);

				using (Stream responseStream = response.ResponseStream)
				using (MemoryStream mem = new MemoryStream())
				{
					lastModified = response.LastModified;
					responseStream.CopyTo(mem);
					result = mem.GetBuffer();
				}
			}
			catch (Exception e)
			{
			}

I get a pInvokeStackImbalance error:

Managed Debugging Assistant 'PInvokeStackImbalance' 
  Message=Managed Debugging Assistant 'PInvokeStackImbalance' : 'A call to PInvoke function 'aws-crt!Aws.Crt.NativeException+SetExceptionCallback::Invoke' has unbalanced the stack. This is likely because the managed PInvoke signature does not match the unmanaged target signature. Check that the calling convention and parameters of the PInvoke signature match the target unmanaged signature.'

It appears the CrtIntegration wrapper isn't playing nicely with the aws-crt assemblies. Help!

This is all inside an asp.net web application:
.NET 4.6.2
AWSSDK.S3.dll 3.7.3.4
AWSSDK.Extensions.CrtIntegration.dll 3.7.0.0
aws-crt.dll 0.3.11.0
aws-crt-http.dll 0.3.11.0
aws-crt-auth.dll 0.3.11.0

I hope I'm just doing something dumb, but maybe not...

---

This is a :bug: bug-report

**Comment by ashovlin** [comment]
Thanks for the snippet. Still investigating, but I am able to reproduce consistently (even with package references) with `<PlatformTarget>x86</PlatformTarget>` Is that your case too?

**Comment by superdex** [comment]
Correct, I’ve even tried newer framework versions, including 4.7.2 and 4.8
with no luck.

Thanks,

**Comment by ashovlin** [comment]
Quick update: fix is is progress over in https://github.com/awslabs/aws-crt-dotnet/pull/72

Once that is merged and released, we'll also have to increment the dependency and version of AWSSDK.Extensions.CrtIntegration in this repository.

**Comment by superdex** [comment]
Awesome, thank  you so much!

**Comment by ashovlin** [comment]
[v3.7.0.1 of AWSSDKExtensions.CrtIntegration](https://www.nuget.org/packages/AWSSDK.Extensions.CrtIntegration/3.7.0.1) was just published, which depends on [v0.3.12 of the CRT packages](https://github.com/awslabs/aws-crt-dotnet/releases/tag/v0.3.12) with this fix.

My test with similar reproduction code looked good, but let us know how your MRAP testing goes.
