### ISSUE TITLE
System.Exception: The semaphore has been disposed.

### ISSUE THREAD

**Issue by sbs-surendhar-kabilan** [aws/aws-sdk-net#1919]
Issue looks like AWSSDK.S3 while error message thrown like semaphore has been disposed in UploadPartAsync method in AWS

Android SDK version 3.1.9
Package version :
AWSSDK.Core : 3.7.0.34
AWSSDK.S3 : 3.7.1.4

Issues logged in Mobile version:  9,10,11

StackTrace:

"stackTrace": "  at System.Threading.SemaphoreSlim.CheckDispose () [0x00013] in <7f881f2be3b9423dab560b1304a2265b>:0 \n  
at System.Threading.SemaphoreSlim.Release (System.Int32 releaseCount) [0x00000] in <7f881f2be3b9423dab560b1304a2265b>:0 \n  
at System.Threading.SemaphoreSlim.Release () [0x00000] in <7f881f2be3b9423dab560b1304a2265b>:0 \n  
at Amazon.S3.Transfer.Internal.MultipartUploadCommand.UploadPartAsync (Amazon.S3.Model.UploadPartRequest uploadRequest, System.Threading.CancellationTokenSource internalCts, System.Threading.SemaphoreSlim asyncThrottler) [0x000a7] in <6eb3c0ec918b4de4a8a187915040d330>:0 ",

**Comment by ashishdhingra** [comment]
Hi @sbs-surendhar-kabilan,

Could you please provide more details along with the sample code for consistent reproduction, in the below format?



## Expected Behavior



## Current Behavior






## Possible Solution



## Steps to Reproduce (for bugs)





## Context



## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

Thanks,
Ashish

**Comment by sbs-surendhar-kabilan** [comment]
Current Behaviour: When uploading videos, this mentioned error was  logging from AWSSDK.S3 package and it was catched in our side.
Expected Behaviour:  When uploading videos, expected to be working fine and this mentioned error should not be logged from AWSSDK.S3 package.

Issues not in our side please see the stack trace 

 Amazon.S3.Transfer.Internal.MultipartUploadCommand.UploadPartAsync (Amazon.S3.Model.UploadPartRequest uploadRequest, System.Threading.CancellationTokenSource internalCts, System.Threading.SemaphoreSlim asyncThrottler)


.Net SDK version 5.0.301
Visual studio Version 16.10.3
.Net standard 2.O

**Comment by ashishdhingra** [comment]
@sbs-surendhar-kabilan Could oh d you please share the following to reproduce the issue:
- Sample code
- Video size 
- Full stack trace

**Comment by sbs-surendhar-kabilan** [comment]
Video Size : Don't know which video size these may occur.

Full-stack trace

"at System.Threading.SemaphoreSlim.CheckDispose () [0x00013] in <7f881f2be3b9423dab560b1304a2265b>:0 \n  at 
System.Threading.SemaphoreSlim.Release (System.Int32 releaseCount) [0x00000] in <7f881f2be3b9423dab560b1304a2265b>:0 \n  
at System.Threading.SemaphoreSlim.Release () [0x00000] in <7f881f2be3b9423dab560b1304a2265b>:0 \n  
at Amazon.S3.Transfer.Internal.MultipartUploadCommand.UploadPartAsync (Amazon.S3.Model.UploadPartRequest uploadRequest, System.Threading.CancellationTokenSource internalCts, System.Threading.SemaphoreSlim asyncThrottler) [0x000a7] in <6eb3c0ec918b4de4a8a187915040d330>:0 ",

Sample code: We are uploading videos while calling AmazonS3Client on our side only issue may occur in the AWSSDK.S3 package. Please see these link

https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/S3/Custom/Transfer/Internal/_async/MultipartUploadCommand.async.cs

**Comment by ashishdhingra** [comment]
> Video Size : Don't know which video size these may occur.
> 
> 
> 
> Full-stack trace
> 
> 
> 
> "at System.Threading.SemaphoreSlim.CheckDispose () [0x00013] in <7f881f2be3b9423dab560b1304a2265b>:0 \n  at 
> 
> System.Threading.SemaphoreSlim.Release (System.Int32 releaseCount) [0x00000] in <7f881f2be3b9423dab560b1304a2265b>:0 \n  
> 
> at System.Threading.SemaphoreSlim.Release () [0x00000] in <7f881f2be3b9423dab560b1304a2265b>:0 \n  
> 
> at Amazon.S3.Transfer.Internal.MultipartUploadCommand.UploadPartAsync (Amazon.S3.Model.UploadPartRequest uploadRequest, System.Threading.CancellationTokenSource internalCts, System.Threading.SemaphoreSlim asyncThrottler) [0x000a7] in <6eb3c0ec918b4de4a8a187915040d330>:0 ",
> 
> 
> 
> Sample code: We are uploading videos while calling AmazonS3Client on our side only issue may occur in the AWSSDK.S3 package. Please see these link
> 
> 
> 
> https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/S3/Custom/Transfer/Internal/_async/MultipartUploadCommand.async.cs

@sbs-surendhar-kabilan This doesn't appear to be the full stack trace. I will try uploading the video file to reproduce issue at my end. Without sample code and full stack trace, the issue might not be fully investigated.

**Comment by sbs-surendhar-kabilan** [comment]
Sample code:

SessionAWSCredentials sessionAwsCredentials = new SessionAWSCredentials(
                    response.MultiPartUploadInfo.AccessKey, response.MultiPartUploadInfo.SecretKey, response.MultiPartUploadInfo.SessionToken);

                AmazonS3Client s3Client = new AmazonS3Client(sessionAwsCredentials, RegionEndpoint.EUWest1);

                TransferUtility transferUtility = new TransferUtility(s3Client);
                TransferUtilityUploadRequest transferUtilityRequest = new TransferUtilityUploadRequest
                {
                    BucketName = response.MultiPartUploadInfo.Bucket,
                    Key = response.MultiPartUploadInfo.Key,
                    FilePath = unsavedmedia.LocalPath,
                    StorageClass = S3StorageClass.Standard,
                    PartSize = response.MultiPartUploadInfo.PartSize,
                    CannedACL = S3CannedACL.Private,
                };

                foreach (KeyValuePair<string, dynamic> header in response.AWSHeaders)
                    transferUtilityRequest.Metadata.Add(header.Key, header.Value);

                await transferUtility.UploadAsync(transferUtilityRequest).ConfigureAwait(false);



Full Stacktrace:

innerExceptions": [
      {
        "type": "System.AggregateException",
        "message": "A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (The semaphore has been disposed.)",
        "innerExceptions": [
          {
            "type": "System.ObjectDisposedException",
            "message": "The semaphore has been disposed.",
            "stackTrace": "  at System.Threading.SemaphoreSlim.CheckDispose () [0x00013] in <7f881f2be3b9423dab560b1304a2265b>:0 \n  at System.Threading.SemaphoreSlim.Release (System.Int32 releaseCount) [0x00000] in <7f881f2be3b9423dab560b1304a2265b>:0 \n  at System.Threading.SemaphoreSlim.Release () [0x00000] in <7f881f2be3b9423dab560b1304a2265b>:0 \n  at Amazon.S3.Transfer.Internal.MultipartUploadCommand.UploadPartAsync (Amazon.S3.Model.UploadPartRequest uploadRequest, System.Threading.CancellationTokenSource internalCts, System.Threading.SemaphoreSlim asyncThrottler) [0x000a7] in <6eb3c0ec918b4de4a8a187915040d330>:0 ",
            "wrapperSdkName": "appcenter.xamarin"
          }
        ],
        "wrapperSdkName": "appcenter.xamarin"
properties": {
    "message:": "TaskSchedulerOnUnobservedTaskException",
    "innerException:": "System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception p",
  },

**Comment by ashishdhingra** [comment]
Hi @sbs-surendhar-kabilan,

Please refer the following articles on guidance for handling the mentioned error:
- https://stackoverflow.com/questions/7883052/a-tasks-exceptions-were-not-observed-either-by-waiting-on-the-task-or-accessi
- https://social.msdn.microsoft.com/Forums/en-US/11afc239-3f2d-4289-9141-f6300c63a5cc/a-tasks-exceptions-were-not-observed?forum=parallelextensions
- https://forums.asp.net/t/1918511.aspx?A+Task+s+exception+s+were+not+observed+either+by+Waiting+on+the+Task+or+accessing+its+Exception+property

Looks like the exception is thrown in your code which is not handled and getting this error. You would need to refactor your code to avoid the above scenario and log the actual exception thrown by your code.

Hope this helps.

Thanks,
Ashish
