### ISSUE TITLE
Remove internal modifier from helper methods in RdsDataService Field class

### ISSUE THREAD

**Issue by Lanayx** [aws/aws-sdk-net#1924]
## Describe the Feature
[Right now](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/RDSDataService/Generated/Model/Field.cs#L93) IsSet***Value helper methods are internal I propose removing this modifier

### Is your Feature Request related to a problem?
Sometimes there is no column metatada, but only fields (when data comes in GeneratedFields), so it's impossible to identify which property was set without calling those methods, right now I'm using this code to return the typed value

```fsharp

let isSetBoolean = lazy typeof<Field>.GetMethod("IsSetBooleanValue", BindingFlags.Instance ||| BindingFlags.NonPublic)
let isSetLong = lazy typeof<Field>.GetMethod("IsSetLongValue", BindingFlags.Instance ||| BindingFlags.NonPublic)
let isSetDouble = lazy typeof<Field>.GetMethod("IsSetDoubleValue", BindingFlags.Instance ||| BindingFlags.NonPublic)

let field =
    if data.GeneratedFields.Count > 0 then
        data.GeneratedFields.[0]
    else
       failwith "There are no generated fields found"
if field.StringValue |> isNull |> not then
    field.StringValue |> box :?> 'T
elif field.ArrayValue |> isNull |> not then
    field.ArrayValue |> box :?> 'T
elif field.BlobValue |> isNull |> not then
    field.BlobValue |> box :?> 'T
elif isSetLong.Value.Invoke(field, null) :?> bool then
    field.LongValue |> box :?> 'T
elif isSetBoolean.Value.Invoke(field, null) :?> bool then
    field.BooleanValue |> box :?> 'T
elif isSetDouble.Value.Invoke(field, null) :?> bool then
    field.DoubleValue |> box :?> 'T
else
    failwith "There are no generated fields found"
```

## Proposed Solution
Without internal attributes it would be easy to call methods without using reflection. This is something that protobuf generator does - it generates public ShouldSerialize*** methods for example

```csharp
[global::ProtoBuf.ProtoMember(8, Name = @"marker")]
[global::System.ComponentModel.DefaultValue(false)]
public bool Marker
{
    get => __pbn__Marker ?? false;
    set => __pbn__Marker = value;
}
public bool ShouldSerializeMarker() => __pbn__Marker != null;
public void ResetMarker() => __pbn__Marker = null;
private bool? __pbn__Marker;
```

### Describe alternatives you've considered
Alternative is not to create a Field wrapper, or continue using reflection, but it's inconvenient

## Additional Context
My wrapper library is here https://github.com/Lanayx/AuroraDataApiClient

### Environment

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change  

---

This is a :rocket: Feature Request

**Comment by ashishdhingra** [comment]
Hi @Lanayx,

Good morning.

Lookin at the example helper method that you mentioned in the issue, looks like these are auto-generated from service models. I'm not sure if it would be feasible to remove the internal modifier on these helper methods, but team would have a look and provide the inputs accordingly.

Thanks,
Ashish
