### ISSUE TITLE
Unable to modify SNS message attributes using `BeforeRequestEvent`

### ISSUE THREAD

**Issue by aschey** [aws/aws-sdk-net#1925]
## Description
We would like to use the `BeforeRequestEvent` delegate on the SNS client to automatically add some message attributes before every SNS message is sent. After trying this, I noticed that the attributes never made it to the published message even though the event fired correctly. After stepping through the code, I believe this is because [this code](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/SimpleNotificationService/Generated/Model/Internal/MarshallTransformations/PublishRequestMarshaller.cs#L65) in the request marshaller is what sets the attributes as request parameters, but that happens before the `BeforeRequestEvent` is triggered [here](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/AmazonServiceClient.cs#L353)

## Reproduction Steps
1. Create an SNS client with a `BeforeRequestEvent` handler attached.
2. Set some message attributes in the handler.
3. Publish a message and notice that no attributes are sent.

Example Code:
```
var snsClient = new AmazonSimpleNotificationServiceClient();
snsClient.BeforeRequestEvent += (sender, args) => BeforeRequestEvent(args);

internal static void BeforeRequestEvent(RequestEventArgs args)
{
    if (args is WebServiceRequestEventArgs { Request: PublishRequest publishRequest })
    {
        publishRequest.MessageAttributes.Add("test", 
			new MessageAttributeValue() { StringValue = "value", DataType = "String" });
    }
}
```

### Environment
* SDK Version: `AWSSDK.Core` - 3.7.3.15
* Package Version: `AWSSDK.SimpleNotificationService` - 3.7.2.46
* OS Info: Windows 10
* Build Environment: Visual Studio
* Targeted .NET Platform:  .NET Core 3.1

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @aschey,

Good morning.

Looking at the design of the SDK, all request marshaller(s) are invoked to construct the `IRequest` object, before it gets a chance to flow through the SDK's request pipeline. Looking at the logic (and also as confirmed by you), [AmazonServiceClient.BeforeRequestEvent](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/Runtime/EServiceBeforeRequestEvent.html) might not be the good place to add new message attributes since the `PublishRequest` is already transformed to `Amazon.Runtime.Internal.IRequest`. Hence, even though you might have access to original `PublishRequest` request, modifying any attribute/collection would not affect the transformed request.

Kindly note that this is not just with the `AmazonSimpleNotificationServiceClient`, it's with other clients as well (even though some clients like S3 have custom implementation as an exception).

Based on above explanation, I do not see if this is a bug. Hope this helps.

Thanks,
Ashish

**Comment by aschey** [comment]
@ashishdhingra Thanks for the quick response. Is there another recommended way we could modify the request before sending it if this is not the suggested way to do so? Our use case is that we need to propagate OpenID claims attached to the currently authenticated user before sending each message. We would like to avoid subclassing the SNS client and overriding the `Publish` method as that gets tedious quickly.

**Comment by ashishdhingra** [comment]
> @ashishdhingra Thanks for the quick response. Is there another recommended way we could modify the request before sending it if this is not the suggested way to do so? Our use case is that we need to propagate OpenID claims attached to the currently authenticated user before sending each message. We would like to avoid subclassing the SNS client and overriding the `Publish` method as that gets tedious quickly.

@aschey Quick question, how are the OpenID claims available? Are you executing the logic as part of ASP.NET application? In that case, the OpenID claims should be available in the current user's session and could be added in the `PublishRequest` directly?

**Comment by aschey** [comment]
> > @ashishdhingra Thanks for the quick response. Is there another recommended way we could modify the request before sending it if this is not the suggested way to do so? Our use case is that we need to propagate OpenID claims attached to the currently authenticated user before sending each message. We would like to avoid subclassing the SNS client and overriding the `Publish` method as that gets tedious quickly.
> 
> @aschey Quick question, how are the OpenID claims available? Are you executing the logic as part of ASP.NET application? In that case, the OpenID claims should be available in the current user's session and could be added in the `PublishRequest` directly?

Yes, that's correct. We can add them in the publish request directly but we're trying to encapsulate this logic in a library or some kind of dependency injection setup so developers for each service using SNS don't have to remember to do that each time and the library can handle that for them.

**Comment by aschey** [comment]
@ashishdhingra that could work, appreciate the help! I'll go ahead and close this since it seems like there's no further action to be taken.
