### ISSUE TITLE
SQS client never throws MessageNotInflightException/ReceiptHandleIsInvalidException when ChangeMessageVisibility is called

### ISSUE THREAD

**Issue by danports** [aws/aws-sdk-net#1927]
Instead of throwing `MessageNotInflightException` or `ReceiptHandleIsInvalidException` when `ChangeMessageVisibility` returns an error, the client just throws a generic `AmazonSQSException` with a message like this:

```
Value AQEBdzu6... for parameter ReceiptHandle is invalid. Reason: Message does not exist or is not available for visibility timeout change.
```

I'm guessing this might be due to a behavior change in the underlying SQS service, since it seems like the response unmarshaller tries to handle this case:

https://github.com/aws/aws-sdk-net/blob/3f98219b4c79916f3539a4ac64b9acd4db9d8239/sdk/src/Services/SQS/Generated/Model/Internal/MarshallTransformations/ChangeMessageVisibilityResponseUnmarshaller.cs#L110-L117

**Comment by danports** [comment]
Sure, I can do that - should just be a matter of sending a message, deleting it, and then trying to change the visibility timeout on it.

**Comment by aaoswal** [comment]
Hi @danports,
Just wanted to check-in to see if you could please provide the sample code solution to reproduce and analyze the issue further?

**Comment by KevinOBrienCimpress** [comment]
Hi, I'm encountering this same problem.

Here is some sample code that should be able to reproduce the issue:

```
using Amazon.SQS;
using Amazon.SQS.Model;

var queueUrl = "QUEUE_URL";

var sqs = new AmazonSQSClient();

await sqs.SendMessageAsync(queueUrl, "test12345");

var receiveMessage = await sqs.ReceiveMessageAsync(queueUrl);

var message = receiveMessage.Messages.FirstOrDefault();

if (message is null)
{
    Console.WriteLine("No message received!");
    return;
}

await sqs.DeleteMessageAsync(queueUrl, message.ReceiptHandle);

try
{
    await sqs.ChangeMessageVisibilityAsync(queueUrl, message.ReceiptHandle, 60);
}
catch (MessageNotInflightException)
{
    Console.WriteLine("Message not in flight exception");
}
catch (AmazonSQSException)
{
    Console.WriteLine("Amazon SQS Exception");
}
catch (Exception)
{
    Console.WriteLine("Other exception");
}
```

**Comment by ctolkien** [comment]
Pretty sure we are hitting this issue as well.....
