### ISSUE TITLE
What is the reason for keeping HttpClientCacheSize to number Environment.ProcessorCount on Linux

### ISSUE THREAD

**Issue by madhub** [aws/aws-sdk-net#1929]
## The Question
Currently we are investigating slowness of S3 access on **Linux deployment**, upon investigation we found number of cache HttpClient varies between Windows & Linux    [relevant section of the code is ClientConfig.cs](https://github.com/aws/aws-sdk-net/blob/b5d440ba2064956c32a0ced3804b34d151eb3123/sdk/src/Core/Amazon.Runtime/ClientConfig.cs#L732)

What is the reason of having different number for cached HttpClients ?
From .NET Core 2.1 onwards HttpClient uses SocketsHttpHandler on both Windows & Linux  and their should not be any behavior changes. 

Here is the sample scenario to show the difference
On 10 CPU systems make 10 S3 request to **same object** on the **same bucket.**

- **On Windows** - First request takes time, and all subsequent request are fast
- **On Linux** - All request request takes equal amount of time which includes connection establish cost 

So should we set the `AmazonS3Config.HttpClientCacheSize` to 1 on Linux ? , any recommendation ?

### Environment

* SDK Version: 3.7.3.12
* Package Version: Awssdk.s3 ver: 3.7.3.12, Awssdk.core ver:3.7.3.19
* OS Info: Windows 10 , Centos 8 
* Build Environment :Terminal `dotnet` 
* Targeted .NET Platform:  .NET 3.1

---

This is a :question: general question

**Comment by ozziepeeps** [comment]
We got bitten by this exact issue, combined with our use of the new `DOTNET_PROCESSOR_COUNT` environment variable in NET6 which exacerbated things. We can confirm that setting `HttpClientCacheSize` to `1` improved performance in our setup.

It would be good to get this fixed in the SDK @normj.

**Comment by rsaunderson88-kw** [comment]
I was also just bit by this when testing on Linux. Requests under 1 MB went from taking almost 200 ms to read the get the object *and* another 200 to copy the stream to 50ms round trip. This is a pretty large difference even for a simple example.

**Comment by danielmarbach** [comment]
Why hasn't this value been streamlined? I mean we are now alread in .NET 8 preview mode, which will be the next LTS and all of what has been written here in this issue is valid for multiple years now.

**Comment by danielmarbach** [comment]
See https://github.com/aws/aws-sdk-net/pull/2549

**Comment by ashishdhingra** [comment]
Closing issue since PR https://github.com/aws/aws-sdk-net/pull/2549 is merged and released per https://github.com/aws/aws-sdk-net/pull/2549#issuecomment-1500486145.
