### ISSUE TITLE
VisualStudio CloudFormation template editor missing AWS parameter List types

### ISSUE THREAD

**Issue by sliedig** [aws/aws-sdk-net#193]
Hello,

I'm getting a validation error when trying to add AWS parameter List types as documented here http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html

![image](https://cloud.githubusercontent.com/assets/597073/6955331/8f755f50-d90e-11e4-98a0-40dbe49ecebd.png)

Regards,

Steve

**Comment by normj** [comment]
Thanks for pointing this out. Unfortunately this will take a little more effort then just updating our schema. I have put the fix in our backlog and will updated here when I have a better idea when the fix will be available.

**Comment by jimfl** [comment]
Since this is not directly SDK related, I have moved the item to our internal backlog.
