### ISSUE TITLE
How to fetch whole aggregates when using DynamoDBContext?

### ISSUE THREAD

**Issue by Kralizek** [aws/aws-sdk-net#1938]
Following several best practices, I've designed my application around a single DynamoDB table that uses the two keys and different secondary indexes to return different parts of the application data.

In a case, I have an aggregate root that supports up to 5 different related types.

This is a quick layout of the table:

|Entity|Hash key|Sort key|
|-|-|-|
|Customer| `$"C:{customer.Id}"` | `"CUSTOMER"` |
|Treatment| `$"C:{customer.Id}"` | `$"T:{treatment.Id}"` |
|Therapist| `$"C:{customer.Id}"` | `$"TH:{therapist.Id}"` |
|Booking| `$"C:{customer.Id}"` | `$"B:{booking.Id}"` |
|Patient| `$"C:{customer.Id}"` | `$"P:{patient.Id}"` |

In some cases, I need to hydrate the whole aggregate and not just a portion of it.

What's the best way to do this in a single API call using the `DynamoDBContext`?

If I were using the low level API, I would simply do a Query with the key condition expression equal to `PK = :pk` but I'm not sure how to do the same using the context.

- the `CreateBatchGet` seems to be aimed at picking specific items by specifying their hash and sort key.
- the `QueryAsync` is strongly typed so it wouldn't suitable in this case, because rows would need to be serialized to different types

Right now this is what I'm doing, but it feels weird that I need to execute five queries to do what the lower client allows to do in one.

```csharp
var treatments = await context.QueryAsync<TestProviderTreatmentRow>($"{providerIdentifier:D}", QueryOperator.BeginsWith, new[] { "T:" }).GetRemainingAsync();

var therapists = await context.QueryAsync<TestProviderTherapistRow>($"{providerIdentifier:D}", QueryOperator.BeginsWith, new[] { "TH:" }).GetRemainingAsync();

var patients = await context.QueryAsync<TestProviderPatientRow>($"{providerIdentifier:D}", QueryOperator.BeginsWith, new[] { "P:" }).GetRemainingAsync();

var bookings = await context.QueryAsync<TestProviderBookingRow>($"{providerIdentifier:D}", QueryOperator.BeginsWith, new[] { "B:" }).GetRemainingAsync();

var provider = await context.LoadAsync<TestProviderRow>($"{providerIdentifier:D}", "CUSTOMER");
```

**Comment by aaoswal** [comment]
Hi @Kralizek,
Thank you for posting a guidance issue. A better way to get the desired outcome would be to use [`DynamoDBContext.FromQuery`](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DotNetDynamoDBContext.html#w20aac17c17c21c35c23).
This method can be defined using [`QueryOperationConfig`](https://docs.aws.amazon.com/sdkfornet1/latest/apidocs/html/T_Amazon_DynamoDBv2_DocumentModel_QueryOperationConfig.htm) which would allow you to set filters and additional conditions along with the attributes that you need to fetch.
[Here](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBContext.QueryScan.html) is a good example of its use-case.

**Comment by Kralizek** [comment]
Hi @aaoswal I'll try implementing your suggestion as soon as possible.

**Comment by Kralizek** [comment]
@aaoswal 

Is this the intended way to use?

```csharp
My.TryGetAWSCredentials(PROFILE_NAME, out var credentials);
IAmazonDynamoDB client = new AmazonDynamoDBClient(credentials, RegionEndpoint.EUWest1);
IDynamoDBContext context = new Amazon.DynamoDBv2.DataModel.DynamoDBContext(client);

var items = await context.FromQueryAsync<TableRow>(new QueryOperationConfig
{
    Select = SelectValues.AllAttributes,
    KeyExpression = new Amazon.DynamoDBv2.DocumentModel.Expression
    {
        ExpressionStatement = "PK = :PK",
        ExpressionAttributeValues = new Dictionary<string, Amazon.DynamoDBv2.DocumentModel.DynamoDBEntry>
        {
            [":PK"] = new Primitive {Type = DynamoDBEntryType.String, Value = "C:501a73ae-8c20-40b1-910a-795143e4663e" }
        }
    }
}).GetRemainingAsync();

items.Dump();

[Amazon.DynamoDBv2.DataModel.DynamoDBTable("my-table")]
public class TableRow
{
    [DynamoDBHashKey] public string PK { get; set; }

    [DynamoDBRangeKey] public string SK { get; set; }
}
```

If so, I would still need to create a type that contains all attributes and then create a function that converts from `TableRow` to the different types of entities contained in the table.

A bit laborious but understandable.

**Comment by aaoswal** [comment]
Hi @Kralizek,
Yes that is the intended way to use `DynamoDBContext.FromQuery`. For your use case, you would need to map the attributes to the objects respectively but this approach would make a single API call using `DynamoDBContext`.
