### ISSUE TITLE
DynamoDb - Empty values handling

### ISSUE THREAD

**Issue by emanuel-v-r** [aws/aws-sdk-net#1942]
I am experiencing this issue where empty strings are being ignored by DynamoDb and when getting the data from there the property that was an empty string is not there anymore.
According to this news, https://aws.amazon.com/about-aws/whats-new/2020/05/amazon-dynamodb-now-supports-empty-values-for-non-key-string-and-binary-attributes-in-dynamodb-tables/ DynamoDB supports empty values starting from 2020.
Do I need to enable this feature via SDK somehow?
For the javascript library seems that there is a "convertEmptyValues" property in the settings https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_lib_dynamodb.html.
Does it exist anything similar in the dotnet SDK that I can enable?

Thank you.

**Comment by aaoswal** [comment]
Hi @emanuel-v-r,
Can you confirm that the attribute that is empty is [not used as a key attribute for a table or index](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_PutItem.html#:~:text=table%27s%20attribute%20definition.-,Empty%20String%20and%20Binary%20attribute%20values%20are%20allowed.%20Attribute%20values%20of%20type%20String%20and%20Binary%20must%20have%20a%20length%20greater%20than%20zero%20if%20the%20attribute%20is%20used%20as%20a%20key%20attribute%20for%20a%20table%20or%20index.,-For%20more%20information)?
If that is not the case, could you please provide a little more information about this issue:
- SDK Version used
- Sample Code for reproduction

**Comment by emanuel-v-r** [comment]
Hi  @aaoswal ,

Thanks for your help.
Yes, I can confirm that, this property is actually defined by our API caller.

* SDK Version: 3.7.1 (which is the latest)
* Sample code for reprodution here https://github.com/emanuel-v-r/DynamoDbSample

I've put a docker-compose file there in case you want to run local  dynamo (amazon/dynamodb-local:1.17.0 which is the latest), and inside the solution, you'll have a launchsettings file that allows you to switch between local dynamo and the real dynamo.

**Comment by aaoswal** [comment]
Hi @emanuel-v-r,
On deeper investigation, I found that the sample code threw [`ResourceNotFoundException`](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/DynamoDBv2/TResourceNotFoundException.html) as the table was still in the `creating` state and hence,  the API was not able to locate the created table.
A good solution to the problem you are facing would be to [wait for the table to be created](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/LowLevelDotNetTableOperationsExample.html#:~:text=private%20static%20void%20WaitUntilTableReady,exception.%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%20while%20(status%20!%3D%20%22ACTIVE%22)%3B%0A%20%20%20%20%20%20%20%20%7D) and call the other methods for operating on the table.

<details>

<summary>Example:</summary>

Function:

```
private static void WaitUntilTableReady(AmazonDynamoDBClient client, string tableName)
{
	string status = null;
	// Let us wait until table is created. Call DescribeTable.
	do
	{
		System.Threading.Thread.Sleep(5000); // Wait 5 seconds.
		try
		{
			var res = client.DescribeTableAsync(new DescribeTableRequest
			{
				TableName = tableName
			});
			Console.WriteLine("Table name: {0}, status: {1}",
							res.Result.Table.TableName,
							res.Result.Table.TableStatus);
			status = res.Result.Table.TableStatus;
		}
		catch (ResourceNotFoundException)
		{
			// DescribeTable is eventually consistent. So you might
			// get resource not found. So we handle the potential exception.
		}
	} while (status != "ACTIVE");
}
```

Function call:
```
WaitUntilTableReady(client, TableName);
await repo.Store(entity);
```

</details>

Using the function above you would be able to wait for the status of the table to be `Active` and then perform operations on it successfully.

Hope this helps!

**Comment by emanuel-v-r** [comment]
Hi @aaoswal ,

Thanks for your answer, I was not getting such error when using local Dynamo.
Anyway I don't create tables this way in real life code.
I am just creating this way in order to simplify and show you the issue, that is not related with that at all.
The issue is that if you run it (and use your code to wait for the table to be created, or simplify use a breakpoint), you will see that the empty string is not returned, and that's the issue that I need to solve.
Are you able to helping me out with that part?
Thank you

**Comment by emanuel-v-r** [comment]
@aaoswal Have you managed to replicate it?

**Comment by aaoswal** [comment]
Hi @emanuel-v-r,
I was able to replicate it and actively working on a resolution.

**Comment by emanuel-v-r** [comment]
> Hi @emanuel-v-r, I was able to reproduce the issue and actively working on a solution.

Thank you so much for your effort.
Should we add the label "bug" for this issue?
Do you have any idea when it's going to be available?

**Comment by aaoswal** [comment]
Hi @emanuel-v-r,
Sorry for the delay but on deeper investigation, I found that there is a flag [`Table.isEmptyStringEnabled`](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/DynamoDBv2/MTableLoadTableIDynamoDBStringBoolean.html) which controls whether empty values are allowed in DynamoDB Table or not. The flag is set to `false` by default.

You can find more information on the same in this previous issue #1787 

Example code snippet:
```
Table.LoadTable(dynamoDb, tableName, true);
```

This would definitely resolve your issue.

Thanks,
Anish.

**Comment by emanuel-v-r** [comment]
> Hi @emanuel-v-r, Sorry for the delay but on deeper investigation, I found that there is a flag [`Table.isEmptyStringEnabled`](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/DynamoDBv2/MTableLoadTableIDynamoDBStringBoolean.html) which controls whether empty values are allowed in DynamoDB Table or not. The flag is set to `false` by default.
> 
> You can find more information on the same in this previous issue #1787
> 
> Example code snippet:
> 
> ```
> Table.LoadTable(dynamoDb, tableName, true);
> ```
> 
> This would definitely resolve your issue.
> 
> Thanks, Anish.

Wow, I was looking in the wrong place all this time, once again @aaoswal thank you so much!
