### ISSUE TITLE
Unity 2021 + Amazon Kinesis VIDEO (AWS SDK for NET - v3.5?)

### ISSUE THREAD

**Issue by codexcandle** [aws/aws-sdk-net#1946]
Dear AWS / Unity ninjas,

I've been struggling in an attempt to integrate the following:

* Amazon Kinesis Video (for WebRTC) 
 https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/what-is-kvswebrtc.html
* Unity 2021

Specifically:
* was unable to find a sample project incorporating the 2 anywhere in the official docs (or online).
* was able to find one example, but in javascript - and thus, NOT specific to Unity:
https://blog.learningdollars.com/2021/05/09/aws-kinesis-video-stream-with-signed-url/
* many "current" 3rd-party examples still reference the old "(mobile) AWS SDK for Unity,"  
* using the "old" sdk, was able to get a basic AWS Cognito example working, but it relied on a class called "UnityInitiallizer."   Has this since been deprecated in the "AWS SDK for NET?" (which is said to include anything Unity should need?)
* what version of the new SDK should Unity developers be using as of today?   The NuGet package mngr implied 3.5 (.7?) was the current stable version?  although, am not using it as am specifically unpacking the DLLs from the mentioned "3.5" package as per the "special consideration" instructions link:
https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/unity-special.html

PLEASE HELP!
I can load in a DLL for "Kinsesis Video" from the AWS SDK for Net (v3.5) - into a C# class with a UnityEngine import.

However, am now STUCK, : (   How should I (we) proceed?

Any "specific" examples for us Unity folk (in 2021) would be immensely appreciated! : )

-hope to hear back (and thank you for reading)!

**Comment by codexcandle** [comment]
fwiw, discovered these 2 amazing vids:
#1:  https://www.youtube.com/watch?v=qzr57U2gWeE&t=912s
#2: https://www.youtube.com/watch?v=lzQ2rLqlqyk&t=28s

#1 - shows Unity (2021) + AWS SDK for Net (v2), and can confirm it works!
- just edit the AWS ids at the top of the "AuthorizationManger" class.
- don't forget! to ensure REGION ENDPOINT matches (Amazon.RegionEndpoint - line #14)
- for first run, use the right-hand side "sign up," and it should work!
- however, he comments that approach #2 should be prefered.

#2 - shows the same as above, but WITHOUT the AWS SDK entirely, and using Cognito Hosted UI to talk to "authorized gateway."

fwiw, and my current project needs - and rolling w/ option #1 for now.

but SUPER HELPFUL! to those also stuck. : )

**Comment by aaoswal** [comment]
Hi @codexcandle,
Does the above solution work for you or do you need additional help?
If it does work, can this issue be closed?

Thanks,
Anish.

**Comment by tyler-ursa** [comment]
@aaoswal  - while was never able to find docu on implementing "amazon kinesis video" into Unity, the above does illustrate the path to login to Cognito.   am using source code supplied with above links to "infer" subsequent implementation.  

cheers.

(close as you see fit.)
