### ISSUE TITLE
How to Get the No of Rows in DynamoDb

### ISSUE THREAD

**Issue by CLOUDFIRE91** [aws/aws-sdk-net#1948]
Hi All 

 I am new to DynamoDB. In My Project i have to get the Number of Rows Inserted in DynamoDB. 

Actually In LowLevelDyanmic DB example it shows how many  rows in  the column. But it displays only 6 hours back data(I got this from SO forum). So i want live rows count. I am working in HighLevelExample.cs.. So i need  source code in HighLevelExample.

Thanks in advance.

**Comment by aaoswal** [comment]
Hi @CLOUDFIRE91,
Getting the number of rows in DynamoDB would require using [Global Secondary Indexes](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-gsi-aggregation.html) and would require the the table to be scanned in its entirety. 

It is not be recommended to scan the entire table as it is highly exhaustive with increase in its size.
<details>

<summary><i>Here is a good example to get the total count:</i></summary>

```
  var client = new AmazonDynamoDBClient();

  var attributesToGet = new List<String> {<<attributes>>}; //primary-key would work best here but any other attribute would also do
  var response = client.ScanAsync(<<TableName>>, attributesToGet);
  Console.WriteLine(response.Result.Count);
```
</details>

References:
1. [AmazonDynamoDBClient.Scan()](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/DynamoDBv2/MDynamoDBScanAsyncStringList!String!CancellationToken.html)
2. [ScanResponse()](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/DynamoDBv2/TScanResponse.html)

**Comment by CLOUDFIRE91** [comment]
Thanks aaoswal for your reply. Actually your code can be used in lowleveltable.cs . or shall i can use your code in  HighLevelTable.cs file also.??

**Comment by aaoswal** [comment]
It can be used in your use case as well.

Hope this helps!
