### ISSUE TITLE
Visual Studio - deploy template stack name validation inconsistent

### ISSUE THREAD

**Issue by sliedig** [aws/aws-sdk-net#195]
There are some inconsistencies when creating a stack via the AWS Explorer in Visual Studio, specifically, validating the stack name.

When you right-click a file in the Solution Explorer and select 'Deploy to AWS CloudFormation' it will accept the valid stack name which contains hyphens and underscores.
 
![image](https://cloud.githubusercontent.com/assets/597073/7038615/1473b12a-dde7-11e4-8e9a-9a563fa1e9bd.png)

However, creating a new stack from the AWS Explorer  window you get a validation error.

![image](https://cloud.githubusercontent.com/assets/597073/7038621/292359ea-dde7-11e4-880b-dfa857ef4847.png)

Expect the behaviour to be consistent.

**Comment by steveataws** [comment]
Thanks for reporting this, we're taking a look.

**Comment by normj** [comment]
Version 1.9.2.2 of the toolkit just got released today which fixes the inconsistency.
