### ISSUE TITLE
DynamoDB Paginators seem not to free up memory

### ISSUE THREAD

**Issue by Kralizek** [aws/aws-sdk-net#1951]
Using paginators to fetch DynamoDB big amount of data seems to leak memory.

I noticed this on my service:

![image](https://user-images.githubusercontent.com/2458439/145455866-218c6246-8b51-49f1-bde3-644fed74090a.png)

Each increasing step correlates to big load operations being performed via query.

This is the code I use to unwrap a paginated request:

```csharp
var lookup = _dynamoDb.Paginators.Query(queryRequest)
                                        .Responses
                                        .ToEnumerable()
                                        .SelectMany(response => response.Items)
                                        .Select(ReadTimeSlotWrapper)
                                        .ToLookup(k => k.TreatmentIdentifier, v => v.TimeSlot);
```

The snippet above uses the package [System.Linq.Async](https://www.nuget.org/packages/System.Linq.Async) to unwrap the async enumerable.

I then proceed to transform the lookup and return it to the caller

```csharp
var response = new Response
{
    List = new List
    {
        Items =
        {
            from grp in lookup
            select new ItemResult
            {
                Key = grp.Key,
                Items = new ItemGroup
                {
                    Items = { grp }
                }
            }
        }
    }
};

return Task.FromResult(response);
```

The service is running on ECS Fargate.

**Comment by aaoswal** [comment]
Hi @Kralizek,
Thank you for submitting the issue. Could you please provide some additional information:
- Can you confirm that the CPU utilization for the container is not maxed out?
- If not, could you elaborate a little more on the size of the workload?
- Any information/configurations/sample code that might help in reproducing the issue?

Thanks,
Anish.

**Comment by Kralizek** [comment]
CPU is pretty stable around 20-30%.

The query usually returns around higher tens of items.

I'm not sure I'm able to create a proper repro case bit I'll try.

**Comment by Kralizek** [comment]
@aaoswal I'm not able to recreate a proper repro.

I've taken a screenshot of the last 12h from the same CloudWatch dashboard. The dips map to service restarts.

<img width="733" alt="image" src="https://user-images.githubusercontent.com/2458439/145831783-48918d24-a996-4319-8954-458389b158af.png">

**Comment by ashishdhingra** [comment]
Hi @Kralizek,

Good afternoon.

Could you please share the sample code solution to consistently reproduce the issue? Garbage collection is undeterministic and sample code would be helpful to isolate any logic issues.

Thanks,
Ashish

**Comment by Kralizek** [comment]
Hi @ashishdhingra 

Unfortunately this isn't a behavior that I was able to reproduce on a small sample.

**Comment by ashishdhingra** [comment]
> ```cs
> response = new Response
> {
>     List = new List
>     {
>         Items =
>         {
>             from grp in lookup
>             select new ItemResult
>             {
>                 Key = grp.Key,
>                 Items = new ItemGroup
>                 
> ```

@Kralizek Thanks for your reply. It would still be helpful if you could share sample code solution for us to reproduce the issue.
