### ISSUE TITLE
Why are the AWS SDK doc comments so littered with unusual paragraph breaks?

### ISSUE THREAD

**Issue by winzig** [aws/aws-sdk-net#1954]
Reading the doc comments from within environments like VSCode yields a very bad user experience:

> <img width="641" alt="screenshot 2021-12-16 at 12 07 39" src="https://user-images.githubusercontent.com/127062/146441892-8d366d3b-957c-4ef5-bc98-d043d70bae5f.png">

When you look at the code itself you can see _why_ it's formatted like this:

> <img width="1124" alt="screenshot 2021-12-16 at 12 05 50" src="https://user-images.githubusercontent.com/127062/146442007-f7f40177-dcd6-46ea-b734-7c78e6d511c0.png">

...but my question is _why_ are all these `<para>` tags littered everywhere and can they be removed?

**Comment by ashishdhingra** [comment]
Hi @winzig,

Good afternoon.

The documentation is question coming from the service models shared by service teams. For SQS service for instance, it's coming from:
- For code documentation: https://github.com/aws/aws-sdk-net/blob/db5c9aec40d2d1f9b8f97d34e95a9b8108c39558/generator/ServiceModels/sqs/sqs-2012-11-05.normal.json#L218
- For SDK API reference: https://github.com/aws/aws-sdk-net/blob/cc4571122bb564b3ff4eb315ae77802eadc50447/generator/ServiceModels/sqs/sqs-2012-11-05.docs.json#L18
 
The documentation in this case for `ReceiveMessage` maps to the service API documentation at https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html. In this case, `<p>` tag gets changed to `<para>` for documentation comment. The documentation generation process is automated and these service models are shared with all the SDK(s), not just the .NET SDK. Hence these cannot be removed.

Thanks,
Ashish

**Comment by winzig** [comment]
It seems like it's the `<li> </li>` tags that might be causing most of the formatting problems, but in any case I hope this can stay open as in general the doc comments are very difficult to read on .NET builds.

**Comment by ashishdhingra** [comment]
> It seems like it's the `<li> </li>` tags that might be causing most of the formatting problems, but in any case I hope this can stay open as in general the doc comments are very difficult to read on .NET builds.

@winzig I'm unsure if this would ever be prioritized. But I will discuss this with the team if we could do something about it.

**Comment by Kralizek** [comment]
I agree with @winzig. This issue has a really bad effect on general development experience.

**Comment by dscpinheiro** [comment]
This is the same problem as #1934, please see my update there.
