### ISSUE TITLE
Lifetime for dependency injected services

### ISSUE THREAD

**Issue by ThomasArdal** [aws/aws-sdk-net#1955]
I noticed something strange with my ASP.NET Core based application after the breakdown on AWS on December 15 (if I remember correctly). After the issue was fixed on AWS, I noticed that the client I have registered would often timeout. I was creating and injecting the service in an ASP.NET Core project in the `Startup.cs` file like this:

```csharp
var emailClient = new AmazonSimpleEmailServiceClient(new BasicAWSCredentials("...", "..."), RegionEndpoint.USWest2);
services.AddSingleton<IAmazonSimpleEmailService>(emailClient);
```

So, with this approach it seemed like the singleton instance in some way had some internal state that the endpoint had been down. Other pieces of code I have (other projects) worked fine. I then learned that there's a better way to install the service:

```csharp
services.AddDefaultAWSOptions(new AWSOptions
{
    Credentials = new BasicAWSCredentials("...", "..."),
    Region = RegionEndpoint.USWest2,
});
services.AddAWSService<IAmazonSimpleEmailService>();
```

When doing this everything was working as expected. I was curious on what this actually changed why I started digging down into the `AddAWSService` method. To my surprise the method also registered the SES instance as a singleton which is what I already did with my previous code. My assumption here is that it wasn't the change of config code that fixed the issue for me, but the fact that the singleton instance was reloaded when deploying the new version.

Do you have some guidance around this? I already found https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-netcore.html which is a great source for using the new config package.

**Comment by aaoswal** [comment]
Hi @ThomasArdal,
Multiple regions were affected during the breakdown on December 15 including services like SES.
Currently both snippets seem to be working so it might be completely coincidental that reloading and redeploying the application solved the issue you faced.

Hope this helps!

**Comment by ThomasArdal** [comment]
I'm expecting both snippets to work since they basically do the same thing: register the client as a singleton. I'm a bit worried that a singleton client doesn't seem to recover well from an AWS breakdown. The performance was very bad with the instance created and constantly timed out. Once the instance was reloaded in memory, everything worked as expected. Do you know if there is some internal state or similar that would cause this?

**Comment by aaoswal** [comment]
No, there is no such internal state or something similar that would lead to this. It might have been a momentary problem during the breakdown and should not affect any current or future deployments.
Are you still experiencing any issues related to timeouts and bad performance when registering using the singleton client?

**Comment by ThomasArdal** [comment]
No, everything is running as expected again. I have a performance ping test set up and I'll monitor this going forward. Thank you for your help.
