### ISSUE TITLE
S3 Client's BucketRegionDetector.BucketRegionCache causing infinite failures in following calls

### ISSUE THREAD

**Issue by dorki** [aws/aws-sdk-net#1956]
## Description
When querying "Bucket Location" for a bucket that exists in region us-east-2 (could be any region except for us-east-1) using the region us-east-1 on the client config, an exception of AuthorizationHeaderMalformed will cause the SDK to put the "correct" region (us-east-2) in the cache.

that exception was originally caused because when querying the bucket using us-east-1, the request URL was bucket_name.s3.amazonaws.com and didn't contain the us-east-1 region explicitly and that DNS name is resolved to the correct region of the bucket "us-east-2". so the endpoint is in us-east-2 but the authentication header was us-east-1.

If from this point I'll try to query the same bucket using another region like "eu-west-1" the endpoint will be eu-west-1 but the authentication header will contain "us-east-2" because the S3Signer will put the cached region on the request as "AlternateRegion" and that will make it take precedence when creating the authorization header. so each request will throw the AuthorizationHeaderMalformed and after few failed retries the client will fail.

## Reproduction Steps
1. Create a bucket in us-east-2
2. Create a client using us-east-1 as the region
3. Query bucket location
4. Create a client using eu-west-1
5. Query bucket location

### Environment
Tested on windows and linux

## Resolution
As a temp solution i changed the default ClientConfig.USEast1RegionalEndpointValue to be regional so the requests to us-east-1 will be to the specific endpoint and not to the bucket dns name.
Another solution can be to set clientConfig.ForcePathStyle that will remove the bucket name from the endpoint.

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @dorki,

Good morning.

Thanks for reporting the issue. Could you please share the sample code so that we are consistently able to reproduce the issue? Just want to make sure that we are testing the same scenario.

Thanks,
Ashish
