### ISSUE TITLE
Add AWSOptions by ImplementationFactory for DI 

### ISSUE THREAD

**Issue by isdaniel** [aws/aws-sdk-net#1957]
## The Question

I hope  [ServiceCollectionExtensions.AddDefaultAWSOptions](https://github.com/aws/aws-sdk-net/blob/master/extensions/src/AWSSDK.Extensions.NETCore.Setup/ServiceCollectionExtensions.cs#L41-L45) be able to support to use `Func<IServiceProvider, AWSOptions>` to create `AWSOptions` object.

Because of some scenarios, we need to get some AWS information from our customer object for DI Container  instead of using `appsetting.json` or hardcode

**Comment by aaoswal** [comment]
Hi @isdaniel,
This does not seem to be a guidance issue. I see that you have already submitted a Pull Request for the same which would be checked towards merging into the SDK.

Thank you for your contribution.

**Comment by isdaniel** [comment]
@aaoswal OK I see, Thanks for you edit tags.

Could I know when would this PR will be reviewed? because our team needs to use this feature.

Thanks.

**Comment by ashishdhingra** [comment]
Needs review from team.

**Comment by ppittle** [comment]
PR https://github.com/aws/aws-sdk-net/pull/1958 is queued for release.

**Comment by ppittle** [comment]
PR https://github.com/aws/aws-sdk-net/pull/1958 is released.
