### ISSUE TITLE
Change dynamoDb client credentials at run time

### ISSUE THREAD

**Issue by hashitha** [aws/aws-sdk-net#1961]
I have run into a problem with Dynamodb `Table.LoadTable(dynamoDbClient, "tablename");`

**App design**

1. Client gets token from cognito userpool
2. this token is sent in `authorization` header
3. Server creates `CognitoAWSCredentials` using the token
4. Server gets the dynamoDb object using these credentials and returns the object to client

**This creates the client credentials in the server**
```
private CognitoAWSCredentials GetCredentials(ServerCallContext context)
{
    var idToken = "";
    var authorizationHeader = context.RequestHeaders.FirstOrDefault(e => e.Key == "authorization");
   
    if (authorizationHeader != null)
    {
        idToken = authorizationHeader.Value;
        //remove string Bearer 
        idToken = idToken.Remove(0, 7);
    }

    var user = new CognitoUser("", ClientId, _userPool, _identityProviderClient)
    {
        SessionTokens = new CognitoUserSession(idToken, null, null, DateTime.Now,
            DateTime.Now.AddHours(1))
    };

    var credentials = user.GetCognitoAWSCredentials(IdentityPoolId, _serviceEndPoint);
    return credentials;
}
```

**Code to get an item**
```
public async Task<T?> GetObjectAsync<T>(string hashKey, string rangeKey, ServerCallContext context)
{
    var credentials = GetCredentials(context);
    
    using var dynamoDbClient = new AmazonDynamoDBClient(credentials, _serviceEndPoint);

    //load table costs ~200ms
    var table = Table.LoadTable(dynamoDbClient, "tablename"); 
      
    //get item costs ~20ms
    var document = await table.GetItemAsync(hashKey, rangeKey);

    var objectstring = document?.ToJsonPretty();
    if (string.IsNullOrEmpty(objectstring)) return default;
    var item = JsonConvert.DeserializeObject<T>(objectstring);
    return item;
}
```
all the users get data from the same table but they have dynamodb fine graned permissions

this code works fine but it has an extra cost of loading table definition with every request ~200ms
is there any way I can load the table initially and then change the credentials with each call?

**Comment by aaoswal** [comment]
Hi @hashitha,
According to the information provided, you mentioned each user having fine grained permissions due to which it would be essential to set up the client with those permissions. Hence, to access the Table you would have to have credentials in-place to validate the permissions before getting the object from the table itself.

Unfortunately, the direct functionality of changing credentials with each call is not currently not present. If I come across any workarounds around this, I shall update the comments on this issue.

Happy Holidays!
