### ISSUE TITLE
AssumeRoleWithWebIdentityCredentialsOptions does not have a setter

### ISSUE THREAD

**Issue by ss22219** [aws/aws-sdk-net#1963]
## Description
I want to customize the DurationSeconds, but there is no setter
[AssumeRoleWithWebIdentityCredentialsOptions.cs](https://github.com/aws/aws-sdk-net/blob/475822dec5e87954b7a47ac65995714ae1f1b115/sdk/src/Core/Amazon.Runtime/Credentials/AssumeRoleWithWebIdentityCredentialsOptions.cs)

**Comment by ashishdhingra** [comment]
Hi @ss22219,

Good afternoon.

Thanks for raising the issue. Could you please explain your scenario with a sample code which requires you to explicitly set `DurationSeconds` property? I'm assuming this is a documentation issue, but I need to check with the team based on your input.

Thanks,
Ashish
