### ISSUE TITLE
Recently Created Files on an S3 Bucket

### ISSUE THREAD

**Issue by ullfindsmit** [aws/aws-sdk-net#1965]
## The Question
I need to import/process files in my app as they get created on the S3 bucket (or on a schedule).
The App runs on a windows machine.
The File is created in the following hierarchy
-Root
--Customer 1
--Customer 2
--Customer 3
----File 1
----File 2
--Customer 5
----File 1
--Customer 6

Currently I have to loop through all customer folders (could be tens of thousands), then find the files in those folders and check their date to see if these are new files.

Is there a more efficient way to do this using the current setup?
I know using lambda functions etc might be an alternative, but I'm specifically looking for how to improve my existing process.

### Environment
* SDK Version: latest
* Package Version: latest
* OS Info: Windows
* Build Environment : Visual Studio 
* Targeted .NET Platform:  .Net Framework

**Comment by aaoswal** [comment]
Hi @ullfindsmit,
Looking at your use-case, I am assuming that you are listing out the objects in your S3 bucket first and then iterating over them to see which ones are the latest ones and need to be updated, you could also get object metadata and then check for their last modified date which might take less processing instead as well.

It seems like these are the most efficient ways to do this.

You could also try having a definitive object naming scheme and then look for the file to see if it exists or not.

For Example: `Customer 1` might have objects called `Customer_1_<Number>` and you could directly lookup for the object name to see if it exists.

```
public bool Exists(string fileKey, string bucketName)
{
        try
        {
            response = _s3Client.GetObjectMetadata(new GetObjectMetadataRequest()
               .WithBucketName(bucketName)
               .WithKey(key));

            return true;
        }

        catch (Amazon.S3.AmazonS3Exception ex)
        {
            if (ex.StatusCode == System.Net.HttpStatusCode.NotFound)
                return false;
        }
}
```

Hope this helps!

**Comment by ullfindsmit** [comment]
@aaoswal I understand what you are saying. Unfortunately, the files are being dropped off by another team and they go by the user's ID first which creates files inside of subfolders and the files can be created over a period of time, so the only option I have is to query each folder and check for new files.

My question is around how do I sort by last modified in the query itself.

**Comment by aaoswal** [comment]
@ullfindsmit Unfortunately since the service API operation [`ListObjects`](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/S3/TListObjectsV2Request.html) does not support sorting by `Last Modified`, the SDK also does not support it. 

A workaround that might work is maintaining a list of objects and then using [`System.Linq`](https://docs.microsoft.com/en-us/dotnet/api/system.linq?view=net-6.0) .NET extension to sort them with the data received from the `ListObjectsResponse` `contents` using the `Last Modified` tag.

Hope this helps!

**Comment by ullfindsmit** [comment]
Understood.
However, LINQ will only work on the result returned.
So if there are 100,000 files, it will only return 1000.
I can live with that as long as they are sorted by DateModified Descending

Otherwise, I have to LOOP through entire 100,000 records (100 calls) to find the most recent files and then sort.

Hope this explains the issue and the reason for this post.

**Comment by aaoswal** [comment]
Glad that helped.
If its okay, can I mark this issue as resolved and close it?

**Comment by ullfindsmit** [comment]
No, the issue is not resolved.
The issue is that I have to make 1000 calls to find out the most recently modified files.
Which is why I posted if there was a way to find recently modified files.
If the first page result (1000) had files that were newer, I would go to page 2, but not need to query 1000 times each run.

**Comment by aaoswal** [comment]
As mentioned earlier sorry but the operation is not supported by the service API and hence is not supported by the SDK itself. 

Unfortunately, as the workaround does not work for you, the only working solution would be to make multiple calls or loop through all the folders and objects to find the most recent ones.
