### ISSUE TITLE
Add target framework for dotnet6.0

### ISSUE THREAD

**Issue by jon-armen** [aws/aws-sdk-net#1967]
## Describe the Feature
Add target framework for dotnet6.0

## Additional Context
Add support for directly targeting dotnet6.0 assemblies instead of falling back to netstandard

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change  

---

This is a :rocket: Feature Request

**Comment by ashishdhingra** [comment]
Needs review with the team. Customer has already submitted a PR.

**Comment by dscpinheiro** [comment]
Apologies for the delay, but we added .NET 8 (the latest LTS version) support starting in versions `3.7.300` of the SDK NuGet packages: https://github.com/aws/aws-sdk-net/blob/main/changelogs/SDK.CHANGELOG.2023.md#376830-2023-11-10-0208-utc
