### ISSUE TITLE
logging via AWS.Logger.Log4net.AWSAppender hangs web app

### ISSUE THREAD

**Issue by alverdal** [aws/aws-sdk-net#1968]
## Description
Web application refuse to start after updating nuget package AWSSDK.core from 3.7.0.45 -> 3.7.1 (and anything newer).
I'm using AWS.Logger.Log4net to send logs to cloud watch.

On my local dev machine I got valid credentials to access cloud watch and the sdk is complaining that I got invalid credentials. 
On 3.7.0.45 this seemed to be ignored and the web application was able to start and run without issues. But after updating to 3.7.1 the application is complaining on credentials and the web application hangs.
I'm running the web application on IIS.

According to the logs it seem that a thread is aborted and that causes the whole web application to halt.
Perhaps you can see if anything related to invalid credentials was changed between these versions that might cause the issue and also instruct me on how I can fix this issue.

## Reproduction Steps
Updated nuget package AWSSDK.Core.
Try to log using the appender
```
<appender name="AWS" type="AWS.Logger.Log4net.AWSAppender,AWS.Logger.Log4net">
		<LogStreamNamePrefix>xx</LogStreamNamePrefix>
		<LogGroup>xx</LogGroup>
		<Region>xx</Region>
		<layout type="log4net.Layout.PatternLayout">
			<conversionPattern value="%-4timestamp [%thread] %-5level %logger %ndc - %message%newline" />
		</layout>
		<LibraryLogFileName>c:\temp\logs\my_app_awslog.txt</LibraryLogFileName>
	</appender>
```
### Logs
```

Log Entry : 
2022-01-05 20:05:03
  :
  :Amazon.Runtime.AmazonServiceException: Unable to get IAM security credentials from EC2 Instance Metadata Service.
   vid Amazon.Runtime.DefaultInstanceProfileAWSCredentials.FetchCredentials()
   vid Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentials()
   vid Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentialsAsync()
   vid Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__7`1.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5`1.MoveNext()
-------------------------------
Log Entry : 
2022-01-05 20:05:03
  :
  :Amazon.Runtime.AmazonServiceException: Unable to get IAM security credentials from EC2 Instance Metadata Service.
   vid Amazon.Runtime.DefaultInstanceProfileAWSCredentials.FetchCredentials()
   vid Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentials()
   vid Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentialsAsync()
   vid Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__7`1.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5`1.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__1`1.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid AWS.Logger.Core.AWSLoggerCore.<LogEventTransmissionSetup>d__33.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid AWS.Logger.Core.AWSLoggerCore.<Monitor>d__31.MoveNext()
-------------------------------
Log Entry : 
2022-01-05 20:05:35
  :
  :Amazon.Runtime.AmazonServiceException: Unable to get IAM security credentials from EC2 Instance Metadata Service.
   vid Amazon.Runtime.DefaultInstanceProfileAWSCredentials.FetchCredentials()
   vid Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentials()
   vid Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentialsAsync()
   vid Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__7`1.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5`1.MoveNext()
-------------------------------
Log Entry : 
2022-01-05 20:05:35
  :
  :Amazon.Runtime.AmazonServiceException: Unable to get IAM security credentials from EC2 Instance Metadata Service.
   vid Amazon.Runtime.DefaultInstanceProfileAWSCredentials.FetchCredentials()
   vid Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentials()
   vid Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentialsAsync()
   vid Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__7`1.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__10`1.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5`1.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__1`1.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid AWS.Logger.Core.AWSLoggerCore.<LogEventTransmissionSetup>d__33.MoveNext()
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid AWS.Logger.Core.AWSLoggerCore.<Monitor>d__31.MoveNext()
-------------------------------
Log Entry : 
1/5/2022 8:05:45 PM
  :
  :System.TimeoutException: Flush Timeout - ServiceURL=https://xxx.xx-1.amazonaws.com/, StreamName=, PendingMessages=2, CurrentBatch=0
-------------------------------
Log Entry : 
2022-01-05 20:05:45
  :
  :System.Threading.ThreadAbortException: The thread was being aborted.
   vid Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__9`1.MoveNext()
   vid System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   vid Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   vid Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__5`1.MoveNext()
-------------------------------
```

### Environment

* SDK Version:
* Package Version: 
```
<package id="AWS.Logger.Core" version="3.0.0" targetFramework="net48" />
  <package id="AWS.Logger.Log4net" version="3.2.1" targetFramework="net48" />
  <package id="AWSSDK.CloudWatchLogs" version="3.7.0.25" targetFramework="net48" />
  <package id="AWSSDK.Core" version="3.7.1" targetFramework="net48" />
  <package id="log4net" version="2.0.12" targetFramework="net48" />
```

* OS Info: Windows 10
* Build Environment: Visual Studio
* Targeted .NET Platform:  .net 4.8

## Resolution

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @alverdal,

Good morning.

Thanks for raising the issue. Could you please share the following:
- How are credentials configured for your application? Kindly refer [Credential and profile resolution](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/creds-assign.html) for credential resolution preference.
- Share the sample code solution targeting .NET Framework 4.8 to reproduce the issue.

Upon checking the [AWSSDK changelog](https://github.com/aws/aws-sdk-net/blob/master/SDK.CHANGELOG.md#37780-2021-07-21-2139-utc), `AWSSDK.Core 3.7.1.0` enabled IPv6 support for IMDS. Not sure if this would be the case for your local development machine since it might not an EC2 instance. Also check if your account under which your web application is running has access to default profile if credentials are configured there on.

Thanks,
Ashish

**Comment by alverdal** [comment]
Hi,

I got no credential configured on my local dev machine.
I should say that I saw that I got the same problem on our test server as well. The logging is working OK on this server when using an earlier version than 3.7.1 (logs showing up in cloudwatch).

Sample code: https://github.com/alverdal/awslog4net-example
You need to publish to IIS for the web site to hang. If running via IIS Express the web site seem to be starting up OK.

**Comment by ashishdhingra** [comment]
> Hi,
> 
> 
> 
> I got no credential configured on my local dev machine.
> 
> I should say that I saw that I got the same problem on our test server as well. The logging is working OK on this server when using an earlier version than 3.7.1 (logs showing up in cloudwatch).
> 
> 
> 
> Sample code: https://github.com/alverdal/awslog4net-example
> 
> You need to publish to IIS for the web site to hang. If running via IIS Express the web site seem to be starting up OK.
> 
> 

@alverdal I would try to look at your sample. However, you need to have credentials configured in order to send logs to CloudWatch. I'm unsure if any changes in Microsoft request pipeline might have impacted this, aa stated earlier, only IPv6 support for IMDS was added in AWSSDK.Core 3.7.1. Try to configure credentials which has IAM policy for logging into CloudWatch.

**Comment by alverdal** [comment]
Hi, thanks for a quick response :) 

To clarify, when I use 3.7.1 version I get no log at all, the application seem to hang and never returns a response. This occuss both locally and on our test server (the test server is configured with working aws credentials).

When I use < 3.7.1 locally the application is working even though it logs some credential errors in the 'AWS.Logger.Log4net.AWSAppender' log file.

When I use < 3.7.1 on the testserver everything is working fine, no credential errors thrown.

So it seems that >= 3.7.1 is hanging the web application both with and without working credentials. 

Hopefully you can reproduce the issue with the repo example.

Thanks.

**Comment by ashishdhingra** [comment]
> Hi,
> 
> I got no credential configured on my local dev machine. I should say that I saw that I got the same problem on our test server as well. The logging is working OK on this server when using an earlier version than 3.7.1 (logs showing up in cloudwatch).
> 
> Sample code: https://github.com/alverdal/awslog4net-example You need to publish to IIS for the web site to hang. If running via IIS Express the web site seem to be starting up OK.

@alverdal When you run the application using IIS Express, it runs under the identity of local user account. When the application is run in IIS, it runs under the web application pool identity. This web application pool identity would not have access to create logs, default credentials file would not be searched for in the user's profile location, etc. Please refer to the workaround in the issue https://github.com/aws/aws-sdk-net/issues/1139 where similar problem was reported. Hope this helps.

**Comment by alverdal** [comment]
I cannot see that it explains why it’s working  depending on which version
of the sdk I use. I’m publishing to the same site in IIS with the same
permissions and it’s only working for version < 3.7.1 .

Have you had time to test the repo?

Thank you

fre 7 jan. 2022 kl. 18:29 skrev Ashish Dhingra ***@***.***>:

**Comment by alverdal** [comment]
@ashishdhingra if it will help to clarify the issue we can have a live session, just let me know :)

**Comment by ashishdhingra** [comment]
While root cause needs to be investigated,  issue is reproducible.

**STEPS:**
1. Cloned user's web application from https://github.com/alverdal/awslog4net-example.
2. Downgraded NuGet packages `AWSSDK.Core` and `AWSSDK.CloudWatchLogs` to version less than `3.7.1`.
3. Opened IIS and created a new web site named `testwebapp` linked to `http://localhost:8080` (Port 80 is used by default web site).
4. Used Visual Studio to Publish the web application to the newly created website (Visual Studio needs to be launched as Administrator)
5. Browsed the new web site (either from within IIS or navigating to `http://localhost:8080`).
6. Default web page is displayed. The log file `c:\temp\logs\tmp\my_app_awslog.txt` (as configured in `log4net.config`) is created and continuously appended with AWS credentials error(s).
7. Upgraded NuGet packages `AWSSDK.Core` and `AWSSDK.CloudWatchLogs` to the latest version.
8. Stopped the web site `testwebapp`. Also stopped World Wide Web Publishing service so that we can delete all logs created at `c:\temp\logs\tmp` and kill the process which is appending AWS logs.
9. Redeployed the web application.
10. Restarted World Wide Web Publishing service and `testwebapp` web site.
11. Browsed the new web site (either from within IIS or navigating to `http://localhost:8080`).

**RESULT:** The default web page is not displayed and appears to be hanged. The log file `c:\temp\logs\tmp\my_app_awslog.txt` is not created.

**Comment by alverdal** [comment]
Good job on reproducing the behaviour 👍

**Comment by ethos-tim** [comment]
I have the exact same issue. Ticket here: https://github.com/aws/aws-logging-dotnet/issues/253

**Comment by ethos-tim** [comment]
I looked at a dump of the hung process and see this is where it is stuck: 

SYMBOL_NAME:  w3wphost!AppHostInitialize+14c
MODULE_NAME: w3wphost
IMAGE_NAME:  w3wphost.dll
FAILURE_BUCKET_ID:  BREAKPOINT_80000003_w3wphost.dll!AppHostInitialize

**Comment by ethos-tim** [comment]
Another way to test this is have ZERO credentials configured. The old version did not hang, it just did NOT log. The new version hangs instead of bypassing the issue and running without logging. This was working for developers without any credentials until we upgraded. After upgrading to get it to work we had to configure AWS CLI and put in default credentials.

**Comment by ethos-tim** [comment]
I had some time today and was testing this with the SDK and Logger source code and it locks up on this line: 
<img width="1000" alt="image" src="https://github.com/aws/aws-sdk-net/assets/51724484/d41de5d2-5cb1-4ae1-9403-9cc4217bd5db">


\aws-sdk\sdk\src\Core\Amazon.Runtime\ClientConfig.cs Line 1108

**Comment by ethos-tim** [comment]
It looks to be a race condition between the SDK trying to get the distributed credentials in a timer and both EC2InstanceMetadata and AmazonServiceClient calling into FallbackInternalConfigurationFactory and blocking each other. 

Stack traces of what is running when it locks: 

<img width="871" alt="RaceCallStack1" src="https://github.com/aws/aws-sdk-net/assets/51724484/ea7aa6bb-ebf8-4193-8369-2f5186293946">

<img width="1111" alt="RaceCallStack2" src="https://github.com/aws/aws-sdk-net/assets/51724484/0adbe350-b053-4ce7-8195-40a27e2d3705">

FallbackInternalConfigurationFactory is running Reset() while it is also having properties read and it appears to lock. 

LMK if I can do anymore to help pinppoint the issue.

**Comment by ethos-tim** [comment]
Settings the environment variable AWS_EC2_METADATA_DISABLED to true stops the lock up.

**Comment by ashovlin** [comment]
Big thanks to @alverdal and @ethos-tim for your work investigating and troubleshooting this!

Confirmed that we do have a deadlock between two threads:

1. The left thread is the one where we're calling `LogManager.GetLogger` explicitly while using `AWS.Logger.Log4net`
    * It calls `GetLogger` first, which acquires [this lock](https://github.com/apache/logging-log4net/blob/19fb2d1ccb2132860b65f30b28bab8132a89b875/src/log4net/Core/DefaultRepositorySelector.cs#L274) in log4net's `DefaultRepositorySelector`
     * Later on it tries to initialize its internal `AmazonCloudWatchLogsClient`. This needs to access the configured retry mode, which leads to the locked call to `FallbackInternalConfigurationFactory.RetryMode` at: https://github.com/aws/aws-sdk-net/blob/a2ad0e42ecf09f5021062250d1edb280f3f53d64/sdk/src/Core/Amazon.Runtime/ClientConfig.cs#L1108
2. The right thread is the timer that loads credentials from EC2's IMDS
    * This beats the left thread to invoking the static constructor for `FallbackInternalConfigurationFactory`
 when it is trying to load the endpoint of the instance metadata service https://github.com/aws/aws-sdk-net/blob/a2ad0e42ecf09f5021062250d1edb280f3f53d64/sdk/src/Core/Amazon.Util/EC2InstanceMetadata.cs#L99 
   * *This ability to override the IMDS endpoint or to switch between IPv4 and IPv6 variants was introduced in [3.7.1.0 of AWSSDK.Core](https://github.com/aws/aws-sdk-net/blob/main/changelogs/SDK.CHANGELOG.2021.md#37780-2021-07-21-2139-utc). Previously the IMDS endpoint was a constant string. This aligns with the reports around when the regression was introduced.*
    * However, the static constructor for `FallbackInternalConfigurationFactory` will create `EnvironmentVariableInternalConfiguration` instance, which gets its own logger here: https://github.com/aws/aws-sdk-net/blob/a2ad0e42ecf09f5021062250d1edb280f3f53d64/sdk/src/Core/Amazon.Runtime/Internal/InternalConfiguration.cs#L113
   * Initializing that logger is blocked on the `lock` inside log4net.

So thread 2 above is blocked when trying to create a logger on the lock held by thread 1 inside log4net. But thread 1 is also blocked, waiting for that static constructor of `FallbackInternalConfigurationFactory` to finish on thread 2 so it can access the retry mode to use for the client inside its logger.


![image](https://github.com/aws/aws-sdk-net/assets/1170880/29508c01-b02b-443a-a431-ad53de354b19)

Configuring credentials other than EC2's, or setting `AWS_EC2_METADATA_DISABLED` like you suggest to disable the second thread should avoid this. I'm still working on a code fix.

**Comment by ashovlin** [comment]
We've released [AWS.Logger.Core v3.3.3](https://www.nuget.org/packages/AWS.Logger.Core/3.3.3) today, which now lazily initializes the internal CloudWatch Logs client. This should avoid the race condition with the SDK's own logging that was leading to the deadlock.

You could either upgrade your pinned version of AWS.Logger.Core, or to [AWS.Logger.Log4net v3.5.3](https://www.nuget.org/packages/AWS.Logger.Log4net/3.5.3) to pull in the latest core.

Let us know if that doesn't mitigate the issue for you, or if anybody is seeing this outside of AWS.Logger.Log4net. Thanks.
