### ISSUE TITLE
Retrive access token using authorization code

### ISSUE THREAD

**Issue by Chamila107** [aws/aws-sdk-net#1972]
Hi ,
We are working on a sample to do a social sign-in with Cognito.At the moment after a successful social sign-in now, we have the authorization code.Now we need to retrieve the tokens using the authorization code. But we can not see any methods implemented in aws-sdk-net to retrieve tokens using the authorization code.
We are aware of the token endpoint (https://docs.aws.amazon.com/cognito/latest/developerguide/token-endpoint.html). But what we would like to know is , what is the method in aws-sdk-net which it can use to retrieve access tokens using authorization code? Thank you

**Comment by ashishdhingra** [comment]
Hi @Chamila107,

Good morning.

For working with Cognito, following high level libraries could be helpful:
- [Amazon.Extensions.CognitoAuthentication](https://www.nuget.org/packages/Amazon.Extensions.CognitoAuthentication/), GitHub repo: [aws/aws-sdk-net-extensions-cognito](https://github.com/aws/aws-sdk-net-extensions-cognito).
- [Amazon.AspNetCore.Identity.Cognito](https://www.nuget.org/packages/Amazon.AspNetCore.Identity.Cognito/), GitHub repo: [aws/aws-aspnet-cognito-identity-provider](https://github.com/aws/aws-aspnet-cognito-identity-provider)

While you could certainly use [AWSSDK.CognitoIdentity](https://www.nuget.org/packages/AWSSDK.CognitoIdentity/) and [AWSSDK.CognitoIdentityProvider](https://www.nuget.org/packages/AWSSDK.CognitoIdentityProvider/) packages from AWSSDK for .NET, these high level libraries abstract away the details for complex scenarios. Hope this helps.

Thanks,
Ashish
