### ISSUE TITLE
Experiencing memory leaks when using RDS Token assembly

### ISSUE THREAD

**Issue by archanasharma3** [aws/aws-sdk-net#1973]
When the application generates an RDS authentication token for use with connecting to an RDS database to generate the password, we are experiencing memory leaks in our application. We are using the Assembly AWSSDK.RDS, Version=3.3.0.0 for now and not the latest version due to package dependencies on other projects. To prove that, So we tried switching the GenerateAuthToken off and used the static password and deployed the change, i could see there is a slow decline but much slower than it was earlier which is in measurable scale. So i believe that the RDP token code is the vast majority of the problem it seems. It is just a toggle option which we switch off it works fine and we don't experience any memory issues. Attaching the metrics from the graph to look at the difference when the change for static password was made and deployed. Please let me know in case you need any more information from my side to look into this issue. Looking forward for the support.

This is the toggle option code -
```C#
 if (applicationDbContextPostgreSqlSettings.GenerateAuthToken.HasValue && applicationDbContextPostgreSqlSettings.GenerateAuthToken.Value)
            {
                builder.Password = RDSAuthTokenGenerator.GenerateAuthToken(
                   applicationDbContextPostgreSqlSettings.RegionEndpoint,
                    applicationDbContextPostgreSqlSettings.Host,
                    applicationDbContextPostgreSqlSettings.Port.Value,
                    applicationDbContextPostgreSqlSettings.Username);
            }
            else
            {
                SecureString password = applicationDbContextPostgreSqlSettings.Password;

                password.Decrypt(plainText =>
                {
                    builder.Password = plainText;
                });
            }
```
![Token-Generation-On](https://user-images.githubusercontent.com/98328914/152368468-ab9266dc-a884-4c2e-876f-764049b83e47.png)
![Difference](https://user-images.githubusercontent.com/98328914/152387111-ca04734d-dcf2-4d16-839e-999a5290199f.png)

**Comment by ashishdhingra** [comment]
Hi @archanasharma3,

Good afternoon.

Could you please share the sample application so that we could reproduce the issue? Above code snippet doesn't provide enough data points that support memory leak because of call to `RDSAuthTokenGenerator.GenerateAuthToken()`. To troubleshoot further, we need to investigate application code and see if it's trying to generate tokens continuously.

Thanks,
Ashish

**Comment by archanasharma3** [comment]
Hello, as requested attaching the startup, and dbcontext context related files. Please let me know if any other files are needed for investigation.
[ApplicationDbContext.txt](https://github.com/aws/aws-sdk-net/files/8014032/ApplicationDbContext.txt)
[Startup.txt](https://github.com/aws/aws-sdk-net/files/8014034/Startup.txt)
[ApplicationDbContextPostgreSql.txt](https://github.com/aws/aws-sdk-net/files/8014049/ApplicationDbContextPostgreSql.txt)
.

**Comment by ashishdhingra** [comment]
Hi @archanasharma3,

Good morning.

Unfortunately, I do not see any logic in [RDSAuthTokenGenerator](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/RDS/Custom/Util/RDSAuthTokenGenerator.cs) that might be causing the memory leaks. I examined your [Startup.txt](https://github.com/aws/aws-sdk-net/files/8014034/Startup.txt) and here are my observations:
- You are using `services.AddScoped<IApplicationDbContext, ApplicationDbContextPostgreSql>();`. Per Microsoft's official documentation [Dependency injection in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-6.0), the `AddScoped` method registers the service with a scoped lifetime, the lifetime of a single request. This means for every request from any user would have a new ApplicationDbContextPostgreSql instance, which could end up calling `Amazon.RDS.Util.RDSAuthTokenGenerator.GenerateAuthToken()` every time. One optimization that could be done here is to cache generated token (however, you would need to add logic to refresh the expired tokens).
- I do notice that many services are registered at application startup. You might want to revisit the services to see if there could be any memory leaks there.

Could you try developing sample application with minimal logic which invokes `Amazon.RDS.Util.RDSAuthTokenGenerator.GenerateAuthToken()` first with `AddScoped()` and then with `AddSingleton()`? Also try upgrading to latest AWSDK version, any identified fixes would be pushed on top of latest version, if any.

Thanks,
Ashish
