### ISSUE TITLE
.NET SDK should support environment variables http_proxy and https_proxy (as AWS CLI does)

### ISSUE THREAD

**Issue by o7g8** [aws/aws-sdk-net#1977]
I want AWS .NET SDK to fetch proxy settings from environment variables `http_proxy` and `https_proxy` in the same way as AWS CLI does, see <https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-proxy.html>.

### Is your Feature Request related to a problem?

I'm always frustrated that I don't get consistent behaviour of AWS toolchain in proxy handling, esp. proxies which require user/password authorization. Currently I need to specify `https_proxy` variable to get AWS CLI working, and then I need to craft an `app.config` file for _every_ .NET application as described in <https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-ref.html#net-dg-config-ref-elements-proxy> .
Situation gets even worse when I need to distribute my apps to other users or organizations, which need to learn the AWS-specific format of the `aws` section in the `app.config` and adjust it to their conditions. A simple and straight environment variable would solve the issue.

Here is the way I have discovered the `http_proxy` and `https_proxy` env. variables don't work with AWS .NET SDK:

- installed a Telerik Fiddler Classic on my machine
- enabled the Fiddler's rule `Require Proxy Authentication` (implies user=1, password=1)
- set the `https_proxy=http://1:1@127.0.0.1:8888`

My .NET Framework-based (not .NET Core) app didn't work (AWS .NET SDK 3.7.5.9).  
When I created an `app.config` following <https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-ref.html#net-dg-config-ref-elements-proxy>  it did work, but I don't think the config file should be necessary.

---

This is a :rocket: Feature Request

**Comment by ashishdhingra** [comment]
This needs review with the team. Also need to check on how other SDK(s) (e.g. Java) handle `HTTP_PROXY` and `HTTPS_PROXY` environment variables.

**Comment by dscpinheiro** [comment]
Today's release of [AWSSDK.Core](https://www.nuget.org/packages/AWSSDK.Core/) (`3.7.301`) includes #2991, which added support for the `http_proxy` and `https_proxy` environment variables.
