### ISSUE TITLE
List-Unsubscribe support for Bounce / Spam notifications

### ISSUE THREAD

**Issue by lepipele** [aws/aws-sdk-net#198]
Hi,

I've been trying to transition from using email for Bounce / Spam notifications to using Amazon SNS / SQS. I must say I am quite impressed how well it this works, however I have one huge problem: when using email I get full email message returned back so I can parse it in order to determine list from which email is sent. When using SNS, I get back Mail object which contains just source address and timestamp as described here:

http://docs.aws.amazon.com/ses/latest/DeveloperGuide/notification-contents.html#mail-object

My questions is - would it be possible that you add value of List-Unsubscribe header (if present in email) to that mail-object? Or some other custom header that we can initialize when sending?

It would be a huge help in determining source - right now I can't support sending multiple newsletters from same address at the same time because if I did that I wouldn't be able to determine which one triggered unsubscribe.

**Comment by lepipele** [comment]
And since I haven't been watching closely - can anybody tell me if support for List-Unsubscribe has improved lately? I think that header is VERY important and when last implementing SES integration I know I needed to juggle with: SendRawEmail and reflection in order to convert MailMessage into MemoryStream. Has this improved? If no, why not - considering that we all want to allow users to unsubscribe as easy as possible... especially now that Gmail and other providers are using this header to offer Unsubscribe in their own GUIs:

http://www.labnol.org/internet/gmail-unsubscribe/28806/

**Comment by lepipele** [comment]
@normj @PavelSafronov Any response on this? I would really prefer to use SNS/SQS instead of manually parsing bounce mails and I am sure others would as well. I definitely want to allow super easy unsubscribe for end customers.

**Comment by PavelSafronov** [comment]
Sorry about the late response.

To add a specific item to a response, you would need to contact the service team. The .NET SDK only exposes what the service provides. The best places to discuss possible changes to the service is actually on the [respective service forums](https://forums.aws.amazon.com/index.jspa). For instance, the [SES forum](https://forums.aws.amazon.com/forum.jspa?forumID=90).

As for simplifying SendRawEmail, thank you for this feedback. I've added this as a feature request to our internal backlog.

**Comment by lepipele** [comment]
Well - I don't know if you made improvements to SendRawEmail in last 4 years, but if you haven't by now I guess it's dead end. Will definitely try to find time and test out new versions - I am still on AWS.dll from 4 years ago and surprisingly it's been working quite well.
