### ISSUE TITLE
Cognito: Unconfirmed user that forgot his password

### ISSUE THREAD

**Issue by burner986** [aws/aws-sdk-net#1984]
My question is similar to https://github.com/aws/aws-sdk-net/issues/866.

Given a user signs up but doesn't continue to confirm his registration. And the user also forgets his password.

When he tries to log in he will receive NotAuthorizedException because of the wrong password. (UserNotConfirmedException only appears with correct password)

When he tries the forgotpassword route he will receive InvalidParameterException due to the unconfirmed account

So essentially in this scenario the users cannot proceed. What would you suggest to do in this situation?

**Comment by ashishdhingra** [comment]
Hi @burner986,

Good morning.

Thanks for posting guidance question. Could you please refer the following comment on [AWS Cognito - HELP required - Unconfirmed email & resetting password](https://www.reddit.com/r/reactnative/comments/ph8ok8/aws_cognito_help_required_unconfirmed_email/)?

> With regards to knowing if they are verified or not, have a flag in your own database that sets whether the user has been verified or not. Cognito has a post verification trigger which you could attach a lambda to to do this. If they are not verified and try to reset password then send them down a confirmation route instead (resend confirmation email)

> Here's the docs for the confirmation trigger https://docs.amazonaws.cn/en_us/cognito/latest/developerguide/user-pool-lambda-post-confirmation.html

I didn't test if it works, but worth giving it a try.

Also refer [Managing error responses](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pool-managing-errors.html) for guidance on how to handle different errors.

Thanks,
Ashish
