### ISSUE TITLE
HashStream does not support seeking

### ISSUE THREAD

**Issue by fh-team22** [aws/aws-sdk-net#1985]
I found this bug always in my log file, i don't know or how this problem coming.

this is my code 

        private async Task<GetObjectResponse> getfileObject(GetObjectRequest request)
        {
            if (fileObject == null)
            {
                try
                {
                    var res = await _client.GetObjectAsync(request);
                    fileObject = res;
                }
                catch (AmazonS3Exception e)
                {
                }
            }
            return fileObject;
        }

I Used AWSSDK 3.7.3.19

?

**Comment by ashishdhingra** [comment]
Hi @fh-team22,

Good morning.

Thanks for posting guidance question. The details that you shared are pretty vague. There doesn't appear to be a problem in the code looking at the high level. Could you please share more detailed sample code along with log file in the below issue template.



## Expected Behavior



## Current Behavior






## Possible Solution



## Steps to Reproduce (for bugs)





## Context



## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

Thanks,
Ashish

**Comment by fh-team22** [comment]
**Expected Behavior:** just read images and PDFs

**Current Behavior:** can I read pdf or image but always give to me this error in the bug log.

**Possible Solution:** I try to stop this bug with different solutions but I can't like I tried to use memory stream but didn't work, as you told me I'm using basic read from S3.

**Steps to Reproduce (for bugs):** I can't find this bug locally, but always appears on production when trying to read an image or pdf.

**Context:** this is log 

Log level
Error

Short message
HashStream does not support seeking

Full message
   at Amazon.Runtime.Internal.Util.HashStream.Seek(Int64 offset, SeekOrigin origin)
   at Microsoft.AspNetCore.Http.SendFileResponseExtensions.SendFileAsyncCore(HttpResponse response, IFileInfo file, Int64 offset, Nullable`1 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.StaticFiles.StaticFileContext.SendRangeAsync()
   at Microsoft.AspNetCore.StaticFiles.StaticFileContext.ServeStaticFile(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)System.NotSupportedException: HashStream does not support seeking
   at Amazon.Runtime.Internal.Util.HashStream.Seek(Int64 offset, SeekOrigin origin)
   at Microsoft.AspNetCore.Http.SendFileResponseExtensions.SendFileAsyncCore(HttpResponse response, IFileInfo file, Int64 offset, Nullable`1 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.StaticFiles.StaticFileContext.SendRangeAsync()
   at Microsoft.AspNetCore.StaticFiles.StaticFileContext.ServeStaticFile(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

Customer
[Guest](https://10.10.2.15/Admin/Customer/Edit/195954638)

Page URL
https://www.masterelectronics.com/upload/parts/datasheets/mf-ai/iag-iug-ieg-ceg-leg.pdf

Referrer URL
https://www.trustedparts.com/

Created on
3/2/2022 9:58:57 PM

AWSSDK is 3.7.3.19

NEST is 6.4.2

NETStandardLibarary is 2.0.3

Windows 10

Visual Studio 2019 Version 16.11.5

.NetCore 5

Other Info in package.json file:
  "version": "1.0.0",
  "name": "nopcommerce",
  "private": true,
  "devDependencies": {
    "del": "^6.0.0",
    "gulp": "^4.0.2",
    "gulp-npm-dist": "^1.0.3",
    "gulp-rename": "^1.4.0",
    "gulp-uglyfly": "^1.4.2",
    "gulp-zip": "^5.0.2"

**Comment by ashishdhingra** [comment]
Hi @fh-team22,

Good morning.

Thanks for your response. Even though you have not shared the code, I can assume the logic in your application. From your code below:
```C#
private async Task<GetObjectResponse> getfileObject(GetObjectRequest request)
{
    if (fileObject == null)
    {
        try
        {
            var res = await _client.GetObjectAsync(request);
            fileObject = res;
        }
        catch (AmazonS3Exception e)
        {
        }
    }
    return fileObject;
}
```

You are trying to get object from S3 bucket only if `fileObject` (declared somewhere, **assuming it is static**) is `null`. The file download might have worked when the object is retrieved for the first time. During this time, the ASP.NET Core internal `Microsoft.AspNetCore.Http.SendFileResponseExtensions.SendFileAsyncCore()` processes (traverses through the bytes) and returns the `FileResult` to the browser. On subsequent file download requests, since you are reusing the existing `GetObjectResponse` object as stored in `fileObject` (declared somewhere, **assuming it is static**), the ASP.NET framework tries to Seek to the beginning of the response stream. Since ResponseStream returned by S3 in AWS SDK for .NET is not seekable, you are getting this error. This issue can also happen if user tries to click download somewhere in your application multiple times.The workaround is to not reuse the `GetObjectResponse` object since the application file download logic has already processed the response stream.

The below simplistic code works like a charm (the code is inly for demonstration purposes, best practices should be followed, including disposing off any unused objects):
```C#
using System.Threading.Tasks;
using Amazon.S3;
using Amazon.S3.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace S3DownloadTestWeb_Issue1985.Controllers
{
    public class HomeController : Controller
    {
        private AmazonS3Client amazonS3Client;
        private string bucketName = "testbucket-issue1985";
        private string objectKey = "test.pdf";

        public HomeController()
        {
            amazonS3Client = new AmazonS3Client();
        }

        public FileResult DownloadPdfFile()
        {
            return File(GetFileObject(new GetObjectRequest() { BucketName = bucketName, Key = objectKey }).Result.ResponseStream, "application/pdf");
        }

        private async Task<GetObjectResponse> GetFileObject(GetObjectRequest getObjectRequest)
        {
            return await amazonS3Client.GetObjectAsync(getObjectRequest);
        }
    }
}
```

You may also refer guidance at https://stackoverflow.com/questions/42861816/copy-between-two-aws-buckets-stream-returned-from-aws-hashstream-does-not-sup, not sure if it works though and might not scale well for large files.

Thanks,
Ashish

**Comment by fh-team22** [comment]
Thank a lot Ashish, I think same code on my project, take a look plz

**this is the class I used** 

using Amazon.S3;
using Amazon.S3.Model;
using Microsoft.Extensions.FileProviders;
using System;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Text;
using System.Threading.Tasks;

namespace AWSS3FileProvider
{
    public class S3ObjectFileContentInfo : IFileInfo
    {
        private GetObjectResponse fileObject = null;
        private GetObjectMetadataResponse fileObjectMetadata = null;
        private AmazonS3Client _client;
        private GetObjectRequest _request;
        private bool? exists;
        public S3ObjectFileContentInfo(AmazonS3Client client, GetObjectRequest request)
        {
            _client = client;
            _request = request;

            var metaRequest = new GetObjectMetadataRequest()
            {
                BucketName = _request.BucketName,
                Key = _request.Key
            };
            fileObjectMetadata = getMetaData(metaRequest).Result;
            fileObject = getfileObject(_request).Result;
        }

        private async Task<GetObjectResponse> getfileObject(GetObjectRequest request)
        {
            if (fileObject == null)
            {
                try
                {
                    var fileObject = await _client.GetObjectAsync(request);
                }
                catch (AmazonS3Exception e)
                {
                }
            }
            return fileObject;
        }
        private async Task<GetObjectMetadataResponse> getMetaData(GetObjectMetadataRequest metaRequest)
        {
            if (fileObjectMetadata == null)
            {
                try
                {
                    var res = await _client.GetObjectMetadataAsync(metaRequest).ConfigureAwait(true);
                    fileObjectMetadata = res;
                }
                catch (AmazonS3Exception e)
                {
                }
            }
            return fileObjectMetadata;
        }

        public bool Exists => Length > 0;

        public long Length => fileObjectMetadata?.ContentLength ?? 0;

        public string PhysicalPath => string.Empty;

        public string Name => Path.GetFileName(fileObject?.Key.TrimEnd('/'));

        public DateTimeOffset LastModified => fileObject?.LastModified ?? new DateTimeOffset(DateTime.Now);

        public bool IsDirectory => fileObject?.Key.EndsWith("/") ?? false;

        public Stream CreateReadStream() => fileObject?.ResponseStream;
    }
}

**call method here:**

        public IFileInfo GetFileInfo(string subpath)
        {
            int storeId = 0;
            var strArray = subpath.Split("ß");
            subpath = strArray[0];
            if (strArray.Length > 1)
            {
                var strStoreId = strArray[1];

                if (!string.IsNullOrEmpty(strStoreId))
                {
                    int.TryParse(strStoreId, out storeId);
                }
            }

            subpath = subpath.TrimStart('/');
            subpath = '/' + subpath;
            subpath = subpath.Substring(1);

            var client = GetClient();
            if (_type != AWSResourceTypeEnum.Invoices)
            {
                subpath = subpath.ToLower();
            }
            GetObjectRequest request = new GetObjectRequest()
            {
                BucketName = _olcAWS.GetFullBucketName(_setting.BucketName, _type, storeId),
                Key = subpath
            };

            var file = new S3ObjectFileContentInfo(client, request);
            if (file.Exists)
                return file;
        }

**Comment by ashishdhingra** [comment]
@fh-team22 It is not evident from the code snippet you shared that you might be reusing the same response steam. Are you reusing the `IFileInfo` object returned by `GetFileInfo()` in your application? If yes, then that's the potential cause of the issue. Please use the guidance provided earlier to investigate your application code that might be reusing the S3 object response stream causing the errors in the log.

In case application logic requires you to cache object contents, then either use `MemoryStream` copy to hold response contents or cache the file in local file system and have your application logic point to the file. Caching multiple S3 objects locally might not be a scalable approach and your should explore a better design.

I'm unsure what more guidance could be provided here, hence closing this issue.

**Comment by gregor-tusar** [comment]
I stumbled on this issue while implementing the `IFileInfo` interface, too.

The suggested solutions in [ashishdhingra comment](https://github.com/aws/aws-sdk-net/issues/1985#issuecomment-1058342071) all copy the whole file from S3 to memory and return it as MemoryStream, which in fact supports seeking. But the issue of that solution is that the whole object is downloaded from S3 into memory each time the seek occurs. This happens very often when you try to transfer video as browsers transfer the content by smaller parts. So those solutions are not optimal for bigger files or videos.

Here is an implementation of **seekable s3 stream** by [@mlhpdx](https://github.com/mlhpdx): [github.com/mlhpdx/seekable-s3-stream](https://github.com/mlhpdx/seekable-s3-stream)
