### ISSUE TITLE
What is the default port for S3 connection?

### ISSUE THREAD

**Issue by NJ261** [aws/aws-sdk-net#1994]
I am wondering which port is being used by S3 for the connections? Is it HTTPS 443? Is there a way to change it to the custom port? Thanks!

Sample code
```cs
var client = new AmazonS3Client(accessKey, secretKey, RegionEndpoint.GetBySystemName(selectedRegion))
var buckets = client.ListBuckets().Buckets;
```

Environment
SDK Version: AWSSDK.Core 3.7.6
Package Version: AWSSDK.S3 3.7.7.14

**Comment by ashishdhingra** [comment]
@NJ261 S3 supported protocols are:
- HTTP (port 80) connection
- HTTPS (port 443) connection

Kindly refer https://docs.aws.amazon.com/general/latest/gr/s3.html. Access ports cannot be changed.

Thanks,
Ashish
