### ISSUE TITLE
Method not found get_CryptoInstance() for some upgrade scenarios

### ISSUE THREAD

**Issue by ashovlin** [aws/aws-sdk-net#1998]
As reported in https://github.com/aws/aws-sdk-net/issues/1992, version [3.7.8 of AWSSDK.Core](https://www.nuget.org/packages/AWSSDK.Core/3.7.8) inadvertently introduced a breaking change in the `Amazon.Util.ICryptoUtil` namespace. 
```
Unhandled Exception: System.MissingMethodException: Method not found: 'Amazon.Util.ICryptoUtil Amazon.Util.CryptoUtilFactory.get_CryptoInstance()'
```
You may encounter this original error if you use a combination of:

1. A service package that was published _before_ version 3.7.8 of AWSSDK.Core as part of the release tagged [3.7.214.0](https://github.com/aws/aws-sdk-net/releases/tag/3.7.214.0) on February 22, 2022.
1. An AWSSDK.Core version greater than or equal to 3.7.8 but less than 3.7.9: `[3.7.8, 3.7.9)`.
1. Functionality that calls Core’s `CryptoUtils` from a service package, such as SQS or S3’s MD5 content verification.

You may mitigate this issue by upgrading to version [3.7.9 of AWSSDK.Core](https://www.nuget.org/packages/AWSSDK.Core/3.7.9), which was released as part of [3.7.232.0](https://github.com/aws/aws-sdk-net/releases/tag/3.7.232.0) on March 17, 2022. 

---
```
Unhandled Exception: System.MissingMethodException: Method not found: 'Amazon.Util.Internal.ICryptoUtil Amazon.Util.CryptoUtilFactory.get_CryptoInstance()'.
```

**However, you may encounter this new exception if you use a combination of:**

1. A service package that was published _between_ [3.7.214.0](https://github.com/aws/aws-sdk-net/releases/tag/3.7.214.0) on February 22, 2022 and [3.7.232.0](https://github.com/aws/aws-sdk-net/releases/tag/3.7.232.0) on March 17, 2022.
1. An AWSSDK.Core version 3.7.9 or later.
1. Functionality that calls Core’s `CryptoUtils` from a service package, such as SQS or S3’s MD5 content verification.

You may mitigate the issue by upgrading the service package(s) to versions from the [3.7.232.0](https://github.com/aws/aws-sdk-net/releases/tag/3.7.232.0) release or later.

**Comment by jvitkauskas** [comment]
Having same issue with AWSSDK.SQS 3.7.2.47 and AWSSDK.Core 3.7.10.11
