### ISSUE TITLE
Specifying region when using ServiceUrl

### ISSUE THREAD

**Issue by DizzyDeveloper** [aws/aws-sdk-net#1999]
## The Question

In localstack version 0.12.17 they introduced support for multi region request handling. Which is all well and good, however, I seem to be unable to specify the region I want to the sdk to use when connecting to localstack via the service url.
Now, we initial insert some data into localstack into the ap-southeast-2 region using the aws cli. However, when we then try to access this data via the sdk it cannot find it. Digging through the code it appears as if the sdk uses the default region of us-west-1 when you are using the ServiceUrl*****. 
So as a workaround I have simply updated the cli insertion code to use us-west-1 as well, doing that then it is all well and good. 
However, I would like to be able to connect to localstack via the ServiceUrl using ap-souteast-2. Is this possible, if so how can this be done?

*****: It does appear as if the sdk attempts to work out the region from ServiceUrl before falling back to the default region. However, I am not sure what the format of the ServiceUrl should be to work out the service url. I've tried http://ap-southeast-2.localstack:4566 but to no avail.

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @DizzyDeveloper,

Good morning.

Thanks for posting the guidance question. If you refer the [ClientConfig](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/Runtime/TClientConfig.html) API reference, for `RegionEndpoint` and `ServiceURL`, it states that `RegionEndpoint and ServiceURL are mutually exclusive properties. Whichever property is set last will cause the other to automatically be reset to null.`.  Similar issue https://github.com/aws/aws-sdk-net/issues/1781 was posted earlier which resulted in elaborated documentation. Unfortunately, we are unable to support `localstack` virtualized environment scenarios.

Thanks,
Ashish

**Comment by DizzyDeveloper** [comment]
Hi @ashishdhingra,

Yea I am aware of that that relation between RegionEndpoint and ServiceURL, which is all well and good, but was just wandering if there was a way around it already.
However, could you not support this localstack virtualization at a basic level by simply allowing someone to override the default region used by the sdk? An "advanced" feature of sorts?

Thanks,
DizzyDeveloper

**Comment by ashishdhingra** [comment]
> Hi @ashishdhingra,
> 
> Yea I am aware of that that relation between RegionEndpoint and ServiceURL, which is all well and good, but was just wandering if there was a way around it already. However, could you not support this localstack virtualization at a basic level by simply allowing someone to override the default region used by the sdk? An "advanced" feature of sorts?
> 
> Thanks, DizzyDeveloper

@DizzyDeveloper Unfortunately no.

**Comment by andy-g** [comment]
Just for anyone else stumbling onto this thread, I ran into the same issue where setting the `RegionEndpojnt` stopped requests going to localstack, and setting the `ServiceURL` remove all references to the region.

Turns out you can specify the `AuthenticationRegion`, which appears to work fine on localstack, and lets you set the `ServiceUrl` to point to localstack. I tested this with EventBridge& Lambda and it seemed to work fine.

**AuthenticationRegion** (https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/Runtime/TClientConfig.html)
> Gets and sets the AuthenticationRegion property. Used in AWS4 request signing, this is an optional property; change it only if the region cannot be determined from the service endpoint.

Credit to:
https://stackoverflow.com/questions/71403539/aws-net-sdk-how-to-specify-region-when-using-localstack
