### ISSUE TITLE
 AWSSDK.Extensions.NETCore.Setup 3.7.2 causing tests to be extremely slow

### ISSUE THREAD

**Issue by dannystommen** [aws/aws-sdk-net#2000]
## Description
we're using AWSSDK.Extensions.NETCore.Setup and since updating it to 3.7.2, running tests became extremely slow in our pipeline. On my local (windows) machine, everything still works as expected. In our pipeline, total time of tests increased from 5 seconds to 130 sec.

Find attached the test results

When looking at all tests, multiple tests take 16 seconds suddenly, like something is being locked. Some tests even take 32 sec. Nothing in between. So a lots of tests complete in milliseconds, a few tests take like 16 sec, and 1 or 2 tests take 32 sec.

### Environment
* SDK Version: .NET 6
* Package Version:  AWSSDK.Extensions.NETCore.Setup 3.7.2
* OS Info: Gitlab runner executing Docker image mcr.microsoft.com/dotnet/sdk:6.0
* Build Environment `dotnet test --configuration Release --filter Category=Unit --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-unit-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"`

---

This is a :bug: bug-report
[test-results.zip](https://github.com/aws/aws-sdk-net/files/8379510/test-results.zip)

**Comment by ashishdhingra** [comment]
Hi @dannystommen,

Good afternoon.

Would it be possible to share a sample code solution containing tests that target 3.7.1 and 3.7.2 respectively, in order for us to investigate the issue?

Thanks,
Ashish

**Comment by Scorpio59** [comment]
may be link to #1996 
we experience the same bug, it work well on local with SSO profile but it take longer with normal profile

**Comment by dannystommen** [comment]
@ashishdhingra I managed to create a sample. Can I sent you this via a DM/email instead of sharing the sample here? I stripped down one of our production projects, which I can not share here publically.

**Comment by ashishdhingra** [comment]
> @ashishdhingra I managed to create a sample. Can I sent you this via a DM/email instead of sharing the sample here? I stripped down one of our production projects, which I can not share here publically.

@dannystommen We need to come up with the minimal reproducible sample to investigate the issue (reference https://stackoverflow.com/help/minimal-reproducible-example). May be just a test case having issue!

**Comment by dannystommen** [comment]
@ashishdhingra I managed to make it minimal, find attached the zip file, with 1 single test in it.

I also managed to find the "cause".  Removing line 11-15 in the `Configuration.cs` file makes the test fast again. 

[test-aws-sdk-extensions-setup.zip](https://github.com/aws/aws-sdk-net/files/8464965/test-aws-sdk-extensions-setup.zip)

Let me know if this is suffiecient, or need anything als from my end.

**Comment by normj** [comment]
@dannystommen Can you describe your pipeline setup? Is it AWS CodeBuild or something else and how are credentials expected to be retrieved for the service clients?

**Comment by dannystommen** [comment]
> @dannystommen Can you describe your pipeline setup? Is it AWS CodeBuild or something else and how are credentials expected to be retrieved for the service clients?

It's running in gitlab. If you commit this code to a gitlab repo, it will automatically run the pipeline (gitlab-ci.yml is included).

Not sure what you mean with "how are credentials expected to be retrieved".

**Comment by dannystommen** [comment]
@ashishdhingra any updates on this?

**Comment by Hawxy** [comment]
>  The other issue doesn't appear to be related since user was getting different execution times due to way credentials were configured.

@ashishdhingra I'm the OP from that issue, that isn't true at all. Unfortunately I forgot to reply to that issue before it closed, but the problem still stands. It has nothing to do with credential configuration, simply changing the package version exposes the issue. I retested today and I still cannot update my packages to anything newer.

**Comment by zippo227** [comment]
I was able to fix it what that solution. Add this to your .json, of course merge it within a current AWS block where applicable without including the additional block. 

"AWS": {
    "DefaultsMode": "Standard"
  },

**Comment by dscpinheiro** [comment]
I'm going to resolve this as it seems to be the same issue as https://github.com/aws/aws-sdk-net/issues/2022. I haven't been able to reproduce using the latest version of the extensions package, but we'll take a look if the problem still exists.

FYI: I tried running your `test-aws-sdk-extensions-setup.zip` example in CodeBuild and did not see longer tests either.
