### ISSUE TITLE
How to throttle upload bandwidth for S3?

### ISSUE THREAD

**Issue by NJ261** [aws/aws-sdk-net#2001]
I have this sample code to upload the files to S3 bucket. When multiple file uploads are going on, it occupies the whole bandwidth and leaves nothing for the remaining applications. I see there is `max_bandwidth` parameter in aws-cli. I was wondering how can we throttle the bandwidth here. Appreciate your help. Thanks!

```cs
var transferUtility = new TransferUtility(AccessKey, SecretKey, RegionEndpoint.GetBySystemName(Region));
var uploadRequest = new TransferUtilityUploadRequest()
{
    BucketName = bucketName,
    FilePath = path,
    Key = keyName
};

await transferUtility.UploadAsync(uploadRequest);
```

Environment
SDK Version: AWSSDK.Core 3.7.6
Package Version: AWSSDK.S3 3.7.7.14

**Comment by ashishdhingra** [comment]
Hi @NJ261,

Good morning.

Thanks for opening guidance question. I do not see parameter such as `max_bandwidth` supported in the SDK. You may refer StackOverflow post https://stackoverflow.com/questions/20852423/bandwidth-throttling-for-s3-upload-using-aws-sdk for a workaround (not sure if it would work for your need), however, it uses `PutObjectRequest` instead. The `TransferUtilityUploadRequest` supports multipart upload and should optimize bandwidth throttling automatically.

Thanks,
Ashish

**Comment by NJ261** [comment]
Okay you mean `TransferUtilityUploadRequest` automatically splits the upload to multiple parts?

**Comment by ashishdhingra** [comment]
> Okay you mean `TransferUtilityUploadRequest` automatically splits the upload to multiple parts?

@NJ261 It depends on the `PartSize` property. Default value is 8MB. Refer https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpu-upload-object.html for an example.
