### ISSUE TITLE
Regarding DynamoDB SDK's default timeout

### ISSUE THREAD

**Issue by rui-ktei** [aws/aws-sdk-net#2005]
Hi, dear AWS SDK dev team,
So we've noticed that the SDK for DynamoDB actually has the default timeout for HttpClient as 100 seconds. This will cause significant latency occasionally because SDK will only retry after more than 1 minute.

If you read the documentation: https://aws.amazon.com/premiumsupport/knowledge-center/dynamodb-high-latency/

The first strategy mentioned is:

Reduce the request timeout settings: Tune the client SDK parameters requestTimeOut and clientExecutionTimeout to timeout and fail much faster (for example, after 50 milliseconds). This causes the client to abandon high latency requests after the specified time period and then send a second request that usually completes much faster than the first. For more information about timeout settings, see [Tuning AWS Java SDK HTTP request settings for latency-aware Amazon DynamoDB applications](https://aws.amazon.com/blogs/database/tuning-aws-java-sdk-http-request-settings-for-latency-aware-amazon-dynamodb-applications/).

Now, this makes me wonder that given this is the recommended practice to reduce latency, why not SDK adopt it by default? Right now, our team has to force DynamoDB SDK to adopt 100ms timeout and we have to be careful if any new service starts using SDK, it needs to configure the SDK with the correct timeout, which is a hassle.

Please correct me if I'm wrong in any of observations above and please guide me to the right path if you think what our team is doing is incorrect.

Thanks heaps!

**Comment by ashishdhingra** [comment]
Hi @rui-ktei,

Good afternoon.

Thanks for posting guidance question. The AWS SDK for .NET does not constrain the timeout value by default if not explicitly by user, and instead uses the default value of 100 seconds as specified by .NET [HttpClient.Timeout](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.timeout?view=net-6.0). You may try using the `DynamoDBClientConfig`'s `Timeout` value to suit your needs as mentioned by the https://aws.amazon.com/premiumsupport/knowledge-center/dynamodb-high-latency/. The DynamoDB request (or any other service's request) flows throw the internal Http request pipeline and different services have different baselined values to improve latency. Hence, SDK doesn't constrain the default value and leaves up to user to fine tune these values as per need.

Thanks,
Ashish

**Comment by rui-ktei** [comment]
Hi, @ashishdhingra 
Thank you for the reply.
I do understand that the SDK does not constraint the default HttpClient timeout value and it's up to the user to fine tune it. 

However, as SDK, in my opinion, it should provide some meaningful default value with best practice, so for most users they can just use SDK with minimum configuration and they also don't need to further fine tune it until they encounter more complex issues. It's like buying an apartment with furniture and live in without worrying about tweaking light switches.

For DyanmoDB SDK, if you read the official documentation https://aws.amazon.com/premiumsupport/knowledge-center/dynamodb-high-latency/, it suggests reducing the timeout to a relatively small value, so that DynamoDB can retry fast, which I believe can solve the most of occasional network timeout issues.

I'm not saying this is a bug of SDK. All I'm saying is from a user's perspective and I suggest that the SDK authors should consider revisiting this default value.

Thank you.
