### ISSUE TITLE
AWS Textract - document by S3 multi region access point

### ISSUE THREAD

**Issue by ildar-shamilov-clearscale** [aws/aws-sdk-net#2006]
I am using Textract with files in S3, this code works when i use bucket name.
But recently i  switched to MRAP.
After changing bucket name to MRAP ARN, i get error on start detection:
> Amazon.Textract.Model.InvalidParameterException: 'Request has invalid parameters'

 ```
var res = await client.StartDocumentTextDetectionAsync(
                new StartDocumentTextDetectionRequest
                {
                    DocumentLocation = new DocumentLocation
                    {
                        S3Object = new S3Object
                        {
                            Bucket = MRAP-ARN,
                            Name = path,
                        },
                    },
                    NotificationChannel = new NotificationChannel
                    {
                        SNSTopicArn = sns,
                        RoleArn = role,
                    },
                });
```

Any advice on this? Maybe there is workaround?

**Comment by ashishdhingra** [comment]
Hi @ildar-shamilov-clearscale,

Good morning.

Thanks for opening guidance issues. Looking at the API for [Textract: S3Object](https://docs.aws.amazon.com/textract/latest/dg/API_S3Object.html), the `Bucket` parameter of `S3Object` needs to be a valid bucket name and accepts the `[0-9A-Za-z\.\-_]*` pattern. Whereas, Multi-Region Access Point ARNs use the format `arn:aws:s3::<account-id>:accesspoint/<MRAP_alias>` as per [Making requests using a Multi-Region Access Point](https://docs.aws.amazon.com/AmazonS3/latest/userguide/MultiRegionAccessPointRequests.html). So it appears that you cannot use MRAP ARN for `Bucket` parameter, hence the **service API** is throwing `InvalidParameterException`. I'm unsure if there is a workaround at this time, there is no mention of MRAP support in AWS Textract documentation.

Thanks,
Ashish
