### ISSUE TITLE
AmazonS3Uri fails to parse S3 Uri

### ISSUE THREAD

**Issue by noam-bionicstork** [aws/aws-sdk-net#2008]
### Describe the bug

Attempt to instantiate an AmazonS3Uri object with an S3 Uri results in an exception

### Expected Behavior

An AmazonS3Uri object should be created, with `uri.Bucket` equals "my-bucket-name" and `uri.Key` equals "file-name"

### Current Behavior

Results in the following exception:
`System.ArgumentException: Invalid S3 URI - hostname does not appear to be a valid S3 endpoint`

### Reproduction Steps

`AmazonS3Uri uri = new AmazonS3Uri("s3://my-bucket-name/file-name");`

### Possible Solution

When running this exact line in Java it works fine. As can be seen in the sources of the Java SDK https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3URI.java
There is an If block at line 81 that handles the case where the Uri stars with "s3://" and if that condition is false they go to the regex check on the host in line 110. In the .NET SDK, it goes straight to that regex check, as can be seen in line 80 https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/S3/Custom/Util/AmazonS3Uri.cs

My suggestion is to add the same if block in the Java SDK

### AWS .NET SDK and/or Package version used

AWSSDK.S3 3.7.3.17

### Targeted .NET Platform

.NET 6

### Operating System and version

Ubuntu

**Comment by ashishdhingra** [comment]
Looking at the logic for  .NET [AmazonS3Uri](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/S3/Custom/Util/AmazonS3Uri.cs), it expects the URI to be the S3 regional endpoint URI for an S3 object, not the `s3://` schemed URI, as pointed in the issue description. This needs review with the team.

**Comment by ashovlin** [comment]
This should be addressed in AWSSDK.S3 v3.7.9.8 that was released today.
* https://www.nuget.org/packages/AWSSDK.S3/3.7.9.8
* https://github.com/aws/aws-sdk-net/releases/tag/3.7.282.1
