### ISSUE TITLE
Split SDK into smaller API set

### ISSUE THREAD

**Issue by neurospeech** [aws/aws-sdk-net#201]
AWS SDK dll is 5MB, and often it is the largest among any other assemblies for web projects, loading and initializing is hurting website startup time so badly.

It would be nice to have individual AWS API as separate assembly, so we can integrate as much we need. For example, we are only using S3 and SES api.

**Comment by normj** [comment]
That is exactly what we are working on now. You can check out the modularization branch to see the work in progress and the following blog posts.

http://blogs.aws.amazon.com/net/post/Tx2JT7AYCL2F6CB/Upcoming-Modularization-of-the-AWS-SDK-for-NET
http://blogs.aws.amazon.com/net/post/Tx2Z61ZXR99PHJJ/Update-on-Modularization-of-the-SDK

**Comment by normj** [comment]
The new modularized SDK was pushed to NuGet today. You can check out our blog post to learn more. 

http://blogs.aws.amazon.com/net/post/Tx3STYSCLGOJWWI/Modularization-Released-to-NuGet-in-Preview

**Comment by pthangapandian** [comment]
I understand that you guys are working on release and documentation, but
what is the upgrade/support plan for existing single SDK model? Is that
mean that we should upgrade to this model right away and upgrades/bug fixes
only be released in modularized SDK going forward? Any update you provide
help us choose the right upgrade path. Thanks in advance.

On Thu, Apr 30, 2015 at 7:50 PM, normj <notifications@github.com> wrote:

> The new modularized SDK was pushed to NuGet today. You can check out our
> blog post to learn more.
>
>
> http://blogs.aws.amazon.com/net/post/Tx3STYSCLGOJWWI/Modularization-Released-to-NuGet-in-Preview
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aws/aws-sdk-net/issues/201#issuecomment-98003512>.
>



-- 
*Pandi Thangapandian*
*Associate Director of Development*
The Common Application
3003 Wilson Blvd, 10th Floor, Ste 1000
Arlington, VA 22201
*703.236.2761*
pthangapandian@commonapp.org
www.commonapp.org
facebook <https://www.facebook.com/commonapp> | twitter
<https://twitter.com/CommonApp> | blog <http://blog.commonapp.org/> |
youtube <https://www.youtube.com/user/CommonAppMedia>

**Comment by normj** [comment]
We chose to have as few breaking changes in V3 as reasonably possible so that developers would find it easy to move to. We haven't finalized our future plans for the existing V2 SDK but it will start getting less service updates once V3 leaves preview.

We do consider V3 production ready today and any issues found with it will be addressed with the same urgency as the existing V2. Service updates will be slightly delayed as we test out our new release process for V3. If you can I highly encouraging you to move to V3 now.

**Comment by amitatgit** [comment]
I am trying to upgrade to modularised version of sdk and having trouble with a project which uses AWS DynamoDB Session Provider (AWS.SessionProvider.dll). This dll still has a dependency on AWSSDK.dll. If i add AWSSDK.dll then it conflicts with AWSSDK.Core.dll.

Any suggestions?
