### ISSUE TITLE
Unity3D Issue

### ISSUE THREAD

**Issue by aredag** [aws/aws-sdk-net#2012]
### Describe the bug

Hello. 
So basically im trying to connect to Amazon but receiving this error 

**HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.**

### Expected Behavior

Extepcted behaviour to connect and see list of buckets

### Current Behavior

Receiving error - **HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.**

### Reproduction Steps

Just use this code 

public class TestAWS : MonoBehaviour
{
    AmazonS3Client s3Client = new AmazonS3Client();

    async void Start()
    {
        var credentials = new BasicAWSCredentials("key", "key");
        s3Client = new AmazonS3Client(credentials, RegionEndpoint.USEast1);
        var res = await s3Client.ListBucketsAsync();
    }

    private static async Task<ListBucketsResponse> MyListBucketsAsync(IAmazonS3 s3Client)
    {
      return await s3Client.ListBucketsAsync();
    }
}

### AWS .NET SDK and/or Package version used

aws-sdk-netstandard2.0-3.7.262.0

### Targeted .NET Platform

2.0 Unity

### Operating System and version

Windows 11

**Comment by ashishdhingra** [comment]
Hi @aredag,

Good morning.

Could you please share the following:
- Version of AWS SDK used (you may list down the NuGet packages).
- How are your credentials configured? (refer [Credential and profile resolution](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/creds-assign.html) for details on how credentials are resolved)
- Share the verbose logs (refer https://github.com/aws/aws-sdk-net/issues/1759#issue-758694510 on how to enable it for .NET Core projects).
- You may examine network request via Fiddler (if possible) to see the exact Http error.

The operation you are doing is a basic operation and the error that you shared does not give enough information for troubleshooting purposes. In case you are new to using AWS SDK, it is advisable that you refer [AWS SDK for .NET developer guide](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/welcome.html).
