### ISSUE TITLE
TransferUtilityUploadDirectoryRequest is missing SSE-C properties

### ISSUE THREAD

**Issue by KarlKl** [aws/aws-sdk-net#2017]
### Describe the feature

TransferUtilityUploadDirectoryRequest is missing the three SSE-C properties:
- ServerSideEncryptionCustomerMethod
- ServerSideEncryptionCustomerProvidedKey
- ServerSideEncryptionCustomerProvidedKeyMD5

### Use Case

I want to use `UploadDirectoryAsync` with SSE-C.

### Proposed Solution

Add the properties and forward them in the UploadDirectoryCommand to the TransferUtilityUploadRequest.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

AWSSDK.S3 3.7.8.25

### Targeted .NET Platform

.NET 6

### Operating System and version

Ubuntu

**Comment by ashishdhingra** [comment]
[PutObjectRequest](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/S3/Custom/Model/PutObjectRequest.cs) and other TransferUtility upload request objects support the said properties. Could be simple fix as suggested by user. Needs review with team.

@KarlKl Thanks for the feature request. Feel free to contribute by submitting the PR.

**Comment by ashovlin** [comment]
This has been released in https://www.nuget.org/packages/AWSSDK.S3/3.7.9 on 05/06/22.
