### ISSUE TITLE
AmazonUnmarshallingException - The string was not recognized as a valid DateTime

### ISSUE THREAD

**Issue by nathanaeljones** [aws/aws-sdk-net#202]
AWSSDK v 2.3.34.0  

Stacktrace: https://gist.github.com/anonymous/412ca79913f5bb4f46d6

Origin: https://stackoverflow.com/questions/29953711/imageresizer-and-s3reader2-the-string-was-not-recognized-as-a-valid-datetime

```
[FormatException: The string was not recognized as a valid DateTime. There is an unknown word starting at index 26.]
   System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles) +10841066
   System.Convert.ToDateTime(String value, IFormatProvider provider) +72
   System.String.System.IConvertible.ToDateTime(IFormatProvider provider) +10
   System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider) +10875023
   Amazon.S3.Model.Internal.MarshallTransformations.S3Transforms.ToDateTime(String value) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.S3\Model\Internal\MarshallTransformations\S3Transforms.cs:79
   Amazon.S3.Model.Internal.MarshallTransformations.GetObjectResponseUnmarshaller.UnmarshallResult(XmlUnmarshallerContext context, GetObjectResponse response) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.S3\Model\Internal\MarshallTransformations\GetObjectResponseUnmarshaller.cs:83
   Amazon.S3.Model.Internal.MarshallTransformations.GetObjectResponseUnmarshaller.Unmarshall(XmlUnmarshallerContext context) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.S3\Model\Internal\MarshallTransformations\GetObjectResponseUnmarshaller.cs:38
   Amazon.Runtime.Internal.Transform.XmlResponseUnmarshaller.Unmarshall(UnmarshallerContext input) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Internal\Transform\ResponseUnmarshallers.cs:94
   Amazon.Runtime.Internal.Transform.S3ReponseUnmarshaller.Unmarshall(UnmarshallerContext input) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Internal\Transform\ResponseUnmarshallers.cs:179
   Amazon.Runtime.Internal.Transform.ResponseUnmarshaller.UnmarshallResponse(UnmarshallerContext context) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Internal\Transform\ResponseUnmarshallers.cs:62
   Amazon.Runtime.Internal.Unmarshaller.UnmarshallResponse(UnmarshallerContext context, IRequestContext requestContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\Handlers\Unmarshaller.cs:206
   Amazon.Runtime.Internal.Unmarshaller.Unmarshall(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\Handlers\Unmarshaller.cs:134
 
[AmazonUnmarshallingException: Error unmarshalling response back from AWS. ]
   Amazon.Runtime.Internal.Unmarshaller.Unmarshall(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\Handlers\Unmarshaller.cs:149
```

**Comment by PavelSafronov** [comment]
Looks like the problem is with parsing the "Expires" header for this particular object. What is the format of this header for the problematic images? How was this header configured?

**Comment by karlgram** [comment]
Thanks for the reply
S3: http://media.fotoapparatuur.nl/IG/85070.jpg
ImageResizer not OK: http://test.fotoapparatuur.nl:42424/s3/media.fotoapparatuur.nl/IG/85070.jpg
S3: http://media.fotoapparatuur.nl/IG/70573.jpg
ImageResizer OK: http://test.fotoapparatuur.nl:42424/s3/media.fotoapparatuur.nl/IG/70573.jpg

**Comment by gokarnm** [comment]
How did you configure the Expires header for the object? The Expires header for the first object is set to *Mon, 28 Apr 2025 21:50:04* ***G4T*** which causes the unmarshaller to fail.

**Comment by gokarnm** [comment]
[Here](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.21) is the link for Expires header spec.

**Comment by karlgram** [comment]
The G4T is the problem. This is the result of an old bug in my code which transfers the image to S3. Apparently it is possible to add an image to S3 with an invalid expiry date. This went undetected until now.

**Comment by nathanaeljones** [comment]
Should AWSSDK fail to access blobs with an invalid Expires header? I have no opinion on this.

**Comment by PavelSafronov** [comment]
I'm hesitating to swallow parsing exceptions in this case. The consumer will receive incorrect data (likely DateTime.Min) and will not be aware that there is an issue.
Considering that the Expires header is used by caching systems and having an incorrect value can actually cost the owner money (more calls to S3), I think the correct course of action is to notify the caller about the incorrect header as soon as possible.

**Comment by nathanaeljones** [comment]
Fair enough, hopefully this thread will shed light on the issue for anyone else with the same issue.

**Comment by gokarnm** [comment]
A fix is now available for this issue, check this [issue](https://github.com/aws/aws-sdk-net/issues/253) for more details.
