### ISSUE TITLE
How can i start contributing here

### ISSUE THREAD

**Issue by sezhiyant** [aws/aws-sdk-net#203]
Hi All,

I am new member to this group. Am not sure if this is the right forum to post this.  I had a basic question about contributing to this group.

Is there a product backlog or something where i can pick something i can contribute ?
Or any suggestions where i could start from.

Regards,
Sezhiyan

**Comment by jimfl** [comment]
Hi! 

The open items in the issues labeled "Feature Request" could be considered a public backlog for the SDK.

Keep in mind that a good deal of the code in the SDK is generated, and that some solutions may require code generation (The code generator is in the ServiceClientGenerator folder.

Thanks for your interest!

**Comment by sezhiyant** [comment]
Thanks Jim.
