### ISSUE TITLE
Unity using .NET 4.x for GameLift Integration breaks other integrated AWS Services

### ISSUE THREAD

**Issue by shfuzetech** [aws/aws-sdk-net#2030]
### Describe the bug

I have a project in Unity 2021.3.2f1 which I have successfully integrated the following AWS Services: 

- SSO
- DynamoDBv2
- CognitoIdentity
- Lambda

I have now started the process of integrating AWS GameLift using the Unity Engine plugin provided on AWS but when I update the project to use .NET 4.x the AWS SDK no longer finds the plugin .dll files for the service mentioned above. My Unity Console window has multiple warnings for each service.

### Expected Behavior

No console/compiler errors. Able to use currently integrated services as before GameLift integration started.

### Current Behavior

As soon as I update the project to use .NET 4.x via the AWS GameLIft Unity plugin settings button my console is flooded with warnings like the following for each of the other services I am required to use: 

`Could not resolve field token 0x04000005, due to: Could not load type of field 'Amazon.SSO.AmazonSSODefaultConfiguration:<Standard>k__BackingField' (0) due to: Could not resolve type with token 01000024 from typeref (expected class 'Amazon.Runtime.IDefaultConfiguration' in assembly 'AWSSDK.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604') assembly:AWSSDK.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604 type:Amazon.Runtime.IDefaultConfiguration member:(null) assembly:C:\Users\stegh\Documents\GitHub\HivePlatform\Assets\Plugins\AWSSDK.SSO.dll type:AmazonSSODefaultConfiguration member:(null)
`

If I ignore the warnings and enter Play mode and run a method which uses another AWS service I receive the following error:

`System.InvalidOperationException: Assembly AWSSDK.SSOOIDC could not be found or loaded. This assembly must be available at runtime to use Amazon.Runtime.SSOAWSCredentials, AWSSDK.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: Failure has occurred while loading a type.
  at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_gc_wbarrier_generic_nostore_internal(intptr)
  at (wrapper write-barrier) System.Object.wbarrier_conc(intptr)
  at (wrapper managed-to-native) System.Reflection.RuntimeConstructorInfo.InternalInvoke(System.Reflection.RuntimeConstructorInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x00005] in <6073cf49ed704e958b8a66d540dea948>:0 
   --- End of inner exception stack trace ---
 `

### Reproduction Steps

Download and install Unity 2021.3.2f1
Navigate to Unity>Wundow>Package Manager and:
1. remove Version Control Package
2. delete version of Newtonsoft.json shipped with Unity (ships a v13 of this package but GameLift requires v12)

Install AWS GameLift Plugin for Unity
Add any other AWS service .dll (e.g. AWS.SSO.dll)
View warnings in Console window

### Additional Information/Context

From other sources online, I have removed the Version Control package from Unity as Unity ships Newtonsoft.json v13 but GameLift required v12.

I then delete the shipped Newtonsoft package from PackageCache folder. I add in the required version of Newtonsoft.json from [here](https://github.com/jilleJr/Newtonsoft.Json-for-Unity/releases/tag/12.0.302).

### AWS .NET SDK and/or Package version used

AWSSDK.Core 3.7.2.3 (shipped with latest version of GameLift Unity Plugin
AWSSDK.CognitoIdentity 3.7.0.166
AWSSDK.DynamoDBv2 3.7.3.42
AWSSDK.IdentityManagement 3.7.2.146
AWSSDK.Lambda 3.7.13.8
AWSSDK.SSO 3.7.0.166
AWSSDK.SSOAdmin 3.7.0.167
AWSSDK.SSOOIDC 3.7.0.166

### Targeted .NET Platform

.NET 4.5

### Operating System and version

Windows 11 v 10.0.22000 Build 22000

**Comment by shfuzetech** [comment]
To note: I have also tried moving the non-GameLift service .dll files to the GameLift package directory but the result is the same.

**Comment by ashishdhingra** [comment]
Hi @shfuzetech,

Starting with version 3.5 of the AWS SDK for .NET, projects using Unity 2018.1 or later should target the .NET Standard 2.0 release of the SDK. You can find additional information in the developer guide: [Unity support](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/unity-special.html) and [Migrating your Unity application](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/net-dg-v35.html#net-dg-v35-changes-unity).

Please try using the .NET Standard 2.0 version of the AWS SDK for .NET (version 3.5 or later).

Thanks,
Ashish

**Comment by shfuzetech** [comment]
> Hi @shfuzetech,
> 
> Starting with version 3.5 of the AWS SDK for .NET, projects using Unity 2018.1 or later should target the .NET Standard 2.0 release of the SDK. You can find additional information in the developer guide: [Unity support](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/unity-special.html) and [Migrating your Unity application](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/net-dg-v35.html#net-dg-v35-changes-unity).
> 
> Please try using the .NET Standard 2.0 version of the AWS SDK for .NET (version 3.5 or later).
> 
> Thanks, Ashish

Hi Ashish,

Thank you so much for your response. I spent some time stripping out the AWS Unity Plugin and have integrated the required plugins for GameLift myself and it is working fine.

I only saw today, while searching for an unrelated issue, that the Unity Plugin is not obsolete. It is very confusing that this plugin is recommended for Unity developers when it was made obsolete over 2 years ago. It is also very much a waste of time when a lot of the example scripts/methods for Unity .NET applications is obsolete and I have to resort to the community on SO/Unity Forums for resolutions /rant.

Thank you for your time. Please feel free to close this bug report.
