### ISSUE TITLE
Modular SQS client throws exception when mutiple threads attempt to read from a queue

### ISSUE THREAD

**Issue by bkrchristopher** [aws/aws-sdk-net#204]
The following NUint test fixture reproduces the issue and comments show explain the root cause of the problem.

 [TestFixture]
    public class ReproSqsThreadingIssue
    {
        [Test]
        public void ReproAwsConcurrencyBugTest()
        {
            var sqs = new AmazonSQSClient(RegionEndpoint.USWest2);
            var queueName = "concurrency-bug";
            var createRespose = sqs.CreateQueue(new CreateQueueRequest(queueName));

            while (true)
            {
                var listQueuesResponse = sqs.ListQueues(queueName);
                var foundQueueList = listQueuesResponse.QueueUrls.FirstOrDefault(s => s.Equals(createRespose.QueueUrl));
                {
                    if (foundQueueList != null)
                    {
                        break;
                    }
                }
                Thread.Sleep(new TimeSpan(0,0,10));
            }

            var task1 = Task.Run(() => GetSqsMessages(sqs, createRespose.QueueUrl));
            var task2 = Task.Run(() => GetSqsMessages(sqs, createRespose.QueueUrl));
            var task3 = Task.Run(() => GetSqsMessages(sqs, createRespose.QueueUrl));
            var task4 = Task.Run(() => GetSqsMessages(sqs, createRespose.QueueUrl));
            var task5 = Task.Run(() => GetSqsMessages(sqs, createRespose.QueueUrl));

            Task.WaitAny(task1, task2, task3, task4, task5);
        }
        public async Task GetSqsMessages(AmazonSQSClient sqs, string url)
        {
            while (true)
            {
                try
                {
                    var response = await sqs.ReceiveMessageAsync(new ReceiveMessageRequest(url) {WaitTimeSeconds = 0});
                    if (response.HttpStatusCode != HttpStatusCode.OK)
                        break;
                }
                catch (Exception e)
                {
                    Console.WriteLine(e.Message);
                    Console.WriteLine(e.StackTrace);
                }
            }
        }
    }
}

**Comment by normj** [comment]
Thanks for reporting, I was able to reproduce the error and will work on getting a fix out soon.

**Comment by bkrchristopher** [comment]
Great!  Happy to see the quick response time.

**Comment by bkrchristopher** [comment]
I've got a test and a fix for this.  I'll submit a pull request.  Use or not as you like.

**Comment by normj** [comment]
Thanks but I have a the fix. I'm just running our tests before releasing. I'll have the fix released by the end of the day.

**Comment by bkrchristopher** [comment]
ok, I appreciate the effort.

**Comment by normj** [comment]
I updated the AWSSDK.Core package to 3.0.0.1 which contains the fix. Looks like NuGet will by default fetch the lowest version specified for its dependencies. So if you just add a reference to AWSSDK.SQS it will fetch 3.0.0.0 Core from NuGet. I'm in the process of updating the minimum version of Core for the service packages to 3.0.0.1 but if you want the update now just update the Core. From the NuGet Console you can run:

Update-Package AWSSDK.Core -pre

**Comment by bkrchristopher** [comment]
Excellent, I'll try it now.

On Tue, May 5, 2015 at 4:55 PM, Norm Johanson <notifications@github.com>
wrote:

> I updated the AWSSDK.Core package to 3.0.0.1 which contains the fix. Looks
> like NuGet will by default fetch the lowest version specified for its
> dependencies. So if you just add a reference to AWSSDK.SQS it will fetch
> 3.0.0.0 Core from NuGet. I'm in the process of updating the minimum version
> of Core for the service packages to 3.0.0.1 but if you want the update now
> just update the Core. From the NuGet Console you can run:
>
> Update-Package AWSSDK.Core -pre
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aws/aws-sdk-net/issues/204#issuecomment-99264356>.
>



-- 
*"Education must enable young people to effect what they have recognized to
be right, despite hardships, despite dangers, despite inner skepticism,
despite boredom, and despite mockery f*r*om the world. . . ."*
*Kurt Hahn, Founder of Outward Bound.*

**Comment by normj** [comment]
The SQS package along with all the other service packages have been updated to require the new core package with the bug fix. Thanks again for letting us know about the bug.
