### ISSUE TITLE
Make FallbackCredentialsFactory public as it has useful functionality

### ISSUE THREAD

**Issue by superlogical** [aws/aws-sdk-net#206]
I want to be able to grab out the Credentials based on FallbackCredentialsFactory, but it's internal so I had to copy the source code for the class into my project.

Also, can we move it to it's own file so that it is easier to find if you do a google search?

https://github.com/aws/aws-sdk-net/blob/master/AWSSDK_DotNet35%2FAmazon.Runtime%2FAWSCredentials.cs#L1086

**Comment by jimfl** [comment]
Added to https://github.com/aws/aws-sdk-net/blob/master/FEATURE_REQUESTS.md
