### ISSUE TITLE
Support for IWebProxy instead of WebProxy

### ISSUE THREAD

**Issue by eocron** [aws/aws-sdk-net#2064]
### Describe the feature

Settings should support IWebProxy interface instead of currently implemented WebProxy support, to allow usage of default proxy in .NET

### Use Case

For now I need to explicitly specify my default proxy, which can change over time and I cant use `WebRequest.DefaultWebProxy` in code because it returns `WebProxyWrapper ` sometimes.

        var configsS3 =
            new AmazonS3Config
            {
                ServiceURL = settings.ServiceUrl,
                ForcePathStyle = true,
                MaxErrorRetry = 0
            };
        if (proxy != null)
        {
            configsS3.SetWebProxy(proxy);//<- this one here accepts only WebProxy, cant use IWebProxy
        }

### AWS .NET SDK and/or Package version used

AWSSDK 3.7.7.26

### Targeted .NET Platform

.NET 6

### Operating System and version

Windows 10, CentOS 8

**Comment by ashishdhingra** [comment]
Hi @eocron,

Good morning.

Thanks for submitting feature request. Could you point me to the use case where `AmazonS3Config.SetWebProxy()` is pointing to `WebProxy`. Looking at `netstandard` version of [ClientConfig.SetWebProxy()](https://github.com/aws/aws-sdk-net/blob/b84db13ad3de702cd0fd810c468855775adde1af/sdk/src/Core/Amazon.Runtime/_netstandard/ClientConfig.cs#L56), it appears to accept `IWebProxy` parameter.

Thanks,
Ashish
