### ISSUE TITLE
Is it possible to merge https://github.com/aws/aws-sdk-net/pull/1962?

### ISSUE THREAD

**Issue by Edric-Li** [aws/aws-sdk-net#2066]
### Describe the feature

I am having problems with special symbols that cannot be uploaded. This Pull Request fixes the issue, if nothing else affects it, is it possible to merge the request and release a new version?

### Use Case

.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

AWSSDKS3 3.7.8.13

### Targeted .NET Platform

Net 6

### Operating System and version

Net 6

**Comment by ashishdhingra** [comment]
@Edric-Li I will bring this attention to the team to review the pull request https://github.com/aws/aws-sdk-net/pull/1962.

**Comment by Edric-Li** [comment]
@ashishdhingra Ok, thanks!

**Comment by Edric-Li** [comment]
Is this PR merged?

**Comment by Edric-Li** [comment]
Can you give priority to this problem, thank you very much.

**Comment by dscpinheiro** [comment]
The PR was closed so I'll close this issue. 

@peterrsongg mentioned he made a fix that could help with the original problem, please follow the updates on #1943
