### ISSUE TITLE
Error on initializing instance of DynamoDBContextConfig class in V3

### ISSUE THREAD

**Issue by amitatgit** [aws/aws-sdk-net#209]
Getting exception on initializing DynamoDBContextConfig class.

Code:
  var xx = new DynamoDBContextConfig()
            {
                TableNamePrefix = "Test",
            };

Exception:
An unhandled exception of type 'System.NullReferenceException' occurred in AWSSDK.DynamoDBv2.dll

Additional information: Object reference not set to an instance of an object.

**Comment by normj** [comment]
Thanks for reporting. I was able to reproduce this and I'm working on the fix now.

**Comment by normj** [comment]
I have just pushed version 3.0.0.3 of the DynamDB package to nuget that fixes the issue. Thanks again for reporting the issue.
