### ISSUE TITLE
Exception thrown: 'System.UnauthorizedAccessException' in System.IO.FileSystem.dll

### ISSUE THREAD

**Issue by yogeshwar-bollu** [aws/aws-sdk-net#2090]
### Describe the bug

I am working on UWP .net desktop application, I am trynna work with AWS SDK S3 to perform upload nad download data from S3 bucket. By following a AWS documentations Its not configuring it. This is how I am accessing it 

I ran this below code in App.xaml.cs 
```C#
var amazonS3Config = new AmazonS3Config
            {
                RegionEndpoint = RegionEndpoint.APNortheast1
            };
            var amazonClient = new AmazonS3Client(Constants.ACCESS_KEY, Constants.SECRET_KEY, amazonS3Config);
            amazonClient.Config.Validate();
```

I ma new to it can someone guide me with this 
Thanks in advance

### Expected Behavior

By running a UWP application it has work connect with AWS or has to configure with provided credentials

### Current Behavior

These are the execptions 

Exception thrown: 'System.UnauthorizedAccessException' in System.IO.FileSystem.dll

Exception thrown: 'System.IO.FileNotFoundException' in System.Private.CoreLib.dll

### Reproduction Steps

This is code in App.xaml.cs

```C#
namespace QMA_UWP
{
    sealed partial class App : Application
    {


        public static IAmazonS3 s3Client;
        
        public App()
        {
            this.InitializeComponent();
            this.Suspending += OnSuspending;


            var amazonS3Config = new AmazonS3Config
            {
                RegionEndpoint = RegionEndpoint.APNortheast1
            };
            var amazonClient = new AmazonS3Client(Constants.ACCESS_KEY, Constants.SECRET_KEY, amazonS3Config);
            amazonClient.Config.Validate();

         
        }
```

This is in the code of getting list in s3 bucket

```C#
using Amazon;
using Amazon.S3;
using Amazon.S3.Model;
using System;
using System.Threading.Tasks;

namespace Amazon.DocSamples.S3
{
    class ListObjectsVersioningEnabledBucketTest
    {
        static string bucketName = "stg-survey-resource-download";
        private static readonly RegionEndpoint bucketRegion = RegionEndpoint.APNortheast1;
        private static IAmazonS3 s3Client;


        public static void GetList()
        {
            s3Client = new AmazonS3Client(bucketRegion);
            s3Client.Config.Validate();

            GetObjectListWithAllVersionsAsync().Wait();
           
        }

        static async Task GetObjectListWithAllVersionsAsync()
        {
            try
            {
                ListVersionsRequest request = new ListVersionsRequest()
                {
                    BucketName = bucketName,

                    MaxKeys = 2
                };
                do
                {
                    
                    ListVersionsResponse response = await s3Client.ListVersionsAsync(request);
                    // Process response.
                    foreach (S3ObjectVersion entry in response.Versions)
                    {
                        Console.WriteLine("key = {0} size = {1}",
                            entry.Key, entry.Size);
                    }

                    if (response.IsTruncated)
                    {
                        request.KeyMarker = response.NextKeyMarker;
                        request.VersionIdMarker = response.NextVersionIdMarker;
                    }
                    else
                    {
                        request = null;
                    }
                } while (request != null);
            }
            catch (AmazonS3Exception e)
            {
                Console.WriteLine("Error encountered on server. Message:'{0}' when writing an object", e.Message);
            }
            catch (Exception e)
            {
                Console.WriteLine("Unknown encountered on server. Message:'{0}' when writing an object", e.Message);
            }
        }
    }
}
```

### AWS .NET SDK and/or Package version used

AWSSDK.S3 3.7.9.42
AWSSDK.Extensions.NETCore.Setup 3.7.2
AWSSDK.Core 3.7.12.24

### Targeted .NET Platform

.NET Framework 4.0

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment]
@yogeshwar-bollu Just curious if the same code if written as a console application works fine for you or not. Could you please confirm?

**Comment by yogeshwar-bollu** [comment]
@ashishdhingra  Yes, I am getting list of objects from S3 bucket in console, but the same thing when try to do it in UWP I am getting exception like above 
Is there any configuration I need to do in UWP

**Comment by ashishdhingra** [comment]
> @ashishdhingra Yes, I am getting list of objects from S3 bucket in console, but the same thing when try to do it in UWP I am getting exception like above Is there any configuration I need to do in UWP

@yogeshwar-bollu Since listing objects work in console application for you, this doesn't appear to be the SDK issue. The issues related to UWP should be raised in appropriate forums. The StackOverflow post https://stackoverflow.com/questions/33082835/windows-10-universal-app-file-directory-access might be helpful.

**Comment by yogeshwar-bollu** [comment]
@ashishdhingra Got it Thanks
