### ISSUE TITLE
Ex :"Your socket connection to the server was not read from or written to within the timeout period"(short issue description)

### ISSUE THREAD

**Issue by elmehdi57** [aws/aws-sdk-net#2092]
### Describe the bug

I want to load an audio file via the PutObjectAsync() method but after a while this exception is thrown ex = {"Your socket connection to the server was not read from or written to within the timeout period."}, otherwise for .txt file the method works very well but once I load a file other than .txt the exception is thrown.
**the size of my tx file: 2MB => works
the size of my mp3 file: 700Ko => does not work**

my code:
_using (var inputStream = new MemoryStream())
{
await request.File.CopyToAsync(inputStream);
var putObjectRequest = new PutObjectRequest()
{
BucketName = "<my_bucket_name>",
Key = "<file_key>",
InputStream = inputStream,
};
await s3Client.PutObjectAsync(putObjectRequest);
}

### Expected Behavior

Upload success

### Current Behavior

Throw Exception Ex :"Your socket connection to the server was not read from or written to within the timeout period"(short issue description)

### Reproduction Steps

my code:
_using (var inputStream = new MemoryStream())
{
await request.File.CopyToAsync(inputStream);
var putObjectRequest = new PutObjectRequest()
{
BucketName = "<my_bucket_name>",
Key = "<file_key>",
InputStream = inputStream,
};
await s3Client.PutObjectAsync(putObjectRequest);
}

### AWS .NET SDK and/or Package version used

"AWSSDK.S3" Version="3.7.9.42"

### Targeted .NET Platform

.Net core 6

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment]
Hi @elmehdi57,

Good morning.

Could you please share the sample solution with reproducible code? Specifically, how is the `request` object in call `request.File.CopyToAsync(inputStream)` populated?

Thanks,
Ashish
