### ISSUE TITLE
Unable to construct a new AmazonDynamoDBClient

### ISSUE THREAD

**Issue by nthornton2010** [aws/aws-sdk-net#2099]
### Describe the bug

When trying to construct a new AmazonDynamoDBClient, I'm receiving the following error after to updating to the latest version of the AWSSDK .Net packages.

`System.TypeLoadException: 'Could not load type 'Amazon.Runtime.IDefaultConfiguration' from assembly 'AWSSDK.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604'.'`

This is the portion of the StackTrace that takes place within the AWSSDK:
```
at Amazon.DynamoDBv2.AmazonDynamoDBConfig..ctor()
   at Amazon.DynamoDBv2.AmazonDynamoDBClient..ctor(AWSCredentials credentials, RegionEndpoint region)
```

### Expected Behavior

A new instance of AmazonDynamoDBClient to be created.

### Current Behavior

The AmazonDynamoDBClient constructor threw the following errror:
`System.TypeLoadException: 'Could not load type 'Amazon.Runtime.IDefaultConfiguration' from assembly 'AWSSDK.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604'.'`

### Reproduction Steps

```
public void Sample()
{
    string region = "us-east-1";
    string accessKey = "[REPLACE WITH A WORKING ACCESS KEY]";
    string secretKey = "[REPLACE WITH A WORKING SECRET KEY]";
    Amazon.Runtime.BasicAWSCredentials basicCredentials = new Amazon.Runtime.BasicAWSCredentials(accessKey, secretKey);

    //It errors here
    using (var client = new Amazon.DynamoDBv2.AmazonDynamoDBClient(basicCredentials, Amazon.RegionEndpoint.GetBySystemName(region)))
    {
        //TODO: Add code when its working
    }
}
```

### AWS .NET SDK and/or Package version used

AWSSDK.Core --- 3.7.12.29
AWSSDK.DynamoDBv2 --- 3.7.4.7

### Targeted .NET Platform

.Net Framework 4.8

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment]
@nthornton2010 Somehow, I'm unable to reproduce the issue. I tested it while creating a new .NET Framework 4.8 Console application and using `AWSSDK.DynamoDBv2` version `3.7.4.7`. Could you check that you project file does not have any references to the old AWSSDK.Core version? Also try cleaning and rebuilding your solution.

**Comment by nthornton2010** [comment]
@ashishdhingra I just tried cleaning/rebuilding, ran multiple git clean commands to delete anything that should no longer be in my repo, and double-checked that there are no references to legacy versions of the DLL. I did realize that I forgot to mention that the application I'm working in is in VB.Net and not C#. I included C# code in the snippet because nobody uses VB.Net anymore and I didn't think it would matter, but maybe it does.

I took a look at the source code for the AmazonDynamoDBClient and tried making a tweak to my code. I'm still getting the error but now I'm a bit closer to it. Instead of passing the region in, I'm now creating an instance of AmazonDynamoDBConfig. This constructor is where the error is being thrown from.

```
            'It now errors here
            Dim config = New AmazonDynamoDBConfig() With {.RegionEndpoint = Amazon.RegionEndpoint.GetBySystemName("us-east-1")}

            Dim accessKey As String = "[REPLACE WITH A WORKING ACCESS KEY]"
            Dim secretKey As String = "[REPLACE WITH A WORKING SECRET KEY]"
            Dim basicCredentials As Amazon.Runtime.BasicAWSCredentials = New Amazon.Runtime.BasicAWSCredentials(accessKey, secretKey)

            Using client = New Amazon.DynamoDBv2.AmazonDynamoDBClient(basicCredentials, config)
                'TODO: Add code when its working
            End Using
```

**Comment by srdjan-drca** [comment]
@ashishdhingra When instantiating AmazonDynamoDBConfig all default configurations are loaded like on picture below. 
C:\Users\Tiac L-25\Desktop\2022-09-07 10_27_26-aws-sdk-net_AmazonDynamoDBConfig.cs at 4ca82b8f08526668b83c7bcd8975092540305335 .png
How do we choose which default configuration will be loaded?

**Comment by nthornton2010** [comment]
I created a new VB project and loaded the specific library we're using into it and it worked fine. I am thinking that one of our other libraries is referencing an older version that I'm not seeing (there's a lot). I'm going to dig through that more. I'll leave this open for today in case I find something that points to this being a bug but I'm thinking its something on my end.

**Comment by nthornton2010** [comment]
I was able to find 1 project referencing the wrong location. Thanks for the help on this.
