### ISSUE TITLE
Cognito Sync and working with Dataset examples

### ISSUE THREAD

**Issue by seaders** [aws/aws-sdk-net#210]
Looking through the docs, and the the API, I'm seeing plenty of references, and classes referring to Cognito Sync, but haven't been able to see any examples of practical usage, and looking through the source code, I can't see any "Synchronize" or similar functions in the Dataset, nor really any of them being complete classes?

Unless I'm completely mistaken, is Cognito Sync not fully supported on the .NET platform?

**Comment by PavelSafronov** [comment]
The .NET SDK supports the Cognito Sync service as outlined in [this API reference](http://docs.aws.amazon.com/cognitosync/latest/APIReference/Welcome.html). The [client code](https://github.com/aws/aws-sdk-net/tree/master/AWSSDK_DotNet35/Amazon.CognitoSync) as well as [client tests](https://github.com/aws/aws-sdk-net/blob/master/AWSSDK_DotNet.IntegrationTests/Tests/CognitoSync.cs) are part of this repo and show how the service can be utilized.

However, the "Synchronize" operation that you are referring to is part of the high-level [CognitoSyncManager](http://docs.aws.amazon.com/cognito/devguide/sync/synchronizing-data/), which is currently not supported by the .NET SDK. CognitoSyncManager is implemented on top of the "low-level" client and adds helpful functionality, but all operations done with the CognitoSyncManager can be done with the currently-supported low-level client.

**Comment by karthiksaligrama** [comment]
@seaders take a look @ https://github.com/aws/amazon-cognito-dotnet. Yesterday we released SyncManager with 3.1 release for the Dot Net 45 and Xamarin Platforms. It is currently in preview.
