### ISSUE TITLE
SQS API doesn't match server response

### ISSUE THREAD

**Issue by slang25** [aws/aws-sdk-net#2108]
### Describe the bug

The following message structure definition describes the `MessageAttributes` to have location name `MessageAttribute`:
https://github.com/aws/aws-sdk-net/blob/master/generator/ServiceModels/sqs/sqs-2012-11-05.api.json#L660-L677

However, the API response from ReceiveMessage contains the message attributes in a property named `MessageAttributes`, so the marshalling code doesn't pick it up:
https://github.com/aws/aws-sdk-net/blob/3db06fe5cc0b2486520b3765b89feb9acba5bd8a/sdk/src/Services/SQS/Generated/Model/Internal/MarshallTransformations/MessageUnmarshaller.cs#L82

Sample response:
```json
{
    "Type": "Notification",
    "MessageId": "43db9b9e-476a-4c52-8d24-993e558a65a2",
    "TopicArn": "...",
    "Message": "{\"Id\":\"2479ce3f-2d41-4688-93d8-bfd97792c018\",\"TimeStamp\":\"2022-09-15T09:40:56.2121Z\"}",
    "Timestamp": "2022-09-15T09:40:59.738Z",
    "SignatureVersion": "1",
    "Signature": "...",
    "SigningCertURL": "...",
    "Subject": "SimpleMessage",
    "MessageAttributes": {
        "content": {
            "Type": "String",
            "Value": "somecontent"
        },
        "binarycontent": {
            "Type": "Binary",
            "Value": "c29tZWJpbmFyeWRhdGE="
        }
    }
}
```

It looks like the API description is incorrect causing incorrect generation of the marshalling code.

### Expected Behavior

Message attributes to be available on the `ReceiveMessagesAsync` response `Message` object.

### Current Behavior

The message attributes on the `ReceiveMessagesAsync` response `Message` object is always empty.

### Reproduction Steps

Call `ReceiveMessagesAsync` with messages that have message attributes and see it has an empty `MessageAttributes` property.

### AWS .NET SDK and/or Package version used

AWSSDK.SQS 3.7.2.102

### Targeted .NET Platform

.NET 6

### Operating System and version

Any

**Comment by slang25** [comment]
Digging deeper, it looks like this is by design as the marshalling is dealing with the XML, and this is the JSON body. I find this a really confusing design. I want to lift out the message attributes from the body and add them to the response Message object, just feels a bit dirty.

**Comment by ashishdhingra** [comment]
> Digging deeper, it looks like this is by design as the marshalling is dealing with the XML, and this is the JSON body. I find this a really confusing design. I want to lift out the message attributes from the body and add them to the response Message object, just feels a bit dirty.

@slang25 Good afternoon. Looks like you have figured out the XML parsing logic for SQS. Please confirm if we could close this issue.

**Comment by slang25** [comment]
@ashishdhingra Yes I understand it now, I find the design a bit odd, but it's all working as designed 🙂

**Comment by normj** [comment]
@slang25 Looking at your sample JSON response it looks like you are talking about a message sent from SNS to SQS. So the message attributes in the message body are the SNS message attributes not the SQS message attributes.
