### ISSUE TITLE
RequestTimeTooSkewed Error: The difference between the request time and the current time is too large.

### ISSUE THREAD

**Issue by rupreetg** [aws/aws-sdk-net#211]
We are getting this error when we upload a large file, say 150 MB to S3. This error comes after 15-20 mins of upload. 

We are creating client software which will push end user data on S3. These will be installed on end user machine on which we won't have much control. 

We've researched this error and what I understand is - it comes when the client time is way different (more than 15 mins) from apple time. One of the common solution given is to install NTP on machine. 

If NTP was the issue, it would have given the error before initiating the upload itself, why does it give in the middle of upload? 

Any idea why are we getting this error, when it works perfectly fine with small files but throws error on large files. 

I haven't found any resolution to this error and stuck with it, any quick help or workaround would really be appreciated. 

We are using v2.3 of AWS SDK. 

Please let me know if any more information is needed.

**Comment by theofanis** [comment]
If you're using an older version than 2.3.26 then you probably experience the bug I mentioned some time ago, explained in https://github.com/aws/aws-sdk-net/issues/182.

Check for AWSConfigs.CorrectForClockSkew and make sure it's value is `true`, or even better update to the stable latest version or v3 preview.

**Comment by rupreetg** [comment]
Great, let me give it a try!

**Comment by rupreetg** [comment]
We tried latest version v2.4 and the bug was fixed. Thank you!
