### ISSUE TITLE
AWSCredentialsFactory returns AssumeRoleAWSCredentials instead of InstanceProfileAWSCredentials

### ISSUE THREAD

**Issue by OlegBoulanov** [aws/aws-sdk-net#2119]
### Describe the bug

Related to this: https://aws.amazon.com/blogs/security/announcing-an-update-to-iam-role-trust-policy-behavior/

https://github.com/aws/aws-sdk-net/blob/cf09e762ffa5de0276c12587e3f292e8d2ef9eb0/sdk/src/Core/Amazon.Runtime/CredentialManagement/AWSCredentialsFactory.cs#L283

same as https://github.com/aws/aws-sdk-net/blob/cf09e762ffa5de0276c12587e3f292e8d2ef9eb0/sdk/src/Core/Amazon.Runtime/CredentialManagement/AWSCredentialsFactory.cs#L261

Shouldn't these return different kind of credentials?

### Expected Behavior

InstanceProfileAWSCredentials should be returned, if instance role with the same ARN is available?

### Current Behavior

AssumeRoleAWSCredentials is returned

### Reproduction Steps

Try `aws sts get-caller-identity`

Notice instance role being used

Create .aws/credentials file:
```
[default]
credential_source = Ec2InstanceMetadata
role_arn =  "instance role arn"
```

Try `aws sts get-caller-identity`

Observe role being assumed

comment out role_arn

Try again, to see original instance role being used

### AWS .NET SDK and/or Package version used

latest

### Targeted .NET Platform

 .NET Framework 4.7

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment]
Hi @OlegBoulanov,

Good afternoon.

The credentials in AWS SDK for .NET are resolved using [FallbackCredentialsFactory.GetCredentials()](https://github.com/aws/aws-sdk-net/blob/cf09e762ffa5de0276c12587e3f292e8d2ef9eb0/sdk/src/Core/Amazon.Runtime/Credentials/FallbackCredentialsFactory.cs#L125). Kindly note that internal implementation is subjected to change without any notice. Without going through the specifics on internal implementation, could you please share the sample code to reproduce the issue where differences are observed between AWS SDK for .NET and AWS CLI?

Thanks,
Ashish

**Comment by OlegBoulanov** [comment]
Hi Ashish,

Thank you for prompt response.

No, the difference is not between SDK and CLI (the latter is using SDK, after all, right?)
The issue, related to the latest AWS Blog is that there is a change pending (see the link in description), which will disallow implicit policy for a role to assume itself for credentials update.

Quite often we need to use multiple roles, and define them in profiles to avoid hard coding.

The blog post cited - correctly proposes that if we intend to obtain a new set of credentials for an instance role, we do not need to invoke AssumeRole(), but rather select it from instance roles already readily available and properly refreshed.

But: AWS SDK  (.NET, at least) does not do that, and I think it should.
Sure I can write a workaround for that, invoking InstanceProfileAWSCredentials(Role) directly, but this kind of defies the purpose of CredentialsFactory resolution process, don't you think?

Thanks,
Oleg

**Comment by ashishdhingra** [comment]
@OlegBoulanov The assumption that AWS CLI is using AWS SDK for .NET is not correct. [AWS CLI](https://github.com/aws/aws-cli) is using it's own runtime and libraries (Python).

**Comment by OlegBoulanov** [comment]
@ashishdhingra - I do realize that CLI uses a different SDK. It is not the question, and I'm well aware of the process.
There is a bug (or missed improvement opportunity) in the code.
The issue would not be of much importance, but [AWS intends to break existing process in less than 6 months,](https://aws.amazon.com/blogs/security/announcing-an-update-to-iam-role-trust-policy-behavior/) while using new process is difficult, if bugs in SDK is not fixed.

Thanks,
Oleg

**Comment by ashishdhingra** [comment]
> @ashishdhingra - I do realize that CLI uses a different SDK. It is not the question, and I'm well aware of the process.
> 
> There is a bug (or missed improvement opportunity) in the code.
> 
> The issue would not be of much importance, but [AWS intends to break existing process in less than 6 months,](https://aws.amazon.com/blogs/security/announcing-an-update-to-iam-role-trust-policy-behavior/) while using new process is difficult, if bugs in SDK is not fixed.
> 
> 
> 
> Thanks,
> 
> Oleg

@OlegBoulanov Thanks. This needs review with the team.

**Comment by normj** [comment]
I would bet no AWS SDK does this. I think all of them assume that if there is a `role_arn` in the profile then it does whatever it needs to do to setup for the AssumeRole call.

It is interesting idea to short circuit the AssumeRole call if the instance metadata role arn and the role to assume are the same. We try to standardize the credential logic across all of the SDK as much as we can, legacy issues get in the way sometimes, so we couldn't unilateral make this change in the .NET SDK. So we would need to get buy in from all of the SDKs teams that this is the right approach before we could make such a change in the .NET SDK. I'll discuss with the wider AWS SDK team but this is not a change we can make quickly.

**Comment by OlegBoulanov** [comment]
@normj, @ashishdhingra  - Thank you for your comments, helping me to clarify my thoughts. 
For now, I will implement a workaround, and close the ticket.
