### ISSUE TITLE
Getting SignatureDoesNotMatch when trying to put objects with non-printable characters.

### ISSUE THREAD

**Issue by theofanis** [aws/aws-sdk-net#212]
In our case, the exact file name that throws the error contains the left-to-right-mark character (wiki http://en.wikipedia.org/wiki/Left-to-right_mark).

We are able to upload the file from the aws console using chrome.
We are able to upload the file using boto3.
We are unable to upload the file using aws sdk v3 preview (3.0.0.2).

**Comment by steveataws** [comment]
Thanks for the bug report, we'll investigate further.

**Comment by theofanis** [comment]
The problem is in the way System.Uri handles characters that are not supposed to exist in a uri.

It simply strips them away even if they are url encoded. Try the lrm char and you will see exactly that.

The string AWSSDK signs includes the key name with url encoding. So lrm is encoded with chars starting with `%`, but the request which gets sent doesn't have the char at all. So when the S3 service signs what it received it obviously signs a different string, this complaining about not matching signatures.

You have to check MSDN pages for the way System.Uri does this. I am currently investigating how to adapt my code to this but I think AWSSDK should take this into consideration when signing the request string since System.Uri isn't going to change.

**Comment by steveataws** [comment]
Thanks for the extra info; this wouldn't be the first time we've had to work around the behavior of System.Uri and encoded characters in a url.

How are you specifying the character in the original keyname that gets submitted to signing - using the &lrm; encoded character or by using the UTF-8 'E2 80 8E' character sequence?

**Comment by theofanis** [comment]
I just assign the file's name to the `PutObjectRequest.Key`. So whatever FileInfo.Name returns already contains the lrm char for the file causing the problem.

But, I also tried creating a Uri from a string containing the encoded lrm char, that is containing the sequence `%E2%80%8E` and Uri strips it away once again.

Checking System.Uri source verifies that behavior. http://referencesource.microsoft.com/#System/net/System/URI.cs,4282

**Comment by PavelSafronov** [comment]
@theofanis as you correctly pointed out, System.Uri removes these characters from the final uri. This means that there is no way for a .NET application to send a request to S3 for a key containing bidirectional control characters.

It's possible to change the SDK (by signing a request where the key has no bidirectional control characters) to get this scenario to "work", but this would lead to unwanted behavior: a user will think they are working with key A, but actually will be working with key B. This will be confusing, and could lead to **loss of user data.**

At this point, I am inclined to say that this is not a change we want to make to the SDK. I am also thinking that the SDK should check for bidirectional control characters in key names and throw an exception, to clearly convey that the .NET SDK is unable to properly handle these characters.

**Comment by theofanis** [comment]
Checking for those characters and throwing before creating the SDK request is not a bad thing. It would certainly help if it clarifies the situation, since it would save a developer from researching this more to find out what I found after putting some significant amount time to it.

Feel free to close this. Thanks for the reply.

**Comment by PavelSafronov** [comment]
We've made and released the change to the SDK to throw an exception if bidirectional control characters are detected in the resource path. Closing.
