### ISSUE TITLE
Default AWS Region to "us-east-1" when creating AmazonOrganizationClient without specifying region

### ISSUE THREAD

**Issue by pbrinson** [aws/aws-sdk-net#2123]
### Describe the feature

According to the documentation for the AWS SDK for .NET (found here: https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/Organizations/NOrganizations.html), when you create an AmazonOrganizationsClient object you must specify the region of us-east-1 (or cn-northwest-1 if inside China). When no region is provided in the constructor an Exception is thrown (Inner Exception 1: AmazonClientException: No RegionEndpoint or ServiceURL configured).

Since the expected region is "us-east-1", wouldn't it make sense to default the AWS Region if no region is specified in the constructor?

### Use Case

I need to use AmazonOrganizationsClient but being forced to include the "us-east-1" region every time I create the object is not needed when a sensible default exists.

### Proposed Solution

Update the AmazonOrganizationsClient constructors and don't take a region as a parameter to default the region to "us-east-1" instead of throwing an Exception.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

AWSSDK.Organizations 3.7.2.67

### Targeted .NET Platform

.NET 6

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment]
@pbrinson Thanks for submitting the feature request. Just to mention here that the SDK logic for `Organizations` service is autogenerated by service models. Without going into implementation details, I'm unsure how this would be implemented.

[AWS Organizations API Reference](https://docs.aws.amazon.com/organizations/latest/APIReference/Welcome.html) and the [above documentation](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/Organizations/NOrganizations.html) both specify that `For the current release of Organizations, specify the us-east-1 region for all Amazon Web Services API and CLI calls made from the commercial Amazon Web Services Regions outside of China.`. However, I'm still not sure if we should default region to `us-east-1` in case this is not true for future releases (not sure if service model has some attribute that dictates the default region).

This needs review with the team.

**Comment by ik130** [comment]
Implementing this feature would require a breaking change. As such, we would consider implementing this in the next major version of the .NET SDK.

**Comment by dscpinheiro** [comment]
Newer versions of the SDK (after `3.7.100`) use a different logic for constructing endpoints, and I don't see this exception anymore in the latest version of the `AWSSDK.Organizations` package (`3.7.300.53` as of today). This snippet works for me even though my default region is not `us-east-1`:
```
[default]
region = us-west-2
output = json
```

```csharp
using Amazon.Organizations;
using Amazon.Organizations.Model;

var organizations = new AmazonOrganizationsClient();
var response = await organizations.ListAccountsAsync(new ListAccountsRequest());
Console.WriteLine(response.HttpStatusCode); // Outputs OK
```

If you still see the problem after updating the service package, please let us know.
