### ISSUE TITLE
InvalidSnapshot.NotFound exception should have meaningful message

### ISSUE THREAD

**Issue by mwhouser** [aws/aws-sdk-net#213]
When issuing an `Amazon.EC2.AmazonEC2Client.DeleteSnapshots()` command, if the snapshot does not exist, then an `Amazon.EC2.AmazonEC2Exception` is thrown with `ErrorCode` value of `InvalidSnapshot.NotFound`.

However, the `Message` property on the exception has the following value:
> Exception of type 'Amazon.EC2.AmazonEC2Exception' was thrown.

It should be something more useful (I think it was in the past), such as "Snapshot x was not found".

AWSSDK version: 2.3.36

**Comment by normj** [comment]
I have reproduce the problem and I'm looking into the cause.

**Comment by normj** [comment]
In this case the service does not return back an error message just an error code. I have updated the SDK to return a better default error message that includes the error code. I also pinged the EC2 team to see about adding an error message in the response.
