### ISSUE TITLE
MachineLearning's PredictRequest's Record might have wrong type

### ISSUE THREAD

**Issue by amattie** [aws/aws-sdk-net#215]
The [Record](https://github.com/aws/aws-sdk-net/blob/8c4d1ca5f02c1c85eab96d471de8be1843e80570/sdk/src/Services/MachineLearning/Generated/Model/PredictRequest.cs#L83) property of PredictRequest is a `Dictionary<string, string>`, and the [marshaller](https://github.com/aws/aws-sdk-net/blob/8c4d1ca5f02c1c85eab96d471de8be1843e80570/sdk/src/Services/MachineLearning/Generated/Model/Internal/MarshallTransformations/PredictRequestMarshaller.cs#L91) appears to write the JSON object as all string values. However, the [AWS ML docs](http://docs.aws.amazon.com/machine-learning/latest/dg/interpreting_predictions.html#real-time-prediction-request-format) say this:

>Values in the Record map should have the same type as the training data. For example, variables that are NUMERIC in the training data also should be numbers in the Record map.

With that said, should the type be `Dictionary<string, object>` so that the type can get written natively by the JsonWriter?

**Comment by PavelSafronov** [comment]
Thanks for reporting this. The [AWS ML docs](http://docs.aws.amazon.com/machine-learning/latest/dg/interpreting_predictions.html#real-time-prediction-request-format) you linked to are incorrect in this regard and will be updated. The map should be string-to-string.
