### ISSUE TITLE
No IntelliSense for NuGet package

### ISSUE THREAD

**Issue by breyed** [aws/aws-sdk-net#216]
The `AWSSDK.dll` assembly in the AWSSDK NuGet package apparently derives from code with XML comments because they show up in online documentation like [this](http://docs.aws.amazon.com/sdkfornet1/latest/apidocs/html/T_Amazon_S3_AmazonS3Client.htm). However, the NuGet package doesn't include `AWSSDK.xml`, which keeps any of those fine comments from appearing in Visual Studio IntelliSense or in the assembly metadata. Please include the file with the XML comments.

**Comment by mateusaubin** [comment]
this is the same issue I've reported back in Sep. 2014
unfortunately it's still open
see #91

**Comment by breyed** [comment]
You're right. Sorry for the dup.

**Comment by normj** [comment]
In the new modularized NuGet packages the XML file is included. Check this blog post for further information.
