### ISSUE TITLE
The difference between the request time and the current time is too large

### ISSUE THREAD

**Issue by AmitManchanda** [aws/aws-sdk-net#217]
I am getting an error the time difference between the request time and the current time is too large while sending large files more than 100 MB with the help of (Multi part Upload Request) 

I read out the same issue id #211 there advised to use aws sdk V3. I was using 2.3.26 first but now i am using 2.3.40 but getting the same error. 

i was not able to find the solution and stuck here. please help me and give suggestion that what should i do.

Please let me know if any more information you needed.

Thanks:)

**Comment by PavelSafronov** [comment]
Can you provide the code that you are using?
