### ISSUE TITLE
Sample code start up: unable to find credentials

### ISSUE THREAD

**Issue by stew21** [aws/aws-sdk-net#218]
I'm just getting started and ran the sample code after creating an AWS console application in VS10 Express. I got an unhandled exception when the system executes

IAmazonEC2 ec2 = new Amazon.EC2.AmazonEC2Client();

The details explain that it cannot find the app.vhost.exe.Config file in the debug folder. I checked and it wasn't there. This could be purely a VS problem, but I'm wondering if anyone as a solution? Thanks.

**Comment by PavelSafronov** [comment]
Can you provide the exception message and full stack trace?
How are you passing your AWS keys to the SDK? [This page of the developer guide](http://docs.aws.amazon.com/AWSSdkDocsNET/latest/DeveloperGuide/net-dg-config-creds.html#net-dg-config-creds-sdk-store) explains how your keys can be setup so the SDK is able to use them.

The simplest way to configure the credentials on your local system is to run the below command (remember to substitute your own keys) in PowerShell to configure the "default" profile, which will automatically be chosen when your code runs:

```Set-AWSCredentials -StoreAs default -AccessKey ACCESS_KEY -SecretKey SECRET_KEY```

Once you run this command, your development environment will be configured with the keys you specified. It's not necessary to run this command again unless you wish to reconfigure the keys.

**Comment by stew21** [comment]
I've got it all figured out and working. I just needed to adjust the keys in the app.config file. I created a new set of keys in AWS. Thanks for your response.
