### ISSUE TITLE
Consistent read overload is missing in DynamoDB

### ISSUE THREAD

**Issue by xandaro** [aws/aws-sdk-net#220]
It seems that there is no way to perform consistent read by hash and range key in .NET SDK:

    var hash = "111";
    var rangekey = "222";

    // this is the only overload and it does not accept GetItemOperationConfig or something similar
    // as parameter to perform consistent read
    var result = await table.GetItemAsync(hash, rangekey);

The above example will work, but it is not consistent and there should be an overload method to specify if the read operation must be consistent.

**Comment by PavelSafronov** [comment]
For consistent reads, use the `GetItemAsync` overload which accepts `GetItemOperationConfig` (in your case it would be [this one](https://github.com/aws/aws-sdk-net/blob/aws-sdk-net-v2/AWSSDK_DotNet45/Amazon.DynamoDBv2/DocumentModel/Table.Async.cs#L113)) and pass in an instance of `GetItemOperationConfig` with `ConsistentRead` set to true.

**Comment by xandaro** [comment]
Thank you Pavel, this resolved the issue.
