### ISSUE TITLE
Stored credentials resolves credentials file to incorrect path (.NET Core on Mac/Linux)

### ISSUE THREAD

**Issue by corruptmem** [aws/aws-sdk-net#221]
The following code is trying to find the ~/.aws/credentials file:
````csharp
return Path.Combine(
    Directory.GetParent(System.Environment.GetFolderPath(System.Environment.SpecialFolder.Personal)).FullName,
    ".aws/credentials");
````
https://github.com/aws/aws-sdk-net/blob/84afada7f15263600155fe314cad09f2802338bc/sdk/src/Core/Amazon.Runtime/AWSCredentials.cs#L378-L380

On Windows, System.Environment.SpecialFolder.Personal equates to C:\Users\username\Documents, so the code calls GetParent to get to the home directory. 

However on Mac/Linux, SpecialFolder.Personal resolves to $HOME, so getting the parent directory results in (for example on a Mac) looking at /Users/.aws/credentials 
This is an issue when trying to use .NET Core

In .NET 4, Microsoft introduced a new SpecialFolder.UserProfile value which will resolve to the intended directory.  Or there are a few other ways that it could be worked around without depending on .NET 4...

**Comment by normj** [comment]
Thanks for letting us know about this issue. I'll work on getting a fix out for this.

**Comment by normj** [comment]
This was fixed with the following pull request. The code will go out with the next nuget push.

https://github.com/aws/aws-sdk-net/pull/222

**Comment by normj** [comment]
This was pushed today with version 3.1. This was also the GA release of the version 3 of the SDK.
