### ISSUE TITLE
Unable to use SDK without log4net dependency

### ISSUE THREAD

**Issue by tbenade** [aws/aws-sdk-net#224]
Hi, I am unable to use the SDK in F# Fake without taking a dependency on log4net. I tried forcing the None logging option using.

```fsharp
Amazon.LoggingOptions.None
```

Example

```fsharp
module Aws

#I "../../packages/AWSSDK.CloudFormation/lib/net45/"
#I "../../packages/AWSSDK.Core/lib/net45/"
#r "AWSSDK.CloudFormation.dll"
#r "AWSSDK.Core.dll"

open Amazon
open Amazon.CloudFormation

Amazon.LoggingOptions.None

let createStack =
  let client = new AmazonCloudFormationClient(RegionEndpoint.APSoutheast2)
  ()
```

Result is always
```ShellSession
/hydrator/stdin(0,1): error FS0078: Unable to find the file 'log4net.dll' in any of
 /Library/Frameworks/Mono.framework/Versions/4.0.2/lib/mono/4.5
 /hydrator/build/modules/../../packages/AWSSDK.CloudFormation/lib/net45/
 /hydrator/build/modules/../../packages/AWSSDK.Core/lib/net45/
 /hydrator
 /hydrator/packages/FAKE/tools/
Stopped due to error
```

**Comment by PavelSafronov** [comment]
What versions of the core and service are you using? Running this on Windows with the latest version of [FAKE](https://www.nuget.org/packages/FAKE/4.3.7) and the latest versions of [CloudFormation](https://www.nuget.org/packages/AWSSDK.CloudFormation/3.1.0.1) and [Core](https://www.nuget.org/packages/AWSSDK.Core/), I was able to construct and use the client without encountering the log4net error.
