### ISSUE TITLE
S3 PutBucketPolicy - Unable to Grant Read-Only Permission to an Anonymous User

### ISSUE THREAD

**Issue by dbasilio** [aws/aws-sdk-net#225]
in the example bucket policies listed here: http://docs.aws.amazon.com/AmazonS3/latest/dev/example-bucket-policies.html It specifies you can put a principal like the following:
`"Principal": "*"`
The SDK has AllUsers, but this creates a principal like the following:
`"Principal": { "AWS": "*" }`
There is currently no way to create a principal specifying only the anonymous user through the sdk. Policy.FromJson can parse this kind of principal into an empty list. When trying to create a policy with an empty list for Principal the .toJson doesn't put a principal in the string, which throws an error when attempting to Put it.
The main difference is that if we put an explicit Deny in the policy for `"*"`, our IAM user can still make requests against that bucket. If `{ "AWS": "*" }` is used, our IAM user is included in those users who are rejected.

**Comment by jimfl** [comment]
This has been addressed in the referenced commit, and was included in yesterday's release.

The change adds a static `Anonymous` Principal instance which should serialize as `"Principal" : "*'"`, as well as making the documentation a little more clear and adding some constants for federated and service principals.
