### ISSUE TITLE
Lambda in Xamarin.iOS - returning signature error when payload

### ISSUE THREAD

**Issue by ceichin** [aws/aws-sdk-net#227]
I'm getting an error when including a payload to invoke a Lambda Function. It works when the payload is empty though. It returns the following error:

"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details. The Canonical String for this request should have been..."

Secret Access Key and other data are ok, and as I said it works when including an empty payload string:

```
try 
{
    var lambdaClient = new AmazonLambdaClient("XXXX", "XXXX", RegionEndpoint.USEast1);

    //var args = @"{""value1"" : ""one"", ""value2"" : ""two"", ""value3"" : ""three""}"; // <--- RETURNS ERROR
    //var args = @"{""value1"" : ""one""}"; // <--- RETURNS ERROR
    //var args = "{ }"; // <--- RETURNS ERROR
    var args = ""; // <--- 202 and responds with the expected message

    var ir = new InvokeRequest() {
        FunctionName = "arn:aws:lambda:us-east-1:XXXXXX:function:helloWorld",
        //Payload = args,
        PayloadStream = AWSSDKUtils.GenerateMemoryStreamFromString(args),
        InvocationType = InvocationType.RequestResponse
    };

    InvokeResponse resp = await lambdaClient.InvokeAsync(ir);

    resp.Payload.Position = 0;
    var sr = new StreamReader(resp.Payload);
    var myStr = sr.ReadToEnd();

    Console.WriteLine("Status code: " + resp.StatusCode);
    Console.WriteLine("Response content: " + myStr);
}
catch (Exception ex) 
{
    Console.WriteLine("error: " + ex.Message);
}
```

I tried with Cognito credentials and same results. Also tried with Payload and/or PayloadStream in the InvokeRequest object, same results.

Working with Xamarin.iOS and Xamarin Studio. I included the package AWSSDK - AWS Lambda 3.1.0.0 from the official NuGet Gallery.

Thanks, hope you can help me!

**Comment by PavelSafronov** [comment]
Thank you for reporting this. We've just released a patched version of the SDK which resolves this issue. The version of the patched Lambda package on NuGet is 3.1.0.1.

Sorry for the inconvenience.
