### ISSUE TITLE
Visual Studio 2015 dark colour theme not being applied

### ISSUE THREAD

**Issue by sliedig** [aws/aws-sdk-net#228]
Hello,

just noticed the colour theme for the AWS toolkit  in Visual Studio 2015 are not being applied correctly to the dark theme.

![image](https://cloud.githubusercontent.com/assets/597073/9219644/e4a55ddc-410e-11e5-8abc-a0cc6674145b.png)

This also applies to the CloudFormation template colouring.

Cheers,

Steve

**Comment by IainCole** [comment]
+1 This is triggering my OCD... I can't work like this.....

**Comment by steveataws** [comment]
Looking. Confirmed this seems to be specific to VS2015 only - the same page in VS2013 and VS2012 looks just fine in dark mode. It also appears to be specific to wizards; regular dialogs seem fine.

**Comment by steveataws** [comment]
v1.6.9.2 of the toolkit has just been released that we believe fixes the issue. Apologies for the inconvenience.

**Comment by sliedig** [comment]
No problems, thanks for the quick resolution!

**Comment by sliedig** [comment]
@steveataws 

Sorry, looks like the parameter fields in the wizard aren't showing up correctly. 

![image](https://cloud.githubusercontent.com/assets/597073/9320614/ab9ff8a6-458e-11e5-9550-32623acfccaa.png)

![image](https://cloud.githubusercontent.com/assets/597073/9320659/202424a4-458f-11e5-8e13-29c04cdce1b8.png)

Regards,
Steve

**Comment by steveataws** [comment]
The labels on the 2nd image are consistent with vs2013 and vs2012 in the dark theme, although I agree they could be more readable. For the first image, only vs2015 appears to show this problem - vs2013 shows the button text as a light gray label. 

I'll see if I can find a better color mapping for these two and get back to you.

**Comment by steveataws** [comment]
Scratch that last message, I was looking at the wrong set of Stack dialogs :-(. 

I've found what I think is the cause, specific to the two pages you listed - I should be able to finish up testing and be able to ship a further fix in the morning.

**Comment by steveataws** [comment]
v1.6.9.3 is now available, with lighter text labels in the two dialogs you list when in dark mode.

**Comment by bpavlov** [comment]
![image](https://cloud.githubusercontent.com/assets/2480572/20814127/1e5b17a8-b821-11e6-8c98-06412bcfb216.png)
