### ISSUE TITLE
Tracking CoreCLR Support

### ISSUE THREAD

**Issue by normj** [aws/aws-sdk-net#229]
Opening an issue to track progress for CoreCLR support in the AWS SDK for .NET.

The work is being done in the [dnxcore-development](https://github.com/aws/aws-sdk-net/tree/dnxcore-development) branch. Currently we can build a version of the SDK and there are some simple tests for SQS and S3. I’d like to push a beta version of the SDK to NuGet for easier consumption but I need to get more testing done first.

### Building:
You can open the sdk/AWSSDK.DnxCore.sln solution to see the CoreCLR version of the SDK and build it. This solution only builds the CoreCLR version of the SDK. To create NuGet packages that contain the all versions of the SDK you need to run the build script.

```C:\Program Files (x86)\MSBuild\14.0\Bin\msbuild .\buildtools\build.proj```

Note this also attempts to build the Xamarin version which requires a Xamarin business license. To turn off Xamarin, add the **DisablePCLSupport** parameter to the build script like this:

```C:\Program Files (x86)\MSBuild\14.0\Bin\msbuild .\buildtools\build.proj /p:DisablePCLSupport=true```

### Credentials:
The CoreCLR does not support using our encrypted SDK store for credentials because that feature requires doing pinvokes to Win32 APIs. Instead use the shared credentials file for managing credentials. Check out the [developer guide](http://docs.aws.amazon.com/AWSSdkDocsNET/latest/V3/DeveloperGuide/net-dg-config-creds.html#creds-file) for further information on the file.

You can also set the environment variables **AWS_ACCESS_KEY_ID** and **AWS_SECRET_ACCESSS_KEY**.

### Feedback:
CoreCLR is very exciting and has lots of changes to .NET development. I'd appreciate any feedback on how we can better take advantage of the new CoreCLR environment.

**Comment by danielcrenna** [comment]
Excellent news!

**Comment by adamhathcock** [comment]
Thanks for this.  Will try soon.

**Comment by martinbooth** [comment]
@normj I have tried to build this, but unfortunately the DisablePCLSupport switch doesn't help me build this without a xamarin business license (which I don't have).

Any ideas how I can build this without xamarin? Is there any prerelease nuget packages that I could use instead of trying to build this?

Thanks

**Comment by normj** [comment]
What is the error you are getting when you build with DisablePCLSupport?

**Comment by martinbooth** [comment]
I believe the error was caused by attempting to build on a machine that had xamarin starter edition installed, and I've been able to work around it by using a different machine.

I have coreclr nuget packages created and referenced. Unfortunately, I now get the following:

System.DllNotFoundException: Unable to load DLL 'BCrypt.dll': The specified module could not be found

I'm trying this on linux, which is probably why the file doesn't exists.

**Comment by superlogical** [comment]
Awesome news, I'll be checking this out too :+1:

**Comment by salerth** [comment]
@normj Thanks, I've got these running now on OSX so will do some testing, using them as local project references.

I'm using dnu restore/dnu build so I did have to add the DNX451 framework to each project.json as my app targets both... but thats just a temporary thing until NuGet I guess!

**Comment by normj** [comment]
Glad you got it working. The DNX451 is temporary because in the NuGet package the existing .NET 4.5 assemblies will be what NuGet resolves to for DNX451..

**Comment by salerth** [comment]
Should we raise issues on this thread for the DNX stuff? or would you prefer separate issues?

I'm trying to make some EC2 requests using the shared credentials file (I need to be able to support multiple AWS accounts), but keep getting the following error:
```
DllNotFoundException: Unable to load DLL 'BCrypt.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Internal.NativeCrypto.Cng.Interop.BCryptOpenAlgorithmProvider(SafeAlgorithmHandle& phAlgorithm, String pszAlgId, String pszImplementation, Int32 dwFlags)
Internal.NativeCrypto.Cng.BCryptOpenAlgorithmProvider(String pszAlgId, String pszImplementation, OpenAlgorithmProviderFlags dwFlags)
Internal.Cryptography.HashProviderDispenser.HashProviderCng..ctor(String hashAlgId, Byte[] key)
System.Security.Cryptography.SHA256.Implementation..ctor()
System.Security.Cryptography.SHA256.Create()
Amazon.Util.CryptoUtilFactory.CryptoUtil.get_SHA256HashAlgorithmInstance()
Amazon.Util.CryptoUtilFactory.CryptoUtil.ComputeSHA256Hash(Byte[] data)
Amazon.Runtime.Internal.Auth.AWS4Signer.SetRequestBodyHash(IRequest request)
Amazon.Runtime.Internal.Auth.AWS4Signer.SignRequest(IRequest request, ClientConfig clientConfig, RequestMetrics metrics, String awsAccessKeyId, String awsSecretAccessKey)
Amazon.Runtime.Internal.Auth.AWS4Signer.Sign(IRequest request, ClientConfig clientConfig, RequestMetrics metrics, String awsAccessKeyId, String awsSecretAccessKey)
Amazon.Runtime.Internal.Signer.SignRequest(IRequestContext requestContext)
Amazon.Runtime.Internal.Signer.PreInvoke(IExecutionContext executionContext)
Amazon.Runtime.Internal.Signer.InvokeAsync[T](IExecutionContext executionContext)
Amazon.Runtime.Internal.PipelineHandler.InvokeAsync[T](IExecutionContext executionContext)
Amazon.Runtime.Internal.CredentialsRetriever.<>n__0[T](IExecutionContext executionContext)
Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__7`1.MoveNext()
```

Using this credentials method:
```

		private AWSCredentials GetCredentials()
		{
			//return new BasicAWSCredentials(accessKey, secretKey);
			return new StoredProfileAWSCredentials(ConfigurationKey);
		}

		internal AmazonEC2Client GetEC2Client(string region = null)
		{
			logger.LogInformation("Getting EC2 client for region {0}", region ?? defaultRegion);
			return new AmazonEC2Client(GetCredentials(), Amazon.RegionEndpoint.GetBySystemName(region ?? defaultRegion));
		}
```

**Comment by normj** [comment]
Reporting the issue here works. What version of the runtime are you running this on (CLR, Mono or CoreCLR)? Also are you running on Linux or Mac?

**Comment by salerth** [comment]
I'm on 1.0.0-beta8-15613    coreclr x64  (OSX)

Actually just found this dotnet/corefx#3056 so seems to be a Corefx issue

**Comment by normj** [comment]
Thanks for the link to the corefx issue!

**Comment by normj** [comment]
Closing this since we have pushed out a new version 3.2.0-beta versions of the SDK to NuGet that contain ASP.NET 5 / CoreCLR support. For any future issues or suggestions please open another issue. Here is the announcement blog for the beta release: 

http://blogs.aws.amazon.com/net/post/Tx1PXTHFL06MZ57/New-Support-for-ASP-NET-5-in-AWS-SDK-for-NET
