### ISSUE TITLE
DBInstance is missing DBClusterIdentifier

### ISSUE THREAD

**Issue by mwhouser** [aws/aws-sdk-net#230]
As per http://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DBInstance.html

`Amazon.RDS.Model.DBInstance` is missing `DBClusterIdentifier`.

On the `aws-sdk-net-v2` branch.

**Comment by PavelSafronov** [comment]
Version 2 of the SDK has been updated and now contains this field.
