### ISSUE TITLE
AWSSDK in NuGet 2.3.50.1 is missing RDS cluster models

### ISSUE THREAD

**Issue by mwhouser** [aws/aws-sdk-net#231]
https://www.nuget.org/packages/AWSSDK/2.3.50.1

When the binaries are pulled from NuGet, `Amazon.RDS.Model.CreateDBClusterSnapshotRequest` et al are missing.

https://github.com/aws/aws-sdk-net/blob/aws-sdk-net-v2/AWSSDK_DotNet35/Amazon.RDS/Model/CreateDBClusterSnapshotRequest.cs

**Comment by PavelSafronov** [comment]
The latest version of the NuGet package (2.3.51) contains this class.
