### ISSUE TITLE
IAmazonIdentityManagementService interface's ListPolicies member

### ISSUE THREAD

**Issue by kareemsulthan07** [aws/aws-sdk-net#232]
while i'm wandering within IAM environment with the resources such as users, roles, policies. All actions regarding to the resources there are exactly the same members (classes, interfaces, and others also) available in awssdk.dll that is the sdk either found on aws web page or library downloaded from here github repository until i decided to enumerate all the managed, inline, user-managed policies associated with the current account.

The ListPolices member of iamazonidentitymanagementservice is intended for that action (as all know) but this particular member is not contained in the awssdk.dll found here (github repository). is there anywhere that it can be found...?

**Comment by PavelSafronov** [comment]
Can you provide a link to "the awssdk.dll found here (github repository)"? It's possible that you are simply referencing an old assembly.
You can get the latest version of the SDK either as an MSI [here](http://aws.amazon.com/sdk-for-net/), or from NuGet (for instance, here's the [IAM package](https://www.nuget.org/packages/AWSSDK.IdentityManagement/)).

**Comment by kareemsulthan07** [comment]
why v3 documentation not containing about the resource APIs, i really enjoyed the programming with resource APIs model. as it indicated i referenced the awssdk.dll downloaded from here. but in the v3 they've removed the documentation regarding to resource APIs and re-referencing to original library is not supporting the resource level APIs usage.

**Comment by PavelSafronov** [comment]
[AWS Resource APIs for .NET in the AWS SDK for .NET](http://docs.aws.amazon.com/AWSSdkDocsNET/latest/V2/DeveloperGuide/resource-level-apis-intro.html) are provided as preview. They are not officially part of the .NET SDK. As such, they're not present in V3 documentation.

**Comment by kareemsulthan07** [comment]
so i should habbit of it.
