### ISSUE TITLE
AwsSwfClient.PollForActivityTaskAsync InvokeAsync does not cancel the http call

### ISSUE THREAD

**Issue by IDontEatSoap** [aws/aws-sdk-net#233]
While using something like:

PollForActivityTaskResponse response = await AwsSwfClient.PollForActivityTaskAsync(request, CancellationTokenSource.Token);

and subsequently setting the token for cancellation, the blocking HTTP call is not canceled.

As a result, any incoming ActivityTask will be pooled and marked as started by SWF, when in fact they're just dropped and ignored by the .NET client. This will result in those activities not being actioned by the .NET client.

The correct behaviour would be the SDK completely dropping the HTTP long pool once the async call is cancelled.

To simulate, in order:

1 - call PollForActivityTaskAsync
2 - cancel the PollForActivityTaskAsync token
3 - queue a SWF activity while the PollForActivityTaskAsync still has a open http socket
4 - the SWF activity is picked up and left in the limbo by the .NET SDK

**Comment by gokarnm** [comment]
Thanks for reporting this issue! Which version of the SDK are you using and which platform are you running against? Can you also post the code where you perform the cancellation?

**Comment by gokarnm** [comment]
Closing this issue. Please reopen this issue if you are still facing a problem with the SDK.

**Comment by GuilMagalhaes** [comment]
@gokarnm As per the issue description I'm using the latest .NET SDK, and the error happens when PollForActivityTaskAsync's CancellationToken is set - any running tasks keep running and that results in activities being picked up but never acted on.

Has anything been done to fix this?

**Comment by gokarnm** [comment]
@GuilMagalhaes, this issue is now being tracked [here](https://github.com/aws/aws-sdk-net/issues/246).
