### ISSUE TITLE
Visual Studio Cloudformation schema for ManagedPolicyArns IAM Role

### ISSUE THREAD

**Issue by sliedig** [aws/aws-sdk-net#234]
Hello,

could you please update the schema to include the ManagedPolicyArns for IAM Roles as per the documentation? 
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html#cfn-iam-role-managepolicyarns

![image](https://cloud.githubusercontent.com/assets/597073/9375160/eda0b586-472f-11e5-9fb2-80494df5d85c.png)

Cheers,

Steve

**Comment by normj** [comment]
Thanks for letting me know. I updated the schema which you should see after next Visual Studio restart.
