### ISSUE TITLE
Visual Studio Cloudformation schema validation error for ImageId? 

### ISSUE THREAD

**Issue by sliedig** [aws/aws-sdk-net#236]
Hello,

not sure about this one, but when I specify a parameter for a image id of type AWS::EC2::Image::Id, and then try to assign that parameter reference to the ImageId property for a launch configuration resource I get a validation error (see image). Should this be valid?

![image](https://cloud.githubusercontent.com/assets/597073/9426572/41ccdd92-497e-11e5-9f9a-54f3177f999d.png)

Regards,
Steve

**Comment by normj** [comment]
I'm taking a look to see what is going on.

**Comment by normj** [comment]
I just released version 1.9.6.4 of the Visual Studio toolkit that fixes this issue. It was a coding change not a schema change so you will need to install the latest version from our website. Thanks for letting me know about the issue.
