### ISSUE TITLE
Cloudsearch support for retrieving statistics for number fields is missing 

### ISSUE THREAD

**Issue by adydaddy** [aws/aws-sdk-net#238]
There is currently no way to get stats for a numeric field alongside a query inside the .net sdk. 

Getting statistics for number fields was officially announced on March-5-2015 but still no support in SDK.

http://aws.amazon.com/releasenotes/Amazon-CloudSearch/5060064203846541

**Comment by gokarnm** [comment]
The latest version of [CloudSearchDomain NuGet package](https://www.nuget.org/packages/AWSSDK.CloudSearchDomain/3.1.1) (version 3.1.1) has support for statistics.
