### ISSUE TITLE
Elastic Transcoder not sending a message to the corresponding Simple Notification Service topic

### ISSUE THREAD

**Issue by vkanwale** [aws/aws-sdk-net#243]
Elastic Transcoder has set up to send a message to the corresponding Simple Notification Service topic. It does complete the job but stopped sending the confirmation after installing the latest AWS SDK update. This code/feature was working perfectly before installation. nothing has changed in the code or setting of ET other than replacing
```
AWSClientFactory.CreateAmazonSimpleNotificationServiceClient(RegionEndpoint.GetBySystemName(awsRegion))
```
with
```
new Amazon.SimpleNotificationService.AmazonSimpleNotificationServiceClient(RegionEndpoint.GetBySystemName(awsRegion))
```
as AWSClientFactory is no longer supported in newer version of SDK. Please review this issue. many thanks in advance.

**Comment by PavelSafronov** [comment]
Are you seeing exceptions when using the SNS client?
If you enable SDK metrics as shown below, do the logs show the Publish request, and are there any errors associated with it?

[Enabling metrics blog post](http://blogs.aws.amazon.com/net/post/TxZLWAOFZJQWRP/Logging-with-the-AWS-SDK-for-NET). You can add the following section to your app.config/web.config to log the metrics to a file.

Enable metrics:
```
<appSettings>
  <add key="AWSLogMetrics" value="true"/>
  <add key="AWSLogging" value="SystemDiagnostics"/>
  <add key="AWSResponseLogging" value="OnError" />
</appSettings>
```

Configure SystemDiagnostics logging:
```
<system.diagnostics>
  <trace autoflush="true"/>
  <sources>
    <source name="Amazon">
      <listeners>
        <add name="text"
             type="System.Diagnostics.TextWriterTraceListener"
             initializeData="c:\Logs\sdk-log.txt"/>
      </listeners>
    </source>
  </sources> 
</system.diagnostics>
```

**Comment by amazonuser** [comment]
tried it.. no error so for..
