### ISSUE TITLE
Message.ParseMessage cannot handle some Timestamps

### ISSUE THREAD

**Issue by JakeR97** [aws/aws-sdk-net#2449]
### Describe the bug

**Context**

- API is set up to recieve notifications from SNS topic
- API endpoint uses `Message.ParseMessage` to read the incoming text body into a Amazon.SimpleNotificationService.Util.Message object

**Whats Happening**

It seems that some SNS events are occuring at a time where the value of the milliseconds has a 0 for it's thousandths place, i.e. "07:00:00.120Z". However when the event is sent to the API, that trailing 0 gets cut off, making it so that the Timestamp cannot be parsed in Message.ParseMessage. The following is a Timestamp pulled from a log of this occurring:
`"Timestamp": "2022-10-03T10:53:40.67Z"`

### Expected Behavior

Message.ParseMessage can handle parsing the Timestamps that SNS generates

### Current Behavior

Message.ParseMessage will fail to parse Timestamps with no trailing 0 in the milliseconds.

### Reproduction Steps

```
string messageAsString = "{\"Message\": \"{}\",\r\n\"MessageAttributes\": {},\r\n\"MessageId\": \"00000000-0000-0000-0000-000000000001\",\r\n\"Signature\": \"KPEbs/9iU6PiR6clYp1RxrhTrFiKLcJCcsV6KB11lBuG3/MAeklOAj/DAfRH1SGrcjGE0EZspUGq0cZL+NGvGQLvFVZB4lVIVALSbQpomNlfPdbJGfI3+GmTAXK36Yg02EY0YDgdg1i51dJYplXVNrk/tWAoLXmPvYJ3UnXVsZit0JF5ONGoQp/sqbRXHmiTvWdc0Jp2QVqjNCxHQMfkamriVFOE3eJxy0T3awXfIsZav84bG/5uSdiZNU0lgQRtH4mgq0scUqH/lh8rR2IB+FiJCnBE0LPQijfQbFR6THCe0pPEWRwXIcCZpGfyoNvZbTWzDlbefjufQkrXPY9XYw==\",\r\n\"SignatureVersion\": \"1\",\r\n\"SigningCertUrl\": \"https://sns.us-west-2.amazonaws.com/SimpleNotificationService-56e67fcb41f6fec09b0196692625d385.pem\",\r\n\"Subject\": null,\r\n\"Timestamp\": \"2022-10-07T07:27:36.37Z\",\r\n\"TopicArn\": \"arn:aws:sns:us-west-2:633153543971:AssociaComms\",\r\n\"Type\": \"Notification\",\r\n\"UnsubscribeUrl\": \"https://sns.us-west-2.amazonaws.com/?Action=Unsubscribe&SubscriptionArn=arn:aws:sns:us-west-2:633153543971:AssociaComms:e202a43a-4104-4235-8e8f-9a2932d48367\"\r\n}"; //Dummy message with Timestamp formatted like bug
Message message = Message.ParseMessage(messageAsString);
```

### AWS .NET SDK and/or Package version used

AWSSDK.SimpleNotificationService 3.7.4.20

### Targeted .NET Platform

net6.0

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment]
Hi @JakeR97,

Good morning.

Could you please provide more details about the API that receives notifications from SNS service? Is ti configured as Lambda to receive notifications? If yes, are you using or did you tries using [Amazon.Lambda.SNSEvents](https://github.com/aws/aws-lambda-dotnet/tree/master/Libraries/src/Amazon.Lambda.SNSEvents) package to receive notifications?

Thanks,
Ashish
