### ISSUE TITLE
Unable to retrieve Out Parameters of a Stored Procedure in Amazon Redshift

### ISSUE THREAD

**Issue by APTest22** [aws/aws-sdk-net#2450]
### Describe the bug

HI, I am unable to retrieve the Out Parameters of a Stored Procedure in Amazon Redshift , I am only able to retrieve the IN parameters , even INOUT parameters which are accepted when creating the stored procedure later are shown as IN parameters during retrieving them , the Out parameters are taken during the creation of the stored procedure but later not able to retrieve them . below is the following SQL Query I am using to retrieve the Stored Procedure parameters . 

" select proc.routine_name as procedure_name,args.parameter_name,args.parameter_mode,args.data_type from information_schema.routines proc left join information_schema.parameters args on proc.specific_schema = args.specific_schema and proc.specific_name = args.specific_name where proc.routine_schema not in ('pg_catalog', 'information_schema') and proc.routine_type = 'PROCEDURE' and proc.specific_name='{0}' order by procedure_name, args.ordinal_position"  

Please help me find a solution for this.
Thanks, and Regards

### Expected Behavior

To Retrieve the Out parameters of a Stored Procedure.

### Current Behavior

Unable to retrieve the out parameters.

### Reproduction Steps

1. Create a stored procedure on Amazon Redshift with IN parameters , INOUT parameters , Out parameters .
2. after successful creation use the following SQL Query to retrieve the parameters of the stored procedure.
3. "select proc.routine_name as procedure_name,args.parameter_name,args.parameter_mode,args.data_type from information_schema.routines proc left join information_schema.parameters args on proc.specific_schema = args.specific_schema and proc.specific_name = args.specific_name where proc.routine_schema not in ('pg_catalog', 'information_schema') and proc.routine_type = 'PROCEDURE' and proc.specific_name='{0}' order by procedure_name, args.ordinal_position"
4. As you can observe the IN parameters are being displayed , the INOUT parameters are also being displayed as IN Parameters , and no Out parameters are being displayed.

### AWS .NET SDK and/or Package version used

Amazon.RedshiftDataAPIService

### Targeted .NET Platform

.NET Framework 4.8

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment]
Hi @APTest22,

Good morning.

Thanks for reporting the issue. Kindly note that the SDK for RedshiftDataAPIService is autogenerated. Let me look into the issue. Could you please share the sample code for reference?

Thanks,
Ashish
