### ISSUE TITLE
Linux certificate issue

### ISSUE THREAD

**Issue by monicatudor** [aws/aws-sdk-net#2454]
### Describe the bug

On Linux can't upload documents using DOT NET 6 and AWSSDK.S3 3.7.9.69

### Expected Behavior

Upload the file to the bucket. This can be done from S3 CLI successfully. 

### Current Behavior

The file doesn't get uploaded. The error received is "System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch"

### Reproduction Steps
```C#
 private AmazonS3Client GetS3Client()
        {
            string clientAccessKey = _config["AWSSettings:AccessKey"];
            string clientSecretKey = _config["AWSSettings:SecretKey"];
            
            var configS3 = new AmazonS3Config
            {
                ServiceURL = _config["AWSSettings:Endpoint"],
                DisableHostPrefixInjection = true,
                UseHttp = bool.Parse(_config["AWSSettings:UseHttp"])
            };           


            if (bool.Parse(_config["AWSSettings:SetEndpoint"]))
            {
                return new AmazonS3Client(clientAccessKey, clientSecretKey, configS3);
            }
            else
            {

                return new AmazonS3Client(clientAccessKey, clientSecretKey, Amazon.RegionEndpoint.EUWest2);
            }

        }

        public async Task<string> UploadStream(Stream stream, string key)
        {
            try
            {
                stream.Position = 0;
                string bucketName = _config["AWSSettings:BucketName"];

                using var client = GetS3Client();
                using var transferUtility = new TransferUtility(client);

                var request = new PutObjectRequest
                {
                    BucketName = bucketName,
                    Key = key,
                   InputStream = stream
                };

                //var request = new TransferUtilityUploadRequest
                //{
                //    BucketName = bucketName,
                //    Key = key,
                //    InputStream = stream
                //};

                try
                {
                    //  await transferUtility.UploadAsync(request);
                    var response = await client.PutObjectAsync(request);
                    if (response.HttpStatusCode == System.Net.HttpStatusCode.OK)
                    {
                        Console.WriteLine($"Successfully uploaded {key} to {bucketName}.");
                        return "done";
                    }
                    else
                    {
                        Console.WriteLine($"Could not upload {key} to {bucketName}.");
                     
                        return $"Could not upload {key} to {bucketName}. {response}";
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Exception encountered on server when uploading file with key {key}. Message:'{ex}'");
                    return $" Upload exception2:{ex}";
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error creating the S3 client. Message:'{ex}'");
                return $" Upload exception1:{ex}"; ;
            }
        }
```

The client is using StorageGRID S3

### Possible Solution

The certificate is present on the server so resolve the RemoteCertificateNameMismatch or allow me to set the path to the certificate. But again, from AWS CLI everything is working as expected.

### Additional Information/Context

I need to use a different endpoint than aws. Also I need to disable the host prefix injection.

### AWS .NET SDK and/or Package version used

AWSSDK.S3 3.7.9.69

### Targeted .NET Platform

.NET 6

### Operating System and version

Linux RedHat 8.1

**Comment by ashishdhingra** [comment]
Hi @monicatudor,

Good afternoon.

Looks like you are using 3rd party service `StorageGRID S3` that simulates AWS S3 like operations. We do not support troubleshooting issues related to 3rd party service. AWS CLI might work fine, not sure if is doing any certificate validation.

Thanks,
Ashish

**Comment by monicatudor** [comment]
Hi, 
Thanks for your quick reply. I appreciate the fact that this is a 3rd party but it is actually using s3.

We know for sure that the AWS CLI is using the certificate. Before adding the certificate on the server, we had to run it with no-verify-ssl. After adding the certificate, the command works without it.

Is there a way with the currect dot net s3 sdk to maybe stop it from verifying the certificate?

**Comment by monicatudor** [comment]
Closed by mistake

**Comment by ashishdhingra** [comment]
> The remote certificate is invalid according to the validation procedure

@monicatudor No, it might not be possible since the underlying HttpClient implementation is not exposed. Refer https://github.com/aws/aws-sdk-net/issues/686#issuecomment-313287324.
