### ISSUE TITLE
Unable to get IAM security credentials from EC2 Instance Metadata Service.

### ISSUE THREAD

**Issue by ew-lei** [aws/aws-sdk-net#2455]
### Describe the bug

Now the s3 getObjectAsysnc is not working, it used to be work okay, after the .net sdk has been recently released all of our downloading function is stop working. 

- using ecs fargate, 
- we do create IAM Roles for Tasks for Amazon ECS tasks
- able to curl 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI inside the container 

<img width="491" alt="image" src="https://user-images.githubusercontent.com/40481280/196840340-391ad22d-25d3-4f13-baab-9eabd865f9f1.png">

<img width="249" alt="image" src="https://user-images.githubusercontent.com/40481280/196840218-43cca166-709a-40d8-9df3-b08e25c6b3e0.png">

### Expected Behavior

able to download the file from s3 

### Current Behavior

 The app is trying to download object from S3, following error throws:

One or more errors occurred. ---> Amazon.Runtime.AmazonServiceException: Unable to get IAM security credentials from EC2 Instance Metadata Service. at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.FetchCredentials() at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentials() at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentialsAsync() at Amazon.Runtime.Internal.CredentialsRetriever.d__7`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Amazon.Runtime.Internal.RetryHandler.d__10`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at Amazon.Runtime.Internal.RetryHandler.d__10`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Amazon.Runtime.Internal.CallbackHandler.d__9`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Amazon.Runtime.Internal.CallbackHandler.d__9`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Amazon.S3.Internal.AmazonS3ExceptionHandler.d__1`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Amazon.Runtime.Internal.ErrorCallbackHandler.d__5`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Amazon.Runtime.Internal.MetricsHandler.d__1`1.MoveNext() --- End of inner exception stack trace --- at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) at Conductor.Website.DownloadAgent.Page_Load(Object sender, EventArgs e) in C:\actions-runner2\_work\Conductor\Conductor\Conductor\Conductor.Website\DownloadAgent.aspx.cs:line 144 at System.Web.UI.Control.OnLoad(EventArgs e) at System.Web.UI.Control.LoadRecursive() at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) ---> (Inner Exception #0) Amazon.Runtime.AmazonServiceException: Unable to get IAM security credentials from EC2 Instance Metadata Service. at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.FetchCredentials() at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentials() at Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentialsAsync() at Amazon.Runtime.Internal.CredentialsRetriever.d__7`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Amazon.Runtime.Internal.RetryHandler.d__10`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at Amazon.Runtime.Internal.RetryHandler.d__10`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Amazon.Runtime.Internal.CallbackHandler.d__9`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Amazon.Runtime.Internal.CallbackHandler.d__9`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Amazon.S3.Internal.AmazonS3ExceptionHandler.d__1`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Amazon.Runtime.Internal.ErrorCallbackHandler.d__5`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Amazon.Runtime.Internal.MetricsHandler.d__1`1.MoveNext()<--- at System.Web.UI.Page.HandleError(Exception e) at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) at System.Web.UI.Page.ProcessRequest() at System.Web.UI.Page.ProcessRequest(HttpContext context) at ASP.downloadagent_aspx.ProcessRequest(HttpContext context) in c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary [ASP.NET](http://asp.net/) Files\root\166104bf\200c6145\App_Web_dmdxcgue.38.cs:line 0 at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

### Reproduction Steps

n/a

### AWS .NET SDK and/or Package version used

AWSSDK.S3 3.7.9.71
AWSSDK.Core 3.7.13.21

### Targeted .NET Platform

.net framework 4.7

### Operating System and version

docker image mcr.microsoft.com/dotnet/framework/aspnet:20181113-4.7.2-windowsservercore-ltsc2019

**Comment by ashishdhingra** [comment]
Hi @ew-lei,

Good morning.

Thanks for reporting the issue. As far as I could tell, there has been no change that could affect the credential resolution. Here are the changes I could see in changelog:
```
### 3.7.376.1 (2022-10-19 13:49 UTC)
...
* S3 (3.7.9.71)
	* Fixed S3 request marshallers to include xmlns attribute in root XML element to make it consistent with S3 API.

### 3.7.376.0 (2022-10-18 18:23 UTC)
...
* Core 3.7.13.21
	* Updating endpoints.json file.
	* All services packages updated to require new Core
```

The ECS task credentials are retrieved using [ECSEC2CredentialsWrapper](https://github.com/aws/aws-sdk-net/blob/b3b57beb79fc84d7e607f8ae3846a23dbd922111/sdk/src/Core/Amazon.Runtime/Credentials/FallbackCredentialsFactory.cs#L95) configured as one of the generators in [FallbackCredentialsFactory](https://github.com/aws/aws-sdk-net/blob/b3b57beb79fc84d7e607f8ae3846a23dbd922111/sdk/src/Core/Amazon.Runtime/Credentials/FallbackCredentialsFactory.cs#L49). This wrapper checks for the existence of either of the environment variables `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` and `AWS_CONTAINER_CREDENTIALS_FULL_URI`. If either one of them is present, it tries to get credentials from IAM role for ECS tasks. If these environment variables are not resolved or if there is any exception retrieving the credentials, then it tries to get credentials from EC2 instance metadata (via call to `DefaultInstanceProfileAWSCredentials.Instance`), which would obviously fail in your case.

Please share the following:
- Do you see any exception in your logs (if enabled) something like `Failed to access environment variables AWS_CONTAINER_CREDENTIALS_RELATIVE_URI and AWS_CONTAINER_CREDENTIALS_FULL_URI.`?
- Did anything changed for your environment?
- Looks like you are using `.NET Framework 4.7`, hence you might want to look at [Additional configuration for Windows IAM roles for tasks](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/windows_task_IAM_roles.html). Also look at `The IAM roles for the task credential provider use port 80 on the container instance. Therefore, if you configure IAM roles for tasks on your container instance, your containers can't use port 80 for the host port in any port mappings.` and `If your Windows instance is restarted, you must delete the proxy interface and initialize the Amazon ECS container agent again to bring the credential proxy back up.`.

Thanks,
Ashish
