### ISSUE TITLE
AwsSwfClient.PollForActivityTaskAsync InvokeAsync does not cancel the task pooling http call

### ISSUE THREAD

**Issue by IDontEatSoap** [aws/aws-sdk-net#246]
While using something like:

PollForActivityTaskResponse response = await AwsSwfClient.PollForActivityTaskAsync(request, CancellationTokenSource.Token);

and subsequently setting the token for cancellation, the blocking HTTP call is not canceled.

As a result, any incoming ActivityTask will be pooled and marked as started by SWF, when in fact they're just dropped and ignored by the .NET client. This will result in those activities not being actioned by the .NET client.

The correct behaviour would be the SDK completely dropping the HTTP long pool once the async call is cancelled.

To simulate, in order:

1 - call PollForActivityTaskAsync
2 - cancel the PollForActivityTaskAsync token
3 - queue a SWF activity while the PollForActivityTaskAsync still has a open http socket
4 - the SWF activity is picked up and left in the limbo by the .NET SDK

**Comment by gokarnm** [comment]
I'm able to replicate this issue. When the cancellation token is cancelled, the task returned by PollForActivityTaskAsync is cancelled, but the underlying HTTP connection is active for 60 seconds which is the duration of the long poll. I'm working on a fix, I'll update this issue when a fix is available.

**Comment by IDontEatSoap** [comment]
that's awesome, thanks :-)

**Comment by gokarnm** [comment]
On further investigation I found that the connection is not active for 60 seconds, I was using Fiddler to check the traffic and it does not show an accurate picture in this case. 
The SDK does a request abort when the request is cancelled. I did a packet capture using WireShark and see that a TCP FIN is sent to the server. The server seems to not respond to this causing retransmission of the TCP FIN a few times and the connections is closed using TCP RST. I saw a window of about 20 seconds between the time the client code gets and exception and when the connection is terminated. There may not be much that the SDK can fix in this scenario as it is already aborting the request when a cancellation request is made.

I have a few questions for you 

1. For the activities that get scheduled to the disconnected clients, what is the TaskStartToCloseTimeout being used? This can be set on the [RegisterActivityTypeRequest.DefaultTaskStartToCloseTimeout](https://github.com/aws/aws-sdk-net/blob/f5c9bce1d6303036718e1b0ad09fe481dd1b52c9/sdk/src/Services/SimpleWorkflow/Generated/Model/RegisterActivityTypeRequest.cs#L213) property. When activities are scheduled to a disconnected client, they would time-out after some time and be rescheduled to an active client. Are you seeing this behavior?

2. What is the scenario where you are cancelling the long poll, is this during application shut down?

**Comment by gokarnm** [comment]
Here is the update on this issue. In case of PollForActivityTaskAsync the client side cancellation will not work. As mentioned in the previous post, the SDK does abort the request but the server can continue to send data from it's end.

I contacted the SWF team and here is their response for shutting down a worker, if that is the reason the cancellation was used.

To gracefully shutdown a worker you need to take the following steps:

1) Shutdown triggered somehow
2) Suspended all workers. That means that no new calls for pollForAcivityTask/pollForDecisionTask will be issued to SWF. However the calls are in progress will not be interrupted.
3) Sleep for a while -> more than 70 seconds (time necessary for the pollForActivityTask/pollForDecisionTask to return) + how much an activity/decision takes to get executed. This is the key step, you need to keep the process running long enough for every activity picked up finishes.
4) Dispose the SWF clients used by the workers.

If the above doesn't work, they could do to unblock workflows by manually responding with cancelled/completed for the activity using our API:
http://docs.aws.amazon.com/amazonswf/latest/apireference/API_RespondActivityTaskCanceled.html 

Depending on retry policies they have configured this will either re-drive the task or fail the workflow.

**Comment by gokarnm** [comment]
Cancellation support for PollForActivityTask has been added as a feature request for SWF. I don't have a timeline on when this feature would be available. The current workaround would be to follow instructions from my previous reply on gracefully shutting down a worker.
