### ISSUE TITLE
Table.PutItemAsync not saving and not throwing an error

### ISSUE THREAD

**Issue by ncipollina** [aws/aws-sdk-net#2461]
### Describe the bug

We are attempting to update records via `Table.PutItemAsync` from a lambda function and the record is not updated. The same code works in a different lambda function pointing at another dynamodb table. The weird thing is that no exception is thrown. 

The function has the necessary permissions to update the table.

### Expected Behavior

I expected the record to be updated with the changes.

### Current Behavior

Table is not updated when calling Table.PutItemAsync. I added logic to have the put return all old attributes, and the return is null. The implementation is below:

```
    public virtual async Task Save(TEntity obj, CancellationToken cancellationToken = default)
    {
        var document = Document.FromJson(JsonSerializer.Serialize(obj));

        var response = await _table.PutItemAsync(document,
            new PutItemOperationConfig { ReturnValues = ReturnValues.AllOldAttributes }, cancellationToken);

        if (response is not null && response.Count > 0)
        {
            _logger.Debug("Record was updated");
        }
        else
        {
            _logger.Debug("Record was inserted");
        }
    }
```

### Reproduction Steps

Code snippet we are using to actually connect to the table was provided above.

### AWS .NET SDK and/or Package version used

AWSSDK.DynamoDBv2/3.7.100

### Targeted .NET Platform

.Net 6

### Operating System and version

Lambda

**Comment by ncipollina** [comment]
One quick note, if I change the implementation to use an `IAmazonDynamoDB` implementation instead of table, the record saves. It looks like under the hood the Table implementation uses that as well.

**Comment by ncipollina** [comment]
Ok, I found the issue. Pointing at the wrong table. Nothing to see here...

**Comment by BirgitPohl** [comment]
But then in this case, you want to see an error saying wrong table, or something. Error messages would be useful. I have a similar case of debugging the unknown as no error is thrown.
