### ISSUE TITLE
Compile fail when using Xamarin.iOS 9.0.1.18 with Xcode7

### ISSUE THREAD

**Issue by agasbzj** [aws/aws-sdk-net#248]
It says: Error MT2001: Could not link assemblies. Reason: Can't not find the nested type '<Amazon.Runtime.SharedInterfaces.ICoreAmazonS3.DeleteAsync>d__3' in 'Amazon.S3.AmazonS3Client (MT2001)

Reference to Xamarin, they explained: Bug 33124 - [iOS] Certain libraries that were compiled by the Microsoft C# 5 compiler (VS 2013) cause "error MT2001: Could not link assemblies. Reason: Can't not find the nested type" during the linking phase of the Xamarin.iOS build process. (For example, any library compiled by VS 2013 that uses an async lambda within a constructor will hit this problem.) 

Please update the lib as soon as possible, thanks.

**Comment by karthiksaligrama** [comment]
This issue should be fixed in Xamarin iOS release 9.0.1.20

For further details please take a look at https://bugzilla.xamarin.com/show_bug.cgi?id=33124. Please update your xamarin version and give it a shot. Let us know if the problem still persists.
