### ISSUE TITLE
Add support for new eu-central-2 region

### ISSUE THREAD

**Issue by ckuehl** [aws/aws-sdk-net#2481]
### Describe the feature

The new eu-central-2 region announced today is not yet supported as a `RegionEndpoint`. Please add support for it.

### Use Case

I want to use the APIs for the new eu-central-2 region.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

3.7.100.14

### Targeted .NET Platform

.NET 6

### Operating System and version

all

**Comment by ashishdhingra** [comment]
Needs review with the team.

**Comment by ashovlin** [comment]
`RegionEndpoint.EUCentral2` now appears in [AWSSDK.Core v3.7.100.15](https://www.nuget.org/packages/AWSSDK.Core/3.7.100.15) via https://github.com/aws/aws-sdk-net/commit/a268504583a65f2fd9aee01d592042207bd3d0fb.

We're taking a look internally at streamlining the process that delivers new regions into the SDK build systems.

**Comment by ckuehl** [comment]
@ashovlin Can we get the same change now for the new `eu-south-2`?

**Comment by ashovlin** [comment]
@ckuehl That flowed through in today's [AWSSDK.Core 3.7.100.19](https://www.nuget.org/packages/AWSSDK.Core/3.7.100.19)  via https://github.com/aws/aws-sdk-net/commit/5ca32fc4165d60e7fd65456cfd187c0c217f8b78.
