### ISSUE TITLE
AOT / trimmed support for .net 7

### ISSUE THREAD

**Issue by kjpgit** [aws/aws-sdk-net#2486]
### Describe the feature

Would like to use the SDK in AOT compiled mode.

This is already supported for java: https://aws.amazon.com/blogs/developer/graalvm-native-image-support-in-the-aws-sdk-for-java-2-x/

AOT works on lambda but without AWS SDK it's not very useful: https://github.com/awslabs/dotnet-nativeaot-labs

However in c# 7, I get trim warnings, and a crash on startup, using the S3 SDK with a console CLI program on linux.

/home/k/.nuget/packages/awssdk.core/3.7.100.16/lib/netcoreapp3.1/AWSSDK.Core.dll : warning IL2104: Assembly 'AWSSDK.Core' produced trim warnings. For more information see https://aka.ms/dotnet-illink/libraries [/home/k/github/aws-dotnet7/src/aot/aot.csproj]
/home/k/.nuget/packages/awssdk.core/3.7.100.16/lib/netcoreapp3.1/AWSSDK.Core.dll : warning IL3053: Assembly 'AWSSDK.Core' produced AOT analysis warnings. [/home/k/github/aws-dotnet7/src/aot/aot.csproj]
/home/k/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.0/framework/System.Net.Http.dll : warning IL3053: Assembly 'System.Net.Http' produced AOT analysis warnings. [/home/k/github/aws-dotnet7/src/aot/aot.csproj]
/home/k/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.0/framework/System.Private.Xml.dll : warning IL3053: Assembly 'System.Private.Xml' produced AOT analysis warnings. [/home/k/github/aws-dotnet7/src/aot/aot.csproj]

Unhandled Exception: System.TypeInitializationException: A type initializer threw an exception. To determine which type, inspect the InnerException's StackTrace property.
 ---> System.TypeInitializationException: A type initializer threw an exception. To determine which type, inspect the InnerException's StackTrace property.
 ---> System.MissingMethodException: No parameterless constructor defined for type 'Amazon.Util.Internal.PlatformServices.NetworkReachability'.
   at System.ActivatorImplementation.CreateInstance(Type, Boolean) + 0x120
   at Amazon.Util.Internal.PlatformServices.ServiceFactory..ctor() + 0x144

### Use Case

Frustrated when CLI programs don't start fast.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

Include="AWSSDK.S3" Version="3.7.101.16

### Targeted .NET Platform

.net 7

### Operating System and version

ubuntu

**Comment by ashishdhingra** [comment]
@kjpgit Thanks for submitting the feature request. Please refer the blog post [Building serverless .NET applications on AWS Lambda using .NET 7](https://aws.amazon.com/blogs/compute/building-serverless-net-applications-on-aws-lambda-using-net-7/) for the Native AOT support. As mentioned, currently, the AWSSDK.Core library used by all the .NET AWS SDKs must also be excluded from trimming. Please review if it provides explanation for the above issue and confirm if this ticket could be closed.

Thanks,
Ashish

**Comment by kjpgit** [comment]
Why on earth are you asking me to close a feature request before it has been implemented???

**Comment by kjpgit** [comment]
I'm not using lambda, just creating a CLI program.  But I read that blog post, and the exclude trimming steps do not work for me.

my aot.csproj:

```
Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PublishAot>true</PublishAot>
    <StripSymbols>true</StripSymbols>

    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Core" Version="3.7.100.21" />
    <PackageReference Include="AWSSDK.S3" Version="3.7.101.21" />
  </ItemGroup>

  <ItemGroup>
      <RdXmlFile Include="rd.xml" />
  </ItemGroup>

</Project>
```

my rd.xml:

```
<Directives xmlns="http://schemas.microsoft.com/netfx/2013/01/metadata">
    <Application>
        <Assembly Name="AWSSDK.Core" Dynamic="Required All"></Assembly>
        <Assembly Name="AWSSDK.S3" Dynamic="Required All"></Assembly>
        <Assembly Name="aot" Dynamic="Required All"></Assembly>
    </Application>
</Directives>
```
```
$ dotnet --version
7.0.100

$ NO_COLOR=1 dotnet publish -r linux-x64 -c Release
MSBuild version 17.4.0+18d5aef85 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  aot -> /home/karl/incoming/aws-dotnet7/src/aot/bin/Release/net7.0/linux-x64/aot.dll
  Generating native code
/home/karl/.nuget/packages/awssdk.core/3.7.100.21/lib/netcoreapp3.1/AWSSDK.Core.dll : warning IL2104: Assembly 'AWSSDK.Core' produced trim warnings. For more information see https://aka.ms/dotnet-illink/libraries [/home/karl/incoming/aws-dotnet7/src/aot/aot.csproj]
/home/karl/.nuget/packages/awssdk.core/3.7.100.21/lib/netcoreapp3.1/AWSSDK.Core.dll : warning IL3053: Assembly 'AWSSDK.Core' produced AOT analysis warnings. [/home/karl/incoming/aws-dotnet7/src/aot/aot.csproj]
/_/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/CryptoConfigForwarder.cs(21): Trim analysis warning IL2026: System.Security.Cryptography.CryptoConfigForwarder..cctor(): Using member 'System.Security.Cryptography.CryptoConfigForwarder.BindCreateFromName()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. The default algorithm implementations might be removed, use strong type references like 'RSA.Create()' instead. [/home/karl/incoming/aws-dotnet7/src/aot/aot.csproj]
/home/karl/.nuget/packages/runtime.linux-x64.microsoft.dotnet.ilcompiler/7.0.0/framework/System.Private.Xml.dll : warning IL3053: Assembly 'System.Private.Xml' produced AOT analysis warnings. [/home/karl/incoming/aws-dotnet7/src/aot/aot.csproj
```

**Comment by kjpgit** [comment]
I see, even though there are still scary warnings from `dotnet publish`, it does NOT crash anymore when I run the exe.  It successfully does a S3 file listing for me.   So that's exciting, I guess.  

You can close this ticket.  Hopefully the SDK will get better docs on this, and support trimming in the future.
