### ISSUE TITLE
Unable to use MediaConvert without specifying the Width of VideoDescription

### ISSUE THREAD

**Issue by ackava** [aws/aws-sdk-net#2488]
### Describe the bug

While in the console, we can create a job without specifying the width, we are only providing height as 720.

That is because the Model `VideoDescription` is wrong.

```c#
        // Summary:
        //     Gets and sets the property Width. Use Width (Width) to define the video resolution
        //     width, in pixels, for this output. If you don't provide a value here, the service
        //     will use the input width.
        [AWSProperty(Min = 32L, Max = 8192L)]
        public int Width
        {
            get
            {
                return _width.GetValueOrDefault();
            }
            set
            {
                _width = value;
            }
        }
``` 

This means that you are forcing us to provide Width in the form of an integer, which is 0 by default and validator tells us that Min Width should be 32. But I do not want to specify the width at all. The documentation says that if we don't provide the width, the converter will take input file's width.

### Expected Behavior

Width should be nullable and should accept null as correct or empty value.

### Current Behavior

```
Error: 
The 'role' field is required. | /outputGroups/0/outputs/0/videoDescription/width: Should be greater than or equal to 32
```

### Reproduction Steps

Simple create a Conversion Job by specifying only height.

### Possible Solution

Make `Width` nullable.

### AWS .NET SDK and/or Package version used

3.7.101.10

### Targeted .NET Platform

.NET 6

### Operating System and version

Windows 10

**Comment by ackava** [comment]
@ashishdhingra 

I have not set the `Width` property, I am only setting `Height` and it gives me the error, Irrespective of Width is set to 0 or not set, I am getting same error.
```
/outputGroups/0/outputs/0/videoDescription/width: Should be greater than or equal to 32
```

**Comment by ashishdhingra** [comment]
> @ashishdhingra 
> 
> 
> 
> I have not set the `Width` property, I am only setting `Height` and it gives me the error, Irrespective of Width is set to 0 or not set, I am getting same error.
> 
> ```
> 
> /outputGroups/0/outputs/0/videoDescription/width: Should be greater than or equal to 32
> 
> ```
@ackava Please share the sample code to troubleshoot the issue.
