### ISSUE TITLE
Version mismatch between NuGet and tags

### ISSUE THREAD

**Issue by niralatuladhar** [aws/aws-sdk-net#2489]
### Describe the issue

[aws sdk doc](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-install-assemblies.html) mentions **nuget always has the latest version of AWS SDK**. However, the latest version specified in [aws sdk tags](https://github.com/aws/aws-sdk-net/tags) does not match with one specified in [NuGet AWS SDK]( https://www.nuget.org/packages/AWSSDK.Core). They are off by 300 + 
https://github.com/aws/aws-sdk-net/tags has [3.7.422.0](https://github.com/aws/aws-sdk-net/releases/tag/3.7.422.0) as latest while Nuget has 3.7.100.21

Which one should we follow?

### Links

https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-install-assemblies.html 
https://github.com/aws/aws-sdk-net/tags
https://www.nuget.org/packages/AWSSDK.Core

**Comment by normj** [comment]
Hi @niralatuladhar 

The repository has the concept of a product version which is that bigger version number you are seeing. A product version is the collection of the service/core package versions that were released as part of that product version. Hopefully it makes a bit more sense from the context of the change log https://raw.githubusercontent.com/aws/aws-sdk-net/master/SDK.CHANGELOG.md

The product version doesn't have much meaning for users pulling the SDK from NuGet but we do have some users that pull the SDK from our zip files of the all the assemblies.

**Comment by ashishdhingra** [comment]
Closing this since relevant information has been provided.
