### ISSUE TITLE
CloudWatch Logs "PutDestination" operation is missing from .NET SDK

### ISSUE THREAD

**Issue by ardave** [aws/aws-sdk-net#249]
As defined here:  https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutDestination.html

The CLI appears to support this operation, so this is just a "nice to have."

**Comment by jimfl** [comment]
What version of the SDK do you have? The operation does seem to be there: 

https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/CloudWatchLogs/Generated/_bcl45/AmazonCloudWatchLogsClient.cs#L1329

**Comment by ardave** [comment]
Couple of months behind on my end, but I see the operation in 2.3.52.  Please disregard, and thanks!
