### ISSUE TITLE
Combination Xray tracing & IAmazonBatch throws ' Cannot find a handler of type EndpointResolver '

### ISSUE THREAD

**Issue by timstuyckens** [aws/aws-sdk-net#2492]
### Describe the bug

An exception is thrown when resolving the IAmazonBatch batch service when Xray OTEL tracing is configured as described in 
https://aws-otel.github.io/docs/getting-started/dotnet-sdk/trace-manual-instr#sending-traces-to-aws-x-ray 

Related packages
- "OpenTelemetry.Contrib.Extensions.AWSXRay" Version="1.2.0" 
- "OpenTelemetry.Contrib.Instrumentation.AWS" Version="1.0.1" 
- "AWSSDK.Batch" Version="3.7.101.23" 
- "AWSSDK.Extensions.NETCore.Setup" Version="3.7.2"

Same project also uses IAmazonS3 and this works.

### Expected Behavior

AmazonBatchClient service can be initialised

### Current Behavior

**Stacktrace**
`
System.InvalidOperationException: Cannot find a handler of type EndpointResolver at Amazon.Runtime.Internal.RuntimePipeline.AddHandlerAfter[T](IPipelineHandler handler) at Amazon.Runtime.Internal.RuntimePipelineCustomizerRegistry.ApplyCustomizations(Type type, RuntimePipeline pipeline) --- End of inner exception stack trace --- at System.RuntimeMethodHandle.InvokeMethod(Object target, Span1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions) at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at Amazon.Extensions.NETCore.Setup.ClientFactory.CreateClient(Type serviceInterfaceType, AWSCredentials credentials, ClientConfig config) at Amazon.Extensions.NETCore.Setup.ClientFactory.CreateServiceClient(ILogger logger, Type serviceInterfaceType, AWSOptions options) at Amazon.Extensions.NETCore.Setup.AWSOptions.CreateServiceClient[T
`

If the commented lines are uncommented
![image](https://user-images.githubusercontent.com/1768681/204743478-6766291c-7280-4d16-900f-c62c0bb1c7b7.png)

### Reproduction Steps

**ConfigureServices**

`
            services.AddOpenTelemetryTracing(builder =>  builder.SetResourceBuilder(resourceBuilder)
                .AddXRayTraceId() // for generating AWS X-Ray compliant trace IDs
                .AddOtlpExporter(options =>
                {
                    options.Endpoint = telemetryConfig.Endpoint;
                }));
Sdk.SetDefaultTextMapPropagator(new AWSXRayPropagator()); // configure AWS X-Ray propagator
`

### Possible Solution

Sound related to https://github.com/aws/aws-xray-sdk-dotnet/issues/267

### AWS .NET SDK and/or Package version used

AWSSDK.Batch   3.7.101.23

### Targeted .NET Platform

.NET 6

### Operating System and version

docker mcr.microsoft.com/dotnet/aspnet:6.0

**Comment by ashishdhingra** [comment]
Hi @timstuyckens,

Good morning. Thanks for reporting the issue.

Could you please try upgrading to `OpenTelemetry.Contrib.Instrumentation.AWS` version `1.0.2` and confirm if it fixes the issue?

Thanks,
Ashish

**Comment by DownChapel** [comment]
Hi, @ashishdhingra upgrading to `OpenTelemetry.Contrib.Instrumentation.AWS` version `1.0.2` seems to have fixed the issue for me.

**Comment by timstuyckens** [comment]
Hi @ashishdhingra 

Thanks for the feedback, ugrading the package fixed the issue (same as @DownChapel  )

Kind regards,
Tim.
