### ISSUE TITLE
scheduler:CreateSchedule does not allow Target RoleArn to contain nested roles

### ISSUE THREAD

**Issue by LuckysGoat** [aws/aws-sdk-net#2495]
### Describe the bug

We are attempting to use the AmazonSchedulerClient to create a new schedule using the CreateScheduleAsync method. When I execute the method I get a validation error regarding the RoleArn of the target:

`Amazon.Scheduler.Model.ValidationException: 1 validation error detected: Value <ARNVALUE> at 'target.roleArn' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:aws(-[a-z]+)?:iam::\\d{12}:role\\/(service-role\\/){0,1}[a-zA-Z0-9\\+=,\\.@\\-_]+\r\n`

The regex is expecting a non-custom role, i.e. it is not allowing me to submit an arn like this:

arn:aws:iam::123456789011:role/first/second/role-name

 Is this validation correct? 

### Expected Behavior

Submitting a custom role arn as the RoleArn for the Target when creating a Schedule should be valid.

### Current Behavior

Submitting a custom role arn as the RoleArn for the Target when creating a Schedule is not valid

### Reproduction Steps

Use the sdk to create a Schedule, use a custom role arn for the Target.RoleArn property.

### Possible Solution

Update the validation for the Target.RoleArn property.

### AWS .NET SDK and/or Package version used

AWSSDK.Scheduler 3.7.100.13

### Targeted .NET Platform

.NET 6.0

### Operating System and version

Windows 10

**Comment by charryson** [comment]
I'm seeing this also; this seems to make it impossible to create a schedule with the SDK. It looks like the same schedule can be fully created the same schedule directly in console.

**Comment by indrora** [comment]
This isn't specific to the .NET SDK... This appears to be a failure by the EventBridge scheduler team: https://docs.aws.amazon.com/scheduler/latest/APIReference/API_Target.html

This regular expression is defined by the service on the AWS side.

**Comment by LuckysGoat** [comment]
Ahhh thanks! Did some googling but never found this document. Anyone know how to report it to the scheduler team?

**Comment by ashishdhingra** [comment]
> https://docs.aws.amazon.com/scheduler/latest/APIReference/API_Target.html

@indrora Thanks for linking to the API doc.

@LuckysGoat / @charryson Could you please share the following:
- Type of role you are using when specifying `arn:aws:iam::123456789011:role/first/second/role-name`? Are these service-linked roles (refer [Using service-linked roles](https://docs.aws.amazon.com/IAM/latest/UserGuide/using-service-linked-roles.html)?
- The service and it's use case when creating service linked role.

The [How EventBridge Scheduler works with IAM](https://docs.aws.amazon.com/scheduler/latest/UserGuide/security_iam_service-with-iam.html#security_iam_service-with-iam-roles-service) specifies that service linked roles are not supported right now. So just wondering how you are able to specify the `RoleArn` in the target via AWS Console.

Thanks,
Ashish

**Comment by LuckysGoat** [comment]
@ashishdhingra 
We are not using service-linked roles.

**Comment by ashishdhingra** [comment]
> @ashishdhingra We are not using service-linked roles.

@LuckysGoat Could you please share what type of role you are using? May be share the role Arn and screenshot from AWS Console which allows to use such a role.

Thanks,
Ashish

**Comment by sbocz** [comment]
Looks like this was fixed in https://github.com/aws/aws-sdk-net/commit/65771a57803721d609140792520d59fd0d0e8a5b
