### ISSUE TITLE
Accessibility concern for link on main website

### ISSUE THREAD

**Issue by tannerdolby** [aws/aws-sdk-net#2497]
### Describe the bug

The `:hover` state for a link right above the "Create a Free Account" button becomes very difficult to read with due to its dark font color on a dark background.
 
<img width="680" alt="Screen Shot 2022-12-10 at 8 49 19 PM" src="https://user-images.githubusercontent.com/48612525/206887062-23394b84-9bec-493a-97bf-61f2152fc9f2.png">

### Current Contrast Ratio
- https://webaim.org/resources/contrastchecker/

<img width="443" alt="Screen Shot 2022-12-10 at 8 29 03 PM" src="https://user-images.githubusercontent.com/48612525/206886976-bea62032-0c59-466c-aaac-e2601c034982.png">

### Expected Behavior

For the link to be visible when hovered and have similar `:hover` styling/behavior as the other links which use the same `#232F3E` background color.

### Current Behavior

Bad contrast (1.04:1) making the link tough to read. It currently has a hover state text color of `#033160` on a `#232F3E` background.

### Reproduction Steps

- Go to https://aws.amazon.com/free/?all-free-tier.sort-by=item.additionalFields.SortRank&all-free-tier.sort-order=asc&awsf.Free%20Tier%20Types=*all&awsf.Free%20Tier%20Categories=*all
- Look for the link 'Learn more about AWS Free Tier' at the top of the page and hover your mouse over the link
- See the bad contrast as the link becomes difficult to see due to its hover state font color

### Possible Solution

Use the same font-color for this links `:hover` state as the menu items in navbar `#f8991d`.

### Additional Information/Context

I couldn't find anywhere on GitHub to file an issue for aws.amazon.com, so I apologize for posting this here. Just thought it would be the quickest way to get the ticket some visibility and your team can transfer it to the correct repo or pass word along to frontend folks to update the hover state for that link to avoid accessibility issues.

### AWS .NET SDK and/or Package version used

N/A

### Targeted .NET Platform

N/A

### Operating System and version

macOS Ventura

**Comment by ashishdhingra** [comment]
@tannerdolby Please advise if you see `Send Feedback` link somewhere (most probably at the bottom) of the page. You may send the feedback using that link. Else I could help routing this to internal team.

**Comment by tannerdolby** [comment]
@ashishdhingra Thanks for the response. I saw a "Send Feedback" link on another page, but not on the page mentioned in this accessibility issue. Here is what I see in the footer, there is a "File a support ticket" but its more of a bug ticket, not support. Maybe best to just route this to internal team if possible.

**Comment by ashishdhingra** [comment]
P78014839

**Comment by ashishdhingra** [comment]
@tannerdolby Apologies for late reply. I have opened ticket with the internal team. Closing this issue here in .NET SDK repo.

**Comment by tannerdolby** [comment]
@ashishdhingra No problem! Thank you for getting this ticket the proper visibility. Happy holidays!
