### ISSUE TITLE
s3FileInfo.Exists returns 403 Forbidden with limited credentials

### ISSUE THREAD

**Issue by jcmurphy** [aws/aws-sdk-net#250]
Hello.  I am using version 3.1.0.0.  When I call S3FileInfo.Exists using a credential with limited access I get 403 Forbidden instead of false.  The policy I'm using is:

```
{
	"Sid": "Stmtxxxx",
	"Effect": "Allow",
	"Action": [
		"s3:*"
	],
	"Resource": [
		"arn:aws:s3:::my_bucket/*"
	]
}
```

With this policy in effect, the following code throws 403 Forbidden:

```csharp
S3FileInfo s3FileInfo = new Amazon.S3.IO.S3FileInfo(s3Client, "my_bucket", "filethatdoesntexist");
if (s3FileInfo.Exists)
{
	fileExists = true;
}
```

If I add the AmazonS3FullAccess policy to the user then the code works as expected.  Thanks for looking into this.

**Comment by normj** [comment]
If you update the policy to the following it will work.

```
{
    "Sid": "Stmtxxxx",
    "Effect": "Allow",
    "Action": [
        "s3:*"
    ],
    "Resource": [
        "arn:aws:s3:::my_bucket/*",
        "arn:aws:s3:::my_bucket"
    ]
}
```

Looks like doing a HEAD request to the bucket for objects that don't exist are considered a bucket operation so you need to add that extra resource.

**Comment by jcmurphy** [comment]
Perfect, that does the trick.  Thanks for the quick response.
