### ISSUE TITLE
Upload Using presigned url not working intermittently in Canada region

### ISSUE THREAD

**Issue by rupamroy** [aws/aws-sdk-net#2500]
### Describe the bug

I am uploading a bunch of files one after another to s3 , for each file I am getting a presigned url from server and then using that to upload the corresponding file to S3. 
The code runs fine in US-east region , but when running that in Canada Central , the same code is intermittently failing , one file is getting uploaded , then randomly another is failing to upload. For those failing to upload we are getting a SignatureDoesMatch exception. 
The only difference between us and Canada is that we are not using KMS-server side encryption in Canada, But I don't think that is an issue since if encryption was an issue possibly all requests would fail. The presigned url is being set with an expiry time of 600 seconds. 

I am clueless about how to find out from the exception or through any other methods what's is causing the signature to mismatch for some of the files and why only in Canada.

Any suggestions regarding this would be very helpful . IF there is a place in S3 logs/flowlogs etc that i can see why the signature mismatched let me know. 

Highly appreciate the help. 

### Expected Behavior

The file upload should happen fine in Canada-central region as it is happening for us-east  . 

### Current Behavior

The code runs fine in US-east region , but when running that in Canada Central , the same code is intermittently failing , one file is getting uploaded , then randomly another is failing to upload. For those failing to upload we are getting a SignatureDoesMatch exception. 

### Reproduction Steps

This is a suggestion required to point to what I could look for.

### AWS .NET SDK and/or Package version used

AWSSDK Core 3.7.100.17

### Targeted .NET Platform

.NET 6

### Operating System and version

6.0-ALPINE Base Image for docker

**Comment by ashishdhingra** [comment]
Hi @rupamroy,

Good afternoon.

Could you please share the following:
- Sample code to reproduce the issue?
- What is the region used to generate pre-signed URL?
- How are you using pre-signed URL to upload files files to S3? Are you downloading the file first and then uploading the file to S3?
- What is the average size of file?
- How long does code execute before it fails?
- Could you also check the region used while uploading file to S3?
- Are you getting signature mismatch error while downloading the file using presigned URL or while uploading file to S3?
- Could you enable verbose logging using the code below and share the detailed logs?
```C#
Amazon.AWSConfigs.LoggingConfig.LogResponses = Amazon.ResponseLoggingOption.Always;
Amazon.AWSConfigs.LoggingConfig.LogTo = Amazon.LoggingOptions.SystemDiagnostics;
Amazon.AWSConfigs.AddTraceListener("Amazon", new System.Diagnostics.ConsoleTraceListener()
```

Thanks,
Ashish

**Comment by rupamroy** [comment]
Thanks Ashish, 

Creating the sample code would be very difficult , and whether i can reproduce it in sample code i am not sure, but will give it a try, Right now I can give you the Http request/responses from the browser captured in chrome developer tools , if you think that will pass. I can provide you for both the passing ones and the failing ones. Do you think that will help?

While i do that here are the answers to some of your questions:

- What is the region used to generate pre-signed URL? - Canada-central
- How are you using pre-signed URL to upload files files to S3? Are you downloading the file first and then uploading the file to S3? - We get the signedurl from the server , the directly upoloading the files to S3 from the browsers
- What is the average size of file? - Varies - 50mb to 1Gb (file does not matter it seems , it fails randonly).
- How long does code execute before it fails? there is no code execution , it is a direct upload to S3 from browser, we start uploading a batch some gets uploaded and some start failing , the one which fails do fail on 3 auto retry's (we have auto retry configured for any failure)
- Could you also check the region used while uploading file to S3? (Ca-central)
- Are you getting signature mismatch error while downloading the file using presigned URL or while uploading file to S3? - while uploading the file to S3
- Could you enable verbose logging using the code below and share the detailed logs? These will only enable the logs for getting the signedurl , the upload happens directly from browser so there is no AWSConfig or aws sdk there. You still want these?

Could you also let me know if Canada-central has any rate limit imposed on S3 , we are sending 2 files at a time to s3 and then the set of next 2 files , is there any difference between rate of upload allowed between US and Canada.

**Comment by ashishdhingra** [comment]
> Could you also let me know if Canada-central has any rate limit imposed on S3 , we are sending 2 files at a time to s3 and then the set of next 2 files , is there any difference between rate of upload allowed between US and Canada.

@rupamroy Please refer [Amazon Simple Storage Service endpoints and quotas](https://docs.aws.amazon.com/general/latest/gr/s3.html) for more details. As requested earlier, please share the following:
- Sample code which reproduces the issue.
  - For Presigned URL generation (BTW, I'm curious how you are using presigned URL to upload the files since AWSSDK.S3 does not currently support Presigned URL POST.)
  - For using the Presigned URL to upload files.
- How are credentials and region configured and resolved?
- Any logs for failed uploads (may be browser logs could help).

Thanks,
Ashish

**Comment by nabilkem1** [comment]
i confirm i have the same issue! working finr in us-east-1 but th epre-signed url started the issue on us-east-1
