### ISSUE TITLE
System.InvalidOperationException: Unable to convert [Amazon.DynamoDBv2.DocumentModel.DynamoDBNull] of type Amazon.DynamoDBv2.DocumentModel.DynamoDBNull to System.String

### ISSUE THREAD

**Issue by cjkarande** [aws/aws-sdk-net#2502]
### Describe the bug

DynamoDBContext.QueryAsync has suddenly started throwing System.InvalidOperationException on query operation after upgrading Visual Studio from 2019 (16.11) to 2022 (17.4.3). We are using DynamoDB in our Xamarin.Forms App.

It seems kind of weird as we did not do any code changes or library updates. This was working fine in VS 2019. 

### Expected Behavior

DynamoDBContext.QueryAsync API call should succeed.

### Current Behavior

DynamoDBContext.QueryAsync API throws the following exception

System.InvalidOperationException: Unable to convert [Amazon.DynamoDBv2.DocumentModel.DynamoDBNull] of type Amazon.DynamoDBv2.DocumentModel.DynamoDBNull to System.String

### Reproduction Steps

After rebuilding the Xamarin Forms project in VS 2022. Our App throws the following exception for DynamoDBContext.QueryAsync API call

System.InvalidOperationException: Unable to convert [Amazon.DynamoDBv2.DocumentModel.DynamoDBNull] of type Amazon.DynamoDBv2.DocumentModel.DynamoDBNull to System.String

### Additional Information/Context

Microsoft Visual Studio Community 2022
Version 17.4.3
VisualStudio.17.Release/17.4.3+33205.214
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

ASP.NET and Web Tools   17.4.326.54890
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.4.326.54890
Azure App Service Tools v3.0.0

C# Tools   4.4.0-6.22580.4+d7a61210a88b584ca0827585ec6e871c6b1c5a14
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Extensibility Message Bus   1.4.1 (main@2ee106a)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.4.19 (8c0a575)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.40817.1 Commit Hash:66443775f9f3b1d8f8fee47af5002828b346688d
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   6.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.0.0.2246202+61cc048d36a3fc9246d2f04625988b19a18ab8f0
Provides languages services for ASP.NET Core Razor.

TypeScript Tools   17.0.10921.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.4.0-6.22580.4+d7a61210a88b584ca0827585ec6e871c6b1c5a14
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.4.0-beta.22512.4+525d5109e389341bb90b144c24e2ad1ceec91e7b
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.4.0.312 (d17-4@be7e8d1)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.4.0.138 (remotes/origin/d17-4@d36bba3cc9)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.4.2 (c457c97)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.1.0.1 (d17-4/13ba222)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: a96bde9
    Java.Interop: xamarin/java.interop/d17-4@fcc33ce2
    SQLite: xamarin/sqlite/3.39.3@23e1ae7
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@0be567a

Xamarin.iOS and Xamarin.Mac SDK   16.1.1.27 (933c6c2c9)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### AWS .NET SDK and/or Package version used

AWSSDK.DynamoDBv2 (3.7.101.9)

### Targeted .NET Platform

.NET Standard 2.0

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment]
@cjkarande Thanks for reporting the issue. The said error should not be a result of Visual Studio upgrade. Could you please share minimal sample code to reproduce the issue?

Thanks,
Ashish

**Comment by cjkarande** [comment]
@ashishdhingra . Below is the sample code 

var records = await AWSServiceProvider.DynamoDBService.Context.QueryAsync<User>(countryCode, QueryOperator.Equal, new List<string> { mobileNumber }).GetNextSetAsync();


It throws the following exception. 

System.InvalidOperationException: Unable to convert [Amazon.DynamoDBv2.DocumentModel.DynamoDBNull] of type Amazon.DynamoDBv2.DocumentModel.DynamoDBNull to System.String


PS: This code was working fine earlier when built in VS2019. Not sure if this has to do anything with the change in the .NET runtime & .NET framework versions, post VS 2022 upgrade

**Comment by ashishdhingra** [comment]
> DynamoDBNull

@cjkarande Thanks for the reply. Could you please share the following so that I could reproduce the issue:
- You mentioned you upgraded from Visual Studio from 2019 to 2022. This should not affect the code. Did you also update the `AWSSDK.DynamoDBv2` package as well? If yes, from what version?
- Details about the DynamoDB table schema (like HaskKey, SortKey).
- Sample data. Also does the sample data has NULL value in any of the fields, such as in Sort Key?

Thanks,
Ashish

**Comment by cjkarande** [comment]
@ashishdhingra , 
- AWSSDK.DynamoDBv2 version during VS2019 was 3.5.4.34 which I initially built with as-is post VS2022 upgrade and discovered this issue. Later I tried updating it to the latest version of 3.7.101.9, however, the problem still persists
- Table has a Hash key and Sort key both of type String and have valid string values (Not Null). The existing records in the table have been persisted earlier through App using DynamoDB APIs during VS2019 time.
-  As we cannot persist Null values for Keys they all have Not Null string values. Some of the other String attributes had Null values and they were working fine earlier. I even tried to replace these Null String attributes with empty strings ("") directly from the AWS console, but the issue still persists and the APIs like LoadAsync and QueryAsync throw the aforementioned exception.
Regards,
CP

**Comment by ashishdhingra** [comment]
> @ashishdhingra ,
> 
> * AWSSDK.DynamoDBv2 version during VS2019 was 3.5.4.34 which I initially built with as-is post VS2022 upgrade and discovered this issue. Later I tried updating it to the latest version of 3.7.101.9, however, the problem still persists
> * Table has a Hash key and Sort key both of type String and have valid string values (Not Null). The existing records in the table have been persisted earlier through App using DynamoDB APIs during VS2019 time.
> * As we cannot persist Null values for Keys they all have Not Null string values. Some of the other String attributes had Null values and they were working fine earlier. I even tried to replace these Null String attributes with empty strings ("") directly from the AWS console, but the issue still persists and the APIs like LoadAsync and QueryAsync throw the aforementioned exception.
>   Regards,
>   CP

@cjkarande Thanks for the reply. As requested earlier, 
- Could you please share sample data (showing hash and sort key values, including rows with null values) and schema details?
- Sample code project with model class. (as an example, refer https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBContext.QueryScan.html)

You may remove sensitive data and replace them with dummy values. I need these details to reproduce the issue. The scenario appears to be a basic one and should not just break with Visual Studio upgrade.

Thanks,
Ashish

**Comment by cjkarande** [comment]
@ashishdhingra, Sorry it was my bad. As other objects Load or Query were working fine, I could debug and isolate the issue. It was emanating from one of my model classes. The issue has now been fixed. 

Apologies for soliciting your time on this issue, I appreciate your support though.
Thanks,
