### ISSUE TITLE
await TransferUtility.Upload hangs

### ISSUE THREAD

**Issue by thorwm-zz** [aws/aws-sdk-net#2511]
### Describe the bug

I have the following code:
```C#
//Get region
            var selectedRegion = RegionEndpoint.GetBySystemName(AWSRegion);
            var client = new AmazonS3Client(selectedRegion);
            var fileTransferUtility = new TransferUtility(client);            

            try
            {
                TransferUtilityUploadRequest transferUtilityUploadRequest = new TransferUtilityUploadRequest()
                {
                    BucketName = bucketName,
                    FilePath = filePath
                };                
                await fileTransferUtility.UploadAsync(transferUtilityUploadRequest);
            }
            catch
            {
            }
```
When using await, the first file uploads but then hangs - there is no return, exception, or action.

### Expected Behavior

I expect the code to continue running so it can process the remaining files that should be uploaded.  If there is a problem, an error should be reported.

### Current Behavior

Nothing is reported back - the code stops responding.

### Reproduction Steps

See above with the code snippet.  This is a similar experience that was reported and was closed in 2020:
https://github.com/aws/aws-sdk-net/issues/1648

### AWS .NET SDK and/or Package version used

AWSSDK.S3 3.7.101.47

### Targeted .NET Platform

.NET Framework 4.8

### Operating System and version

Windows 10

**Comment by dscpinheiro** [comment]
Could you share more details about the files / part size you're using? I tested locally with a few 10MB files (created using _fsutil_ - `For /L %i in (1,1,1000) do fsutil file createnew D%i.tmp 10485760`) and this code worked for me:

```csharp
AWSConfigs.LoggingConfig.LogMetrics = true;
AWSConfigs.LoggingConfig.LogTo = LoggingOptions.Console;
AWSConfigs.LoggingConfig.LogResponses = ResponseLoggingOption.Always;

var client = new AmazonS3Client();
var fileTransferUtility = new TransferUtility(client);

foreach (var file in Directory.GetFiles(@"C:\Temp"))
{
    var transferUtilityUploadRequest = new TransferUtilityUploadRequest
    {
        BucketName = "my-test-bucket",
        FilePath = file,
        Key = Guid.NewGuid().ToString("D"),
        PartSize = 1048576
    };

    await fileTransferUtility.UploadAsync(transferUtilityUploadRequest);
}
```

I added the logging statements at the beginning so I could see the requests going to S3.

**Comment by thorwm-zz** [comment]
Daniel,Thank you for your example - I found out where I went wrong.  When calling the routine, I was using .Wait() on the end where I should have been using await at the front.
I'll close this item and thank you again for your prompt response (a much better experience than when posting questions on repost.aws)
Thor 
    On Wednesday, January 4, 2023 at 09:03:58 AM CST, Daniel Pinheiro ***@***.***> wrote:  
 
 


Could you share more details about the files / part size you're using? I tested locally with a few 10MB files (created using fsutil - For /L %i in (1,1,1000) do fsutil file createnew D%i.tmp 10485760) and this code worked for me:
AWSConfigs.LoggingConfig.LogMetrics = true;
AWSConfigs.LoggingConfig.LogTo = LoggingOptions.Console;
AWSConfigs.LoggingConfig.LogResponses = ResponseLoggingOption.Always;

var client = new AmazonS3Client();
var fileTransferUtility = new TransferUtility(client);

foreach (var file in Directory.GetFiles(@"C:\Temp"))
{
    var transferUtilityUploadRequest = new TransferUtilityUploadRequest
    {
        BucketName = "my-test-bucket",
        FilePath = file,
        Key = Guid.NewGuid().ToString("D"),
        PartSize = 1048576
    };

    await fileTransferUtility.UploadAsync(transferUtilityUploadRequest);
}
I added the logging statements at the beginning so I could see the requests going to S3.
