### ISSUE TITLE
Ability to add headers to CloudWatch `PutLogEventsRequest`

### ISSUE THREAD

**Issue by MatisseHack** [aws/aws-sdk-net#2515]
### Describe the feature

According to [this guide](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Generation_PutLogEvents.html), sending embedded metric format logs to CloudWatch Logs requires adding an extra header to the request (`x-amzn-logs-format: json/emf`). The example code shows how to add this header with the Java SDK, but there doesn't seem to be an equivalent way to add headers with the .NET SDK.

### Use Case

I would like to be able to generate embedded metric format logs using C#

### Proposed Solution

Perhaps the `PutLogEventsRequest` object could have a `Headers` property?

### Other Information

I think I can add the desired header by modifying the runtime pipeline, but that approach is cumbersome because it requires creating several extra classes.

I'm also aware that I could use the [aws-embedded-metrics-dotnet](https://github.com/awslabs/aws-embedded-metrics-dotnet) package along with the CloudWatch Agent to send metrics, but I need to keep everything in process for my application.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

AWSSDK.CloudWatchLogs 3.7.102.31

### Targeted .NET Platform

.NET 7

### Operating System and version

Alpine Linux 3.16

**Comment by ashishdhingra** [comment]
Looks like we already have issue https://github.com/aws/aws-logging-dotnet/issues/186 for Logging library. Adding ability to add headers should also enable to fix the related issue.

**Comment by normj** [comment]
Here is an example of how you can modify the CloudWatch Logs service client to pass in the emf header.

```
using Amazon.CloudWatchLogs;
using Amazon.CloudWatchLogs.Model;
using Amazon.Runtime;

var client = new AmazonCloudWatchLogsClient(Amazon.RegionEndpoint.USWest2);
client.BeforeRequestEvent += AddEMFHeader;

client.PutLogEventsAsync(new PutLogEventsRequest { /* Add log data */ });

static void AddEMFHeader(object sender, RequestEventArgs e)
{
    var args = e as Amazon.Runtime.WebServiceRequestEventArgs;
    if(args != null)
    {
        // To inform the CloudWatch Logs service that the Embedded Metric Format log messages is being sent the additional header x-amzn-logs-format has to 
        // sent in the service request with the content type "json/emf".
        // https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Specification.html#CloudWatch_Embedded_Metric_Format_Specification_PutLogEvents
        args.Headers["x-amzn-logs-format"] = "json/emf";
    }
}
```

**Comment by MatisseHack** [comment]
Thanks for the suggestion @normj! That does seem like an improvement over creating a pipeline handler and sub-classing `AmazonCloudWatchLogsClient`. I'd still love a built in solution that's even more ergonomic!

**Comment by normj** [comment]
@MatisseHack We have no plans in the current major version of the SDK to make editing the headers for request more accessible then the code I shared above. When we do version 4 of the SDK we hope to revisit how customizations to the on going request could be made. I'm going to close this issue since nothing more is going to be done in the foreseeable feature to change the design of modifying headers. 

As far as making EMF in general more accessible that is up to the CloudWatch Logs team and how they model their service.

**Comment by gordonpn** [comment]
@MatisseHack 

Any EMF logs that can reach CloudWatch Logs will now be parsed and metrics can be generated from them. You don't need the EMF header anymore.

If you face any issues, you can get in touch with me!

**Comment by MatisseHack** [comment]
Looks like it does indeed work without the extra header! Thanks!
