### ISSUE TITLE
Lambda memory at 100% usage with S3 Client

### ISSUE THREAD

**Issue by kakins** [aws/aws-sdk-net#2516]
### Describe the bug

A Lambda using the S3 client continually increases in memory usage after `PutObjectAsync` is invoked over a series of Lambda executions. 

### Expected Behavior

This assumes the issue is with the SDK itself.  

But after following the patterns described in AWS documentation for initializing and using the SDK, I would expect the following

- The S3 Client should clean up resources efficiently after each invocation  
- And/or garbage collection should be occurring regularly to avoid 100% memory usage  

### Lambda Insights

Redeployment of the Lambda shows memory usage “normal” at about 50%, then slowly climbs to 100%

![image](https://user-images.githubusercontent.com/14915247/211908029-68f762c0-16e8-46c6-9b9e-85c1535dd5e8.png)

Memory usage never declines once MAX memory used reaches 100%

![image](https://user-images.githubusercontent.com/14915247/211908130-18831b6f-3445-4e38-8e78-d73a95b2b382.png)

Almost all individual Lambda Instances eventually reach 100% memory usage

![image](https://user-images.githubusercontent.com/14915247/211908235-c512736c-cdae-4c0b-b784-a6d8c8eb76e4.png)

100% Memory is correlated with occasional Lambda errors resulting from timeouts

![image](https://user-images.githubusercontent.com/14915247/211908280-7fb2d98e-4152-40d7-9c07-e6bd334f2e5e.png)

### CloudWatch
Logs for one Lambda instance, showing memory increasing over time

![image](https://user-images.githubusercontent.com/14915247/211908418-f15c8ab3-65fd-4589-b57e-2295872c2f41.png)

### Code
Commenting out the call to `PutObjectAsync` eliminates the problem, even when the Lambda is under heavier load

![image](https://user-images.githubusercontent.com/14915247/211915241-55f836b8-bd13-4f6c-aaaa-df3c28bd5e25.png)

![image](https://user-images.githubusercontent.com/14915247/211911452-30a80af1-15be-4f3e-8478-ff1aa1862e5c.png)

Memory usage is steady, and even drops off after load testing is complete

![image](https://user-images.githubusercontent.com/14915247/211915109-a5fc037c-b887-492c-a215-4a0ab40f4425.png)

### Reproduction Steps
This is a very much trimmed down version of the lambda, but basically the same setup/concept.  

```csharp
    public class Function
    {
        private static ServiceProvider _serviceProvider;

        public Function()
        {
            var serviceCollection = BuildServiceCollection();
            _serviceProvider = serviceCollection.BuildServiceProvider();
        }

        public async Task<SQSBatchResponse> FunctionHandler(SQSEvent sqsEvent, ILambdaContext context)
        {
            try
            {
                using var scope = _serviceProvider.CreateScope();
                return await scope.ServiceProvider
                    .GetService<MyHandler>()
                    .Execute(sqsEvent, context);
            }
            catch (Exception)
            {
                context.Logger.LogCritical("Unable to process the SQS event");
                throw;
            }
        }

        private static ServiceCollection BuildServiceCollection()
        {
            var services = new ServiceCollection();

            // I also tried .AddScoped() here, which didn't improve things
            services.AddTransient<MyHandler>();

            // The default lifetime scope of this service is a Singleton
           //  So each scope should be using this same service, not recreating a new instance, which is what I'd expect
            services.AddAWSService<IAmazonS3>();

            return services;
        }
    }

    public class MyHandler
    {
        private readonly IAmazonS3 _s3Client;

        public MyHandler(IAmazonS3 s3Client)
        {
            _s3Client = s3Client;
        }

        public async Task Handle()
        {
            // The issue is most definitely here... 
            var response = await _s3Client.PutObjectAsync(CreatePutObjectRequest());
        }

        private PutObjectRequest CreatePutObjectRequest()
        {
            return new PutObjectRequest
            {
                ContentBody = "HELLO",
                BucketName = "mybucketname",
                Key = Guid.NewGuid().ToString(),
            };
        }
    }

```

### Additional Information/Context

Things I've tried:

1. Disposing the S3 Client manually, either directly after each call or implementing IDisposable in my class
2. Avoiding using the injected `IAmazonS3` and directly instantiating the client, and disposing immediately afterward
3. Adding `<ServerGarbageCollection>false</ServerGarbageCollection>` to my csproj to hopefully let Lambda use GC more efficiently (I read about this in some blogs)
4. Commenting out the `PutObjectAsync` call, leaving the injected `IAmazonS3` constructor argument in place, allowing DI to do any initialization and setup.  Eliminated initialization of the client object as a potential cause.

Context surrounding the Lambda execution:
- It is triggered by SQS messages, with the expectation of each Lambda handling ~10 messages concurrently every 5 seconds per Lambda instance
- We need a new DI scope per message to avoid threading/state issues
- Max memory is 512mb for the lambda, which honestly seems a little excessive to handle this workload
  - I tried increasing the memory to 640mb to see if maybe using the SDK was just pushing the limit
  - This did not help -- 100% memory usage was still reached within a few minutes
 - Each object uploaded to S3 is about 2.5 MB

### AWS .NET SDK and/or Package version used

3.7.9.21

![image](https://user-images.githubusercontent.com/14915247/211918263-b0d7a021-f2dc-40d1-a45e-3fa4824d05b6.png)

### Targeted .NET Platform

.NET 6

### Operating System and version

Windows 10 (local), Linux (AWS deploy)

**Comment by kakins** [comment]
Following up on this... perhaps it's not something only related to `PutObjectAsync`?   I tried an alternative method of using `IAmazonS3.GetPreSignedUrlRequest` in combination with the .NET `HttpClient.PutAsync` and still eventually peaked at 100%.

**Comment by kakins** [comment]
Doing a little bit more digging.  Could this partially be me misunderstanding some of the AWS metrics?   It seems like the metrics I displayed above are the max memory a specific lambda instance utilized...however that doesn't mean the instance is ALWAYS using that much memory for the given data point in time.  It just means that at some point in time 100% was used?

**Comment by kakins** [comment]
Sorry, a little more comment here.  After doing a little more experimentation, I can confirm that concurrently uploading the same number/size of S3 objects using a separate console app test harness **does not** show an increase in memory.   I see garbage collection taking place and memory usage staying pretty constant.

So perhaps it could be an issue related to the Lambda runtime?  I was able to see a little better performance using smaller S3 payload sizes, but memory eventually climbed to 100%.

**Comment by normj** [comment]
I have been running your code for awhile now and it memory usage is constant at 58% and I'm using 256 MB memory setting. What is your SQS batch size window?

Can you also try setting the following in your csproj file?
```
<ConcurrentGarbageCollection>false</ConcurrentGarbageCollection>
```

**Comment by kakins** [comment]
Sorry for the delay in response.  The batch size window currently is 0.  We previously had it at 1s, but noticed the Lambda was taking sometimes 15-20 seconds to pick up a new message from the queue, which didn't seem right.

I should also mention that our code does process each incoming SQS message concurrently, which I didn't specify in the code snippet.

So for instance if we get 3 messages, what basically happens is this...
```
var tasks = sqsEvent.Records.Select(record => myHandler.Handle(record));
await Task.WhenAll(tasks);
```

I will try setting that csproj value now...

**Comment by kakins** [comment]
I tried setting `<ConcurrentGarbageCollection>false</ConcurrentGarbageCollection>` and still get the same result.  Hard to tell if it's better or worse.

![image](https://user-images.githubusercontent.com/14915247/212706415-687469cc-8b05-4bfa-bb92-7f620197a8ad.png)

**Comment by kakins** [comment]
Even though I'm still suspicious of S3, because the problem goes away when I comment out the S3 call, I can try deploying a trimmed down version of our Lambda with our concurrent SQS message handling.  That way we can eliminate any other processing the Lambda does and focus on the S3 client.  

Some things we've tried recently as temporary measures so we can continue working:
1. Decrease the Lambda timeout so that the delays from maxing out memory aren't as great
2. Decrease the Lambda batch size from 10 to 5
3. Decrease the size of data we're uploading from 2MB to 1MB

These changes makes a difference in terms of how fast we max out memory, but don't prevent it from happening.

**Comment by normj** [comment]
Just as an experiment to collect data can you set the Lambda memory settings to 3 GB which will give the Lambda function a lot more CPU. I want to understand if there was enough available CPU would the GC keep up.

**Comment by kakins** [comment]
Ok yeah you may be onto something.  Increasing the memory to 3GB showed usage holding steady at about 14%.
![image](https://user-images.githubusercontent.com/14915247/213829401-4c89e138-c381-4966-bee3-4d50ff83b4be.png)


I tried increasing to 1GB a week ago, but I guess I didn't think about going much higher than that, thinking it'd just max out eventually.

**Comment by kakins** [comment]
@normj So based on my previous comment we can increase the memory and alleviate the CPU bottleneck.  

Do you think there's anything else worth looking into related to the SDK?  For instance, should 512MB be a reasonable amount of memory for about 10MB-20MB uploaded per lambda execution?

**Comment by ashishdhingra** [comment]
> @normj So based on my previous comment we can increase the memory and alleviate the CPU bottleneck.
> 
> Do you think there's anything else worth looking into related to the SDK? For instance, should 512MB be a reasonable amount of memory for about 10MB-20MB uploaded per lambda execution?

@kakins Please advise if this issue is resolved. CCing @normj for inputs, if any to the last comment.

**Comment by normj** [comment]
Adding a bit more information. I would really always look at the memory setting as sliding scale of how much power you want/need behind your function. Naming the setting `memory` is not my favorite thing.

There are things we would like to do to the SDK to reduce the amount of temporary object created which adds pressure to the GC but they aren't low hanging items that we can easily do. To top it off SQS is an older XML based service over the wire and all of that XML parsing causes a lot of temporary objects.

**Comment by kakins** [comment]
@normj Thanks for helping me take a look at this.  Interesting information concerning SQS, but I'm not 100% sure how much SQS played a role in this situation.  All the indicators pointed to the S3 library.  That said, I think we can work with a little increased memory for the time being, we just won't be able to optimize cost/performance to the degree I originally expected.

@ashishdhingra I think we can go ahead and close.

**Comment by normj** [comment]
@kakins Sorry you are right about SQS not being important in this discussion. Was going through a bunch of issues and lost some context on this discussion. 😅
