### ISSUE TITLE
C# .NET 6.0 cannot retrieve JWT to use as the WebIdentityToken in an AssumeRoleWithWebIdentityRequest.escription)

### ISSUE THREAD

**Issue by rlhagerm** [aws/aws-sdk-net#2517]
### Describe the bug

This is a copy of an original issue posted to the code examples repository, here: https://github.com/awsdocs/aws-doc-sdk-examples/issues/3965

The text below is copied from that issue for reference.

### Expected Behavior

I am trying to get the credentials from the Kubernetes Service Account (which is injected into the container) with an attached role that gives access to S3. Here is the code that I am running:

```C#
var stsClient = new AmazonSecurityTokenServiceClient(RegionEndpoint.USWest2);

        try
        {
            var request = new AssumeRoleWithWebIdentityRequest()
            {
                WebIdentityToken = _configuration["AWS_WEB_IDENTITY_TOKEN_FILE"],
                RoleArn = _configuration["AWS_ROLE_ARN"],
                RoleSessionName = "AssumedRoleUser"
             };

            var assumeRoleResult = await stsClient.AssumeRoleWithWebIdentityAsync(request);

            var credentials = assumeRoleResult.Credentials;

            Console.WriteLine("Access Stuff: " + credentials.AccessKeyId + " Secret: " + credentials.SecretAccessKey + " Token: " + credentials.SessionToken);

            var client = new AmazonS3Client(credentials);
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.ToString());
        }

        return response;
```
I would expect the AssumeRoleWithWebIdentityAsync call would return a proper result so that I can use the credentials in standing up a new AmazonS3Client.

### Current Behavior

However, when the stsClient.AssumeRoleWithWebIdentityAsync(request) runs it throws the following error:
```
Amazon.SecurityToken.Model.InvalidIdentityTokenException: The ID Token provided is not a valid JWT. (You may see this error if you sent an Access Token) 23 ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown. 22 at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken) 21 at Amazon.Runtime.Internal.HttpHandler1.InvokeAsync[T](IExecutionContext executionContext)
20
at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
19
at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
18
--- End of inner exception stack trace ---
17
at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionStream(IRequestContext requestContext, IWebResponseData httpErrorResponse, HttpErrorResponseException exception, Stream responseStream)
16
at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionAsync(IExecutionContext executionContext, HttpErrorResponseException exception)
15
at Amazon.Runtime.Internal.ExceptionHandler1.HandleAsync(IExecutionContext executionContext, Exception exception) 14 at Amazon.Runtime.Internal.ErrorHandler.ProcessExceptionAsync(IExecutionContext executionContext, Exception exception) 13 at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext) 12 at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext) 11 at Amazon.Runtime.Internal.Signer.InvokeAsync[T](IExecutionContext executionContext) 10 at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext) 9 at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext) 8 at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext) 7 at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext) 6 at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext) 5 at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext) 4 at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext) 3 at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext) 2 at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext) 1 
```

It's acting like the _configuration["WS_WEB_IDENTITY_TOKEN_FILE"] is not pulling the token assigned to the AWS_WEB_IDENTITY_TOKEN_FILE environment variable. Here is the env section of the container:

     - env: - name: AWS_STS_REGIONAL_ENDPOINTS value: regional - name: AWS_DEFAULT_REGION value: us-west-2 - name: AWS_REGION value: us-west-2 - name: AWS_ROLE_ARN value: 'arn:aws:iam::XXXXXXXXXXXX:role/service-account-name' - name: AWS_WEB_IDENTITY_TOKEN_FILE value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token

### Reproduction Steps

1. Create a Kubernetes Service Account (should be using the OpenID Connect provider of the Cluster and that provider should be created in IAM)
2. Assign a Role (with S3 permissions) to the created service account (with a trust policy defined like this:
```JSON
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::XXXXXX:oidc-provider/oidc.eks.us-west-2.amazonaws.com/id/xxx"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.us-west-2.amazonaws.com/id/xxx:aud": "sts.amazonaws.com",
                    "oidc.eks.us-west-2.amazonaws.com/id/xxx:sub": "system:serviceaccount:$namespace:service-account-name"
                }
            }
        }
    ]
}
```

3.  Create a C# .NET 6.0 application and deploy it to the linux container, then run the code.

### Additional Information/Context

I don't have the original information on this issue, but the link above will connect you with the originator. I will also provide him with a link to this issue. The issue could not be transferred directly from a separate org.

### AWS .NET SDK and/or Package version used

3.7.100.16

### Targeted .NET Platform

.NET 6

### Operating System and version

Linux container (I believe it is Ubuntu 18.04)

**Comment by ashishdhingra** [comment]
Hi @ChristianSHansen,

Good morning. Thanks for reporting the issue. I believe you are using the `AssumeRoleWithWebIdentityRequest` incorrectly. If you refer the example at [AmazonSecurityTokenServiceClient.AssumeRoleWithWebIdentity (AssumeRoleWithWebIdentityRequest)](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/SecurityToken/MSecurityTokenServiceAssumeRoleWithWebIdentityAssumeRoleWithWebIdentityRequest.html), it sets the `WebIdentityToken` property to actual value.
```C#
var client = new AmazonSecurityTokenServiceClient();
var response = client.AssumeRoleWithWebIdentity(new AssumeRoleWithWebIdentityRequest 
{
    DurationSeconds = 3600,
    Policy = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"Stmt1\",\"Effect\":\"Allow\",\"Action\":\"s3:ListAllMyBuckets\",\"Resource\":\"*\"}]}",
    ProviderId = "www.amazon.com",
    RoleArn = "arn:aws:iam::123456789012:role/FederatedWebIdentityRole",
    RoleSessionName = "app1",
    WebIdentityToken = "Atza%7CIQEBLjAsAhRFiXuWpUXuRvQ9PZL3GMFcYevydwIUFAHZwXZXXXXXXXXJnrulxKDHwy87oGKPznh0D6bEQZTSCzyoCtL_8S07pLpr0zMbn6w1lfVZKNTBdDansFBmtGnIsIapjI6xKR02Yc_2bQ8LZbUXSGm6Ry6_BG7PrtLZtj_dfCTj92xNGed-CrKqjG7nPBjNIL016GGvuS5gSvPRUxWES3VYfm1wl7WTI7jn-Pcb6M-buCgHhFOzTQxod27L9CqnOLio7N3gZAGpsp6n1-AJBOCJckcyXe2c6uD0srOJeZlKUm2eTDVMf8IehDVI0r1QOnTV6KzzAI3OY87Vd_cVMQ"
});

AssumedRoleUser assumedRoleUser = response.AssumedRoleUser;
string audience = response.Audience;
Credentials credentials = response.Credentials;
int packedPolicySize = response.PackedPolicySize;
string provider = response.Provider;
string subjectFromWebIdentityToken = response.SubjectFromWebIdentityToken;
```

Whereas, in your case, you are just passing the path to the web identity token file represented by environment variable `AWS_WEB_IDENTITY_TOKEN_FILE` (an assumption). Could you please check the value of `_configuration["AWS_WEB_IDENTITY_TOKEN_FILE"]` in your code and verify if it represents the path to token file or the actual value inside the token file?

Thanks,
Ashish

**Comment by ChristianSHansen** [comment]
I will need to try that and see if it will work. Thanks!

**Comment by ChristianSHansen** [comment]
I'm am currently validating the Web Identity Token in my container.

**Comment by ChristianSHansen** [comment]
Okay, I have tried a few things but I keep getting back "403 Unauthorized". I'm wondering if I need to include a Policy with the AssumeRoleWithWebIdentityRequest or if I can assign the Policy to the Role in IAM?

**Comment by ChristianSHansen** [comment]
@ashishdhingra see my previous comment for a question I have.

**Comment by ashishdhingra** [comment]
> @ashishdhingra see my previous comment for a question I have.

@ChristianSHansen Apologies for late reply. If you refer [AmazonSecurityTokenServiceClient.AssumeRoleWithWebIdentity (AssumeRoleWithWebIdentityRequest)](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/SecurityToken/MSecurityTokenServiceAssumeRoleWithWebIdentityAssumeRoleWithWebIdentityRequest.html), it specifies `You cannot use session policies to grant more permissions than those allowed by the identity-based policy of the role that is being assumed.`. So you might want to check if the role in IAM allows you to assume the inline policy (depending on role permissions).

Thanks,
Ashish
