### ISSUE TITLE
Signature expired exception when the lambda runs for more than 5 minutes

### ISSUE THREAD

**Issue by lionel1704** [aws/aws-sdk-net#2525]
### Describe the bug

I have a lambda that runs using a docker container which works as expected most of the time. In some cases the lambda needs to run for more than 5 minutes. Whenever this happens, the client that calls the lamdba gets the following exception after 5 minutes of the lambda invocation:
```
Signature expired: 20230119T123539Z is now earlier than 20230119T123547Z (20230119T124047Z - 5 min.)
```

The lambda itself runs to completion and returns the result, but the client is no longer waiting for the result since the exception is already thrown. The timeout for the lambda at the server(less) end is 10minutes. The timeout at the client is set to 15 minutes.
This is how the lambda is invoked:
```
var lambdaClient = new AmazonLambdaClient(new AmazonLambdaConfig
{
    ServiceURL = serviceUrl,
    Timeout = TimeSpan.FromMinutes(15),
});


var request = new InvokeRequest
{
    FunctionName = functionName,
    InvocationType = InvocationType.RequestResponse,
    Payload = payload
};
var response = await lambdaClient.InvokeAsync(request);
if (response.StatusCode == 200 && response.FunctionError == null)
{
    using var sr = new StreamReader(response.Payload);
    return await sr.ReadToEndAsync();
}
```

Reading the suggestion in https://github.com/aws/aws-sdk-net/issues/1639 I tried setting `ResignRetries: true`
Unfortunately, that didn't help either.

### Expected Behavior

The client should wait for the response from the lambda to come through without throwing the Signature expired exception.

### Current Behavior

A signature expired exception is thrown before the response from the lambda arrives.

### Reproduction Steps

Use any lambda that runs for more than 5 minutes and try invoking it with using the code in specified above with a higher timeout setting.

### AWS .NET SDK and/or Package version used

AWSSDK.Lambda 3.7.103.2

### Targeted .NET Platform

.NET 6

### Operating System and version

Ubuntu 20.04

**Comment by ashishdhingra** [comment]
Hi @lionel1704,

Good afternoon.

Thanks for reporting the issue. Did you also tried to enable the response logging using the below code, as also suggested in the https://github.com/aws/aws-sdk-net/issues/1639#issuecomment-644900342: 
```C#
// Log responses and metrics to cloud watch. 
AWSConfigs.LoggingConfig.LogMetrics = true;
AWSConfigs.LoggingConfig.LogTo = LoggingOptions.Console;
AWSConfigs.LoggingConfig.LogResponses = ResponseLoggingOption.Always;
```

Please try enabling this in the calling client code, and if required, also enable it on Lambda, to find the exact root cause.

Also confirm if this issue happens intermittently or with every invocation, when it takes more than 5 min? Would it be possible to share the sample Lambda solution code (along with `.csproj` file) that could be used to reproduce the issue end-to-end.

Thanks,
Ashish

**Comment by lionel1704** [comment]
@ashishdhingra thanks for your response. I was putting together a barebones example to reproduce the error and in the process, we've identified the issue - the timeout was not being initialized correctly. We are now able to proceed further. Thank you :)

**Comment by saintarian** [comment]
@lionel1704 - I'm facing the same issue now and my lambda client initialization code looks similar to the code you had pasted at the top. I'm curious to hear what your fix was.

**Comment by travismorenz** [comment]
I'm also seeing the same.

**Comment by lionel1704** [comment]
The issue I had was how the configuration was being initialized. This is how my working code looked in the end:
```
var lambdaClient = new AmazonLambdaClient(new AmazonLambdaConfig
{
    ServiceURL = serviceUrl,
    Timeout = TimeSpan.FromMinutes(15),
    ResignRetries = true
});


var request = new InvokeRequest
{
    FunctionName = functionName,
    InvocationType = InvocationType.RequestResponse,
    Payload = payload
};
var response = await lambdaClient.InvokeAsync(request);
if (response.StatusCode == 200 && response.FunctionError == null)
{
    using var sr = new StreamReader(response.Payload);
    return await sr.ReadToEndAsync();
}
```
