### ISSUE TITLE
Could not load type 'Amazon.Runtime.IDefaultConfiguration' from assembly 'AWSSDK.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604'. | STACK TRACE:    at Amazon.SecurityToken.AmazonSecurityTokenServiceConfig..ctor()\r\n   at Amazon.SecurityToken.AmazonSecurityTokenServiceClient..ctor(RegionEndpoint region)

### ISSUE THREAD

**Issue by sravanidurga** [aws/aws-sdk-net#2527]
### Describe the bug

   I'm getting this error sometimes after deploying code to server
   
   Could not load type 'Amazon.Runtime.IDefaultConfiguration' from assembly 'AWSSDK.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604'. | STACK TRACE:    at Amazon.SecurityToken.AmazonSecurityTokenServiceConfig..ctor()\r\n   at Amazon.SecurityToken.AmazonSecurityTokenServiceClient..ctor(RegionEndpoint region)
   
   **Here is the attached code snippet :**
    AssumeRoleRequest assumeRequest = new AssumeRoleRequest
                    {
                        RoleArn = ConfigHandler.GetConfigValue("AWS_ROUTE53_ASSUMED_ROLE_NAME"),
                        DurationSeconds = 3600,
                        RoleSessionName = ConfigHandler.GetConfigValue("AWS_ROUTE53_ASSUMED_SESSION_NAME")
                    };
                    var assumeRoleResult = new AmazonSecurityTokenServiceClient(GetRegion(ConfigHandler.GetConfigValue("AWS_ROUTE53_REGION"))).AssumeRole(assumeRequest);
                    AWSCredentials tempCredentials = new SessionAWSCredentials(
                       assumeRoleResult.Credentials.AccessKeyId,
                       assumeRoleResult.Credentials.SecretAccessKey,
                       assumeRoleResult.Credentials.SessionToken);
                    _route53Client = new AmazonRoute53Client(tempCredentials);
                    
    **I have .net45 application where below are the references to the packages that I've installed**
    
    <Reference Include="AWSSDK.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604, processorArchitecture=MSIL">
      <HintPath>..\packages\AWSSDK.Core.3.7.103.18\lib\net45\AWSSDK.Core.dll</HintPath>
    </Reference>
        <Reference Include="AWSSDK.SecurityToken, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604, processorArchitecture=MSIL">
      <HintPath>..\packages\AWSSDK.SecurityToken.3.7.100.57\lib\net45\AWSSDK.SecurityToken.dll</HintPath>
    </Reference>
    
    Not sure why it is broken sometimes without any change
    
 

### Expected Behavior

Retrieving the Temporary Credentials using AssumeRole Method.

### Current Behavior

Throwing exception during creation of AmazonSecurityTokenServiceClient();

### Reproduction Steps

Redeployed code but it is broken sometimes and working sometimes

### AWS .NET SDK and/or Package version used

AWSSDK.Core.3.7.103.18
AWSSDK.SecurityToken.3.7.100.57

### Targeted .NET Platform

.NET FrameWork 4.5

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment]
@sravanidurga Thanks for reporting the issue. This issue appears to be similar to https://github.com/aws/aws-sdk-net/issues/2099. Does any of your projects, somehow, refer the older version of `AWSSDK.Core`, directly or indirectly via transitive dependency? If yes, then please
- Upgrade to the latest version of AWSSDK.Core.
- Clean and rebuild the solution
- Deploy the code

You might also want to check if you have older versions of `AWSSDK.*` assemblies in GAC, which may be installed by tools utilizing these assemblies.

Thanks,
Ashish

**Comment by sravanidurga** [comment]
Hi @ashishdhingra Should all aplications hosted on the server needs the latest version of AWSSDK.Core ?
One of our applications has AWSSDK.Core3.3.106.11 and other applicaiton has latest on the same server where I'm getting this error.
These both are independent applications 
Should it be latest on both applications ?

**Comment by ashishdhingra** [comment]
> Hi @ashishdhingra Should all aplications hosted on the server needs the latest version of AWSSDK.Core ? One of our applications has AWSSDK.Core3.3.106.11 and other applicaiton has latest on the same server where I'm getting this error. These both are independent applications Should it be latest on both applications ?

@sravanidurga I would suggest making change to the application having issue, testing it in a **non-prod** environment to see if everything works fine and the reported issue is resolved. In case you still see the said error in production, you might want to check if the `AWSSDK.*` assemblies are somehow installed in GAC (as suggested earlier).

**Comment by xts-velkumars** [comment]
Any updates on this? I'm also facing same issue. 
Every time I need to update the latest version from nuget to make application working.

**Comment by sravanidurga** [comment]
If there are multiple apps hosted on a server and some of the apps are using older version then I was getting this issue 
I've updated AWS to latest in all apps and that resolved the issue
