### ISSUE TITLE
The GetAWSOptions extension method is case-sensitive

### ISSUE THREAD

**Issue by justhoma** [aws/aws-sdk-net#2529]
### Describe the feature

The [GetAWSOptions extension method](https://github.com/aws/aws-sdk-net/blob/fe04f027f66b37dd38cbb0f8e55d2b23eea7ffc4/extensions/src/AWSSDK.Extensions.NETCore.Setup/ConfigurationExtensions.cs) uses the [GetDeclaredProperty method](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.typeinfo.getdeclaredproperty?view=netcore-3.1) which is case-sensitive which means that we are required to use Pascal-Case within our appsettings files.
For example, calling the following works fine to set the ServiceURL on the AWSOptions class:
```
{
  "AwsOptions": {
    "ServiceURL": "https://localhost:9021"
  }
}
```
But the following fails (note the camel-casing)
```
{
  "AwsOptions": {
    "serviceURL": "https://localhost:9021"
  }
}
```

### Use Case

All other packages that we consume are case-insensitive when it comes to ```appsettings``` files.

### Proposed Solution

Change the existing implementation to use

`typeInfo.DeclaredProperties.SingleOrDefault(x => x.Name.ToUpperInvariant() == child.Key.ToUpperInvariant())`

instead of

`typeInfo.GetDeclaredProperty(child.Key)`

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

AWSSDK.Extensions.NETCore.Setup 3.7.2

### Targeted .NET Platform

.NET 7

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment]
For reference, [Configuration keys and values](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-7.0#configuration-keys-and-values) specifies that the keys are case-insensitive. Needs review with the team.

**Comment by ashishdhingra** [comment]
This is released/fixed in [AWSSDK.Extensions.NETCore.Setup version 3.7.5](https://www.nuget.org/packages/AWSSDK.Extensions.NETCore.Setup/3.7.5).
