### ISSUE TITLE
AmazonCognitoIdentityConfig throws exception in release build

### ISSUE THREAD

**Issue by bryceburrows** [aws/aws-sdk-net#2535]
### Describe the bug

This code works in debug mode on my iMac when running my Xamarin forms app.
```

var   credentials = new CognitoAWSCredentials(
                "ap-southeast-2:etcetcblahdeblah", // Identity pool ID
                RegionEndpoint.APSoutheast2 // Region

```

But throws a very poor exception when run in release build

"The type initializer for 'Amazon.CognitoIdentity.AmazonCognitoIdentityConfig' threw an exception."

`var config = new AmazonCognitoIdentityConfig();
  config.RegionEndpoint = RegionEndpoint.APSoutheast2;`

throws the same exception.

### Expected Behavior

I expect the release build version to work like the Debug version does.

### Current Behavior

this exception is thrown

The type initializer for 'Amazon.CognitoIdentity.AmazonCognitoIdentityConfig' threw an exception.

### Reproduction Steps

    //        var config = new AmazonCognitoIdentityConfig();
      //      config.RegionEndpoint = RegionEndpoint.APSoutheast2;
                 

            System.Diagnostics.Debug.WriteLine("ready to try");
                try
            {
    credentials = new CognitoAWSCredentials(
                "ap-southeast-2:extrabigthatisntgoingtobeshared", // Identity pool ID
                RegionEndpoint.APSoutheast2 // Region
    );
            }
            catch (Exception ex)
            {
            
                System.Diagnostics.Debug.WriteLine(ex.Message);
            
            }

### AWS .NET SDK and/or Package version used

AWSSDK.CognitoIdentity 3.7.100.69

### Targeted .NET Platform

Xamarin forms Android

### Operating System and version

iMac Monterey

**Comment by ashishdhingra** [comment]
Hi @bryceburrows,

Good morning.

Thanks for opening the issue. Could you please enable verbose logging and shared the detailed logs? Verbose logging could be enabled using the below code:
```C#
Amazon.AWSConfigs.LoggingConfig.LogResponses = Amazon.ResponseLoggingOption.Always;
Amazon.AWSConfigs.LoggingConfig.LogTo = Amazon.LoggingOptions.SystemDiagnostics;
Amazon.AWSConfigs.AddTraceListener("Amazon", new System.Diagnostics.ConsoleTraceListener());
```

Thanks,
Ashish

**Comment by ashishdhingra** [comment]
> Hiya ConsoleTraceListener doesn't exist in the Xamarin forms version the app currently targets. I tried pointing a defaulttracerlistener to log to a file but nothing was created :/
> 
> Do you have another option?

@bryceburrows You could try using `log4net` as mentioned in https://aws.amazon.com/blogs/developer/logging-with-the-aws-sdk-for-net/ to log to a file. Quick question, how are you authenticating via Cognito and then using the temporary session credentials in your application?

**Comment by ashishdhingra** [comment]
@bryceburrows Could you please share are you authenticating via Cognito and then using the temporary session credentials in your application?

**Comment by ashishdhingra** [comment]
> I found a solution Clean
> 
> 1. remove  all AWS sdks
> 2. reinstall AWS sdks
> 3. In Xamarin Android build options - compile with no SDK linking.
>    rebuild and run  - all works.
> 
> Cle

@bryceburrows Thanks for your reply. Good to hear that it works for you. Closing this issue.

**Comment by santoshParihar** [comment]
Hi, I am getting the same exception : 

    {
      "message": "The type initializer for 'Amazon.CognitoIdentity.AmazonCognitoIdentityConfig' threw an exception.",
      "stackTrace": "LogCapture.GetStackTrace ",
      "type": "Exception"
    },
    
    I am using ASW SDK for Unity and used s3 package. 
    I integrated it into Unity Editor, It works perfectly. I can send the file to s3.
    
    When I create an Android build/ iOS build, It throws the above error and hence can't send the file to s3. 
    
    I am using IL2CPP , Unity ver 2020.3.48f1 ,  .Net ver : 2.0
