### ISSUE TITLE
AmazonS3Config.AuthenticationRegion is now ignored

### ISSUE THREAD

**Issue by Louspirit** [aws/aws-sdk-net#2540]
### Describe the bug

After updating from 3.5.1.7 to 3.7.103.9, I cannot use custom region for AWS V4 requests, which is needed for S3 compatible storage with different region naming (in my case _ovh_).

### Expected Behavior

Can use `AmazonS3Config.AuthenticationRegion` like before

### Current Behavior

It uses default us-east-1 region for AWS4 requests authentication, despite having set `AmazonS3Config.AuthenticationRegion` parameter

### Reproduction Steps

Setup an app with 3.5.1.7 that connects to a custom region: 

`new AmazonS3Client(s3AccessKey, s3AccessSecret, new AmazonS3Config { UseAccelerateEndpoint = s3Acceleration, ServiceURL = $"https://s3.{s3Region}.cloud.ovh.net", AuthenticationRegion = s3Region, SignatureVersion = "V4" })`

It works.

![image](https://user-images.githubusercontent.com/2952456/219017627-502a7f06-a933-4b87-bdca-302e9591f386.png)

Same code in 3.7.103 doesn't work...

![image](https://user-images.githubusercontent.com/2952456/219017873-28461a2a-4e9b-41d0-98e6-b64b44c1ece6.png)

### Possible Solution

Has the parameter is ignored or changed?

### Additional Information/Context

I use a lambda function in C# net6 deployed on AWS eu-west-1.
This lambda function is called by git lfs to store files in an S3 compatible storage in OVH.
My lambda code needs to override serviceUrl and AuthenticationRegion to call OVH S3 with custom values.

### AWS .NET SDK and/or Package version used

AWSSDK.S3 3.7.103.9 KO
AWSSDK.S3 3.5.1.7 OK
AWSSDK.S3 3.5.10.2 OK
AWSSDK.S3 3.7.9.30 OK
**AWSSDK.S3 3.7.10.1 OK**
AWSSDK.S3 3.7.102.2 KO
AWSSDK.S3 3.7.101.61 KO
AWSSDK.S3 3.7.101.10 KO
AWSSDK.S3 3.7.101 KO
**AWSSDK.S3 3.7.100 KO**

### Targeted .NET Platform

.net 6.0.4

### Operating System and version

Windows 10/11

**Comment by Louspirit** [comment]
The problem appeared later than I said, see version used.

**Comment by ashishdhingra** [comment]
Looks like at https://github.com/aws/aws-sdk-net/blob/0fb3f01067713d215363ec098a92d3ee05898434/sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/BaseEndpointResolver.cs#L124, for `SigV4` request, we are overriding the `AuthenticationRegion` with the region determined from the (default) profile (the `AuthenticationRegion` was initially set to the value used in `Amazons3Config`).

**Comment by ashishdhingra** [comment]
Hi @Louspirit,

Good afternoon.

Thanks for reporting the issue. Could you please share the following for further investigation:
- Verbose logs. These could be enabled using the below code (if using console application):
```C#
Amazon.AWSConfigs.LoggingConfig.LogResponses = Amazon.ResponseLoggingOption.Always;
Amazon.AWSConfigs.LoggingConfig.LogTo = Amazon.LoggingOptions.SystemDiagnostics;
Amazon.AWSConfigs.AddTraceListener("Amazon", new System.Diagnostics.ConsoleTraceListener());
```
- How did you determined that it's using the incorrect `AuthenticationRegion` value?
- Could you please share sample code solution that demonstrates use to authentication region (perhaps in logs) in version `3.7.10.1` (or earlier) and later versions (when problem started happening). 

Thanks,
Ashish

**Comment by Louspirit** [comment]
Hello @ashishdhingra,
Thanks for your response.

Let's give some context:
"
I use a lambda function in C# net6 deployed on AWS eu-west-1.
This lambda function is called by git lfs to store files in an S3 compatible storage in OVH.
My lambda code needs to override serviceUrl and AuthenticationRegion to call OVH S3 with custom values.
"

Have you seen my pictures? With same code, the region goes from `sbg ` to `us-east-1` in the log. 
If I don't use AuthenticationRegion,  the region isn't shown in the URL.

My region in the profile is set to `eu-west-1`, which corresponds to where my lambda function is deployed.

**Comment by klementi** [comment]
We released the build with the fix today, please use AWSSDK.Core >= 3.7.105.6 and AWSSDK.S3 >=3.7.103.13

**Comment by Louspirit** [comment]
Thanks, it's working now 👍🏻
