### ISSUE TITLE
AmazonS3Client.GetPreSignedURL returns Requests specifying Server Side Encryption with AWS KMS managed keys require AWS Signature Version 4

### ISSUE THREAD

**Issue by ElectricVampire** [aws/aws-sdk-net#2543]
### Describe the bug

AmazonS3Client.GetPreSignedURL is not working and returns -

**Code Snippet**
```
 var url = _clientAmazonS3.GetPreSignedURL(req);
```

```
<Error>
	<Code>InvalidArgument</Code>
	<Message>Requests specifying Server Side Encryption with AWS KMS managed keys require AWS Signature Version 4.</Message>
	<ArgumentName>Authorization</ArgumentName>
	<ArgumentValue>null</ArgumentValue>
	<RequestId>A8J68687WD1KS3N9</RequestId>
	<HostId>gniI0gIocSiaLqEb58698870970pk3VQWwl4BK1Fjtly0Q/8=</HostId>
</Error>
```

Now when I checked -
**AWSConfigsS3.UseSignatureVersion4** its already true.

But strangely if I explicitly set to true PreSigned url get generated.
```
var sign = AWSConfigsS3.UseSignatureVersion4;  //sign is true
AWSConfigsS3.UseSignatureVersion4 = true;  //set sign to true
 var url = _clientAmazonS3.GetPreSignedURL(req);
```

### Expected Behavior

Presigned url should be generated

### Current Behavior

Getting error while generating presigned url

### Reproduction Steps

Register S3 client via DI and make call to GetPriSignedUrl method

### Possible Solution

I had to explicitly set the AWSConfigsS3.UseSignatureVersion4 = true while its value is already true.

### AWS .NET SDK and/or Package version used

AWSSDK.S3.3.7.103.10

### Targeted .NET Platform

.NET 6

### Operating System and version

AmazonLinux

**Comment by ashishdhingra** [comment]
Hi @ElectricVampire,

Good afternoon.

Thanks for reporting the issue. Unfortunately, I'm unable to reproduce the issue when using the `AWSSDK.Extensions.NETCore.Setup` package and following instructions at [Using AWSSDK.Extensions.NETCore.Setup and the IConfiguration interface](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-netcore.html). Here is the sample code below for ASP.NET Web MVC .NET 6 application:
**.csproj**
```XML
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="AWSSDK.Extensions.NETCore.Setup" />
    <None Remove="AWSSDK.S3" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.7.4" />
    <PackageReference Include="AWSSDK.S3" Version="3.7.103.12" />
  </ItemGroup>
</Project>
```
**Program.cs**
```
using Amazon.S3;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddControllersWithViews();
builder.Services.AddDefaultAWSOptions(builder.Configuration.GetAWSOptions());
builder.Services.AddAWSService<IAmazonS3>();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Home/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();

app.UseRouting();

app.UseAuthorization();

app.MapControllerRoute(
    name: "default",
    pattern: "{controller=Home}/{action=Index}/{id?}");

app.Run();
```
**Controllers\HomeController.cs**
```C#
using System.Diagnostics;
using Amazon.S3;
using Amazon.S3.Model;
using Microsoft.AspNetCore.Mvc;
using PresignedUrlDITest.Models;

namespace PresignedUrlDITest.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private IAmazonS3 S3Client { get; set; }
    private const string bucketName = "testbucket-issue1880";
    private const string objectKey = "RS_20220303_NYLIFE_US_943.csv";
    private const double timeoutDurationHours = 12;

    public HomeController(ILogger<HomeController> logger, IAmazonS3 s3Client)
    {
        _logger = logger;
        this.S3Client = s3Client;
    }

    public IActionResult Index()
    {
        string presignedUrl = S3Client.GetPreSignedURL(new GetPreSignedUrlRequest()
        {
            BucketName = bucketName,
            Key = objectKey,
            Expires = DateTime.UtcNow.AddHours(timeoutDurationHours)
        });

        this.ViewBag.PresignedUrl = presignedUrl;
        return View();
    }
}
```
**Views\Home\Index.cshtml**
```CSHTML
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    PresignedUrl: @ViewBag.PresignedUrl
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>


```
Thanks for opening the issue. Could you please provide some details:
- Whether S3 server side encryption is enabled?
- What additional packages (and versions) you are consuming? Since you are using DI, are you using `AWSSDK.Extensions.NETCore.Setup` package? If yes, did you add statement `builder.Services.AddDefaultAWSOptions(builder.Configuration.GetAWSOptions());` to configure default AWS options (I'm unsure if this would affect the signature version used). While debugging I observed that S3 client object had SignatureVersion set as `4` in client config.
- Sample code solution showing DI setup.

Thanks,
Ashish

**Comment by ElectricVampire** [comment]
@ashishdhingra 

1. Whether S3 server side encryption is enabled?
- YES

3. What additional packages (and versions) you are consuming? Since you are using DI, are you using AWSSDK.Extensions.NETCore.Setup package? If yes, did you add statement builder.Services.AddDefaultAWSOptions(builder.Configuration.GetAWSOptions()); to configure default AWS options (I'm unsure if this would affect the signature version used). While debugging I observed that S3 client object had SignatureVersion set as 4 in client config.
```
 services.AddAWSService<IAmazonS3>();
```
```
                <PackageReference Include="Amazon.Extensions.S3.Encryption" Version="2.0.3" />
		<PackageReference Include="AWSSDK.S3" Version="3.7.101.15" />
		<PackageReference Include="AWSSDK.SecurityToken" Version="3.7.100.15" />
		<PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.7.2" />
```

No I am not doing `builder.Services.AddDefaultAWSOptions(builder.Configuration.GetAWSOptions());` .
Yes version for signature is 4 but my code only works when I explicitly set it to `AWSConfigsS3.UseSignatureVersion4 = true;` 

check [this](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/S3/Custom/AWSConfigs.S3.cs#L106), I do see explicit setting the version has another flag.
My presigned url has `AWSAccessKeyId=` which is signature v2 and v4 signature has `X-Amz-Credential`. So even though `AWSConfigsS3.UseSignatureVersion4` is true S3 was still using v2 version , only setting it explicitly forced s3 to use v4.

5. Sample code solution showing DI setup.
```
 services.AddAWSService<IAmazonS3>();
```

**Comment by ElectricVampire** [comment]
@ashishdhingra : Thanks for help - I was able to solve the issue using 3.7.4 version of `AWSSDK.Extensions.NETCore.Setup`. I think this should be documented somewhere as its pretty straight forward use case

**Comment by ashishdhingra** [comment]
> @ashishdhingra : Thanks for help - I was able to solve the issue using 3.7.4 version of AWSSDK.Extensions.NETCore.Setup. I think this should be documented somewhere as its pretty straight forward use case.

@ElectricVampire I got notified about the above comment, which appears to be deleted. Are you still facing the issue? Could you please advise what needs to be documented?

Thanks.
Ashish

**Comment by ElectricVampire** [comment]
@ashishdhingra I thought it worked with 3.7.4 version but it did not, i had AWSConfigsS3.UseSignatureVersion4 = true; set, once i removed than it started failing. Hence deleted the comment

**Comment by ashishdhingra** [comment]
> AWSConfigsS3.UseSignatureVersion4 = true;

@ElectricVampire Just curious, what is the expiry duration of the presigned URL? Is it longer than 7 days, it would default back to `SigV2`.

Thanks,
Ashish

**Comment by ashishdhingra** [comment]
> @ashishdhingra I thought it worked with 3.7.4 version but it did not, i had AWSConfigsS3.UseSignatureVersion4 = true; set, once i removed than it started failing. Hence deleted the comment

@ElectricVampire Somehow, I'm unable to reproduce the issue for S3 bucket with `AWS Key Management Service key (SSE-KMS)` encryption enabled. The above code in https://github.com/aws/aws-sdk-net/issues/2543#issuecomment-1435366382 works fine with `builder.Services.AddDefaultAWSOptions(builder.Configuration.GetAWSOptions());` commented out.

I'm unsure if in your appsettings.json, you have default signature as `V2`. Could you please share the following:
- Sample code solution
-  Any other S3 bucket settings that we should be aware of?
- When was the bucket created? New buckets created support only Sig V4.
- Are you setting endpoint URL explicitly in `ClientConfig` explicitly? If yes, what does it look like?

Thanks,
Ashish

**Comment by niemyjski** [comment]
Does anyone know if this setting is still needed in the v4 client and if it's been fully resolved?

**Comment by normj** [comment]
@niemyjski If you are referring to the `UseSignatureVersion4` setting it was removed in V4 because we always use V4 with the exception of the expiration date being longer then 7 days the most that can be done for SigV4. In that case we fallback to SigV2.
