### ISSUE TITLE
Review pull request #2534 (DynamoDB transaction support)

### ISSUE THREAD

**Issue by RenesansJG** [aws/aws-sdk-net#2544]
### Describe the feature

I have implemented a solution to issue #1453 — supporting transactional operations for the DynamoDB object persistence and document models, but my PR hasn’t been reviewed for 2 weeks. Can someone please take a look at it?
PR is #2534 

### Use Case

The PR adds support for transactional operations in the DynamoDB object persistence and document models.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

AWSSDK.DynamoDBv2 3.7.101.47

### Targeted .NET Platform

.NET 7

### Operating System and version

Windows 11

**Comment by ashovlin** [comment]
#2534 was manually merged and released today as [version 3.7.103 of AWSSDK.DynamoDBv2](https://www.nuget.org/packages/AWSSDK.DynamoDBv2/3.7.103).
* https://github.com/aws/aws-sdk-net/commit/33de1ae3981d3471117ac7b93752855f4cb6c728 through https://github.com/aws/aws-sdk-net/commit/c98aeb417faef1c7a0161cb1a56a0c6479569319

Thanks again for your contribution (and reminder for reviewing it)!
