### ISSUE TITLE
InitSDK fails when trying to run server executable for Gamelift Anywhere fleet

### ISSUE THREAD

**Issue by gabetoth-alder** [aws/aws-sdk-net#2552]
### Describe the bug

Init fails when trying to run server for Gamelift Anywhere

### Expected Behavior

InitSDK succeeds as described in documentation

### Current Behavior

After starting the server executable the following fatal exception is thrown:

Windows:
```
|Fatal|WebSocket.connect|System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it.
InitSDK failure : [GameLiftError: ErrorType=LOCAL_CONNECTION_FAILED, ErrorName=Local connection failed., ErrorMessage=Connection to local agent could not be established.]˛
```
Linux:
```
|Fatal|WebSocket.connect|System.Net.Sockets.SocketException (0x80004005): Connection refused
                              at System.Net.Sockets.TcpClient..ctor (System.String hostname, System.Int32 port) [0x0006d] in <39d8670c8f6e487fb992d3c14d754584>:0
                              at WebSocketSharp.WebSocket.setClientStream () [0x0005f] in <3dbc6ef0559a4023b6744a59e39dceea>:0
                              at WebSocketSharp.WebSocket.doHandshake () [0x00000] in <3dbc6ef0559a4023b6744a59e39dceea>:0
                              at WebSocketSharp.WebSocket.connect () [0x00073] in <3dbc6ef0559a4023b6744a59e39dceea>:0
InitSDK failure : [GameLiftError: ErrorType=LOCAL_CONNECTION_FAILED, ErrorName=Local connection failed., ErrorMessage=Connection to local agent could not be established.]
```

### Reproduction Steps

1. Install AWS CLI to the target hardware and configure it. 
2. Create a custom location for Gamelift Anywhere, then create a fleet with setting it to Anywhere instance type.
3. Register this hardware with the register-compute command.
4. Request an auth token with the get-compute-auth-token command.
5. Run the server executable.
6. Observe exception.

### AWS .NET SDK and/or Package version used

AWSSDK.Core.3.7.105.9
AWSSDK.GameLift.3.7.102.48

### Targeted .NET Platform

Unity 2020.3.42f1, .NET 4.x, Mono or IL2CPP scripting backend

### Operating System and version

windows 11, Ubuntu 20.04

**Comment by ashishdhingra** [comment]
Hi @gabetoth-alder,

Good morning.

Thanks for reporting the issue. Somehow, I do not see AWS SDK calls in the stack trace above. From the error above, it appears to be connection refused error.

Are you referring to:
- [GameLift server SDK reference for C#](https://docs.aws.amazon.com/gamelift/latest/developerguide/integration-server-sdk-csharp-ref.html)? OR, 
- https://github.com/aws/amazon-gamelift-plugin-unity?
 
These are not maintained by AWS SDK for .NET team.

Thanks,
Ashish
