### ISSUE TITLE
Lambda AddPermissionRequest generates an error: "The request signature we calculated does not match the signature you provided"

### ISSUE THREAD

**Issue by lambch0p** [aws/aws-sdk-net#256]
I'm trying to add permissions to a lambda function.  The AmazonLambdaClient I create is able to create the function, so the Access & Secret key details are OK, but when trying to AddPermission I receive the error above.

My basic test code is a follows:

    public AddPermissionResponse SetPerms()
    {
    var region = RegionEndpoint.USEast1;
    var client = new AmazonLambdaClient(region);

            var request = new AddPermissionRequest
            {
                FunctionName = "CloudTrailEventProcessing",
                SourceAccount = 999999999999",
                SourceArn = "arn:aws:s3:::cloudtrail-999999999999",
                StatementId = "id1",
                Principal = "s3.amazonaws.com",
                Action = "lambda:InvokeFunction"
            };
            return client.AddPermission(request);
        }

Resulting in an Amazon.Lambda.AmazonLambdaException:
The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

Thanks
M

**Comment by PavelSafronov** [comment]
Thanks for reporting this. I'm able to reproduce this issue, looking into it now.

**Comment by PavelSafronov** [comment]
We've just patched Core with a fix for this issue. Please try the latest versions of Core and Lambda packages.

**Comment by lambch0p** [comment]
Thanks Pavel.  I can confirm this resolves the issue for AddPermission.  The problem still exists for GetPolicy(GetPolicyRequest) though.  I'll create another ticket for that.
