### ISSUE TITLE
AmazonDynamoDBClient fails to operate after creation another client instance with invalid credentials.

### ISSUE THREAD

**Issue by anat0li** [aws/aws-sdk-net#2560]
### Describe the bug

AmazonDynamoDBClient instances seem to be cached somehow by AccessKey. After the first attempt of client creation with an invalid SecretKey, the second attempt of client creation with the same AccessKey, but a valid SecretKey this time, results in the client instance that is not operating properly throwing the same errors as being created with invalid credentials.

### Expected Behavior

The first client that was created with invalid credentials is expected to fail to operate with InvalidSignatureException thrown.

The second client that was created with valid credentials is expected to operate correctly delivering the expected results for the methods executed.

### Current Behavior

The first client that was created with invalid credentials fails to operate with InvalidSignatureException thrown.

The second client that was created with valid credentials also fails to operate with InvalidSignatureException thrown.

### Reproduction Steps

The following code can be used to demonstrate the problem. All ###... sequences are to be replaced with the correct values for the account access key, secret key, and region.

```
using Amazon;
using Amazon.DynamoDBv2;
using Amazon.DynamoDBv2.Model;
using Amazon.Runtime;

const string accessKey = "###########";
const string secretKey = "###############################";

static async Task<int> GetTableCount(string accessKey, string secretKey)
{
    var credentials = new BasicAWSCredentials(accessKey, secretKey);
    using var client = new AmazonDynamoDBClient(credentials, RegionEndpoint.#######);
    try
    {
        var response = await client.ListTablesAsync(
            new ListTablesRequest());
        return response.TableNames.Count;
    }
    catch (AmazonDynamoDBException exception)
    {
        Console.WriteLine(exception.ErrorCode);
        return -1;
    }
}

int error = await GetTableCount(accessKey, "THIS_IS_A_MADE_UP_NON_EXISTING_KEY");
Console.WriteLine(error);

int count = await GetTableCount(accessKey, secretKey);
Console.WriteLine(count);
```
Currently, the program outputs the following:

```
InvalidSignatureException
-1
InvalidSignatureException
-1
```

If the error lines are commented out, as it is shown below

```
// int error = await GetTableCount(accessKey, "THIS_IS_A_MADE_UP_NON_EXISTING_KEY");
// Console.WriteLine(error);

int count = await GetTableCount(accessKey, secretKey);
Console.WriteLine(count);
```
the program outputs just the expected number of tables for the specified account, say 5.

Then the expected program output:
```
InvalidSignatureException
-1
5
```

with outputting the expected table count for the second, properly created client.

### Possible Solution

Caching client instances by whole credentials, not just by the access key. But I don't really know how that is currently implemented in SDK.  

### AWS .NET SDK and/or Package version used

AWSSDK.DynamoDBv2 Version="3.7.101"

### Targeted .NET Platform

.NET Framework 4.7, .NET 6

### Operating System and version

Windows 10

**Comment by anat0li** [comment]
Interestingly, for the swapped call order, as below:

```
int count = await GetTableCount(accessKey, secretKey);
Console.WriteLine(count);

int error = await GetTableCount(accessKey, "THIS_IS_A_MADE_UP_NON_EXISTING_KEY");
Console.WriteLine(error);
```

the program outputs as expected:

```
5
InvalidSignatureException
-1
```

**Comment by ashishdhingra** [comment]
- Reproducible on Windows 10 targeting .NET 6.
- Not reproducible on Mac.

**Comment by anat0li** [comment]
BTW, despite to **dynamodb** label, similar behavior can be shown for other SDK packages. For instance, using the following method:

```
static async Task<int> GetUserCount(string accessKey, string secretKey)
{
    var credentials = new BasicAWSCredentials(accessKey, secretKey);
    using var client = new AmazonIdentityManagementServiceClient(credentials, RegionEndpoint.USEast2);
    try
    {
        var response = await client.ListUsersAsync(
            new ListUsersRequest());
        return response.Users.Count;
    }
    catch (AmazonIdentityManagementServiceException exception)
    {
        Console.WriteLine(exception.ErrorCode);
        return -1;
    }
}
```

the same output can be received for AWSSDK.IdentityManagement Version="3.7.100"

**Comment by ashishdhingra** [comment]
P83496504

**Comment by anat0li** [comment]
What is the meaning of this ID?

**Comment by ashishdhingra** [comment]
> What is the meaning of this ID?

Please ignore it. We are investigating.

**Comment by normj** [comment]
Hi @anat0li 

This issue is caused by how the .NET SDK pools HTTP clients across service clients. In your example both instances of the `AmazonDynamoDBClient` are using the same  HTTP client under the covers and then the same HTTP connection. The error is coming from the service side as part of their negative auth cache which is keyed off by access key id. The negative auth cache window is relatively short, in the order of seconds.

The only way for us to address this behavior for the .NET SDK is not pool HTTP clients across service clients which would be a significant performance hit. Given that most times users are dealing with invalid credentials and then repair with correct credentials would involve a new access key id as well we are not going to make that change. If your case does involve having the same access key id and you need to work around this you can construct the service client like below disabling the pool of Http clients.

var config = new AmazonSecurityTokenServiceConfig
{
    RegionEndpoint = RegionEndpoint.USWest2,
    CacheHttpClient = false
};
using var client = new AmazonSecurityTokenServiceClient(credentials, config);
