### ISSUE TITLE
MultipartUploadCommand.UploadPartAsync does not do retries

### ISSUE THREAD

**Issue by kasarino** [aws/aws-sdk-net#2561]
### Describe the feature

Amazon.S3.Transfer.Internal.MultipartUploadCommand.UploadPartAsync() does not do retries.
I believe it should do, in the same way as DownloadCommand.ExecuteAsync(), basing on _s3Client.Config.MaxErrorRetry

### Use Case

Than larger is multipart upload than higher is the probability of a total failure if not retry failed parts

### Acknowledgements

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

AWSSDK.S3 3.7.8.13

### Targeted .NET Platform

.NET Framework 4.7

### Operating System and version

Windows 10

**Comment by kasarino** [comment]
`
        private async Task<UploadPartResponse> UploadPartAsync(UploadPartRequest uploadRequest, CancellationTokenSource internalCts, SemaphoreSlim asyncThrottler)
        {
            var maxRetries = _s3Client.Config.MaxErrorRetry;

            for (int retry = 1; ; retry++)
            {
                try
                {
                    return await _s3Client.UploadPartAsync(uploadRequest, internalCts.Token)
                        .ConfigureAwait(continueOnCapturedContext: false);
                }
                catch (Exception exception)
                {
                    if (retry <= maxRetries)
                    {
                         Logger.DebugFormat("Multipart Upload {0} part #{1} retry #{2}", uploadRequest.UploadId, uploadRequest.PartNumber, retry);
                    }
                    else
                    {
                        if (!(exception is OperationCanceledException))
                        {
                            // Cancel scheduling any more tasks
                            // Cancel other UploadPart requests running in parallel.
                            internalCts.Cancel();
                        }
                        throw;
                    }
                }
                finally
                {
                    asyncThrottler.Release();
                }
            }
        }       
`

**Comment by ashishdhingra** [comment]
@kasarino Good morning. Thanks for opening feature request. Have you looked at [Retries and timeouts](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/retries-timeouts.html). AWS SDK for .NET should retry failed service API calls automatically based on retry mode and max error retry configuration. So I don't think we need to add duplicated capability specific to `MultipartUploadCommand.UploadPartAsync()` given that we have centralized retry for all SDK service API calls.

Thanks,
Ashish

**Comment by kasarino** [comment]
Hello @ashishdhingra , thank you for reply.
I use TransferUtility.UploadAsync() as follows and it actually does not do retries...
```
            AmazonS3Config config = new AmazonS3Config()
            {
                ServiceURL = serviceURL,
                RetryMode = Amazon.Runtime.RequestRetryMode.Standard,
                MaxErrorRetry = 3
            };
            client = new AmazonS3Client(awsAccessKeyId, awsSecretAccessKey, config);
                var transferUtility = new TransferUtility(client);
                await transferUtility.UploadAsync( filePath,
                                          TargetBucket,
                                          TargetObjectKey
                                        );

```

**Comment by ashishdhingra** [comment]
@kasarino Could you please enable verbose logging using below code and share the logs to see if the failed `UploadPartAsync` call is not retried:
```C#
Amazon.AWSConfigs.LoggingConfig.LogResponses = Amazon.ResponseLoggingOption.Always;
Amazon.AWSConfigs.LoggingConfig.LogTo = Amazon.LoggingOptions.SystemDiagnostics;
Amazon.AWSConfigs.AddTraceListener("Amazon", new System.Diagnostics.ConsoleTraceListener());
```

Thanks,
Ashish

**Comment by kasarino** [comment]
Hello @ashishdhingra 
here are requested logs [https://file.io/jzpHJwMJq1bo]
Thank you!

**Comment by ashishdhingra** [comment]
> Hello @ashishdhingra here are requested logs https://www.dropbox.com/s/ok6iq3tb7bztnyw/log400_no_retry_example.zip?dl=0 Thank you!

@kasarino Could you please share the following:
- What is the endpoint `https://emam.qstartest.net:18085`? Doesn't appear to be AWS service.
- Are you using 3rd party storage that simulates AWS S3 service?
- Is the retry issue reproducible when used against actual AWS S3 service?

Unfortunately, we do not support 3rd party AWS simulated environments.

Thanks,
Ashish

Thanks,
Ashish

**Comment by kasarino** [comment]
Hello @ashishdhingra 
yes, I test at 3rd party S3 service (and it is hard to reproduce at actual AWS S3 as it almost never returns network errors :))
Thank you for your time, let's close this issue.
