### ISSUE TITLE
IAmazonS3 GetObjectAsync throws "The specified key does not exist." Exception - Before returned not found http response

### ISSUE THREAD

**Issue by DavidRooney** [aws/aws-sdk-net#2563]
### Describe the bug

IAmazonS3 GetObjectAsync is throwing a "The specified key does not exist." Exception where as before it was not found http response. To be specific it throws an AggregateException that contains this AmazonS3Exception.

I have reviewed the documentation here - https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/S3/MIS3GetObjectAsyncGetObjectRequestCancellationToken.html and can't see any indication of this change or that any exceptions would be thrown and need to be handled.

Assuming this is a bug.

![Aggregate exception](https://user-images.githubusercontent.com/5816946/223105788-2287305d-47c8-4554-baa8-36dfe68d6bd2.png)
![Inner Exception - AmazonS3Exception](https://user-images.githubusercontent.com/5816946/223105836-0cbcd473-dbe5-41f5-81bb-97f419fd2d4e.png)

### Expected Behavior

Not found response to be returned

### Current Behavior

key does not exist exception

### Reproduction Steps

1. Download AWSSDK.S3 version 3.7.101.10
2. Call IAmazonS3.GetBucketAsync using a GetObjectRequest object for a key that doesn't exist

### AWS .NET SDK and/or Package version used

AWSSDK.S3 3.7.101.10

### Targeted .NET Platform

.NET 6

### Operating System and version

Windows, Mac, Lambda

**Comment by ashishdhingra** [comment]
@DavidRooney Good morning. Thanks for opening the issue. Could you please elaborate the issue? The specified error is returned by the S3 service. Were you getting a different error earlier? If yes, in which version and the previous error?

Thanks,
Ashish

**Comment by DavidRooney** [comment]
Thanks for getting back so quickly. Below is an example of the code. the first line throws the exception. We have never had this error before and seems to have start int he last couple of days. Normally the response would not be a 200 and our code would handle this.

```
public async Task<string> GetBucketObject(string bucketName, string key, CancellationToken cancellationToken = default)
{
	var request = new GetObjectRequest
	{
		BucketName = bucketName,
		Key = key
	};
			
	using var response = await _s3Client.GetObjectAsync(request, cancellationToken);
	if (response.HttpStatusCode != System.Net.HttpStatusCode.OK)
	{
		return null;
	}
	using var responseStream = response.ResponseStream;
	using var reader = new StreamReader(responseStream);

	return await reader.ReadToEndAsync();
}
```

**Comment by DavidRooney** [comment]
Just an FYI, we are also seeing this same issue with Tables that already exist in glue. It not returns AggregateExceptions and we haven't changed this code for Months.

Example code is:
```
            IAmazonGlue _amazonGlueClient = new GlueClientProxy();

            try
            {
                var response = await _amazonGlueClient.CreateTableAsync(createTableRequest);
            }
            catch (AlreadyExistsException)
            {
                // Return table exists
            }
            catch (AggregateException e) // This is how we are having to handle this at a quick workaround
            {
                if (e.GetBaseException().Message == $"Table already exists.")
                {
                    // Return table exists
                }
                else
                {
                    throw;
                }
            }
```

I understand this should probably be a separate issue though. Seems odd that these would happen at the same time. It's as if AWS are moving to an Exception based response pattern over Response objects with HTTP status codes. But I can't find anything online about this breaking change

**Comment by ashishdhingra** [comment]
@DavidRooney Thanks for your response. As far as I know, nothing has changed in SDK for returning exceptions. I'm unsure if anything changed on the service API side. Were you using the same version earlier where you were relying on HTTP status code instead of exception?

Thanks,
Ashish

**Comment by DavidRooney** [comment]
Yes we got the error without updating any versions. We haven't updated any nuget packages in our solution since November. Since discovering this exception we have updated and we still get the exception. So this definitely feels like service API side.

**Comment by ashishdhingra** [comment]
> Yes we got the error without updating any versions. We haven't updated any nuget packages in our solution since November. Since discovering this exception we have updated and we still get the exception. So this definitely feels like service API side.

@DavidRooney We are unaware of any change in behavior from the service side. The SDK is also unchanged w.r.t. handling HTTP response/exceptions from service API.

**Comment by ashovlin** [comment]
I haven't found other reports of this searching internally, and am pretty stumped so far. The `AmazonS3Exception` with _The specified key does not exist._ is what the SDK returns when we receive a 404 from S3, since long before November.

```
HTTP/1.1 404 Not Found
x-amz-request-id: <redacted>
x-amz-id-2: <redacted>
Content-Type: application/xml
Transfer-Encoding: chunked
Date: Thu, 16 Mar 2023 14:42:57 GMT
Server: AmazonS3

126
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>bad-key-123</Key><RequestId>redacted</RequestId><HostId>redacted</HostId></Error>
0
```

I know you've said you haven't changed the code, but has any other aspects of your application changed:
* How the S3 client is configured?
* .NET version?
* Lambda runtime?
* Which regions, buckets/access points, etc. you're getting objects from?
* Any networking/observability/etc. middleware that the requests may be passing through?

You mentioned "Windows, Mac, Lambda":
* Is it reproducible consistently across all three?
* Which Lambda runtime are you using?

**Comment by DavidRooney** [comment]
Apologies, I don't receive updates and because we added workarounds this issue hasn't come up to remind me to check back!

To answer your questions:

- How the S3 client is configured?
   - We use erviceCollection.AddAWSService<IAmazonS3>(); to configure the S3 client
- .NET version?
   - We run all .NET code on the latest LTS so .NET 6 right now.
- Lambda runtime?
   - We use .NET 6 runtime in all our AWS Lambdas. 
- Which regions, buckets/access points, etc. you're getting objects from?
   - All S3 buckets are on eu-west-2 which is the same region as the Lambdas that access it.
- Any networking/observability/etc. middleware that the requests may be passing through?
   - None. We have Proxy code for encapsulated all IAmazonS3 functionality but it's a simple proxy with no manipulation
- Is it reproducible consistently across all three? Windows, Mac, Linux
   - We haven't tested Mac but have seen the error in our Production Lambdas as well as debugging on Windows machines.

With all this in mind we have not been monitoring this error. We could create a new test to see if it's still occurring after updating the SDK versions again. I'll update when we can do this
