### ISSUE TITLE
If a SharedCredentialsFile doesn't exist, using environment credentials throws an exception

### ISSUE THREAD

**Issue by Ed1970SC** [aws/aws-sdk-net#2568]
### Describe the bug

When using a .net6 console app where a Shared Credentials File doesn't exist on disk, trying to use EnvironmentVariablesAWSCredentials throws an exception.

### Expected Behavior

It should not throw an exception. 

### Current Behavior

Unhandled exception. System.TypeInitializationException: The type initializer for 'Amazon.Runtime.Internal.FallbackInternalConfigurationFactory' threw an exception.
 ---> System.ArgumentException: Invalid region endpoint provided
   at Amazon.Internal.RegionEndpointProviderV3.GetNonstandardRegionEndpoint(String regionName)
   at Amazon.Internal.RegionEndpointProviderV3.GetRegionEndpoint(String regionName)
   at Amazon.RegionEndpoint.GetEndpoint(String systemName, String displayName)
   at Amazon.RegionEndpoint.GetBySystemName(String systemName)
   at Amazon.Runtime.CredentialManagement.SharedCredentialsFile.TryGetProfile(String profileName, Boolean doRefresh, Boolean isSsoSession, CredentialProfile& profile)
   at Amazon.Runtime.CredentialManagement.SharedCredentialsFile.TryGetProfile(String profileName, CredentialProfile& profile)
   at Amazon.Runtime.CredentialManagement.CredentialProfileStoreChain.TryGetProfile(String profileName, CredentialProfile& profile)
   at Amazon.Runtime.Internal.ProfileInternalConfiguration.Setup(ICredentialProfileSource source, String profileName)
   at Amazon.Runtime.Internal.ProfileInternalConfiguration..ctor(ICredentialProfileSource source)
   at Amazon.Runtime.Internal.FallbackInternalConfigurationFactory.Reset()
   at Amazon.Runtime.Internal.FallbackInternalConfigurationFactory..cctor()
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.FallbackInternalConfigurationFactory.get_RetryMode()
   at Amazon.Runtime.ClientConfig.get_RetryMode()
   at Amazon.Runtime.AmazonServiceClient.BuildRuntimePipeline()
   at Amazon.Runtime.AmazonServiceClient..ctor(AWSCredentials credentials, ClientConfig config)
   at Amazon.S3.AmazonS3Client..ctor(AWSCredentials credentials, AmazonS3Config clientConfig)
   at Amazon.S3.AmazonS3Client..ctor(AWSCredentials credentials, RegionEndpoint region)
   at SdkWoes.Program.Main(String[] args) in Program.cs:line 13

### Reproduction Steps

        static void Main(string[] args)
        {
            Console.WriteLine("Hello, World!");
            EnvironmentVariablesAWSCredentials creds = new EnvironmentVariablesAWSCredentials();
            using var client = new AmazonS3Client(creds, RegionEndpoint.USEast1);

        }

### Possible Solution

The problem stems from the Amazon.Runtime.CredentialManagement.CredentialProfileStoreChain.TryGetProfile. It instantiates a SharedCredentialsFile object. The SharedCredentialsFile assumes there is actual a file somewhere on disk. 

The profile/credentials loading process needs to gracefully handle when only the EnvironmentVariablesAWSCredentials are the source of credential info (i.e. when no shared credentials file exists on disk)

### Additional Information/Context

This .net app is running on a build server so the user home directory, etc does not have the .aws/ folder. The user folder gets wiped before and after every build job.

### AWS .NET SDK and/or Package version used

AWSSDK.Code 3.7.105.15
AWSSDK.S3 3.7.103.23

### Targeted .NET Platform

.net 6

### Operating System and version

Windows 2019

**Comment by ashishdhingra** [comment]
Hi @Ed1970SC,

Good morning.

Unfortunately, I'm unable to reproduce the issue. Below are the steps:
- Ensured that the shared `credentials` and `config` file (under `%USERPROFILE%`\.aws`) doesn't exist.
- In Visual Studio debug configuration, configured the environment variables for credentials (as documented at [Credential and profile resolution](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/creds-assign.html)).
- Executed the below code via Visual Studio (used `AWSSDK.S3` version `3.7.103.24`. Also, this code enables verbose logging):
```C#
using Amazon;
using Amazon.Runtime;
using Amazon.S3;

Amazon.AWSConfigs.LoggingConfig.LogResponses = Amazon.ResponseLoggingOption.Always;
Amazon.AWSConfigs.LoggingConfig.LogTo = Amazon.LoggingOptions.SystemDiagnostics;
Amazon.AWSConfigs.AddTraceListener("Amazon", new System.Diagnostics.ConsoleTraceListener());

EnvironmentVariablesAWSCredentials creds = new EnvironmentVariablesAWSCredentials();
using var client = new AmazonS3Client(creds, RegionEndpoint.USEast1);
client.ListBucketsAsync().Wait();
Console.Read();
```
**RESULT:**
Below is the redacted output:
```
Amazon Information: 0 : Credentials found using environment variables.
Amazon Information: 0 : The environment variable AWS_ENABLE_ENDPOINT_DISCOVERY was not set with a value.
Amazon Information: 1 : The environment variable AWS_MAX_ATTEMPTS was not set with a value.
Amazon Information: 2 : The environment variable AWS_RETRY_MODE was not set with a value.
Amazon Information: 3 : The environment variable AWS_EC2_METADATA_SERVICE_ENDPOINT was not set with a value.
Amazon Information: 4 : The environment variable AWS_EC2_METADATA_SERVICE_ENDPOINT_MODE was not set with a value.
Amazon Information: 5 : The environment variable AWS_USE_DUALSTACK_ENDPOINT was not set with a value.
Amazon Information: 6 : The environment variable AWS_USE_FIPS_ENDPOINT was not set with a value.
Amazon Information: 0 : Unable to find a profile named 'default' in store Amazon.Runtime.CredentialManagement.CredentialProfileStoreChain
Amazon Information: 0 : Resolved DefaultConfigurationMode for RegionEndpoint [us-east-1] to [Legacy].
Amazon Information: 1 : Credentials found using environment variables.
Amazon Verbose: 0 : Received response (truncated to 1024 bytes): [<?xml version="1.0" encoding="UTF-8"?>
<ListAllMyBucketsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Owner><ID>d54292206871cec539963f22c342d765ba1d4375d3e600a45fad04ca2a86dc14</ID><DisplayName>REDACTED</DisplayName></Owner><Buckets><Bucket><Name>REDACTED</Name><CreationDate>REDACTED</CreationDate></Bucket><Bucket><Name>REDACTED</Name><CreationDate>REDACTED</CreationDate></Bucket></Buckets></ListAllMyBucketsResult>]
```

Thanks,
Ashish

**Comment by Ed1970SC** [comment]
Digging in my initial assessment wasn't quite correct. There is an .aws directory in the home directory and the config and credentials files are present. The config file contains:
```
[default]
region =  
```

The credentials file contains:
```
[default]
aws_access_key_id =  
aws_secret_access_key =  
aws_session_token =  
```

It's the lack of values for those fields that seems to be the source of the problem. That makes me question, is that by design or a bug...

**Comment by ashishdhingra** [comment]
> It's the lack of values for those fields that seems to be the source of the problem. That makes me question, is that by design or a bug...

@Ed1970SC This is as per design. For above files, you should either provide a valid value or not specify the key at all. Per [Credential and profile resolution](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/creds-assign.html), `default` profile is probed before environment variables (there is an open issue https://github.com/aws/aws-sdk-net/issues/1779 to make it consistent with other SDK(s), however, that would be fixed in next major version). Please refer to similar issue https://github.com/aws/aws-sdk-net/issues/1908#issuecomment-910826163 reported in the past.

I would advise to wipe out user folder before and after every build job (as you mentioned earlier). Please confirm if we could close this issue now that we have found the root cause and workaround.

Thanks,
Ashish

**Comment by Ed1970SC** [comment]
For completeness, there are multiple work arounds. Wiping the files as suggest above. Another is to use the AWS_SHARED_CREDENTIALS_FILE environment variable and create a file with the contents:
```
[profile default]
region=us-east-1
```
