### ISSUE TITLE
S3 client does not work with the s3.eu-central-1.wasabisys.com subdomain

### ISSUE THREAD

**Issue by Mr0N** [aws/aws-sdk-net#2583]
### Describe the bug

Problem:
The aws-sdk-net client does not work with the s3.eu-central-1.wasabisys.com subdomain.

Steps to Reproduce:
Create a new instance of AmazonS3Client, specifying the s3.eu-central-1.wasabisys.com subdomain as the endpoint, for example:

```
var client = new AmazonS3Client(
    "ACCESS_KEY",
    "SECRET_KEY",
    new AmazonS3Config
    {
        ServiceURL = "https://s3.eu-central-1.wasabisys.com"
    });
```
Try to perform any operation, for example, get a list of buckets:
csharp
`var response = await client.ListBucketsAsync();`
Expected Result:
The ListBucketsAsync method should execute successfully and return the list of buckets.

Actual Result:
The ListBucketsAsync method throws an Amazon.S3.AmazonS3Exception with the message "The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint."

Assumptions:
The problem is related to incorrect configuration of the client or incorrect handling of the s3.eu-central-1.wasabisys.com subdomain in the aws-sdk-net client.

Additional Information:
The s3.wasabisys.com subdomain works with the client.
The problem occurs only with the s3.eu-central-1.wasabisys.com subdomain.
The problem may be related to the addition of a new regional endpoint for S3 in Wasabi.
There may be a bug in the code of the aws-sdk-net client that does not allow processing of the s3.eu-central-1.wasabisys.com subdomain.

### Expected Behavior

-

### Current Behavior

-

### Reproduction Steps

-

### Possible Solution

-

### AWS .NET SDK and/or Package version used

-

### Targeted .NET Platform

Net 6

### Operating System and version

Linux,Windows is good work

**Comment by ashishdhingra** [comment]
Hi @Mr0N,

Good afternoon.

I tested the below code using the standard AWS S3 endpoint for `eu-central-1` and it works perfectly fine:
```C#
using (var tempClient = new AmazonS3Client(new AmazonS3Config() { ServiceURL = "https://s3.eu-central-1.amazonaws.com" }))
{
    var listbucketsResponse = tempClient.ListBucketsAsync().Result;
}
```

Looks like you are using `AWSSDK.S3` with 3rd party [Wasabi Cloud Storage Service](https://wasabi.com/). While most of the AWS SDKs might work fine with these 3rd party S3 (like) service, unfortunately, we do not support using AWS SDK with these 3rd party services. You might want to open ticket with Wasabi support for possible workaround.

Thanks,
Ashish

**Comment by ashishdhingra** [comment]
> Regions were excluded, this code worked in Windows, well, it did not work in a docker container running on Linux
> 
> log 2023-04-10 22:54:15 Amazon Information: 0 : The environment variable AWS_ENABLE_ENDPOINT_DISCOVERY was not set with a value. 2023-04-10 22:54:15 Amazon Information: 1 : The environment variable AWS_MAX_ATTEMPTS was not set with a value. 2023-04-10 22:54:15 Amazon Information: 2 : The environment variable AWS_RETRY_MODE was not set with a value. 2023-04-10 22:54:15 Amazon Information: 3 : The environment variable AWS_EC2_METADATA_SERVICE_ENDPOINT was not set with a value. 2023-04-10 22:54:15 Amazon Information: 4 : The environment variable AWS_EC2_METADATA_SERVICE_ENDPOINT_MODE was not set with a value. 2023-04-10 22:54:15 Amazon Information: 5 : The environment variable AWS_USE_DUALSTACK_ENDPOINT was not set with a value. 2023-04-10 22:54:15 Amazon Information: 6 : The environment variable AWS_USE_FIPS_ENDPOINT was not set with a value. 2023-04-10 22:54:15 Amazon Information: 0 : UserCrypto is not supported. This may be due to use of a non-Windows operating system or Windows Nano Server, or the current user account may not have its profile loaded. Unable to load shared library 'Crypt32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libCrypt32.dll: cannot open shared object file: No such file or directory 2023-04-10 22:54:15 Amazon Information: 0 : Unable to find a profile named 'default' in store Amazon.Runtime.CredentialManagement.CredentialProfileStoreChain 2023-04-10 22:54:15 Amazon Information: 0 : Resolved DefaultConfigurationMode for RegionEndpoint [] to [Legacy].

@Mr0N Thanks for the information. This information that it is not working in Docker was missing from the issue description. On Windows, the region might have been picked from `default` profile (in `credentials` or `config` file) or other source (refer [Region resolution](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-region-selection.html)). On Docker, you might want to set these in environment variables.

Again, we do not support troubleshooting issues with AWS SDK when used with 3rd party services.

Thanks,
Ashish

**Comment by Mr0N** [comment]
> Contributor

start working)
