### ISSUE TITLE
DynamoDB: UTF8 Strings on AttributeValue

### ISSUE THREAD

**Issue by zmj** [aws/aws-sdk-net#2595]
### Describe the feature

Instead of getting and setting `AttributeValue.S` (type string, UTF16), I would like another getter/setter that exposes the value as UTF8 (type ReadOnlyMemory<byte> or a wrapper around it).

### Use Case

My application uses UTF8 strings internally, and it's annoying to encode/decode the values when interacting with DynamoDB.

### Proposed Solution

A new config on the DynamoDB client instructs it to serialize and deserialize using `AttributeValue.S_U8` instead of `AttributeValue.S`. This would be opt-in; the current behavior remains the default.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

AWSSDK.DynamoDBv2 3.7.102.13

### Targeted .NET Platform

.NET 6+

### Operating System and version

N/A

**Comment by ashishdhingra** [comment]
Per [Supported data types and naming rules in Amazon DynamoDB](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html), `Strings are Unicode with UTF-8 binary encoding.`. Whereas the .NET `string` represents text as a sequence of UTF-16 code units.

Needs review with the team.

**Comment by ashishdhingra** [comment]
@zmj Could you please provide a scenario where your application would need to use UTF-8 strings? .NET string is UTF-16 by default.

Thanks,
Ashish

**Comment by zmj** [comment]
My application doesn't use the `System.String` type (other than to interact with the DynamoDB SDK). It deserializes from UTF-8 json input, storing `ReadOnlyMemory<byte>` and using that for business logic. Only the ASCII character set is valid input.

My goal with this proposed change is to pass those `ReadOnlyMemory<byte>` buffers containing UTF-8 text to the DynamoDB SDK, instead of converting to UTF-16 `System.String` to set `AttributeValue.S`.

**Comment by normj** [comment]
Sorry but this isn't a feature that is practical for us to do in the SDK.

The `Attribute.S` property is generated from the service model using our .NET SDK generator. In order to do this we would have to  update the generator for all string properties to generate an auxiliary using `ReadOnlyMemory<byte>`. That would have a massive foot print across the SDK. Also given our JSON parser, which is not the modern `System.Text.Json`, the `ReadOnlyMemory<byte>` would end up still being converted to a string.
