### ISSUE TITLE
LastModified date from GetObjectAttributesAsync() is {01/01/0001 00:00:00}

### ISSUE THREAD

**Issue by AlanRitchie** [aws/aws-sdk-net#2599]
### Describe the bug

Calling `GetObjectAttributesAsync` returns a response with a last modified date set to {01/01/0001 00:00:00}.  Calling the api directly has a correct Last-Modified header

### Expected Behavior

`GetObjectAttributesAsync` should return a response with the same `LastModified` date as `GetObjectMetadataAsync` `GetObjectAsync` or `ListObjectsV2` 

### Current Behavior

Response.LastModified is {01/01/0001 00:00:00}

### Reproduction Steps

Using .Net Core 6 console app and AWSSDK.S3 version 3.7.104.13

```
using Amazon;
using Amazon.S3.Model;
using Amazon.S3;

string accountName = redacted;
string accountKey = redacted;
string systemName = "eu-central-1";
string bucketName = redacted;
string objectName = redacted;

AWSConfigs.LoggingConfig.LogTo = LoggingOptions.Console;

var client = new AmazonS3Client(accountName, accountKey, RegionEndpoint.GetBySystemName(systemName));


// Do a GetObjectAttributes request
var request = new GetObjectAttributesRequest
{
    BucketName = bucketName,
    Key = objectName,
    ObjectAttributes = new List<ObjectAttributes> { ObjectAttributes.ObjectSize }
};
GetObjectAttributesResponse response = await client.GetObjectAttributesAsync(request);

Console.WriteLine(response.ObjectSize);
Console.WriteLine(response.LastModified.ToString());

// compare to a GetObjectMetadataRequest
var request2 = new GetObjectMetadataRequest
{
    BucketName = bucketName,
    Key = objectName
};
var response2 = await client.GetObjectMetadataAsync(request2);

Console.WriteLine(response2.ContentLength);
Console.WriteLine(response2.LastModified.ToString());
```

### AWS .NET SDK and/or Package version used

AWSSDK.S3 version 3.7.104.13

### Targeted .NET Platform

.Net 6

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment]
The `GetObjectAttributesResponseUnmarshaller` was added in commit https://github.com/aws/aws-sdk-net/commit/35d623ab334e14ebc21bd984b4b1a89d977dec7b#diff-9b147ad4991c32fa55cbc71640d3cee9f392ecb2119e027184e5ecda3d511a55.

**Comment by ashishdhingra** [comment]
This has been fixed in [AWSSDK.S3 version 3.7.104.18](https://www.nuget.org/packages/AWSSDK.S3/3.7.104.18)
