### ISSUE TITLE
Lambda GetPolicy(GetPolicyRequest) generates an error: "The request signature we calculated does not match the signature you provided

### ISSUE THREAD

**Issue by lambch0p** [aws/aws-sdk-net#260]
Hi,

I'm using the AWSSDK.Core.3.1.3.2 and AWSSDK.Lambda.3.1.2.1 packages.

When I try to  perform a GetPolicy call on the Lambda client, I receive the error in the subject line.

Sample code:

    public GetPolicyResponse GetPerms(string functionName)
    {
        var region = RegionEndpoint.USEast1;
        var client = new AmazonLambdaClient(region);
        var request = new GetPolicyRequest
        {
            FunctionName = functionName;
        }
        return client.GetPolicy(request);
    }

Thanks

**Comment by PavelSafronov** [comment]
I'm able to reproduce this issue and we are working on a fix. No estimate at this time, though.

**Comment by PavelSafronov** [comment]
We've just released a patched version of the Lambda package to resolve this issue. Please try the latest package or source.

**Comment by lambch0p** [comment]
Thanks Pavel.  I can confirm it works.
