### ISSUE TITLE
.marks files are not retrieving from s3 

### ISSUE THREAD

**Issue by kellycastrof** [aws/aws-sdk-net#2606]
### Describe the bug

There are some .marks files in an s3 bucket that were created by Polly, and when trying to get those files from s3 using the ListObjectsAsync method with a prefix is not return those files.
Boto3 for Python and AWS CLI don't have this issue.

### Expected Behavior

When calling the ListObjectsAsync method with a prefix, all files with the specified prefix should be returned regardless of the file extension.

### Current Behavior

In some cases, the file is retrieved in the list, but in others the list is empty.

### Reproduction Steps

1. Upload .marks file in S3 bucket using a prefix
2. Use ListObjects with the prefix used to get the file

### Additional Information/Context

Maybe it's a problem with the content type headers of the file
The content of the file is not a valid JSON (this is generated by aws polly):

```
{"time":373,"type":"word","start":5,"end":8,"value":"had"}
{"time":373,"type":"word","start":5,"end":8,"value":"had"}
{"time":373,"type":"word","start":5,"end":8,"value":"had"}
```

### AWS .NET SDK and/or Package version used

AWSSDK.Core 3.7.106
AWSSDK.S3 3.7.101

### Targeted .NET Platform

net6.0

### Operating System and version

macOS Ventura 13.2.1

**Comment by ashishdhingra** [comment]
Per [Using Speech Marks](https://docs.aws.amazon.com/polly/latest/dg/using-speechmarks.html), Amazon Polly supports only the JSON format when returning speech marks. Example JSON at this documentation is `{"time":373,"type":"word","start":5,"end":8,"value":"had"}` which is similar to what is reported in the ticket.
