### ISSUE TITLE
S3FileInfo Exists with space in the key name

### ISSUE THREAD

**Issue by shaunbowe** [aws/aws-sdk-net#262]
I have tried every encoding I can think of for the key name and Exists always returns false. I have tried the following:
Leaving spaces un-encoded
Replacing with %20
Replacing with +
Replacing with %2B

In each case S3FileInfo.Exists returns false. I am using v2.3.52.0.

Here is some sample code:
```c#
public Stream GetFileContents(IAmazonS3 s3Client, string bucketName, string key) {
    var fileInfo = new S3FileInfo(s3Client, bucketName, key);
    if (fileInfo.Exists) {
         return fileInfo.OpenRead();
    }

    return null;
}
```

**Comment by normj** [comment]
I'm taking a look

**Comment by normj** [comment]
I haven't been able reproduce the error. Here is the test code I wrote but it always passes.

```
public void FileWithSpacesInName()
{
    var key = "The Space.txt";
    Client.PutObject(new PutObjectRequest
        {
            BucketName = bucketName,
            Key = key,
            ContentBody = "Test Data"
        });

    // Wait for eventual consistency of S3 before checking if the object exists
    Thread.Sleep(TimeSpan.FromSeconds(2));

    S3FileInfo fileInfo = new S3FileInfo(Client, bucketName, key);
    Assert.IsTrue(fileInfo.Exists);
}
```

I'm wondering if the encoding issue happened when you put the object in S3. Can you give some details on how the object was uploaded?

**Comment by shaunbowe** [comment]
I swear this didn't work yesterday. Now it works great. I know you walked over to the S3 team and had them fix this issue. Thanks for looking and sorry to waste your time.
