### ISSUE TITLE
No Such host is known 

### ISSUE THREAD

**Issue by PuneetKumar-02** [aws/aws-sdk-net#2625]
### Describe the bug

While reading file content from S3 bucket using .Net SDK, most of the time we are getting the data but frequently we are getting "No Such host is known" error. Due to this, many calls are getting failed daily. Our code has 'polly retry' mechanism which calls/retries to fetch it from S3( in case call gets failed) due to which our users are facing latency. For example, for one request we got the error "No Such host is known" even after retrying the same request for three times and when the same request was made after some time, we got successful response in milli seconds. Could you please help to resolve this issue ?

SDK version - 3.7.2

Code snippet:
AmazonS3 _s3Client = new AmazonS3Client(AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, RegionEndpoint.GetBySystemName(AWS_REGION));
GetObjectRequest request = new GetObjectRequest
{
BucketName = AWS_BUCKETNAME,
Key = fileName
};
GetObjectResponse response = await _s3Client.GetObjectAsync(request);
using (StreamReader reader = new StreamReader(response.ResponseStream))
{
responseObject = reader.ReadToEnd();
}

### Expected Behavior

Should able to read file content from S3 bucket using .Net SDK without any issues

### Current Behavior

Frequently we are getting "No such host is known" while reading data from S3 file.

### Reproduction Steps

Completely sporadic issue, no specific steps to replicate

### AWS .NET SDK and/or Package version used

3.7.2

### Targeted .NET Platform

.Net core 3.1

### Operating System and version

Windows 10,Windows 11, Windows server 2016

**Comment by PuneetKumar-02** [comment]
What is the average size of file(s) being retrieved from S3? around 100 KB
Are other applications also experiencing similar issue? yes other application which are using SDK having the same issue
Has the issue started after updating AWSSDK.S3 to a specific version OR is it an ongoing issue? no
Could you try upgrading to latest version of AWSSDK.S3 and check if it resolves the issue. Let us try
Could you share the verbose logs? These could be enabled using below minimal code: actually application is in production so as of now we donot have such logs and requires deployment to enable these logs

**Comment by ashishdhingra** [comment]
> this issue comes sporadic not with each call, execution environment is not a EC2 instance
> 
> What is the average size of file(s) being retrieved from S3? around 100 KB Are other applications also experiencing similar issue? _yes other application in which we are using SDK having the same issue_ Has the issue started after updating AWSSDK.S3 to a specific version OR is it an ongoing issue? _no_ Could you try upgrading to latest version of AWSSDK.S3 and check if it resolves the issue. _Let us try_ Could you share the verbose logs? These could be enabled using below minimal code: _actually application is in production so as of now we don't have such logs and requires deployment to enable these logs_

@PuneetKumar-02 Could you also share the below:
- Your execution environment (EC2 instance, Standalone machine, etc.)
  - If EC2 instance, is it behind the private VPC?
  - Could you please check the firewall rules or security group rules?

In case verbose logging using below code is not possible:
```
Amazon.AWSConfigs.LoggingConfig.LogResponses = Amazon.ResponseLoggingOption.Always;
Amazon.AWSConfigs.LoggingConfig.LogTo = Amazon.LoggingOptions.SystemDiagnostics;
Amazon.AWSConfigs.AddTraceListener("Amazon", new System.Diagnostics.ConsoleTraceListener());
```
please monitor the network request (may be using some network monitoring tool) and examine the host that SDK request is trying to reach out to you.

In case the request works sometimes and fails other times, it might be firewall issue or security group issue. SDK also has inbuilt retry mechanism as documented at [Retries and timeouts](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/retries-timeouts.html).

Thanks,
Ashish

**Comment by PuneetKumar-02** [comment]
actually I am able to resolve this , I will add my comments about the fix and close this so that it migt help somebody to resolve this type of issue

**Comment by ashishdhingra** [comment]
> actually I am able to resolve this , I will add my comments about the fix so that it might help somebody to resolve this type of issue and close this

@PuneetKumar-02 Thanks for the confirmation. I will close this issue for now. Feel free to add your resolution to this issue as suggested earlier, so that it could help others. :)
