### ISSUE TITLE
Async RDSAuthTokenGenerator

### ISSUE THREAD

**Issue by benlongo** [aws/aws-sdk-net#2628]
### Describe the feature

RDSAuthTokenGenerator only exposes a synchronous interface for obtaining the auth token. 

### Use Case

Since this is going over the network potentially I don't want to block.

### Proposed Solution

Add `GenerateAuthTokenAsync` overloads.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

AWSSDK.RDS 3.7.119.6

### Targeted .NET Platform

.NET 7

### Operating System and version

AmazonLinux

**Comment by normj** [comment]
Does this PR look like what you are asking for: https://github.com/aws/aws-sdk-net/pull/2629

**Comment by benlongo** [comment]
Yes, apologies for creating a redundant issue.

**Comment by benlongo** [comment]
Yes that should do it - thanks!

**Comment by normj** [comment]
Async version has been released as part of version [3.7.119.11](https://www.nuget.org/packages/AWSSDK.RDS/3.7.119.11) of the RDS module
