### ISSUE TITLE
Ability to mock generic TransactWrite<T>

### ISSUE THREAD

**Issue by roelvandenbrand** [aws/aws-sdk-net#2630]
### Describe the feature

With a IAmazonDynamoDB or IDynamoDBContext I would like to be able to return TransactWrite<T>. There does not seem to be a public constructor or interface which would be very handy.

### Use Case

Mocking Transactions. First building the TransactWriteItems with AddSaveItem and such. And at last do a mocked ExecuteAsync call. 

### Proposed Solution

Make a public constructor for TransactWrite<T> or an interface to be able to mock it directly. 

### Other Information

I also tried the DbContext.CreateTransactWrite with a mocked DescribeTablesAsync, but internally DescribeTables is used. Which is not in the interface. So I could not create a TransactWrite<T> that way either.

### Acknowledgements

- [X] I may be able to implement this feature request

### AWS .NET SDK and/or Package version used

AWSSDK.DynamoDBv2 3.7.103.20

### Targeted .NET Platform

.NET 6

### Operating System and version

Windows 11,  AmazonLinux

**Comment by ashishdhingra** [comment]
Needs review with the team. Similar feature requests to improve testability are queued.

**Comment by roelvandenbrand** [comment]
> 
I can try to add in the interfaces in a PR specifically for this.

**Comment by roelvandenbrand** [comment]
> Needs review with the team. Similar feature requests to improve testability are queued.

I see there are a few, but priority might be at other issues. It looks like changing stuff to return interfaces would break some implementations. But it will improve testability for a lot of people. Is there anything I could help with?

**Comment by 96malhar** [comment]
Hello, we have been working on the V4 of the AWS SDK for .NET. We have added the ability to mock various DynamoDB operations by adding interfaces in both the Data Model mode and Document Model mode in DynamoDB. 

Refer to this PR - https://github.com/aws/aws-sdk-net/pull/3450

Specifically for the `TransactWrite<T>` class, it now implements the `ITransactWrite<T>` interface which can mocked inside unit tests. 

This feature is available in the AWSSDK.DynamoDBv2 Version [4.0.0-preview.2](https://www.nuget.org/packages/AWSSDK.DynamoDBv2/4.0.0-preview.2)
