### ISSUE TITLE
Support environment variable config for default region and service endpoint

### ISSUE THREAD

**Issue by jonathanfoster** [aws/aws-sdk-net#265]
We should be able to use an environment variable to set the default region and service endpoint. This makes it easier to have the entire AWS config in environment variables instead of mixing application config files and env vars.

**Comment by normj** [comment]
I like the idea of being able to configure the region with environment variables. I added this to our feature request list for tracking and closed the issue.

https://github.com/aws/aws-sdk-net/blob/master/FEATURE_REQUESTS.md
