### ISSUE TITLE
Failed to resolve AmazonDateTimeUnmarshallingException::.ctor when compiling with Xamarin.iOS

### ISSUE THREAD

**Issue by bholmes** [aws/aws-sdk-net#267]
When using AWSSDK.S3 version [3.1.3.2][1] or [3.1.3.3][2] from NuGet in a Xamarin.iOS project there is now a error during compilation.

`MTOUCH: error MT2002: Failed to resolve "System.Void Amazon.Runtime.AmazonDateTimeUnmarshallingException::.ctor(System.String,System.String,System.String,System.String,System.String,System.Exception)" reference from "AWSSDK.Core, Version=3.1.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604"`

I believe this was introduced in this [commit][4] because the [AWSSDK.S3][2] NuGet was updated and not the [AWSSDK.Core][3] NuGet where this new type was introduced.  

[1]: https://www.nuget.org/packages/AWSSDK.S3/3.1.3.2
[2]: https://www.nuget.org/packages/AWSSDK.S3/3.1.3.3
[3]: https://www.nuget.org/packages/AWSSDK.Core/3.1.3.2
[4]: https://github.com/aws/aws-sdk-net/commit/c4ca9a8f1a95e0cbc5f6bb0233326abe5cf18c83

**Comment by gokarnm** [comment]
Thanks for reporting this, yes it's an issue with the S3 and Core versions being not correctly incremented. I'll push a fix for this soon.

**Comment by gokarnm** [comment]
The latest version of the [AWSSDK.S3](https://www.nuget.org/packages/AWSSDK.S3) package, version 3.1.3.4, fixes this issue.
