### ISSUE TITLE
S3FileInfo.Delete throws (403) forbidden but deletes file anyway

### ISSUE THREAD

**Issue by adamveld12** [aws/aws-sdk-net#268]
I'm using AWSSDK.S3 version 3.1.0.0 and when using `S3FileInfo.Delete` I get an {"Access Denied"}	System.Exception {Amazon.S3.AmazonS3Exception} (403) Forbidden *but* when I go to S3 on the management console the object was deleted anyway.

Everything works as expected (deletes object and doesn't exception) when I use `AmazonS3Client.DeleteObject`.

To reproduce:

```C#

    using (var client = new AmazonS3Client("accessKey", "secretKey", RegionEndpoint.USEast1))
    {     
       var key = $"test/ReproduceS3FileInfoDeleteBug.txt";
        var fileInfo = new S3FileInfo(client, "bucket", key);
        using (var txtOut = new StreamWriter(fileInfo.OpenWrite()))
        {
            txtOut.Write("some text");
        }

       try 
       {
           // this fails
           fileInfo.Delete();
       }
       catch
       {
           // if you do fileInfo.Exists here, it will be false
       }
    }
```

The policy
```JSON
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmtxxxxx",
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::bucket/test/*"
            ]
        }
    ]
}
```

I also tried the suggestion in #250 and I still had the same issue.

**Comment by normj** [comment]
The S3 File IO library does more under the covers then just delete in this case. Because it tries simulate a file system it makes sure that if the object being deleted is the the last object with the key prefix of "test/" then create a 0 byte object with just that prefix so it doesn't look like the "Directory" was deleted. I was able to delete the object when I used a policy like this.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmtxxxxx",
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::bucket/test/*"
            ]
        },
        {
            "Sid" : "dc0f067382e24fa2bc5a6f5d4c34f44e",
            "Effect" : "Allow",
            "Action" : "s3:GetBucketLocation",
            "Resource" : "arn:aws:s3:::bucket"
        }
    ]
}
```

This just adds the ability to check which region the bucket is in.

**Comment by adamveld12** [comment]
:+1:  Thanks for the explanation. I dove into the source and now it all makes a lot more sense.
