### ISSUE TITLE
IAmazonRDS is missing method for rds:ModifyDBSnapshotAttribute

### ISSUE THREAD

**Issue by mwhouser** [aws/aws-sdk-net#269]
`Amazon.RDS.IAmazonRDS` is missing a method for `ModifyDBSnapshotAttribute` as per http://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ModifyDBSnapshotAttribute.html

**Comment by normj** [comment]
Thanks for letting us know. I'll track down why the operation is missing.

**Comment by normj** [comment]
We just released version 3.1.3 of the RDS NuGet package that contains this support.

https://www.nuget.org/packages/AWSSDK.RDS/3.1.3
