### ISSUE TITLE
how to use iOT .net sdk

### ISSUE THREAD

**Issue by livesankp** [aws/aws-sdk-net#270]
Hello,

I am looking for SDK documentation for iOT so i can use node.js connection to .NET sdk.
I am trying to achieve connection based solution where each device can have its own independent connection and i can publish and subscribe on connection based.

Lets say i have to two device i want to control using node.js which maintains their independent connection. Is it possible ?

**Comment by PavelSafronov** [comment]
Good question, though I think this question is better suited for the [AWS IoT Forum](https://forums.aws.amazon.com/forum.jspa?forumID=210). It's also possible that someone has asked a similar question before.

**Comment by livesankp** [comment]
I tried there but i am not able to post question there.

**Comment by gokarnm** [comment]
Closing as this issue is more appropriate for the [AWS IoT Forum](https://forums.aws.amazon.com/forum.jspa?forumID=210) . OP has posted this [query](https://forums.aws.amazon.com/thread.jspa?threadID=219448&tstart=0) on the IoT Forum.
