### ISSUE TITLE
DynamoDB object persistence model does not expose ReturnConsumedCapacity nor ExclusiveStartKey

### ISSUE THREAD

**Issue by bradmurray** [aws/aws-sdk-net#271]
If you want to monitor your consumed capacity as part of your queries/scans you have to use the lower-level scans. There should be a way to get this back in a query<tableName> or scan<tableName> call. Same thing with LastEvaluatedKey and ExclusiveStartKey.

**Comment by PavelSafronov** [comment]
You're correct, this information is not exposed right now. We are looking into ways to expose this information, but don't have an estimate of when that work will be finished or how it will be implemented.

For now, one way to monitor the consumed capacity while using the Object Persistence Model is to create a proxy client class to intercept and modify requests, then intercept the responses. Here's a partial implementation of such a class, as well as how it can be used. (Note that I've only shown the implementations of Scan and Describe methods, as these are the minimum of what is required for this example.)

ProxyClient:
```
private class ProxyClient : IAmazonDynamoDB
{
    public AmazonDynamoDBClient Client { get; set; }
    public Action<ConsumedCapacity> ReportConsumedCapacity { get; set; }

    public ScanResponse Scan(ScanRequest request)
    {
        request.ReturnConsumedCapacity = ReturnConsumedCapacity.TOTAL;
        var response = Client.Scan(request);
        ReportConsumedCapacity(response.ConsumedCapacity);
        return response;
    }
    public DescribeTableResponse DescribeTable(DescribeTableRequest request)
    {
        return Client.DescribeTable(request);
    }
}
```

Using ProxyClient:
```
using(var client = new AmazonDynamoDBClient())
{
    var proxyClient = new ProxyClient
    {
        Client = client,
        ReportConsumedCapacity = cc => Console.WriteLine(cc.TableName + " : " + cc.CapacityUnits)
    };
    using(var context = new DynamoDBContext(proxyClient))
    {
        var items = context.Scan<Movie>().ToList();
        Console.WriteLine(items.Count);
    }
}
```

**Comment by PavelSafronov** [comment]
This request has been added to our feature request list for tracking. Closing the issue.

https://github.com/aws/aws-sdk-net/blob/master/FEATURE_REQUESTS.md
