### ISSUE TITLE
SES KMS S3 bucket decryption

### ISSUE THREAD

**Issue by recker76** [aws/aws-sdk-net#272]
(leveraging feature request from js lib)

Recently AWS SES started accepting inbound email, saved in an S3 bucket. There's an option to encrypt the data, which is great, otherwise everything is exposed as plain text in your bucket.

The problems start with only accepting a KMS key for encryption. That means it needs to be managed from the AWS side.

The official documentation says on the subject:

Your mail is encrypted by Amazon SES using the Amazon S3 encryption client before the mail is submitted to Amazon S3 for storage. It is not encrypted using Amazon S3 server-side encryption. This means that you must use the Amazon S3 encryption client to decrypt the email after retrieving it from Amazon S3, as the service has no access to use your AWS KMS keys for decryption. This encryption client is available with the AWS Java SDK and AWS Java Ruby only.
http://docs.aws.amazon.com/ses/latest/DeveloperGuide/receiving-email-action-s3.html

How can we bring that functionality to the .net lib, so we can decrypt and read our messages using c#?

Thanks!!

**Comment by PavelSafronov** [comment]
At the moment, this is not supported. This request has been added to our feature request list for tracking. Closing the issue.

https://github.com/aws/aws-sdk-net/blob/master/FEATURE_REQUESTS.md
