### ISSUE TITLE
SDK Example - signed cloudfront distribution

### ISSUE THREAD

**Issue by craigseymour** [aws/aws-sdk-net#276]
I would recently have found a complete worked example of setting up a CloudFront distribution using signed URLs very helpful, from setting up the S3 bucket, through creating the OAI, the distribution, the policy, uploading an object, to finally creating a time-signed URL.

**Comment by jimfl** [comment]
Did you manage to get your use-case working? If so, would you feel comfortable contributing a sample? We can walk you through the process of how to format sample code for inclusion in the documentation.

**Comment by craigseymour** [comment]
Thanks for following up.   

In the end, what I needed to do became trivial, because the S3 and CloudFront consoles now allow the creation of all the necessary infrastructure, so the code I’ve had to write is just a few lines to generate the signed URL.  

However, the need for a full sample still stands; without the blog post I was following (http://improve.dk/how-to-set-up-and-serve-private-content-using-s3/) I don’t think I’d have been able to figure out all the necessary steps – the documentation (http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/PrivateContent.html is comprehensive, but hard to get into.  Also, whilst I don’t need to programmatically create the distribution (we only need one), I’m sure there are others out there who do need to do so.

**Comment by jimfl** [comment]
Thanks for the feedback. We're working on ways to make more sample code available for more common use cases and keeping it up-to-date.

Also, I have forwarded the feedback to the technical writing team for the developer guide.
