### ISSUE TITLE
ListQueues from AmazonSQSClient never respond.

### ISSUE THREAD

**Issue by raphaelhudvoy** [aws/aws-sdk-net#277]
I created a Window Service that uses SQS queues to communicate. The problem is after deployment, when the service starts, the method ListQueues of the AmazonSQSClient don't respond back (making the service startup crash). However if I retry immediately a second time, it works fine. It is only when there is no deployment for at least 45 minutes that the problem occurs.

**Comment by PavelSafronov** [comment]
Can you post your code? Does the ListQueues call never return, or returns after a long time?

**Comment by raphaelhudvoy** [comment]
Hi, 

I created a simple Topshelf service to reproduce the problem. 
Here is the constructor of the Topshelf service. The first deployment (no deployment for at least 30 minutes) gets stuck after "test 2" . The "test 3" logs is never reached. The service times out before the function returns any value. However if I retry immediately a second time, it works fine.

    public class TestService
    {
        private static readonly Logger log = LogManager.GetCurrentClassLogger();

        public TestService()
        {

            var client = new AmazonSQSClient();
            // List all queues that start with "aws".
            log.Trace("test 1");
            var request = new ListQueuesRequest
            {
                QueueNamePrefix = "dev"

            };

            log.Trace("test 2");
            var response = client.ListQueues(request);
            log.Trace("test 3");
        }

        public void Start()
        {
            log.Trace("start");
        }

        public void Stop()
        {
            log.Trace("stop");
        }

    }

Thanks for you time

**Comment by PavelSafronov** [comment]
I tried the sample service you posted with Topshelf and have not yet encountered the blocking you describe. What version of the .NET SDK are you using and which build? (Version 3 of the .NET SDK has versions for .NET 3.5, 4.5, and PCL.) Also, which region are you running this against?

**Comment by raphaelhudvoy** [comment]
When I run the code on localhost it works fine. It is really occurring during first deployment. 
Versions:
AWSSDK 2.3.52
TOPSHELF 3.2.0
.NET Framework 4.5

**Comment by PavelSafronov** [comment]
How and where are you deploying? Does this issue appear if you use the latest version of the SDK? Here is the the latest SQS package NuGet package: [SQS 3.1.0.4](https://www.nuget.org/packages/AWSSDK.SQS/3.1.0.4).

**Comment by raphaelhudvoy** [comment]
I updated to the new SQS 3.1.0.4 but the problem is still occurring. I dploy using codeDeploy on a EC2 instance that is part of an auto-scaling group in us-east-1 region.

**Comment by PavelSafronov** [comment]
Are you using and IAM Role and an Instance Profile on the EC2 instance to get the credentials?
In the example above, you are using the SDK inside the service constructor. Have you tried making the SDK calls after Start() is invoked?

I'm going to try reproducing your specific error case, but this will take a bit of time.

**Comment by PavelSafronov** [comment]
Can you also provide your CodeDeploy deployment specification?

**Comment by raphaelhudvoy** [comment]
There was an error that I missed during compilation when I updated to SQS 3.1.0.4. I fixed it and now it works! You made my day. Thanks you for your help and support.

**Comment by PavelSafronov** [comment]
Happy to hear you've resolved this. :) Closing issue.

**Comment by raphaelhudvoy** [comment]
Actually it was the move to the Start() function that fixed the problem, not the update! Thanks

**Comment by thomasrosted** [comment]
@PavelSafronov We experience the exact same thing. Any idea why moving it to Start() will prevent the problem where first start within 30 min. will get stuck on that line?
