### ISSUE TITLE
Upload and Download at the same for large file

### ISSUE THREAD

**Issue by veereshi** [aws/aws-sdk-net#278]
I am looking solution  for download large file during upload 
for example i have started uploading from one user(100 GB file) it takes an hour at the same other user need to start download the file  at other end without waiting to complete upload process

**Comment by jimfl** [comment]
There is no pre-built solution for this use case. 

How you approach this problem depends on your use case. Are you thinking of single uploader and a single downloader, or a single upload with multiple downloaders?

[Amazon Kinesis][3] was designed to stream data and have multiple consumers of the data, bit it far more complex than simple file transfers.

You might also try asking your question on [StackOverflow][1] or the [AWS Forums][2] to see if other people have had the same issue.

[1]: http://stackoverflow.com
[2]: https://forums.aws.amazon.com/index.jspa
[3]: https://aws.amazon.com/kinesis/
