### ISSUE TITLE
Uploading CloudSearch documents using the .NET SDK

### ISSUE THREAD

**Issue by adaam2** [aws/aws-sdk-net#279]
I had previously used the 2011 version of the CloudSearch API, but now I've created some new domains running on the 2013-01-01 CloudSearch engine. I want to be able to use the CloudSearch .NET package available on NuGet (v3) to upload batches of JSON to our new CloudSearch domain

I can't seem to see anything in the method list relating to uploading documents. I can list out the domains and index documents (across all of the domains on our AWS account presumably) but I can't seem to find any method in the SDK that will do the uploading of new data. We previously uploaded documents using the CLI but I can't believe that this feature is missing from the v3 version of the API? I would really like to be able to do this programatically without launching up a process to run the CLI.

**Comment by PavelSafronov** [comment]
You are looking for the [CloudSearch Domain package](https://www.nuget.org/packages/AWSSDK.CloudSearchDomain/). The CloudSearch API is used to work with domains, while the CloudSearch Domain API is used for working with documents.

**Comment by adaam2** [comment]
Hi @PavelSafronov 

Thank you! I was tired.

Closing

**Comment by azizj1** [comment]
Are there any docs on the CloudSearch Domain package?

**Comment by PavelSafronov** [comment]
What docs are you looking for? Both CloudSearch and CloudSearch Domain services are documented in the same Developer Guide, [here](http://docs.aws.amazon.com/cloudsearch/latest/developerguide/what-is-cloudsearch.html).

**Comment by azizj1** [comment]
I was looking for [http://docs.aws.amazon.com/sdkfornet/v3/apidocs/Index.html](this), which I found through your link. Thanks!
