### ISSUE TITLE
AsyncRunner overwriting exception stack trace when throwing

### ISSUE THREAD

**Issue by cilliemalan** [aws/aws-sdk-net#281]
See [AsyncRunner.cs:68](https://github.com/aws/aws-sdk-net/blob/f5c9bce1d6303036718e1b0ad09fe481dd1b52c9/sdk/src/Core/Amazon.Runtime/Internal/_async/AsyncRunner.cs#L68)

This code makes exceptions thrown from async methods seem like they originated from AsyncRunner.cs:68.

Perhaps rather do this:
```C#
ExceptionDispatchInfo.Capture(exception).Throw();
```
(see http://stackoverflow.com/a/33994871/562229)

**Comment by normj** [comment]
Thanks for tip. I updated the code. I'll update the issue when it is released.

**Comment by normj** [comment]
Version 3.1.4.1 of the AWSSDK.Core package was pushed to NuGet which contains this change.
