### ISSUE TITLE
Support for CloudFormation Templates With SSM Documents

### ISSUE THREAD

**Issue by AlWilliamson** [aws/aws-sdk-net#283]
The CloudFormation Template parser in Visual Studio is not aware of AWS::SSM::Document resources. It highlights the object with red underlining and when you hover over the Type statement the following is displayed: "Type key is invalid for this object "

This was a recent addition, so other resources like KMS are likely also missing. Please see this posting for a list: 
https://aws.amazon.com/about-aws/whats-new/2015/12/aws-cloudformation-adds-support-for-aws-codepipeline-aws-config-and-more/

**Comment by normj** [comment]
Thanks for pointing that out. I'll get the schema updated.

**Comment by normj** [comment]
The CloudFormation schema has been updated. You should see the changes the next time you restart Visual Studio.

**Comment by AlWilliamson** [comment]
I restarted Visual Studio, and indeed the Type no longer has an issue, however the rest of the SSM document schema may need to be updated as well. 

![image](https://cloud.githubusercontent.com/assets/12662114/11673609/1fbf3c0e-9dcf-11e5-9abf-64f8e3421737.png)

**Comment by normj** [comment]
Sorry about that, restart Visual Studio and you should see that fixed. Note, for the actual SSM document we only validate that it is valid json.
