### ISSUE TITLE
Stop touching the web.config and app.config files when you install nuget packages

### ISSUE THREAD

**Issue by superlogical** [aws/aws-sdk-net#284]
I think this is the code that does it https://github.com/aws/aws-sdk-net/blob/master/sdk%2Fnuget-content%2Finstall.ps1#L144

Can get annoying when this accidentally get's checked into source control.

~~~~~~~~~
<!--AWSProfileName is used to reference an account that has been registered with the SDK.
If using AWS Toolkit for Visual Studio then this value is the same value shown in the AWS Explorer.
It is also possible to register an account using the <solution-dir>/packages/AWSSDK-X.X.X.X/tools/account-management.ps1 PowerShell script
that is bundled with the nuget package under the tools folder.

		<add key="AWSProfileName" value="" />
-->
~~~~~~~~~

**Comment by gokarnm** [comment]
Thanks for the feedback! This is primarily meant to direct new users to use profiles, as it's one of the preferred mechanisms to refer AWS credentials. I will get back to you on how we can address your feedback.

The script will not add the app setting key if "AWSProfileName" is already defined in app.config. How are you referring credentials in your application?

**Comment by gokarnm** [comment]
We stopped updating the app.config from SDK version [3.1.31](https://github.com/aws/aws-sdk-net/blob/master/SDK.CHANGELOG.md#31310-2015-12-01-2316-utc) onwards when we introduced Roslyn code analyzers. We now run the install script present [here](https://github.com/aws/aws-sdk-net/blob/master/sdk/code-analysis/NuGetInstallScripts/install.ps1) which does not modify the app/web.config.
