### ISSUE TITLE
AmazonDynamoDBConfig.MaxErrorRetry can't be set after creating client

### ISSUE THREAD

**Issue by WalkerCodeRanger** [aws/aws-sdk-net#285]
If you try to create an `AmazonDynamoDBClient` and set the `MaxErrorRetry` with:

    var client = new AmazonDynamoDBClient(new EnvironmentAWSCredentials(), RegionEndpoint.GetBySystemName("us-east-1"));
    client.Config.MaxErrorRetry = 1000;

Then the retry setting doesn't take effect.  You can confirm this with the debugger by looking in the `client.RuntimePipeline.Handlers` at the `retryHandler.RetryPolicy.MaxRetries`.

On the other hand, if you construct a client with a config that has `MaxErrorRetry` set like:

    var config = new AmazonDynamoDBConfig()
    {
    	MaxErrorRetry = 1000,
    	RegionEndpoint = RegionEndpoint.GetBySystemName("us-east-1"),
    };
    var client = new AmazonDynamoDBClient(new EnvironmentAWSCredentials(), config);

It will work.

I would expect either this would work, or the `client.Config` type would not expose setters if setting the property will have no effect.

**Comment by normj** [comment]
Exposing the Config property off of the service client was a mistake in version 3. In previous versions of the SDK the property was internal. Most likely it was made public so the service clients, now in separate packages, would be able to access it and we meant to go back to find a better solution but forgot.

To avoid threading issues we don't want users changing values on the config object which could cause unexpected behavior in a threaded environment. I'm going to deprecate the property to avoid users having this confusion in the future. Config values need to be set during the construction of the client.

**Comment by WalkerCodeRanger** [comment]
One way to address that would be to create an interface that `AmazonDynamoDBConfig` implements that is read only (exposes only the getters).  Then you could change the `client.Config` property to expose the config through that interface.

**Comment by normj** [comment]
That is pretty much the solution I'm working on now.

**Comment by normj** [comment]
This property was changed into a readonly property in the 3.2 line of the SDK which is in the dnxcore-development branch.

https://github.com/aws/aws-sdk-net/commit/543f90d65196996bef9a8eea88d6d8815dc03304
