### ISSUE TITLE
High value of AmazonDynamoDBConfig.MaxErrorRetry causes exception

### ISSUE THREAD

**Issue by WalkerCodeRanger** [aws/aws-sdk-net#286]
I have correctly set AmazonDynamoDBConfig.MaxErrorRetry per #285  to 1000.  I am using such a high value because this is a migration tool that we want to pretty much never fail, but just wait until there is enough capacity.  I get the folllowing exception (stack trace shorted to only relavant portion):

	Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Exception: Batch Write Failed: Number must be either non-negative and less than or equal to Int32.MaxValue or -1.
	Parameter name: millisecondsTimeout ---> System.ArgumentOutOfRangeException: Number must be either non-negative and less than or equal to Int32.MaxValue or -1.
	Parameter name: millisecondsTimeout
	   at System.Threading.Thread.SleepInternal(Int32 millisecondsTimeout)
	   at System.Threading.Thread.Sleep(Int32 millisecondsTimeout)
	   at Amazon.DynamoDBv2.Internal.DynamoDBRetryPolicy.pauseExponentially(Int32 retries) in d:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\Internal\DynamoDBRetryPolicy.cs:line 58
	   at Amazon.DynamoDBv2.Internal.DynamoDBRetryPolicy.WaitBeforeRetry(IExecutionContext executionContext) in d:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\Internal\DynamoDBRetryPolicy.cs:line 47

You can see there appears to be a bug in the `DynamoDBRetryPolicy.pauseExponentially` method.  The problem seems to be in the line `int delay = (retries == 0) ? 0 : 50 * (int)Math.Pow(2, retries - 1);`  I believe that `Math.Pow(2, retries - 1)` is overflowing the range of `int` causing it to go negative which causes the later line `Amazon.Util.AWSSDKUtils.Sleep(delay);` to try to sleep for a negative number of milliseconds.

**Comment by PavelSafronov** [comment]
We've released an updated version of DynamoDB and Core which resolves this issue.
For your case, simply upgrading the DynamoDB package is enough. If you are using a different service and need this same functionality, you'll need to update Core to the latest version.

**Comment by WalkerCodeRanger** [comment]
Looking at the new version of [`pauseExponentially()`](https://github.com/aws/aws-sdk-net/blob/b4ffd68533d82f4d89ea459bcc71c4442c708e7c/sdk/src/Services/DynamoDBv2/Custom/Internal/DynamoDBRetryPolicy.cs) it looked like there could still be overflow issues.  I wrote a unit test and sure enough, if you set `MaxBackoffInMilliseconds = int.MaxValue`, then on retry 29 your code would pause for 536,870,912 ms when it should pause for 2,147,483,647 ms (int max).

Here is some unit tested code I am using to compute the correct delay time.  It uses bit shifting which will be much faster than `Math.Pow` and will also return zero on negative retries,

	public int PauseTime(int retries)
	{
		if(retries <= 0) return 0;
		retries--;
		// A signed int has 31 bits we can shift in, but we need 6 bits of space to multiply by 50
		if(retries > 31 - 6) return MaxBackoffInMilliseconds;
		var milliseconds = 50 * (1 << retries);
		return Math.Min(milliseconds, MaxBackoffInMilliseconds);
	}
