### ISSUE TITLE
why the package name of DynamoDB is 'DynamoDBv2'? not DynamoDBv3 or DynamoDB?

### ISSUE THREAD

**Issue by doodoori2** [aws/aws-sdk-net#289]
hello,

I'm using AWSSDK.DynamoDBv2 (3.1.1.3) with AWSSDK.Core (3.1.4.2)

I am confused with to understanding package name of DynamoDB. 

is there any reason to postfix with V2 ?

**Comment by normj** [comment]
A couple years back the DynamoDB service made significant breaking changes to their API. To avoid breaking users at the time me put the new service API under the v2 postfix so customers can opt into the new API. For version 3 of the AWS SDK we did not carry forward the old original API of DynamoDB but we didn't remove the v2 postfix to avoid breaking anybody moving from version 2 of the SDK to version 3.

**Comment by doodoori2** [comment]
Thanks for quick reply! :+1:
