### ISSUE TITLE
Endpoint definition in new json format and UseHttp

### ISSUE THREAD

**Issue by vitezslav-popovsky-solarwinds** [aws/aws-sdk-net#291]
Hello,

I am just trying to upgrade the testing environment to the new AWSSDK version. We used custom region endpoint defined as:

```xml
<Endpoint>
  <ServiceName>monitoring</ServiceName>
  <Http>true</Http>
  <Https>false</Https>
  <Hostname>localhost/Aws</Hostname>
</Endpoint>
```

I can see that `ClientConfig.GetUrl` method used this parameters in following way:
```csharp
internal static string GetUrl(RegionEndpoint regionEndpoint, string regionEndpointServiceName, bool useHttp)
{
    var endpoint = regionEndpoint.GetEndpointForService(regionEndpointServiceName);
    bool shouldUseHttp;
    if (endpoint.HTTP && endpoint.HTTPS)    // if both are supported, go with user preference
        shouldUseHttp = useHttp;
    else if (endpoint.HTTPS)                // if HTTPS is supported, go with HTTPS
        shouldUseHttp = false;
    else                                    // if HTTP is supported, go with HTTP
        shouldUseHttp = true;

    string url = new Uri(string.Format(CultureInfo.InvariantCulture, "{0}{1}", shouldUseHttp ? "http://" : "https://", endpoint.Hostname)).AbsoluteUri;
    return url;
}
```

Is there any possibility how to force new AWSSDK to http protocol for custom region using only configuration files? I know that there is a possibility to set `client.Config.UseHttp = true;` in runtime but this is no option in my case. New json configuration obviously does not have these `http` and `https` properties.

**Comment by normj** [comment]
Currently there is no way to do this through configuration. The AWS SDKs are in the process of moving to a new endpoint definition format that does specify the protocol. The Java SDK just recently switched over and you can see the example of the definition format here

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/resources/com/amazonaws/partitions/endpoints.json

We haven't scheduled the work yet for the .Net SDK to switch to it, but this will be the direction the .Net SDK takes.
