### ISSUE TITLE
Encrypted Upload from AWS S3 in .NET Portable for Windows Universal 

### ISSUE THREAD

**Issue by karolys** [aws/aws-sdk-net#292]
Just curious if there has been any changes in official support for this? I'm am writing a Universal Windows App and I would like to use AWS S3 to upload encrypted files but as of August 2015 the S3.Encryption library was unavailable in the .NET Portable version of S3. 

Is there any way I could accomplish this?

**Comment by gokarnm** [comment]
The PCL (portable class library) version of the SDK currently does not support AmazonS3EncryptionClient. It will take some investigation to check if this can be supported on PCL. I'll mark this as a feature request.
