### ISSUE TITLE
Replace System.Security.Cryptography.Hashing and System.Security.Cryptography.Hashing.Algorithms with System.Security.Cryptography.Algorithms in .NET Core version

### ISSUE THREAD

**Issue by davidedwardjohnson** [aws/aws-sdk-net#293]
Hello, I was recreating a microservice that uses the AWS-SDK-NET in asp.net 5 (rc1) using the latest beta version 3.2.1-beta and was running into the following issue when building

```Error	CS0433	The type 'RandomNumberGenerator' exists in both 'System.Security.Cryptography.Algorithms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Security.Cryptography.RandomNumberGenerator, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'	MedEngine.Services.Clients5.Core.DNX Core 5.0```

I am referencing System.Security.Cryptography.Algorithms version 4.0.0-beta-23516 as I am using Rfc2898DerviveBytes in one of my classes.

After some investigation I believe the build error is being caused by the AWSSDK.Core.Dnx project referencing 

```"System.Security.Cryptography.Hashing": "4.0.0-beta-23225",
        "System.Security.Cryptography.Hashing.Algorithms": "4.0.0-beta-23225",```

It appears that RandomNumberGenerator appears in the same namespace in those assemblies and S.S.C.A.

According to https://github.com/dotnet/corefx/issues/2882 S.S.C.H and S.S.C.H.A are now obsolete and S.S.C.A should be used instead.  

I think that changing AWSSDK.Core.DNX to using S.S.C.A should resolve this problem?

**Comment by steveataws** [comment]
Thanks for the info; we'll take a look for future releases.

**Comment by normj** [comment]
I pushed out version 3.2.2-beta that updates the references to S.S.C.A. Thanks for pointing out the the switch to the new packages!
