### ISSUE TITLE
Long paths cause TransferUtility.Upload to throw ArgumentException

### ISSUE THREAD

**Issue by jweyrich** [aws/aws-sdk-net#294]
The exception message is `The file indicated by the FilePath property does not exist!`.

A quick inspection revealed it's caused by a validation in [TransferUtility.cs#L372 ](https://github.com/aws/aws-sdk-net/blob/f5c9bce1d6303036718e1b0ad09fe481dd1b52c9/sdk/src/Services/S3/Custom/Transfer/TransferUtility.cs#L372) that fails because it uses `FileInfo`, which expressly does not support long paths (those longer than `MAX_PATH`).

I'm not sure whether this is a regression or if it was never supported - didn't go thru all the history to check.

**Comment by PavelSafronov** [comment]
It appears that long paths were never supported. This is an issue with FileInfo, so I'm not sure if/when there would be a fix or a workaround available.

**Comment by jweyrich** [comment]
Hmm, I suspected that. I'd suggest a fix using native APIs like `CreateFile` (and unicode counterparts), which support long paths (disregarding portability for the sake of argument). Fixing this way may require an extensive effort, but someone already worked our all (or most) details in the past - see [ZetaLongPaths](https://github.com/UweKeim/ZetaLongPaths) - it has almost drop-in replacements for `FileInfo` and `DirectoryInfo` without such restriction.

**Comment by jweyrich** [comment]
If it's worth anything, leaving PCL out, a (very) quick impact check on the S3/Custom/ code reveals the following:

- Model/_bcl/PutObjectRequest.bcl.cs: Uses `System.IO.FileStream` and `System.IO.Path`;
- Model/_bcl/UploadPartRequest.bcl.cs: Uses `System.IO.FileStream` and `System.IO.Path`;
- Model/_bcl45/GetObjectResponse.cs: Uses `System.IO.FileStream`, `System.IO.FileInfo` and `System.IO.File (for Exists)`;
- Model/GetObjectResponse.cs: Uses `System.IO.FileStream`, `System.IO.File` (for Exists) and `System.IO.FileInfo`;
- Transfer/_bcl35/TransferUtility.bcl35.cs: Uses `System.IO.File` (for Exists);
- Transfer/Internal/_async/DownloadCommand.async.cs: Uses `System.IO.FileStream` and `System.IO.File` (for Exists);
- Transfer/Internal/_bcl/DownloadDirectoryCommand.bcl.cs: Uses `System.IO.File` (for Exists);
- Transfer/Internal/_bcl35/DownloadCommand.bcl35.cs: Uses `System.IO.FileStream` and `System.IO.File` (for Exists);
- Transfer/Internal/_bcl35/UploadDirectoryCommand.bcl35.cs: Uses `System.IO.Directory` (for GetFiles) and `System.IO.FileInfo`;
- Transfer/Internal/_bcl45/UploadDirectoryCommand.async.bcl45.cs: : Uses `System.IO.Directory` (for GetFiles) and `System.IO.FileInfo` (to retrieve the file length);
- Transfer/Internal/DownloadCommand.cs: Uses `System.IO.File` (for Exists) and `System.IO.FileInfo`;
- Transfer/TransferUtility.cs: Uses `System.IO.File` (for Exists);
- Transfer/TransferUtilityUploadRequest.cs: Uses `System.IO.FileInfo` (haven't checked but seems to use only the file length);
- Util/_bcl/AmazonS3Util.Operations.cs: Uses `System.IO.File` (for OpenRead);

I believe the only thing ZetaLongPaths doesn't cover is the `FileStream`.

**Comment by PavelSafronov** [comment]
I agree that the path limit is frustrating. Given the complexity of all the platforms the .NET SDK is supported on and the amount of effort it would take to implement this change, it is not high on our priority list. If other developers disagree and feel this is higher priority than other feature work for the SDK, then please +1 this issue.

**Comment by jweyrich** [comment]
Looks like .NET >= 4.6.2 on Windows 10 supports long paths natively, but it is not enabled by default. You need to change a local group policy - https://blogs.msdn.microsoft.com/jeremykuhne/2016/07/30/net-4-6-2-and-long-paths-on-windows-10/ - Anyway, it's good to see the direction .NET is taking.
