### ISSUE TITLE
Converge AWS environment variable expectations with other AWS SDKs and CLIs?

### ISSUE THREAD

**Issue by petemounce** [aws/aws-sdk-net#295]
The .NET SDK looks up the AWS secret access key from the `AWS_SECRET_KEY` environment variable ([docs ref](http://docs.aws.amazon.com/AWSSdkDocsNET/latest/V3/DeveloperGuide/net-dg-config-creds.html)). This is inconsistent with the way the other AWS client tools do it:
* [node SDK (which is always referenced in docs with the `AWS` prefix](https://github.com/aws/aws-sdk-js/blob/master/lib/credentials/environment_credentials.js#L67)
* [AWS CLI (so presumably python SDK too)](http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-environment)
* [go SDK (tries both)](https://github.com/aws/aws-sdk-go/blob/master/aws/credentials/env_provider.go#L28-L29)

It would be nice to converge, since then there are fewer cross platform gotchas. At JUST EAT, we work across .NET, node, ruby, the CLI, and powershell.

**Comment by steveataws** [comment]
Good idea, we'll do a survey of all the SDKs and tools and take a look.

**Comment by steveataws** [comment]
3.1.73.0, released 5/26, now supports the same environment variables as the other SDKs. Resolving.

**Comment by petemounce** [comment]
Excellent; thanks.
