### ISSUE TITLE
Make exception types defined in the SDK serializable

### ISSUE THREAD

**Issue by eiriktsarpalis** [aws/aws-sdk-net#296]
.NET exceptions are expected to be serializable objects, which is why the `System.Exception` base class implements the `ISerializable` interface. Earlier today I noticed that the exception types defined in the AWS SDK are not serializable, on account of their implementations omitting the required `ISerializable` boilerplate for this to be possible. In my application, I want to be able to send any errors (SDK exceptions included) to a remote host.

To give an example of what is required, here's a [commit](https://github.com/eiriktsarpalis/aws-sdk-net/commit/ea2728588d78ef041795250a2bbc913de3b65ded) that adds the required boilerplate to `AmazonServiceException`. I can provide a PR that expands this to all the exception type definitions if you want.

**Comment by steveataws** [comment]
Hi,

This was an oversight; we'd be happy to accept a PR if you want, or we'll just schedule the work to add serializable support into an upcoming sprint.

**Comment by eiriktsarpalis** [comment]
I actually started working on this, but was overwhelmed by the sheer number of exception types that the SDK is defining. Since I'm not all too familiar with the source, I think I'd rather leave this to you guys.

**Comment by PavelSafronov** [comment]
This request has been added to our feature request list for tracking. Closing the issue.

https://github.com/aws/aws-sdk-net/blob/master/FEATURE_REQUESTS.md
