### ISSUE TITLE
Couldnt build the Core.PCL

### ISSUE THREAD

**Issue by Foroughi** [aws/aws-sdk-net#297]
Hi , I just got the sources , but I could build the it. After some checks , I found out that there some unsolved references in Code.PCL project.and here is the list of those  : 

PCLCrypto
PCLStorage
System.Net.Http
System.Net.Http.Primitives
Sytem.Net.Http.Extensions

So any Idea about these missing references ?

**Comment by steveataws** [comment]
Thanks for letting us know; I'll get one of the devs to look into it and see if we've missed something.

**Comment by PavelSafronov** [comment]
This is intentional. You need to run a NuGet restore to pick up these packages.

**Comment by Foroughi** [comment]
Nice hint , thanks for your help . problem has been solved.
