### ISSUE TITLE
Unexpected behaviour when picking up credentials

### ISSUE THREAD

**Issue by emilmuller** [aws/aws-sdk-net#2980]
### Describe the bug

When you do this:

`services.AddDefaultAWSOptions(configuration.GetAWSOptions());`

And you have this in your appsettings file:

```
"AWS": {
  "Profile": "my_profile"
}
```

You expect it to look up credentials in .aws\credentials under 'my_profile'. However, that is not what it does. It *only* looks up 'default' in that file, and settles on that. This is highly unexpected behaviour and leads to https://github.com/aws/aws-sdk-net/issues/499 and numerous of frustrated posts on stackoverflow.

Strictly speaking, it follows the behaviour described on https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/creds-assign.html, but it is highly unexpected, and should be changed. Many do not have 'default' credentials, and if they do, might end up using unintended credentials.

Kind regards, Emil

### AWS .NET SDK and/or Package version used

<PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.7.7" />

### Targeted .NET Platform

.NET 7

### Operating System and version

Windows

**Comment by emilmuller** [comment]
Hi!

I can see that the Profile property is set, so that's not the problem. The problem is that it is only reading 'default' from the credentials file. I don't need to set the ProfilesLocation. It is reading the correct path (it is reading [default] from the correct file). Not using IIS.

Steps to reproduce:

1. Add [default] and [my_profile] to credentials file in user directory with access keys.
2. Set "Profile": "my_profile"
3. Run the application and observe that it uses the [default] credentials and not [my_profile] credentials.

Kind regards, Emil

**Comment by ashishdhingra** [comment]
> "AWS": {
>   "Profile": "my_profile"
> }

@emilmuller Good afternoon. I'm unsure what your setup looks like, however, I'm unable to reproduce the issue. For reproduction, I used the below steps:
- Added the below test profile in `credentials` file (in addition to `default` profile.
```INI
[default]
aws_access_key_id = ASIA3MBXXXX
aws_secret_access_key = mVXXXX

[testprofile]
aws_access_key_id=testaccesskey
aws_secret_access_key=testsecretkey
```
- Created a new ASP.NET Core Web Application (.NET 7).
- Added the NuGet package references for `AWSSDK.Extensions.NETCore.Setup` and `AWSSDK.S3`, using the latest versions. Here's how the `.csproj` file looks like:
```XML
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.7.7" />
    <PackageReference Include="AWSSDK.S3" Version="3.7.106" />
  </ItemGroup>

</Project>
```
- Added the `AWS` key in `appsettings.json`:
```JSON
{
  "AWS": {
    "Profile": "testprofile"
  },
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*"
}
```
- Added the following in `Program.cs`:
```C#
builder.Services.AddDefaultAWSOptions(builder.Configuration.GetAWSOptions());
builder.Services.AddAWSService<IAmazonS3>();
```
- In Index.cshtml.cs, added dependency on `IAmazonS3` in constructor.
```CSHTML
using Amazon.S3;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TestNet7WebApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        IAmazonS3 S3Client { get; set; }

        public IndexModel(ILogger<IndexModel> logger, IAmazonS3 s3Client)
        {
            _logger = logger;
            this.S3Client = s3Client;
        }

        public void OnGet()
        {

        }
    }
}
```
- Setup breakpoint in `Index.cshtml.cs` and debug the application in VS 2022. When the breakpoint is hit, inspect the `Credentials` property of `AmazonS3Client` object.

**RESULT:**
`AmazonS3Client` is using the the credentials setup in `testprofile` in user's `credentials` file as shown below:
![Screenshot 2023-06-20 at 3 05 53 PM](https://github.com/aws/aws-sdk-net/assets/67916761/d9166636-bdb1-4025-971e-195983820733)
