### ISSUE TITLE
Issue in Uploading and Downloading files to S3 bucket after upgrading the AWS.SDK.S3 reference to version

### ISSUE THREAD

**Issue by shu3112** [aws/aws-sdk-net#2984]
### Describe the bug

Issue in Uploading and Downloading files to S3 bucket after upgrading the AWS.SDK.S3 version to 3.7.104.13.  We have dotnet application where we have written code to upload/download file from Bucket. For every upload we create a folder under the root Bucket with Name as current timestamp. E.g. "2023-06-22 19:24:44.1706" i.e. with space in it. 
When we had referenced the older version of AWSSDK,S3 there was no issue in it but with new version of 3.7.104.13, we get the issue as below:

"message": "The request signature we calculated does not match the signature you provided. Check your key and signing method."
"errorCode": "SignatureDoesNotMatch"

### Expected Behavior

File should be uploaded or downloaded through the code even if the bucket name has space in it.

### Current Behavior

If the Bucket has space in the name, we get signature issue in uploading/downloading the file.

### Reproduction Steps

Bucket Name(with full hierarchy) with any space in it is causing the issue.

### AWS .NET SDK and/or Package version used

AWSSDK.S3"3.7.104.13

### Targeted .NET Platform

.NET Core 3.1

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment]
@shu3112 Good morning. Thanks for reporting the issue. Kindly confirm if you are using folder hierarchy (S3 doesn't have concept of folders) in the `BucketName`. if yes, please refer to https://github.com/aws/aws-sdk-net/issues/2622#issuecomment-1581208688. It was never intended to pass in a key prefix as part of the BucketName property and that working in the past was an accidental side affect.

Thanks,
Ashish
