### ISSUE TITLE
Unable to Scan with Multiple Conditions

### ISSUE THREAD

**Issue by jbtamaresgit** [aws/aws-sdk-net#2987]
### Describe the bug

Hi, 

I was unable to scan objects with multiple conditions using `ScanAsync` below is the code snippet: 
```
if(DynamoDBContext != null)
{
     List<ScanCondition> scanConditions = new List<ScanCondition>
     {
           new ScanCondition("SortKey", ScanOperator.Equal, "sk1"),
           new ScanCondition("TestBool", ScanOperator.Equal, new DynamoDBBool(true))
      };
     return await DynamoDBContext.ScanAsync<T>(scanConditions).GetRemainingAsync();
}
```
And below I have these in my table: 
![image](https://github.com/aws/aws-sdk-net/assets/44351076/524461c1-c2b2-4c9a-b887-ac7403bd9f37)

Below is the result of the debug:
![image](https://github.com/aws/aws-sdk-net/assets/44351076/cd337e2e-e996-465b-9951-813a976c225c)

Removing one of the conditions will give me results:
![image](https://github.com/aws/aws-sdk-net/assets/44351076/a42ae351-7ba8-46d4-afff-f32b871843ac)

### Expected Behavior

Return based on the scan conditions

### Current Behavior

Did not return

### Reproduction Steps

Add multiple conditions on scan conditions list

### AWS .NET SDK and/or Package version used

AWSSDK.AmazonDynamoDBv2 3.7.103.21

### Targeted .NET Platform

.NET 7

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment]
Hi @jbtamaresgit,

Good morning.

Thanks for reporting the issue.

Unfortunately, I'm unable to reproduce the issue. For Object Persistence model, you would need to use convertor to convert between `bool` and `DynamoDBBool` types, and also need to set `DynamoDBContextConfig.Conversion` for `DynamoDBContext` to `DynamoDBEntryConversion.V2`. I suspect there might be an issue with your convertor where it might only be handling `bool` data, not if the user passes `DynamoDBBool` in `ScanCondition`. For the example table schema shared by you, the below code works fine (2 results are returned; where I created 3 items with one of them having `TestBool` value as `false`):
```C#
using System;
using System.Collections.Generic;
using Amazon.DynamoDBv2;
using Amazon.DynamoDBv2.DataModel;
using Amazon.DynamoDBv2.DocumentModel;
using Amazon.Runtime;

using (AmazonDynamoDBClient client = new AmazonDynamoDBClient())
{
    DynamoDBContext context = new DynamoDBContext(client, new DynamoDBContextConfig() { Conversion = DynamoDBEntryConversion.V2 });

    if (context != null)
    {
        List<ScanCondition> scanConditions = new List<ScanCondition>
        {
           new ScanCondition("SortKey", ScanOperator.Equal, "sk1"),
           new ScanCondition("TestBool", ScanOperator.Equal, new DynamoDBBool(true))
        };
        var scanResponse = await context.ScanAsync<TestTable>(scanConditions).GetRemainingAsync();
    }
}

[DynamoDBTable("TestTable")]
public class TestTable
{
    [DynamoDBHashKey]
    public string Id { get; set; }

    [DynamoDBRangeKey]
    public string SortKey { get; set; }

    [DynamoDBProperty("TestBool", typeof(DynamoDBNativeBooleanConverter))]
    public bool TestBool { get; set; }
}

public class DynamoDBNativeBooleanConverter : IPropertyConverter
{
    public DynamoDBEntry ToEntry(object value)
    {
        DynamoDBEntry entry = DynamoDBNull.Null;

        if (value != null)
        {
            if (value is DynamoDBBool)
            {
                entry = (DynamoDBBool) value;
            }
            else
            {
                entry = new DynamoDBBool(bool.TryParse(value?.ToString(), out var val) && val);
            }
        }

        return entry;
    }

    public object FromEntry(DynamoDBEntry entry)
    {
        return entry.AsDynamoDBBool().Value;
    }
}
```

Thanks,
Ashish

**Comment by jbtamaresgit** [comment]
Hi @ashishdhingra ,
I do not have the conversion set `DynamoDBContextConfig.Conversion` for `DynamoDbContext` but I do have the property converter 
```
public class DynamoDBNativeBooleanConverter : IPropertyConverter
{
        public DynamoDBEntry ToEntry(object value) => new DynamoDBBool(bool.TryParse(value?.ToString(), out var val) && val);
        public object FromEntry(DynamoDBEntry entry) => entry.AsDynamoDBBool().Value;
}
```
And that should not be a problem since I can comment out the `SortKey` `Condition` and leave the `TestBool` and it will return those with `TestBool` as `True` but never did when adding both of the `ScanCondition`. 

Does the conversion for the `DynamoDbContext` needed to be added in order for multiple `ScanConditions` to work?

**Comment by ashishdhingra** [comment]
> Hi @ashishdhingra ,
I do not have the conversion set DynamoDBContextConfig.Conversion for DynamoDbContext but I do have the property converter
>
> public class DynamoDBNativeBooleanConverter : IPropertyConverter
> {
>        public DynamoDBEntry ToEntry(object value) => new DynamoDBBool(bool.TryParse(value?.ToString(), out var val) && val);
>        public object FromEntry(DynamoDBEntry entry) => entry.AsDynamoDBBool().Value;
}
>And that should not be a problem since I can comment out the SortKey Condition and leave the TestBool and it will return those with TestBool as True but never did when adding both of the ScanCondition.

@jbtamaresgit Good morning. I was also using the same converter as you, but since you are using ` ScanCondition("TestBool", ScanOperator.Equal, new DynamoDBBool(true))`, the property converter's `ToEntry` will fail since it is trying to use `bool.TryParse()` on `DynamoDBBool` object. Please modify your converter to the logic shared in https://github.com/aws/aws-sdk-net/issues/2987#issuecomment-1613814193. Also make sure to decorate `TestBool` property with `[DynamoDBProperty("TestBool", typeof(DynamoDBNativeBooleanConverter))]` attribute. The code shared in https://github.com/aws/aws-sdk-net/issues/2987#issuecomment-1613814193 works perfectly fine at my end.

Thanks,
Ashish

**Comment by jbtamaresgit** [comment]
Hi @ashishdhingra ,
I reworked our tables so I am using `QueryAsync` to query objects with a single `ScanCondition` and it works great, so I guess I am not going to dabble around the `ScanAsync`. Thanks for your help.
