### ISSUE TITLE
EventBridge Scheduler Client fails to CreateSchedule with a FIFO SQS Target and a FIFO SQS Dead Letter Queue

### ISSUE THREAD

**Issue by maxmoore14** [aws/aws-sdk-net#2999]
### Describe the bug

When attempting to create a Schedule with a FIFO SQS Target & DLQ, the response is:

System.AggregateException: 'One or more errors occurred. (1 validation error detected: Value 'arn:aws:sqs:us-east-1:999999999999:TestDLQ.fifo' at 'target.deadLetterConfig.arn' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:aws(-[a-z]+)?:sqs:[a-z0-9\-]+:\d{12}:[a-zA-Z0-9\-_]+)'

Notice the regex does not allow for the .fifo suffix.

### Expected Behavior

A FIFO target should allow for a FIFO DLQ and the Schedule should create successfully.

### Current Behavior

System.AggregateException: 'One or more errors occurred. (1 validation error detected: Value 'arn:aws:sqs:us-east-1:999999999999:TestDLQ.fifo' at 'target.deadLetterConfig.arn' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:aws(-[a-z]+)?:sqs:[a-z0-9\-]+:\d{12}:[a-zA-Z0-9\-_]+)'

### Reproduction Steps

```
string targetSQSFifoArn = "TODO";
string targetSQSFifoDLQArn = "TODO";
string targetIAMRoleArn = "TODO";
using (AmazonSchedulerClient amazonSchedulerClient = new())
{
    try
    {
        using (Task<CreateScheduleResponse> createScheduleResponseTask = amazonSchedulerClient.CreateScheduleAsync(new CreateScheduleRequest
        {
            FlexibleTimeWindow = new FlexibleTimeWindow
            {
                Mode = FlexibleTimeWindowMode.OFF
            },
            GroupName = "GROUP1",
            Name = "SCHEDULE1",
            ScheduleExpression = "rate(5 minutes)",
            State = ScheduleState.ENABLED,
            Target = new Target
            {
                Arn = targetSQSFifoArn,
                DeadLetterConfig = new Amazon.Scheduler.Model.DeadLetterConfig
                {
                    Arn = targetSQSFifoDLQArn
                },
                Input = "foo",
                RetryPolicy = new RetryPolicy
                {
                    MaximumEventAgeInSeconds = 60,
                    MaximumRetryAttempts = 1
                },
                RoleArn = targetIAMRoleArn,
                SqsParameters = new SqsParameters
                {
                    MessageGroupId = "foo"
                }
            }
        }))
        {
            Console.WriteLine(createScheduleResponseTask.Result.HttpStatusCode);
        }
    }
    catch (Exception ex)
    {
        Console.WriteLine(ex);
    }
}
```

### Possible Solution

Likely just need to fix the regex to allow for an optional ".fifo" suffix.

### AWS .NET SDK and/or Package version used

AWSSDK.Scheduler 3.7.101.111

### Targeted .NET Platform

.NET 6

### Operating System and version

AWS Lambda (.NET 6)

**Comment by dscpinheiro** [comment]
Does EventBridge Scheduler support setting a FIFO queue as DLQ? I saw the same error when using the CLI and console, so it looks like the service doesn't support this at the moment (it did allow me to use a Standard queue in the retry policy)

FYI: That regex is coming directly from the service model (https://github.com/aws/aws-sdk-net/blob/master/generator/ServiceModels/scheduler/scheduler-2021-06-30.api.json#L353-L358), our client is generated and doesn't modify the regex at all.

**Comment by maxmoore14** [comment]
You are correct, even the console fails with the same error. I will close this bug as it does not relate to the SDK.

FIFO queues must have FIFO DLQs (https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-dead-letter-queues.html), so this seems like a defect in Scheduler itself I think.
