### ISSUE TITLE
ScheduledInstance.PreviousSlotEndTime should be nullable

### ISSUE THREAD

**Issue by mwhouser** [aws/aws-sdk-net#300]
In cases before the first time slot begins, there is no "previous" time slot.

The response for the `previousSlotEndTime` field is null and/or empty. Calling `aws ec2 describe-scheduled-instances` does not include a value for `previousSlotEndTime`.

So the value for `ScheduledInstance.PreviousSlotEndTime` should be `null` in this case.

Similarly at the end of the term, after the final slot begins, there would be no "next" time slot. So the `ScheduledInstance.NextSlotStartTime` should be `null`.

**Comment by PavelSafronov** [comment]
Unfortunately, making these fields nullable would be a breaking change.
For value types, if the property was not returned by the server, the property will be equal to that type's ```default``` value. So to test if ```PreviousSlotEndTime``` or ```NextSlotStartTime``` were returned by the service, you can compare the value of the field to either ```default(DateTime)``` or ```DateTime.MinValue``` (they are the same values).
