### ISSUE TITLE
Setting DynamoDbTable name per region and environment as prefix and suffix

### ISSUE THREAD

**Issue by prad9** [aws/aws-sdk-net#301]
Hi There,
We currently have DynamoDbTable table names as AWSRegion-TableName-Environment e.g Virginia-TableName-Dev

We didn't had any problems using this pattern in our node apps until we used aws-sdk-net. We have realized that there is no way to get table name which has suffix for .net sdk. Can you please suggest any alternative? We are aware that we can use DynamoDbContext.TableNamePrefix but we also require TableNameSuffix or similar functionality?

**Comment by PavelSafronov** [comment]
At the moment, only prefixes are supported. If you are using DynamoDBContext to work with your tables, the per-operation config object ```DynamoDBOperationConfig``` has the field ```OverrideTableName``` that can be used to completely override the table name. Though this does mean that you will need to specify it per operation.
You mention that this pattern works with node. Can you provide some more information on this? How are table prefixes and suffixes handled there?

**Comment by prad9** [comment]
Thanks for suggestion. The way we are doing right now in .Net is by setting TableName attribute to the DynamoDbTable .net object. But this is not giving us flexibility to change the table name at runtime (by passing prefix and suffix from config). We are thinking to change the code slightly to use .net Document table to achieve this). What do you recon?

We didn't had any problems in node because the api is so flexible and we could be able to pass in the table name at run time with prefix and suffix to do the table operations.

**Comment by PavelSafronov** [comment]
You could use the Table object, by loading the appropriate table, like this:
```
var table = Table.LoadTable(client, "Virginia-TableName-Dev");
var doc = table.GetItem("hash-key");
```

The other approach I suggested was passing in a DynamoDBOperationConfig when making a call against the DynamoDBContext, like this:
```
// DynamoDBContext approach
var opConfig = new DynamoDBOperationConfig
{
    OverrideTableName = "Virginia-TableName-Dev"
};
var animal = ddbContext.Load<Animal>("hash-key", opConfig);
```

**Comment by prad9** [comment]
Overriding table name worked fine. Thanks for your help.
