### ISSUE TITLE
Lambda long polling with SQS sending infinite request

### ISSUE THREAD

**Issue by SubhashJuyal** [aws/aws-sdk-net#3012]
### Describe the bug

Create an application using .net core 6 lambda template.

Use AWS sdk for create IAmazonSQS client. Write the code to fetch message from sqs using long polling mechanism. 

Create a test application for invoking the lambda handler. Add the debugger in first line of the test app.

Observed an awkward behavior. Even before calling the constructor, the infinite number of request are sent by application for fetching the SQS messages using long polling. I have not even call the method to receive the message but when I am checking using fiddler tool, the application started to send the messages without stopping. 

So I am not able to fetch the message from SQS as before calling the method, there are already many calls that have been sent by the application. 

### Expected Behavior

Lambda should only send the messages when we  call the method. Kindly create sample application using 
Lambda template for .net core and IAmazonSQS library of AWS sdk.

you will find this behavior only on Lambda with .net core 6 runtime.  This is not reproducible on .net framework, .net core console application.

Kindly help to find the solution for this asap.

### Current Behavior

Unable to process the messages.

### Reproduction Steps

Create sample application using above steps. Also call this method _amazonSQS.ReceiveMessageAsync(_receiveMessageRequest, CancellationToken.None)

I am using long polling to fetch messages from sqs. 

### AWS .NET SDK and/or Package version used

<PackageReference Include="Amazon.Lambda.Core" Version="2.1.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.2.0" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.7.7" />
    <PackageReference Include="AWSSDK.S3" Version="3.7.201.1" />
    <PackageReference Include="AWSSDK.SQS" Version="3.7.200.3" /

### Targeted .NET Platform

.net core 6,.net core 3.1

### Operating System and version

Windows for testing

**Comment by ashishdhingra** [comment]
@SubhashJuyal Thanks for reporting the issue. Could you please share sample code solution (may be attach it as a ZIP file) so that we have the consistent reproduction for the issue?

Thanks,
ashish

**Comment by SubhashJuyal** [comment]
Thanks for replying.
You can just create application using AWS SDK lambda template application using .net core 6 in visual studio.
In the lambda handler, use long polling to fetch messages from sqs using ISQSservice. Use latest nuget package.
Put the break point on the first line of the test project and start observing sqs API calls using fiddler. You will observe request will start to sent even before send request mathod is called.

If you face any issues on this, then I will share the code.

**Comment by ashishdhingra** [comment]
> Thanks for replying. You can just create application using AWS SDK lambda template application using .net core 6 in visual studio. In the lambda handler, use long polling to fetch messages from sqs using ISQSservice. Use latest nuget package. Put the break point on the first line of the test project and start observing sqs API calls using fiddler. You will observe request will start to sent even before send request mathod is called.
> 
> If you face any issues on this, then I will share the code.

@SubhashJuyal Could you please let me know the following:
- Details about test project.
- Are you developing Lambda Handler as a simple lambda function and using [AWSSDK.Extensions.NETCore.Setup](https://github.com/aws/aws-sdk-net/tree/master/extensions/src/AWSSDK.Extensions.NETCore.Setup) package to setup DI using `IAmazonSQS` interface?
  - If not using test project, are you using the Lambda Test Tool to test locally where you are setting up breakpoint in Lambda handler.
  - I'm asking this since you appear to use Fiddler to monitor network calls, hence it is assumed that you are testing lambda handler locally.

I tested using the below function handler and noticed that there was only one call to `sqs.us-east-2.amazonaws.com` in Fiddler.
```C#
using Amazon;
using Amazon.Lambda.Core;
using Amazon.SQS;
using Microsoft.Extensions.DependencyInjection;
using Amazon.Extensions.NETCore.Setup;
using Amazon.SQS.Model;

// Assembly attribute to enable the Lambda function's JSON input to be converted into a .NET class.
[assembly: LambdaSerializer(typeof(Amazon.Lambda.Serialization.SystemTextJson.DefaultLambdaJsonSerializer))]

namespace TestLambdaSQSLongPolling;

public class Function
{
    private ServiceProvider? _serviceProvider;
    private readonly IAmazonSQS? _amazonSQS;
    private readonly string queueUrl = "<<queue-url>>";

    public Function()
    {
        ConfigureServices();
        _amazonSQS = _serviceProvider?.GetService<IAmazonSQS>();
    }


    public async Task FunctionHandler(string input, ILambdaContext context)
    {
        context.Logger.LogLine($"Starting long polling...");

        var response = await _amazonSQS.ReceiveMessageAsync(new ReceiveMessageRequest() { QueueUrl = queueUrl }, CancellationToken.None);
        
        context.Logger.LogLine($"Recevied {response.Messages.Count} messages.");
    }

    private void ConfigureServices()
    {
        var serviceCollection = new ServiceCollection();

        serviceCollection.AddDefaultAWSOptions(new AWSOptions
        {
            Region = RegionEndpoint.USEast2
        });
        serviceCollection.AddAWSService<IAmazonSQS>();

        _serviceProvider = serviceCollection.BuildServiceProvider();
    }

}
```
Here is the `.csproj` file:
```XML
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>
    <!-- This property makes the build directory similar to a publish directory and helps the AWS .NET Lambda Mock Test Tool find project dependencies. -->
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <!-- Generate ready to run images during publishing to improve cold start time. -->
    <PublishReadyToRun>true</PublishReadyToRun>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" Version="2.1.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.3.1" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.7.7" />
    <PackageReference Include="AWSSDK.SQS" Version="3.7.200.23" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="7.0.0" />
  </ItemGroup>
</Project>
```

Have you somehow monitored Dead Letter Queue (DLQ) as well for Lambda function? In case your setup is different from mine, please share the requested information in previous comments, including SQS configuration, etc. to troubleshoot further.

Thanks,
Ashish
