### ISSUE TITLE
Pre-signed url for PUT with custom metadata does not work on S3 outpost

### ISSUE THREAD

**Issue by grsw92** [aws/aws-sdk-net#3014]
### Describe the bug

The problem we encounter is that the pre-presigned url for PUT request gets rejected by S3 outpost when used.

I did couple of tests and compared urls generated from .NET SDK and boto3 (S3 client for python). The boto3 links were always working in my case. 

I spotted the difference in the links generated by those two. In the boto3 generated link the query params are URL encoded, whereas in the link from the .NET library are not.

The most problematic seems to be `;` in the `X-Amz-SignedHeaders` value - after manually replacing the semicolon with `%3B` the url works as expected.

There is also `X-Amz-Credential` that in our case contains not encoded `/` but even with that it works fine when the one above is fixed manually.

Based on my tests these are the conditions for this to happen:
- pre-signed for needs to be for S3 outpost. I tested the same scenario with access point to standard S3. Only S3 outpost rejects the link
- the custom metadata needs to be added. I guess because without this there is no semicolon in the params

### Expected Behavior

The generated link should not be rejected by the server

### Current Behavior

The server response for generated link is 400 (Bad Request) and the message in the response body says:
```xml
<Error>
   <Code>InvalidRequest</Code>
   <Message>Access Denied</Message>
   ...
</Error>
```

### Reproduction Steps

Below code fails, but it should not:
```C#
    // initialize client
    var creds = new BasicAWSCredentials(...);
    var config = new AmazonS3Config { UseArnRegion = true };
    var client = new AmazonS3Client(creds, config);
    
    // create pre-signed url
    var customMetadata = "MyMetadata";
    
    var request = new GetPreSignedUrlRequest
    {
        BucketName = "<arn to S3 outpost access point>",
        Key = "object_key",
        Verb = HttpVerb.PUT,
        Protocol = Protocol.HTTPS,
        Expires = DateTime.Now.AddMinutes(30)
    };

    var metadata = "metadata-value";
    request.Metadata.Add(customMetadata, metadata);
    
    var preSignedUrl = client.GetPreSignedURL(request);
    
    // uncomment this for workaround
    // preSignedUrl = preSignedUrl.Replace(";", "%3B");

    // make the request 
    var httpClient = new HttpClient();
    var httpRequest = new HttpRequestMessage(HttpMethod.Put, preSignedUrl)
    {
        Content = new StringContent("foo"),
        Headers = { { $"X-Amz-Meta-{customMetadata}", metadata } }
    };

    var response = await httpClient.SendAsync(httpRequest, new CancellationTokenSource(TimeSpan.FromSeconds(30)).Token);
    response.EnsureSuccessStatusCode();
```

### Possible Solution

Add URL encoding for query param values of the link returned by `GetPreSignedURL`

### AWS .NET SDK and/or Package version used

AWSSDK.S3 3.7.201.4

### Targeted .NET Platform

.NET 7

### Operating System and version

ubuntu

**Comment by ashishdhingra** [comment]
Hi @grsw92,

Good morning.

While I somehow do not have access to create/configure S3 Outposts, using the below code for your scenario with normal S3 bucket does not reproduce the scenario (used `AWSSDK.S3` version `3.7.201.4`):
```C#
using Amazon;
using Amazon.S3;
using Amazon.S3.Model;
using Amazon.S3.Util;
using System;
using System.Collections.Generic;
using System.IO;
using System.Net;

namespace PresignedUrlTest
{
    class GenPresignedURLTest
    {
        private const string bucketName = "<<bucket-name>>";
        private const string objectKey = "<<object-key>>";
        private const string filePath = @"<<full-path-to-txt-file>>";

        private static readonly RegionEndpoint bucketRegion = RegionEndpoint.USEast2; // Specify suitable region
        private static IAmazonS3 s3Client;

        public static void Main()
        {
            s3Client = new AmazonS3Client(bucketRegion);

            Dictionary<string, string> metadata = new Dictionary<string, string>()
            {
                { "MyMetadata", "metadata-value" }
            };
            var url = GeneratePreSignedURL(metadata);
            UploadObject(url, metadata);
        }

        private static void UploadObject(string url, Dictionary<string, string> metadata = null)
        {
            HttpWebRequest httpRequest = WebRequest.Create(url) as HttpWebRequest;
            httpRequest.Method = "PUT";

            if (metadata != null && metadata.Count > 0)
            {
                WebHeaderCollection myWebHeaderCollection = httpRequest.Headers;

                foreach (KeyValuePair<string, string> keyValuePair in metadata)
                {
                    myWebHeaderCollection.Add($"X-Amz-Meta-{keyValuePair.Key}", keyValuePair.Value);
                }
            }
            
            using (Stream dataStream = httpRequest.GetRequestStream())
            {
                var buffer = new byte[8000];
                using (FileStream fileStream = new FileStream(filePath, FileMode.Open, FileAccess.Read))
                {
                    int bytesRead = 0;
                    while ((bytesRead = fileStream.Read(buffer, 0, buffer.Length)) > 0)
                    {
                        dataStream.Write(buffer, 0, bytesRead);
                    }
                }
            }
            HttpWebResponse response = httpRequest.GetResponse() as HttpWebResponse;
        }

        private static string GeneratePreSignedURL(Dictionary<string, string> metadata = null)
        {
            var request = new GetPreSignedUrlRequest
            {
                BucketName = bucketName,
                Key = objectKey,
                Verb = HttpVerb.PUT,
                Expires = DateTime.Now.AddMinutes(30),
                Protocol= Protocol.HTTPS
            };

            if (metadata != null && metadata.Count > 0)
            {
                foreach (KeyValuePair<string, string> kvp in metadata)
                {
                    request.Metadata.Add(kvp.Key, kvp.Value);
                }
            }
            
            string url = s3Client.GetPreSignedURL(request);
            return url;
        }
    }
}
```

**Presigned URL Generated:**
```
https://<<bucket-name-REDACTED>>.s3.us-east-2.amazonaws.com/<<object-key-REDACTED>>?X-Amz-Expires=1798&X-Amz-Security-Token=<<REDACTED>>X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=<<REDACTED>>/20230731/us-east-2/s3/aws4_request&X-Amz-Date=20230731T211205Z&X-Amz-SignedHeaders=host;x-amz-meta-mymetadata&X-Amz-Signature=<<REDACTED>>
```

Notice that the `X-Amz-SignedHeaders` parameter value does not have `;` URL encoded.

The presigned URL generation follows the specification mentioned at:
- [Signing and authenticating REST requests](https://docs.aws.amazon.com/AmazonS3/latest/userguide/RESTAuthentication.html)
- [Authenticating Requests: Using Query Parameters (AWS Signature Version 4)](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html)
- [Create a signed AWS API request](https://docs.aws.amazon.com/IAM/latest/UserGuide/create-signed-request.html) (refer example **Example: Request with authentication parameters in the query string** where `;` character in `X-Amz-SignedHeaders` is not URL encoded)


Does your code works fine with normal S3 bucket (without Outposts)? I'm unsure why S3 Outposts would have a different behavior than S3 (or S3 Access Points).

Thanks,
Ashish

**Comment by grsw92** [comment]
@ashishdhingra

> [Create a signed AWS API request](https://docs.aws.amazon.com/IAM/latest/UserGuide/create-signed-request.html) (refer example Example: Request with authentication parameters in the query string where ; character in X-Amz-SignedHeaders is not URL encoded)

The description of this example says it's not encoded only for readability purposes. 

![image](https://github.com/aws/aws-sdk-net/assets/51381375/6a4efb9f-9f08-4a60-8aa9-e71fe1b4cd65)

> Does your code works fine with normal S3 bucket (without Outposts)? I'm unsure why S3 Outposts would have a different behavior than S3 (or S3 Access Points).

Yes. Apart from outposts I did several runs with standard S3 accessed by bucket name, access point and multi-region access point. Only the S3 outpost rejected these requests.

**Comment by ashishdhingra** [comment]
@grsw92 Thanks for the call out. Let me run some tests on normal S3 using .NET SDK and preferably some other SDK (like Java and AWS CLI). Once the findings are confirmed, I will review this with the team.

**Comment by ashishdhingra** [comment]
Replacing `;` in `X-Amz-SignedHeaders` parameter with URL encoded `%3B` works fine with normal S3 bucket.

Tracing (debugging) through the code, 
- The query string parameter key(s) and value(s) are URL Encoded [here](https://github.com/aws/aws-sdk-net/blob/08e1d4619c3745fbd7acdd7f2e11ba9266df3bc2/sdk/src/Core/Amazon.Runtime/Internal/Auth/AWS4Signer.cs#L1020C117-L1020C126).
  - This uses [AWSSDKUtils.UrlEncode()](https://github.com/aws/aws-sdk-net/blob/08e1d4619c3745fbd7acdd7f2e11ba9266df3bc2/sdk/src/Core/Amazon.Util/AWSSDKUtils.cs#L1025) which uses `RFC Number` as `3986`. This does not define `;` in [ValidUrlCharacters](https://github.com/aws/aws-sdk-net/blob/08e1d4619c3745fbd7acdd7f2e11ba9266df3bc2/sdk/src/Core/Amazon.Util/AWSSDKUtils.cs#L106). the value `host;x-amz-meta-mymetadata` (for example) for `X-Amz-SignedHeaders` appears to be encoded to `host%3Bx-amz-meta-mymetadata`.
- The canonicalized query string at [code path](https://github.com/aws/aws-sdk-net/blob/08e1d4619c3745fbd7acdd7f2e11ba9266df3bc2/sdk/src/Core/Amazon.Runtime/Internal/Auth/AWS4Signer.cs#L1031) has value `X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=<<REDACTED>>&X-Amz-Date=20230801T202245Z&X-Amz-Expires=1798&X-Amz-Security-Token=<<REDACTED>>&X-Amz-SignedHeaders=host%3Bx-amz-meta-mymetadata` (for example), notice encoded `;` in `X-Amz-SignedHeaders`.
- [GetPreSignedURLInternal()](https://github.com/aws/aws-sdk-net/blob/08e1d4619c3745fbd7acdd7f2e11ba9266df3bc2/sdk/src/Services/S3/Custom/AmazonS3Client.Extensions.cs#L79) appears to use [signingResult4.ForQueryParameters](https://github.com/aws/aws-sdk-net/blob/08e1d4619c3745fbd7acdd7f2e11ba9266df3bc2/sdk/src/Services/S3/Custom/AmazonS3Client.Extensions.cs#L168C43-L168C76) which has not encoded query string parameters.
  - So `SigV4` calculation appears to URL encode `X-Amz-SignedHeaders` per specification, the presigned URL generation appears to be using not encoded value.
- [AWS4SigningResult.ForQueryParameters](https://github.com/aws/aws-sdk-net/blob/08e1d4619c3745fbd7acdd7f2e11ba9266df3bc2/sdk/src/Core/Amazon.Runtime/Internal/Auth/AWS4SigningResult.cs#L93) doesn't appear to return URL encoded value for `HeaderKeys.XAmzSignedHeadersHeader` (`X-Amz-SignedHeaders`).

So the possible fix is to update [AWS4SigningResult.ForQueryParameters](https://github.com/aws/aws-sdk-net/blob/08e1d4619c3745fbd7acdd7f2e11ba9266df3bc2/sdk/src/Core/Amazon.Runtime/Internal/Auth/AWS4SigningResult.cs#L93) to use the URL encoded value for `HeaderKeys.XAmzSignedHeadersHeader` (`X-Amz-SignedHeaders`).

Just a note, the [W3C Recommendation from 1999](http://www.w3.org/TR/1999/REC-html401-19991224/appendix/notes.html#h-B.2.2) is obsolete. The current status, according to the [2014 W3C Recommendation](https://www.w3.org/TR/2014/REC-html5-20141028/forms.html#url-encoded-form-data), is that semicolon is now illegal as a parameter separator.

**Comment by ashishdhingra** [comment]
@grsw92 The fix has been released in `AWSSDK. Core 3.7.201.0`. Please update to latest version.
