### ISSUE TITLE
'=' in secret key causes truncation by credentials parser

### ISSUE THREAD

**Issue by L0G1C** [aws/aws-sdk-net#302]
Hello,

So I have a aws_secret_access_key in a credentials file that ends with the characters "==".

When I put my credentials in AWS Explorer, or 'hard code' them into my AmazonS3Client config, everything works. But when I try to pull from the credentials file, I find that the .net sdk truncates the two "=" operators. 

I decompiled the StoredProfileAWSCredentials.cs I noticed the following:

` private class CredentialsFileParser
    { ... private const string keyValueSeparator = "="; ...}
`

The KeyValueSeparator being set to "=" makes me think that my secret key is being truncated by throwing off the parser?

I end up with a truncated secret key which fails to authenticate with the client.

**Comment by normj** [comment]
I checked with the auth team and they said AWS doesn't vend AWS secret key that have "=" characters. Are you sure you are working with an AWS secret key?

**Comment by L0G1C** [comment]
Oh I see. We are using an "S3 compatible" storage, not actually an AWS s3.

**Comment by PavelSafronov** [comment]
We're looking into updating the credentials parser implementation to support your usecase. Will update this issue when this change is made.

**Comment by L0G1C** [comment]
Do you guys accept pull requests from others if I want to work on the change on my end and send you my solution incase you want to use it?

**Comment by PavelSafronov** [comment]
Absolutely. Feel free to submit a PR and we'll review it.

**Comment by PavelSafronov** [comment]
The PR for this feature has been accepted. Closing.

**Comment by L0G1C** [comment]
Just curious, how once PR has been accepted how long before I see it on the nuget package for the AWS SDK? What's the software deployment cycle like?

**Comment by PavelSafronov** [comment]
The NuGet package should be updated today. I'll comment here when it is.
Mostly, we update the packages when there is a service update, a major bug is found, or if someone requests it.

**Comment by PavelSafronov** [comment]
[AWSSDK.Core NuGet package 3.1.4.4](https://www.nuget.org/packages/AWSSDK.Core/3.1.4.4) contains this change. You should now be able to update the core package in your VS project to the latest version.

**Comment by L0G1C** [comment]
Man, this sucks. I got version 3.1.4.4 and see that the change to the split function is there. But somehow after using StoredProfileAWSCredentials I still wind up with the _wrapped credentials "secret key" value missing the 2 "=" at the end of the string. =/

**Comment by PavelSafronov** [comment]
Please make sure that your application is in fact using the latest version of AWSSDK.Core. I've just tested this behavior with the below code and confirmed that the code works with the latest version of AWSSDK.Core from NuGet.

```
var path = Path.GetTempFileName();
File.WriteAllText(path, @"[test]
aws_access_key_id = blah==
aws_secret_access_key=foo==
aws_session_token= baz==
");

var creds = new StoredProfileAWSCredentials("test", path);
var ic = creds.GetCredentials();
Debug.Assert(ic.AccessKey.EndsWith("=="));
Debug.Assert(ic.SecretKey.EndsWith("=="));
Debug.Assert(ic.Token.EndsWith("=="));
```
