### ISSUE TITLE
Async tasks never activate on certain networks

### ISSUE THREAD

**Issue by AbeGellis** [aws/aws-sdk-net#3023]
### Describe the bug

We are building a Unity application with the AWS SDK included as a NuGet package. We make significant use of Cognito Identity and Pinpoint async calls for authentication and logging. We maintain both iOS and Android versions; both use IL2CPP / .NET Standard 2.1 compatibility.

When no network is available, the tasks generated by these async calls never exit the `TaskStatus.WaitingForActivation` state. We intend this application to be usable offline, and so cancel any tasks that remain in `TaskStatus.WaitingForActivation` after a few seconds.

All of the described functionality works as intended in the Unity Editor and works most of the time in iOS and Android builds. However, one of our non-developer employees has been able to consistently reproduce a failure to ever get past `TaskStatus.WaitingForActivation`, but only on a specific internet network (Verizon FiOS, if that's relevant). 

The devices in question (and the editor, on a computer on the same network) are able to make successful SDK calls under other circumstances, including switching to mobile data instead of using the network, but consistently fail when connected to that WiFi (even when the timeout is set to 60 seconds). The devices are otherwise able to access the network normally.

We are at a loss for how to further diagnose or address this issue, or reproduce it under other circumstances.

### Expected Behavior

Async Cognito and Pinpoint SDK calls execute and resolve with either successful task result objects or exceptions on any network, and only "get stuck" when no network is available on which to start executing.

### Current Behavior

Async Cognito and Pinpoint SDK calls appear to never start (remaining at `TaskStatus.WaitingForActivation`) on a specific internet network.

### Reproduction Steps

Reproduction steps have not been isolated, except for testing from the same network as our unfortunate non-developer.

It appears as though all SDK calls are failing to resolve, but the most obvious are
```C#
AmazonCognitoIdentityProviderClient.InitiateAuthAsync // User SRP and Refresh flows
AmazonPinpointClient.PutEventsAsync
```

### AWS .NET SDK and/or Package version used

AWSSDK.CognitoIdentity.3.7.100.152
AWSSDK.CognitoIdentityProvider.3.7.101.152
AWSSDK.Core.3.7.108.1
AWSSDK.Pinpoint.3.7.102.5
AWSSDK.SecurityToken.3.7.103.21

### Targeted .NET Platform

.NET Standard 2.1

### Operating System and version

Affects Android and iOS

**Comment by ashishdhingra** [comment]
@AbeGellis Good afternoon. Thanks for opening the issue. Please advise the following:
- Have you followed [Special considerations for Unity support](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/unity-special.html) for Unity support?
  - For `IL2CPP` you would need to use `link.xml` to avoid trimming.
- Also check [Async: why is my task status always WaitingForActivation](https://forum.unity.com/threads/async-why-is-my-task-status-always-waitingforactivation.1346657/) for similar issue. Are you keeping track of individual tasks for checking status?
- May be enable verbose logging using steps mentioned in section `Set Logging Information` at https://docs.aws.amazon.com/mobile/sdkforunity/developerguide/setup-unity.html using `awsconfig.xml` file. (unsure if it would work, but please give it a try)

Thanks,
Ashish

**Comment by AbeGellis** [comment]
> @AbeGellis Good afternoon. Thanks for opening the issue. Please advise the following:
> 
> * Have you followed [Special considerations for Unity support](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/unity-special.html) for Unity support?
>   
>   * For `IL2CPP` you would need to use `link.xml` to avoid trimming.
`link.xml` is in place as recommended. The issue is not present in other builds - a trimming issue would be, as I understand.
> * Also check [Async: why is my task status always WaitingForActivation](https://forum.unity.com/threads/async-why-is-my-task-status-always-waitingforactivation.1346657/) for similar issue. Are you keeping track of individual tasks for checking status?
I can confirm that the `WaitingForActivation` value is obtained from the `Task` directly instead of being kept around as in that user's issue.
> * May be enable verbose logging using steps mentioned in section `Set Logging Information` at https://docs.aws.amazon.com/mobile/sdkforunity/developerguide/setup-unity.html using `awsconfig.xml` file. (unsure if it would work, but please give it a try)
We are not using the AWS Mobile SDK for Unity, we are using the AWS SDK for .NET in a Unity project via NuGet. There is no `UnityInitializer` to initialize. Is there a way to enable verbose logging in the SDK for .NET?

**Comment by ashishdhingra** [comment]
@AbeGellis Logging could be enabled using below code in SDK for .NET:
```C#
Amazon.AWSConfigs.LoggingConfig.LogResponses = Amazon.ResponseLoggingOption.Always;
Amazon.AWSConfigs.LoggingConfig.LogTo = Amazon.LoggingOptions.SystemDiagnostics;
Amazon.AWSConfigs.AddTraceListener("Amazon", new System.Diagnostics.ConsoleTraceListener());
```

Without proper concrete reproduction steps we are unsure on how to troubleshoot the issue. Also it happens in certain networks where `Task` status is `TaskStatus.WaitingForActivation`, so this doesn't appear to be AWS SDK for .NET issue since the Task activation is handled by underlying .NET platform.
