### ISSUE TITLE
Add m7a class instancetypes

### ISSUE THREAD

**Issue by doskabouter** [aws/aws-sdk-net#3032]
### Describe the feature

On the website I'm able to choose f.e. m7a.medium as instancetype when creating a new instance.
These values are not yet available to the sdk, and I would like to be able to start instances of that type from my tools.

### Use Case

These are the only non-burstable singlecore machines and as such perfect for my workload

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

3.7.621.0

### Targeted .NET Platform

,NET Framework 3.5

### Operating System and version

Windows 10

**Comment by normj** [comment]
In what way is `m7a.medium` not available in the SDK? We don't have enumerations or anything for instance types and if you are trying to start an instance you would set the `InstanceType` string property for the `RunInstance` operation to `m7a.medium`.

**Comment by doskabouter** [comment]
The enumeration I use is the Amazon.EC2.InstanceType as defined here: https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/EC2/Generated/ServiceEnumerations.cs#L7418
I never realized I could just do a new InstanceType("m7a.medium")... thanks for the tip!

**Comment by normj** [comment]
Today's release of the SDK picked up the last instance type enumeration values including the m7a types. https://github.com/aws/aws-sdk-net/blob/master/changelogs/SDK.CHANGELOG.2023.md#376290-2023-08-24-1829-utc
