### ISSUE TITLE
S3 download actions that is expected to return precondition failed instead raises generic exceptions

### ISSUE THREAD

**Issue by cagriy** [aws/aws-sdk-net#3039]
### Describe the bug

Trying to download a file from S3, using .NET 7. Request object has an EtagToNotMatch property added with an md5 hash. According to the documentation, if Etag matches, GetObjectAsync should return PreconditionFailed HTTP status in the response object. However, in my tests it simply throws an 
```
"Error making request with Error Code NotModified and Http Status Code NotModified. No further error information was returned by the service."
```
exception with the inner exception message of 
```
{Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.Internal.RedirectHandler.HandleRedirect(IExecutionContext executionContext)
   at Amazon.Runtime.Interna…}
```

Since the exception occurs before the response object is populated there is no practical way to check HTTP Status code to see if it is PreconditionFailed (412). Response status in the exception is set to Not Modified instead of 412.

### Expected Behavior

If Etag does not match, the GetObjectAsync method should return either:
1 - A response object with Response.HTTPStatusCode set to System.Net.HttpStatusCode. PreconditionFailed
or 
2 - If an exception is to be thrown, this should be a specific PreconditionFailed exception rather than HttpErrorResponseException so that the specific reason for the exception can be identified and handled.

I don't think this is a misbehaviour, we expect an return code of 412, so not sure if exception is relevant.

### Current Behavior

Method throws a generic HttpErrorResponseException making it impossible to identify if there is a problem with the request or it is merely the download not being performed due to matching etags.

I expect same problem to occur with other filters (matching tag and modifiedsince) as they are also designed to return precondition failed. But this has not been tested.

### Reproduction Steps

Below is slightly modified version of the example AWS SDK code to add etag. Can be tested against any bucket/file, issue occurs when the etags are matching.

```
// Create a GetObject request
        var request = new GetObjectRequest
        {
            BucketName = bucketName,
            Key = objectName,
        };
        
        // Specify eTag if needed
        if (etag is not null)
        {
            request.EtagToNotMatch=etag;
        }

        // Issue request and remember to dispose of the response
        GetObjectResponse response = null ;
        try
        {
            response = await _client.GetObjectAsync(request);
            // Save object to local file
            await response.WriteResponseStreamToFileAsync(filePath, false, CancellationToken.None);
            return response.HttpStatusCode == System.Net.HttpStatusCode.OK;
        }
        catch (AmazonS3Exception ex)
        {
            Console.WriteLine($"Error saving {objectName}: {ex.Message} / {response.HttpStatusCode}");
            return false;
        }
    }
```

### AWS .NET SDK and/or Package version used

AWSSDK.S3 3.7.201.4

### Targeted .NET Platform

.NET 7

### Operating System and version

macOS Ventura, VS 2022 for Mac

**Comment by ashishdhingra** [comment]
@cagriy Good morning. Per [S3 GetObject API](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObject.html#API_GetObject_RequestSyntax) documentation:
- For `If-Match`, _Return the object only if its entity tag (ETag) is the same as the one specified; otherwise, return a 412 (precondition failed) error._
- For `If-None-Match`, _ Return the object only if its entity tag (ETag) is different from the one specified; otherwise, return a 304 (not modified) error._

In your code, you are using `EtagToNotMatch` property of `GetObjectRequest` expecting a `412` error. Did you intend to use `EtagToMatch` property instead?

I used `EtagToMatch` property and for exception with `PreconditionFailed` status code as mentioned in S3 documentation:
<img width="1554" alt="Screenshot 2023-09-08 at 10 45 30 AM" src="https://github.com/aws/aws-sdk-net/assets/67916761/efdca65e-00a9-4519-b53c-da754db512e3">


Thanks,
Ashish

**Comment by cagriy** [comment]
Dear Ashish, 

Thanks a lot for looking into this issue. I was trying to use EtagToNotMatch. Intention was to download a file if it HAS been changed and hashes didn’t match.

You are right, S3 API documentations explains that this filter returns 304 (not modified) instead of 412 (precondition failed)

Then we have a problem with AWS .NET SDK documentation:

https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/S3/TGetObjectRequest.html

On this page please go down to the table and find EtagToNotMatch, or search for it.

￼

I am sure I’ve seen other documents as well, but they might have been derived from this one.

Many thanks,

Cagri

**Comment by ashishdhingra** [comment]
> EtagToNotMatch

@cagriy Thanks for the response. This appears to be AWS .NET SDK SPI documentation issue. S3 model has the correct details for [GetObjectRequest$IfNoneMatch](https://github.com/aws/aws-sdk-net/blob/7ed1970eb3c9e0ce2d0cc53e9f7d78819502ac7a/generator/ServiceModels/s3/s3-2006-03-01.docs.json#L2003). For most part the documentation is auto-generated from service models, the hand-crafted GetObjectRequest model class has incorrect details for [EtagToNotMatch](https://github.com/aws/aws-sdk-net/blob/7ed1970eb3c9e0ce2d0cc53e9f7d78819502ac7a/sdk/src/Services/S3/Custom/Model/GetObjectRequest.cs#L617).

Needs review with the team.

Thanks,
Ashish

**Comment by normj** [comment]
@ashishdhingra Yes it looks like the NDoc in our SDK code is incorrect. This is not part of the generated code so we just need to make a PR to fix up the NDoc for the property.

**Comment by ashishdhingra** [comment]
The API reference has been fixed.
