### ISSUE TITLE
Using .NET SNS with Phonegap

### ISSUE THREAD

**Issue by sankp** [aws/aws-sdk-net#304]
Hello,

I have phonegap app and i want to use Amazon SNS service for push notification.
Can't find any good example which is easy to understand and implement. Amazon docs are really confusing in terms of topics, directing user to to google website for GCM etc.
Is there any good end to end working example, blog etc available ?

**Comment by normj** [comment]
I have limited knowledge of Phonegap but as I recall it is HTML and JavaScript based so I'm not sure what this has to do with .Net. You should ask on the SNS forums

https://forums.aws.amazon.com/forum.jspa?forumID=72
