### ISSUE TITLE
DynamoDBContext.SaveAsync<T> unexpectedly mutates the provided object. @dynamodb

### ISSUE THREAD

**Issue by jamescarter-le** [aws/aws-sdk-net#3049]
### Describe the issue

I have the following class:

public Foo {
  // ...PK and SK
  public Dictionary<string, Bar> Children { get; set; }
}

When passing this to `DynamoDBContext.SaveAsync<Foo>` the object Foo is returned the same, however Children has now been replaced with a new object.

It is not explained that that Save mutates the provided object, destroying any references other objects may have taken on Foo.Children. This has caused me some time in debugging.

Please can you explain why you made this so, or provide an alternative operation that will not mutate the provided object.

### Links

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/CRUDHighLevelExample1.html

**Comment by ashishdhingra** [comment]
@jamescarter-le Please refer comment https://github.com/aws/aws-sdk-net/issues/3047#issuecomment-1716371895 for workaround. Save would by default replace/persist the child properties. You may try using `IgnoreNullValues` property of [DynamoDBOperationConfig](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/DynamoDBv2/TDynamoDBOperationConfig.html) class and use overloaded version of `SaveAsync()` to pass this object. Please check.

Thanks,
Ashish

**Comment by jamescarter-le** [comment]
Hi, I do want the behavior of saving the properties on the entity, but I do not want it to alter my entity in a way that leaves the original object reference but destroys the children.

If we need a deep copy before passing to AWS that is fine, but I think the docs should mention that the entity will be modified by the operation in the documentation.

I personally dropped the DbContext and went back to documents and attribute maps for this example, but I think documentation could be improved here to let people know the object WILL be modified as a side - effect.

**Comment by ashishdhingra** [comment]
@jamescarter-le Good afternoon. Could you please explain what do you mean by `oDBContext.SaveAsync<T> unexpectedly mutates the provided object` where in your case, Children has now have been replaced with a new object.

I tested your scenario using below code (used current version `3.7.300.3` of `AWSSDK.DynamoDBv2`):
```C#
var client = new AmazonDynamoDBClient(RegionEndpoint.USEast2);
var context = new DynamoDBContext(client);

Foo foo = new Foo()
{
    Id = "TestId",
    Children = new Dictionary<string, Bar>
    {
        { "test1", new Bar() { SomeProperty = "value1" } },
        { "test2", new Bar() { SomeProperty = "value2" } }
    }
};
  var barReference = foo.Children;
var barTest1ChildReference = foo.Children["test1"];
var barTest2ChildReference = foo.Children["test2"];

await context.SaveAsync<Foo>(foo);
Console.WriteLine($"Is Bar reference same: {barReference == foo.Children}");
Console.WriteLine($"....Is Bar Test1 reference same: {barTest1ChildReference == foo.Children["test1"]}");
Console.WriteLine($"....Is Bar Test2 reference same: {barTest2ChildReference == foo.Children["test2"]}");

public class Foo
{
    [DynamoDBHashKey("Id")]
    public string Id { get; set; }

    [DynamoDBProperty]
    public Dictionary<string, Bar>? Children { get; set; }
}

public class Bar
{
    [DynamoDBProperty]
    public string SomeProperty { get; set; }
}
```

Executing above code prints the following in console output:
```
Is Bar reference same: True
....Is Bar Test1 reference same: True
....Is Bar Test2 reference same: True
```
This indicates that the reference type(s) of `List` instance and corresponding child items haven't changed.

Please advise if I'm missing anything.

Thanks,
Ashish

**Comment by jamescarter-le** [comment]
I had almost the same assertions in my test for this to track down my issue, and the first assertion (Children) failed.

I'll go back through my source history to find the AWS Library version and post something to reproduce, and if fixed confirm it and close the ticket.

**Comment by jamescarter-le** [comment]
You are comparing with the Equality operator the dictionary, which uses the list of KeyValuePairs underlying the dictionary.

I believe if you check they are the same object reference this will be false.

`Object.ReferenceEquals` will check if these are literally the same object references, to confirm if this is still an issue.

**Comment by ashishdhingra** [comment]
> You are comparing with the Equality operator the dictionary, which uses the list of KeyValuePairs underlying the dictionary.
> 
> I believe if you check they are the same object reference this will be false.
> 
> `Object.ReferenceEquals` will check if these are literally the same object references, to confirm if this is still an issue.

@jamescarter-le C# `==` operator on reference types returns true if its two operands refer to the same object. To validate your assumption, I modified code to the following:
```C#
var client = new AmazonDynamoDBClient(RegionEndpoint.USEast2);
var context = new DynamoDBContext(client);

Foo foo = new Foo()
{
    Id = "TestId",
    Children = new Dictionary<string, Bar>
    {
        { "test1", new Bar() { SomeProperty = "value1" } },
        { "test2", new Bar() { SomeProperty = "value2" } }
    }
};
  var barReference = foo.Children;
var barTest1ChildReference = foo.Children["test1"];
var barTest2ChildReference = foo.Children["test2"];

await context.SaveAsync<Foo>(foo);
Console.WriteLine($"Is Bar reference same: {barReference == foo.Children}");
Console.WriteLine($"....Is Bar Test1 reference same: {barTest1ChildReference == foo.Children["test1"]}");
Console.WriteLine($"....Is Bar Test2 reference same: {barTest2ChildReference == foo.Children["test2"]}");

Console.WriteLine($"Is Bar reference same (using Object.ReferenceEquals()): {Object.ReferenceEquals(barReference, foo.Children)}");
Console.WriteLine($"....Is Bar Test1 reference same (using Object.ReferenceEquals()): {Object.ReferenceEquals(barTest1ChildReference, foo.Children["test1"])}");
Console.WriteLine($"....Is Bar Test2 reference same (using Object.ReferenceEquals()): {Object.ReferenceEquals(barTest2ChildReference, foo.Children["test2"])}");
```

This outputs:
```
Is Bar reference same: True
....Is Bar Test1 reference same: True
....Is Bar Test2 reference same: True
Is Bar reference same (using Object.ReferenceEquals()): True
....Is Bar Test1 reference same (using Object.ReferenceEquals()): True
....Is Bar Test2 reference same (using Object.ReferenceEquals()): True
```

**Comment by jamescarter-le** [comment]
Thanks for running that test! I'll roll back to an earlier version to check if I've raised this in error. 👍

**Comment by ashishdhingra** [comment]
> Thanks for running that test! I'll roll back to an earlier version to check if I've raised this in error. 👍

@jamescarter-le May be check if there is a copy/paste issue at your end where your test might be comparing different objects! :)
