### ISSUE TITLE
Interface for S3 TransferUtility

### ISSUE THREAD

**Issue by johncmckim** [aws/aws-sdk-net#305]
I would like to write some unit tests for code that uses the S3 `TransferUtility` class. I want to be able to verify that certain `TransferUtility` are called with particular arguments using Moq. However, since `TransferUtility` does not have an Interface this is impossible.

Would it be possible to extract an interface from `TransferUtility`?

**Comment by normj** [comment]
The request makes sense. We'll take a look at adding the interface.

**Comment by PavelSafronov** [comment]
We've updated S3 to include an ITransferUtility interface. It is available in version 3.1.3.11 of the S3 package.

**Comment by johncmckim** [comment]
Thanks for the quick update. Really appreciated.
