### ISSUE TITLE
Getting intermittent "PAM authentication failure" while connecting to aurora postgres

### ISSUE THREAD

**Issue by ElectricVampire** [aws/aws-sdk-net#3050]
### Describe the bug

Once a day we are randomly getting "PAM authentication failure" while connecting to aurora postgres database.

**Analysis:**
We are following - https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/UsingWithRDS.IAMDBAuth.Connecting.NET.html

In our code we make call to `Amazon.RDS.Util.RDSAuthTokenGenerator.GenerateAuthToken(RegionEndpoint.USEast1, "mysqlcluster.cluster-123456789012.us-east-1.rds.amazonaws.com", 3306, "jane_doe");` and cache the token for 12 mins (ExpireTime*0.8) and after every 12mins we make call to RDSAuthTokenGenerator.GenerateAuthToken and for debugging purpose we logged the token - it had 900sec expire time but we got an error just after 2 mins which means this token which we recevied was no longer valid for more than 2 mins.

After checking [code ](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/RDS/Custom/Util/RDSAuthTokenGenerator.cs#L88)of RDSAuthTokenGenerator I found that it uses `FallbackCredentialsFactory.GetCredentials()` which returns a token which is valid for one hour in our case.

So when we make call to  `RDSAuthTokenGenerator.GenerateAuthToken` it generates session creds which are valid till next 1hr, and returns us a rds token which is valid for next 15mins. When we make next call to `RDSAuthTokenGenerator.GenerateAuthToken` it reuses the session creds because they are still valid and returns new rds token for next 15 mins.
Now consider the case - we are 55mins into application flow since first call was made to `RDSAuthTokenGenerator.GenerateAuthToken` when session creds were created and they are now valid for only 5 more mins. If I make a call to `RDSAuthTokenGenerator.GenerateAuthToken` now, it will return me the RDS token which expire time header will say its valid for 900 seconds but database will reject it after 5 mins as underlying session token is only valid for 5 mins.

This issue is intermittent because it only get reproduced when a database call is made in small window you are caching RDS token and you make a call to fetch token just before session token is going to expire and now for any further call you use the cached token which will be invalid once underlying session token expires.

### Expected Behavior

`RDSAuthTokenGenerator.GenerateAuthToken(RegionEndpoint.USEast1, "mysqlcluster.cluster-123456789012.us-east-1.rds.amazonaws.com", 3306, "jane_doe")` should honor expire time of underlying session credential before setting expire time of RDS token.
Either Create the new session credential before requesting the rds token  
OR
Set appropriate expire time in rds token header after considering expire time of session credential.

Right now to solve the issue - I am doing `FallbackCredentialsFactory.Reset()`; before making call to generate the new rds token to solve my problem.

I also understand that there is an overload to pass the `AWSCredentials` but to generate that I need to be aware of where my code is running and have to assume role accordingly and this logic is already present in  `FallbackCredentialsFactory`.

### Current Behavior

RDS Token is getting expired before 900seconds due to expire of underlying session token

### Reproduction Steps

Reproduction of issue will depend on expire time of your session credentials. In my case its 1 hr.
- Write a code to connect to Aurora Postgres Database
- Here before connecting to DB you have to make call to RDSAuthTokenGenerator.GenerateAuthToken(RegionEndpoint.USEast1, "mysqlcluster.cluster-123456789012.us-east-1.rds.amazonaws.com", 3306, "jane_doe")
- Generated token will have validity of 900sec, you cache it for 12mins, so call to GenerateAuthToken will be made every 12mins
- Put a sleep of 9mins between every DB call
- You will see after one hour you will be using a token to connect to database whose underlying creds are expired and they will get authentication failure from DB

### Possible Solution

Right now to solve the issue - I am doing FallbackCredentialsFactory.Reset(); before making call to generate the new rds token to solve my problem. This resets the session creds.

### AWS .NET SDK and/or Package version used

               <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.7.7" />
		<PackageReference Include="AWSSDK.RDS" Version="3.7.119.11" />
		<PackageReference Include="AWSSDK.SecretsManager" Version="3.7.102.59" />
		<PackageReference Include="AWSSDK.SecurityToken" Version="3.7.103.16" />		

### Targeted .NET Platform

.NET 6

### Operating System and version

AmazonLinux

**Comment by ashishdhingra** [comment]
The 1st option `RDSAuthTokenGenerator.GenerateAuthToken(RegionEndpoint.USEast1, "mysqlcluster.cluster-123456789012.us-east-1.rds.amazonaws.com", 3306, "jane_doe") should honor expire time of underlying session credential before setting expire time of RDS token.` makes more sense. May be check the expiration time of the session token and request a new one if it is not within 15 min expiration time.

Needs review with the team.

**Comment by ashishdhingra** [comment]
@ElectricVampire We made some changes recently that changed the preemptive credential refresh time to 15 min. Could you please try upgrading to latest version and see if it mitigates your issue.

Thanks,
Ashish

**Comment by ElectricVampire** [comment]
@ashishdhingra in which version changes were done, is it possible to provide commit or pr link?

**Comment by ashishdhingra** [comment]
> @ashishdhingra in which version changes were done, is it possible to provide commit or pr link?

@ElectricVampire The commit https://github.com/aws/aws-sdk-net/commit/63f6ea7a3c702f7b52ad6168efc0183b2162f329 increases PreemptExpiryTime to 15 minutes.

**Comment by ElectricVampire** [comment]
I am testing this today, will update the status of test soon

**Comment by ElectricVampire** [comment]
@ashishdhingra 
I see that new STS token got generated after 45mins, seems issue is fixed for EKS after upgrading the nugets to latest version.

I was looking at code and I see for [EC2 ](https://github.com/aws/aws-sdk-net/blob/63f6ea7a3c702f7b52ad6168efc0183b2162f329/sdk/src/Core/Amazon.Runtime/Credentials/DefaultInstanceProfileAWSCredentials.cs#L40) - STS token expire is expireTime - 2mins.....so do you think can this problem still exists in EC2?
I do not have EC2 machine to have this tested.

**Comment by ashishdhingra** [comment]
> @ashishdhingra I see that new STS token got generated after 45mins, seems issue is fixed for EKS after upgrading the nugets to latest version.
> 
> I was looking at code and I see for [EC2 ](https://github.com/aws/aws-sdk-net/blob/63f6ea7a3c702f7b52ad6168efc0183b2162f329/sdk/src/Core/Amazon.Runtime/Credentials/DefaultInstanceProfileAWSCredentials.cs#L40) - STS token expire is expireTime - 2mins.....so do you think can this problem still exists in EC2? I do not have EC2 machine to have this tested.

@ElectricVampire Thanks for your response. I see the following code comment [here](https://github.com/aws/aws-sdk-net/blob/33334593b0fd471530220a649e1df2554512fcc9/sdk/src/Core/Amazon.Runtime/Credentials/DefaultInstanceProfileAWSCredentials.cs#L191C13-L193C49):
```C#
// By default, the refreshRate will continue to be 
// _refreshRate, but if FetchCredentials() returns an expired credential,
// the refresh rate will be adjusted
```

The logic appears to adjust the refresh rate [here](https://github.com/aws/aws-sdk-net/blob/33334593b0fd471530220a649e1df2554512fcc9/sdk/src/Core/Amazon.Runtime/Credentials/DefaultInstanceProfileAWSCredentials.cs#L215). So I guess EC2 instance metadata case should be fine. We could revisit refresh rate if there are reports of similar issue for this use case.

Please confirm if we could close this issue.

Thanks,
Ashish
