### ISSUE TITLE
Setting ReturnValuesOnConditionCheckFailure does not return Item property in ConditionalCheckFailedException

### ISSUE THREAD

**Issue by theGusPassos** [aws/aws-sdk-net#3067]
### Describe the bug

When setting the ReturnValuesOnConditionCheckFailure to ALL_OLD the Item property inside ConditionalCheckFailedException is not being set.

### Expected Behavior

The ConditionalCheckFailedException should return an Item property with the current value in the db.

### Current Behavior

The value returned for the Item property is empty.

### Reproduction Steps

```
            var request = new UpdateItemRequest
            {
                TableName = "table",
                Key = new Dictionary<string, AttributeValue>
                {
                    { "KEY", new AttributeValue { S = "1" } }
                },
                ConditionExpression = $"state" = :expectedState",
                ExpressionAttributeValues = _expressionAttributeValues,
                UpdateExpression = $"SET state = :newState",
                ReturnValuesOnConditionCheckFailure = ReturnValuesOnConditionCheckFailure.ALL_OLD,
               };

            try
            {
                var response = await _ddbClient.UpdateItemAsync(request);
                if (response?.HttpStatusCode == System.Net.HttpStatusCode.OK)
                {
                    return;
                }
            }
            catch (ConditionalCheckFailedException e)
            {
                var actualStateInDb = e.Item["state"].S;
            }
```

### Additional Information/Context

Running Dynamo in local container.

### AWS .NET SDK and/or Package version used

AWSSDK.DynamoDBv2 3.7.203.1

### Targeted .NET Platform

net7.0

### Operating System and version

Windows 11

**Comment by bhoradc** [comment]
Hi @theGusPassos,

Thanks for reporting the issue. But I am unable to replicate the behaviour. Using the `AWSSDK.DynamoDBv2 3.7.203.1` package, I am able to get the existing item property value on the `ConditionalCheckFailedException`. 
Also, not sure how the reserved keyword 'state' is allowed for an attribute name in your program. 

Here's the code that I used:

```c#
 try
 {
     AmazonDynamoDBClient client = new AmazonDynamoDBClient();

     var request = new UpdateItemRequest
     {
         TableName = "table",
         Key = new Dictionary<string, AttributeValue>() { { "KEY", new AttributeValue { S = "1" } } },

         ConditionExpression = $"flag = :expectedState",
         
         ExpressionAttributeValues = new Dictionary<string, AttributeValue>()
         {
             { ":newState", new AttributeValue { S = "inactive" } },
             { ":expectedState", new AttributeValue { S = "active" } }
         },
         UpdateExpression = $"SET flag = :newState",
         ReturnValuesOnConditionCheckFailure = Amazon.DynamoDBv2.ReturnValuesOnConditionCheckFailure.ALL_OLD,

     };

     var response = await client.UpdateItemAsync(request);
     if (response?.HttpStatusCode == System.Net.HttpStatusCode.OK)
     {
         return;
     }
 }
 catch (ConditionalCheckFailedException e)
 {
     var actualStateInDb = e.Item["flag"].S;
     Console.WriteLine(actualStateInDb);
 }
```
Execution Result: `inactive`

Can you please share the `_expressionAttributeValues` details? And also maybe the exact output you are getting? 

Regards, 
Chaitanya

**Comment by theGusPassos** [comment]
@bhoradc apparently the error only happens when hitting my local dynamo db, even though its using the latest version...
When I hit one in aws, it returns the actual value.
