### ISSUE TITLE
AWS S3 : Unable Copying an object from one bucket to another bucket using multipart copy access denied error

### ISSUE THREAD

**Issue by krishsingh-git** [aws/aws-sdk-net#3068]
### Describe the bug

AWS S3 : Unable Copying an object from one bucket to another bucket using multipart upload (RequestPayer does not exist in CopyPartRequest class)

![image](https://github.com/aws/aws-sdk-net/assets/134712777/1e8cc768-0267-4aa4-9dd2-194d94ae3a2e)

### Expected Behavior

AWS S3 :  Copying an object from one bucket to another bucket using multipart copy using RequestPayer setting

### Current Behavior

AWS S3 : Unable Copying an object from one bucket to another bucket using multipart copy access denied error

AWS S3 : Unable Copying an object from one bucket to another bucket using multipart upload (RequestPayer does not exist in CopyPartRequest class)

 

### Reproduction Steps

do MultiPartObjectCopyAsync from one bucket to another bucket
```C#
while (bytePosition < metadataResponse.ContentLength)
                {
                    partNumber++;
                    CopyPartRequest copyRequest = new CopyPartRequest
                    {
                        DestinationBucket = target.BucketName.Value,
                        DestinationKey = target.Key.Value,
                        SourceBucket = source.BucketName.Value,
                        SourceKey = source.Key.Value,
                        UploadId = initResponse.UploadId,
                        FirstByte = bytePosition,
                        LastByte = bytePosition + partSize - 1 >= metadataResponse.ContentLength
                            ? metadataResponse.ContentLength - 1
                            : bytePosition + partSize - 1,
                        PartNumber = partNumber
                    };
                    bytePosition += partSize;
                    copyPartRequests.Add(copyRequest);

                    // Check if AWS credentials are expired
                    bool isExpired = s3ExtendedCopyClient.IsCredentialExpired();
                    _appLoger.Info($"Is credential expired: {isExpired}" );
                    if (isExpired)
                    {
                        _appLoger.Info("Credentials are expired, requesting new...");
                        Result<IExtendedAmazonS3> extendedAmazonS3Result = s3ExtendedCopyClient.Recreate();
                        if (extendedAmazonS3Result.IsFailure)
                            throw new Exception(extendedAmazonS3Result.Error);

                        s3ExtendedCopyClient = extendedAmazonS3Result.Value;
                        _appLoger.Info("New credential has been assigned");
                    }

                    Task<CopyPartResponse> task = Task.Run(() =>
                    {
                        CopyPartResponse response = s3ExtendedCopyClient.AmazonS3
                            .CopyPartAsync(copyRequest)
                            .Result;

                        _appLoger.Info($"Multipart copying an object [{source.Path.Value}] to [{target.Path.Value}]. {Environment.NewLine}The record id is [{id}]. {Environment.NewLine}Progress is [{(copyRequest.LastByte * 100) / metadataResponse.ContentLength}%] ...");
                        return response;
                    });

                    responses.Add(await task);

                    // Set domain properties
                    serviceInfo.SetProgress(CalculateProgress(copyRequest.LastByte, metadataResponse.ContentLength));
                    serviceInfo.SetStatus(Status.Running.Value);

                    // DB updates
                    await _serviceInfoRepository.UpdateAsync(serviceInfo);

                    _appLoger.Info($"Requesting part copy of object [{source.Path.Value}] to [{target.Path.Value}]. {Environment.NewLine}The record id is [{id}]. {Environment.NewLine}Progress is [{CalculateProgress(copyRequest.LastByte, metadataResponse.ContentLength)}%] ...");
                }
```

### Additional Information/Context

It is working fine with Java code
```Java
 List<CopyPartResult> copyResponses = new ArrayList<CopyPartResult>();
        while (bytePosition < objectSize) {
            // The last part might be smaller than partSize, so check to make sure
            // that lastByte isn't beyond the end of the object.
            long lastByte = Math.min(bytePosition + partSize - 1, objectSize - 1);

            // Copy this part.
            CopyPartRequest copyRequest = new CopyPartRequest()
                    .withSourceBucketName(bucketName)
                    .withSourceKey(source)
                    .withDestinationBucketName(targetBucket)
                    .withDestinationKey(target)
                    .withUploadId(initResult.getUploadId())
                    .withFirstByte(bytePosition)
                    .withLastByte(lastByte)
                    .withPartNumber(partNum++).withRequesterPays(true);
            copyResponses.add(amazonS3Client.copyPart(copyRequest));
            bytePosition += partSize;
        }
```

### AWS .NET SDK and/or Package version used
AWS SDK .net 3.7.9.17

### Targeted .NET Platform
.net core 3

### Operating System and version
windows

**Comment by ashishdhingra** [comment]
@krishsingh-git Thanks for reporting the issue. Upon looking at the higher level, looks like the Java code is setting `x-amz-request-payer` header by executing `.withRequesterPays(true)` statement. There is no such supported property in .NET SDK's `CopyPartRequest`. Most of the code in .NET S3 version is hand crafted, so there is high probability that this property was somehow missed during implementation.

I'm not sure if the Access Denied error is related to this missing header. This needs reproduction. Could you please share the following:
- Your S3 bucket settings which I should use to reproduce the issue?
- Are you executing the Java code against the same source and destination bucket(s)/key(s)?
- Are you using the same credentials for running Java and .NET code?

Once reproduced, I will review this issue with the team.

Thanks,
Ashish

**Comment by krishsingh-git** [comment]
Hi Ashish,

Thanks for mail,

I am using below bucket using I am role in .net code

Source Bucket: nprd-cntdel-wh-s3
Target : skyuhd-inbound-bucket-stg

       "ProfileRegion": "eu-west-2",

        // Copy Region endpoint
        "CopyRegion": "eu-west-2",

Let me know if any other details required.

Method:

public async Task<Result<CompleteMultipartUploadResponse>> MultiPartObjectCopyAsync(
            IS3Location source,
            IS3Location target,
            IExtendedAmazonS3 s3ExtendedCopyClient,
            IAmazonS3 s3DownloadClient,
            int id)
        {
            // The only place where we know about progress //

            _appLoger.Info($"Multipart copying an object [{source.Path.Value}] to [{target.Path.Value}] has started. {Environment.NewLine}The record id is [{id}].");
            List<CopyPartResponse> responses = new List<CopyPartResponse>();
            List<CopyPartRequest> copyPartRequests = new List<CopyPartRequest>();

            // Setup information required to initiate the multipart upload.
            InitiateMultipartUploadRequest initiateRequest =
                new InitiateMultipartUploadRequest
                {
                    BucketName = target.BucketName.Value,
                    Key = target.Key.Value,
                    CannedACL = S3CannedACL.BucketOwnerFullControl,
                    RequestPayer = RequestPayer.Requester
                };

            try
            {
                // Initiate the upload.
                InitiateMultipartUploadResponse initResponse =
                    await s3ExtendedCopyClient.AmazonS3.InitiateMultipartUploadAsync(initiateRequest);

                // Get the size of the object.
                GetObjectMetadataRequest metadataRequest = new GetObjectMetadataRequest
                {
                    BucketName = source.BucketName.Value,
                    Key = source.Key.Value,
                    RequestPayer = RequestPayer.Requester
                };

                GetObjectMetadataResponse metadataResponse = await
                    s3DownloadClient.GetObjectMetadataAsync(metadataRequest);

                // Copy the parts.
                long partSize = 2048 * (1L << 20); // Part size is 2 GB.

                long bytePosition = 0;
                int partNumber = 0;

                // Get service info from DB, so we can update a progress
                IServiceInfo serviceInfo = await _serviceInfoRepository.GetByIdAsync(id);

                while (bytePosition < metadataResponse.ContentLength)
                {
                    partNumber++;
                    CopyPartRequest copyRequest = new CopyPartRequest
                    {
                        DestinationBucket = target.BucketName.Value,
                        DestinationKey = target.Key.Value,
                        SourceBucket = source.BucketName.Value,
                        SourceKey = source.Key.Value,
                        UploadId = initResponse.UploadId,
                        FirstByte = bytePosition,
                        LastByte = bytePosition + partSize - 1 >= metadataResponse.ContentLength
                            ? metadataResponse.ContentLength - 1
                            : bytePosition + partSize - 1,
                        PartNumber = partNumber
                    };
                    bytePosition += partSize;
                    copyPartRequests.Add(copyRequest);

                    // Check if AWS credentials are expired
                    bool isExpired = s3ExtendedCopyClient.IsCredentialExpired();
                    _appLoger.Info($"Is credential expired: {isExpired}" );
                    if (isExpired)
                    {
                        _appLoger.Info("Credentials are expired, requesting new...");
                        Result<IExtendedAmazonS3> extendedAmazonS3Result = s3ExtendedCopyClient.Recreate();
                        if (extendedAmazonS3Result.IsFailure)
                            throw new Exception(extendedAmazonS3Result.Error);

                        s3ExtendedCopyClient = extendedAmazonS3Result.Value;
                        _appLoger.Info("New credential has been assigned");
                    }

                    Task<CopyPartResponse> task = Task.Run(() =>
                    {
                        CopyPartResponse response = s3ExtendedCopyClient.AmazonS3
                            .CopyPartAsync(copyRequest)
                            .Result;

                        _appLoger.Info($"Multipart copying an object [{source.Path.Value}] to [{target.Path.Value}]. {Environment.NewLine}The record id is [{id}]. {Environment.NewLine}Progress is [{(copyRequest.LastByte * 100) / metadataResponse.ContentLength}%] ...");
                        return response;
                    });

                    responses.Add(await task);

                    // Set domain properties
                    serviceInfo.SetProgress(CalculateProgress(copyRequest.LastByte, metadataResponse.ContentLength));
                    serviceInfo.SetStatus(Status.Running.Value);

                    // DB updates
                    await _serviceInfoRepository.UpdateAsync(serviceInfo);

                    _appLoger.Info($"Requesting part copy of object [{source.Path.Value}] to [{target.Path.Value}]. {Environment.NewLine}The record id is [{id}]. {Environment.NewLine}Progress is [{CalculateProgress(copyRequest.LastByte, metadataResponse.ContentLength)}%] ...");
                }

                // Set up to complete the copy.
                CompleteMultipartUploadRequest completeMultiPartUploadRequest =
                    new CompleteMultipartUploadRequest
                    {
                        BucketName = target.BucketName.Value,
                        Key = target.Key.Value,
                        UploadId = initResponse.UploadId,
                        RequestPayer = RequestPayer.Requester,
                    };

                completeMultiPartUploadRequest.AddPartETags(responses);

                // Check AGAIN if AWS credentials are expired
                if (s3ExtendedCopyClient.IsCredentialExpired())
                {
                    Result<IExtendedAmazonS3> extendedAmazonS3Result = s3ExtendedCopyClient.Recreate();
                    if (extendedAmazonS3Result.IsFailure)
                        throw new Exception(extendedAmazonS3Result.Error);

                    s3ExtendedCopyClient = extendedAmazonS3Result.Value;
                }

                // Complete the copy.
                CompleteMultipartUploadResponse completeUploadResponse =
                    await s3ExtendedCopyClient.AmazonS3.CompleteMultipartUploadAsync(completeMultiPartUploadRequest);

                _appLoger.Info($"Copy of object [{source.Path.Value}] to [{target.Path.Value}] completed. {Environment.NewLine}The record id is [{id}].");

                return Task.FromResult(Result.Success(completeUploadResponse)).Result;
            }
            catch (AmazonS3Exception ex)
            {
                string message = $"Error encountered on the [S3.Copy.Service] server when multipart copying an object [{source.Path.Value}] to [{target.Path.Value}]. {Environment.NewLine}The record id is [{id}]. {Environment.NewLine}Message:'{ex.Message}'";
                _appLoger.Error(message);
                return Task.FromResult(Result.Failure<CompleteMultipartUploadResponse>(message)).Result;
            }
            catch (Exception ex)
            {
                string message = $"Unknown error encountered on the [S3.Copy.Service] server when multipart copying an object [{source.Path.Value}] to [{target.Path.Value}]. {Environment.NewLine}The record id is [{id}]. {Environment.NewLine}Message:'{ex.Message}'";
                _appLoger.Error(message);
                return Task.FromResult(Result.Failure<CompleteMultipartUploadResponse>(message)).Result;
            }
        }

Thanks

**Comment by ashishdhingra** [comment]
@krishsingh-git Id you remove `RequestPayer` from code below:

```C#
InitiateMultipartUploadRequest initiateRequest =
                new InitiateMultipartUploadRequest
                {
                    BucketName = target.BucketName.Value,
                    Key = target.Key.Value,
                    CannedACL = S3CannedACL.BucketOwnerFullControl,
                    RequestPayer = RequestPayer.Requester
                };
 ```

does it work?

Thanks,
Ashish

**Comment by krishsingh-git** [comment]
No it is ot working
Same error : : '20231013T083115ZAccess Denied)'

**Comment by ashishdhingra** [comment]
> No it is ot working
> Same error : : '20231013T083115ZAccess Denied)'

@krishsingh-git Could you also provide inputs for the below as well to troubleshoot further;

- Is the `Requester Pays` setting enabled for both source and destination buckets?
- Please share the verbose logs; these could be enabled using code below:
  ```C#
  Amazon.AWSConfigs.LoggingConfig.LogResponses = Amazon.ResponseLoggingOption.Always;
  Amazon.AWSConfigs.LoggingConfig.LogTo = Amazon.LoggingOptions.SystemDiagnostics;
  Amazon.AWSConfigs.AddTraceListener("Amazon", new System.Diagnostics.ConsoleTraceListener());
  ```

Thanks,
Ashish

**Comment by krishsingh-git** [comment]
*   Is the Requester Pays setting enabled for both source and destination buckets? : It is for Source bucket, when we disabled copy  is working , but when enabled back it is not working again.
  *   Please share the verbose logs; these could be enabled using code below: We do not have access on client bucket

·        Amazon.AWSConfigs.LoggingConfig.LogResponses = Amazon.ResponseLoggingOption.Always;

·        Amazon.AWSConfigs.LoggingConfig.LogTo = Amazon.LoggingOptions.SystemDiagnostics;

Amazon.AWSConfigs.AddTraceListener("Amazon", new System.Diagnostics.ConsoleTraceListener());


Is there any way to set RequestPayer  true in CopyPartRequest class ?
Here in below
CopyPartRequest copyRequest = new CopyPartRequest
                    {
                        DestinationBucket = target.BucketName.Value,
                        DestinationKey = target.Key.Value,
                        SourceBucket = source.BucketName.Value,
                        SourceKey = source.Key.Value,
                        UploadId = initResponse.UploadId,
                        FirstByte = bytePosition,
                        LastByte = bytePosition + partSize - 1 >= metadataResponse.ContentLength
                            ? metadataResponse.ContentLength - 1
                            : bytePosition + partSize - 1,
                        PartNumber = partNumber
                    };

**Comment by ashishdhingra** [comment]
@krishsingh-git As mentioned in the comment https://github.com/aws/aws-sdk-net/issues/3068#issuecomment-1759949795, currently there is no way to set `RequestPayer` in `CopyPartRequest` class. However, I'm unable to reproduce the issue using the below code:
```C#
async Task MultipartUploadCopyWithRequestPayerTest(IAmazonS3 s3Client, string sourceBucket, string targetBucket, string sourceObjectKey, string targetObjectKey)
{
    // Create a list to store the upload part responses.
    List<UploadPartResponse> uploadResponses = new List<UploadPartResponse>();
    List<CopyPartResponse> copyResponses = new List<CopyPartResponse>();

    // Setup information required to initiate the multipart upload.
    InitiateMultipartUploadRequest initiateRequest =
        new InitiateMultipartUploadRequest
        {
            BucketName = targetBucket,
            Key = targetObjectKey,
            CannedACL = S3CannedACL.BucketOwnerFullControl,
            RequestPayer = RequestPayer.Requester
        };

    // Initiate the upload.
    InitiateMultipartUploadResponse initResponse =
        await s3Client.InitiateMultipartUploadAsync(initiateRequest);

    // Save the upload ID.
    String uploadId = initResponse.UploadId;

    try
    {
        // Get the size of the object.
        GetObjectMetadataRequest metadataRequest = new GetObjectMetadataRequest
        {
            BucketName = sourceBucket,
            Key = sourceObjectKey
        };

        GetObjectMetadataResponse metadataResponse =
            await s3Client.GetObjectMetadataAsync(metadataRequest);
        long objectSize = metadataResponse.ContentLength; // Length in bytes.

        // Copy the parts.
        long partSize = 5 * (long)Math.Pow(2, 20); // Part size is 5 MB.

        long bytePosition = 0;
        for (int i = 1; bytePosition < objectSize; i++)
        {
            CopyPartRequest copyRequest = new CopyPartRequest
            {
                DestinationBucket = targetBucket,
                DestinationKey = targetObjectKey,
                SourceBucket = sourceBucket,
                SourceKey = sourceObjectKey,
                UploadId = uploadId,
                FirstByte = bytePosition,
                LastByte = bytePosition + partSize - 1 >= objectSize ? objectSize - 1 : bytePosition + partSize - 1,
                PartNumber = i
            };

            copyResponses.Add(await s3Client.CopyPartAsync(copyRequest));

            bytePosition += partSize;
        }

        // Set up to complete the copy.
        CompleteMultipartUploadRequest completeRequest =
        new CompleteMultipartUploadRequest
        {
            BucketName = targetBucket,
            Key = targetObjectKey,
            UploadId = initResponse.UploadId
        };
        completeRequest.AddPartETags(copyResponses);

        // Complete the copy.
        CompleteMultipartUploadResponse completeUploadResponse =
            await s3Client.CompleteMultipartUploadAsync(completeRequest);
    }
    catch (AmazonS3Exception e)
    {
        Console.WriteLine("Error encountered on server. Message:'{0}' when writing an object", e.Message);
    }
    catch (Exception e)
    {
        Console.WriteLine("Unknown encountered on server. Message:'{0}' when writing an object", e.Message);
    }
}
```

Kindly note that I have Admin access to both buckets. I'm unsure if the credentials used to execute the Java code are same as the ones used for .NET code. The `Access Denied` error usually means the IAM role or credentials used to execute AWS service operation does not have proper permissions.

Also refer the post [S3:CopyObject - Access Denied](https://medium.com/collaborne-engineering/s3-copyobject-access-denied-5f7a6fe0393e) for reference where it specifies that you also need to have `S3:GetObjectTagging` and `S3:PutObjectTagging` permissions to copy objects with tags.

Please enable verbose logging to examine where the credentials are resolved for .NET code to troubleshoot further.

Thanks,
Ashish

**Comment by krishsingh-git** [comment]
there should be property request payer in copypartrequest class, Please update SDK

**Comment by ashishdhingra** [comment]
> there should be property request payer in copypartrequest class, Please update SDK

@krishsingh-git I have opened new issue https://github.com/aws/aws-sdk-net/issues/3081. This would be reviewed with the team.

**Comment by ashishdhingra** [comment]
The fix has been released in [AWSSDK.S3 version 3.7.205.22](https://www.nuget.org/packages/AWSSDK.S3/3.7.205.22).

**Comment by krishsingh-git** [comment]
Thanks
