### ISSUE TITLE
RestoreRequests returns XML Malformed when RetrievalTier = GlacierJobTier.Expedited

### ISSUE THREAD

**Issue by clovisdanielss** [aws/aws-sdk-net#3069]
### Describe the bug

When I tried to run the following code, I got the following error: The XML you provided was not well-formed or did not validate against our published schema. 

The code follows:
```
var restorationRequest = new RestoreObjectRequest
{
     BucketName = settings.Bucket,
     Days = days,
     Key = filename,
     RetrievalTier = GlacierJobTier.Expedited,
     Tier = GlacierJobTier.Expedited,
};
_ = await client.RestoreObjectAsync(restorationRequest);
```

I know that It may be too little information, but the operation goes wrong just when I set RetrivialTier or Tier. If I try to make the same request just with BucketName, Days and Key, it works fine. 

I was looking in others SDKs for S3 and I found similar issues. Like this one for Java: https://stackoverflow.com/questions/52166563/set-data-retrieval-option-on-s3-bucket-for-glacier-storage-class. And this one for ruby: https://github.com/boto/boto3/issues/2656.

I dont know what the main problem is, but I think that at least should indicate a more specific error message.

I think maybe is a bug. Idk. 

### Expected Behavior

It should at least show a more specific error message. 

### Current Behavior

The XML you provided was not well-formed or did not validate against our published schema

### Reproduction Steps

Try to RestoreObjectAsync like in this code:

```
var restorationRequest = new RestoreObjectRequest
{
     BucketName = settings.Bucket,
     Days = days,
     Key = filename,
     RetrievalTier = GlacierJobTier.Expedited,
     Tier = GlacierJobTier.Expedited,
};
_ = await client.RestoreObjectAsync(restorationRequest);
```

### AWS .NET SDK and/or Package version used

3.7.203.7

### Targeted .NET Platform

.NET 7.0

### Operating System and version

Windows 11

**Comment by ashishdhingra** [comment]
Needs to be reproduced.
