### ISSUE TITLE
AWS OIDC authentication failure (Incorrect token audience) with two applications

### ISSUE THREAD

**Issue by bagajjal** [aws/aws-sdk-net#3071]
### Describe the bug

I apologize if this issue seems out of place here. If it is, please inform me of the appropriate GitHub repository to move this issue.

I'm currently working on implementing AWS OIDC authentication with Azure AD (AAD) as the OpenID provider. I have two applications (appId1, appId2). When using appId1 to authenticate with AAD, I obtain a token for appId2, meaning that the AAD access token has appId2 as its audience. Subsequently, I invoke AssumeRoleWithWebIdentityAsync() by providing the AAD access token. This configuration functions properly with AAD access token V1 but encounters issues with AAD access token V2 i.e., AWS OIDC authentication was successful using AAD access token V1 but not with AAD access token V2.

When utilizing AAD access token V2, if I employ appId2 for authentication with AAD and obtain a token for itself (where the AAD access token has appId2 as its audience) and present this token, the AWS OIDC authentication succeeds.

I have confirmed that my AWS account has the correct OIDC authentication configuration. Specifically, I have added appId2 to the OIDC clientID list, and appId2 has been granted assumeRole permissions to the AWS IAM role.

This seems to be a bug in the AWS OIDC authentication using AAD V2 access tokens using two AAD applications.

Please look into the attached document for more details,
[AWS_V2_accesstoken_error.docx](https://github.com/aws/aws-sdk-net/files/12968773/AWS_V2_accesstoken_error.docx)

Code for AWS OIDC authentication using AAD V2 access token
`

    private async Task<AwsCredentials> AcquireAwsCredentials()
    {
        var token = await GetToken(this.solutionFirstPartyAppappId, this.solutionFirstPartyApptenantId, this.solutionFirstPartyAppcertpath, this.aadInstance, this.partnerAppId);

        var request = new AssumeRoleWithWebIdentityRequest
        {
            RoleSessionName = roleAuthorizationData.RoleSessionName,
            RoleArn = roleAuthorizationData.RoleArn,
            WebIdentityToken = token
        };

        AmazonSecurityTokenServiceClient amazonSecurityTokenServiceClient = new AmazonSecurityTokenServiceClient(new AnonymousAWSCredentials());

        var assumeRoleWithWebIdentityResponse = await amazonSecurityTokenServiceClient.AssumeRoleWithWebIdentityAsync(request);
        Console.WriteLine("Successfully got AWS temporary security credentials");
    }

    private static async Task<string> GetToken(string appId, string tenantId, string certPath, string aadInstance, string audience)
    {
        bool withSendX5C = false;
        var clientCert = new X509Certificate2(certPath);
        var azureRegion = ConfidentialClientApplication.AttemptRegionDiscovery;
        var authority = $"https://login.microsoftonline.com/{tenantId}/oauth2/v2.0/token";
        var application = ConfidentialClientApplicationBuilder.Create(appId)
        .WithCertificate(clientCert, withSendX5C)
        .WithAuthority(authority)
        .WithAzureRegion(azureRegion)
        .Build();
        var requestBuilder = application.AcquireTokenForClient(new string[] { $"api://{audience}/.default" });
        if (withSendX5C)
        {
            requestBuilder = requestBuilder.WithSendX5C(true);
        }

        AuthenticationResult authResult = await requestBuilder.ExecuteAsync();
        Console.WriteLine($"AAD Token: {authResult.AccessToken}");

        return authResult.AccessToken;
    }
`

### Expected Behavior

AWS OIDC authentication should succeed. 

### Current Behavior

AWS OIDC authentication fails with "Incorrect token audience" if we use AAD v2 access token with 2 applications.

### Reproduction Steps

1. Create 2 applications in AAD, Azure AD.
2. Using appId1 credentials authenticate with AD and request token for appId2. i.e., AAD will return AAD V2 access token with audience as appId2.
3. Now call the AssumeRoleWithWebIdentityAsync()
4. AWS OIDC authentication call fails with "Incorrect token audience".

### AWS .NET SDK and/or Package version used

"AWSSDK.SecurityToken" Version="3.7.102.2" 

### Targeted .NET Platform

.NET 7

### Operating System and version

Windows 11

**Comment by bagajjal** [comment]
+ @normj

**Comment by bagajjal** [comment]
@normj, @ashishdhingra, could you please have a look at this issue.

**Comment by ashishdhingra** [comment]
@bagajjal Good morning. I do not think this is an SDK issue. Could you please refer https://repost.aws/knowledge-center/eks-troubleshoot-oidc-and-irsa which has details on how to check if the audience is correct?

Thanks,
Ashish

**Comment by bagajjal** [comment]
@ashishdhingra, I refer to https://repost.aws/knowledge-center/eks-troubleshoot-oidc-and-irsa but it didn't answer my question.
Is there a different GitHub repository that I can post this question?

**Comment by bagajjal** [comment]
@ashishdhingra , this seems to be a clear bug on AWS side as the same setup (using 2 applications) works for AAD V1 access token but not for the AAD v2 access token.

**Comment by ashishdhingra** [comment]
> @ashishdhingra , this seems to be a clear bug on AWS side as the same setup (using 2 applications) works for AAD V1 access token but not for the AAD v2 access token.

@bagajjal Could you please confirm your audience for OIDC? I'm unsure if something changed in AAD V2. Kindly note that most of the `AWSSDK.SecurityToken` package is autogenerated, hence doesn't appear to be AWS .NET SDK issue. The error clearly indicates that incorrect audience is set.

The audience is configured while creating identity provider as shown below:
![Screenshot 2023-10-24 at 3 41 56 PM](https://github.com/aws/aws-sdk-net/assets/67916761/a52651d6-6454-40e4-951e-df8f9aae7cb9)

Also refer [Creating OpenID Connect (OIDC) identity providers](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc.html?icmpid=docs_iam_help_panel_create) if you want to add additional audiences (client IDs).

Could you also share the minimal code solution and set up steps, that reproduces the issue?

Thanks,
Ashish

**Comment by bagajjal** [comment]
@ashishdhingra,  I did the recording for both AAD V2 access token (Failed case)  and the AAD V1 access token. Please reopen this issue for tracking.

AAD V2 access token [recording](https://balupublicclouds.blob.core.windows.net/aws-oidc-auth/AWS%20OIDC%20-%20AAD%20v2%20access%20token%20failure.mp4)
AAD V1 access token [recording](https://balupublicclouds.blob.core.windows.net/aws-oidc-auth/AWS%20OIDC%20auth%20v1%20access%20token%20working.mp4)

**Comment by bagajjal** [comment]
Please find the AWS Cloud formation template used in both the cases.

[AWS-OIDCauth-V1.txt](https://github.com/aws/aws-sdk-net/files/13302135/OIDCauth-V1-outlook-tenant.txt)
[AWS-OIDCauth-V2.txt](https://github.com/aws/aws-sdk-net/files/13302136/OIDCauth-V2-outlook-tenant.txt)

**Comment by bagajjal** [comment]
@ashishdhingra , any update?
