### ISSUE TITLE
SQS Attribute MD5 mismatch for the Binary type.

### ISSUE THREAD

**Issue by vburenin** [aws/aws-sdk-net#308]
Hi folks,

I am experiencing this issue when I am trying to calculate MD5 hash for the binary typed attribute.
Issue is reproducible even for one attribute.

'MessageAttribute.1.Name': 'testname',
'MessageAttribute.1.Value.DataType': 'Binary',
'MessageAttribute.1.Value.BinaryValue': '123',

The MD5 I get from SQS is 7aad2f4b0331285b6ce9683fe98ae563

When I try to calculate the same hash on my end, I get 4969dd151b0a6c8b619ebb802f76e035

Another issue that could point to the problem is that if binary value is just one byte I get this error back from SQS:
```

<?xml version="1.0"?>
<ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/">
  <Error>
    <Type>Sender</Type>
    <Code>InvalidParameterValue</Code>
    <Message>The message attribute \'testname\' must contain non-empty message attribute value for message attribute type \'Binary\'.</Message>
    <Detail/>
  </Error>
  <RequestId>1ecd79c5-5ff9-51ce-9d99-36fe3ddbaf5b</RequestId>
</ErrorResponse>
```

For types String and Number MD5 checksum matches as expected.

Thoughts?

**Comment by PavelSafronov** [comment]
Can you post your code? The below sample works and stepping through the code I can see that the MD5 that the SDK calculates matches what the service sends over, 4969dd151b0a6c8b619ebb802f76e035.
```
var request = new SendMessageRequest
{
    QueueUrl = queueURL,
    MessageBody = "The quick brown fox jumped over the lazy dog",
    MessageAttributes = new Dictionary<string, MessageAttributeValue>
    {
        {
            "testname",
            new MessageAttributeValue
            {
                DataType = "Binary",
                BinaryValue = new MemoryStream(Encoding.UTF8.GetBytes("123"))
            }                    
        }
    }
};
var response = Client.SendMessage(request);
```

**Comment by vburenin** [comment]
This is a sample code I use to send a request:

```
def code_test1():
    conn = boto.connect_sqs()
    params = {
        'MessageBody': 'еуые',
        'DelaySeconds': 0,
        'MessageAttribute.1.Name': 'testname',
        'MessageAttribute.1.Value.DataType': 'Binary',
        'MessageAttribute.1.Value.BinaryValue': '123',
    }
    q = conn.get_queue('vbtestqueue')
    m = conn.get_object('SendMessage', params, Message, q.id, verb='POST')
    print(m.md5_message_attributes)
```

Response I get back is:

```
<?xml version="1.0"?><GetQueueUrlResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><GetQueueUrlResult><QueueUrl>https://sqs.us-west-2.amazonaws.com/722908396484/vbmytest123</QueueUrl></GetQueueUrlResult><ResponseMetadata><RequestId>b53118c3-cee4-5d0c-9fd0-57ff9385d3db</RequestId></ResponseMetadata></GetQueueUrlResponse>' 200
b'<?xml version="1.0"?><SendMessageResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><SendMessageResult><MessageId>4905b3f1-ced5-4472-b2d8-9f9cbf4fc7ba</MessageId><MD5OfMessageAttributes>7aad2f4b0331285b6ce9683fe98ae563</MD5OfMessageAttributes><MD5OfMessageBody>e33b26a38b9a575159b5dd5ef3290090</MD5OfMessageBody></SendMessageResult><ResponseMetadata><RequestId>7e40bcfe-c556-52d8-be3b-f3c298371c0f</RequestId></ResponseMetadata></SendMessageResponse>'
```

MD5OfMessageAttributes: 7aad2f4b0331285b6ce9683fe98ae563

I use hand written piece of code in Go to calculate MD5 of message attributes. I get exactly what you posted.
You can find that code here: https://github.com/vburenin/firempq/blob/sqs_proto/server/sqsproto/send_message/send_message.go#L80

**Comment by vburenin** [comment]
Found the problem. Problem is in boto2 library. It builds a little malformed SQS request that is not well parsed by SQS service, so it ends up with the wrong MD5. Switching to boto3 resolved the problem.

**Comment by PavelSafronov** [comment]
Looks like this is also fixed in boto: https://github.com/boto/boto/commit/f2dcdbe067a102935fa47e18f1f074cacce9d2fd

**Comment by vburenin** [comment]
Not sure it can fix it. I issue request as this

```
def code_test1():
    conn = boto.connect_sqs()
    params = {
        'MessageBody': 'some random data',
        'DelaySeconds': 0,
        'MessageAttribute.1.Name': 'testname',
        'MessageAttribute.1.Value.DataType': 'Binary',
        'MessageAttribute.1.Value.BinaryValue': '123',
    }
    queue = conn.get_queue('testqueuename')
    m = conn.get_object('SendMessage', params, Message, queue.id, verb='POST')
    print(m.md5_message_attributes)
```

I prepare all attributes manually, it seems like problem is closer to the wire layer. I didn't dig really deep.

However, thanks for the response.

**Comment by vburenin** [comment]
More data on this. SQS expects binary data to be base64 encoded which is not clearly documented. Finally hijacking deep into source code I found where it happens.
