### ISSUE TITLE
IOException calling IAmazonSQS.ReceiveMessageAsync

### ISSUE THREAD

**Issue by mdemler** [aws/aws-sdk-net#3080]
### Describe the bug

Our handled exception handling caught this error when calling IAmazonSQS.ReceiveMessageAsync.  This is the one and only time that we've seen this error.

System.IO.IOException: Unable to write data to the transport connection: Connection reset by peer.
  ?, in async Task<IWebResponseData> HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
  ?, in async Task<T> HttpHandler<TRequestContent>.InvokeAsync<T>(IExecutionContext executionContext)
  ?, in async Task<T> Unmarshaller.InvokeAsync<T>(IExecutionContext executionContext)
  ?, in async Task<T> ValidationResponseHandler.InvokeAsync<T>(IExecutionContext executionContext)
  ?, in async Task<T> ErrorHandler.InvokeAsync<T>(IExecutionContext executionContext) x 2
  ?, in async Task<T> CallbackHandler.InvokeAsync<T>(IExecutionContext executionContext)
  ?, in async Task<T> Signer.InvokeAsync<T>(IExecutionContext executionContext)
  ?, in async Task<T> EndpointDiscoveryHandler.InvokeAsync<T>(IExecutionContext executionContext) x 2
  ?, in async Task<T> CredentialsRetriever.InvokeAsync<T>(IExecutionContext executionContext)
  ?, in async Task<T> RetryHandler.InvokeAsync<T>(IExecutionContext executionContext) x 2
  File "AWSTracingPipelineHandler.cs", line 101, in async Task<T> AWSTracingPipelineHandler.InvokeAsync<T>(IExecutionContext executionContext)
    }
  ?, in async Task<T> CallbackHandler.InvokeAsync<T>(IExecutionContext executionContext) x 2
  ?, in async Task<T> ErrorCallbackHandler.InvokeAsync<T>(IExecutionContext executionContext)
  ?, in async Task<T> MetricsHandler.InvokeAsync<T>(IExecutionContext executionContext)
  File "/_/Konducter.Notification.Service/NotificationQueueProcessor.cs", line 131, col 9, in async Task<List<ReceivedMessage>> NotificationQueueProcessor.ReceiveAsync(CancellationToken cancellationToken)

### Expected Behavior

The SDK should be catching and handling this error, reporting to the caller as an AmazonSQSException or some other documented exception.

### Current Behavior

The exception is thrown through to the caller.

### Reproduction Steps

Random error; unable to reproduce.

### AWS .NET SDK and/or Package version used

AWSSDK.SQS 3.7.200.33

### Targeted .NET Platform

.NET 7

### Operating System and version

Linux 5.10.192

**Comment by ashishdhingra** [comment]
@mdemler Thanks for reporting the issue. The error `System.IO.IOException: Unable to write data to the transport connection: Connection reset by peer.` indicates some network connectivity issue. The AWS SDK for .NET has retry mechanism for failed service calls, refer [Retries and timeouts](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/retries-timeouts.html).
- Do you see any data loss for the AWS operation invoked (in this case it appears to be processing SQS messages)?
- When did the error 1st started happening?
- What is the application setup looks like?
- Could you provide verbose logs? These could be enabled using below code:
  ```C#
  Amazon.AWSConfigs.LoggingConfig.LogResponses = Amazon.ResponseLoggingOption.Always;
  Amazon.AWSConfigs.LoggingConfig.LogTo = Amazon.LoggingOptions.SystemDiagnostics;
  Amazon.AWSConfigs.AddTraceListener("Amazon", new System.Diagnostics.ConsoleTraceListener());
  ```
- Sample code to reproduce the issue (I see that you mentioned that the error is random, so inputs for above questions might help)
- How are AWS credentials configured for your application?

Thanks,
Ashish

**Comment by mdemler** [comment]
We've only seen this happen the one time on October 22 at 11:57 PM Pacific.

This was experienced in a Fargate controlled container that's been running without issue for 6+ months.

A background task/thread continually executes within this process and calls IAmazonSQS.ReceiveMessageAsync(ReceiveMessageRequest) with MaxNumberOfMessages=10 and WaitTimeSeconds=20.

Our application caught this exception within a last resort exception handler.  While it didn't formally experience data loss, it would have aborted the task that was processing the message queue, meaning no new messages would be processed until the container was restarted.

We are currently only catching AmazonSQSExceptions as expected to be thrown from IAmazonSQS.ReceiveMessageAsync(), as the SDK documentation doesn't provide a full list of what's expected on a call-by-call basis that I've seen.  Should we be extending this to catch IOExceptions and others, or is this indeed something within the SDK that it's not handling correctly?

**Comment by ashishdhingra** [comment]
> We've only seen this happen the one time on October 22 at 11:57 PM Pacific.
> 
> This was experienced in a Fargate controlled container that's been running without issue for 6+ months.
> 
> A background task/thread continually executes within this process and calls IAmazonSQS.ReceiveMessageAsync(ReceiveMessageRequest) with MaxNumberOfMessages=10 and WaitTimeSeconds=20.
> 
> Our application caught this exception within a last resort exception handler. While it didn't formally experience data loss, it would have aborted the task that was processing the message queue, meaning no new messages would be processed until the container was restarted.
> 
> We are currently only catching AmazonSQSExceptions as expected to be thrown from IAmazonSQS.ReceiveMessageAsync(), as the SDK documentation doesn't provide a full list of what's expected on a call-by-call basis that I've seen. Should we be extending this to catch IOExceptions and others, or is this indeed something within the SDK that it's not handling correctly?

@mdemler As mentioned in my previous comment, `IOException` could occur due to variety of reasons, some of which are not controlled by SDK. In such cases, the application should be resilient and catch/log such errors, without terminating the process. In ideal case, the exception should bubble up to a global exception handler which logs this error for further troubleshooting.

Thanks,
Ashish
