### ISSUE TITLE
S3 TransferUtility UploadAsync with non seekable stream is not sending metadata or headers

### ISSUE THREAD

**Issue by ymor** [aws/aws-sdk-net#3082]
### Describe the bug

When using the UploadAsync method on the S3 TransferUtility with an input stream that is non seekable.  Provided metadata is not been stored against the object

### Expected Behavior

The metadata I set on the TransferUtilityUploadRequest  to be stored with the object

### Current Behavior

The metadata provided on the TransferUtilityUploadRequest  is not stored against the object

### Reproduction Steps

Essentially I'm using this example https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/mvc/models/file-uploads/samples/5.x/LargeFilesSample/Controllers
However instead of storing it to disk I'm passing it to the TransferUtility to upload.  The underlying stream is the HttpRequestStream which is non seekable

### Possible Solution

https://github.com/aws/aws-sdk-net/blob/0015a303eeba3e74c0c5bdf06003182a36a3c582/sdk/src/Services/S3/Custom/Transfer/Internal/_async/MultipartUploadCommand.async.cs#L198
Construct the InitiateMultipartUploadRequest with the metadata provided in the  TransferUtilityUploadRequest 

### AWS .NET SDK and/or Package version used

AWSSDK.S3 3.7.205.15

### Targeted .NET Platform

.net 7

### Operating System and version

Ubuntu

**Comment by ashishdhingra** [comment]
Reproducible with below code:
```C#
string bucketName = "some-testbucket";

using (AmazonS3Client amazonS3Client = new AmazonS3Client(RegionEndpoint.USEast2))
{
    // Stream returned by HttpClient.GetStreamAsync() is non-seekable
    HttpClient hc = new HttpClient();
    ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
    Stream nonSeekableWebStream = await hc.GetStreamAsync("https://www.google.com");

    TransferUtilityUploadRequest transferUtilityUploadRequest = new TransferUtilityUploadRequest()
    {
        BucketName = bucketName,
        Key = "testfile1.txt",
        InputStream = nonSeekableWebStream
    };

    transferUtilityUploadRequest.Metadata.Add("testmetadata", "testvalue");
    TransferUtility transferUtility = new TransferUtility(amazonS3Client);
    await transferUtility.UploadAsync(transferUtilityUploadRequest); // The uploaded file doesn't has metadata

    // Get seekable stream
    using (var seekableMemoryStream = new MemoryStream())
    {
        (await hc.GetStreamAsync("https://www.google.com")).CopyTo(seekableMemoryStream);
        seekableMemoryStream.Position = 0;

        transferUtilityUploadRequest = new TransferUtilityUploadRequest()
        {
            BucketName = bucketName,
            Key = "testfile2.txt",
            InputStream = seekableMemoryStream
        };

        transferUtilityUploadRequest.Metadata.Add("testmetadata", "testvalue");
        await transferUtility.UploadAsync(transferUtilityUploadRequest); // The uploaded file will have metadata
    }
}
```

Needs review with the team.

**Comment by ymor** [comment]
@ashishdhingra Thank you for sorting out some reproducible code. I was going to have a go at writing a small example myself today!  
One other thing to notes is that headers are also not correctly sent.

**Comment by ashishdhingra** [comment]
Fix released in [AWSSDK.S3 (3.7.205.24)](https://www.nuget.org/packages/AWSSDK.S3/3.7.205.24).
