### ISSUE TITLE
Error Handling for SimpleUploadCommand

### ISSUE THREAD

**Issue by lklein53** [aws/aws-sdk-net#3093]
### Describe the feature

If I am not missing something it's currently not possible to notice if the SimpleUploadCommand invoked via the TransferUtility, in case a MultipartUpload is not suitable, failed or not. The HttpStatus code of the internally used PutObjectResponse is not exposed nor is an exception thrown in case of a not success status code. 

### Use Case

Be able to check if the SimpleUploadCommand actually succeeded without having to make another S3 API call.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

AWSSDK.S3 3.7.205.14

### Targeted .NET Platform

.NET 7

### Operating System and version

Ubuntu

**Comment by ashishdhingra** [comment]
@lklein53 Thanks for opening feature request. Looking at [SimpleUploadCommand.ExecuteAsync()](https://github.com/aws/aws-sdk-net/blob/3d2233db3a09e3e310904b215f4d640cc923dc9a/sdk/src/Services/S3/Custom/Transfer/Internal/_async/SimpleUploadCommand.async.cs#L41), you are correct that it doesn't expose underlying `PutObjectResponse` object. If you check [PutObject](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html) API documentation, it returns bunch of headers along with HTTP status code. In case of error from the service, SDK in this scenario, uses [S3ReponseUnmarshaller.UnmarshallException()](https://github.com/aws/aws-sdk-net/blob/3d2233db3a09e3e310904b215f4d640cc923dc9a/sdk/src/Services/S3/Custom/Model/Internal/MarshallTransformations/S3ReponseUnmarshaller.cs#L99C48-L99C67) and return it to the calling code as [AmazonS3Exception](https://github.com/aws/aws-sdk-net/blob/3d2233db3a09e3e310904b215f4d640cc923dc9a/sdk/src/Services/S3/Custom/AmazonS3Exception.cs#L30C18-L30C35) exception object.

Are you not getting exception in case of error from service or some environmental exception conditions? Please confirm.

Thanks,
Ashish

**Comment by lklein53** [comment]
thanks for the quick response. Sorry my mistake, should have looked more carefully. In my tests i just mocked away the PutObject method of the client which of course will not use the [S3ReponseUnmarshaller.UnmarshallException()](https://github.com/aws/aws-sdk-net/blob/3d2233db3a09e3e310904b215f4d640cc923dc9a/sdk/src/Services/S3/Custom/Model/Internal/MarshallTransformations/S3ReponseUnmarshaller.cs#L99C48-L99C67)
