### ISSUE TITLE
Calling AmazonS3Client.GetObjectAsync() on lambda function take too long (~5s) on the first invoke

### ISSUE THREAD

**Issue by hoainam1593** [aws/aws-sdk-net#3116]
### Describe the bug

I'm using S3 client in lambda function, this is my code:
```
public class SomeLambdaFunction
{
    public async Task<string> Handler(string input, ILambdaContext context)
    {
        var client = new AmazonS3Client();
        // begin stop watch
        await client.GetObjectAsync("<bucket-name>", "<object-key>");
        //end stopwatch and see took ~5s
    }
}
```
when I deploy and invoke in the first time, it took ~5s to execute client.GetObjectAsync, when I run later (reuse lambda instance), it complete instantly

### Expected Behavior

AmazonS3Client.GetObjectAsync complete instantly on any invoke

### Current Behavior

AmazonS3Client.GetObjectAsync take too long in the first invoke

### Reproduction Steps

- write lambda function using S3
- call a S3 API after deploy
- do benchmark that calling and see that calling take too long

### AWS .NET SDK and/or Package version used

AWSSDK.S3 3.7.304.1

### Targeted .NET Platform

.net 6.0

### Operating System and version

lambda environment

**Comment by ashishdhingra** [comment]
> @hoainam1593 Good morning. Thanks for opening the issue. The 1st invocation could take long due to Lambda cold start times, also you confirmed that the subsequent executions happen almost instantaneously. You may also try temporarily enabling verbose logging to see any SDK logic causing delay using code below:
> 
> ```cs
> Amazon.AWSConfigs.LoggingConfig.LogResponses = Amazon.ResponseLoggingOption.Always;
> Amazon.AWSConfigs.LoggingConfig.LogTo = Amazon.LoggingOptions.Console;
> Amazon.AWSConfigs.AddTraceListener("Amazon", new System.Diagnostics.ConsoleTraceListener());
> ```
> 
> Thanks, Ashish

@hoainam1593 Could you please share the Lambda memory settings as well?

**Comment by hoainam1593** [comment]
I used the lowest one 128MB

**Comment by ashishdhingra** [comment]
@hoainam1593 We recently pushed a new version `AWSSDK.Core` version `3.7.300.18` that contained fix for performance degradation reported as part of another issue. Could you please check if upgrading to this version (or later) fixes your issue?

Thanks,
Ashish
