### ISSUE TITLE
Can I post a object with content-encoding:gzip to s3 bucket?

### ISSUE THREAD

**Issue by pchuri** [aws/aws-sdk-net#312]
I'd like to post a gzipped file with content-encoding:gzip to s3 bucket by using unityv3 branch of aws-sdk-net.
Can I append the content-encoding header?

**Comment by johnnyhoffman** [comment]
You can do this with PutObjectAsync, assuming you are using the newly supported UnityWebRequest HttpClient. For example:
To have the SDK use UnityWebRequest: 
 ```AWSConfigs.HttpClient = AWSConfigs.HttpClientOption.UnityWebRequest;```
Creating the request:
```
var request = new PutObjectRequest()
{
    BucketName = bucketName,
    Key = fileName,
    InputStream = stream
};
request.Headers.ContentEncoding = "gzip";
```

**Comment by pchuri** [comment]
@johnnyhoffman Thank you for your answer :smiley:
