### ISSUE TITLE
Performance Degradation and Increased Allocation in AWSSDK.S3 Versions 3.7.107.4 and Above

### ISSUE THREAD

**Issue by SonalCalcey** [aws/aws-sdk-net#3122]
### Describe the bug

We have identified a performance degradation in our API after updating the AWSSDK.S3 package to the latest version 3.7.304.1. 
Upon investigation, we have identified that performance degradation is occurring after the AWSSDK.S3 version 3.7.107.4. 

Furthermore, we have done a Benchmark test for the AWS SDK.S3 versions such as
- 3.7.107.3
- 3.7.107.4
- 3.7.304.1

To help you better understand the issue, we have prepared a sample description highlighting the key observations and differences.

### Expected Behavior

Expected to have similar performance and allocation rate for as **AWSSDK.S3 - 3.7.107.3** after the Nuget package update.

### Current Behavior

(Benchmark results were taken using [BenchmarkDotNet](https://github.com/dotnet/BenchmarkDotNet) **v0.13.10**)

**Summary for the AWS SDK.S3 3.7.107.3**

![s3-sdk-3 7 107 3-benchmark-result](https://github.com/aws/aws-sdk-net/assets/139344044/ff452fb8-e495-45d3-9121-7b59ce724d16)

Benchmark log: [s3-sdk-3.7.107.3-benchmark.log](https://github.com/aws/aws-sdk-net/files/13511443/s3-sdk-3.7.107.3-benchmark.log)

**Summary for the AWS SDK.S3 3.7.107.4**

![s3-sdk-3 7 107 4-benchmark-result](https://github.com/aws/aws-sdk-net/assets/139344044/7ae5ab05-15d5-4c08-a6de-6fd5d29b3bae)

Benchmark log: [s3-sdk-3.7.107.4-benchmark.log](https://github.com/aws/aws-sdk-net/files/13511463/s3-sdk-3.7.107.4-benchmark.log)

**Summary for the AWS SDK.S3 3.7.304.1**

![s3-sdk-3 7 304 1-benchmark-result](https://github.com/aws/aws-sdk-net/assets/139344044/4cc322d4-e340-4b04-afe5-0e4448a42b9d)

Benchmark log: [s3-sdk-3.7.304.1-benchmark.log](https://github.com/aws/aws-sdk-net/files/13511507/s3-sdk-3.7.304.1-benchmark.log)

### Reproduction Steps

**Code used for the Benchmark:** 

![code](https://github.com/aws/aws-sdk-net/assets/139344044/13db39e1-5e3c-4571-b424-2fe8c79f6431)

### AWS .NET SDK and/or Package version used

AWSSDK.S3 - 3.7.107.3
AWSSDK.S3 - 3.7.107.4
AWSSDK.S3 - 3.7.304.1

### Targeted .NET Platform

.NET Framework 7

### Operating System and version

Windows 10 Enterprise

**Comment by ashishdhingra** [comment]
Perhaps issue https://github.com/aws/aws-sdk-net/issues/3116 is similar.

**Comment by SonalCalcey** [comment]
The issue is similar to this https://github.com/aws/aws-sdk-net/issues/3116, but each signed URL generation has a high memory allocation rate as well.

**Comment by afroz429** [comment]
Thanks for the reporting the issue and taking time to pinpoint the exact version where the performance degradation started. These details were very helpful in identifying the root cause. The issue was with the AWSSDK Core and we resolved it in 3.7.300.18. The latest nuget packages already shipped with this fix.
