### ISSUE TITLE
Region is lost for AwsSigV4HttpConnection when using AssumeRoleAWSCredentials

### ISSUE THREAD

**Issue by isaacws** [aws/aws-sdk-net#3135]
### Describe the bug

**Summary:**
Given a basic aws credential that assumes a role for access to an Opensearch serverless endpoint, when the access token refreshes then I find logs trying to access "GET 169.254.169.254/latest/dynamic/instance-identity/document" which times out causing latency in my application. This indicates that the region is not being found on the token refresh and the credential search is trying to find the region and finally failing to query EC2 instance metadata. This introduces 5 seconds of latency on these token refresh requests. The app still continues to work and the token does refresh but the region search causes issues in my logs and latency in the application. The search behavior is found in the following file. https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/AWSRegion.cs#L179
 

### Expected Behavior

When using an AssumeRoleAWSCredential and specifying the region on creation of the AwsSigV4HttpConnection, token refreshes should pull the region from that specified in the AwsSigV4HttpConnection.

### Current Behavior

Given a basic aws credential that assumes a role for access to an Opensearch serverless endpoint, when the access token refreshes then I find logs trying to access "GET 169.254.169.254/latest/dynamic/instance-identity/document" which times out causing latency in my application.

### Reproduction Steps
```C#
//Ensure that credentials are not in the environment or profile but just passed in via strings.
var awsCredential = new BasicAWSCredentials(credentials.AccessKey, credentials.Secret);
var newCredentials = new AssumeRoleAWSCredentials(
                                                       awsCredential,
                                                       roleArn,
                                                       "opensearch-session");
var connection = new AwsSigV4HttpConnection(newCredentials, RegionEndpoint.USEast2, "aoss");
var connectionSettings = new ConnectionSettings(endpointUri, connection);
var openSearchClient = new OpenSearchClient(connectionSettings);
//wait for token refresh to occur.
```

### Possible Solution

**Work around:**
Set the AWS_REGION environment variable so that the fall through region search finds something. This is less than optimal when utilizing multiple AWS credentials and regions.

### Additional Information/Context

Token refresh for assumed credentials appears to happen hourly.

### AWS .NET SDK and/or Package version used

AWSSDK.Core 3.7.202.5

### Targeted .NET Platform

.Net 6.0, .net framework 4.72

### Operating System and version

Windows Server 2019

**Comment by ashishdhingra** [comment]
@isaacws Good morning. [AwsSigV4HttpConnection](https://opensearch-project.github.io/opensearch-net/api/OpenSearch.Net.Auth.AwsSigV4.AwsSigV4HttpConnection.html) is the class in [OpenSearch .NET Client](https://opensearch-project.github.io/opensearch-net/index.html) library. It has `RegionEndpoint` as one of the parameters in the constructor. This library is not maintained by AWS SDK team. Have you tried opening the issue in their support forums where the library might not be setting the region in client configuration internally?

Thanks,
Ashish

**Comment by isaacws** [comment]
@ashishdhingra Thank you for the clarification. Perhaps this would be better suited in the AwsSigV4HttpConnection suite. I'll open the issue there. It could be a combination of factors between the two packages. It is definitely following the escalation search ending in the EC2 on token refresh which made me think it was something in the AssumeRoleAWSCredentials

**Comment by isaacws** [comment]
Created bug with OpenSearch .Net Client github. https://github.com/opensearch-project/opensearch-net/issues/490

**Comment by ashishdhingra** [comment]
@isaacws Since you have opened issue in OpenSearch repo, please confirm if we could close the issue here.

**Comment by isaacws** [comment]
I did receive a response back from the OpenSearch team. Here is a link to why this issue should be in the AWS-SDK project. 

https://github.com/opensearch-project/opensearch-net/issues/490#issuecomment-1880213351

Given this information, it seems to me AssumeRoleAWSCredentials should accept a region, after all it is on credential refresh that it can't find the region and then fails. I misunderstood the mechanism by which the AwsSigV4HttpConnection was used in this context. The region is only related to signature calculations for this object. The token refresh is however dealt with by the SDK and that is where region is not being found in my use case.

**Comment by ashishdhingra** [comment]
> opensearch-project/opensearch-net#490 (comment)

@isaacws Could you please advise how you came to conclusion that credential search is causing region to be probed? Refer [Assume role credential provider](https://docs.aws.amazon.com/sdkref/latest/guide/feature-assume-role-credentials.html), where there is no dependency on the region.

What SDK operation your application and opensearch library trying to invoke when you notice the latency? If the region endpoint is not provided while invoking SDK service operation, then SDK would try to probe the region.

Thanks,
Ashish

**Comment by isaacws** [comment]
We are using datadog and I can see a probe to try to get region and failing all the way back to EC2. I assume without digging further this occurs on  [GenerateNewCredentials](https://github.com/aws/aws-sdk-net/blob/d64a655c697f705bf1d93593f5b03000d2527038/sdk/src/Core/Amazon.Runtime/Credentials/AssumeRoleAWSCredentials.cs#L98)

**Comment by normj** [comment]
@isaacws Since you said the request to instance metadata times out. Do you know if you have disabled instance metadata on the EC2 instances? You can tell the SDK to not use EC2 instance metadata by setting the `AWS_EC2_METADATA_DISABLED` environment variable to `true`.

**Comment by isaacws** [comment]
@normj My setup is literally the reproduction code. I do not have any environmental variables set. All values are passed into the classes manually from strings. The issue was worked around by setting the region in the environmental variable but I would not think that is ideal when dealing with multiple regions and aws accounts.

**Comment by normj** [comment]
@isaacws My question was more how was the EC2 instance setup. I'm trying to figure out why you are getting time out even reaching instance metadata service. The way the `FallbackRegionFactory` works is once it ever resolves a region it caches the result and used that for all future calls for `GetRegionEndpoint`. You can see that here https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/AWSRegion.cs#L179

So in your situation it seems like instance metadata service is never accessible. Or am I misunderstanding the situation and you are not even running on an EC2 environment but the code is still trying to go to EC2 instance metadata and slowly failing.

**Comment by isaacws** [comment]
Sorry for the slow response here as I have been on vacation. I am not running an EC2 instance. The region search ends on the EC2 method. I am not running EC2 at all so the EC2 query is what times out.

**Comment by m0a0k0s** [comment]
I have a similar issue on one of the self-hosted environments (not in AWS). IAmazonS3 and IAmazonBedrockRuntime registered through AWSSDK.Extensions.NETCore.Setup with the region set in services.AddDefaultAWSOptions. When I debug locally, it fails immediately with 'A socket operation was attempted to an unreachable network. (169.254.169.254:80) System.Net.Sockets.SocketException (10051): A socket operation was attempted to an unreachable network.' But in the environment setup, it looks like 169.254 is something legit and it makes 5 retries with 5 seconds delay each before continue processing the request. The error happens on DI dependency initialization.

**Comment by m0a0k0s** [comment]
config.DefaultConfigurationMode here https://github.com/aws/aws-sdk-net/blob/a55fc1e7cc85d1c3f09965af12676e973679724a/extensions/src/AWSSDK.Extensions.NETCore.Setup/ClientFactory.cs#L246
trigger default region fallback in `_defaultConfigurationProvider.GetDefaultConfiguration(RegionEndpoint, defaultConfigurationMode)`
