### ISSUE TITLE
Deregistration of token device on iOS

### ISSUE THREAD

**Issue by janv97** [aws/aws-sdk-net#3137]
### Describe the bug

We are experiencing a problem receiving web push notifications in a PWA on iOS device. At the moment the device is registered in the PWA we receive all the push notifications. If we then minimize the PWA and receive another notification at that time. Then the device is deregistered at a sudden. Probably because the device token is nog longer recognized by AWS SNS or Firebase.

By te way, this work fine on Android, but not on iOS. We send our web push notifications via AWS SNS with Firebase.

### Expected Behavior

We expect te token/device not to be deregistered when receiving a notification while the PWA is minimized. Basically just as it works now with Android devices.

### Current Behavior

-

### Reproduction Steps

-

### AWS .NET SDK and/or Package version used

AWSSDK.SimpleNotificationService 3.7.300.20

### Targeted .NET Platform

.NET 7

### Operating System and version

iOS 17.1.1

**Comment by dscpinheiro** [comment]
Would it be possible to share reproduction steps and the current behavior you're seeing? Unfortunately right now there isn't enough information for us to investigate the problem.
