### ISSUE TITLE
PutObjectRequest with a stream taken directly from GetObjectResponse throws exception

### ISSUE THREAD

**Issue by grsw92** [aws/aws-sdk-net#3146]
### Describe the bug

I have a sample of a really basic copy file scenario using file streams, which does not work. It performs PutObject operation with using a stream received from GetObject operation.

### Expected Behavior

The PUT operation on a stream received from GET operation is expected to be working out of the box

### Current Behavior

 The scenario fails on second put object with following exception:
```
Unhandled exception. Amazon.S3.AmazonS3Exception: Could not determine content length
   at Amazon.S3.Model.Internal.MarshallTransformations.PutObjectRequestMarshaller.GetStreamWithLength(Stream baseStream, Int64 hintLength)
   at Amazon.S3.Model.Internal.MarshallTransformations.PutObjectRequestMarshaller.Marshall(PutObjectRequest putObjectRequest)
   at Amazon.S3.Model.Internal.MarshallTransformations.PutObjectRequestMarshaller.Marshall(AmazonWebServiceRequest input)
   at Amazon.Runtime.Internal.Marshaller.PreInvoke(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Marshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3PreMarshallHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.PipelineHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.<>n__0[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
```

### Reproduction Steps

```
public static async Task Run(AmazonS3Client s3Client, string bucket, string key, CancellationToken cancellationToken)
{
    // upload file
    var content = Guid.NewGuid().ToString();
    await s3Client.PutObjectAsync(new PutObjectRequest
    {
        BucketName = bucket,
        Key = key,
        InputStream = new MemoryStream(Encoding.UTF8.GetBytes(content)),
        AutoCloseStream = true
    }, cancellationToken);

    // copy file
    // get file stream
    var result = await s3Client.GetObjectAsync(new GetObjectRequest
    {
        BucketName = bucket,
        Key = key,
    }, cancellationToken);

    // put file stream - throws
    await s3Client.PutObjectAsync(new PutObjectRequest
    {
        BucketName = bucket,
        Key = $"{key}_1",
        InputStream = result.ResponseStream,
        AutoCloseStream = false
    }, cancellationToken);
}
```

### Additional Information/Context

The stream received from GetObjectResponse is of type `Amazon.Runtime.Internal.Util.MD5Stream` which surprisingly has the property `Length` set, however it is not Seekable.

It seems the exception is thrown [here](https://github.com/aws/aws-sdk-net/blob/459d2e5410af5a5b0e26ba6951e75bf0c420351a/sdk/src/Services/S3/Custom/Internal/AmazonS3PostMarshallHandler.cs#L248C57-L248C65) because `Position` property is not supported in the `MD5Stream`. 

### AWS .NET SDK and/or Package version used

AWSSDK.S3 3.7.201.17

### Targeted .NET Platform

.NET 7

### Operating System and version

ubuntu 22.04

**Comment by ashishdhingra** [comment]
@grsw92 Good morning. Thanks for opening the issue. The Content Length is a requirement for S3 service API. Stream returned from `GetObjectResponse` is not seekable and hence cannot be used directly with PutObject API. As a workaround, please use the `TransferUtility` in the latest version of SDK where we recently added support for non-seekable streams.

Thanks,
Ashish

**Comment by plachor** [comment]
Hi this does not make sense for my case. 

Does `PutObject API` utilize seeking in any scenario (like going to beginning?) or it takes stream as it is and streams reaming bytes using knowledge how much there is left to stream ? 

If there seek done to beginning on case when position is greater than 0 than throw exception on attempt to set position to zero.  But allow to query for position. This way your SDK would produce response on get which using same SDK could be used during upload (many would dare to think that this scenario would be supported I guess). You can throw on SET attempt and allow for GETs on `Position` in `MD5Stream`.

Sounds insane that you cannot perform upload of stream that you obtained using one SDK.

And since multipart requires minimum 5MB parts this is huge issue for anyone that wishes to create memory light app that will copy many streams in parallel between buckets (world wide) without need to keep 5MB buffers per each copy task.

**Comment by ashishdhingra** [comment]
> Hi this does not make sense for my case.
> 
> Does `PutObject API` utilize seeking in any scenario (like going to beginning?) or it takes stream as it is and streams reaming bytes using knowledge how much there is left to stream ?
> 
> If there seek done to beginning on case when position is greater than 0 than throw exception on attempt to set position to zero. But allow to query for position. This way your SDK would produce response on get which using same SDK could be used during upload (many would dare to think that this scenario would be supported I guess). You can throw on SET attempt and allow for GETs on `Position` in `MD5Stream`.
> 
> Sounds insane that you cannot perform upload of stream that you obtained using one SDK.
> 
> And since multipart requires minimum 5MB parts this is huge issue for anyone that wishes to create memory light app that will copy many streams in parallel between buckets (world wide) without need to keep 5MB buffers per each copy task.

@plachor The Content-Length is the requirement of S3, not AWS SDK. For non-seekable stream, this would throw the said exception. Refer more details [here](https://github.com/aws/aws-sdk-net/issues/675#issuecomment-311160927). For smaller objects of size less then 5MB, you could use `MemoryStream` to buffer the object into memory and then using it for `PutObjectRequest`. For large objects, TransferUtility would automatically buffer parts into memory per latest implementation.

CCing @normj for any further inputs.

Thanks,
Ashish

**Comment by normj** [comment]
As @ashishdhingra mentioned S3 requires the content-length which can not be acquired from the non-seekable network stream that came back from the `GetObject` call. You can manually set the `content-length` on the `PutObject` request so that the SDK will not try to obtain the content-length from the `GetObject` response stream.

```csharp
var getResponse = await s3Client.GetObjectAsync(bucketName, sourceKey);

var putRequest = new PutObjectRequest
{
    BucketName = bucketName,
    Key = destnationKey,
    InputStream = getResponse.ResponseStream
};

putRequest.Headers["Content-Length"] = getResponse.ContentLength.ToString();

await s3Client.PutObjectAsync(putRequest);
```

**Comment by plachor** [comment]
Thnx for suggestion but actually `MD5Stream` provides `Length`. Issue is that it throws on attempt to GET `Position` which is used to calculate content length.

 It seems reasonable to change as you can easily provide position by counting already streamed bytes. I do also understand why SET should throw on not seekable stream. 

If you do not wish to count transfered bytes you can throw if position is not equal 0 but accept returning 0 if streaming has not yest started. I have not checked every code line but believe this is only checked once ?

**Comment by ashishdhingra** [comment]
@plachor Good afternoon. Please let us know if you are unblocked and if this issue could be closed.
