### ISSUE TITLE
TransferUtilityDownloadDirectoryRequest is missing SSE-C properties

### ISSUE THREAD

**Issue by lrocher** [aws/aws-sdk-net#3147]
### Describe the feature

TransferUtilityUploadDirectoryRequest is missing the three SSE-C properties:

    ServerSideEncryptionCustomerMethod
    ServerSideEncryptionCustomerProvidedKey
    ServerSideEncryptionCustomerProvidedKeyMD5

### Use Case

I want to use TransferUtility.DownloadDirectory with SSE-C.
TransferUtility.UploadDirectory already manage this feature.

### Proposed Solution

Add the properties and forward them in the DownloadDirectoryCommand to the TransferUtilityUploadDownload.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

AWSSDK.S3 3.7.305.10

### Targeted .NET Platform

.NET Framework 4.7

### Operating System and version

Windows

**Comment by ashishdhingra** [comment]
@lrocher Thanks for the PR. I will discuss this with team and would soon be reviewed.
