### ISSUE TITLE
ListObjectsV2Response.NextContinuationToken is not obfuscated

### ISSUE THREAD

**Issue by iKingNinja** [aws/aws-sdk-net#3152]
### Describe the bug

While `ListObjectsV2Response.NextContinuationToken` should be an obfuscated value, the SDK is returning the last object key in the page

### Expected Behavior

`ListObjectsV2Response.NextContinuationToken` should be obfuscated.

### Current Behavior

`ListObjectsV2Response.NextContinuationToken` is not obfuscated but the last object's key in the page.

### Reproduction Steps

```cs
ListObjectsV2Request request = new()
{
    BucketName = "BucketName",
    ContinuationToken = nextPageCursor,
    MaxKeys = maxObjectsCount
};

ListObjectsV2Response res = await client.ListObjectsV2Async(request);
List<string> ObjectsNames = new();

foreach (S3Object obj in res.S3Objects)
{
    ObjectsNames.Add(obj.Key);
}

return new
{
    nextPageCursor = res.NextContinuationToken,
    ObjectsNames = ObjectsNames
};
```

### AWS .NET SDK and/or Package version used

AWSSDK.S3 3.7.305.14

### Targeted .NET Platform

.NET 6.0

### Operating System and version

Windows 10 Home

**Comment by dscpinheiro** [comment]
Do you see the same behavior in other SDKs? This is the CLI equivalent, which may be the easiest to compare with: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3api/list-objects-v2.html

We hand-write most of our S3 code, but we use the value from the service as is: https://github.com/aws/aws-sdk-net/blob/f7a3a70a75ff1c4d5bc877b10a03e836cfcbe32a/sdk/src/Services/S3/Custom/Model/Internal/MarshallTransformations/ListObjectsV2ResponseUnmarshaller.cs#L133

**Comment by iKingNinja** [comment]
> Do you see the same behavior in other SDKs? This is the CLI equivalent, which may be the easiest to compare with: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3api/list-objects-v2.html

No, i tried with the AWS CLI and the result is obfuscated.

```cmd
C:\Users\Me>aws s3api list-objects-v2 --bucket mybucket --endpoint-url https://s3.cubbit.eu --max-items 1
{
    ...
    "NextToken": "eyJDb250aW51YXRpb25Ub2tlbiI6IG51bGwsICJib3RvX3RydW5jYXRlX2Ftb3VudCI6IDF9"
}

**Comment by dscpinheiro** [comment]
I wonder if Cubbit may be returning a different `NextToken` when all objects have been retrieved... I'd still check with the CLI, but run that command in a loop similar to this:
```powershell
$ContinuationToken = $null

Do {
    If ($null -eq $ContinuationToken) {
        $ListResponse = aws s3api list-objects-v2 --bucket mybucket --endpoint-url https://s3.cubbit.eu --max-items 1 --output json | ConvertFrom-Json
    } Else {
        $ListResponse = aws s3api list-objects-v2 --bucket mybucket --endpoint-url https://s3.cubbit.eu --max-items 1 --starting-token $ContinuationToken --output json | ConvertFrom-Json
    }

    $ContinuationToken = $ListResponse.NextToken
    Write-Host $ContinuationToken
} While ($null -ne $ContinuationToken)
```

If you see the not obfuscated key there as well you'll have to reach out to Cubbit, this is not something we can change on the SDK side.

**Comment by iKingNinja** [comment]
This is the result of running the script you send in PowerShell and all tokens are correctly obfuscated.
```
eyJDb250aW51YXRpb25Ub2tlbiI6IG51bGwsICJib3RvX3RydW5jYXRlX2Ftb3VudCI6IDF9
eyJDb250aW51YXRpb25Ub2tlbiI6IG51bGwsICJib3RvX3RydW5jYXRlX2Ftb3VudCI6IDJ9
eyJDb250aW51YXRpb25Ub2tlbiI6IG51bGwsICJib3RvX3RydW5jYXRlX2Ftb3VudCI6IDN9
eyJDb250aW51YXRpb25Ub2tlbiI6IG51bGwsICJib3RvX3RydW5jYXRlX2Ftb3VudCI6IDR9
eyJDb250aW51YXRpb25Ub2tlbiI6IG51bGwsICJib3RvX3RydW5jYXRlX2Ftb3VudCI6IDV9
eyJDb250aW51YXRpb25Ub2tlbiI6IG51bGwsICJib3RvX3RydW5jYXRlX2Ftb3VudCI6IDZ9
eyJDb250aW51YXRpb25Ub2tlbiI6IG51bGwsICJib3RvX3RydW5jYXRlX2Ftb3VudCI6IDd9
eyJDb250aW51YXRpb25Ub2tlbiI6IG51bGwsICJib3RvX3RydW5jYXRlX2Ftb3VudCI6IDh9
eyJDb250aW51YXRpb25Ub2tlbiI6IG51bGwsICJib3RvX3RydW5jYXRlX2Ftb3VudCI6IDl9
```

**Comment by dscpinheiro** [comment]
Thanks for taking a look.

Would it be possible to share more of your application? Unfortunately I don’t have access to Cubit, but I double checked today and the SDK doesn’t modify the token returned from S3. If it helps, here's one method we have that has a similar logic (iterate through the list response):

https://github.com/aws/aws-sdk-net/blob/f7a3a70a75ff1c4d5bc877b10a03e836cfcbe32a/sdk/src/Services/S3/Custom/Transfer/Internal/_bcl45%2Bnetstandard/DownloadDirectoryCommand.cs#L143-L161
