### ISSUE TITLE
Use Regex source generator when targeting net8.0

### ISSUE THREAD

**Issue by martincostello** [aws/aws-sdk-net#3156]
### Describe the feature

As part of the .NET 7 release, a [source generator for Regular Expressions was introduced](https://devblogs.microsoft.com/dotnet/regular-expression-improvements-in-dotnet-7/#source-generation).

As the AWS SDKs for .NET now target `net8.0`, this functionality can be leveraged to potentially improve the performance of regular expression operations within the SDKs.

A cursory search of the code suggests there are 20+ places in the code this could potentially be of use: [code search](https://github.com/search?q=repo%3Aaws%2Faws-sdk-net+%22new+Regex%28%22+language%3AC%23&type=code).

A specific example can be found here, which I noticed while looking into #3153:

https://github.com/aws/aws-sdk-net/blob/4650fa53914bdeea1e10fdac42f902638b77eee9/sdk/src/Core/Amazon.Runtime/Credentials/AssumeRoleWithWebIdentityCredentials.cs#L51

This specific example could be changed like this:

```diff
+ #if NET8_0_OR_GREATER
+ [GeneratedRegex(@"^[\w+=,.@-]{2,64}$")]
+ private static partial Regex RoleSessionNameRegex();
+ #else
  private static readonly Regex _roleSessionNameRegex = new Regex(@"^[\w+=,.@-]{2,64}$", RegexOptions.Compiled);
+ private static Regex RoleSessionNameRegex() => _roleSessionNameRegex;
+ #endif
```

The call sites in this case would then be changed from `_roleSessionNameRegex` to `RoleSessionNameRegex()`.

### Use Case

Improve the cold-start and runtime performance of applications using the AWS .NET SDKs.

### Proposed Solution

Update the custom code to use the Regex source generator where the pattern is known at compile-time and update the generated code to do the same.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

Anywhere `Regex` is used with a compile-time known pattern.

### Targeted .NET Platform

.NET 8

### Operating System and version

All

**Comment by normj** [comment]
This is a great idea. Any interest in submitting a PR? Otherwise I will try and get to it when I can.

**Comment by martincostello** [comment]
Sure, happy to try and tackle this at some point in the next few weeks.

If you could give me a pointer to where I'd need to go for updating the generated parts of the code, that would be useful.

**Comment by normj** [comment]
The generator is in the same repository here `https://github.com/aws/aws-sdk-net/tree/main/generator`.

It uses T4 templates. So basically you edit the `tt` files. and then run `ServiceClientGenerator` project in the solution and it will regenerate all of the service clients. Generate takes a minute or so to run not to bad. I think you have to use Visual Studio for the T4. Not sure on Rider's support for T4.

**Comment by normj** [comment]
Word of warning when working in the generator, is avoid the temptation of fixing some white space or alignment issue. You don't want a PR that causes thousands of files to change. If there are a lot of files changed we usually do the PRs with just the generator changes and allow the build system to handle the regeneration and commit. PRs with hundreds or thousands of files changes is just to hard to look at.
