### ISSUE TITLE
"Intelligent-Tiering" not classifying ssm param tier properly when value length is over 4096

### ISSUE THREAD

**Issue by Matheusbafutto** [aws/aws-sdk-net#3157]
### Describe the bug

According to the documentation on ssm parameter tiers [here](https://docs.aws.amazon.com/systems-manager/latest/userguide/parameter-store-advanced-parameters.html), the Tier value `Intelligent-Tiering` is meant to auto-infer whether an ssm param needs to be standard or advanced.

When we make a PUT request to create a new ssm param using this client library I have experienced the following response when my Value has length larger that 4096 characters:

> Standard tier parameters support a maximum parameter value of 4096 characters. To create a larger parameter value, upgrade the parameter to use the advanced-parameter tier. For more information, see https://docs.aws.amazon.com/systems-manager/latest/userguide/parameter-store-advanced-parameters.html 

By inspecting the library code, I see that `Intelligent-Tiering` is the default value for tier. It feels strange to me that even though we are setting a tier value for auto-detecting what parameter tier should apply, the API still errors out saying that we need to explicitly tell it to create an advanced ssm parameter.

I think ssm param requests with Tier set to "Intelligent-Tiering"  should be able to look at the Value length to tell whether the param needs to be advanced or not. The way things stand today, my current solution is to look at length of Value in my app layer and set Tier to "Advanced" explicitly (which works but does not seem ideal). 

### Expected Behavior

Making a create ssm param request with the client library setting Value to a string with length larger than 4096 and Tier to "Intelligent-Tiering" should succeed in creating an advanced ssm parameter request instead of erroring out.

### Current Behavior

"Intelligent-Tiering" seems to ignore Value length requirement when assessing which tier it needs to assign to the new ssm parameter on creation.

"Intelligent-Tiering" assigns `standard` tier to the prospective ssm param and the API returns an error

### Reproduction Steps

Create a new `SsmModel.PutParameterRequest` from namespace `Amazon.SimpleSystemsManagement` setting Value to a string with length larger than 4096 and whatever other parameters are needed.

Instantiate a new `AmazonSimpleSystemsManagementClient` from the same namespace and call the `PutParameter` with the parameter created above.

Verify the API returned a validation error instead of creating an advanced param

### Possible Solution

Check the Value length requirement in the backend of the API when classifying the tier of a new ssm parameter instead of throwing a validation error

### AWS .NET SDK and/or Package version used

AWSSDK.Core 3.7.300.28

### Targeted .NET Platform

.Net Framework 4.8

### Operating System and version

OSX Sonoma

**Comment by dscpinheiro** [comment]
Could you share some [reproducible code](http://sscce.org/)? I tested with the latest available version of the `AWSSDK.SimpleSystemsManagement` package (`3.7.301.35` as of today), and did not see any validation errors (it created the parameter with the expected tier - advanced):

```csharp
using Amazon.SimpleSystemsManagement;
using Amazon.SimpleSystemsManagement.Model;

var client = new AmazonSimpleSystemsManagementClient();
var response = await client.PutParameterAsync(new PutParameterRequest
{
    Tier = ParameterTier.IntelligentTiering,
    Type = ParameterType.String,
    Name = "test-parameter",
    Value = File.ReadAllText("file-with-size-longer-than-4kb.json")
});

Console.WriteLine(response.HttpStatusCode); // OK
Console.WriteLine(response.Version); // 1
Console.WriteLine(response.Tier); // Advanced
```
