### ISSUE TITLE
TransferUtilityUploadDirectoryRequest not returning filename

### ISSUE THREAD

**Issue by hashitha** [aws/aws-sdk-net#317]
I am using TransferUtilityUploadDirectoryRequest and getting the file at UploadDirectoryProgressEvents  using e.CurrentFile and this returns the file normally. However, when I set UploadFilesConcurrently = true and set ConcurrentServiceRequests = 5, e.CurrentFile returns NULL but it returns the other properties on e such as e.TotalBytes

**Comment by normj** [comment]
That is by design in concurrent mode. Since there isn't a single file that is currently being uploaded we can't say what the current file is.

**Comment by hashitha** [comment]
So there is no way to find out which file completed successfully in
concurrent mode?


In my case, I am tying to update a dynamodb table when a single file
uploads successfully.

**Comment by normj** [comment]
Not currently. We'll add to our backlog to take a look at more evening information during concurrent mode but for now you will have to turn off concurrent mode if you want this information.

An alternative if it fits with your application's design is you could use S3's notification feature to call a Lambda function that you could use to update DynamoDB.

**Comment by hashitha** [comment]
No Worries, using the Lambda function won't work in this case so I will turn off concurrent mode
