### ISSUE TITLE
Return Response Headers in ResponseMetadata for BedrockRuntime actions

### ISSUE THREAD

**Issue by jhart0** [aws/aws-sdk-net#3171]
### Describe the feature

When using the AWS CLI or other AWS SDKs (such as Java), the response headers contain the bedrock-specific latency, output tokens and input tokens.

e.g. for the InvokeModel API action:
`
{'Date': 'Fri, 02 Feb 2024 12:44:00 GMT', 'Content-Type': 'application/json', 'Content-Length': '1419', 'Connection': 'keep-alive', 'x-amzn-RequestId': '3abacd58-8693-4a25-b1c0-e80ab9efb812', 'X-Amzn-Bedrock-Invocation-Latency': '14244', 'X-Amzn-Bedrock-Output-Token-Count': '300', 'X-Amzn-Bedrock-Input-Token-Count': '13'}
`

When using the .NET SDK, the ResponseMetadata only contains the requestId, as per: https://github.com/aws/aws-sdk-net/blob/3.7.740.0/sdk/src/Core/Amazon.Runtime/Internal/Transform/ResponseUnmarshallers.cs#L211-L229

### Use Case

For metering and observability into BedrockRuntime inference requests, these headers are useful for logging or taking programmatic action based on the generated tokens (e.g. throttling or rate limiting). 

### Proposed Solution

Return `X-Amzn-Bedrock-*` headers when using BedrockRuntime API actions as part of ResponseMedata

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

AWSSDK.BedrockRuntime.3.7.301.32

### Targeted .NET Platform

.NET 6 

### Operating System and version

OSX Sonoma

**Comment by normj** [comment]
@jhart0 I talked with the Bedrock team about these headers and why they aren't modeled to properties that would be generated in the .NET SDK. They are treating these headers as sort of internal subject to change for now. The .NET SDK only exposes the data they model in the service model that we generate from. We don't have any current plans in changing the public interface of service APIs to expose the raw HTTP headers.

That being said if you want the pseudo secret backdoor way of accessing them you can attach an `AfterResponseEvent` event on the service client and access the headers for service API calls made on the service client.

```csharp
AmazonBedrockRuntimeClient client = new AmazonBedrockRuntimeClient();

client.AfterResponseEvent += (o, e) =>
{
    if(e is Amazon.Runtime.WebServiceResponseEventArgs we)
    {
        foreach(var name in we.ResponseHeaders.Keys)
        {
            if(name.StartsWith("X-Amzn-Bedrock", StringComparison.OrdinalIgnoreCase))
            {
                Console.WriteLine($"{name}: {we.ResponseHeaders[name]}");
            }
        }
    }
};
```

var response = await  client.InvokeModelAsync(request);

**Comment by jhart0** [comment]
Awesome, works well, thanks @normj
