### ISSUE TITLE
Performance downgrade with AmazonCloudFrontUrlSigner in Linux Environment (Ubuntu 22.04.3 LTS) 

### ISSUE THREAD

**Issue by SonalCalcey** [aws/aws-sdk-net#3172]
### Describe the bug

We've identified a performance degradation in **AmazonCloudFrontUrlSigner** when generating a signed URL using the **GetCannedSignedURL** method in **Ubuntu 22.04.3 LTS**. After some further investigation, we have identified that the issue only appears on  **Ubuntu 22.04.3 LTS**.

Furthermore, we have done a Benchmark test for the **Ubuntu** versions such as

- Ubuntu 22.04.3 LTS
- Ubuntu 20.04.3 LTS
- Ubuntu 18.04.6 LTS

To help you better understand the issue, we have prepared a sample description highlighting the key observations and differences. Kindly be aware that the tests were executed on **Ubuntu** versions within the **WSL 2** environment.

(Benchmark results were taken using [BenchmarkDotNet ](https://github.com/dotnet/BenchmarkDotNet)v0.13.11)

**Summary for Ubuntu 22.04.3 LTS**

![Signed Url-Ubuntu 22 04 LTS 1](https://github.com/aws/aws-sdk-net/assets/139344044/34a54633-9560-4921-b2b4-cb5c9ecac707)

![Signed Url-Ubuntu 22 04 LTS 2](https://github.com/aws/aws-sdk-net/assets/139344044/2ea63fe1-1825-4292-9661-1b6a6a95490c)

**Benchmark log 1:**
[benchmark_tester.SignedUrlRunner-20240205-104837-Ubuntu 22.04 LTS-Run1.log](https://github.com/aws/aws-sdk-net/files/14165507/benchmark_tester.SignedUrlRunner-20240205-104837-Ubuntu.22.04.LTS-Run1.log)

**Benchmark log 2:**
[benchmark_tester.SignedUrlRunner-20240205-105435-Ubuntu 22.04 LTS-Run2.log](https://github.com/aws/aws-sdk-net/files/14165508/benchmark_tester.SignedUrlRunner-20240205-105435-Ubuntu.22.04.LTS-Run2.log)

**Summary for Ubuntu 18.04.6 LTS**

![Signed Url-Ubuntu 18 04 LTS 1](https://github.com/aws/aws-sdk-net/assets/139344044/7c73533c-0855-4f4a-9f74-4b5865f6af5c)

![Signed Url-Ubuntu 18 04 LTS 2](https://github.com/aws/aws-sdk-net/assets/139344044/d60b6776-aea4-42b1-95e3-02d7a0230941)

**Benchmark log 1:**
[benchmark_tester.SignedUrlRunner-20240205-122748-Ubuntu 18.04 LTS-Run1.log](https://github.com/aws/aws-sdk-net/files/14165410/benchmark_tester.SignedUrlRunner-20240205-122748-Ubuntu.18.04.LTS-Run1.log)

**Benchmark log 2:**
[benchmark_tester.SignedUrlRunner-20240205-123016-Ubuntu 18.04 LTS-Run2.log](https://github.com/aws/aws-sdk-net/files/14165414/benchmark_tester.SignedUrlRunner-20240205-123016-Ubuntu.18.04.LTS-Run2.log)

Summary for Ubuntu 20.04.3 LTS

![Signed Url-Ubuntu 20 04 LTS 1](https://github.com/aws/aws-sdk-net/assets/139344044/0f9bffa5-0a34-4349-aee1-1949c6ce6120)

![Signed Url-Ubuntu 20 04 LTS 2](https://github.com/aws/aws-sdk-net/assets/139344044/1529036f-cea9-4aef-a44b-63195f937d07)

**Benchmark log 1:**
[benchmark_tester.SignedUrlRunner-20240205-161924-Ubuntu 20.04 LTS-Run1.log](https://github.com/aws/aws-sdk-net/files/14165540/benchmark_tester.SignedUrlRunner-20240205-161924-Ubuntu.20.04.LTS-Run1.log)

**Benchmark log 2:**
[benchmark_tester.SignedUrlRunner-20240205-162138-Ubuntu 20.04 LTS-Run2.log](https://github.com/aws/aws-sdk-net/files/14165534/benchmark_tester.SignedUrlRunner-20240205-162138-Ubuntu.20.04.LTS-Run2.log)

### Expected Behavior

Expected to have a similar performance as the earlier versions of Ubuntu. 

### Current Behavior

**GetCannedSignedURL** generation is **10x** slower in **Ubuntu 22.04.3 LTS**

### Reproduction Steps

```

using Amazon;
using Amazon.CloudFront;
using Amazon.S3;
using Amazon.S3.Model;
using BenchmarkDotNet.Attributes;
using Microsoft.Extensions.Configuration;

namespace benchmark_tester;

[MemoryDiagnoser]
public class SignedUrlRunner
{
	// CloudFront 
	private static string _sourceKey;
	private static string _cloudFrontKeyId;
	private static string _cloudFrontPrivateKey;
	private static string _cloudFrontDistributionDomain;

	// S3
	private static string _accessKeyId;
	private static string _secretAccessKey;
	private static string _bucketName;
	private static AmazonS3Client _s3Client;

	private static readonly DateTime ExpiresOnTime = DateTime.Now.AddMinutes(5);

	[GlobalSetup]
	public void GlobalSetup()
	{
		var configuration = new ConfigurationBuilder()
			.AddJsonFile("appsettings.json", optional: false)
			.Build();

		_sourceKey = configuration["AWS:SourceKey"]!;

		// CloudFront
		_cloudFrontKeyId = configuration["CloudFront:KeyPairId"]!;
		_cloudFrontPrivateKey = configuration["CloudFront:PrivateKey"]!;
		_cloudFrontDistributionDomain = configuration["CloudFront:DistributionName"]!;

		// S3
		_accessKeyId = configuration["AWS:AccessKeyId"]!;
		_secretAccessKey = configuration["AWS:SecretAccessKey"]!;
		_bucketName = configuration["AWS:BucketName"]!;
		_sourceKey = configuration["AWS:SourceKey"]!;
		_s3Client = new AmazonS3Client(_accessKeyId, _secretAccessKey, RegionEndpoint.APSoutheast1);
	}

	[GlobalCleanup]
	public void GlobalCleanup()
	{
		_s3Client.Dispose();
	}

	[Benchmark]
	public string CloudFrontGenerateSignedUrl()
	{
		return AmazonCloudFrontUrlSigner.GetCannedSignedURL(
			AmazonCloudFrontUrlSigner.Protocol.https,
			_cloudFrontDistributionDomain,
			new StringReader(_cloudFrontPrivateKey),
			_sourceKey,
			_cloudFrontKeyId,
			ExpiresOnTime
		);
	}

	[Benchmark]
	public string WildCardCloudFrontSignedUrl()
	{
		var policy = AmazonCloudFrontUrlSigner.BuildPolicyForSignedUrl("*", ExpiresOnTime, null);
		var signedFullUrl = AmazonCloudFrontUrlSigner.SignUrl(
			_sourceKey,
			_cloudFrontKeyId,
			new StringReader(_cloudFrontPrivateKey),
			policy);

		return signedFullUrl.Split("?")[1];
	}

	[Benchmark]
	public string S3GenerateSignedUrl()
	{
		GetPreSignedUrlRequest request = new()
		{
			BucketName = _bucketName,
			Key = _sourceKey,
			Expires = DateTime.Now.AddMinutes(5)
		};

		return _s3Client.GetPreSignedURL(request);
	}
}
```

### AWS .NET SDK and/or Package version used

AWSSDK.CloudFront - 3.7.301.39
AWSSDK.Core - 3.7.302.6
AWSSDK.SecretsManager - 3.7.302.21

### Targeted .NET Platform

.NET 7

### Operating System and version

Windows 10

**Comment by dscpinheiro** [comment]
Are you using OpenSSL 3 in Ubuntu 2022? I wonder if it's the same issue as #3165
