### ISSUE TITLE
Packages not restoring with .Net Core

### ISSUE THREAD

**Issue by ProTip** [aws/aws-sdk-net#318]
I'm getting the following error on Ubuntu 14.04 using ```dotnet``` at the installed version listed on the core site ```1.0.0.001598-1```:

```
Errors in project.json
    AWSSDK.ECS 3.1.3.1 is not compatible with DNXCore,Version=v5.0.
    AWSSDK.Core 3.1.4.3 is not compatible with DNXCore,Version=v5.0.
```

Is this due to the bump from 4.5 to 5.0? Can anything be done?

**Comment by normj** [comment]
To use the the AWS sdk in ASP.NET Core based applications you need to use the 3.2.X versions of the NuGet packages. Note, they are currently marked as beta.
