### ISSUE TITLE
AWSSDK.Extensions.CrtIntegration AssemblyFileVersion is not updated

### ISSUE THREAD

**Issue by koimatcha** [aws/aws-sdk-net#3181]
### Describe the bug

Hi, the file version of 'AWSSDK.Extensions.CrtIntegration.dll' is still "Version 3.7.0.0". So the Installer does not update the previous version of this file at all. The "AssemblyFileVersion" should be "3.7.300.1".

"extensions/src/AWSSDK.Extensions.CrtIntegration/Properties/AssemblyInfo.cs"
[assembly: AssemblyFileVersion("3.7.0.0")] <= here

### Expected Behavior

Any installer can replace the previous version of AWSSDK.Extensions.CrtIntegration.dll with the new one.

### Current Behavior

The Installer does not replace the previous version of this file.

### Reproduction Steps

Installing AWSSDK.Extensions.CrtIntegration.dll by creating any MSI installer.

### AWS .NET SDK and/or Package version used

AWSSDK.Extensions.CrtIntegration 3.7.300.1

### Targeted .NET Platform

.NET Framework 4.8.1

### Operating System and version

Windows 11

**Comment by bhoradc** [comment]
Hi @koimatcha, 

Thanks for bringing this issue to our notice. We will review this with our team and work on the fix accordingly. 

Regards, 
Chaitanya

**Comment by dscpinheiro** [comment]
This has been fixed in the latest version of the `AWSSDK.Extensions.CrtIntegration` package: https://www.nuget.org/packages/AWSSDK.Extensions.CrtIntegration/3.7.300.3
