### ISSUE TITLE
Proxy authentication using Kerberos

### ISSUE THREAD

**Issue by ianf79** [aws/aws-sdk-net#3195]
### Describe the feature

We recently moved from the C++ SDK for improved proxy support when working with secure traffic in the C# SDK. It seems that the C# SDK does not support proxy authentication using Kerberos. 

### Use Case

The SDK should be able to connect correctly on a network that uses a proxy that intercepts TLS traffic and uses proxy authentication using Kerberos.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

3.7

### Targeted .NET Platform

.NET 6

### Operating System and version

Windows

**Comment by dscpinheiro** [comment]
Kerberos is not supported directly, but you have access to how the `HttpClient` is created. 

[This blog post](https://lucaspacheco.dev/kerberos-authentication-dotnet/) has details on how to authenticate with Kerberos using .NET, you should be able to do something similar using the SDK's `HttpClientFactory`:

```csharp
using Amazon.Runtime;
using Amazon.S3;
using System.Net;

class KerberosClientFactory : HttpClientFactory
{
    public override HttpClient CreateHttpClient(IClientConfig clientConfig)
    {
        var credentialsCache = new CredentialCache { ... };
        var httpClientHandler = new HttpClientHandler { ... };

        return new HttpClient(httpClientHandler);
    }
}

var s3 = new AmazonS3Client(new AmazonS3Config
{
    HttpClientFactory = new KerberosClientFactory()
});
await s3.ListBucketsAsync();
```

This re:Invent talk from last year has more details on `HttpClientFactory`: https://www.youtube.com/watch?v=t3swORUjuBk&t=683s

**Comment by AlmeidaVitor** [comment]
We are looking for a built in solution for this and not to have to implement kerberos ourselves.

We are requesting this to be reopened as directed by Mike Lauenstein
