### ISSUE TITLE
Unhandled ProvisionedThroughputExceededException crashing Mono server

### ISSUE THREAD

**Issue by foliba** [aws/aws-sdk-net#320]
When running multiple stress tests (locally on windows and on our Mono servers) we encountered an unhandled ProvisionedThroughputExceededException when writing to our DynamoDB.
Even having a try catch around the SDK call, the exception isn't handled.

This unhandled exception seems to crash our Mono server.

- AWSSDK version: 2.3.52.0
- .NET runtime: 4.5
- Mono 4.2.1

StackTrace:
```
at Amazon.Runtime.Internal.HttpRequest.GetResponse() in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\HttpHandler\HttpWebRequestFactory.cs:line 114
  at Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:line 84
  at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 57
  at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\Handlers\Unmarshaller.cs:line 48
  at Amazon.Runtime.Internal.PipelineHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\PipelineHandler.cs:line 57
  at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdkandtools-release\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 70
```

**Comment by PavelSafronov** [comment]
Can you post code that repros this issue?

**Comment by foliba** [comment]
Hey Pavel, thanks for your quick reply.

We basically just send the write call using the AWS SDK:

```public async Task<bool> Save<T>(T entity) where T : class, new()
        {
            if (entity == null)
            {
                return false;
            }

            try
            {
                await Context.SaveAsync(entity).ConfigureAwait(false);
                return true;
            }
            catch (Exception e)
            {
                return false;
            }
        }
```

Where Context is of type: Amazon.DynamoDBv2.DataModel.DynamoDBContext

In any case, this exception should be caught by the try catch around the SDK call, shouldn't it?

Remark:
We encountered the same issue when using the
`Save<T>(T value, DynamoDBOperationConfig operationConfig = null)`
function of the AWS SDK.

Thanks again for looking into this!
Cheers.

**Comment by PavelSafronov** [comment]
Are you encountering the same un-catchable exception if using the sync methods? Can you provide the code which calls your Save<T> method? Can you provide the simplest possible sample that reproduces this behavior consistently?

**Comment by foliba** [comment]
Hei Pavel,

thanks for following up.
We indeed encounter the same behavior when using the sync methods. The code looks like this:

```
public bool Save<T>(T entity) where T : class, new()
{
	try
	{
		using (var client = new AmazonDynamoDBClient(awsAccessKey, awsSecretKey, config))
		{
			using (var context = new DynamoDBContext(client, ContextConfig))
			{
				context.Save(entity);
			}
		}

		return true;
	}
	catch (Exception e)
	{
		//	log error
		return false;
	}
}
```

As Requested I gonna provide a small project with the simplest sample that reproduces this behavior as soon as possible tomorrow morning.

Thanks again for looking into this.

Cheers

**Comment by foliba** [comment]
Hey Pavel,

thanks for being patient.
I just put together a small project as requested.
You can find it here: https://github.com/foliba/ServiceStackIssue320

We added both versions: async and sync.
The async version reproduces our issue 100%. The sync calls in about 75% of all cases.

Thanks again for looking into this.
Cheers,
Roman

**Comment by PavelSafronov** [comment]
Thanks for the repo.

Running the code locally on Windows, I am able to see the exception dialog ("ProvisionedThroughputExceededException was unhandled by user code"), though this does not crash the IIS server. Is this the same behavior you are seeing?

How are you running this code on Mono?

We're not sure why this is happening yet, but one way to avoid the exception seems to be to use the client. For instance, you can replace the ```context.SaveAsync...``` call with
```
await client.PutItemAsync(
    context.GetTargetTable<T>().TableName,
    context.ToDocument(entity).ToAttributeMap()).ConfigureAwait(false);
```

**Comment by foliba** [comment]
Hey Pavel,

correct, we are running on Mono. Sadly this exception causes the server to crash. IIS seems to be a bit nicer here.
Thanks for the suggestion. Will communicate with our other developers and report back.

Cheers,
Roman

**Comment by foliba** [comment]
Hey Pavel,

Just wanted to let you know that your supposed fix works flawlessly. We deployed to our test servers some weeks ago and monitored for for a while. No uncaught exceptions anymore. ;-)

Thanks for your help! Much appreciated.
Cheers,
Roman
