### ISSUE TITLE
Set Content Type (mime code) for csv files

### ISSUE THREAD

**Issue by stoilovkr** [aws/aws-sdk-net#3213]
### Describe the feature

When I upload .csv files using this client, the mime code is not inferred from the file extension and defaulting to application/octet-stream. I see a long list of file types in [AmazonS3Util.cs class](https://github.com/aws/aws-sdk-net/blob/fad56d05b452da7623071a1517378223ff38db27/sdk/src/Services/S3/Custom/Util/AmazonS3Util.cs#L52), but not for a common file type like .csv. Is there a reason why is the mime code text/csv or application/csv not inferred? Any of them would be much better than just defaulting to application/octet-stream.

### Use Case

As a developer I want to have text/csv content type inferred by the sdk from extension, so I don't need to write workaround code to infer the content type in end users code, when it defaults to application/octet-stream.

### Proposed Solution

Simply add a line ` { ".csv", "text/csv" },` in the `extensionToMime` [dictionary initialization](https://github.com/aws/aws-sdk-net/blob/fad56d05b452da7623071a1517378223ff38db27/sdk/src/Services/S3/Custom/Util/AmazonS3Util.cs#L52).

### Acknowledgements

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

Latest

### Targeted .NET Platform

.NET 7

### Operating System and version

Windows 11

**Comment by bhoradc** [comment]
Hi @stoilovkr, 

Thank you for submitting this feature request. I understand how the automatic detection of the `text/csv` MIME type would improve the developer experience when uploading CSV files. 

Will discuss this with the team to take it forward accordingly. 

Regards, 
Chaitanya

**Comment by ashishdhingra** [comment]
@stoilovkr Thanks for submitting feature request. We will discuss it with the team to get it prioritized. Feel free to contribute PR for the change.

**Comment by muhammad-othman** [comment]
@stoilovkr This change was released and you can find it in [S3 v3.7.306](https://www.nuget.org/packages/AWSSDK.S3/3.7.306)
