### ISSUE TITLE
TargetFramework in AWSSDK.Core uses non-documented string for .net8

### ISSUE THREAD

**Issue by nicholi** [aws/aws-sdk-net#3219]
### Describe the bug

The nuspec generated for AWSSDK.Core is specifying the following for .NET8 targetFramework.
```
<group targetFramework=".NETCoreApp8.0" />
```

This usage causes a minor warning when using [paket](https://fsprojects.github.io/Paket/) as dependency resolver for AWSSDK.Core.
```
Could not detect any platforms from '.netcoreapp8.0' in 'REDACTED_HOMEDIR\.nuget\packages\awssdk.core\3.7.302.16\awssdk.core.nuspec', please tell the package authors
```

However the correct string for .NET8 would just be `net8.0`, not .NETCoreApp8.0. I believe the intention was the last framework which would officially use NetCoreApp was 3.1. Since .NET5 the strings should be `net5.0`, `net6.0`, etc.
As documented: https://learn.microsoft.com/en-us/dotnet/standard/frameworks

Obviously an extremely minor warning, which seems to cause no actual problems at all in using the library in .net8 projects. There is apparently undocumented support for continued usage of .NETCoreApp#, but I can't find any reference for .NETCoreApp8.0 anywhere. I'm not sure what exactly is translating the nuspec's to output that when packaging, nothing obvious seems to be pointing to it. However there is quite a complex set of buildtools being used here, so I couldn't dig too deep myself.

### Expected Behavior

Receiving no warning when installing nupkg with paket.

### Current Behavior

Warning printed when installing AWSDK.Core package with paket.
```
Could not detect any platforms from '.netcoreapp8.0' in 'REDACTED_HOMEDIR\.nuget\packages\awssdk.core\3.7.302.16\awssdk.core.nuspec', please tell the package authors
```

### Reproduction Steps

Just setting up a simple solution/project and installing AWSDK.Core with paket.

Simple enough command instructions to run on both Windows (powershell) and Linux (bash).
```
mkdir TestSln
cd TestSln

# empty sln and csproj
dotnet new sln
dotnet new classlib -n TestProject

dotnet new tool-manifest
dotnet tool install paket
dotnet paket init

# add AWSSDK.Core dependency
echo "nuget AWSSDK.Core" >> paket.dependencies
echo "AWSSDK.Core" >> TestProject/paket.dependencies

# now download/install dependencies
dotnet paket install
```

At which point you should receive the output with the warning about the unsupported TargetFramework.
```
Paket version 8.0.3+75b30cdcb8859e8d129f139444d9b9b600bfff07
Resolving dependency graph...
Could not detect any platforms from '.netcoreapp8.0' in 'REDACTED_HOMEDIR\.nuget\packages\awssdk.core\3.7.302.16\AWSSDK.Core.3.7.302.16.nupkg\AWSSDK.Core.nuspec', please tell the package authors
Updated packages:
  Group: Main
    - AWSSDK.Core: 3.7.302.16 (added)
    - Microsoft.Bcl.AsyncInterfaces: 8.0.0 (added)
    - System.Runtime.CompilerServices.Unsafe: 6.0.0 (added)
    - System.Threading.Tasks.Extensions: 4.5.4 (added)
Installing into projects:
Created dependency graph (4 packages in total)
Could not detect any platforms from '.netcoreapp8.0' in 'REDACTED_HOMEDIR\.nuget\packages\awssdk.core\3.7.302.16\awssdk.core.nuspec', please tell the package authors
Total time taken: 1 second
```

### AWS .NET SDK and/or Package version used

AWSSDK.Core 3.7.302.16

### Targeted .NET Platform

.NET 8

### Operating System and version

Windows, Ubuntu

**Comment by ashishdhingra** [comment]
Needs review with the team. The TFM for .NET 8.0 is `net8.0`.

**Comment by ashishdhingra** [comment]
The `.nuspec` for current `AWSSDK.Core` version `3.7.400.9` is below:
```XML
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>AWSSDK.Core</id>
    <version>3.7.400.9</version>
    <title>AWSSDK - Core Runtime</title>
    <authors>Amazon Web Services</authors>
    <owners>Amazon Web Services</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <license type="expression">Apache-2.0</license>
    <licenseUrl>https://licenses.nuget.org/Apache-2.0</licenseUrl>
    <icon>images\AWSLogo.png</icon>
    <projectUrl>https://github.com/aws/aws-sdk-net/</projectUrl>
    <description>The Amazon Web Services SDK for .NET - Core Runtime</description>
    <language>en-US</language>
    <tags>AWS Amazon cloud aws-sdk-v3</tags>
    <dependencies>
      <group targetFramework=".NETFramework3.5" />
      <group targetFramework=".NETFramework4.5" />
      <group targetFramework=".NETStandard2.0">
        <dependency id="Microsoft.Bcl.AsyncInterfaces" version="1.1.0" />
      </group>
      <group targetFramework=".NETCoreApp3.1" />
      <group targetFramework=".NETCoreApp8.0" />
    </dependencies>
  </metadata>
</package>
```
Below is the content of T4 template for [CoreNuspec.tt](https://github.com/aws/aws-sdk-net/blob/069f14d45721e53f582ee6a53074816f113ec799/generator/ServiceClientGeneratorLib/Generators/NuGet/CoreNuspec.tt#L1):
```XML
<#@ template language="C#" #>
<#@ assembly name="System.Core" #>

<?xml version="1.0" encoding="utf-8"?>
<package> 
  <metadata> 
    <id>AWSSDK.Core</id>
    <title>AWSSDK - Core Runtime</title>
    <version><#=this.Session["FileVersion"]#><#=this.Session["NuGetPreviewFlag"]#></version> 
    <authors>Amazon Web Services</authors>
    <description>The Amazon Web Services SDK for .NET - Core Runtime</description>
    <language>en-US</language>
    <license type="expression">Apache-2.0</license>
    <projectUrl>https://github.com/aws/aws-sdk-net/</projectUrl>
    <tags>AWS Amazon cloud aws-sdk-v3</tags>
    <icon>images\AWSLogo.png</icon>
    <dependencies>
      <group targetFramework="net35">
      </group>
      <group targetFramework="net45">
      </group>
	    <group targetFramework="netstandard2.0">
        <dependency id="Microsoft.Bcl.AsyncInterfaces" version="1.1.0" />
      </group>
      <group targetFramework="netcoreapp3.1">
      </group>
      <group targetFramework="net8.0">
      </group>		
    </dependencies>
  </metadata> 
  <files>
    <file src="..\..\nuget-content\AWSLogo.png" target="images\" />
    <file src="..\..\nuget-content\account-management.ps1" target="tools" />

    <file src=".\bin\Release\net35\AWSSDK.Core.dll" target="lib\net35" />
    <file src=".\bin\Release\net35\AWSSDK.Core.xml" target="lib\net35" />
    <file src=".\bin\Release\net35\AWSSDK.Core.pdb" target="lib\net35" />

    <file src=".\bin\Release\net45\AWSSDK.Core.dll" target="lib\net45" />
    <file src=".\bin\Release\net45\AWSSDK.Core.xml" target="lib\net45" />
    <file src=".\bin\Release\net45\AWSSDK.Core.pdb" target="lib\net45" />

    <file src=".\bin\Release\netstandard2.0\AWSSDK.Core.dll" target="lib\netstandard2.0"/>
    <file src=".\bin\Release\netstandard2.0\AWSSDK.Core.xml" target="lib\netstandard2.0"/>
    <file src=".\bin\Release\netstandard2.0\AWSSDK.Core.pdb" target="lib\netstandard2.0"/>

    <file src=".\bin\Release\netcoreapp3.1\AWSSDK.Core.dll" target="lib\netcoreapp3.1"/>
    <file src=".\bin\Release\netcoreapp3.1\AWSSDK.Core.xml" target="lib\netcoreapp3.1"/>
    <file src=".\bin\Release\netcoreapp3.1\AWSSDK.Core.pdb" target="lib\netcoreapp3.1"/>

    <file src=".\bin\Release\net8.0\AWSSDK.Core.dll" target="lib\net8.0"/>
    <file src=".\bin\Release\net8.0\AWSSDK.Core.xml" target="lib\net8.0"/>
    <file src=".\bin\Release\net8.0\AWSSDK.Core.pdb" target="lib\net8.0"/>
  </files>
</package>
```
The T4 template has correct `targetFramework`.

Unsure if [CoreNuspec.tt](https://github.com/aws/aws-sdk-net/blob/069f14d45721e53f582ee6a53074816f113ec799/generator/ServiceClientGeneratorLib/Generators/NuGet/CoreNuspec.tt#L1) is superseded by [Nuspec.tt](https://github.com/aws/aws-sdk-net/blob/069f14d45721e53f582ee6a53074816f113ec799/generator/ServiceClientGeneratorLib/Generators/NuGet/Nuspec.tt#L1), which uses [NuGetTargetPlatform](https://github.com/aws/aws-sdk-net/blob/069f14d45721e53f582ee6a53074816f113ec799/generator/ServiceClientGeneratorLib/Generators/NuGet/Nuspec.tt#L35C97-L35C116), which somehow has the incorrect value for a dependency.

**Comment by dscpinheiro** [comment]
This should be fixed in the version of `AWSSDK.Core` that was just released (https://www.nuget.org/packages/AWSSDK.Core/3.7.400.11). 

The issue was the SDK repository includes a copy of `NuGet.exe` to create our packages (https://github.com/aws/aws-sdk-net/tree/main/sdk/.nuget), and its version was out of date (it was released before .NET 8 came out).
