### ISSUE TITLE
Elastic Transcoder requires empty string for notifications that are not required

### ISSUE THREAD

**Issue by phillip-haydon** [aws/aws-sdk-net#322]
During the creation of a pipeline:

```
Client.CreatePipeline(new CreatePipelineRequest
            {
                *snip*
                Notifications = new Notifications
                {
                    Completed = "arn:aws:sns:us-east-1:******:Video-Media-Completed",
                    Error = "",
                    Progressing = "",
                    Warning = ""
                }
            })
```

If you don't specify the un-required notifications:

e.g

```
                Notifications = new Notifications
                {
                    Completed = "arn:aws:sns:us-east-1:******:Video-Media-Completed"
                }
```

It throws an error saying:

> The "Error" field is not allowed to be null., The "Progressing" field is not allowed to be null., The "Warning" field is not allowed to be null.

This makes no sense considering the values can be an empty string to specify that there are no notifications to be raised for these events.

null should be allowed.

**Comment by gokarnm** [comment]
I agree with you that this is a poor experience. Unfortunately, this is the current service behavior. We have forwarded your feedback to the Elastic Transcoder team and they have added a backlog task to improve this functionality.

**Comment by phillip-haydon** [comment]
@gokarnm I disagree. This can be fixed in the SDK without needing to touch core transcoder, just default the values in the SDK to empty string and don't force me to have to do it, gives a better user experience without having to care about the elastic transcoder implementation.

**Comment by phillip-haydon** [comment]
@gorkarnm do you want me to send a PR fixing the ctor?

**Comment by PavelSafronov** [comment]
[Version 3.1.0.5 of the ElasticTranscoder package](https://www.nuget.org/packages/AWSSDK.ElasticTranscoder/3.1.0.5) now allows you to pass null values for notifications when calling CreatePipeline.

**Comment by phillip-haydon** [comment]
Awesome @PavelSafronov thank you very much :)
