### ISSUE TITLE
AWS Trusted Advisor List endpoints failing when paginating

### ISSUE THREAD

**Issue by devo-sausal** [aws/aws-sdk-net#3226]
### Describe the bug

AWS Trusted Advisor List endpoints are not able to fetch subsequent pages when using `NextToken`.

![image](https://github.com/aws/aws-sdk-net/assets/163878788/fdc64668-76a0-4f6f-b541-9654dd65f090)

### Expected Behavior

Provided `nextToken` should fetch the results from the subsequent page.

### Current Behavior

Provided `nextToken` results in 400 Bad Request response:
```json
{"message":"Pagination token exception in operation 'ListChecks': filter parameters changed in the request"}
```

This applies to other List endpoints, such as `ListRecommendations`

### Reproduction Steps

```csharp
using Amazon;
using Amazon.Runtime;
using Amazon.TrustedAdvisor;
using Amazon.TrustedAdvisor.Model;

namespace AmazonTrustedAdvisorBug;

public static class BugReproduce
{
	public static async Task BugReproduceAsync(AWSCredentials credentials)
	{
		var client = new AmazonTrustedAdvisorClient(credentials, RegionEndpoint.USEast1);
		
		var requestPage1 = new ListChecksRequest()
		{
			MaxResults = 1
		};
		var responsePage1 = await client.ListChecksAsync(requestPage1);

		if(!string.IsNullOrEmpty(responsePage1.NextToken))
		{
			var requestPage2 = new ListChecksRequest()
			{
				MaxResults = 1,
				NextToken = responsePage1.NextToken
			};

			// Throws an exception here.
			var responsePage2 = await client.ListChecksAsync(requestPage2);
		}
		else
		{
			throw new Exception("Unsuitable account setup. The account should have at least 2 check entries to ensure 2 pages can be fetched.");
		}
	}
}
```

### Possible Solution

It's very likely that `NextToken` is not whitelisted from the arguments list that are being checked when validating on the AWS TrustedAdvisor's api-side.

I assume the validation is here to ensure filter parameters don't change so that the formed query behind the scenes remains the same across the pages. However, if it simply checks the received query arguments and doesn't take nextToken as a special argument into account, then it doesn't comply with the documentation.
As per:
https://docs.aws.amazon.com/trustedadvisor/latest/APIReference/API_ListChecks.html#API_ListChecks_RequestParameters
`nextToken` = *The token for the next set of results. Use the value returned in the previous response in the next request to retrieve the next set of results.*

### Additional Information/Context

As previously mentioned, this is likely a broader issue with the API itself. I was able to reproduce this using AWS CLI as well.
`aws trustedadvisor list-checks --region=us-east-1 --debug --no-cli-pager --page-size=1`
> An error occurred (ValidationException) when calling the ListChecks operation: Pagination token exception in operation 'ListChecks': filter parameters changed in the request

It might be useful to forward this to the AWS Trusted Advisor team.

### AWS .NET SDK and/or Package version used

AWSSDK.TrustedAdvisor 3.7.300.53

### Targeted .NET Platform

.NET 7.0, .NET 8.0

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment]
This needs reproduction, perhaps comparing the behavior with AWS CLI and/or AWS Java SDK (v2).

**Comment by devo-sausal** [comment]
As of this moment, it appears that this have been fixed. AWS CLI is able to paginate, and TrustedAdvisor SDK works as intented.

AWS CLI command for reproduction step was listed under `Additional Context` where the command would have been this:
`aws trustedadvisor list-checks --region=us-east-1 --debug --no-cli-pager --page-size=1`
