### ISSUE TITLE
AWSSDK.Core triggers CWE-798 - Hardcoded credentials

### ISSUE THREAD

**Issue by skirk-mpr** [aws/aws-sdk-net#3240]
### Describe the bug

This is more of an FYI but our organization just turned on AWS Inspector for AWS Lambda and we are getting false positives for the finding **_CWE-798 - Hardcoded credentials_** in AWSSDK.Core.  

From the finding it looks like its complaining because the string 'password' is contained within the name of a property (EC2InstancePassword).  

![image](https://github.com/aws/aws-sdk-net/assets/42186060/22ab88f6-54b7-4276-9a79-c4a398f46a1e)

### Expected Behavior

Not trigger CWE-798 - Hardcoded credentials

### Current Behavior

Triggers CWE-798 - Hardcoded credentials

### Reproduction Steps

Deploy Lambda with AWSSDK.Core and run AWS Inspector against it.

### AWS .NET SDK and/or Package version used

AWSSDK.Core

### Targeted .NET Platform

.NET 6

### Operating System and version

AmazonLinux

**Comment by ashishdhingra** [comment]
Needs review with the team.

**Comment by ashishdhingra** [comment]
P124646133

**Comment by ashishdhingra** [comment]
@skirk-mpr I reviewed this issue with the team. There doesn't appear to be a way to ignore this false positive reported by AWS Inspector. I have opened internal ticket with AWS Inspector team to get their inputs on how to disable such false positives. Would report any updates here as it is available.

**Comment by skirk-mpr** [comment]
@ashishdhingra -- thanks so much, appreciate you circling back regarding this!  Figured there wasn't really something warranting a fix on the SDK side, but either way, wanted to flag it so your team was aware.  

Also, somilar thing is also getting flagged with `Amazon.Extensions.CognitoAuthenitcation`

![image](https://github.com/aws/aws-sdk-net/assets/42186060/dbac333c-ebab-47c5-9258-997e6574fe6a)

**Comment by ashishdhingra** [comment]
@skirk-mpr Additionally you might refer [Suppressing Amazon Inspector findings with suppression rules](https://docs.aws.amazon.com/inspector/latest/user/findings-managing-supression-rules.html) on how to create rule suppress such warnings.

**Comment by skirk-mpr** [comment]
Thank you, @ashishdhingra!

**Comment by ashishdhingra** [comment]
@skirk-mpr I would close this issue for now since I have created ticket for the service team. They are working internally on a fix.

**Comment by ashishdhingra** [comment]
@skirk-mpr Based on communication from service team, looks like they have implemented fix to exclude AWS SDK(s) from scanning.
