### ISSUE TITLE
NET core doesn't has S3FileInfo class

### ISSUE THREAD

**Issue by bnuzhouwei** [aws/aws-sdk-net#3272]
### Describe the feature

NET core doesn't has S3FileInfo class but net 4 does.

### Use Case

OpenWrite and Append is simple when support directly write data to streams.

### Proposed Solution

Support it

### Other Information

a

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

3.7.307.4

### Targeted .NET Platform

NET 6

### Operating System and version

All

**Comment by dscpinheiro** [comment]
I'll close this as a duplicate as we already have an existing feature request for `S3DirectoryInfo` (which would include `S3FileInfo` as well): https://github.com/aws/aws-sdk-net/issues/1461

It's in our backlog but it hasn't been prioritized yet.
