### ISSUE TITLE
AWSSDK.Core referencing very old System.Security.Cryptography.Algorithms

### ISSUE THREAD

**Issue by bartonjs** [aws/aws-sdk-net#329]
Creating a new dotnet core project, referencing AWSSDK.EC2 3.2.3-beta and NETStandard.Library 1.0.0-rc2-23925, and resolving dependencies emits:

```
warn : Detected package downgrade: System.Security.Cryptography.Algorithms from 4.0.0-rc3-23720 to 4.0.0-beta-23516
warn :  repro (>= 1.0.0) ->
    AWSSDK.EC2 (>= 3.2.3-beta) ->
    AWSSDK.Core (>= 3.2.3-beta && < 3.3.0-beta) ->
    System.Net.Http (>= 4.0.1-rc3-23720) ->
    runtime.linux.System.Net.Http (>= 4.0.1-rc3-23720) ->
    System.Security.Cryptography.Algorithms (>= 4.0.0-rc3-23720)
warn :  repro (>= 1.0.0) ->
    AWSSDK.EC2 (>= 3.2.3-beta) ->
    AWSSDK.Core (>= 3.2.3-beta && < 3.3.0-beta) ->
    System.Security.Cryptography.Algorithms (>= 4.0.0-beta-23516)
```
(artificial linebreaks inserted for legibility)

Some under the covers incompatibility has happened in the 4 months since that beta build, in particular a rename of the native shim targets.

The current tracking-to-release branch (1.0.0-rc2) build is System.Security.Cryptography.Algorithms-4.1.0-rc2-23925; and the current master build is System.Security.Cryptography.Algorithms-4.1.0-rc3-23925  (rc2 v rc3).  Note that the package version bumped from 4.0.0 to 4.1.0 (4.0.0 never had a stable build, but a dependency graph redraw happened to allow net46 compatibility separate from net461 compatibility).

**Comment by normj** [comment]
CoreCLR is in a weird state right now until rc2 is released to NuGet. I can't move the AWS SDK to System.Security.Cryptography.Algorithms-4.1.0-rc2-23925 because that is only available in the unstable myget feed. If I did anybody that pulls in the SDK and is using just the stable nuget feed would be broken. That would be anybody using CoreCLR from Visual Studio unless they were advanced enough to create a NuGet.Config file to add myget feed.

**Comment by bartonjs** [comment]
Hmm.  Well, that's a position that's hard to disagree with.

We're driving to get rc2 complete right now, so hopefully we'll have something newer on nuget soon.  In the meantime I'm hoping that an explicit reference to the new version solves the problem.

**Comment by bartonjs** [comment]
https://www.nuget.org/packages/System.Security.Cryptography.Algorithms/4.1.0-rc2-24027

"soon" apparently was a relative term. Anyways, just wanted to let you guys know that new packages were pushed.

**Comment by normj** [comment]
Thanks for the heads up!

**Comment by normj** [comment]
Version 3.2.4-beta was pushed which updates the SDK to RC2

**Comment by bartonjs** [comment]
Good to know.  Thanks :)
