### ISSUE TITLE
TransferUtility does not support downloading objects in Requester Pays buckets.

### ISSUE THREAD

**Issue by krishsingh-git** [aws/aws-sdk-net#3301]
### Describe the bug

TransferUtility does not support downloading objects in Requester Pays buckets.

await s3Client.DownloadToFilePathAsync(
                    s3Location.BucketName.Value, s3Location.Key.Value,
                    downloadPath.Path.Value, additionalProperties);

### Expected Behavior

TransferUtility does not support downloading objects in Requester Pays buckets.
allow download ,, remove access denied error

### Current Behavior

TransferUtility does not support downloading objects in Requester Pays buckets.

await s3Client.DownloadToFilePathAsync(
                    s3Location.BucketName.Value, s3Location.Key.Value,
                    downloadPath.Path.Value, additionalProperties);

### Reproduction Steps

await s3Client.DownloadToFilePathAsync(
                    s3Location.BucketName.Value, s3Location.Key.Value,
                    downloadPath.Path.Value, additionalProperties);

### Possible Solution

add requestpayer in transfer utility DownloadToFilePathAsync

### AWS .NET SDK and/or Package version used

AWSSDK.S3 3.7.9.17

### Targeted .NET Platform

.net core 3.1

### Operating System and version

window

**Comment by krishsingh-git** [comment]
its high priority ?can anyone look into issue

**Comment by bhoradc** [comment]
Hi @krishsingh-git, 

Thank you for reporting the issue. If you came across the `Access denied` error, when downloading object from a `Requester Pays` bucket using TransferUtility, can you kindly provide below additional information?

- Self-contained code sample that reproduces the `Access Denied` error.
- Does the Source and destination resides in cross-accounts?

Regards, 
Chaitanya

**Comment by krishsingh-git** [comment]
Hi,

We are using below method to download file

  await s3Client.DownloadToFilePathAsync(
                    s3Location.BucketName.Value, s3Location.Key.Value,
                    downloadPath.Path.Value, additionalProperties);


  *   Does the Source and destination resides in cross-accounts?
  *   Source: is S3 buclet destination is netwok path.

**Comment by krishsingh-git** [comment]
please make it P1,, in our organisation ,, its burning issue

**Comment by krishsingh-git** [comment]
please arrange a call i will explain

**Comment by bhoradc** [comment]
Hi @krishsingh-git,

I am able to reproduce the `Access Denied` AmazonS3Exception when downloading objects using the Transfer utility with `Requester Pays` enabled. 

Below are the steps and the code sample I used with the latest .NET SDK/Package version for reproduction. 

- Enabled `Requester pays` option from the console for the bucket in account A. 
- Configured the necessary bucket policies for `s3:GetObject` for the IAM role from account B. 
- Using below snippet, I am getting the S3 access exception when downloading the object (account A) from account B. 

```c#
using Amazon.S3;
using Amazon.S3.Transfer;
using System;
using System.Threading.Tasks;

namespace ReqPaysIssue_3301
{
    class Program
    {
        static async Task Main(string[] args)
        {
            try
            {
                IAmazonS3 s3Client = new AmazonS3Client();
                var transferUtil = new TransferUtility(s3Client);
                await transferUtil.DownloadAsync(new TransferUtilityDownloadRequest
                {
                    BucketName = <<bucket_name>>,
                    Key = <<key>>,
                    FilePath = <<file_path>>,
                });
            }
            catch (Exception ex)
            {
                await Console.Out.WriteLineAsync(ex.Message);
                throw;
            } 
        }     
    }    
}
```

Reproduced output:

`Access Denied
Unhandled exception. Amazon.S3.AmazonS3Exception: Access Denied
 ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.`

Kindly let me know if above reproduction is unclear or if you have any other observations. 

I will review this issue with the SDK team and keep you posted on the updates. 

Regards, 
Chaitanya

**Comment by ashishdhingra** [comment]
@krishsingh-git `RequestPayer` property should be available in `AWSSDK.S3` version `3.7.307.27` (refer [Chengelog](https://github.com/aws/aws-sdk-net/blob/main/changelogs/SDK.CHANGELOG.2024.md#378020-2024-05-02-1836-utc))

**Comment by krishsingh-git** [comment]
Thank you so much  for help.

I would suggest please reverify across AWSSDKS3 .net, if anywhere else required to add/enable "RequestPayer".
