### ISSUE TITLE
il2cpp-codegen.h Unknown type name '__declspec' NORETURN

### ISSUE THREAD

**Issue by TobiSchulz** [aws/aws-sdk-net#331]
Hey,

i have build my app on ios several times and it worked. Today i want to try a new touch script but ios build has failed.

il2cpp-codegen.h - Unknown type name '__declspec'
In file included from /Users/tobias/Projekte/myproject/iOS/Classes/Native/Bulk_AWSSDK.CognitoIdentity_1.cpp:98:
Expanded from macro 'NORETURN'

Expected ';' after top level declarator
In file included from /Users/tobias/Projekte/myproject/iOS/Classes/Native/Bulk_AWSSDK.CognitoIdentity_1.cpp:98:

I have not changed anything on aws side. Unity Player (ios) works perfect. Android Build works great too.

AWSSDK (24.03.2016) 3.1.56.0
Unity 5.3.1p2
iOS Build Target iPad 3 IOS 8

I don´t know what to do... hope you can help me.

Thank you

**Comment by karthiksaligrama** [comment]
can you paste your script that you wrote here?

**Comment by TobiSchulz** [comment]
sorry,

in my link.xml was AWSSDK.MobileAnalytics but it was not in my project (cause of AWSSDK update). Thats why exporting with unity got an UnusedBytecodeStripper2 error and on mono the xcode error above.

Now it works! Sorry for the to early Issue submit.

Thank you for your help and work!

**Comment by cmitides89** [comment]
I am having the same exact issue except mine says in file included from users....../il2cpp_output/Bulk_Assembly-CSharp-firstpass_1.cpp can some one help me? Thank you :)
