### ISSUE TITLE
V4 Development: Sensible LangVersion

### ISSUE THREAD

**Issue by danielmarbach** [aws/aws-sdk-net#3316]
### Describe the feature

Came up as a discussion point in https://github.com/aws/aws-sdk-net/pull/3293#discussion_r1593689240

### Use Case

At least make it possible to define static lambdas to avoid closure capturing.

### Proposed Solution

Target LangVersion or higher

Azure SDK targets now LangVersion 11 https://github.com/Azure/azure-sdk-for-net/pull/33890 even though they support net standard 2.0

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

v4

### Targeted .NET Platform

All

### Operating System and version

All

**Comment by dscpinheiro** [comment]
@danielmarbach I'm closing this since we're now using C# 11 for .NET 8 and C# 9 for the other TFMs (`net472`, `netstandard2.0`, and `netcoreapp3.1`).

I think that should be enough to use newer features, but please let us know if you have any other concerns.

**Comment by danielmarbach** [comment]
Is it worth the complexity of two lang versions? Why not have 11 across the board? You can shim/poly fill a lot (I already brought this up elsewhere) and for the very few things that requires runtime support you could add an analyzer or some other form of early capturing mechanism. Probably even a PR review checklist would do it.

**Comment by dscpinheiro** [comment]
I can bring this up with Norm when he gets back from vacation. Like you said, I believe the concern was getting C# 11 to work with the .NET Framework (I don't think he had a chance to look at / make a decision on whether we're going to use Polyfill / PolySharp).
