### ISSUE TITLE
Cannot Get DynamoDB record when model inherits from base class with member with the same name

### ISSUE THREAD

**Issue by alvaromon** [aws/aws-sdk-net#3343]
### Describe the bug

I am experiencing an issue getting a record from a Dynamo table when the model class inherits from a base class that includes a class member with the same name as the deriving class.

```C#
[DynamoDBTable("T-TableName")]
public class MyClass: BaseClass
{
    [DynamoDBHashKey]
    public new string Number
    {
        get => base.Number;
        set => base.Number = value;
    }
    public new List<string>? Addresses { get; set; }
}
```

```C#
public class BaseClass
{
    public string Number { get; set; }

    public IList<string> Addresses { get; set; }
}
```

Calling this function:
`context.LoadAsync<MyClass?>(hashKey);`

Throws a `InvalidOperationException`

This issue was noticed when upgrading AWSSDK packages from:

`AWSSDK.Core Version=3.7.100.23 --> AWSSDK.Core Version=3.7.302.20`
`AWSSDK.DynamoDBv2 Version=3.7.100.23 --> AWSSDK.DynamoDBv2 Version=3.7.302`

### Expected Behavior

The DynamoDB record with the matching hashKey is returned

### Current Behavior

InvalidOperationException is thrown with the following reason:

`Dictionary already contains item with key Addresses`

### Reproduction Steps

1. Create a model class for a DynamoDB record that inherits from a base class. The base class and inheriting class must have a class member with the same name. 

2. Try to get a record from the table using `LoadAsync<>` 

### Possible Solution

It seems this issue was resolved once already:

https://github.com/aws/aws-sdk-net/issues/906

### AWS .NET SDK and/or Package version used

AWSSDK.DynamoDBv2 Version=3.7.302
AWSSDK.Core Version=3.7.302.20

### Targeted .NET Platform

.NET Core 8

### Operating System and version

Windows 11

**Comment by YuriiMocherniuk** [comment]
I'm having a similar issue, also on .NET 8:
System.InvalidOperationException: Dictionary already contains item with key Usage
   at Amazon.Util.Internal.InternalSDKUtils.AddToDictionary[TKey,TValue](Dictionary`2 dictionary, TKey key, TValue value)
   at Amazon.DynamoDBv2.DataModel.StorageConfig.GetMembersDictionary(Type type)
   at Amazon.DynamoDBv2.DataModel.StorageConfig..ctor(Type targetType)
   at Amazon.DynamoDBv2.DataModel.ItemStorageConfig..ctor(Type targetType)
   at Amazon.DynamoDBv2.DataModel.ItemStorageConfigCache.CreateStorageConfig(Type baseType, String actualTableName, DynamoDBFlatConfig flatConfig)
   at Amazon.DynamoDBv2.DataModel.ItemStorageConfigCache.GetConfig(Type type, DynamoDBFlatConfig flatConfig, Boolean conversionOnly)
   at Amazon.DynamoDBv2.DataModel.BatchWrite`1..ctor(DynamoDBContext context, Type valuesType, DynamoDBFlatConfig config)
   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.CreateBatchWrite[T](DynamoDBOperationConfig operationConfig)

Do you think its origin is the same? Previously before .NET 8 and AWS NuGet packages upgrade we haven't been facing such problem.

**Comment by YuriiMocherniuk** [comment]
Extra information: the issue started to occur after the following NuGet package upgrade:
![image](https://github.com/aws/aws-sdk-net/assets/80033872/268b2760-838e-48aa-b643-beebc2e6877b)

**Comment by bhoradc** [comment]
Hello @alvaromon, 

Thank you for reporting the issue. Using below code sample I am able to reproduce the `InvalidOperationException` that you mentioned.

```c#
using Amazon.DynamoDBv2;
using Amazon.DynamoDBv2.DataModel;

namespace DDB_LoadAsync_3343
{
    public class Program
    {
        public static async Task Main()
        {
            Amazon.AWSConfigs.LoggingConfig.LogResponses = Amazon.ResponseLoggingOption.Always
            Amazon.AWSConfigs.LoggingConfig.LogTo = Amazon.LoggingOptions.Console;
            Amazon.AWSConfigs.AddTraceListener("Amazon", new System.Diagnostics.ConsoleTraceListener());

            var client = new AmazonDynamoDBClient();
            DynamoDBContext context = new DynamoDBContext(client);

            var d = new MyClass { Number = "3.7.302", Addresses = new List<string>() { "add1", "add2" } };

            await context.SaveAsync<MyClass>(d);

            var loaded = await context.LoadAsync<MyClass>(d.Number, d.Addresses);
        }

        private class BaseClass
        {
            public string Number { get; set; }
            public IList<string> Addresses { get; set; }
        }

        [DynamoDBTable("OverrideBase")]
        private class MyClass : BaseClass
        {
            [DynamoDBHashKey]
            public new string Number
            {
                get => base.Number;
                set => base.Number = value;
            }
            public new List<string>? Addresses { get; set; }  
        }
    }
}
```

I am able to reliably reproduce this error with `AWSSDK.DynamoDBv2 3.7.300` onwards. I will review this issue with the .NET SDK team to investigate it further. We shall keep you posted. 

Hi @YuriiMocherniuk, 

The error you mentioned looks similar. Can you provide code sample for your use-case? Also, I don't see the package version for `AWSSDK.DynamoDBv2` in the [screenshot](https://github.com/aws/aws-sdk-net/issues/3343#issuecomment-2173172760) that you shared. 
 
Regards, 
Chaitanya

**Comment by YuriiMocherniuk** [comment]
Hi @bhoradc,

Actually, we had several NuGet packages referenced in other projects and the AWSSDK.Core, AWSSDK.DynamoDBv2 packages probably got referenced here as a transitive dependencies (they haven't been referenced in this case explicitly).

As for the code that throws exception, overall it looks as follows:
```var batch = context.CreateBatchWrite<UsageItem>();```
context member here has DynamoDBContext type.

In this case there's Usage property present on both UsageItem class and its parent class. The type differs  as in your example with Addresses property and we also use new keyword in the child class. 

I hope this information helps with issue resolution.

Regards,
Yura

**Comment by philasmar** [comment]
We are currently working on a fix for this issue.

**Comment by philasmar** [comment]
We have released a fix for this bug today.

Please use the new package versions and try again:
AWSSDK.Core: **3.7.304.19**
AWSSDK.DynamoDBv2: **3.7.303.25**

**Comment by alvaromon** [comment]
thank you the team. That was very fast!
