### ISSUE TITLE
.Net 8 Blazor Webassembly does not work with Dynamodb

### ISSUE THREAD

**Issue by genifycom** [aws/aws-sdk-net#3347]
A simple scan request in Blazor Webassembly .Net 8 gets an exception. The identical code works in .Net 6 Core.

```
    public static async Task<string> ScanRequest()
    {
        IAmazonDynamoDB _ddbClient = new AmazonDynamoDBClient(aws_access_key, aws_secret_key, RegionEndpoint.USEast1);

        var request = new ScanRequest
        {
            TableName = "mytable",
            Limit = 10
        };

        try
        {
            var response = await _ddbClient.ScanAsync(request);
        }
        catch (Exception ex)
        {
            var msg = ex.Message;
        }
        return "done";
    }
```

Create client succeeds, but the ScanAsync gives 'The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.'

**Comment by normj** [comment]
Set the `UseAlternateUserAgentHeader` property to `true`. The user agent header is included as part of the signature but when you run in the browser with WebAssembly the browser changes the user agent string messing up the signature.

```
Amazon.AWSConfigs.UseAlternateUserAgentHeader = true;
```

Sorry this issue didn't come to my attention earlier. With the provided solution I'm going to close the issue assuming you haven't been waiting on this solution and hopefully found the answer somewhere else.

**Comment by genifycom** [comment]
Thanks Norm
