### ISSUE TITLE
Unable to connect to Timestream from using  endpoint (.Net)

### ISSUE THREAD

**Issue by Anna-Ignatov** [aws/aws-sdk-net#3349]
### Describe the bug

Trying to connect to Timestream from .Net using  query endpoint  - we are using private VPC

### Expected Behavior

Connect to Timestream

### Current Behavior

This is configuration we sent:
    _RegionEndpoint = RegionEndpoint.EUWest1,
    Timeout = tsConfig.Timeout,
    MaxErrorRetry = tsConfig.MaxErrorRetry,
    EndpointDiscoveryEnabled=true_     
And received
**_Amazon.Runtime.AmazonClientException: Failed to discover the endpoint for the request. Requests will not succeed until an endpoint can be retrieved or an endpoint is manually specified_**
We tried to specify also 
_ServiceURL= "https://query-cell1.timestream.eu-west-1.amazonaws.com"_
And received the same error.
We also tried to set   EndpointDiscoveryEnabled= false - with the same result
In case we do no specify service URL we receive
**The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing** 

### Reproduction Steps

var awsConfig=new AmazonTimestreamQueryConfig
            {
                RegionEndpoint = RegionEndpoint.EUWest1,
                Timeout = tsConfig.Timeout,
                MaxErrorRetry = tsConfig.MaxErrorRetry,
                EndpointDiscoveryEnabled=false
             //   ServiceURL= "https://query-cell1.timestream.eu-west-1.amazonaws.com"  
            };
            Services.AddScopedAsImplementedInterfaces<AmazonTimestreamQueryClient>(awsConfig);
            
We have a log of configuration:
 public AwsTimeSeriesRepository(TimeSeriesConfig config, IAmazonTimestreamQuery timestreamClient,
     ILogger<AwsTimeSeriesRepository> logger)
 {
     _timestreamQueryBuilder = new TimestreamQueryBuilder(config);
     _timestreamClient = timestreamClient;
     _logger = logger;
     _config = config;
     _logger.LogInformation("config={config}", JsonConvert.SerializeObject(_config));
     _logger.LogInformation("AWSConfig={awsConfig}", JsonConvert.SerializeObject(timestreamClient.Config));
 }

            Please, see the AWS configuration we received in log:
"ServiceId": "Timestream Query",
	"RegionEndpointServiceName": "query.timestream",
	"ServiceVersion": "2018-11-01",
	"UserAgent": "aws-sdk-dotnet-coreclr/3.7.301.22 ua/2.0 os/linux#5.10.217.205 md/ARCH#X64 lang/.NET_Core#7.0.20 md/aws-sdk-dotnet-core#3.7.304.17 api/Timestream Query#3.7.301.22",
	"Profile": null,
	"AWSTokenProvider": {
		"ProfileName": null
	},
	"SignatureMethod": 1,
	"SignatureVersion": "4",
	"UseAlternateUserAgentHeader": false,
	"RegionEndpoint": null,
	"ServiceURL": "
[https://query-cell1.timestream.eu-west-1.amazonaws.com/"](https://query-cell1.timestream.eu-west-1.amazonaws.com/%22)
,
	"UseHttp": false,
	"AuthenticationRegion": null,
	"AuthenticationServiceName": "timestream",
	"MaxErrorRetry": 1,
	"IsMaxErrorRetrySet": true,
	"LogResponse": false,
	"ReadEntireResponse": false,
	"BufferSize": 8192,
	"ProgressUpdateInterval": 102400,
	"ResignRetries": false,
	"AllowAutoRedirect": true,
	"LogMetrics": false,
	"DisableLogging": false,
	"DefaultConfigurationMode": 5,
	"ProxyCredentials": null,
	"Timeout": "1.00:00:00",
	"UseDualstackEndpoint": false,
	"UseFIPSEndpoint": false,
	"IgnoreConfiguredEndpointUrls": false,
	"DisableRequestCompression": false,
	"RequestMinCompressionSizeBytes": 10240,
	"ClientAppId": null,
	"ThrottleRetries": true,
	"CorrectedUtcNow": "2024-06-20T12:44:10.776782+00:00",
	"ClockOffset": "00:00:00",
	"DisableHostPrefixInjection": false,
	"EndpointDiscoveryEnabled": false,
	"EndpointDiscoveryCacheLimit": 1000,
	"RetryMode": 0,
	"FastFailRequests": false,
	"CacheHttpClient": true,
	"HttpClientCacheSize": 1,
	"ReadWriteTimeout": null,
	"EndpointProvider": {},
	"ProxyHost": null,
	"ProxyPort": 0,
	"MaxConnectionsPerServer": null,
	"HttpClientFactory": null
}

### AWS .NET SDK and/or Package version used

AWSSDK.TimestreamQuery" Version="3.7.301.22"

### Targeted .NET Platform

.Net7

### Operating System and version

AmazonLinux

**Comment by ashishdhingra** [comment]
@Anna-Ignatov Good morning. Thanks for opening the issue. [Service endpoints](https://docs.aws.amazon.com/general/latest/gr/timestream.html) lists the service endpoints for TimeStream. Could you try or confirm below:
- Enable verbose logging using code below and share/examine the detailed log for exact error:
  ```C#
  Amazon.AWSConfigs.LoggingConfig.LogResponses = Amazon.ResponseLoggingOption.Always;
  Amazon.AWSConfigs.LoggingConfig.LogTo = Amazon.LoggingOptions.SystemDiagnostics;
  Amazon.AWSConfigs.AddTraceListener("Amazon", new System.Diagnostics.ConsoleTraceListener());
  ```
  You may develop a simple console application and run it on your EC2 instance in private VPC to isolate the configuration.
- Check your VPC for security group rules that might be blocking outgoing traffic.

Thanks,
Ashish

**Comment by dscpinheiro** [comment]
@Anna-Ignatov and @amraninoam Did this exception start happening after you updated the `AWSSDK.TimestreamQuery` package? There was a change on how the SDK resolves endpoints in version `3.7.100`, so I'm trying to understand if this was an unintended side effect.

**Comment by amraninoam** [comment]
@dscpinheiro , I have tried it with the latest SDK, you can find my code [here](https://github.com/amraninoam/TimestreamQuery-DotNet), and the specific SDK versions [here](https://github.com/amraninoam/TimestreamQuery-DotNet/blob/e9c0e14af97eba2b767e814d9598b77a45ac98f9/TimestreamQuery/TimestreamQuery.csproj#L11)
I also tried with [lower SDKs on a different branch ](https://github.com/amraninoam/TimestreamQuery-DotNet/blob/1551237699d146f8aa57336f974814dcaec88b98/TimestreamQuery/TimestreamQuery.csproj#L11), it result in the same behaviour as 3.7.300.

**Comment by dscpinheiro** [comment]
Thanks for the repository, it was helpful when we were troubleshooting the problem.

I put out a PR (https://github.com/aws/aws-sdk-net/pull/3367) that was included in today’s release; it has more details but as you mentioned it was related to the custom service URL and an odd TimeStream behavior we weren’t accounting for.

Would you be able to test again with the latest version of the `AWSSDK.TimestreamQuery` package (which is [3.7.301.29](https://www.nuget.org/packages/AWSSDK.TimestreamQuery/3.7.301.29)) and let us know if the fix worked for you?

**Comment by amraninoam** [comment]
Running the [new package](https://github.com/amraninoam/TimestreamQuery-DotNet/blob/cfebcc52a1541dc0b69f6efdf93100cea56538bf/TimestreamQuery/TimestreamQuery.csproj#L16):
1. serviceURL=https://query-cell1.timestream.eu-west-1.amazonaws.com works as expected in an environment with internet.
I will check it later on with vpc endpoint and no internet connection and will update.
2. [Skipping serviceURL](https://github.com/amraninoam/TimestreamQuery-DotNet/blob/cfebcc52a1541dc0b69f6efdf93100cea56538bf/TimestreamQuery/Program.cs#L37) and passing only region works as expected: Calling https://query.timestream.eu-west-1.amazonaws.com first, and then https://query-cell1.timestream.eu-west-1.amazonaws.com
3. serviceURL=https://query.timestream.eu-west-1.amazonaws.com fails with exception that IMHO is hard to decipher: 
```
AWS Timestream Query Error: The service returned an error with Error Code UnknownOperationException and HTTP Body: {"__type":"com.amazon.coral.service#UnknownOperationException"}
Error Code: UnknownOperationException
Error Type: Unknown
Request ID: 589eabc6-e0b7-44b1-bddd-38f580a12bed
```

**Comment by dscpinheiro** [comment]
Great, glad it solved your issue! I agree that exception is hard to understand, unfortunately TimeStream has this odd behaviour where the operations requiring endpoint discovery (e.g. `Query`) _only work_ when using the _cell_ endpoints.

I mentioned this in my PR too, but this is one of the reasons we don't use the endpoint discovery for new services (as you noticed, you can run into a few sharp edges).
