### ISSUE TITLE
When cancelled, dynamodb.eu-west-1.amazonaws.com throws an exception instead of returning HTTP code

### ISSUE THREAD

**Issue by AleksandrsJakovlevsVisma** [aws/aws-sdk-net#3355]
### Describe the bug

dynamodb.eu-west-1.amazonaws.com exits gracefully when for example one tries to update an entity that doesn't exist (it returns 400), however, if the request has been canceled, the server throws TaskCanceledException

### Expected Behavior

dynamodb.eu-west-1.amazonaws.com should return some HTTP error code (400, for example) when the request is canceled.

### Current Behavior

It throws TaskCanceledException exception

### Reproduction Steps

1. Issue a POST request with a cancellation token
2. Make sure the cancellation token is canceled before the request finishes processing
3. Observe the exception

### Additional Information/Context

I have been using AWSSDK.DynamoDBv2 nuget package to call the server. Libraries correctly throw TaskCancelledException when dynamodb request throws that exception, however, I expect the server not to throw that exception. I realize this might not be the place to report this, but I am hoping that if that's indeed a wrong place, someone would point me to the correct one

### AWS .NET SDK and/or Package version used

AWSSDK.DynamoDBv2 3.7.301.20

### Targeted .NET Platform

.NET 8

### Operating System and version

Windows 11

**Comment by normj** [comment]
When the cancellation token is canceled that is all handled on the client side. It could even happen before the request is even sent to the AWS service. The .NET runtime is what generates the `TaskCanceledException`.
