### ISSUE TITLE
AWS SDK (Unity) Support for Windows Store (Hololens)

### ISSUE THREAD

**Issue by ryrich** [aws/aws-sdk-net#337]
Is there any way to configure the AWS unitypackages so they can be built on platform "Windows Store" so it can be used with Hololens? Or any information on if that is being looked at for a future version?

Thanks much,

Ryan R.

**Comment by karthiksaligrama** [comment]
@ryrich at this time we do not support windows store apps for unity. This has been added to our feature requests for now.
