### ISSUE TITLE
Support for conditional writes in DynamoDBContext

### ISSUE THREAD

**Issue by bslatner** [aws/aws-sdk-net#338]
If that support is there, I can't find it. It's really the only thing keeping me from using it across the board. As it stands, I have multiple cases where I use AmazonDynamoDBClient.PutItem to create items, and the DynamoDBContext for everything else.

**Comment by PavelSafronov** [comment]
Out of the box the DynamoDBContext provides support for conditional writes only through the ```DynamoDBVersion``` attribute. Here's the [developer guide](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/VersionSupportHLAPI.html) with more information, though the short of it is that you designate a specific field on your POCO and this is used to make sure that you are the only one updating that specific item.

If you need to specify other conditions, you'll need to use either the client (as you're doing now), or the Table object. Below is an example of putting an item with a condition, while still mostly working with POCOs (in this case, the class is Product).

```
var table = Context.GetTargetTable<Product>();
var document = Context.ToDocument(product);

Expression expression = new Expression
{
    ExpressionStatement = "attribute_not_exists(referencecounter) or referencecounter = :cond1",
    ExpressionAttributeValues = new Dictionary<string, DynamoDBEntry>
    {
        {":cond1", 0}
    }
};
PutItemOperationConfig config = new PutItemOperationConfig
{
    ConditionalExpression = expression
};
table.PutItem(document, config);
```
