### ISSUE TITLE
AmazonBedrockRuntimeClient and anthropic.claude-3-5-sonnet-20240620-v1:0 throw exception

### ISSUE THREAD

**Issue by Clive321A** [aws/aws-sdk-net#3384]
### Describe the bug

Trying to execute a query, and its not clear from documentation (or I cant find) whether I can use AmazonBedrockRuntimeClient to run against anthropic.claude-3-5-sonnet-20240620-v1:0 models

I get this error, which seems to indicate im not calling the correct method, but there are no other ways to invoke Bedrock using the runtime client.

Amazon.BedrockRuntime.Model.ValidationException: 'Malformed input request: #: required key [prompt] not found#: required key [max_tokens_to_sample] not found#: extraneous key [Messages] is not permitted#: extraneous key [MaxTokens] is not permitted#: extraneous key [AnthropicVersion] is not permitted, please reformat your input and try again.'

### Expected Behavior

Query executes without exception

### Current Behavior

Amazon.BedrockRuntime.Model.ValidationException: 'Malformed input request: #: required key [prompt] not found#: required key [max_tokens_to_sample] not found#: extraneous key [Messages] is not permitted#: extraneous key [MaxTokens] is not permitted#: extraneous key [AnthropicVersion] is not permitted, please reformat your input and try again.'

### Reproduction Steps

```
body =new ClaudeMessageBody() //my class
{
   "anthropic_version":"bedrock-2023-05-31",
   "max_tokens":1000,
   "Messages":[
      {
         "Role":"user",
         "Content":[
            {
               "Type":"pdf",
               "Source":{
                  "Type":"base64",
                  "media_type":"application/pdf",
                  "Data":"JVBERi0xLjQKJd....xxxxxxxxxxxxxx"
               },
               "Text":null
            },
            {
               "Type":"text",
               "Text":"Please Summarise this"
            }
         ]
      }
   ]
}

var jsonBody = JsonConvert.SerializeObject(body);
var bodyStream = new MemoryStream(Encoding.UTF8.GetBytes(jsonBody));

   var request = new InvokeModelRequest
   {
       ModelId = "anthropic.claude-3-5-sonnet-20240620-v1:0",
       ContentType = "application/json",
       Accept = "application/json",                    
       Body = bodyStream
       
   };

 using (AmazonBedrockRuntimeClient client = GetAwsClient())
 {
InvokeModelResponse response = await client.InvokeModelAsync(payload);
}

```

### Possible Solution

Im unsure if I can use AmazonBedrockRuntimeClient  with Claude 3.5,  If not is there an alternative?

### Additional Information/Context

Im unsure if I can use AmazonBedrockRuntimeClient  with Claude 3.5,  If not is there an alternative?

### AWS .NET SDK and/or Package version used

AWSSDK.Bedrock 3.7.302.36

### Targeted .NET Platform

.NET 8
Region us-east-1
And we have permission to that Model

### Operating System and version

Windows 10, Linux

**Comment by bhoradc** [comment]
Hello @Clive321A, 

Apologies for long silence here. For some reasons, I am unable to reproduce the exception using Claude 3.5 model. 

Meanwhile I tried below code sample to run the Multimodal prompt with Claude 3 model instead. 

```c#
 static async Task Main(string[] args)
 {
     string modelId = "anthropic.claude-3-sonnet-20240229-v1:0";
     string base64PdfData = "/9j/4Q/+RXhpZgAATU0A....";

     var messageBody = new Dictionary<string, object>()
     {
         ["anthropic_version"] = "bedrock-2023-05-31",
         ["max_tokens"] = 1000,
         ["messages"] = new List<object>()
                 {
                      new Dictionary<string, object>()
                      {
                           ["role"] = "user",
                           ["content"] = new List<object>()
                           {
                               new Dictionary<string, object>()
                               {
                                    ["type"] = "image",
                                    ["source"] = new Dictionary<string, object>()
                                    {
                                         ["type"] = "base64",
                                         ["media_type"] = "image/jpeg",
                                         ["data"] = base64PdfData
                                    },
                               },
                               new Dictionary<string, object>()
                               {
                                   ["type"] = "text",
                                   ["text"] = "Please Summarise this"
                               }
                           }
                      }
                 }
     };

     var jsonBody = JsonConvert.SerializeObject(messageBody);
     var bodyStream = new MemoryStream(Encoding.UTF8.GetBytes(jsonBody));

     var request = new InvokeModelRequest
     {
         ModelId = modelId,
         ContentType = "application/json",
         Accept = "application/json",
         Body = bodyStream
     };

     try
     {
         AmazonBedrockRuntimeClient client = GetAwsClient();
         InvokeModelResponse response = await client.InvokeModelAsync(request);
         Console.WriteLine("Response:");

         var modelResponse = await JsonNode.ParseAsync(response.Body);
         var responseText = modelResponse["content"]?[0]?["text"] ?? "";
         Console.WriteLine(responseText);
     }
     catch (AmazonServiceException e)
     {
         Console.WriteLine("Error: " + e.Message);
     }
 }

 private static AmazonBedrockRuntimeClient GetAwsClient()
 {
     return new AmazonBedrockRuntimeClient();
 }
 ```

Above code results in a proper response, no exception thrown. 

* If I update the key  `["anthropic_version"]` to `["Anthropic_version"]` and `["messages"]` to `["Messages"]` I get below exception (similar to one you got on Claude 3.5).

```log
Error: Malformed input request: #: required key [prompt] not found#: required key [max_tokens_to_sample] not found#: extraneous key [Messages] is not permitted#: extraneous key [max_tokens] is not permitted#: extraneous key [Anthropic_version] is not permitted, please reformat your input and try again.
```

* Can you confirm if you get the exception when running with other models (like Claude 3)?

* It may not be related to the exception directly, but I couldn't find `pdf` as one of the supported content type. Valid values are image and text, per [Anthropic Claude Messages API](https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-anthropic-claude-messages.html#model-parameters-anthropic-claude-messages-request-response).

* Can you provide more context for setting `"Text":null` on the Message Input and `payload` used on `client.InvokeModelAsync(payload)`?

Regards, 
Chaitanya
