### ISSUE TITLE
SSO fails with "Failed to find sso_session"

### ISSUE THREAD

**Issue by bazzilic** [aws/aws-sdk-net#3393]
### Describe the bug

When trying to use SSO with a .NET 8 app, it fails with `Amazon.Runtime.AmazonClientException: Invalid Configuration.  Failed to find sso_session [Acme Dev]` even though `aws sso login` was done before, and SSO seemingly worked fine (e.g., I can do `aws s3 ls --profile acme-dev` and it works).

### Expected Behavior

.NET 8 app is able to auth with AWS using SSO.

### Current Behavior

Fails with an exception

`Amazon.Runtime.AmazonClientException: Invalid Configuration.  Failed to find sso_session [Acme Dev]`

#### 1. Configure SSO
```
❯ aws configure sso
SSO session name (Recommended): Acme Dev
SSO start URL [None]: https://*********.awsapps.com/start/#
SSO region [None]: **-****-1
SSO registration scopes [sso:account:access]:
Attempting to automatically open the SSO authorization page in your default browser.
If the browser does not open or you wish to use a different device to authorize this request, open the following URL:

https://device.sso.**-****-1.amazonaws.com/

Then enter the code:

****-****
There are 3 AWS accounts available to you.
Using the account ID **************
The only role available to you is: dev-admin
Using the role name "dev-admin"
CLI default client Region [None]:
CLI default output format [None]:
CLI profile name [dev-admin-************]: acme-dev

To use this profile, specify the profile name using --profile, as shown:

aws s3 ls --profile acme-dev
```

Checking that it works:

```
❯ aws s3 ls --profile acme-dev
...
here it outputs an actual list of my buckets
...
```

#### 2. Check the Profile File
```
❯ cat ~/.aws/config
[profile acme-dev]
sso_session = Acme Dev
sso_account_id = ***********
sso_role_name = dev-admin
[sso-session 'Acme Dev']
sso_start_url = https://*********.awsapps.com/start/#
sso_region = **-****-1
sso_registration_scopes = sso:account:access
```

#### 3. Use SSO in .NET App

First, set the environment variable: `AWS_PROFILE=acme-dev`

Then in my code:

```csharp
namespace Example;
public static class Settings {
  static Settings() {
    var region = RegionEndpoint.GetBySystemName("**-****-1"); // redacted
    var s3Client = new AmazonS3Client(region);
  }
}
```

Launching the program fails on `new AmazonS3Client(region);` with the following stack trace:
```
Unhandled exception. System.TypeInitializationException: The type initializer for 'Example.Settings' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Amazon.Runtime.Internal.FallbackInternalConfigurationFactory' threw an exception.
 ---> Amazon.Runtime.AmazonClientException: Invalid Configuration.  Failed to find sso_session [Acme Dev]
   at Amazon.Runtime.CredentialManagement.SharedCredentialsFile.TryGetProfile(String profileName, Boolean doRefresh, Boolean isSsoSession, Boolean isServicesSection, CredentialProfile& profile)
   at Amazon.Runtime.CredentialManagement.SharedCredentialsFile.TryGetProfile(String profileName, CredentialProfile& profile)
   at Amazon.Runtime.CredentialManagement.CredentialProfileStoreChain.TryGetProfile(String profileName, CredentialProfile& profile)
   at Amazon.Runtime.Internal.ProfileInternalConfiguration.Setup(ICredentialProfileSource source, String profileName)
   at Amazon.Runtime.Internal.ProfileInternalConfiguration..ctor(ICredentialProfileSource source)
   at Amazon.Runtime.Internal.FallbackInternalConfigurationFactory.Reset()
   at Amazon.Runtime.Internal.FallbackInternalConfigurationFactory..cctor()
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.FallbackInternalConfigurationFactory.get_IgnoreConfiguredEndpointUrls()
   at Amazon.Runtime.ClientConfig.get_IgnoreConfiguredEndpointUrls()
   at Amazon.Runtime.ClientConfig.get_ServiceURL()
   at Amazon.S3.AmazonS3Config.Validate()
   at Amazon.Runtime.AmazonServiceClient..ctor(AWSCredentials credentials, ClientConfig config)
   at Amazon.S3.AmazonS3Client..ctor(RegionEndpoint region)
   at Example.Settings..cctor() in /path/to/app/src/Settings.cs:line 31
   --- End of inner exception stack trace ---
```

### AWS .NET SDK and/or Package version used

AWSSDK.CORE – 3.7.304.30
AWSSDK.S3 – 3.7.310.7
AWSSDK.SecretsManager.Caching – 1.0.6
AWSSDK.SSO – 3.7.300.119
AWSSDK.SSOIDC – 3.7.302.30

### Targeted .NET Platform

.NET 8

### Operating System and version

OSX Sonoma 14.5

**Comment by dscpinheiro** [comment]
The error message could be better, but can you check if using a session name without spaces (i.e. `acme-dev`) works? Even though the CLI supports this use case, .NET (and other SDKs) are following this specification (https://docs.aws.amazon.com/sdkref/latest/guide/file-format.html): 

> A section definition is a line that applies a name to a collection of settings. Section definition lines start and end with square brackets (`[` `]`). Inside the brackets, there is a section type identifier and a custom name for the section. You can use letters, numbers, hyphens (`-`), and underscores (`_`), but no spaces.

Here's a similar report for the Rust SDK (that one was related to the profile name, but same logic applies to the SSO section): https://github.com/awslabs/aws-sdk-rust/issues/1097

**Comment by bazzilic** [comment]
Indeed, that worked, thank you @dscpinheiro!
I feel that this discrepancy is quite confusing though.

**Comment by dscpinheiro** [comment]
Agree. In hindsight the CLI shouldn't have allowed this format, but at this point it'd be a breaking change for them to fix it.

**Comment by jmwoliver** [comment]
Relatedly, I had this happen with the Go SDK today and removing the space fixed it for me too.

```go
import "github.com/aws/aws-sdk-go/aws/session"

sess, err := session.NewSessionWithOptions(s3Options)
if err != nil {
  return nil, err
}
```

Returns this error:
```
failed to find SSO session section, Acme Dev
```

Using `acme-dev` instead with `aws configure sso` solved the issue.
