### ISSUE TITLE
SSH key forwarding when launching instance

### ISSUE THREAD

**Issue by mj-nowak** [aws/aws-sdk-net#340]
Is it possible to setup ssh key forwarding?  We have a bastion host server that we ssh into and then we are then able to ssh into other servers in our ASG.  I have set the default Putty settings to have "agent forwarding" enabled and am able to reach our servers in the ASG no problem if I connect manually , but if I connect to the bastion host through Visual Studio, the key is not being forwarded and the connection is refused.  Please let me know if this is something simple I am missing because I was not able to find much, if not any reference to this feature online.  Thank you!

**Comment by PavelSafronov** [comment]
Can you clarify exactly what you are trying to do in Visual Studio and what errors you are receiving?

**Comment by mj-nowak** [comment]
Yeah sorry, the stack I am working on now launches an instance we call our "Bastion Host", it also launches 2 Consul node servers as part of a ASG.  The way our security groups/networking is setup, you cannot directly connect to the Consul node servers, you must first SSH into the Bastion server, then SSH from that server into the Consul node servers.  In order for the key the authenticate to the Consul nodes you must turn on "Allow agent forwarding" inside putty (Connection->SSH->Auth->Authentication parameters).  This works if I manually open a putty session, and I have this setting turned on by default.  However, if I right click the Bastion Server instance inside VS using the AWS toolkit and hit "Open SSH session", I am able to connect to that server, but if I try to SSH into a node the connection is refused because I am assuming the "agent forwarding" is not enabled in that particular putty session.

UPDATE:  As I was writing this and getting the terminal output to try and show you what was happening, I was able to connect to the Consul node through the method I was explaining above.  Im not sure what changed (maybe a restart?) but it is now working.  Sorry for the unnecessary ticket!

**Comment by normj** [comment]
Glad you were able to fix the issue
