### ISSUE TITLE
IoT Core MQTT with SQS and .NET Framework 4.8 intermittently drops payload attribute

### ISSUE THREAD

**Issue by nfvelado** [aws/aws-sdk-net#3405]
### Describe the bug

When ingesting MQTT under load to a single device, where the device sends a message, then the server sends a message over and over, and an SQS payload topic rule is used:

SELECT * as payload, topic() as topic, traceid() as traceId, clientId() as clientId, principal() as principalId, sourceip() as ipAddress FROM 'device/+/mo/#'

Where the .NET Framework CDK is used to read SQS messages, an intermittent SQS message is received without a payload attribute as shown here:

Body: {
  "topic": "device/NT-00999/mo/data/38",
  "traceId": "3e090b84-30a8-2b9d-e8b5-9163864624dd",
  "clientId": "NT-00999",
  "principalId": "981307f9ed56b5ebede3f576ac86b027dba5517f8f5eec4e2a7a3d7cd9cc6ce5",
  "ipAddress": "207.189.176.142"
}

A similar problem was originally observed when using a base64 MQTT payload, where the payload delivered would intermittently have the \n as the starting character of the payload and be missing a trailing length character.  From here, I switched back to JSON payloads, where the symptom seems to be a complete loss of the payload attribute.

### Expected Behavior

The payload attribute should be present and correct with all packets, as it is with most packets.

### Current Behavior

The payload attribute is dropped when parsing incoming messages here and as shown in the log snipit above:

        var client = m_sqsClient;

        var request = new ReceiveMessageRequest
        {
          QueueUrl = queueUrl,
          AttributeNames = attributeNames,
          MaxNumberOfMessages = maxNumberOfMessages,
          VisibilityTimeout = visibilityTimeout,
          WaitTimeSeconds = waitTimeSeconds,           
        };

        while (true)
        {
          var response = await client.ReceiveMessageAsync(request);

          if (response.Messages.Count > 0)
          {

### Reproduction Steps

Using .NET Framework 8, with AWSSDK version 3.7.400.1 (and previous versions).  Client 1 sends a publish to topic A, at which time client 2 sends a response to topic B, and client 1 sends a response to topic C.  From here, there are back to back messages that include client 2 sending a message on topic B and client 1 sending a response to topic C.  After around 30-40 messages, the SQS message received via the .NET SDK is missing the payload attribute.

IoT Payload Rule:
SELECT * as payload, topic() as topic, traceid() as traceId, clientId() as clientId, principal() as principalId, sourceip() as ipAddress FROM 'device/+/mo/#'

delivered SQS message:
Body: {
  "topic": "device/NT-00999/mo/data/38",
  "traceId": "3e090b84-30a8-2b9d-e8b5-9163864624dd",
  "clientId": "NT-00999",
  "principalId": "981307f9ed56b5ebede3f576ac86b027dba5517f8f5eec4e2a7a3d7cd9cc6ce5",
  "ipAddress": "207.189.176.142"
}

Additionally, and separate, when using a base64 payload, sending a single message from client 2 on topic B results in a malformed base64 encoded payload with the rule:
SELECT encode(*, 'base64') as payload, topic() as topic, traceid() as traceId, clientId() as clientId, principal() as principalId, sourceip() as ipAddress FROM 'device/+/mo/#'

Here, the payload starts with a '\n' character and is missing a trailing length character delimiter.

### Possible Solution

Assuming a race condition is present in the IoT Core rule processing, or more likely, on the .NET client SDK receiving the SQS message.

### AWS .NET SDK and/or Package version used

AWSSDK 3.7.400.1

### Targeted .NET Platform

.NET Framework 4.8

### Operating System and version

Windows 11 Pro

**Comment by nfvelado** [comment]
If the SQS message is not deleted, upon re-delivery, it also is missing the payload block again.

**Comment by ashishdhingra** [comment]
@nfvelado Good afternoon. Could you please share the following:
- Complete minimal reproducible code, rather than a code snippet. The snippet you shared is just a basic code form receiving SQS messages.
- List of all packages used in your project, specifically `IoT Core MQTT`
- Was the issue happening earlier or started happening after package upgrade? If yes, please share the list of packages used before and after the error started happening.
- Logs, if any.

Thanks,
Ashish

**Comment by nfvelado** [comment]
Hi Ashish, thanks for the quick response.  Issue was happening before and after the SDK upgrade.  

I meant .NET Framework SDK, not CDK above.

Query above is set as an IoT Core message routing payload rule that forwards to an SQS queue.  Please close for the time being, until I can find a way to reproduce more consistently with a better trace.  Thanks,

Nick
