### ISSUE TITLE
Return MemoryStreams with accessible buffers

### ISSUE THREAD

**Issue by paulomorgado** [aws/aws-sdk-net#3409]
### Describe the feature

At least APIs in the `KeyManagementService` return values in `MemoryStream`.

However, the internal buffer is not exposable to the user causing unnecessary memory copies.

### Use Case

```csharp
using var kmsClient = new AmazonKeyManagementServiceClient(awsAccessKey, awsSecretAccessKey, region);

// ...

var decryptRequest = new DecryptRequest
{
    // ...
};

var decryptedMessage = await kmsClient.DecryptAsync(decryptRequest, default);

decryptedMessage.Plaintext.GetBuffer(); // <- throws System.UnauthorizedAccessException: 'MemoryStream's internal buffer cannot be accessed.'
```

### Proposed Solution

Most usages I've seem, the `MemoryStream` is used only to wrap a `byte[]` created just for that.

Using [`MemoryStream(Byte[], Int32, Int32, Boolean, Boolean)`](https://learn.microsoft.com/en-us/dotnet/api/system.io.memorystream.-ctor#system-io-memorystream-ctor(system-byte()-system-int32-system-int32-system-boolean-system-boolean)), instead of [`MemoryStream(Byte[])`](https://learn.microsoft.com/en-us/dotnet/api/system.io.memorystream.-ctor#system-io-memorystream-ctor(system-byte())), would expose the internal buffer and, thus, not requiring extra allocations and copies.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

AWSSDK.KeyManagementService 3.7.300.52

### Targeted .NET Platform

.NET 8

### Operating System and version

Windows and Linux

**Comment by normj** [comment]
Oh I like this idea. Thanks for the suggestion.

**Comment by paulomorgado** [comment]
> Oh I like this idea. Thanks for the suggestion.

I can bootstrap a PR, if you'd like me to.

**Comment by normj** [comment]
I had sometime and was able to put a PR out. I did the work in a V4 development branch which we are hoping to get previews out soonish.

**Comment by paulomorgado** [comment]
Those seem the ones immediately impacting `KeyManagementService`.

But there seems to be a lot more: https://github.com/search?q=repo%3Aaws%2Faws-sdk-net%20%22new%20MemoryStream(%22&type=code

**Comment by normj** [comment]
Those are internal usages of MemoryStream that don't need access to the `GetBuffer`. The spot of code I changed affects all of the MemoryStreams that are created on the response objects of service calls. Where you would interact with them directly.

**Comment by normj** [comment]
Closing as PR has been merged into V4.
