### ISSUE TITLE
Do not create strings just for comparison

### ISSUE THREAD

**Issue by paulomorgado** [aws/aws-sdk-net#3411]
### Describe the feature

`Amazon.Runtime.Internal.Marshaller.PreInvoke` has this code:

```csharp
#if NETSTANDARD
            var method = requestContext.Request.HttpMethod.ToUpperInvariant();
#else
            var method = requestContext.Request.HttpMethod.ToUpper(CultureInfo.InvariantCulture);
#endif
            if (method != "GET" && method != "DELETE" && method != "HEAD")
```

`method` is only used for comparison and can potentially be a newly allocated string.

### Use Case

Creating objects that do not need to be created, not only uses memory and CPU to create them, but also causes GC work.

### Proposed Solution

Use [`Equals(String, String, StringComparison)`](https://learn.microsoft.com/en-us/dotnet/api/system.string.equals#system-string-equals(system-string-system-string-system-stringcomparison)) with [`StringComparison.OrdinalIgnoreCase`](https://learn.microsoft.com/en-us/dotnet/api/system.stringcomparison), instead:

```csharp
            var method = requestContext.Request.HttpMethod;
            if (!"GET".Equals(method, StringComparison.OrdinalIgnoreCase)
                && "DELETE".Equals(method, StringComparison.OrdinalIgnoreCase)
                && "HEAD".Equals(method, StringComparison.OrdinalIgnoreCase))
```

Ordinal ignore-case comparison can also be used in dictionaries, avoiding creating creating new strings just for index lookup.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

AWSSDK.KeyManagementService 3.7.300.52

### Targeted .NET Platform

.NET 8

### Operating System and version

Windows and Linux

**Comment by ashishdhingra** [comment]
Appears to be valid suggestion. Needs review with the team.

**Comment by ashovlin** [comment]
We refactored that code that was inspecting the HTTP verbs recently via https://github.com/aws/aws-sdk-net/pull/3338.

Though there are likely other occurrences of creating strings for comparisons, if you have others that are in a hot spot.

**Comment by paulomorgado** [comment]
> @paulomorgado Good morning. Thanks for opening the issue. Could you please point me to the exact location of code which you are referring to? I'm unable to find the code you are referring to [here](https://github.com/aws/aws-sdk-net/blob/main/sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/Marshaller.cs).
> 
> Thanks, Ashish

According to @ashovlin, this code has been replaced.
