### ISSUE TITLE
Avoid creating unnecessary intermediate strings

### ISSUE THREAD

**Issue by paulomorgado** [aws/aws-sdk-net#3415]
### Describe the feature

I found in the code base code like this:

```csharp
            using (StringWriter stringWriter = new StringWriter(CultureInfo.InvariantCulture))
            {
                // ...
                string snippet = stringWriter.ToString();
                request.Content = System.Text.Encoding.UTF8.GetBytes(snippet);
            }
```

`StringWriter` uses an internal `StringBuilder` that will be used to produce a `string` just to get the `utf-8` bytes.

### Use Case

Creating objects that do not need to be created, not only uses memory and CPU to create them, but also causes GC work.

### Proposed Solution

Consider using a `StreamWriter` instead:

```csharp
using (var ms = new MemoryStream())
{
    using (var writer = new new StreamWriter(ms))
    {
       // ...
    }
    request.Content = ms.ToArray();
}
```

### Other Information

If `IRequest.Content` was a `ArraySegment<byte>`, this:

```csharp
request.Content = ms.ToArray();
```

coulde be this:

```csharp
request.Content = new ArraySegment<byte>(ms.GetBuffer(), 0, (int)ms.Length);
```

which is one less `byte[]` allocation.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

AWSSDK.KeyManagementService 3.7.300.52

### Targeted .NET Platform

.NET 8

### Operating System and version

Windows and Linux

**Comment by bhoradc** [comment]
Hello @paulomorgado, 

Thank you for taking the time to share your performance optimization findings! Since you are open to contributing a PR, please feel free to do so. Team will be happy to review it. 


Regards, 
Chaitanya

**Comment by paulomorgado** [comment]
> ```cs
> StringWriter
> ```

Just under `sdk` and not counting `sdk/test`, it's about 9500 files.

Is the code base covered in tests for all that?

**Comment by dscpinheiro** [comment]
Your PR has been merged and will be included in the next preview release of the SDK.

Thanks again for the contribution!
