### ISSUE TITLE
ExcessCapacityTerminationPolicy default value bug - Titlecase required

### ISSUE THREAD

**Issue by cschlemmer** [aws/aws-sdk-net#342]
When trying to use the following value;
ExcessCapacityTerminationPolicy.Default.Value the result is "default" but needs to be "Default" for the Spot Fleet Request to successfully submit without an error. I can manually override this value when stepping through the code to correct this.

**Comment by steveataws** [comment]
This value, and casing, is coming out of the service team's own model from which the SDK's generate. I've raised an internal ticket with the service team to either relax the casing check on their side, or supply us with a corrected model. Once they process the ticket we'll update this issue.

Thanks for reporting it.

**Comment by PavelSafronov** [comment]
This has been addressed by the service. Thank you for reporting the issue.
