### ISSUE TITLE
KeyManagementService - GenerateDataKeyRequest - Security Token Invalid

### ISSUE THREAD

**Issue by ggkilmon** [aws/aws-sdk-net#343]
I am attempting to make a GenerateDataKey request to KMS, but I receive the following exception: The security token included in the request is invalid

When I look at my request object, the Amazon.Runtime.Internal.IAmazonWebServiceRequest.UseSigV4 property is set to false.  I believe this value should be set to true for all KMS requests, however I don't have access to do so manually without creating my own request object.

Sample code:
```c#

            AmazonKeyManagementServiceConfig config = new AmazonKeyManagementServiceConfig()
            {
                RegionEndpoint = RegionEndpoint.USEast1,
            };

            AmazonKeyManagementServiceClient client = new AmazonKeyManagementServiceClient(config);

            GenerateDataKeyRequest request = new GenerateDataKeyRequest()
            {
                KeyId = "alias/TestKey",
            };
            
            GenerateDataKeyResponse response = client.GenerateDataKey(request);
            
            Assert.AreEqual(HttpStatusCode.OK, response.HttpStatusCode);

```

**Comment by ggkilmon** [comment]
i should have included the version, sorry...

AWSSDK - AWS Key Management Service 3.1.1.3 from NuGet
AWSSDK - Core Runtime 3.1.4.3 from NuGet

**Comment by jimfl** [comment]
How are you supplying credentials to your program? Are you able to make calls with other clients?

**Comment by ggkilmon** [comment]
credentials are supplied via AWS credentials store
I added them via Windows PowerShell for AWS

I will attempt to access another service, like S3, and report back

**Comment by jimfl** [comment]
Do you have the profile configured in your app.config?

    <configuration>
      <appSettings>
        <add key="AWSProfileName" value="development"/>
      </appSettings>
    </configuration>

**Comment by ggkilmon** [comment]
yes
```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <appSettings>
    <add key="AWSProfileName" value="default" />
  </appSettings>
</configuration>
```

**Comment by ggkilmon** [comment]
when attempting to connect to S3, I was given the error that it didn't know my access key

It turns out my access key was set to inactive; once it was set to active, I was able to list my buckets from S3

I then attempted my first KMS test, and I was able to get a successful response.

Thanks for your help
