### ISSUE TITLE
Support conditional put in TransferUtility (S3)

### ISSUE THREAD

**Issue by leidegre** [aws/aws-sdk-net#3451]
### Describe the feature

There's currently no way to include a `If-None-Match: *` or similar condition with the transfer operation. It's not that S3 doesn't support this but it's not possible to pass this information to the CompleteMultipartUpload operation.

### Use Case

I use `If-None-Match: *` specifically to prevent overwriting stuff already in storage.

### Proposed Solution

Simply make it possible to add `If-None-Match: *` to `TransferUtilityUploadRequest`. Currently there's no way to influence the CompleteMultipartUpload operation via the TransferUtilityUploadRequest.

### Other Information

I've snooped around the code and the only way I managed to do this of the V3 code, is this.

```cs
class AmazonX3CompleteMultipartUploadRequestMarshaller : IMarshaller<IRequest, CompleteMultipartUploadRequest>, IMarshaller<IRequest, AmazonWebServiceRequest>
{
	public IRequest Marshall(AmazonWebServiceRequest input)
	{
		return Marshall((CompleteMultipartUploadRequest)input);
	}

	public IRequest Marshall(CompleteMultipartUploadRequest input)
	{
		var req = CompleteMultipartUploadRequestMarshaller.Instance.Marshall(input);
		req.Headers["If-None-Match"] = "*";
		return req;
	}
}

class AmazonX3Client : AmazonS3Client
{
	public AmazonX3CompleteMultipartUploadRequestMarshaller CompleteMultipartUploadRequestMarshaller { get; } = new();

	public AmazonX3Client(AWSCredentials credentials, AmazonS3Config config) : base(credentials, config) { }

	public override Task<CompleteMultipartUploadResponse> CompleteMultipartUploadAsync(CompleteMultipartUploadRequest request, CancellationToken cancellationToken = default)
	{
		InvokeOptions options = new InvokeOptions();
		options.RequestMarshaller = CompleteMultipartUploadRequestMarshaller;
		options.ResponseUnmarshaller = CompleteMultipartUploadResponseUnmarshaller.Instance;
		return InvokeAsync<CompleteMultipartUploadResponse>(request, options, cancellationToken);
	}
}
```

I would prefer to use the TransferUtility but I need to be able to make it a conditional PUT that won't overwrite what is already in storage.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

AWSSDK.S3 3.7.401.2

### Targeted .NET Platform

.NET 8

### Operating System and version

Windows 11

**Comment by leidegre** [comment]
On second though, my solution to this problem will work with the TransferUtility, there should be no need for this because I can pass my AmazonX3Client to the TransferUtility instance and it should do the right thing.

**Comment by ashishdhingra** [comment]
Thanks for self resolution.
