### ISSUE TITLE
AWS Toolkit - DynamoDB Doesn't clear Scan conditions on creation of new table

### ISSUE THREAD

**Issue by damiangreen** [aws/aws-sdk-net#346]
Steps to reproduce. 
1. Select an existing table
2. Create a new table.
3. Select a dropdown.

In this example, I previously had a 'Users' table open. then I created a 'User' table. Currently it has no attributes. but lots are showing
![aws-toolkit-bug](https://cloud.githubusercontent.com/assets/1592820/15175265/66f748a2-175d-11e6-8191-97c7c34c1835.PNG)

then pressing scan shows a popup '
Error executing query: Object reference not set to an instance of an object.'

**Comment by steveataws** [comment]
Having trouble reproducing this issue. Can you clarify what you meant by 'select an existing table'.

I tried opening an existing table and adding a scan condition -- I only see the attributes in that table. Then I created a new table from the Explorer and opened a view onto it. When I add a scan condition, I only see the single hash key attribute I specified for the table during creation.

**Comment by damiangreen** [comment]
Could you try creating a table called 'Users' and then create one called 'User'.
There seems to be funky behaviour  with table names called 'User'.

I just managed to recreate this issue by opening a table called HighwaysEnglandTripInformationSystem.Users, then creating one called HighwaysEnglandTripInformationSystem.User.
i.e. singular.

**Comment by steveataws** [comment]
Thanks, I'll try that.

**Comment by sstevenkang** [comment]
@damiangreen , we still couldn't repro this problem. We are going to close this due to inactivity, feel free to reopen this issue if you are still experiencing the problem..
