### ISSUE TITLE
AWS Toolkit. VS themes cause issue with new DynamoDB Table dialog

### ISSUE THREAD

**Issue by damiangreen** [aws/aws-sdk-net#347]
Here I'm using Dark with light theme.
![screenshot 2016-05-11 09 58 04](https://cloud.githubusercontent.com/assets/1592820/15175618/18ab3990-175f-11e6-9625-d8e757d4109d.png)

**Comment by steveataws** [comment]
What version of Visual Studio and the toolkit are you using? From the title bar buttons it looks like this is a Windows 7 OS?

I can't repro the issue on my Windows 10/VS2015 install, but a colleague just demo'd some similar wierdness on his Win7 system with this wizard so I'll try and track it down. Thanks for reporting.

**Comment by damiangreen** [comment]
It's win 7. VS 2015. if you open that image in an image editor and up the contrast you can see the font is there, jsut slightly differnet to the background colour

**Comment by normj** [comment]
New versions of the toolkit use the native theming API in Visual Studio to fix this problem.
