### ISSUE TITLE
AWS Toolkit - DynamoDB - UX Improvement - set reasonable upper bound on default column width

### ISSUE THREAD

**Issue by damiangreen** [aws/aws-sdk-net#348]
If one attribute value is rather long then  you need to scroll right a long way and resize the column  so you can see the columns to the right of it. It would be good if instead of the column width defaulting to the maximum attribute value. It would be limited to something more sensible.  e.g 300px

![column width](https://cloud.githubusercontent.com/assets/1592820/15242436/12f367ee-18ee-11e6-8fae-30f2012ff2c8.png)

**Comment by vellozzi** [comment]
This feature request has been added to our backlog.
