### ISSUE TITLE
Consider adding TryAddDefaultAWSOptions to AWSSDK.Extensions.NETCore.Setup

### ISSUE THREAD

**Issue by paulomorgado** [aws/aws-sdk-net#3481]
### Describe the feature

`Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.AddDefaultAWSOptions` always registers `AWSOptions` even if there was a previous registration.

There should be a `TryAddDefaultAWSOptions` to register only if it hasn't been registered before, like `TryAddAWSService`.

### Use Case

```csharp
configuration.TryAddDefaultAWSOptions();
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

AWSSDK.Extensions.NETCore.Setup version 3.7.301

### Targeted .NET Platform

.NET 8

### Operating System and version

Window, Linux, etc.

**Comment by ashishdhingra** [comment]
@paulomorgado Thanks for submitting feature request. Feel free to contribute PR that could be implemented by the team.

**Comment by paulomorgado** [comment]
> @paulomorgado Thanks for submitting feature request. Feel free to contribute PR that could be implemented by the team.

Done: #3484

**Comment by dscpinheiro** [comment]
Your PR has been merged, and will be included in the next preview release of the SDK.

Thanks again for the contribution!
