### ISSUE TITLE
IVS mutator type does not match backing field type

### ISSUE THREAD

**Issue by gabr0236** [aws/aws-sdk-net#3487]
### Describe the bug

Example:
```
public partial class StreamSessionSummary
{
    private DateTime? _endTime;
...
    public DateTime EndTime
    {
         get { return this._endTime.GetValueOrDefault(); }
         set { this._endTime = value; }
    }
}
```

As the mutator is non-nullable i am not able to assign `null` to `_endTime` and thus not able to mock the different possible responses from the API.

This seems to be a general issue, stemming from how the code is being auto generated. 

Or maybe value types are always marked as nullable? In that case i would expect to be able to define the property as nullable in `generator/ServiceModels/ivs/ivs-2020-07-14.normal.json`

I wanted to look at a fix myself but its not quite clear where/how the autogeneration happens.

### Expected Behavior

I would expect the mutator type to match the backing field type to be able to simulate diffrent possible responses from the IVS API.

### AWS .NET SDK and/or Package version used

AWSSDK.IVS 3.7.400.23

### Targeted .NET Platform

.net 8

### Operating System and version

MacOS Sononoma 14.0

**Comment by dscpinheiro** [comment]
This behavior is expected in the current version of the .NET SDK (i.e. 3.7.x), but we fixed this in the next major version (V4) which is currently in preview and can be tracked in https://github.com/aws/aws-sdk-net/issues/3362; Here's the relevant section of the [announcement blog post](https://aws.amazon.com/blogs/developer/preview-1-of-aws-sdk-for-net-v4/):
> V4 changes properties on classes used for requests and responses that used value types like int, bool, and DateTime to use the nullable version, essentially changing the type from bool to bool?. This addresses a long standing issue many users had with the SDK in that they could not tell, for example, if a boolean property is false because the service returned false, or if the property is false because that is the default value for bool types.

For example, here's how the `EndTime` property is defined in V4 (which is available in https://www.nuget.org/packages/AWSSDK.IVS/4.0.0-preview.2): https://github.com/aws/aws-sdk-net/blob/40aeb0ea7cfe64cc269a5d25735bcf130b17db74/sdk/src/Services/IVS/Generated/Model/StreamSessionSummary.cs#L42-L53

**Comment by ashishdhingra** [comment]
@dscpinheiro Thanks for the response.
