### ISSUE TITLE
NullReferenceException in MetricsHandler when ResponseMetadata is null

### ISSUE THREAD

**Issue by hwoodiwiss** [aws/aws-sdk-net#3493]
### Describe the bug

I'll preface this with the fact that I don't expect that this is likely/can happen in usual operation of the SDK against an actual AWS service.

While testing using an HTTP client interception library, in recent versions of AWSSDK.SimpleNotificationService, if the ResponseMetadata is not set in the response, a NullReferenceException is thrown in [MetricsHandler](https://github.com/aws/aws-sdk-net/blob/main/sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/MetricsHandler.cs#L52).

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

I would expect the metrics handler to handle the null case for ResponseMetadata more defensively, and then either throw a descriptive exception, or silently continue.

### Current Behavior

Throws NullReferenceException dereferencing null ResponseMetadata when trying to set RequestId span attribute

### Reproduction Steps

I'll have to get back to you with this later.

### AWS .NET SDK and/or Package version used

AWSSDK.SimpleNotificationService 3.7.400.26 (though likely applies to several more as this will be based on the resolved AWSSDK.Core library version)

### Targeted .NET Platform

.NET 8

### Operating System and version

Windows 10, Ubuntu (CI Runner)

**Comment by muhammad-othman** [comment]
Hi @hwoodiwiss
Thank you for raising this issue! The `ResponseMetadata` is a part of the response that’s automatically initialized and included in AWS SDK operations. It’s designed for internal use, and we didn’t anticipate that other libraries would handle it differently or modify its behavior.

We’ll definitely look into this further, but I’m curious what interception library are you using?

**Comment by hwoodiwiss** [comment]
Hey @muhammad-othman, thanks for responding so quickly, I'm using an internal library built on top of https://github.com/justeattakeaway/httpclient-interception. 

Yeah that makes sense, I appreciate it's not a common use-case, I just thought it worth raising, in case we can blunt a slightly sharp edge.

**Comment by ashishdhingra** [comment]
Needs review with the team.

**Comment by muhammad-othman** [comment]
@ashishdhingra I've create #3496 to fix it since it was a very small change.
