### ISSUE TITLE
InternalSDKUtils trim warning

### ISSUE THREAD

**Issue by tmitchel2** [aws/aws-sdk-net#3497]
### Describe the bug

Usage of AWSSDK.Core 3.7.400.22 with native aot causes the following trimmer warning.

ILC : Trim analysis warning IL2075: Amazon.Util.Internal.InternalSDKUtils.ApplyValues(Object,IDictionary`2<String,Object>): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicProperties' in call to 'System.Type.GetProperty(String)'. The return value of method 'System.Object.GetType()' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

No trim warnings.

### Current Behavior

Trim warnings raised.

### Reproduction Steps

Reference AWSSDK.Core and try to publish with PublishAot true...  Various parts of my csproj are below.

```
  <PropertyGroup>
    <TrimmerSingleWarn>false</TrimmerSingleWarn> 
  </PropertyGroup>

  <ItemGroup> 
    <PackageReference Include="Amazon.Lambda.RuntimeSupport" Version="1.11.0" />
    <PackageReference Include="Amazon.Lambda.Core" Version="2.3.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.4.3" />
    <PackageReference Include="Amazon.Lambda.APIGatewayEvents" Version="2.7.1" />
  </ItemGroup>

  <ItemGroup>
    <!-- <TrimmerRootAssembly Include="AWSSDK.Core" /> -->
    <TrimmerRootAssembly Include="Amazon.Lambda.APIGatewayEvents" />
    <TrimmerRootAssembly Include="bootstrap" />
  </ItemGroup>
```

### Additional Information/Context

Also, setting the AWSSDK.Core reference as a trimmer root assembly results in even more warnings.

### AWS .NET SDK and/or Package version used

AWSSDK.Core 3.7.400.22

### Targeted .NET Platform

.NET 8

### Operating System and version

OSX Arm64

**Comment by bhoradc** [comment]
Hi @tmitchel2, 

Thank you for bringing this issue to our attention. Our team will work towards implementing a suitable fix.

Regards, 
Chaitanya
