### ISSUE TITLE
NewerConcurrentVersions in LifecycleRuleNoncurrentVersionExpiration is ignored

### ISSUE THREAD

**Issue by BreakingBread0** [aws/aws-sdk-net#3500]
### Describe the bug

When setting a lifecycle configuration with noncurrent version expiry, NewerConcurrentVersions seems to not be serialized into the request (see https://github.com/aws/aws-sdk-net/blob/main/sdk/src/Services/S3/Custom/Model/Internal/MarshallTransformations/PutLifecycleConfigurationRequestMarshaller.cs#L124)

This doesnt appear to be right, especially since there is no documentation describing this behaviour. Having a quick look around, the PutBucketLifecycleConfigurationRequestMarshaller for S3Control seems to do serialize it (https://github.com/aws/aws-sdk-net/blob/main/sdk/src/Services/S3Control/Generated/Model/Internal/MarshallTransformations/PutBucketLifecycleConfigurationRequestMarshaller.cs#L172)

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

NewerNoncurrentVersions being written into the request.

### Current Behavior

The NewerNoncurrentVersions is ignored during serialization.

### Reproduction Steps

This is my current code:
```csharp
PutLifecycleConfigurationRequest request = new()
{
    BucketName = bucketName,
    Configuration = new()
    {
        Rules = new()
        {
            new Amazon.S3.Model.LifecycleRule() {
                NoncurrentVersionExpiration = new LifecycleRuleNoncurrentVersionExpiration()
                {
                    NewerNoncurrentVersions = keepItems,
                    //NoncurrentDays = keepDays,
                },
                AbortIncompleteMultipartUpload = new LifecycleRuleAbortIncompleteMultipartUpload()
                {
                    DaysAfterInitiation = 7
                },
                Expiration = new LifecycleRuleExpiration()
                {
                    //Am object which only has deletion markers
                    ExpiredObjectDeleteMarker = true,
                },
                Id = lifecycleConfigName,
                Status = LifecycleRuleStatus.Enabled,
                Filter = new()
            }
        }
    }
};
```

### AWS .NET SDK and/or Package version used

AWSSDK.S3 3.7.404.1 (latest at time of writing)

### Targeted .NET Platform

.NET 8

### Operating System and version

Windows 10

**Comment by bhoradc** [comment]
Hi @BreakingBread0, 

Thank you for reporting the issue. We acknowledge the property `NewerNoncurrentVersions` is not sent on the request object. Our team will further investigate and work on the fix for it. 

Regards, 
Chaitanya

**Comment by muhammad-othman** [comment]
Hello @BreakingBread0,
`PutLifecycleConfigurationRequest.NewerNoncurrentVersions` is serialized and sent to S3 as part of [v3.7.404.7](https://www.nuget.org/packages/AWSSDK.S3/3.7.404.7).
Feel free to reach out if you faced any other issues.
