### ISSUE TITLE
[feat] Missing ctor for AmazonSimpleEmailServiceV2Client

### ISSUE THREAD

**Issue by lonix1** [aws/aws-sdk-net#3519]
### Describe the feature

Add a constructor to `AmazonSimpleEmailServiceV2Client` which takes:
- credentials
- region
- config

### Use Case

That class has numerous ctors but none allow setting all the above, and the properties are readonly so cannot be set after instantiation.

(I know the SDK will try default files and env vars, but we are not using those; we use a secrets management system, so must specify the values programmatically.)

### Proposed Solution

Either one of these would be fine:
```cs
public AmazonSimpleEmailServiceV2Client(
  AWSCredentials credentials, 
  RegionEndpoint region, 
  AmazonSimpleEmailServiceV2Config clientConfig)
```
or
```cs
public AmazonSimpleEmailServiceV2Client(
  string awsAccessKeyId, 
  string awsSecretAccessKey, 
  RegionEndpoint region, 
  AmazonSimpleEmailServiceV2Config clientConfig)
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

AWSSDK.SimpleEmailV2
3.7.403.1

### Targeted .NET Platform

.NET 8

### Operating System and version

linux

**Comment by dscpinheiro** [comment]
You can set the region endpoint in the `AmazonSimpleEmailServiceV2Config` class, like this:
```
// Retrieved from your secrets management system.
var accessKey = "...";
var secretKey = "...";

var ses = new AmazonSimpleEmailServiceV2Client(accessKey, secretKey, new AmazonSimpleEmailServiceV2Config
{
    RegionEndpoint = RegionEndpoint.USWest2
});
```

Would that be an option for you?
