### ISSUE TITLE
SendEmailAsync throws incorrect exception

### ISSUE THREAD

**Issue by lonix1** [aws/aws-sdk-net#3526]
### Describe the bug

SESv2: [SendEmailAsync](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/SimpleEmailV2/MSimpleEmailServiceV2SendEmailAsyncSendEmailRequestCancellationToken.html) is supposed to throw [MailFromDomainNotVerifiedException](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/SimpleEmailV2/TMailFromDomainNotVerifiedException.html) for a mail sent from an unverified domain.

However it actually throws a [MessageRejectedException](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/SimpleEmailV2/TMessageRejectedException.html):

```
Amazon.SimpleEmailV2.Model.MessageRejectedException: Email address is not verified. The following identities failed the check in region MY-REGION: Foo Bar <noreply@example.com>
``` 

Since we use the exceptions to determine what failed, our code responds to failure incorrectly. This is obviously a problem.

I hope the other exceptions are working as intended.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

To work as documented.

### Current Behavior

Throws incorrect exception.

### Reproduction Steps

Send a mail via `SendEmailAsync` using an unverified domain.

### AWS .NET SDK and/or Package version used

AWSSDK.SimpleEmailV2 3.7.403.1

### Targeted .NET Platform

.NET 8

### Operating System and version

linux

**Comment by bhoradc** [comment]
Hello @lonix1, 

Thank you for reporting the issue. I am able to reproduce this scenario using below minimal code sample. 

`AWSSDK.SimpleEmailV2 - 3.7.403.4`

```c#
static async Task Main(string[] args)
{
    AmazonSimpleEmailServiceV2Client _sesClient = new AmazonSimpleEmailServiceV2Client();
    var request = new SendEmailRequest
    {
        FromEmailAddress = "emailadd1@domain1.com",
        Destination = new Destination { ToAddresses = new List<string> { "emailadd2@domain2.com" } },
        Content = new EmailContent
        {
            Simple = new Message
            {
                Subject = new Content { Data = "This is Test email" },
                Body = new Body
                {
                    Html = new Content { Data = "This is HTML Content" },
                    Text = new Content { Data = "This is Text Content" }
                }
            }
        },
    };
    try
    {
        var response = await _sesClient.SendEmailAsync(request);
        Console.WriteLine(response.MessageId);
    }
    catch (Exception ex)
    {
        Console.WriteLine(ex);
    }
}
```

Exception:
```.log
Amazon.SimpleEmailV2.Model.MessageRejectedException: Email address is not verified. The following identities failed the check in region US-EAST-1: emailadd2@domain2.com
 ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
```

I will review it with the team to further investigate the issue. 

Regards, 
Chaitanya

**Comment by ashishdhingra** [comment]
Per SESv2 > [SendEmail](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_SendEmail.html), this service API throws below errors:
```
AccountSuspendedException
The message can't be sent because the account's ability to send email has been permanently restricted.

HTTP Status Code: 400

BadRequestException
The input you provided is invalid.

HTTP Status Code: 400

LimitExceededException
There are too many instances of the specified resource type.

HTTP Status Code: 400

MailFromDomainNotVerifiedException
The message can't be sent because the sending domain isn't verified.

HTTP Status Code: 400

MessageRejected
The message can't be sent because it contains invalid content.

HTTP Status Code: 400

NotFoundException
The resource you attempted to access doesn't exist.

HTTP Status Code: 404

SendingPausedException
The message can't be sent because the account's ability to send email is currently paused.

HTTP Status Code: 400

TooManyRequestsException
Too many requests have been made to the operation.

HTTP Status Code: 429
```

[SimpleEmailV2](https://github.com/aws/aws-sdk-net/tree/main/sdk/src/Services/SimpleEmailV2) package in AWS .NET SDK is automatically generated from the service API models. Perhaps, we need to open ticket with SES service team to advise further.

Thanks,
Ashish

**Comment by ashishdhingra** [comment]
@lonix1 Good morning. Thanks for reporting the issue. Even though I have opened an issue with service team, I would request to verify some information.

Per [SendEmail](https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_SendEmail.html), **MailFromDomainNotVerifiedException** is thrown when `The message can't be sent because the sending domain isn't verified.`. Sending domain is email domain of sender, not destination.

In our reproduction code below:
```C#
static async Task Main(string[] args)
{
    AmazonSimpleEmailServiceV2Client _sesClient = new AmazonSimpleEmailServiceV2Client();
    var request = new SendEmailRequest
    {
        FromEmailAddress = "emailadd1@domain1.com",
        Destination = new Destination { ToAddresses = new List<string> { "emailadd2@domain2.com" } },
        Content = new EmailContent
        {
            Simple = new Message
            {
                Subject = new Content { Data = "This is Test email" },
                Body = new Body
                {
                    Html = new Content { Data = "This is HTML Content" },
                    Text = new Content { Data = "This is Text Content" }
                }
            }
        },
    };
    try
    {
        var response = await _sesClient.SendEmailAsync(request);
        Console.WriteLine(response.MessageId);
    }
    catch (Exception ex)
    {
        Console.WriteLine(ex);
    }
}
```
it gave exception:
```
Amazon.SimpleEmailV2.Model.MessageRejectedException: Email address is not verified. The following identities failed the check in region US-EAST-1: emailadd2@domain2.com
 ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
```
The SES service is complaining about the destination email address `emailadd2@domain2.com`, not the sender domain.

Please confirm the following:
- Share self-contained reproducible code, if different from what we used to reproduce your scenario.
- Could you please check what happens when you specify valid destination domain and/or email address?
- Do you have the sample use case where your sender domain in SES is not verified?

Thanks,
Ashish

**Comment by ashishdhingra** [comment]
@lonix1 Received below communication from SES service team:
___
This error is supposed to be thrown when the custom MAIL FROM domain on the identity is not verified. Custom MAIL FROM domain verification is different than domain verification: https://docs.aws.amazon.com/ses/latest/dg/mail-from.html

The docs for V1 mentions this: https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/SimpleEmail/TMailFromDomainNotVerifiedException.html

The response of "Message rejected: Email address not verified" is therefore expected when they are using an unverified identity to send emails. If cx is using account in sandbox mode, both sender and recipient needs to be verified. If they are in production, they need to verify the sender domain/email only.

Thanks,
Ashish
