### ISSUE TITLE
Amazon S3 Bucket Log Reader/Analyzer in .NET.

### ISSUE THREAD

**Issue by Mohammedgadi123** [aws/aws-sdk-net#354]
Is there any sample code to read the logs generated by CloudFront on manipulating objects of
configured S3 Bucket.

**Comment by PavelSafronov** [comment]
There is no sample code that I am aware of. You may want to ask this question on the [CloudFront forum](https://forums.aws.amazon.com/forum.jspa?forumID=46), it's likely the users there can point you in the right direction.
