### ISSUE TITLE
Bug (AWS Explorer DynamoDB ) Deleting Global Secondary Index before saving gives error dialog

### ISSUE THREAD

**Issue by damiangreen** [aws/aws-sdk-net#355]
Steps to recreate:
1) Click on Table Property.
2) Click Add icon next to Global Secondary Index.
3) don't populate the index name, hash key etc.
4) Click delete icon (i.e. i didn't want to create it after all ) 
 An error dialog appears showing "Only one index can be created or deleted at a time."
This is a bit confusing as I was trying to delete one index (that hadnt yet been created)

The only way to remove this index is to cancel out of the Table Properties dialog entirely
![dynamodb-bug](https://cloud.githubusercontent.com/assets/1592820/15359277/78b2c1a4-1d00-11e6-89fb-78d2b82cbdf2.png)

**Comment by steveataws** [comment]
Fix released in toolkit version 1.6.9.20, available at http://sdk-for-net.amazonwebservices.com/latest/AWSToolsAndSDKForNet.msi. 

I think there are some usability issues remaining with this dialog, for example showing that an index deletion is pending transmission to the service at the time 'add' is clicked -- currently the dialog will show the same error as it has a pending deletion, disallowing addition but you can't see the deleted item waiting to be committed. I think it would also be useful to have a Refresh button on the grid for scenarios where multiple updates need to be made (one at a time, per service limitation). I've added an item to our backlog to try and address this in a future release.

Thanks for reporting the issue.
