### ISSUE TITLE
Getting error regarding signing request

### ISSUE THREAD

**Issue by RobQuatela** [aws/aws-sdk-net#3558]
### Describe the bug

When using the SDK I am receiving this error below. I am not sure if this has something to do with using version 4 for signing. All I did was update the nuget packages to 4.x

The request signature we calculated does not match the signature you provided. Check your key and signing method.

### Regression Issue

- [X] Select this option if this issue appears to be a regression.

### Expected Behavior

I expected to make a PutObject request using the SDK

### Current Behavior

I am receiving the error below on the same code before I updated the package

The request signature we calculated does not match the signature you provided. Check your key and signing method.

### Reproduction Steps

`using var client = new AmazonS3Client("ACCESS_KEY", "SECRET_KEY",RegionEndpoint.USEast1);
            try
            {
                var bytes = Convert.FromBase64String(base64Content);
                using var stream = new MemoryStream(bytes);
                var putRequest = new PutObjectRequest()
                {
                    BucketName = "cdn.test.com/vcards",
                    Key = $"{fileName}.vcf",
                    InputStream = stream,
                    ContentType = "text/x-vcard"
                };

                var response = await client.PutObjectAsync(putRequest);
                return $"https://cdn.test.com/vcards/{fileName}.vcf";
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }`

### AWS .NET SDK and/or Package version used

AWSSDK 4.0.0-preview.4

### Targeted .NET Platform

.NET 7

### Operating System and version

MacOS & Docker

**Comment by dscpinheiro** [comment]
No, this is not a regression in V4. Newer versions of the S3 package (after `3.7.100`) do not allow the bucket name to contain the key prefix (i.e the slash character).

This comment has more details: https://github.com/aws/aws-sdk-net/issues/2622#issuecomment-1581208688

For your code, I don't know what `cdn.test.com` is but I assume changing the `PutRequest` to the following should work:
```csharp
var putRequest = new PutObjectRequest
{
    BucketName = "cdn.test.com",
    Key = $"vcards/{fileName}.vcf",
    InputStream = stream,
    ContentType = "text/x-vcard"
};
```

**Comment by RobQuatela** [comment]
That was it! Thank you again for this!!
