### ISSUE TITLE
Amazon.S3.AmazonS3Exception: Error making request with Error Code BadRequest and Http Status Code BadRequest. No further error information was returned by the service.

### ISSUE THREAD

**Issue by danchykon** [aws/aws-sdk-net#3573]
### Describe the bug

when i upload file from local environment everything is ok, but throws an exception when i try to upload a file from an application that runs in a private kubernetes cluster

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

successful upload response or detailed error response

### Current Behavior

returns BadRequest error without further information

### Reproduction Steps

impossible to reproduce because error happens in private kubernetes cluster

### Additional Information/Context

![image](https://github.com/user-attachments/assets/60c42daa-63f8-447d-9c47-73136fa88e55)
![image](https://github.com/user-attachments/assets/bd9ed490-0c65-407a-bddc-36fa28351ccb)
![image](https://github.com/user-attachments/assets/2550d200-5951-4928-82bf-781f0ced31e4)

### AWS .NET SDK and/or Package version used

AWSSDK.Extensions.NETCore.Setup 3.7.301
AWSSDK.S3 3.7.410.1
AWSSDK.SSO 3.7.400.59
AWSSDK.SSOOIDC 3.7.400.59

### Targeted .NET Platform

.NET 8

### Operating System and version

docker image mcr.microsoft.com/dotnet/aspnet:8.0

**Comment by danchykon** [comment]
> Hi @danchykon,
> 
> Good morning. Thanks for opening the issue. Please share the minimal code solution to troubleshoot the issue. Also, is the endpoint and bucket name same as your local environment as in Kubernetes? I notice that the credentials were resolved from environment variables. Could you check if the credentials configured are correct in your private Kubernetes cluster?
> 
> Thanks, Ashish

Hi @ashishdhingra 
- endpoint and bucket name is same as my local env as in kubernetes
- credentials are same as my local env as in kubernetes and of course configured correctly
- 
![image](https://github.com/user-attachments/assets/c4413647-b6ba-4403-8749-bd0ca31e2d2e)
![image](https://github.com/user-attachments/assets/e0aadc9b-1107-4708-a2d3-2178046dd71f)

**Comment by ashishdhingra** [comment]
@danchykon Thanks for your response. The code doesn't provide much information to troubleshoot the issue. Please enable verbose logging using code below and share the verbose logs (as text):
```C#
AWSConfigs.LoggingConfig.LogTo = LoggingOptions.Console;
AWSConfigs.LoggingConfig.LogMetricsFormat = LogMetricsFormatOption.JSON;
AWSConfigs.LoggingConfig.LogResponses = ResponseLoggingOption.Always;
AWSConfigs.LoggingConfig.LogMetrics = true;
```

This would at least provide the response received from service.

Thanks,
Ashish
