### ISSUE TITLE
Undeleted merge datasets accumulating

### ISSUE THREAD

**Issue by pfleeter** [aws/aws-sdk-net#360]
When I go into the identity browser on the AWS console, I see that I have 7 merge data sets (or at least data sets named <datasetname>.<merged identity>.  However, when I use the sqlite3 client on my Mac to look in my local storage, I see only one.  When I sync datasets in the Unity editor, only the one that is in my local storage is handed to the merge callback.

How can I get the other datasets into my local storage, so that they will trigger the merge callback?

**Comment by normj** [comment]
I believe this was fixed with PR https://github.com/aws/aws-sdk-net/pull/414
