### ISSUE TITLE
Memory leak when calling DynamoDbContext.LoadAsync method with cancellation token

### ISSUE THREAD

**Issue by Funbit** [aws/aws-sdk-net#361]
I don't have a simple code sample (found the problem minutes ago), but it can be described pretty easily. 
I have a method that looks like this:

```
public async Task<ProcessedMailMessage> GetAsync(string messageId)
{
    using (var context = new DynamoDBContext(_client, _dbConfig))
    {
        var loadedEntity = await context
            .LoadAsync<ProcessedMailMessage>(messageId, _cancellationToken)
            .ConfigureAwait(false);
        return loadedEntity;
    }
}
```

If `_cancellationToken` is not null and lives much longer than the `DynamoDbContext `(i.e. global cancellation token) - then `LoadAsync `creates a deserialized `ProcessedMailMessages `object and ties it to the token, producing memory leak. If I remove the `_cancellationToken` parameter from the `LoadAsync `call - leak is gone.

I have peeked at the source code via R# and believe that the root of the problem is that `LoadAsync `uses `AsyncRunner.Run` method which calls `cancellationToken.Register` method, but does not dispose `CancellationTokenRegistration `object returned by it (it is `IDisposable`). 

I'm using AWSSDK.DynamoDBv2.dll v3.1.1.1, but latest version leads to the same problem.

I will try to create a separate simple project that reproduces the problem, but unfortunately I will be able to do that only on Sunday. 

Regards

**Comment by Funbit** [comment]
By the way, here is the detailed description of the problem:
http://stackoverflow.com/questions/14627226/why-is-my-async-await-with-cancellationtokensource-leaking-memory

For now to avoid the problem one should avoid using cancellation token in LoadAsync method.

Looking forward to the fix.
Thank you.

**Comment by PavelSafronov** [comment]
SDK Core version 3.1.7 contains a fix for this bug.

**Comment by Funbit** [comment]
Thank you!
