### ISSUE TITLE
Does the Unity SDK work with Desktop platforms?

### ISSUE THREAD

**Issue by dfiverr** [aws/aws-sdk-net#364]
Does this Unity SDK run and work with Desktop platforms like Mac and PC? Please let me know, thank you.

**Comment by karthiksaligrama** [comment]
yes android, iOS and standalone platforms are supported at the moment.

**Comment by dfiverr** [comment]
Another question, why is the User Information Store in Amazon Cognito limited to just 20 megabytes? What if my users want to store 100 megabytes worth of images? Also, should it be used to store user files or is it better to just put small details about the user there? Thank you

**Comment by PavelSafronov** [comment]
If you need to store more data, this should go into a different cloud resource, such as [Amazon S3](https://aws.amazon.com/s3/).

**Comment by dfiverr** [comment]
Thanks Pavel, does Amazon S3 provide the same file syncing functionality as Cognito?

**Comment by PavelSafronov** [comment]
The S3 module of the .NET SDK does not provide syncing functionality like Cognito. In short, it is a simple upload and download model. You can take a look at [this section of the S3 developer guide](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingTheMPDotNetAPI.html) for some information about how S3 can be used from the .NET SDK.

**Comment by karthiksaligrama** [comment]
Closing this issue assuming fixed.
