### ISSUE TITLE
NullReferenceException when using LoadAsync in DynamoDB with C#

### ISSUE THREAD

**Issue by rmurdough** [aws/aws-sdk-net#365]
I am using the DynamoDBV2 library from NuGet - version 3.1.4.1

I use LoadAsync method from a DynamoDBContext context as follows: 

```
using (DynamoDBContext context = new DynamoDBContext(client, new DynamoDBContextConfig { ConsistentRead = true, SkipVersionCheck = true }))
{
     ret = context.LoadAsync<T>(id);
}
```

With this call I get the following exception and cannot figure out if this is a bug in the library or if I am calling it wrong.

System.NullReferenceException: Object reference not set to an instance of an object.&#xD;&#xA;   at Amazon.DynamoDBv2.DocumentModel.Table.DescribeTable(String tableName) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DocumentModel\Table.cs:line 302&#xD;&#xA;   at Amazon.Runtime.Internal.Util.Cache`2.GetValueHelper(TKey key, Boolean&amp; isStaleItem, Func`2 creator) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\Util\SdkCache.cs:line 424&#xD;&#xA;   at Amazon.DynamoDBv2.DocumentModel.Table.LoadTableInfo() in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DocumentModel\Table.cs:line 130&#xD;&#xA;   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.GetTable(String tableName, DynamoDBFlatConfig flatConfig) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DataModel\ContextInternal.cs:line 119&#xD;&#xA;   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.GetTargetTable(ItemStorageConfig storageConfig, DynamoDBFlatConfig flatConfig) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DataModel\ContextInternal.cs:line 109&#xD;&#xA;   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.LoadHelper[T](Key key, DynamoDBFlatConfig flatConfig, ItemStorageConfig storageConfig, Boolean isAsync) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DataModel\Context.cs:line 318&#xD;&#xA;   at Amazon.DynamoDBv2.DataModel.DynamoDBContext.&lt;&gt;c__DisplayClass106_0`1.&lt;LoadAsync&gt;b__0() in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DataModel\_async\Context.Async.cs:line 105&#xD;&#xA;   at Amazon.Runtime.Internal.AsyncRunner.&lt;&gt;c__DisplayClass1_0`1.&lt;Run&gt;b__1() in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\_async\AsyncRunner.cs:line 46&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at Amazon.Runtime.Internal.AsyncRunner.&lt;&gt;c__DisplayClass1_1`1.&lt;Run&gt;b__0() in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\_async\AsyncRunner.cs:line 71&#xD;&#xA;   at System.Threading.Tasks.Task`1.InnerInvoke()&#xD;&#xA;   at System.Threading.Tasks.Task.Execute()&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()&#xD;&#xA

**Comment by PavelSafronov** [comment]
From the code sample you have provided, it looks like you are making the LoadAsync call, immediately disposing of the context object, while the LoadAsync call is attempting to use the context object. If you hold off on disposing of the context until the result comes back, you should not get an exception. This can be done, for instance, by changing your code as follows:
```
item = await context.LoadAsync<T>(id);
```

Another option is to synchronously wait by retrieving the *.Result* property, as follows:
```
item = context.LoadAsync<T>(id).Result;
```

If you are writing a synchronous application, though, it's easier to simply call Load, instead of LoadAsync:
```
item = context.Load<T>(id);
```

**Comment by rmurdough** [comment]
Thanks, apologize for my error.
