### ISSUE TITLE
Support for cloning Beanstalk environment?

### ISSUE THREAD

**Issue by omerlh** [aws/aws-sdk-net#367]
Hey,
You can clone environment through the portal and through the cli, but I couldn't find a matching method in the client. Does this operation supported?
Thanks!

**Comment by steveataws** [comment]
Operations in the SDK map directly to api's exposed on the service endpoint. Clone (from the Elastic Beanstalk CLI) isn't exposed this way and we'd need to write some form of wrapper utility in the SDK to achieve this, once we determine what operations Clone does under the covers (which would of course need to wait to be resourced against other work).

If cloning from the SDK is something you feel we really should invest in then add a comment in the next day or so and I'll add a feature request to our backlog.

**Comment by omerlh** [comment]
Hey
This is something we consider using, but since it is not possible we found other ways to achieve that.
If this is something you could support in the future, it will be great.
Thanks!

**Comment by normj** [comment]
Closing for now, if/when the service exposes the Clone operation we will update the SDK to support it.
