### ISSUE TITLE
Register and log in with Unity SDK?

### ISSUE THREAD

**Issue by dfiverr** [aws/aws-sdk-net#369]
Hello,
I am working with the Cognito Unity SDK, and am a little bit lost as to how to provide registration for user log in for my users. Does Amazon Cognito have built in user registration, log in, and email verification? I do not want to use Facebook or Gmail for authenticating my users.
Please let me know.
Thank you

**Comment by PavelSafronov** [comment]
[Amazon Cognito Identity User Pools](http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools.html) is a Beta feature which allows you to "create and maintain a user directory and add sign-up and sign-in to your mobile app or web application", it may be what you're looking for.

**Comment by karthiksaligrama** [comment]
At this time though we are not supporting Cognito User Pools for Unity sdk. Adding this to feature requests.

**Comment by dfiverr** [comment]
So, right now only using external (like Facebook and GMail) Log In providers is supported? What about if I have my own PHP backend for log in and sign up?
Thank you

**Comment by karthiksaligrama** [comment]
You can use a developer authenticated flow. Read more about it @ http://docs.aws.amazon.com/cognito/latest/developerguide/developer-authenticated-identities.html

**Comment by dfiverr** [comment]
Thanks karthiksaligrama, the documentation is hard for me to follow but I will do my best to implement it.

**Comment by dfiverr** [comment]
To anyone that finds this thread and with this question, take a look at https://github.com/danilop/LambdAuth for handling the login and registration

**Comment by aschearer** [comment]
Any chance this feature can be re-opened? Without this feature Cognito is not nearly as interesting as I'm left implementing platform-specific identity. Going through the documentation in the link above or looking through the "Developer Authenticated Identities" documentation, these options are not simple. Once I have to maintain my own authentication service or tie together half a dozen AWS services, I might as well side step Cognito altogether and either build my own stack or rely on 1st party identity and sync services.

**Comment by PavelSafronov** [comment]
The issue is closed, but this feature request is on our roadmap. There are limited resources available for handling issues and by keeping the list of open issues lean we can respond in a timely manner.

**Comment by henning101** [comment]
@karthiksaligrama is there an update on Cognito User Pool authentication for Unity? I would love to have an AWS Amplify-like sign-up/login form in Unity. Alternatively is there a way to implement this by myself?
