### ISSUE TITLE
Non AWS/S3 endpoint being forced to use v4 Auth even when v2 is specified

### ISSUE THREAD

**Issue by ben-schumacher** [aws/aws-sdk-net#375]
Even after setting AmazonS3Client SignatureVersion="2", non-amazon S3 endpoints are being interpreted as real S3 endpoints and forced to use v4 authentication/signature on GET object.  This is because the regex is encompassing all endpoints that contain "s3".  For example, s3.mycompany.com returns true as a match in the regex expression.  This breaks the code when pointing the SDK to non-amazon backed that doesn't support v4 authentication/signatures.

Code forcing v4 Auth is in \src\services\s3\custom\internal\AmazonS3KmsHandler.cs
`internal static void EvaluateIfSigV4Required(IRequest request)
        {
            // Skip this for S3-compatible storage provider endpoints
            if ((request.OriginalRequest is S3.Model.GetObjectRequest) && (AmazonS3Uri.IsAmazonS3Endpoint(request.Endpoint)))
            {
                var region = new AmazonS3Uri(request.Endpoint.OriginalString).Region;
                if(region != RegionEndpoint.USEast1)
                    request.UseSigV4 = true;
            }
        }`

Regex code is in \src\services\s3\custom\util\AmazonS3Uri.cs

`private const string EndpointPattern = @"^(.+\.)?s3[.-]([a-z0-9-]+)\.";`

**Comment by normj** [comment]
Version 3.1.7.1 of the S3 Nuget package was just released that contains this fix.
