### ISSUE TITLE
Mac OS X Desktop Unity Build data fails to appear on Mobile Analytics Dashboard (but exports to S3)

### ISSUE THREAD

**Issue by sumpfork** [aws/aws-sdk-net#376]
According to https://github.com/aws/aws-sdk-net/issues/364 Unity desktop builds are supposed to be supported, and similarly https://forums.aws.amazon.com/thread.jspa?messageID=717598 seems to imply that only running in the Unity editor will produce data that does not appear on the AWS Mobile Analytics Dashboards.

However, when I build my game for Mac OS X desktop, events do not appear in the dashboard - same as for in the editor. They do export to S3, with a device section of

```
"device": {
    "locale": {
      "code": null
    },
    "make": "Unknown",
    "model": "Unknown",
    "platform": {
      "name": "Unknown",
      "version": "Unknown"
    }
  }
```

which I assume is the problem of them not appearing on the dashboard. The same game does send events that appear on the dashboard when run on iOS with a device section of

```
"device": {
    "locale": {
      "code": "en_CA",
      "country": "CA",
      "language": "en"
    },
    "make": "apple",
    "model": "iPhone",
    "platform": {
      "name": "iPhone OS",
      "version": "9.3.2"
    }
  }
```

Are desktop builds actually supposed to be supported like https://github.com/aws/aws-sdk-net/issues/364 claims? Or is there a way to set the device section manually to fix this? Otherwise, this seems like a bug.

**Comment by karthiksaligrama** [comment]
yes it does look like the platform make and model is not correctly set in case of desktop platforms. Thanks for reporting this error will take a look
