### ISSUE TITLE
Want Amazon.SimpleEmail.AmazonSimpleEmailServiceClient.ListReceiptRulesAsync Meshod

### ISSUE THREAD

**Issue by guitarrapc** [aws/aws-sdk-net#377]
AWSSDK.NET is marvelous SDK to automate AWS with C#. Thank you for this super cool project. 

Today, I have request about new Method for SES ReceiptRule. Currently there are only ```Amazon.SimpleEmail.AmazonSimpleEmailServiceClient.DescribeReceiptRuleAsync()``` Method and ListXxxx is not prepare to rules, you know there are both ```DescribeXxxx``` and ```ListXxxxx``` for many other APIs like ListReceiptRuleSetsAsync. 

![image](https://cloud.githubusercontent.com/assets/3856350/15986297/85acf7e2-303f-11e6-9afd-1e8fb4e7005b.png)

This enforce me to catch ```RuleDoesNotExistException``` when need to list rule and automate rule creation.

It's very happy if there are new method to describe list of recipient rules.
Cheers,

**Comment by normj** [comment]
Glad to hear the praise for the SDK:)

Looks like what you are asking for would be a new service operation. I suggest you open an issue on SES forums to let them know about the feature you want. When the services hear directly from customers what features they need that helps them prioritize their work.

https://forums.aws.amazon.com/forum.jspa?forumID=90
