### ISSUE TITLE
[COGNITO] Unhandled exceptions after synchronize anonymous data set

### ISSUE THREAD

**Issue by sebas86** [aws/aws-sdk-net#381]
This happens only if pool has disabled anonymous login.

Steps to reproduce:
1. In AWS panel disable anonymous account for test pool.
2. Open Cognito sample scene and provide pool id and region name.
3. Play scene.
4. Click synchronize.

Result (from Unity console):
[anonymous_exceptions.txt](https://github.com/aws/aws-sdk-net/files/313498/anonymous_exceptions.txt)

**Comment by karthiksaligrama** [comment]
i'm not sure what is it you are trying to say. Are you saying that the sdk is not handling the exceptions correctly?

I can see that the cognito client throws a `NotAuthorizedException` and the cognito sync fails the synchronization. Is there any other behavior that you are expecting?

**Comment by sebas86** [comment]
I miss Debug.LogException in log.

I forget about: http://docs.aws.amazon.com/mobile/sdkforunity/developerguide/setup-unity.html
