### ISSUE TITLE
[COGNITO] [SYNC] Data duplication after changing identity

### ISSUE THREAD

**Issue by sebas86** [aws/aws-sdk-net#382]
After switching authorization credentials SDK has few problems:
1. Many unhandled exceptions visible on console.
2. Not working synchronization.
3. Data duplication between different identities – in some cases after application restart all exceptions disappears but SDK sends all data stored locally for previous authorized identity for new one identity.

Steps to reproduce:
1. Enable Facebook authorization for test pool.
2. Open Cognito sample scene, put pool id and region name.
3. Configure Facebook SDK.
4. Fix SDK code for Facebook or just add some custom text input for Facebook Token.
5. Play scene.
6. Change some data which will be saved.
7. Provide FB Token for account A, click synchronize, wait for synchronize finish (console log).
8. Provide FB Token for account B, click synchronize, wait for errors ().
9. Restart app, provide FB token for account B, click synchronize, notice this time operation can success but also previously saved data for account A will be also saved on account B.

Result (from Unity console):
[cognito_account_change.txt](https://github.com/aws/aws-sdk-net/files/313545/cognito_account_change.txt)

**Comment by karthiksaligrama** [comment]
for 1 if you don't want logs to be made visible set your logging as per the Readme file.
for 2 can you specify what is not working in synchronization?
for 3 the sdk uses a instance of cognito aws credentials. If the login data changes in the cognito credentials and we get a new identity from service we will reparent the dataset to the new identity. In order to avoid this you need to associate the facebook account b with a different instance of cognito aws credentials. basically follow log out and login step.

**Comment by sebas86** [comment]
1. Right, I forget about awsconfig.xml… But this logs noise looks like many unhandled exceptions (I miss it's just LogException deep in SDK internals).
2. Related with 3. doesn't synchronize at all, all request fail.
3. Ok, so I just must check if previous and current token belongs to this same user and reset credentials by hand… I supposed it's handled automatically just like in case when identity is switched according to identity merge.

**Comment by karthiksaligrama** [comment]
for the log noise you can enable only error logs on the unity console. so you get only exception. But can't help you with the stacktrace since thats the way unity debug logs work.

**Comment by sebas86** [comment]
Thanks for hint, sadly I don't find nothing about how log out in official guide but I find some error report with useful information. Right now works if after switching users I call `ResetCredentials`, code bellow based on example from SDK:

```C#
void ResetCredentials()
{
	if (_credentials != null)
	{
		_credentials.Clear();
		_credentials = null;
		if (_syncManager != null)
		{
			_syncManager.Dispose();
			_syncManager = null;
		}
		if (playerInfo != null)
		{
			UnregisterDatasetEvents();
			playerInfo.Dispose();
			playerInfo = SyncManager.OpenOrCreateDataset("PlayerInfo");
			RegisterDatasetEvents();
		}
	}
}

void Start()
{
    UnityInitializer.AttachToGameObject(this.gameObject);

    // Open your datasets
    playerInfo = SyncManager.OpenOrCreateDataset("PlayerInfo");

    // Fetch locally stored data from a previous run
    alias = string.IsNullOrEmpty(playerInfo.Get("alias")) ? "Enter your alias" : playerInfo.Get("alias");
    playerName = string.IsNullOrEmpty(playerInfo.Get("playerName")) ? "Enter your full name" : playerInfo.Get("playerName");

	RegisterDatasetEvents();
}

void RegisterDatasetEvents()
{
	playerInfo.OnSyncSuccess += this.HandleSyncSuccess;
	playerInfo.OnSyncFailure += this.HandleSyncFailure;
	playerInfo.OnSyncConflict = this.HandleSyncConflict;
	playerInfo.OnDatasetMerged = this.HandleDatasetMerged;
	playerInfo.OnDatasetDeleted = this.HandleDatasetDeleted;
}

void UnregisterDatasetEvents()
{
	playerInfo.OnSyncSuccess -= this.HandleSyncSuccess;
	playerInfo.OnSyncFailure -= this.HandleSyncFailure;
	playerInfo.OnSyncConflict -= this.HandleSyncConflict;
	playerInfo.OnDatasetMerged -= this.HandleDatasetMerged;
	playerInfo.OnDatasetDeleted -= this.HandleDatasetDeleted;
}

[…]
```

**Comment by sebas86** [comment]
Sadly data duplication still occurs. After switch account Cognito Sync still merges data between two different and not linked identities (this identities are authorized with different Facebook accounts). What is wrong with code above? Reinitializing is not enough to switch identity to new one? Maybe I should just reset local database content? If answer is yes, how I should do it?

**Comment by sebas86** [comment]
> basically follow log out and login step.
There are nothing about this in official developer guide
http://docs.aws.amazon.com/cognito/latest/developerguide/developer-authenticated-identities.html. Can you provide any link to place where log out is described step by step?

My workaround works right now for me, but afraid that this just stops work with next SDK update according to some undocumented/undefined behaviors used in this solution.

**Comment by karthiksaligrama** [comment]
Calling credentials.Clear should log you out.

**Comment by sebas86** [comment]
This is not enough. Credentials are invalidated, I can login using another account, but Cognito Sync keeps all previous user data. After login as other identity Cognito Sync merges previous user data stored in local DB and new one fetched from server. This in my case cause game progress duplication between different users.

**Comment by klaytaybai** [comment]
Closing due to age, inactivity, and AWS alternatives.
