### ISSUE TITLE
S3 Client Creation Failing in Release Mode

### ISSUE THREAD

**Issue by thetheosopher** [aws/aws-sdk-net#384]
My Windows UWP application is failing in release mode within the AmazonS3Client constructor.  From what I can tell, this is related to an inability to load endpoint definitions from an embedded resource.  I have attached a call stack dump.  This works wonderfully in debug mode.  I have tried various workarounds to specify the service URL's and other configuration parameters manually rather than use the RegionEndpoint static properties, but it fails in the same manner regardless as if it tries to read the embedded resource regardless of how the AmazonS3Client is constructed -- and fails in release mode consistently.  I'm using AWSSDKCore 3.1.7 and AWSSDK.S3 3.1.7.2. 

![callstack](https://cloud.githubusercontent.com/assets/14339127/16066068/6b40f752-326d-11e6-9bfe-35d898a3dc10.png)

**Comment by normj** [comment]
I have not been able to reproduce this issue. Are you still seeing this issue?

**Comment by thetheosopher** [comment]
I was unable to resolve so I had to remove my dependency on the SDK and put together my own limited functionality library for the handful of S3 and SQS requests I needed to make.  I ran into a similar issue with my own UWP libraries when resolving string resources in release mode and had to implement some workarounds in order to get past it.
