### ISSUE TITLE
SQS adding QueueURL to request returns client exception

### ISSUE THREAD

**Issue by justinsaraceno** [aws/aws-sdk-net#385]
Using the 3.2.4.1 beta .NET SDK (with .NET Core RC2), when attempting a ReceiveMessageAsync or DeleteMessageAsync with the queueUrl property set to any valid queue URL (including the queue URL set for the AmazonSQSClient), returns a client exception, "_the specified queue does not exist or you do not have access to it_".

**sample client:**
```
var sqsConfig = new AmazonSQSConfig
{
	RegionEndpoint = "RegionEndpoint.USEast1",
	ServiceURL = "https://sqs.us-east-1.amazonaws.com/123456789012/myQueue"
};

var credentials = new AnonymousAWSCredentials();
var client = new AmazonSQSClient(credentials, sqsConfig);
```

**sample delete message request with the queueURL set:**
```
private static DeleteMessageResponse DeleteMessageFromQueue(string receiptHandle)
{
	var request = new DeleteMessageRequest(
		queueUrl: "https://sqs.us-east-1.amazonaws.com/123456789012/myQueue",
		receiptHandle: receiptHandle);

	return _client.DeleteMessageAsync(request).Result;
}
```

When the `DeleteMessageRequest` object has the `queueURL` set as shown above, the indicated client exception is thrown.  When the `queueURL` is explicitly set to null for the `DeleteMessageRequest` object, the `DeleteMessageAsync` operation is successful.

The same case is true for the `ReceiveMessageRequest` when it has its `QueueUrl` property set.

Why would setting the client QueueUrl and the DeleteMessageRequest queueUrl properties to the same value cause this exception?  Why do the requests need their QueueUrl properties set to null in order for this to work?

**Comment by sstevenkang** [comment]
The sample code has a problem where the `ServiceURL` is malformed.  See the documentation [here](http://docs.aws.amazon.com/AWSSdkDocsNET/V3/DeveloperGuide/how-to/sqs/InitSQSClient.html).  `ServiceURL` property should be set to `"https://sqs.us-east-1.amazonaws.com"`.  Furthermore, since `RegionEndpoint` property is specified, setting `ServiceURL` is redundant in this case.
