### ISSUE TITLE
S3 Bucket Association With User

### ISSUE THREAD

**Issue by dfiverr** [aws/aws-sdk-net#388]
My application allows for users to store their files. I will be storing their files within a S3 bucket. Should I design it so each user gets their own S3 bucket, but the application will be used by tens of thousands of users, each user storing tens of thousands of files. But I see the maximum amount of buckets allowed is 100. Or if I store all the files in a single buckets, how would I relate each users cognito identity to their files? Would I give each user a folder inside the bucket? 
Thank you

**Comment by normj** [comment]
S3 has hard limits on the number of buckets so you don't want to go down the path of a bucket per user. What I see people usually do is use one bucket but put all the user's data under a certain prefix. By that I mean the S3 object key might start with with something like <user-id>/score.data. For the  policy that the user assumes you can lock the permissions down to the prefix in the bucket.

For a more information about how to setup the policy check out the Cognito docs or ask in the Cognito forums.

http://aws.amazon.com/documentation/cognito/
https://forums.aws.amazon.com/forum.jspa?forumID=173

**Comment by dfiverr** [comment]
Thanks normj do you think a prefix is better than storing the user who the file belongs to in the metadata of the file Object?

**Comment by normj** [comment]
I don't believe you can restrict policy based on metadata. Also the ListObjects operations allows you to give a prefix so you use that to get the objects just for a user.

**Comment by dfiverr** [comment]
Sounds good. Any advice on how to file sync a users files across multiple devices and s3?

**Comment by dfiverr** [comment]
@normj Do you think its a good idea to use each users identityId of the user as the prefix (like us-east-1:df44faf6-147b-3f2f-a8cf-421e5f7c28bf) as the prefix? it seems a little long. Or the email? 
Please let me know, thank you.

**Comment by normj** [comment]
Sorry for the late response but yes identityid is a common pattern I see for the S3 prefix. For better info on the usage of Cognito I would suggest using the Cognito forums. https://forums.aws.amazon.com/forum.jspa?forumID=173
