### ISSUE TITLE
Amazon Glacier 3.2.4.1-beta nuget package for netstandard1.5 missing classes

### ISSUE THREAD

**Issue by AerisG222** [aws/aws-sdk-net#389]
I am trying to get started with Amazon Glacier in a new .netcore application.  I am referencing the nuget package referenced above, but am not able to compile as I am getting errors indicating that the namespace Amazon.Glacier.Transfer is not found.

dotnet restore worked fine, and when I inspect the dll that is pulled down for netstandard1.5 by using "monop2 -r:./AWSSDK.Glacier.dll", I do see Amazon.Glacier namespaces, but not Amazon.Glacier.Transfer (a total of 170 types).  When I then run the same command on the dll in net45, I do see this namespace, and results in a total of 176 types.

**Comment by normj** [comment]
Amazon.Glacier.Transfer is a high level abstraction on top of Amazon.Glacier.IAmazonGlacier that we haven't yet ported to .NET Core. It is on our plan to do but I don't have an ETA when we will release it.

**Comment by normj** [comment]
Amazon.Glacier.Transfer has been added to netstandard in version 3.2.7-beta
