### ISSUE TITLE
How to use Cognito User Pool in Xamarin

### ISSUE THREAD

**Issue by imnasif** [aws/aws-sdk-net#390]
Here's the original question
https://github.com/awslabs/aws-sdk-xamarin/issues/36

**Comment by PavelSafronov** [comment]
The original question links to an AWS Forum post about this - https://forums.aws.amazon.com/thread.jspa?messageID=725316

The feature is planned to be available for Xamarin (and other SDKs), though I can't give an expected delivery date.

**Comment by guitarrapc** [comment]
I'm also struggling with UserPool sign in. Several SDK have sample and method but seems not in .NET SDK, through.

- [Android](https://mobile.awsblog.com/post/TxNYVQQ3A2LT6Y/Using-Android-SDK-with-Amazon-Cognito-Your-User-Pools)
- [Android](http://docs.aws.amazon.com/cognito/latest/developerguide/using-amazon-cognito-user-identity-pools-android-sdk.html)
- [iOS](http://docs.aws.amazon.com/cognito/latest/developerguide/using-amazon-cognito-user-identity-pools-ios-sdk.html)
- [JavaScript](http://docs.aws.amazon.com/cognito/latest/developerguide/using-amazon-cognito-user-identity-pools-javascript-examples.html)

I also looking forward to see Amazon.ServiceProvider on .NET and Unity!

**Comment by syedrakib** [comment]
struggling with this..... any ETA yet?

**Comment by akamud** [comment]
Is this not possible ATM?

**Comment by EmilAlipiev** [comment]
what is the status on this? anything available? doable?

**Comment by gokarnm** [comment]
This feature is available in the iOS, Android and JS SDK but not in the .NET SDK, I've add this as a feature request but I don't have an ETA for when this will be available.

Related to #495

**Comment by PavelSafronov** [comment]
I believe this is the same request as #495, closing this issue.
