### ISSUE TITLE
AWSSDK.S3 - Encoding Square Brackets

### ISSUE THREAD

**Issue by m-hoffmann-vertical** [aws/aws-sdk-net#394]
Hello,

I think I found an issue regarding URL encoding in AWSSDK.S3. Characters like '%', '+' and '&' are correctly escaped in S3 keys, except for square brackets ('[' and ']').

When I try to manually escape these brackets in a S3 key (e.g. '[' to '%25'), the AWSSDK.S3 also escapes my percentage sign.

Are there any other ways to use square brackets within the .NET AWSSDK.S3?

Thanks!

**Comment by PavelSafronov** [comment]
Can you post your code and sample keys that are not working with the .NET SDK? Which version of the SDK are you using?

I was able to run the below code without issues, and it uses a key with square brackets:
```
var s3Client = new AmazonS3Client();

var key = "key[with]brackets";
s3Client.PutObject(new PutObjectRequest
{
    BucketName = bucketName,
    Key = key,
    ContentBody = content
});

using(var response = s3Client.GetObject(bucketName, key))
{
    using(var reader = new StreamReader(response.ResponseStream))
    {
        var s3content = reader.ReadToEnd();
        Assert.AreEqual(content, s3content);
    }
}
```

**Comment by m-hoffmann-vertical** [comment]
I am using AWSSDK.Core 3.1.8.1 and AWSSDK.S3 3.1.8.0.

The following code leads to the HTTP 500 response at the bottom.
```
var request = new PutObjectRequest();
request.FilePath = filePath;
request.BucketName = containerName;
request.Key = "[Test]";
request.CannedACL = S3CannedACL.PublicReadWrite;

PutObjectResponse response = null;

try
{
    response = await _s3Client.PutObjectAsync(request, cancellationToken);
}
finally
{
    if (response is IDisposable) ((IDisposable)response).Dispose();
}
```

```
PUT https://storage.contoso.com:9021/test-container/[Test]/ HTTP/1.1
x-amz-acl: public-read-write
Content-Type: text/plain
User-Agent: aws-sdk-dotnet-45/3.1.8.0 aws-sdk-dotnet-core/3.1.8.1 .NET_Runtime/4.0 .NET_Framework/4.0 OS/Microsoft_Windows_NT_6.2.9200.0 ClientAsync
X-Amz-Date: Mon, 04 Jul 2016 14:31:55 GMT
Authorization: AWS XXX:XXX
Host: storage.contoso.com:9021
Content-Length: 0

HTTP/1.1 500 Illegal character in path at index 55: https://storage.contoso.com:9021/test-container/[Test]/
Cache-Control: must-revalidate,no-cache,no-store
Content-Type: text/html;charset=ISO-8859-1
Content-Length: 1483
Server: Jetty(7.6.4.v20120524)

<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 Illegal character in path at index 55: https://storage.contoso.com:9021/test-container/[Test]/</title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /test-container/[Test]/. Reason:
<pre>    Illegal character in path at index 55: https://storage.contoso.com:9021/test-container/[Test]/</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>          
</body>
</html>
```

**Comment by PavelSafronov** [comment]
Thanks for including the response wirelog. Looks like you are using Jetty and that's the software that is throwing the 500 response. It's likely that Jetty does not support these characters. Not sure what you can do to change this behavior, though.
Closing as this appears to be an issue with Jetty.

**Comment by m-hoffmann-vertical** [comment]
Thank you for your reply. Indeed, Jetty has the problems with square brackets and not AWSSDK.S3.

Currently, I am not able to mask square brackets with AWSSDK.S3. Other characters like '%', '&', '+' are masked correctly.

Is it possible to change the requesting url from `https://storage.contoso.com:9021/test-container/[Test]` to `https://storage.contoso.com:9021/test-container/%5BTest%5D`?

When I am trying to mask the key manually, `%255BTest%255D` is set in the request URL instead of `%5BTest%5D`. This actually makes sense, since AWSSDK.S3 escapes the percentage signs.

**Comment by PavelSafronov** [comment]
I don't believe you can "mask" the square brackets. Are you able to replace square brackets with a different set of characters that Jetty would understand?

**Comment by l-moeller-vertical** [comment]
Hallo, 
I continue the task of my colleague and we have still problems with square brackets. I've tested the issue again. We are using AWSSDK.Core and AWSSDK.S3 nuget package on version 3.3.0
We can not spot any other characters that are not masked except the square brackets.
For example the outgoing request header of a call with "{Curly Brackets}[Square Brackets].txt" looks like this:
`PUT /test-bucket/%7BCurly%20Brackets%7D[Square%20Brackets].txt HTTP/1.1`

Is it possible that the SDK mask the square brackets? Would be great and thanks for the support.

**Comment by PavelSafronov** [comment]
Apologies for the late reply, and unfortunately it's pretty much the same as before: there is no way for the SDK to "mask" square brackets and it's unlikely there ever will be.
You would need to either work around this limitation in your work-flow, use a different SDK, or modify the source of the current SDK to not encode these problematic characters.
