### ISSUE TITLE
AWSSDK version 3.1.6 .net 3.5, AmazonS3  and CleverSafe cannot create Bucket the body of  the request is different than <CreateBucketConfiguration> #question

### ISSUE THREAD

**Issue by luis-fernando-camacho-metalogix** [aws/aws-sdk-net#396]
Hi Guys,

this a question is not bug or issue and sorry for my english grammar. 

I have a problem when I try to create a bucket using amazonS3 and Cleversafe with AWSSDK version 3.1.6 and .net 3.5.
I observed that AWSSDK generate the following body in his PUTBUCKET request for example If I use the following C#:
`<PutBucketConfiguration><LocationConstraint>us-west-1</LocationConstraint></PutBucketConfiguration>`

```
private static void CreateBucketWithCleverAutoProvisionMethod()
        {
            ServicePointManager.ServerCertificateValidationCallback += (sender, cert, chain, error) => { return true; };
            BasicAWSCredentials basicCredentials = new BasicAWSCredentials("My accesskey", "my secret key");
            AmazonS3Config configurationClient = new AmazonS3Config();
            configurationClient.ForcePathStyle = true;
            configurationClient.ServiceURL = "https://18.140.198.126";
            configurationClient.UseHttp = true;
            try
            {
                using (AmazonS3Client clientConnection = new AmazonS3Client(basicCredentials, configurationClient))
                {
                    PutBucketRequest newBucket = new PutBucketRequest();
                    newBucket.BucketName = "cleversafeone";
                    newBucket.BucketRegionName = "us-west-1";
                    PutBucketResponse response = clientConnection.PutBucket(newBucket);
                }
            }
            catch (AmazonS3Exception exception)
            { 
                ULS.writeException(exception)
            }
        }
```
```
```

 I get "The XML you provided was not well-formed or did not validate against our published schema." exception.

So the CleverSafe support tell that the body of the PUTBucket request should be :

 `<CreateBucketConfiguration><LocationConstraint>us-west-1</LocationConstraint></CreateBucketConfiguration>
`

and not 
`<PutBucketConfiguration><LocationConstraint>us-west-1</LocationConstraint></PutBucketConfiguration>`

Even in AWS documentation it shows that the PutBucket call should send the **CreateBucketConfiguration** XML

 <CreateBucketConfiguration> :
[http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUT.html]
```
Could you explain me why is there difference between body request,please? or
Could you explain me why Does AWSSDK.S3 generate <PutBucketConfiguration> instead of <CreateBucketConfiguration> for the PutBucketRequest>?

```
thanks for your time and have a nice day.

best regards,
Luis Fernando Camacho.

@trevorrowe  @mtdowling  @fulghum @isuttle @samritchie

**Comment by PavelSafronov** [comment]
Curious. I just tested the SDK against S3 and was successfully able to create a bucket, with the following request body:
`<PutBucketConfiguration><LocationConstraint>us-west-1</LocationConstraint></PutBucketConfiguration>`

It looks to be identical to the one you specified.

Are you hitting S3, or a different service?

**Comment by luis-fernando-camacho-metalogix** [comment]
thanks for answering. yes  I am using [Cleversafe](https://www.cleversafe.com/) + AmazonS3.
so CleverSafe team support told me that they expect `<CreateBucketConfiguration><LocationConstraint>us-west-1</LocationConstraint></CreateBucketConfiguration>`
and they told that they used Using the latest version of the AWS Java SDK(1.11.9), we were able to createBuckets . Here's an example of that code using java:

AmazonS3 s3client = new AmazonS3Client(awsCreds);
s3client.setEndpoint("http://xx.xx.xx.xx");

try {
if(!(s3client.doesBucketExist(bucketName)))
{
s3client.createBucket( bucketName, provisioningCode);
}

this java code returns the followin request header and body. 
PUT /dlbucket/ HTTP/1.1
Host: xx.xx.xx.xx
x-amz-content-sha256: b024c388d9d8769030008afd6e302524ed1308a9f3c108bfa4e481d652b5313cf
Authorization: AWS4-HMAC-SHA256 Credential=VwH86UNo2ob82AcIYkA1/20160623/us-east-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-type;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=bc8552d13ab7db355cdf4d1303ecd2142e300c9bbb5b9e5e3740bb60796be78f
X-Amz-Date: 20160623T192110Z
User-Agent: aws-sdk-java/1.11.9 Mac_OS_X/10.11.4 Java_HotSpot(TM)_64-Bit_Server_VM/25.73-b02/1.8.0_73
amz-sdk-invocation-id: 5f1aed3f-20c9-4fa9-9552-836f51b05341
amz-sdk-retry: 0/0/
Content-Type: application/octet-stream
Content-Length: 153
Connection: Keep-Alive
Expect: 100-continue

HTTP/1.1 100 Continue

<CreateBucketConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><LocationConstraint>us-west-1</LocationConstraint></CreateBucketConfiguration>HTTP/1.1 200 OK

So I do not understand why AWSSDK.S3 for .net generate `<PutBucketConfiguration><LocationConstraint>us-west-1</LocationConstraint></PutBucketConfiguration>` instead of `<CreateBucketConfiguration><LocationConstraint>us-west-1</LocationConstraint></CreateBucketConfiguration>`?
So AWS documentation it shows that the [PutBucket](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUT.html) call should send the **CreateBucketConfiguration** XML

Is there any support aws doc link  about <PutBucketConfiguration> body generate by PutBucketResquest in AWS SDK .net documentation ?

**Comment by PavelSafronov** [comment]
The request XML was corrected in the latest version of the .NET SDK. Thanks for bringing this to our attention.
