### ISSUE TITLE
Provide AWS{3,4}Signer that takes a HttpRequestMessage

### ISSUE THREAD

**Issue by paddie** [aws/aws-sdk-net#397]
Or is there some example of how to convert a HttpRequestMessage to an IRequest that the current AWS4Signer uses.

We're calling api-gateway using IAM authorization which requires the execute-api service, and that requires the AWS4Signature that uses HMAC-256. It would be really nice to have some maintained utility that enables one to sign a generic HttpRequestMessage.

I've copied this gist for now, but I am seeing some discrepancies between what is in the aws-sdk-net AWS4Signer.

Is there a better way than the one I am using?

**Comment by normj** [comment]
We don't have a better approach now but making a signing code more accessible is something we want to do for these API Gateway cases.

**Comment by paddie** [comment]
Aye, that sounds good. I'm merging what is in the aws4signer and the gist
for now (since it is missing some steps), let me know if you want to look
at it. The signer will take only a HttpRequstMessage and add the Authorize
headers as your signer does.

**Comment by vellozzi** [comment]
This has been added to our feature request list: https://github.com/aws/aws-sdk-net/blob/master/FEATURE_REQUESTS.md

**Comment by jakejscott** [comment]
I'm using AWS Elastic Search Service and requests need to be signed.

There is a nuget package which has to implement the signing code but there's bugs in that library. 

For example if you try to enable gzip compression it doesn't work and you get the error:

 `The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.`

https://github.com/bcuff/elasticsearch-net-aws

Is gzip compression compatible with v4 signing?

**Comment by niraj-bpsoftware** [comment]
Any update on when signer would be available as a utility in sdk?

**Comment by NeilBostrom** [comment]
Just leaving a +1 for having public API for signing HttpClient requests (or anything really) and not having to use internal namespaces for it.

**Comment by slikk66** [comment]
Having the ability to sign requests for AWS services should be considered a high priority for a production AWS SDK!

We just ran into a big roadblock here because I decided to use signed API GATEWAY for a project and one of our backend systems is in .NET and well, oof :/

**Comment by epvanhouten** [comment]
The SDK not enabling authenticating IAM against API Gateways is currently being a blocker.

**Comment by karlanke** [comment]
This is also required for HealthImaging DICOM requests, FYI, since those methods are not available in the normal API/SDK. Really weird that we have to go to a third-party for a security method that takes credentials

**Comment by obrassard** [comment]
Could you provide an update regarding this functionality? It seems unusual that we need to rely on a third-party package like [Aws4RequestSigner](https://www.nuget.org/packages/Aws4RequestSigner/) to sign HttpRequestMessage objects.

In our specific use case, we need to sign requests made to an AppSync Events APIs in order to publish events using IAM credentials
