### ISSUE TITLE
Support for netstandard

### ISSUE THREAD

**Issue by niemyjski** [aws/aws-sdk-net#398]
Do you have any plans to support net standard?

**Comment by normj** [comment]
The 3.2 beta NuGet package currently support net standard 1.5.

**Comment by niemyjski** [comment]
I was looking at AWSSDK.S3 which doesn't look like it's been updated. Can you please confirm

**Comment by niemyjski** [comment]
https://www.nuget.org/packages/AWSSDK.S3/3.2.4.1-beta

**Comment by niemyjski** [comment]
@normj what about s3?

**Comment by normj** [comment]
What trouble are you having using S3 with netstandard? The package targets netstandard 1.5 and as 3.2.5-beta the package was moved to the 1.0 release of .NET Core.

**Comment by niemyjski** [comment]
@normj this is not true..

https://www.nuget.org/packages/AWSSDK.S3/3.2.5-beta

```
Dependencies
All Frameworks
AWSSDK.Core (>= 3.2.5-beta && < 3.3.0-beta)
Portable Class Library (.NETFramework 4.5, Windows 8.0, WindowsPhone 8.0, WindowsPhoneApp 8.1)
AWSSDK.Core (>= 3.2.5-beta && < 3.3.0-beta)
```

**Comment by niemyjski** [comment]
Says all and pcl and I'm not sure what all means in this context.

**Comment by normj** [comment]
The all includes .NET Core and if you follow the link to AWSSDK.Core you will see that supports netstandard 1.5. What is the error you are getting? I have verified pulling in the S3 package from nuget for .NET Core works.
