### ISSUE TITLE
NotImplementedException thrown by PCLStorage dependency when running in .NET Core

### ISSUE THREAD

**Issue by groppe** [aws/aws-sdk-net#399]
Developing a .NET Core application in VS 2015 on Windows, and I need to use the S3 SDK. When I try to do a basic file upload to S3, a NotImplementedException is thrown:
```
var amazonS3Client = new AmazonS3Client(credentials, RegionEndpoint.USEast1);
try
{
    PutObjectRequest request = new PutObjectRequest
    {
         BucketName = bucketUrl,
         Key = key,
         FilePath = filepath
     };

    CancellationToken token = new CancellationToken();

    amazonS3Client.PutObjectAsync(request, token).Wait();
}
catch (AmazonS3Exception s3Exception)
{
    logger.LogError(s3Exception.Message);
}
```
`System.NotImplementedException`: This functionality is not implemented in the portable version of this assembly.  You should reference the PCLStorage NuGet package from your main application project in order to reference the platform-specific implementation.
   at PCLStorage.FileSystem.get_Current()

I manually installed the PCLStorage NuGet package via VS 2015, but still got the same exception.

**Comment by normj** [comment]
Our .NET Core support does not rely PCStorage. Our NuGet package contains both a portable class library for the Xamarin platform and a netstandard library for the .NET Core. I'm wondering if you are somehow pulling in the portable class library version which won't work in .NET Core. What version of the SDK are you referencing and can you share how you declared your frameworks in your project.json.

**Comment by groppe** [comment]
The relevant snippet of my project.json is below:
```
"AWSSDK.S3": "3.2.4.1-beta",
"AWSSDK.Core": "3.2.4.1-beta",
"Validation": "2.2.5",
"PCLCrypto": "2.0.147"
```
Also, I'm having to reference the last two because I receive build errors if I do not specify those versions. The SDK seems to reference older versions.

**Comment by normj** [comment]
The AWS SDK is was retargeted to netstandard1.5 with RC2 and no longer targets dnxcore50. Try changing the dnxcore50 in the frameworks to netstandard1.5.

**Comment by niemyjski** [comment]
@normj can you update the S3 package with maybe a new beta and add support for netstandard officially. I don't want to do an imports to bring a pcl package in.. I want official netstandard support like the core package. Until this happens we can't update Foundatio to support s3 on .net core. https://github.com/exceptionless/Foundatio

**Comment by normj** [comment]
I'm not sure what you are looking for besides what we already provide. The 3.2.5-beta version of the SDK is targeting the official netstandard1.5 as you can see on the NuGet page?

https://www.nuget.org/packages/AWSSDK.Core/3.2.5-beta

**Comment by normj** [comment]
Closing since I believe there is no action for us to take
