### ISSUE TITLE
Got Exception The request signature we calculated does not match the signature you provided. Check your key and signing method.

### ISSUE THREAD

**Issue by dfiverr** [aws/aws-sdk-net#401]
I am getting the issue "Got Exception The request signature we calculated does not match the signature you provided. Check your key and signing method." when trying to get the metadata of files in my bucket. I am working with the Unity SDK. Funny enough, it seems to occur most when my developer authenticated user is not logged in. Please let me know if there is a way to resolve this.

Here is what my request looks like:         

var request = new ListObjectsRequest()
        {
            BucketName = S3BucketName,
            Prefix = LambdAuthLogin.IdentityId
        };

**Comment by dfiverr** [comment]
Some more information, I get the "Got Exception The request signature we calculated does not match the signature you provided. Check your key and signing method." error when I am logged in with my developer authenticated account. Funny enough, it seems to list the metadata just fine when it is anonymous and not logged in, but this is useless to me. I'm using the LambdAuth project for user authentication. Some additional information, GetObjectMetadataAsync is whats giving me the "Got Exception The request signature we calculated does not match the signature you provided. Check your key and signing method."  error.

**Comment by dfiverr** [comment]
Here is what my method to grab the metadata looks like

    /// <summary>
    /// Gets the meta data of an object
    /// </summary>
    /// <param name="key"></param>
    public void ListObjectMetadata(string key)
    {
        AWSConfigs.HttpClient = AWSConfigs.HttpClientOption.UnityWebRequest;

        Debug.Log("ListObjectMetadata starting, key was : " + key);

        var request = new GetObjectMetadataRequest()
        {
            BucketName = S3BucketName,
            Key = key
        };

        Debug.Log("key length was : " + key.Length);

        Client.GetObjectMetadataAsync(request, (responseObject) =>
        {
            if (responseObject.Exception == null)
            {
                if (responseObject.Response != null)
                {

                    Debug.Log("metadata was : " + responseObject.Response.Metadata[NAME_METADATA_KEY]);

                }
                else
                {
                    Debug.Log("responseObject.Response.ResponseStream was null!");
                }
            }
            else
            {
                Debug.Log("Got Exception " + responseObject.Exception.Message);
            }
        });
    }

**Comment by PavelSafronov** [comment]
How are you providing credentials to the Client object?

**Comment by dfiverr** [comment]
@PavelSafronov I was providing it in the accessor method for the client, but I have actually fixed this problem now in a similar manner (by actually providing the credentials every time).

For anyone who encounters similar problems in the future, the way I was able to fix it is by putting the following code into each method and instantiating the client every call.

```
        using (var client = new AmazonS3Client(accesskey, secret, _S3Region))
        {
            client.ListObjectsAsync(request, (responseObject) =>
```
