### ISSUE TITLE
RefreshingAWSCredentials does not refresh credentials for Unity

### ISSUE THREAD

**Issue by madangosain** [aws/aws-sdk-net#402]
```
public abstract class RefreshingAWSCredentials : AWSCredentials
```

does not refresh credentials automatically. It consistently gives error for multiple devices over different regions:

AmazonClientException: The retrieved credentials have already expired: Now = 06/23/2016 22:20:36, Credentials expiration = 06/23/2016 22:16:01
AmazonClientException: The retrieved credentials have already expired: Now = 06/23/2016 16:54:28, Credentials expiration = 06/23/2016 15:55:41
AmazonClientException: The retrieved credentials have already expired: Now = 06/23/2016 21:51:26, Credentials expiration = 06/23/2016 20:50:09

I believe that RefreshingAWSCredentials code is not waiting for new credentials to loaded for Unity and assuming it is synchronous. 

Moreover AWSCredentials.cs does not expose _currentState or either CurrentState.ExpirationTime for developer to implement their own auto-refreshing. We are stuck with current issue without any help. I've seen several threads for the same without any solution
https://forums.aws.amazon.com/thread.jspa?threadID=233919
https://forums.aws.amazon.com/thread.jspa?threadID=234211

At the minimum, if you can make currentState public, that will allow us to auto-refresh the credentials ourselves by calling GetCredentialsAsync

**Comment by madangosain** [comment]
This bug is still reproducible and I see that Andreyul's PR is not merged. Do we have any workaround for this?

**Comment by madangosain** [comment]
@karthiksaligrama , any update on this issue? Can you please make currentState public so that developer can refresh the credentials as needed.

**Comment by mcmorry** [comment]
Any update? is several months that this bug is open...

**Comment by PavelSafronov** [comment]
PR #427 replaced all the `DateTime.Now` and `DateTime.UtcNow` uses in the SDK with a "corrected" DateTime value, so this issue should not be occurring with the latest version of the SDK.
Resolving.
