### ISSUE TITLE
Republish on 1.0 RTM Core

### ISSUE THREAD

**Issue by akatz0813** [aws/aws-sdk-net#403]
Hi!  Now that the RTM packages are starting to be published (run times are already on download.microsoft.com), how quickly will you be publishing an update to nuget?

**Comment by normj** [comment]
We'll be taking a look at updating to RTM when it releases this week.

**Comment by akatz0813** [comment]
Thanks @normj It's out!

**Comment by justinsaraceno** [comment]
In a file -> new console project with .NET Core 1.0 RTM and then adding AWSSDK.DynamoDBv2 3.2.4.1-beta, there's a conflict between .NET Core's version of _System.Runtime.InteropServices_ (v 4.1) and AWSSDK's _System.Runtime.InteropServices_ (v 4.0).

If you're not using InteropServices in your logic, the work-around for now seems to be to comment out the assembly Guid attribute in AssemblyInfo.cs

Not sure if it's a NuGet bug that 2 conflicting versions of this assembly are allowed to be loaded, or if it's the expectation of the AWSSDK package to follow the matching assembly version.

**Comment by normj** [comment]
I just pushed version 3.2.5-beta to NuGet which ups the support for .NET Core 1.0

**Comment by akatz0813** [comment]
thank you for being so quick on this!!
