### ISSUE TITLE
AmazonS3Client does not contain GetObject?

### ISSUE THREAD

**Issue by doomchild** [aws/aws-sdk-net#405]
Using the 3.2.4.1-beta package from NuGet (and the output of "dotnet --version" being "1.0.0-preview2-003121"), I can't build my project.  This worked in the RC1 phase of .NET Core, but now, running "dotnet build" gives this output:

Project my-project (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling my-project version=v1.0
/usr/local/share/dotnet/dotnet compile-csc @~/code/my-project/obj/Debug/netcoreapp1.0/dotnet-compile.rsp returned Exit Code 1
~/code/my-project/Controllers/ArchiveController.cs(49,59): error CS1061: 'AmazonS3Client' does not contain a definition for 'GetObject' and no extension method 'GetObject' accepting a first argument of type 'AmazonS3Client' could be found (are you missing a using directive or an assembly reference?)

Compilation failed.
    0 Warning(s)
    1 Error(s)

**Comment by PavelSafronov** [comment]
You need to be calling GetObjectAsync instead.

**Comment by doomchild** [comment]
Okay, that fixes the build.  Now for the why.  If I open up the assembly with DotPeek (or just rely on Omnisharp's completions), the `GetObject` method exists.  Is there some other voodoo going on here?

**Comment by PavelSafronov** [comment]
Don't know about Omnisharp, but DotPeek should be reporting that there is an **internal** GetObject method.

**Comment by doomchild** [comment]
This is the part where I realize I didn't notice the access modifier on the method and hang my head in shame.

**Comment by PavelSafronov** [comment]
No worries. I'm just amused that this is the question that got asked for issue [405](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#405) of this repo.
