### ISSUE TITLE
[Unity] Endless sync lock and no callback caused by network failure during GetIdentityId

### ISSUE THREAD

**Issue by pfleeter** [aws/aws-sdk-net#406]
`Dataset.SynchronizeAsync` will call `FireSyncFailureEvent` if it determines that the network status is `NotReachable`.  It makes this determination using Unity's `Application.internetReachability` in `NetworkInfo`.  However, according to Unity's [documentation](http://docs.unity3d.com/ScriptReference/Application-internetReachability.html), this check cannot be used to determine whether the internet is actually reachable.  Assume that it is not actually functional.

In this case, `SynchronizeAsync` will call `SynchronizeHelperAsync` (which locks itself), which will call `SynchornizeInternal` in another thread via the `AsyncExecutor`.  In `SynchornizeInternal`, `CognitoCredentials.GetIdentityId` is called.  Since it cannot communicate with the identity service, it will return a "base stream is null" exception, which is not handled in `SynchornizeInternal`.  The exception is caught by `SafeExecute`, the sync success or failure events are never fired, and the lock on the dataset is never released.

A logged example of this can be seen in [this forum post](https://forums.aws.amazon.com/message.jspa?messageID=721512#721512).

**Comment by klaytaybai** [comment]
Closing due to age, inactivity, PR referenced in the linked forum post

**Comment by klaytaybai** [comment]
Closing due to age, inactivity, PR referenced in the linked forum post
