### ISSUE TITLE
create a policy with hyphens as part of the arn (not in the account ID) has them stripped

### ISSUE THREAD

**Issue by pwildabide** [aws/aws-sdk-net#407]
new Policy(string accountId)
or
new Policy(string provider, string id) 

If the provider is AWS it will automatically strip any hypens. However if there are hyphens in the IAM role for example, these will get stripped as well. This seems like a bug?

Java SDK has overload: 

Principal(String provider, String id, boolean stripHyphen)
Constructs a new principal with the specified id and provider.

**Comment by pwildabide** [comment]
Added a pull request with overloaded method for consideration

**Comment by normj** [comment]
I pushed version 3.1.8.1 of the AWSSDK.Core NuGet package which contains the pull request.

**Comment by pwildabide** [comment]
Thank you very much!
