### ISSUE TITLE
Sync count of local merged data set doesn't match reparented remote dataset.

### ISSUE THREAD

**Issue by pfleeter** [aws/aws-sdk-net#413]
On Unity, during a merge, the local dataset and records are copied to a new name ("dataset.identity").  If a synchronize is attempted on this dataset, it can fail because the local version of that dataset has an unmodified dataset sync count, where the remote merge dataset has a sync count of 1.  The sync fails with an error that the sync count of the local merge data set does not exist.

Often times, a sync is performed prior to a deletion, but the sync does not succeed, and this can lead to the accumulation of merge datasets in the remote store.

**Comment by pfleeter** [comment]
Related to #360

**Comment by klaytaybai** [comment]
I think your PR fixed this, so I'm closing this issue.
