### ISSUE TITLE
UploadPartRequest.InputStream requires a seekable stream

### ISSUE THREAD

**Issue by smbecker** [aws/aws-sdk-net#416]
I am attempting to use multi-part upload to upload a file. I am doing the chunking of the input content myself and initially the stream that I was providing to `UploadPartRequest.InputStream` was not seekable and that was causing an exception due to [this line](https://github.com/aws/aws-sdk-net/blob/6c3be79bdafd5bfff1ab0bf5fec17abc66c7b516/sdk/src/Core/Amazon.Runtime/Internal/Util/PartialWrapperStream.cs#L43) in PartialWrapperStream. I simply changed the return value of `CanSeek` to return `true` even though I still have the implementation of Seek throwing a NotSupportedException and everything worked as expected. It doesn't appear that Seek is ever called so I am unclear as to why the stream requires a seekable base stream.

**Comment by sstevenkang** [comment]
A seek-able stream must support `Length`, `SetLength`, `Position`, and `Seek` per msdn documentation [here](https://msdn.microsoft.com/en-us/library/system.io.stream.canseek(v=vs.110).aspx).  `PartialWrapperStream` does invoke `Length` and `Position` on the base stream in the same constructor scope.

**Comment by dave-yotta** [comment]
How is this guidance/question? Non seekable streams should be supported.
