### ISSUE TITLE
Cognito Developer Authenticated Identities

### ISSUE THREAD

**Issue by hashitha** [aws/aws-sdk-net#420]
I have a lambda that returns an identityId and a Token using GetOpenIdTokenForDeveloperIdentityRequest and it works fine.

Now I want to use this in app, This is the code I have so far which is giving me error 
Invalid login token. Can't pass in a Cognito token.

```
public class DeveloperAuthenticatedCredentials : CognitoAWSCredentials
    {
        const string PROVIDER_NAME = "login.test.myapp";
        const string IDENTITY_POOL = "[IDENTITY_POOL ]";
        static readonly RegionEndpoint REGION = RegionEndpoint.USEast1;
        private string Username = null;

        public DeveloperAuthenticatedCredentials(string username)
            : base(IDENTITY_POOL, REGION)
        {
            Username = username;
        } 

        public override async System.Threading.Tasks.Task<CognitoAWSCredentials.IdentityState> RefreshIdentityAsync()
        {
            
            //The backend has to send us back an Identity and a OpenID token
            Token token = getTockentFromLambda();

            string identityId = token .identityId;
            string token = token .token;

            var idState = new IdentityState(identityId, PROVIDER_NAME, token, false);
              
            return idState;
        } 
    }
```

Main method to login
```
public void login(){
    DeveloperAuthenticatedCredentials credentials = new DeveloperAuthenticatedCredentials("useremail");

    credentials.AddLogin("cognito-identity.amazonaws.com", "[Token]");
    credentials.GetCredentials();

}
```

**Comment by dfiverr** [comment]
That's strange, here is what my login code looks like (fully working):

    public void InvokeLogin(string email, string password)
    {
        //this is just for testing only, need to verify
        JSONObject j = new JSONObject(JSONObject.Type.OBJECT);
        j.AddField("email", email);
        j.AddField("password", password);

        Debug.Log(j.Print());

        Client.InvokeAsync(new Amazon.Lambda.Model.InvokeRequest()
        {
            FunctionName = "LambdAuthLogin",
            Payload = j.Print()

        },
        (responseObject) =>
        {
            if (responseObject.Exception == null)
            {
                Debug.Log(Encoding.ASCII.GetString(responseObject.Response.Payload.ToArray()) + "\n");

                JSONObject encodedString = new JSONObject(Encoding.ASCII.GetString(responseObject.Response.Payload.ToArray()));


                if (encodedString[0].b)
                {
                    IdentityId = Convert.ToString(encodedString[1].str);
                    Token = Convert.ToString(encodedString[2].str);

                    
                    Debug.Log("identityId was: " + IdentityId);
                    Debug.Log("token was: " + Token);
                    Debug.Log("logged in is true, proceed");
                }
                else
                {
                    Debug.Log("username or password was false");
                }

                //JSONObject result = encodedString.Count;


            }
            else
            {
                Debug.Log(responseObject.Exception + "\n");
            }
        }
        );
    }

**Comment by hashitha** [comment]
Login part work, it's the part where using the received token to access some resource like dynamodb or S3 that doesn't work for me. Did you manage to use the identity and token to access S3 or dynamodb?

**Comment by dfiverr** [comment]
@hashitha when you do something, make sure you use this type of structure

        using (var client = new AmazonS3Client(accesskey, secret, _S3Region))
        {
            client.PostObjectAsync(request, (responseObj) =>
            {
            
            });
         }

**Comment by hashitha** [comment]
where do you get the accesskey and secretkey? The InvokeLogin function you provided only returns identity and token

**Comment by dfiverr** [comment]
@hashitha you get that from your AWS account, you gotta generate one (where exactly I dont remember, maybe cognito)

**Comment by hashitha** [comment]
I think you have to generate temporary credentials using the identity and token. If you get it from the console they are not temporary and it defeats the purpose of using cognito

**Comment by dfiverr** [comment]
@hashitha Yes you need the identity and token for each user but you need to use the access key and a secret access key as well. Regardless, you have the right to your opinion to think that you don't. Good luck.

**Comment by hashitha** [comment]
Thanks @dfiverr, I am only saying because none of the blogs or documentation mentions anything about a secretkey and access key at the client

 [http://docs.aws.amazon.com/cognito/latest/developerguide/developer-authenticated-identities.html](url)

 [https://mobile.awsblog.com/post/Tx3E3NJURV1LNV1/Integrating-Amazon-Cognito-using-developer-authenticated-identities-An-end-to-en](url)

**Comment by Andreyul** [comment]
AmazonS3Client constructor accepts AWSCredentials parameter which is a base class for DeveloperAuthenticatedCredentials.
http://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/S3/MS3S3ctorAWSCredentials.html
```
public AmazonS3Client(
    AWSCredentials credentials
)
```

**Comment by hashitha** [comment]
That is what I am trying but I keep getting error

`Invalid login token. Can't pass in a Cognito token.`

when I set login

`credentials.AddLogin("cognito-identity.amazonaws.com", "eyJraWQiOiJ1cy1lYXN0LTExIiwidHlwIjoiSldTIiwiYWxnIjoiUlM1MTIifQ.eyJzdWIiOiJ1cy1lYXN0LTE6Y2NiMDQ2NDAtODM3YS00MzZjLTg4MTgtN2E4ZTdjZWYxOWMwIiwiYXVkIjoidXMtZWFzdC0xOmM4ZmUyMzE0LWU2ODgtNDg2NC1hZWQ2LWE4NjZhZmUyZWJlYyIsImFtciI6WyJhdXRoZW50aWNhdGVkIiwibG9naW4ucXVicy5wYWNzLnBdasdasdY3MucGFjc3NlcnZlcjp1cy1lYXN0LTE6YzhmZTIzMTQtZTY4OC00ODY0LWFlZDYtYTg2NmFmZTJlYmVjOmJtaXNlY3JldCJdLCJpc3MiOiJodHRwczovL2NvZ25pdG8taWRlbnRpdHkuYW1hem9uYXdzLmNvbSIsImV4cCI6MTQ3MDI0MTM4NSwiaWF0IjoxNDcwMjQxMDg1fQ.Oavnwsba-D-lU-bbE-8qkgdADAv6l824Ny-trM6nZ7J84HacEqDukHB3sjFvo4JlmAYNKqmPh7i7ZKsIoNS6j9J_NBQVdNjedoNE7lOqsi5h-fCKk3mOka0bMGYpu8GUUY-34dRMIX0_7u7l6rWsxxiTHPdKFhnzO0m0mQ7vwZa0kA0mwjE5UWMMVu2-emhuQDRJCCTyppFkGBgNVpYeODL0o2NOVOSAxupJ6b3XUZGIN-8FjPvhrYqxzffL-O0sIhnJSKbIPleOr0kri9dTVy01yhChllpXftSv9FvuDw0_89450j_quL68UixBv935Oni9XyPvtKxydH4GEfpQ_A");`

if I don't set it then it works but I get credentals to unauth role

**Comment by Andreyul** [comment]
```
public class DeveloperAuthenticatedCredentials : CognitoAWSCredentials
{
    private string developerProviderName;
    private string backendUrl;
    private string gameCenterPlayerId;

    public DeveloperAuthenticatedCredentials(string identityPoolId, RegionEndpoint region, string developerProviderName, string backendUrl)
        : base(identityPoolId, region)
    {
        this.developerProviderName = developerProviderName;
        this.backendUrl = backendUrl;
    }

    public void SetGameCenterPlayerId(string gameCenterPlayerId)
    {
        AddLogin(developerProviderName, string.Empty);
        this.gameCenterPlayerId = gameCenterPlayerId;
        ClearCredentials();
    }

    public void RemoveGameCenterPlayerId()
    {
        RemoveLogin(developerProviderName);
        this.gameCenterPlayerId = string.Empty;
        ClearCredentials();
    }

    protected override IdentityState RefreshIdentity()
    {
        // call backend
        ...
        
        return new IdentityState(<identityId from backend>, developerProviderName, <token from backend>, false);
    }
}

private void Test()
{
    const string MyProviderName = "login.test.myapp";
    var credentials = new DeveloperAuthenticatedCredentials(
        "<pool id>",
        RegionEndpoint.USEast1,
        MyProviderName,
        "https://xxxxxxxxxx.execute-api.us-east-1.amazonaws.com/gamecenter/login");

    credentials.SetGameCenterPlayerId("G:1234567890");

    var s3Client = new AmazonS3Client(credentials, RegionEndpoint.USEast1);
    s3Client.ListBucketsAsync(OnListBucketsComplete, new AsyncOptions() { ExecuteCallbackOnMainThread = true });
}

private void OnListBucketsComplete(AmazonServiceResult<ListBucketsRequest, ListBucketsResponse> responseObject)
{
    Debug.Log("OnListBucketsComplete " + responseObject);
}
```

**Comment by hashitha** [comment]
Thanks @Andreyul  got it working using your code. It seems I was using 
`public override async Task<IdentityState> RefreshIdentityAsync()`
instead of 
`protected override IdentityState RefreshIdentity()`

**Comment by kobechenyang** [comment]
I followed the similar steps to create my credentials. But I am keep getting "Invalid login token. Issuer doesn't match providerName" error. I opened up an ticket here:  https://github.com/aws/aws-sdk-net/issues/1251 Do you guys have any insight?
