### ISSUE TITLE
Unity Dynamodb BatchWrite using SDK

### ISSUE THREAD

**Issue by madangosain** [aws/aws-sdk-net#421]
```
BatchWrite<Score> batchWrite = Context.CreateBatchWrite<Score>();
batchWrite.AddPutItems(scoreList);
```

When using Batch Write using .Net unity high level sdk, do I need to be concerned about 
1) UpdateItem/PutItem - whether my requests are update or new entry, it'll work fine right?
2) 25 batch requests limit? Does SDK automatically take care of this limit if my scorelist contains more than 100 items. Or Do I need to break it into chunks of 25 max?

**Comment by PavelSafronov** [comment]
1. The BatchWrite operation only supports Put and Delete operations. There is no way to do an Update as part of BatchWrite.
2. The Context object will take care of batching the requests into lots of 25, you don't have to do this.

**Comment by madangosain** [comment]
1. Somehow updates are working perfectly with Batch Write using SDK. My batchwrite list contains new and updated elements. Everytime I test this in unity editor on mac, it successfully updates the existing values and write/creates new values in dynamo db. What am I missing here? Is it not reliable or guaranteed ?
2. Verified this is working correctly, thanks

**Comment by PavelSafronov** [comment]
The confusion here has to do with the difference between DynamoDB's UpdateItem and PutItem operations. [PutItem](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_PutItem.html) replaces an entire item with the passed-in data, while [UpdateItem](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html) edits an item's attributes. UpdateItem therefore leaves the existing attributes alone if they are not specified in the request. This is not supported for BatchWrite, so you are not updating an existing item, you are replacing it. If an existing item has attributes that you are not specifying during BatchWrite, the PutItem operation will end up removing those.

**Comment by madangosain** [comment]
Thank you for the quick response. You are absolutely correct.
