### ISSUE TITLE
.NetCore support

### ISSUE THREAD

**Issue by rutmir** [aws/aws-sdk-net#422]
Hello, in aws-sdk-net/sdk/src/Core/Amazon.Util/_pcl/CryptoUtil.pcl.cs file you are using PCLCrypto in HMACSign method, but getter in PCLCrypto.WinRTCrypto.MacAlgorithmProvider not implemented for PCL environment and cannot run on NetCore.App. Do you plan to work on this problem?

**Comment by normj** [comment]
I'm assuming you are using version 3.2.5-beta of the AWS SDK. If that is the case you shouldn't be picking up the PCL version of the SDK. The NuGet package contains a separate netstandard 1.5 version of the SDK which is what should be resolved to when you add the reference to a netcore project. I have heard a couple people have similar issues like this. Is it possible for you to share your project.json file to help us figure out why sometimes NuGet resolves to the PCL version instead of the netstandard version.

**Comment by rutmir** [comment]
{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "AWSSDK.S3": "3.1.8.1",
    "Newtonsoft.Json": "9.0.1",
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.0"
  },
  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },
  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true,
    "debugType": "portable"
  },
  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },
  "publishOptions": {
    "include": [
      "wwwroot",
      "web.config",
      "docker-compose.yml",
      "docker-compose.debug.yml",
      "Dockerfile.debug",
      "Dockerfile",
      "client.json",
      "settings.json"
    ]
  },
  "scripts": {
    "postpublish": [
      "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%"
    ]
  }
}

**Comment by normj** [comment]
You are specifying 3.1.8.1 of the AWSSDK.S3 package. Netcore standard support is currently in our beta versions with the latest version being 3.2.5-beta.

https://www.nuget.org/packages/AWSSDK.S3/3.2.5-beta

**Comment by rutmir** [comment]
yes, it work thank you.
