### ISSUE TITLE
DefaultTimeout property missing in TransferUtilityConfig 

### ISSUE THREAD

**Issue by fabiod822c** [aws/aws-sdk-net#423]
Hello,
I'm using AWSSDK.S3 (.NET) version: 3.1.0.0 and I've downloaded the package from NuGet,
but I don't find property **DefaultTimeout** as described in documentation (http://docs.aws.amazon.com/AmazonS3/latest/dev/HLuploadFileDotNet.html).

Amazon.S3.Transfer.TransferUtilityConfig config = new TransferUtilityConfig();
config.**DefaultTimeout**

Can you verify?
Thanks.

**Comment by Singh400** [comment]
https://forums.aws.amazon.com/thread.jspa?threadID=142429

**Comment by PavelSafronov** [comment]
The forum post linked above is correct. Here is the relevant part:

> DefaultTimeout is only available in .NET 3.5 version of the SDK. It's not supported in the .NET 4.5 version of the SDK. In 4.5, you can construct an S3 client (AmazonS3Client) having an AmazonS3Config with the Timeout property set and pass it to the TransferUtility constructor to achieve the same effect.
