### ISSUE TITLE
Limit an upload filesize with a Pre-signed URL 

### ISSUE THREAD

**Issue by hequs** [aws/aws-sdk-net#424]
I'm using S3 to store users' files on my website. In order to optimize server load, I've configured a direct file upload from browser for my users. The flow is the following:
1) user calls the server API method to retrieve a Pre-singed Upload Url
2) user uploads some file to AWS S3 directly with the url
3) user call another API method to notify server, that the upload was finished

I want to protect my S3 storage from obusing, so I need the way to limit the maximum file size. Unfortunately, I have not found a way to do this via .Net SDK.

I've read about restriction polices for HTTP POST (http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-post-example.html). Can it be applied on a Pre-signed Url flow. 

Regards, Vadim.

**Comment by PavelSafronov** [comment]
I don't believe your use-case is supported for pre-signed urls, but take a look at [Authenticating Requests in Browser-Based Uploads Using POST ](http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-UsingHTTPPOST.html). This should cover your case and there is built-in support for limiting the upload size (along with other options) using a [POST policy](http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-HTTPPOSTConstructPolicy.html).

**Comment by tejasmanohar** [comment]
Is the top answer here correct/endorsed?

https://stackoverflow.com/questions/25991275/limit-size-of-objects-while-uploading-to-amazon-s3-using-pre-signed-url

>>>The V4 signing protocol offers the option to include arbitrary headers in the signature. See: http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html So, if you know the exact Content-Length in advance, you can include that in the signed URL. Based on some experiments with CURL, S3 will truncate the file if you send more than specified in the Content-Length header. Here is an example V4 signature with multiple headers in the signature http://docs.aws.amazon.com/general/latest/gr/sigv4-add-signature-to-request.html

**Comment by janacm** [comment]
For any other wanderers that end up on this thread - if you set the Content-Length attribute when sending the request from your client, there a few possibilities:

1. The Content-Length is calculated automatically, and S3 will store up to 5GB per file
2. The Content-Length is manually set by your client  
2a - The Content-Length matches your actual file size and S3 stores it.
2b - The Content-Length is less than your actual file size, so S3 will truncate your file to fit it.
2c - The Content-Length is larger than your actual file size, and you will receive a 400 Bad Request

In any case, a malicious user can override your client and manually send a HTTP request with whatever headers they want, including a much larger Content-Length than you may be expecting. Signed URLs do not protect against this! The only way is to setup an POST policy. Official docs here:  https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-HTTPPOSTConstructPolicy.html

More details here: https://janac.medium.com/sending-files-directly-from-client-to-amazon-s3-signed-urls-4bf2cb81ddc3?postPublishedType=initial

Alternatively, you can have a Lambda that automatically deletes files that are larger than expected.

**Comment by orekav** [comment]
> For any other wanderers that end up on this thread - if you set the Content-Length attribute when sending the request from your client, there a few possibilities:

@janacm 

Thanks for sharing the link to your post but it seems it is not public.

![Screenshot 2024-02-28 at 11 50 06](https://github.com/aws/aws-sdk-net/assets/15952456/4af22ba8-aaa0-4021-97c3-e7cae9baa6ae)

**Comment by janacm** [comment]
> > For any other wanderers that end up on this thread - if you set the Content-Length attribute when sending the request from your client, there a few possibilities:
> 
> @janacm
> 
> Thanks for sharing the link to your post but it seems it is not public.
> 
> ![Screenshot 2024-02-28 at 11 50 06](https://private-user-images.githubusercontent.com/15952456/308536775-4af22ba8-aaa0-4021-97c3-e7cae9baa6ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NTYwNjgsIm5iZiI6MTcwOTc1NTc2OCwicGF0aCI6Ii8xNTk1MjQ1Ni8zMDg1MzY3NzUtNGFmMjJiYTgtYWFhMC00MDIxLTk3YzMtZTdjYWU5YmFhNmFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDIwMDkyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5MDE5MzkyOTA3MzgwYWQ1MDk4MmM4MjQ3NjgwZTJmNjUxODMwYWIxYjlkNWFlZTA5MDA1OWNjMmNmNDg4YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SO2GIAHTMWVk55bYfr93XnM78oDHiu4JLuznHVkiB6s)
> 
> This one is free to read https://zaccharles.medium.com/s3-uploads-proxies-vs-presigned-urls-vs-presigned-posts-9661e2b37932

Hey here's that link without paywall: https://towardsaws.com/sending-files-directly-from-client-to-amazon-s3-signed-urls-4bf2cb81ddc3?sk=88c25bcd8689b40a4fd4045d4cf93eff
