### ISSUE TITLE
TransferUtility - DownloadAsync - PCL

### ISSUE THREAD

**Issue by Magic73** [aws/aws-sdk-net#429]
It doesn't work :)
TransferUtilityDownloadRequest need a property FilePath where I have to set the local destination file path (using PCLStorage library).

I have to specify the full path (from the root) beacuse inside DownloadCommand.async.cs there is this check:

```
           var file = await PCLStorage.FileSystem.Current.GetFileFromPathAsync(this._request.FilePath).ConfigureAwait(false);
                        if (file != null)
                            await file.DeleteAsync().ConfigureAwait(false);
```

and GetFileFromPathAsync request a full path. OK... 

but then, there is a call to response.WriteResponseStreamToFileAsync, where inside there is a new call (file GetObjectResponse.pcl.cs):

```
await CreateDirectory(filePath).ConfigureAwait(continueOnCapturedContext: false);
```

and inside of CreateDirectory, we have:

```
        var directoryName = Path.GetDirectoryName(filePath);
        var folder = await PCLStorage.FileSystem.Current.LocalStorage
            .CreateFolderAsync(directoryName, PCLStorage.CreationCollisionOption.OpenIfExists)
            .ConfigureAwait(false);
```

and here the Exception :)

CreateFolderAsync request a local path, but filePath is a full path.

If I change the property FilePath of the TransferUtilityDownloadRequest with a relative path, I get the exception when calling PCLStorage.FileSystem.Current.GetFileFromPathAsync, beacuse this function want a full path.

**Comment by Magic73** [comment]
I fixed DownloadCommand.async.cs adding this line:

                        string localFilePath = this._request.FilePath.Replace(PCLStorage.FileSystem.Current.LocalStorage.Path, "");

just before:

if (retries == 0)

and then, changing the calls to WriteResponseStreamToFileAsync into

await response.WriteResponseStreamToFileAsync(**localFilePath**, false, cancellationToken)
                                .ConfigureAwait(continueOnCapturedContext: false);

**Comment by Magic73** [comment]
The solution that I proposed doesn't work on iOS and Android. So, it is is an issue with the UWP platform.

How could be solved properly?

**Comment by sunchunqiang** [comment]
Hi @Magic73 

Did you encounter the issue only on UWP platform if you don't modify DownloadCommand.async.cs? 

According to my test, the API TransferUtility.DownloadRequest work on iOS and Android platform by using a full path for TransferUtilityDownloadRequest.FilePath.

**Comment by Magic73** [comment]
Long time passed, let me check..

**Comment by muellerfr** [comment]
This issue has been closed because it has not had recent activity. If you still need help, please open a new issue.
