### ISSUE TITLE
SimpleDB on latest SDK

### ISSUE THREAD

**Issue by galvesribeiro** [aws/aws-sdk-net#431]
Hello guys! 

I dont see docs on how to use SimpleDB on the latest SDK only on the old one. Is it going to be supported or is deprecated in .Net SDK?

Thanks

**Comment by PavelSafronov** [comment]
SimpleDB is supported with the latest SDK.

If you are looking at V2 documentation, then those instructions are still perfectly valid.

If you are looking at V1 documentation, they'll mostly work, though there were some minor changes like removing *.WithPROPERTY* methods and *.OPERATIONResult* properties from service responses. You can see a comprehensive list of V1-to-V2 changes in [this migration guide](http://docs.aws.amazon.com/AWSSdkDocsNET/V2/DeveloperGuide/migration-v2-net-sdk.html).

**Comment by galvesribeiro** [comment]
Thanks for the promptly reply @PavelSafronov! I'll have a look on those :)
