### ISSUE TITLE
ETag/Version handling on Low level APIs and conditional batch

### ISSUE THREAD

**Issue by galvesribeiro** [aws/aws-sdk-net#432]
Hello guys.

In the Object Model there is a way to make the operations check for the version/etag by simply set a specific attribute to the C# class and the context will deal with the value however, I dont see a way to deal with it while using the C# lower APIs. Is there a way to do that?

Another point are WriteBatch requests... There are only PUT and Delete operations Supported? Also there is no way to make an item in the batch conditional. How can we make that? Thanks

**Comment by PavelSafronov** [comment]
The version check that the DynamoDBContext supports is called [Optimistic Locking](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBContext.VersionSupport.html). This can be accomplished with the low-level API by setting [Update.Expected](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html#DDB-UpdateItem-request-Expected) or [Update.ConditionExpression](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html#DDB-UpdateItem-request-ConditionExpression) fields with the values you are expecting, then catching the possible exception if the values do not match.

You are correct, WriteBatch does not support Update or conditionals. This is a limitation of the underlying [BatchWriteItem service operation](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchWriteItem.html), and as such there is no way to make the DynamoDBContext's BatchWrite support these cases. If you need either of these features, you'll need to issue individual (non-batch) requests.

**Comment by galvesribeiro** [comment]
I end up by doing the conditional expression as you suggested to handle the version.

Regarding the WriteBatch, its a shame it isn't supported by DynamoDB. This is very useful and is supported on other NoSQL on-premises and Cloud Services Providers. Will try to implement a "transaction-like" mechanism to workaround this limitation.

Thanks again for the replies @PavelSafronov

**Comment by PavelSafronov** [comment]
If you'd like, you can post a feature request on the [DynamoDB forum](https://forums.aws.amazon.com/forum.jspa?forumID=131) for the WriteBatch operation.

**Comment by galvesribeiro** [comment]
Tried with no luck :(
![image](https://cloud.githubusercontent.com/assets/4714040/17451787/ef7fa590-5b3f-11e6-8040-9fa3cacdf4c6.png)

**Comment by galvesribeiro** [comment]
@PavelSafronov regarding the ETag we are having a problem...

Imagine the following update expression:

``` C#
"SET ETag = ETag + :increment"
```

Where `:increment` is set to 1. So basically I'm trying to while upserting, increment the ETag atomically. I get an error while executing it that says the element ETag doesn't exist. Indeed there is no record in the DB.

So, do you have an example on how to mimic the behavior of the `DynamoDBVersion` behavior while using the low-level APIs?

Thanks

**Comment by PavelSafronov** [comment]
[This blog post](https://blogs.aws.amazon.com/net/post/TxZQM7VA9AUZ9L/DynamoDB-Series-Expressions) has an example of incrementing an attribute ("wins") even if it doesn't exist. I believe you need to use the [ADD](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.Modifying.html#Expressions.Modifying.UpdateExpressions.ADD) action instead of SET.
