### ISSUE TITLE
AWS usage of SQLite PCL causes problem on Android N (Xamarin)

### ISSUE THREAD

**Issue by chracing** [aws/aws-sdk-net#436]
Android Xamarin app using AWS Mobile Analytics is using this SDK that pulls in SQLite PCL from Microsoft that has not had recent updates. This PCL has issues with Android N as it is using private system apis via invoke. This is blocked on Android N. Resulting in a error message to the user of the application. This problem is well documented about SQLite api usage on Android N.

**Comment by karthiksaligrama** [comment]
we are aware of this problem, we will update when we have a fix

**Comment by karthiksaligrama** [comment]
fixed with 3.3.1.0 version of Mobile Analytics
