### ISSUE TITLE
ALB support for .NET Core

### ISSUE THREAD

**Issue by ievgeniiVlasyuk** [aws/aws-sdk-net#438]
Recently, ALB was announced and integration with ECS was introduced. 
Are there any plans of supporting it on 3.2.* version of sdk?
As far as I see, 3.1.* version already has it [0ac61ae](https://github.com/aws/aws-sdk-net/commit/0ac61aed26cb43139faf652184114a6a647bfa8c)

**Comment by steveataws** [comment]
We've only being doing every-so-often periodic refreshes of the 3.2 beta version of the SDK, so new service updates in this branch do lag behind the mainline 3.1 version. It will get added but I don't have an ETA for the next refresh at the moment.

**Comment by normj** [comment]
We pushed out version 3.2.7 today that contains this service.
