### ISSUE TITLE
unity s3 get HttpErrorResponseException

### ISSUE THREAD

**Issue by NerminShawkat** [aws/aws-sdk-net#440]
I'm using unity sdk and running s3example scene, only Post Object is working 
when i click all other buttons from the editor or android I get

HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
Amazon.Runtime.Internal.UnityWwwRequest.EndGetResponse (IAsyncResult asyncResult)
Amazon.Runtime.Internal.HttpHandler`1[System.String].GetResponseCallbackHelper (System.Object state)
UnityEngine.Debug:LogException(Exception)
Amazon.Runtime.Internal.Util.UnityDebugLogger:Error(Exception, String, Object[])
Amazon.Runtime.Internal.Util.Logger:Error(Exception, String, Object[])
Amazon.Runtime.Internal.ErrorHandler:ProcessException(IExecutionContext, Exception)
Amazon.Runtime.Internal.ErrorHandler:InvokeAsyncCallback(IAsyncExecutionContext)
Amazon.Runtime.Internal.PipelineHandler:AsyncCallback(IAsyncExecutionContext)
Amazon.Runtime.Internal.PipelineHandler:InvokeAsyncCallback(IAsyncExecutionContext)
Amazon.S3.Internal.AmazonS3ResponseHandler:InvokeAsyncCallback(IAsyncExecutionContext)
Amazon.Runtime.Internal.PipelineHandler:AsyncCallback(IAsyncExecutionContext)
Amazon.Runtime.Internal.PipelineHandler:InvokeAsyncCallback(IAsyncExecutionContext)
Amazon.Runtime.Internal.Unmarshaller:InvokeAsyncCallback(IAsyncExecutionContext)
Amazon.Runtime.Internal.PipelineHandler:AsyncCallback(IAsyncExecutionContext)
Amazon.Runtime.Internal.PipelineHandler:InvokeAsyncCallback(IAsyncExecutionContext)
Amazon.Runtime.Internal.RedirectHandler:InvokeAsyncCallback(IAsyncExecutionContext)
Amazon.Runtime.Internal.PipelineHandler:AsyncCallback(IAsyncExecutionContext)
Amazon.Runtime.Internal.PipelineHandler:InvokeAsyncCallback(IAsyncExecutionContext)
Amazon.Runtime.Internal.HttpHandler`1:GetResponseCallbackHelper(Object)

I also tried  to set asyncoptions "new AsyncOptions { ExecuteCallbackOnMainThread = false }", but I'm still getting the same exception

**Comment by karthiksaligrama** [comment]
Can you enable logs and tell me what's the error message you are getting in the logs. Also what version of sdk are you using?

**Comment by NerminShawkat** [comment]
thank you it's working now, I wasn't using the right s3 region

**Comment by artourky** [comment]
@NerminShawkat Hey, I've the exactly opposite problem every other buttons work except the **Post Object** and I get this error
```
Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
```

**Comment by NerminShawkat** [comment]
@artourky  and the region was the problem?

**Comment by artourky** [comment]
@NerminShawkat I have the bucket configured for "eu-central-1" and I changed it in the _S3Example.cs_ as well still, It doesn't work.

**Comment by artourky** [comment]
@NerminShawkat as It turns out, It was indeed the **Region**, What I did was that I changed the **Region** at the Start of the script to match the Bucket  I've created on AWS

```csharp
string S3Region = RegionEndpoint.EUCentral1.SystemName;
private RegionEndpoint _S3Region
{
    get { return RegionEndpoint.GetBySystemName(S3Region); }
}
```
So adding the **Region** field inside the **PostObjectRequest()** so it became
```csharp
var request = new PostObjectRequest()
{
	Bucket = S3BucketName,
	Key = SampleFileName,
	InputStream = stream,
	CannedACL = S3CannedACL.Private,
	Region = _S3Region
};
```
It worked.
I guess the default **Region** inside the **PostObjectRequest()** is _us-west-2_
