### ISSUE TITLE
AWS Security Token Service 3.1.4.5 - Assume Roles for greater than an hour

### ISSUE THREAD

**Issue by MarkDordoy-JustEat** [aws/aws-sdk-net#441]
Hello

AWS recently released support for assuming a role for up to 12 hours. The current release version currently still only supports up to 1 hour, and will through an exception is anything greater than this is passed. 

How long will it be until it is able to assume roles for up to 12 hours? 

Thanks

**Comment by PavelSafronov** [comment]
No, there is no way right now to get role sessions for the SDK longer than an hour. Longer sessions are console only.
