### ISSUE TITLE
AmazonSimpleSystemsManagementClient.ListDocumentsAsync not returns all documents

### ISSUE THREAD

**Issue by guitarrapc** [aws/aws-sdk-net#444]
Description
----
ListDocumentsAsync() Method seems missing response for several documents.

But I can get document with GetDocumentAsync().

```cs
await client.GetDocumentAsync("AWS-RunShellScript");
```

![image](https://cloud.githubusercontent.com/assets/3856350/17998931/b9cd442a-6bb1-11e6-85d1-ac71e7cf4a5f.png)

Is this bug or as expected behavior?

Repro
----

When following.
![image](https://cloud.githubusercontent.com/assets/3856350/17998882/708fc06c-6bb1-11e6-9182-8bfdbd5594cb.png)

Run this

```cs
    var region = RegionEndpoint.APNortheast1;
    var client = new Amazon.SimpleSystemsManagement.AmazonSimpleSystemsManagementClient(region);
    await client.ListDocumentsAsync();
```

Missing Platform : Linux document and else.

![image](https://cloud.githubusercontent.com/assets/3856350/17998837/42104bee-6bb1-11e6-8164-08405c440c4a.png)

While AWSPowerShell returns all documents.

```powreshell
PS > Get-SSMDocumentList

Name                              Owner  PlatformTypes
----                              -----  -------------
AWS-ConfigureCloudWatch           Amazon {Windows}
AWS-ConfigureWindowsUpdate        Amazon {Windows}
AWS-FindWindowsUpdates            Amazon {Windows}
AWS-InstallApplication            Amazon {Windows}
AWS-InstallMissingWindowsUpdates  Amazon {Windows}
AWS-InstallPowerShellModule       Amazon {Windows}
AWS-InstallSpecificWindowsUpdates Amazon {Windows}
AWS-JoinDirectoryServiceDomain    Amazon {Windows}
AWS-ListWindowsInventory          Amazon {Windows}
AWS-RunPowerShellScript           Amazon {Windows}
AWS-RunShellScript                Amazon {Linux}
AWS-UpdateEC2Config               Amazon {Windows}
AWS-UpdateSSMAgent                Amazon {Windows, Linux}
```

**Comment by PavelSafronov** [comment]
The response you receive from the ListDocuments (or ListDocumentsAsync) operation contains a NextToken field. If this field is non-empty, you need to pass this token into another call of ListDocuments (or ListDocumentsAsync) to get the next page of items. For instance:
```
var request = new ListDocumentsRequest();
do
{
    var response = client.ListDocuments(request);
    request.NextToken = response.NextToken;
} while (!string.IsNullOrEmpty(request.NextToken));
```

**Comment by guitarrapc** [comment]
What a shame:) Yes, definitely you are collect. Is that any reason default restricted up to 10 results? It seems like each response data is small enough to expand it to 50, the maximum in current.

**Comment by guitarrapc** [comment]
Is there any way to get Command History through SDK? I couldn't  find any...

http://docs.amazonaws.cn/sdkfornet/v3/apidocs/items/SimpleSystemsManagement/NSimpleSystemsManagementModel.html

**Comment by PavelSafronov** [comment]
I'll ask the service team about the default page size. Resolving the issue for now.
