### ISSUE TITLE
Cognito identityPoolId fails to satisfy regex.

### ISSUE THREAD

**Issue by tsharju** [aws/aws-sdk-net#445]
I have a weird problem. Always when I try to use Cognito credentials I get `'identityPoolId' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w-]+:[0-9a-f-]+`. The poolId I get from AWS console does not match that regex. My poolId is something like `us-east-1_xxxxxx`.

Is the SDK incompatible with the current AWS Cognito API version or something?

I'm using the latest SDK for Unity.

**Comment by tsharju** [comment]
Ah. Looks like I was using the *User PoolId* instead of *Identity PoolId*. The SDK works fine.

**Comment by dash7ou** [comment]
:-1:

**Comment by Lelouch-Lamperouge-Code-Geass** [comment]
@tsharju How did you solve the problem? 

Had same issue.
https://stackoverflow.com/questions/69958161/whats-the-equivalent-of-cognitoidentitycredentials-for-user-pool
