### ISSUE TITLE
ListPartsRequest.PartNumberMarker is a string, but ListPartsResponse.NextPartNumberMarker is an int?

### ISSUE THREAD

**Issue by DaveVdE** [aws/aws-sdk-net#447]
Why are these different types? I'm probably going to get away with it by just adding `.ToString()` but I think this needs some polish.

**Comment by PavelSafronov** [comment]
This was a decision made in the earliest versions of the SDK and it matches the [service documentation](http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadListParts.html). We've maintained the same types going forward to avoid making a breaking change, so unfortunately this does mean these types will stay as-in for the foreseeable future.
