### ISSUE TITLE
AWS Explorer - Unable to see S3 Topic Bucket Notification filters

### ISSUE THREAD

**Issue by damiangreen** [aws/aws-sdk-net#452]
Consider this code:

```
var topicConfigurations = new List<TopicConfiguration>
{
    new TopicConfiguration
    {
        Events = new List<EventType>
        {
            new EventType("s3:ObjectCreated:*")
        },
        Filter = new Filter
        {
            S3KeyFilter = new S3KeyFilter
            {
                FilterRules = new List<FilterRule>
                {
                    new FilterRule("suffix", ".zip"),
                }
            }
        },
        Topic = topicArn
    }
};
var request = new PutBucketNotificationRequest
{
    BucketName = _configuration.S3BucketName,
    TopicConfigurations = topicConfigurations,
};

return await GetClient().PutBucketNotificationAsync(request);
```

If I go to AWS Explorer on the S3 Bucket to see if the filter has been created correctly I have no way of seeing the filter rules. I appreciate this may be a feature request.

![s3-question](https://cloud.githubusercontent.com/assets/1592820/18507296/b1b2d9ac-7a67-11e6-905c-3ea3102d37d7.PNG)

**Comment by PavelSafronov** [comment]
Sorry, not sure I'm following yet. The screenshot shows that there is the "s3:ObjectCreated:*" notification created, exactly what the code is doing. You also mention "s3:ObjectRemoved:*" filter, but that's not what is shown in the code or the screenshot.

Can you clarify what you are attempting to do, what is happening, and what you are expecting to happen instead?

**Comment by damiangreen** [comment]
ah sorry. I can't see the filter file. i.e.  "suffix", ".zip"

**Comment by normj** [comment]
I agree, it would be a good feature to add. I'll add that to our backlog.

**Comment by vellozzi** [comment]
This feature request has been added to our backlog.
