### ISSUE TITLE
Server side encryption support when using S3FileInfo objects

### ISSUE THREAD

**Issue by ocdavison** [aws/aws-sdk-net#453]
The S3DirectoryInfo and S3FileInfo objects made it quite easy to transition from traditional Windows file storage to AWS S3. However, we would really like to take advantage of S3's server side encryption, but don't see a way to do so using the S3FileInfo object. Is this possible? If not, mind adding it as a feature request? Thanks!!!

**Comment by PavelSafronov** [comment]
This is not currently supported, but we will add this request to our backlog.
