### ISSUE TITLE
ios applicationWillTerminate (is/how is OnApplicationQuit handled ?)

### ISSUE THREAD

**Issue by xddregan** [aws/aws-sdk-net#454]
update:
Maybe a clearer version of question is 
Does the aws Unity SDK handle OnApplicationQuit on IOS (does it clean up all threads etc. ) ?
I don't see it referenced in the Source (But i'm not that familiar with source) and it may be handled in a different way. 

Any feedback would be useful as if I can't resolve issue, I plan to replace sdk with HTTP->API Gateway interface which is quite a big change. 

thanks
Dominick 

----------
#Since adding Aws Unity Sdk <aws-sdk-unity_3.1.74.0> to mobile project primarily to access DynamoDB. Apple is reporting a lot of crashes when applicationWillTerminate is called. The crashes are somewhat random. Sometimes in Unity's ~MemoryPool and sometimes in RuntimeCleanup and occasionally in some IOS static destructors. 
I was wondering how Aws Unity Sdk handles applicationWillTerminate on IOS ?

 I see that there are still threads that are waiting on GetTable -- even after Unity App is destroyed
<img width="576" alt="screenshot" src="https://cloud.githubusercontent.com/assets/22261395/18609941/53d6d4ec-7cc3-11e6-8cd7-71561cd59c06.png">
Also some threads waiting on semaphoe_wait_trap. 

Is there a way to cleanup the Aws threads/waits on applicationWillTerminate

The issue isn't user facing as it happens as shutdown, but it's still important as it's reported to Apple as crash 

The released verison of apps are using aws-sdk-unity_3.1.74.0 

any help or guidance on how to address this is appreciated
thanks
Dominick

**Comment by karthiksaligrama** [comment]
The SDK creates the threads and leaves it for the system to collect them when the application terminates. We don't handle applicationWillTerminate explicitly on any platform
