### ISSUE TITLE
Deploy ASP.NET Core application to Windows 2012 v1.2.0

### ISSUE THREAD

**Issue by mtschneiders** [aws/aws-sdk-net#455]
I'm trying to deploy an ASP.NET Core App to a windows instance using the AWS plugin for Visual Studio, but without success. 

The outputs indicates it succeeded, but the actual deploy didn't happen. 
When I connect to the instance, the files in the folder "C:\inetpub\AspNetCoreWebApps\app" were not replaced and there are no new files in the "C:\Program Files\Amazon\ElasticBeanstalk\logs" folder

**Visual Studio Output:**

    upload complete
    creating new version 'v20160917182527' for application xyz
    requesting update of environment 'xyz' with application version 'v20160917182527'
    Publish to AWS Elastic Beanstalk environment 'xyz' completed successfully

**Elastic beanstalk Events:** 

    Deploying new version to instance(s).
    New application version was deployed to running EC2 instances.
    Environment update completed successfully.

**Instance Config:** 

    64bit Windows Server 2012 R2 v1.2.0 running IIS 8.5

I've tried looking at the Event Viewer, but couldn't see anything related there.
One other thing that I noticed is that the EB Health indicator is always grey for this environment.

Is there any way to troubleshoot this?

**Comment by normj** [comment]
Can you take look at the log files in C:\cfn\log, that might give more indication what is going wrong. In particular the cfn-init file.

**Comment by mtschneiders** [comment]
Thanks for the answer @normj.

I noticed that if I restart the EC2Config service, the next deploy works, but not the one after that.
It seems that the deploy process itself leaves the service in an invalid state.

About the cnf-init log file, there are some backup errors ocurring, this is one of them:
[ERROR] Could not move c:\cfn\cfn-hup.conf.bak2 to c:\cfn\cfn-hup.conf.bak
[WARNING] Error restoring backup file c:\cfn\cfn-hup.conf.bak: Could not rename c:\cfn\cfn-hup.conf.bak2: [Error 183] Cannot create a file when that file already exists

In the cfn-init-cmd log file, the following error occurs:
[INFO] Config Hook-EnactAppDeploy
[INFO] ============================================================
[INFO] Command hooks
[INFO] -----------------------Command Output-----------------------
[INFO] 	'HooksExecutor.exe' is not recognized as an internal or external command,
[INFO] 	operable program or batch file.
[INFO] ------------------------------------------------------------

**Comment by normj** [comment]
Thanks for the info, I'll check in with the Beanstalk team to see if that have seen that behavior before.

**Comment by normj** [comment]
Looks like this is an issue with the Beanstalk service. Can you open up an issue on the Beanstalk forums which that team monitors and will be able to help you.

https://forums.aws.amazon.com/forum.jspa?forumID=86

**Comment by mtschneiders** [comment]
Opened up an issue on the Beanstalk forum as you suggested: [Link](https://forums.aws.amazon.com/thread.jspa?threadID=240815)

Thanks for the help.

**Comment by normj** [comment]
Closing this since the issue will now be tracked on the Beanstalk Forums

**Comment by happylime** [comment]
Hi,
I have similar issue. Did you manage to resolve this?
Thanks!

**Comment by mtschneiders** [comment]
Nope, I tried seeking for help on the Beanstalk forums, but it didn't work out.

**Comment by ricardojohnny** [comment]
Hi, 
I have similar issue. Did you manage to resolve this?

**Comment by p-doyle** [comment]
I am having the same issue as well.  In cfn-init-cmd.txt it says both HooksExecutor.exe and TailLogs.exe are "not recognized as an internal or external command, operable program or batch file."  Any ideas?

**Comment by nbear99** [comment]
If you got the message, please check your AMI image. If you use a custom AMI, please test with official AMI first.
```
[INFO] 'HooksExecutor.exe' is not recognized as an internal or external command,
[INFO] operable program or batch file.
```
