### ISSUE TITLE
"MD5 hash mismatch for message id" for empty messages.

### ISSUE THREAD

**Issue by Neustart** [aws/aws-sdk-net#457]
Hi guys,
I faced with next problem:
I put message from AWS CLI which consist of one space by next command:
```
aws sqs send-message --queue-url https://sqs.us-west-2.amazonaws.com/77... --message-body " " --delay-seconds 0
```
After that I have an exception when trying to get this message from the queue from my c# code:
Code: 
```
ReceiveMessageResponse receiveMessageResponse = _objClient.ReceiveMessage(receiveMessageRequest);
```
Exception: 
```
{"MD5 hash mismatch for message id 5ea584f8-607a-4110-963b-7cc015ce1d05"}
```
I want to delete problem messages like this from my queue, but I can't do this, because can't achieve ReceiptHandle from receiveMessageResponse variable, because of exception

**Comment by PavelSafronov** [comment]
The .NET SDK does not properly handle all-whitespace message bodies or message attributes. You would need to delete the problem messages like this using a different tool, like the AWS CLI.

**Comment by Neustart** [comment]
Thanks for your reply

**Comment by jagadeeshkushalappa** [comment]
Even I'm getting "MD5 hash mismatch for message id" for empty messages. while reading messages from SQS. Unable to handle it and unable to delete it. Anyone got solution for this, please suggest.

![image](https://github.com/aws/aws-sdk-net/assets/142787841/97c009c1-d7b5-42e7-ac48-03c2aaa46adf)
