### ISSUE TITLE
Can't Install Latest Stable Release 3.3.0.1 into a Visual Studio project

### ISSUE THREAD

**Issue by sanster23** [aws/aws-sdk-net#459]
I am trying to build a project using .NET SDK for AWS but the nuget package installer fails while installing version Latest Stable Release 3.3.0.1:

![pckage_installation failed](https://cloud.githubusercontent.com/assets/15207772/18861783/7c392b1c-84a5-11e6-9e83-a66a1357c9a7.PNG)

The output for installer is as as follows 

![package_installation output](https://cloud.githubusercontent.com/assets/15207772/18861816/aabf0254-84a5-11e6-9adb-5b3a30435696.png)

**I was able to workaround this by first installing a lower version and then updating the nuget package to the latest version
But when I build the project the same error pops up**
 
![build_errors](https://cloud.githubusercontent.com/assets/15207772/18861893/11c4efae-84a6-11e6-91ca-1142ad8b4a3b.png)
![build_errors_2](https://cloud.githubusercontent.com/assets/15207772/18862032/1f54e0d8-84a7-11e6-9ee5-954b678b2b6d.png)

So how do I install or update to the Latest Stable Release of .NET AWS SDK ?

**Comment by Myfreedom614** [comment]
I noticed that AWSSDK.Core V3.3.0.1 added some .Net dependencies which is not compatible in UWP.

For example: [System.Threading.Thread](https://www.nuget.org/packages/System.Threading.Thread/)

That's the reason you see this exception in VS:
`Install-Package : System.Threading.Thread 4.0.0 provides a compile-time reference assembly for System.Threading.Thread on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm.`

**Comment by sanster23** [comment]
So is there any workaround to use AWSSDK V3.3.0.1 in my project or I can't use it at all??

**Comment by Myfreedom614** [comment]
@sanster23 Yes, please see my updated answer in [here](http://stackoverflow.com/questions/39718364/problems-in-updating-aws-net-sdk-in-a-uwp-project-from-v3-1-10-to-v3-3-0-1/39746611?noredirect=1#comment66819021_39746611)

**Comment by normj** [comment]
The 3.3.X versions of the SDK have separate dlls for netstandard (.net core) and portable class library (PCL). What is supposed to happen and what we need to figure out why it isn't happening is why NuGet is choosing the netstandard version over the PCL.

**Comment by sanster23** [comment]
@normj  The documentation of AWSSDK V3.3.0.1 shows the Encryption and TransferUtility(upload and download directory etc.) but when I installed the sdk in Visual Studio these are missing. 
So is that a bug too..
or a problem on my end??

**Comment by normj** [comment]
The download directory operations aren't available in the PCL due to issues of navigating the file system in mobile platforms. In our SDK API docs at the bottom is the version info table which indicates in which platforms the operation is available.

**Comment by sstevenkang** [comment]
We think https://github.com/aws/aws-sdk-net/commit/375a66cf6df should address this problem.  Could you update to the latest nuget packages and give it another try?

**Comment by sanster23** [comment]
@normj I checked  the Nuget Packages for the aws sdk version 3.3.6.0 it was not there will you please publish the new version to the official nuget repo

**Comment by normj** [comment]
3.3.6 is the current overall SDK product version number. Which we update whenever any of the SDK NuGet packages updates. The product version helps us keep track when individual SDK NuGet packages get updated. If you look the SDK change log:

https://github.com/aws/aws-sdk-net/blob/master/SDK.CHANGELOG.md

you can see product version 3.3.6 contain an updated version of AWSSDK.Core with version number 3.3.1.

**Comment by sstevenkang** [comment]
@sanster23, any luck with with the latest nuget packages?

**Comment by sanster23** [comment]
@sstevenkang  I was able to update the nuget packages 
Thanks for the updates
