### ISSUE TITLE
Can't set proxy in ClientConfig in Xamarin project using AWS SDK.

### ISSUE THREAD

**Issue by acmayberry** [aws/aws-sdk-net#460]
It looks as if the methods for setting a WebProxy on ClientConfig are only available for CoreCLR builds and are not exposed in the version downloaded from nuget.  How is it possible to set a proxy for the SDK in the version deployed via nuget.

**Comment by normj** [comment]
We don't currently have support for setting proxy information in the portable class library version of the SDK which is used for Xamarin projects.

**Comment by acmayberry** [comment]
This makes it very difficult to develop Xamarin projects which connect to AWS in an enterprise setting.  I have the proxy set on my emulator, but the HTTPClient used by the SDK ignores those settings.  Are there any thoughts on when or if this might be implemented?

**Comment by spati2** [comment]
We are pleased to announce that the .NET SDK now supports WebProxy support for Portable Class Libraries. Update the your application to use the latest .NET SDK (you an download the msi from https://aws.amazon.com/sdk-for-net/) and give it a try. Let me know if you had any other questions or concerns.

**Comment by acmayberry** [comment]
So ironic that I just checked on this for the first time today in months.  Thanks very much!

**Comment by acmayberry** [comment]
Something to point out when using a proxy is that when using CognitoAWSCredentials you need to use the constructor that takes a AmazonCognitoIdentityClient and AmazonSecurityTokenServiceClient and pass proxy information to them via their configs as well.  This took me some time to discover.

**Comment by spati2** [comment]
Thanks for the information. Closing the issue now.
