### ISSUE TITLE
Amazon.Runtime.AmazonUnmarshallingException occurred with .NET DynamoDBv2  3.3.0

### ISSUE THREAD

**Issue by lkinsella** [aws/aws-sdk-net#464]
I've just started coming across an issue with our DynamoDB code however it only seems to happen when using DynamoDB-Local.

We're using the latest 3.3.0 build of the DynamoDBv2 libary on .NET Core. We can run the code fine against a real DynamoDB instance and records are inserted just fine. However at present when we try and run this against DynamoDB-Local we get the follow:

> Amazon.Runtime.AmazonUnmarshallingException occurred
>   HResult=-2146233088
>   LastKnownLocation=""
>   Message=Error unmarshalling response back from AWS. 
>   RequestId=""
>   Source=AWSSDK.Core
>   StackTrace:
>        at Amazon.Runtime.Internal.Transform.JsonResponseUnmarshaller.Unmarshall(UnmarshallerContext input) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\Transform\ResponseUnmarshallers.cs:line 189
>        at Amazon.Runtime.Internal.Transform.ResponseUnmarshaller.UnmarshallResponse(UnmarshallerContext context) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\Transform\ResponseUnmarshallers.cs:line 63
>        at Amazon.Runtime.Internal.Unmarshaller.UnmarshallResponse(UnmarshallerContext context, IRequestContext requestContext) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\Unmarshaller.cs:line 208
>        at Amazon.Runtime.Internal.Unmarshaller.Unmarshall(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\Unmarshaller.cs:line 147
>        at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 81
>        at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 46
>        at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\RetryHandler\RetryHandler.cs:line 87
>        at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 46
>        at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 46
>        at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\ErrorCallbackHandler.cs:line 44
>        at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\MetricsHandler.cs:line 40
>        at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\RuntimePipeline.cs:line 136
>        at Amazon.Runtime.AmazonServiceClient.Invoke[TRequest,TResponse](TRequest request, IMarshaller`2 marshaller, ResponseUnmarshaller unmarshaller) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\AmazonServiceClient.cs:line 192
>        at Amazon.DynamoDBv2.AmazonDynamoDBClient.DescribeTable(DescribeTableRequest request) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Generated\_mobile\AmazonDynamoDBClient.cs:line 1186
>        at Amazon.DynamoDBv2.DocumentModel.Table.DescribeTable(String tableName) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DocumentModel\Table.cs:line 302
>        at Amazon.Runtime.Internal.Util.Cache`2.GetValueHelper(TKey key, Boolean& isStaleItem, Func`2 creator) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\Util\SdkCache.cs:line 424
>        at Amazon.DynamoDBv2.DocumentModel.Table.LoadTableInfo() in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DocumentModel\Table.cs:line 130
>        at Amazon.DynamoDBv2.DataModel.DynamoDBContext.GetTable(String tableName, DynamoDBFlatConfig flatConfig) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DataModel\ContextInternal.cs:line 119
>        at Amazon.DynamoDBv2.DataModel.DynamoDBContext.GetTargetTable(ItemStorageConfig storageConfig, DynamoDBFlatConfig flatConfig) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DataModel\ContextInternal.cs:line 109
>        at Amazon.DynamoDBv2.DataModel.DynamoDBContext.SaveHelper[T](T value, DynamoDBOperationConfig operationConfig, Boolean isAsync) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DataModel\Context.cs:line 267
>        at Amazon.DynamoDBv2.DataModel.DynamoDBContext.<>c__DisplayClass99_0`1.<SaveAsync>b__0() in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Custom\DataModel\_async\Context.Async.cs:line 60
>        at Amazon.Runtime.Internal.AsyncRunner.<>c__DisplayClass0_0.<Run>b__0() in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\_async\AsyncRunner.cs:line 28
>        at Amazon.Runtime.Internal.AsyncRunner.<>c__DisplayClass1_0`1.<Run>b__1() in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\_async\AsyncRunner.cs:line 46
>     --- End of stack trace from previous location where exception was thrown ---
>        at Amazon.Runtime.Internal.AsyncRunner.<>c__DisplayClass1_1`1.<Run>b__0() in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\_async\AsyncRunner.cs:line 70
>        at System.Threading.Tasks.Task`1.InnerInvoke()
>        at System.Threading.Tasks.Task.Execute()
>     --- End of stack trace from previous location where exception was thrown ---
>        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>        at Kingpin.Common.Dynamo.Clients.DynamoClient.<InsertAsync>d__10`1.MoveNext()
>     --- End of stack trace from previous location where exception was thrown ---
>        at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>        at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>        at Kingpin.Service.Chat.Dynamo.DynamoChatHistoryRepository.<InsertAsync>d__2.MoveNext() in D:\Contracts\MediaTonic\Kingpin\kingpin-service-chat\src\Kingpin.Service.Chat.Dynamo\ChatHistoryRepository.cs:line 29
>   InnerException: 
>        HResult=-2146233088
>        Message=Invalid character '<' in input string
>        Source=AWSSDK.Core
>        StackTrace:
>             at ThirdParty.Json.LitJson.Lexer.NextToken() in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\ThirdParty\Json\Lexer.cs:line 884
>             at ThirdParty.Json.LitJson.JsonReader.ReadToken() in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\ThirdParty\Json\JsonReader.cs:line 253
>             at ThirdParty.Json.LitJson.JsonReader.Read() in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\ThirdParty\Json\JsonReader.cs:line 295
>             at Amazon.Runtime.Internal.Transform.JsonUnmarshallerContext.Read() in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\Transform\JsonUnmarshallerContext.cs:line 182
>             at Amazon.DynamoDBv2.Model.Internal.MarshallTransformations.DescribeTableResponseUnmarshaller.Unmarshall(JsonUnmarshallerContext context) in D:\Jenkins\jobs\v3-stage-release\workspace\AWSDotNetPublic\sdk\src\Services\DynamoDBv2\Generated\Model\Internal\MarshallTransformations\DescribeTableResponseUnmarshaller.cs:line 51
>             at Amazon.Runtime.Internal.Transform.JsonResponseUnmarshaller.Unmarshall(UnmarshallerContext input) in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Internal\Transform\ResponseUnmarshallers.cs:line 182
>        InnerException: 

We're using the latest DynamoDB downloaded and ran automatically through this URL: http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.tar.gz

Has anyone any ran into this issue and/or have any suggestions as I'm a little stumped at present?

I  went looking for a list of previous versions of DynamoDB-Local with the hope of trying an older version but couldn't find any. Because we can talk to live DynamoDB fine my assumption is the problem is with DynamoDB-Local and not the SDK itself. We seem to be able to read fine at present, this only happens when writing.

We use DynamoDB-Local for testing purposes as it's generally not practical to do against live instances.

**Comment by sstevenkang** [comment]
> HResult=-2146233088
> Message=Invalid character '<' in input string
> Source=AWSSDK.Core

Looking at the inner exception the json library had some trouble parsing the response.  Could you capture the response and see what the problem may be using a tool such as Fiddler?

**Comment by lkinsella** [comment]
It seems this was down to the way we were handling table prefixes, not entirely sure how but we've managed to resolve it.
