### ISSUE TITLE
Removing MSBuild-integrated NuGet restores / Remove .nuget folder / deprecation

### ISSUE THREAD

**Issue by derFunk** [aws/aws-sdk-net#468]
Hi there,

Is there any special reason to have the sdk/.nuget folder?

If not, I'm proposing to remove the https://github.com/aws/aws-sdk-net/tree/master/sdk/.nuget folder from this repository.

Reason: _MSBuild-integrated restores_ are deprecated and should not be used anymore. Instead: _automatic restore capabilities of NuGet 2.7 and above_.
See http://docs.nuget.org/ndocs/consume-packages/package-restore#migrating-to-automatic-restore

Removing the .nuget folder should not bring up any problems - A central/system wide NuGet installation or Visual Studio should be used instead - see also http://docs.nuget.org/ndocs/consume-packages/package-restore.

References to the .nuget folder in `.csproj` will have to be removed as well of course:
`<Import Project="$(SolutionDir)\.nuget\NuGet.targets" Condition="Exists('$(SolutionDir)\.nuget\NuGet.targets')" />`
This can be automated by using these scripts: https://github.com/owen2/AutomaticPackageRestoreMigrationScript

**Comment by normj** [comment]
Thanks for the info. Is our current system blocking you? I'm waiting for the new tooling updates for .NET Core before doing anymore updates to our project system.

**Comment by derFunk** [comment]
It's not blocking me, it just may confuse people like myself, because the integrated NuGet version 3.4.x contains some bugs for netcore which are mostly all fixed in the current 3.5 RC.

I'm also not quite 100% sure how VS 2015 Upd. 3 is handling these .nuget references - not sure if the binary gets used here or not. It seems the the tooling currently is a bit messy.

**Comment by normj** [comment]
The tooling is pretty messy now. It has been a challenge for us to get our legacy .NET 3.5 support, Xamarin, Unity, .NET 4.5 and .NET Core to play nice with each other. Which is why I want to avoid messing with it till the tooling gets a bit less messy :)

**Comment by normj** [comment]
Closing for now. Once .NET Core moves to msbuild we can revisit how we use NuGet
