### ISSUE TITLE
Can we have a Gitter Channel?

### ISSUE THREAD

**Issue by derFunk** [aws/aws-sdk-net#469]
... like `aws-sdk-ruby`, `aws-sdk-js` and `aws-sdk-go` have? 

Would love to chat and exchange knowledge with fellow .net sdk users!

**Comment by vellozzi** [comment]
We're considering the possibility but don't have an ETA right now.  Stay tuned...

**Comment by gokarnm** [comment]
We now have a Gitter channel for the [SDK](https://gitter.im/aws/aws-sdk-net) and one for [AWS Lambda for .NET Core](https://gitter.im/aws/aws-lambda-dotnet)!
