### ISSUE TITLE
IDynamoDBContext missing some of the public methods of it's concrete interface DynamoDBContext

### ISSUE THREAD

**Issue by damiangreen** [aws/aws-sdk-net#470]
These methods need to be pulled up into the interface

`ScanAsyncAll` `BatchPutAsync`, `BatchDeleteAsync` `CreateBatchWriteAndPutItems` `CreateBatchWriteAndPutSingleItem`

This prevents us from returning a  IDynamoDBContext from our services and mocking.

I.e I'd like to do this 

```
public IDynamoDBContext GetDynamoDbContext()
{
	return new DynamoDBContext(GetAmazonDynamoDbClient());
}
```

but am forced to return the concrete type

```
public DynamoDBContext GetDynamoDbContext()
{
	return new DynamoDBContext(GetAmazonDynamoDbClient());
}
```

**Comment by PavelSafronov** [comment]
The methods you have mentioned do not exist on the DynamoDBContext class that is part of the SDK.
Are the methods extension methods? If so, they can be updated to be extensions on the interface IDynamoDBContext instead of the concrete type DynamoDBContext.

**Comment by damiangreen** [comment]
ah ok great , i see that the interface is partial. thanks
