### ISSUE TITLE
Consolidated Billing

### ISSUE THREAD

**Issue by StuartMeeks** [aws/aws-sdk-net#471]
Can we add functionality to create a new sub-account under a master account for use with master accounts that have consolidated billing setup?

**Comment by PavelSafronov** [comment]
Have you looked into [AWS Identity and Access Management (IAM)](https://aws.amazon.com/iam/)? This service allows you to setup users and roles under a master account.

If you need assistance with this service, I recommend posting questions to the [IAM forum](https://forums.aws.amazon.com/forum.jspa?forumID=76). This repo deals mainly with the AWS .NET SDK. Service feature questions or feature requests are better suited for the individual service forums.

**Comment by StuartMeeks** [comment]
Further research uncovers that there's no existing API available to create a customer tenant.
