### ISSUE TITLE
Amazon.SQS.Model.QueueDoesNotExistException

### ISSUE THREAD

**Issue by Jamesxql** [aws/aws-sdk-net#473]
When I send a GetQueueUrlRequest, the AmazonSQSClient will throw a QueueDoesNotExistException if the queue doesn't exists. 

But when I send a SendMessageRequest to the aws, it just throw a AmazonSQSException. 

Why are you doing this design?

**Comment by sstevenkang** [comment]
Hey there.  Thanks for reporting this behavior.  It seems like <code>QueueDoesNotExistException</code> was not modeled for <code>SendMessage</code> operation.  Even the [REST API doc](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SendMessage.html) is not listing it as a valid error.  You can see this in `generator\ServiceModels\sqs-2012-11-05.normal.json`.  We'll work with the SQS service team to resolve this.

**Comment by sstevenkang** [comment]
Hi James.  Service team has this on their backlog, but we have no idea when they'll get to fix this inconsistency.  Since there's no actionable item on our part, I am going to close this.  Feel free to ping on the AWS forums or cut a support ticket.
