### ISSUE TITLE
Using GetCannedSignedURL requires spaces in filename to be replaced with +

### ISSUE THREAD

**Issue by danspam** [aws/aws-sdk-net#476]
If you have uploaded a file to S3 with spaces in the name e.g. the resource path is 'some/folder/my document.pdf' then using AmazonCloudFrontUrlSigner.GetCannedSignedURL to generate a private cloudfront url does not work (you get access denied) unless you replace spaces with +, so the resource path must be changed to 'some/folder/my+document.pdf'

**Comment by sstevenkang** [comment]
Sorry for the confusion.  The function takes a URL as a parameter in string type and it is illegal to have a literal space in URL.  Regarding S3 specifically, S3 supports url codepoint translated address such as `some/folder/my%20document.pdf`.  We'll update the docs to clarify this, but it is expected of the function  caller to provide a valid URL.

**Comment by danspam** [comment]
Ok, I see. Would it make sense then to have some rudimentary validation on
the parameters of the function?

**Comment by sstevenkang** [comment]
For historical reasons, we use string instead of URI throughout our codebase.  It's unreasonable to do validation on all instances where we deal with URI. :(

**Comment by gokarnm** [comment]
Closing this issue. Feel free to reopen if needed.
