### ISSUE TITLE
EC2 DescribeReservedInstances doesn't return reservation using region as scope

### ISSUE THREAD

**Issue by SonjaChevre** [aws/aws-sdk-net#483]
Reserved Instances can now be set to automatically apply across all Availability Zones in a region (see details here: https://aws.amazon.com/blogs/aws/ec2-reserved-instance-update-convertible-ris-and-regional-benefit/). 

After changing all the reservations in one region to use the region scope, I have noticed that the SDK call DescribeReservedInstances doesn't return any of the region scope based reservations (but only older expired reservations).

SDK version 1.10.0.6

**Comment by PavelSafronov** [comment]
Can you post code that shows this behavior?
Are you certain the SDK version is 1.10.0.6?

**Comment by SonjaChevre** [comment]
I'm using the MSI installer for the SDK and have updated it to the latest version before posting this ticket - see:

![2016-11-04 09_37_35-extensions and updates](https://cloud.githubusercontent.com/assets/17831497/19999397/7002345c-a272-11e6-9fb6-5a47e6dd0d8d.png)

AWSSDK.Core and AWSSDK.EC2 reference properties show version 3.3.0.0.

Sample code (simplified):

```
AmazonEC2Client ec2 = new AmazonEC2Client(RegionEndpoint.USEast1);
DescribeReservedInstancesRequest request = new DescribeReservedInstancesRequest();
try
{
     DescribeReservedInstancesResponse response = ec2.DescribeReservedInstances(request);
     
     // always return the total number of reservations with zone scope, reservations with region scopes are ignored 
     Console.WriteLine(response.ReservedInstances.Count + " reservations found");

     foreach (ReservedInstances reservedInstance in response.ReservedInstances)
     {
           if (reservedInstance.State == "active")
           {
              // do stuff
            }
      }
}
catch (Exception ex)
 {
       // exception code
}
```

any help appreciated - thanks!

**Comment by PavelSafronov** [comment]
According to [EC2 documentation for DescribeReservedInstances](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeReservedInstances.html), it looks like you need to specify a Filter to configure the "scope" to be "Region" to get reservations with region scopes. Here's an example of such a filter.

```
DescribeReservedInstancesRequest request = new DescribeReservedInstancesRequest
{
    Filters = new List<Amazon.EC2.Model.Filter>
    {
        new Amazon.EC2.Model.Filter
        {
            Name = "scope",
            Values = new List<string>
            {
                "Region"
            }
        }
    }
};
```

**Comment by SonjaChevre** [comment]
hmm seems it is working now - even without the additional filter.
thanks for the help on this one - issue can be closed (I don't think I'm able to close it by myself?).

**Comment by riegel** [comment]
I am having the same issue and reserved instances that are scoped with region do not show up using the API.

**Comment by riegel** [comment]
This is the specific API request that should return 2 reserved instances that have a scope of region. It returns an empty list of reserved instances.

     https://ec2.us-west-2.amazonaws.com/?Action=DescribeReservedInstances
     This Fails, scope=region

I have other accounts that have Reserved Instances with a scope of "Availability Zone" and the API works as expected with those.

     https://ec2.us-east-1.amazonaws.com/?Action=DescribeReservedInstances
     This suceeds, scope=Availability Zone
