### ISSUE TITLE
AmazonSQSClient is missing the synchronous methods when targeting .NetCore

### ISSUE THREAD

**Issue by necoras** [aws/aws-sdk-net#485]
I have a .Net Core service which is targeting .NET Framework 4.6.1. I have to target the .NET Framework in order to run the Service as a Windows Service rather than in IIS.

My Unit Test project targets .NetCoreApp v1.0. 

In my service I call GetQueueAttributes. When I try to setup my unit test I get the following exception:
"'AmazonSQSClient' does not contain a definition for 'GetQueueAttributes'."

The AmazonSQSClient does have GetQueueAttributesAsync, but not the GetQueueAttributes. Looking at a few other methods there are only Async versions of them as well. 

Is this lack of synchronous methods intentional? Will these methods be supported in future releases, or is this the expected behavior indefinitely?

**Comment by PavelSafronov** [comment]
The lack of synchronous methods is intentional. You can see Norm's explanation for it [here](https://github.com/aws/aws-sdk-net/issues/480#issuecomment-257382757).

**Comment by necoras** [comment]
Great, thanks. That's what I was looking for.
