### ISSUE TITLE
AWS S3 3.3.0 - Xamarin and iOS link error

### ISSUE THREAD

**Issue by Magic73** [aws/aws-sdk-net#486]
Environment: Visual Studio 2015 - Xamarin 4.2.0.719 - Xamarin.iOS 10.2.0.4 - Xcode 10.1
 Previously I used the 3.1.11 version, and I hadn't any issue.
 Yesterday I updated my nuget package to the 3.3.0 and now I can't compile anymore with linker behaviour "SDK assembly only".
 I'm able to compile only if I set linker behaviour to "don't link".

This is the error:
 Failed to resolve "System.Void Amazon.Runtime.Internal.Util.AESEncryptionPutObjectStream::.ctor(System.IO.Stream,System.Byte[],System.Byte[])" reference from "AWSSDK.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604"

**Comment by normj** [comment]
We are tracking down the issue now. It looks like the new .NET Core version of the SDK added in 3.3 is causing trouble with the reference resolution for Xamarin. I'll post back as soon as we have this fixed but till then the work around is to stay on version 3.1.X

**Comment by Magic73** [comment]
I got the same issue with Droid too. Again, it works only with "don't link" option.

**Comment by sstevenkang** [comment]
We think change cda0e0bf39c2810e9a1f01a14a55d47835e252ca will address the reference issue.   Could you get the latest nuget packages(Core version 3.3.5) and see if it resolves your problem?

**Comment by Magic73** [comment]
It worked :) (both on iOS an Droid)

Thank you!

**Comment by sstevenkang** [comment]
Happy to help! :)
