### ISSUE TITLE
Xamarin: Error executing statement Busy in SqlLocalStorage.SetupDatabase during initial CognitoSyncManager constructor-call

### ISSUE THREAD

**Issue by ksloginov** [aws/aws-sdk-net#488]
After update from Core.3.1.4.3 CognitoSync 3.1.1.0 to Core 3.3.5 and CognitoSync 3.3.1.2 - we've been using old versions due to https://github.com/aws/aws-sdk-net/issues/479 - we've noticed, that first time users triggers  `GetCognitoSyncManager() `:

		public static CognitoSyncManager GetCognitoSyncManager() 
		{
			if (cognitoSyncManager == null) 
			{
				cognitoSyncManager = new CognitoSyncManager(
					new CognitoAWSCredentials(
						"eu-west-1:b.....", // Identity Pool ID
						RegionEndpoint.EUWest1),
					RegionEndpoint.EUWest1
				);
			}

			return cognitoSyncManager;
		}

we are getting `Error executing statement Busy `in `SqlLocalStorage.SetupDatabase`:
<img width="845" alt="screen shot 2016-11-16 at 12 46 31" src="https://cloud.githubusercontent.com/assets/1670172/20346200/20ba0022-abfb-11e6-8397-bf6f7df4dbcc.png">

As a result, app is crashing. Then, after restart - it works normally. Same code in Android works fine.

Any ideas what can it be? Anything i forgot?
Thanks!

**Comment by sstevenkang** [comment]
The message `Error executing statement Busy` is incorrect. What it really should say is `The query reported result 'Busy'`.   Does this problem repro consistently?  This looks like a resource contention caused by code outside of the SDK.

> The SQLITE_BUSY result code indicates that the database file could not be written (or in some cases read) because of concurrent activity by some other database connection, usually a database connection in a separate process.

**Comment by ksloginov** [comment]
@sstevenkang thanks for your reply! Yes, it's 100% consistent: every time I re-install, first call of `new CognitoSyncManager(...)` throws an exception. Then after restarting the app - it works as expected.

**Comment by ksloginov** [comment]
Just an update from my side: I believe, I've workarounded the issue by putting all crucial initializations into critical section and, as I remember, it solved the issue. (though I might did some other refactoring as well). So I guess we can close it :-)

**Comment by sstevenkang** [comment]
Glad that you figured out a fix.  The SDK makes no guarantee when a client instance/dependent resource is shared by multiple threads.
