### ISSUE TITLE
SES .NET core support

### ISSUE THREAD

**Issue by aclave1** [aws/aws-sdk-net#491]
Hello, I've noticed that the amazon SES library does not yet support .NET core. Is this feature on the roadmap, or is the smtp subsystem drastically different in .NET core?

**Comment by sstevenkang** [comment]
This is news to me.  Did you just search for `SES`?  I believe we refer to it as `SimpleEmail`.  You can see the nuget package [here](https://www.nuget.org/packages/AWSSDK.SimpleEmail/).

**Comment by aclave1** [comment]
Yep, you're right. I did search for just SES.
