### ISSUE TITLE
SAML Profiles not available in .Net Core

### ISSUE THREAD

**Issue by rohitshrivastava04** [aws/aws-sdk-net#496]
After a lot of debugging, I figured out, SAML profiles are not available in a .Net Core project whereas same is easily available in .Net Framework.

Is there a plan to support StoredProfileFederatedCredentials in .Net Core?

My experience:
Register profile using PowerShell as described here:
http://docs.aws.amazon.com/powershell/latest/userguide/saml-pst.html

Create a new project in . Net Core, SAML profile not available. Create a new project .Net Framework, SAML profile is available and it works like charm.

**Comment by steveataws** [comment]
Hi,

At some point we hope to support the use of the SAML credential profiles in .NET Core environments, but we've not completed validation that all of the classes we use are available or have alternate workarounds. Last time we looked, prior to .NET Core going GA, some networking classes appeared to be absent.

We are doing some work on our credential classes so we'll take another look prior to finalizing the changes to see what, if anything, needs to be done (or can be done).

**Comment by cfbarbero** [comment]
+1

**Comment by rohitshrivastava04** [comment]
@steveataws can it be looked up again after as now .net core is GA and they made a lot of progress, this should be viable now.

**Comment by wwilliams** [comment]
+1

**Comment by vellozzi** [comment]
This has been added to our feature request list: https://github.com/aws/aws-sdk-net/blob/master/FEATURE_REQUESTS.md
