### ISSUE TITLE
Parsing code for AWS SimpleNotification PublishRequest from SNS message is not correct. 

### ISSUE THREAD

**Issue by GenZodd** [aws/aws-sdk-net#502]
The Amazon.SimpleNotificationService.Util.Message class has a method called "ParseMessage". This message needs to take a SNS JSON object and parse it into the "message" class. However, the parsing code reference the SigningCertUrl field incorrectly. 

This is the JSON you get from SNS.

`{
  "Records": [
    {
      "EventSource": "aws:sns",
      "EventVersion": "1.0",
      "EventSubscriptionArn": "arn:.......",
      "Sns": {
        "Type": "Notification",
        "MessageId": "ce4a1d7c-c50d-51ea-bfe8-4dc1078795fe",
        "TopicArn": "arn:.......",
        "Subject": null,
        "Message": "test queue",
        "Timestamp": "2016-12-04T07:05:46.709Z",
        "SignatureVersion": "1",
        "Signature": "<mysighere>",
        "SigningCertUrl": "<pem url here>",
        "UnsubscribeUrl": "<unsub url here>",
        "MessageAttributes": {}
      }
    }
  ]
}`

If you select just the SNS field object you get this JSON
`{
        "Type": "Notification",
        "MessageId": "ce4a1d7c-c50d-51ea-bfe8-4dc1078795fe",
        "TopicArn": "arn:.......",
        "Subject": null,
        "Message": "test queue",
        "Timestamp": "2016-12-04T07:05:46.709Z",
        "SignatureVersion": "1",
        "Signature": "<mysighere>",
        "SigningCertUrl": "<pem url here>",
        "UnsubscribeUrl": "<unsub url here>",
        "MessageAttributes": {}
      }`

Notice how the field is named "SigningCertUrl". 

Here is the json selection code from the "ParseMessage" method.

Line 160
`message.SigningCertURL = Message.ValidateCertUrl(func("SigningCertURL"));`

Notice how it has capital URL instead of Url. All the Url fields in this method reference "URL" instead of "Url" so null is always returned. This makes the ValidateCert function error out.

**Comment by PavelSafronov** [comment]
Where is the JSON you mention coming from?

**Comment by GenZodd** [comment]
I got the JSON from just printing to CloudFront the payload on the input parameter, when invoked by SNS. Once I did a replace on messageText and Change "Url" to "URL" everything worked. 

     public string FunctionHandler(object messageText, ILambdaContext context)
     {           
            context.Logger.Log($"message type: {message.Type}");
     }

**Comment by PavelSafronov** [comment]
The JSON data that is sent to a Lambda function from SNS is not the same as what Message.ParseMessage expects, as you've already noticed.
You should rewrite your function handler to use the SNSEvent type defined in the [Amazon.Lambda.SNSEvents NuGet package](https://www.nuget.org/packages/Amazon.Lambda.SNSEvents). The parsing will happen automatically. Here's an example of using the SNSEvent in Lambda:

```
public void FunctionHandlerSNS(SNSEvent snsEvent, ILambdaContext context)
{
    foreach (var record in snsEvent.Records)
    {
        Console.WriteLine($"Message = [{record.Sns.Message}]");
        Console.WriteLine($"UnsubscribeUrl = [{record.Sns.UnsubscribeUrl}]");
    }
}
```

**Comment by GenZodd** [comment]
Prefect thanks for the info. I thought it felt a little odd but was assuming the object I was after was in the SimpleNotificationService nuget. I did not see the event package.
