### ISSUE TITLE
Visual Studio 2015 dark color theme not being applied.

### ISSUE THREAD

**Issue by bpavlov** [aws/aws-sdk-net#504]
This issue was reported here: https://github.com/aws/aws-sdk-net/issues/228 Since it is closed I am opening new issue.

![image](https://cloud.githubusercontent.com/assets/2480572/20907652/35d2322e-bb58-11e6-9a30-69a8c210ba6c.png)

**Comment by steveataws** [comment]
Hi,

Out of curiosity what values do you have for either (or both) of these registry keys:

HKCU\Software\Microsoft\VisualStudio\12.0\General\CurrentTheme
HKCU\Software\Microsoft\VisualStudio\14.0\ApplicationPrivateSettings\Microsoft\VisualStudio\ColorTheme

If neither of those keys exist, can you find a ColorTheme key in your Visual Studio registry hives for the current user?

**Comment by bpavlov** [comment]
HKCU\Software\Microsoft\VisualStudio\14.0\ApplicationPrivateSettings\Microsoft\VisualStudio\ColorTheme is `0*System.String*1ded0138-47ce-435e-84ef-9ec1f439b749`

**Comment by bpavlov** [comment]
After the update from 09.02.2017 it is okay.
