### ISSUE TITLE
MSI Installer fails

### ISSUE THREAD

**Issue by pieterdhondt** [aws/aws-sdk-net#505]
With the latest installer (AWSToolsAndSDKForNet_sdk-3.3.27.0_ps-3.3.27.0_tk-1.11.0.0) this keeps happening:

![image](https://cloud.githubusercontent.com/assets/213126/20922465/8557b4a4-bba8-11e6-9415-fdcc8b9936a9.png)

I tried several times, also uninstalling first etc.

When using AWSToolsAndSDKForNet_sdk-3.3.24.0_ps-3.3.24.0_tk-1.10.0.6, it installs without any issue.

**Comment by ralsu091** [comment]
See also https://forums.aws.amazon.com/thread.jspa?messageID=754010&tstart=0

**Comment by steveataws** [comment]
Hi,

Thanks for the notification. We're investigating the issue and will report back here and on the forum thread when we have a resolution.

**Comment by vellozzi** [comment]
This issue has been fixed and released.
