### ISSUE TITLE
Unable to load DLL 'Crypt32.dll' when running .net core app in docker container

### ISSUE THREAD

**Issue by devlife** [aws/aws-sdk-net#507]
I'm running a .NET Core app in a docker container (`FROM microsoft/dotnet:1.0.1-sdk-projectjson`) and when I try to set my credentials via `ProfileManager.RegisterProfile(profileName, accessKey, secret);` I get the following exception. Am I missing some piece of setup?

```
System.DllNotFoundException: Unable to load DLL 'Crypt32.dll': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Amazon.Runtime.Internal.Settings.UserCrypto.CryptProtectData(DATA_BLOB& pDataIn, String szDataDescr, DATA_BLOB& pOptionalEntropy, IntPtr pvReserved, CRYPTPROTECT_PROMPTSTRUCT& pPromptStruct, CryptProtectFlags dwFlags, DATA_BLOB& pDataOut)
   at Amazon.Runtime.Internal.Settings.UserCrypto.Encrypt(String unencrypted)
   at Amazon.Runtime.Internal.Settings.SettingsCollection.ObjectSettings.WriteToJson(JsonWriter writer)
   at Amazon.Runtime.Internal.Settings.SettingsCollection.Persist(StreamWriter writer)
   at Amazon.Runtime.Internal.Settings.PersistenceManager.saveSettingsType(String type, SettingsCollection settings)
   at Amazon.Util.AWSCredentialsProfile.Persist(String profileName, String accessKeyId, String secretKey)
```

When running it on my windows os it works fine. It also fails on a mac.

```
"dependencies": {
    "AWSSDK.Core": "3.3.5",
    "AWSSDK.EC2": "3.3.4"
}
```

**Comment by vellozzi** [comment]
ProfileManager is only supported on Windows platforms.  Before using it you need to check that ProfileManager.IsAvailable == true.  In the short term we'll add a better exception message.

For the long term we're working on a way for you to be able to read/write to the ~/.aws/credentials file instead.  Although, we don't have an ETA on that.

**Comment by devlife** [comment]
Ah ok that's def great to know. How can I proceed in the meantime? Is there a different API I should be using?

**Comment by PavelSafronov** [comment]
If you are referring to `RegisterProfile`, then there's no reason to be calling that in your application. [This blog post](https://aws.amazon.com/blogs/developer/registerprofile/) explains a bit of what this API does and why it doesn't need to be called.

**Comment by chazt3n** [comment]
@devlife - were you able to find any way around this?

**Comment by devlife** [comment]
@chazt3n I just ended up using the client `constructor` overrides to pass in creds:

`var ec2Client = new AmazonEC2Client(accessKey, secret, RegionEndpoint.USEast1);`

I kept the accessKey and secret in aspnet secrets.

**Comment by vellozzi** [comment]
We now have support for the shared credentials file.  That's the same credential file used by the AWS CLI.
You can get credentials directly from the .NET credentials file, directly from the shared credentials file, or use a fallback mechanism.  The fallback mechanism looks for the profile in the .NET credential file and falls back to the shared file if the profile isn't found in the .NET credential file.

- The .NET credential file is accessed with the NetSDKCredentialsFile class.
- The shared credential file is accessed with the SharedCredentialsFile class.
- CredentialProfileStoreChain implements the fallback mechanism.

I suggest using CredentialProfileStoreChain.  If you have a profile in the .NET credential file on your dev box your code will find it.  In production you can then use the shared credential file without any code changes.

[Here](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-creds.html) is a link to the relevant topic in the developer guide.

**Comment by chazt3n** [comment]
Thank you very much
