### ISSUE TITLE
Using iot-data api to publish message but return signature not match exception

### ISSUE THREAD

**Issue by sijwang** [aws/aws-sdk-net#509]
Found some issues about iot-data api

All lib are downloaded by using nuget
version:
```
<packages>
  <package id="AWSSDK.Core" version="3.3.6" targetFramework="net452" />
  <package id="AWSSDK.IoT" version="3.3.1.4" targetFramework="net452" />
  <package id="AWSSDK.IotData" version="3.3.0.5" targetFramework="net452" />
  <package id="AWSSDK.S3" version="3.3.5.1" targetFramework="net452" />
</packages>
```

using following code to publish, but the exception 
"The request signature we calculated does not match the signature you provided. Check your AWS Secret"
 is always thrown 

```
  AmazonIotDataConfig amazonIotDataConfig = new AmazonIotDataConfig();
  amazonIotDataConfig.RegionEndpoint = RegionEndpoint.APNortheast1;
  amazonIotDataConfig.UseHttp = false;
  amazonIotDataConfig.SignatureVersion = "4";
  amazonIotDataConfig.ServiceURL = amazonIotDataConfig.DetermineServiceURL();
  AmazonIotDataClient amazonIotDataClient = new AmazonIotDataClient("[ACCESS_KEY_ID]",   "[SECRET_ACCESS_KEY]", amazonIotConfig);
  try
  {
    String jsonString = "{"
               + "\"state\": {"
               + "\"reported\": {"
               + "\"door\": \"OFF\""
               + "}"
               + "}"
               + "}";

      MemoryStream memStream = new MemoryStream(Encoding.UTF8.GetBytes(jsonString ?? string.Empty));

      PublishRequest publishRequest = new PublishRequest();
      publishRequest.Qos = 0;
      publishRequest.Payload = memStream;
      publishRequest.Topic = "\\$aws/things/[THING_ID]/shadow/update";

      return amazonIotDataClient.Publish(publishRequest);
  }
  catch (System.Exception e)
  {
    throw e;
  }
```

Had use the same ACCESS_KEY_ID,  SECRET_ACCESS_KEY with Python boto3 iot-data api to publish message. In that context, the key pair works fine.

Had use another key pair with S3 R/W permission and .net aws s3 api to list my S3 Objects. In that context, it is normal.

Summarize the situation:

1. the key pairs are ok, permissions of key pair are also ok.
2. the AWS4Signer is ok, because using S3 Client to list S3 Objects in root Bucket is ok.
3. There might be some issues in AmazonIotDataClient or AmazonIotDataConfig for api user to config request for producing siginature.

Thanks.

**Comment by PavelSafronov** [comment]
Thank you for reporting this issue. It's a bug with how the SDK signs and invokes requests where Topic contains the "$" character. We're looking into a possible fix. At the moment it looks like you'll need to use a different SDK for these sorts of requests.

**Comment by sijwang** [comment]
@PavelSafronov Thank you for your reply. 
We need to implement a mobile application based on Xamarin, but not familiar with .net and c#.
so we need to ask for more details to evaluate the way to work-around.

1. Would you describe more specifically about "a different SDK for these sorts of requests"? Did you mean that we need to use other lib to access AWS iot-data web service?

2. When the issue possibly be fixed?

3.Our purpose is to control mcu based device that connected to AWS iot service via MQTT.
Is it possible to follow the information the article (UpdateThingShadow http://docs.aws.amazon.com/iot/latest/developerguide/API_UpdateThingShadow.html) provided to update iot thing status through iot thing shadow HTTP Restful api and aws will deliver the update status req to mcu based device via MQTT?

Thanks.

**Comment by PavelSafronov** [comment]
We're working on a possible fix right now, but can't say for sure when the fix would be available.

1. Currently, the .NET SDK is not capable of making calls against topics which have a "$" in the name.
2. Don't know yet.
3. Not certain, this would be a question for the [IoT forum](https://forums.aws.amazon.com/forum.jspa?forumID=210).

**Comment by PavelSafronov** [comment]
We've just released version 3.3.0.6 of [IotData package](https://www.nuget.org/packages/AWSSDK.IoTData) which works with topics that contain "$". Please try that.

**Comment by sijwang** [comment]
@PavelSafronov 
Thank you and your team members.
It's works, message can be sent with topics contains "$" via AWS iotdata library 3.3.0.6.

**Comment by sijwang** [comment]
Issue solved!
