### ISSUE TITLE
Unity Question: Amazon Pinpoint

### ISSUE THREAD

**Issue by Deathwing** [aws/aws-sdk-net#510]
Hey guys,

I just wanted to know if it is currently possible to integrate Amazon Pinpoint with Unity or I'm simply missing something? :)

Because we wanted to update from AWSMobileAnalytics to AWSPinpoints for the Events & Push Campaigns.

Cheers!

**Comment by gokarnm** [comment]
Amazon Pinpoint is not currently available in the Unity SDK. Adding as a feature request.

**Comment by POANG1** [comment]
Its been 6 months guys we REALLY REALLY need Pinpoint support in Unity. pleeeeaaase :)

**Comment by aphexyuri** [comment]
👍

**Comment by oleschaper** [comment]
With Mobile Analytics deprecated and a small time window of migrating to Pinpoint in the next few weeks, what is the status on this one? How are we supposed to migrate if there is no support for it?

**Comment by MartinGebske** [comment]
Still no update on this?
