### ISSUE TITLE
Read ServiceURL from Environment?

### ISSUE THREAD

**Issue by doc** [aws/aws-sdk-net#516]
Using this new config process I cant seem to read and set the ServiceURL from an environment variable.

**Comment by PavelSafronov** [comment]
Can you provide some more information on what you are trying to do, what you are expecting, and what is actually happening? Sample code reproducing your issue would be very helpful.

**Comment by doc** [comment]
Hi @PavelSafronov,

Apologies for the vaguely written issue, let me try and expand.

I'm using the AWSSDK to talk to an S3 compatible backend requiring me to set the ServiceURL property on AmazonS3Config. My expectation is that I should be able to set an environment variable (or otherwise configure) and have the config framework 'do the right thing' as is the case with AWS_ACCESS_KEY_ID et al. The only way I've been able to get this to work locally is by calling the  AmazonS3Config API as per below:

```   var s3config = new AmazonS3Config
            {
                ForcePathStyle = true,
                ServiceURL = Environment.GetEnvironmentVariable("AWS_SERVICE_URL")
            };
```

I hope this helps further elucidate the situation.

**Comment by PavelSafronov** [comment]
Can you use the AWS_REGION environment variable instead? If you are using a standard S3 AWS endpoint, you should be able to set this variable.

**Comment by doc** [comment]
No, this won't work as I'm not always talking to Amazon S3; in some instances Minio or Ceph implementations are part of our solution. In cases where the S3 backend is not Amazon we need to set the ServiceURL property.

**Comment by PavelSafronov** [comment]
Ah, got it. You'll have to continue to manually read the ServiceURL from the environment (or anywhere else that you may choose to store it).
Setting the ServiceURL property from the AWS_SERVICE_URL environment is not something that we will be adding to the SDK. Since the SDK supports 88 services, it's not possible to use the same ServiceURL for all of them.
