### ISSUE TITLE
Is there any way to get a request/response id from anywhere other than the HTTP headers?

### ISSUE THREAD

**Issue by erick-thompson** [aws/aws-sdk-net#517]
I have a need to log errors that occur when performing operations on various AWS services (S3, Dynamo, SQS, RDS, etc). Most of these services have a concept of a request/response id that represents something we can send to Amazon tech support for debugging, and for correlation. The error handling is a few layers up from the direct usage of AWS, so I don't have any of the AWS request/response objects. Is this value created or set somewhere that code that isn't at the HTTP level can access it (e.g., thread local storage)?

**Comment by PavelSafronov** [comment]
You can enable SDK metrics logging, which will log request ids. Here a few blog posts describing this: [Logging with the AWS SDK for .NET](https://aws.amazon.com/blogs/developer/logging-with-the-aws-sdk-for-net/), [Alternative Formatting for Metrics Data in .NET SDK Logs
](https://aws.amazon.com/blogs/developer/alternative-formatting-for-metrics-data-in-net-sdk-logs/), and [Retrieving Request Metrics from the AWS SDK for .NET
](https://aws.amazon.com/blogs/developer/retrieving-request-metrics-from-the-aws-sdk-for-net/)
This data is also available on all responses and exceptions that are thrown by the SDK. Here's an example of retrieving both through code:
```
using (var dynamoDbClient = new AmazonDynamoDBClient())
{
    var response = dynamoDbClient.ListTables();
    Console.WriteLine("Response RequestId: {0}", response.ResponseMetadata.RequestId);
    try
    {
        dynamoDbClient.DescribeTable("fake-table");
    }
    catch (AmazonServiceException ase)
    {
        Console.WriteLine("Exception RequestId: {0}", ase.RequestId);
    }
}
```
