### ISSUE TITLE
Android Notifications via Amazon SNS for Unity missing Title and Icon

### ISSUE THREAD

**Issue by goneale** [aws/aws-sdk-net#518]
When sending a push notification, the Android notification comes through ok, but the icon is a white square as there is no provision to specify the black and white notification icon which meet Android's requirements, nor is there any Title, it just comes through blank.

I have seen the gcmhelper-src folder provided in the SNS sample, but I am not a java expert and I'm not sure how to adjust these files and recompile into the Plugins\Android\aws-unity-sns-gcm-helper.jar file to suit my needs including a new resource for a notification icon .png.

Is the SNS library for Unity intending to be updated soon, or can somebody knowledge provide steps in how I would achieve this? It's not ideal to go live with a white box and a missing title for notifications.

**Comment by PavelSafronov** [comment]
Can you clarify which SNS sample you are using and where it was downloaded from?

**Comment by goneale** [comment]
Sure, the default Unity AWS package - https://github.com/aws/aws-sdk-net/blob/master/Unity.README.md via the "Download the Unity Package" link. When imported, it additionally comes with a gcmhelper-src folder for I assume altering the Android integration.

**Comment by PavelSafronov** [comment]
Looks like the library that you're referring to is fairly old and needs to be updated. Adding this as a feature request.

**Comment by goneale** [comment]
Ok. If it can be updated to support the Title feature via the GCM payload or even in the C# configuration file along with a ability to specify an Android notification icon that would be great.

**Comment by goneale** [comment]
If I could also suggest incorporating the following implementation - https://medium.com/yammer-engineering/gcm-push-notifications-registration-done-right-7aba759d1d55 This would allow all users with the app to automatically register on GCM via SNS when they receive the app update.

As it stands with this package, each user needs to run the app once to be subscribed to notifications which is not that great considering push notifications are coming as a subsequent update to my app.

**Comment by karthiksaligrama** [comment]
The GCM registration bit is outdated in the SDK. you could take a look at code in this package https://github.com/awslabs/aws-sdk-unity-samples/tree/master/SNS/gcmhelper-src and try to implement the mechanism using the latest google play services.

I'm closing this issue as we do not plan to update the helper libraries. Future version of the SNS package for Unity may not include the helper libraries as well.
