### ISSUE TITLE
S3DirectoryInfo.GetFiles returns exception "key is a directory name"

### ISSUE THREAD

**Issue by bwgit** [aws/aws-sdk-net#52]
The following simple test returns the above exception:

S3DirectoryInfo test = new S3DirectoryInfo(client, "bucketname", "testdir/test");
test.Create();
var files = test.GetFiles("*", SearchOption.AllDirectories);

The reason is that S3DirectoryInfo.Create is creating an object called "testdir/test/" (note the trailing slash). 

S3DirectoryInfo.EnumerateFiles checks each returned s3Object, skipping those that EndsWith("\") - I'm taking a guess here, but perhaps the s3Object key is returned with a "/" slash, which doesn't satisfy this check?

The end result is passing an object key with a trailing slash to the S3FileInfo constructor, which then throws the exception.

**Comment by goldengrisha** [comment]
I tested, all was working fine if change '/' to '\'.
