### ISSUE TITLE
CloudFormation: Custom resource support for .NET Core Lambda functions

### ISSUE THREAD

**Issue by NeilBostrom** [aws/aws-sdk-net#520]
I wanted to write some custom resources for my CloudFormation templates using .NET core in AWS Lambdas. All the samples are in JS and Python at the moment:

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/walkthrough-custom-resources-lambda-lookup-amiids.html

I'm assuming CloudFormation requests / response models are not currently supported by the SDK? I found S3 models and others but no CloudFormation ones.

I've written a version of the request / response model for CloudFormation in Lambdas. Is this something you would be interested in me creating a PR for?

I also have a working version of cfn-response in .NET which feels like it would be super handy to have in the SDK for people to be able to call on their Lambda response calls. The version is based around the documentation at:

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-code.html#cfn-lambda-function-code-cfnresponsemodule

Let me know if you are interested in any of the above and I can look at creating a PR for it.

**Comment by PavelSafronov** [comment]
When you say "S3 models", are you referring to the S3 events that are defined in the [Amazon.Lambda.S3Events NuGet package](https://www.nuget.org/packages/Amazon.Lambda.S3Events)? If so, and you are looking to add similar events classes, please open an issue in the [aws-lambda-dotnet repo](https://github.com/aws/aws-lambda-dotnet).

**Comment by NeilBostrom** [comment]
Totally correct. Thank you for the info.
