### ISSUE TITLE
S3 Get Object Async error with Byte Range starting at 0

### ISSUE THREAD

**Issue by ANTROPO** [aws/aws-sdk-net#522]
I am trying to setup partial downloads for an object on s3.

```
GetObjectRequest request = new GetObjectRequest();
request.BucketName = bucket;
request.Key = key;
request.ByteRange = new ByteRange (0, range);

S3Client.GetObjectAsync (request, ((responseObject) => {
  ProcessResponse (responseObject, size, step, range);
}), null);
```

Regardless of what is inside of ProcessResponse, when the Byte Range is set to 0 - something, I immediately get Amazon.Runtime.Internal.HttpErrorResponseException, before even the callback is called.

When I set the byte range to 1 - something the request is processed correctly, but at the end, when all parts are processed, I am missing 1 byte :)

What am I doing wrong? Thanks!

**Comment by ANTROPO** [comment]
I noticed, that if I supply the whole size of the file in bytes -1 byte as the end range, the GetObjectAsync call doesn't result in an error. But if this number is lets say 1/10 of the size, there is the mentioned error.

**Comment by ANTROPO** [comment]
I can work around this issue, by first getting the first byte by setting the ByteRange to 0,0 and then proceeding with larger chunks of a few megabytes.

**Comment by PavelSafronov** [comment]
What version of the SDK are you using?
Can you verify the first code sample that you posted? I can't get that to compile, there is no `GetObjectAsync` overloads that accepts a lambda that operates on the response object.

Can you post the full exception that you are seeing?
