### ISSUE TITLE
missing GetPreSignedURL(request) function in Unity

### ISSUE THREAD

**Issue by daves0** [aws/aws-sdk-net#525]
I'd like to upload to S3 using pre-signed urls from Unity (if I can get past all the SDK bugs in uploading .. sigh ... is anything being done on any of them?) but I get this message when I add a call to GetPreSignedURL (even just pasting in the sample code fails):

Assets/Test.cs(256,34): error CS1061: Type `Amazon.S3.AmazonS3Client' does not contain a definition for `GetPreSignedURL' and no extension method `GetPreSignedURL' of type `Amazon.S3.AmazonS3Client' could be found. Are you missing an assembly reference?

I'm not missing an assembly reference .. the method just ain't there.  If you look at the source code for the full .Net version, there's stuff in there for it .. but a search in the Mobile SDK doesn't turn up anything except in DynamoDB, where it's using the request to do the work:

this.s3ClientCache.GetClient(this.RegionAsEndpoint).GeneratePreSignedURL(....)

I did searches here on Git using the "This repository" search.

Sorry for the rambling, I've been fighting the SDK and S3 all day and my brain is fried.  All I want to do is upload a file, it shouldn't be nearly this hard.

**Comment by soapyigu** [comment]
Hi @daves0 , actually we have the function here: aws-sdk-net/sdk/src/Services/S3/Custom/_bcl+coreclr+pcl/AmazonS3Client.Extensions.cs. Did you expect this one?

Feel free to shoot any questions or feedback, looking forward to hearing from you.

**Comment by levin-Imagin8ors** [comment]
hi, need help with generating PreSignedURL's in Unity

**Comment by DanielOS96** [comment]
I'm also having this problem any solution yet?

**Comment by feliperb98** [comment]
Same problem here

**Comment by feliperb98** [comment]
@ashishdhingra thank you for the labeling, hope the problem can be fixed soon.

**Comment by ashishdhingra** [comment]
Hi @daves0,

Good afternoon.

Starting with version 3.5 of the AWS SDK for .NET, projects using Unity 2018.1 or later should target the .NET Standard 2.0 release of the SDK. You can find additional information in the developer guide: [Unity support](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/unity-special.html) and [Migrating your Unity application](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/net-dg-v35.html#net-dg-v35-changes-unity).

Please try using the .NET Standard 2.0 version of the AWS SDK for .NET (version 3.5). Kindly confirm if this is still an issue.

Thanks,
Ashish

**Comment by craftercis** [comment]
Hello. Sorry for reopening this topic but I want to ask how i can make a pre request url in a Unity script.

I use this but it is not working. I get the url in de debug but when i open it is gives an error

`using Amazon;
using Amazon.S3;
using Amazon.S3.Model;
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class test : MonoBehaviour
{
    private const string bucketName = "name";
    // Specify your bucket region (an example region is shown).
    private static readonly RegionEndpoint bucketRegion = RegionEndpoint.EUWest3;
    private static IAmazonS3 s3Client;

    public static InputField inputField;
    public static InputField pasteURLField;


    public void Start()
    {
        Main();
    }

    public static void Main()
    {
        s3Client = new AmazonS3Client(bucketRegion);
        string urlString = GeneratePreSignedURL();
        Console.WriteLine(urlString);
        Console.Read();
    }
    static string GeneratePreSignedURL()
    {
        string urlString = "";
        try
        {
            GetPreSignedUrlRequest request1 = new GetPreSignedUrlRequest
            {
                BucketName = bucketName,
                Key = inputField.text,
                Expires = DateTime.Now.AddSeconds(30),
            };
            urlString = s3Client.GetPreSignedURL(request1);
        }
        catch (AmazonS3Exception e)
        {
            Console.WriteLine("Error encountered on server. Message:'{0}' when writing an object", e.Message);
        }
        catch (Exception e)
        {
            Console.WriteLine("Unknown encountered on server. Message:'{0}' when writing an object", e.Message);
        }
        Debug.Log(urlString);
        return urlString;
    }
}
`

**Comment by craftercis** [comment]
> EDIT: Hello. I have this script working in the editor. When i type the name of the S3 file in a Inputfield and I press a button the URL is set to another inputfield so that i can copy and paste it to google. But when I build it to Android it crashes when i press the button. Who can help me?
> 
> `using Amazon;
> using Amazon.S3;
> using Amazon.S3.Model;
> using System;
> using System.Collections;
> using System.Collections.Generic;
> using UnityEngine;
> using UnityEngine.UI;
> 
> public class Test : MonoBehaviour
> {
> private const string bucketName = "***";
> // Specify your bucket region (an example region is shown).
> private static readonly RegionEndpoint bucketRegion = RegionEndpoint.EUWest3;
> private static IAmazonS3 s3Client;
> 
> ```
> private static InputField setNameField;
> private static InputField setURLField;
> 
> public void ButtonClick()
> {
>     setNameField = GameObject.Find("Set Name InputField").GetComponent<InputField>();
>     setURLField = GameObject.Find("Set URL InputField").GetComponent<InputField>();
>     Main();
> }
> 
> public void Main()
> {
>     s3Client = new AmazonS3Client(bucketRegion);
>     string urlString = GeneratePreSignedURL();
>     Console.WriteLine(urlString);
>     Console.Read();
> }
> static string GeneratePreSignedURL()
> {
>     string urlString = "";
>     try
>     {
>         //ServerSideEncryptionMethod ssem = new ServerSideEncryptionMethod("AWSKMS");
>         GetPreSignedUrlRequest request1 = new GetPreSignedUrlRequest
>         {
>             BucketName = bucketName,
>             Key = setNameField.text,
>             Expires = DateTime.Now.AddSeconds(10),
>             Verb = 0,
>             //ServerSideEncryptionKeyManagementServiceKeyId = "some-value",
>             //ServerSideEncryptionMethod = ServerSideEncryptionMethod.AWSKMS
>         };
>         urlString = s3Client.GetPreSignedURL(request1);
>     }
>     catch (AmazonS3Exception e)
>     {
>         Console.WriteLine("Error encountered on server. Message:'{0}' when writing an object", e.Message);
>     }
>     catch (Exception e)
>     {
>         Console.WriteLine("Unknown encountered on server. Message:'{0}' when writing an object", e.Message);
>     }
>     setURLField.text = urlString;
>     Debug.Log(urlString);
>     return urlString;
> }
> ```
> 
> }
> `

I solved it. I had to put my accessKey and secretKey together with the Region in AmazonS3Client.

If someone later also has this problem here is the code.

`using Amazon;
using Amazon.Runtime;
using Amazon.S3;
using Amazon.S3.Model;
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Net;
using UnityEngine;
using UnityEngine.UI;

public class TestGenerate : MonoBehaviour
{

    public static InputField setUrlField;

    public void Start()
    {
        //This is the InputField where you can copy the URL from.
        setUrlField = GameObject.Find("Set URL InputField").GetComponent<InputField>();
    }

    public static string GetContents(string path)
    {
        HttpWebRequest request = HttpWebRequest.Create(path) as HttpWebRequest;
        HttpWebResponse response = request.GetResponse() as HttpWebResponse;

        using (Stream stream = response.GetResponseStream())
        using (StreamReader reader = new StreamReader(stream))
        {
            Debug.Log(path);
            setUrlField.text = path;
            return reader.ReadToEnd();
        }
    }

    public void Test()
    {
        var credentials = new BasicAWSCredentials("YOUR ACCESSKEY", "YOUR SECRET KEY");
        // Create a client. Set the region endpoint to your region!
        AmazonS3Client client = new AmazonS3Client(credentials, RegionEndpoint.EUWest3);

        // Create a CopyObject request
        GetPreSignedUrlRequest request = new GetPreSignedUrlRequest
        {
            BucketName = "YOUR BUCKET NAME",
            Key = "YOUR OBJECT KEY",
            Expires = DateTime.UtcNow.AddSeconds(10)
        };

        // Get path for request
        string path = client.GetPreSignedURL(request);

        // Test by getting contents
        string contents = GetContents(path);
    }
}
`
