### ISSUE TITLE
Opening AWSSDK.Unity.sln crashes visual studio 2015 community

### ISSUE THREAD

**Issue by kasradzenika** [aws/aws-sdk-net#530]
What happened:

1. Cloned the repo
2. Double-clicked AWSSDK.Unity.sln. Visual Studio 2015 Community started loading the solution.
3. Pop-up: visual studio stopped working > click debug
4. Another copy of visual studio starts with the message:
system.io.directorynotfoundexception: Could not find a part of the path [repo_root]\sdk\src\Core\Library\UnityAssemblies

I closed both instances of visual studio and manually created the above-mentioned folder. Again, launched the AWSSDK.Unity.sln and it opened OK.

**Comment by normj** [comment]
The issue has been fixed if you pull latest master branch.
