### ISSUE TITLE
Add Support for Cognito User Pools for Unity

### ISSUE THREAD

**Issue by kasradzenika** [aws/aws-sdk-net#534]
This is a feature request that needs next to no effort to implement, I got it working by:
1. Dublicate **AWSSDK.CognitoIdentityProvider.Net35.csproj** and name it **AWSSDK.CognitoIdentityProvider.MockUnity.csproj**
2. I am using VS2015 so I have to delete **project.json** in the **AWSSDK.CognitoIdentityProvider**'s folder to force it to use **packages.config**, not sure if you have to to this on VS2017
3. open **AWSSDK.Unity.sln**
4. in the solution explorer: right click >> add >> existing project >> navigate to **AWSSDK.CognitoIdentityProvider.MockUnity.csproj** >> Add
5. in the solution explorer: unfold the newly added project's *References* and there should be a missing library: **AWSSDK.Net35.Core**. Right click on it >> Remove (del)
6. right click on the same *References* >> add reference >> projects >> AWSSDK.Unity.Core
7. Build then copy the generated **/bin/unity/CognitoIdentityProvider.dll** into Unity

NOTE: in Unity's build settings I'm using **.Net 2.0** (NOT subset), don't know if this matters but it's building fine in Unity

**Comment by CostelloNicho** [comment]
Thank you for the work around @kasradzenika. Got some time on my hands so I may just wait till it's officially supported here. Awesome stuff.

**Comment by SolidWhiteSven** [comment]
Hey, I've done the port using your steps here. Had some problems with Unity 2017 but got it to compile with the UnityEngine.dll from the 5.6.5 version. Because I want everyone else who looks for this to not have the long and bad experience of porting this, so I've added a fork to the AWS SDK, containing the Cognito Identity Provider and the source project that I created it with. Hope it helps :-)

https://github.com/SolidWhiteSven/amazon-cognito-unity

All the Best, 

Sven

**Comment by kasradzenika** [comment]
have you tested it?

**Comment by SolidWhiteSven** [comment]
@kasradzenika Yes, I've successfully signed up a user, confirmed the user with a code that was sent to my email and then logged the newly created user in, all using the 5.6.5 version of Unity. A problem was, that you cannot do these asynchronous calls that you need to use for the AWS calls in the main thread, Unity doesn't like that. But you can do those calls in a new thread and everything's fine.

**Comment by adrianbaciuc** [comment]
@SolidWhiteSven Hi, Sven! I came across your fork before reading this thread and I was banging my head against the source project and Unity 2017. It now makes sense that you got it working with the Unity 5.6.5 dll.

On the other hand I need some directions for actually getting the SRP to work. I keep running into mismatches between async methods in various tutorials and sync methods in the dll. I understand why this is happening but cannot find a working guide.

Any help is much appreciated and thanks for publishing your fork.

Thanks,
Adrian.

**Comment by SolidWhiteSven** [comment]
Hey @adrianbaciuc, sadly I didn't quite have to worry about SRP and don't really know what that is... Maybe this helps? 

https://stackoverflow.com/questions/42668607/authentication-aws-cognito-srp

With the async calls, I wrote myself a separate class, hanedling all the Cognito stuff. I have a "SignUpUser" method in there, that only starts a new thread and inserts a callback method. In this thread, I then do all the CognitoIdentityProviderClient.SignUp-method to do the actual sign up. Internally it seems as if asynchronous calls are made so you need to do this in a separate thread, not the Unity main thread. The signup-method is called synchronously, as far as I can tell, so after it returns, I check the result and call the callback-method that was provided to the thread in the beginning. With that callback, you know when your signup has finished, although in the response, you still aren't in the main Unity thread, so you can only set some class variables and log something to the debug console. 

Also I had to configure this line here in the Start()-function of my Cognito-Access class:
AWSConfigs.HttpClient = AWSConfigs.HttpClientOption.UnityWebRequest;

Hope this helps, 

Best regards, 

Sven

**Comment by rygo6** [comment]
NM, was because I was trying to do it with the 45 sln.
