### ISSUE TITLE
Best way to hide secret access key?

### ISSUE THREAD

**Issue by dfiverr** [aws/aws-sdk-net#541]
What is the best way to hide a secret access key? Surely there is a better way than just making it private and read only. The only example I could find is something like 
```
using (var client = new AmazonS3Client(accessKey, secretAccessKey, _S3Region))
{

}
```
but this doesnt look very safe, and the docs say not to embed these keys within the app. I am using Unity. I have the users sign in token from Cognito, but it doesnt look the same as what I need here.

**Comment by PavelSafronov** [comment]
Take a look at this series of blog posts we have written on the subject of credentials:
- [Access Key Management for .NET Applications – Part 1](https://aws.amazon.com/blogs/developer/access-key-management-for-net-applications-part-1/)
- [Using IAM Users (Access Key Management for .NET Applications – Part 2)](https://aws.amazon.com/blogs/developer/using-iam-users-access-key-management-for-net-applications-part-2/)
- [IAM Credential Rotation (Access Key Management for .NET Applications – Part 3)](https://aws.amazon.com/blogs/developer/iam-credential-rotation-access-key-management-for-net-applications-part-3/)
- [IAM Roles for Amazon EC2 instances (Access Key Management for .NET Applications – Part 4)](https://aws.amazon.com/blogs/developer/iam-roles-for-amazon-ec2-instances-access-key-management-for-net-applications-part-4/)

Hope that provides a good starting point.

**Comment by dfiverr** [comment]
Thanks @PavelSafronov but that information is hard for me to understand, and not really clear. I have looked through all 4. I am not using EC2 instances, but AWS Lambda for the back end, and Unity as the client. Would you be able to provide more specific information?

**Comment by PavelSafronov** [comment]
Lambda will provide your Lambda function with credentials, so you don't need to store any credentials there.
If your Unity client uses the .NET SDK, you should be using Cognito to get credentials onto the device.

You'll want to familiarize yourself with Cognito, so the [Cognito Developer Guide](http://docs.aws.amazon.com/cognito/latest/developerguide/what-is-amazon-cognito.html) is a good place to start.

The [Amazon Cognito Credentials Provider post](https://aws.amazon.com/blogs/developer/amazon-cognito-credentials-provider/) provides an overview of using Cognito with the .NET SDK, while the follow-up [Updated Amazon Cognito Credentials Provider post](https://aws.amazon.com/blogs/developer/updated-amazon-cognito-credentials-provider/) shows the new, simplified way to construct `CognitoAWSCredentials`.

**Comment by normj** [comment]
Closing as I believe this is answered. Feel free to reopen if you have more issues.
