### ISSUE TITLE
AWSSDK.Lambda support for .net core 

### ISSUE THREAD

**Issue by akatz0813** [aws/aws-sdk-net#542]
It seems that this Package is one of the very few that does not support .net core. Is there a way to use the sdk from .net core to invoke a lambda function?  We can of course make http calls but the sdk is easier.

**Comment by PavelSafronov** [comment]
[AWSSDK.Lambda package](https://www.nuget.org/packages/AWSSDK.Lambda) supports .NET Core and can be used from Lambda functions.
Which version are you trying to use? I was able to use the latest package to deploy and run the following handler on Lambda.

```
public async Task<string> FunctionHandler(ILambdaContext context)
{
    using (var client = new Amazon.Lambda.AmazonLambdaClient())
    {
        var functions = (await client.ListFunctionsAsync()).Functions;
        return string.Join(", ", functions.Select(f => f.FunctionName));
    }
}
```

**Comment by akatz0813** [comment]
I apologize, you're right.  I didn't see the .netstandard support, but it appears this is PCL.
