### ISSUE TITLE
AWS Elasticsearch with NEST .net

### ISSUE THREAD

**Issue by luizgustavogp** [aws/aws-sdk-net#544]
Is possible use [NEST](https://github.com/elastic/elasticsearch-net) with these SDK?

Thanks!

**Comment by PavelSafronov** [comment]
Can you be more specific?
This repo is for the .NET SDK and issues with it, your question may be more appropriate for the NEST repo.

**Comment by luizgustavogp** [comment]
My on premise application use NEST to mapping requests and responses to strongly typed objects  and provide query DSL that maps one-to-one with Elasticsearch. I did not find these features in this SDK.
I didn't want to make major changes to my project to work on AWS Elasticsearch.

Can you provide a sample or doc api to: create a index, add, remove and serarch documents?

Thanks!

**Comment by PavelSafronov** [comment]
From [the Amazon Elasticsearch developer guide](http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/what-is-amazon-elasticsearch-service.html):
> Amazon Elasticsearch Service (Amazon ES) is a managed service that makes it easy to create a domain and deploy, operate, and scale Elasticsearch clusters in the AWS Cloud.

So Amazon Elasticsearch and the related .NET SDK client are used **only** to create and manage an Elasticsearch cluster, while accessing the data in that cluster - including creating an index, adding, removing, and searching documents - can be done with any compatible Elasticsearch client, including NEST.

You'll want to go through the NEST documentation for examples of how to work with documents.

**Comment by Kralizek** [comment]
I use Elasticsearch hosted by AES in production.

With the help of this library https://github.com/bcuff/elasticsearch-net-aws we can correctly sign the requests to our domain so that we can enforce stronger access policies.

**Comment by luizgustavogp** [comment]
Hi @Kralizek, thanks for you suggestion. 

@PavelSafronov  this is way to work with Elasticsearch on AWS? 
Is necessary sign the requests? 
What is you suggestion?

**Comment by PavelSafronov** [comment]
@luizgustavogp , sorry, I don't have any experience with Elasticsearch, so can't comment on the best approach. You'll want to take a look at the [Amazon Elasticsearch developer guide](http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/what-is-amazon-elasticsearch-service.html) for best-practices around usage, see if someone has posted a similar question on the [Amazon Elasticsearch forum](https://forums.aws.amazon.com/forum.jspa?forumID=200), and look into the library @Kralizek mentioned.

**Comment by EmilAlipiev** [comment]
Hey, did you figure out how to do it using Nest? Do we have to sign every request?

**Comment by Kralizek** [comment]
Hi,
AWS stuff will be able to give you proper support on the issue (I am just a passionate Architect that uses Elasticsearch on his projects).

You mainly have two options:
1) open up your domain to specific IPs and send unsigned requests
2) sign your requests with the library I linked above.

I strongly suggest case 1) for development clusters (the opened ip being your office ip) and 2) for production load with your servers in the wild.

The library i linked (I am user, not involved with its development) offers a clean abstraction of the whole request signing process.

You and your developers will never have to care about signing requests to elasticsearch through nest ever again! :)

Let me know if something is not clear. :)
