### ISSUE TITLE
Limit HTTP Connections 

### ISSUE THREAD

**Issue by rsrini83** [aws/aws-sdk-net#546]
Hi,

My application is a self host microservice and purpose of this service is to upload multiples files to S3 instance. Each webrequest provides accessKey, secretKey and bucket information and contains 100 files  to upload. Each webrequest is associated with an AmazoneS3Client instance, using this instance all 100 files will be pushed to S3 bucket. Looks like AmazonS3Client creating a HTTPConnection pool of 16 i think (Total virtual processors are 16) even though i may use 1 or 2.  After a while server seems slow and i could see lot of connections are in TIME_WAIT ( checked using netstat -a).

Now the question here is, How can i restrict connection pool to 2 or 3 instead of 16.

P.S: When i tested with one single request, AmazonS3Client created 2 connections which i'm able to see the in Resource Monitor. So i presumed it creates one HttpWebRequest object per core. I might be wrong. But this is what i observed. 

I need to resolve soon.  Any help is appreciated.  Let me know if any info is required.

Thanks in advance.

**Comment by randall-peakey-com** [comment]
Probably the most important thing to remember is to dispose of your instances.
If you do not, connections will hang around after they are finished.
Eventually you will hit a limit and won't be able to send any more requests.

In regards to using parallel (system.threading.tasks?), look into ParallelOptions (MaxDegreeOfParallelism)

**Comment by rsrini83** [comment]
@randall-peakey-com,

Thanks for your quick response. Yes i invoked dispose method after all files upload. and Yes i'm using MaxDegreeOfParallelism to 4. 

Any idea by default how many connections get created ? Is there a way to restrict pool of connections to 2 or 3. I understand this will impact on the large files upload.

**Comment by randall-peakey-com** [comment]
Clarification requested....
Do you invoke dispose after all the files are uploaded, or do you dispose each instance as the individual files are uploaded?

I do not know how many will get created for each instance.  Once I started disposing the instances after each use I didn't see any connections hanging around.

**Comment by rsrini83** [comment]
I dispose the object after all files are uploaded in the request(100 in my case).  Application gets around 50 to 60 requests at a time,  creating a thread pool is heavy weight so my process become slow with in a few minutes and  sometimes it doesn't respond.

**Comment by PavelSafronov** [comment]
Can you post your code?

**Comment by rsrini83** [comment]
Here is the code,


`
        public async Task<TransporterResponse> Upload(BackupRequest request, AWSStorageConfig storageConfig)
        {
            var uploadFiles = request.UploadFiles; // Gets all 100 Files
            try
            {
                if (request.Location != null && request.Location.Length > 0 && !request.Location.EndsWith("/"))
                {
                    request.Location += "/";
                }
                AWSCredentials awsCredentials = new Amazon.Runtime.BasicAWSCredentials(storageConfig.AccessKey, storageConfig.SecretKey);
                AmazonS3Config s3Config = new AmazonS3Config
                {
                    Timeout = TimeSpan.FromSeconds(1000),            // Default value is 100 seconds
                    ReadWriteTimeout = TimeSpan.FromSeconds(3000),   // Default value is 300 seconds
                    MaxErrorRetry = 2,                              // Default value is 4 retries
                    RegionEndpoint = GetRegion(storageConfig.Region),
                    UseHttp = true,
                    MaxIdleTime = 5,
                    ConnectionLimit = 5,
                    ProxyHost = null
                };
                List<Exception> uploadExceptions = new List<Exception>();
                AmazonS3Client s3Client = new AmazonS3Client(awsCredentials, s3Config);
				// With Parallel
                await uploadFiles.ParallelForEachAsync(async file =>
                {
                    try
                    {
                        await GetUploadTask(request, storageConfig, s3Client, s3Config, file);
                    }
                    catch (Exception e)
                    {
                        uploadExceptions.Add(e);
                    }
                }, maxDegreeOfParalellism: 5);
                s3Client.Dispose();
                if (uploadExceptions.Count != 0)
                {
                    throw new AggregateException(uploadExceptions);
                }
            }
            catch (AmazonS3Exception s3Exception)
            {
                Logger.Error("[backup] - Completed with error");
                Logger.Debug(s3Exception.Message, s3Exception);
                if (s3Exception.ErrorCode == "NoSuchBucket")
                {
                    // Create Bucket and retry if it is cloudcontrols3
                }
                return new TransporterResponse()
                {
                    Status = "ERROR",
                    ErrorCode = "ERR-S3-UPLOAD-FAILED",
                    ErrorMessage = s3Exception.Message
                };
            } catch(Exception e)
            {
                Logger.Error("[backup] - Completed with error");
                Logger.Debug(e.Message, e);
                if (e is AggregateException)
                {
                    throw e;
                } else
                {
                    return new TransporterResponse()
                    {
                        Status = "ERROR",
                        ErrorCode = "ERR-UPLOAD-FAILED",
                        ErrorMessage = e.Message
                    };
                }
            }
            Logger.Debug("[backup] - Backedup to s3 bucket");
            return new TransporterResponse()
            {
                Status = "SUCCESS"
            };
        }

        private async Task GetUploadTask(BackupRequest request, AWSStorageConfig storageConfig, AmazonS3Client s3Client, AmazonS3Config  s3Config, HttpFile file)
        {
            String fileName = file.Name.Split(new char[] { ';' })[0];
            String key = request.Location + fileName;
            S3FileInfo info = new S3FileInfo(s3Client, storageConfig.Bucket, key);
            if(info.Exists)
            {
                // Throws 303 - Resource exist already.
                throw new GeneralServiceErrorException(Infrastructure.Errors.Enums.ServiceErrorEnum.DuplicateItem, "AWS Key exist already - " + key);
            }
            TransferUtility fileTransferUtility = new TransferUtility(s3Client);
            Stream iStream = file.Value; // This is the Stream.
            TransferUtilityUploadRequest fileTransferUtilityRequest = new TransferUtilityUploadRequest
            {
                BucketName = storageConfig.Bucket,
                StorageClass = S3StorageClass.Standard,
                PartSize = 6291456, // 6 MB.
                Key = key,
                InputStream = iStream, //stream,
                CannedACL = S3CannedACL.Private,
            };
            Logger.Debug("[GetUploadTask] - Item Content Length- " + iStream.Length);
            await fileTransferUtility.UploadAsync(fileTransferUtilityRequest);
            Logger.Debug("[GetUploadTask] - Total Time s3 Upload - " + s3UploadWatch.Elapsed.TotalMilliseconds);
        }
`

**Comment by randall-peakey-com** [comment]
Have you tried to create and dispose the AmazonS3Client object inside GetUploadTask?

**Comment by rsrini83** [comment]
Initially i was doing that, upon a google search found one of link(github issue link) that suggested to reuse the client object across multiple threads instead of creating. Updated code to reuse.

**Comment by randall-peakey-com** [comment]
I'd also suggest disposing the fileTransferUtility when finished.

**Comment by rsrini83** [comment]
Oh okay. Will try that now.

**Comment by rsrini83** [comment]
Modified the code and tried now, you can see lot of connections are in TIME_WAIT state.  My current test is with 20 requests in parallel, each request contains 100 files.

![image](https://cloud.githubusercontent.com/assets/16274962/22667320/51c8ae16-ece2-11e6-98ba-9f033721d5fd.png)

**Comment by randall-peakey-com** [comment]
Did you also switch to  creating and disposing the AmazonS3Client object inside GetUploadTask?

**Comment by rsrini83** [comment]
No. Will try that tomorrow and update you. I need to go to bed now as it became very late (3 AM)...
Thanks for your time.

**Comment by PavelSafronov** [comment]
If your application is receiving 50-60 requests at a time, and each of these has 100 files to upload, the parallelization approach you are taking seems like a bad idea for overall throughput, as well as the CPU and memory impact. You're spinning up a large number of threads, but are then trying to limit how many connections are being used by throttling the number of connections each of those threads is going to use. A simpler approach is to instead control the number of threads that are uploading at any one time.

This can be done by using a single thread to do all of the uploads. This thread would grab a single file upload off a queue and run the `GetUploadTask` logic on that file, while the `Upload` method would just add items onto this queue. Using this approach you will be transferring one file at a time, but this will be done in the background and you can very accurately control how many connections are used. (As opposed to spinning up an unknown number of threads and trying to throttle each of those thread's connections.)

Finally, to properly take advantage of `AmazonS3Config.ConnectionLimit`, you should set `AmazonS3Config.ForcePathStyle` to `true`.
Explanation: S3 supports [path-style access](http://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html), and this is what the .NET SDK goes with by default. If a bucket-name is DNS compliant (and a few other factors), the url that the SDK will try to reach will be of the format `https://BUCKET.s3-REGION.amazonaws.com/KEY`. If the bucket is not DNS compliant or `AmazonS3Config.ForcePathStyle` is set to true, the SDK will use `https://s3-REGION.amazonaws.com/BUCKET/KEY`. As you can see, if `AmazonS3Config.ForcePathStyle` is set to false, the host will be different for each bucket, which means that `AmazonS3Config.ConnectionLimit` will apply to traffic to that bucket only. If your application is acting on different DNS compatible buckets, this will mean that each *bucket* has `AmazonS3Config.ConnectionLimit`, as opposed to each *region*.

**Comment by rsrini83** [comment]
Hi PavelSafronov,


--Srinu

**Comment by rsrini83** [comment]
I'm really sorry, by mistake i clicked Close and comment.  

HI PavelSafronov,

Agree with your comments. Yes we are going to introduce Queue mechanism. However this may not solve with root problem, how to control the connection limit per AmazonS3Client instance. 

In your second comment you mentioned need to set azonS3Config.ForcePathStyle to true. and this is the default behavior for .NET SDK. In this case when i set ConnectionLimit to 5 then it should get effected right ?  Or did you i understand wrong ?

Due to this issue, quickly implemented direct HTTPWebRequest direct upload. How ever intermittent receiving 403 Forbidding  error for some requests.  Do you have any idea what could be the issue ?  
I taken the code from AWS site to generate  Pre-Signed URL - http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-examples-using-sdks.html#sig-v4-examples-using-sdk-dotnet

**Comment by PavelSafronov** [comment]
The root problem is that you are spawning **at least** 1000 simultaneous HTTP requests (50 requests * 100 files per request / parallelism of 5 = 50 * 100 / 5 = 1000). It's irrelevant if you are able to "control the connection limit per AmazonS3Client instance". Even if you set the connection limit to be 1 per AmazonS3Client instance (the minimum), you then spin up 1000 instances and all of them try to upload, so you'll still end up with at least 1000 connections.

Once you use a single thread for all uploads instead of spawning 1000 simultaneous requests, it should resolve the problem you are having with too many connections or a slow system.

`AmazonS3Config.ForcePathStyle` is `false` by default. To exactly control how many S3 connections you are making, you'll need to set `AmazonS3Config.ConnectionLimit` to the connection number **and** `AmazonS3Config.ForcePathStyle` to true. But this will mostly be irrelevant once you implement the upload thread approach.

Replacing AmazonS3Client calls with the same number of HTTPWebRequest calls will not solve your problem, and as you've noticed it'll require you to implement retry logic to cope with intermittent errors, among other things. The SDK already has retry logic and performs retries automatically for you, so I suggest using the SDK instead of manually creating and firing HTTPWebRequests.

**Comment by rsrini83** [comment]
Hi PavelSafronov,

Thanks for the detail analysis and suggestions. As suggested we reduced the input requests to 16  and removed the parallelism and one file at a time from each request (out of 100 files). This result into 16 uploads at a time, how ever 16 instances. 

Used the below code to configure s3client.   
` 
AmazonS3Config s3Config = new AmazonS3Config
                {
                    Timeout = TimeSpan.FromSeconds(10),
                    ReadWriteTimeout = TimeSpan.FromSeconds(300),  
                    MaxErrorRetry = 2,
                    RegionEndpoint = GetRegion(storageConfig.Region),
                    DisableLogging = false,
                    MaxIdleTime = 5,
                    ConnectionLimit = 5,
                    ProxyHost = null,
                    LogMetrics = false,
                    LogResponse = false,
                    UseNagleAlgorithm = false,
                    ForcePathStyle = true 
                };
`

Even after these changes, EC2 VM becomes sluggish and our upload became very slow after 1o to 15 mins. 

Please let me know if you have any other suggestion. Or is there any other mechanism to upload multiples in a single web request ?

Using windows 2012 RC2, and Updated TCP/IP fine tuninings like MaxUserPort, waittimeddelay etc.

**Comment by rsrini83** [comment]
Hi PavelSafronov,

Thanks for your support and suggestions. We root caused the actual issue. It is not issue with AmazonS3Client instances, it is due to the drive latency.  I'm using Nancy Framework for self hosting application, it uses temporary files if the file size above certain size. Due to heavy requests, it was writing/reading data to/from disk. Over the period disk became bad and latency increased to above 500 ms. This caused our system hang and application sluggishness. 

@randall-peakey-com 
Thank you for your time and providing your valuable comments.


--Srinu
