### ISSUE TITLE
Is ListObjectsByTagsRequest Supported?

### ISSUE THREAD

**Issue by akatz0813** [aws/aws-sdk-net#548]
I notice there is a domain object for Amazon.S3.Model.ListObjectsByTagsRequest but no corresponding method on the AmazonS3Client.  Any further info or examples would be great!

**Comment by sstevenkang** [comment]
This is actually not a supported operation by the S3 and it seems like we pushed these files in error.  Thanks for letting us know about this.

**Comment by PavelSafronov** [comment]
These classes have been removed. Sorry about the confusion.
