### ISSUE TITLE
Error when using ZipArchiveEntry.Open() stream in TransferUtility.Upload

### ISSUE THREAD

**Issue by peterpociask** [aws/aws-sdk-net#549]
I am working on some code to grab a zipped directory, iterate through the contents, and upload them to S3. If you use the stream from ZipArchiveEntry.Open(), the upload fails with a 400 error from the S3 service: "Missing required header for this request: x-amz-content-sha256"

If you CopyTo the stream to a memory stream and use that instead, it works correctly. I've attached a code sample of the working code. 

[ZipStreamExample.txt](https://github.com/aws/aws-sdk-net/files/765470/ZipStreamExample.txt)

**Comment by PavelSafronov** [comment]
Which version of the SDK are you using? I've tried the code you specified but got a different exception, having to do with the ```e.Open()``` Stream not being able to return a length.

**Comment by peterpociask** [comment]
I am using v3.3.5.4 from nuget. I suspect the stream not being able to return its length is the underlying source of the problem.

**Comment by PavelSafronov** [comment]
It's certainly a problem when I try to run the sample you provided, but it's strange that we're getting different errors. Either way, providing a Stream that is seekable and able to return a length is the workaround here.

**Comment by normj** [comment]
Closing as you discovered you must use a seekable stream for S3.
