### ISSUE TITLE
Performance on iPhone 4S

### ISSUE THREAD

**Issue by wivlaro** [aws/aws-sdk-net#552]
Hi we're experiencing quite poor performance on an iPhone 4S with UnityMainThreadDispatcher taking up a few milliseconds of CPU time every single frame. We suspect that it's because it called Application.internetReachability every frame. There are reports that that function leaks memory which is consistent with our findings, but the performance is the big problem for us.

Is it possible to rewrite this test to use something else? Or not test every single frame, but cache the result for at least a few seconds?

I will try to go in at some point and fix it myself, but the .sln file does not open in MonoDevelop or Xamarin (I am on Mac OS X) so it's not easy to get set up developing for this project.

**Comment by klaytaybai** [comment]
We're now going to use #711 to track this issue.
