### ISSUE TITLE
"Invoke Lambda Function" is not listing all lambda functions

### ISSUE THREAD

**Issue by bpavlov** [aws/aws-sdk-net#553]
When I am trying to Invoke Lambda Function on file in S3 bucket I am not able to see all the lambdas that I have in the drop down list.

![image](https://cloud.githubusercontent.com/assets/2480572/22854634/a0008b70-f07b-11e6-88b1-d34b6f54144f.png)

**Comment by normj** [comment]
Do you see some but not all functions in the control?

**Comment by bpavlov** [comment]
Yes.

**Comment by socketnorm** [comment]
Version 1.11.7.0 of the toolkit came out today which now lists all the functions not just the first page of functions returned by Lambda.

**Comment by normj** [comment]
Version 1.11.7.0 of the toolkit came out today which now lists all the functions not just the first page of functions returned by Lambda.

**Comment by bpavlov** [comment]
I am with 1.12.0.0 and still facing the issue?

![image](https://cloud.githubusercontent.com/assets/2480572/25436408/de05ddda-2a9b-11e7-89a3-e2cf4b277680.png)

**Comment by normj** [comment]
Sounds like you are using the preview VS 2017 version. For VS 2017 you need redownload the preview from original post which will install version 1.12.0.4

https://aws.amazon.com/blogs/developer/preview-of-the-aws-toolkit-for-visual-studio-2017/
