### ISSUE TITLE
Using Cognito credentials to authenticate S3?

### ISSUE THREAD

**Issue by dfiverr** [aws/aws-sdk-net#554]
I am building an app that allows users to upload their files to Amazon S3. I am authenticating users with Cognito, how do I pass the authenticated credentials to S3 so that a user has to be signed in and verified to be allowed to upload?

**Comment by PavelSafronov** [comment]
These two blog posts address how Cognito can be used with the .NET SDK - [Amazon Cognito Credentials Provider](https://aws.amazon.com/blogs/developer/amazon-cognito-credentials-provider/) and [Updated Amazon Cognito Credentials Provider](https://aws.amazon.com/blogs/developer/updated-amazon-cognito-credentials-provider/).

**Comment by normj** [comment]
Closing as I believe this is answered. Feel free to reopen if you have more questions.
