### ISSUE TITLE
Exception in TransferUtilityUploadRequest.Upload with AmazonS3EncryptionClient

### ISSUE THREAD

**Issue by lellis1936** [aws/aws-sdk-net#557]
When using UploadDirectory with  AmazonS3EncryptionClient, an exception always occurs at the end of the transfer.

It appears as if the files were transferred correctly.

A similar exception also occurs on the download side when using DownloadDirectory

Using AWSSDK.S3 v4.0.30319

In code that follows, GetClient returns an AmazonS3EncryptionClient object.  It result in the exception listed at the end of the post. 

```
using (client = GetClient())
{
    TransferUtility transferUtility = new TransferUtility(client);

    TransferUtilityUploadDirectoryRequest uploadRequest =
        new TransferUtilityUploadDirectoryRequest
        {
            BucketName = bucketName,
            Directory = @"C:\testfolder",
            KeyPrefix="testfolder",
            ServerSideEncryptionMethod = ServerSideEncryptionMethod.AES256,
            SearchOption = SearchOption.AllDirectories,
            UploadFilesConcurrently=true,
            SearchPattern = "."

        };

    transferUtility.UploadDirectory(uploadRequest);
    Console.WriteLine("\rUpload complete");
}
```

Exception: System.NullReferenceException, Source is AWSSDK.S3.  The is .Net 4.5

```
Stack trace:
   at Amazon.S3.Transfer.Internal.UploadDirectoryCommand.<ExecuteAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Amazon.S3.Transfer.TransferUtility.UploadDirectory(TransferUtilityUploadDirectoryRequest request)
   at mys3upload.Program.DirectoryUploader.UploadDirectory(String directoryName) in c:\SCM\mys3upload\mys3upload\Program.cs:line 267
   at mys3upload.Program.DirectoryUploader.Upload(String filePath) in c:\SCM\mys3upload\mys3upload\Program.cs:line 235
   at mys3upload.Program.Main(String[] args) in c:\SCM\mys3upload\mys3upload\Program.cs:line 51
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by lellis1936** [comment]
Coding error.

**Comment by PavelSafronov** [comment]
Do you run into the same error if the S3 client is not AmazonS3EncryptionClient?
Is this the full stack trace?

**Comment by lellis1936** [comment]
The error does not occur with the standard (non-encrypting) S3 client.

Yes, this is the full stack trace.

**Comment by lellis1936** [comment]
I have shown the code for GetClient below.  RSA key is hard-coded as this is for demo only.

            static IAmazonS3 GetClient()
            {
                IAmazonS3 client;

                AmazonS3CryptoConfiguration config =
                    new AmazonS3CryptoConfiguration
                    { RegionEndpoint = Amazon.RegionEndpoint.USEast1 };

                if (noCrypt)
                {
                    client = new AmazonS3Client(key, Access, config);
                }
                else
                {
                    RSA rsaAlgorithm = RSA.Create();
                    rsaAlgorithm.FromXmlString(
                    @"<RSAKeyValue><Modulus>sxWOYcZrI7wYqp+xFrJwl5/zHOcDmVxVjF3H+WrKE1BHiJn5xU+ZwcmL7dnj9b4IPxJC10BOTBRScPtcdrse4fcKQTR158NwlTvcurD2JscSqY+0J/ImNKsvfm0GoEBxGyQtRdU3/4Jx0lYO+JzHUvCEoSv20lZUSaVetEyu3Rc=</Modulus><Exponent>AQAB</Exponent><P>4mEfRiAfLgZelfxxZ76/VhWF0nq70L8uqOTvAlG1w57kmc/9Stji4jtrCHWioaUCKeQ/IRVt90FID1Ob63v14w==</P><Q>yoQ4HpzWniZgP+rvEhj70DcHAUWUtC9qXUmPU5QsEFAyOKS+2lqZdl8cBRtkqghyL9izmMZWby7z6o8JEBiCPQ==</Q><DP>DX0eAO6vDO4COsuk8jqSag20QJthj4mkvRmPCENYIkTYeDXFcO1Fb5d8xC9GNn1/iIF6JX2CZOY15fvkYX6sYw==</DP><DQ>fqqqa0NP3YVFSFVKiPhFcFsqr3n046qQjZ633d/cm6t9bf5lPS/Tsr0USoFyugMkYJba5mCPqWUlvP0P/xhFRQ==</DQ><InverseQ>3WlRMzBplhbb+gp7tenRUr5g+H7y+KSwonY/rfj4e/6QXgwzuamzrEB3iWdXHV3PmwwZdweYn7046RAzGEwXjQ==</InverseQ><D>C6lGLbi5ZkjLxGSEqAkzirQIJSQn2FcqXOsIaAXbpblPByabnI0L4pIIshLDpM9cgxrhzllqH8sc+S1s/nA92PYLBEyZ6uuid7YI7Xh0WybLb7iPbsI2YkSy1XosECpJpxVZMmILUS0qz0SnqsyQpi1kUEgu2c/6pic5+1dZJCU=</D></RSAKeyValue>"
					
                    );

                    EncryptionMaterials materials = new EncryptionMaterials(rsaAlgorithm);

                    client = new AmazonS3EncryptionClient(key, Access, config, materials);

                }

                return client;

            }

**Comment by PavelSafronov** [comment]
This is a bug in the UploadDirectory code, thanks for reporting it. We'll have a patch out soon.

**Comment by lellis1936** [comment]
I believe the same bug exists in DownloadDirectory, FYI...

**Comment by PavelSafronov** [comment]
We've pushed out a fix to the issue with UploadDirectory. It appears that DownloadDirectory is functioning correctly in this case. Resolving.
