### ISSUE TITLE
[DynamoDB] Serialization/deserialization of documents

### ISSUE THREAD

**Issue by miltador** [aws/aws-sdk-net#564]
**Propasal:** make `DynamoDBContext.FromDocument` and `DynamoDBContext.ToDocument` methods static or provide the alternative API for these actions.

Here is a real world example.

Consider following model:
```csharp
    [DynamoDBTable("Actors")]
    public class Actor
    {
        [DynamoDBHashKey]
        public string Name { get; set; }

        [DynamoDBProperty(Converter = typeof(AddressesConverter))]
        public IEnumerable<Address> Addresses { get; set; }
    }

    public class Address
    {
        public string Street { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
    }
```

Now let's try to implement the converter for `Addresses` list. I do want to store it with DynamoDB types so I implemented the following converter:

```csharp
    public class AddressesConverter : IPropertyConverter
    {
        private readonly DynamoDBContext _context = new DynamoDBContext();

        public object FromEntry(DynamoDBEntry entry)
        {
            var addresses = entry.AsListOfDocument();
            var list = new List<Address>();
            foreach (var address in addresses)
            {
                list.Add(_context.FromDocument<Address>(address));
            }
            return list;
        }

        public DynamoDBEntry ToEntry(object value)
        {
            var adresses = value as IEnumerable<Address>;
            if (adresses == null) return null;

            var list = new DynamoDBList();
            foreach (var address in adresses)
            {
                list.Add(_context.ToDocument(address));
            }
            return list;
        }
    }
```
With the context instance I have also exceptions in output like these:
```
Exception thrown: 'Amazon.Runtime.Internal.HttpErrorResponseException' in AWSSDK.Core.dll
Exception thrown: 'Amazon.DynamoDBv2.Model.ResourceNotFoundException' in AWSSDK.Core.dll
Exception thrown: 'Amazon.DynamoDBv2.Model.ResourceNotFoundException' in AWSSDK.Core.dll
Exception thrown: 'Amazon.DynamoDBv2.Model.ResourceNotFoundException' in AWSSDK.Core.dll
```

However, it is not an ideal solution and I cannot really understand why these methods aren't static and why there is no serializer\deserializer for it, maybe `FromDocument` and `ToDocument` can be moved out of `DynamoDBContext`.

**Comment by PavelSafronov** [comment]
If you change the `Addresses` definition to `public List<Address> Addresses`, you can remove the `DynamoDBProperty` attribute and associated converter altogether, because `DynamoDBContext` is able to convert concrete collection types and simple POCOs like the one you have listed.

That being said, the reason that these methods require a DynamoDBContext is that the context uses table information to make choices when creating the Document, which in turn requires an instance of a DynamoDBClient.

Can you provide more information about the exceptions you mentioned? Under what conditions are these thrown?

**Comment by miltador** [comment]
@PavelSafronov, then [these docs](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DotNetSDKHighLevel.html#DotNetDynamoDBContext.SupportedTypes) seems to be outdated. It is said that the collection must be of one of the primitive types. And it would be helpful to show it in [this sample](https://github.com/awslabs/aws-sdk-net-samples/blob/master/ConsoleSamples/AmazonDynamoDB_Sample/AmazonDynamoDB_Sample/DataModelSchema.cs#L60), cause it is a bit confusing that a simple POCO class is being serialized to XML.

Exceptions are thrown when I call either `FromDocument` or `ToDocument` on the context instance inside of my converter. I guess I should give the context some configured database config or something.

**Comment by PavelSafronov** [comment]
We'll work to update the docs, and if you want you can open a PR with the suggested changes against the [samples repo](https://github.com/awslabs/aws-sdk-net-samples).

Are these exceptions thrown and caught within the DynamoDBContext, or are you catching them in your code? If the latter, can you provide a code sample reproducing this?

**Comment by miltador** [comment]
@PavelSafronov, a code sample is in the issue itself. I rewrote my code to use Lists as you suggested and it works so I went on.

**Comment by michelemottini** [comment]
Being able to use `FromDocument` / `ToDocument` without having to instantiate a full `DynamoDBContext` could be pretty useful, for example if you want to store different .NET (related) classes in the same DynamoDB table
