### ISSUE TITLE
AmazonDynamoDBClient: provide synchronous API to users

### ISSUE THREAD

**Issue by miltador** [aws/aws-sdk-net#566]
I am using `AWSSDK.DynamoDBv2` together with dotnet core app.
I need to use `AmazonDynamoDBClient` to create and update table in synchronous context but the public API is async-only.
Why all the synchronous API in `AmazonDynamoDBClient` is internal? Any reason it's not public?
By the way, the [documentation samples](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/LowLevelDotNetWorkingWithTables.html) also use synchronous methods.

**Comment by PavelSafronov** [comment]
[Norm's earlier reply](https://github.com/aws/aws-sdk-net/issues/480#issuecomment-257382757) addressed this in part. The async methods encourage best practice for the platform, while the internal sync calls make it simpler for us to write higher-level abstractions such as `Table` and `DynamoDBContext`.

Thanks for pointing out the documentation issue.
