### ISSUE TITLE
SNS BroadcastReceiver not found 

### ISSUE THREAD

**Issue by Zophiel** [aws/aws-sdk-net#569]
Registration works fine. However when receiving a simple text message from SNS, android crashes the app stating it cannot find BroadcastReceiver at neither my appname path or the com.amazonaws.unity path. Latest sdk downloaded from the read me. Included google play services jar and support v4.jar.

Manifest attached:
[AndroidManifest.xml.zip](https://github.com/aws/aws-sdk-net/files/811916/AndroidManifest.xml.zip)

**Comment by gokarnm** [comment]
Can you share sample code that demonstrates the issue and details on the SDK/version you are using?

**Comment by Zophiel** [comment]
It's pretty much the latest everything. The scene im building is the default test scene included in the unity package. SDK is aws-sdk-unity_3.3.57.0

**Comment by karthiksaligrama** [comment]
The GCM registration bit is outdated in the sdk. you could take a look at code in this package https://github.com/awslabs/aws-sdk-unity-samples/tree/master/SNS/gcmhelper-src and try to implement the mechanism using the latest google play services.
