### ISSUE TITLE
Probe for Region Endpoint should not be set to false when endpoint is null

### ISSUE THREAD

**Issue by JonCubed** [aws/aws-sdk-net#570]
I have a lambda which connects to DynamoDb, for local testing I can set a region but when its not testing (live) I want it to use the region the lambda is in.

I would create the AmazonDynamoDBConfig as following where `regionEndpoint` is an optional parameter that defaults to `null`

```csharp
_dynamoDbConfig = new AmazonDynamoDBConfig
{
    RegionEndpoint = regionEndpoint
};
```

if `regionEndpoint = null` (which is when not testing) then I get `No RegionEndpoint or ServiceURL configured` 

this however will work
```csharp
 _dynamoDbConfig = new AmazonDynamoDBConfig();

if( regionEndpoint != null)
{
    _dynamoDbConfig.RegionEndpoint = regionEndpoint;
}
```

I tracked this down to [ClientConfig#L117](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/ClientConfig.cs#L117) where `probeForRegionEndpoint` is set to `false` regardless of value being set.

I think that this line should be moved to within the if statement

```csharp
set
{
    this.serviceURL = null;

    this.regionEndpoint = value;

if (this.regionEndpoint != null)
{
    this.probeForRegionEndpoint = false;
    var endpoint = this.regionEndpoint.GetEndpointForService(RegionEndpointServiceName, this.UseDualstackEndpoint);
    if (endpoint != null && endpoint.SignatureVersionOverride != null)
        this.SignatureVersion = endpoint.SignatureVersionOverride;
    }
}
```

happy to make a pr if you agree

**Comment by normj** [comment]
Thanks for pointing this out. I agree with your premise but let me review the code to see what the implications are if we made a change.

**Comment by JonCubed** [comment]
sure no problems

**Comment by sstevenkang** [comment]
Marking this as resolved.  If this solution doesn't work for you, feel free to open a new one.
