### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by auryum** [aws/aws-sdk-net#573]
Copy of my Installation Log. I got a message about not finding a remote dubugger...

3/4/2017 18:28:53 - Microsoft VSIX Installer
3/4/2017 18:28:53 - -------------------------------------------
3/4/2017 18:28:53 - vsixinstaller.exe version:
3/4/2017 18:28:53 - 15.0.26127.0 built by: D15REL
3/4/2017 18:28:53 - -------------------------------------------
3/4/2017 18:28:53 - Command line parameters:
3/4/2017 18:28:53 - C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VSIXInstaller.exe,C:\Users\fhmoh\Downloads\AWSToolkitPackage.VS2017.vsix,/installas:4220,/callingprocessid:11920
3/4/2017 18:28:53 - -------------------------------------------
3/4/2017 18:28:53 - Microsoft VSIX Installer
3/4/2017 18:28:53 - -------------------------------------------
3/4/2017 18:28:53 - Initializing Install...
3/4/2017 18:28:54 - Extension Details...
3/4/2017 18:28:54 - 	Identifier         : 12ed248b-6d4a-47eb-be9e-8eabea0ff119
3/4/2017 18:28:54 - 	Name               : AWS Toolkit for Visual Studio 2017
3/4/2017 18:28:54 - 	Author             : Amazon Web Services LLC
3/4/2017 18:28:54 - 	Version            : 1.12.0.0
3/4/2017 18:28:54 - 	Description        : The AWS Toolkit for Visual Studio is an extension for Microsoft Visual Studio that makes it easier for developers to develop, debug, and deploy .NET applications using Amazon Web Services. With the AWS Toolkit for Visual Studio, you'll be able to get started faster and be more productive when building AWS applications.
3/4/2017 18:28:54 - 	Locale             : en-US
3/4/2017 18:28:54 - 	MoreInfoURL        : http://aws.amazon.com/sdkfornet
3/4/2017 18:28:54 - 	InstalledByMSI     : False
3/4/2017 18:28:54 - 	SupportedFrameworkVersionRange : [4.6,)
3/4/2017 18:28:54 - 
3/4/2017 18:28:55 - 	SignatureState     : ValidSignature
3/4/2017 18:28:55 - 	SignedBy           : Amazon.com, Inc.
3/4/2017 18:28:55 - 	Certificate Info   : 
3/4/2017 18:28:55 - 		-------------------------------------------------------
3/4/2017 18:28:55 - 		[Subject]       : CN="Amazon.com, Inc.", OU=Amazon Web Services, O="Amazon.com, Inc.", L=Seattle, S=Washington, C=US
3/4/2017 18:28:55 - 		[Issuer]        : CN=Symantec Class 3 SHA256 Code Signing CA, OU=Symantec Trust Network, O=Symantec Corporation, C=US
3/4/2017 18:28:55 - 		[Serial Number] : 221F14F6E28EA1ABD010EA24DA1BBA0B
3/4/2017 18:28:55 - 		[Not Before]    : 6/21/2016 21:00:00
3/4/2017 18:28:55 - 		[Not After]     : 6/18/2017 20:59:59
3/4/2017 18:28:55 - 		[Thumbprint]    : 695BF9422F01FFEEC9187B1FD688185A1B299CAE
3/4/2017 18:28:55 - 
3/4/2017 18:28:55 - 	Supported Products : 
3/4/2017 18:28:55 - 		Microsoft.VisualStudio.Community
3/4/2017 18:28:55 - 			Version : [15.0,)
3/4/2017 18:28:55 - 
3/4/2017 18:28:55 - 	References         : 
3/4/2017 18:28:55 - 		-------------------------------------------------------
3/4/2017 18:28:55 - 		Identifier   : Microsoft.VisualStudio.MPF.11.0
3/4/2017 18:28:55 - 		Name         : Visual Studio MPF 11.0
3/4/2017 18:28:55 - 		Version      : [11.0]
3/4/2017 18:28:55 - 		MoreInfoURL  : 
3/4/2017 18:28:55 - 		Nested       : No
3/4/2017 18:28:55 - 
3/4/2017 18:28:55 - 	Prerequisites      : 
3/4/2017 18:28:55 - 		-------------------------------------------------------
3/4/2017 18:28:55 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
3/4/2017 18:28:55 - 		Name         : Visual Studio core editor
3/4/2017 18:28:55 - 		Version      : [15.0,)
3/4/2017 18:28:55 - 
3/4/2017 18:28:55 - Signature Details...
3/4/2017 18:28:55 - 	Extension is signed with a valid signature.
3/4/2017 18:28:55 - 
3/4/2017 18:28:55 - Searching for applicable products...
3/4/2017 18:28:55 - Found installed product - Global Location
3/4/2017 18:28:55 - Found installed product - Visual Studio Professional 2017 RC
3/4/2017 18:28:56 - PKGDEF Information: Looking for master PkgDef file, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\master.pkgdef

3/4/2017 18:28:56 - PKGDEF Information: Creating PkgDefCacheNonVolatile
3/4/2017 18:28:56 - PKGDEF Information: Double-checking master pkgdef file
3/4/2017 18:28:56 - PKGDEF Information: PkgDefManagement initialized
3/4/2017 18:28:56 - PKGDEF Information: RootFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\

3/4/2017 18:28:56 - PKGDEF Information: ShellFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\

3/4/2017 18:28:56 - PKGDEF Information: PkgDefSearchPath, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\devenv.admin.pkgdef

3/4/2017 18:28:56 - PKGDEF Information: ImageManifestSearchPath, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions;C:\Users\fhmoh\AppData\Local\Microsoft\VisualStudio\15.0_907d5d97\Extensions

3/4/2017 18:28:56 - PKGDEF Information: ApplicationExtensionsFolder, Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions

3/4/2017 18:28:56 - PKGDEF Information: "ZeroImpact" = dword:0, "MergeRegistry" = dword:3
3/4/2017 18:28:56 - PKGDEF Information: PkgDefCache flags, PKGDEF: 7005
3/4/2017 18:28:56 - PKGDEF Information: PkgDefManagement startup complete
3/4/2017 18:28:58 - The extension with ID '12ed248b-6d4a-47eb-be9e-8eabea0ff119' is not installed to Visual Studio Professional 2017 RC.
3/4/2017 18:29:08 - The following target products have been selected...
3/4/2017 18:29:08 - 	Visual Studio Professional 2017 RC
3/4/2017 18:29:08 - 
3/4/2017 18:29:10 - Beginning to install extension to Visual Studio Professional 2017 RC...
3/4/2017 18:29:11 - VSIX TaskScheduler: VSIX Auto Updatetask already exists.
3/4/2017 18:29:15 - Install Error : System.InvalidOperationException: The path '[installdir]\Common7\IDE\Remote Debugger' defined in the catalog.json file is not valid.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.ValidatePackage(VsixPackage vsixPkg, String installDir, Boolean installPerMachine, String sourceFile)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.ValidateCatalog(Catalog catalog, String installDir, Boolean installPerMachine)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

**Comment by steveataws** [comment]
Opening the catalog.json file I can see the reference to the remote debugger but none of our toolkit has a dependency on the remote debugger component, to my knowledge. Thanks for reporting it, we'll see if we can repro.

**Comment by gokarnm** [comment]
We are not able to repro this. Could you provide any more information that would help us replicate this issue.

**Comment by gokarnm** [comment]
Closing this issue. We'll need more information to repro the installer error. Feel free to reopen.
