### ISSUE TITLE
AWS options missing bucket name .netcore?

### ISSUE THREAD

**Issue by ali-raza-iftikhar** [aws/aws-sdk-net#574]
AWSOptions class missing bucketname property in .netcore is there any specific reason. 
i want to get the file url. I there a way arround other than this ?
   ```
 var request = new GetPreSignedUrlRequest
           

  {
                    
                    BucketName = awsOptions.,
                    Key = keyName,
                    Expires = DateTime.Now.AddDays(1)),
                    Protocol = Protocol.HTTP
                };
```

**Comment by normj** [comment]
By AWSOptions are you refering to `Amazon.Extensions.NETCore.Setup.AWSOptions`? These options are meant for configuring the AWS clients not for individual request parameters.

**Comment by ali-raza-iftikhar** [comment]
Okay. Thanks brother for your feedback. :-)
