### ISSUE TITLE
CloudWatch LambdaException with no error details when Invoking Lambda with an AmazonLambdaClient property

### ISSUE THREAD

**Issue by guywald** [aws/aws-sdk-net#575]
Hi,

Testing a C# Lambda function similar to the AddBlogAsync example and the Blogs Serverless Application Model template.

In the class there is a `IDynamoDBContext DDBContext { get; set; }` property (like the example). Similarly I've added the property `AmazonLambdaClient lambdaClient { get; set; }`. I forgot to add the NuGet import for AWSSDK.Lambda to project.json. This makes the invocation (via Api Gateway) return a **LambdaException** with no details on CloudWatch.

When I remove the _{get; set;}_ and just let it be a private field the error shows the details saying the NuGet library wasn't found.

I'm using Amazon.Lambda.Core 1.0.0

**Comment by normj** [comment]
How did your function compile without that dependency? Did you use our Visual Studio or dotnet CLI tooling to do the deployment?

**Comment by guywald** [comment]
@normj Visual Studio with the AWS tool to deploy. It compiled because it wasn't a compile error. The example has the `DDBContext ` as a property (With get and set), which is why wrote `lambdaClient `also as a property. Any reason it should not?

**Comment by PavelSafronov** [comment]
Are you still encountering this issue after adding the AWSSDK.Lambda dependency?

**Comment by guywald** [comment]
No. the issue focuses on the part that the AWS error was not clear.

**Comment by PavelSafronov** [comment]
Ah, got it, the issue is that Lambda did not provide a good error when a required dependency was not part of the published package. Looking into this.

**Comment by vellozzi** [comment]
The messaging for this is much clearer in the .NET Core 2.0 Lambda runtime.
Unfortunately we aren't planning to fix this in the .NET Core 1.0 Lambda runtime.
