### ISSUE TITLE
Amazon.Runtime.AmazonServiceException

### ISSUE THREAD

**Issue by progsherief** [aws/aws-sdk-net#576]
we develop a win service c# file watcher to sync any update to our amazon s3 bucket . but when file is created , this rais this exception at log:

The following is the exception message:

Amazon.Runtime.AmazonServiceException: A WebException with status ConnectFailure was thrown. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond (ip) at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress) at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)

**Comment by normj** [comment]
So does it work for file watcher update and delete events but not create events?

**Comment by progsherief** [comment]
thx dear for ur support ,
tell now we need create event only , I will try the other event .
-I notice that when I run fiddler it working ok ,
-when I close fiddler .net raise this error:


 Faulting application name: Watcher.exe, version: 1.0.0.0, time stamp:
0x58be58fe

Faulting module name: KERNELBASE.dll, version: 10.0.10240.16384, time
stamp: 0x559f3b2a

Exception code: 0xe0434352

Fault offset: 0x000b3e28

Faulting process id: 0x12e0

Faulting application start time: 0x01d2970f964da2f6

Faulting application path: D:\Multimedia
eng\Work\Watcher\Watcher\Watcher\bin\Debug\Watcher.exe

Faulting module path: C:\Windows\SYSTEM32\KERNELBASE.dll

Report Id: 2ccb2b43-096e-4b8f-b548-f56a64a1497d

Faulting package full name:

Faulting package-relative application ID:



----------------

and this error :

Application: Watcher.exe


Framework Version: v4.0.30319


Description: The process was terminated due to an unhandled exception.


Exception Info: System.NotSupportedException


at System.IO.FileStream.Init(System.String, System.IO.FileMode,
System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32,
System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean,
Boolean, Boolean)


at System.IO.FileStream..ctor(System.String, System.IO.FileMode,
System.IO.FileAccess, System.IO.FileShare, Int32, System.IO.FileOptions,
System.String, Boolean, Boolean, Boolean)


at System.IO.StreamWriter.CreateFile(System.String, Boolean, Boolean)


at System.IO.StreamWriter..ctor(System.String, Boolean,
System.Text.Encoding, Int32, Boolean)


at System.IO.StreamWriter..ctor(System.String, Boolean)


at Watcher.Watcher.FolderWatcher_Created(System.Object,
System.IO.FileSystemEventArgs)


at System.IO.FileSystemWatcher.OnCreated(System.IO.FileSystemEventArgs)


at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(Int32,
System.String)


at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32, UInt32,
System.Threading.NativeOverlapped*)


at
System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32,
UInt32, System.Threading.NativeOverlapped*)




thx for ur help

**Comment by PavelSafronov** [comment]
Can you post the code that produces these errors?
Are other S3 operations (ListBuckets, ListObjects, etc.) working correctly?
