### ISSUE TITLE
What is the Android permission GET_ACCOUNTS used for?

### ISSUE THREAD

**Issue by Giacom** [aws/aws-sdk-net#577]
Hi, with Unity and with the latest version of Android I noticed that GET_ACCOUNTS will ask the user to allow access to their contacts. I was wondering what you use this permission for so I can see if it is possible to remove it, as I only use the Cognito Sync service.

Thanks.

**Comment by PavelSafronov** [comment]
Which SDK are you using?

**Comment by Giacom** [comment]
.net SDK for Unity

**Comment by karthiksaligrama** [comment]
are these permissions getting added when you try to export it as Android project? 

The SDK doesn't require any permissions except for ACCESS_NETWORK_STATE, and INTERNET.

**Comment by gokarnm** [comment]
Closing this issue, the SDK only requires ACCESS_NETWORK_STATE, and INTERNET permissions. The GET_ACCOUNTS permission may be added by Unity IDE. Feel free to reopen if you feel this is an SDK issue.

**Comment by oddgames-david** [comment]
![image](https://user-images.githubusercontent.com/1932174/61421883-a2bd7280-a93b-11e9-9606-d4b77e31d6ff.png)

The unity packages add a manifest with GET_ACCOUNTS, I'm using Kinesis and S3
