### ISSUE TITLE
Cognito remembering Devices isn't not working?

### ISSUE THREAD

**Issue by BBNicolas** [aws/aws-sdk-net#578]
I've set up Cognito to always remember the user's device and when authenticating my user I'm getting a NewDeviceMetadata object with a device group and device key, but when checking the device list of the user there aren't any devices remembered.
This is a problem when trying to use the refresh token, since Cognito is set to always remember the devices and therefore a device is also required for a refresh.
For now I simply set Cognito to never remember the devices, but I would prefer to have this working instead of avoiding the problem.

**Comment by PavelSafronov** [comment]
Can you clarify if this is an issue you are experiencing with the service or with the SDK?

**Comment by BBNicolas** [comment]
I'm guessing it's more a service problem, but then again, I haven't really found anyone else having this problem. To make the login request I'm pretty much using the same code as dbeattie71 here: [https://gist.github.com/dbeattie71/44ea3a13145f185d303e620c299ab1c5](url)
And like said above I'm getting a device key in response, but when listing the devices of the user there aren't any. So I was wondering if I need to do some sort of validation for that device key to be remembered on cognito.

**Comment by PavelSafronov** [comment]
Seems like this is a question for the Cognito service team and is best suited for their [AWS forum](https://forums.aws.amazon.com/forum.jspa?forumID=173).
Resolving for now. If you determine that you've located a bug with the .NET SDK for this scenario, feel free to re-open this issue or create a new one.

**Comment by BBNicolas** [comment]
I would like to reopening this issue, since I've tested logging in with an iPad which uses the AWS iOS SDK and it worked, the iPad was listed on the AWS Cognito console so it is not a service problem. Now I'd like to know how to do the same but using the .NET SDK. Is there any method that is supposed to be called once a login has been made to remember the device or is it suppose to be automatic on logon?

**Comment by PavelSafronov** [comment]
Can you share the working iOS SDK code and the .NET SDK code that is not working for you?

**Comment by BBNicolas** [comment]
An example of how I register, validate and login a user using .NET can be found here: [https://gist.github.com/BBNicolas/5ab3f1f8c604ebe2e4ecf14c35487495](https://gist.github.com/BBNicolas/5ab3f1f8c604ebe2e4ecf14c35487495)

For the IOS example it has been made by another development team so I don't have the source code.

**Comment by BBNicolas** [comment]
Here is the register IOS code: [https://gist.github.com/BBNicolas/c88157590cc0eb89684fee6f2b99d8f8](https://gist.github.com/BBNicolas/c88157590cc0eb89684fee6f2b99d8f8)

**Comment by PavelSafronov** [comment]
I'm unfamiliar with the specific details of Cognito and how it applies here (hence the recommendation to consult the forums), but the below snippet from [this blog post](https://aws.amazon.com/blogs/mobile/tracking-and-remembering-devices-using-amazon-cognito-your-user-pools/) seems to be relevant:
>  Each SDK can take a callback during the authentication call, which defines how users are asked if they want to remember the device. This authentication call consumes the UpdateDeviceStatus API. That API can be called any time to update the status as needed. **The mobile SDKs use convenience wrappers around this method to make the calls more intuitive.**

The **last sentence** may explain why you are seeing a difference of behaviors between the iOS SDK and the .NET SDK: the iOS SDK may be obfuscating this logic and/or performing the calls on your behalf. The .NET code you supplied doesn't appear to do this. The DEVICE_KEY is also being set to null, though I'm not sure if that's relevant.

**Comment by BBNicolas** [comment]
I've read thought the blog and this is what I was missing:

> The path to getting these credentials is as follows:
> 
>      
> 
> 1. Every time the user signs in with a new device, the client is given the device key at the end of a successful authentication 
> 2. From this key, the client creates a secret, using the secure remote password (SRP) protocol, and generates a salt and password verifier.
> 3. With that salt, verifier, and the key it was originally given, the client calls the ConfirmDevice API remotely. It is only then that Amazon Cognito begins tracking this device. During this entire flow, the secret remains on only the physical device.

I did my best to create a .NET version of the "generateHashDevice" method based on the JS code [here](https://github.com/aws/amazon-cognito-identity-js/blob/master/src/AuthenticationHelper.js)
and I've updated my code here: [ https://gist.github.com/BBNicolas/5ab3f1f8c604ebe2e4ecf14c35487495]( https://gist.github.com/BBNicolas/5ab3f1f8c604ebe2e4ecf14c35487495)

The device key is now showing on the AWS Cognito Console and using the provided device key while refreshing now works. But the .NET SDK really needs to wrap these calls like the other SDK do, as for now our only solution is to go thought the other SDK and translate bits of code too .NET.

NOTE:
I've only tested using the device key in a refresh call and I haven't tried other calls which might need this device key as well. Like login which when given shouldn't create a new device key, but use the already remembered one. (Passing DEVICE_KEY set as null creates a new one)

**Comment by PavelSafronov** [comment]
Glad to hear that you've been able to get your usecase working.
You are correct, the .NET SDK is missing some of the convenience wrappers that are provided by the mobile SDKs called out in the blog post. We have a feature on our backlog to add similar functionality, but currently do not have an ETA.

**Comment by niraj-bpsoftware** [comment]
Is this functionality implemented for .NET mobile SDK? I am not able to find it in AWSSDK.Extensions.CognitoAuthentication library as well.

> Glad to hear that you've been able to get your usecase working.
> You are correct, the .NET SDK is missing some of the convenience wrappers that are provided by the mobile SDKs called out in the blog post. We have a feature on our backlog to add similar functionality, but currently do not have an ETA.
