### ISSUE TITLE
Lex PostContentRequest and PostContentResponse

### ISSUE THREAD

**Issue by acmayberry** [aws/aws-sdk-net#581]
I do not see either of these available in the current SDK.  However, they are described in the documentation here:

http://docs.aws.amazon.com/lex/latest/dg/API_PostContent.html 

and that document references the AWS SDK for .NET as having implemented this functionality.

It is my understanding that this functionality is required for voice interaction with AWS Lex.  Is this correct?

**Comment by PavelSafronov** [comment]
You are correct, only PostText is supported at the moment. PostContent may eventually be supported, though I cannot comment on if or when.

**Comment by PavelSafronov** [comment]
Resolving, as there is currently no actionable work here.
