### ISSUE TITLE
Use MTurk sandbox endpoint for testing?

### ISSUE THREAD

**Issue by mmmscott** [aws/aws-sdk-net#583]
Was looking through the source code and trying to use the MTurk dll but couldn't find a way to use the sandbox endpoint for testing. Is there a way to do this?

**Comment by PavelSafronov** [comment]
I think the response to [this issue](https://github.com/aws/aws-sdk-js/issues/1390) should help you out.

**Comment by sstevenkang** [comment]
@mmmscott, I think the link @PavelSafronov provided contains all the necessary information for you to use the sandbox endpoint.  I am going to close this, but feel free to reopen it!
