### ISSUE TITLE
Role authentication fails on ECS

### ISSUE THREAD

**Issue by Layoric** [aws/aws-sdk-net#588]
I've been running an application on ECS that picks up credentials using the ECS Service Role that has been assigned to the ECS service and give S3 permissions. 

I recently deployed with the newst version of AWSSDK.S3 dependency and started getting the following errors.

`One or more errors occurred. (Unable to retrieve credentials. Message = "The type Amazon.Runtime.URIBasedRefreshingCredentialHelper+SecurityCredentials doesn't have the property 'RoleArn'".)`

I've rolled back to 3.3.5.7 and everything is working as expected.

I'm running on Docker 1.12.6, Dotnet Core 1.0.3.

Let me know if you need any more information.

**Comment by sstevenkang** [comment]
Hi @Layoric , thanks for reporting the issue.  We think this is due to a bad merge and have a fix coming soon.

**Comment by vellozzi** [comment]
This issue has been fixed in AWSSDK.ECS 3.3.3.3

Please let us know if you have any further issues.
