### ISSUE TITLE
User pools in the Unity SDK. Supported? Question

### ISSUE THREAD

**Issue by CostelloNicho** [aws/aws-sdk-net#590]
Does the SDK for Unity support User pools? Can't seem to find any of that functionality. If not, any ETA? There has been a post on the AWS forums about his since October of 2016. 

Thanks!

**Comment by PavelSafronov** [comment]
At this time the SDK does not support Cognito User Pools for the Unity SDK. We have this feature on our backlog, but as is standard Amazon policy, we cannot comment on when this will be available.

**Comment by sstevenkang** [comment]
We have a different issue with lengthy discussions related to this here: https://github.com/aws/aws-sdk-net/issues/495
