### ISSUE TITLE
AmazonKinesisClient: should I use a single instance per app?

### ISSUE THREAD

**Issue by stephen-swensen** [aws/aws-sdk-net#592]
Hi -

I am wondering what best practices are for creating and disposing of `AmazonKinesisClient`s. Should it be used as a singleton for the entire app (is it thread safe / optimized for concurrent use internally?), or should it be created and disposed in a narrower scope.

Thanks,

Stephen

**Comment by PavelSafronov** [comment]
All .NET SDK clients are thread-safe that you can keep a single one around, but they're also light-weight so you can create one in a narrower scope. So it depends on your use-case: if you are going to use a single set of credentials and are going to access Kinesis in the same region for your entire application, a singleton is a sensible pattern.

**Comment by stephen-swensen** [comment]
@PavelSafronov thanks for insight, good to know!

**Comment by PavelSafronov** [comment]
NP. Closing issue, but feel free to reopen if you have more questions.
