### ISSUE TITLE
Release Notes are out of date

### ISSUE THREAD

**Issue by RobBiddle** [aws/aws-sdk-net#594]
Release Notes here: https://aws.amazon.com/releasenotes/PowerShell are very far behind.

**Comment by PavelSafronov** [comment]
After the 3.1.0 version bump the versions for both PowerShell Tools and the SDK are now in sync, so the [SDK changelog](https://github.com/aws/aws-sdk-net/blob/master/SDK.CHANGELOG.md) corresponds to changes for both SDK and PowerShell. Please refer to the SDK changelog for information on what changed in the PowerShell tools.
