### ISSUE TITLE
Feature request: Getting instance credentials (for invoking ApiGateway)

### ISSUE THREAD

**Issue by mbp** [aws/aws-sdk-net#597]
When ApiGateway endpoint is set up to use  `x-amazon-apigateway-auth: type: aws_iam`, we need to sign every request with access key / secret key (AWS Signature 4).

In order to get this for a running EC2 instance (iam instance profile), we need to do call meta data service endpoint `http://169.254.169.254/latest/meta-data/iam/security-credentials/{role}`

 It would be nice if there was a public method in the AWS SDK, returning these credentials for me, instead of me manually writing code to get it from the meta data service.
It is my understanding that the AWS SDK already does this "under the hood" on normal AWS API calls

**Comment by normj** [comment]
You can create an instance of `Amazon.Runtime.InstanceProfileAWSCredentials` on an EC2 instance and then call `GetCredentials()` get to get the credentials.

**Comment by Kralizek** [comment]
Does the SDK have a way to sign HttpClient requests? I couldn't find anything but samples of code on how to sign a request manually.

**Comment by PavelSafronov** [comment]
The SDK does not have a generic method to sign HTTP requests.

The signer functionality is available [here](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Internal/Auth/AWS4Signer.cs), so you can copy the relevant pieces of code or use AWS4Signer class directly, but keep in mind that this class is in an Internal namespace and so it can be changed and/or removed at any time.

**Comment by joewaid** [comment]
Do you have any plans to expose the AWS4Signer functionality publicly in the .net sdk? It seems like other aws sdks have publicly available methods to do this.
