### ISSUE TITLE
3.3.5 broke GetPreSignedURL 

### ISSUE THREAD

**Issue by Spongman** [aws/aws-sdk-net#599]
reopening #587 . please don't prematurely close issues. the message it sends, quite clearly is "**we don't care about your feedback. go away**".

the format of the URL generated by GetPreSignedURL was changed in release 3.3.5.

the new style of URL no longer work against S3 - it returns a "SignatureDoesNotMatch" error.

pre-3.3.5 generated URLs that looked like this:
````
https://mybucket.s3-us-west-2.amazonaws.com/mykey?AWSAccessKeyId=<MyKeyID>&Expires=1489619417&Signature=<Signature>&x-amz-meta-download=140&branch=development&machine=something
````

post-3.3.5 URLs look like this:
````
https://mybucket.s3-us-west-2.amazonaws.com/mykey?X-Amz-Expires=86400&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=<Signature>%2F20170314%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20170314T231800Z&X-Amz-SignedHeaders=host%3Bx-amz-meta-download&X-Amz-Signature=<Signature>&x-amz-meta-download=140&branch=development&machine=something
````

notice how the parameters passed are completely different.

**Comment by PavelSafronov** [comment]
Reopened issue #587. As this is clearly a duplicate, resolving in favor of 587.
