### ISSUE TITLE
XAmzContentSHA256Mismatch when putting objects in dotnet core app

### ISSUE THREAD

**Issue by acornies** [aws/aws-sdk-net#607]
I'm trying to test the following code in a dotnet core v1.1.1 app:

```
var putRequest = new PutObjectRequest();
putRequest.BucketName = "samplebucket";
putRequest.Key = "this-is-a-test.txt";
putRequest.ContentBody = "this is a test";
            
var putResponse = await _s3Client.PutObjectAsync(putRequest);
```

I've also tried various combinations of the TransferUtility class but the result is always a XAmzContentSHA256Mismatch error. I'm using the AWSSDK.S3: 3.3.5.10 version of .net client.

I can successfully list, create, delete buckets but I have problems in putting objects. I also tried switching the signature versions of the s3 client from version 2 to version 4 with no luck.

I should also note that I'm testing against a local Ceph S3 endpoint running Jewel. Is there a known incompatibility issue here?

**Comment by PavelSafronov** [comment]
Do you only encounter errors when using Ceph S3 endpoint? Does your application work against public S3?

**Comment by acornies** [comment]
It does work against s3.amazonaws.com, so I suppose it's not technically an issue for this repository. Any more insight would be helpful as this is probably an issue with my local Ceph docker container. Using this btw: https://github.com/ceph/ceph-docker/tree/master/ceph-releases/jewel/ubuntu/14.04/demo.

**Comment by PavelSafronov** [comment]
You're right, this question does seem to be more appropriate for the Ceph repo, as they would have the required expertise to advise about this error.
Resolving. Feel free to re-open if your investigation leads to an issue with the AWS SDK for .NET.
