### ISSUE TITLE
IAmazonS3 missing HeadBucket

### ISSUE THREAD

**Issue by jasoncwik** [aws/aws-sdk-net#616]
It appears that the IAmazonS3 interface is missing calls for HeadBucket, but if you look at the implementation classes AmazonS3Client, it exists.  Any reason it's in the implementation but not the interface?

**Comment by jasoncwik** [comment]
Actually, looking closer, the HeadBucket in AmazonS3Client is marked internal as well, so it's not available to developers.

**Comment by PavelSafronov** [comment]
It's been a while, but I think we decided to exclude this operation from the public SDK because `AmazonS3Util.DoesS3BucketExist` performs a similar check and we wanted to avoid confusion. Will `DoesS3BucketExist` work for your use-case?

**Comment by jasoncwik** [comment]
Hmm... strange placement, but yes that meets our needs.
