### ISSUE TITLE
AmazonS3Util.DoesS3BucketExistAsync returns True when it gets HTTP/1.1 403 Forbidden

### ISSUE THREAD

**Issue by andymac4182** [aws/aws-sdk-net#618]
I noticed I was receiving a response saying bucket existed when it didn't exist in the interface. Turned out to be related to credentials being incorrect. I have reproduced this in LINQPad and Fiddler.

```
var aws = new AmazonS3Client("asdf", "asdf", RegionEndpoint.APSoutheast2);
(await AmazonS3Util.DoesS3BucketExistAsync(aws, $"DoesntExist{Guid.NewGuid()}")).Dump();
```

I believe its related to this line https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/S3/Custom/Util/AmazonS3Util.cs#L607

**Comment by PavelSafronov** [comment]
S3 responds with `403 Forbidden` in at least two cases:
1. when a bucket exists but you don't have access to it, for instance if you make this call against someone else's bucket
2. when the specified keys are incorrect

I don't believe there's a way for the SDK to differentiate between case 1 and 2.

**Comment by andymac4182** [comment]
We use this for 2 things at the moment. To check if a bucket we want is created and also to stop conflicts with existing buckets that we or someone else own. The UI currently informs you of this before you even get paste the first step. Is there maybe a better API call that could be done?

**Comment by PavelSafronov** [comment]
Can you clarify which UI you are referring to?

**Comment by andymac4182** [comment]
I was referring to the S3 UI. 

Maybe the better solution would be for me to call a method that I can use to confirm my credentials are correct in our application?

**Comment by PavelSafronov** [comment]
That sounds like a good idea. You can first make (for example) a `ListBuckets` call to verify that the keys you are using are correct, then call `DoesS3BucketExist` to check if the bucket does indeed exist.
