### ISSUE TITLE
AmazonS3Client.putObject Metadata not saved properly

### ISSUE THREAD

**Issue by msully62** [aws/aws-sdk-net#619]
When attempting to create a new S3 object I cannot save Metadata values with the object when using either Headers or Metadata collections on the PutObjectRequest.  Setting metadata explicitly with PutObjectRequest.ContentType DOES work however.  

See notes in the example below on what works and what doesn't.

```
IAmazonS3 client = new AmazonS3Client("",
    "+", RegionEndpoint.USWest2);

PutObjectRequest putRequest = new PutObjectRequest
{
    BucketName = bucketName,
    Key = keyName
};
// putRequest.Headers.ContentType = "image/jpeg";   **BAD: SAVES OBJECT BUT NOT METADATA**
//putRequest.Metadata.Add("content-type", "image/jpeg");  **BAD: SAVES OBJECT BUT NOT METADATA **
putRequest.ContentType = "image/png";   **GOOD: SAVES OBJECT AND METADATA**

putRequest.FilePath = filename;

PutObjectResponse putResponse = client.PutObject(putRequest);
```

**Comment by sstevenkang** [comment]
I can't repro this. Which version of the SDK you are using?  In the current version [`PutObjectRqeuest.ContentType` ](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/S3/Custom/Model/PutObjectRequest.cs#L351)is a simple alias for 'PutObjectRequest.Headers.ContentType'.  

In the example code you provided the commented out code i setting "image/jpeg" and the uncommented code is setting "image/png".  Was that intentional?

**Comment by msully62** [comment]
I am using version 3.3.5.12 for .Net.  Do you have a sample of it working for you?  I assumed that PutObjectRequest.ContentType was an alias as you mentioned, but I can't get the meta data to save no matter what I try.  Thanks

**Comment by msully62** [comment]
Actually, now my "Good" method is not working either.

**Comment by sstevenkang** [comment]
Ah, I think I figured out what's going on.  I think you are expecting the metadata key of `content-type` to be stored as `content-type` key, but all metadata properties will have `x-amz-meta-` prefix.  Thus, when you make the call `putRequest.Metadata.Add("content-type", "image/jpeg")` it will be stored as key value pair of `x-amz-meta-content-type` and `image/jpeg`.  

What I am curious is why `putRequest.Headers.ContentType = "image/jpeg"` is not working out for you.  How are you verifying that content type is not set?  I am using AWS Web Console to verify the metadata properties are set correctly after the sample code you provided.

**Comment by msully62** [comment]
Hi.  I know I had this working on Friday but now I’m back to square one.  I’ve tried all of the following….

putRequest.Headers.ContentType = “image/jpeg”
putRequest.ContentType = “image/jpeg”
putRequest.Metadata.Add(“content-type”, “image/jpeg”)

I view the Object in my S3 bucket after created and the MetaData contains nothing at all.  I’ve been looking at the SDK code this afternoon and like you said the .ContentType is just setting the Headers, so I don’t get why it wouldn’t work.. Do you think there’s any chance it could be a permissions issue on our S3 bucket?. I can’t imagine why it would create the object but not the meta data?

Thank you for responding.  I’d appreciate any suggestions you might have.

Thank you,
Michael


STARZ | A LIONSGATE COMPANY

**Comment by msully62** [comment]
Here’s another interesting thing.  I tried to add meta data to my object via the console and got the error shown in the attachment.  I can’t believe there would be permissions that granular?



STARZ | A LIONSGATE COMPANY

**Comment by msully62** [comment]
I've discovered that this is a permissions/role issue.  I was toggling between Admin role and my IAM and I'm able to see the MetaData tags when using my IAM.  So it appears that the tags were always being added but I couldn't see them when under the Admin role.  I don't fully understand why I wouldn't be able to view them but I should be good now.

**Comment by msully62** [comment]
Thanks for your help with this, I appreciate it.
