### ISSUE TITLE
Inconsistent configuration section names in SDK and its documentation

### ISSUE THREAD

**Issue by betabandido** [aws/aws-sdk-net#624]
While trying to use an `app.config` file to store my AWS profile and some DynamoDB-related information, I have found out some inconsistencies between the section names actually supported by the SDK and the ones described in the documentation.

According to http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-ref.html#net-dg-config-ref the way to specify the profile name is by using the `profileName` tag as in:

```
<aws
  profileName="development"
  <!-- ... -->
</aws>
```

However, in [ConfigurationExtensions.cs](https://github.com/aws/aws-sdk-net/blob/4fc4edc575e8ea5180322b3490303f30ed658906/extensions/src/AWSSDK.Extensions.NETCore.Setup/ConfigurationExtensions.cs#L101) a tag named `profile` is looked for (instead of `profileName`).

I am loading the `app.config` file as follows:

```
Configuration = new ConfigurationBuilder()
    .SetBasePath(Directory.GetCurrentDirectory())
    .AddXmlFile("app.config")
    .Build();
```

The following statement:

`Configuration.GetAWSOptions().Profile`

returns `null` if `profileName` is used, but it returns the correct profile name if `profile` is used instead.

A similar, but probably unrelated problem, occurs when trying to specify the table name prefix in the `app.config` file. According to the documentation (same link as above), the way to specify the prefix is as follows:

```
<aws
  <!-- ... -->
  <dynamoDB>
    <dynamoDBContext
      tableNamePrefix="string value">
   </dynamoDBContext>
  </dynamoDB>
</aws>
```

But, in [AWSConfigs.DynamoDB.cs](https://github.com/aws/aws-sdk-net/blob/3ea604ff2c90cebbb7e76cb8da89a75955c2400b/sdk/src/Services/DynamoDBv2/Custom/AWSConfigs.DynamoDB.cs#L63) the key to access this property is defined as:

`public const string DynamoDBContextTableNamePrefixKey = "AWS.DynamoDBContext.TableNamePrefix";`

It seems the `dynamoDB` tag is missing (compared to the documentation). Moreover, I believe that the table name prefix is intended to be read from the configuration in the following statement:

`this.TableNamePrefix = AWSConfigs.GetConfig(AWSConfigsDynamoDB.DynamoDBContextTableNamePrefixKey);`

See code [here](https://github.com/aws/aws-sdk-net/blob/3ea604ff2c90cebbb7e76cb8da89a75955c2400b/sdk/src/Services/DynamoDBv2/Custom/AWSConfigs.DynamoDB.cs#L168).

But, if I am not mistaken, that method is implemented [here](https://github.com/aws/aws-sdk-net/blob/37b2546044248de151a6ce47641ba096728fb5cb/sdk/src/Core/_coreclr/AWSConfigs.coreclr.cs#L35) and it just returns `null`:

```
public static string GetConfig(string name)
{
    return null;
}
```

So, it seems the `tableNamePrefix` tag might not be supported for .NET core.

I have managed to have it working by adding the following statements to my application:

```
AWSConfigsDynamoDB.Context.TableNamePrefix = Configuration
    .GetSection("aws")?
    .GetSection("dynamoDB")?
    .GetSection("dynamoDBContext")?["tableNamePrefix"];
```

Where `Configuration` is the result of using the `ConfigurationBuilder` (as shown earlier).

But, I wonder whether there is a better way to do it.

## Environment

* AWSSDK.Core version used: 3.3.12
* Operating System and version: Windows 10
* Visual Studio version: 2017
* Targeted .NET platform: .NET core 1.0

## .NET Core Info

* .NET Core version used for development: .NET core 1.0
* .NET Core version installed in the environment where application runs: .NET core 1.0
* Output of `dotnet --info`: 
```
.NET Command Line Tools (1.0.3)

Product Information:
 Version:            1.0.3
 Commit SHA-1 hash:  37224c9917

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.3
```

* Contents of project.json/project.csproj: 
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.Core" Version="3.3.12" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.3.4.6" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.3.0.3" />
    <PackageReference Include="Microsoft.Extensions.CommandLineUtils" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Xml" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="1.1.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="app.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
```

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by sstevenkang** [comment]
Hi, it looks like you are looking at the wrong documentation.  Notice that there's a separate [configuration documentation page](http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-netcore.html) for .Net Core which specifies `Profile` as the key instead of `profileName`.

Regarding the DynamoDB problem you encountered, are you creating the service client as suggested in the documentation?

```cs
var options = Configuration.GetAWSOptions();
IAmazonS3 client = options.CreateServiceClient<IAmazonS3>();
```

**Comment by betabandido** [comment]
What about the documentation for other fields such as `tableNamePrefix`? Do they follow the format described in the page I referenced?

Yes, I create the client following the approach you mentioned.

I created a [minimal example](https://github.com/betabandido/AWS-TablePrefix) showing the problem where `DynamoDBContextConfig` is not initialized with the expected table name prefix. In the `appsettings.json` file I placed the `tableNamePrefix` setting both directly under the AWS node and under the DynamoDB node (as it is not very clear from the documentation where it should be placed).

**Comment by sstevenkang** [comment]
No they do not.  `System.Configuration` namespace is not supported in CoreCLR and this breaks how service specific configuration is consumed by each client. The `AWSSDK.Extensions.NETCore.Setup` is our package that supports a few critical configurations like credentials & region.

We'll update the docs to make this clear.

**Comment by betabandido** [comment]
Is there any recommended way to set up the table name prefix from the configuration file in .NET core?

**Comment by PavelSafronov** [comment]
There is no mechanism yet for the .NET Core version of the SDK to get the value from the file, but once you do get this value from a configuration into your application, you can apply it globally by setting `AWSConfigsDynamoDB.Context.TableNamePrefix`.

**Comment by rtellez91** [comment]
> 
> 
> There is no mechanism yet for the .NET Core version of the SDK to get the value from the file, but once you do get this value from a configuration into your application, you can apply it globally by setting `AWSConfigsDynamoDB.Context.TableNamePrefix`.

Is there any better way to do this? I read that way would be deprecated.

**Comment by unleashed-jamest** [comment]
This is still broken in 2020?
