### ISSUE TITLE
How can configure  WAF ( web app firewall )

### ISSUE THREAD

**Issue by sun2sun** [aws/aws-sdk-net#625]
Hello ,
i try to install  AWSSDK - AWS WAF 3.3.1.15  from nuget in visual studio 2013 and it install completely.
now how can start or configure WAF to protect my website from injection or xss or common attack.
please guide me.

**Comment by gokarnm** [comment]
Hi @sun2sun, it does not seem like you are facing any issues with the SDK. If you are looking for resources to use the service, here is the [Getting Started](http://docs.aws.amazon.com/waf/latest/developerguide/getting-started.html) developer guide. You can also ask questions on [WAF Discussion Forum](https://forums.aws.amazon.com/forum.jspa?forumID=207).

Closing the issue, feel free to reopen.
