### ISSUE TITLE
Make UploadPartResponseUnmarshaller public

### ISSUE THREAD

**Issue by smbecker** [aws/aws-sdk-net#628]
It appears that most of the unmarshallers (at least in the S3 client) are public. However, `UploadPartResponseUnmarshaller` is not. Is there a reason why? Can it be made public?

## Expected Behavior
Expect `UploadPartResponseUnmarshaller` to be publicly accessible.

## Current Behavior
`UploadPartResponseUnmarshaller` is currently internal.

## Possible Solution
Currently, I have to work-around this limitation using reflection:

```c#
var uploadUnmarshallerType = typeof(UploadPartRequestMarshaller).GetTypeInfo()
  .Assembly.GetType("Amazon.S3.Model.Internal.MarshallTransformations.UploadPartResponseUnmarshaller");
uploadUnmarshaller = (ResponseUnmarshaller)uploadUnmarshallerType.GetRuntimeProperty("Instance").GetValue(null);
```

## Your Environment
* AWSSDK.Core version used: 3.3.8
* AWSSDK.S3 version used: 3.3.5.8
* Operating System and version: Windows, Mac, and Linux
* Visual Studio version: VS 2015
* Targeted .NET platform: .Net CoreCLR

## .NET Core Info
* .NET Core version used for development: 1.0.0-preview2-1-003177
* .NET Core version installed in the environment where application runs: 1.0.0-preview2-1-003177
* Output of `dotnet --info`: 
```
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
```

**Comment by PavelSafronov** [comment]
This was an oversight. Every other service's marshallers are generated and public, except S3's, and this is one of the uneven edges. We'll make all the marshallers public.

Out of curiosity, what is your use-case of creating and using the marshaller manually?

**Comment by smbecker** [comment]
I have a custom implementation of `IHttpRequestFactory`. In my code, I needed to pass some contextual information (mostly tracing) down to the `IHttpRequest` object. The only way that I could find to do that was through deriving from `RequestContext` and passing that with the call. Consequently, the only way that I could find to do that was effectively duplicate the logic of `UploadPartAsync` and `InvokeAsync` on the S3 client. A bit cumbersome but still glad that the necessary extension points were available to make it happen.

**Comment by gokarnm** [comment]
If your goal is to use a custom `IHttpRequestFactory` instead of the default one, you can achieve it using the following steps. Does this help?

1. Subclass the `AmazonS3Client` and override [`CustomizeRuntimePipeline`](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/S3/Generated/_bcl45/AmazonS3Client.cs#L216) method.

2. Replace the default HttpHandler with a custom one. We need to call the base method to retain customizations in the parent class.

```
protected override void CustomizeRuntimePipeline(RuntimePipeline pipeline)
{
    base.CustomizeRuntimePipeline(pipeline);

    var myHttpRequestFactory = [Initialize your IHttpRequestFactory implementation]
    var myHttpHandler = new Amazon.Runtime.Internal.HttpHandler<System.Net.Http.HttpContent>(
        httpRequestFactory, this);
    pipeline.ReplaceHandler<Amazon.Runtime.Internal.HttpHandler>(myHttpHandler);
}
```

**Comment by smbecker** [comment]
I already have the custom `IHttpRequestFactory` wired in. Not sure `BeforeRequestEvent` would work for my use case since it is a shared S3 client, so call-specific contextual information wouldn't be available in a shared client event handler.

**Comment by PavelSafronov** [comment]
All S3 marshallers have been made public, closing.

**Comment by smbecker** [comment]
And I see that it has already been pushed to nuget, thanks.
