### ISSUE TITLE
SessionAttributes in Lex PostContent 

### ISSUE THREAD

**Issue by anthonyjhd** [aws/aws-sdk-net#630]
I'm having an issue sending SessionAttributes to lex in PostContent. Even using the value in the sample [here](http://docs.aws.amazon.com/lex/latest/dg/API_runtime_PostContent.html#API_runtime_PostContent_Examples), I get the error "Failed to decode session attributes. Session attributes should be a Base64 encoded json map of String to String".

 `request.SessionAttributes = "eyJ1c2VyTmFtZSI6IkJvYiJ9"; `

eyJ1c2VyTmFtZSI6IkJvYiJ9 decodes to {"userName":"Bob"}

## Current Behavior
Get error: "Failed to decode session attributes. Session attributes should be a Base64 encoded json map of String to String"

## Your Environment
3.3.1.1 of AWSSDK.Lex
3.3.12 of AWSSDK.Core

**Comment by PavelSafronov** [comment]
That sample is for the API in general. When using the .NET SDK you should simply provide the JSON string, the SDK will base64 encode it for you.
