### ISSUE TITLE
"The path is not of a legal form" exception when S3 initialized from memory-loaded assembly

### ISSUE THREAD

**Issue by agclark81** [aws/aws-sdk-net#631]
A bug was introduced in commit https://github.com/aws/aws-sdk-net/commit/28296c79805440bab799a072f59c65e701ad23e1 when GetEndpointJsonSourceStream was added. This method attempts to find an endpoint JSON file in the same directory as the running assembly, using Path.GetDirectoryName(typeof(RegionEndpointProviderV3).Assembly.Location). When an assembly is loaded as a byte array, however, Assembly.Location is an empty string, as per https://msdn.microsoft.com/en-us/library/system.reflection.assembly.location(v=vs.110).aspx. This causes an exception to be thrown on Path.GetDirectoryName, since it expects a non-empty string.

The following exception is thrown:

System.ArgumentException: The path is not of a legal form.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at Amazon.Internal.RegionEndpointProviderV3.GetEndpointJsonSourceStream()
   at Amazon.Internal.RegionEndpointProviderV3..ctor()
   at Amazon.RegionEndpoint.get_RegionEndpointProvider()
   at Amazon.RegionEndpoint.get_InternedRegionEndpoint()
   at Amazon.Runtime.ClientConfig.set_RegionEndpoint(RegionEndpoint value)

I'm happy to submit a PR for a fix, but it should be sufficient just to skip over the new code addition if typeof(RegionEndpointProviderV3).Assembly.Location == string.Empty.

**Comment by sstevenkang** [comment]
Thanks for reporting this.  Looking into this now.  Seems like straight forward fix.

**Comment by catester** [comment]
Thanks @agclark81 for reporting this early on and thanks @sstevenkang for fixing it quickly :) I was shocked with this error after deploying, it happened only when the DLL was embedded, i.e. loaded from bytes so it was a subtle error which could not be detected during development.

**Comment by PavelSafronov** [comment]
This has been fixed in the latest version of AWSSDK.Core. Closing.
