### ISSUE TITLE
Add interfaces for classes with internal constructors as returned by IDynamoDBContext methods

### ISSUE THREAD

**Issue by mbp** [aws/aws-sdk-net#632]
When working with `Amazon.DynamoDBv2.DataModel`, specifically `IDynamoDBContext`, it is useful to be able to mock the interface in a unit test.

However it is not possible to mock many of the types being returned by methods on the `IDynamoDBContext` interface.

Examples are `Table` and `BatchGet`.

As an example with NSubstitute

    dynamoDbContext.GetTargetTable<MyModel>().ReturnsForAnyArgs(new Table());

However it is not possible to create an instance of `Table` because it has only internal constructors. For the same reason it is also not possible to mock the class.

**Comment by PavelSafronov** [comment]
Looks like this is related to #604, but concerns a slightly different set of files. This isn't on our roadmap right now, but I will add it to our [feature requests backlog](https://github.com/aws/aws-sdk-net/blob/master/FEATURE_REQUESTS.md).
If you're interested in working on this addition, we're always happy to accept a pull request.

**Comment by PavelSafronov** [comment]
Request added to backlog. Closing.

**Comment by Kralizek** [comment]
I just stumbled on this very issue. Is there a way to vote up a feature request?
