### ISSUE TITLE
Medium Trust System.Security.SecurityException

### ISSUE THREAD

**Issue by mikemike396** [aws/aws-sdk-net#633]
Below code works fine in local environment, once uploaded to shared medium trust windows server (Host gator) it fails with error. Contacted hosting they said they do not have AWS DLL's in GAC. Anyway to get this running in medium trust environment? Thank You!

**DLLs:** 
AWSSDK.S3 - 3.3.0.0
AWSSDK.Core - 3.3.0.0

Code:
```
AWSCredentials credentials = new BasicAWSCredentials("xx", "xx");
var s3Client = new AmazonS3Client(credentials, Amazon.RegionEndpoint.USEast1);
var bucketName = "bucketName";
PutObjectRequest putRequest = new PutObjectRequest
{
    BucketName = bucketName,
    Key = imageName,
    InputStream = post.image
};

PutObjectResponse response1 = s3Client.PutObject(putRequest);
```

Error:
```
System.TypeInitializationException: The type initializer for 'Amazon.S3.AmazonS3Config' threw an exception. --->
System.Security.SecurityException: Request for the permission of type 'System.Security.Permissions.EnvironmentPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed. at
System.Security.CodeAccessSecurityEngine.Check(Object demand, StackCrawlMark& stackMark, Boolean isPermSet) at
System.Security.CodeAccessSecurityEngine.Check(CodeAccessPermission cap, StackCrawlMark& stackMark) at
System.Security.CodeAccessPermission.Demand() at
System.Environment.GetEnvironmentVariable(String variable) at
Amazon.Util.Internal.InternalSDKUtils.GetExecutionEnvironmentUserAgentString() at
Amazon.Util.Internal.InternalSDKUtils.BuildUserAgentString(String serviceSdkVersion) at
Amazon.S3.AmazonS3Config..cctor() --- End of inner exception stack trace --- at
Amazon.S3.AmazonS3Config..ctor() at
```

**Comment by PavelSafronov** [comment]
Do you have a way to reproduce this same error locally?

**Comment by mikemike396** [comment]
I was not able to reproduce it locally, even with Medium trust forced. My hosting must have some special settings that I am not aware of. We ended up performing the upload using native iOS and Android AWS SKD. Thank You.

**Comment by DanielChilcott** [comment]
This exception is being thrown because methods in System.Environment (for example GetEnvironmentVariable) are marked with the "SecuritySafeCritical" attribute which prevents them from executing when environment permission has not been included for an AppDomain. 

Is there any way to avoid having the SDK attempt to access env variables? This would solve the problem.

**Comment by mikemike396** [comment]
We ended up moving the upload process to the client side instead of server side. Thanks for the tips tho!
