### ISSUE TITLE
Should remove dangerous GET_ACCOUNTS permission for Unity@Android

### ISSUE THREAD

**Issue by qua-iy** [aws/aws-sdk-net#634]
AndroidManifest.xml is bundled inside the Unity package, and a dangerous permission `GET_ACCOUNTS` is written here: https://github.com/aws/aws-sdk-net/blob/1a5187e0dcddadba10a6b90fd827f2e485af0f9c/buildtools/UnityTools/Plugins/Android/AndroidManifest.xml#L20
According to #577, Unity SDK should not require this permission.
Why this is remaining?

## Expected Behavior
Bundled AndroidManifest.xml should declare minimum permissions.

## Current Behavior
Many permissions are declared, along with dangerous permission.

## Possible Solution
Please remove all permissions that are not required.

## Your Environment
* AWSSDK.Core version used: 3.3.82.1
* Service assembly and version used: Firehose
* Operating System and version: Mac OSX
* Visual Studio version: ---
* Targeted .NET platform: Unity

**Comment by PavelSafronov** [comment]
You are correct, I believe this permission is required by `aws-unity-sns-gcm-helper`. We are looking into removing this plugin and the associated permission.

**Comment by brettvg** [comment]
This still hasn't been fixed. Building Unity projects using the current AWS Unity plugin still adds GET_CONTACTS to he manifest within an apk.

This is a pretty major issue, has there been progress in removing it?

**Comment by kromenak** [comment]
This is also an issue for us. This may contribute to us using a different service, since we would prefer to avoid showing any "scary" permissions to users when they download our game.
