### ISSUE TITLE
Inconsistencies in retrieving Cloudfront logs files from S3 in chronological order specifying a first file

### ISSUE THREAD

**Issue by flo8** [aws/aws-sdk-net#638]
We have a .Net Core (1.1) C# application using AWSSDK.S3 3.3.5.7 and AWSSDK.Core 3.3.8.2 (Visual Studio 2017) and running on Ubuntu 16.04.

Our app is ran every X minutes to check if there are new files on our S3 bucket containing Cloudfront log files and retrieve them. While our code seems to work well in most cases, it seems sometimes some files are not retrieved. For instance, as you can see on the screenshot below, there are 2 files that were uploaded by Cloudfront:
![screenshot](https://cloud.githubusercontent.com/assets/2037837/25662809/25ebe070-3016-11e7-8a65-370f5d983790.png)

Here is the function I wrote that is supposed to retrieve all the files that were created since startFromFileName passed as a parameter. 

When I call this function with the S3 file ending with "e390acc1.gz", it doesn't list the file ending with "1fA260df", even if the latter was created 10 minutes later (more recent). Any idea what I am doing wrong here?

```
public async Task<List<string>> GetBucketFilesList(string bucketName, string prefix, string startFromFileName)
{
    List<string> fileList = new List<string>();

    try
    {
        // Make sure that the start file exists
        if (startFromFileName != String.Empty)
        {
            if (Exists(bucketName, startFromFileName) == false)
            {
                // file doesn't exist, let's return an empty list
                return fileList;
            }
        }

        // Create our list object request
        ListObjectsRequest request = new ListObjectsRequest();
        request.BucketName = bucketName;
        request.Prefix = prefix;

        // We may have to retrieve all files created after a specific date
        DateTime? last_file_date = null;

        // If we have a start file, specify it, otherwise we'll get everything in the bucket
        if (startFromFileName != String.Empty)
        {
            // Retrieve metadata of the last processed file 
            GetObjectRequest obj_request = new GetObjectRequest
            {
                BucketName = bucketName,
                Key = startFromFileName
            };

            using (var response = await client.GetObjectAsync(obj_request))
            {
                // Save the creation date of the last processed file
                last_file_date = response.LastModified;
            }

            // Only retrieved files from this last processed file
            request.Marker = startFromFileName;
        }
            

        // Process all the paginated results from S3 (each page has a 1000 object limit)
        while (true)
        {
            Task<ListObjectsResponse> response = client.ListObjectsAsync(request);

            if (response.Exception == null)
            {
                foreach (S3Object o in response.Result.S3Objects)
                {
                    //Console.WriteLine("{0}\t{1}\t{2}", o.Key, o.Size, o.LastModified);

                    // If we have a start file specified
                    // we must check file dates in order to be sure that the file has not been already processed
                    if(
                        (startFromFileName != String.Empty && last_file_date != null) == false
                        ||
                        o.LastModified.ToUniversalTime() > last_file_date)
                    {
                        fileList.Add(o.Key);
                    }
                }

                // If response is truncated, set the marker to get the next set of keys.
                if (response.Result.IsTruncated)
                {
                    // Proceed to the next page
                    request.Marker = response.Result.NextMarker;
                }
                else
                {
                    // We're done, break
                    break;
                }
            }
        }
    }
    catch (Exception e)
    {
        // Something went wrong
    }

    return fileList;
}
```

**Comment by flo8** [comment]
Just to keep track and help people who will read this probably later: I think the problem actually lies in the fact that we are dealing with Cloudfront logs. The function I posted above sorts file by filename (alphabetically), yet it seems that the uniqueid in the cloudfront log file name is completely random. So it means that in a given S3 bucket, if you have 2 Cloudfront log files that were created like 5 minutes apart, you can't know which one came first in C# API.
@PavelSafronov can you confirm this?
Many thanks

**Comment by PavelSafronov** [comment]
You are correct, the [format for Cloudfront log file names](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/AccessLogs.html#AccessLogsFileNaming) stipulates that log files for a given hour will have the same prefix, but the unique id means that the order of the files does not correlate to log creation order.

Given the extra bit of information in your last message, I now (finally!) understand what's happening. You are assuming that S3 returns the files in order of creation, but according to [S3 ListObjects documentation](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGET.html) the objects returned are in lexographical order. So if you're starting from "e390acc1.gz", S3 will not return "1fA260df.gz", since that file comes before "e390acc1.gz". If you start from "1fA260df.gz", S3 will return "e390acc1.gz".

**Comment by flo8** [comment]
Thanks @PavelSafronov for making this clear 👍
