### ISSUE TITLE
ELB .Net Upload not working with StatusCode 'Forbidden', Message 'Anonymous access is forbidden for this operation'

### ISSUE THREAD

**Issue by pfusco** [aws/aws-sdk-net#639]
## Expected Behavior
I would expect the application package to use the default credentials from the profile to create the s3 bucket.

## Current Behavior
It does not seem to be using the credentials and tries to create the s3 bucket as Anonymous

## Steps to Reproduce (for bugs)
Try to deploy the application to and exist ELB app through the Extension

## Your Environment
Windows 10 pro
Visual Studio 2017 Community 4.6.01586
AWS Toolkit vsion 1.12.0.5

## .NET Core Info

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by PavelSafronov** [comment]
How are you configuring the credentials on the ELB instance or in the app that you deploy there? How are you constructing the S3 client?

**Comment by sstevenkang** [comment]
Could you provide a snippet of toolkit log from `C:\Users\<username>\AppData\Local\AWSToolkit\logs\visualstudio`  that's relevant to the issue you are seeing?

**Comment by normj** [comment]
We were able to reproduce this problem when we were using credentials from the shared credentials file and not the toolkit's credential store. We just put a new version 1.11.7.4 of the Toolkit for VS 2013 - 2015 and version 1.12.0.6 for VS 2017 that fixes this issue. Please download the latest to see if it resolves your issue.

**Comment by sstevenkang** [comment]
Closing this issue.  Please do let us know if you are experiencing the same issue after updating your toolkit to latest.

**Comment by jpf5064** [comment]
I'm having this issue today when deploying to Elastic Beanstalk

**Comment by pranavpeddi** [comment]
I'm having this issue today when deploying to Elastic Beanstalk
