### ISSUE TITLE
Unity : S3Example GetObjects not working. User-Agent header issue

### ISSUE THREAD

**Issue by kashifshabbir** [aws/aws-sdk-net#643]
I downloaded latest unity SDK "aws-sdk-unity_3.3.83.0.zip" and installed S3 unitypackage.
but in GetObjects function I am getting error. Following is trace of the problem

```
ArgumentException: Cannot set Request Header User-Agent - name contains illegal characters or is not user-overridable
UnityEngine.Networking.UnityWebRequest.SetRequestHeader (System.String name, System.String value) (at /Users/builduser/buildslave/unity/build/artifacts/generated/common/modules/UnityWebRequest/WebRequestBindings.gen.cs:473)
UnityEngine.WWW..ctor (System.String url, System.Byte[] postData, System.Collections.Generic.Dictionary`2 headers) (at /Users/builduser/buildslave/unity/build/Runtime/WebRequestWWW/UWRWWW.cs:60)
Amazon.Runtime.Internal.UnityMainThreadDispatcher+<InvokeRequest>d__7.MoveNext ()
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at /Users/builduser/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Amazon.Runtime.Internal.UnityMainThreadDispatcher:ProcessRequests()
Amazon.Runtime.Internal.UnityMainThreadDispatcher:Update()
```

Expected Behavior
It used to work seamlessly in Unity version 5.6

Steps to Reproduce
Simply running example scene can reproduce issue

Your Environment
I am currently using Unity 2017.1.0b2 and building for MAC platform. 
.NET version in Unity build settings: 3.5

**Comment by sstevenkang** [comment]
Hi, could you  provide a sample code that repros this problem?

**Comment by kashifshabbir** [comment]
I downloaded the Unity SDK from here http://sdk-for-net.amazonwebservices.com/latest/aws-sdk-unity.zip

Here is function I am using from S3Example.cs
 ```
public void GetObjects(Action callback)
    {
        var request = new ListObjectsRequest()
        {
            BucketName = S3BucketName
        };
   
        Client.ListObjectsAsync(request, (responseObject) =>
            {
                if (responseObject.Exception == null)
                {
                    responseObject.Response.S3Objects.ForEach((o) =>
                        {
                            s3Objects.Add(o);
                        });
                    callback();
                    
                }
                else
                {
                    Debug.Log("GetObjects got exceptional :D");
                }
            });
    }
```

Error is in line 
```
        Client.ListObjectsAsync(request, (responseObject) =>
```
You can see exception stack trace in question above

**Comment by PavelSafronov** [comment]
@schakkis, it sounds like the problem you are seeing is different, can you please open a new issue?

**Comment by schakkis** [comment]
@PavelSafronov 
Sorry, was a bit too fast with an earlier assumption. I think it's still the same issue, but the error that is presented is just different in the current Unity beta. 

Should I still report a new issue, or is it okay to keep it here?

**Comment by PavelSafronov** [comment]
Ah, I see what you mean. OK, this seems like the appropriate issue then.

Can you try attaching the below callback to find out what the problematic header is?
```
client.BeforeRequestEvent += (sender, args) =>
{
    var wsrea = args as WebServiceRequestEventArgs;
    foreach(var header in wsrea.Headers)
    {
        Console.WriteLine("{0} = [{1}]", header.Key, header.Value);
    }
};
```

**Comment by schakkis** [comment]
Just ran a quick test; here is the log output: 

```User-Agent = [aws-sdk-unity/3.3.6.0 aws-sdk-core/3.3.13.4 .NET_Runtime/2.0 UnityVersion/2017.1.0b4 OS/unity__ ClientAsync UnityWWW]
UnityEngine.Debug:Log(Object)
AWSSDK.Examples.S3Example:<GetObjects>m__9(Object, RequestEventArgs) (at Assets/Examples/S3Example.cs:210)
Amazon.Runtime.AmazonServiceClient:ProcessRequestHandlers(IExecutionContext)
Amazon.Runtime.Internal.CallbackHandler:RaiseOnPreInvoke(IExecutionContext)
Amazon.Runtime.Internal.CallbackHandler:PreInvoke(IExecutionContext)
Amazon.Runtime.Internal.CallbackHandler:InvokeAsync(IAsyncExecutionContext)
...
Amazon.Runtime.Internal.PipelineHandler:InvokeAsync(IAsyncExecutionContext)
Amazon.Runtime.Internal.ThreadPoolExecutionHandler:InvokeAsyncHelper(IAsyncExecutionContext)
Amazon.Runtime.Internal.Util.ThreadPoolThrottler`1:Callback(Object)
```

**Comment by kashifshabbir** [comment]
I couldn't find `BeforeRequestEvent` in `IAmazonS3 client`. Am I missing something?

**Comment by schakkis** [comment]
@kashifshabbir
It's available in `AmazonServiceClient`. For a quick test it's easiest to just cast to that.

**Comment by kashifshabbir** [comment]
There you go!
`User-Agent = aws-sdk-unity/3.3.5.9 aws-sdk-core/3.3.10.0 .NET_Runtime/2.0 UnityVersion/2017.1.0b2 OS/unity__ ClientAsync UnityWWW`
Like @schakkis  I am getting similar header and stack trace.

**Comment by schakkis** [comment]
I did a little more investigation. It looks like AWSSDK doesn't properly detect that it should be using `UnityWebRequest` in Unity 2017.1.0bX.

If I manually set the client it seems to be working fine.
```Amazon.AWSConfigs.HttpClient = Amazon.AWSConfigs.HttpClientOption.UnityWebRequest;```

**Comment by kashifshabbir** [comment]
Thanks a lot. It is fine with this workaround now!

**Comment by schakkis** [comment]
Short update; 

We started looking into Unity 2017.1 now again since they are closing in on release. Testing with Unity 2017.1.0f1 this error still occurs. 

We have also discovered a related problem; Unity has changed more things in UnityWebRequest and the reflection code in AWS SDK (UnityWebRequestWrapper.cs) doesn't work anymore. 

See https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Pipeline/_unity/UnityWebRequestWrapper.cs#L56
 and https://docs.unity3d.com/2017.1/Documentation/ScriptReference/Networking.UnityWebRequest.html

```isError``` seems to have been replaced with ```isHttpError``` and ```isNetworkError```.

**Comment by kashifshabbir** [comment]
Thanks for update.

This workaround ```Amazon.AWSConfigs.HttpClient = Amazon.AWSConfigs.HttpClientOption.UnityWebRequest;``` worked fine for all platforms except windows build.

I am using unity 2017.1.0b2 on macOS Sierra.

I am getting following error in Windows Platform Build
```
NullReferenceException: Object reference not set to an instance of an object
  at Amazon.Runtime.Internal.UnityWebRequestWrapper..cctor () [0x00000] in <filename unknown>:0 
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for Amazon.Runtime.Internal.UnityWebRequestWrapper
  at Amazon.AWSConfigs.set_HttpClient (HttpClientOption value) [0x00000] in <filename unknown>:0 
```

For now I am waiting for unity 2017.1 to come out of beta.

**Comment by Niknokc** [comment]
@kashifshabbir
Hi. 2017.1 is out of beta now, do you still have this issue?
`Amazon.AWSConfigs.HttpClient = Amazon.AWSConfigs.HttpClientOption.UnityWebRequest;`
Works just fine on OSX for me, but throws same errors you listed in your last update.
Any tips?

**Comment by tbc01** [comment]
Having same issue as @Niknokc.

**Comment by schakkis** [comment]
This has also been reported in #696, #701 & #704 

We have used the same approach as @lakrsv described in #701 and rolled our own dll.

**Comment by kozzles** [comment]
Any chance this will be fixed in the official AWSSDK release for Unity soon? I was hoping https://github.com/aws/aws-sdk-net/pull/709 might fix it, but this issue still appears to be active for 2017.1. We could go the rolling our own dll approach, but would prefer that the official release supports 2017.1 out of the box. Thanks!

**Comment by chenchen2015** [comment]
Apparently, pull request #709 still did not totally fix the same issue. I'm still receiving the bug message below in Unity 2017.1 versions (specifically, 2017.1.2p2)
```
InvalidOperationException: Cannot override system-specified headers
UnityEngine.Networking.UnityWebRequest.SetRequestHeader (System.String name, System.String value) (at C:/buildslave/unity/build/artifacts/generated/common/modules/UnityWebRequest/WebRequestBindings.gen.cs:482)
UnityEngine.WWW..ctor (System.String url, System.Byte[] postData, System.Collections.Generic.Dictionary`2 headers) (at C:/buildslave/unity/build/Runtime/WebRequestWWW/UWRWWW.cs:62)
Amazon.Runtime.Internal.UnityMainThreadDispatcher+<InvokeRequest>d__7.MoveNext ()
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Amazon.Runtime.Internal.UnityMainThreadDispatcher:ProcessRequests()
Amazon.Runtime.Internal.UnityMainThreadDispatcher:Update()
```

Here's a temporary fix for Unity 2017.1 versions. Presumably, this should also work in Unity 2017.2 versions if you have the same bug, but I haven't tested. @schakkis was right, all you need is to manually override the target ```HttpClient``` interface with ```UnityWebRequest```. To do this, the best way I have found is to add it right after ```UnityMainThreadDispatcher``` awakes. 
```c#
// UnityMainThreadDispatcher.cs
public void Awake()
{
      _logger = Logger.GetLogger(this.GetType());
      // Call the method to process requests at a regular interval.
      _nextUpdateTime = Time.unscaledTime;
      _nextUpdateTime += _updateInterval;

      // Override HttpClient here
     Amazon.AWSConfigs.HttpClient = Amazon.AWSConfigs.HttpClientOption.UnityWebRequest;
}

As you can see, simply override the HttpClient as suggested by @schakkis in the ```Awake()``` method in [UnityMainThreadDispatcher.cs](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Pipeline/_unity/UnityMainThreadDispatcher.cs) code, and compile again. Now everything should be back working again!

**Comment by mosky17** [comment]
setting the client manually is working for OSX but not for iOS:

```
NullReferenceException: A null value was found where an object instance was required.
  at Amazon.Runtime.Internal.UnityWebRequestWrapper..ctor (System.String url, System.String method) [0x00000] in <filename unknown>:0 
  at Amazon.AWSConfigs.set_HttpClient (HttpClientOption value) [0x00000] in <filename unknown>:0 
  at AmazonController.Start () [0x00000] in <filename unknown>:0 
Rethrow as TypeInitializationException: The type initializer for 'Amazon.Runtime.Internal.UnityWebRequestWrapper' threw an exception.
  at Amazon.AWSConfigs.set_HttpClient (HttpClientOption value) [0x00000] in <filename unknown>:0 
  at AmazonController.Start () [0x00000] in <filename unknown>:0 
```

Any solution?

**Comment by kvasukib** [comment]
Hi @mosky17,

For iOS, do you have a link.xml file that contains the content as described in https://github.com/aws/aws-sdk-net/blob/master/Unity.README.md#unity-sdk-fundamentals?

**Comment by mosky17** [comment]
thanks for your response @kvasukib , my issue was resolved after updating the cognito library, seems it was out of date.

**Comment by kvasukib** [comment]
Hi @chenchen2015,

We covered setting the client manually here: https://aws.amazon.com/blogs/mobile/unity-v3-support-in-the-aws-sdk-for-net-is-out-of-preview/.

**Comment by chenchen2015** [comment]
Thank you @kvasukib  I was hoping that AWS could solve this issue.

**Comment by neosatus** [comment]
I'm having the same error trying to get DynamoDB setup. I'm using 2017.2 and it says that HttpClient does not exist in Amazon.AWSConfigs. Is there somewhere else to set it in 2017.2?

**Comment by kvasukib** [comment]
Hi @neosatus, Can you follow this guide  https://aws.amazon.com/blogs/mobile/unity-v3-support-in-the-aws-sdk-for-net-is-out-of-preview/ and set the HttpClient to UnityWebRequest manually in the app?

**Comment by neosatus** [comment]
I added:

```
Amazon.AWSConfigs.HttpClient = Amazon.AWSConfigs.HttpClientOption.UnityWebRequest;
```

to UnityMainThreadDispatcher's Awake function and get this error:

```
error CS0117: 'Amazon.AWSConfigs' does not contain a definition for 'HttpClient'
```

**Comment by almorak** [comment]
i encountered similar problem, with sns package (3.3.0.25)
I have added AWSConfigs.HttpClient = AWSConfigs.HttpClientOption.UnityWebRequest; 
it solved The Exception BUT  still no response, return or exception with SnsClient.CreatePlatformEndpointAsync

Need some advice.
(that part of code just same as example )
Im using unity 2017.1.0.3.

**Comment by IsmaelNascimento** [comment]
You can now, use sdk of S3 modified and better: https://github.com/IsmaelNascimento/aws-sdk-s3-for-unity
