### ISSUE TITLE
Cognito User Pools are missing UserPoolTags

### ISSUE THREAD

**Issue by simonbuchan** [aws/aws-sdk-net#646]
The SDK is completely missing `UserPoolTags` from the model at the moment.

They should be added to `Amazon.CognitoIdentityProvider.Model` types:
- `CreateUserPoolRequest`
- `UpdateUserPoolRequest`
- `UserPoolType`

It *looks* like this should just be updating `generator/ServiceModels/cognito-idp/cognito-idp-2016-04-18.normal.json`, and regenerating the clients, but I can't see an existing instance of `Dictionary<>` there - what should that look like if we were trying to build a private version for now?

Are there any other workarounds I'm missing?

**Comment by sstevenkang** [comment]
Thanks for reporting this.  We just pushed out a new version of CognitoIdentityProvider (3.3.3.0) with 152468dff1b8869c447e48e0df73fa0e0a8aaa50

**Comment by simonbuchan** [comment]
Wow, thanks for the fast response! 💖
