### ISSUE TITLE
AmazonS3Config SignatureVersion="2" Is Ignored

### ISSUE THREAD

**Issue by tlawrence** [aws/aws-sdk-net#647]
When connecting to a non-AWS endpoint (not tested against S3 bucket may be the same..) the client is sending V4 requests even when overridden to v2.

## Expected Behavior
Client should authenticate correctly and list buckets

## Current Behavior
Server rejects authentication with "The AWS Access Key Id you provided does not exist in our records."

Connection Code:
```
using Amazon.Runtime;
using Amazon.S3;
using Amazon.S3.Model;

AmazonS3Config config = new AmazonS3Config()
  {
	ForcePathStyle = true,
	SignatureVersion = "2",
	ServiceURL = Endpoint,
	SignatureMethod = Amazon.Runtime.SigningAlgorithm.HmacSHA1,


  };

  AmazonS3Client s3 = new AmazonS3Client(new BasicAWSCredentials(AccessKey, SecretKey), config);

  var buckets = s3.ListBuckets(new ListBucketsRequest());
```

## Possible Solution
Works in S3 Nuget package 3.3.4.1
Broken in S3 Nuget package 3.3.5

## Steps to Reproduce (for bugs)
run code above in console app. 
Check HTTP requests (I used Fiddler), v4 signed requests are observed

## Your Environment

* AWSSDK.Core version used: 3.3.13.4
* Service assembly and version used: S3 3.3.5 or later
* Operating System and version: Mac OSX / Mono 5.0.0.94 (but failing on Windows too)
* Visual Studio version: VS17 for Mac Preview 10 7.0 build 3051
* Targeted .NET platform: net461

possible relation to #587 ??

**Comment by tlawrence** [comment]
Further to this I have just discovered that setting:

```
using Amazon;

AWSConfigsS3.UseSignatureVersion4 = false;
```

allows the connection to succeed. 


Is the SignatureVersion property of AmazonS3Config deprecated?

**Comment by vellozzi** [comment]
We have a fix for this issue and will release it as soon as we're able to.

**Comment by vellozzi** [comment]
The fix for this has been released in nuget packages AWSSDK.S3 3.3.6.2 and AWSSDK.Core 3.3.14.1

**Comment by tlawrence** [comment]
Thanks for taking the time to look at this.

**Comment by ypriverol** [comment]
I'm facing the same issue with version 3.3.31.
