### ISSUE TITLE
AWSSDK.Core >= 3.3.5 not installing on .NET Framework 4.5

### ISSUE THREAD

**Issue by ibiller** [aws/aws-sdk-net#651]
Tried to install latest AWSSDK.Core from NuGet on a brand new project and received an error: 'AWSSDK.Core' already has a dependency defined for 'PCLStorage'.  NuGet reports no dependencies for .NET Framework 4.5 (and I've installed and used it in the past without problems).  

Expected behavior: 
 Install-Package AWSSDK.Core -Version 3.3.14 -> installed

Current behavior:
 Install-Package AWSSDK.Core -Version 3.3.14
Install-Package : 'AWSSDK.Core' already has a dependency defined for 'PCLStorage'.
At line:1 char:16
+ Install-Package <<<<  AWSSDK.Core -Version 3.3.14
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

Temporary workaround: 
Install-Package AWSSDK.Core -Version 3.3.4.1
Installing 'AWSSDK.Core 3.3.4.1'.
Successfully installed 'AWSSDK.Core 3.3.4.1'.

Repro:
create new console project for .NET Framework 4.5
add AWSSDK.Core from NuGet package manager or type
Install-Package AWSSDK.Core -Version 3.3.14 in NuGet console

Env:
Visual Studio 2013
.NET Framework 4.5
Win7
NuGet  2.8.50313.46

Let me know if any further information needed

**Comment by sstevenkang** [comment]
Hmm I can't repro this on my environment and I am on Win10.  I don't think the operating system would affect nuget dependency resolution.  Could you try these two things:
1. Update NuGet to 2.12.x
2. Clean out your nuget cache(usually under` c:\Users\<username>\.nuget\packages` and `C:\Users\<username>\AppData\Local\NuGet`

**Comment by ibiller** [comment]
Updating to 2.12 fixed it.  Thanks for the suggestion!
