### ISSUE TITLE
AWS Toolkit for Visual Studio 2017 doesn't support IAM roles or MFA

### ISSUE THREAD

**Issue by jimcroft** [aws/aws-sdk-net#652]
Our organisation uses multiple AWS accounts for various dev, test and production purposes. All this is based around an IAM model that requires assuming roles in other accounts all of which require MFA.

This makes the use of the VS toolkit impossible right now.

Ideally we'd like to see the same level of role/mfa support as we see in the AWS CLI.

**Comment by steveataws** [comment]
We have this on our backlog and I've just bumped the priority.

**Comment by jimcroft** [comment]
BTW I couldn't see a repo for the VS toolkit. Is it open sourced like the Eclipse one or closed? If currently closed any chance of that changing in the near future?

**Comment by steveataws** [comment]
The toolkit for Visual Studio isn't open sourced. It's something we evaluate periodically, but there are no current plans to do this in the near future

**Comment by vellozzi** [comment]
This issue has been added to out backlog.  Please feel free to comment if you have more questions.

**Comment by joewaid** [comment]
Any updates on getting MFA support added to the Visual Studio add-in? It's a nice tool, but useless without mfa support.

**Comment by jhaygood86** [comment]
My employer just started enforcing MFA with our AWS accounts, and AWS Explorer is basically useless without MFA support now.

Any updates wrt to MFA support?

**Comment by NArnott** [comment]
Just getting started on AWS, and our IT guys set up MFA out of the box. So we're stuck not being ablue to use the AWS tools for visual studio 2019. Big bummer as that's what we initially trained on using. What's the word on this?
