### ISSUE TITLE
Unmarshaller blocks on async calls on .NET Core running on Linux

### ISSUE THREAD

**Issue by bcuff** [aws/aws-sdk-net#653]
Unmarshaller blocks reading the HTTP response stream on .NET Core / Linux

## Expected Behavior
Unmarshaller should not block on reading the response stream.

## Current Behavior
The actual stream implementation (CurlResponseStream) on .NET Core / Linux will block on Stream.Read()

See stack trace:
```
00007F4C775A47F0 00007f53bebd5360 [GCFrame: 00007f4c775a47f0] 
00007F4C775A4920 00007f53bebd5360 [HelperMethodFrame_1OBJ: 00007f4c775a4920] System.Threading.Monitor.ObjWait(Boolean, Int32, System.Object)
00007F4C775A4A50 00007F5343B75DEF System.Threading.ManualResetEventSlim.Wait(Int32, System.Threading.CancellationToken)
00007F4C775A4AE0 00007F5343B47B72 System.Threading.Tasks.Task.SpinThenBlockingWait(Int32, System.Threading.CancellationToken)
00007F4C775A4B40 00007F5343B479C9 System.Threading.Tasks.Task.InternalWait(Int32, System.Threading.CancellationToken)
00007F4C775A4C20 00007F5343B602E4 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
00007F4C775A4C40 00007F5343C9819F System.Runtime.CompilerServices.TaskAwaiter`1[[System.Int32, System.Private.CoreLib]].GetResult()
00007F4C775A4C50 00007F5344FA96E3 System.Net.Http.CurlHandler+CurlResponseStream.Read(Byte[], Int32, Int32)
00007F4C775A4CA0 00007F5344F7A28C System.Net.Http.DelegatingStream.Read(Byte[], Int32, Int32)
00007F4C775A4CB0 00007F5343B38E17 System.IO.StreamReader.ReadBuffer()
00007F4C775A4CD0 00007F5343B38634 System.IO.StreamReader.Read()
00007F4C775A4CF0 00007F534554F109 ThirdParty.Json.LitJson.Lexer.State1(ThirdParty.Json.LitJson.FsmContext)
00007F4C775A4D20 00007F534554ED3B ThirdParty.Json.LitJson.Lexer.NextToken()
00007F4C775A4D90 00007F534554EC87 ThirdParty.Json.LitJson.JsonReader.ReadToken()
00007F4C775A4DB0 00007F534554EA2E ThirdParty.Json.LitJson.JsonReader.Read()
00007F4C775A4DE0 00007F53466089F7 Amazon.Runtime.Internal.Transform.JsonUnmarshallerContext.Read()
00007F4C775A4E00 00007F5346608899 Amazon.DynamoDBv2.Model.Internal.MarshallTransformations.GetItemResponseUnmarshaller.Unmarshall(Amazon.Runtime.Internal.Transform.JsonUnmarshallerContext)
00007F4C775A4E50 00007F5346607B89 Amazon.Runtime.Internal.Transform.JsonResponseUnmarshaller.Unmarshall(Amazon.Runtime.Internal.Transform.UnmarshallerContext)
00007F4C775A4E90 00007F5345588B69 Amazon.Runtime.Internal.Transform.ResponseUnmarshaller.UnmarshallResponse(Amazon.Runtime.Internal.Transform.UnmarshallerContext)
00007F4C775A4EB0 00007F53455888F9 Amazon.Runtime.Internal.Unmarshaller.UnmarshallResponse(Amazon.Runtime.Internal.Transform.UnmarshallerContext, Amazon.Runtime.IRequestContext)
00007F4C775A4F10 00007F5345587AE0 Amazon.Runtime.Internal.Unmarshaller+<UnmarshallAsync>d__5.MoveNext()
00007F4C775A4F90 00007F53455876F5 System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Amazon.Runtime.Internal.Unmarshaller+<UnmarshallAsync>d__5, AWSSDK.Core]](<UnmarshallAsync>d__5 ByRef)
00007F4C775A4FD0 00007F5345587679 Amazon.Runtime.Internal.Unmarshaller.UnmarshallAsync(Amazon.Runtime.IExecutionContext)
00007F4C775A5080 00007F534557B933 Amazon.Runtime.Internal.Unmarshaller+<InvokeAsync>d__3`1[[System.__Canon, System.Private.CoreLib]].MoveNext()
00007F4C775A5130 00007F53455875C7 DomainBoundILStubClass.IL_STUB_UnboxingStub()
00007F4C775A5150 00007F5343AF6E71 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
00007F4C775A51A0 00007F5343B92BEB System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunnerWithContext.RunWithCapturedContext()
00007F4C775A51D0 00007F5343B76EB2 System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean, System.Threading.Tasks.Task ByRef)
00007F4C775A5200 00007F5343B48193 System.Threading.Tasks.Task.FinishContinuations()
00007F4C775A5280 00007F5343B4DCA4 System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib]].TrySetResult(System.__Canon)
00007F4C775A52A0 00007F5343B5AB67 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib]].SetResult(System.__Canon)
00007F4C775A52D0 00007F534557E501 Amazon.Runtime.Internal.HttpHandler`1+<InvokeAsync>d__9`1[[System.__Canon, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib]].MoveNext()
```

## Possible Solution
Make the call to UnmarshalResponse async if Stream.CanSeek is false.
[See synchronous call](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Pipeline/Handlers/Unmarshaller.cs#L189)

## Steps to Reproduce (for bugs)
Run an application on .NET Core / Linux that retrieves large objects from DynamoDB or some other AWS service.
Attach a debugger & break until you find that threads that are blocking on CurlResponseStream.Read() (see above)

## Context
We discovered this while debugging another DynamoDB-related issue.

## Your Environment

* AWSSDK.Core version used: 3.3.7.1
* Service assembly and version used: DynamoDB
* Operating System and version: Ubuntu 16.04
* Visual Studio version: 2017
* Targeted .NET platform: .NET Core 1.1.1

## .NET Core Info

* .NET Core version used for development: 1.1.1
* .NET Core version installed in the environment where application runs: 1.1.1
* Output of `dotnet --info`: 
```
ubuntu@ip-172-0-7-13:~$ dotnet --info
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.1
```
* Contents of project.json/project.csproj: n/a

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by sstevenkang** [comment]
Hi, what's the surface issue you are seeing?  Are you running out of background threads to run tasks on?

Async calls have to block at some point down the stack to make progress.  Even if we provided `UnmarshallResponseAsync()`, for services that use JSON protocol, it's going to be blocked by the LitJson library that will be doing a synchronous call underneath(see ` ThirdParty.Json.LitJson.JsonReader.Read()`).

**Comment by bcuff** [comment]
Often when we notice a host running higher than usual load we will notice the majority of threads blocking on reading responses. I realize that the JSON deserialization is synchronous, however you could buffer the response stream into a MemoryStream before feeding it to LitJson.

**Comment by sstevenkang** [comment]
Well, currently PCL variants are hitting the same code path, so I think we need to make a more generic change by having our Unmarshallers support async.  I'll add this to our backlog.  Thanks for reporting this!

**Comment by bcuff** [comment]
you're welcome.

**Comment by david-poirier-csn** [comment]
Please add async support to Marshallers as well - I'm streaming uploads to S3 and would like it to be truly async end-to-end.

**Comment by mbp** [comment]
I would like to add, that when using https://github.com/benaadams/Ben.BlockingDetector in ASP.NET Core application using SimpleDB, it will tell you that the XML Unmarshaller is not running async.

```
warn: Ben.Diagnostics.BlockingMonitor[6]
      Blocking method has been invoked and blocked, this can lead to threadpool starvation.
         at System.Net.Http.HttpConnection.HttpContentReadStream.Read(Byte[] buffer, Int32 offset, Int32 count)
         at System.IO.StreamReader.ReadBuffer(Span`1 userBuffer, Boolean& readToUserBuffer)
         at System.IO.StreamReader.ReadSpan(Span`1 buffer)
         at System.IO.StreamReader.Read(Char[] buffer, Int32 index, Int32 count)
         at System.Xml.XmlTextReaderImpl.ReadData()
         at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
         at System.Xml.XmlTextReaderImpl.FinishPartialValue()
         at System.Xml.XmlTextReaderImpl.get_Value()
         at System.Xml.XmlReader.InternalReadContentAsString()
         at System.Xml.XmlReader.ReadContentAsString()
         at Amazon.Runtime.Internal.Transform.XmlUnmarshallerContext.ReadElement()
         at Amazon.Runtime.Internal.Transform.XmlUnmarshallerContext.Read()
         at Amazon.SimpleDB.Model.Internal.MarshallTransformations.AttributeUnmarshaller.Unmarshall(XmlUnmarshallerContext context)
```

**Comment by Dunge** [comment]
I'm seeing the same behavior here. Process make many DynamoDB queries, and at some point everything freeze.

All my threads are blocked in ThirdParty.Ionic.Zlib.CrcCalculatorStream.Read that is not async. Coming from the AttributeValueUnmarshaller. And the internal socket manualResetEventSlim timeout is set to -1 so it never seems to unblock.

I'm not sure what I could do to prevent this since all of my calls are async.

**Comment by Dunge** [comment]
<img width="1989" height="650" alt="Image" src="https://github.com/user-attachments/assets/2d93f2c2-e4e2-475b-9bd5-69b9399c70ce" />
