### ISSUE TITLE
The encrypted store is not available on this platform.

### ISSUE THREAD

**Issue by LastImmort** [aws/aws-sdk-net#654]
## Expected Behavior
it`s normal or bug?When rinnig .net core app on win sercer 2016 got error
does this platform supported?
## Current Behavior
An error occurred while starting the application.

AmazonClientException: The encrypted store is not available on this platform.
Amazon.Util.Internal.SettingsManager.EnsureAvailable()

AmazonClientException: The encrypted store is not available on this platform.
Amazon.Util.Internal.SettingsManager.EnsureAvailable()
Amazon.Runtime.CredentialManagement.NetSDKCredentialsFile..ctor()
RBTV.Startup.ConfigureServices(IServiceCollection services) in Startup.cs
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

## Steps to Reproduce (for bugs)
publish .net core proj and run it with
`     var awsOptions = Configuration.GetAWSOptions();

            var options = new CredentialProfileOptions {
                AccessKey = "key",
                SecretKey = "key"
            };

            var profile = new CredentialProfile("default", options) {
                Region = 'region'
            };
//THIS IS ERROR LINE
        `    var netSDKFile = new NetSDKCredentialsFile();`
            //register new profile in sdk file
            `netSDKFile.RegisterProfile(profile);``
in ConfigureServices section
## Context
After publish can`t add new profile

 AWSSDK.Core version used: latest
Operating System and version: windows server 2016
 Visual Studio version: vse 2017 15.2

.NET Core version used for development: 1.1.1
.NET Core version installed in the environment where application runs: 1.1.1

**Comment by vellozzi** [comment]
NetSDKCredentialsFiles are stored per user, per machine.  The account that IIS runs under isn't able to use the Windows Data Protection APIs.  This error message will be improved, but it's still not possible to use the encrypted credentials file from ASP.NET in IIS.
Please use the SharedCredentialsFile instead. See [Configuring AWS Credentials](http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-creds.html) for instructions on how to do that.
Feel free to reopen this issue if you have more questions.
