### ISSUE TITLE
Profile name in appsettings.json ignored

### ISSUE THREAD

**Issue by tehtechguy** [aws/aws-sdk-net#655]
I have a credentials file, stored in `%userprofile%\.aws\credentials` that looks something like this:

```
[dev]
#[default]
aws_access_key_id = ...
aws_secret_access_key = ...

...

# [other]
[default]
aws_access_key_id = ...
aws_secret_access_key = ...
```

My `appsettings.json` file looks something like this:

```
{
  ...

  "AWS": {
    "Profile": "dev",
    "Region": "us-east-1"
  }
}
```

I have a .NET Standard 1.4 class library that is using various components from `Amazon`. This library is shared between multiple .NET Core App 1.1 projects and a .NET Framework 4.6.1 project.

In the library, I have some code that looks something like this (reduced for simplicity):

```
public class SqsClient : ISqsClient // Interface not shown for simplicity
{
    public RegionEndpoint Region { get; set; }
    
    public async Task<int> GetTotalNumberOfMessages()
    {
        var request = new GetQueueAttributesRequest
        {
            QueueUrl = QueueUri,
            AttributeNames = new List<string>
            {
                "ApproximateNumberOfMessages",
                "ApproximateNumberOfMessagesDelayed",
                "ApproximateNumberOfMessagesNotVisible"
            }
        };

        using (var client = new AmazonSQSClient(Region))
        {
            // BREAKPOINT HERE
            var response = await client.GetQueueAttributesAsync(request);
            return response.ApproximateNumberOfMessages +
                   response.ApproximateNumberOfMessagesDelayed +
                   response.ApproximateNumberOfMessagesNotVisible;
        }
    }
}
```

In our test library (.NET Core App 1.1), we have something simple like this:

```
// Note that the appsettings.json file is located at the root of this test lib
var builder = new ConfigurationBuilder().AddJsonFile("appsettings.json");
var configuration = builder.Build();

var region = RegionEndpoint.GetBySystemName(
    configuration.GetSection("AWS:Region").Value);
var client = new SqsClient{Region=region};
var result = await client.GetTotalNumberOfMessages();
```

When trying to run the above code, I get an exception telling me that my creds are invalid. After placing a breakpoint, where noted above, I was able to see that the credentials that the client was using were not `dev`, but instead `default`. If I remove the default creds, an error occurs informing me that I don't have a default set. If I change the default to be `dev`, then everything works as expected.

I have a hunch that the appsettings file isn't being observed. Presumably if it were being read, then the correct profile would have been loaded.

Note that back when we were using .NET Framework 4.6.1 for everything, the above pattern worked as expected with the web.config.

For now, I can workaround this by manually editing the credentials file and setting the default; however, I have many environments I use, so doing this is not ideal.

Possibly related issues: #499, #536

**Comment by sstevenkang** [comment]
Could you share which version of `AWSSDK.Core` and `AWSSDK.Extensions` you are using?

**Comment by tehtechguy** [comment]
I'm using AWSSDK.Core 3.3.14 (across all projects). I'm not using AWSSDK.Extensions; instead I create the client as follows `var client = new AmazonSQSClient(Region)`. The class that uses that client is wrapped inside of a higher-level class, because of that I don't need the DI benefit provided by the extensions (I instead use my own higher-level class).

**Comment by sstevenkang** [comment]
Your application is picking the `default` profile because the SDK is not doing anything with the `appsettings.json` file.  ConfigurationManager is not available in .NET Core so we provide AWSSDK.Extensions to support scenarios like this where configuration is provided through `appsettings.json`.  Please take a look at this [Configuring AWS SDK with .NET Core](http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-netcore.html).

**Comment by tehtechguy** [comment]
Thanks for the clarification. I refactored my code to use a shared `IAmazonSQS` instance instead of using it as a disposable. This allowed me to inject the the client and use the extensions.
