### ISSUE TITLE
Unity3D BeginDescribeGameSessions Exception

### ISSUE THREAD

**Issue by TiagoJSM** [aws/aws-sdk-net#657]
I'm using GameLift to host my Unity3D multiplayer game, locally I tested the server and client connection through GameLiftLocal and it worked fine

When calling describe-game-sessions in the command line the request works fine, but when calling the code from Unity3D I get an error
```c#
var client = new AmazonGameLiftClient(awsAccessKeyId, wsSecretAccessKey, RegionEndpoint.USWest2);
 
 
var gameSessionsResponse = client.BeginDescribeGameSessions(
                new DescribeGameSessionsRequest()
                {
                    FleetId = _fleetId,
                },
                (result) => DescribeGameSessionsHandler(result, client),
                null);
 
...
 
 
private void DescribeGameSessionsHandler(IAsyncResult result, AmazonGameLiftClient client)
        {
            var response = client.EndDescribeGameSessions(result);
        }
```

Am I doing something wrong code wise?

I also tried to compile GameLift referencing AWSCore Unity project, but I end up getting another exception when calling DescribeGameSessions and BeginDescribeGameSessions  simply doesn't do anything

In DescribeGameSessionsHandler the result contains an exception with the following stack:

Amazon.Runtime.AmazonServiceException: A WebException with status SendFailure was thrown. ---> System.Net.WebException: Error getting response stream (Write: The authentication or decryption has failed.): SendFailure ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: Invalid certificate received from server. Error code: 0xffffffff800b010a\r\n at Mono.Security.Protocol.Tls.Handshake.Client.TlsServerCertificate.validateCertificates (Mono.Security.X509.X509CertificateCollection certificates) [0x00000] in <filename unknown>:0 \r\n at Mono.Security.Protocol.Tls.Handshake.Client.TlsServerCertificate.ProcessAsTls1 () [0x00000] in <filename unknown>:0 \r\n at Mono.Security.Protocol.Tls.Handshake.HandshakeMessage.Process () [0x00000] in <filename unknown>:0 \r\n at (wrapper remoting-invoke-with-check) Mono.Security.Protocol.Tls.Handshake.HandshakeMessage:Process ()\r\n at Mono.Security.Protocol.Tls.ClientRecordProtocol.ProcessHandshakeMessage (Mono.Security.Protocol.Tls.TlsStream handMsg) [0x00000] in <filename unknown>:0 \r\n at Mono.Security.Protocol.Tls.RecordProtocol.InternalReceiveRecordCallback (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 \r\n --- End of inner exception stack trace ---\r\n at Mono.Security.Protocol.Tls.SslStreamBase.AsyncHandshakeCallback (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 \r\n --- End of inner exception stack trace ---\r\n at System.Net.HttpWebRequest.EndGetRequestStream (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 \r\n at Amazon.Runtime.Internal.HttpRequest.EndGetRequestContent (IAsyncResult asyncResult) [0x00000] in E:\\JenkinsWorkspaces\\v3-trebuchet-release\\AWSDotNetPublic\\sdk\\src\\Core\\Amazon.Runtime\\Pipeline\\HttpHandler\\_bcl\\HttpWebRequestFactory.cs:275 \r\n at Amazon.Runtime.Internal.HttpHandler`1[System.IO.Stream].GetRequestStreamCallbackHelper (System.Object state) [0x00023] in E:\\JenkinsWorkspaces\\v3-trebuchet-release\\AWSDotNetPublic\\sdk\\src\\Core\\Amazon.Runtime\\Pipeline\\HttpHandler\\HttpHandler.cs:301 \r\n --- End of inner exception stack trace ---\r\n at Amazon.Runtime.Internal.WebExceptionHandler.HandleException (IExecutionContext executionContext, System.Net.WebException exception) [0x00058] in E:\\JenkinsWorkspaces\\v3-trebuchet-release\\AWSDotNetPublic\\sdk\\src\\Core\\Amazon.Runtime\\Pipeline\\ErrorHandler\\_bcl\\WebExceptionHandler.cs:44 \r\n at Amazon.Runtime.Internal.ExceptionHandler`1[T].Handle (IExecutionContext executionContext, System.Exception exception) [0x00000] in E:\\JenkinsWorkspaces\\v3-trebuchet-release\\AWSDotNetPublic\\sdk\\src\\Core\\Amazon.Runtime\\Pipeline\\ErrorHandler\\ExceptionHandler.cs:38 \r\n at Amazon.Runtime.Internal.ErrorHandler.ProcessException (IExecutionContext executionContext, System.Exception exception) [0x0005c] in E:\\JenkinsWorkspaces\\v3-trebuchet-release\\AWSDotNetPublic\\sdk\\src\\Core\\Amazon.Runtime\\Pipeline\\ErrorHandler\\ErrorHandler.cs:204 \r\n at Amazon.Runtime.Internal.ErrorHandler.InvokeAsyncCallback (IAsyncExecutionContext executionContext) [0x00028] in E:\\JenkinsWorkspaces\\v3-trebuchet-release\\AWSDotNetPublic\\sdk\\src\\Core\\Amazon.Runtime\\Pipeline\\ErrorHandler\\ErrorHandler.cs:141

**Comment by gokarnm** [comment]
Hi @TiagoJSM, the [AWS Mobile SDK for Unity](http://docs.aws.amazon.com/mobile/sdkforunity/developerguide/) currently does not support GameLift. If you are using the SDK bits that target .NET Framework 3.5/4.5, it would not work correctly.

**Comment by TiagoJSM** [comment]
Hello @gokarnm, thank you for letting me know

I'm going to close this issue then
