### ISSUE TITLE
BatchWrite and BatchGet methods missing in interface IDynamoDBContext

### ISSUE THREAD

**Issue by Reynier01** [aws/aws-sdk-net#658]
When using IDynamoDBContext for dependency injection to enable mocking for unit tests, the following methods are not available (although they are implemented in the concrete class "DynamoDBContext")

```
public BatchGet<T> CreateBatchGet<T>();
public BatchGet<T> CreateBatchGet<T>(DynamoDBOperationConfig operationConfig);
public BatchWrite<T> CreateBatchWrite<T>();
public BatchWrite<T> CreateBatchWrite<T>(DynamoDBOperationConfig operationConfig);
public MultiTableBatchGet CreateMultiTableBatchGet(params BatchGet[] batches);
public MultiTableBatchWrite CreateMultiTableBatchWrite(params BatchWrite[] batches);
```
This prevents us from using and testing these method by injecting the DynamoDBContext

## Expected Behavior
Contract between DynamoDBContext and IDynamoDBContext should include the 6 methods mentioned above:

```
        public MyClass(IDynamoDBContext context)
        {
            context.CreateBatchGet<MyEntity>();
            context.CreateBatchGet<MyEntity>(new DynamoDBOperationConfig());
            context.CreateMultiTableBatchGet(...);

            context.CreateBatchWrite<MyEntity>();
            context.CreateBatchWrite<MyEntity>(new DynamoDBOperationConfig());
            context.CreateMultiTableBatchWrite(...);
        }
```

## Current Behavior
No contract between concrete class and interface for 6 methods mentioned above

## Possible Solution
Add 6 methods mentioned above to `IDynamoDBContext` interface.

## Steps to Reproduce (for bugs)
```
        public MyClass(IDynamoDBContext context)
        {
            context.CreateBatchGet<MyEntity>();
            context.CreateBatchGet<MyEntity>(new DynamoDBOperationConfig());
            context.CreateMultiTableBatchGet(...);

            context.CreateBatchWrite<MyEntity>();
            context.CreateBatchWrite<MyEntity>(new DynamoDBOperationConfig());
            context.CreateMultiTableBatchWrite(...);
        }
```

## Context
We are trying to inject a DynamoDBContext into our classes, so that we can mock the DynamoDB service for unit tests

## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 1.1.0
* .NET Core version installed in the environment where application runs: 1.1.0
* Output of `dotnet --info`: 
.NET Command Line Tools (1.0.0-preview2-1-003177)
Product Information:
 Version:            1.0.0-preview2-1-003177
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

* Contents of project.json/project.csproj: 
```
{
  "version": "1.0.0-*",

  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.1.0"
    },
    "Amazon.Lambda.Core": "1.0.0",
    "AWSSDK.SQS": "3.3.1.9",
    "AWSSDK.DynamoDBv2": "3.3.4.12",
    "AWSSDK.S3": "3.3.5.9",
    "Newtonsoft.Json": "9.0.1"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  }
}
```

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by normj** [comment]
Yes, I agree they are missing on the .NET Core version of the interface. I'll take a look at adding those onto the interface.

**Comment by Reynier01** [comment]
Awesomeness! I will look out for the update.

**Comment by normj** [comment]
Version 3.3.4.13 of AWSSDK.DynamoDBv2 package was released today with these methods added to the interface.
