### ISSUE TITLE
Default value confusion in ReceiveMessageRequest (SQS)

### ISSUE THREAD

**Issue by omerkorenn** [aws/aws-sdk-net#664]
Hi,

I'm using SQS, and i found `WaitTimeSeconds` property confusing.
In the POV of the developer, this property should be `int`, which means that its default value is 0.
Where under the surface, you are using `int?` and if no one set this property it gets of course `null`.
Both have different behavior of the long polling settings.
I suggest to reflect outside that the type of the property is nullable.
So developers, can infer from the code, that there is difference between 0 and null, and expect different behavior.

https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/SQS/Generated/Model/ReceiveMessageRequest.cs

(I think same goes to other properties as well)

Thanks.

**Comment by sstevenkang** [comment]
Yes, I agree.  However, changing the type of the member would be a backward incompatible change and will break other developer's code that relies on this value being a primitive int instead of a nullable int. In the next major version of the SDK, we'll consider making this change.
