### ISSUE TITLE
DynamoDB SDK - No unprocessed item information when DocumentBatchWrite throws exception

### ISSUE THREAD

**Issue by kckc** [aws/aws-sdk-net#665]
When a ProvisionedThroughputExceededException happens in the middle of a batch write, We don't know what items are processed and what isn't. 

## Expected Behavior
Like the UnprocessedItems property in Low-level Batch Write response, there should be some information about what items are added to DynamoDB and what isn't.

## Current Behavior
Currently the sdk throws a ProvisionedThroughputExceededException with no indication of what is processed.

## Possible Solution
In the exception, include a ResponseBody or some parameter that contains the unprocessed items.

## Context
We have a periodic job that copies data from a SQL database into DynamoDB, once the data is inside DynamoDB, they will be deleted from SQL database. If the batch write is partially successful, we don't know what data are already copied in DynamoDB without querying it. This risk duplicating data or truncating data.

## Your Environment
* AWSSDK.Core version used: v3.3.14
* Service assembly and version used: AWSSDK.DynamoDBv2 v3.3.4.13
* Operating System and version: Windows 10
* Visual Studio version: Visual Studio 2015 Update 3
* Targeted .NET platform: Windows

**Comment by PavelSafronov** [comment]
This is related #623 and is a known feature request. Your table is likely severely under-provisioned, and in my long response in that issue should provide some relevant information about this case and possible workarounds.

Closing, but feel free to respond if you feel we should keep this issue open as well.

**Comment by kckc** [comment]
Thanks for the response and your reply in the other issue is very helpful and thorough!

**Comment by dcsena** [comment]
Hey, looks 5 years later and the high-level SDK still doesn't give unprocessed items in the response? Is this the right place to +1 this feature request?
