### ISSUE TITLE
AWSPowerShell: Write-S3Object uses virtual host mode when EndpointUrl is set

### ISSUE THREAD

**Issue by dermeister0** [aws/aws-sdk-net#670]
## Expected Behavior

I'm trying to upload a file to S3-compatible storage (Minio). It works fine with AWS CLI, but fails with PowerShell cmdlet.

```
PS C:\Temp> &"C:\Program Files\Amazon\AWSCLI\aws.exe" s3 cp .\test.txt s3://mybucket/s3test.txt --endpoint-url https://s3.example.com
upload: .\test.txt to s3://mybucket/s3test.txt
```

## Current Behavior

```
PS C:\Temp> Write-S3Object -BucketName mybucket -Key s3test.txt -File .\test.txt -EndpointUrl https://s3.example.com

A WebException with status NameResolutionFailure was thrown.
```

```
PS C:\Temp> Write-S3Object -BucketName s3 -Key mybucket/s3test.txt -File .\test.txt -EndpointUrl https://s3.example.com

PUT https://s3.example.com/s3/mybucket/s3test.txt

The specified bucket is not valid.
```

Write-S3Object always tries to use virtual host (mybucket.s3.example.com).

## Possible Solution

If EndpointUrl is set, use path style method (https://s3.example.com/mybucket) instead of virtual hosted style (https://mybucket.s3.example.com).

## Steps to Reproduce (for bugs)

Try to upload a file using Write-S3Object to S3-compatible storage that does not support virtual hosts for buckets.

## Context

[Minio](https://www.minio.io/) runs on s3.example.com.

## Your Environment

```
PS C:\Temp> (Get-Module AWSPowerShell).Version

Major  Minor  Build  Revision
-----  -----  -----  --------
3      3      99     0
```

**Comment by steveataws** [comment]
The SDK is coded to switch to virtual style addressing if the bucket name is DNS compatible - see lines 120 and 124 in https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/S3/Custom/Internal/AmazonS3PostMarshallHandler.cs. As you will see, the SDK does have a configuration setting to force path style addressing if needed, but this isn't currently exposed in the S3 cmdlets.

Adding a new switch parameter to the S3 cmdlets to set this config switch to force path addressing, if -EndpointUrl is used, would address this issue. I'll make and test the change, but I don't have an ETA for release just now.

**Comment by steveataws** [comment]
v3.3.119.0, just released, contains a change to the S3 cmdlets behavior to match the AWS CLI. If -EndpointUrl is specified, the cmdlets switch over automatically to path style addressing.

Resolving.
