### ISSUE TITLE
S3 Signature V4 Chunked Upload seems to be missing the required Content-Encoding header

### ISSUE THREAD

**Issue by GuySirton** [aws/aws-sdk-net#678]
The content-encoding: aws-chunked header appears to be missing from simple S3 PUT object requests made with the SDK.  This header is seemingly required per the Amazon docs [Transferring Payload in Multiple Chunks](http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html#example-signature-calculations-streaming):

> you must include the following headers: ... Content-Encoding ... Set the value to aws-chunked. 

The absence of the header causes the upload to fail with some 3rd party S3 implementations and could fail in the future with AWS S3.

## Expected Behavior
HTTP request with chunked upload should have the Content-Encoding HTTP header set to aws-chunked.

## Current Behavior
Uploading an object via PutObjectRequest results in the following (Wireshark captured) request:

> PUT /bucket-65916701/object-67786390 HTTP/1.1
> Content-Type: text/plain
> x-amz-meta-color: Yellow
> x-amz-meta-size: Large
> User-Agent: aws-sdk-dotnet-45/3.3.7.0 aws-sdk-dotnet-core/3.3.14.1 .NET_Runtime/4.0 .NET_Framework/4.0 OS/Microsoft_Windows_NT_6.1.7601_Service_Pack_1 ClientSync
> host: 10.96.99.147:18082
> X-Amz-Date: 20170620T220803Z
> X-Amz-Decoded-Content-Length: 5
> X-Amz-Content-SHA256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD
> Authorization: AWS4-HMAC-SHA256 Credential=3BH0GKN78U80LK4MTOX8/20170620/us-east-1/s3/aws4_request, SignedHeaders=content-length;content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length;x-amz-meta-color;x-amz-meta-size, Signature=7360771f56b9fcd0abe0a638b8a94e29774c85a61f2825def4fa237c5223ac09
> Content-Length: 177
> Expect: 100-continue
> 
> HTTP/1.1 100 Continue
> 
> 5;chunk-signature=1d3be98c5974e40689bb9cb22a4ec760050e8efcef603759050b043348de8b21
> Hello
> 0;chunk-signature=dcb82f2f6f476b08a8bc54e5ad84189098d0c2627652326102f3b2ebfb431fcc

## Possible Solution
https://github.com/aws/aws-sdk-net/blob/1fb233d6ebe1e988c847699f936e4b87034d5774/sdk/src/Core/Amazon.Runtime/Internal/Auth/AWS4Signer.cs#L428

This code appears to append the content encoding if one is present but doesn't create the header otherwise.  Create the header here if there is none.

## Steps to Reproduce (for bugs)
```
PutObjectRequest request = new PutObjectRequest()
            {
                BucketName = "bucket-65916701",
                Key = "object-67786390",
                ContentBody = "Hello"
            };
request.Metadata.Add("color", "Yellow");
request.Metadata.Add("size", "Large");
PutObjectResponse response = s3Client.PutObject(request);
```

## Context
I'm using the SDK with in-house S3 compatible software and I'm unable to upload objects into the system.

## Your Environment
AWSToolsAndSDKForNet_sdk-3.3.111.0_ps-3.3.109.0_tk-1.12.1.1

* AWSSDK.Core version used: 3.3.0.0
* Operating System and version:  Windows 7 x64
* Visual Studio version:  2015 Professional
* Targeted .NET platform: 4.5.2

## .NET Core Info

* .NET Core version used for development: 4.5.2
* .NET Core version installed in the environment where application runs: 4.5.2
* Contents of project.json/project.csproj: 

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProductVersion>9.0.30729</ProductVersion>
    <SchemaVersion>2.0</SchemaVersion>
    <ProjectGuid>{2ECCA326-DA2E-4B3E-8152-459FF716B7FC}</ProjectGuid>
    <OutputType>Exe</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>S3TestClientCSharp</RootNamespace>
    <AssemblyName>S3TestClientCSharp</AssemblyName>
    <TargetFrameworkVersion>v4.5.2</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <IsWebBootstrapper>false</IsWebBootstrapper>
    <FileUpgradeFlags>
    </FileUpgradeFlags>
    <OldToolsVersion>3.5</OldToolsVersion>
    <UpgradeBackupLocation />
    <PublishUrl>publish\</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Disk</InstallFrom>
    <UpdateEnabled>false</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <ApplicationRevision>0</ApplicationRevision>
    <ApplicationVersion>1.0.0.%2a</ApplicationVersion>
    <UseApplicationTrust>false</UseApplicationTrust>
    <BootstrapperEnabled>true</BootstrapperEnabled>
    <TargetFrameworkProfile />
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <DocumentationFile>
    </DocumentationFile>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <DocumentationFile>
    </DocumentationFile>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it.
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
  <Choose>
    <When Condition=" '$(TargetFrameworkVersion)' == 'v3.5' Or '$(TargetFrameworkVersion)' == 'v4.0' ">
      <ItemGroup>
        <Reference Include="AWSSDK.Core, Version=3.0.0.0, Culture=neutral, processorArchitecture=MSIL">
          <SpecificVersion>False</SpecificVersion>
          <Private>True</Private>
          <HintPath>C:\Program Files (x86)\AWS SDK for .NET\bin\Net35\AWSSDK.Core.dll</HintPath>
        </Reference>
        <Reference Include="AWSSDK.EC2, Version=3.0.0.0, Culture=neutral, processorArchitecture=MSIL">
          <SpecificVersion>False</SpecificVersion>
          <Private>True</Private>
          <HintPath>C:\Program Files (x86)\AWS SDK for .NET\bin\Net35\AWSSDK.EC2.dll</HintPath>
        </Reference>
        <Reference Include="AWSSDK.SimpleDB, Version=3.0.0.0, Culture=neutral, processorArchitecture=MSIL">
          <SpecificVersion>False</SpecificVersion>
          <Private>True</Private>
          <HintPath>C:\Program Files (x86)\AWS SDK for .NET\bin\Net35\AWSSDK.SimpleDB.dll</HintPath>
        </Reference>
        <Reference Include="AWSSDK.S3, Version=3.0.0.0, Culture=neutral, processorArchitecture=MSIL">
          <SpecificVersion>False</SpecificVersion>
          <Private>True</Private>
          <HintPath>C:\Program Files (x86)\AWS SDK for .NET\bin\Net35\AWSSDK.S3.dll</HintPath>
        </Reference>
      </ItemGroup>
    </When>
    <Otherwise />
  </Choose>
  <ItemGroup>
    <Reference Include="AWSSDK.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604, processorArchitecture=MSIL">
     <SpecificVersion>False</SpecificVersion>
      <HintPath>..\..\..\..\Program Files (x86)\AWS SDK for .NET\bin\Net45\AWSSDK.Core.dll</HintPath>
    </Reference>
    <Reference Include="AWSSDK.S3, Version=3.3.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\..\..\..\Program Files (x86)\AWS SDK for .NET\bin\Net45\AWSSDK.S3.dll</HintPath>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.configuration" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="S3TestClientCSharp.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <BootstrapperPackage Include="Microsoft.Net.Client.3.5">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1 Client Profile</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.2.0">
      <Visible>False</Visible>
      <ProductName>.NET Framework 2.0 %28x86%29</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.0">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.0 %28x86%29</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
  </ItemGroup>
  <ItemGroup>
    <None Include="App.config">
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>
</Project>

```

**Comment by PavelSafronov** [comment]
This was a [recent change](https://github.com/aws/aws-sdk-net/blob/master/SDK.CHANGELOG.md#33800-2017-04-21-1802-utc) to fix [an issue where the Content-Encoding header was being set to an empty string](https://github.com/aws/aws-sdk-net/issues/559). You can roll back to a version of AWSSDK.Core earlier than 3.3.13.0, and that should work with the non-S3 system you're using.

**Comment by GuySirton** [comment]
Is this bug fixes?  I don't see the commit hash.  Thanks!

**Comment by grofit** [comment]
I have this issue too, I appreciate that a fix for an existing bug caused this behaviour but it still seems like this is a bug not a question, as reverting to a previous version does not seem to be a suitable fix, just a workaround.

**Comment by bhaskar2018** [comment]
I also have this issue. The Content-Encoding header is still missing.
I tried to upload an object using aws sdk .net 4.5 sample program, and the request didn't have Content-Encoding set.

aws-sdk-dotnet-45/3.3.8.2 aws-sdk-dotnet-core/3.3.17.0 .NET_Runtime/4.0 .NET_Framework/4.0 OS/Microsoft_Windows_NT_6.2.9200.0 ClientAsync TransferManager/MultipartUploadCommand'

Request:
`{'HTTP_AUTHORIZATION': 'AWS4-HMAC-SHA256 Credential=4a203e8a63cc4fdfa4bbd3ea6c208bac/20181228/us-east-1/s3/aws4_request, SignedHeaders=content-length;content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=e7d32398ec602bd2fbfbbcd613ba26835d2036f6215862255a04ee91dadb242e', 'SCRIPT_NAME': '', 'keystone.token_auth': <keystonemiddleware.auth_token._user_plugin.UserAuthPlugin object at 0x7f00e68d5b90>, 'webob.adhoc_attrs': {'response': <_AuthTokenResponse at 0x7f00e68d5f50 200 OK>}, 'REQUEST_METHOD': 'PUT', 'HTTP_X_AMZ_DATE': '20181228T181903Z', 'PATH_INFO': '/bucket1/BBBunny123', 'SERVER_PROTOCOL': 'HTTP/1.0', 'QUERY_STRING': 'partNumber=4&uploadId=YzQ0Yjk2MzMtMzdhYy00NDkyLWEwZjItZjBhYjA0M2FjYjMx', 'REMOTE_ADDR': '150.50.2.89', 'CONTENT_LENGTH': '5246566', 'HTTP_X_AMZ_DECODED_CONTENT_LENGTH': '5242880', 'HTTP_USER_AGENT': 'aws-sdk-dotnet-45/3.3.8.2 aws-sdk-dotnet-core/3.3.17.0 .NET_Runtime/4.0 .NET_Framework/4.0 OS/Microsoft_Windows_NT_6.2.9200.0 ClientAsync TransferManager/MultipartUploadCommand', 'eventlet.posthooks': [], 'RAW_PATH_INFO': '/bucket1/BBBunny123', 'REMOTE_PORT': '58993', 'eventlet.input': <eventlet.wsgi.Input object at 0x7f00df266250>, 'HTTP_X_IDENTITY_STATUS': 'Invalid', 'wsgi.url_scheme': 'http', 'SERVER_PORT': '80', 'HTTP_X_AMZ_CONTENT_SHA256': 'STREAMING-AWS4-HMAC-SHA256-PAYLOAD', 'wsgi.input': <eventlet.wsgi.Input object at 0x7f00df266250>, 'HTTP_HOST': 'hostname.xxx.xxx.xxx', 'wsgi.multithread': True, 'HTTP_EXPECT': '100-continue', 'wsgi.version': (1, 0), 'SERVER_NAME': '150.50.2.132', 'GATEWAY_INTERFACE': 'CGI/1.1', 'wsgi.run_once': False, 'wsgi.errors': <swift.common.utils.LoggerFileObject object at 0x7f00df2665d0>, 'wsgi.multiprocess': False, 'swift.trans_id': 'tx8f4b1c9093d1422389664-005c266917', 'CONTENT_TYPE': 'text/plain', 'swift.cache': <swift.common.memcached.MemcacheRing object at 0x7f00df2667d0>}`
