### ISSUE TITLE
Bypass server side ssl validation in Amazon client in .NET core

### ISSUE THREAD

**Issue by VenkateshSrini** [aws/aws-sdk-net#686]
Hi,
While using Amazon s3 client in .NET core, I would like to provide an option to by pass server side certificate validation. How do I do that. In .net core I can achieve the same by passing the HTTPClientHandler to Http client but how do I set the same for Amazon s3 client?

**Comment by normj** [comment]
We don't currently have an exposed way to do that in the SDK.

**Comment by VenkateshSrini** [comment]
Hi normj,
Ok no issues. Is there some guidance that you can help us with so that we can do it for our own by taking the source code?
Also when is this feature expected to be available

**Comment by normj** [comment]
The class [HttpRequestMessageFactory.cs](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Pipeline/HttpHandler/_mobile/HttpRequestMessageFactory.cs) is what manages the HttpClient for the SDK. Don't let the _mobile directory fool you. For both Xamarin and .NET Core we use HttpClient and we did Xamarin first which is why it is in the _mobile folder.

We have no planned feature to expose turning off SSL validation.

**Comment by VenkateshSrini** [comment]
Hi,
I have added this as an attribute in ICLientConfig. The same bas been handled in client config. Could you please tell him how the client config attributes are populated from S3 Options

**Comment by VenkateshSrini** [comment]
I have added a validate certificate in ICLientconfig. Then in the cientConfig I have added a variable. By default it will be true. If the user wants t turn this off, he can set the value in the through configuration. Based on that ServerCertifcate delegate will be added. I have done the code changes and pushed the same. Please let me know if additional things needs to be done

**Comment by VenkateshSrini** [comment]
@normj ,
Has this feature been implemented now. If so how do the same

**Comment by VenkateshSrini** [comment]
@normj,
Can you please tell me if the same has been implemented now?

**Comment by jduke123** [comment]
Has this been implemented? Currently running into the same issue.

**Comment by VenkateshSrini** [comment]
Yes a solution to this problem is available. Please see the sample code @ https://github.com/VenkateshSrini/S3SSSSLFactory.
