### ISSUE TITLE
DynamoDBv2 error on 3.3.4.15

### ISSUE THREAD

**Issue by rserna2** [aws/aws-sdk-net#687]
Hello,

The following is no longer working with the new version

AmazonDynamoDBClient client = new AmazonDynamoDBClient();
  Table ThreadTable = Table.LoadTable(client, "sometable");

**Comment by normj** [comment]
What error are you getting? Also can you describe the platform you are running on?

**Comment by aliniacobv** [comment]
Running this code locally, in a .net core console app (target .net core 1.1) and it will work. 
Publish the code in a lambda function in aws, and it crashes.

**Comment by rserna2** [comment]
It's a lambda function. The moment the above code is executed the following error displays

{
  "errorMessage": "RequestId: 791ef616-****-11e7-****-******** Process exited before completing request"
}

The moment AWSSDK.DynamoDBv2 is reverted back to version 3.3.4.14 everything works.

**Comment by rserna2** [comment]
That is correct.

The issue is when publishing the code in a lambda function.

**Comment by gokarnm** [comment]
Could you share your project.json or csproj file?

**Comment by rserna2** [comment]
"profile"     : "default",
    "region"      : "us-east-1",
    "configuration" : "Release",
    "framework"     : "netcoreapp1.0",
    "function-runtime" : "dotnetcore1.0",
    "function-memory-size" : 256,
    "function-timeout"     : 30,
    "function-handler"     :
"AWSProject::AWSProject.Function::FunctionHandler",
    "function-name"        : "AWSProject",
    "function-role"        : "arn:aws:iam::usernumber:role/rolename",
    "environment-variables" : ""

**Comment by rserna2** [comment]
This is the same behavior I am experiencing.

**Comment by sstevenkang** [comment]
Thanks for reporting this.  We discovered that we introduce a bad dependency which led to the lambda execution failiure.  Please update all your AWSSDK nuget packages to the latest and let us know if the issue persists.

**Comment by rserna2** [comment]
Thank you for you prompt response.

It works well now.
