### ISSUE TITLE
Incomplete list of functions in Select Project Source window (New AWS Lambda Project)

### ISSUE THREAD

**Issue by bpavlov** [aws/aws-sdk-net#688]
When I try to create new Lambda Project from already existing Lambda in cloud I am not able to see all Lambdas in my account. 

I am using:
Visual Studio 2017 v15.2 build 26430.14
AWS Toolkit v1.12.1.1

![image](https://user-images.githubusercontent.com/2480572/27957438-3a23352c-6327-11e7-82bf-d28b432fffd2.png)

**Comment by steveataws** [comment]
Can you check to see if there any signs of errors relating to the calls to get the function list in your toolkit logs, stored at %USERPROFILE%\AppData\Local\AWSToolkit\logs\visualstudio ? It might be easier to check if you close down all VS instances, delete any existing logs, then start up VS and bring up the wizard before checking the log contents.

**Comment by bpavlov** [comment]
I am not receiving any errors. 

> 2017-07-24 16:10:33,975 [1] INFO  Amazon.AWSToolkit.S3FileFetcher - Loading hosted file 'AccountTypes.xml' from local path 'C:\Users\XXXXXXX\AppData\Local/AWSToolkit/downloadedfiles/AccountTypes.xml'

> 2017-07-24 16:10:35,629 [1] INFO  Amazon.AWSToolkit.Utility - ...resolved for C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\fox34xob.jy3\SDK\AWSSDK.Core.dll

> 2017-07-24 16:14:31,142 [38] INFO  Amazon.AWSToolkit.MobileAnalytics.AMAServiceCallHandler - Reponse from AMAClient.PutEvents(request) meta data: Amazon.Runtime.ResponseMetadata, response HttpStatusCode: Amazon.Runtime.ResponseMetadata

> 2017-07-24 16:15:28,342 [21] INFO  Amazon.AWSToolkit.S3FileFetcher - Loading hosted file 'LambdaSampleFunctions/SampleFunctionsManifest.xml' from local path 'C:\Users\XXXXXXX\AppData\Local/AWSToolkit/downloadedfiles/LambdaSampleFunctions/SampleFunctionsManifest.xml'

> 2017-07-24 16:15:28,342 [1] INFO  Amazon.AWSToolkit.MobileAnalytics.SimpleMobileAnalytics - Queuing analytics event in local queue with timestamp: 07/24/2017 13:15:28

> 2017-07-24 16:15:28,342 [1] INFO  Amazon.AWSToolkit.MobileAnalytics.SimpleMobileAnalytics - Queuing analytics event in local queue with timestamp: 07/24/2017 13:15:28

> 2017-07-24 16:15:28,384 [1] INFO  Amazon.AWSToolkit.S3FileFetcher - Loading hosted file 'flags/usa.png' from local path 'C:\Users\XXXXXXX\AppData\Local/AWSToolkit/downloadedfiles/flags/usa.png'

> 2017-07-24 16:15:28,422 [1] INFO  Amazon.AWSToolkit.S3FileFetcher - Loading hosted file 'AccountTypes.xml' from local path 'C:\Users\XXXXXXX\AppData\Local/AWSToolkit/downloadedfiles/AccountTypes.xml'

> 2017-07-24 16:15:28,422 [1] INFO  Amazon.AWSToolkit.S3FileFetcher - Loading hosted file 'AccountTypes.xml' from local path 'C:\Users\XXXXXXX\AppData\Local/AWSToolkit/downloadedfiles/AccountTypes.xml'

**Comment by normj** [comment]
I found in the code we were filtering out Node.js 6.10 Lambda functions. I have made the fix which will go out with the next version. Is it possible that was causing your problem?

**Comment by normj** [comment]
Version 1.13.0.2 of the toolkit went out yesterday that added Node.js 6.10 functions to the list. I assume that was the problem. If not feel free to reopen.
