### ISSUE TITLE
AWSCredentials.GetCredentialsAsync should use Task.FromResult

### ISSUE THREAD

**Issue by damianh** [aws/aws-sdk-net#690]
Spotted this splunking the code https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Credentials/AWSCredentials.cs#L38 :

        public virtual System.Threading.Tasks.Task<ImmutableCredentials> GetCredentialsAsync()
        {
            return System.Threading.Tasks.Task.Run<ImmutableCredentials>(() => this.GetCredentials());
        }

Is the task offload specifically needed? Usually returning a synchronous result in a task, one would use `Task.FromResult`

## Possible Solution

        public virtual System.Threading.Tasks.Task<ImmutableCredentials> GetCredentialsAsync()
        {
            return System.Threading.Tasks.Task.FromResult<ImmutableCredentials>(this.GetCredentials());
        }

## Your Environment
* AWSSDK.Core version used:  3.3.8.2

**Comment by normj** [comment]
Thanks, you are right that is the better way. I'll make that change.

**Comment by damianh** [comment]
PR'd.

**Comment by sstevenkang** [comment]
Change is in master.  9d90caa5 and a new AWSSDK.Core nuget is available.  Closing.
