### ISSUE TITLE
Does StreamResponse really need to be disposable?

### ISSUE THREAD

**Issue by OskarKlintrot** [aws/aws-sdk-net#699]
## Expected Behavior
To be able to use `GetObjectAsync` like this:

```
            var response = await s3Client.GetObjectAsync(new GetObjectRequest
            {
                BucketName = bucketName,
                Key = keyName
            });
            using (var s = new StreamReader(response.ResponseStream))
            {
                var responseContent = s.ReadToEnd();
                Assert.AreEqual(testContent, responseContent);
            }
```
From [`CommonTests.IntegrationTests.S3.KeyNameTests.PutObjectWithQuestionableKey`](https://github.com/aws/aws-sdk-net/blob/1a5187e0dcddadba10a6b90fd827f2e485af0f9c/sdk/test/CrossPlatformTests/CommonTests/IntegrationTests/S3/KeyNameTests.cs#L109-L131)

## Current Behavior
Since `GetObjectResponse` inherits `StreamResponse` it must be disposed since [it won't be garbage collected](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/S3/Custom/Model/StreamResponse.cs#L43) in order to avoid memory leak (if I understand it correct). Now it must be used as in [`Amazon.DNXCore.IntegrationTests.S3.S3ServiceClientTests.TestS3PutWithBodyProperty`](https://github.com/aws/aws-sdk-net/blob/37b2546044248de151a6ce47641ba096728fb5cb/sdk/test/CoreCLR/IntegrationTests/IntegrationTests/S3/S3ServiceClientTests.cs#L49-L54):
```
            using (var getObjectResponse = await Client.GetObjectAsync(getObjectRequest))
            using (var reader = new StreamReader(getObjectResponse.ResponseStream))
            {
                var content = reader.ReadToEnd();
                Assert.Equal(putObjectRequest.ContentBody, content);
            }
```

## Possible Solution
Don't implement the disposable-pattern in `StreamResponse` and update the documentation. Sure it would be a breaking change but it will show up when compiling and will be super easy to fix and wont cause any pesky runtime errors. But it might fix some tiny memory leaks out there! :) 

## Context
The issue here is that since you have to dispose `getObjectResponse` you can't just simply do this:
```
// S3FileStorageService, implementing IFileStorageService
var response = await _s3Client.GetObjectAsync(request);
return (response.ResponseStream, response.Headers.ContentType);
```
```
// FileController, uses DI and IFileStorageService
// This works with more or less everything from local files to S3, Azure etc.
var file = await _fileStorageService.GetBlobAsync(filename);
return File(file.Stream, file.ContentType);
```

Since `response` in my example above should be disposed to avoid memory leaks you have to either copy the stream to a new stream that you can return (and hence reading the stream twice instead of just once) or wrap it in something else and return that, causing leaky abstractions. I can't find anything better on [SO](https://stackoverflow.com/a/6214185/4826084) either. You could always use `GetObjectMetadataAsync` to retrive `ContentType` together with the `OpenStreamAsync` method on the  `TransferUtility` class to retrieve the stream. This avoids the pain points I mentioned earlier but introduces a new one: calling S3 twice instead of just once.

**Comment by vellozzi** [comment]
This isn't something we can fix; we aren't able to introduce breaking changes.
The IDisposable pattern is common in .NET and we believe it's reasonable to include it in our interface.

**Comment by PavelSafronov** [comment]
To add to this, disposing of `StreamResponse` is the same as disposing of the `ResponsStream` object. So as long as you are disposing of the underlying stream, disposing of the `StreamResponse` object is optional and won't lead to a memory leak if it is skipped.
So the first snippet you posted does not leak memory. Third and fourth snippets are fine as well, assuming that `File` properly disposes of the stream.

**Comment by OskarKlintrot** [comment]
Thanks for the clarification @PavelSafronov! My knowledge about GC is very limited and I assumed that the `GC.SuppressFinalize(this)` in `StreamResponse` would cause it to never be garbage collected unless using a `using` block. You don't happen to have any link to some info about how it works that I can read up on? Sorry if I'm going a bit OT, just very curious about how this works!

**Comment by PavelSafronov** [comment]
[This SO question](https://stackoverflow.com/questions/3038571/) delves a bit into `GC.SuppressFinalize(this)`.
