### ISSUE TITLE
.net core 1.1 SNS message.IsMessageSignatureValid missing

### ISSUE THREAD

**Issue by brianmatic** [aws/aws-sdk-net#702]
I am trying to port code from a .Net 4.5 project to .Net core 1.1 project.  When I include the AWS SimpleNotificationService nuget package I am now missing methods that are on the SNS message object.  I can see in the source that there is a condition compile check for BCL around the methods.  How do I resolve this?

## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development:  1.1
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by vellozzi** [comment]
We've determined that the classes necessary to support this are included in .NET Core.
We're working on adding this now.

**Comment by vellozzi** [comment]
This is fixed in AWSSDK.SimpleNotificationService 3.3.0.21.
