### ISSUE TITLE
.Net Core HTTP connections are not reused

### ISSUE THREAD

**Issue by Chickenzilla** [aws/aws-sdk-net#703]
When using the AmazonDynamoDBClient in a high throughput fashion (1000+ requests/second), nodes can exhaust their ephemeral port pool due to the number of closed connections in TIME_WAIT.  Response times also suffer due to TCP/SSL connection setup handshaking for most/all requests.  After all ephemeral ports are exhausted, other services/operations on the node tend to fail as well, so the "damage" is not limited to DynamoDb clients.

## Expected Behavior
HTTP connections should be allowed to be reused, along with pipelining of requests if possible, unless specifically configured otherwise.  This would keep connections in the TIME_WAIT state to a minimum and improve latency over the wire.

## Current Behavior
HTTP connections are not reused and this is causing our application to exhaust the machine's ephemeral port pool, causing widespread issues not limited to loss of DynamoDb access.  Latency seems to also suffer, likely partly due to having to establish a connection all the time before the request proper can be made.

## Possible Solution
Unknown, something is not allowing the connection to be reused.  HttpClient (which I believe is employed in .Net Core), supports settings such as `httpClient.DefaultRequestHeaders.ConnectionClose = false;` and may require the entire response to be read and then disposed from each request in order to pipeline well.  The backend service also needs to allow connection reuse.

## Steps to Reproduce (for bugs)
We have created a public repo with a test case written in .Net Core 1.0 which will reproduce the issue when run.  It can be found at https://github.com/mParticle/aws-sdk-issues/tree/master/DynamoDbTester .  It requires a table set up which the default credentials have write access to, with a partition key of "key" and sufficient quota.  An example command line might be: `dotnet DynamoDbTester.dll <table-name> 0 8 3`, which in our testing produces plenty of traffic to observe the issue.

We have also tried various settings for the AmazonDynamoDBClient, such as turning on CacheHttpClient, enabling UseHttp, setting MaxConnectionsPerServer to 1000, and enabling ReadEntireResponse.  All have had no effect.

## Context
We're trying to launch a new service for our platform that utilizes DynamoDb at large scale.  We're in final production testing, and were blindsided by this issue when we ran out of ephemeral ports.  Our test app mimics the production load that caused the issue fairly closely, except for the artificial data and arbitrary waiting (our actual code consumes work from SQS as well).

## Your Environment

* Running on an EC2 instance of type c3.2xlarge
* AWSSDK.Core version used: 3.3.17
* Service assembly and version used: 3.3.4.16
* Operating System and version: Ubuntu 14.04.4 LTS
* Visual Studio version: Community 2015 w/ Update 3
* Targeted .NET platform: Built on .Net Core 1.0.0-preview2-003121, run on 1.0.1 and 1.1.0

## .NET Core Info

* .NET Core version used for development: 1.0.0-preview2-003121
* .NET Core version installed in the environment where application runs: Tried 1.0.1 (cee57bf6c981237d80aa1631cfe83cb9ba329f12) and 1.1.0 (928f77c4bc3f49d892459992fb6e1d5542cb5e86)
* Output of `dotnet --info`: 
```
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.4
```
* Contents of project.json/project.csproj: 
```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0"
    },
    "AWSSDK.DynamoDBv2": "3.3.4.16"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  }
}
```
[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by normj** [comment]
.NET Core version of the SDK does reuse the HttpClient by default. How long running the sample program till you start seeing errors?

**Comment by Chickenzilla** [comment]
With high enough load you can watch the TIME_WAIT connections grow with `sudo netstat -n | grep TIME_WAIT | grep ":443" | wc -l`, replacing :443 with :80 if UseHttp is enabled, of course.  To get it to fail, simply keep pushing more throughput until you exhaust all of your connections in TIME_WAIT.  I just did a HTTP test with low volume where I captured the packets and you are correct that the connections seem to be reused in that scenario, so it must be something specific to high load.

**Comment by Chickenzilla** [comment]
I can confirm I have a packet capture which shows the client closing the HTTP connections after 1 request when under high load.  Sadly, I can't reliably scrub this capture of potentially sensitive data or else I would post it somewhere.

**Comment by akatz0813** [comment]
This article might be of assistance.  https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

**Comment by akatz0813** [comment]
Hi @PavelSafronov Just want to add that this github issue is linked to a Production Down case 4181689071 and we are an Enterprise Support customer.  Anything we can do to assist in the testing and troubleshooting of this issue we will absolutely do!  Thank you!

**Comment by PavelSafronov** [comment]
I'm running your code sample on a c3.2xlarge instance against a table with 500/500 provisioned reads/writes, and the connections go up to ~25k but I never get the error you're seeing. Continuing to investigate, as obviously the connections in the thousands is an issue, but it is strange that I'm not able to get the same exception.

**Comment by akatz0813** [comment]
I believe you need to push it up over 32k connections...that's where ephemeral exhaustion hits.  We also tested with 5/1000 provisioned iops.

**Comment by PavelSafronov** [comment]
I tried running your sample application on Windows 10, and this does not result in the thousands of TIME_WAIT connections that occurs on Ubuntu. We're still investigating, though this does suggest that this may be the result of an edge case/bug inside HttpClient, and not something that the SDK has control over.

**Comment by PavelSafronov** [comment]
As @normj mentioned, the SDK is caching the HttpClient and is reusing it for these requests. [Relevant source](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Pipeline/HttpHandler/_mobile/HttpRequestMessageFactory.cs#L64).

**Comment by Chickenzilla** [comment]
Yeah, I found that code a short while ago and was hoping for a race condition or so, but a Windows 10 test with no issue would seem to indicate a deeper .net core bug on linux...

**Comment by Chickenzilla** [comment]
I have a *very* experimental idea I cobbled together that may mitigate this issue.  Basically, it's an option I added to your `IClientConfig` which tells the `HttpRequestMessageFactory.CreateHttpClient` function not to use HttpClients from other instances.  It will still cache its own HttpClient instead of making one per request (which is universally bad), however.  Then, externally to AWS SDK, I have made a pool of 32 AmazonDynamoDBClient's, which I iterate over each time I make a dynamo call.  This has allowed me to get more throughput with marginal TIME_WAIT connections at the cost of increased memory consumption and context switching.  I'll be testing with higher throughputs once I let this test bake for a bit to confirm my findings.

**Comment by gokarnm** [comment]
The difference in connection reuse on Windows vs Linux seems to be related to [corefx#21227](https://github.com/dotnet/corefx/issues/21227). There is another open issue [corefx#14612](https://github.com/dotnet/corefx/issues/14612) that talks about pipelining support not being available in WinHttpHandler or CurlHandler, which are user by HttpClient.

We'll continue to investigate this issue and check if we can implement a workaround in the SDK itself.

**Comment by PavelSafronov** [comment]
I just tried running your repro against HTTPS by removing the line `UseHttp = true` and the issue did not reproduce. Can you confirm that you are seeing this issue when hitting both HTTP and HTTPS endpoints, or just with HTTP?

**Comment by Chickenzilla** [comment]
We actually were seeing the issue only when using HTTPS (the default) in production, the UseHttp=true was an attempt to validate other scenarios and made it in to the test tool.  I'm very surprised you aren't running into the issue with HTTPS, but it's possible you need to use more throughput in HTTPS mode for some reason?  I can try to get it to repro using the tool with HTTPS, meantime.

**Comment by PavelSafronov** [comment]
Sigh, sorry about that, I was using netstat incorrectly. This is an issue with HTTP and HTTPS.

**Comment by Chickenzilla** [comment]
Glad to hear you are seeing it still, I just verified we're definitely seeing it with HTTPS anyhow.

**Comment by Chickenzilla** [comment]
So, I'm having a hell of a time integrating my workaround code into our solution via nuget.  Do you sign your publicly published packages with a different signing key then the one in this repo?  Also, would you be open to accepting a PR which essentially disables the global http client caching and makes it per client instance when on netcore?  In my testing I have found this to be something of a mitigation, by pooling service clients manually.

**Comment by PavelSafronov** [comment]
The officially-published assemblies use a different key than the one in this repo, correct.

It really depends on how this addition is exposed and what kind of an impact it has on the rest of the SDK. We will be more likely to accept the PR if it is purely an opt-in approach and doesn't introduce too much complexity or destabilizes the rest of the SDK.

**Comment by Chickenzilla** [comment]
I think the best way to make it opt-in is to add a new setting to `IClientConfig`/`ClientConfig`, maybe "ShareHttpClient"(?) which can default to true (current code flow) and when set to false will invoke the unsharable path in `HttpRequestMessageFactory.CreateHttpRequest()` where it checks `CanClientConfigBeSerialized`.  I'm definitely open to suggestions on how to make it cleaner.  I'm not sure what unit tests govern this area of code yet, either, so any help you could provide there would be appreciated.

**Comment by PavelSafronov** [comment]
That sounds like it's going in the right direction. We would want to make the setting self-explanatory enough that it's clear when it should be used, but without seeing exactly what the fix is it's hard to make a call.

Same thing for unit tests, without knowing what's changing I'm not sure how testing will be impacted yet. Are you thinking of unit tests around this specific issue (running tests in a Linux environment to test the TIME_WAIT issue), or running tests to make sure that your changes haven't broken other aspects of the SDK?

**Comment by Chickenzilla** [comment]
I was only thinking of unit tests to confirm my change wouldn't break anything else in the SDKs.  I think orchestrating a unit test which proves this issue on linux is outside the scope of what I'm willing to take on for this, as well as the fact that my change does not purport to fix anything, only mitigate.  

Regarding what the fix "is", the idea is somewhat simple: in CoreFx on linux, HttpClient holds a libcurl multi handle per instance of HttpClientHandler, and this is what is responsible for the connection pooling.  In my desired change, each Amazon service client instance will hold a unique instance of HttpClient and its associated handler, allowing me to pool clients such that the workload on any one client overwhelms it less than having one handle to service all of the traffic.  Currently the options are a new HttpClient per request, which is worse, or a globally cached instance, which causes this issue under high load.

**Comment by PavelSafronov** [comment]
Having an HttpClient per service client would be breaking/poor behavior for anyone who constructs a service client for every call, which as you noted is not optimal.

I wonder if instead we should be adding an HttpClientCache, which is keyed off the endpoint - similar to [the current cache](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Pipeline/HttpHandler/_mobile/HttpRequestMessageFactory.cs#L42) - and the number of clients depends on the platform. In Windows this cache can be configured to hold a maximum of 1 HttpClient per endpoint, while in .NET Core on Linux it will hold `Environment.ProcessorCount` instances. (The number of cached clients will of course be user-configurable.) Then when a service request is made we'll retrieve a random HttpClient instance from the cache. It seems like it should be the same approach as what you're doing with multiple service clients.

**Comment by Chickenzilla** [comment]
That is definitely a good option; I was suggesting changes with an eye to keep modified code in your library to a minimum but since you're going to be publishing it, it makes more sense to make it a more universal solution at the cost of additional changes.  Are you able to implement this?

**Comment by PavelSafronov** [comment]
I'm trying to gather more information from the corefx team ([issue 21227](https://github.com/dotnet/corefx/issues/21227)) to understand exactly what's happening here, as that may impact what kind of a fix we make. After we get that information we'll implement a corresponding fix, which may be the HttpClient cache I described.

Are you currently unblocked by your workaround?

**Comment by Chickenzilla** [comment]
I would have been, but the surface area of AWS SDKs in our various projects, combined with the fact that I cannot compile a drop-in replacement for only one of them because the signing keys are different, means I am not.  That's why I was asking about you publishing the changes instead.

**Comment by PavelSafronov** [comment]
If your approach is isolated to changes in `HttpRequestMessageFactory.CreateHttpClient`, then that workaround can be made at runtime, without having to modify any SDK code.

Here's a rough overview of what's involved:
1. Copy [HttpRequestMessageFactory.cs](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Pipeline/HttpHandler/_mobile/HttpRequestMessageFactory.cs) into your codebase and make the required changes to `HttpRequestMessageFactory.CreateHttpClient`
2. Subclass `AmazonDynamoDBClient`
3. Override `CustomizeRuntimePipeline` and replace the [default HttpHandler](https://github.com/aws/aws-sdk-net/blob/756b9be7952aff2072441d1bb1b407990b071cd5/sdk/src/Core/Amazon.Runtime/AmazonServiceClient.cs#L420-L421) with your own implementation
4. Wherever you instantiated `AmazonDynamoDBClient`, instantiate the subclass now
5. Calls through this client will now be using your logic for HttpClient creation/caching

I think the above should unblock you entirely until we figure out, implement, test, and release a generic SDK solution.

**Comment by Chickenzilla** [comment]
I will look into doing this, thanks!

**Comment by PavelSafronov** [comment]
Earlier you mentioned keeping a pool of DynamoDB clients around and using those. Reading over the code again I stumbled on another approach that you can use to guarantee that each DynamoDB client has its own HttpClient, without needing to modify any SDK code. You simply need to set `AmazonDynamoDBConfig.MaxConnectionsPerServer` to a different value. Below code snippet tests out this approach. You can see that a different number of clients is cached if you comment out the `MaxConnectionsPerServer` line of code.

```
var httpClientCache = typeof(Amazon.Runtime.HttpRequestMessageFactory)
    .GetTypeInfo()
    .GetField("_httpClientCache", BindingFlags.Static | BindingFlags.NonPublic)
    .GetValue(null) as IDictionary<string, HttpClient>;
for(int i=0;i<10;i++)
{
    var config = new AmazonDynamoDBConfig
    {
        RegionEndpoint = RegionEndpoint.USEast1,
        MaxConnectionsPerServer = 10 * 1024 + i
    };
    using (var client = new AmazonDynamoDBClient(config))
    {
        await client.ListTablesAsync();
    }
}

Console.WriteLine("HttpClientCache size = {0}", httpClientCache.Count);
```

**Comment by anjmao** [comment]
I have the same issue and sometimes getting up to 4 seconds latency because of many TIME_WAIT connections also seems like MaxConnectionsPerServer is not helping either. Looks like this is the issue with HttpClient itself. @Chickenzilla have you tried any workaround?

**Comment by Chickenzilla** [comment]
We tried several, eventually going with the most recent workaround posted (a pool of object with different max connections per instance).  We don't have enough data yet to confirm the issue is mitigated yet, however.

**Comment by jweyrich** [comment]
Not sure if it's the same problem, but I faced something similar with `CLOSE_WAIT` - I filled an issue for myself at https://github.com/teltec/Everest/issues/15. There are some screenshots attached showing multiple connections in `CLOSE_WAIT` state.

**Comment by normj** [comment]
I have pushed version 3.3.18 of AWSSDK.Core which has the new property **HttpClientCacheSize** on the base class for all of the service client config like AmazonDynamoDBConfig which will allow you to increase the number of HttpClient objects the SDK will use. This will help when the amount of requests coming through overwhelms the underlying libcurl implementation of the non-windows version of HttpClient. On Windows the default value for **HttpClientCacheSize** is still 1 so there will be no change in behavior because this problem as not been reproducible on Windows. On other platforms the default is equal to **System.Environment.ProcessorCount**
