### ISSUE TITLE
DownloadDirectoryProgressArgs: NumberOfFilesDownloaded always zero when  AmazonS3EncryptionClient used

### ISSUE THREAD

**Issue by LarryEllis** [aws/aws-sdk-net#705]
When using client-side encryption (AmazonS3EncryptionClient) and the TransferUtility DownloadDirectory method, progress statistics are supposed to be available through the DownloadedDirectoryProgressEvent event.

The event fires just fine.   All the progress statistics are present and correct, with one exception:  the count of files transferred (NumberOfFilesDownloaded) is always zero.

This symptom only occurs with the encrypting client.   When using the standard AmazonS3Client, all statistics are correct.

## Expected Behavior
NumberOfFilesDownloaded should increment as the transfer progresses.

## Current Behavior
NumberOfFilesDownloaded remains zero

## Steps to Reproduce

Create folder called c:\testdir, then copy half dozen good sized files there (>8K each)

Run following console program.

	using System;
	using Amazon.S3;
	using Amazon.S3.Encryption;
	using Amazon.S3.Transfer;
	using System.IO;
	using System.Security.Cryptography;
	
	namespace ProgressReportingFailureS3
	{
	class Program
	{
        static string _keyID = "<REDACTED>";
        static string _secretAccessKey = "<REDACTED>";
        static string _bucketName = "<REDACTED>";

        static string _rsaKey;
       

        static void Main(string[] args)
        {
            var rsa = RSA.Create();
            _rsaKey = rsa.ToXmlString(true);

            DirectoryUploader.Upload();

            DirectoryDownloader.Download();

            Console.ReadLine();
        }

        class DirectoryUploader
        {

            static IAmazonS3 client;

            public static void Upload()
            {
                try
                {
                    UploadDirectory();
                }
                catch (AmazonS3Exception s3Exception)
                {
                    Console.WriteLine(s3Exception.Message,
                                      s3Exception.InnerException);
                }
            }

            static void UploadDirectory()
            {

                using (client = GetClient())
                {
                    TransferUtility transferUtility = new TransferUtility(client);
                    TransferUtilityUploadDirectoryRequest uploadRequest =
                        new TransferUtilityUploadDirectoryRequest
                        {
                            BucketName = _bucketName,
                            Directory = @"C:\testdir",
                            KeyPrefix = "testdir",
                            ServerSideEncryptionMethod = ServerSideEncryptionMethod.AES256,
                            SearchOption = SearchOption.AllDirectories,
                            UploadFilesConcurrently = true,
                            SearchPattern = @"*"
                        };

                    uploadRequest.UploadDirectoryProgressEvent +=
                        new EventHandler<UploadDirectoryProgressArgs>
                            (uploadDirectoryRequest_UploadDirectoryPartProgressEvent);

                    transferUtility.UploadDirectory(uploadRequest);
                    Console.WriteLine("\rUpload complete                                        ");

                }
            }

            static IAmazonS3 GetClient()
            {
                IAmazonS3 client;

                AmazonS3CryptoConfiguration config =
                    new AmazonS3CryptoConfiguration
                    { RegionEndpoint = Amazon.RegionEndpoint.USEast1 };

                RSA rsaAlgorithm = RSA.Create();
                rsaAlgorithm.FromXmlString(_rsaKey);

                EncryptionMaterials materials = new EncryptionMaterials(rsaAlgorithm);

                client = new AmazonS3EncryptionClient(_keyID, _secretAccessKey, config, materials);

                return client;

            }

            static void uploadDirectoryRequest_UploadDirectoryPartProgressEvent(object sender, UploadDirectoryProgressArgs e)
            {
                Console.Write("\r{0:0}% complete  {1} of {2} files transferred", e.TransferredBytes * 100.0 / e.TotalBytes, e.NumberOfFilesUploaded, e.TotalNumberOfFiles);
            }

        }

        //----------------------------------------------------------------------------------------------------

        class DirectoryDownloader
        {
            static IAmazonS3 client;

            public static void Download()
            {
                try
                {
                    DownloadDirectory();
                }
                catch (AmazonS3Exception s3Exception)
                {
                    Console.WriteLine(s3Exception.Message,
                                      s3Exception.InnerException);
                }
            }

            static void DownloadDirectory()
            {
                using (client = GetClient())
                {
                    {
                        TransferUtility transferUtility = new TransferUtility(client);

                        TransferUtilityDownloadDirectoryRequest downloadRequest =
                            new TransferUtilityDownloadDirectoryRequest
                            {
                                BucketName = _bucketName,
                                LocalDirectory = @"c:\testdir",
                                S3Directory = "testdir"

                            };

                        downloadRequest.DownloadedDirectoryProgressEvent +=
                            new EventHandler<DownloadDirectoryProgressArgs>
                                (downloadDirectoryRequest_DownloadPartProgressEvent);

                        //transferUtility.Download(downloadRequest);
                        transferUtility.DownloadDirectory(downloadRequest);

                    }
                }
            }
            static void downloadDirectoryRequest_DownloadPartProgressEvent(object sender, DownloadDirectoryProgressArgs e)
            {
                Console.Write("\r{0:0}% complete  {1} of {2} files transferred", e.TransferredBytes * 100.0 / e.TotalBytes, e.NumberOfFilesDownloaded, e.TotalNumberOfFiles);
            }
        }

        static IAmazonS3 GetClient()
        {
            IAmazonS3 client;

            AmazonS3CryptoConfiguration config =
                new AmazonS3CryptoConfiguration
                {
                    RegionEndpoint = Amazon.RegionEndpoint.USEast1
                };

            RSA rsaAlgorithm = RSA.Create();
            rsaAlgorithm.FromXmlString(_rsaKey);

            EncryptionMaterials materials = new EncryptionMaterials(rsaAlgorithm);

            client = new AmazonS3EncryptionClient(_keyID, _secretAccessKey, config, materials);

            return client;

        }

    }
 }

## Your Environment
.Net 4.5.2
 AWSSDK.S3 3.3.8.2
AWSSDK.Core 3.3.17

**Comment by sstevenkang** [comment]
Hi, @LarryEllis, we have a fix in review and will release it soon.  Thanks for reporting this!

**Comment by sstevenkang** [comment]
Hey, I forgot to update the thread, but we believe we fixed this with a5f9e0a56e8537099d94aeed51cad990d2be116b.  Let us know if the issue persists after updating it to the latest S3 package.

**Comment by sstevenkang** [comment]
Closing.
