### ISSUE TITLE
Incorrect Time In LocalRecord.DeviceLastModifiedDate

### ISSUE THREAD

**Issue by blindgoat** [aws/aws-sdk-net#707]
When resolving conflicts, `conflict.LocalRecord.DeviceLastModifiedDate` is incorrect. The h/m/s of the DateTime are correct for LOCAL time, but it's set to UTC Kind. It should be UTC but the h/m/s need to be properly converted.

## Expected Behavior
The `conflict.LocalRecord.DeviceLastModifiedDate` should be properly converted to UTC time instead of manually set to UTC with the same h/m/s

## Current Behavior
If it's 1700 local time, and 2300 UTC, the `DeviceLastModifiedDate` is stored as 1700 UTC when it should be 2300 UTC.

Example printouts of the local and remote conflicted record, where the issue is in the local record and marked by ***:
**Local**
`Key:[health], Value:[0], SyncCount:[28], LastModifiedDate:[07/27/2017 23:45:51], LastModifiedBy:[Amazon Cognito Management Console], DeviceLastModifiedDate:[***07/27/2017 17:46:16***], IsModified:[True]`

**Remote**
`Key:[health], Value:[100], SyncCount:[29], LastModifiedDate:[07/27/2017 23:46:25], LastModifiedBy:[Amazon Cognito Management Console], DeviceLastModifiedDate:[07/27/2017 23:46:25], IsModified:[False]`

## Steps to Reproduce
1. Ensure local time is different than UTC
2. Create a conflict by: making local change without syncing, make remote change, then sync
3. Look at `conflict.LocalRecord.DeviceLastModifiedDate` and note that the time matches your local time but it's using UTC Kind

## Context
I want to prefer local changes that are more recent than remote changes so I need to compare like:

```
if(conflict.LocalRecord.LastModifiedDate > conflict.RemoteRecord.LastModifiedDate ||
   correctedLocalRecordDeviceLastModifiedDate > conflict.RemoteRecord.LastModifiedDate)
	return conflict.ResolveWithLocalRecord();

return conflict.ResolveWithRemoteRecord();
```

but since `correctedLocalRecordDeviceLastModifiedDate` is incorrect, it won't work without manually fixing the DateTime.

## Environment

- AWSSDK.CognitoSync.3.3.1.21.unitypackage
- Windows 10
- Unity 5.6.0p3

**Comment by PavelSafronov** [comment]
Can you provide a full code sample illustrating the issue and the possible workaround you've developed?
If this can be a stand-alone console application (non-Unity) that would allow us to more quickly look into this issue.

**Comment by blindgoat** [comment]
Pavel,

I leave out of town in 15 minutes and can't deliver a full code sample in that time, but I will give you what I think will illustrate the fix.

```
private void Start()
{
	// other connection/starting info here
	
	_playerInfo.OnSyncConflict = SyncConflictCallback;
}

private bool SyncConflictCallback(Dataset dataset, List<SyncConflict> conflicts)
{
	List<Record> resolvedRecords = new List<Record>(conflicts.Count);
	foreach(SyncConflict conflict in conflicts)
	{
		resolvedRecords.Add(ResolveWithMostRecent(conflict));
	}

	dataset.Resolve(resolvedRecords);
	return true;
}

private Record ResolveWithMostRecent(SyncConflict conflict)
{
	System.DateTime correctedLocalRecordDeviceLastModifiedDate = GetProperDeviceLastModifiedDate(conflict.LocalRecord);
	if(conflict.LocalRecord.LastModifiedDate > conflict.RemoteRecord.LastModifiedDate || correctedLocalRecordDeviceLastModifiedDate > conflict.RemoteRecord.LastModifiedDate)
		return conflict.ResolveWithLocalRecord();

	return conflict.ResolveWithRemoteRecord();
}

private System.DateTime GetProperDeviceLastModifiedDate(Record record)
{
	System.DateTime badDate = (System.DateTime)record.DeviceLastModifiedDate;
	return new System.DateTime(badDate.Year, badDate.Month, badDate.Day, badDate.Hour, badDate.Minute, badDate.Second, System.DateTimeKind.Local).ToUniversalTime();
}
```

To cause the conflict to occur it's very straightforward:

1. link fb account and sync data to server
2. make local change to a field and do NOT sync to server
3. in AWS console, make remote change to the same field as in step 2 and sync it in console
4. sync on client and see conflict
5. notice that conflict.LocalRecord.DeviceLastModifiedDate is using UTC timezone but the timestamp is off by how every many hours your local time is off from UTC

**Comment by blindgoat** [comment]
**Update:** The problem is actually when the library stores the `device_last_modified_timestamp` in the local storage and I only happened to notice it during conflict resolution.

The bug is here: https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/CognitoSync/Custom/SyncManager/Storage/_unity/SQLiteLocalStorage.unity.cs#L475

Note that from the documentation of Record.cs, `deviceLastModifiedDate` is supposed to be 

> The local timestamp of this record when it was last modified.

I have verified that records are being written to the database with `deviceLastModifiedDate` stored as LOCAL time, but they are then read in as UTC time in the above link.

Hopes this helps :)

**Comment by blindgoat** [comment]
@PavelSafronov Do you need more info on this?

**Comment by blindgoat** [comment]
Can I get some sort of acknowledgement that this is a confirmed bug, so I make sure we are implementing things correctly?
