### ISSUE TITLE
AWSSDK AutoScaling not found (dotnet core)

### ISSUE THREAD

**Issue by bastiflew** [aws/aws-sdk-net#710]
Hello,

I try to use AutoScalingClient in a dotnet core 1.1 program.
I already use ECS in this program, and everything is fine.
But for AutoScaling, the namespace is not even found into Visual Studio 2017 Pro.
The installed nuget is AWSSDK.AutoScaling 3.3.1.

Is something missing into the SDK, or the nuget is corrupt ?
Thanks

**Comment by PavelSafronov** [comment]
This could be caused by the dotnet tools not properly restoring the dependencies. Try closing Visual Studio, then running `dotnet restore` from your project directory.

**Comment by bastiflew** [comment]
All nuget are installed correctly, actually I have only AWSSDK.ECS and AWSSDK.AutoScaling.
Both use AWSSDL.Core 3.3.17

**Comment by bastiflew** [comment]
Nevermind, after few close and reopen, switching to dotnet core 1.1.2 and everything is fine.
