### ISSUE TITLE
UnityMainThreadDispatcher is too heavy to use with high FPS games

### ISSUE THREAD

**Issue by qua-iy** [aws/aws-sdk-net#711]
I profiled my game performance on iOS and I found that UnityMainThreadDispatcher is consuming like 0.7 ms every 0.1 second. This behavior have a big impact to my game running at 60 fps, leading to drop a frame.

![ios_profiling](https://user-images.githubusercontent.com/24807859/28854348-aa912a04-7771-11e7-867a-1ac77045cb25.png)

## Expected Behavior
Please don't use much of a time of very limited time.

## Current Behavior
UnityMainThreadDispatcher is using 0.7 ms every 0.1 second after initialization.

## Possible Solution
I didn't investigate internal of SDK, but I think getting status of network reachability is not a light operation.
https://github.com/aws/aws-sdk-net/blob/caee9aafe81c1007c15dd9cb591e1e812d52b115/sdk/src/Core/Amazon.Runtime/Pipeline/_unity/UnityMainThreadDispatcher.cs#L113

## Your Environment
* AWSSDK.Core version used: 3.3.82.1
* Service assembly and version used: Firehose
* Operating System and version: iOS 10.3.0
* Visual Studio version: ---
* Targeted .NET platform: Unity

**Comment by oddgames-david** [comment]
I'm only using Kinesis and experiencing 1.8ms per frame being used by this method.

Definitely needs looking at as it's a show stopper for inexperienced game devs that wont be able to modify and compile the sdk on their own.

**Comment by oddgames-david** [comment]
It's still an issue, you need to remove the ServiceFactory.Instance.GetService<INetworkReachability>() running every frame. I've solved it by editing the .dll every time you release.

**Comment by ashishdhingra** [comment]
Hi @qua-iy / @oddgames-david,

Starting with version 3.5 of the AWS SDK for .NET, projects using Unity 2018.1 or later should target the .NET Standard 2.0 release of the SDK. You can find additional information in the developer guide: [Unity support](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/unity-special.html) and [Migrating your Unity application](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/net-dg-v35.html#net-dg-v35-changes-unity).

Please try using the .NET Standard 2.0 version of the AWS SDK for .NET (version 3.5). 

Thanks,
Ashish
