### ISSUE TITLE
AWSPowerShell: "Get" Cmdlets with Singular Nouns Should Get All Resources When No ID Specified

### ISSUE THREAD

**Issue by bgshacklett** [aws/aws-sdk-net#714]
## Expected Behavior
Cmdlets beginning with the `Get` verb and ending with a singular noun (e.g.: CfnStackResource) should retrieve all of the related resources when no identifier is specified via Parameter; there should be no need for a Cmdlet with a plural noun.

## Current Behavior
The `Get-CfnStackResource` Cmdlet throws an error stating that the logicalResourceId parameter is required:
```
> get-cfnstackresource -Region us-east-1 -StackName MyStack
get-cfnstackresource : 1 validation error detected: Value null at
'logicalResourceId' failed to satisfy constraint: Member must not be null
At line:1 char:1
+ get-cfnstackresource -Region us-east-1 -StackName MyStack
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Amazon.PowerShe...kResource
   Cmdlet:GetCFNStackResourceCmdlet) [Get-CFNStackResource], InvalidOperati
  onException
    + FullyQualifiedErrorId : Amazon.CloudFormation.AmazonCloudFormationExce
   ption,Amazon.PowerShell.Cmdlets.CFN.GetCFNStackResourceCmdlet
```

## Possible Solution
Given the current example of the `Get-CfnStackResource` Cmdlet:
* The `Get-CfnStackResource` Cmdlet could call the `Get-CfnStackResources` Cmdlet, passing the StackName parameter through, if no LogicalResourceId is specified.
* Eventually, the `Get-CfnStackResources` Cmdlet should be deprecated and refactored as a private method. This would reduce the complexity of the Cmdlet Set (no more guessing whether a Cmdlet should use a plural noun) and bring the module in line with SD01 in the Strongly Encouraged Development Guidelines document: https://msdn.microsoft.com/en-us/library/dd878270(v=vs.85).aspx#SD01. 

## Steps to Reproduce (for bugs)
1. Ensure that no region is configured via persisted or shell default mechanisms
1. Initialize the authentication variables
    * `AWS_SESSION_TOKEN`  
    * `AWS_ACCESS_KEY_ID`
    * `AWS_SECRET_ACCESS_KEY`
1. Run `Get-CfnStackResource -StackName <StackName>` where <StackName> is the name of an existing stack.

## Context
I run into errors from time to time, as it can be difficult to remember which Cmdlets require a plural noun when I wish to retrieve all resources. This often occurs when I'm attempting to do large queries against an account to see how resources relate to one another.

## Your Environment
Platform      : Win32NT
ServicePack   : 
Version       : 10.0.14393.0
VersionString : Microsoft Windows NT 10.0.14393.0
                                   
PSVersion                      5.1.14393.1480                                
PSEdition                      Desktop                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.14393.1480}     
BuildVersion                   10.0.14393.1480                               
CLRVersion                     4.0.30319.42000                               
WSManStackVersion              3.0                                           
PSRemotingProtocolVersion      2.3                                           
SerializationVersion           1.1.0.1

**Comment by PavelSafronov** [comment]
The more recent versions of the PowerShell tools have `Get-CFNStackResourceList`, which is consistent with the guidelines you mentioned, but we cannot remove `Get-CfnStackResources` because that would be a breaking change.

Changing the behavior of `Get-CfnStackResource` as you described is a bit problematic: 
`Get-CFNStackResource` calls [`DescribeStackResource`](http://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_DescribeStackResource.html), while `Get-CFNStackResources` calls  [`DescribeStackResources`](http://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_DescribeStackResources.html). `DescribeStackResources` has more parameters (`PhysicalResourceId` right now, but this can of course change in the future), so changing `Get-CfnStackResource` to pass-through to a different cmdlet would either be an incomplete solution (some calls can be passed through) or would entail hoisting parameters from one cmdlet to another (which wouldn't be applicable at all times).

**Comment by steveataws** [comment]
All plural named cmdlets have in fact now been removed (with aliases available to prevent breaking changes, as Pavel notes). An additional difficulty here (from an end user perspective) is mapping the cmdlet name to the underlying service API name, to try and help comprehend what the command does. We try to hint at this in the cmdlet help by directly noting the API that will be called.

What also doesn't help is that we don't mark parameters yet as mandatory. We have this as a backlog feature to implement, once we are sure we have a safety net customers can use to bypass the mandatory checks in the (hopefully rare to never) case that we ship a module version that incorrectly marks a parameter, or some combination of parameters, as required when in fact supplying them as demanded would cause an error. As the module is pre-installed on EC2 Windows images, you can imagine the blast radius of such an error and PowerShell itself has no built-in means to allow users to disregard the parameter attribution to work around such an error. In this particular case, marking the id parameter as required, and taking a single value, would go a long way toward indicating this is not a cmdlet that returns a collection of items (the old plural name aside).

The naming convention we try to adhere to is to suffix 'List' to the noun when the cmdlet can return multiple elements. This is a standard we have come to adopt over time and we're admittedly not always successful in this as services can implement APIs (not always at the same time!) with names such as 'DescribeXYZ' and 'ListXYZ', both of which return multiple elements.

**Comment by bgshacklett** [comment]
Thank you for taking the time to read my feedback. I'm happy to hear that you're striving for consistency in naming. While it doesn't exactly match the behavior that I would expect from a PowerShell module, I understand that there are implementation details which carry significant complexity, and it sounds like the work you're doing to standardize will be make a significant positive impact in making the behavior intuitive.

**Comment by steveataws** [comment]
Re-reading this issue, I don't think there is much else we can do besides continuing to drive name consistency (which we've done), so resolving the issue. Feel free to reopen if there is more conversation to be had.
