### ISSUE TITLE
using AWSEndpointDefinition with .net core

### ISSUE THREAD

**Issue by arishlabroo** [aws/aws-sdk-net#719]
previously, to change "hostname:port" for services like SQS i used to add a custom `endpoints.json` file in `AWSEndpointDefinition` app config setting. 

This setting is not available in core AwsOptions settings. 

How can we use custom `endpoint-url` with dotnet core sdk?
 
For e.g. 
`aws --endpoint-url=http://myurl.com sqs list-queues`
works from the command line, but I cannot replay this behavior using the SDK.

http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html#config-setting-awsendpointdefinition

**Comment by sstevenkang** [comment]
There isn't a way to provide a custom endpoints.json file in .net core sdk.  We'll add this work to our backlog.

**Comment by arishlabroo** [comment]
Thankyou @sstevenkang . 
In the meantime can you suggest a workaround? I am trying to do local testing using `localstack` and providing a ServiceUrl in the config does not work.

**Comment by sstevenkang** [comment]
When creating a service client, you should able to override the endpoint the client is hitting by passing in a derivative of ClientConfig object: https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/ClientConfig.cs#L140.  Would this help at all?

**Comment by cultavix** [comment]
👍  Would be awesome if we could override the AWS endpoint. Exactly as @arishlabroo says, for `localstack`

**Comment by pingvinen** [comment]
You can use LocalStack by setting the `ServiceUrl` (as suggested by @sstevenkang) using something like the following.

```csharp
var config = new AmazonSimpleNotificationServiceConfig();
config.ServiceUrl = "http://localhost:4575";

new AmazonSimpleNotificationServiceClient(config);
```
