### ISSUE TITLE
AWS Serverless Application deployment is crashing VS2017

### ISSUE THREAD

**Issue by 13neno** [aws/aws-sdk-net#725]
I am trying to publish an out of the box AWS Serverless Application project, choosing the ASP.NET Core Web API Blueprint. 

## Expected Behavior
I expect the Serverless Application to be uploaded successfully - the Lambda Function and API Gateway to be created and visible in the console as well as being able to complete a simple test hitting the Values API (ValuesController).

## Current Behavior
1. Right click the project
2. Click Publish to AWS Lambda...
3. Chose my account profile to use => region: (Asia Pacific (Sydney))
4. Configuration: Release => Framework: netcoreapp1.0
5. Stack Name: "RandomName" => S3 Bucket - "MyS3BucketWhichIveCreated" => Click Next 
6. BucketName: left it as empty
7. ShouldCreateBucket: false => Click Publish
8. Publishing screen goes right through until the end and then closes the Wizard window (no errors are printed)
9. The Stack window appears for a second (all fields are empty) then VS freezes with a dialog saying "Microsoft Visual Studio 2017 has stopped working - Windows can try to restart the program."
10. Restarting or closing - I can see the Lambda Function is not created in the console

## Context
I am just trying to test this relatively new technology to see if it is a viable option for our organization.

## Your Environment

* Installed AWS Toolkit for Visual Studio 2017 via Visual Studio's Extensions and Updates window (VSIX)
* Windows 7 (virtual machine)
* Visual Studio 2017 v15.2
* .NetCoreApp 1.0
* .Net Core SDK 1.0.4 (x64)

Everything is from the template and I have not touched a thing in the solution. I have tried the same process a few times. I have also tried uninstalling and reinstalling the AWS Toolkit for Visual Studio 2017. Any help is much appreciated!

**Comment by danielalvescorrea** [comment]
Having a very similar problem. I can publish the out of the box app. Then I've developed a very simple application that performs a select on a MySql DB, and this app crashes VS also right after the wizard window closes. Still haven't found the problem.

**Comment by normj** [comment]
I'm not able to reproduce this problem. Have you tried the .NET Core 2.0 support? If the problem is still happening open an issue on the [aws-lambda-dotnet](https://github.com/aws/aws-lambda-dotnet) repository.
