### ISSUE TITLE
Cannot use AWS_PROFILE to change the profile used

### ISSUE THREAD

**Issue by dpurrington** [aws/aws-sdk-net#727]
## Expected Behavior
Credential resolution should have [the same features as the CLI](
http://docs.aws.amazon.com/cli/latest/topic/config-vars.html#general-options). I discovered that the AWS_PROFILE environment variable is not used by this SDK.

It should work according to the same approach used by other AWS SDK implementations (including the nodejs SDK).

## Current Behavior
Currently, it is hard coded to use the "default" profile, regardless of whether or not the AWS_PROFILE value is set to something else.

## Possible Solution
In the [FallbackCredentialsFactory](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Credentials/FallbackCredentialsFactory.cs#L52), if AWS_PROFILE is defined, use that value for the DefaultProfileName. Otherwise, use "default".

## Steps to Reproduce (for bugs)
Setup is more about the credentials configuration than the test code. 
* The test code can be to use any AWS resource. 
*The credentials config should be to put credentials into a non-default profile and remove the default profile. 
*Set the AWS_PROFILE environment to the name of the profile you used
*Run some code to access an AWS resource (e.g., S3.ListBuckets)

## Context
I'm using the [AWS Secure Token Service](http://docs.aws.amazon.com/STS/latest/APIReference/Welcome.html) and putting the credentials into the credentials file. They expire frequently. Everytime that happens, I need to either copy/paste the values into the default profile, or export them to environment variables.

## Your Environment

* AWSSDK.Core version used: 1.0.4
* Service assembly and version used: AWSSDK.DynamoDBv2" Version="3.3.4.17
* Operating System and version: Ubuntu
* Visual Studio version: n/a
* Targeted .NET platform: dotnet core v1.1

**Comment by dpurrington** [comment]
I suggest categorizing this as a bug, since all other SDKs and the CLI use the same approach to credential resolution.

**Comment by vellozzi** [comment]
Good catch, thanks for the feedback.  We're actively working on this but I'm not able to provide an ETA.  I'll update this issue when we have it fixed.

**Comment by vellozzi** [comment]
Fix pushed in AWSSDK.Core 3.3.17.6.
