### ISSUE TITLE
How can I enable the logging in new versions of SDK for Xamarin ? #Xamarin

### ISSUE THREAD

**Issue by ilpoimigee** [aws/aws-sdk-net#729]
## Expected Behavior
In AWSSDK.MobileAnalytics (3.1.1.0) and AWSSDK.CognitoIdentity (3.1.0.1) i am able to get logging work as instructed on Xamarin Developer Guide http://docs.aws.amazon.com/mobile/sdkforxamarin/developerguide/setup.html#set-logging
But when updating or even creating completely new project with new versions of AWSSDKs I do not get any log output

## Possible Solution
I have noticed that Packages dependencies have changed from old to new version, not same packages installed due to dependencies.

## Steps to Reproduce (for bugs)
Install old versions of AWSSDK and instructions for logging -> logs work
Install latest versions and instructions -> Logs not visible

This seems to be reproducible on fresh installations of projects as well. 

## Context
In my project configuration AWSSDK.MobileAnalytics is not working at all. And I want to debug to see what is root cause. And without logs of latest versions I am not able to provide accurate information for AWS SDK team to reproduce error situation

## Your Environment
Xamarin for Mac (all latest updates)
Xamarin iOS Mobile App project
---
			// Enable logging of the AWS for DEBUG mode
			var loggingConfig = AWSConfigs.LoggingConfig;
			loggingConfig.LogMetrics = true;
			loggingConfig.LogResponses = ResponseLoggingOption.Always;
			loggingConfig.LogMetricsFormat = LogMetricsFormatOption.Standard;
			loggingConfig.LogTo = LoggingOptions.SystemDiagnostics;
---

**Comment by sunchunqiang** [comment]
@ilpoimigee   Sorry for the inconvenience caused. To investigate the issue, I need some information from you.

1. You cannot get any log or only some of the logs.
2. which version of SDK are you using? Current latest version of AWSSDK.Core is 3.3.28.1, are you using this one?
3. Do you test on a device or an emulator. 
4. Can you try current latest SDK to see if the issue can be reproduced?  I tried the latest sdk on an iOS emulator, I can get logs from AWSSDK.
