### ISSUE TITLE
IOptions<ClientConfig> should be resolved for configuration of AWS Services

### ISSUE THREAD

**Issue by ddrinka** [aws/aws-sdk-net#732]
The pattern for configuration in .Net Core is to resolve `IOptions<MyConfigurationClass>` through dependency injection.  aws-sdk should support this pattern, in addition to `AWSOptions`.

## Expected Behavior
```csharp
services.Configure<ClientConfig>(SomeConfiguration);    //I may resolve IOptions<ClientConfig> in other, more exotic ways than through an IConfiguration
services.AddAWSService<IAmazonS3>();    //I haven't provided AWSOptions, nor have I called AddDefaultAWSOptions to configure a default

...

class DoS3Things
{
  public DoS3Things(IAmazonS3 s3)
  {
    //S3 is configured based on IOptions<ClientConfig>
  }
}
```

## Current Behavior
```csharp
services.AddDefaultAWSOptions(Configuration.GetAWSOptions());  //This assumes many things about my configuration files and dependency injection requirements
services.AddAWSService<IAmazonS3>();

...

class DoS3Things
{
  public DoS3Things(IAmazonS3 s3)
  {
    //S3 is configured based on AWSOptions which loaded its configuration from IConfiguration
  }
}
```

## Context
Our projects resolve configuration both through the simple IConfiguration functionality, as well as more complex methods like searching IConfiguration for top-level elements that match the namespace and type of the requested IOptions.  To resolve configuration for AWS using our existing functionality, we'd like aws-sdk to conform to the .Net Core configuration pattern of resolving IOptions<MyConfigurationClass> through DI.  The current GetAWSOptions functionality supports many use cases, but also makes assumptions about how Configuration is arranged and implemented locally.

**Comment by kosmakoff** [comment]
I wonder why this is not a thing yet, after 2 and half years.

Today I stumbled upon the very same problem, when I was not able to register custom configuration for S3 Client which is registered via Dependency Injection.

Can I do the PR for this?

**Comment by ddrinka** [comment]
I feel this is still a valid feature request, unless the change has been implemented or the developers have responded with wont-fix.

**Comment by bwn-z** [comment]
3 years have passed but the problem is still actual

**Comment by ppittle** [comment]
The **AWSSDK.Extensions.NETCore.Setup** package does support building `AWSOptions` from Configuration and it has become signaficantly easier in [**3.7.2**](https://github.com/aws/aws-sdk-net/commit/fee04cc171445d276c37a97e7abed8eed81a9f85) with the [addition of this overload to `AddDefaultAWSOptions` for late binding](https://github.com/aws/aws-sdk-net/blob/master/extensions/src/AWSSDK.Extensions.NETCore.Setup/ServiceCollectionExtensions.cs#L57):

```csharp
public static IServiceCollection AddDefaultAWSOptions(
  this IServiceCollection collection, 
  Func<IServiceProvider, AWSOptions> implementationFactory, 
  ServiceLifetime lifetime = ServiceLifetime.Singleton)
```
---
To demonstrate this, I've created a lambda application using the _AWS Serverless Application (.NET Core - C#)_ project template.

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>
    <!-- This property makes the build directory similar to a publish directory and helps the AWS .NET Lambda Mock Test Tool find project dependencies. -->
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer" Version="7.0.1" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.7.2" />
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer" Version="7.0.1" />   
    <PackageReference Include="AWSSDK.SimpleEmailV2" Version="3.7.1.55" />    
  </ItemGroup>
</Project>
```

I'll use a custom POCO config, which will serialize easier than `AWSOptions`:

```csharp
public class CustomConfiguration
{
  public string RegionEndpointName { get; set; }
}
```

I've setup Configuration in `LocalEntryPoint.CreateHostBuilder` including adding a value for `RegionEndpointName`:

```csharp
public class LocalEntryPoint
{
  public static IHostBuilder CreateHostBuilder(string[] args) =>
      Host.CreateDefaultBuilder(args)
	// Add Configuration so I can bind CustomConfiguration
          .ConfigureAppConfiguration(config =>
          {
              config.AddInMemoryCollection(new List<KeyValuePair<string, string>>
              {
                  new KeyValuePair<string, string>(
                      $"{nameof(CustomConfiguration.RegionEndpointName)}",
                      RegionEndpoint.CACentral1.SystemName) 
              });
          })
          .ConfigureWebHostDefaults(webBuilder =>
          {
              webBuilder.UseStartup<Startup>();
          });
}
```

Then in `Startup.ConfigureServices` I added the necessary bindings:

```csharp
public class Startup
{
	// This method gets called by the runtime. Use this method to add services to the container
	public void ConfigureServices(IServiceCollection services)
	{
		// Bind IOptions<CustomConfiguration>
		services.AddOptions<CustomConfiguration>().Configure(options => Configuration.Bind(options));
		
		// Use late binding for AWSOptions, it will request IOptions<CustomConfiguration>
		// and use that configuration object to construct a custom AWSOptions class
		services.AddDefaultAWSOptions(sp =>
		{
			var customConfig = sp.GetService<IOptions<CustomConfiguration>>();

			return new AWSOptions
			{
				Region = RegionEndpoint.GetBySystemName(customConfig.Value.RegionEndpointName)
			};
		});

		// Add bindings for AWS Services as normal.
		services.AddAWSService<IAmazonSimpleEmailServiceV2>();

		services.AddControllers();
	}
```

Finally, in my Controller, I can constructor inject a `IAmazonSimpleEmailServiceV2` that was built based off of the bound `CustomConfiguration` object:

```csharp
[Route("api/[controller]")]
public class ValuesController : ControllerBase
{
	private readonly IAmazonSimpleEmailServiceV2 _simpleEmailService;

	public ValuesController(IAmazonSimpleEmailServiceV2 simpleEmailService)
	{
		_simpleEmailService = simpleEmailService;
	}

	// GET api/values
	[HttpGet]
	public IEnumerable<string> Get()
	{
		return new string[] { _simpleEmailService.Config.RegionEndpoint.DisplayName };
	}
}
```

Upon invoking _/api/Values_, I'd get a response of _"Canada (Central)"_, as that's the Display Name for the `RegionEndpoint.CACentral1` that I specified in `LocalEntryPoint.CreateHostBuilder`.

**Comment by awesomeinsight** [comment]
> The **AWSSDK.Extensions.NETCore.Setup** package does support building `AWSOptions` from Configuration. It has become signaficantly easier in [**3.7.2**](https://github.com/aws/aws-sdk-net/commit/fee04cc171445d276c37a97e7abed8eed81a9f85) with the [addition of this overload to `AddDefaultAWSOptions` for late binding](https://github.com/aws/aws-sdk-net/blob/master/extensions/src/AWSSDK.Extensions.NETCore.Setup/ServiceCollectionExtensions.cs#L57):
> 
> ```cs
> public static IServiceCollection AddDefaultAWSOptions(
>   this IServiceCollection collection, 
>   Func<IServiceProvider, AWSOptions> implementationFactory, 
>   ServiceLifetime lifetime = ServiceLifetime.Singleton)
> ```
> 
> To demonstrate this, I've created a lambda application using the _AWS Serverless Application (.NET Core - C#)_ project template.
> 
> ```
> <Project Sdk="Microsoft.NET.Sdk.Web">
>   <PropertyGroup>
>     <TargetFramework>netcoreapp3.1</TargetFramework>
>     <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
>     <AWSProjectType>Lambda</AWSProjectType>
>     
>     <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
>   </PropertyGroup>
>   <ItemGroup>
>     <PackageReference Include="Amazon.Lambda.AspNetCoreServer" Version="7.0.1" />
>     <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.7.2" />
>     <PackageReference Include="Amazon.Lambda.AspNetCoreServer" Version="7.0.1" />   
>     <PackageReference Include="AWSSDK.SimpleEmailV2" Version="3.7.1.55" />    
>   </ItemGroup>
> </Project>
> ```
> 
> I'll use a custom POCO config, which will serialize easier than `AWSOptions`:
> 
> ```cs
> public class CustomConfiguration
> {
>   public string RegionEndpointName { get; set; }
> }
> ```
> 
> I've setup Configuration in `LocalEntryPoint.CreateHostBuilder` including adding a value for `RegionEndpointName`:
> 
> ```cs
> public class LocalEntryPoint
> {
>   public static IHostBuilder CreateHostBuilder(string[] args) =>
>       Host.CreateDefaultBuilder(args)
> 	// Add Configuration so I can bind CustomConfiguration
>           .ConfigureAppConfiguration(config =>
>           {
>               config.AddInMemoryCollection(new List<KeyValuePair<string, string>>
>               {
>                   new KeyValuePair<string, string>(
>                       $"{nameof(CustomConfiguration.RegionEndpointName)}",
>                       RegionEndpoint.CACentral1.SystemName) 
>               });
>           })
>           .ConfigureWebHostDefaults(webBuilder =>
>           {
>               webBuilder.UseStartup<Startup>();
>           });
> }
> ```
> 
> Then in `Startup.ConfigureServices` I added the necessary bindings:
> 
> ```cs
> public class Startup
> {
> 	// This method gets called by the runtime. Use this method to add services to the container
> 	public void ConfigureServices(IServiceCollection services)
> 	{
> 		// Bind IOptions<CustomConfiguration>
> 		services.AddOptions<CustomConfiguration>().Configure(options => Configuration.Bind(options));
> 		
> 		// Use late binding for AWSOptions, it will request IOptions<CustomConfiguration>
> 		// and use that configuration object to construct a custom AWSOptions class
> 		services.AddDefaultAWSOptions(sp =>
> 		{
> 			var customConfig = sp.GetService<IOptions<CustomConfiguration>>();
> 
> 			return new AWSOptions
> 			{
> 				Region = RegionEndpoint.GetBySystemName(customConfig.Value.RegionEndpointName)
> 			};
> 		});
> 
> 		// Add bindings for AWS Services as normal.
> 		services.AddAWSService<IAmazonSimpleEmailServiceV2>();
> 
> 		services.AddControllers();
> 	}
> ```
> 
> Finally, in my Controller, I can constructor inject a `IAmazonSimpleEmailServiceV2` that was built based off of the bound `CustomConfiguration` object:
> 
> ```cs
> [Route("api/[controller]")]
> public class ValuesController : ControllerBase
> {
> 	private readonly IAmazonSimpleEmailServiceV2 _simpleEmailService;
> 
> 	public ValuesController(IAmazonSimpleEmailServiceV2 simpleEmailService)
> 	{
> 		_simpleEmailService = simpleEmailService;
> 	}
> 
> 	// GET api/values
> 	[HttpGet]
> 	public IEnumerable<string> Get()
> 	{
> 		return new string[] { _simpleEmailService.Config.RegionEndpoint.DisplayName };
> 	}
> }
> ```
> 
> Upon invoking _/api/Values_, I'd get a response of _"Canada (Central)"_, as that's the Display Name for the `RegionEndpoint.CACentral1` that I specified in `LocalEntryPoint.CreateHostBuilder`.

I'm trying to set `ForcePathStyle` Property like that but the value `true` is never set.
Using the AddDefaultAWSOptions I cannot specifiy such a property. What is the best approach to set this when using dependency injection?

```csharp
builder.Services
        .AddSingleton<IAmazonS3>(p => {
            var config = new AmazonS3Config
            {
                RegionEndpoint = RegionEndpoint.EUCentral1,
                Profile = new Profile("FooBar1234"),
                ForcePathStyle = true,
                ServiceURL = "http://foo-bar:9000"
            };
            return new AmazonS3Client(config);
        });
```
