### ISSUE TITLE
AmazonS3Util.PostUpload does not dispose WebResponse

### ISSUE THREAD

**Issue by cookav** [aws/aws-sdk-net#733]
## Expected Behavior
`WebResponse` inside `AmazonS3Util.PostUpload` should be disposed.

## Current Behavior
`WebResponse` is not disposed and keeps connection open which prevents subsequent requests from succeeding. See: https://github.com/aws/aws-sdk-net/blob/ba7f040dd074d10fd19ca1728f71919b20726c1f/sdk/src/Services/S3/Custom/Util/_bcl/AmazonS3Util.Operations.cs#L373-L383

**Comment by normj** [comment]
Yeap we should be disposing that. I'll get that fixed up.

**Comment by normj** [comment]
Version 3.3.10.4 of AWSSDK.S3 was pushed with this fix.
