### ISSUE TITLE
TagQuery.cs can't find how to use it

### ISSUE THREAD

**Issue by avtor13** [aws/aws-sdk-net#734]
in AWSSDK.S3.dll we can see class TagQuery, but i can't find where should i pass that instance to. And i didn't found any example... 

Your tech support offered to ask here too.
AWSSDK.S3 version 3.3.0.0

**Comment by sstevenkang** [comment]
Hi, this file was erroneously added to the repo.  It's not being used anywhere. We'll remove this in the future release.

**Comment by avtor13** [comment]
Hi, Steven. What should i to do you don't remove it but implemented? ))
