### ISSUE TITLE
Consider support for low trust environments

### ISSUE THREAD

**Issue by DanielChilcott** [aws/aws-sdk-net#737]
We run an app integration platform so our connectors/adapters need to be able to run in de-privileged AppDomains.

I've identified at least three classes of issues that prevent this SDK from being used in de-priv'd AppDomains namely:

* Calls to System.Environment.GetEnvironmentVariable
* Attempts to access Filesystem - specifically to query endpoints.json (in my opinion, FS reads should be put in try catch blocks so code can fall through to obtaining endpoints.json from embedded resource)
* Custom implementations of GetObjectData in Exception objects (can't be done because GetObjectData is decorated with SecurityCritical

There are a number of StackOverflow users who have posted questions around how to get the SDK to work in low trust. Almost all appear to be running the SDK under IIS and they end up using a higher priv account to resolve which is a security concern.

To resolve these issues for our own purposes, I added a compile symbol SANDBOX and made changes to the above areas. AFAIK, only the Core project requires these changes.

You can see these at https://github.com/Flowgear/aws-sdk-net/commit/2e601c7c38e04903aac15c933e297cfe692d0e5b - this is not ready for PR but I would like to hear whether you would consider a PR and whether the approach of SANDBOX symbol is appropriate.

**Comment by normj** [comment]
We are open to a PR to support low trust environments but I don't want to have to produce yet another assembly which it seems like using the symbol approach would be. The difficult issue will be the GetObjectData problem.
