### ISSUE TITLE
Roslyn folder removed when publishing using AWS Toolkit or the upload and deploy button on beanstalk

### ISSUE THREAD

**Issue by ZeroMSN** [aws/aws-sdk-net#739]
## Expected Behaviour
The Roslyn folder should not be removed otherwise the website will not work. If I RDP into the environment and manually copy the Roslyn folder through the mapped remote drives then the web site works.

## Current Behaviour
When publishing my .NET Framework 4.7 web site using C# via the Toolkit on VS2017, the published folder when uploaded excludes the Roslyn folder which contains the Roslyn compiler and its resources. Manually publishing it to a folder locally as 'release' includes the folder which I then zip up and try to upload through the AWS beanstalk console using the 'upload and deploy' button on my beanstalk environment which also seems to remove the Roslyn folder after having deployed. When I open the zip file, the Roslyn folder is there.

Obtained the following from the beanstalk logs
    Exception type: HttpException

    Exception message: Could not find a part of the path 'C:\inetpub\wwwroot\bin\roslyn\csc.exe'.
   at System.Web.Compilation.BuildManager.ReportTopLevelCompilationException()
   at System.Web.Compilation.BuildManager.EnsureTopLevelFilesCompiled()
   at System.Web.Compilation.BuildManager.CallAppInitializeMethod()
   at System.Web.Hosting.HostingEnvironment.Initialize(ApplicationManager appManager, IApplicationHost appHost, IConfigMapPathFactory configMapPathFactory, HostingEnvironmentParameters hostingParameters, PolicyLevel policyLevel, Exception appDomainCreationException)

## Possible Solution
Include the Roslyn folder when publishing the website using the toolkit on VS2017 or through the upload and deploy button when uploading zip file which clearly has the folder when previewing it.

## Steps to Reproduce (for bugs)
Create a .NET 4.7 web project on VS2017 and try to upload it using the toolkit or through the upload and deploy button within the beanstalk console on AWS site.

## Context
Can't publish the site and it means I have to have a decent connection to the internet as it prevents me from mobile working. It's not as easy as it used to be where I could just publish and see it work. Should be the same as Azure where you click and it publishes. Azure just works but AWS seems to be a bit broken at the moment.

## Your Environment
* Operating System and version: Windows Server 2016 / IIS10
* Visual Studio version: 2017
* Targeted .NET platform: .NET Framework 4.7

## .NET Core Info
Not using .NET Core.

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by ghost1face** [comment]
I've run into the same issue last week, the problem for me seems to be with [roslyn v.1.0.6 and v1.0.7](https://www.nuget.org/packages/Microsoft.CodeDom.Providers.DotNetCompilerPlatform).   

At first I reported the issue to the roslyn team, but on further investigation it looks like the microsoft deploy includes the missing folder.

## Your Environment
* Operating system and version: Windows 10
* Visual Studio version: 2017
* Targeted .NET platform: .NET 4.6

**Comment by normj** [comment]
I have produced the error as well with version 1.0.7 and like @ghost1face found it does work correctly with version 1.0.5. I'll keep investigating but for now the work around is to use version 1.0.5.

**Comment by adamjzeffer** [comment]
downgrading to version 1.0.5 worked for me as well. I did run into an issue after downgrading where the bin folder was locked as read-only .

Similar to what was reported here https://developercommunity.visualstudio.com/content/problem/71302/binroslyn-files-locked-during-build.html

Removing the read-only lock through the properties window on the bin folder resolved this , and I was able to get my app successfully published to the aws eb env.

**Comment by MattDillard** [comment]
I encountered this problem with v1.0.7 as well. I upgraded to the newer 1.0.8 release, and it appears to have been addressed.
