### ISSUE TITLE
Error in Visual Studio when importing credentials from CSV file

### ISSUE THREAD

**Issue by BenWal** [aws/aws-sdk-net#741]
I just set up a new IAM user and I'm trying to use Visual Studio to create a profile on my client. When I import the CSV file, I get an error stating:

Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

## Expected Behavior
Credentials should be imported.

## Current Behavior
Profile creation dialog disappears and I'm sent back to the profile selection dialog

## Your Environment

* Toolkit version used: 1.12.1.6
* Operating System and version: Windows 10 Pro Version 10.0.14393 Build 14393
* Visual Studio version: Visual Studio Community Edition 2017 v 15.3.3
* Targeted .NET platform: None, yet

**Comment by mikebuckley5** [comment]
I'm having the same issue too. Same Enviroment as @BenWal.

**Comment by vib-hu** [comment]
I have also faced the same problem and credentials copy pasting is also not allowed.
Toolkit version used: 1.12.2.1
Operating System: Windows 7 Ultimate 64 bit OS
Visual Studio version: Visual Studio Enterprise Edition 2017 v 15.2

![capture](https://user-images.githubusercontent.com/10459403/32186821-2f6195f0-bdc9-11e7-8580-4ba2dde33494.PNG)

**Comment by turjachaudhuri** [comment]
Any update on this issue? Just observed the same issue now .

**Comment by steveataws** [comment]
Apologies for the delay, this got overlooked. We did fix an issue with importing csv files to the toolkit late last year, but if you've just experienced the same issue then it suggests there is another edge case in the csv file layout that we missed. 

Would you mind confirming the version of Visual Studio, and AWS toolkit, you are using and also posting the headers and some **sample** data from your csv file that I can attempt to repro with? **Please be sure to not post any real keys** :-)

**Comment by vib-hu** [comment]
Hi Steve,

These are the details.
Toolkit version used: 1.12.2.1
Operating System: Windows 7 Ultimate 64 bit OS
Visual Studio version: Visual Studio Enterprise Edition 2017 v 15.2

But i have faced this issue 3 months back, didn't try again recently.

**Comment by steveataws** [comment]
vib-hu@,

Do you happen to recall where in the AWS Console you exported the csv file from? Was it for an IAM user or root credentials or somewhere else?

**Comment by vib-hu** [comment]
@steveataws 

To be honest i didn't remember that. @turjachaudhuri recently faced this issue i think he can provide that info.

**Comment by steveataws** [comment]
Resolving issue as I've not been able to repro with csv files I've created recently. Feel free to reopen if anyone gets a csv file that we fail to import (and if this happens, please add the columns headers -- **NOT** the credential data -- to the issue).
