### ISSUE TITLE
User profiles created in Visual Studio are not available in the AWS CLI

### ISSUE THREAD

**Issue by BenWal** [aws/aws-sdk-net#742]
I created a user profile in Visual Studio. I installed the Windows bash subsystem, and used pip to install the AWS CLI. Invoking "aws configure list" afterwards showed no existing profiles on the machine.

## Expected Behavior
I expected to see my profile available in all AWS tools.

**Comment by vellozzi** [comment]
There are two locations for credential profiles.  One specific to Visual Studio and one shared by Visual Studio and the CLI.  In Visual Studio they're labeled ".NET Credentials" and "Shared Credentials", respectively.

.NET credentials are encrypted and stored within the user's AppData folder.  Shared credentials are stored at $HOME/.aws/credentials.  The shared profiles are the only ones that are seen by both the AWS CLI and the Visual Studio Toolkit.

Both types can be edited in Visual Studio but there's currently no way to create new shared credential profiles in Visual Studio.

This needs to be added.  In the meantime, if you create a new shared profile using [aws configure](http://docs.aws.amazon.com/cli/latest/reference/configure/) it will show up in the Visual Studio Toolkit.

**Comment by normj** [comment]
It is now possible to save credentials in the $HOME/.aws/credentials file which will be accessible to the AWS CLI
