### ISSUE TITLE
default "Timeout" of AmazonS3Config on CORECLR is not set.

### ISSUE THREAD

**Issue by dirty49374** [aws/aws-sdk-net#747]
default "Timeout" of AmazonS3Config on CORECLR is not set.

## Expected Behavior
uploading amazon s3 should not be canceled by timeout.

## Current Behavior
no CORECLR setting in AmazonS3Config.Initialize()

```
    public partial class AmazonS3Config : ClientConfig
    {
        ...
        protected override void Initialize()
        {           
            this.AllowAutoRedirect = false;
#if BCL45
            // Set Timeout and ReadWriteTimeout for S3 to max timeout as per-request
            // timeouts are not supported.
            this.Timeout = ClientConfig.MaxTimeout;
            this.ReadWriteTimeout = ClientConfig.MaxTimeout;
#elif PCL
            // Only Timeout property is supported for WinRT and Windows Phone.
            // Set Timeout for S3 to max timeout as per-request
            // timeouts are not supported.
            this.Timeout = ClientConfig.MaxTimeout;
#endif
        }
}
```

## Your Environment

* AWSSDK.Core version used: master
* Service assembly and version used: master 
* Operating System and version: windows .NET CORE
* Visual Studio version: visual studio 2017
* Targeted .NET platform: 

## .NET Core Info

* .NET Core version used for development: 1.1.0
* .NET Core version installed in the environment where application runs: 1.1.0
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by spati2** [comment]
As a work around you can add code to set the timeout on AmazonS3Config yourself. The SDK will correct this bug.

**Comment by klaytaybai** [comment]
This has been fixed in https://github.com/aws/aws-sdk-net/commit/c24dfcd94c1cd1a3b06b139f86d4f194faf1930d.
