### ISSUE TITLE
Async calls failing on OSX

### ISSUE THREAD

**Issue by pfeurean** [aws/aws-sdk-net#759]
Attached please find a simple console program.  It needs a bucket name and credentials.  When running on OSX it crashes the framework.  When debugging with VS4MAC, a crash log is generated. I've included it in the project.  When just running the console app, it simply ends execution.

When I run the same project on windows OR linux via docker, everything works as expected. Any help would be great.  I'll post this in the github project as well.

[WTFAWSCON.zip](https://github.com/aws/aws-sdk-net/files/1328218/WTFAWSCON.zip)

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 

.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d

* Contents of project.json/project.csproj: 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by sstevenkang** [comment]
I think you may want to post this on https://github.com/dotnet/coreclr repo instead.  Looking at the source of the crash:
```
Termination Signal:    Segmentation fault: 11
...
Thread 12 Crashed:
0   libcrypto.35.dylib              0x00007fff68162a64 ASN1_STRING_cmp + 20
```
Either the libcrypto library on your machine has a bug or lobcoreclr is calling the library with incorrect parameters triggering segfault.  Have you tried setting a breakpoint at `ASN1_STRING_cmp` in lldb and see what parameters were passed in? 

Either way, I don't think this is an issue with the SDK.  As you mentioned, your project builds and runs fine on windows and linux which seem to indicate that this is a runtime problem.  I would like to close this issue unless you have some more data points that indicate that there is a bug in the SDK.
