### ISSUE TITLE
 Fn::GetAtt on an AWS::S3::Bucket returns incomplete attributes 

### ISSUE THREAD

**Issue by r2690698** [aws/aws-sdk-net#760]
When building a CFN template the following using Fn::GetAtt on an AWS::S3::Bucket resource a full list of valid attributes are not listed for that resource type. 

for example
`    "LogBucketArn": 
    {
      "Value": {"Fn::GetAtt" : [ "S3BucketLogging", "Arn"]},
      "Description": "S3BucketLogging DomainName",
      "Export" : {"Name" : {"Fn::Sub": "${AWS::StackName}-S3BucketLoggingArn" }}
    },` 

Arn is not considered valid. this is not correct. 

## Your Environment
AWS Toolkit for VS 2017 
v1.12.1.6
Windows 10

**Comment by normj** [comment]
Arn has been added to the schema
