### ISSUE TITLE
ListHostedZones not found in .Net Core

### ISSUE THREAD

**Issue by evolcode** [aws/aws-sdk-net#762]
The latest version of AmazonRoute53Client(); is different when comparing the .Net Standard to .Net Core. 
For example:
`        public ListHostedZonesResponse ListHostedZones(ListHostedZonesRequest request);`

Is not available in .Net Core.

**Comment by sstevenkang** [comment]
Are you looking for `ListHostedZonesAsync()`?  Also, the binaries always targeted netstandard1.3.  Did you mean to say .net45 vs .net core?

**Comment by sstevenkang** [comment]
I am closing this.  Feel free to comment on this issue if you have unresolved problems.
