### ISSUE TITLE
AsyncRunner.CS performance bug affecting DynamoDB calls and client system as a whole

### ISSUE THREAD

**Issue by anmarht** [aws/aws-sdk-net#766]
DynamoDB calls end up being executed in https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Internal/_async/AsyncRunner.cs. Code currently creates a Thread, eventhough it is reserving a thread on the Threadpool, then Joining both threads. This results in a high CPU load affecting the whole system, plus can't achieve highest performance possible.

## Expected Behavior
- CPU usage to align with performance
- High performance

## Current Behavior
Unneeded threads created. CPU goes high. Low performance.

## Possible Solution
I've created the fix on my forked repo:

https://github.com/anmarht/aws-sdk-net/commit/61d002a1c36f7dfedbb6b26af54e10626f7a3d1c

### Some test results:

Below are test results of using UpdateItemAsync to update 10000 items.

|                      | Original AWS SDK    | After applying my fix |
|----------------------|---------------------|-----------------------|
| Updating 10000 items | 48,254 milliseconds | 9,830 milliseconds    |

## Steps to Reproduce (for bugs)

Here are 2 test applications, to show performance with the original code, and after fixing it as well:

https://github.com/anmarht/aws-sdk-bug

## Context
Making a lot of DynamoDB Updates in a heavily multi-threaded application would slow the system and not achieve adequate performance. I've noticed this because when dealing with other services performance was very good (like S3 or SQS), except DynamoDB so i've done my research to find if there's any possible bug. 

## Your Environment
- Used the SDK code directly at https://github.com/aws/aws-sdk-net
- Also used Nugets AWSSDK.DynamoDBv2 v3.3.4.17 and AWSSDK.Core v3.3.17.9
- OS: Windows 10 64bit Core i7 with an SSD
- Microsoft Visual Studio Enterprise 2017 V15.3.3
- .NET: .NET 4.6.2 (or SDK solution AWSSDK.Net45.sln)

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by alfattal** [comment]
Congrats on this achievement!

**Comment by normj** [comment]
This was fixed with PR https://github.com/aws/aws-sdk-net/pull/896
