### ISSUE TITLE
S3 Key with unicode sequence U+0065 U+0301 cannot be accessed

### ISSUE THREAD

**Issue by tparnell** [aws/aws-sdk-net#767]
## Expected Behavior

Keys with the following unicode should be accessible via calls to `GetObjectRequest` or `GetObjectMetadataRequest`: 
````
é  // U+0065 U+0301
````
Note that this is different from the normal way to express this character in unicode (U+00E9)

## Current Behavior

When we construct a `GetObjectRequest` or `GetObjectMetadataRequest` and make a get call, we get a 404:
````
Amazon.S3.AmazonS3Exception : The specified key does not exist.
  ----> Amazon.Runtime.Internal.HttpErrorResponseException : The remote server returned an error: (404) Not Found.
````

## Possible Solution

The SDK normally encodes unicode correctly.  It should handle this case gracefully.

## Steps to Reproduce (for bugs)

Create a S3 object with a key that contains the unicode sequence U+0065 U+0301.  Attempt to access it via the SDK.

## Your Environment

* AWSSDK.Core version used: 3.3.0.0
* Service assembly and version used: 
* Operating System and version: Windows 10 Pro, v 1703 
* Visual Studio version: 15.3.5
* Targeted .NET platform: v4.5

**Comment by sstevenkang** [comment]
I was able to create an S3 object with the keys: `\u0065\u0301` and `blep\u0065\u0301` and make GetObject and GetObjectMetadata requests.  Could you provide a sample code that repors the exception?

**Comment by tparnell** [comment]
Looks like this may have been an error in our code.  I see correct SDK behavior in simple tests.  Apologies for the noise.
