### ISSUE TITLE
aws-toolkit-for-visual-studio-2017 slow startup

### ISSUE THREAD

**Issue by LilMinmax** [aws/aws-sdk-net#768]
I am not sure where to report feedback for this product:

https://aws.amazon.com/blogs/developer/general-availability-of-the-aws-toolkit-for-visual-studio-2017/

There was an announcement here for the extension that says I can open a new issue here, so I'm doing that.

The issue is that VS2017 flags this extension as something that's adding 5 seconds on average to VS2017 startup time. See attached screenshot.

<img width="707" alt="aws_toolkit_5_sec" src="https://user-images.githubusercontent.com/923717/31555931-bfab5d88-aff7-11e7-8194-5d520909e954.png">

The expected behavior is: AWS Toolkit for Visual Studio 2017 would not go over whatever threshhold VS2017 is using to determine that an extension is problematic.

If there's a better place to report this, please let me know.

**Comment by paulogodinhoaq** [comment]
It does the same for ReSharper for me, I think you can ignore that.

**Comment by InsidiousForce** [comment]
I can ignore it sure, but if it's adding 5 seconds to VS startup time, then that can be improved. I think the Visual Studio team gets a lot of "Visual Studio takes a long time to start" complaints so they've started adding telemetry on things that are slow during startup, hence this message. Whatever it's doing during startup that's slow, it should be able to do faster or later. I have 26 extensions loading, what if they all took 5 seconds?

**Comment by normj** [comment]
Thanks for letting us know, we'll take a look to see what we can do to speed up the startup.

**Comment by InsidiousForce** [comment]
I'll say explicitly that I really like the toolkit, makes life super easy, hence the desire to see things like this improved. Thanks for all your engineering efforts

**Comment by normj** [comment]
@InsidiousForce Thanks for the positive feedback!

**Comment by comknight** [comment]
I am having a similar issue and get the following errors on startup.  It takes 14 seconds to load for me and AWS toolkit doesnt work, will not let me publish or use AWS tools.

119 |   | Begin package load [AWSToolkitPackage] | {12ED248B-6D4A-47EB-BE9E-8EABEA0FF119} |   | VisualStudio | 2017/10/26 03:51:40.257
-- | -- | -- | -- | -- | -- | --
120 | ERROR | LegacySitePackage failed for package [AWSToolkitPackage]Source: 'AWSToolkit.S3' Description: Method not found: 'System.Threading.Tasks.Task`1<System.Collections.Generic.IList`1<System.String>> Amazon.Runtime.SharedInterfaces.ICoreAmazonS3.GetAllObjectKeysAsync(System.String, System.String, System.Collections.Generic.IDictionary`2<System.String,System.Object>)'. System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<System.Collections.Generic.IList`1<System.String>> Amazon.Runtime.SharedInterfaces.ICoreAmazonS3.GetAllObjectKeysAsync(System.String, System.String, System.Collections.Generic.IDictionary`2<System.String,System.Object>)'.   at Amazon.AWSToolkit.S3.Nodes.S3RootViewModel.BuildClient(AWSCredentials awsCredentials)   at Amazon.AWSToolkit.Navigator.Node.ServiceRootViewModel..ctor(IMetaNode metaNode, IViewModel parent, String name)   at Amazon.AWSToolkit.S3.Nodes.S3RootViewModel..ctor(AccountViewModel accountViewModel)   at Amazon.AWSToolkit.S3.Nodes.S3RootViewMetaNode.CreateServiceRootModel(AccountViewModel account)   at Amazon.AWSToolkit.Account.AccountViewModel.CreateServiceChildren()   at Amazon.AWSToolkit.Navigator.NavigatorControl.updateActiveRegion()   at Amazon.AWSToolkit.Navigator.NavigatorControl.onRegionChanged(Object sender, SelectionChangedEventArgs e)   at System.Windows.Controls.SelectionChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)   at System.Windows.Controls.ComboBox.OnSelectionChanged(SelectionChangedEventArgs e)   at System.Windows.Controls.Primitives.Selector.InvokeSelectionChanged(List`1 unselectedInfos, List`1 selectedInfos)   at System.Windows.Controls.Primitives.Selector.SelectionChanger.End()   at System.Windows.Controls.Primitives.Selector.SelectionChanger.SelectJustThisItem(ItemInfo info, Boolean assumeInItemsCollection)   at System.Windows.Controls.Primitives.Selector.OnSelectedItemChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)   at Amazon.AWSToolkit.Navigator.NavigatorControl.setInitialRegionSelection()   at Amazon.AWSToolkit.Navigator.NavigatorControl._ctlAccounts_PropertyChanged(Object sender, PropertyChangedEventArgs e)   at Amazon.AWSToolkit.CommonUI.Components.RegisteredProfilesPicker._ctlCombo_SelectionChanged(Object sender, SelectionChangedEventArgs e)   at System.Windows.Controls.SelectionChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)   at System.Windows.Controls.ComboBox.OnSelectionChanged(SelectionChangedEventArgs e)   at System.Windows.Controls.Primitives.Selector.InvokeSelectionChanged(List`1 unselectedInfos, List`1 selectedInfos)   at System.Windows.Controls.Primitives.Selector.SelectionChanger.End()   at System.Windows.Controls.Primitives.Selector.SelectionChanger.SelectJustThisItem(ItemInfo info, Boolean assumeInItemsCollection)   at System.Windows.Controls.Primitives.Selector.OnSelectedItemChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)   at Amazon.AWSToolkit.CommonUI.Components.RegisteredProfilesPicker.set_SelectedAccount(AccountViewModel value)   at Amazon.AWSToolkit.Navigator.NavigatorControl.Initialize(AWSViewModel viewModel)   at Amazon.AWSToolkit.ToolkitFactory.InitializeToolkit(NavigatorControl navigator, IAWSToolkitShellProvider shellProvider, String additionalPluginPaths)   at Amazon.AWSToolkit.VisualStudio.AWSToolkitPackage.Initialize()   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp) | {12ED248B-6D4A-47EB-BE9E-8EABEA0FF119} | 80131513 | VisualStudio | 2017/10/26 03:51:41.288
121 | ERROR | SetSite failed for package [AWSToolkitPackage](null) | {12ED248B-6D4A-47EB-BE9E-8EABEA0FF119} | 80131513 | VisualStudio | 2017/10/26 03:51:41.304
122 | ERROR | End package load [AWSToolkitPackage] | {12ED248B-6D4A-47EB-BE9E-8EABEA0FF119} | 80131513 | VisualStudio | 2017/10/26 03:51:42.319

**Comment by normj** [comment]
In the latest version of the toolkit, 1.13.0.2 I reworked the startup code of the toolkit to do more of the initialization work in a background process. Although I have never seen startup as bad as 117 seconds, something very bad must have occurred for that to happen. Do you know if you had network connectivity when you had the bad timeout? I wonder if there is was a network call happening on the UI thread that is stuck until a timeout occurs.
