### ISSUE TITLE
Cannot mock DynamoDBv2 AsyncSearch for unit testing AWS calls

### ISSUE THREAD

**Issue by jazpearson** [aws/aws-sdk-net#772]
Would like to be able to properly unit test my code which uses the AWS SDK, and in particular the AsyncSearch class.

## Possible Solution
1. Create an interface for this class
2. Create an empty public constructor may also work

**Comment by mercury-jin-autodesk** [comment]
I have  the same issue with AsyncSearch.

**Comment by ColWhi** [comment]
Any update on this, causing us some pain

**Comment by assyadh** [comment]
Thanks @Supercheez, I'll have a look at the PR.

**Comment by arifemre61** [comment]
> at the PR.

Do you have chance to look at it ?

**Comment by 0leksii** [comment]
Hello,

Any update regarding this?

**Comment by j1mb0jay** [comment]
This would be very nice please

**Comment by leninator** [comment]
+ 1 vote for me. It's painful to test.

**Comment by Elchapanebro** [comment]
Frankly, The TDD approach of this lib is pretty shocking, why have you got interfaces that expose internally constructed objects such as `AsyncSearch<T>` and `Table` ? It makes for grim reading when trying to carry out the simplest of mocking in unit tests.

Just adding a public empty constructor would allow a safe non breaking fix for this - albeit not the best, but it should not have taken over a year to come to this conclusion.

**Comment by kwbauer** [comment]
When will we see movement on this issue. Not being able to write proper unit tests is very frustrating.

Just add the empty and public constructor so that we can mock the class.

**Comment by Elchapanebro** [comment]
> When will we see movement on this issue. Not being able to write proper unit tests is very frustrating.
> 
> Just add the empty and public constructor so that we can mock the class.

@kwbauer  - I ended up caving in and wrapping this code in a new class with what should be the appropriate interface in this library. - I means that my unit tests are testing the wrapper, and not the actual call within the AWSSDK which means I'm not 100% happy about it, but it will do. Code snippets below.

```c#
    internal interface IAsyncSearch<T>
    {
        bool IsDone { get; }

        Task<IReadOnlyList<T>> GetNextSetAsync(CancellationToken cancellationToken);

        Task<IReadOnlyList<T>> GetRemainingAsync(CancellationToken cancellationToken);
    }

    internal sealed class AsyncSearchWrapper<T> : IAsyncSearch<T>
    {
        private readonly AsyncSearch<T> asyncSearch;

        public AsyncSearchWrapper(AsyncSearch<T> asyncSearch)
        {
            this.asyncSearch = asyncSearch;
        }

        public bool IsDone => this.asyncSearch.IsDone;

        public async Task<IReadOnlyList<T>> GetNextSetAsync(CancellationToken cancellationToken)
        {
            return await this.asyncSearch.GetNextSetAsync(cancellationToken);
        }

        public async Task<IReadOnlyList<T>> GetRemainingAsync(CancellationToken cancellationToken)
        {
            return await this.asyncSearch.GetRemainingAsync(cancellationToken);
        }
    }

    internal sealed class GeminiDbContext : IGeminiDbContext
    {
        private readonly Lazy<IDynamoDBContext> context;

        public GeminiDbContext(IDynamoDBContext context)
        {
            this.context = context;
        }

        public IAsyncSearch<T> Query<T>(object hashKeyValue, DynamoDBOperationConfig operationConfig = null)
        {
            var search = this.context.Value.QueryAsync<T>(hashKeyValue, operationConfig);
            return new AsyncSearchWrapper<T>(search);
        }
    }
```

I also renamed the wrapper method to `Query` istead of `QueryAsync`, as its not actually an Async method.

Hope this helps.

**Comment by KeithGarry** [comment]
Just got burned by this.  +1 for some way to mock AsyncSearch.

**Comment by KeithGarry** [comment]
After following @Hardconkers code I have successfully managed to mock out the IAsyncSearch.  Here's an example:

```
var mockDynamoDbContext = new Mock<IMockableDynamoDbContext>();
var clientsRepo = new ClientsRepo(mockDynamoDbContext.Object, new RepoExceptionFactory());
var asyncSearchWrapper = new Mock<IAsyncSearch<Client>>();


var clientResult = new List<Client>() { new Client() };

asyncSearchWrapper.Setup(x => x.IsDone).Returns(true);
asyncSearchWrapper.Setup(x => x.GetRemainingAsync(new CancellationToken())).ReturnsAsync(() =>
{
    return new List<Client>() { new Client() };
});
asyncSearchWrapper.Setup(x => x.GetNextSetAsync(It.IsAny<CancellationToken>()))
    .ReturnsAsync(clientResult);


mockDynamoDbContext.Setup(x => x.FromQueryAsync<Client>(
        It.IsAny<QueryOperationConfig>(), null))
    .Returns(asyncSearchWrapper.Object);

var result = await clientsRepo.GetClientsByNameAsync("test");
```

**Comment by ahmed-malik-cko** [comment]
Hi Guys, 
Any chance this issue can move into the main library it's a bit frustrating not being able to write unit tests as part of the main library?

**Comment by nukec** [comment]
There is a PR here https://github.com/aws/aws-sdk-net/pull/1187 , but was never merged.

**Comment by bsolovij-ebsco** [comment]
Bump

**Comment by JuFrolov** [comment]
Bump

**Comment by kidchenko-tw** [comment]
Bump

**Comment by shortyh** [comment]
Bump

**Comment by brpyne** [comment]
Bump

**Comment by martinjansa** [comment]
Bump

**Comment by eric-davis** [comment]
BUMP!!!

**Comment by osherzhukovebsco** [comment]
Bump

**Comment by dj-mothman** [comment]
bump

**Comment by AdalbertKhoolsaat** [comment]
bump

**Comment by jakubbujak** [comment]
It is ridiculous not to do anything about it for 5 years (sic!) 😡 😡 😡

**Comment by jgv115** [comment]
bump

Just wondering if there has been any movement on this?

**Comment by normj** [comment]
I put out this PR to provide a way to mock AsyncSearch. It is not perfect given the constraints we have to avoid making breaking changes but I would appreciate some thoughts on the PR.

https://github.com/aws/aws-sdk-net/pull/2089

**Comment by jakubbujak** [comment]
If anyone wants workaround you can use approach propsed in this comment:

https://github.com/aws/aws-sdk-net/issues/772#issuecomment-578885398

Works fine 😃  But still it would be better to have that out of the box from library 👎

**Comment by normj** [comment]
@jakubbujak Are you saying that my [PR](https://github.com/aws/aws-sdk-net/pull/2089) that would go in the box would not suffice?

**Comment by jakubbujak** [comment]
I did not write anything like that, it may be, but I did not have time to review it :)

**Comment by normj** [comment]
Version 3.7.4.9 of the AWSSDK.DynamoDBv2 package was recently released with https://github.com/aws/aws-sdk-net/pull/2089 that adds the ability to subclass `AsyncSearch` for mocking purposes.

```
        public class MockAsyncSearch<T> : AsyncSearch<T>
        {
            public override Task<List<T>> GetNextSetAsync(CancellationToken cancellationToken = default(CancellationToken))
            {
                return Task.FromResult(new List<T>());
            }
        }

        [TestMethod]
        [TestCategory("DynamoDBv2")]
        public async Task TestMockingAsyncSeach()
        {
            var mockDBContext = new Mock<IDynamoDBContext>();
            mockDBContext
                .Setup(x => x.ScanAsync<DataItem>(
                   It.IsAny<IEnumerable<ScanCondition>>(),
                   It.IsAny<DynamoDBOperationConfig>()))
                .Returns(
                   new MockAsyncSearch<DataItem>() // Return mock version of AsyncSearch
                );

            var search = mockDBContext.Object.ScanAsync<DataItem>(new List<ScanCondition>());
            Assert.IsInstanceOfType(search, typeof(MockAsyncSearch<DataItem>));

            var items = await search.GetNextSetAsync();
            Assert.AreEqual(0, items.Count());
        }
```
