### ISSUE TITLE
[Argument cannot be null. Parameter name: baseStream] after opened for a hour

### ISSUE THREAD

**Issue by Thaina** [aws/aws-sdk-net#774]
I was using aws sdk in unity game and use both facebook and cognito developer identity token for credential to call lambda function

But when I used developer token and opened my app ,which ping lambda every 30 seconds, for approximately one hour. This error was popped up

I was suspect it would be a problem about token expired

## Expected Behavior
Should not have any error in this process

## Current Behavior
This cause an error that was caught in the system

## Steps to Reproduce (for bugs)
- Generate cognito developer identity token from server
- use that token as credential to LambdaClient in unity3D
- Use lambda client to invoke every 30 seconds continuously for a hour
- Catch the error

## Your Environment
Unity3D
AWSSDK.Lambda, Version=3.3.0.0
AWSSDK.CognitoIdentity, Version=3.3.0.0

**Comment by sstevenkang** [comment]
Could you share what exact APIs you used?  Also, what's the error that was returned by the service?  Please help us help you by providing more concrete detail such as sample code, exact error message, or http traffic capture.

**Comment by Thaina** [comment]
@sstevenkang I suspect it most likely the `AmazonLambdaClient.InvokeAsync` my app use that function in almost everything.

**Argument cannot be null. Parameter name: baseStream** is most likely came from

https://github.com/aws/aws-sdk-net/blob/37b2546044248de151a6ce47641ba096728fb5cb/sdk/src/Core/Amazon.Runtime/Internal/Util/WrapperStream.cs#L45

But I don't know much detail about it from my app. Only log error from some client sometimes so it hard to track

**Comment by sstevenkang** [comment]
Just to start, a stacktrace would help us narrow down how the exception surfaced.

**Comment by Thaina** [comment]
@sstevenkang I can't get stacktrace because it really random behaviour that occur with unknown cause from aws sdk

**Comment by vandelpal** [comment]
I have same error for SnsClient.SubscribeAsync and SnsClient.CreatePlatformEndpointAsync
Responce Callback recieve Exception with this stacktrace:

Amazon.Runtime.Internal.Util.WrapperStream..ctor	
Amazon.Runtime.Internal.Util.CachingWrapperStream..ctor	
.at	
Amazon.Runtime.Internal.Util.CachingWrapperStream:.ctor	
Amazon.Runtime.Internal.Transform.XmlUnmarshallerContext..ctor	
Amazon.Runtime.Internal.Transform.XmlResponseUnmarshaller.ConstructUnmarshallerContext	
Amazon.Runtime.Internal.Transform.ResponseUnmarshaller.CreateContext	
Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException
