### ISSUE TITLE
Random [Error unmarshalling response back from AWS]

### ISSUE THREAD

**Issue by Thaina** [aws/aws-sdk-net#775]
It seem like when I return large json data from aws to client. Sometimes it will cause this error. It happen not from specific call but can happen with any large chunk of json

## Expected Behavior
Never have this error

## Current Behavior
This error can popped up randomly when call lambda to get data

## Steps to Reproduce (for bugs)
Return a data larger than 40kb

## Your Environment
AWS Lambda dotnet core as server
AWSSDK.Lambda Version 3.3.*
Amazon.Lambda.Core Version 1.0.*
Amazon.Lambda.Serialization.Json Version 1.1.*

Unity3D as client
AWSSDK.Lambda, Version=3.3.0.0
AWSSDK.CognitoIdentity, Version=3.3.0.0

**Comment by sstevenkang** [comment]
Could you capture what exactly is being returned by lambda?

**Comment by Thaina** [comment]
@sstevenkang 

This is some sample of log error I got recently. It not so often but it randomly popped up

![image](https://user-images.githubusercontent.com/1042507/31680889-e0d78e54-b39f-11e7-80b0-4a80bdd26c2d.png)

**Comment by sstevenkang** [comment]
Is the reporting tool cutting off the response at the end?  If it is not doing that, it does look like an invalid json object.  Also, is there anyway you could provide the text response body instead of a screenshot?

**Comment by Thaina** [comment]
@sstevenkang Yes the response was cut from the logger. I think the actual message was fully intact

But is it possible that the unmarshalling error would came from an invalid json?

**Comment by sstevenkang** [comment]
Hmmm.  It was a guess.  There's not enough information to say.  Could you provide a small sample that repros this problem?

**Comment by Thaina** [comment]
@sstevenkang As I was state that it would randomly came from trying to return large data from lambda server while client calling lambda.InvokeAsync
