### ISSUE TITLE
Building ARM and x64 facing release build errors

### ISSUE THREAD

**Issue by jefhai** [aws/aws-sdk-net#776]
I'm trying to build a UWP application for release using AWS SDK (Core, S3, Cognito), but I'm having these error pop up. Any thoughts an suggestions would be really helpful! 

I'm building towards fall creators, and my min is set to 240.

``1>C:\Users\jeffreyhaines\.nuget\packages\microsoft.net.native.compiler\1.7.1\tools\Microsoft.NetNative.targets(697,5): warning : ILTransform : warning ILT0005: Type 'Amazon.Runtime.Internal.Util.AESEncryptionPutObjectStream' was not included in compilation, but was referenced in method 'EncryptionUtils.EncryptRequestUsingInstruction(Stream, EncryptionInstructions)'. There may have been a missing assembly.
1>C:\Users\jeffreyhaines\.nuget\packages\microsoft.net.native.compiler\1.7.1\tools\Microsoft.NetNative.targets(697,5): warning : ILTransform : warning ILT0003: Method 'EncryptionUtils.EncryptRequestUsingInstruction(Stream, EncryptionInstructions)' will always throw an exception due to the missing method 'AESEncryptionPutObjectStream..ctor(Stream, byte[], byte[])'. There may have been a missing assembly.
1>C:\Users\jeffreyhaines\.nuget\packages\microsoft.net.native.compiler\1.7.1\tools\Microsoft.NetNative.targets(697,5): warning : ILTransform : warning ILT0005: Type 'Amazon.Runtime.Internal.Util.AESEncryptionUploadPartStream' was not included in compilation, but was referenced in method 'EncryptionUtils.EncryptUploadPartRequestUsingInstructions(Stream, EncryptionInstructions)'. There may have been a missing assembly.
1>C:\Users\jeffreyhaines\.nuget\packages\microsoft.net.native.compiler\1.7.1\tools\Microsoft.NetNative.targets(697,5): warning : ILTransform : warning ILT0003: Method 'EncryptionUtils.EncryptUploadPartRequestUsingInstructions(Stream, EncryptionInstructions)' will always throw an exception due to the missing method 'AESEncryptionUploadPartStream..ctor(Stream, byte[], byte[])'. There may have been a missing assembly.
1>C:\Users\jeffreyhaines\.nuget\packages\microsoft.net.native.compiler\1.7.1\tools\Microsoft.NetNative.targets(697,5): warning : ILTransform : warning ILT0005: Type 'Amazon.Runtime.Internal.Util.AESDecryptionStream' was not included in compilation, but was referenced in method 'EncryptionUtils.DecryptStream(Stream, EncryptionInstructions)'. There may have been a missing assembly.
1>C:\Users\jeffreyhaines\.nuget\packages\microsoft.net.native.compiler\1.7.1\tools\Microsoft.NetNative.targets(697,5): warning : ILTransform : warning ILT0003: Method 'EncryptionUtils.DecryptStream(Stream, EncryptionInstructions)' will always throw an exception due to the missing method 'AESDecryptionStream..ctor(Stream, byte[], byte[])'. There may have been a missing assembly.
1>C:\Users\jeffreyhaines\.nuget\packages\microsoft.net.native.compiler\1.7.1\tools\Microsoft.NetNative.targets(697,5): warning : ILTransform : warning ILT0005: Type 'Amazon.Runtime.Internal.Util.EncryptUploadPartStream' was not included in compilation, but was referenced in method 'SetupDecryptionHandler.PostInvokeSynchronous(IExecutionContext, byte[])'. There may have been a missing assembly.
1>C:\Users\jeffreyhaines\.nuget\packages\microsoft.net.native.compiler\1.7.1\tools\Microsoft.NetNative.targets(697,5): warning : ILTransform : warning ILT0003: Method 'SetupDecryptionHandler.PostInvokeSynchronous(IExecutionContext, byte[])' will always throw an exception due to the missing method 'EncryptUploadPartStream.get_InitializationVector()'. There may have been a missing assembly.
1>C:\Users\jeffreyhaines\.nuget\packages\microsoft.net.native.compiler\1.7.1\tools\Microsoft.NetNative.targets(697,5): warning : ILTransform : warning ILT0005: Type 'Amazon.Runtime.Internal.Util.DecryptStream' was not included in compilation, but was referenced in method 'GetObjectResponse.<>c.<ValidateWrittenStreamSize>b__114_0(Stream)'. There may have been a missing assembly.``

Here are my dependencies:

Syncfusion Controls for UWP XAML, Version=15.3.0.33
AWSSDK.CognitoIdentity 3.3.2.15
AWSSDK.Core 3.3.18
AWSSDK.S3 3.3.11.2
Microsoft.ApplicationInsights 2.4.0
Microsoft.ApplicationInsights.PersistenceChannel 1.2.3
Microsoft.ApplicationInsights.WindowsApps 1.1.1
Microsoft.EntityFrameworkCore.Sqlite 1.1.3
Microsoft.NETCore.UniversalWindowsPlatform 5.4.1
Microsoft.Toolkit.Uwp 1.5.1
Microsoft.Toolkit.Uwp.UI 1.5.1
Microsoft.Toolkit.Uwp.UI.Controls 1.5.1
Newtonsoft.Json 10.0.3 
Win2D.uwp 1.21.0

**Comment by normj** [comment]
It looks like we have an issue with our nuspec file for AWSSDK.S3 and AWSSDK.CognitoIdentity which is causing Visual Studio to pull in the .NET Standard version of the those packages but then for AWSSDK.Core it is pulling in the portable class library version.

**Comment by jefhai** [comment]
@normj what is the timeline for a fix? we are still unable to build our projects because of this issue.

**Comment by normj** [comment]
New versions of all of the packages was released today that should fix the issue.

**Comment by jefhai** [comment]
I'm seeing a set of new errors pointing to amazon:

Severity	Code	Description	Project	File	Line	Suppression State
Error		ILT0005: 'C:\Users\jeffreyhaines\.nuget\packages\microsoft.net.native.compiler\1.7.1\tools\x64\ilc\Tools\nutc_driver.exe @"C:\Users\jeffreyhaines\Documents\git\StorySlab-Windows\SCHWING\obj\x64\Release\ilc\intermediate\MDIL\SCHWING.rsp"' returned exit code 1	SCHWING	C:\Users\jeffreyhaines\.nuget\packages\microsoft.net.native.compiler\1.7.1\tools\Microsoft.NetNative.targets	697	
Error		Type 'System.Net.IWebProxy' was not included in compilation, but was referenced in method 'AmazonS3HttpUtil.GetProxyIfAvailableAndConfigured(IClientConfig)'. There may have been a missing assembly.	SCHWING	C:\Users\jeffreyhaines\.nuget\packages\microsoft.net.native.compiler\1.7.1\tools\Microsoft.NetNative.targets	697	
Error		Method 'AmazonS3HttpUtil.GetHttpClient(IClientConfig)' will always throw an exception due to the missing method 'HttpClientHandler.set_Proxy(IWebProxy)'. There may have been a missing assembly.	SCHWING	C:\Users\jeffreyhaines\.nuget\packages\microsoft.net.native.compiler\1.7.1\tools\Microsoft.NetNative.targets	697	
Error		Method 'AmazonS3HttpUtil.GetHttpClient(IClientConfig)' will always throw an exception due to the missing method 'HttpClientHandler.set_Proxy(IWebProxy)'. There may have been a missing assembly.	SCHWING	C:\Users\jeffreyhaines\.nuget\packages\microsoft.net.native.compiler\1.7.1\tools\Microsoft.NetNative.targets	697	
Error		Type 'System.Net.IWebProxy' was not included in compilation, but was referenced in method 'AmazonS3HttpUtil.GetProxyIfAvailableAndConfigured(IClientConfig)'. There may have been a missing assembly.	SCHWING	C:\Users\jeffreyhaines\.nuget\packages\microsoft.net.native.compiler\1.7.1\tools\Microsoft.NetNative.targets	697

**Comment by jefhai** [comment]
Hello, just wanted to report we were able to successfully build after migrating our Syncfusion dependency, which we believe was precompiled and interfering with the ones AWS SDK required. After moving from the precompiled Syncfusion package installer to managing them under Nuget, the Amazon errors I reported resolved and we were able to compile for all target platforms.

**Comment by normj** [comment]
Thanks for following up and letting us know what was causing the additional errors.
