### ISSUE TITLE
VS 2017 while attempt to publish using AWS 2017 toolkit seeing error

### ISSUE THREAD

**Issue by mzd555** [aws/aws-sdk-net#779]
... invoking 'dotnet publish', .....
......
......

Error: Project is referencing NETStandard.Library version 1.6.1. Max version supported by netcoreapp1.0 is 1.6.0.
Error: NETStandard.Library 1.6.1 is used for target framework netcoreapp1.1.
Error: Check the following dependencies for versions compatible with netcoreapp1.0:
Error: Amazon.Lambda.Serialization.Json : 1.1.0
Error: MySqlConnector : 0.29.1

**Comment by normj** [comment]
MySqlConnector is pulling in dependencies that are targeted for .NET Core 1.1 which Lambda doesn't support. Looks like the last version that targeted .NET Core 1.0 was version 0.13.0. 

I understand the versioning and lack of support for a newer .NET Core runtime is challenging right now and we are working to improve that.
