### ISSUE TITLE
MalformedXML response on PutLifecycleConfiguration()

### ISSUE THREAD

**Issue by jimmiea** [aws/aws-sdk-net#784]
## Expected Behavior
Lifecycle rule should be created without errors

## Current Behavior
I'm getting "_MalformedXML, The XML you provided was not well-formed or did not validate against our published schema_" when using the PutLifecycleConfiguration endpoint.
Lifecycle rule not created.

My request captured by fiddler _(masked out some data with xxx)_

	PUT https://testbcktlifecyc.s3-eu-west-1.amazonaws.com/?lifecycle HTTP/1.1
	Content-Type: application/xml
	Content-MD5: xxx
	User-Agent: aws-sdk-dotnet-45/3.3.11.4 aws-sdk-dotnet-core/3.3.18.2 .NET_Runtime/4.0 .NET_Framework/4.0 OS/Microsoft_Windows_NT_6.2.9200.0 ClientSync
	host: testbcktlifecyc.s3-eu-west-1.amazonaws.com
	X-Amz-Date: 20171026T110154Z
	X-Amz-Content-SHA256: xxx
	Authorization: AWS4-HMAC-SHA256 Credential=xxx/eu-west-1/s3/aws4_request, SignedHeaders=content-md5;content-type;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=xxx
	Content-Length: 218

	<LifecycleConfiguration><Rule><Transition><Days>1</Days><StorageClass>GLACIER</StorageClass></Transition><ID>testbcktlifecyc_rule1</ID><Status>Enabled</Status></Rule></LifecycleConfiguration>

My response captured by fiddler

	HTTP/1.1 400 Bad Request
	x-amz-request-id: xxx
	x-amz-id-2: xxx
	Content-Type: application/xml
	Transfer-Encoding: chunked
	Date: Thu, 26 Oct 2017 11:01:55 GMT
	Connection: close
	Server: AmazonS3

	13f
	<?xml version="1.0" encoding="UTF-8"?>
	<Error><Code>MalformedXML</Code><Message>The XML you provided was not well-formed or did not validate against our published schema</Message><RequestId>xx</RequestId><HostId>xx</HostId></Error>
	0

I got the same error when using SDK 2.3.55.2

## Steps to Reproduce (for bugs)
Create LifecycleConfiguration object

	var configuration= new LifecycleConfiguration()
	{
		Rules = new List<LifecycleRule>
				{
					 new LifecycleRule
					{
						Id = "Rule1",
						Status = LifecycleRuleStatus.Enabled,
						Transitions = new List<LifecycleTransition>
						{
							new LifecycleTransition
							{
								Days = 1,
								StorageClass = S3StorageClass.Glacier
							}
						},
						
					}
				}
	};

and put using PutLifecycleConfiguration()

	PutLifecycleConfigurationRequest request = new PutLifecycleConfigurationRequest
	{
		BucketName = bucketName,
		Configuration = configuration
	};
	var response = _Client.PutLifecycleConfiguration(request);

## Your Environment
* AWSSDK.Core version used: Version=3.3.0.0
* Operating System and version: win 10
* Visual Studio version: 2015
* Targeted .NET platform: 4.5

**Comment by spati2** [comment]
Have you tried setting the expiration and the prefix values on the lifecycle rule? I was able to make a successful request once I set those values.

new LifecycleRule
                {
                    Id = "Rule1",
                    Status = LifecycleRuleStatus.Enabled,
                    Transitions = new List<LifecycleTransition>
                    {
                        new LifecycleTransition
                        {
                            Days = 1,
                            StorageClass = S3StorageClass.Glacier
                        }
                    },
                    Expiration = new LifecycleRuleExpiration { Days = 5 },
                    Prefix = "Logs/"

**Comment by jimmiea** [comment]
Nice, that did the trick!
I could even leave Prefix = "" and it let it through, and applied the rule on the whole bucket as I wanted.

So I guess it should apply the <Prefix></Prefix> even if the Prefix property isn't used.

thanks

**Comment by spati2** [comment]
np. I have followed up with S3 , to correct the error message. Thanks for bringing this up.
