### ISSUE TITLE
Issue with PUTObject when (zero byte) stream comes from a zip file

### ISSUE THREAD

**Issue by tapmantwo** [aws/aws-sdk-net#788]
## Expected Behavior
When PUT Object is called with a stream from within a compressed zip file, and is zero bytes in length, it should work (i.e. the object should be created in the S3 bucket)

## Current Behavior
We receive a 400 response, with the error: 
`Missing required header for this request: x-amz-content-sha256`

The header does not exist on the request.  If you upload the same file (not in a zip) it works fine, and also files with content from within the zip file also work fine.

## Steps to Reproduce (for bugs)
I have attached a console application to demonstrate the issue;
[ZeroByteIssue.zip](https://github.com/aws/aws-sdk-net/files/1434375/ZeroByteIssue.zip)

Launch it as follows;

`ZeroByteIssue.exe <accesskey> <secretkey> <bucketname> <region name>`

eg 

`ZeroByteIssue.exe myaccesskey mysecretkey my-bucket-name eu-west-2

## Context
We offer a facility for people to upload zip files, which we then unzip and store each individual file in S3.  This currently fails if the zip file contains a zero byte file.

## Your Environment
Targeting .NET 4.5, using 3.3.0.0 of the AWS SDK, running on awindows.

**Comment by steveataws** [comment]
Thanks for letting us know, and including a repro case. We'll take a look asap.

**Comment by normj** [comment]
We have identified the issue and have queued up a fix to go out in the next release.

**Comment by normj** [comment]
I pushed out version 3.3.19 of AWSSDK.Core and 3.3.12.1 of AWSSDK.S3 that contains the bug fix. Thanks for reporting the issue.

**Comment by tapmantwo** [comment]
That is a great turn around, thank you 😄

**Comment by sstevenkang** [comment]
@tapmantwo, once you've verified the fix, could you close this issue?

**Comment by tapmantwo** [comment]
Sure thing - will aim to do that this week.

**Comment by tapmantwo** [comment]
Confirmed this is fixed - thank you once again 👍
