### ISSUE TITLE
Still having issues building with reference to Amazon APIs?

### ISSUE THREAD

**Issue by jefhai** [aws/aws-sdk-net#789]
We are still unable to build our projects after thinking we had it fixed. Is there anything you can think of? Does there appear to be a problem on your side? Can you explain how .Net Standard/.Net Framework/.Net Core works with respect to AWS SDKs. Our biggest recent change in the past months has been the addition of Entity Core Framework 1.1.3. Are you aware of any incompatibilities with that package?

1>C:\Users\jefhai\.nuget\packages\microsoft.net.native.compiler\1.7.1\tools\Microsoft.NetNative.targets(697,5): warning : ILTransform : warning ILT0010: Could not find assembly 'System.Net.Http.Primitives, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' referenced by 'AWSSDK.S3'.
1>C:\Users\jefhai\.nuget\packages\microsoft.net.native.compiler\1.7.1\tools\Microsoft.NetNative.targets(697,5): warning : ILTransform : warning ILT0010: Could not find assembly 'System.Net.Http.Primitives, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' referenced by 'AWSSDK.S3'.
1>C:\Users\jefhai\.nuget\packages\microsoft.net.native.compiler\1.7.1\tools\Microsoft.NetNative.targets(697,5): warning : ILTransform : warning ILT0010: Could not find assembly 'System.Net.Http.Primitives, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' referenced by 'AWSSDK.S3'.
1>  Processing application code
1>C:\Users\jefhai\.nuget\packages\microsoft.net.native.compiler\1.7.1\tools\Microsoft.NetNative.targets(697,5): warning : ILTransform : warning ILT0010: Could not find assembly 'System.Net.Http.Primitives, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' referenced by 'AWSSDK.S3'.
1>C:\Users\jefhai\Documents\git\StorySlab-Windows\OurApp\Properties\Default.rd.xml(25): warning : ILTransform : warning ILT0027: Namespace 'System.Net.IWebProxy' within '' could not be found.
1>  Computing application closure and generating interop code
1>    Loading 142 modules...
1>    Generating code...
1>    Interop code generated.
1>  Generating serialization code
1>  Compiling interop code
1>  Generating System.Reflection.DispatchProxy proxy code.
1>C:\Users\jefhai\.nuget\packages\microsoft.net.native.compiler\1.7.1\tools\Microsoft.NetNative.targets(697,5): warning : ILTransform : warning ILT0005: Type 'System.Net.IWebProxy' was not included in compilation, but was referenced in method 'AmazonS3HttpUtil.GetProxyIfAvailableAndConfigured(IClientConfig)'. There may have been a missing assembly.
1>C:\Users\jefhai\.nuget\packages\microsoft.net.native.compiler\1.7.1\tools\Microsoft.NetNative.targets(697,5): warning : ILTransform : warning ILT0003: Method 'AmazonS3HttpUtil.GetHttpClient(IClientConfig)' will always throw an exception due to the missing method 'HttpClientHandler.set_Proxy(IWebProxy)'. There may have been a missing assembly.
1>  Cleaning up unreferenced code
1>  Generating native code
1>  Generating fixups for native code

**Comment by jefhai** [comment]
@normj referencing this previous issue https://github.com/aws/aws-sdk-net/issues/776

**Comment by jefhai** [comment]
@normj if possible maybe we could im chat? gitter perhaps? my company and I are struggling with this. Appreciate your time and help

**Comment by normj** [comment]
@jamesiri I'm on our gitter channel now, https://gitter.im/aws/aws-sdk-net?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge. But I will be away for a lot the afternoon. If you can create a simple repo case that I can take a look at that would help.

**Comment by jefhai** [comment]
Hey @normj, I'll try to connect with you on gitter if we can/need. Appreciate it.

Here is a sample project for you to look at. It's really basic. It is an empty project with AWS SDK and EntityFrameworkCore dependencies added. We are targeting Anniversary and min at 240.

https://github.com/themimcompany/AwsSampleIssue

**Comment by jefhai** [comment]
![awssampleissue](https://user-images.githubusercontent.com/22269225/32399113-ed5f48c4-c0c9-11e7-97bf-e5998ceeaaed.PNG)

**Comment by jefhai** [comment]
We believe this assembly issue is the root cause preventing us from certifying apps in the store. for some reason?

**Comment by normj** [comment]
We have identified a problem that might be causing our reference to get an HttpClient in a UAP application not to resolve with the AWSSDK.S3 package. The fix for us is shove all HttpClient work in the AWSSDK.Core which handles platform specific dependencies. In this case AWSSDK.S3 uses the HttpClient directly for some features and it doesn't resolve to the correct platform version for UAP apps.

Can you try adding a NuGet dependency to **Microsoft.Net.Http** to see if that gets you passed your issue?

We'll start work on abstracting away the HttpClient to AWSSDK.Core but that might take a week or so. I'm hoping the short term fix of adding the dependency to **Microsoft.Net.Http** gets you moving forward why we do the fuller fix.

**Comment by jefhai** [comment]
Thanks @normj, adding **Microsoft.Net.Http** did eliminate the warning. We will test our store submissions and let you know if we hit a wall. Your long term solution sounds good.

**Comment by sstevenkang** [comment]
Hi.  We haven't forgotten about this issue.  We have a potential fix in the review at the moment.

**Comment by spati2** [comment]
Hi, the fix for this issue should be out now. Download the latest nuget packages and let me know if there are any other concerns
