### ISSUE TITLE
S3FileInfo does not correctly say whether file exists

### ISSUE THREAD

**Issue by cidthecoatrack** [aws/aws-sdk-net#793]
When using S3FileInfo, it always returns `false` for the property `Exists`

## Expected Behavior
If the file exists in the S3 bucket, the property should return `true`

## Current Behavior
The property always returns `false`, even if the file is in fact in S3, even if other SDK commands can in fact return the desired file.

## Steps to Reproduce (for bugs)

The following xUnit test shows the issue:

```csharp
[Fact]
public void FileExists()
{
    var fileName = Guid.NewGuid().ToString() + "\\dummy\\path\\to\\file.txt";

    using (var client = clientFactory.GetClient())
    {
        var objectRequest = new PutObjectRequest();
        objectRequest.BucketName = config.BucketName;
        objectRequest.ContentBody = Guid.NewGuid().ToString();
        objectRequest.Key = fileName;

        var response = client.PutObject(objectRequest);
        Assert.Equal(HttpStatusCode.OK, response.HttpStatusCode);

        var request = new ListObjectsV2Request();
        request.BucketName = config.BucketName;

        var listResponse = client.ListObjectsV2(request);
        Assert.Equal(HttpStatusCode.OK, listResponse.HttpStatusCode);
        var contains = listResponse.S3Objects.Any(o => o.Key == fileName && o.BucketName == config.BucketName);
        Assert.True(contains);

        var putObject = listResponse.S3Objects.First(o => o.Key == fileName && o.BucketName == config.BucketName);
        Assert.Equal(config.BucketName, putObject.BucketName);
        Assert.Equal(fileName, putObject.Key);
        Assert.InRange(putObject.LastModified, DateTime.Now.AddMinutes(-1), DateTime.Now.AddMinutes(1));
        Assert.Equal(36, putObject.Size);

        var getResponse = client.GetObject(config.BucketName, fileName);
        Assert.Equal(HttpStatusCode.OK, getResponse.HttpStatusCode);
        Assert.Equal(config.BucketName, getResponse.BucketName);
        Assert.Equal(fileName, getResponse.Key);
        Assert.InRange(getResponse.LastModified.ToLocalTime(), DateTime.Now.AddMinutes(-1), DateTime.Now.AddMinutes(1));

        var info = new S3FileInfo(client, config.BucketName, fileName);
        Assert.True(info.Exists);
    }
}
```

All assertions in this test will pass - except for the last one, using the `S3FileInfo` class, which returns `false` for the `Exists` property.  Other fields on the class (such as `Directory` and `BucketName`) are correct.  `Length` is also 0 - it is as if it fails on the assumed `GetObject` request that underlies the constructor.

## Context
As the `Exists` property is the recommended way to see if a file exists in S3 or not, it is disturbing that the property does not seem to be working.  I am hoping that I have simply done something incorrect, but as of yet I do not know what that could be.

## Your Environment

* AWSSDK.Core version used: `3.3.19` (S3 SDK is version `3.3.12.1`)
* Operating System and version: Windows 10 development environment
* Visual Studio version: 2015 Enterprise
* Targeted .NET platform: `4.5.1`

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by sstevenkang** [comment]
S3 implicitly converts the forward slashes(\) in to backslash(/) in keys.  Please take a look at the table under [Characters to Avoid](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html).

**Comment by cidthecoatrack** [comment]
@sstevenkang - thanks for the tip, but that doesn't explain why the same file name works when searching for the key in the list response, or when using a `GetObjectRequest` directly, but then fails when using `S3FileInfo`.  It can be further noted that the `S3DirectoryInfo` behaves correctly regarding whether a directory exists or not (I know "directories" aren't really a thing in S3, but the abstraction is what I am focusing on here).

**Comment by sstevenkang** [comment]
Sorry, I meant to say that "it looks like S3 implicitly converts...". S3's public documentation doesn't specify how S3 handles the backslash characters beyond that it shouldn't be used in keyname.  I think we can read that as "using backslashes may result in undefined behavior."

Regarding your question about inconsistent behavior in the SDK, S3FileInfo uses `GetObjectMetadataRequest` underneath whereas S3DirectoryInfo uses `GetBucketLocation` or `ListObjetRequest`.

Is there a reason you want the key to contain a backslash?

**Comment by cidthecoatrack** [comment]
No particular reason.  And now,m after making that change, I see it working.  Sorry for the false bug - I was confused when I saw (in the source code)[https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/S3/Custom/_bcl/IO/S3FileInfo.cs] where the constructor does explicit checks around backslashes, but not around forward slashes.

**Comment by sstevenkang** [comment]
No worries!

Regarding the backslash check, we really should be doing forward slash checks as well.  I am a little hesitant to make this change as it may be a breaking change...
