### ISSUE TITLE
Getting a PlatformNotSupportedException when trying to write to kinesis

### ISSUE THREAD

**Issue by lbezawada** [aws/aws-sdk-net#795]
When i try to write to kinesis using the following code, i get a PlatformNotSupportedException.
The below code is part of a Lambda function which has full permissions (AmazonKinesisFullAccess) to kinesis stream. I don't think it's an issue with a dependency version being .net core 1.1 as i wouldn't have been able to publish to AWS if it were.       
    
``` C#
        public async Task<PutRecordResponse> AddRecordToKinesisStreamAsync<TMessage>(string streamName, string partitionKey, TMessage data)
        {
            byte[] dataBytes = Encoding.UTF8.GetBytes(Serializer.WriteObjectJsonUTCDate(data));

            using (var memStream = new MemoryStream(dataBytes))
            {
                using (var kinesis = new AmazonKinesisClient())
                {
                    PutRecordRequest putRecordRequest = new PutRecordRequest()
                    {
                        StreamName = streamName,
                        PartitionKey = partitionKey,
                        Data = memStream
                    };
                    return await kinesis.PutRecordAsync(putRecordRequest);
                }
            }
        }
```

EXCEPTION TYPE: System.PlatformNotSupportedException
EXCEPTION MESSAGE: Operation is not supported on this platform.
STACK TRACE: 
   at System.Runtime.InteropServices.OSPlatform.get_Windows()
   at Amazon.Runtime.ClientConfig.get_HttpClientCacheSize()
   at Amazon.Runtime.HttpRequestMessageFactory.CreateConfigUniqueString(IClientConfig clientConfig)
   at Amazon.Runtime.HttpRequestMessageFactory.CreateHttpRequest(Uri requestUri)
   at Amazon.Runtime.Internal.HttpHandler`1.CreateWebRequest(IRequestContext requestContext)
   at Amazon.Runtime.Internal.HttpHandler`1.<InvokeAsync>d__9`1.MoveNext()

**Comment by sstevenkang** [comment]
Seems like this is related to https://github.com/aws/aws-sdk-net/issues/791

**Comment by kekedk** [comment]
I use this temp work around:
```
var config = new AmazonSQSConfig
{
    HttpClientCacheSize = Environment.ProcessorCount
};
var client = new AmazonSQSClient(creds, config)
```
Since `HttpClientCacheSize ` is from the base class, so I would assume that you can do the same for kinesis config

**Comment by kekedk** [comment]
Other solutions:

1. Remove packages that reference .net standard 1.6.1
2. Force downgrade of System.Runtime.InteropServices.RuntimeInformation to version 4.0.0

**Comment by normj** [comment]
This is related to pulling in .NET Core 1.1 dependencies in a Lambda project. As @kekedk  mentioned make sure you have no indirect references to NETStandard.Library1.6.1. You can find out what NuGet package is doing that by looking at the *.deps.json file in your publish folder.
