### ISSUE TITLE
Cannot Download Installer for Visual Studio 2017

### ISSUE THREAD

**Issue by jmawebtech** [aws/aws-sdk-net#797]
Hi,

I am unable to download the Visual Studio 2017 .NET Toolkit from your site:

https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.AWSToolkitforVisualStudio2017#qna

The page just refreshes. I tried installing the VS 2017 toolkit here:

https://aws.amazon.com/sdk-for-net/

It appears to only work for VS 2013 and 2015. Do you have a 2017 version?

**Comment by gokarnm** [comment]
@jmawebtech, I'm able to download the VS 2017 VSIX from Visual Studio marketplace. The installer on AWS website does support VS 2017.
Which version/edition of VS 2017 is being used? Did you try the marketplace website using a different browser/machine?

**Comment by jmawebtech** [comment]
I found the correct link here: 

https://aws.amazon.com/blogs/developer/preview-of-the-aws-toolkit-for-visual-studio-2017/

https://sdk-for-net.amazonwebservices.com/preview/AWSToolkitPackage.VS2017.vsix

I use the latest version of Chrome. The link works fine in Edge.

**Comment by steveataws** [comment]
The changes in VS2017 to enable side-by-side installs of multiple versions makes it hard to support from a traditional Windows installer (msi), hence we took the decision to only distribute the toolkit for the 2017 editions of Visual Studio on the Visual Studio Marketplace. This is also generally becoming the more popular way to distribute Visual Studio extensions and has several attractive side effects such as automatic notifications of new updates etc. The ability of Microsoft's vsixinstaller in 2017 to allow extension content to be placed outside of the extension folder itself (for example our MSBuild targets for CloudFormation projects), something we previously required an msi to handle, was also a factor.

From this page - https://aws.amazon.com/visualstudio/ - clicking the 'AWS Toolkit for Visual Studio 2017' button should take you to the marketplace home for the tools (https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.AWSToolkitforVisualStudio2017). Clicking the other button will trigger a download of the msi for versions of the toolkit supporting VS2013 and VS2015. You should be able to find the toolkit on the marketplace from within Visual Studio 2017's Tools -> Extensions and Updates dialog (a search in the Online category for 'AWS' shows the toolkit), which is currently at v1.13.0.6.

The last set of links you posted were to the pre-release preview version of the toolkit which is quite old by now. You might want to check to see if an update is available. I also recommend uninstalling the preview version before installing the official RTM version. I can't recall significant changes affecting install layout between preview and the first version released to the marketplace, but as it was quite some time ago I could have overlooked something.

As the links from the AWS home pages etc all seem ok, and I'm seeing the correct version of the toolkit in  the marketplace I'm going to resolve this issue. Feel free to reopen if you still cannot find the toolkit or encounter a bad link from the AWS pages to the marketplace entry.
