### ISSUE TITLE
S3FileInfo.Key property should exist

### ISSUE THREAD

**Issue by adauti** [aws/aws-sdk-net#798]
When loading files to S3 using the APIs you have to generally specify the BucketName in a property and the Key in a separate property.  However, when you are getting information by using the S3FileInfo, you cannot go the other way and get the Key value by specifying for example S3FileInfo.Key.

Apologies if this exists under another property that i may have missed.

Currently, to get the Key Value of an S3 object, i have to do something like S3FileInfo.FullName.Replace("s3:\","").Replace()...etc etc.  I think you get the point.

**Comment by sstevenkang** [comment]
I agree. We'll add this to our backlog.
