### ISSUE TITLE
Amazon.Runtime.AmazonClientException: The retrieved credentials have already expired

### ISSUE THREAD

**Issue by ore-boris** [aws/aws-sdk-net#800]
I am running into attached exception from Amazon.Runtime.RefreshingAWSCredentials call several times a week, in clients talking to different Amazon services. 

Most frequently it happens in the  AWS Logger (aws-logging-dotnet). Below two attached files are from two log4net appenders, working in the same application. The appender from aws-logger-errors-2.log was actively sending log messages which successfully arrived to AWS CloudWatchLogs, and suddenly it run into credentials expired error. Last successful log record was stamped by 2017-11-19 13:39:10,161, and the exception in the attached log stamped by 11/19/2017 13:40:09, saying that credentials have expired at 11/19/2017 13:39:48.
[aws-logger-errors-2.log](https://github.com/aws/aws-sdk-net/files/1486908/aws-logger-errors-2.log)
Another example is from another appender which was quite silent, and woke up at 11/20/2017 00:03:31 only to see that credentials have expired at the same time as in the prevous one 11/19/2017 13:39:48
[aws-logger-errors-1.log](https://github.com/aws/aws-sdk-net/files/1486907/aws-logger-errors-1.log)

I also saw this error with SNS service once:
```
2017-11-13 13:42:21,354 [22745] ORE.BoTrader.Bll.Logic.AutoTrader ERROR Auto trading exception during OrderFlow Monitor timer event:
Amazon.Runtime.AmazonClientException: The retrieved credentials have already expired: Now = 11/13/2017 13:42:21, Credentials expiration = 11/13/2017 04:21:22
   at Amazon.Runtime.RefreshingAWSCredentials.UpdateToGeneratedCredentials(CredentialsRefreshState state)
   at Amazon.Runtime.RefreshingAWSCredentials.GetCredentials()
   at Amazon.Runtime.Internal.CredentialsRetriever.PreInvoke(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext)
   at Amazon.Runtime.AmazonServiceClient.Invoke[TRequest,TResponse](TRequest request, IMarshaller`2 marshaller, ResponseUnmarshaller unmarshaller)
   at Amazon.SimpleNotificationService.AmazonSimpleNotificationServiceClient.Publish(PublishRequest request)
   at ORE.BoTrader.Bll.Logic.AutoTrader.OnOrderFlowMonitorTimerElapsedEvent(Object source, ElapsedEventArgs e) in C:\Users\eddie\ORE-GIT\ore\Source\Web\BoTrader\BoTraderBll\Logic\AutoTrader.cs:line 738
```

In all 3 cases service access was authorized via IAM role attached to an EC2 instance where the error occurred.

I expect credentials to be updated transparently, as per documentation: 
[Granting Access Using an IAM Role](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-hosm.html#net-dg-roles)
> If the client doesn't find credentials in App.config, it retrieves temporary credentials that have the same permissions as those associated with the IAM role from instance metadata. The credentials are stored by the constructor on behalf of the application software, and are used to make calls to AWS from that client object. Although the credentials are temporary and eventually expire, the SDK client periodically refreshes them so that they continue to enable access. **This periodic refresh is completely transparent to the application software.**

I see that the issue is gone after restarting the module which uses AWS client, so that the client performs fresh connection to the service. After restart it may happen again after several hours or several days or weeks of normal operation.

I believe this issue is not the same as [#393](https://github.com/aws/aws-sdk-net/issues/393), as the machine clock was NTP synchronized when the issue was observed.

I am not aware of specific chain of events that lead to this issue, so cannot provide clear steps to reproduce the issue at the moment.

In the case of AWS Logger the issue is breaking monitoring cycle for local queue of the log records to be sent to AWS and as a result logging to AWS stops. 

If the service is used in our own code - we can catch the exception and reconnect to the service.

In the logs for AWS Logger, we were using latest version of AWSSDK.Core (3.3.19.0). The SNS example is for AWSSDK.Core V3.3.17.9 All involved services are running on Windows Server 2016, and use .NET V4.6.2.

**Comment by Bluestreak2k5** [comment]
This might be related to the same Issue I'm having on a desktop machine Issue #806 . It seems that some process is keeping the credentials file open the entire time. Since your using a role like I am, your likely writing it to the same file.

You can't update the file because the file is being held open, which then causes the credentials to fail because they are old. You may have to setup something to stop/restart the service to get around this.

You could log changes to the credentials file doing a tail -f or something similar to see that it doesn't change.

**Comment by ore-boris** [comment]
I checked machines where I saw the exceptions, and confirmed they do not have .aws\credentials files on them. This goes along with my understanding that using [temporary credentials](http://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp.html)  does not involve any file manipulations. 
Also I do not have either AWS Toolkit or Visual Studio installed on the machines, and I use AWS SDK for .NET directly in my C# code.
I understand that permissions from  an IAM role attached to an EC2 instance are granted via temporary credentials mechanism ([Using an IAM Role to Grant Permissions to Applications Running on Amazon EC2 Instances](http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2.html)).
Finally, I checked code involved in a refresh of temporary credentials from EC2 instance profile ([InstanceProfileAWSCredentials.cs](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Credentials/InstanceProfileAWSCredentials.cs), [URIBasedRefreshingCredentialHelper.cs](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Credentials/URIBasedRefreshingCredentialHelper.cs) and [RefreshingAWSCredentials.cs](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Credentials/RefreshingAWSCredentials.cs))  and I do not see any file manipulations there either. It looks like it keeps credentials in memory and does some periodic attempts to refresh them, but apparently something goes wrong in this process.
So, in my scenario I cannot confirm that constantly open .aws\credentials file could have caused the exceptions.

**Comment by smadigan-hli** [comment]
We are also seeing this issue, any update?

**Comment by smadigan-hli** [comment]
one thing that might help - this only seems to affect .NET processes, not (for example) python processes

**Comment by normj** [comment]
So you know this isn't being ignored I'm going back through the code to see if I can find corner cases that are being missed with how the SDK refreshes the credentials.

**Comment by smadigan-hli** [comment]
Great, thanks for the update

**Comment by sstevenkang** [comment]
We released a [new implementation](https://github.com/aws/aws-sdk-net/commit/ade50e7562d6df9b3fb72a11f4db44a4f74c05c4) of instance profile credentials in https://www.nuget.org/packages/AWSSDK.Core/3.3.24.

**Comment by swlasse** [comment]
Just a note on this one. I have experienced the same exception in a docker container where we were using the AWS .NET SDK to access S3. Due to a misconfiguration, outbound Internet traffic got blocked "over night" and thus blocked the SDK from automatically refreshing credentials (giving us the above exception).

Fixing the misconfiguration and restarting the container solved it for us.
