### ISSUE TITLE
DynamoDBContext only has LoadAsync method, lacking Load

### ISSUE THREAD

**Issue by rabejens** [aws/aws-sdk-net#804]
I added AWSSDK.DynamoDBv2 to my .net core project and tried to use `DynamoDBContext` but found it only has a `LoadAsync` method. Is this correct with .net core, or do I have to add an additional dependency?

**Comment by sstevenkang** [comment]
Yes that's correct.  Is there a reason to use `Load()` over `LoadAsync()`?

**Comment by normj** [comment]
Close as I believe this is answered.

**Comment by Jeremy-Barnes** [comment]
@sstevenkang Why do the tutorials/documentation refer to a synchronous `Load()` if it doesn't exist?
http://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/DynamoDBv2/MDynamoDBContextLoadObject.html

http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DotNetDynamoDBContext.html

> Load
Retrieves an item from a table. The method requires only the primary key of the item you want to retrieve.

By default, DynamoDB returns the item with values that are eventually consistent. For information on the eventual consistency model, see Read Consistency.

Note

To perform this operation in the background, use the LoadAsync method instead.

**Comment by freeborn5** [comment]
is there an example of LoadAsync()
