### ISSUE TITLE
Handle incorrect system time

### ISSUE THREAD

**Issue by cheif** [aws/aws-sdk-net#81]
We are experiencing problems with users that have incorrect system times, namely that their put-object requests gets a time-skewed error from amazon, which is expected.

Our current solution is just to display to the users that they need to set their system time and try again, not a very elegant solution.

It would be nice if there existed a way to either seed the library with a NTP-synced DateTime or just use this as a standard for the library, but i'm not sure if there are other implications to this, aside from a small performance hit.

So any thoughts?

**Comment by PavelSafronov** [comment]
The latest version of the SDK (2.3.23) now identifies clock-skew and corrects for it. More information is available in [this blog post](http://blogs.aws.amazon.com/net/post/Tx2HM54KL5LMTGI/).

**Comment by robhruska** [comment]
@PavelSafronov Thanks for the fix, much appreciated!
