### ISSUE TITLE
The XML you provided was not well-formed or did not validate against our published schema

### ISSUE THREAD

**Issue by xin-young** [aws/aws-sdk-net#810]
![default](https://user-images.githubusercontent.com/8943317/33866213-3fa35268-df30-11e7-8589-3f75289cc28d.png)
![default](https://user-images.githubusercontent.com/8943317/33866226-4c67e856-df30-11e7-8f78-1fb97920aa44.png)
![default](https://user-images.githubusercontent.com/8943317/33866375-53cc3376-df31-11e7-9178-c131c36749a2.png)
![default](https://user-images.githubusercontent.com/8943317/33866411-91128078-df31-11e7-9e3c-336f83edddaa.png)

i work follow the document，but a exception appear when merge files.
http://docs.aws.amazon.com/zh_cn/AmazonS3/latest/dev/LLuploadFileDotNet.html

**Comment by normj** [comment]
When you call CompleteMultipartUploadAsync you need to fill in the PartETags collection on the CompleteMultipartUploadRequest object with all of the parts you uploaded. We definitely need a better error message.

You can also use Amazon.S3.Transfer.TransferUtility which will automatically take care of the multipart upload.

**Comment by xin-young** [comment]
Good suggestions.The first instance of the document misled me.I want to upload data directly from the Web page to S3,so choose this way.

**Comment by fractos** [comment]
Just hit this - you definitely need better error messages.
