### ISSUE TITLE
Delete multipartpart error 

### ISSUE THREAD

**Issue by xin-young** [aws/aws-sdk-net#812]
![tim 20171213144555](https://user-images.githubusercontent.com/8943317/33925350-b88256c2-e014-11e7-8f93-eb8c4dc10ec9.png)

After CompleteMultipartUpload is successful, 3 empty  parts have not been removed.
If there is only one part, the situation will not appear.

![tim 20171213144813](https://user-images.githubusercontent.com/8943317/33925353-b9e113f0-e014-11e7-9eb7-b463738572c0.png)

AWS Toolkit for Visual Studio 2017 1.13.0.2
.NET CORE 2.0.3

**Comment by normj** [comment]
Without a code example showing what you are doing there is not much help we can provide. By this data online it looks like a bug in the code calling the SDK.

**Comment by xin-young** [comment]
You are right,i made some mistakes in keeping uploadid.Keeping uploadid is difficult in situations where multiple sessions and filenames are unknown.
