### ISSUE TITLE
CloudFormation validation for DynamoDB scaling

### ISSUE THREAD

**Issue by NeilBostrom** [aws/aws-sdk-net#813]
## Expected Behavior
CloudFormation template validation inside Visual Studio validates TargetTrackingScalingPolicyConfiguration and ScalingTargetId properties of AWS::ApplicationAutoScaling::ScalingPolicy. The document uploads to CloudFormation fine without any validation errors, so the errors are local to Visual Studio.

## Current Behavior
Validation fails for TargetTrackingScalingPolicyConfiguration with:

TargetTrackingScalingPolicyConfiguration key is invalid for this object.

ScalingTargetId with a ref target of AWS::ApplicationAutoScaling::ScalableTarget fails with:

*** is an invalid type for this reference.		

![image](https://user-images.githubusercontent.com/18393729/33933577-0dc1a3bc-dfee-11e7-8b39-0e56b2d8d375.png)

![image](https://user-images.githubusercontent.com/18393729/33933592-1e52de44-dfee-11e7-991c-994bbf7ab6fa.png)

## Possible Solution
Support these new CloudFormation types.

## Steps to Reproduce (for bugs)

`		"DynamoDBTableApplicationSetting": {
			"Type" : "AWS::DynamoDB::Table",
			"DeletionPolicy": "Retain",
			"Condition": "CreateDynamoDbTables",
			"Properties" : {
				"AttributeDefinitions" : [
					{
						"AttributeName" : "Key",
						"AttributeType" : "S"   
					}
				],
				"KeySchema" : [
					{
						"AttributeName" : "Key",
						"KeyType" : "HASH"
					}
				],
				"ProvisionedThroughput" : {
					"ReadCapacityUnits" : "1",
					"WriteCapacityUnits" : "1"
				},
				"TableName": "ApplicationSettings"
			}
		},
		"DynamoDBTableApplicationSettingWriteCapacityScalableTarget": {
			"Type": "AWS::ApplicationAutoScaling::ScalableTarget",
			"Condition": "CreateDynamoDbTables",
			"Properties": {
				"MaxCapacity": 50,
				"MinCapacity": 1,
				"ResourceId": { "Fn::Join": ["/", ["table", { "Ref": "DynamoDBTableApplicationSetting" } ]	] },
				"RoleARN": { "Fn::GetAtt": ["DynamoDBScalingRole", "Arn"] },
				"ScalableDimension": "dynamodb:table:WriteCapacityUnits",
				"ServiceNamespace": "dynamodb"
			}
		},
		"DynamoDBTableApplicationSettingWriteScalingPolicy": {
			"Type": "AWS::ApplicationAutoScaling::ScalingPolicy",
			"Condition": "CreateDynamoDbTables",
			"Properties": {
				"PolicyName": "DynamoDBTableApplicationSettingWriteScalingPolicy",
				"PolicyType": "TargetTrackingScaling",
				"ScalingTargetId": { "Ref": "DynamoDBTableApplicationSettingWriteCapacityScalableTarget" },
				"TargetTrackingScalingPolicyConfiguration": {
					"TargetValue": 50.0,
					"ScaleInCooldown": 60,
					"ScaleOutCooldown": 60,
					"PredefinedMetricSpecification": {
						"PredefinedMetricType": "DynamoDBWriteCapacityUtilization"
					}
				}
			}
		},`

## Your Environment
Visual Studio 2017
AWS Toolkit for Visual Studio 2017 - 1.13.0.2

**Comment by normj** [comment]
Yeap, the toolkit's CloudFormation schema has gotten a bit out of date with the rush for the re:Invent conference. I'll work on getting it back up to date over the next few days.

**Comment by normj** [comment]
I got the CloudFormation schema updated over the holidays. Next time restart Visual Studio you should see those errors go away.

**Comment by NeilBostrom** [comment]
So good news is "TargetTrackingScalingPolicyConfiguration key is invalid for this object." error is now gone, however, "*** is an invalid type for this reference." still happening.

![image](https://user-images.githubusercontent.com/18393729/34515383-c13a8fd6-f069-11e7-9665-bcd0f53a171d.png)

![image](https://user-images.githubusercontent.com/18393729/34515408-de1bbc74-f069-11e7-80d2-ac8b7cc97d51.png)

As I mentioned before, the template apply in Cloudformation fine, just validation errors in VS.

**Comment by normj** [comment]
Whoops, sorry about that miss. You should see that validation go away the next time you restart VS.

**Comment by NeilBostrom** [comment]
Legend!
