### ISSUE TITLE
AWS Transfer Utility does not set content types correctly when uploading a directory

### ISSUE THREAD

**Issue by disophisis** [aws/aws-sdk-net#814]
When uploading a directory with the Transfer Utility, it is not setting content types correctly, causing the browser to interpret these files incorrectly when accessing our static site on our s3 bucket.

## Expected Behavior
Content types should be set on .svg, .json, and .css files

## Current Behavior
Currently when uploading a directory certain files are not showing the correct content types.  In our case, any files that is showing this behavior has been set to application/octet-stream instead.

## Steps to Reproduce (for bugs)
Current code:
```
TransferUtilityUploadDirectoryRequest req = new TransferUtilityUploadDirectoryRequest
{
	BucketName = _bucketName,
	Directory = _directory,
	CannedACL = S3CannedACL.PublicRead
};

await util.UploadDirectoryAsync(req);
```

## Context
These files are interpreted incorrectly by the browser when trying to access the static website on our s3 bucket.

## Your Environment

* AWSSDK.Core version used:  3.3.21.1
* Service assembly and version used: 
* Operating System and version:  Win 10 

## .NET Core Info

* .NET Core version used for development:   2
.NET Command Line Tools (2.0.3)

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.3\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by normj** [comment]
To confirm what I'm seeing the SDK do

css -> text/css (Which seems right)
svg -> image/svg+xml (Which seems right)
json -> application/octet-stream (Not correct and should be application/json)

Is that what you are seeing?

**Comment by disophisis** [comment]
I feel a little foolish now.  Turns out all these files were in an assets directory that was not getting included with the upload.  Dev tools were showing 403s for those files rather than 404s so it was a little confusing.  I added a search option to the upload directory request so it includes subdirectories now and it seems like it is working way better.
