### ISSUE TITLE
WorkDocs: Ampersands in User ID not handled correctly in ActivateUser, DeactivateUser, DeleteUser, UpdateUser

### ISSUE THREAD

**Issue by murphy112358** [aws/aws-sdk-net#816]
The WorkDocs APIs ActivateUser, DeactivateUser, DeleteUser, UpdateUser have the following URL formats where User ID is specified as part of the URL:

    /api/v1/users/{UserId}/activation
    /api/v1/users/{UserId}

The ampersand does not seem to be URL-escaped, resulting in an unintended failure (Invalid SigV4 signature.)

**Comment by mikmurphy** [comment]
Same API calls via the AWSCLI succeed.

**Comment by normj** [comment]
Thanks for reporting the issue. We'll take a look.

**Comment by mikmurphy** [comment]
In looking at the source, the URL is not URI-encoded prior to sigv4 signing.

**Comment by normj** [comment]
Wanted to let you know I'm still looking into. I am reproducing the problem and I'm digging through the signing code. It is going to take a bit as the signing code is one of the trickiest parts of the SDK.

**Comment by mikmurphy** [comment]
Please reopen the issue.On Jul 9, 2020 5:23 PM, "github-actions[bot]" <notifications@github.com> wrote:
We have noticed this issue has not recieved attention in a year. We will close this issue for now. If you think this is in error, please feel free to comment and reopen the issue.

**Comment by ashishdhingra** [comment]
Hi @murphy112358,

Good evening.

I tried to use AWSSDK.WorkDocs API to activate user using call `AmazonWorkDocsClient.ActivateUserAsync`. This method accepts `ActivateUserRequest` object containing the `UserId`. The user ID as per my analysis is of the form `S-1-5-21-1697062004-3222066451-2888852732-1109&d-906764719b` which contains an ampersand `&`. When I invoked `AmazonWorkDocsClient.ActivateUserAsync` call, it worked perfectly fine without any issue. 

Could you please confirm if this is still an issue with the latest AWSSDK.WorkDocs 3.5.0.71 package?

Thanks,
Ashish

**Comment by emu7800** [comment]
Please resolve if the issue has since been addressed. Thanks!
--------- Original Message --------- Subject: Re: [aws/aws-sdk-net] WorkDocs: Ampersands in User ID not handled correctly in ActivateUser, DeactivateUser, DeleteUser, UpdateUser (#816)
