### ISSUE TITLE
No libsqlite3.so for x86_64 Androids in Unity3d packages

### ISSUE THREAD

**Issue by Hinidu** [aws/aws-sdk-net#817]
Hello!
Packages for Unity3d have libsqlite3.so inside but only for ARM architecture. And what's even worse they have this file in the root of Plugins directory (though the same file is inside inner ARM-specific directory).
Because of that we had huge performance degradation on Android devices with x86_64. We build fat apk with both architectures supported, but device found that this .so-file is built for ARM and choose ARM binaries even if it's CPU is x86_64.
We are lucky because we actually don't need these .so-files and could just remove them.

**Comment by kvasukib** [comment]
Thanks, @Hinidu for pointing it out. We are looking into it.
