### ISSUE TITLE
libsqlite3 binaries in Unity3d packages which doesn't need them

### ISSUE THREAD

**Issue by Hinidu** [aws/aws-sdk-net#818]
Hello!
It looks like all packages for Unity3d have libsqlite3 binaries inside but it is only used in CognitoSync and MobileAnalytics services.
So it looks like it is not needed to include these binaries in other packages. Taking into account another issue: https://github.com/aws/aws-sdk-net/issues/817. Including these unnecessary binaries even drastically degrade performance on some devices.

**Comment by kvasukib** [comment]
Thanks, @Hinidu for pointing it out. We are looking into it.
