### ISSUE TITLE
Unity2017.3 , aws lambda sdk  can not use long string.

### ISSUE THREAD

**Issue by ulgerang** [aws/aws-sdk-net#820]
when I use unity 2017.3 , I can not use long string.
 it occur  exception.

Amazon.Lambda.AmazonLambdaException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

## Steps to Reproduce (for bugs)

send any long message, about 2000 charactor  ,  to lambda using unity aws sdk.

ResultText.text = "Invoking '" + FunctionNameText.text + " function in Lambda... \n";
            string text = @"{""key1"":""aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"" }";

            Debug.Log("text.legnth "+ text.Length);

            Client.InvokeAsync(new Amazon.Lambda.Model.InvokeRequest()
            {
                FunctionName = "HelloLamda",
                Payload = text
            },
            (responseObject) =>
            {
                ResultText.text += "\n";
                if (responseObject.Exception == null)
                {
                    ResultText.text += Encoding.ASCII.GetString(responseObject.Response.Payload.ToArray()) + "\n";
                }
                else
                {
                    ResultText.text += responseObject.Exception + "\n";
                }
            }
            );

## Your Environment

I just used 'AWSSDK.Lambda.3.3.10.0.unitypackage'
and Unity 2017.3

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 
.net 3.5  and .net 4.6

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by rams3s** [comment]
After upgrading to Unity2017.3 and AWSSDK.Lambda.3.3.10.0.unitypackage, we also encountered a similar issue.

I can confirm that the issue is only occurring for a request with a 'heavy' payload.
Requests with smaller payloads continue to work properly as they used to...

Please let me know if I can provide any extra info that can help identify the cause of this issue...

**Comment by amir-ahinoam** [comment]
After upgrading to Unity2017.3 I encountered a similar issue, but in my case I get the lambda exception with very short payload.

**Comment by kvasukib** [comment]
Thanks for reporting to us. We are looking into it.
@rams3s @amir-ahinoam @ulgerang Can you quantify the size of the string from which the calls to Lambda through Unity SDK fail? Was it working in older versions of Unity as in Unity 2017.2?

**Comment by ulgerang** [comment]
@kvasukib  It is working in Unity 2017.2 .  Using 2017.3,  small string works fine, but long string make it fail.

**Comment by amir-ahinoam** [comment]
@kvasukib in Unity 2017.2 & 2017.2.1 with AWSSDK.lambda 3.3.8.3 & 3.3.10.0 it works fine. With Unity 2017.3 it fails for payload as short as 68 chars.

**Comment by kvasukib** [comment]
Thanks, @ulgerang, and @amir-ahinoam. We are investigating.

**Comment by xavrr** [comment]
even stranger, on my side for the same given payload it will not always fail...  1 out of 4/5 requests would work.

**Comment by jordanmuraskin** [comment]
Could this be a similar problem as issue #823 ?

**Comment by housei** [comment]
@kvasukib 
I understood how to avoid this error.
You can avoid errors by setting UnitWebRequest.chunkedTransfer to false.
I'd like to ask you to fix it with AWSSDK.

I responded by the following method.

`
UnityInitializer.AttachToGameObject(gameObject);
gameObject.AddComponent<CustomUnityMainThreadDispatcher>();
`

CustomUnityMainThreadDispatcher.cs
https://gist.github.com/housei/b38cc93d6e8fe7caa2764d5b0dc34393

**Comment by snanurag** [comment]
For me, it gives error quite often but not always. So what I do, is send the request repeatedly. It gives the error like 7-8 times and then succeeds. But screen waits for that long time. So it is really a show stopper for user experience. My launch is waiting for the resolution of this bug. I won't even do the alpha launch of my game without it being fixed. 

So please guys.. Make it a priority...
