### ISSUE TITLE
Visual Studio w/ AWS Toolkit - Publishing Docker configuration to Elastic Beanstalk Docker Environment

### ISSUE THREAD

**Issue by andytl6** [aws/aws-sdk-net#821]
## Feature Request
Provide an ability to publish from Visual Studio to a AWS Elastic Beanstalk Single Container Docker  Environment [1] such as the '64bit Amazon Linux 2017.09 v2.8.1 running Docker 17.06.2-ce' [2] using the AWS Toolkit for VS 2017

AWS Toolkit to recognize that publishing should factor in the Dockerrun.aws.json files, and/or Dockerfile as specified here [3].  

Currently, when publishing from Visual Studio to an EB environment that uses a Dockerrun.aws.json file, the publishing process ignores the file and publishes the Project as a 'normal' application into IIS. It's not aware that the publish process involves an EB single container docker environment and ignores the custom configurations in the .json file

References: 
[1] http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/docker-singlecontainer-deploy.html
[2] http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/concepts.platforms.html#concepts.platforms.docker
[3] http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_docker_image.html

## Environment
Visual Studio Community 2017 - v15.3.3
AWS Toolkit for Visual Studio 2017 - 1.12.2.1
.Net Framework v 4.6.1
Windows 10

**Comment by normj** [comment]
You might want try our new toolkit feature to deploy docker containers to an ECS cluster. You need the latest version of the toolkit to use it. Here are the docs for the new feature. 

http://docs.aws.amazon.com/toolkit-for-visual-studio/latest/user-guide/deployment-ecs.html

**Comment by andytl6** [comment]
Thanks, will take a look.
Prefer an Elastic Beanstalk solution Visual Studio for this, if the concept is even possible.

**Comment by normj** [comment]
Is the goal to use docker or to run your ASP.NET Core on Linux? Wondering what is the more important goal, tooling support for Elastic Beanstalk and Docker or getting a Linux based ASP.NET Core Beanstalk environment.

**Comment by Pelias2525** [comment]
I am in the same situation where I am publishing to AWS Elastic Beanstalk from AWS Toolkit for Visual Studio 2017. Without the inclusion of the dockerfile in the zip the deployment fails. Right now it requires manual manipulation of the deployment package, breaking the intent of the 'Publish the Elastic Beanstalk' automation. Any thoughts on this?

**Comment by MikeyFriedChicken** [comment]
After you publish the asp.net core from VS to AWS should the site then be available to use?  Do you need a task of some kind running?   Bit confused why it needs a task?

**Comment by Pelias2525** [comment]
After you publish the project, if you navigate to the Beanstalk Application, the application deployment will have failed. Exploring the logs, it's due to the dockerfile /dockerrun.aws.json files not being present in the deployment zip automatically uploaded during publish. The workaround is to then to go to the Application Versions area, download the latest deployment, manually add the files to the zip and then redeploy using that modified zip file. We need those 2 files to be included in the original publication cycle.
