### ISSUE TITLE
.Net Core Signature Mismatch

### ISSUE THREAD

**Issue by neurospeech** [aws/aws-sdk-net#823]
I have following code, one is ASP.NET 4.5 and same is used for ASP.NET Core 2.0, 

Following ASP.NET 4.5 works fine

NuGet 
```xml
  <package id="AWSSDK.Core" version="3.3.17.4" targetFramework="net45" />
  <package id="AWSSDK.S3" version="3.3.8.2" targetFramework="net45" />
```

```c#
Amazon.Runtime.AWSCredentials cd = new Amazon.Runtime.BasicAWSCredentials(Key, Secrete);
client = new AmazonS3Client(cd, Amazon.RegionEndpoint.USEast1);
Amazon.S3.Model.PutObjectRequest req = new Amazon.S3.Model.PutObjectRequest();
req.BucketName = name;
req.Key = path;
req.InputStream = ms;
req.ContentType = mimeType;
req.Headers.CacheControl = "public,max-age=3240000";
req.CannedACL = S3CannedACL.PublicRead;

client.PutObject(req);
```

Following ASP.NET Core 2.0 code gives Signature Mismatch Error **"The request signature we calculated does not match the signature you provided. Check your AWS secret access key and signing method."**

NuGet
```xml
    <PackageReference Include="AWSSDK.S3" Version="3.3.16" />
```

```c#
Amazon.Runtime.AWSCredentials cd = new Amazon.Runtime.BasicAWSCredentials(key, secrete);
client = new AmazonS3Client(cd, Amazon.RegionEndpoint.USEast1);

Amazon.S3.Model.PutObjectRequest req = new Amazon.S3.Model.PutObjectRequest();
req.BucketName = name;
req.Key = path;
req.ContentType = mimeType;

req.Headers.CacheControl = "public,max-age=3240000";
req.InputStream = stream;
req.CannedACL = S3CannedACL.PublicRead;

await client.PutObjectAsync(req);
```

Key, Secret, Name and Path passed are exactly same for both cases. Also I have verified that there is no extra special character in bucket Name (it is alphanumeric).

I have gone through change log to see if any special config is needed for signature version, but as per your change log, S3 client after "3.3.6.2" uses SigV4 by default. So in both the projects SigV4 is turned on by default.

**Comment by normj** [comment]
I have been playing around with this today and I'm seeing some odd behavior. Can you try in your cache control to add a space between the comma and the word max? Like this
```csharp
req.Headers.CacheControl = "public, max-age=3240000";
```

My theory is the .NET Core HttpClient is automatically adding a space which was not there when we computed the signature.

**Comment by neurospeech** [comment]
@normj Thanks !! that fixed it.

**Comment by normj** [comment]
Great. Let me know of any other headers you see this behavior of spaces being added in automatically. I'll see if there is a way for us to handle it in the SDK. I'm thinking we can detect the cache control is set and make sure there is a space between the comma separated values before passing the request along to the signer and the HttpClient.

**Comment by ebekker** [comment]
I'm having the same issue with the .NET Core SDK 2.1 preview 2 -- for any request (tried S3 and R53).

**Comment by sstevenkang** [comment]
@ebekker that's an HTTP client bug in preview 2.  Please test against nightly builds.  See https://github.com/aws/aws-sdk-net/issues/932

**Comment by ebekker** [comment]
Thanks, I upgraded to the recently released [RC1 build](https://blogs.msdn.microsoft.com/dotnet/2018/05/07/announcing-net-core-2-1-rc-1/) and tested it out and everything is peachy again.

Thanks!

**Comment by qiuxinyidian** [comment]
i have the same issue with net3.5
`
                PutObjectRequest tmpRequest = new PutObjectRequest
                {
                    BucketName = tmpBucketName,
                    Key = tmpKey

                };

                PutObjectResponse tmpResponce;
                using (FileStream stream = new FileStream(tmpFilePath, FileMode.Open))
                {
                    tmpRequest.InputStream = stream;
                    tmpResponce = s3Client.PutObject(tmpRequest);
                }
`

**Comment by mungojam** [comment]
It seems the order is also important:

`max-age=0, no-cache` doesn't work
`no-cache, max-age=0` does

This is with .net core 2.1 LTS and latest amazon libraries.

I'm not clear why this issue was closed?

**Comment by qiuxinyidian** [comment]
i try to Circumvent the problem by v2 .

**Comment by motoko89** [comment]
> @normj I'm also experiencing the same thing using the `ContentType` property
> 
> **Doesn't work**
> 
> ```
> PutObjectRequest putRequest = new PutObjectRequest
> {
>    ContentType = "application/json;charset=utf8",
>    ...
> }
> ```
> 
> **Works**
> 
> ```
> PutObjectRequest putRequest = new PutObjectRequest
> {
>    ContentType = "application/json; charset=utf8",
>    ...
> }
> ```
> 
> This is really painful and hard for users to find :/

Thank you thank you thank you. It took me almost 2 hours to find your reply but it would have cost me two days otherwise. This should be more at the top. All the stackoverflow questions point to file name and I only got issue starting last week while never changed my naming logic
