### ISSUE TITLE
Support for EC2 Systems Manager Parameter Store

### ISSUE THREAD

**Issue by melih154** [aws/aws-sdk-net#829]
Using latest AWSSDK.Core Nuget Package(3.3.21.6) 

Trying to store and retrieve the RDS Connection Strings from EC2 System Manager Parameter Store on my .Net Application.

Couldn't find a way to do that using AWS SDK. Searched through v3 APIDocs, specifically on EC2, KMS, Amazon and Amazon Util - but no luck. Is that supported on AWS SDK?

Also, found out that AWS CLI supports this functionality. Any way to run commands on AWS CLI using AWS SDK for .NET?

Here is the EC2 System Manager Parameter Store
https://eu-west-2.console.aws.amazon.com/systems-manager/parameters

**Comment by melih154** [comment]
Found it, sorry for this.
https://docs.aws.amazon.com/sdkfornet/v3/apidocs/index.html?page=SSM/MSSMGetParameterGetParameterRequest.html

**Comment by steveataws** [comment]
No worries, resolving issue.
