### ISSUE TITLE
Significant upload performance variance between using a stream and a filepath

### ISSUE THREAD

**Issue by tapmantwo** [aws/aws-sdk-net#831]
Hi, we've been investigating some performance issues with uploads to S3 using the SDK.  On our production servers (which are in a London data centre),  we've observed that a 250mb file can take up to 1m 35s to upload to a bucket (in EU-WEST-2).

We investigated this further - the code is currently using the TransferUtility class, so we tried a few experiements;
1) Use the lower level multi part api - no difference
2) Use the put object api - no difference
3) The code currently uses the 'InputStream' option, so we changed it to use FilePath - massive difference.  We found that using the FilePath, the upload completed in 15 seconds.

So, I have created a small test harness to demonstrate the difference.  

[UploadPerfIssue.exe.zip](https://github.com/aws/aws-sdk-net/files/1614908/UploadPerfIssue.exe.zip)

[UploadPerfIssue Code.zip](https://github.com/aws/aws-sdk-net/files/1614912/UploadPerfIssue.Code.zip)

If you update the app config with appropriate credentials, and then run it with a command line argument specifying the size of file (in mb) you want to test with, it  will run both variants, and output the timings.

eg

`UploadPerfIssue.exe 250`

On our production box, which has a connection with a 470mb/s, the results for a 250mb file were

```
Uploading as a file
Call took 00:00:17
Uploading as a stream 
Call took 00:01:15
```

On our office network, which has a connection with 150mb/s, the results for a 250mb file were

```
Uploading as a file
Call took 00:00:13
Uploading as a stream 
Call took 00:00:18
```

and with a 1gb file

```
Uploading as a file
Call took 00:00:38
Uploading as a stream 
Call took 00:01:14
```

So the variance seems to depend on connection and file size.

We could move over to the file path option, but that would be a large scale change for us, as we primarily deal with streams (and indeed, there are some options where a file path isn't really an option for us).

## Expected Behavior
Both options should perform roughly the same

## Current Behavior
Dependent on network connection and file size, the variance between each option is quite large

## Steps to Reproduce (for bugs)
Run the attached tool, specifying a file size in mb as a command line arg.  Note, you will also need to set access key, secret key, bucket and region in the config file.  

## Context
Complaints of poor performance in production

## Your Environment
Windows Server, .NET 4.6.1

**Comment by normj** [comment]
When you upload on object via a FilePath the TransferUtility will break up the file and upload parts in parallel. With streams we can't break up the object so we have to load each part sequentially.

**Comment by tapmantwo** [comment]
Ah I see.  So actually the Parallelisation isn't possible with streams.  Thanks!
