### ISSUE TITLE
AWSPowerShell Copy-S3Object fails when -key parameter value starts with a "/"

### ISSUE THREAD

**Issue by getSurreal** [aws/aws-sdk-net#833]
Prior to AWSPowerShell 3.3.215.0 the key parameter worked with a leading "/" on Copy-S3Object
Read-S3Object and Get-S3Object still work with a leading "/"

## Expected Behavior
When using Copy-S3Object the key parameter should work with a leading "/"

## Current Behavior
Copy-S3Object : Index was out of range. Must be non-negative and less than the size of the collection.

## Steps to Reproduce (for bugs)
Copy-S3Object -BucketName test-bucket -Key /data/sample.txt -DestinationKey /data/sample-copy.txt

## Context
We have a lot of automated code that started failing after upgrading AWSPowerShell

**Comment by steveataws** [comment]
Apologies, this cmdlet recently underwent some work to enable it to support copies of objects greater than 5GB in size between buckets and it looks like we broke something. I'll get a fix out asap.

**Comment by steveataws** [comment]
v3.3.221.0 was shipped with the fix yesterday evening, resolving issue. Feel free to reopen if you encounter continued problems.
