### ISSUE TITLE
Unable To Post Files

### ISSUE THREAD

**Issue by JGuthrie-Bluebeck** [aws/aws-sdk-net#835]
Folks this just feels like the SDK is broken and after reading issues like below it makes me want to move to another provider.

https://github.com/aws/aws-sdk-net/issues/332

For me the problem is pretty clearly that in the web request it is trying to set headers that it shouldn't be touching:

InvalidOperationException: Cannot override system-specified headers

Looks like the culprit is Content-Length.

This happening when I try to put anything into my bucket (I can get from it just fine). I get different errors when I try to post but they where so generically non-sensical I switched to put.

The other change I have from the demo example is that I use:

`  awsCredentials = new BasicAWSCredentials(AWSAccessKey, AWSSecretKey);`

**Comment by gokarnm** [comment]
@JGuthrie-Bluebeck , which version of SDK, platform is being used?

**Comment by JGuthrie-Bluebeck** [comment]
Hey @gokarnm, latest version at time of writing so 3.3.220 for the zip and 3.3.16.2 for S3 specifically

**Comment by sstevenkang** [comment]
@JGuthrie-Bluebeck , if you are using .NET Core, what's the runtime verison?  You can get this by running `dotnet --info`

**Comment by JGuthrie-Bluebeck** [comment]
Sorry was not specific on my part, forgot to mention this is me using the Unity SDK (As in the title of the other post).

Its using .net 3.5, Unity also has the option of .net 4.6 but I strongly doubt it will matter in this case (plus 4.6 support is not currently marked as stable so would rather avoid it)

**Comment by msf567** [comment]
I also have this issue, using the S3 Sample scene from the sdk. I can list objects and buckets no problem, but upon attempting to Post, I get hit with 

> Exception while posting the result object: Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
  at Amazon.Runtime.Internal.UnityRequest.EndGetResponse (IAsyncResult asyncResult) [0x00000] in <filename unknown>:0 
  at Amazon.S3.AmazonS3Client.ProcessPostResponse (IAsyncResult result) [0x00000] in <filename unknown>:0 

I've scoured the other issue thread related to this and applied all of the fixes described, and still have the same issue.

I can absolutely provide more information upon request.

**Comment by awesomeunleashed** [comment]
I just spent a couple hours doing research and tweaking the SDK source code, and I discovered the issue and solution (for Unity 2017.3, at least) are noted here:
https://answers.unity.com/questions/1450373/set-content-length-header-for-unitywebrequest-post.html

Adding `chunkedTransfer = false` to the `UnityWebRequest` creation in `UnityWebRequestWrapper` fixed the issue for me.

**Comment by chenchen2015** [comment]
For those of you guys like me who do not know exactly how to set `chunkedTransfer = false` in the source code, here's one way to do it (inside [`UnityWebRequestWrapper.cs`](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Pipeline/_unity/UnityWebRequestWrapper.cs)):

Add the following line within the `UnityWebRequestWrapper` constructor body
```c#
// in UnityWebRequestWrapper()

unityWebRequestInstance = Activator.CreateInstance(unityWebRequestType);

// Disable chunkedTransfer
unityWebRequestType.GetProperty ( "chunkedTransfer" ).GetSetMethod ().Invoke ( unityWebRequestInstance, new object[] { false } );
```

**Comment by Arc8ngel** [comment]
@chenchen2015 - Can your method be accomplished with the Unity SDK packages directly, or is it necessary to pull the source in order to amend UnityWebRequestWrapper?

I'm just trying to get S3Example.unity up and running.  It will list the objects in my bucket, but the POST always fails, same as @msf567 reported above.  I'm assuming it's this wrapper/chunkedtransfer issue.
_Unity 2017.3.1f1 + aws-sdk-unity_3.3.269.0_

**Comment by chenchen2015** [comment]
@Arc8ngel you have to do this in the source code and recompile the DLLs yourself

**Comment by AltairMartinez** [comment]
The proposed solution was not enough for me and it is still happening. I applied a similar solution for UnityWwwRequestFactory.cs and this fixed it for me. 

```
        public void SetRequestHeaders(IDictionary<string, string> headers)
        {
            foreach (var item in headers)
            {
                **//unity web request doesnt allow us to add the Host, User-Agent and Content-Length headers
                if (item.Key.Equals(HeaderKeys.HostHeader, StringComparison.InvariantCultureIgnoreCase)
                        || item.Key.Equals(HeaderKeys.ContentLengthHeader, StringComparison.InvariantCultureIgnoreCase)
                        || item.Key.Equals(HeaderKeys.UserAgentHeader, StringComparison.InvariantCultureIgnoreCase))
                    continue;**

                this.Headers.Add(item);
            }
        }
```

**Comment by ashishdhingra** [comment]
Hi @JGuthrie-Bluebeck,

Good afternoon.

Starting with version 3.5 of the AWS SDK for .NET, projects using Unity 2018.1 or later should target the .NET Standard 2.0 release of the SDK. You can find additional information in the developer guide: [Unity support](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/unity-special.html) and [Migrating your Unity application](https://docs.aws.amazon.com/sdk-for-net/latest/developer-guide/net-dg-v35.html#net-dg-v35-changes-unity).

Please try using the .NET Standard 2.0 version of the AWS SDK for .NET (version 3.5). 

Thanks,
Ashish
