### ISSUE TITLE
Git tag formatting bug?

### ISSUE THREAD

**Issue by b-stime** [aws/aws-sdk-net#836]
Today, if you look at e.g., https://www.nuget.org/packages/AWSSDK.Core/ , you'll see the latest available version of the AWSSDK.Core is:

3.3.21.6

However, if you look at the tags on GitHub, the version with the lowest apparent string-edit-distance (https://en.wikipedia.org/wiki/Levenshtein_distance) is:

3.3.216.0

I think there might be a bug in the code that formats the git tag strings.

![image](https://user-images.githubusercontent.com/34577613/34956132-6526625a-f9ed-11e7-8470-ce7051742638.png)

**Comment by gokarnm** [comment]
@b-stime , the tags on the aws-sdk-net repo represent an SDK release and are independent of the version of AWSSDK.Core package. We tag the repo with a logical product version for each public release that can include one or more service updates or a core package update. This version is also used in the [SDK change log](https://github.com/aws/aws-sdk-net/blob/master/SDK.CHANGELOG.md). Let me know if you have more questions.
