### ISSUE TITLE
.NETCore (NetStandard) Status

### ISSUE THREAD

**Issue by guitarrapc** [aws/aws-sdk-net#843]
I'm not sure issue is right place to question about subject, is there any list about each SDK support statuses? 

I think this Blog post is the last update about and there are no other references.
> https://aws.amazon.com/blogs/developer/aws-and-net-core-2-0/ 

for example, I'm making .NETStandard 2.0 library and want to use AWSSDK.ElasticLoadBalancing but not supporting yet. (Every time I'm checking nuget package dependency)

> https://www.nuget.org/packages/AWSSDK.ElasticLoadBalancing/

Any advice is appreciated.

**Comment by sstevenkang** [comment]
I am a little confused.  netstandard2.0 is a superset of netstandard1.3 and is/should be compatible.

**Comment by guitarrapc** [comment]
You are right. AWSSDK.ElasticLoadBalancing is my misunderstand, it can compile with netstandard2.0.
