### ISSUE TITLE
HttpHandler seems to send request with empty body when exception occures in WriteContentToRequestBody

### ISSUE THREAD

**Issue by tukaef** [aws/aws-sdk-net#849]
We've found a strange file on our S3 storage. The headers were correct (except `Content-Length`) but content was empty, though we're always setting it. 
Unfortunately we could not save logs for this, but it's worth mention that our app was in low memory condition, when this file was created. 

[This method](https://github.com/aws/aws-sdk-net/blob/756b9be7952aff2072441d1bb1b407990b071cd5/sdk/src/Core/Amazon.Runtime/Pipeline/HttpHandler/HttpHandler.cs#L141) seems to send a request even when it fails to write content to request body:

```
try
{
    var requestContent = await httpRequest.GetRequestContentAsync().ConfigureAwait(false);
    WriteContentToRequestBody(requestContent, httpRequest, executionContext.RequestContext);
}
catch(Exception e)
{
    edi = System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(e);
}

if (edi != null)
{
    await CompleteFailedRequest(executionContext, httpRequest).ConfigureAwait(false);

    edi.Throw();
}
```
 
Is that an expected behavior? I think it might be the cause (extremely rare, though) of empty files creation.
In our case, it supposed to be `OutOfMemotyException` occured in `WriteContentToRequestBody`.

Environment
* AWSSDK.Core version: 3.3.16.2
* .NET Core version: 2.0.5
* Runtime ID: ubuntu.14.04-x64

**Comment by sstevenkang** [comment]
Could you give a little more detail?  How did you diagnose that OOM is linked to the empty file?  Pardon my skepticism because OOM exceptions are usually fatal.  I am curious as to how it managed to send off HTTP request with 0 content-length.

**Comment by tukaef** [comment]
The only information that I have is that app memory was exceeding cgroups limit and the app was killed by OOM Killer in few seconds after file creation. So if there was an exception, then it _could_ be OOM.

Please, consider this issue as a question: What whould be sent if an exception occured in `WriteContentToRequestBody`? I found out that we're actually [sending ](https://github.com/aws/aws-sdk-net/blob/756b9be7952aff2072441d1bb1b407990b071cd5/sdk/src/Core/Amazon.Runtime/Pipeline/HttpHandler/HttpHandler.cs#L197) the request in `CompleteFailedRequest` method. So is there a possibility we're sending request without body?

**Comment by tukaef** [comment]
There was a bug in our S3 storage. Sometimes it created empty files when an incomplete chunked encoded request was sent.
