### ISSUE TITLE
X-Ray for HttpClient

### ISSUE THREAD

**Issue by smcmurrin-RA** [aws/aws-sdk-net#850]
We're using the System.Net.Http.HttpClient, and the X-Ray SDK example uses HttpWebRequest. Is there a way or to use x-ray with the HttpClient, or a plan to be able to use the HttpClient in the future?

**Comment by normj** [comment]
Adding support for HttpClient is something we are looking into but first we are trying to finish up the .NET Core support.

**Comment by jjohs** [comment]
Will HttpClient support be included in the .NET Core final release?

**Comment by normj** [comment]
Support for HttpClient was added in 2.2.0-beta of the package AWSXRayRecorder.Handlers.System.Net
