### ISSUE TITLE
Pagination not working on Route53 ListResourceRecordSetsAsync

### ISSUE THREAD

**Issue by ranga543** [aws/aws-sdk-net#852]
## Expected Behavior
`listResourceRecordSetsResponse.NextRecordIdentifier` should have value when there are records left to process.

### Pagination Not working
`listResourceRecordSetsResponse.NextRecordIdentifier` always returns `null` even though there are records left to process.

## Steps to Reproduce (for bugs)
```C#
           var hostedZonesResponse = await _amazonRoute53.ListHostedZonesAsync();
            foreach (var hostedZone in hostedZonesResponse.HostedZones)
            {
               // Test pagination
                var r = new ListResourceRecordSetsRequest(hostedZone.Id) {MaxItems = "2"};
                do
                {
                    var listResourceRecordSetsResponse = await _amazonRoute53.ListResourceRecordSetsAsync(r);
                    r.StartRecordIdentifier = listResourceRecordSetsResponse.NextRecordIdentifier;
                   Process(listResourceRecordSetsResponse.ResourceRecordSets)
                } while (!string.IsNullOrEmpty(r.StartRecordIdentifier));
            }
```

## Your Environment

* AWSSDK.Route53 version used: 3.3.13

## .NET Core Info

* .NET Core version used for development: 2

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by sstevenkang** [comment]
This seems like an issue on the service side. If I can repro it, I'll let the Route53 team know.

**Comment by sstevenkang** [comment]
It actually looks like you are misusing the API.  You probably want to use `NextRecordName` instead of `NextRecordIdentifier`:

>**IsTruncated**
>A flag that indicates whether more resource record sets remain to be listed. If your results were truncated, you can make a follow-up pagination request by using the _NextRecordName_ element.

> **NextRecordIdentifier**
> _Weighted, latency, geolocation, and failover resource record sets only_: If results were truncated for a given DNS name and type, the value of SetIdentifier for the next resource record set that has the current DNS name and type.
