### ISSUE TITLE
Missing ActionIdentifiers in Amazon.Auth.AccessControlPolicy.ActionIdentifiers

### ISSUE THREAD

**Issue by aphedges** [aws/aws-sdk-net#853]
The `Amazon.Auth.AccessControlPolicy.ActionIdentifiers` namespace contains classes that contain `ActionIdentifier`s for most actions available in AWS. However, some are missing.

## Expected Behavior
There should be `ActionIdentifier`s for actions such as AttachGroupPolicy, DetachRolePolicy, and SnsReceive, along with many others.

## Current Behavior
Currently, if one needs the `ActionIdentifier` for a missing action, one needs to manually create it. They are likely missing because new actions were added after the files were last modified in 2015.

## Possible Solution
A `static`, `readonly` `ActionIdentifier` can be made for each missing action in classes such as `IdentityandAccessManagementActionIdentifiers`. This should be a relatively simple fix, as there is only one line needed for each missing action.

## Context
This has required the manual creation of the missing `ActionIdentifier`s I need for a project. Ideally, this workaround would not be needed because the SDK should include them. Not requiring separate logic for the missing `ActionIdentifier`s would improve my code quality and maintainability.

**Comment by ryanwilliams83** [comment]
It would be good if you could prioritize fixing this issue.
I just spent an hour troubleshooting a typo in a code generated IAM policy.

// Rediculous
Action = new List<string>
{
	S3ActionIdentifiers.DeleteObject.ActionName,
	@"s3:DeleteObjectTagging",
	S3ActionIdentifiers.DeleteObjectVersion.ActionName,
	@"s3:DeleteObjectVersionTagging",
	S3ActionIdentifiers.GetObject.ActionName,
	S3ActionIdentifiers.GetObjectAcl.ActionName,
	@"s3:GetObjectTagging",
	S3ActionIdentifiers.GetObjectTorrent.ActionName,
	S3ActionIdentifiers.GetObjectVersion.ActionName,
	S3ActionIdentifiers.GetObjectVersionAcl.ActionName,
	@"s3:GetObjectVersionTagging",
	@"s3:GetObjectVersionTorrent",
	S3ActionIdentifiers.PutObject.ActionName,
	S3ActionIdentifiers.PutObjectAcl.ActionName,
	@"s3:PutObjectTagging",
	S3ActionIdentifiers.PutObjectVersionAcl.ActionName,
	@"s3:PutObjectVersionTagging"
}

**Comment by klaytaybai** [comment]
Hi @ryanwilliams83, thank you for reviving this issue.   I will try to get the team to agree to coming up with a better long term solution or process.  I cannot make guarantees as to when to this will be done, but it is very unlikely that it will come before re:Invent at the end of the month.
