### ISSUE TITLE
AWS S3 TransferUtility for Unity

### ISSUE THREAD

**Issue by chenchen2015** [aws/aws-sdk-net#854]
Currently (as of release `v3.3.227.0`), S3.TransferUtility is not yet supported in the Unity SDK. Is there any official plan to support this in Unity any time soon?

Here's one of the biggest benefit using TransferUtility:
> When uploading large files by specifying file paths instead of a stream, TransferUtility uses multiple threads to upload multiple parts of a single upload at once. When dealing with large content sizes and high bandwidth, this can **increase throughput significantly**.

Which is definitely a handy feature to have for many file intensive use cases.

**Comment by sstevenkang** [comment]
Unfortunately we don't have any immediate plans to support it.
