### ISSUE TITLE
Configure dependency injection in .NET Core 

### ISSUE THREAD

**Issue by danijel88** [aws/aws-sdk-net#859]
I had follow https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-netcore.html 
but in Startup.cs when I want to add service IAmazonS3 getting an error.
![image](https://user-images.githubusercontent.com/2229396/35904207-9200ae46-0be2-11e8-978e-57e62193be42.png)

can you please let me know why this doesnt works ?

**Comment by sstevenkang** [comment]
I can't repro this problem.  Did you forget to add AWSSDK.S3 nuget package?

**Comment by danijel88** [comment]
It is added. I tried to not include this line into Startup.cs and uploading is working without any problems.

**Comment by sstevenkang** [comment]
Could you just share us with a complete repro?

**Comment by danijel88** [comment]
Hello,
Here is link where you can find how I'm trying to set AWS SDK https://github.com/danijel88/TestAwsSDK

Thanks for your time
Kind Regards,
Danijel

**Comment by sstevenkang** [comment]
In the documentation you linked it says:

> To use the Configuration object to get the AWS options, first add the AWSSDK.Extensions.NETCore.Setup NuGet package. Then, add your options to the configuration file.

In the project you provided, I added S3 and NetCore.Setup packages, it built and the application runs fine.
