### ISSUE TITLE
Secure API Access with Cognito and API Gateway

### ISSUE THREAD

**Issue by luizgustavogp** [aws/aws-sdk-net#860]
Hy guys,

## Expected Behavior

Secure my API Gateway with API Cognito OAuth2 Scopes.

## Context

I sent a get request to my API with the authorization header, but I received a 401:

` var uri = new Uri("https://....execute-api.us-east-1.amazonaws.com/dev/customer");
            var client = new HttpClient();
            client.DefaultRequestHeaders.Add("Authorization",  context.AuthenticationResult.AccessToken);
            var response = client.GetAsync(uri).Result;
            var responseString = response.Content.ReadAsStringAsync().Result;`

I´m using  API Gateway with Cognito OAuth2 Scopes authorization and this example [cognitoauthentication-extension-library](https://aws.amazon.com/pt/blogs/developer/cognitoauthentication-extension-library-developer-preview/) to SignIn a user on Cognito.

Is necessary sign the request or only add the authoriztion header with the[ Access Token](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html#amazon-cognito-user-pools-using-the-access-token) is enough?

## Your Environment
Xamarin Portable
Windows 10 x64

**Comment by sstevenkang** [comment]
What' the response from the service?

**Comment by luizgustavogp** [comment]
Hi, 
I changed to use an **Identity Token** instead of **Access Token** and works fine.

[Reference link](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-enable-cognito-user-pool.html#apigateway-enable-cognito-user-pool)
