### ISSUE TITLE
SQS Client ChangeMessageVisibility hangs

### ISSUE THREAD

**Issue by wsiddiqui** [aws/aws-sdk-net#867]
This is the call we're using synchronously:

`_sqsClient.ChangeMessageVisibility(new ChangeMessageVisibilityRequest(queueUrl, receiptHandle, 0));
`

where _sqsClient is an instance of AmazonSQSClient.

We're also using X-Ray, so when we create an instance of AmazonSQSClient, we're doing:

`var _sqsClient = new AmazonSQSClient(RegionEndpoint.USEast1);
new AWSSdkTracingHandler(AWSXRayRecorder.Instance).AddEventHandler(_sqsClient );`

## Expected Behavior
ChangeMessageVisibilityRequest should complete, setting the message's visibility timeout to 0 to put it back on the queue without having to wait for the visibility timeout, and then the application proceeds as normal. 

## Current Behavior
A call is made out to the sqs client as specified above, but that call never returns, and the application doesn't proceed since it's synchronous. 

## Steps to Reproduce (for bugs)
`var _sqsClient = new AmazonSQSClient(RegionEndpoint.USEast1);
new AWSSdkTracingHandler(AWSXRayRecorder.Instance).AddEventHandler(client);
_sqsClient.ChangeMessageVisibility(new ChangeMessageVisibilityRequest(queueUrl, receiptHandle, 0));
`

## Context
We're trying to put a message we took off the SQS queue back on the queue. Setting the visibility timeout should change the message from being In Flight to Available. 

## Your Environment
SDK: AWSSDK.SQS 3.3.3.2
IDE: Visual Studio 2017 Enterprise 15.5.0
Framework: .NET Framework 4.6.1

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by sstevenkang** [comment]
Since this is Xray related, this is probably better tracked in the xray repo: https://github.com/aws/aws-xray-sdk-dotnet.
