### ISSUE TITLE
.NET Core CreateBatchGet not working with Global Secondary Index using Object Persistence Model

### ISSUE THREAD

**Issue by ryantomlinson** [aws/aws-sdk-net#881]
## Expected Behavior
When calling the `CreateBatchGet` method on `DynamoDBContext` I'm passing in the `DynamoDBOperationConfig` object into the constructor to specify the `IndexName`. The expected behaviour is that my query is executed on the GSI specified in this index.

## Current Behavior
When using a GSI there are no results returned in `BatchGet<T>` instance. When I don't try and specify and index (by not passing a `DynamoDBOperationConfig` into the constructor of `CreateBatchGet`) then I do get a response as expected.

## Possible Solution
Unsure

## Steps to Reproduce (for bugs)
```
using System;
using Amazon;
using Amazon.DynamoDBv2;
using Amazon.DynamoDBv2.DataModel;

namespace CreateBatchGetExample.Console
{
    class Program
    {
        static void Main(string[] args)
        {
            var client = new AmazonDynamoDBClient(RegionEndpoint.USEast1);
            var dynamoDbContext = new DynamoDBContext(client);
            
            var environmentsBatchRead = dynamoDbContext.CreateBatchGet<Environment>(
                new DynamoDBOperationConfig
                {
                    IndexName = "ProjectId-index"
                });
            
            environmentsBatchRead.AddKey("d0fd325b-08d1-4874-8a06-3b45043fe658");
            var result = environmentsBatchRead.ExecuteAsync();

            result.Wait();

            var environments = environmentsBatchRead.Results;

            System.Console.ReadKey();
        }

        [DynamoDBTable("TestApp.Environment")]
        public class Environment
        {
            [DynamoDBHashKey]
            public string EnvironmentId { get; set; }
            public string CreatedBy { get; set; }
            public string Name { get; set; }
            [DynamoDBGlobalSecondaryIndexHashKey("ProjectId-index")]
            public string ProjectId { get; set; }
            public string SdkKey { get; set; }
            public DateTime CreatedDate { get; set; }
        }
    }
}
```

## Context
I need to query upon a GSI for multiple items by key. I don't see any reason why this shouldn't work. My only guess is that it's not taking into account the `DynamoDBOperationConfig.IndexName`.

## Your Environment
* AWSSDK.DynamoDBv2 version 3.3.6
* .NetCoreApp 2
* Mac OSx High Sierra 10.13.3
* Jetbrains Rider

## .NET Core Info
* dotnet Core version 2.1.4

**Comment by ryantomlinson** [comment]
<img width="737" alt="screen shot 2018-02-26 at 09 09 56" src="https://user-images.githubusercontent.com/1033384/36662232-a2785b96-1ad5-11e8-92ac-5a5de4680d0a.png">

This image showing the debug information for `environmentsBatchRead` confirms my suspicions that the GSI hash key isn't being taken into account and instead it is still using the table hash key of `EnvironmentId`.

**Comment by Sarel-Esterhuizen** [comment]
It looks like BatchGet is only supported on the base table at this point in time and not on indexes.
