### ISSUE TITLE
Kinesis video streams in .Net

### ISSUE THREAD

**Issue by francoisdutoit** [aws/aws-sdk-net#882]
Hi,
Are there any examples as to how to read a Kinesis video stream in .Net?
Currently I am able to see my stream in the AWS console - but how do I use the AWSSDK.KinesisVideo to access my streams?

Thanks!

**Comment by vellozzi** [comment]
There aren't any existing examples. 
[Here](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/Index.html) is the method you would use to list your streams.
From that link you should be able to get to the rest of the AmazonKinesisVideoClient documentation.
Let me know if you have other specific questions.

**Comment by vellozzi** [comment]
I missed that you're specifically trying to read a stream.
[Here](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/Index.html)'s the API I think you're looking for.

**Comment by francoisdutoit** [comment]
@vellozzi 
Both the links you gave me just link to the SDK..... can you maybe point me to the method I need to use?
Thanks!

**Comment by vellozzi** [comment]
Here they are.
[AmazonKinesisVideoClient.ListStreams](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/KinesisVideo/MKinesisVideoListStreamsListStreamsRequest.html)
[AmazonKinesisVideoMediaClient.GetMedia](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/KinesisVideoMedia/MKinesisVideoMediaGetMediaGetMediaRequest.html)

**Comment by francoisdutoit** [comment]
@vellozzi 

Think I'm getting close to my solution - I have opened another issue regarding the above ( AmazonUnmarshallingException #885 ) Just getting an exception - Can you maybe look at the request and see if I am missing something?

Thanks!

**Comment by kashy422** [comment]
Hey geys, 
I am trying to make a PUT_MEDIA request from dotnet. I compiled JAVA project and took resources DLL for windows. NO LUCK. Even I am not able to make any progress using .net aws kinesis media library 
any example code for producer is highly appreciated.

**Comment by axolmain** [comment]
Any progress?

**Comment by kashy422** [comment]
I tried my best to work in dotnet but failed to achieve any good results. 
But, I have figured out a way, I build a python code (using boto) added it as resource in Dotnet App and Ran it via scripting runtime. 

here you can find python code 
https://www.linkedin.com/pulse/streaming-camera-video-aws-kinesis-streams-using-python-kashif-ayub-map9f/?trackingId=7nyNcFsAHCxk7J4%2FCvAN%2Fw%3D%3D

and here is how I used it in dotnet app
```
MediaStreamerExt mediaStreamer = new MediaStreamerExt();
mediaStreamer.Start("PyResource.py", $"{MyArgument});
```
