### ISSUE TITLE
Limit an S3 upload filesize with a Pre-signed URL ?

### ISSUE THREAD

**Issue by re-pvsr** [aws/aws-sdk-net#883]
Is it possible to limit file upload size in a Pre-signed URL in AWS S3 ?

I understand that it is possible in HTTP POST, but pre-signed urls are so much easier because the signature is generated by the SDK (I am using Java)

So, 
1. Can i set a max file size using something like Content-Length in pre-signed URL ? 
2. What is the alternative ? I understand that I can use HTTP POST but I hate the cumbersome signature generation process - wish there was a SDK generated signature process in HTTP Post - or is there ?

Many thanks for any help

**Comment by normj** [comment]
S3 does not have this support. You could possibly do it if you knew the exact file length but presigned doesn't have any sort of range support
