### ISSUE TITLE
Extend Amazon.S3.Model.ByteRange so that it supports range that is missing "start" or "end" value

### ISSUE THREAD

**Issue by eangelov** [aws/aws-sdk-net#886]
With current implementation of the ByteRange  class only range that have both start and end values can be set: bytes=500-999

According to [w3](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.35) the range can be in the following formats:
bytes=-500
bytes=9500-

**Comment by sstevenkang** [comment]
I didn't quite follow what this means:

> With current implementation of the ByteRange class only range that have both start and end values can be set: bytes=500-999

Could you clarify your question?

**Comment by eangelov** [comment]
The current implementation of the [ByteRange ](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/S3/TByteRange.html) class has only 1 constructor with 2 mandatory parameters, making the creation of a range that does not have an "end"( example: bytes=9500- ) impossible

**Comment by binsenpai** [comment]
Also would like to see this implemented. +1 from me.

**Comment by klaytaybai** [comment]
Hi @eangelov, in case you missed it, bisenpai made a pull request for this that was now submitted.

**Comment by eangelov** [comment]
Hi when are the changes made by binsenpai expected to enter the production build ?
