### ISSUE TITLE
Insufficient smallA is 2 bytes of non-cryptographic randomness instead of 128 bytes of secure randomness

### ISSUE THREAD

**Issue by timadamson** [aws/aws-sdk-net#887]
In the javascript SDK "a" is 128 bytes of cryptographically secure randomness but here it is 2 bytes from System.Random, which is not suitable for crypto:

```
        /// <summary>
        /// Return the Tuple of (A, a) for SRP
        /// </summary>
        /// <returns></returns>
        internal static Tuple<BigInteger, BigInteger> CreateAaTuple()
        {
            BigInteger a, A;
            do
            {
                a = new BigInteger(16, new Random());
                A = g.ModPow(a, N);
            } while (A.Mod(N).Equals(BigInteger.Zero));

            return Tuple.Create<BigInteger, BigInteger>(A, a);
        }
```
extensions/src/AWSSDK.Extensions.CognitoAuthentication/Util/AuthenticationHelper.cs

System.Random is also used here:
```
        internal static void GenerateDeviceSaltAndVerifier(string deviceGroupKey, string deviceKey, string password)
        {
            byte[] deviceKeyHash = GetDeviceKeyHash(deviceGroupKey, deviceKey, password);
            Random random = new Random();

            Salt = new byte[16];
            random.NextBytes(Salt);

            Verifier = CalculateVerifier(Salt, deviceKeyHash);
        }
```
/extensions/src/AWSSDK.Extensions.CognitoAuthentication/Util/CognitoDeviceHelper.cs

**Comment by sstevenkang** [comment]
We are planning on addressing this today.

**Comment by sstevenkang** [comment]
Issue has been addressed with:
https://github.com/aws/aws-sdk-net/commit/2a3d53f300975f501439498c501d6ccf42c2433c
https://github.com/aws/aws-sdk-net/commit/f6a85d66edc05300ea8767840c7bf8018ffc3891

0.9.2 of the nuget package is out here: https://www.nuget.org/packages/AWSSDK.Extensions.CognitoAuthentication/0.9.2
