### ISSUE TITLE
Kinesis Video - Empty Payload

### ISSUE THREAD

**Issue by francoisdutoit** [aws/aws-sdk-net#889]
Hi,
I'm currently able to do a GetMedia request - however - I never get any data back.
Below is the code that I am using and attached are some screenshots of my object contents after the call. 

I have checked in the AWS console and the video that I am pushing to Kinesis is showing there...
Any ideas why this could be happening? 

Thanks!

               var dataEndPoint = _videoClient.GetDataEndpoint(getDataEndpointRequest).DataEndpoint;
                var videoMediaClient = new AmazonKinesisVideoMediaClient(dataEndPoint, _credentials);

                var mediaRequest = new GetMediaRequest()
                {
                    StreamARN = _streamARN,
                    StartSelector = new StartSelector
                    {
                        StartSelectorType = StartSelectorType.EARLIEST
                    },
                };

                GetMediaResponse getMediaResponse = new GetMediaResponse();
                try
                {
                    getMediaResponse = videoMediaClient.GetMedia(mediaRequest);

                }
                catch(Exception ex)

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html
![payload1](https://user-images.githubusercontent.com/9386768/36936290-160df018-1f0c-11e8-9aa9-138a7e650170.JPG)
![payload2](https://user-images.githubusercontent.com/9386768/36936291-16739918-1f0c-11e8-994e-e08c0fc71241.JPG)

**Comment by steveataws** [comment]
Per documentation [here](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/index.html?page=KinesisVideoMedia/TGetMediaResponse.html&tocid=Amazon_KinesisVideoMedia_Model_GetMediaResponse) the content is wrapped in a stream in the response object. 

In the code you supplied I don't see any references to the payload member or reading of the stream?

**Comment by francoisdutoit** [comment]
Hi @steveataws ,

Thanks for the response :) 

So I have been debugging and checking the contents of the getMediaResponse object - and looked at the payload object (the second attached image ) .

1.) There are two exceptions.
2.) Any specific way to parse the stream - as I have tried and not getting anything back....

Thanks!

**Comment by francoisdutoit** [comment]
Hi @steveataws ,

Still - no luck... see mu code below - I am getting no bytes from the stream... n is 0 after first pass
Any ideas why?

        private void ReadStream(GetMediaResponse getMediaResponse)
        {
            var stream = getMediaResponse.Payload;

            byte[] bytes = new byte[100];
            int numBytesToRead = 100;
            int numBytesRead = 0;
            do
            {
                int n = stream.Read(bytes, numBytesRead, 10);
                numBytesRead += n;
                numBytesToRead -= n;

            } while (numBytesRead > 0);

        }

**Comment by francoisdutoit** [comment]
Got it working :)
Thanks!

**Comment by jonathanmesser** [comment]
Any chance you could help shed a little light on what you did to fix it? I'm hitting the exact same issues as your screenshots. 

```
            AmazonKinesisVideoClient videoClient = new AmazonKinesisVideoClient(credentials, Amazon.RegionEndpoint.USWest2);
            ListStreamsResponse streamsInfo = videoClient.ListStreams(new ListStreamsRequest { });
            var dataEndPoint = videoClient.GetDataEndpoint(new GetDataEndpointRequest { APIName = APIName.GET_MEDIA, StreamARN = streamsInfo.StreamInfoList[0].StreamARN }).DataEndpoint;

            AmazonKinesisVideoMediaClient videoMediaClient = new AmazonKinesisVideoMediaClient(dataEndPoint, credentials);

            GetMediaRequest mediaRequest = new GetMediaRequest();
            mediaRequest.StreamARN = streamsInfo.StreamInfoList[0].StreamARN;
            mediaRequest.StartSelector = new StartSelector { StartTimestamp = DateTime.Now.AddMinutes(-45), StartSelectorType = StartSelectorType.SERVER_TIMESTAMP };
            try
            {
                GetMediaResponse mediaResponse = videoMediaClient.GetMedia(mediaRequest);
                var stream = mediaResponse.Payload;
            }
            catch (Exception ex)
            {
                
            }
```

![kinesis_getmedia_error1](https://user-images.githubusercontent.com/43242338/45897628-48946500-bd9d-11e8-90e2-eab0e81c8790.png)
![kinesis_getmedia_error2](https://user-images.githubusercontent.com/43242338/45897629-48946500-bd9d-11e8-9209-898c9829283d.png)

**Comment by francoisdutoit** [comment]
@jonathanmesser - I have not looked at the code in a while - but the below is pretty much what I did...note you would have to deal with the exceptions...was just returning null during testing.

` _credentials = new BasicAWSCredentials(accessKeyID, secretKey);
  _videoClient = new AmazonKinesisVideoClient(_credentials, RegionEndpoint.USWest2);`

`_streamARN = ListStream().StreamInfoList[0].StreamARN;`

`        public ListStreamsResponse ListStream()
        {
            try
            {
                return _videoClient.ListStreams(new ListStreamsRequest());
            }
            catch (Exception ex)
            {
                return null;
            }

        }`

` public GetMediaResponse RetrieveMediaAsync()
        {

            try
            {
                var getDataEndpointRequest = new GetDataEndpointRequest
                {
                    APIName = "GET_MEDIA",
                    StreamARN = _streamARN,
                };

                var dataEndPoint = _videoClient.GetDataEndpoint(getDataEndpointRequest).DataEndpoint;
                var videoMediaClient = new AmazonKinesisVideoMediaClient(dataEndPoint, _credentials);

                var mediaRequest = new GetMediaRequest()
                {
                    StreamARN = _streamARN,
                    StartSelector = new StartSelector
                    {
                        StartSelectorType = StartSelectorType.EARLIEST
                    },
                };

                GetMediaResponse getMediaResponse = new GetMediaResponse();
                try
                {
                    getMediaResponse = videoMediaClient.GetMedia(mediaRequest);


                }
                catch (Exception ex)
                {

                }
                return getMediaResponse;
            }
            catch (Exception ex)
            {
                return null;
            }

        }`

**Comment by francoisdutoit** [comment]
@jonathanmesser - I have not looked at the code in a while - but the below is pretty much what I did...note you would have to deal with the exceptions...was just returning null during testing.

`	_credentials = new BasicAWSCredentials(accessKeyID, secretKey);
 	_videoClient = new AmazonKinesisVideoClient(_credentials, RegionEndpoint.USWest2);

	_streamARN = ListStream().StreamInfoList[0].StreamARN;

        public ListStreamsResponse ListStream()
        {
            try
            {
                return _videoClient.ListStreams(new ListStreamsRequest());
            }
            catch (Exception ex)
            {
                return null;
            }
        }

	public GetMediaResponse RetrieveMediaAsync()
        {
            try
            {
                var getDataEndpointRequest = new GetDataEndpointRequest
                {
                    APIName = "GET_MEDIA",
                    StreamARN = _streamARN,
                };

                var dataEndPoint = _videoClient.GetDataEndpoint(getDataEndpointRequest).DataEndpoint;
                var videoMediaClient = new AmazonKinesisVideoMediaClient(dataEndPoint, _credentials);

                var mediaRequest = new GetMediaRequest()
                {
                    StreamARN = _streamARN,
                    StartSelector = new StartSelector
                    {
                        StartSelectorType = StartSelectorType.EARLIEST
                    },
                };

                GetMediaResponse getMediaResponse = new GetMediaResponse();
                try
                {
                    getMediaResponse = videoMediaClient.GetMedia(mediaRequest);


                }
                catch (Exception ex)
                {

                }
                return getMediaResponse;
            }
            catch (Exception ex)
            {
                return null;
            }
        }`

**Comment by jonathanmesser** [comment]
Thanks @francoisdutoit - I tried with that sample and still hit the same issue.

**Comment by francoisdutoit** [comment]
The below should work...
``private string _streamARN;
        private BasicAWSCredentials _credentials;
        private AmazonKinesisVideoClient _videoClient;

        public async Task<Stream> Get()
        {
            try
            {
                var accessKeyID = "YOURKEY";
                var secretKey = "YOURSECRET";

                _credentials = new BasicAWSCredentials(accessKeyID, secretKey);
                _videoClient = new AmazonKinesisVideoClient(_credentials, RegionEndpoint.USWest2);            
                _streamARN = ListStream().StreamInfoList[2].StreamARN;


              var getDataEndpointRequest = new GetDataEndpointRequest
                {
                    APIName = "GET_MEDIA",
                    StreamARN = _streamARN,
                };

                var dataEndPoint = _videoClient.GetDataEndpoint(getDataEndpointRequest).DataEndpoint;

                var videoMediaClient = new AmazonKinesisVideoMediaClient(dataEndPoint, _credentials);

                var mediaRequest = new GetMediaRequest()
                {
                    StreamARN = _streamARN,
                    StartSelector = new StartSelector
                    {
                        StartSelectorType = StartSelectorType.NOW
                    },
                };

                GetMediaResponse getMediaResponse = new GetMediaResponse();
                getMediaResponse = await videoMediaClient.GetMediaAsync(mediaRequest);
                return getMediaResponse.Payload;
            }
            catch(Exception ex)
            {
                return null;
            }
        }

        public ListStreamsResponse ListStream()
        {
            try
            {
                return _videoClient.ListStreams(new ListStreamsRequest());
            }
            catch (Exception ex)
            {
                return null;
            }
        }``
