### ISSUE TITLE
Cryptic error message: "The connection with the server was terminated abnormally" due to permission issues on upload (ASP.Net Core)

### ISSUE THREAD

**Issue by meurig** [aws/aws-sdk-net#890]
When uploading to an S3 bucket and encountering an issue with permissions (in this case, the problem arises when setting a canned ACL, the upload works otherwise) I get a very unhelpful error message.

Original issue reported here:
https://stackoverflow.com/questions/49116483/the-connection-with-the-server-was-terminated-abnormally-when-uploading-to-to

## Expected Behavior
If the issue is with permissions, the error message should say so, instead of giving nothing to go on when debugging.

## Current Behavior
This is the error I get currently:

    Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware:Error: An unhandled exception has occurred: The write operation failed, see inner exception.
    System.IO.IOException: The write operation failed, see inner exception. ---> 
    System.Net.Http.WinHttpException: The connection with the server was 
    terminated abnormally
       --- End of inner exception stack trace ---
 
A full stack trace is available here:  https://pastebin.com/BGny5ULG

## Possible Solution
It took me lots of trial and error figure out where the real error lies (I'm still not finished). An error message telling me what the real issue is would be very useful!

## Steps to Reproduce (for bugs)
This is my code (I've starred out the bucket name for security):

    private async Task S3UploadFileAsync(string fileName, Stream stream)
    {
        using (IAmazonS3 client = new AmazonS3Client(Amazon.RegionEndpoint.EUWest2))
        {
            var uploadRequest = new TransferUtilityUploadRequest
            {
                InputStream = stream,
                BucketName = "******-*****",
                CannedACL = S3CannedACL.AuthenticatedRead,
                Key = fileName
            };
            TransferUtility fileTransferUtility = new TransferUtility(client);
            try
            {
                await fileTransferUtility.UploadAsync(uploadRequest);
            }
            catch (System.Exception e)
            {
                throw e;
            }
        }
    }

If I remove the CannedACL line, it doesn't throw an error, but the file is created without Read permission for my app. From this I've decided it's really an error to do with setting permissions.

I suspect to reproduce the issue you'd need to set up the permissions on the S3 bucket (in)correctly, but I don't know enough about the real problem to advise on how to reproduce those yet.

## Context
I'm trying to take a stream and upload it to an S3 bucket, with the ability to read it back again.

## Your Environment
* AWSSDK.Core version used: 3.3.21.6
* Service assembly and version used: AWSSDK.S3 3.3.17
* Operating System and version: Running on EC2 instance with 64bit Windows Server 2016 v1.2.0 running IIS 10.0
* Visual Studio version: VS2017 (15.5.4)
* Targeted .NET platform:  .NET Core 2.0

## .NET Core Info
* .NET Core version used for development: 2.0.0
* .NET Core version installed in the environment where application runs: 2.0.0
* Output of `dotnet --info`: 
```
    .NET Command Line Tools (2.1.4)

    Product Information:
     Version:            2.1.4
     Commit SHA-1 hash:  5e8add2190

    Runtime Environment:
     OS Name:     Windows
     OS Version:  10.0.14393
     OS Platform: Windows
     RID:         win10-x64
     Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

    Microsoft .NET Core Shared Framework Host

      Version  : 2.0.5
      Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```
* Contents of project.json/project.csproj: https://pastebin.com/hgXra2kt

**Comment by andyfurniss4** [comment]
Also experiencing this. Any news?

**Comment by AdamFrisby** [comment]
Also experiencing this.

**Comment by AdamFrisby** [comment]
I should add a post-script here, for us, upgrading to .NET Core 2.2. resolved the issue.
