### ISSUE TITLE
ListThingsAsync with attribute search does not work

### ISSUE THREAD

**Issue by anti-matter** [aws/aws-sdk-net#892]
This search for "things" for AWS IoT does not work. Note if I remove the attributes search criteria, then it works just fine (but returns too many items). I double and triple checked to ensure the attributes are set correctly on the things, it's as if ListThingsAsync() is not searching correctly.
```C#
var thingListReq = new ListThingsRequest
            {
                AttributeName = "Parent",
                AttributeValue = parentName,
                MaxResults = NumSimulatedDevices,
            };
            var things = IotClient.ListThingsAsync(thingListReq).Result.Things;
            if (things.Count < NumSimulatedDevices)
            {
                // We always get exactly 0 results from the search with 100 things provisioned!!
                return;
            }
```

## Context
I have a large number of IoT things and not being able to search for specific ones hurts.

## Your Environment

* AWSSDK.Core version used: latest
* Targeted .NET platform: .NET Core 2.0

## .NET Core Info

* .NET Core version used for development: 2.0
* .NET Core version installed in the environment where application runs: Same

**Comment by ashishdhingra** [comment]
Hi @anti-matter,

Good afternoon.

I was going through backlog and came across this issue. Could you please check if this is still an issue with latest version of AWS SDK for .NET?

Thanks,
Ashish
