### ISSUE TITLE
[S3] PutObject High Memory Usage

### ISSUE THREAD

**Issue by Singh400** [aws/aws-sdk-net#894]
Whilst under taking performance work centred around memory, we have discovered that this method:-

https://github.com/aws/aws-sdk-net/blob/9814e245e0cd9c4435a17185e866813869d427da/sdk/src/Services/S3/Generated/_bcl45/AmazonS3Client.cs#L4421

Causes LOH allocations as well as fragmentation. As we are uploading small sized images (many thousand times a day) we can't see why this should be the case. This was revealed by taking dumps of production servers and dumping out the byte arrays. The byte arrays in question contained `;chunk-signature=` with image data afterwards.

Using dotTrace we have been able to narrow down the allocations to `ChunkedUploadWrapperStream` specifically the constructor:-

https://github.com/aws/aws-sdk-net/blob/9814e245e0cd9c4435a17185e866813869d427da/sdk/src/Core/Amazon.Runtime/Internal/Util/ChunkedUploadWrapperStream.cs#L73

For every invocation of the constructor two byte arrays are created each having a minimum size of `131072`:-

https://github.com/aws/aws-sdk-net/blob/9814e245e0cd9c4435a17185e866813869d427da/sdk/src/Core/Amazon.Runtime/Internal/Util/ChunkedUploadWrapperStream.cs#L40

The threshold for objects to go onto the LOH is 85,000 bytes. We believe this is the root cause of the problem we are experiencing.

## Expected Behavior
That uploading small files doesn't cause LOH allocation and further on down the line fragmentation.

## Current Behavior
Every time you upload an image to S3 two byte arrays are created with a minimum size of 131072. This is greater than the 85,000 threshold causing both byte arrays to be allocated directly to the LOH.

## Possible Solution
There are a few possible solutions:-

1. Use [System.Buffers](http://adamsitnik.com/Array-Pool/) to have a pool of byte arrays that can be recycled.
2. Use [Microsoft.IO.RecyclableMemoryStream](http://www.philosophicalgeek.com/2015/02/06/announcing-microsoft-io-recycablememorystream/) to have a pool of MemoryStreams - we have used this to great effect in our own code to reduce LOH allocations by 99.6%.
3. Expose `DefaultChunkSize` so that consumers of the API can set it themselves
4. Lower `DefaultChunkSize` to a number that is by default lower than the LOH threshold. Microsoft use 81920 in `Stream`:- https://referencesource.microsoft.com/#mscorlib/system/io/stream.cs,50

## Steps to Reproduce (for bugs)
	using System;
	using System.IO;
	using Amazon;
	using Amazon.Runtime;
	using Amazon.S3;
	using Amazon.S3.Model;

	namespace AWS_S3_Test_Harness
	{
		public class Program
		{
			private const string _bucketName = "_bucketName";
			private const string _accessKey = "_accessKey";
			private const string _secretKey = "_secretKey";
			private static readonly BasicAWSCredentials _credentials = new BasicAWSCredentials(_accessKey, _secretKey);

			public static void Main(string[] args)
			{
				var readAllBytes = File.ReadAllBytes(@"..\..\sample_image.png"); // https://a0.awsstatic.com/main/images/logos/aws_logo_smile_1200x630.png

				for (int index = 0; index < 200; index++)
				{
					PutObject(index + ".png", new MemoryStream(readAllBytes));   
				}
			}

			private static void PutObject(string fileName, Stream fileContent)
			{
				try
				{
					using(var client = new AmazonS3Client(_credentials, RegionEndpoint.EUWest1))
					{
						var putObjectRequest = new PutObjectRequest
						{
							Timeout = TimeSpan.FromSeconds(5),
							BucketName = _bucketName,
							CannedACL = S3CannedACL.PublicRead,
							InputStream = fileContent,
							StorageClass = S3StorageClass.Standard,
							ServerSideEncryptionMethod = ServerSideEncryptionMethod.None,
							Key = "aws-s3-test-harness/" + fileName
						};

						client.PutObject(putObjectRequest);
					}
				}
				catch(Exception exception)
				{
					Console.WriteLine(exception);
				}
			}
		}
	}

## Context
Our platform provides an API in which our customers can send us images. We then transform and upload these images to S3. We receive many thousands of images per hour.

## Your Environment

* AWSSDK.Core version used: 3.3.21.15
* Service assembly and version used: 3.3.17.1
* Operating System and version: Windows Server 2012 R2 6.3 Build 9600
* Visual Studio version:  2015 Professional Update 3
* Targeted .NET platform: 4.5.2

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by Singh400** [comment]
I realise I didn't add any statistics to my opening post. The test harness in the opening post uses [this image ](https://a0.awsstatic.com/main/images/logos/aws_logo_smile_1200x630.png) and just uploads it 200 times via:-

https://github.com/aws/aws-sdk-net/blob/9814e245e0cd9c4435a17185e866813869d427da/sdk/src/Services/S3/Generated/_bcl45/AmazonS3Client.cs#L4421

**Total .NET Allocations**: 114MB
**SOH Allocations**: 64MB
**LOH Allocations**: 50MB

![all_calls](https://user-images.githubusercontent.com/1906778/37242730-585697ae-2466-11e8-9ac2-67bf61d8b200.png)

And then if we drill down into one call to `PutObject`:-

![single_call](https://user-images.githubusercontent.com/1906778/37242748-7835bbf4-2466-11e8-8eb2-08fef519b77c.png)

It looks like every call to `PutObject` has a fixed cost of `0.3 MB`. I'm happy to submit to PR that lowers `DefaultChunkSize` to `81920` if it is welcome.

Thanks,
Indy

**Comment by Singh400** [comment]
I made the change (https://github.com/Singh400/aws-sdk-net/commit/008c5ff4198f03aa76095a9ebc5bfc5aa81497dc) locally and complied the need projects in release and re-ran my test harness:-

**Total .NET Allocations**: 98MB
**SOH Allocations**: 98MB
**LOH Allocations**: 0.4MB

![all_calls](https://user-images.githubusercontent.com/1906778/37255269-c1035f5e-2541-11e8-846b-491c78b5ba04.png)

And then if we drill down into one call to `PutObject`:-

![single_call](https://user-images.githubusercontent.com/1906778/37255271-c908812a-2541-11e8-8ca3-d700b81a99f8.png)

Thanks,
Indy

**Comment by Singh400** [comment]
This bug was fixed and released in [AWSSDK.Core 3.3.21.19](https://github.com/aws/aws-sdk-net/pull/899#issuecomment-377350277)

Core Version | Total RAM | Small Object Heap | Large Object Heap
------------ | ------------- | ------------- | -------------
v3.3.21.18 | 116 MB | 66 MB | 50 MB
v3.3.21.19 | 99 MB | 98 MB | 0.4 MB

Incidentally, `GetPreSignedURL` offers much better performance memory wise:-

https://github.com/aws/aws-sdk-net/blob/37b2546044248de151a6ce47641ba096728fb5cb/sdk/src/Services/S3/Custom/_bcl%2Bcoreclr%2Bpcl/AmazonS3Client.Extensions.cs#L81

Total RAM | Small Object Heap | Large Object Heap
------------- | ------------- | -------------
32 MB | 32 MB | 0.4 MB

Thanks for fixing this bug. Closing.

Cheers,
Indy

**Comment by rsrini83** [comment]
HI Indy-Singh,
We are observing the similar behavior(99% RAM usage) when uploading 100+ GB file using TransferUtility.  We are using AWS Core 3.3.8 version(little old). However i just want to understand is it the same issue or am i facing different issue ? 

System Configuration;
OS: Windows 2012 R2
RAM: 16 GB
Usage: 15.6 GB
AWS Core: 3.3.8

--Srinu

**Comment by indy-singh** [comment]
@rsrini83 I would update to the latest version of AWS Core and try again.

**Comment by indy-singh** [comment]
Microsoft broke https://referencesource.microsoft.com/#mscorlib/system/io/stream.cs,50 the now correct location is https://github.com/microsoft/referencesource/blob/f7df9e2399ecd273e90908ac11caf1433e142448/mscorlib/system/io/stream.cs#L53
