### ISSUE TITLE
s3 throw when call GetObjectAsync(GetObjectRequest)

### ISSUE THREAD

**Issue by benzsuankularb** [aws/aws-sdk-net#897]
Throw 
`Unhandled Exception: System.AggregateException: One or more errors occurred. (Operation is not supported on this platform.)`
when call `client.GetObjectAsync(GetObjectRequest)` in S3Client

## Expected Behavior
It shouldn't have any error

## Current Behavior

It's throw me
> Unhandled Exception: System.AggregateException: One or more errors occurred. (Operation is not supported on this platform.) ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
>    at System.Security.Cryptography.KeyedHashAlgorithm.Create(String algName)
>    at Amazon.Util.CryptoUtilFactory.CryptoUtil.HMACSign(Byte[] data, String key, SigningAlgorithm algorithmName)
>    at Amazon.Runtime.Internal.Auth.S3Signer.SignRequest(IRequest request, RequestMetrics metrics, String awsAccessKeyId, String awsSecretAccessKey)
>    at Amazon.Runtime.Internal.Signer.SignRequest(IRequestContext requestContext)
>    at Amazon.Runtime.Internal.Signer.PreInvoke(IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.Signer.InvokeAsync[T](IExecutionContext executionContext)
>    at Amazon.Runtime.Internal.CredentialsRetriever.<InvokeAsync>d__0`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Amazon.Runtime.Internal.RetryHandler.<InvokeAsync>d__0`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__0`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Amazon.Runtime.Internal.CallbackHandler.<InvokeAsync>d__0`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Amazon.S3.Internal.AmazonS3ExceptionHandler.<InvokeAsync>d__0`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Amazon.Runtime.Internal.ErrorCallbackHandler.<InvokeAsync>d__0`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Amazon.Runtime.Internal.MetricsHandler.<InvokeAsync>d__0`1.MoveNext()
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)

## Possible Solution
Don't know but quite sure it's about dependencies.
The stacktrace throw at System.Security.Cryptography.KeyedHashAlgorithm

## .NET Core Info

Dependencies
![screen shot 2561-03-12 at 03 15 49](https://user-images.githubusercontent.com/2444351/37258008-bd5bc064-25a3-11e8-948b-5033d7958608.png)

> .NET Command Line Tools (2.1.4)
> 
> Product Information:
>  Version:            2.1.4
>  Commit SHA-1 hash:  5e8add2190
> 
> Runtime Environment:
>  OS Name:     Mac OS X
>  OS Version:  10.13
>  OS Platform: Darwin
>  RID:         osx.10.12-x64
>  Base Path:   /usr/local/share/dotnet/sdk/2.1.4/
> 
> Microsoft .NET Core Shared Framework Host
> 
>   Version  : 2.0.5
>   Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54

**Comment by gagandeepp** [comment]
benzsuankularb  is this still open?

**Comment by gagandeepp** [comment]
can you please share your code base?

**Comment by benzsuankularb** [comment]
Hmm, I'm not with those codes now and didn't remember if I get it worked at that time.
So sorry.
