### ISSUE TITLE
Is AppSync available for Xamarin?

### ISSUE THREAD

**Issue by johnchoicl** [aws/aws-sdk-net#901]
I was just wondering is AWS AppSync is available for Xamarin PCL or Xamarin.iOS/Xamarin.Android?
I kinda see the code but are they just placeholders for now?
Github : https://github.com/aws/aws-sdk-net/tree/master/sdk/src/Services/AppSync

Then how come there's Nuget project?
Nuget : https://www.nuget.org/packages/AWSSDK.AppSync

If this is meant to work, please confirm it for me. I really couldn't find any sample snippet or app on Google but hopefully I will be able to work it out myself as long as this is "meant" to work. 
Thanks in advance!

**Comment by codegrue** [comment]
Is there a sample project for AppSync in Xamarin?

**Comment by aherrick** [comment]
Anyone make any progress with this? Looking for an update. Thanks!

**Comment by tsilenzio** [comment]
Any updates on this? I would like to use this in a project I am working on, thank you!

**Comment by fadulalla** [comment]
I've done all my server-side stuff (schema, data sources... etc) only to find out there's nothing about appsync on xamarin 😞 .. I probably should have checked availability before embarking!

Would be nice to get an official word/update on it :)

**Comment by muellerfr** [comment]
Hello @johnchoicl,

I have added this as a feature request in our backlog and have submitted it to the team for prioritization. I do not have specific timeline that I can share at this point. We will let you know, either on this thread, or through a forum announcement when the feature is released in the SDK

**Comment by BryanGerre** [comment]
@johnchoicl Thanks for adding this. Any progress so far?

**Comment by muellerfr** [comment]
@BryanGerre,

Unfortunately, there's no update to report yet.

**Comment by flusharcade** [comment]
Hey all, just letting you know that the AppSync client is currently in development, will have an update on dates for release soon.

**Comment by BryanGerre** [comment]
Awesome!

**Comment by muellerfr** [comment]
@BryanGerre, who is Flush Arcade? Where did this email come from?

**Comment by BryanGerre** [comment]
Not sure Git blanked out the email I assumed it was someone in your organization. When I reply it posts to the appropriate git

**Comment by muellerfr** [comment]
Not sure where this came from. I have no update on an AppSync client for Xamarin.

**Comment by NeuronKarrde** [comment]
Is there any news about AppSync for Xamarin? So now, using AmazonAppSyncClient, we can work with appsync service(create, update, delete functions, tables, query), but no any way just to launch query?

**Comment by SOliasS** [comment]
> Are there any news about AppSync for Xamarin? So now, using AmazonAppSyncClient, we can work with appsync service(create, update, delete functions, tables, query), but no any way just to launch query?

Is AppSync now working for Xamarin?

**Comment by NeilBostrom** [comment]
+1 for AppSync GraphQL client for .NET SDK.

For those trying to do this manually today, I have a [gist available](https://gist.github.com/NeilBostrom/cab8b9275e39bb90ecf8e06ab980664b) that shows using the built-in [AWS4Signer](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/Internal/Auth/AWS4Signer.cs) to access an AppSync GraphQL endpoint using [GraphQL .NET client](https://github.com/graphql-dotnet/graphql-client) protected by [AWS_IAM authorization](https://docs.aws.amazon.com/appsync/latest/devguide/security.html).

**Comment by philipogorman** [comment]
+1 I'm also really interested in seeing a sample xamarin or dotnetcore example application

**Comment by niraj-bpsoftware** [comment]
+1

**Comment by ltaljaard** [comment]
+1

**Comment by tenninebt** [comment]
+1

**Comment by ltaljaard** [comment]
@muellerfr Hi, how can we find out whether a Xamarin version is in the pipeline, and an indication of when it might come out? If there are no such plans, how can we go about it to get it on the radar? I for one think that Xamarin support would have the potential to bring a significant user base over from MS Azure (Mobile Apps which also supports offline sync) to AWS AppSync. This is the only reason that we are still on Azure - all our UI code is done in Xamarin.

**Comment by FreakyAli** [comment]
+1

**Comment by klaytaybai** [comment]
As part of our [platform consolidation project](https://github.com/aws/aws-sdk-net/projects/1), Xamarin components are being archived.   [Xamarin users hoping to utilize AWS AppSync](https://github.com/aws/aws-sdk-net/issues/1346) should use the .NET SDK targeted to .NET Standard 2.0.

**Comment by philipogorman** [comment]
@klaytaybai does the  .NET Standard 2.0 AWS .NET SDK have examples for AppSync? Thanks

**Comment by ltaljaard** [comment]
Ok but can you release a sample Xamarin app that uses it so that we can see how it should be done?

**Comment by Mikilll94** [comment]
Any update on this? Could you provide a sample project for AppSync with Xamarin?

**Comment by philipogorman** [comment]
I have been in contact with aws support about this, this is what they sent me:

To sync the data between the client and server you can push data to your AppSync data source using mutations [1]. With AppSync subscriptions, you can get updates to the data back in real time whenever a mutation is performed [2]. 

There is currently no .NET SDK which can be used for interacting with your AppSync API, but calls to AppSync can be made over internet using a HTTP client. Therefore, you can leverage HTTP requests to make queries and mutations over internet. Subscriptions in AppSync need a Websocket connection and operate like a normal graphQL subscription [3].  I do not have a C# code example for subscriptions, but I have attached a great document (AppSyncwscat.docx) that shows how to connect to your AppSync real time endpoint using wscat, which I think you may find useful. You can try to use that example to change the logic and adapt it for whatever SDK you are using. 

With regards to AWS .Net SDK with AppSync libraries, there is currently a feature request open for an AWS .Net SDK with AppSync libraries, but there is no timeline available for when this will be released. Although there is no timeline available for an AWS .Net SDK with AppSync libraries, please note that AppSync can be used from any SDK that has GraphQL capabilities. 


===References===
[1] Mutations: https://docs.aws.amazon.com/appsync/latest/devguide/quickstart-write-queries.html#add-data-with-a-graphql-mutation 
[2] Real-Time Data: https://docs.aws.amazon.com/appsync/latest/devguide/real-time-data.html 
[3] Subscriptions: https://graphql-dotnet.github.io/docs/getting-started/subscriptions/ 
[AppSyncwscat.docx](https://github.com/aws/aws-sdk-net/files/4635208/AppSyncwscat.docx)

**Comment by Dids** [comment]
So why are there NuGet packages for both AppSync and Amplify, if neither are supported in C#/.NET?

The very existence of these packages, combined with the fact that they're actively maintained/new versions get released, it all just seems highly confusing, especially as the official documentation seems to be all over the place regarding this too.

**Comment by henry-delgado** [comment]
just singing to the choir... any support on Xamarin for AppSync? Having to create work arounds but not too successful yet :)

**Comment by haideralifaheem** [comment]
Any Updates please,anytime line for AppSync in Xamarin

**Comment by ppittle** [comment]
Similar issue tracking adding support AppSync/Amplify

**Comment by hunanniu** [comment]
We will address this request in the ticket mentioned by @ppittle
