### ISSUE TITLE
FromAttributeMap fail to map object with Map properties. 

### ISSUE THREAD

**Issue by kabzit13** [aws/aws-sdk-net#903]
Hi. 
I one of my lambda functions reacting on events in DynamoDb. I need to get data from new image. 
But when I am trying to convert NewImage to Document I am finding that all Map fields (Sub-documents) are now DynamoDBNull. 

I was not able to find any other way how to convert Dictionary<string, AttributeValue> to Document or to POCO directly.

## Expected Behavior

Document.FromAttributeMap should create a document with all sub-documents. 

## Current Behavior

Currently when using Document.FromAttributeMap on DynamoDb stream event record, that contains record with complex documents (that contains Map fields), new Documents will have DynamoDbNull value objects on all map fields.

## Possible Solution

I have checked that adding additional check will solve it. But maybe I don't know about all cases.

 Amazon.DynamoDBv2.DocumentModel.Document
```
private static bool TryToDynamoDBNull(AttributeValue attributeValue, out DynamoDBNull ddbNull)
        {
            ddbNull = null;
            if (attributeValue.IsSetNULL() && attributeValue.NULL)
            {
                ddbNull = new DynamoDBNull();
            }
            return (ddbNull != null);
        }
```

## Context

Trying to map DynamoDbEvent record to POCO. After it I wont to use objects properties for my business logic

## Your Environment

* AWSSDK.Core version used:  3.3.19
* Service assembly and version used: AWSSDK.DynamoDBv2 (3.3.4.3)
* Operating System and version: Lambda, same behavior in local unit-tests on Windows 10
* Visual Studio version: 15.5.2
* Targeted .NET platform: netcore1.0

## .NET Core Info

* .NET Core version used for development: 1.0
* .NET Core version installed in the environment where application runs: 1.1.7
* Output of `dotnet --info`: 

.NET Command Line Tools (1.1.7)

Product Information:
 Version:            1.1.7
 Commit SHA-1 hash:  263223c7b2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.1.7
* Contents of project.json/project.csproj: 
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.0</TargetFramework>
    <AssemblyName>General.Notifier</AssemblyName>
    <OutputTypeEx>Exe</OutputTypeEx>
    <PackageId>General.Notifier</PackageId>
    <PackageTargetFallback>$(PackageTargetFallback);dnxcore50</PackageTargetFallback>
    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <GenerateAssemblyDescriptionAttribute>false</GenerateAssemblyDescriptionAttribute>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GenerateAssemblyCopyrightAttribute>false</GenerateAssemblyCopyrightAttribute>
    <GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
    <GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
    <PreserveCompilationContext>false</PreserveCompilationContext>
    <ApplicationIcon />
    <OutputType>Library</OutputType>
    <StartupObject />
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <WarningsAsErrors />
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.DynamoDBEvents" Version="1.0.1" />
    <PackageReference Include="AutoMapper" Version="6.1.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="2.0.1" />
    <PackageReference Include="AWSSDK.SimpleEmail" Version="3.3.3" />
    <PackageReference Include="AWSSDK.S3" Version="3.3.14" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="1.1.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="1.1.2" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.3.3" />
    <PackageReference Include="Amazon.Lambda.Core" Version="1.0.0" />
    <PackageReference Include="Amazon.Lambda.Serialization.Json" Version="1.1.0" />
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer" Version="0.9.0-preview1" />
    <PackageReference Include="Amazon.Lambda.Logging.AspNetCore" Version="1.1.0" />
    <PackageReference Include="NETStandard.Library" Version="1.6.0" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Amazon.Lambda.Tools" Version="1.8.0" />
  </ItemGroup>

</Project>
```

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by sstevenkang** [comment]
Could you share with us what the event looks like?

**Comment by kabzit13** [comment]
I have found what cause such behavior. 
We have a handler which gets DynamoDBEvent as on of params. 
To test this functionality, I have serialized with Amazon.Lambda.Serialization.Json.JsonSerializer and logged event that i have received from DynamoDb.  

It was looks like this:
{
    "Records": [
        {
            "EventSourceArn": "arn:aws:dynamodb:us-east-1:********:table/Dev-Aggregator-OrderInfo/stream/2018-01-09T15:52:14.296",
            "AwsRegion": "us-east-1",
            "Dynamodb": {
                "ApproximateCreationDateTime": "2018-03-23T10:19:00Z",
                "Keys": {
                    "Id": {
                        "B": null,
                        "BOOL": false,
                        "IsBOOLSet": false,
                        "BS": [],
                        "L": [],
                        "IsLSet": false,
                        "M": {},
                        "IsMSet": false,
                        "N": null,
                        "NS": [],
                        "NULL": false,
                        "S": "0045-00045-18-00016",
                        "SS": []
                    }
                },
                "NewImage": {
                    "Campaign": {
                        "B": null,
                        "BOOL": false,
                        "IsBOOLSet": false,
                        "BS": [],
                        "L": [],
                        "IsLSet": false,
                        "M": {
                            "DistributorId": {
                                "B": null,
                                "BOOL": false,
                                "IsBOOLSet": false,
                                "BS": [],
                                "L": [],
                                "IsLSet": false,
                                "M": {},
                                "IsMSet": false,
                                "N": "5",
                                "NS": [],
                                "NULL": false,
                                "S": null,
                                "SS": []
                            },
                            "Id": {
                                "B": null,
                                "BOOL": false,
                                "IsBOOLSet": false,
                                "BS": [],
                                "L": [],
                                "IsLSet": false,
                                "M": {},
                                "IsMSet": false,
                                "N": "1",
                                "NS": [],
                                "NULL": false,
                                "S": null,
                                "SS": []
                            },
                            "ProgramId": {
                                "B": null,
                                "BOOL": false,
                                "IsBOOLSet": false,
                                "BS": [],
                                "L": [],
                                "IsLSet": false,
                                "M": {},
                                "IsMSet": false,
                                "N": "5",
                                "NS": [],
                                "NULL": false,
                                "S": null,
                                "SS": []
                            },
                            "BusinessUnitNumber": {
                                "B": null,
                                "BOOL": false,
                                "IsBOOLSet": false,
                                "BS": [],
                                "L": [],
                                "IsLSet": false,
                                "M": {},
                                "IsMSet": false,
                                "N": null,
                                "NS": [],
                                "NULL": false,
                                "S": "B10248948",
                                "SS": []
                            }
                        },
                        "IsMSet": true,
                        "N": null,
                        "NS": [],
                        "NULL": false,
                        "S": null,
                        "SS": []
                    },
                    "Id": {
                        "B": null,
                        "BOOL": false,
                        "IsBOOLSet": false,
                        "BS": [],
                        "L": [],
                        "IsLSet": false,
                        "M": {},
                        "IsMSet": false,
                        "N": null,
                        "NS": [],
                        "NULL": false,
                        "S": "0045-00045-18-00016",
                        "SS": []
                    }
                },
                "OldImage": {
                    "Campaign": {
                        "B": null,
                        "BOOL": false,
                        "IsBOOLSet": false,
                        "BS": [],
                        "L": [],
                        "IsLSet": false,
                        "M": {
                            "DistributorId": {
                                "B": null,
                                "BOOL": false,
                                "IsBOOLSet": false,
                                "BS": [],
                                "L": [],
                                "IsLSet": false,
                                "M": {},
                                "IsMSet": false,
                                "N": "6",
                                "NS": [],
                                "NULL": false,
                                "S": null,
                                "SS": []
                            },
                            "Id": {
                                "B": null,
                                "BOOL": false,
                                "IsBOOLSet": false,
                                "BS": [],
                                "L": [],
                                "IsLSet": false,
                                "M": {},
                                "IsMSet": false,
                                "N": "1",
                                "NS": [],
                                "NULL": false,
                                "S": null,
                                "SS": []
                            },
                            "ProgramId": {
                                "B": null,
                                "BOOL": false,
                                "IsBOOLSet": false,
                                "BS": [],
                                "L": [],
                                "IsLSet": false,
                                "M": {},
                                "IsMSet": false,
                                "N": "5",
                                "NS": [],
                                "NULL": false,
                                "S": null,
                                "SS": []
                            },
                            "BusinessUnitNumber": {
                                "B": null,
                                "BOOL": false,
                                "IsBOOLSet": false,
                                "BS": [],
                                "L": [],
                                "IsLSet": false,
                                "M": {},
                                "IsMSet": false,
                                "N": null,
                                "NS": [],
                                "NULL": false,
                                "S": "B10248948",
                                "SS": []
                            }
                        },
                        "IsMSet": true,
                        "N": null,
                        "NS": [],
                        "NULL": false,
                        "S": null,
                        "SS": []
                    },
                    "Id": {
                        "B": null,
                        "BOOL": false,
                        "IsBOOLSet": false,
                        "BS": [],
                        "L": [],
                        "IsLSet": false,
                        "M": {},
                        "IsMSet": false,
                        "N": null,
                        "NS": [],
                        "NULL": false,
                        "S": "0045-00045-18-00016",
                        "SS": []
                    }
                },
                "SequenceNumber": "440465700000000050221105786",
                "SizeBytes": 1496,
                "StreamViewType": {
                    "Value": "NEW_AND_OLD_IMAGES"
                }
            },
            "EventID": "b2ff2db6752fa08336375217e5565d51",
            "EventName": {
                "Value": "MODIFY"
            },
            "EventSource": "aws:dynamodb",
            "EventVersion": "1.1",
            "UserIdentity": null
        }
    ]
}

And then I used such event for unit tests and for test event in lambda console. 

Then I have found to get real event I should get data from stream not from DynamoDBEvent object. 
So maybe Amazon.Lambda.Serialization.Json.JsonSerializer should serialize to same format as stream have before converting to DynamoDBEvent. 
If not, then this issue could be closed. 

Thanks and sorry for bothering.

**Comment by kabzit13** [comment]
`{
    "Records": [
        {
            "EventSourceArn": "arn:aws:dynamodb:us-east-1:********:table/Dev-Aggregator-OrderInfo/stream/2018-01-09T15:52:14.296",
            "AwsRegion": "us-east-1",
            "Dynamodb": {
                "ApproximateCreationDateTime": "2018-03-23T10:19:00Z",
                "Keys": {
                    "Id": {
                        "B": null,
                        "BOOL": false,
                        "IsBOOLSet": false,
                        "BS": [],
                        "L": [],
                        "IsLSet": false,
                        "M": {},
                        "IsMSet": false,
                        "N": null,
                        "NS": [],
                        "NULL": false,
                        "S": "0045-00045-18-00016",
                        "SS": []
                    }
                },
                "NewImage": {
                    "Campaign": {
                        "B": null,
                        "BOOL": false,
                        "IsBOOLSet": false,
                        "BS": [],
                        "L": [],
                        "IsLSet": false,
                        "M": {
                            "DistributorId": {
                                "B": null,
                                "BOOL": false,
                                "IsBOOLSet": false,
                                "BS": [],
                                "L": [],
                                "IsLSet": false,
                                "M": {},
                                "IsMSet": false,
                                "N": "5",
                                "NS": [],
                                "NULL": false,
                                "S": null,
                                "SS": []
                            },
                            "Id": {
                                "B": null,
                                "BOOL": false,
                                "IsBOOLSet": false,
                                "BS": [],
                                "L": [],
                                "IsLSet": false,
                                "M": {},
                                "IsMSet": false,
                                "N": "1",
                                "NS": [],
                                "NULL": false,
                                "S": null,
                                "SS": []
                            },
                            "ProgramId": {
                                "B": null,
                                "BOOL": false,
                                "IsBOOLSet": false,
                                "BS": [],
                                "L": [],
                                "IsLSet": false,
                                "M": {},
                                "IsMSet": false,
                                "N": "5",
                                "NS": [],
                                "NULL": false,
                                "S": null,
                                "SS": []
                            },
                            "BusinessUnitNumber": {
                                "B": null,
                                "BOOL": false,
                                "IsBOOLSet": false,
                                "BS": [],
                                "L": [],
                                "IsLSet": false,
                                "M": {},
                                "IsMSet": false,
                                "N": null,
                                "NS": [],
                                "NULL": false,
                                "S": "B10248948",
                                "SS": []
                            }
                        },
                        "IsMSet": true,
                        "N": null,
                        "NS": [],
                        "NULL": false,
                        "S": null,
                        "SS": []
                    },
                    "Id": {
                        "B": null,
                        "BOOL": false,
                        "IsBOOLSet": false,
                        "BS": [],
                        "L": [],
                        "IsLSet": false,
                        "M": {},
                        "IsMSet": false,
                        "N": null,
                        "NS": [],
                        "NULL": false,
                        "S": "0045-00045-18-00016",
                        "SS": []
                    }
                },
                "OldImage": {
                    "Campaign": {
                        "B": null,
                        "BOOL": false,
                        "IsBOOLSet": false,
                        "BS": [],
                        "L": [],
                        "IsLSet": false,
                        "M": {
                            "DistributorId": {
                                "B": null,
                                "BOOL": false,
                                "IsBOOLSet": false,
                                "BS": [],
                                "L": [],
                                "IsLSet": false,
                                "M": {},
                                "IsMSet": false,
                                "N": "6",
                                "NS": [],
                                "NULL": false,
                                "S": null,
                                "SS": []
                            },
                            "Id": {
                                "B": null,
                                "BOOL": false,
                                "IsBOOLSet": false,
                                "BS": [],
                                "L": [],
                                "IsLSet": false,
                                "M": {},
                                "IsMSet": false,
                                "N": "1",
                                "NS": [],
                                "NULL": false,
                                "S": null,
                                "SS": []
                            },
                            "ProgramId": {
                                "B": null,
                                "BOOL": false,
                                "IsBOOLSet": false,
                                "BS": [],
                                "L": [],
                                "IsLSet": false,
                                "M": {},
                                "IsMSet": false,
                                "N": "5",
                                "NS": [],
                                "NULL": false,
                                "S": null,
                                "SS": []
                            },
                            "BusinessUnitNumber": {
                                "B": null,
                                "BOOL": false,
                                "IsBOOLSet": false,
                                "BS": [],
                                "L": [],
                                "IsLSet": false,
                                "M": {},
                                "IsMSet": false,
                                "N": null,
                                "NS": [],
                                "NULL": false,
                                "S": "B10248948",
                                "SS": []
                            }
                        },
                        "IsMSet": true,
                        "N": null,
                        "NS": [],
                        "NULL": false,
                        "S": null,
                        "SS": []
                    },
                    "Id": {
                        "B": null,
                        "BOOL": false,
                        "IsBOOLSet": false,
                        "BS": [],
                        "L": [],
                        "IsLSet": false,
                        "M": {},
                        "IsMSet": false,
                        "N": null,
                        "NS": [],
                        "NULL": false,
                        "S": "0045-00045-18-00016",
                        "SS": []
                    }
                },
                "SequenceNumber": "440465700000000050221105786",
                "SizeBytes": 1496,
                "StreamViewType": {
                    "Value": "NEW_AND_OLD_IMAGES"
                }
            },
            "EventID": "b2ff2db6752fa08336375217e5565d51",
            "EventName": {
                "Value": "MODIFY"
            },
            "EventSource": "aws:dynamodb",
            "EventVersion": "1.1",
            "UserIdentity": null
        }
    ]
}`
