### ISSUE TITLE
AWS CostExplorerClient getting a error with The remote name could not be resolved: 'ce.us-west-2.amazonaws.com'

### ISSUE THREAD

**Issue by Mehtach** [aws/aws-sdk-net#905]
string StartDate = "2018-03-03";
                string EndDate = "2018-03-20";
                Amazon.CostExplorer.AmazonCostExplorerClient clientExplorer = new AmazonCostExplorerClient();
                Amazon.CostExplorer.Model.DateInterval DateTimePeriod = new Amazon.CostExplorer.Model.DateInterval();
                DateTimePeriod.Start = StartDate;
                DateTimePeriod.End = EndDate;                
                Amazon.CostExplorer.Model.GetTagsRequest tag = new Amazon.CostExplorer.Model.GetTagsRequest();
                tag.NextPageToken = null;
                tag.SearchString = null;
                tag.TagKey = "tag";
                tag.TimePeriod = DateTimePeriod;
                var getTag = clientExplorer.GetTags(tag); -> getting exception 
![amazonerror](https://user-images.githubusercontent.com/37617349/37703385-874a6b0e-2d1b-11e8-985a-8585f8eed4b0.png)

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by Singh400** [comment]
According to https://docs.aws.amazon.com/general/latest/gr/rande.html#billing_region only https://ce.us-east-1.amazonaws.com is available for AWS Cost Explorer.

**Comment by sstevenkang** [comment]
Yup.  AWS Cost Explorer is only available on us-east-1.

**Comment by Mehtach** [comment]
Thanks, It worked by changing the region to us-east-1.
Does it mean that resources created in other regions will not list here?
