### ISSUE TITLE
Include XML Documentation on NuGet Packages

### ISSUE THREAD

**Issue by mateusaubin** [aws/aws-sdk-net#91]
This should be a quickie...

When downloading the AWS SDK from http://aws.amazon.com/sdkfornet/ the package contains a XML file with the documentation for the whole DLL.

However the NuGet package doesn't contains such file, causing the whole documentation to be missing.

It would be great to have it attached to the NuGet package.

Thanks.

**Comment by normj** [comment]
In the new modularized NuGet packages the XML file is included. Check this blog post for further information.
