### ISSUE TITLE
Cannot configure the AWS account

### ISSUE THREAD

**Issue by tupq** [aws/aws-sdk-net#911]
I tried to add a aws IAM user to aws explorer in visual studio 2017 but this error always occurs : 

---------------------------
Error loading AWS profiles: Method not found: 'System.Threading.Tasks.Task`1<System.Collections.Generic.Dictionary`2<System.String,System.String>> Amazon.Runtime.SharedInterfaces.ICoreAmazonSQS.GetAttributesAsync(System.String)'.
---------------------------

Here's my steps 

- I created an account in the AWS IAM Management Console.
- I assigned this account AdministratorAccess and created access keys.
- I installed the AWS SDK for .NET for Visual Studio 2017.
- In the Visual Studio AWS Explorer, I selected and created a New Account Profile. 
- When I  "Save & Close" the error occurs

I don't know what am I missing? Let me know if you need more information.

**Comment by steveataws** [comment]
Do you by any chance have the Visual Studio PowerShell Tools extension installed, along with the AWS Tools for Windows PowerShell module?

We have had reports that this can lead to a conflict in loaded AWS SDK modules; the toolkit uses the SDK assemblies built for .NET 4.5, whereas our PowerShell module uses SDK assemblies built with .NET 3.5 which do not contain the new task based async apis. If the 3.5 modules get loaded first then it's possible for this error to occur.

Let us know your setup so we can confirm and find a solution or investigate further?

**Comment by tupq** [comment]
Thank steveataws,
The cause of the issue is the same as you figure out, I uninstall the extension and it works now.
