### ISSUE TITLE
AWS Toolkit for Visual Studio 2017 - Publishing Docker configuration to Elastic Beanstalk Docker Worker

### ISSUE THREAD

**Issue by Pelias2525** [aws/aws-sdk-net#912]
I am creating an application that deploys to an Elastic Beanstalk Worker instance to perform background processing of long running tasks. I would like to use the 'Publish to AWS Elastic Beanstalk' plugin for Visual Studio to publish this Docker image. As of now, there is no way to specify additional files to include in the uploaded package. 

Because this is a Worker environment, I have the requirement to deploy to Linux. Linux based Docker instances require that the Dockerfile be included in the deployment package. Since the plugin does not account for this, it requires that the Dockerfile be added by hand after the publication has occurred and re-uploading the modified package.

In addition, Worker environments running activity timers require that the cronjob.config file be included in a .ebextensions folder in the deployment package. Once again, without the ability to flag files for inclusion in the package, one is left hand editing the package and then re-uploading. 

My expectation is that the developer would have a way to identify additional resources to be included in the deployment package uploaded to Elastic Beanstalk. 

Traditionally the 'Copy to Output Directory' file property in Visual Studio has been used to identify files to be included during publication. Any ability for the developer to specify these files, even a flat file whitelist, would greatly improve the current deployment headache.

**Comment by Pelias2525** [comment]
I am utilizing a [Beanstalk Worker Environment](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features-managing-env-tiers.html) for a number of reasons:

1) I have adopted Beanstalk to remove the need to manage my own EC2 resources and provide dynamic scaling based on workload.
2) I looked into adopting the Serverless Lambda functionality for background processing; but would need to utilize [Fargate](https://docs.aws.amazon.com/toolkit-for-visual-studio/latest/user-guide/deployment-ecs-aspnetcore-fargate.html) to allow long running processes. My current deployment is in US-West2....which is not supported by Fargate, so that option is out...
3) The Beanstalk Worker environment represents an optimal implementation for me, allowing external environments (such as websites) to add activities onto the built in message queue for the background process to handle asyncronously. This, plus the built in timer support, is so much more efficient than creating a Windows service to sit on an EC2 instance and churn, doing nothing 90% of the time and heavy processing 10% of the time.

The tooling is wonderful and (at least from my perspective) would need slight modifications to allow for this use case. I see that there is [some need](https://github.com/aws/aws-sdk-net/issues/821) for this type of functionality by others and would love to see the tooling grow to support Beanstalk Workers.

**Comment by Pelias2525** [comment]
Do you know if/when there will be Fargate support for US-West-2?

**Comment by normj** [comment]
1) I know the Fargate team is planning on region expansion rollout but I don't know when, hopefully soon!

2) Beanstalk is a great service for having your AWS resources be managed for you like you noted above and we will continue to rely on it in the toolkit as our primary way of deploying web applications and we hope to expand on its capabilities even more. We have just started building our container support in the toolkit and there are lot more things we would like to do with it. Container support is a bit more free form then just web applications or a worker role which give a lot of flexibility but does have more things for you to manage, although Fargate does reduce that a lot. 

One of the features we have been debating about with our container support is in the first page of the container publish wizard where you select an ECS service or ECS task is also include Beanstalk's docker based solution stack as options as well. Which I think would solve your needs. That would give users like yourself the ability to do Container deployments but take advantage of Beanstalks ability to manage your AWS resources. Would that make your life easier?

**Comment by Pelias2525** [comment]
Yes, that would help; honestly right now there are so many options for deploying applications to AWS that it can be a bit overwhelming. 

Currently in my production environment I am running a single EC2 instance running a Windows service that takes care of all background processing. 

When I started looking into deploying a task based application to AWS, Serverless Lambda functions seemed like the way to go. After spending 2 days looking into that technology and wrapping my head around .NET Core examples, I was ready to begin implementation. It wasn't until I was ready to publish that I hit the wall of [Fargate not supporting my region](https://aws.amazon.com/about-aws/whats-new/2017/11/introducing-aws-fargate-a-technology-to-run-containers-without-managing-infrastructure/) and as well as [weak static file support](https://github.com/aws/aws-lambda-dotnet/issues/250).

Since I was already deploying web applications through Beanstalk I decided to look into workers to solve my use cases, only to find that applications could only be deployed to Linux; I then hit the brick wall of "why doesn't my deployment work" when publishing. Two trouble tickets later I determine that it is due to the tooling not including the necessary files to make my deployment function. 

Its been a frustrating week, and I still don't feel as though I have an end-to-end solution. 
I really like the direction that AWS is heading and am just trying to find the right technology to suit my needs.

**Comment by fernandojs** [comment]
@Pelias2525  

I'm in the same situation here.
EB Worker environment is the best choice for my background applications, but I cannot deploy at now.

**Comment by Pelias2525** [comment]
Not getting any traction on this thread. Hopefully the issue can be addressed soon.

**Comment by normj** [comment]
Sorry I haven't had time to dedicate to this feature. Having people chime in asking for this feature does help me push to get this prioritized.

**Comment by fernandojs** [comment]
@Pelias2525 Could you write a simple tutorial "how run docker in EB Worker"?

@normj I appreciate your help.

**Comment by Pelias2525** [comment]
@fernandojs 
Once you have published to the Elastic Beanstalk, you'll need to go to the 'Application Versions' page for that environment and download the package that was just published. Then copy the DockerFile from your Visual Studio project into the root of the downloaded zip file and then 'Upload and Deploy' that modified package. The worker environment should restart, find the dockerfile and successfully initialize. This needs to be done EVERY TIME you perform a publish. Depending on what you're doing with your worker, you may need to copy additional files into the root of the zip file, such as the .ebextensions folder.

**Comment by fernandojs** [comment]
@Pelias2525 I tried follow these steps, but is not works, because when I published the application to EB Worker all libraries and dependencies were compiled in Visual Studio before the upload, then in the zip file just have the dll's, however my DockerFile find the csproj files to build the container, like that:

`FROM microsoft/aspnetcore:2.0 AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/aspnetcore-build:2.0 AS build
WORKDIR /src
COPY DownloaderAspNetCore/DownloaderAspNetCore.csproj DownloaderAspNetCore/
COPY Priceio.Dto/Priceio.Dto.csproj Priceio.Dto/
RUN dotnet restore DownloaderAspNetCore/DownloaderAspNetCore.csproj
COPY . .
WORKDIR /src/DownloaderAspNetCore
RUN dotnet build DownloaderAspNetCore.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish DownloaderAspNetCore.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "DownloaderAspNetCore.dll"]
`

**Comment by Pelias2525** [comment]
@fernandojs 
My docker file just grabs the already compiled files from the publish folder

FROM microsoft/dotnet:2.1-aspnetcore-runtime
ARG source
WORKDIR /app
EXPOSE 80
COPY ${source:-obj/Docker/publish} .
ENTRYPOINT ["dotnet", "xxxx.dll"]
