### ISSUE TITLE
Server Side Encryption with .NET SDK - "S3FileInfo" Class

### ISSUE THREAD

**Issue by kuldeepmarganache** [aws/aws-sdk-net#914]
I didn't come across any documentation if S3FileInfo supports SSE related parameters. Please clarify.

Ref: https://docs.aws.amazon.com/sdkfornet/latest/apidocs/items/TS3IOS3FileInfoNET45.html 

I was looking for an option where "S3FileInfo" class can provide an option to pass the Server Side Encryption related parameters similar to "PutObjectRequest". My goal is to be able to use the following methods from S3FileInfo class with Server Side Encryption. 
1. MoveTo(S3FileInfo)
2. Replace(S3FileInfo, S3FileInfo)

Request you to provide any information if this is supported currently. If not I would like to request this feature in S3FileInfo class.

**Comment by ocdavison** [comment]
I would definitely love to see this feature added. Thx!
