### ISSUE TITLE
Xamarin: CognitoSyncManger class missing again

### ISSUE THREAD

**Issue by niraj-bpsoftware** [aws/aws-sdk-net#916]
## Expected Behavior
CognitoSyncManager should be available in latest AWSSDK stable nugget packages.

## Current Behavior
CognitoSyncManager is gone again in AWSSDK.CognitoSync 3.3.1.29, AWSSDK Core (3.3.21.20). Is there any other class we are supposed to use now?

![image](https://user-images.githubusercontent.com/37313526/38280372-3f9d00c8-37e8-11e8-9b8e-5f37306c933c.png)

## Possible Solution
Please suggest alternative to CognitoSyncManager or add SyncManager

## Your Environment

![image](https://user-images.githubusercontent.com/37313526/38279486-e218b522-37e3-11e8-9df5-abd6c9f8e003.png)

* AWSSDK.Core version used: 3.3.21.20
* Visual Studio version: 2017
* Targeted .NET platform: 1.3

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by niraj-bpsoftware** [comment]
@sstevenkang ...please let me know if you have any update. Thank You.

**Comment by niraj-bpsoftware** [comment]
Hi @sstevenkang @normj 
The CognitoSyncManager is in portable class version which is what AWSSDK use for Xamarin. The .NET Standard version does not have the CogntioSyncManager. However it should be available for .NET Standard version as well.

**Comment by sstevenkang** [comment]
Hi, the existing CognitoSyncManager is written targetting PCL.  We need to do the work to port this for .NET Standard.  Currently we don't have any plans to support this feature yet.
