### ISSUE TITLE
Add CognitoIdentityProvider for Unity

### ISSUE THREAD

**Issue by danieldownes** [aws/aws-sdk-net#918]
For some reason the CognitoIdentityProvider project is not included for Unity and may help to make User Pools accessible when adding in AWSSDK.Extensions.CognitoAuthentication.

**Comment by jemgal** [comment]
when i call StartWithSrpAuthAsync method in a unity C# script it doesnt return a response, this could be beacause of the fact that is not supported in unity?

**Comment by taylorECD** [comment]
@jemgal Did you ever get anywhere with this issue? I'm getting the same result with StartWithSrpAuthAsync() in Unity 2018.2.0f2. No errors, warnings, results, exceptions, the code stops being executed at that line. No way to debug at this point either. I made a couple posts trying to identify the problem at the aws-sdk-net gitter and unity forums

**Comment by Raeion** [comment]
any updates?
