### ISSUE TITLE
S3 operations not working. Not able to fetch credentials from IAM role attached to docker container using AWS SDK .NET CORE

### ISSUE THREAD

**Issue by sumanthupadhya** [aws/aws-sdk-net#920]
## Expected Behavior
Fetch or any crud operations for AWS S3 should work using IAM roles attached to the instance. 
 

## Current Behavior
It is failing when trying to get all s3 objects or upload a simple file to S3.
throws the error as shown below.
I have followed the steps of using AWSSDK.Extensions.NETCore.Setup and dependency injection for the .net core but it is showing the below error attached is the stack trace.

[Stack trace.txt](https://github.com/aws/aws-sdk-net/files/1890521/Stack.trace.txt)

 
## Steps to Reproduce (for bugs)
Attached is a sample .net core application which I have tried and is having the same issue for replication.
[TestS3_Files.zip](https://github.com/aws/aws-sdk-net/files/1890557/TestS3_Files.zip)

## Your Environment

* AWSSDK.Extensions.NETCore.Setup version used: **3.3.5**
* AWSSDK.S3: **3.3.18**
* Operating System and version: Linux Container hosted in Marathon 
* Visual Studio version: 2017 Professional
* Targeted .NET platform: .Net Core 2.0

## .NET Core Info

* .NET Core version used for development:  **2.0**
* .NET Core version installed in the environment where application runs:  **runs on docker image microsoft/aspnetcore-build:1.0-2.0**
* Output of `dotnet --info`:  ![dotnet info](https://user-images.githubusercontent.com/27328785/38507710-da03e0cc-3c3a-11e8-8ad6-80b2645a51aa.png)

 

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by sstevenkang** [comment]
Is the `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` environment variable set in your container?

**Comment by sumanthupadhya** [comment]
No, it is not set. 
the container is not running in ECS. It's running in an AWS Linux box managed by MESOS and Marathon.

Can you help me with how to add this value in .net core application? and what this URI contains?

**Comment by sumanthupadhya** [comment]
What value we need to set for **AWS_CONTAINER_CREDENTIALS_RELATIVE_URI** ?? IAM Role Name ? or ARN?

**Comment by sstevenkang** [comment]
When you say a linux box, do you mean an ec2 instance?  If so, is IMDS running?  Could you check with the command `wget http://169.254.169.254/latest/meta-data/iam/security-credentials/`.

If the host you are running is not an ec2 instance, then you need to manually set the IAM role credentials  as described in the [README.md](https://github.com/mesosphere/aws-cli).

**Comment by sumanthupadhya** [comment]
We are running on ec2 instances and we already have java based applications which are running fine with the IAM Roles.
Only the C# .NET Sdk is having the above-mentioned issue

**Comment by sstevenkang** [comment]
I am confused, what did you mean in the title "Not able to fetch credentials from IAM role attached to docker container"?

**Comment by sumanthupadhya** [comment]
We are using Continuous Delivery with Docker on MESOS. The docker containers that are running currently are having IAM role attached. 
Other applications that are using JAVA & Python SDK's are able to get the credentials when we create an S3Client object.
for .Net core sdk it is failing with the error attached with this issue.  
if we specify access key and secret keys explicitly things work, but ideally we should not do this and the credentials should be picked up automatically from IAM Role like other SDK's.

**Comment by sstevenkang** [comment]
We've re-implemented existing instance profile credentials [here](https://github.com/aws/aws-sdk-net/commit/ade50e7562d6df9b3fb72a11f4db44a4f74c05c4).  This change should be available in the latest release of [AWSSDK.Core](https://www.nuget.org/packages/AWSSDK.Core/3.3.24).

**Comment by vellozzi** [comment]
Assuming the fix worked.
Closing due to lack of response.

**Comment by sumanthupadhya** [comment]
Yes, the latest re-implementation has fixed the issue. Thank you.
