### ISSUE TITLE
DownloadDBLogFilePortion often fails 

### ISSUE THREAD

**Issue by mjdaly** [aws/aws-sdk-net#921]
DownloadDBLogFilePortion often fails with error `This file contains binary data and should be downloaded instead of viewed`. 

Support recommend using [DownloadCompleteDBLogFile](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_LogAccess.html#DownloadCompleteDBLogFile).

## Expected Behavior
DownloadCompleteDBLogFile method can be called from `AmazonRDSClient`

## Current Behavior
DownloadDBLogFilePortion can fail due to:
1. too many API calls 
1. binary data in file.

## Possible Solution
Add DownloadCompleteDBLogFile method to `AmazonRDSClient`

## Your Environment

* AWSSDK.Core version used: 3.3.2
* Service assembly and version used: 3.3.2
* Operating System and version: Win 10
* Visual Studio version: 2017
* Targeted .NET platform: .NET Core 2.0

**Comment by sstevenkang** [comment]
What's the exception or error message you get?

**Comment by mjdaly** [comment]
**Error Message**
> This file contains binary data and should be downloaded instead of viewed.

I don't have a full stack trace from the production log.

This error has been documented multiple times on other API wrappers:

- https://github.com/aws/aws-cli/issues/2400
- https://github.com/aws/aws-cli/issues/2268
- https://github.com/boto/botocore/issues/910
- https://stackoverflow.com/a/37051952/1057567

**Comment by sstevenkang** [comment]
This looks like a service side problem. I would open a support ticket against RDS. I don't think there's a whole lot we can do in the SDK.
