### ISSUE TITLE
ListTrainingJobs LastModifiedTimeAfter filter not filtering properly

### ISSUE THREAD

**Issue by AirWrek** [aws/aws-sdk-net#926]
Using the LastModifiedTimeAfter filter option in the ListTrainingJobsRequest is returning all jobs including those which were last modified before the time passed

## Expected Behavior
Using the LastModifiedTimeAfter filter option in the ListTrainingJobsRequest should return just those jobs that have been last modified after that value.

## Current Behavior
Using the LastModifiedTimeAfter filter option in the ListTrainingJobsRequest is returning jobs before the filter value, seems as though it is being ignored.  Checking with CreationTimeAfter gives expected results.

## Steps to Reproduce (for bugs)
`           SM.AmazonSageMakerClient client = new SM.AmazonSageMakerClient(credentials);
            SM.Model.ListTrainingJobsRequest request = new SM.Model.ListTrainingJobsRequest {
                LastModifiedTimeAfter = DateTime.UtcNow.AddDays(-1)
            };
            SM.Model.ListTrainingJobsResponse response = client.ListTrainingJobs(request);
`

In my case returns 19 job summaries, most of which were last modified before a day ago.  Switching from LastModifiedTimeAfter to CreationTimeAfter returns just 1 (as expected).

## Your Environment

* AWSSDK.Core version used: v3.3.21.19
* Service assembly and version used: v3.3.4
* Operating System and version: windows 10 pro
* Visual Studio version: Visual Studio Professional 2017 15.6.6
* Targeted .NET platform: 4.5.2

**Comment by ashishdhingra** [comment]
Hi @AirWrek,

Good afternoon.

I was going through backlog and came across this issue. Could you please check if this is still an issue with latest version of AWS SDK for .NET?

Thanks,
Ashish
