### ISSUE TITLE
Header keys need to be considered as case insensitive

### ISSUE THREAD

**Issue by vadmeste** [aws/aws-sdk-net#927]
AWS SDK .NET needs to consider header keys as case insensitive as HTTP RFC says: http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

```
Each header field consists of a name followed by a colon (":") and the 
field value. Field names are case-insensitive.
```

It would be great of this can be fixed as done in AWS SDK java: https://github.com/aws/aws-sdk-java/pull/1016

**Comment by normj** [comment]
This has been fixed as part of version 3.7.103.7 of AWSSDK.S3
