### ISSUE TITLE
[Request for Clarification] Resource APIs Roadmap

### ISSUE THREAD

**Issue by pingzing** [aws/aws-sdk-net#929]
Hi! We're working in a .NET Core environment, and are using SNS for push notifications. We generate a lot of topics, and have a long-running, periodic task to clear them out when we get too close to the limit. This is hampered by the forced-paginated nature of the SDK. In my search for a better way, I discovered an old blog post from 2014, and a preview release of the AWS Resource APIs https://github.com/aws/aws-sdk-net/tree/resourceAPI-preview that allowed consumption of paginated APIs in an `IEnumerator`-like fashion.

Combined with a dash of `Parallel.ForEach`, this resulted in very fast, easy-to-read code, when compared to the using the paginated APIs.

Unfortunately, the old preview releases are .NET 4.5 only. Are there any intentions of moving forward with the Resource APIs, or releasing a version of them that supports .NET Core?

Thanks!

**Comment by sstevenkang** [comment]
We are aware of this gap.  However, there's nothing that we can share publicly at this point.
