### ISSUE TITLE
AWS Toolkit 2017 with multiple VS Studio 2017 instances

### ISSUE THREAD

**Issue by seroche** [aws/aws-sdk-net#930]
Hi Guys, 

I have an issue with the latest version of the AWS Toolkit for VS 2017 Community. 

Whenever, I open several instances of VS I get the following error message: 

> Error loading AWS profiles: The process cannot access the file '<path the my credentials>' because it is being used by another process

![image](https://user-images.githubusercontent.com/12636347/38718445-c46fc43c-3f1f-11e8-8cb5-d5a359c16b8b.png)

This pop-up will appear at least 10 times when using multiple instance of VS 2017.

After disabling AWS Toolkit extensions, this message goes away. If I remember correctly my scenario was working correctly not so long ago.

Any idea?

**Comment by steveataws** [comment]
Thanks for letting us know. I'm not sure as to the root cause yet, as that credential file is only opened in read-only mode by the toolkit, but we will take a look and see what recent changes may have caused the change in behavior.

**Comment by seroche** [comment]
Did you manage to reproduce the issue? If yes, Is there an ETA on this one? 
This bug is driving me nuts!

**Comment by normj** [comment]
We made some changes in the area of the code a couple months back. Can you let us know if you are still seeing this error?

**Comment by billycc** [comment]
i have version 1.14.5.0 of the aws toolkit extension, from 11/26, and vs community 2017 15.9.4.

i just got the message.

i have 2 sln's open, one with 5 projects, the second with 29 projects. the message came up about 5 times after i opened the second sln. i closed the second sln (29 projects) and re-opened it, and I got the message once. also, perhaps noteworthy, the "toolkit_artifact_guid" key in the credentials file changes during sln open.

i closed out the 1st sln and re-opened it, and got the popup more than 7 times before i gave up and killed vs. toolkit_artifact_guid changed many times during sln open.

**Comment by awschristou** [comment]
Hello @seroche and @billycc  - We recently released version 1.15.2.1 of the Toolkit, which contained improvements to reduce locking contention on the shared credentials files. Could you please let us know if you still get the "Error loading AWS profiles" message with this version?

**Comment by billycc** [comment]
@awschristou it appears to be fixed for me. i tried opening multiple heavy SLNs in vs2017 and did not get the credentials popup at all.

**Comment by billycc** [comment]
spoke too soon. overnight several instances of vs2017 crashed + restarted themselves. and i've got at least four windows of the original error message: 

> Error loading AWS profiles: The process cannot access the file 'C:\Users\Billy\.aws\credentials' because it is being used by another process.

Also, vs is very keen to warn me that the AWS Toolkit is causing seconds of unresponsiveness.

And, one of my restarted vs instances suggests that AWS Toolkit may have caused whatever crash.
