### ISSUE TITLE
Setting CacheControl causes PutObjectAsync to throw exception

### ISSUE THREAD

**Issue by TommyN** [aws/aws-sdk-net#931]
I have a ASP.NET Core 2.0 application where I try to set the Cache Header for a file that I upload to S3.
I want to set it to: "max-age=300,must-revalidate"

The following code fails:
```
putRequest.Headers.CacheControl = "max-age=300,must-revalidate";
```
with a very unhelpful error message:
```
Exception thrown: 'Amazon.S3.AmazonS3Exception' in System.Private.CoreLib.dll
The request signature we calculated does not match the signature you provided. 
Check your key and signing method.
```

Omitting the ",must-revalidate" part works.
Example:
```
putRequest.Headers.CacheControl = "max-age=300";
```

## Steps to Reproduce

Write code to upload a file to S3 and set .CacheControl to "max-age=300,must-revalidate";
Example:
```
var client = new AmazonS3Client();
var mstream = new MemoryStream(Encoding.UTF8.GetBytes("{}"))
PutObjectRequest putRequest = new PutObjectRequest
{
    BucketName = "mybucket",
    Key = "my_empty_json_file",
    InputStream = mstream,
    AutoCloseStream = false,
    ContentType = "application/json; charset=utf-8",
    CannedACL = S3CannedACL.PublicRead
};

putRequest.Headers.CacheControl = "max-age=300,must-revalidate";

PutObjectResponse response = await client.PutObjectAsync(putRequest);
```

## Environment

* AWSSDK.Core version used: 3.3.18
* Operating System and version: Windows 10
* Visual Studio version: 15.6
* Targeted .NET platform: .Net Core 2.0

## .NET Core Info

```
.NET Command Line Tools (2.1.100)

Product Information:
 Version:            2.1.100
 Commit SHA-1 hash:  b9e74c6520

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.100\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

**Comment by sstevenkang** [comment]
Does the workaround in https://github.com/aws/aws-sdk-net/issues/823 applicable in this case?

**Comment by sstevenkang** [comment]
Great that the workaround work for you.  This is an S3 issue that we can't really do much about in the SDK. :(

**Comment by rhysstubbs** [comment]
(sorry for the comment but it may help someone else)

Using v3 of the AWS .NET library I was trying to add the `Cache-Control` header to objects I was persisting.

Note that it _would not_ work with the following:

```c#
putRequest.Headers.CacheControl = "public, max-age=31622400";
```

But _would_ work with:

```c#
putRequest.Headers.CacheControl = "public,max-age=31622400";
```
