### ISSUE TITLE
Release notes on the GitHub releases?

### ISSUE THREAD

**Issue by winzig** [aws/aws-sdk-net#939]
The [releases page](https://github.com/aws/aws-sdk-net/releases) typically has comments that are not illuminating (e.g. "Commit version number update changes"):

<img width="449" alt="screen shot 2018-04-25 at 3 50 18 pm" src="https://user-images.githubusercontent.com/127062/39276973-5f4b5014-48a0-11e8-89fc-706ecb3a4439.png">

The [CHANGELOG](https://github.com/aws/aws-sdk-net/blob/master/SDK.CHANGELOG.md) has good release notes, but it's quite large and you have to go digging for it when a new release comes out. 

It would be extremely helpful if the notes for the latest release could be included in the git release itself. Not only does it make the releases page more useful, but you can actually [subscribe to a feed of  GitHub releases](https://github.com/aws/aws-sdk-net/releases.atom) by adding `.atom` to the end of the URL, and if the release notes were included instead of "Commit version number update changes," then one wouldn't need to go looking elsewhere for the change info.

**Comment by winzig** [comment]
Would like to keep this open.

**Comment by dscpinheiro** [comment]
It took a while, but we're now publishing the changelog details as GitHub releases as well:

![gh-release](https://github.com/user-attachments/assets/1b9fce10-d854-43e9-be61-e8715e8c3de6)
