### ISSUE TITLE
DateTime.Now in the session state provider

### ISSUE THREAD

**Issue by ldsenow** [aws/aws-sdk-net#94]
Hi,

I am in a research to use DynamoDB as our session state store. I found that it compares the session expiry by using DateTime.Now not DateTime.UtcNow. It means we need to make sure all our web servers are using the same timezone. I think we can avoid this by saving expiry date in UTC and comparing with UTC.

Cheers,
Ld

**Comment by normj** [comment]
Closing as the session provider has moved to its own repository

https://github.com/aws/aws-dotnet-session-provider
