### ISSUE TITLE
New IConfigurationProvider Extension for SSM Parameter Store

### ISSUE THREAD

**Issue by KenHundley** [aws/aws-sdk-net#940]
Hi AWS team,

I have created an implementation of Microsoft.Extensions.Configuration.IConfigurationProvider with SSM Parameter store as the backing data source. This can be added to the array of configuration providers at the startup of an Asp.Net Core app, allowing you to get your configuration values from SSM in addition to json files, environment variables, etc.

This enhancement seems like it would fit very nicely into this project under the "extensions" section, but I wanted to see if this submission is something you would be interested in before I took the time to fork and add all the necessary updates to fit it into this project.

The basic use looks like:
```
.ConfigureAppConfiguration((hostingContext, configBuilder) =>
{
    configBuilder.AddJsonFile("appsettings.json", true, true);
    configBuilder.AddEnvironmentVariables();

    var config = configBuilder.Build();
    configBuilder.AddAmazonSimpleSystemsManagement(source =>
    {
        source.AwsOptions = config.GetAWSOptions();
        source.Prefix = "/app/environment/etc"; //or config["SSM:Prefix"], etc.
        source.ReloadAfter = TimeSpan.FromHours(1); //optional
    });
})
```

Let me know and I will work on this over the weekend.

**Comment by normj** [comment]
Agreed, that would be a great extension to have. It is something we have talked about doing but haven't been able to find time. Do you have a repo I can check out?

**Comment by KenHundley** [comment]
not yet, just local development, but I can can easily upload a copy later tonight when I get home

**Comment by KenHundley** [comment]
Hi @normj,

Check out: [This sample code](https://github.com/KenHundley/Amazon.Extensions.Configuration.AmazonSimpleSystemsManagement)

It's fully functional and the extension classes should ideally only need some cleanup, exception handling, and xml comments updates.

Before you run it you should run the following commands to insert the needed SSM Params:
```
aws ssm put-parameter --name "/myapp/dev/applicationsettings/settingsssmplain" --value "FromSSM-Plain" --type String --overwrite
aws ssm put-parameter --name "/myapp/dev/applicationsettings/settingsssmsecured" --value "FromSSM-Secured" --type SecureString --overwrite
```
If you have input or concerns just let me know.

**Comment by KenHundley** [comment]
Also, I'm pretty sure I can create a version of this for the new Secrects Manager service. I'll look at that over the next few days.

**Comment by KenHundley** [comment]
Hey @normj,

Let me know if you are satisfied with the example code and overall structure I will move forward

**Comment by normj** [comment]
@KenHundley I haven't forgotten about this. I'm just away at a conference right now. Once I'm back in the office I'll take sometime to dive into it.

**Comment by normj** [comment]
The code looks good, just a couple feedback items.

1) SSM at some point changed their name from Amazon Simple System Management to AWS Systems Manager. Any place you use the full name you should use AWS System Manager as their is little to no references anymore on the AWS website for the old name.

2) The configuration in the Program.cs seems overly complicated. I wonder if a SSM configuration specific extension method on IWebHostBuilder would make it more intuitive to use.

**Comment by KenHundley** [comment]
1. I definitely don't mind changing the name, but just to point it out, it'll be inconsistent with both the SDK that it's based around and the classes in that SDK. 
    - IAmazonSimpleSystemsManagement
    - AWSSDK.SimpleSystemsManagement
2. I gave the most complex version to demonstrate all the available options. 
    The simplest config extension being
    ```csharp
    builder.AddAmazonSimpleSystemsManagement(awsOptionsFactory, prefix)
    ```
    However, as I'm writing this I realized I can add an extension that implicitly creates the AWSOptions object getting it down to this simplest form
    ```csharp
    .ConfigureAppConfiguration((hostingContext, configBuilder) =>
    {
        configBuilder.AddAWSSystemManager(prefix)
    }
    ```


It seems like you are good with the overall concept and design (with a couple exceptions), so if you agree I'll start incorporating it into the existing extensions code, and we can make adjustments as needed. Agree?

**Comment by KenHundley** [comment]
@normj Can you help answer a question about `AWSOptions` for me?

I'm using a `ChangeToken` to initiate a reload of the parameters on a user defined scheduled. This allows the extension to work with `IOptionsSnapshot`. However, I have a question about this. Is it safe to create the `AWSOptions` object once on startup and continue to use it hours/days/weeks/months to create instances of the `IAmazonSimpleSystemsManagement` service for retrieval of the latest parameters? Or should I create a new `AWSOptions` each time I'm initiating a retrieval of the parameters? I'm really most concerned here when it comes to things like Assume Role where the credentials will expire after a time. 

I think it's the former, but any input would be nice.

**Comment by KenHundley** [comment]
One more quick question. 
For the name change do you prefer:
```csharp
builder.AddAWSSystemManager(prefix);
``` 
or 
```csharp
builder.AddAWSSystemManagerParameterStore(prefix);
```
Personally I think the second is to long, but wanted to ask since I'm making the necessary changes

**Comment by normj** [comment]
If the values for AWSOptions are changing I think you would want to create a new one instance and a new instance of the service client. In the case of Assume Role if the profile specified for the AWSOptions is an Assume Role profile it will take care of refreshing the credentials before they expire.

For the name change I prefer.  

```csharp
builder.AddAWSSystemsManager(prefix);
```
Note, the system part is pluralized in the service name. AWS System**s** Manager.

**Comment by KenHundley** [comment]
Closing this question since it's actively being worked on
