### ISSUE TITLE
Cannot Install AWS Tools for VS 2017

### ISSUE THREAD

**Issue by mcoles-thortech** [aws/aws-sdk-net#942]
AWS Tools for VS 2017 install is failing

## Expected Behavior
With VS 2017 already installed, I expect AWS Tools for VS 2017 to install successfully.

## Current Behavior
With VS 2017 already installed, the AWS Tools for VS 2017 installer fails to install with the message "The installation was unable to install the extension to all the selected products.... This extension is not installable on any currently installed products."

## Possible Solution
Fix the installer.

## Steps to Reproduce (for bugs)
Install VS 2017 Enterprise. Run the AWS Tools for VS 2017 installer.

## Context
Yes it affected me. I am trying to develop against AWS using VS.

## Your Environment
Windows 10
Visual Studio 2017 Enterprise

**Comment by steveataws** [comment]
Can I assume you're the same user as reported a problem on the VS marketplace? I was about to respond there with an invitation to post the install log here or report it direct to Microsoft (it's their installer and they have looked at these issues before and made fixes).

Our only requirement, listed in the manifest for our package, is the 'core editor' (ie the core IDE itself). We have had other users report issues when multiple different editions of the 2017 IDE have been installed, or previews of upcoming releases. In these cases after forwarding the logs to Microsoft they've found and fixed the relevant issue in the vsixinstaller.

Do you only have Enterprise installed, or are other editions (Community, Professional, BuildTools) installed side by side? Is it the current GA of Enterprise or are you running one of the preview releases?

To help us help further, can you post the vsixinstaller log output into the issue?

**Comment by mcoles-thortech** [comment]
I did a full uninstall and reinstall of VS 2017 Enterprise and re-ran the AWS Toolkit installer, and the install succeeded this time.

**Comment by steveataws** [comment]
Good to know you are up and running; do you happen to have a copy of the install log from the first failed install attempt?

**Comment by mcoles-thortech** [comment]
Thanks for the response. Yes, I am the same user. Unfortunately before reinstalling VS 2017 I cleared out my temp directories, so not able to supply the failed logs. I only have VS 2017 Enterprise installed on this one -- no other versions of VS at this time. It is the current release of VS 2017, version 15.6.7.
