### ISSUE TITLE
ServicePointManager does not work with AWSSDK

### ISSUE THREAD

**Issue by VenkateshSrini** [aws/aws-sdk-net#944]
We are using .NET core 2.0. We would want to list objects from an S3 bucket. The S3 instance has SSL related issue and we would want our code to ignore the same. In .NET core 2.0 ServicePointManager has been introduced. So ideally the code is like below
```
ServicePointManager.ServerCertificateValidationCallBack=(s,c,ch,ssl)=>true; 
using (var client = AmazonClient(...))
{
}
```
But even after doing this the SSL validation is not bypassed. Is their any other way to get this working

## Expected Behavior
SSL validation should be bypassed

## Current Behavior
SSL validation is not by passed and we are getting an security error

## Steps to Reproduce (for bugs)
any normal instance with a self signed certificate

## Context
Unable to use AWSSD in .NET core 2.0

## Your Environment

* AWSSDK.Core version used: 3.3.18.2
* Service assembly and version used: 
* Operating System and version: windows 7
* Visual Studio version: VS 2017 
* Targeted .NET platform: .NET core 2.0

## .NET Core Info

* .NET Core version used for development: .NET core 2.0
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 2.0.2
* Contents of project.json/project.csproj: <<Cannot provide owing to NDA>>

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by normj** [comment]
This is a .NET Core issue and how HttpClient and ServicePointManager work together. You can reduce this with this code sample that doesn't use our SDK to see that it doesn't work.

```csharp
using System;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;

namespace ServiceCallbackTest
{
    class Program
    {
        static void Main(string[] args)
        {
            Test().Wait();
        }

        static async Task Test()
        {
            ServicePointManager.ServerCertificateValidationCallback = (s, c, ch, ssl) =>
            {
                Console.WriteLine("Got callback");
                return true;
            };

            using (var client = new HttpClient())
            {
                var content = await client.GetStringAsync("https://aws.amazon.com/");
                Console.WriteLine("Got Content");
            }
        }
    }
}
```

To do what you want you would have to add a callback to the HttpClientHandler passed into the HttpClient. But right now we don't expose the HttpClient used by the SDK to do that type of manipulation and we don't intend to leak that out of our abstraction layer right now.

**Comment by VenkateshSrini** [comment]
@normj ,
Thanks for your help. I have raised this in corefx repo also. Meanwhile I would like to highlight a scenario. We are working on .NET core projects big time. We have a local installation of S3 with not so proper SSL certificate which results in SSL Error. Just because AWSSDK does not support a feature to skip SSL validation we are unable to consume this SDK from .NET core

Yes not exposing HttpClient is good strategy. But at least you need to expose an property like validateSSL that will skip this validation

**Comment by VenkateshSrini** [comment]
Hi All,

Just wanted to update the solution to this problem. Recent version of AWS SDK we have an option to set an http factory that is inherited from AWS.Runtime.HttpFactory. In that there is a method called CreateHttpClient. We need to use that and then create a custom factory and set the same in AWS client config instance while creating Amazon S3 client. That way we have control to set SSL options via HTTP client handler.

**Comment by niraj-bpsoftware** [comment]
Hi @VenkateshSrini ,
Thanks for the update. We are experiencing similar kind of issue. Would you mind providing some sample code that highlights your fix?
Thanks.

**Comment by VenkateshSrini** [comment]
Hi Niraj,
Please see the code @https://github.com/VenkateshSrini/S3SSSSLFactory
