### ISSUE TITLE
ScanConditions not working with type N values

### ISSUE THREAD

**Issue by niraj-bpsoftware** [aws/aws-sdk-net#945]
When I try to filter on int data types (type N for dynamodb) for any attribute, DynamoDBContext.ScanAsync doesn't filter values. 
for e.g., 
   conditions.Add(new ScanCondition("Processed", ScanOperator.NotEqual,"1"));
above condition will not filter out records with Processed flag to 1.

However, as soon as I change type of "Processed" attribute to string (type S for dynamodb), query works fine.

I have noticed this behavior for ScanOperator.NotEqual, ScanOperator.Equal. Not sure if issue is related to ScanOperator or related to ScanCondition in general.

## Your Environment

* AWSSDK.Core version used: 3.3.22.3
* Visual Studio version: VS 2017
* Targeted .NET platform: 4.6.1

## .NET Core Info

* .NET Core version used for development: 2.0

**Comment by normj** [comment]
Can you provide a code sample reproducing the problem? Here is my code that I wrote to attempt to reproduce the problem but it worked correctly and the scan only return back 1 of the 2 items.

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Amazon;
using Amazon.DynamoDBv2;
using Amazon.DynamoDBv2.DocumentModel;
using Amazon.DynamoDBv2.DataModel;

namespace ScanTest
{
    class Program
    {
        static DynamoDBContext _context = new DynamoDBContext(RegionEndpoint.USEast1);
        static void Main(string[] args)
        {
            _context.Save<People>(new People { Id = "1", Name = "Lewis", Age = 9 });
            _context.Save<People>(new People { Id = "2", Name = "Frida", Age = 7 });

            var people = _context.Scan<People>(new ScanCondition("Age", ScanOperator.NotEqual, 7));
            foreach(var person in people)
            {
                Console.WriteLine(person.Name);
            }
        }
    }

    public class People
    {
        public string Id { get; set; }

        public string Name { get; set; }

        public int Age { get; set; }
    }
}
```

**Comment by niraj-bpsoftware** [comment]
Hi @normj ,
I think I was doing something wrong as It's working fine now. Thank you for checking out.
Regards,
Niraj Bhatt
