### ISSUE TITLE
Unable to implement Custom Aws ConfigBuilder (.NET 4.7.1) because of dependency of AWSSDK from ConfigurationManager

### ISSUE THREAD

**Issue by alex-valchuk** [aws/aws-sdk-net#946]
## Expected Behavior

Starting from Autumn 2017 .NET 4.7.1 provides a possibility to create custom **configuration builders**.
A link to new feature: https://github.com/aspnet/MicrosoftConfigurationBuilders#implementing-more-keyvalue-config-builders

I would like to create one for reading secrets from **AWSSecretsManager** and register it in my Web/App.config file. 

## Current Behavior

Unfortunately while initializing a new instance of **AmazonSecretsManagerClient** inside my custom config builder class **AWS SDK** throws an exception. 
The reason for it is that it has strict dependency from **ConfigurationManager** class.

## Possible Solution

It would be nice to have a possibility to inject a config reader to **AmazonSecretsManagerClient** constructor or to somewhere else to avoid coupling with .Net **ConfigurationManager**

## Steps to Reproduce (for bugs)

1. Create custom config builder to read from AWS and register it in App/Web.config
2. Specify *configBuilders="AwsCustomConfigBuider"* for **appSettings** tag in App/Web.config
3. Call *ConfigurationManager.AppSettings["someKey"]* somewhere in your code

## Your Environment

* AWSSDK.Core.Net45, AWSSDK.SecretsManager.Net45, ConfigurationManager, Microsoft Configuration Builders
* Windows 2010
* Visual Studio 2017
* .NET Framework 4.7.1

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by normj** [comment]
That is going to be a tricky to untangle from ConfigurationManager in a non breaking way. This is unfortunate because it is a really cool feature you are attempting to add.

**Comment by alex-valchuk** [comment]
Thank you Norm for the answer.
Happy to let you know about it

**Comment by JeffRausch** [comment]
I would love to have this as well, tried to get it working and ran into this same issue and found this thread.  
I don't know all the inner workings of the AWS client code but maybe something similar to how Microsoft did their AzureKeyVaultConfigBuilder to access the Azure Key Vault.  Potentially have an AWSParameterStoreConfigBuilder that could take in the settings normally in AppSettings (AWSProfileName, AWSProfilesLocation, AccessKey, SecretKey, etc.) and when this ConfigBuilder is used the client knows to skip looking at the AppSettings for these values.

[MicrosoftConfigBuilders code (see **AzureKeyVaultConfigBuilder** heading)](https://github.com/aspnet/MicrosoftConfigurationBuilders)
[ConfigBuilder announced (see **Secure Configuration with Azure Key Vault** heading)](https://blogs.msdn.microsoft.com/webdev/2017/11/17/announcing-net-4-7-1-tools-for-the-cloud/)

**Comment by sureshpala** [comment]
I am also facing the similar issue...are there any alternatives for this?

**Comment by alex-valchuk** [comment]
> I am also facing the similar issue...are there any alternatives for this?

Hi sureshpala,

The alternative for me was a full implementation of a client that reads secrets making http requests to AWS.

You can look for it in my [git repository](https://github.com/alex-valchuk/AwsSecretsManagerService/blob/master/AwsSecretsManagerClient.cs).

**Comment by dimitry** [comment]
@alex-valchuk this is great! (your repo). did you ever combine it with MS Configuration Builder to make a custom ConfigBuilder?
