### ISSUE TITLE
Support for Binary Data using Razor Pages

### ISSUE THREAD

**Issue by mattleigh** [aws/aws-sdk-net#951]
I have created a new Visual Studio project using the Serverless Razor Pages template provided by the AWS SDK.  It works fine when I run it locally, but after deploying it images referenced via html img tags cannot be displayed (I am using a jpeg image in my project for testing).  I believe this is due to the support for binary files not being configured correctly.

According to [this](https://aws.amazon.com/blogs/developer/serverless-asp-net-core-2-0-applications/) page 

> If your web application displays images, we recommend you serve those images from Amazon S3. This is more efficient for returning static content like images, Cascading Style Sheets, etc. Also, to return images from your Lambda function to the browser, you need to do extra configuration in [API Gateway for binary data](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings-configure-with-console.html).

I have added the image/jpeg to the Binary Media Types in the API Gateway settings but they are still not being served correctly.  If I try hitting the image path directly from the browser I get "The image {image path} cannot be displayed because it contains errors.".  If I retrieve the image using Powershell it looks like the content is an array of integers.

a. Can anyone tell me what I'm doing wrong?
b. If this is an issue around the Binary Media Type configuration, can the required config be added to the serverless.template file in the Razor Pages VS template

**Comment by normj** [comment]
Can you move this to the [aws-lambda-dotnet](https://github.com/aws/aws-lambda-dotnet) repository where we handle these types of issues.

**Comment by mattleigh** [comment]
Moved to https://github.com/aws/aws-lambda-dotnet/issues/279
