### ISSUE TITLE
How to contribute this SDK repository 

### ISSUE THREAD

**Issue by Johpilliar** [aws/aws-sdk-net#952]
I went through this repository and i like to contribute to this repository. As per my understanding there was no onboarding document or any guidelines on how to assign issue to myself. I am unable to find any contact mail id for any clarification.

**Comment by normj** [comment]
Yes, we are lacking in on boarding documentation. Are you looking to contribute features or help resolve issues? We welcome pull requests if there are things you would like to add or if you would like to discuss a feature before implementing you can chat in the gitter channel or open a issue.

**Comment by Johpilliar** [comment]
Thanks for you reply. Myself and friends are looking to contribute some features in this repository. So we were looked  boarding documentations to understand the existing code. Like you said, we were not able to find it. Then I have tried to assign existing issues with my name but not able to do it. Can you please help me to assign bugs so that i can start contribute to this repository.

**Comment by sstevenkang** [comment]
Feel free to respond to an issue and comment that you would like to take a look.  Also, feel free to create a PR.
