### ISSUE TITLE
Bug: Cognito SignUpAsync crashes

### ISSUE THREAD

**Issue by ThomasJaeger** [aws/aws-sdk-net#953]
I'm trying to signup a user with AWS Cognito with my .net core 2.0 console app and a user pool. My app crashes when this line gets executed:

`var result = await _client.SignUpAsync(signUpRequest);`

## Expected Behavior
SignUpAsync should work and return a `SignUpResponse`.

## Current Behavior
My .net core 2.0 console simply stops working, crashes, with no exceptions rasied whatsoever. No log entries are generated at all.

## Possible Solution
As a minimum, exception MUST be rasied and not let developers leave in the dark. Fix SignUpAsync!!!

## Steps to Reproduce (for bugs)
I tried to setup AWS SDK logging with log4net but the only thing that gets logged is my own log info entry. HELP!!!! Super frustrating.

Here is the Program.cs portion to setup logging:

    [assembly: log4net.Config.XmlConfigurator(ConfigFile = "log4net.config")]

    namespace ASSA
    {
        class Program
        {
            private static readonly ILog log = LogManager.GetLogger(MethodBase.GetCurrentMethod().DeclaringType);
            private static readonly ILoggerRepository repo = LogManager.GetRepository(Assembly.GetEntryAssembly());

            static void Main(string[] args)
            {
                if (repo.Configured)
                    Console.WriteLine("configured");

                AWSConfigs.AWSRegion = "us-east-1";
                AWSConfigs.LoggingConfig.LogTo = LoggingOptions.Log4Net;
                AWSConfigs.LoggingConfig.LogResponses = ResponseLoggingOption.Always;

                log.Info("Started ASSA...");
                ShowMenu();
                WaitForMenuSelection();
            }

Here is the SignUpUser method:

    public async Task<bool> SignUpUser(string username, string password, string email, string phoneNumber, string firstName, string lastName)
        {
            try
            {
                var signUpRequest = new SignUpRequest
                {
                    ClientId = CLIENT_ID,
                    Username = username,
                    Password = password
                };

                var attributeType = new AttributeType
                {
                    Name = "phone_number",
                    Value = phoneNumber
                };
                signUpRequest.UserAttributes.Add(attributeType);

                var attributeType1 = new AttributeType
                {
                    Name = "email",
                    Value = email
                };
                signUpRequest.UserAttributes.Add(attributeType1);

                var attributeType2 = new AttributeType
                {
                    Name = "given_name",
                    Value = firstName
                };
                signUpRequest.UserAttributes.Add(attributeType2);

                var attributeType3 = new AttributeType
                {
                    Name = "family_name",
                    Value = lastName
                };
                signUpRequest.UserAttributes.Add(attributeType3);

                var result = await _client.SignUpAsync(signUpRequest);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                return false;
            }
            return true;
        }

Here is how I setup the credentials:

    try
    {
        BasicAWSCredentials creds = null;

        var chain = new CredentialProfileStoreChain();
        if (chain.TryGetAWSCredentials("Thomas", out var awsCredentials))
        {
            creds = new BasicAWSCredentials(awsCredentials.GetCredentials().AccessKey, awsCredentials.GetCredentials().SecretKey);
        }

        _client = new AmazonCognitoIdentityProviderClient(creds, Amazon.RegionEndpoint.USEast1);
    }
    catch (Exception e)
    {
        Console.WriteLine(e);
        throw;
    }

## Context
I'm trying to sign-up a new user using Cognito with my user pool.

## Your Environment
![image](https://user-images.githubusercontent.com/1396719/39966977-3ccba72e-5682-11e8-856f-83c5f434de8c.png)
* AWSSDK.Core version used: 2.0
* Service assembly and version used: 
* Operating System and version: Windows 10
* Visual Studio version: 2017 Version 15.6.6
* Targeted .NET platform: Core 2.0

## .NET Core Info
* .NET Core version used for development: 2.0
* .NET Core version installed in the environment where application runs: 2.0
* Output of `dotnet --info`: 

    .NET Command Line Tools (2.1.104)

    Product Information:
     Version:            2.1.104
     Commit SHA-1 hash:  48ec687460

    Runtime Environment:
     OS Name:     Windows
     OS Version:  10.0.16299
     OS Platform: Windows
     RID:         win10-x64
     Base Path:   C:\Program Files\dotnet\sdk\2.1.104\

    Microsoft .NET Core Shared Framework Host

      Version  : 2.0.6

      Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d

* Contents of project.json/project.csproj: 

    <Project Sdk="Microsoft.NET.Sdk">

      <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>netcoreapp2.0</TargetFramework>
      </PropertyGroup>

      <ItemGroup>
        <PackageReference Include="AWSSDK.CognitoIdentity" Version="3.3.2.22" />
        <PackageReference Include="AWSSDK.CognitoIdentityProvider" Version="3.3.9.5" />
        <PackageReference Include="AWSSDK.Core" Version="3.3.22.5" />
        <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.3.8" />
        <PackageReference Include="AWSSDK.Extensions.CognitoAuthentication" Version="0.9.4" />
        <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.3.5" />
        <PackageReference Include="AWSSDK.Lambda" Version="3.3.13.2" />
        <PackageReference Include="log4net" Version="2.0.8" />
      </ItemGroup>

      <ItemGroup>
        <Folder Include="Properties\" />
      </ItemGroup>

      <ItemGroup>
        <ProjectReference Include="..\Domain\AltoSignal\AltoSignal.csproj" />
      </ItemGroup>

      <ItemGroup>
        <None Update="App.config">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="log4net.config">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
      </ItemGroup>

    </Project>

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by dpix** [comment]
This might be related to my issue https://github.com/aws/aws-sdk-net/issues/937

Try removing the catch and writing to the console in your code. Console logs will not get picked up by your logger

**Comment by ThomasJaeger** [comment]
Removing the catch does not show anything either. The app still crashes when executing

`var result = await _client.SignUpAsync(signUpRequest);`

This is frustratring. This is blocking me and our project for days now. I'm having serious doubts about the AWS SDK quality now. I wish the authors would take time and reply here.

**Comment by ThomasJaeger** [comment]
@dpix What do you mean by console logs will not get picked up by the logger? 
Here is my log4net.config file content:

    <?xml version="1.0" encoding="utf-8" ?>
    <log4net>
      <root>
        <level value="ALL" />
        <appender-ref ref="file" />
      </root>
      <appender name="file" type="log4net.Appender.FileAppender">
        <file value="C:\Users\Thomas\Documents\GitHub\MotherShip\ASSA\assa.log" />
        <appendToFile value="true" />
        <lockingModel type="log4net.Appender.FileAppender+MinimalLock" />
        <layout type="log4net.Layout.PatternLayout">
          <conversionPattern value="%date %level %logger - %message%newline" />
        </layout>
      </appender>
    </log4net>

My console app does log at the initial startup with:

     log.Info("Started ASSA...");

If I could at least see the excpetion or what the heck is wrong with Cognito, it wouldn't be so frustratring. But, I got zilch for any kind of exception from the AWS SDK.

**Comment by ThomasJaeger** [comment]
I can't be t he only one trying to use the AWS SDK with a desktop app and AWS Cognito. Anyone?

**Comment by ThomasJaeger** [comment]
Ok, so I downloaded the entire AWS SDK source, build it, and debugged the following integration test:

     Amazon.Extensions.CognitoAuthentication.IntegrationTests.AuthenticationSignUpUserTests.TestSignUpProcess

I put a breakpoint on line 71 and went back to my AWS Console, I can see the temporary user pool that was created including the two test users. Line 63 with

     await pool.SignUpAsync(userID, password, userAttributes, validationData).ConfigureAwait(false);

was successfull.  So, this is good. At least I know that the SignUpAsync does work and looks like I'md doing something wrong with my code. Now, I have to find out what the correct steps are.

**Comment by sstevenkang** [comment]
Do you have a stack trace of where the exception is thrown?

**Comment by ThomasJaeger** [comment]
@sstevenkang No stack trace is produced. No exception is raised. The console app just stops/crashes.

**Comment by pieruz** [comment]
@ThomasJaeger  Hi Thomas, did you solve this problem? If yes, how? I'm trying to resolve it too, but as I wrote there no hints or similar.
