### ISSUE TITLE
Retrieve list of CloudWatch Alarms for an instance via PowerShell

### ISSUE THREAD

**Issue by johnwc** [aws/aws-sdk-net#970]
Is there a PowerShell cmdlet that will list all configured CW Alarms for an instance?

**Comment by sstevenkang** [comment]
No. Also, I think this is too specific of a usecase for us to add this  as a custom powershell cmdlet.

**Comment by johnwc** [comment]
The aws console does it, so why would it be to specific??

**Comment by sstevenkang** [comment]
[DescribeAlarms](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_DescribeAlarms.html) should list all the alarms and you can probably filter it by whether there are associated instances.

AWS Console has that functionality because the console team implemented the feature.

**Comment by sstevenkang** [comment]
You can probably do something like:

```
Get-CWAlarm -Region <region> | Where-Object {(ForEach-Object -InputObject $_.Dimensions -Process { $_.Name -eq "InstanceId" -and $_.Value -eq "<instanceid>"}) -contains $true }
```

**Comment by johnwc** [comment]
That does work, but when you are dealing with a enterprise environment and there are thousands of alarms; this takes a very long time to run. Is there anyway the CW team can expose the describeAlarmsForResourceIds method to AWS services? Or add the ability to filter the describeAlarms method?

**Comment by prakashst205** [comment]
@sstevenkang : i tried your command but it gives me no output though i have CW alarm configured on my instances.Any help

**Comment by johnwc** [comment]
@sstevenkang it's been two years, and I gave a very good reason why we would not want to pull all of the alarms down first and then filter locally. It takes a very very long time to pull all of our alarms down for all of our instances in our VPC, to then find the few for a single instance.

**Comment by normj** [comment]
@johnwc To provide what you want we need the service to add the feature in their API. I would recommend letting them know about your need via their forums. https://forums.aws.amazon.com/forum.jspa?forumID=138 There backlog is driven based on customer asks and the asks are more impactful if they come directly from the customer.

**Comment by prakashst205** [comment]
can some one explore the below cmd:
Get-CWAlarm -Region <region> | Where-Object {(ForEach-Object -InputObject $_.Dimensions -Process { $_.Name -eq "InstanceId" -and $_.Value -eq "<instanceid>"}) -contains $true }
Does it works for you ?

**Comment by johnwc** [comment]
@prakashst205  That doesn't look like valid powershell. What are you trying to accomplish with the command?

**Comment by prakashst205** [comment]
Yes i found in the earlier script property name is not available either it is namespace .
Actually i having n number of ec2 instances , i wanted to extract all the cloud watch alarm for each instances with the instance id.
I tried get-cwalalarm but it gives alarm name but not instance id which also i m looking for.

**Comment by johnwc** [comment]
@prakashst205 To retrieve all the CW alarms for a single instance, you must pull back ALL CW alarms and then filter on them locally. If you are in a large org, the `Get-CWAlarm` call may take a while to return all the CW alarms.

```powershell
$InstanceId = "<your instance id>"
Get-CWAlarm | Where-Object {(ForEach-Object -InputObject $_.Dimensions -Process { $_.Name -eq "InstanceId" -and $_.Value -eq "$InstanceId"}) -contains $true }
```

@normj I know you mentioned to go over to the forums to ask for this feature, but is there any way that you can forward this issue link to someone over in that area so that can see what we have to do in order to list the CW alarms for just one instance?
