### ISSUE TITLE
AWS Gamelift for Unity - support status?

### ISSUE THREAD

**Issue by prodigga** [aws/aws-sdk-net#973]
Hey there.

I was wondering what the status is of Unity support for Gamelift?

It seems like the Gamelift client is not supported in Unity, but confusingly there are developer guides for how to write a Unity Server using Gamelift [located here.](https://docs.aws.amazon.com/gamelift/latest/developerguide/gamelift-sdk-server-api.html)

So I can make a server that works with Gamelift in Unity, but I can't make a game using Unity that connects to it using Gamelift?

I am targeting Android and iOS.

Some clarification would be great, cheers.

**Comment by ashegoulding** [comment]
See if this interests you :)

https://github.com/fixstu/aws-sdk-net
