### ISSUE TITLE
Support for S3 Select?

### ISSUE THREAD

**Issue by martinkoslof** [aws/aws-sdk-net#974]
I was just curious if support for S3 Select is coming in the near future. I saw a new release was made yesterday (06/01) but nothing related to this. We actually have a use case for S3 Select and I'd prefer to not have to use Boto3 or wrap python in our .net core micro services.

**Comment by normj** [comment]
It's coming. It requires some new core changes to the SDK that we are still working on but we know this is an important feature and we want to get it out for .NET.

**Comment by costleya** [comment]
We released S3 Select support for the AWS SDK for .NET.

https://aws.amazon.com/blogs/developer/amazon-s3-select-support-in-the-aws-sdk-for-net/
https://www.nuget.org/packages/AWSSDK.S3/3.3.20
