### ISSUE TITLE
Using this for Code Commit --git-credential-AWSSV4.exe , This does not fetches the .Net SDK credentials set using SAML federation.  But instead this error is throw always

### ISSUE THREAD

**Issue by ameenibrahim** [aws/aws-sdk-net#975]
https://github.com/aws/aws-sdk-net/blob/5e89eed153496a9c0a6bc0d5279c9e409be2b787/sdk/src/Core/Amazon.Runtime/Credentials/_bcl%2Bcoreclr/StoredProfileAWSCredentials.cs#L142

**Comment by ameenibrahim** [comment]
My RegisteredAccounts.json


{
    "9a85f8b3-127e-4e95-9414-0bbdaf31159b" : {
        "EndpointName" : "ADFS-Demo",
        "RoleArn"      : "arn:aws:iam::504971575277:saml-provider/ADFS,arn:aws:iam::504971575277:role/ADFS-Users",
        "ProfileType"  : "SAML",
        "DisplayName"  : "SAMLDemoProfile"
    },
    "9c18e795-4207-4816-9c33-567745427529" : {
        "EndpointName" : "ADFS-Demo",
        "RoleArn"      : "arn:aws:iam::504971575277:saml-provider/ADFS,arn:aws:iam::504971575277:role/ADFS-Users",
        "ProfileType"  : "SAML",
        "DisplayName"  : "default",
        "Region"       : "us-east-1"
    }
}

**Comment by ameenibrahim** [comment]
I am trying to setup CodeCommit + ADFS - SAML profile in a windows environment (without AWS CLI and ). If I use AWS CLI Git helper with .ini credential file format, git commands work without issues. But if I use git-credential-AWSSV4.exe and proper profile, then this error is thrown. 

My .gitconfig files looks like this

[user]
        name = Ameen
        email = ameen@awsameen.com
[credential]
        helper = !'C:\\Users\\ameen\\AppData\\Roaming\\GitCredStore\\git-credential-AWSSV4.exe' --profile=default
        UseHttpPath = true

**Comment by sstevenkang** [comment]
Could you clarify what you mean by .NET SDK credentials?  Are you talking about encrypted stored credentials?  Those are only accessible by .NET SDK and VS toolkit.  

The only credentials that git-credentials-AWSSV4 would work with is the credential pair in `C:\users\<user>\.aws\credentials`

**Comment by ameenibrahim** [comment]
Hi ssteven,

 Yes you are right. I meant the credentials stored in C:\Users\<username>\AppData\Local\AWSToolkit/RegisteredAccounts.json encrypted creds. 

  It would be ideal if the git-credentials-AWSSV4 would read the credentials stored after SAML authentication for federated users. 

Also I see in code that this first looks for creds in SDK store if not found searches for the shared credentials file in user home location.

                    _wrappedCredentials = ProfileManager.GetAWSCredentials(lookupName);

https://github.com/aws/aws-sdk-net/blob/5e89eed153496a9c0a6bc0d5279c9e409be2b787/sdk/src/Core/Amazon.Runtime/Credentials/_bcl%2Bcoreclr/StoredProfileAWSCredentials.cs#L114

**Comment by sstevenkang** [comment]
This is not a supported use case.  :(  

The encrypted stored credentials is a custom solution for .NET SDK and Toolkit.  It's not AWS wide specification.
