### ISSUE TITLE
using the Unity plugin for the SDK in editor

### ISSUE THREAD

**Issue by zaibach333** [aws/aws-sdk-net#977]
This was in an archived feature request, was it forgotten about? 

Very practical use-case for this:
Unity3d hosts their own cloud building server with the option of editor scripts to be run before export.
for each platform one may want/need to upload assetbundles or other platform-specific assets to s3

This is currently possible with signedURLs but there doesn't seem to a way to use the SDK plugin on their cloud build scripts because the plugin requires Unity to be in play mode.

SignedURLs are limitted to some basic file manipulation, but are file specific, what if you say, want to create a folder for each version of the cloud built assets, you would need access to the SDK. 

I would very much like to know where the priority is for this issue, and I hope it hasn't been forgotten.

**Comment by michaeleconomy** [comment]
Could you guys fix this?  Theres lots of requests for this it looks like (when i search google at least).

**Comment by abarra-ngs** [comment]
Hey @zaibach333 it's been a year from now since you write this post issue. Did you achieve to get the AWS SDK working on editor mode? I have the same issue today.

Thanks

**Comment by zaibach333** [comment]
We didn't find a way for it to work in editor or cloud, so, this is in the same state. haven't tried a more recent plugin for Unity in some time though.

**Comment by HarelNimrod** [comment]
For anyone looking into this problem - I've managed to work around it by hooking the editor update loop instead of the mono update which the library depends on.

Not the prettiest solution - but it works :)

Here's the code snippet to initialize S3 only for edit mode / batch mode:
`	private MethodInfo _updateMethod;
		private UnityMainThreadDispatcher _unityMainThreadDispatcher;
		private object[] _methodArgs;
		private void HookEditorUpdatesInBatchMode()
		{
			GameObject initializer = GameObject.Instantiate(new GameObject("Unity Initializer"));
			UnityInitializer.AttachToGameObject(initializer);
			
			// Use reflection to manually simulate the awake function work + inject update calls for it...
			UnityInitializer unityInitializer = initializer.GetComponent<UnityInitializer>();
			Type t = unityInitializer.GetType();
			BindingFlags bindingFlags = BindingFlags.Static | BindingFlags.NonPublic | BindingFlags.Instance;
			
			FieldInfo fieldInfo = t.GetField("_instance", bindingFlags);
			fieldInfo.SetValue(null, unityInitializer);
			
			fieldInfo = t.GetField("_mainThread", bindingFlags);
			fieldInfo.SetValue(null, Thread.CurrentThread);

			// Internal code copied from UnityInitializer Awake()
			AmazonHookedPlatformInfo.Instance.Init();
			AWSConfigs.AddTraceListener("Amazon", (TraceListener) new UnityDebugTraceListener("UnityDebug"));
			initializer.AddComponent<UnityMainThreadDispatcher>();

			// Finally, get the main thread dispatcher update method to call it "manually" using the editor's update loop.
			_unityMainThreadDispatcher = initializer.GetComponent<UnityMainThreadDispatcher>();
			_updateMethod = _unityMainThreadDispatcher.GetType().GetMethod("Update", bindingFlags);
			_methodArgs = new object[] {};
			EditorApplication.update += OnEditorUpdate;
		}

		private void OnEditorUpdate()
		{
			if (_updateMethod != null)
			{
				_updateMethod.Invoke(_unityMainThreadDispatcher, new object[] {});
			}
		}`
