### ISSUE TITLE
AmazonSimpleNotificationServiceConfig constructor call to GetEnvironmentVariable() causes System.Security.SecurityException

### ISSUE THREAD

**Issue by cloudspider** [aws/aws-sdk-net#980]
The **System.Environment.GetEnvironmentVariable** method is not allowed to be called within a **Dynamics 365 Online** instance.

The following code causes an exception when run within a Dynamics 365 Online plugin.

```
var snsClient = new AmazonSimpleNotificationServiceClient(new BasicAWSCredentials(ACCESS_KEY, SECRET_KEY), RegionEndpoint.USEast1);
```

The AmazonSimpleNotificationServiceClient method calls the AmazonSimpleNotificationServiceConfig constructor and although all of the required config parameters are supplied, the constructor will still attempt to call System.Environment.GetEnvironmentVariable and this results in a System.Security.SecurityException.

Dynamics 365 online does not allow environment variables to be read and reports the following exception:

**System.Security.SecurityException: Request for the permission of type 'System.Security.Permissions.EnvironmentPermission**

```
Entered Plugins.ContactPlugin.Execute()
Plugins.ContactPlugin is firing for Entity: contact, Message: Update, Method: ExecutePluginLogic
Exception: System.TypeInitializationException: The type initializer for 'Amazon.SimpleNotificationService.AmazonSimpleNotificationServiceConfig' threw an exception. 
---> System.Security.SecurityException: Request for the permission of type 'System.Security.Permissions.EnvironmentPermission, 
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.

at System.Security.CodeAccessSecurityEngine.Check(Object demand, StackCrawlMark& stackMark, Boolean isPermSet)
at System.Security.CodeAccessPermission.Demand()
at System.Environment.GetEnvironmentVariable(String variable)
at Amazon.Util.Internal.InternalSDKUtils.GetExecutionEnvironment()
at Amazon.Util.Internal.InternalSDKUtils.GetExecutionEnvironmentUserAgentString()
at Amazon.Util.Internal.InternalSDKUtils.BuildUserAgentString(String serviceSdkVersion)
at Amazon.SimpleNotificationService.AmazonSimpleNotificationServiceConfig..cctor()

--- End of inner exception stack trace ---
at Amazon.SimpleNotificationService.AmazonSimpleNotificationServiceConfig..ctor()
at Amazon.SimpleNotificationService.AmazonSimpleNotificationServiceClient..ctor(AWSCredentials credentials, RegionEndpoint region)
at Plugins.ContactPlugin.ExecutePluginLogic(IServiceProvider serviceProvider)
at Plugins.BasePlugin.Execute(IServiceProvider serviceProvider)
Exiting Plugins.ContactPlugin.Execute()
```

## Possible Solution

Add a new constructor for 
Amazon.SimpleNotificationService.AmazonSimpleNotificationServiceConfig that accepts a set of config parameters and therefore removes the need to call System.Environment.GetEnvironmentVariable(String variable).

**Comment by cloudspider** [comment]
A quick fix may be to add a protective try/catch within GetExecutionEnvironment.

see line 223:

https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Util/Internal/InternalSDKUtils.cs#L223

```
        internal static string EXECUTION_ENVIRONMENT_ENVVAR = "AWS_EXECUTION_ENV";
        internal static string GetExecutionEnvironment()
        {
            try
            {
                return Environment.GetEnvironmentVariable(EXECUTION_ENVIRONMENT_ENVVAR);
            }
            catch
            {
                return string.Empty;
            }
        }
```

**Comment by sstevenkang** [comment]
Yup, this definitely a case we should handle.  Thanks for the report.

**Comment by DanielD** [comment]
I am having this same issue.  Has anyone found a workaround for it?

**Comment by duongue** [comment]
@sstevenkang any update on this?

**Comment by cloudspider** [comment]
@DanielD, @sstevenkang  - It would be great if my simple try/catch fix above could be applied soon.

Short of that, you can use the following C# code.


        // refer to:  https://docs.aws.amazon.com/general/latest/gr/sigv4-signed-request-examples.html


        static string ToHexString(byte[] array)
        {
            StringBuilder hex = new StringBuilder(array.Length * 2);
            foreach (byte b in array)
            {
                hex.AppendFormat("{0:x2}", b);
            }
            return hex.ToString();
        }

        /// <summary>
        /// Generates a keyed-hash message authentication code using the SHA256 hash algorithm
        /// </summary>
        /// <param name="data"></param>
        /// <param name="key"></param>
        /// <returns></returns>
        static byte[] HmacSHA256(string data, byte[] key)
        {
            string algorithm = "HmacSHA256";
            KeyedHashAlgorithm kha = KeyedHashAlgorithm.Create(algorithm);
            kha.Key = key;

            return kha.ComputeHash(Encoding.UTF8.GetBytes(data));
        }

        static byte[] GetSignatureKey(string key, string dateStamp, string regionName, string serviceName)
        {
            byte[] kSecret = Encoding.UTF8.GetBytes(("AWS4" + key).ToCharArray());
            byte[] kDate = HmacSHA256(dateStamp, kSecret);
            byte[] kRegion = HmacSHA256(regionName, kDate);
            byte[] kService = HmacSHA256(serviceName, kRegion);
            byte[] kSigning = HmacSHA256("aws4_request", kService);

            return kSigning;
        }


        /// <summary>
        /// Generates an almost-unique 256-bit (32-byte) signature (cryptographic hash or digest) for a text string or data file
        /// Hash functions compress large amounts of data into a small message digest.
        /// </summary>
        /// <param name="message"></param>
        /// <returns></returns>
        static string Sha256(string message)
        {
            var crypt = new System.Security.Cryptography.SHA256Managed();
            var hash = new System.Text.StringBuilder();
            byte[] crypto = crypt.ComputeHash(Encoding.UTF8.GetBytes(message));
            foreach (byte theByte in crypto)
            {
                hash.Append(theByte.ToString("x2"));
            }
            return hash.ToString();
        }


        public static string SNSPublish_POST(SnsConfig config, string subject, string message)
        {
            var ACCESS_KEY = config.AccessKey;  // "AXIAJXXHN5TGKLDT7XXX";
            var SECRET_KEY = config.SecretKey; // "zzOxVDPDl3Ix4xQqZvJPSXriXT21XE+FZwxPENQx";

            var topicArn = Uri.EscapeDataString(config.Topic);  //"arn:aws:sns:us-east-1:888553369388:nameof-topic"
            subject = Uri.EscapeDataString(subject);
            message = Uri.EscapeDataString(message);


            var t = DateTime.UtcNow;
            var amz_date = t.ToString("yyyyMMddTHHmmssZ");
            var date_stamp = t.ToString("yyyyMMdd");

            var method = "POST";
            var service = "sns";
            var region = config.Region; /// "us-east-1";
            var endpoint = config.Endpoint;  /// "https://sns.us-east-1.amazonaws.com";

            var uri = new Uri(endpoint);
            var host = uri.Host;


            var content_type = "application/x-www-form-urlencoded";

            /*             
                # Step 2: Create canonical URI--the part of the URI from domain to query 
                # string (use '/' if no path)             
             */
            var canonical_uri = "/";

            /*
                # Step 3: Create the canonical query string. In this example (a GET request),
                # request parameters are in the query string. Query string values must
                # be URL-encoded (space=%20). The parameters must be sorted by name.
                # For this example, the query string is pre-formatted in the request_parameters variable.             
             */
            var canonical_querystring = string.Empty;


            /*  
                # Step 4: Create the canonical headers and signed headers. Header names
                # must be trimmed and lowercase, and sorted in code point order from
                # low to high. Note that there is a trailing \n.
            */
            var canonical_headers = $"content-type:{content_type}\nhost:{host}\nx-amz-date:{amz_date}\n";


            /*
                # Step 5: Create the list of signed headers. This lists the headers
                # in the canonical_headers list, delimited with ";" and in alpha order.
                # Note: The request can include any headers; canonical_headers and
                # signed_headers lists those that you want to be included in the 
                # hash of the request. "Host" and "x-amz-date" are always required.             
             */
            var signed_headers = "content-type;host;x-amz-date";


            /*
                # Step 6: Create payload hash. For POST the payload (body of the request) 
                # contains the request parameters.
             */

            var request_parameters = $"Action=Publish&Message={message}&Subject={subject}&TopicArn={topicArn}";

            var payload_hash = Sha256(request_parameters);


            /*
                # Step 7: Combine elements to create canonical request             
             */
            var canonical_request = method + '\n' + canonical_uri + '\n' + canonical_querystring + '\n' + canonical_headers + '\n' + signed_headers + '\n' + payload_hash;
            Console.WriteLine($"Canonical Request:\n{canonical_request}\n");

            var canonical_request_hash = Sha256(canonical_request);
            Console.WriteLine($"Canonical Request Hash:\n{canonical_request_hash}\n");


            /*************TASK 2: CREATE THE STRING TO SIGN*************/

            var algorithm = "AWS4-HMAC-SHA256";
            var credential_scope = $"{date_stamp}/{region}/{service}/aws4_request";
            var string_to_sign = $"{algorithm}\n{amz_date}\n{credential_scope}\n{canonical_request_hash}";
            Console.WriteLine($"String To Sign:\n{string_to_sign}\n");


            /************* TASK 3: CALCULATE THE SIGNATURE *************/


            //Create the signing key using the function defined above.
            var signing_key = GetSignatureKey(SECRET_KEY, date_stamp, region, service);
            var signature_hash = HmacSHA256(string_to_sign, signing_key);
            var signature = ToHexString(signature_hash);

            Console.WriteLine($"Signature:\n{signature}\n");


            /************* TASK 4: ADD SIGNING INFORMATION TO THE REQUEST *************/
            /*
                # The signing information can be either in a query string value or in 
                # a header named Authorization. This code shows how to use a header.
                # Create authorization header and add to request headers             
             */


            var authorization_header = $"{algorithm} Credential={ACCESS_KEY}/{credential_scope}, SignedHeaders={signed_headers}, Signature={signature}";
            Console.WriteLine($"Authorization Header:\n{authorization_header}\n");


            var url = endpoint;
            Console.WriteLine($"URL:\n{url}\n");

            var request = WebRequest.Create(url);

            try
            {

                request.Method = method;
                request.ContentType = content_type;


                request.Headers.Add("x-amz-date", amz_date);
                request.Headers.Add("Authorization", authorization_header);

                Console.WriteLine($"Headers:\n{request.Headers.ToString()}\n");


                var data = Encoding.UTF8.GetBytes(request_parameters);
                request.ContentLength = data.Length;


                using (var stream = request.GetRequestStream())
                {
                    stream.Write(data, 0, data.Length);
                }


                var response = request.GetResponse();
                var responseString = new StreamReader(response.GetResponseStream()).ReadToEnd();
                return responseString;                
            }
            catch (System.Exception ex)
            {
                Console.WriteLine($"EXCEPTION:\n{ex.ToString()}");
                return ex.ToString();
            }
        }

**Comment by klaytaybai** [comment]
@cloudspider,  I removed your last comment until I could get a security team to verify that your last comment was not accidentally exposing private information.  This does not seem to be the case; I am told the possibly sensitive information was invalid and likely fake.  Still, please be careful to not write sensitive information anywhere in your code, even in comments because they may accidentally get checked in publicly or otherwise made visible.  

I am reposting for you:

-- cloudspider --
 It would be great if my simple try/catch fix above could be applied soon.

Short of that, you can use the following C# code.

    // refer to:  https://docs.aws.amazon.com/general/latest/gr/sigv4-signed-request-examples.html


    static string ToHexString(byte[] array)
    {
        StringBuilder hex = new StringBuilder(array.Length * 2);
        foreach (byte b in array)
        {
            hex.AppendFormat("{0:x2}", b);
        }
        return hex.ToString();
    }

    /// <summary>
    /// Generates a keyed-hash message authentication code using the SHA256 hash algorithm
    /// </summary>
    /// <param name="data"></param>
    /// <param name="key"></param>
    /// <returns></returns>
    static byte[] HmacSHA256(string data, byte[] key)
    {
        string algorithm = "HmacSHA256";
        KeyedHashAlgorithm kha = KeyedHashAlgorithm.Create(algorithm);
        kha.Key = key;

        return kha.ComputeHash(Encoding.UTF8.GetBytes(data));
    }

    static byte[] GetSignatureKey(string key, string dateStamp, string regionName, string serviceName)
    {
        byte[] kSecret = Encoding.UTF8.GetBytes(("AWS4" + key).ToCharArray());
        byte[] kDate = HmacSHA256(dateStamp, kSecret);
        byte[] kRegion = HmacSHA256(regionName, kDate);
        byte[] kService = HmacSHA256(serviceName, kRegion);
        byte[] kSigning = HmacSHA256("aws4_request", kService);

        return kSigning;
    }


    /// <summary>
    /// Generates an almost-unique 256-bit (32-byte) signature (cryptographic hash or digest) for a text string or data file
    /// Hash functions compress large amounts of data into a small message digest.
    /// </summary>
    /// <param name="message"></param>
    /// <returns></returns>
    static string Sha256(string message)
    {
        var crypt = new System.Security.Cryptography.SHA256Managed();
        var hash = new System.Text.StringBuilder();
        byte[] crypto = crypt.ComputeHash(Encoding.UTF8.GetBytes(message));
        foreach (byte theByte in crypto)
        {
            hash.Append(theByte.ToString("x2"));
        }
        return hash.ToString();
    }


    public static string SNSPublish_POST(SnsConfig config, string subject, string message)
    {
        var ACCESS_KEY = config.AccessKey; 
        var SECRET_KEY = config.SecretKey;

        var topicArn = Uri.EscapeDataString(config.Topic);  //"arn:aws:sns:us-east-1:888553369388:nameof-topic"
        subject = Uri.EscapeDataString(subject);
        message = Uri.EscapeDataString(message);


        var t = DateTime.UtcNow;
        var amz_date = t.ToString("yyyyMMddTHHmmssZ");
        var date_stamp = t.ToString("yyyyMMdd");

        var method = "POST";
        var service = "sns";
        var region = config.Region; /// "us-east-1";
        var endpoint = config.Endpoint;  /// "https://sns.us-east-1.amazonaws.com";

        var uri = new Uri(endpoint);
        var host = uri.Host;


        var content_type = "application/x-www-form-urlencoded";

        /*             
            # Step 2: Create canonical URI--the part of the URI from domain to query 
            # string (use '/' if no path)             
         */
        var canonical_uri = "/";

        /*
            # Step 3: Create the canonical query string. In this example (a GET request),
            # request parameters are in the query string. Query string values must
            # be URL-encoded (space=%20). The parameters must be sorted by name.
            # For this example, the query string is pre-formatted in the request_parameters variable.             
         */
        var canonical_querystring = string.Empty;


        /*  
            # Step 4: Create the canonical headers and signed headers. Header names
            # must be trimmed and lowercase, and sorted in code point order from
            # low to high. Note that there is a trailing \n.
        */
        var canonical_headers = $"content-type:{content_type}\nhost:{host}\nx-amz-date:{amz_date}\n";


        /*
            # Step 5: Create the list of signed headers. This lists the headers
            # in the canonical_headers list, delimited with ";" and in alpha order.
            # Note: The request can include any headers; canonical_headers and
            # signed_headers lists those that you want to be included in the 
            # hash of the request. "Host" and "x-amz-date" are always required.             
         */
        var signed_headers = "content-type;host;x-amz-date";


        /*
            # Step 6: Create payload hash. For POST the payload (body of the request) 
            # contains the request parameters.
         */

        var request_parameters = $"Action=Publish&Message={message}&Subject={subject}&TopicArn={topicArn}";

        var payload_hash = Sha256(request_parameters);


        /*
            # Step 7: Combine elements to create canonical request             
         */
        var canonical_request = method + '\n' + canonical_uri + '\n' + canonical_querystring + '\n' + canonical_headers + '\n' + signed_headers + '\n' + payload_hash;
        Console.WriteLine($"Canonical Request:\n{canonical_request}\n");

        var canonical_request_hash = Sha256(canonical_request);
        Console.WriteLine($"Canonical Request Hash:\n{canonical_request_hash}\n");


        /*************TASK 2: CREATE THE STRING TO SIGN*************/

        var algorithm = "AWS4-HMAC-SHA256";
        var credential_scope = $"{date_stamp}/{region}/{service}/aws4_request";
        var string_to_sign = $"{algorithm}\n{amz_date}\n{credential_scope}\n{canonical_request_hash}";
        Console.WriteLine($"String To Sign:\n{string_to_sign}\n");


        /************* TASK 3: CALCULATE THE SIGNATURE *************/


        //Create the signing key using the function defined above.
        var signing_key = GetSignatureKey(SECRET_KEY, date_stamp, region, service);
        var signature_hash = HmacSHA256(string_to_sign, signing_key);
        var signature = ToHexString(signature_hash);

        Console.WriteLine($"Signature:\n{signature}\n");


        /************* TASK 4: ADD SIGNING INFORMATION TO THE REQUEST *************/
        /*
            # The signing information can be either in a query string value or in 
            # a header named Authorization. This code shows how to use a header.
            # Create authorization header and add to request headers             
         */


        var authorization_header = $"{algorithm} Credential={ACCESS_KEY}/{credential_scope}, SignedHeaders={signed_headers}, Signature={signature}";
        Console.WriteLine($"Authorization Header:\n{authorization_header}\n");


        var url = endpoint;
        Console.WriteLine($"URL:\n{url}\n");

        var request = WebRequest.Create(url);

        try
        {

            request.Method = method;
            request.ContentType = content_type;


            request.Headers.Add("x-amz-date", amz_date);
            request.Headers.Add("Authorization", authorization_header);

            Console.WriteLine($"Headers:\n{request.Headers.ToString()}\n");


            var data = Encoding.UTF8.GetBytes(request_parameters);
            request.ContentLength = data.Length;


            using (var stream = request.GetRequestStream())
            {
                stream.Write(data, 0, data.Length);
            }


            var response = request.GetResponse();
            var responseString = new StreamReader(response.GetResponseStream()).ReadToEnd();
            return responseString;                
        }
        catch (System.Exception ex)
        {
            Console.WriteLine($"EXCEPTION:\n{ex.ToString()}");
            return ex.ToString();
        }
    }
