### ISSUE TITLE
[Information Request] How to use AWS logging with Glacier?

### ISSUE THREAD

**Issue by maxima120** [aws/aws-sdk-net#981]
I am trying to log whatever happens during Glacier calls. But I don't get any logging in the file..

I use this article: https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

the app is using log4net configure in xml file. I tried to configure AWS logging in the code though:

`                client = new AmazonGlacierClient(accessKeyId, secretAccessKey, config);

                AWSConfigs.Logging = LoggingOptions.Log4Net | LoggingOptions.SystemDiagnostics;
                AWSConfigs.LogMetrics = true;
                AWSConfigs.ResponseLogging = ResponseLoggingOption.Always;`

**Comment by gokarnm** [comment]
@maxima120 , what does the _log4net_ or _System.Diagnostics_ configuration in app.config look like? Can you share the relevant sections. This [blog](https://aws.amazon.com/blogs/developer/logging-with-the-aws-sdk-for-net/) has snippets for logger configuration.

**Comment by maxima120** [comment]
Ill look it up on Monday.. but just to clarify - same config works with S3 but not Glacier.

**Comment by maxima120** [comment]
OK the config worked for me like this: 
(log4net and AWSConfigs.LogTo - didn't)
 ```
 <appSettings>
    <add key="AWSLogMetrics" value="true"/>
    <add key="AWSLogging" value="SystemDiagnostics"/>
  </appSettings>

  <system.diagnostics>
    <trace autoflush="true"/>
    <sources>
      <source name="Amazon">
        <listeners>
          <add name="text" type="System.Diagnostics.TextWriterTraceListener" 
            initializeData="d:awssdk.log"/>
        </listeners>
      </source>
    </sources>
  </system.diagnostics>
```
