### ISSUE TITLE
Glacier multi-part upload - insufficient information in progress event

### ISSUE THREAD

**Issue by maxima120** [aws/aws-sdk-net#983]
I use `UploadMultipartPartRequest.StreamTransferProgress` to capture progress of a multi-part upload.

The parts are uploading as parallel tasks. Hence the event fires for different parts and I have no way to identify which.

I tried to use various `StreamTransferProgressArgs` properties but the only way I found it working if I `IncrementTransferred` and calculate percent using the source file length in my code. The other properties seems to return information relative to the part, event was fired (eg PercentDone is not total percent but the part percent).

Now, the IncrementTransferred is good solution unless you get retries. If you retry a part - then there is no way to figure whats going on.

The way to solve it, is to return information to identify part which fired the event (eg **return the whole request as `StreamTransferProgressArgs.UploadMultipartPartRequest`**)

**Comment by costleya** [comment]
Have you tried capturing the request reference within your event handler?

```csharp
var request = new UploadMultipartPartRequest()
{
  ...
}
request.StreamTransferProgress += (sender, args) => {
  var uploadId = request.UploadId;
  // use uploadId
}
```

**Comment by maxima120** [comment]
this is not how it should be implemented. The class which exposes the event has to be returned as the _sender_ parameter. You return `AmazonGlacierClient` instead.

Outer variables for lambda methods memory management is a nice bonus in .NET but I wouldn't rely solely on it. What if I want a method to handle the event ?

**Comment by vellozzi** [comment]
As this point we wouldn't be able to change that due to backward compatibility issues.
I've added this to our backlog for the next major version though.
In the meantime, here's a possible workaround:
```
var request = new UploadMultipartPartRequest()
{
  ...
}
request.StreamTransferProgress += (sender, args) =>
{
    HandleStreamTransferProgress(request, args);
}
public void HandleStreamTransferProgress(UploadMultipartPartRequest sender, StreamTransferProgressArgs args)
{
    //stuff
}
```
Feel free to comment or reopen if this doesn't work for you.

**Comment by maxima120** [comment]
Sure thank you
