### ISSUE TITLE
AWSOptions not parsed correctly from appSettings.json

### ISSUE THREAD

**Issue by monnecc** [aws/aws-sdk-net#984]
## Expected Behavior
With .NET Core, the configuration of the AWS region is not parsed correctly. This is my configuration: 
`"AWS": { "Region": "eu-west-1" }`
After the call to config.GetAWSOptions() the region is still null. So the parsing from a string to a RegionEndpoint object doesn't work.

## My Environment
* AWSSDK.Extensions.NETCore.Setup version used: 3.3.6
* Operating System and version: Windows 10
* Visual Studio version: 2017, 15.7.3
* Targeted .NET platform: .NET Core 2.0

**Comment by sstevenkang** [comment]
I am guessing you are using this as the content of appsettings.json?  What you provided is not a valid json file.

```
{
    "AWS": {
        "Profile": "local-test-profile",
        "Region": "us-west-2"
     }
}
```

I couldn't repro it locally.  Could you provide a minimal repro and share it with us?

**Comment by monnecc** [comment]
Ah, I'm sorry, it actually works. I was trying out the AWSSDK.Extensions.Configuration.AWSSystemsManager library, which in on the verge of being merged into the AWS SDK. An extension method in that library causes the confusion, because it assumes the AWS options are already loaded into the IConfigurationBuilder I pass. But that isn't the case with me. Thank you for your time and I'll close the issue.
