### ISSUE TITLE
EC2InstanceMetadata does not provide IPv6 information

### ISSUE THREAD

**Issue by nvivo** [aws/aws-sdk-net#985]
## Expected Behavior

IPv6 information is not available via SDK. The information is available via direct http request to the metadata api.

```
curl http://169.254.169.254/latest/meta-data/network/interfaces/macs/[mac]/ipv6s
```

## Current Behavior

Only IPv4 information is available via SDK.

![image](https://user-images.githubusercontent.com/202449/41622324-9c25b4d2-73e5-11e8-8acc-a258c418d584.png)

## Your Environment
* AWSSDK.Core version used: 3.3.24

**Comment by normj** [comment]
Ah, yes we have updated this helper class for any instance new metadata field in a while.
