### ISSUE TITLE
Feature request: follow s3 error redirects

### ISSUE THREAD

**Issue by russau** [aws/aws-sdk-net#988]
boto3 has a nice feature that will follow the redirect in the error you get to a wrong region.  From the [code](https://github.com/boto/botocore/blob/553b5fba857948f7ce7541eb4d3c63a0000cc35c/botocore/utils.py#L895):

> An S3 request sent to the wrong region will return an error that
> contains the endpoint the request should be sent to. This handler
> will add the redirect information to the signing context and then
> redirect the request.

## Expected Behavior

An operation on an object in the wrong region is automatically redirected to the correct region.

## Current Behavior

An operation on an object in the wrong region currently throws an AmazonS3Exception:

`Amazon.S3.AmazonS3Exception: 'The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.'`

**Comment by russau** [comment]
FWIW - the Java SDK can also be configured to do the same -> https://github.com/aws/aws-sdk-java/blob/2d15a603a96f98076f5458db49d659f296eab313/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L5092

There is a configuration to set [forceGlobalBucketAccessEnabled](https://github.com/aws/aws-sdk-java/blob/216331fa3f97e3f46588946630e3abdb31d7830b/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/S3ClientOptions.java#L45).

**Comment by SpaceAge12** [comment]
This feature seems nice. Otherwise what is the alternative? Initalize a new client for each S3 bucket in different regions?
