### ISSUE TITLE
AWS Gamelift sdk for Unity

### ISSUE THREAD

**Issue by TejaswiniiB** [aws/aws-sdk-net#989]
Hi, I am trying to write client side code using AWSGameLift API for my Unity project. Is GameLift service available for .NET 3.5 ? 

I am using Unity 2017.4.3f1 version. I have changed my project settings to support .NET 4.6 Experimental and restarted unity. I was able to install Amazon game lift for my project using nuget package manager in visual studio. Then, I was able to access Amazon GameLift API in my vs code. But API was still inaccessible in Unity editor (there were errors at using Amazon code) . And after sometime they became inaccessible in vs too. Does anyone know why, and how to solve this issue?

**Comment by ashegoulding** [comment]
Dup: #973

**Comment by klaytaybai** [comment]
Closing as a duplicate.  Please also review [our AWS SDK for .NET v3.5 preview](https://aws.amazon.com/blogs/developer/aws-sdk-for-net-v3-5-preview/) if you haven't already.  Switching to targeting our .NET Standard code will allow Unity developers to access all of our AWS services.
