### ISSUE TITLE
Multiple errors 400 - The conditional request failed on Session Provider

### ISSUE THREAD

**Issue by tucaz** [aws/aws-sdk-net#99]
Hi, this is a [question I posted on StackOverflow](http://stackoverflow.com/questions/23528952/400-bad-request-on-aws-dynamo-db-as-session-provider-for-asp-net) last week and it seems like a bug. I'm sorry but I was not able to get any solid repro, but just some evidence regarding of it's existance. Here is the full question with minor edits.

---

We use [AWS's DynamoDB Session Provider](https://github.com/aws/aws-sdk-net/blob/master/AWS.Extensions/SessionProvider/DynamoDBSessionStateStore.cs) in our app to store session data.

I recently moved to an environment where I can have NewRelic monitoring my app and it started throwing alerts regarding Dynamo DB access. However, NewRelic is the only monitoring tool that is getting it. I cannot see anything related to this problem in my application logging (log4net) or the Windows event viewer.

I searched a lot and even went through the source code of the provider but came out empty.

I'm getting (400) Bad Request from what is seems to be all the calls made during a period of 1 or 2 minutes at a time happening 3 or 4 times per hour.

The stacktrace I could get is not promising:

```
at System.Net.HttpWebRequest.GetResponse()
at System.Net.HttpWebRequest.GetResponse()
at Amazon.Runtime.AmazonWebServiceClient.getResponseCallback(IAsyncResult result)
```

And the offending URL is: 

```
dynamodb.us-east-1.amazonaws.com/Stream/GetResponse
```

By using Fiddler during a low usage period in the weekend on the production server I was able to capture some bad requests that were throw. I'm getting "The conditional request failed" which seems to happen because the value was updated while requesting and old value and therefore the value is not consistent to what was expected. Below is a full request/response as a sample.

Request:

```
POST https://dynamodb.us-east-1.amazonaws.com/ HTTP/1.1
X-Amz-Target: DynamoDB_20120810.UpdateItem
Content-Type: application/x-amz-json-1.0
User-Agent: aws-sdk-dotnet-35/2.0.15.0 .NET Runtime/4.0 .NET Framework/4.0 OS/6.2.9200.0 SessionStateProvider TableSync
Host: dynamodb.us-east-1.amazonaws.com
X-Amz-Date: 20140510T153947Z
X-Amz-Content-SHA256: e7a4886acac6ccf16f0da9be962d3a68bd50e381c202277033d0d2bb3208aa8a
Authorization: AWS4-HMAC-SHA256 Credential=redacted/20140510/us-east-1/dynamodb/aws4_request, SignedHeaders=content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-target, Signature=redacted
Accept: application/json
X-NewRelic-ID: redacted
X-NewRelic-Transaction: redacted
Content-Length: 399

{
    "TableName": "ASP.NET_SessionState",
    "Key": {
        "SessionId": {
            "S": "redacted"
        }
    },
    "AttributeUpdates": {
        "LockId": {
            "Value": {
                "S": "42a9ed29-7a92-4455-8733-2f56c7d974b3"
            },
            "Action": "PUT"
        },
        "Locked": {
            "Value": {
                "N": "1"
            },
            "Action": "PUT"
        },
        "LockDate": {
            "Value": {
                "S": "2014-05-10T15:39:47.324Z"
            },
            "Action": "PUT"
        }
    },
    "Expected": {
        "Locked": {
            "Value": {
                "N": "0"
            },
            "Exists": true
        }
    },
    "ReturnValues": "ALL_NEW"
}
```

Response:

```
HTTP/1.1 400 Bad Request
x-amzn-RequestId: redacted
x-amz-crc32: redacted
Content-Type: application/x-amz-json-1.0
Content-Length: 120
Date: Sat, 10 May 2014 15:33:17 GMT

{
    "__type": "com.amazonaws.dynamodb.v20120810#ConditionalCheckFailedException",
    "message": "The conditional request failed"
}
```

---

_Graph 1_

![Non Web Transactions - Graph 1](http://i.stack.imgur.com/3i2My.png)

_Graph 2_

![Errors - Graph 2](http://i.stack.imgur.com/pnMOV.png)

Any help is appreciated. Thanks!

**Comment by superlogical** [comment]
Is it worth adding a Timer that will say every 30 minutes call the DeleteExpiredSessions static method?

**Comment by normj** [comment]
That is an interesting thought. We would need it to be an opt in feature so that no one would be surprised about all the provision throughput being used up. Another thing that needs to be considered is if this is running in an environment with multiple instances we would probably not want this full table scan to run on every instance.
