### ISSUE TITLE
AWS Toolkit for Visual Studio Deployment Green but returns 404

### ISSUE THREAD

**Issue by Neuroforge** [aws/aws-sdk-net#991]
We normally deploy our site via AWS Toolkit for Visual Studio, so far without issue.

Upon recent deploys the AWS Console is showing Green with "Environment update completed successfully.".

However when accessing the site via the Route53 Url of https://xxxxxx.com or the EB Url - xxxxxx-env.xxxxxx.us-west-1.elasticbeanstalk.com it is returning  

Error for https://XXXX.com

This xxxxx.com page can’t be found
No web page was found for the web address: https://xxxxx.com/
HTTP ERROR 404

Error for xxxxxxxx-xxxxxxxxx.us-west-1.elasticbeanstalk.com

This xxxxxx-env.xxxxxx.us-west-1.elasticbeanstalk.com page can’t be found
No web page was found for the web address: http://xxxxxxxxxxx-xxx.xxxxxxxx.us-west-1.elasticbeanstalk.com/
Go to http://elasticbeanstalk.com/

Cannot see any obvious issue. The project works locally in Development and Production mode set.

## Expected Behavior

The deployment should continue as normal, succeed, provide a Green status and then be available via the url.

## Current Behavior

Status is Green.
Url returns 404 for direct environment URL and Route53 URL.

## Context

Unable to access instance after successful deployment
[logs.txt](https://github.com/aws/aws-sdk-net/files/2162910/logs.txt)

## Your Environment

* AWSSDK.Core version used: 
* Service assembly and version used: 
* Operating System and version: 
* Visual Studio version: 
* Targeted .NET platform: 

AWSSDK.Core 3.3.24
.NET Core 2.0
Visual Studio 2017 4.7.03056

## .NET Core Info

* .NET Core version used for development: 
* .NET Core version installed in the environment where application runs: 
* Output of `dotnet --info`: 
* Contents of project.json/project.csproj: 

.NET Core 2.0.8
Target .NET runtime 4.0

'dotnet --info'
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-preview2-008533
 Commit:    996eb6c92c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300-preview2-008533\

Host (useful for support):
  Version: 2.1.0-preview2-26406-04
  Commit:  6833f3026b

.NET Core SDKs installed:
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.1.102 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.300-preview2-008533 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview2-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview2-final [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0-preview2-26406-04 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by steveataws** [comment]
Although I've tagged this as the toolkit, I think this needs the service team to look at - I'll raise an internal ticket to alert them to the issue,

**Comment by Neuroforge** [comment]
I think the issue was my csproj file. If anyone faces this issue, then please check all files and folders are correct after any merges.
