### ISSUE TITLE
[Information request] How to download Glacier archive in parallel (multipart)

### ISSUE THREAD

**Issue by maxima120** [aws/aws-sdk-net#992]
FastGlacier claims they can download an archive as multipart in parallel threads.

I tried to split download in parallelfor loop but stuck as the stream doesn't support seek : `using (Stream webStream = jobOutputResponse.Body)` 

any advice how it can be achieved? if a file very large - I don't want wait hours to only have it failed in the end. Downloading as parts in parallel can utilize bandwidth better I believe and make this more stable.

**Comment by vellozzi** [comment]
Can you post a link to the FastGlacier docs you're talking about, and a code sample?

**Comment by maxima120** [comment]
https://fastglacier.com/

> Support for Multipart Downloads for fast and reliable data transfer 

FastGlacier settings:
![image](https://user-images.githubusercontent.com/10121753/42688198-a4d2d358-869b-11e8-8c3d-f2a6df02a59e.png)

My code was going to be like the sample below, but considering that CanSeek is false on the stream it wont work:

`
Parallel.ForEach(parts, new ParallelOptions() { MaxDegreeOfParallelism = threads }, (Action<Part, ParallelLoopState>)((part, state) =>
{
    byte[] buffer = new byte[60000];
    //WriteLog("CanSeek {0}.", webStream.CanSeek);

    webStream.Position = part.Start;

    while ((int n = webStream.Read(buffer, 0, buffer.Length)) > 0)
    {
        fileToSave.Write(buffer, 0, n);
    }
}));
`

**Comment by vellozzi** [comment]
I'm not familiar with FastGlacier and I can't find any documentation on their API.

If the jobOutputResponse is a [JobOutputResponse](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/Glacier/TGetJobOutputResponse.html) from the AWS SDK for .NET then reading the stream in parallel threads isn't how it's used.  Look at [Downloading an Archive in Amazon Glacier Using the AWS SDK for .NET](https://docs.aws.amazon.com/amazonglacier/latest/dev/downloading-an-archive-using-dotnet.html) to get an idea of how to download a file in parts using the AWS SDK for .NET.

The idea is that multiple requests should be made to GetJobOutput, one for each byte range you want to read.  Each JobOutputResponse contains part of the file.  You should use GetJobOutputAsync to achieve the parallelism you're looking for.  I wouldn't expect reading the Body of one JobOutputResponse in parallel to work.

Without more documentation on FastGlacier I'm afraid that I can only help you with the AWS SDK for .NET.

**Comment by maxima120** [comment]
Thank you.
