### ISSUE TITLE
AmazonS3Util.DoesBucketExist returns true when result is inconclusive

### ISSUE THREAD

**Issue by maynardflies** [aws/aws-sdk-net#993]
When calling DoesBucketExist, only BadRequest and NotFound return codes return false.  Any other code, such as UnAuthorized or ServerError cause it to return true instead of throwing an exception

## Expected Behavior
An exception should be thrown detailing the return code error

## Current Behavior
Utility will return true, which can be misleading or wrong

## Possible Solution
Utility should throw an exception commensurate with the returned status code and error text

## Steps to Reproduce (for bugs)
Attempt to check existence of a bucket in an account to which you do not have appropriate access.  Regardless of the existence of the bucket, the return value will be true

## Your Environment
* AWSSDK.Core version used: 3.3.23.1
* Operating System and version: Windows 10, Windows Server 2012
* Targeted .NET platform: 4.6.1

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by klaytaybai** [comment]
This issue is outdated and the described behavior is confirmed to be intentional, so I'm closing this.
