### ISSUE TITLE
AWS Toolkit Fails to Publish Containers That Involve Multiproject Dependencies

### ISSUE THREAD

**Issue by jaybyrrd** [aws/aws-sdk-net#994]
If a project requires other projects, right clicking the project you would like to deploy and selecting Publish Container to AWS ultimately fails. 

For example: 
If I have a solution MySolution with Projects MyProject and DependencyProject that MyProject relies on.

To be more clear the folder structure is as follows
MySolution
    MyProject
    DependencyProject

The docker build runs from MySolution/MyProject as the working directory. The dockerfile generated by visual studio usually says something like "COPY MyProject/MyProject.csproj MyProject/", however because it is running from the same directory it cannot find that file. 

Suppose you modify the dockerfile to say just "COPY MyProject.csproj MyProject/" this still does not solve the problem that the dependency "DependencyProject" is located relatively at "../DependencyProject/DependencyProject.csproj"

Suppose you modify the dockerfile so that it points at that relative directory, you get an error like 
COPY failed: Forbidden path outside the build context: ../DependencyProject/DependencyProject.csproj

There are two possible fixes. Make the working directory of the docker build the solution directory or call docker build -f instead of docker build. 

## Expected Behavior
It should publish and run commands correctly

## Current Behavior
It runs from the project directory, not the solution directory, resulting in a failure.

## Possible Solution
Change the working directory to the solution directory or change the command to docker build -f

## Steps to Reproduce (for bugs)
Create a solution with two projects, one of which being asp.net or console and the other of which being a class library
Make the deployable application require the class library
Attempt to Publish the deployable application to an AWS Container

## Context
Trying to test deploying our applications to ECS to see how it works and can't because this fails. 

## Your Environment
Visual Studio 2017 Pro
AWS Toolkit

[logging]: http://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-other.html

**Comment by steveataws** [comment]
Thanks for letting us know, we'll take a look.

**Comment by jaybyrrd** [comment]
Thanks for the prompt response @steveataws, if I can do anything else let me know! Is the Visual Studio Toolkit code on github somewhere as well? I was having trouble finding it if so and might have taken a stab at fixing this issue.

**Comment by normj** [comment]
In the next version of the toolkit that should come out soon I updated it to better detect when docker build should run from the solution folder and not the project folder. Also the wizard is updated so you can override the directory docker build is run in case we don't properly detect the directory. I'll update this issue when that release is out.

**Comment by jaybyrrd** [comment]
@normj very cool. Thank you so much!

**Comment by normj** [comment]
Closing as this was released a few months back. Sorry this should have been updated before.

**Comment by Buzzefall** [comment]
It is still extremely unclear how to configure AWS Toolkit to run docker from specific working dir. 

For some reason the toolkit decided to run docker build from a project directory. But I have multi-project solution, so the rest of the projects won't be in the build context. 

**And this issue renders the toolkit useless at some point.**
